### ISSUE TITLE
[Feature] [Zipkin UI] Bundle Zipkin Lens UI in our distribution as a widget component

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#10000]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

@wankai123  enhanced our Zipkin support in past months. Ref doc, https://skywalking.apache.org/docs/main/next/en/setup/backend/zipkin-trace/

Now, we are more confident to work as an alternative server for people who wants their Zipkin traces to stay side by side with other metrics/logs in an all-in-one APM.

@Fine0830 The lens UI source codes are here, https://github.com/openzipkin/zipkin/tree/master/zipkin-lens. It is a very lightweight UI component, I am considering we could bundle them in our distribution, and you could wrap it as a widget to let the dashboard host it on a tab page.

### Use case

@wankai123 could help you to set up test env for testing. 

@Fine0830 There is no feature change requirement. You need to decide whether we should copy/paste those codes, which may be helpful if we need to bump up dependencies to fix CVE or expired libs. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Notice, if we are going to copy them, we should keep their license headers, and put the statement in the LICENSE and NOTICE files of source codes and binary, as we are doing re-distribution.

**Comment by wu-sheng** [comment]
@tacigar told me there are several enhancements he wants to land on the code base, 

- https://github.com/openzipkin/zipkin/pull/3348
- https://github.com/openzipkin/zipkin/pull/3349
- https://github.com/openzipkin/zipkin/pull/3350

They are tested and used for a private distribution. We should adopt those too.

**Comment by wu-sheng** [comment]
The one last step is to wait for @Fine0830 to provide a new kind of widget, which could host the Zipkin lens UI on an isolated iFramework. This widget would work separately.

**Comment by wu-sheng** [comment]
@kezhenxu94 Let's leverage the latest UI widget and bring Zipkin Lens UI into the Service Mesh dashboard. And consider opening Zipkin tracing in Istio of Showcase?

**Comment by kezhenxu94** [comment]
@wu-sheng did you expect to put the Zipkin UI here? 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/15965696/210745755-73db53a1-6f11-479d-958f-b29cfa3168e6.png">

What should users see in this tab if they enable SkyWalking Envoy tracer? They would be confused why the trace tab is showing Zipkin since they enable SkyWalking tracer.

Also, I don't think Zipkin is tightly bound to `Service Mesh` so there is no point to put it under that menu.
