### ISSUE TITLE
[Bug] The latest version is 8.13.0. The filtering endpoint configuration does not take effect

### ISSUE THREAD

**Issue by azydbly** [apache/skywalking#10022]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

SkyWalking APM version 9.2.0 and Java Agent version 8.13.0 are used to filter endpoints that do not need to be monitored.  The configuration succeeds but does not take effect.

### What you expected to happen

Hope to fix this problem

### How to reproduce

When SkyWalking APM and Java Agent download the latest version and filter the spingboot Admin health endpoint, the endpoint information is still visible on the UI page

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you only say something is not working, there is nothing we can do.

**Comment by azydbly** [comment]
> If you only say something is not working, there is nothing we can do.

这不是bug吗，按照官网文档中配置过滤端点不进行监控， 不生效。

**Comment by BertOnline** [comment]
I probably know what you mean. Refer to the following configuration. Add apm-trace-ignore-plugin.config in your agent dir.
![image](https://user-images.githubusercontent.com/17882970/206188672-9797d95e-89de-4701-96db-e60ae645533e.png)
```yml
trace.ignore_path=${SW_AGENT_TRACE_IGNORE_PATH:*/health}
```
