### ISSUE TITLE
[Feature] [BanyanDB] Support no SeriesID for relative small dataset of record

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#10054]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

BanyanDB requires `SeriesID` for every Stream to shard and unique the record row. But in some cases, such as newly added SpanAttachedEvent, records are not generated on-demand and only in specific scope(for specific instance/pod in the example case). So the size of the dataset would not be huge, but we can't tell how big it would do, and we don't have a suitable field in the record entity as a SeriesID.

So, we should create a SeriesID mechanism, which generates ID on the server side. This ID should be generated in self-adaption. OAP could provide some configurations at the scale to assist.

### Use case

We need to discuss more details about this when BanyanDB server picks this up.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
@wu-sheng Is this still the case?

**Comment by wu-sheng** [comment]
I don't see necessity about this. Let's close his for now.
