### ISSUE TITLE
[Feature]  Grafana integration

### ISSUE THREAD

**Issue by jingslunt** [apache/skywalking#10074]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

grafana support trace and topology now

### Use case

grafana support trace and topology now

### Related issues

grafana support trace and topology now

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you want to propose that, you want to do something, go ahead. 
This is not a kind of requirement, the project maintainers would do.
