### ISSUE TITLE
[Feature] investigate the possibility for supporting PromQL

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#10080]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the past two years, we supported Prometheus through OpenTelemetry(OC and OLTP) for ingest. We have several asks about how about query stage.
It is early to say we could or should support it, but there is a chance we could investigate the possibility and meaning of PromQL.

Ref PromQL 2.37(LTS), https://prometheus.io/docs/prometheus/2.37/getting_started/

We would do more discussions in this thread to update the progress. 

**Notice, this has not been selected on the roadmap.**

### Use case

People who like Grafana, or other query platforms supporting PromQL, could read metrics from SkyWalking. 

If this gets verified and supported, we could do research for traces and logs for more query protocols.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
FYI @apache/skywalking-committers If any of you feel interests, you could follow this thread.

**Comment by hanahmily** [comment]
MAL core semantics are a variant of PromQL, so we have some experience with PromQL. I want to discuss the scope of PromQL to OAP:

  * Do we tend to use PromQL as an alternative to GraphQL-based APIs? Beside Topology and Trace querying, PromQL might be in place of most scenarios. But we can extend PromQL to support them if we want to go "all-in" PromQL. 
  * Do we replace MAL and LAL with PromQL since they derive from the latter?
  * Furthermore, will OAL get involved?

**Comment by wu-sheng** [comment]
I can't see the point to do the replacement, because that would impact the whole query.
Also, SkyWalking would keep in pre-calculation as recommended. The main point of this is exposing the aggregated query in another channel, nothing more.
So, MAL, OAL, GraphQL APIs are kept for good reasons.

**Comment by wu-sheng** [comment]
The current multiple dimensions query would be the fundamental query to provide time-series data, this would not even impact the storage level. The whole PromeQL implementation is on top of GraphQL. @hanahmily

**Comment by wu-sheng** [comment]
I reviewed the PromQL. I think besides the basic grammar, we could choose these four APIs as MVP
1. Metadata Query API, https://prometheus.io/docs/prometheus/2.37/querying/api/#querying-metadata. Metadata has a specific meaning for us. We could expose our metadata metric names(e.g. service_traffic).
   - listMetrics could be considered a kind of metadata if possible(TBD)
2. Metrics value Query API,  https://prometheus.io/docs/prometheus/2.37/querying/api/#expression-queries. Metrics as time-series values could be queried and returned in the expected format.
   - When the `range` is missed, we could pick the latest 30 mins
   - We need to recognize and pick dimensions automatically, to avoid `too many data points` error and overload
   - There should be a complete label set to define our scope in order to get metrics correctly. I didn't read Grafana+PromQL Datasource carefully yet, but I hope we have a chance to provide topology, at least topology line metrics.
3. Alerts API, https://prometheus.io/docs/prometheus/2.37/querying/api/#alerts. This could directly query our alarms with some pre-defined labels(e.g. rule_name)
4. Build Info, https://prometheus.io/docs/prometheus/2.37/querying/api/#build-information. This is our version service.

With all the implementation, we need to define our details, mostly about specific labels. Complete docs should be added under `APIs/Query APIs/PromQL`
<img width="247" alt="image" src="https://user-images.githubusercontent.com/5441976/209427655-76b5969a-27c9-4f3c-ba4f-8f082c5879c3.png">
 
**Notice, we should explicitly declare at the top of the new PromQL API doc. The APIs are built on top of GraphQL APIs, and only provide a feature subset of GraphQL APIs**.

@wankai123 Please add anything you found on your side.

**Comment by wu-sheng** [comment]
I just removed `TBD` label. Sync from @wankai123 we at least could have metadata and metric query support.
This should be possible to continue on implement details.
