### ISSUE TITLE
[Feature] The performance of queryTrace by traceId in Huge dataset is slow in ES

### ISSUE THREAD

**Issue by dylanforest** [apache/skywalking#10094]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

#5023 had mentioned poor performance in trace query. Still, when we need to store trace in months, and everyday's segment is huge, the latency of trace query is unacceptable.

### Use case

Maybe we could  use an indepent trace_index store only traceid and startTime and endTime.
And Searching the startTime and endTime in the trace_index before querying trace in limited segment index.

And Just like metrics record procedure,  doc with specific trace_id of trace_index can only be cached and updated by specific skywalking instance.

### Related issues

#5023 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
There is nothing changed due to this proposal. You will still need to query segments by trace ID.
And you referred a years ago issue, it doesn't mean anything for the current codes.

**Comment by dylanforest** [comment]
Thanks. Anyway, consider add duaration option for traceid search? So that it might help narrowing down the query range.

**Comment by wu-sheng** [comment]
AFAIK, no, we are not planning for this. A lot of users would complain if we add this. And more importantly, no proposal/vote is started by a committer, so, nothing should be changed.
