### ISSUE TITLE
[BanyanDB] Add TLS options for HTTP server(gRPC gateway)

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#10099]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The HTTP server should enable TLS support when the gRPC server enables TLS. 

 * Set up gateway gRPC client’s certs and keys automatically. It should load gRPC’s certs without passing it through a flag.
 * HTTP TLS key and certs could be either identical or different from gRPC’s.
 * Support reloading keys and certs. gRPC TLS doesn’t support this feat, though. Both of them should implement it.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DevPJ9** [comment]
Hello @hanahmily. I would like to work on this.

**Comment by hanahmily** [comment]
Implemented by https://github.com/apache/skywalking-banyandb/pull/245
