### ISSUE TITLE
[Bug] ElasticSearchClient -253506821 [I/O dispatcher 1] INFO  [] - Bulk execution id [xxxx] completed in 610 milliseconds, size：xxxx

### ISSUE THREAD

**Issue by andotorg** [apache/skywalking#10096]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

library.client.elasticsearch.ElasticSearchClient -253506821 [I/O dispatcher 1] INFO  [] - Bulk execution id [xxxx] completed in 610 milliseconds, size：xxxx

### What you expected to happen

library.client.elasticsearch.ElasticSearchClient -253506821 [I/O dispatcher 1] INFO  [] - Bulk execution id [xxxx] completed in 610 milliseconds, size：xxxx

### How to reproduce

library.client.elasticsearch.ElasticSearchClient -253506821 [I/O dispatcher 1] INFO  [] - Bulk execution id [xxxx] completed in 610 milliseconds, size：xxxx

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Why do you post an issue but only with a INFO log?

**Comment by andotorg** [comment]
Sorry, I'll rewrite it
