### ISSUE TITLE
[Bug] 9.2-oap升级9.3报错

### ISSUE THREAD

**Issue by coolmingwu** [apache/skywalking#10107]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

9.2版本切换9.3版本后报错
mysql-root.json layer_entity_name: MYSQL_All_MySQL-Root conflict with exist configuration id: b6e3763c-882d-417f-8556-3cf0187cb8db
java.lang.IllegalArgumentException: File: mysql-root.json layer_entity_name: MYSQL_All_MySQL-Root conflict with exist configuration id: b6e3763c-882d-417f-8556-3cf0187cb8db

### What you expected to happen

切换后能顺利升级，正常使用

### How to reproduce

9.2直接升级9.3，存储使用的ES

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We only accept English on GitHub.

**Comment by BertOnline** [comment]
Try to delete your es ui-template.

**Comment by erikwoo** [comment]
curl -X DELETE "http://localhost:9200/sw_ui_template"
