### ISSUE TITLE
[Bug] change oap version 9.2 to 9.3 error

### ISSUE THREAD

**Issue by coolmingwu** [apache/skywalking#10110]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

i want to change oap server version 9.2 to 9.3, use storage is elasticsearch
program startup error is : mysql-root.json layer_entity_name: MYSQL_All_MySQL-Root conflict with exist configuration id: b6e3763c-882d-417f-8556-3cf0187cb8db
java.lang.IllegalArgumentException: File: mysql-root.json layer_entity_name: MYSQL_All_MySQL-Root conflict with exist configuration id: b6e3763c-882d-417f-8556-3cf0187cb8db

### What you expected to happen

The program is running properly.

### How to reproduce

change oap server version 9.2 to 9.3, use storage is elasticsearch

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Clear the UI_TEMPLATE index. Notice, we never mentioned upgrading is transparent
This is not a bug.

**Comment by erikwoo** [comment]
how to Clear the UI_TEMPLATE index please?

**Comment by erikwoo** [comment]
curl -X DELETE "http://localhost:9200/sw_ui_template"

**Comment by Spinestars** [comment]
> curl -X DELETE "http://localhost:9200/sw_ui_template"

curl -X DELETE "http://localhost:9200/${SW_NAMESPACE}_ui_template"
