### ISSUE TITLE
[BanyanDB][Bug] Cache topNAggregation's schema in the measure module. 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#10121]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

Cache the topNAggregation's schema in the measure's metadata repository. The query should not fetch the schema through ETCD each time. 

This issue is related to https://github.com/apache/skywalking-banyandb/blob/main/banyand/query/processor_topn.go#L65. The measure cache is at https://github.com/apache/skywalking-banyandb/blob/main/banyand/measure/metadata.go

### What you expected to happen

None.

### How to reproduce

None.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mikechengwei** [comment]
Can i try to finish this pr?

**Comment by lujiajing1126** [comment]
I suppose it has been completed
