### ISSUE TITLE
[Bug] Wrong data format of Apdex in service list panel if metric type is readmetricsvalue

### ISSUE THREAD

**Issue by inversionhourglass** [apache/skywalking#10123]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

Wrong data format of Apdex in service list panel if metric type is `readmetricsvalue`.

![image](https://user-images.githubusercontent.com/15099549/206112391-c74591b3-11d9-444c-989c-afd88a5f9772.png)

### What you expected to happen

The actual value should be divided by 10000.

### How to reproduce

In edit mode, change metric type of service_apdex from `readmetricsvalues` to `readmetricsvalue`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you changed the way to read metrics, you should change the calculation `format`.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/5441976/206114490-64397b15-bf99-4ff8-b92f-93bedb4604a6.png">

I did a try, it is good.
