### ISSUE TITLE
[Feature] Enhance redisson plugin to adapt Virtual Cache

### ISSUE THREAD

**Issue by pg-yang** [apache/skywalking#10137]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Virtual cache represents the cache nodes detected by [server agents' plugins](https://skywalking.apache.org/docs/main/next/en/setup/service-agent/server-agents).

Redisson plugin hasn't adapted the tags of[ Virtual cache](https://skywalking.apache.org/docs/main/next/en/setup/service-agent/virtual-cache/)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mohammedtabish0** [comment]
Can I pick this up?

**Comment by wu-sheng** [comment]
@mohammedtabish0 Please go ahead.

**Comment by wu-sheng** [comment]
@mohammedtabish0 Any update? As this had been assigned a week.

**Comment by mohammedtabish0** [comment]
@wu-sheng I was busy with some work so couldn't actually fully pick this up last week. I was looking into the documentation and the code and trying to find other PR's or Commits which might be related to this but couldn't find any thing around this. 
I wanted to know where do we exactly provide these tags for the cache span in the plugins. I couldn't find any reddison plugin in the code base. I am a little bit confused here.

**Comment by wu-sheng** [comment]
The code base is in the Java agent repository, https://github.com/apache/skywalking-java/tree/main/apm-sniffer/apm-sdk-plugin/redisson-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/redisson

**Comment by xzyJavaX** [comment]
If Redisson and Lettuce want to adopt uniform tags, there are still some problems to be solved:
1、How to set 'CACHE_CMD', 'CACHE_OP' and 'CACHE_KEY' in batch method？
2、How to obtain the Key in Lettuce？It seems that you need to call 
'CommandArgs<?, ?> args = redisCommand.getArgs()' first, and then call 'args.toCommandString()' to get a string similar to "key<key1> value<value1>", then cut the string.

**Comment by wu-sheng** [comment]
> If Redisson and Lettuce want to adopt uniform tags, there are still some problems to be solved:
> 
> 1、How to set 'CACHE_CMD', 'CACHE_OP' and 'CACHE_KEY' in batch method？
> 
> 2、How to obtain the Key in Lettuce？It seems that you need to call 
> 
> 'CommandArgs<?, ?> args = redisCommand.getArgs()' first, and then call 'args.toCommandString()' to get a string similar to "key<key1> value<value1>", then cut the string.

Please don't mix different topics on an issue.
What you are asking is another thing, actually.

**Comment by xzyJavaX** [comment]
https://github.com/apache/skywalking/issues/10168, this issue is closed

**Comment by wu-sheng** [comment]
> https://github.com/apache/skywalking/issues/10168, this issue is closed

So.what? That is irrelevant too.

**Comment by xzyJavaX** [comment]
Should I propose a new issue？
