### ISSUE TITLE
[Bug] no data in virtual cache 

### ISSUE THREAD

**Issue by yuxh** [apache/skywalking#10130]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

9.3 provide virtual cache in General-Service, but I cann't find any data in this page

### What you expected to happen

I use redisson 3.17 with spring boot 2 in my app, I can see redis request in "trace",but no data can be detected in 'virtual cache'   
<img width="765" alt="Snipaste_2022-12-08_10-39-06" src="https://user-images.githubusercontent.com/1754573/206346270-dcea7e82-becd-48b6-b472-f21f7ccd134d.png">

### How to reproduce

skywalking 9.3.0, agent 8.13,  found no error in log

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pg-yang** [comment]
We haven't supported redisson, at least for now.

**Comment by wu-sheng** [comment]
The plugin should follow this doc to add the required tags. Otherwise, no analysis would be made.

https://skywalking.apache.org/docs/main/next/en/setup/service-agent/virtual-cache/

**Comment by yuxh** [comment]
> We haven't supported redisson, at least for now.
Is there any document for support list, java-agent's supported-list has no clue for which plugin to support this 'virtual cache' function.

**Comment by wu-sheng** [comment]
Read the change logs. If a plugin is updated to support all tags, they are listed there. 
All these tags are available to check on span check, you can check on your own too.

**Comment by zhangiicc** [comment]
{
                    "traceId": "04e17bbb14554f669473476739d400a0.362921.16709314191639443", 
                    "segmentId": "04e17bbb14554f669473476739d400a0.362921.16709314191639442", 
                    "spanId": 1, 
                    "parentSpanId": 0, 
                    "refs": [ ], 
                    "serviceCode": "crm-membe", 
                    "serviceInstanceName": "crm-membe-5895d95fbb-4kws8", 
                    "startTime": 1670931419165, 
                    "endTime": 1670931419166, 
                    "endpointName": "Jedis/get", 
                    "type": "Exit", 
                    "peer": "10.100.244.34:19000", 
                    "component": "Jedis", 
                    "isError": false, 
                    "layer": "Cache", 
                    "tags": [
                        {
                            "key": "db.type", 
                            "value": "Redis"
                        }, 
                        {
                            "key": "db.statement", 
                            "value": "get"
                        }
                    ], 
                    "logs": [ ], 
                    "attachedEvents": [ ]
                }

**Comment by zhangiicc** [comment]
I useJedis in my app, I can see redis request in "trace",but no data can be detected in 'virtual cache'

**Comment by wu-sheng** [comment]
Again, read the doc. https://skywalking.apache.org/docs/main/next/en/setup/service-agent/virtual-cache/

Your tags are not the expected ones. Only the latest Java agent(8.13.0) adopted this.
