### ISSUE TITLE
[Bug] Lettuce and redisson do not support uniform tags.

### ISSUE THREAD

**Issue by xzyJavaX** [apache/skywalking#10168]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

There was a commit of "Update guava-cache,jedis,memcached,ehcache plugins to adopt uniform tags (#303)", but there is no change to lettuce and redisson, why.

### What you expected to happen

skip

### How to reproduce

skip

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Duplicate https://github.com/apache/skywalking/issues/10137.

There is no why. If some one wants it, they should take an action. Send a pull request.

**Comment by xzyJavaX** [comment]
If Redisson and Lettuce want to adopt uniform tags, there are still some problems to be solved:
1、How to set 'CACHE_CMD', 'CACHE_OP' and 'CACHE_KEY' in batch method？
2、How to obtain the Key in Lettuce？It seems that you need to call 
'CommandArgs<?, ?> args = redisCommand.getArgs()' first, and then call 'args.toCommandString()' to get a string similar to "key<#key1> value<#value1>", then cut the string.
