### ISSUE TITLE
[Feature] Trace Sampling can use nanosecond instead of millisecond

### ISSUE THREAD

**Issue by Dark1Forest** [apache/skywalking#10173]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

If the call time is less than one millisecond, I will not see the call time
like this
![image](https://user-images.githubusercontent.com/49264473/208145622-aeb29138-beab-46de-baf3-ee0899c577d9.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Duplicate https://github.com/SkyAPM/go2sky/issues/174#issuecomment-1354786561
