### ISSUE TITLE
[BanyanDB][OAP] Refactor topology query

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#10171]
There are two issues here:

### Redundant tags
`sourceService` and `destService ` are not used in the final analysis. Entity ID should be enough for decoding.

### Use `groupBy` in the query 

`TopologyDAO` is not using `groupBy` query, so with 30-60 min, we face a huge dataset of the query results.

_Originally posted by @wu-sheng in https://github.com/apache/skywalking/pull/10170#discussion_r1050716464_

**Comment by wu-sheng** [comment]
`Redundant tags` had been fixed.
