### ISSUE TITLE
Support to customize the report period of JVM relative metrics.

### ISSUE THREAD

**Issue by dylanforest** [apache/skywalking#10179]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

We got a thread leak in micro-service and the thread count is up to 4000.
The CPU usage is very low for threads except one skywalkingAgent thread's usage is up 40%.

The JVMMetrics is collected every 1 sec, and everytime it checks all 4000 thread's status.

### What you expected to happen

The JVMMetrics does not have to be collected so frequently. Maybe 2 or 3 collection in 1min is enough?

### How to reproduce

Creating 4000 threads.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't create so many threads, what do you mean memory leak?

**Comment by dylanforest** [comment]
It's NOT memory leak. The thread leak is no created by the agent. It's triggered by the service which the agent is wathing.
The problem is when skywalking-java monitoring a service with many threads, one of the agent's threads' CPU usage is high.
As a contrast, Pinpoint's agent does not have the problem.

After tracing the agent's thread, we local time cost at ThreadProvider.getThreadMetrics().
This func takes 400ms to check all  4000  threads' status in our case, and this process goes every 1sec.

**Comment by wu-sheng** [comment]
>As a contrast, Pinpoint's agent does not have the problem.

There is no point to mention this. Please don't do this in further discussion.

**Comment by wu-sheng** [comment]
> After tracing the agent's thread, we local time cost at ThreadProvider.getThreadMetrics().
This func takes 400ms to check all 4000 threads' status in our case, and this process goes every 1sec.

Yes, this is how it works. What do you want to ask?

**Comment by dylanforest** [comment]
> Yes, this is how it works. What do you want to ask?
Is this frequency necessary？I checked the oap,  the related metrics are aggregated by longAvg() in 1min.
I wonder if 2 or 3 collections in 1min is enough?

**Comment by dylanforest** [comment]
> There is no point to mention this. Please don't do this in further discussion

Got

**Comment by wu-sheng** [comment]
> > Yes, this is how it works. What do you want to ask?
> 
> Is this frequency necessary？I checked the oap, the related metrics are aggregated by longAvg() in 1min. I wonder if 2 or 3 collections in 1min is enough?

You could contribute a feature to customize this period if you like.

**Comment by dylanforest** [comment]
I will, thank you!
