### ISSUE TITLE
skywaling es data issue

### ISSUE THREAD

**Issue by bruse-peng** [apache/skywalking#10217]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

i want learn about the detail of elasticseatch index data

### Use case

i need search  data of es derectly not by skywaling UI,now i have two question:
1、what is the different of the index skywalking_log-xxx and skywalking_segment-xxxx
2、when i search the es data of skywalking_segment-xxxx ,the data result is encryptioned how can i get the original data

### Related issues

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Explain this is not community responsibility. We only encourage you read data through APIs.
