### ISSUE TITLE
[Bug]  No connection established

### ISSUE THREAD

**Issue by code-farmer-i** [apache/skywalking#10215]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Server Side Agent (apache/skywalking-nodejs)

### What happened

{
  file: '/Volumes/development/projects/app_pc_pduiv2/node_modules/.pnpm/skywalking-backend-js@0.6.0/node_modules/skywalking-backend-js/lib/agent/protocol/grpc/clients/HeartbeatClient.js',
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  level: 'error',
  message: 'Failed to send heartbeat 14 UNAVAILABLE: No connection established',
  stack: 'Error: 14 UNAVAILABLE: No connection established\n' +
    '    at Object.callErrorFromStatus (/Volumes/development/projects/app_pc_pduiv2/node_modules/.pnpm/@grpc+grpc-js@1.7.3/node_modules/@grpc/grpc-js/build/src/call.js:32:19)\n' +
    '    at Object.onReceiveStatus (/Volumes/development/projects/app_pc_pduiv2/node_modules/.pnpm/@grpc+grpc-js@1.7.3/node_modules/@grpc/grpc-js/build/src/client.js:195:52)\n' +
    '    at Object.onReceiveStatus (/Volumes/development/projects/app_pc_pduiv2/node_modules/.pnpm/@grpc+grpc-js@1.7.3/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)\n' +
    '    at Object.onReceiveStatus (/Volumes/development/projects/app_pc_pduiv2/node_modules/.pnpm/@grpc+grpc-js@1.7.3/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)\n' +
    '    at /Volumes/development/projects/app_pc_pduiv2/node_modules/.pnpm/@grpc+grpc-js@1.7.3/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:78:11)\n' +
    'for call at\n' +
    '    at ServiceClientImpl.makeUnaryRequest (/Volumes/development/projects/app_pc_pduiv2/node_modules/.pnpm/@grpc+grpc-js@1.7.3/node_modules/@grpc/grpc-js/build/src/client.js:163:34)\n' +
    '    at ServiceClientImpl.reportInstanceProperties (/Volumes/development/projects/app_pc_pduiv2/node_modules/.pnpm/@grpc+grpc-js@1.7.3/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\n' +
    '    at Timeout._onTimeout (/Volumes/development/projects/app_pc_pduiv2/node_modules/.pnpm/skywalking-backend-js@0.6.0/node_modules/skywalking-backend-js/lib/agent/protocol/grpc/clients/HeartbeatClient.js:63:43)\n' +
    '    at listOnTimeout (node:internal/timers:557:17)\n' +
    '    at processTimers (node:internal/timers:500:7)'
}

### What you expected to happen

No error

### How to reproduce

start agent

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is your local env issue. Check the npm logs.
