### ISSUE TITLE
Exception alias sw_log missing  on 9.3.0 [Bug] 

### ISSUE THREAD

**Issue by XiamenGeek** [apache/skywalking#10236]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

After I startup OAPServer, there are Exceptions on OAPServer log periodically.  Exception log as bellow:

> 2023-01-0520:37:42,216-org.apache.skywalking.oap.servercore.storage.ttl.DataTTLKeeperTimer - 66 [pool-6-thread-1] ERROR [] Remove data in background failure. 
java.util.concurrent.ExecutionException:java.lang.RuntimeException:{"error":"alias [sw_log] missing", "status":404
....

I have checked ES index. There's no sw_log index. 
ES version: 6.8

### What you expected to happen

Should no such Exception on OAP server log.

### How to reproduce

Skywalking OAP server: 9.3.0
Elasticsearch Version: 6.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@wankai123 Do we have this index? I never faced this.

**Comment by wankai123** [comment]
> @wankai123 Do we have this index? I never faced this.

Yes, we have this index in `LogRecord`, but I never saw this exception.

**Comment by wu-sheng** [comment]
@XiamenGeek Could you provide more context? I can't tell what happens.

**Comment by wu-sheng** [comment]
Whether do you use indices/templates from an old version?

**Comment by XiamenGeek** [comment]
> Whether do you use indices/templates from an old version?

No, before reinstall skywalking 9.3.0 I have cleaned all indices of Skywalking on ES, which with sw_ prefix.

**Comment by wu-sheng** [comment]
How about templates? Try on a new and empty ElasticSearch.
I feel you have some legacy in your ElasticSearch.

**Comment by XiamenGeek** [comment]
> How about templates? Try on a new and empty ElasticSearch. I feel you have some legacy in your ElasticSearch.

Could you tell me what is templates name ? Besides indices with sw_ prefix, any other  indices are left? @wu-sheng

**Comment by wu-sheng** [comment]
https://skywalking.apache.org/docs/main/v9.3.0/en/setup/backend/backend-storage/#elasticsearch

Document has listed the indices. The prefix(without day-format) names are templates.

**Comment by XiamenGeek** [comment]
Looks like all are with prefix "sw_", including the template sw_ui_template. @wu-sheng 
<html>
<body>


index | number_of_shards | number_of_replicas
-- | -- | --
sw_ui_template | indexShardsNumber | indexReplicasNumber
sw_metrics-all-${day-format} | indexShardsNumber | indexReplicasNumber
sw_log-${day-format} | indexShardsNumber * superDatasetIndexShardsFactor | superDatasetIndexReplicasNumber
sw_segment-${day-format} | indexShardsNumber * superDatasetIndexShardsFactor | superDatasetIndexReplicasNumber
sw_browser_error_log-${day-format} | indexShardsNumber * superDatasetIndexShardsFactor | superDatasetIndexReplicasNumber
sw_zipkin_span-${day-format} | indexShardsNumber * superDatasetIndexShardsFactor | superDatasetIndexReplicasNumber
sw_records-all-${day-format} | indexShardsNumber | indexReplicasNum


</body>
</html>

**Comment by wankai123** [comment]
@XiamenGeek I think you removed all `sw_log` index manually before, you can try remove the index_template `sw_log` and restart OAP.

**Comment by XiamenGeek** [comment]
@wankai123  sw_log index is not found on ES, where can I remove?

**Comment by wu-sheng** [comment]
> @wankai123  sw_log index is not found on ES, where can I remove?

This is a template, not an index.

**Comment by XiamenGeek** [comment]
> > @wankai123  sw_log index is not found on ES, where can I remove?
> 
> This is a template, not an index.

Where is this sw_log template located? @wu-sheng

**Comment by wu-sheng** [comment]
This is an ElasticSearch concept, not us. Learn from their docs.

**Comment by XiamenGeek** [comment]
It works! Thanks！ @wu-sheng @wankai123
