### ISSUE TITLE
Failed to start the Java service introducing the agent

### ISSUE THREAD

**Issue by Zwl0113** [apache/skywalking#10232]
Background: Our service has encountered many startup failures, which occur occasionally. It is generally caused by the introduction of knife4j and skywalking java agent at the same time. An error is reported indicating a bytecode injection conflict. At present, there is no good solution. Please help us，Stack in file

[stack.txt](https://github.com/apache/skywalking/files/10349196/stack.txt)

**Comment by wu-sheng** [comment]
You have submitted one, don't report again. 

https://github.com/apache/skywalking/discussions/10231
