### ISSUE TITLE
Windows Monitoring

### ISSUE THREAD

**Issue by Donadominic** [apache/skywalking#10242]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Apache Skywalking does not support windows monitoring. But it will be helpful if this feature is available. What all changes can contribute towards this feature?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mikechengwei** [comment]
@wu-sheng I think we need to implement the collection of windows logs and metric data. I think I can realize this function. Can you assign this issue to me?

**Comment by wu-sheng** [comment]
> @wu-sheng I think we need to implement the collection of windows logs and metric data. I think I can realize this function. Can you assign this issue to me?

Metrics are required, logs are nice to have.

**Comment by wu-sheng** [comment]
> /assign

Just assigned it to you, good luck.

**Comment by mikechengwei** [comment]
> > /assign
> 
> Just assigned it to you, good luck.

Thanks for trust !

**Comment by wu-sheng** [comment]
> > > /assign
> 
> > 
> 
> > Just assigned it to you, good luck.
> 
> 
> 
> Thanks for trust !

I had noticed several fixed you made on BanyanDB as starts. It is good to see you are involving more like this.

**Comment by wu-sheng** [comment]
@mikechengwei One suggestion, once you have done the research, and know how to start, and which components you are going to use(such as which windows agent, which protocol(otlp?)), you could share here, in case of somethings unexpected in the last minute, to waste too much time.

**Comment by mikechengwei** [comment]
> @mikechengwei One suggestion, once you have done the research, and know how to start, and which components you are going to use(such as which windows agent, which protocol(otlp?)), you could share here, in case of somethings unexpected in the last minute, to waste too much time.

I will make a design and invite you to review it together.

**Comment by Donadominic** [comment]
If it is successful, please let me know. Because I am in need of this feature.

**Comment by mikechengwei** [comment]
> @mikechengwei Some discussions from @Donadominic are happening on slack, you are better to join and keep in the loop.

ok.

**Comment by mikechengwei** [comment]
@wu-sheng I have send my slack mail to [dev@skywalking.apache.org](mailto:dev@skywalking.apache.org).

**Comment by wu-sheng** [comment]
The invitation has been sent to your mail box.

**Comment by wu-sheng** [comment]
@mikechengwei Any update about this?

**Comment by mikechengwei** [comment]
Refer to Slack discuisson and Linux Monitoring ,i wrote the design document Windows Monitoring.

We can leverages Prometheus [windows_exporter](https://github.com/prometheus-community/windows_exporter) to collect metrics data from the windows machine and leverages OpenTelemetry Collector to transfer the metrics to OpenTelemetry receiver and into the Meter System. VM entity as a Service in OAP and on the Layer: `OS_WINDOWS`.

We can also use InfluxDB  Telegraf to collect windows metric,and use [Telegraf receiver](https://skywalking.apache.org/docs/main/next/en/setup/backend/telegraf-receiver/) plugin to store to the [Meter System](https://skywalking.apache.org/docs/main/next/en/concepts-and-designs/meter/)

## detailed step
For OpenTelemetry receiver:

1. Setup Prometheus windows-exporter.
2. Setup OpenTelemetry Collector . Provide otel configuration example  `otel-collector-config.yaml`.
3. Config SkyWalking OpenTelemetry receiver.

For Telegraf receiver:

1. Setup telegraf collect metrics to influxDB, telegraf support [Windows Services Input Plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_services/README.md).
2. Setup InfluxDB Telegraf’s telegraf.conf file specific rules according to Telegraf receiver document.
3. Config SkyWalking Telegraf receiver.

We need provdie supported Metrics detail on promethues windows exporter and telegraf windows input plugin.

## Develop Plan
1. Run and test the windows exporter collection process
	- provide windows metric otel configuration file example   `otel-collector-config.yaml`. 
	- provide otel metric handle rule file.
2. Run and test the telegraf collection process
	- provide telegraf windows input configuration example file `telegraf.conf `
	- provide telgraf receiver metric handle rule file

**Comment by mikechengwei** [comment]
> Refer to Slack discuisson and Linux Monitoring ,i wrote the design document Windows Monitoring.
> 
> We can leverages Prometheus [windows_exporter](https://github.com/prometheus-community/windows_exporter) to collect metrics data from the windows machine and leverages OpenTelemetry Collector to transfer the metrics to OpenTelemetry receiver and into the Meter System. VM entity as a Service in OAP and on the Layer: `OS_WINDOWS`.
> 
> We can also use InfluxDB Telegraf to collect windows metric,and use [Telegraf receiver](https://skywalking.apache.org/docs/main/next/en/setup/backend/telegraf-receiver/) plugin to store to the [Meter System](https://skywalking.apache.org/docs/main/next/en/concepts-and-designs/meter/)
> 
> ## detailed step
> For OpenTelemetry receiver:
> 
> 1. Setup Prometheus windows-exporter.
> 2. Setup OpenTelemetry Collector . Provide otel configuration example  `otel-collector-config.yaml`.
> 3. Config SkyWalking OpenTelemetry receiver.
> 
> For Telegraf receiver:
> 
> 1. Setup telegraf collect metrics to influxDB, telegraf support [Windows Services Input Plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_services/README.md).
> 2. Setup InfluxDB Telegraf’s telegraf.conf file specific rules according to Telegraf receiver document.
> 3. Config SkyWalking Telegraf receiver.
> 
> We need provdie supported Metrics detail on promethues windows exporter and telegraf windows input plugin.
> 
> ## Develop Plan
> 1. Run and test the windows exporter collection process
>    
>    * provide windows metric otel configuration file example   `otel-collector-config.yaml`.
>    * provide otel metric handle rule file.
> 2. Run and test the telegraf collection process
>    
>    * provide telegraf windows input configuration example file `telegraf.conf `
>    * provide telgraf receiver metric handle rule file

@wu-sheng WDYT?

**Comment by wu-sheng** [comment]
From official perspective, Prometheus to OTEL collector to OAP should be good enough.

**Comment by mikechengwei** [comment]
> From official perspective, Prometheus to OTEL collector to OAP should be good enough.

ok,i will finish this feature firstly.

**Comment by wu-sheng** [comment]
Oh, there is one step, you need to update UI to add a new menu item for Windows side by side with Linux.
