### ISSUE TITLE
[Feature] Trace Sampling at agent side

### ISSUE THREAD

**Issue by tjzheng1002** [apache/skywalking#10243]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I have seen source code of SegmentAnalysisListener,trace sampling at server side means huge burden on the network,even if on the local area network.

### Use case

Can we modify source code of TraceSegmentServiceClient to trace sampe at agent side before sending to the oap server? 

### Related issues

None,just an idea in my head.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
There is client sampling already. You could check the doc.
