### ISSUE TITLE
[Bug] php-fpm freeze after large amount of requests when skywalking agent enabled with unavailable skywalking server address

### ISSUE THREAD

**Issue by guoyk93** [apache/skywalking#10240]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

PHP 7.4.23 with latest `Skywalking Agent` compiled from source.

When `Skywalking Agent` enabled with an unavailable `Skywalking Server` address, the `php-fpm` process freezes after large amount of requests (approx `pm.max_children*100`). 

Any new requests will failed with `Nginx` `504 Gateway Time-out`, until `php-fpm` restarted.

### What you expected to happen

Under any circustences, event when mis-configured or simply `Skywalking Server` failling to start, the `Skywalking Agent` should not preventing `php-fpm` from running properly.

### How to reproduce

I'v made a repository to reproduce:

https://github.com/guoyk93/php-skywalking-debug.

**Steps**

1. Start container

    ```shell
    docker run -ti --rm --name php-skywalking-debug -p 8088:80 ghcr.io/guoyk93/php-skywalking-debug:latest
    ```

2. Stress the container with `Apache Benchmark Tool`

    ```shell
    ab -n 10000 -c 200 http://127.0.0.1:8088/
    ```

3. At some point of time, approximate 5000 (`pm.max_children*100`) requests done, whole `php-fpm` process will freeze. Any new http request will respond with `nginx` `504 Gateway Time-out`, until container restart.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment]
Thanks for your report. The problem should occur in the IPC, waiting for my repair.

**Comment by guoyk93** [comment]
https://github.com/guoyk93/php-skywalking-debug/commit/27e4de1a71f424a33fe724556080251814ad861b
