### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SWHHEART** [apache/skywalking#10257]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

When using 8.9.1, I found that the LAST_PING field in the instance_traffic table would always be replaced by the old time. For example, the updated time 202301101712 would be overwritten by 202311011909 later, which caused me to judge the instance status. Ask for answers 

### What you expected to happen

alaways the last time

### How to reproduce

this happens when the service has a large number of requests

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
8.x is EOF. We are not following that anymore.
