### ISSUE TITLE
[Feature] : Enable or disable agent dynamically through runtime option

### ISSUE THREAD

**Issue by westbigben** [apache/skywalking#10265]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Dear Apache SW team,

Thank you for your support.

Now, coming from using New Relic(NR) and intending to migrate over to Apache Skywalking(SW), I have a feature request that I couldn't find in SW that was available in NR. I'm sorry if I'm comparing these two, but that one feature will help me segregate and ease out my microservice deployment.

The requirement is:

1. I would keep my agent to be running as default on my docker image. Therefore, all new containers will have the java-agent running and will start streaming data to the SW server.
2. Whichever Microservice I don't want to report into SW, I will just add a run-time JVM option (something like -Dskywalking.agent.enable=false) and therefore, that container won't transmit data to the server.

### Use case

Some of my lower environments may not need monitoring, or I may need only few services across staging, pre-prod and prod to write into SW. 
In which case, the services which I wish were quiet, I can configure the runtime values to use the dynamic configuration option. 

The other fact is since we use helm to deploy applications, the lower environments' helm charts maybe +1 or +2 versions in comparison to that on production, thereby instead of managing multiple agent.configs or SW servers, it will be good if these can be handled dynamically.

So on those instances, if I pass JAVA_OPTS="-javaagent:/skywalking.jar -Dskywalking.agent.disable=false", those service related containers maybe left out from logging data.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you asking disabling service aget through -D?
This is strange, why you could add -D but can't remove -javaagent?

**Comment by westbigben** [comment]
Thank you for the reply. So let me elaborate a little:

We have a springboot based base-alpine image,

where our internal javaagent and the skywalking javaagent are both incorporated. Now, all our other app helms use this base image and build their charts upon that. So, to delete the javaagent on the base image will mean modifying close to 400 app helm charts which would be a long-drawn and company-wide impacting change, which might never get a green light.

So, adding that flag would be targetting only one helm chart at a time, also, some of these apps may never want to move into SW, sometimes they want to move in or out.

**Comment by wu-sheng** [comment]
OK. From tech perspective, this is easy. You could contribute a new config for the agent, which would be exposed as system property(-D) and System env variable automatically.

Would you like to contribute this directly?

**Comment by westbigben** [comment]
Thank you Sir Wu-sheng. Although I would love to, I am not very well versed on how to get that done. I have come from system admin background into DevOps realm very recently and my programming language is very naive at best.

**Comment by wu-sheng** [comment]
@westbigben I submitted the https://github.com/apache/skywalking-java/pull/439 for this.
With the more you use this, I would recommend you to be familiar with codes, most likely, we may need new plugins or some bug fixes.

**Comment by westbigben** [comment]
@wu-sheng - Thank you and I am going through the code. It could help me gain speed.
