### ISSUE TITLE
[Bug] grpc alarm failed to update configuration from dynamic configuration source

### ISSUE THREAD

**Issue by inversionhourglass** [apache/skywalking#10274]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

OAP Version: 9.3.0

When using gRPCHook for alarm, the configuration cannot be updated from the dynamic configuration source.

I found some problems with GRPCCallback.

If there is no gRPCHook configuration under `alarm-settings.yml` during initialization, the `alarmSetting` field will be set to null in the constructor, and the `doAlarm` method will always exit when the first condition is judged.

https://github.com/apache/skywalking/blob/3220339a1c167e03a2d483024091de384c66861b/oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/grpc/GRPCCallback.java#L49-L68

### What you expected to happen

gRPC alarm configuration supports dynamic configuration.

### How to reproduce

1. Use any kind of dynamic configuration, add gRPCHook alarm configuration.
2. trigger any alarms.
3. You will not receive any alarms.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by inversionhourglass** [comment]
The current code reads the latest dynamic configuration in the `onGRPCAlarmSettingUpdated` method, but its execute after the `alarmSetting == null`, and the `alarmSetting` field is not updated in the `onGRPCAlarmSettingUpdated` method.

I made a few tweaks and it works fine.
https://github.com/inversionhourglass/skywalking/commit/aeb1c4a53304c54083ce33796f827f6009fd9a4f

**Comment by wu-sheng** [comment]
If you want to fix this, welcome.
