### ISSUE TITLE
Is there any plan to develop the go version backend server?

### ISSUE THREAD

**Issue by mesosxzan** [apache/skywalking#10280]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Is there any plan to develop the go version backend server?because I found that the java version takes up a lot of cpu and memory

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No, there is no point to do this.
