### ISSUE TITLE
[Feature] [UI] Improve the clarity of event list display in trace span

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#10295]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Change the event list in trace span to Trace view

### Use case

Currently, the event list displayed in trace spans is not clear and easy to understand. We suggest implementing a trace display mode where the current span is used as the root span, and event names are displayed as span names. Additionally, the events should be sorted based on their start time (in nanoseconds) to form a trace tree. This way, the names of the events will be easily visible on the left side, and the execution time will be easily visible on the right side. This will greatly improve the overall visibility and clarity of the trace spans.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We just need to reuse similar UI component, it doesn't need to a span.

**Comment by wu-sheng** [comment]
This could be using the style of alerting page to show the time series flow.

**Comment by mrproliu** [comment]
Sure. Also, I propose adding a timeline to the right side of the Trace view(style like the below image) to quickly and easily visualize each event's start and end times. 
![image](https://user-images.githubusercontent.com/3417650/217780150-93d446cf-1d0c-45af-84c8-c6dde79d8c1b.png)

**Comment by wu-sheng** [comment]
Resolved by https://github.com/apache/skywalking-booster-ui/pull/234
