### ISSUE TITLE
[Bug] Live demo return 401 error

### ISSUE THREAD

**Issue by saikrishna-chunchu** [apache/skywalking#10307]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

When I visit the Live Demo link(http://demo.skywalking.apache.org/) from https://skywalking.apache.org/#demo page, I am seeing "401 Authorization Required" error page.

### What you expected to happen

It should prompt the user to enter Basic Auth credentials.

### How to reproduce

Visit the link http://demo.skywalking.apache.org directly 
or 
click on the Live Demo button in https://skywalking.apache.org/#demo page.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
The browser requires an auth, yes. 
It would pop out a box, you may have some local setup.
The username and password are on website already.

**Comment by saikrishna-chunchu** [comment]
**Google Chrome browser (Version 109.0.5414.75 (Official Build) (64-bit))**
The Basic Auth pop-up dialog is not prompted. I observed the same issue in the Incognito window as well.

**Microsoft Edge**
The Basic Auth pop-up dialog is shown, and I was able to login.

Thanks.

**Comment by Superskyyy** [comment]
v109.0.5414.120 Chrome verified pop up shows, edge latest pop up shows. It's most likely your environment problem, please try to reset/reinstall your browser. Unless you can find out what went wrong, there's not much we can do on the server side.

If you would like to access the demo bypassing the prompt, please use `username:password@http://demo.skywalking.apache.org/`

**Comment by adudiapis** [comment]
What are the login credentials to see live demo? 
URL: http://demo.skywalking.apache.org

**Comment by adudiapis** [comment]
**skywalking:skywalking**

Found credentials on Updev site, thanks to them. Leaving the link if someone like me are wondering what the credentials are. https://uptrace.dev/get/open-source-apm.html#skywalking

**Comment by Superskyyy** [comment]
> What are the login credentials to see live demo? URL: http://demo.skywalking.apache.org

The credentials are right there on our official landing page.. 

![image](https://github.com/apache/skywalking/assets/26076517/0f86f7e8-c1bb-48b6-84f2-8bb55fc156b0)
