### ISSUE TITLE
[Feature] [BanyanDB] Write-ahead Logging(WAL)

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#10301]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

WAL is a technology to provide atomicity and durability in DB. A write-ahead log is an append-only disk-resident structure used for crash recovery. The changes are first recorded in the log before the changes are written to the database’s memory. These records could be overwritten when they are flushed to the stable storage(disk).

BanyanDB will use WAL to build several crucial components:

1. The redo log for crash recovery.
2. A queue to share data between different components. For example, the measure module sends data to topN processor through a WAL-based queue.
3. pipelines for data replication.

Based on the above requirements, BanyanDB’s WAL has to support the following:

1. Batch write. WAL should provide single and batch write operations.
2. Partitioned. There are several segments in a WAL. Clients have capacities to interact with a segment independently.
3. Unblocked write. Writing should not block other operations.
4. Files rotation. A new segment file will be created when the segment is full.
5. Retention. Expired files could be cleaned up based on the max size.

_Caveat: WAL should avoid MMAP be referring to https://db.cs.cmu.edu/mmap-cidr2022/_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HHoflittlefish777** [comment]
Please assign to me.

**Comment by hanahmily** [comment]
@HHoflittlefish777 Please draft a design of WAL and place it to https://github.com/apache/skywalking-banyandb/tree/main/docs/concept. The core committers will review it through a PR.

**Comment by HHoflittlefish777** [comment]
@hanahmily Should I pull two request?One is docs, the other is code？

**Comment by hanahmily** [comment]
Exactly. We should align the details before coding.

**Comment by HHoflittlefish777** [comment]
Got it.

**Comment by hanahmily** [comment]
After a talk with @HHoflittlefish777 , we remove the consumer part from the WAL core. The consumer-related algorithms will belong to the dedicated modules using the WAL core. 

We are also thrilled to try use [Async Direct IO](https://www.scylladb.com/2017/10/05/io-access-methods-scylla/) to implement the flushing procedure of WAL since the MMAP is never an option for us. AIO/DIO could bring high performance to BanyanDB. But it is also a challenge, taking more time to do testing and tuning. Before it was generally available, we still relied on the traditional BufferIO. WAL should introduce a switch to enable/disable the DirectIO. This flag could be [a build tag](https://www.digitalocean.com/community/tutorials/customizing-go-binaries-with-build-tags).
