### ISSUE TITLE
add “ALL” item for General-Root's trace dashboard

### ISSUE THREAD

**Issue by qw4285632q** [apache/skywalking#10320]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

in skywalking ui 8.6.3 We can quickly find out which services have error calls in the last 5 minutes through the all option of the service. However, in the latest version of the ui interface, the all option cannot be selected for global search

### Use case

Add all option when selecting services in trace interface in General-Root interface

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> which services have error calls in the last 5 minutes through the all option of the service

This is a typical no-sense behavior. Why you are doing this? Why isn't there an alterting rule to trigger but you still search for.
