### ISSUE TITLE
[Bug] In projects enhanced with jdk-threading-plugin and kafka-plugin, duplicate TraceId can occur

### ISSUE THREAD

**Issue by yaboofzu** [apache/skywalking#10321]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

在使用  jdk-threading-plugin和 kafka-plugin   增强的项目中，会出现TraceId 重复的情况
In projects enhanced with jdk-threading-plugin and kafka-plugin, duplicate TraceId can occur

### What you expected to happen

Skywalking 需要管理插件之间的相互影响，保证TraceId 不能重复。
Skywalking manages the interactions between plug-ins to ensure that traceids cannot be repeated.

### How to reproduce

示例如下：
for example：
```
@Component
public class TestConsumer implements Runnable {
    private Logger logger = LoggerFactory.getLogger(this.getClass());
    private KafkaConsumer<String, String> consumer;
   @Autowire
    private ExecutorService executorService;

    @PostConstruct
    public void initKafkaConsumer() {
        int threadNum = SysConfig.getInteger("worksheet.statistic.threads", Runtime.getRuntime().availableProcessors());
        handleMap = AbstractHandler.getHandlerList();
        consumer = new KafkaConsumer<>(worksheetKafkaClient.consumeProperties());
       // 这里被jdk-threading-plugin 增强， 创建TraceContext
       // enhance by  jdk-threading-plugin,  generate TraceContext
        this.run();
   }
    @Override
    public void run() {
      
        logger.info("consumer start ");
        try {
            while (running) {
                ConsumerRecords<String, String> poll = consumer.poll(200);
                logger.info("poll message");
                for (ConsumerRecord<String, String> record : poll) {
   // Cn:多线程创建的Trace上下文会传递到下游，  
   //kafka-plugin在上游TraceContext存在的情况下，将无法再按照消息的维度重新生成TraceContext
   //因此导致所有消息的 traceId 均重复掉了,主要是因为这里复用了多线程生成的的TraceContext
   // En:The Trace context created by multiple threads is passed downstream,
   // kafka-plugin can't regenerate TraceContext based on the dimensions of the message if the upstream TraceContext 
   // exists, consumer message traceId repeat ，the traceId create by  multiple threads not kafka        
                    executorService.submit(() -> processMessage(record));
                }
            }
        } catch (WakeupException ex) {
            logger.info("wakeup consumer while running=" + running,ex);
        } catch (Exception e) {
            logger.error("kafka stopped!", e);
        } finally {
            try {
                consumer.close();
            } catch (Exception e) {
                logger.error(String.format("close kafka consumer %s failed!", JSON.toJSONString(handleMap.keySet())), e);
            }
        }
    }
}
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is unable to control from a general use plugin.

> All bootstrap plugins are optional, due to unexpected risk. 

Take the warning seriously, when the official doc puts it in the first line.

https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/bootstrap-plugins/

Don't be native to think all things work automatically.

**Comment by wu-sheng** [comment]
When the plugin was added, we knew from beginning, what you described could happen and must happen one way or another.
This is why it is only in optional.
Application codes are super complex, automatical cross thread tracing is impossible to work as always. This is for sure. We provided manual toolkit to ask you to control manual.
Don't expect unexisting magic.
