### ISSUE TITLE
springboot uses nacos as the registry center. The internal protocol of nacos is grpc. The springboot service cannot be started when SkyWalking java-agent is used

### ISSUE THREAD

**Issue by shining-stars-lk** [apache/skywalking#10331]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

springboot uses nacos as the registry center. The internal protocol of nacos is grpc. The springboot service cannot be started when SkyWalking java-agent is used.

**version:**
spring-boot:2.3.12.RELEASE
spring-cloud:Hoxton.SR12
spring-cloud-starter-alibaba-nacos-discovery:2.2.7.RELEASE
nacos-common:2.0.3
nacos:2.0.3
skywalking: java-agent8.14.0

### What you expected to happen

It is suspected that SkyWalking incorrectly enhanced the grpc, causing the springboot service to fail to register with nacos through the grpc.
![微信图片_20230202154633](https://user-images.githubusercontent.com/40255310/216262719-b4d07b64-beab-422f-8dbf-42c05ab15697.png)

### How to reproduce

Check to see if the grpc of nacos has been incorrectly enhanced

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Our plugin is designed for general gRPC use. We don't have information how nacos uses it internally.
And I can't understand the error you posted. 
I cab share is that, a dynamic field is planned to add into gRPC class as interceptor, this is a standard change for SkyWalking. You may be better to discuss with nacos team why this would becom an issue.
