### ISSUE TITLE
Performance analysis without data

### ISSUE THREAD

**Issue by JavaLionLi** [apache/skywalking#10336]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

![image](https://user-images.githubusercontent.com/31852897/216542982-8f44f313-3c62-462e-ab09-1603d3550eb4.png)
![image](https://user-images.githubusercontent.com/31852897/216543030-06c670c2-d996-4ce6-82a3-8d5c3d36392c.png)
![image](https://user-images.githubusercontent.com/31852897/216543068-18769f0d-19d9-44c6-8576-b37d5e040e64.png)

Unable to collect data
Is which step wrong
Please advise

### What you expected to happen

Hope to collect data

### How to reproduce

After connecting, create a new task and access interface, and wait until the task time is reached, and there is no data.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JavaLionLi** [comment]
sky 8.9.1

**Comment by wu-sheng** [comment]
Profiling is based on sampling, it could have no data if it happens occasionally.
Also, v8 is EOL. We are not following it anymore.

**Comment by wu-sheng** [comment]
Profiling is based on sampling, it could have no data if it happens occasionally.
Also, v8 is EOL. We are not following it anymore.

**Comment by JavaLionLi** [comment]
> Profiling is based on sampling, it could have no data if it happens occasionally. Also, v8 is EOL. We are not following it anymore.

I have requested more than 10 times within the sampling time and still have no data.

**Comment by wu-sheng** [comment]
I can't tell what happens. You need to locate it by yourself first. I can only say, if requests are too fast, there is no profiling.

**Comment by wu-sheng** [comment]
One more thing, you are trying to profile a webflux request? It is cross thread request process, you would get nothing. It is always too quick to finish.
Recommend you read profiling doc first.

**Comment by JavaLionLi** [comment]
> One more thing, you are trying to profile a webflux request? It is cross thread request process, you would get nothing. It is always too quick to finish. Recommend you read profiling doc first.

Known problem, spring-gateway use is invalid, undertow use is invalid (version 2.2.22), tomcat is valid
