### ISSUE TITLE
[Feature] [Python] Add log reporter support for loguru

### ISSUE THREAD

**Issue by Jedore** [apache/skywalking#10334]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I use [loguru](https://github.com/Delgan/loguru) to log in python program.  But, python agent log reporter can't catch loguru's log.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to contribute this?

**Comment by Jedore** [comment]
> Are you going to contribute this?

Yeah, i will contribute this featue.

**Comment by Jedore** [comment]
> Great! Since loggers are used through out user applications and other packages, please make sure to thoroughly test (and provide new e2e tests) when enhancing the feature.
> 
> The current logging interceptor only instruments the built-in logging.py, so you need to modify the structure/configurations a bit. 

Thanks for tips.

**Comment by wu-sheng** [comment]
@Superskyyy Would we consider this in 1.0 or 1.1?
I feel we pushed further for 1.0 in months.

**Comment by Superskyyy** [comment]
> @Superskyyy Would we consider this in 1.0 or 1.1? I feel we pushed further for 1.0 in months.

Depends on @Jedore's speed, I'm aiming a vote this weekend.

**Comment by Superskyyy** [comment]
> > @Superskyyy Would we consider this in 1.0 or 1.1? I feel we pushed further for 1.0 in months.
> 
> Depends on @Jedore's speed, I'm aiming a vote this weekend. Since this change will be quite small but multiple users have asked if I remember correctly.

**Comment by wu-sheng** [comment]
Got it. Thanks.

I can see 3 left in https://github.com/apache/skywalking/issues/9939 Do you plan to finish these two as well?

**Comment by Superskyyy** [comment]
> Got it. Thanks.
> 
> I can see 3 left in #9939 Do you plan to finish these two as well?

Yes it's coming very soon. I actually already finished the code two months ago as a huge PR. Yet I kept finding other bugs from the agent and covid thing so it was blocked until recently. :|

**Comment by wu-sheng** [comment]
Thanks. I just want to make sure milestone is accurate.
Look forwars to the 1.0

**Comment by Jedore** [comment]
> > @Superskyyy Would we consider this in 1.0 or 1.1? I feel we pushed further for 1.0 in months.
> 
> Depends on @Jedore's speed, I'm aiming a vote this weekend. This change will be quite small but multiple users have asked if I remember correctly.

I will try to make it as fast as i can. 👨‍💻

**Comment by Superskyyy** [comment]
> > > @Superskyyy Would we consider this in 1.0 or 1.1? I feel we pushed further for 1.0 in months.
> > 
> > 
> > Depends on @Jedore's speed, I'm aiming a vote this weekend. This change will be quite small but multiple users have asked if I remember correctly.
> 
> I will try to make it as fast as i can. 👨‍💻

Thanks!

**Comment by Jedore** [comment]
About feature, I would follow these steps:
1. Create a `sw_loguru` module in `skywalking.log` package. 
2. Move `sw_logging.transform` function to `log.formatter` module.
3. Move `build_log_tags` function from  `sw_logging` to `log.formatter` module.

Is there anything inappropriate ？
And I will think about test part a little latter. 
Hope for your suggestion. @Superskyyy

**Comment by Jedore** [comment]
About feature, I would follow these steps:
1. Create a `sw_loguru` module in `skywalking.log` package. 
2. Move `sw_logging.transform` function to `log.formatter` module.
3. Move `build_log_tags` function from  `sw_logging` to `log.formatter` module.

Is there anything inappropriate ？
And I will think about test part a little latter. 
Hope for your suggestion. @Superskyyy

**Comment by Superskyyy** [comment]
> About feature, I would follow these steps:
> 
> 1. Create a `sw_loguru` module in `skywalking.log` package.
> 2. Move `sw_logging.transform` function to `log.formatter` module.
> 3. Move `build_log_tags` function from  `sw_logging` to `log.formatter` module.
> 
> Is there anything inappropriate ？ And I will think about test part a little latter. Hope for your suggestion. @Superskyyy

That sounds great. I guess the other important thing is to see if loguru and sw_logging can co-exist, if they produce duplicated results you will need to provide a configuration to disable one of them. I don't know how lorugu works though.

**Comment by Jedore** [comment]
Ok，i got it. Thanks.@Superskyyy

**Comment by Jedore** [comment]
Now, it's a little complex. `loguru`'s logic/structure are not like `logging`, and `loguru` has different versions different log parameters. So i would put `sw_loguru` into `plugins` package and make individual functions for it. `loguru` and `logging` can coexist, they have different entries and exits, so there would not be duplicated logs. 

And I'm a little puzzled about e2e test. Can you make a brief introduction and how to run e2e test on my computer ?
Thanks very much. @Superskyyy

**Comment by Superskyyy** [comment]
Hi, it's okay that you put it into plug-ins folder due to the version differences. 

As to e2e tests, it's perfectly normal to be confused at first glance. Let me walk you through it.

... unfinished be right back.

**Comment by Superskyyy** [comment]
And don't hurry, take your time. @Jedore

**Comment by Jedore** [comment]
> And don't hurry, take your time. @Jedore

Got it.  👌

**Comment by Jedore** [comment]
I have done, but my env(poetry) in trouble from adding loguru to pyproject.toml. 😢
