### ISSUE TITLE
When I successfully installed the php skywalking agent, the php worker process kept hanging up

### ISSUE THREAD

**Issue by zhaozuowu** [apache/skywalking#10346]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

When I successfully installed the php skywalking agent, the php worker process kept hanging up

  php.ini setting

[skywalking]
extension=skywalking_agent.so

# Enable skywalking extension or not.
skywalking_agent.enable = On

# Log file path.
skywalking_agent.log_file = /usr/local/etc/skywalking-php.log

# Log level: one of `OFF`, `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`.
skywalking_agent.log_level = INFO

# Address of skywalking oap server.
skywalking_agent.server_addr =http://127.0.0.1:11800

# Application service name.
skywalking_agent.service_name = gateway-uat

# Skywalking version.
skywalking_agent.skywalking_version = 8

# Skywalking worker threads, 0 will auto set as the cpu core size.
 #skywalking_agent.worker_threads = 3

______________________________________

Error in php-error.log

zend_mm_heap corrupted
[05-Feb-2023 13:46:05] WARNING: [pool www] child 115 exited with code 1 after 1350.514043 seconds from start
[05-Feb-2023 13:46:05] NOTICE: [pool www] child 157 started

### What you expected to happen

I expect it to work

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### What happened

        php.ini setting

[skywalking]
extension=skywalking_agent.so

# Enable skywalking extension or not.
skywalking_agent.enable = On

# Log file path.
skywalking_agent.log_file = /usr/local/etc/skywalking-php.log

# Log level: one of `OFF`, `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`.
skywalking_agent.log_level = INFO

# Address of skywalking oap server.
skywalking_agent.server_addr =http://127.0.0.1:11800

# Application service name.
skywalking_agent.service_name = gateway-uat

# Skywalking version.
skywalking_agent.skywalking_version = 8

# Skywalking worker threads, 0 will auto set as the cpu core size.
 #skywalking_agent.worker_threads = 3

______________________________________

Error in php-error.log

zend_mm_heap corrupted
[05-Feb-2023 13:46:05] WARNING: [pool www] child 115 exited with code 1 after 1350.514043 seconds from start
[05-Feb-2023 13:46:05] NOTICE: [pool www] child 157 started

      

### What you expected to happen

我希望能修复这个问题

### How to reproduce

fix

### Anything else

fix

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@jmjoy I am not sure whether this kind of issue report makes sense. There is no reproduce processes or demo codes.
Your call.

**Comment by zhaozuowu** [comment]
> @jmjoy我不确定这种问题报告是否有意义。没有复制过程或演示代码。 你的来电。
成功安装php skywalking_agent 扩展后，请求php，worker就直接挂了，对应的php-error.log:

WARNING: [pool www] child 72 exited on signal 11 (SIGSEGV) after 24.121933 seconds from start

**Comment by wu-sheng** [comment]
If you keep posting in Chinese, I have to close all you posted. We need to keep all global users readable. Please update your words as soon as possible.

**Comment by wu-sheng** [comment]
@zhaozuowu Open source community is not a thing like your commercial customer service. If you can't provide codes to reproduce the error, we don't know how we can help.
Putting a simple error message doesn't help actually. You should learn how to talk to a community remote to you.

**Comment by zhaozuowu** [comment]
> @zhaozuowu Open source community is not a thing like your commercial customer service. If you can't provide codes to reproduce the error, we don't know how we can help. Putting a simple error message doesn't help actually. You should learn how to talk to a community remote to you.


The php-fpm error log has a re-error code：
[05-Feb-2023 14:53:18] WARNING: [pool www] child 72 exited on signal 11 (SIGSEGV) after 24.121933 seconds from start

**Comment by jmjoy** [comment]
Please open `coredump` and use `gdb` to print the backtrace.

**Comment by wu-sheng** [comment]
As no context discussion keeps happening on off list, no point to trace here.
