### ISSUE TITLE
[Bug] trace.ignore_path not working

### ISSUE THREAD

**Issue by Alceatraz** [apache/skywalking#10353]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Skywalking still show trace of endpoint `/status`

### What you expected to happen

Endpont of `/status` in trace should dispear.

### How to reproduce

- Move `optional-plugins/apm-trace-ignore-plugin-8.14.0.jar` into `plugins`
- Add `trace.ignore_path=${SW_TRACE_IGNORE_PATH:/status}` into agent.conf
- Inject `SW_TRACE_IGNORE_PATH` or not ( use default value `/status` )
- Boot java application with agent

### Anything else

Using: 
- elastic-7.17.8 
- oap-9.2.0 
- ui-9.2.0 
- java-agent-8.14.0

FYI:

- Using K8S readProbe for `/status`
- A SpringBoot web appliction

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Alceatraz** [comment]
I'm willing to submit a PR, But I worry about that my ability not enough to do that.

**Comment by wu-sheng** [comment]
Notice, `/status` is not the endpoint. Check the UI of endpoint or trace, the name of endpoint and span's operation name are suitable endpoint name.

**Comment by wu-sheng** [comment]
And this is only a question, please submit to the discussion panel next time.
