### ISSUE TITLE
ui Search Select Query date logs cannot automatically jump to the specified time range

### ISSUE THREAD

**Issue by liuxin638507** [apache/skywalking#10354]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

After a time range is selected from 9.2.0 to 9.3.0, logs cannot be automatically diverted to the time range. In version 9.1.0, logs can be diverted to the time range

### What you expected to happen

![image](https://user-images.githubusercontent.com/32058132/217136180-c8947d6d-eaf0-4ebd-9489-9253056e6713.png)

### How to reproduce

Select a service, adjust the time range, and check whether log is switched to the selected time range

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@Fine0830 This seems a log widget bug?
