### ISSUE TITLE
[v9.x UI Feature] Using URL parameters as conditions to query trace

### ISSUE THREAD

**Issue by MagikLau** [apache/skywalking#10359]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[v9.x UI Feature] Using URL parameters as conditions to query trace

Hard to query simple traces without this api after [[Rocketbot UI is replaced by the new Booster UI(https://github.com/apache/skywalking-booster-ui) since 9.0.0 release](https://github.com/apache/skywalking-rocketbot-ui)]

Thanks a lot

### Use case

example(from previous PR):
http://localhost:8880/trace?endpointname=runtest&traceid=2.30.15753618423830000

### Related issues

issue before 9.x
https://github.com/apache/skywalking/issues/4205

Previous PR at 6.6.0
https://github.com/apache/skywalking/pull/4037/commits/66cfe67dbd9261772b7ca2d15c2337e618cc8f8b

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Pick the endpoint ID before searching trace. We wouldn't support this.
