### ISSUE TITLE
skywalking8.6 use  kafka-reporter-plugin-8.6.0.jar can not print tid 

### ISSUE THREAD

**Issue by CCcreate** [apache/skywalking#10363]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

skywalking8.6 使用 kafka-reporter-plugin-8.6.0.jar  无法打印tid 并且 skywalking控制台也没有追踪ID

### What you expected to happen

可以打印追踪ID

### How to reproduce

windows10 系统 java springboot2.2.5 整合skywalking8.6 kafka传输日志 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
SkyWalking v8 is EOL. So, no further discussion.
And reporter has nothing related about teace ID in logs.
