### ISSUE TITLE
[Bug] Skywalking SQL error.Booster-UI cannot display data

### ISSUE THREAD

**Issue by gamlungJoeng** [apache/skywalking#10368]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

In the browser panel of the UI, the custom Widget has no data display.
For example: the browser_app_page_fmp_avg chart does not show any results no matter how the time scale is switched

### What you expected to happen

Normal display data in custom widget.

### How to reproduce

     1. Start a skywalking-OAP 
     2. Import skywalking-client-js and register an app when app start.
     3. Open booster-ui browser panel. Add custom widget of browser_app_page_fmp_avg and save to refresh browser.
     4. Switch time scale at will

### Anything else

     I lack Java knowledge, but I turned on the database query log, which records the SQL executed during booster-UI queries. In the SQL of "select id, value from table where id in (id1, id2)" in the log, id1 and id2 lack the base64 encoding part of "endpoint".
The id in the browser_app_page_fmp_avg table consists of date + serviceId + endPoint. However, the value of id in the sql of Skywalking-OAP is only date+serviceId.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gamlungJoeng** [comment]
![image](https://user-images.githubusercontent.com/118876071/217761093-ed26a15a-7508-478c-b523-ddd748fb281f.png)
![image](https://user-images.githubusercontent.com/118876071/217761269-62f1ad43-08be-44b3-b88f-9fdbaf155406.png)
![image](https://user-images.githubusercontent.com/118876071/217761399-33e8eff8-4142-41df-ad00-a7acd6240fc3.png)

**Comment by wu-sheng** [comment]
This is browser monitoring, I don't know what do you expect.
Showing database not have data doesn't mean anything.

**Comment by gamlungJoeng** [comment]
There is data in the database, but the query function of the console is not responding normally. The log shows that there is an error in the query statement, which I think exists in the OAP node
