### ISSUE TITLE
[Bug] Performance analysis function can be used normally

### ISSUE THREAD

**Issue by wangming2674** [apache/skywalking#10361]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

When I use the performance analysis function in skywalking for my project, I can't get any data no matter what.

Then I try to find the cause of this problem,I have tested the single application based on spring-boot and the micro-service application based on spring-cloud-alibaba many times, when I use the web container as 'undertow'(my project default web container is undertow), the performance analysis function does not work properly, but when I switch the web container as 'tomcat', I can use the performance analysis function normally.

Therefore, I think it is possible that skywalking's support for 'undertow' web container has compatibility problems or is not handled well enough.

The version of dependencies I use is：
skywalking version:9.3.0(This problem exists in several versions，for example, 8.9.1)
java agent:8.13.0
undertow verion:2.2.2.Final
embedded tomcat version:9.0.70

If you have time, I hope to fix this issue, it will make skywalking better，thanks.

### What you expected to happen

Performance analysis function can be used normally.

### How to reproduce

Create a new task, and then request the interface to test.
Using the default embedded tomcat container is normal, after switching undertow can not use the performance analysis function normally.

### Anything else

These are my test result, I hope it can help you understand this problem.
1.test when use tomcat(normal):
![image](https://user-images.githubusercontent.com/37762337/217421923-1cefc351-ccbf-4a55-87e5-64de1331acbc.png)
![image (1)](https://user-images.githubusercontent.com/37762337/217422484-d4784902-c4c8-4a7d-9a8b-6df9468a529b.png)

2.test when use undertow(wrong):
![image](https://user-images.githubusercontent.com/37762337/217421401-4294efda-cf79-4309-a2ef-53387d676ea2.png)
![image](https://user-images.githubusercontent.com/37762337/217422921-263a6eb4-33d8-44ab-b43e-d799321652be.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Most likely duplcate #10377

**Comment by wangming2674** [comment]
> Most likely duplcate #10377
@wu-sheng 
I am sorry, I can't find #10377, you mean is #10337?

It looks like the phenomenon is the same as #10337,

Thanks for your reply, hope to see this issue fixed in 9.4.0, have a good day~ 😄
