### ISSUE TITLE
[Feature] java agent self-monitor

### ISSUE THREAD

**Issue by chenyi19851209** [apache/skywalking#10362]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Hello, the current UI of skywalking does not see the self-monitoring function of javaAgent (including dynamically closing the buried point of javaAgent in an emergency, displaying the last report time of javaAgent's heartbeat, the number of segments reported per minute, and the statistics of the number of internal errors in javaAgent) , please confirm whether skywalking currently does not have the self-monitoring function of javaAgent? We want to enhance the self-monitoring function of javaAgent and contribute to the skywalking community

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No, there is not.
