### ISSUE TITLE
[Feature] reports error mysql-root.json after starting layer_entity_name: MYSQL_All_MySQL-root conflict with exist configuration

### ISSUE THREAD

**Issue by zhanghengdashuaibi** [apache/skywalking#10375]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Version
9.3.0 reports error mysql-root.json after starting layer_entity_name: MYSQL_All_MySQL-root conflict with exist configuration UI is also version 9.3.0, without any configuration

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This means you have old UI settings in the database. Remove the old UI template table, and reboot.

**Comment by wu-sheng** [comment]
Notice, this should be a discussion only, don't repeatedly use issue panel as this is never asked.
