### ISSUE TITLE
[bug]apm-trace-ignore-plugin-8.14.0.jar not work in windows10+skywalking-apm-9.3.0+java8 ?

### ISSUE THREAD

**Issue by xusong** [apache/skywalking#10372]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

**apm-trace-ignore-plugin-8.14.0.jar not work in windows10+skywalking-apm-9.3.0+java8 ?**

### What you expected to happen

i want to path like http://127.0.0.1:8090/sw/xxx/ff not trace by agent for a test.

### How to reproduce

i had copy apm-trace-ignore-plugin-8.14.0.jar into skywalking-agent\plugins and add apm-trace-ignore-plugin.config into skywalking-agent\config and reboot app run by springboot2.
the skywalking-agent\logs\skywalking-api.log show "INFO 2023-02-09 18:06:52.157 main IgnoreConfigInitializer : Ignore config file found in D:\tools\apache-skywalking-apm-bin\skywalking-agent\config\apm-trace-ignore-plugin.config." and "INFO 2023-02-09 18:06:54.835 main AgentClassLoader : D:\tools\apache-skywalking-apm-bin\skywalking-agent\plugins\apm-trace-ignore-plugin-8.14.0.jar loaded. "

context of apm-trace-ignore-plugin.config here is 
trace.ignore_path=GET:/xxx/**,GET:/xxx/*,GET:/xxx/ff,/xxx*,/xxx,/xxx/*,/xxx/**,/sw/xxx/*,/sw/xxx/**,/sw/xxx*,/sw/xxx

note: /sw is contextPath

but after curl http://127.0.0.1:8090/sw/xxx/ff or http://127.0.0.1:8090/sw/xxx, sw still trace it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Try to debug on your own. This plugin had been asked a lot.

**Comment by xusong** [comment]
GET:/sw/xxx/**  take effect
