### ISSUE TITLE
Support Java profiling continues when cross thread.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#10373]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, the profiling targets the endpoint, and ends in current thread and segment only.
We could enhance this to make the profiling flag continues with Snapshot(capture/continue). Therefore, we could have a multi-thread profiling for one endpoint.

### Use case

Typically with more undertow use case, when it doesn't work with SpringMVC, the profiling feature is limited.
Also, for some in memory scheduleling, the current profiling doesn't fit well.

By implementing this enhancement, we should consider enhancing profiling Snapshot to bring thread or segment ID for UI to distinguish threads and merge them with different options.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mikechengwei** [comment]
Can I try to finish this function?

**Comment by wu-sheng** [comment]
@mrproliu When you and @Fine0830 finished all, and the feature is ready on demo.skywalking.a.o, please close here. 
I will run 8.15.0 agent side release.

One question, what will happen if agent 8.15 reports multiple profiled segments for the older(< 9.5.0) OAP? Is the old UI still working?

**Comment by mrproliu** [comment]
> One question, what will happen if agent 8.15 reports multiple profiled segments for the older(< 9.5.0) OAP? Is the old UI still working?

In the old UI, it still works, but the name displayed in Segment will be different from the configured endpoint name in Profiling because no merging process has been performed on the displayed segment at this time.

**Comment by wu-sheng** [comment]
OK. That should be fine.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/pull/10613 has merged.

@mrproliu Is this feature ready? If so, let's bring the showcase updated to this latest feature and verify again.
