### ISSUE TITLE
[Feature] 启动后报错mysql-root.json layer_entity_name: MYSQL_All_MySQL-Root conflict with exist configuration

### ISSUE THREAD

**Issue by zhanghengdashuaibi** [apache/skywalking#10370]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

9.3.0版本
启动后报错mysql-root.json layer_entity_name: MYSQL_All_MySQL-Root conflict with exist configuration
ui也是9.3.0版本，没有做任何配置

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't accept Chinese issue.
