### ISSUE TITLE
[Feature] Add a new cpm aggregation function that does not lose precision when downsampled

### ISSUE THREAD

**Issue by toffentoffen** [apache/skywalking#10419]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For services with a low rate of requests, for instance 1 per hour, the `cpm` aggregation function loses the requests when it is downsampled to hours or days treating it as effectively 0 requests.
This lose of precision can misleading while being unable to different if there really has been a request or not.

### Use case

Create a new function, for instance `cpm5d` (5 decimals), that doesn't lose precision after downsampling.
We need at least 5 decimals if we want to represent as precise as possible 1 request in a concrete hour of a day, downsampled to days.
The following example is 1 request in a concrete hour or a day. Which means at the end 1 request per day.
1 decimal: 1 / 1440 = 0 // We cannot different anymore
4 decimals: (1 * 10000) / 1440 = 6
5 decimals: (1 * 100000) / 1440 = 69

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Ref https://github.com/apache/skywalking/pull/10420#issuecomment-1476205729

**Comment by toffentoffen** [comment]
Should we revert UI committed changes for the CPM5D function?

**Comment by wu-sheng** [comment]
I think we should to keep consistent.

**Comment by wu-sheng** [comment]
@Fine0830 Could you remove that? I noticed it mixed with another change.

**Comment by Fine0830** [comment]
> @Fine0830 Could you remove that? I noticed it mixed with another change.

Sure
