### ISSUE TITLE
[Feature] Storage-elasticsearch-plugin supports query of selected fields

### ISSUE THREAD

**Issue by xzyJavaX** [apache/skywalking#10421]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In storage-elasticsearch-plugin, query of selected fields is not supported at present, and the entire data must be found every time.Similar functions are already available in other modules,for example:[storage-banyandb-plugin](https://github.com/apache/skywalking/blob/master/oap-server/server-storage-plugin/storage-banyandb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/banyandb/measure/BanyanDBMetadataQueryDAO.java#L166-L181)

### Use case

No response

### Related issues

No response

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is a nice-to-have thing. If you want to follow this, welcome.
