### ISSUE TITLE
[Feature] Can skywalking store plaintext json data when it uses elasticsearch as storage?

### ISSUE THREAD

**Issue by c8679724** [apache/skywalking#10425]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

When using skywalking, our company slightly modified the java agent, enabling the java agent to collect the header and body of http request as tag. After storage on elasticsearch, because spans are stored after base64 encoded protobuf object, the body content spans cannot be searched. Therefore, you hope to store plaintext json data when storage on elasticsearch.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Once you changed to private rather than upstream consensus, you are on your own only. Don't ask upstream to adopt your private fork. That is not how open source works.
