### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zhaoxiaojie0415** [apache/skywalking#10436]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

I use the skywalking v8.7.0 and thrift 0.9.3. In my case, A service communicate B service via thrift. If an error has occurred during the sendBase phase,  the ExitSpan would not be stopped。When the next request comes, the same thread always repeats the traceid generated for the first time.

### What you expected to happen

TServiceClientInterceptor does not stop Span. It seems that skywalking only stop the ExitSpan generated by thrift after the ”receiveBase“ method in TServiceClientReceiveInterceptor class.

### How to reproduce

We can define a thrift IDL as follows:
service TestThrift {
struct TRequest{
   1: map<string, string> property;
}

void testRpc(1: TRequest request)
}

We can create a TRequest, then put  "key="test", value=null" into the property. This would be generated a NPE in the "sendBase" phase. Subsequently, we keep making RPC requests, and we can observe that the same thread is consistently using the same traceId.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No title, and 8.7.0 is EOL.

**Comment by zhaoxiaojie0415** [comment]
> No title, and 8.7.0 is EOL.

Thanks, I found 8.14.0 has same issue, I submit an new issue.
