### ISSUE TITLE
[Bug] [INFRA] Summary LICENSE incorrectly for rust project.

### ISSUE THREAD

**Issue by jmjoy** [apache/skywalking#10446]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

License Tools (apache/skywalking-eyes)

### What happened

For example, in the project <https://github.com/apache/skywalking-rust>,
I run the command to generate the LICENSE file:

```shell
license-eye dependency resolve --summary ./dist-material/LICENSE.tpl -c .github/licenserc.yaml
```

But the dependencies url is not correct, such as:

```
========================================================================
Apache-2.0 licenses
========================================================================
The following components are provided under the Apache-2.0 License. See project link for details.
The text of each license is the standard Apache 2.0 license.
    https://npmjs.com/package/bytesize/v/1.1.0 1.1.0 Apache-2.0
    https://npmjs.com/package/e2e/v/0.0.0 0.0.0 Apache-2.0
    https://npmjs.com/package/prost/v/0.11.0 0.11.0 Apache-2.0
    https://npmjs.com/package/prost-build/v/0.11.1 0.11.1 Apache-2.0
    https://npmjs.com/package/prost-derive/v/0.11.0 0.11.0 Apache-2.0
    https://npmjs.com/package/prost-types/v/0.11.1 0.11.1 Apache-2.0
    https://npmjs.com/package/protobuf-src/v/1.0.5+3.19.3 1.0.5+3.19.3 Apache-2.0
    https://npmjs.com/package/skywalking/v/0.5.0 0.5.0 Apache-2.0
    https://npmjs.com/package/sync_wrapper/v/0.1.1 0.1.1 Apache-2.0
```

They should be prefix by `https://crates.io/`, not `https://npmjs.com/`.

### What you expected to happen

Dependencies prefix by `https://crates.io/`, such as `https://crates.io/crates/bytesize/1.1.0`.

### How to reproduce

In the project <https://github.com/apache/skywalking-rust>,
run the command to generate the LICENSE file:

```shell
license-eye dependency resolve --summary ./dist-material/LICENSE.tpl -c .github/licenserc.yaml
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
the link is generated according to your `./dist-material/LICENSE.tpl`, check your LICENSE.tpl template file
