### ISSUE TITLE
[CI] Spring 6 plugin test fails

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#10440]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Ref https://github.com/apache/skywalking-java/actions/runs/4250392441/jobs/7391536573

### What you expected to happen

Tests passed and suddenly began to fail in recent days. Need some recheck.

### How to reproduce

CI standard process.

### Anything else

How does Spirng6 test scenario use `<compiler.version>1.8</compiler.version>`? I remember it should be JDK 17.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
I've been not able to reproduce, even I clean up all my environment locally, including Docker images, agent codes, etc., will investigate some time later
