### ISSUE TITLE
[Bug] OAP TTL Slave table not deleted

### ISSUE THREAD

**Issue by ydyzxm** [apache/skywalking#10463]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

DataTTLKeeperTimer During the scheduled task, only data in the primary table is deleted. Data in the secondary table is not deleted. As a result, the data store is too large for a long time

### What you expected to happen

When the primary table is deleted, data in the secondary table is also deleted

### How to reproduce

If the segment data is reported, both the segment table and the segment_tag table are written into the segment table. However, when a scheduled task is deleted, only the segment data is deleted

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@wankai123 Could you confirm this? I just want to confirm and don't need to fix as all are going to be changed.

@kezhenxu94 Let's notice this in new implementations.

@ydyzxm See #10366

**Comment by wankai123** [comment]
Could you please share which version you use, there's a bug fixed before: https://github.com/apache/skywalking/pull/9508

**Comment by ydyzxm** [comment]
9.2.0

**Comment by ydyzxm** [comment]
user mysql ：H2HistoryDeleteDAO

**Comment by ydyzxm** [comment]
use mysql ：H2HistoryDeleteDAO

**Comment by wankai123** [comment]
Can you check the slave tables have `time_bucket` column?

**Comment by ydyzxm** [comment]
no，slave tables don't have time_bucket，delete By id

**Comment by ydyzxm** [comment]
If you add time_bucket field from slave table, the change is significant and you may have to change everything from table creation to query presentation

**Comment by wankai123** [comment]
> no，slave tables don't have time_bucket，delete By id

I don't know what do you mean,  JDBC TTL  don't have delete By id logic.

> If you add time_bucket field from slave table, the change is significant and you may have to change everything from table creation to query presentation

9.2 slave table should have time_bucket column , please check the fix #9508
Did you follow the change log upgrade your OAP?

**Comment by wu-sheng** [comment]
@kezhenxu94 will finish the new design implementation in 9.4.0. Generally, we don't have to follow this no matter it was fixed.

@ydyzxm I will close this, if you want to dig deeper, try the latest with a new env.
