### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ydyzxm** [apache/skywalking#10462]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

DataTTLKeeperTimer 定时任务删除数据时，只删除主表中的数据，从表的数据未进行删除，长时间会导致数据存储过大

### What you expected to happen

删除主表时，同时对从表数据进行删除

### How to reproduce

上报链路数据，此时同时写入 segment表，以及segment_tag表，但是定时任务删除时，只会对segment数据进行删除

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
English only on GitHub and no title.
Invalid issue report.
