### ISSUE TITLE
[Feature] When can curl_multi_exec be supported about PHP agent's cUrl ?

### ISSUE THREAD

**Issue by xxping** [apache/skywalking#10474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

we found curl_multi_exec not supported about PHP agent。
cURL work well ,but curl_multi_exec can't find HTTP_SW8 ,so we hope it can be supported it as soon as possible.

### Use case

we found curl_multi_exec not supported about PHP agent。
cURL work well ,but curl_multi_exec can't find HTTP_SW8 ,so we hope it can be supported it as soon as possible.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment]
Will support, but not now.
