### ISSUE TITLE
[Feature] node.js sdk support axios v1.0

### ISSUE THREAD

**Issue by aladdin-add** [apache/skywalking#10487]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

axios v1.0 has been supported a few months ago: https://github.com/axios/axios/blob/v1.x/CHANGELOG.md#100---2022-10-04

### Related issues

n/w

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to do this? We have hundreds of plugins, we would not follow all targets upgrade(new release), the whole community do instead.
