### ISSUE TITLE
[Feature] Option to edit a startup probe of oap in helm chart

### ISSUE THREAD

**Issue by rabajaj0509** [apache/skywalking#10481]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

From https://github.com/apache/skywalking/issues/10071, we know that oap container can take a considerable amount of time to startup, a good way to start up without invoking a deadlock via a liveliness probe (which could cause multiple restarts of the container) is to make use of the [startup probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes). Until the application boots completely for the first time, the startup probe will disable the liveliness probe and readiness probe.  This way it will help users to set liveliness and readiness probes with lesser `initialDelaySeconds` setting.  

### Related issues

https://github.com/apache/skywalking/issues/10071

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
closed by https://github.com/apache/skywalking-kubernetes/pull/108
