### ISSUE TITLE
[Bug] Entry Span does not override tag(AbstractTag, String) method

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#10480]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

In the `EntrySpan`, it only overrides `tag(String, String)`

```java
    @Override
    public EntrySpan tag(String key, String value) {
        if (stackDepth == currentMaxDepth || isInAsyncMode) {
            super.tag(key, value);
        }
        return this;
    }
```

but not this method,

```java
@Override
    public AbstractTracingSpan tag(AbstractTag<?> tag, String value) {
// ...
    }
```

while `ExitSpan` does for both.

### What you expected to happen

We should add,

```java
    @Override
    public AbstractTracingSpan tag(AbstractTag<?> tag, String value) {
        if (stackDepth == currentMaxDepth || tag.isCanOverwrite() || isInAsyncMode) {
            super.tag(tag, value);
        }
        return this;
    }
```

This cause confusion when we were investigating `Spring 6.x` test failure in https://github.com/apache/skywalking-java/pull/466#issuecomment-1452944810.

This latter issue is reported in #

### How to reproduce

Run `Spring 6.x scenario` test case and debug locally

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Close for now. No update in a month.
