### ISSUE TITLE
[Bug] Spring cloud gateway project logback cannot print TraceID

### ISSUE THREAD

**Issue by MorganMaxg** [apache/skywalking#10509]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.
- Similar like this is #5906 , But no Solution

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Cannot print TraceId on spring cloud gateway with logback.

### What you expected to happen

expected a real value of traceid, not `TID:N/A`

### How to reproduce

Follow these steps:
1. Download my code from project [springcloudgatewaylogbacktraceiderror](https://github.com/MorganMaxg/springcloudgatewaylogbacktraceiderror.git)
2. Build project with `mvn clean package`
3. start project. ``
4. testing with a url such as `curl 127.0.0.1:8081/demo/test`, log will print '[TID:N/A] [reactor-http-nio-2] INFO  c.e.m.filter.TraceIdGlobalFilter -hello world, N/A'

### Anything else

How can i print the traceId in GlobalFilter.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This was discussed many many times. Please search before opening a new one.

**Comment by MorganMaxg** [comment]
well, what's the final conclusion. I find nothing in #5906

**Comment by MorganMaxg** [comment]
I solve the problem by this way. 

1. `cp bootstrap-plugins/apm-jdk-threading-plugin-8.14.0.jar plugins/`. 
2. add add options to jvm `-Dskywalking.plugin.jdkthreading.threading_class_prefixes=io.netty.util.concurrent`

**Comment by hnsongbiao** [comment]
@wu-sheng 这个问题到底要怎么解决啊，都看到说问题是重复的，没看到在spring cloud gateway里记录traceId的方法，请提供解决办法的文档地址，

**Comment by hnsongbiao** [comment]
> This was discussed many many times. Please search before opening a new one.

 how to resolve this problem?

**Comment by wu-sheng** [comment]
Why ping me? The plugin is not written by me. I don't know anything about agent running in Spring cloud.

**Comment by BothSavage** [comment]
> > 这已经讨论过很多次了。请先搜索再打开新的。
> 
> 如何解决这个问题？

https://bothsavage.github.io/article/240121-skywaking

**Comment by BothSavage** [comment]
> 我通过这种方式解决问题。使用 Tomcat 方式运行 spring-cloud-gateway，而不是 netty。

https://bothsavage.github.io/article/240121-skywaking

**Comment by chenbihao** [comment]
As far as I know, the corresponding plugin is not maintained by anyone, so gateway 4 is not supported
