### ISSUE TITLE
[Bug] ERROR skywalking_agent::execute: before execute ex err=PHPer(ExpectType(ExpectTypeError { expect_type: TypeInfo { t: 4 }, actual_type: TypeInfo { t: 262 } }))

### ISSUE THREAD

**Issue by xxping** [apache/skywalking#10517]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

php agent log show 
ERROR skywalking_agent::execute: before execute ex err=PHPer(ExpectType(ExpectTypeError { expect_type: TypeInfo { t: 4 }, actual_type: TypeInfo { t: 262 } }))
how to fix it

### What you expected to happen

php agent log show 
ERROR skywalking_agent::execute: before execute ex err=PHPer(ExpectType(ExpectTypeError { expect_type: TypeInfo { t: 4 }, actual_type: TypeInfo { t: 262 } }))
how to fix it

### How to reproduce

php agent log show 
ERROR skywalking_agent::execute: before execute ex err=PHPer(ExpectType(ExpectTypeError { expect_type: TypeInfo { t: 4 }, actual_type: TypeInfo { t: 262 } }))
how to fix it

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xxping** [comment]
0.3.0 version

**Comment by jmjoy** [comment]
Code ?

**Comment by xxping** [comment]
my config
/etc/php/7.4/fpm/php.ini
![image](https://user-images.githubusercontent.com/11566855/223907273-dea08b6f-1caa-4fdb-bc73-e09c1cf6a436.png)

**Comment by xxping** [comment]
and the error log is
![image](https://user-images.githubusercontent.com/11566855/223907812-4a5801ad-6dab-4729-aebe-7b1dd95b4429.png)

**Comment by jmjoy** [comment]
Please write a demo to reproduce the error, otherwise I can't fix it.

**Comment by xxping** [comment]
what demo?sorry I don't understand. 
I just integrated the agent into my php project.and the  config is the above description,then the error show " ERROR shutdown: skywalking_agent::channel: channel send failed err=No such file or directory (os error 2)"

**Comment by xxping** [comment]
I searched for similar questions. It seems to only appear in version 0.2, but my version is 0.3.0

**Comment by xxping** [comment]
Hello. Can you give me some help?

**Comment by wu-sheng** [comment]
In the open-source, if you need some help, provide demo codes and steps to help on reproducing the error.
Otherwise, it is not worth to take maintainers so much time to guess.

**Comment by xxping** [comment]
[curl_php.txt](https://github.com/apache/skywalking/files/10940327/curl_php.txt)

It's curl code

**Comment by jmjoy** [comment]
> [curl_php.txt](https://github.com/apache/skywalking/files/10940327/curl_php.txt)
> 
> It's curl code @wu-sheng @jmjoy

This code failed to reproduce the issue.

**Comment by xxping** [comment]
> > [curl_php.txt](https://github.com/apache/skywalking/files/10940327/curl_php.txt)
> > It's curl code @wu-sheng @jmjoy
> 
> This code failed to reproduce the issue.


I think the problem may not be the code. I put the project in the K8S cluster, and through ingress-nginx access, I found that there is no SW8 key in http header. Could it be caused by ingress-nginx?

**Comment by jmjoy** [comment]
> I think the problem may not be the code. I put the project in the K8S cluster, and through ingress-nginx access, I found that there is no SW8 key in http header. Could it be caused by ingress-nginx?

Maybe not.

**Comment by jmjoy** [comment]
Please try latest version.
