### ISSUE TITLE
The current fetching data (/tagKeys) is logged with Exception while fetching data (/tagKeys) : null

### ISSUE THREAD

**Issue by liuxin638507** [apache/skywalking#10533]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

![image](https://user-images.githubusercontent.com/32058132/224721381-0345ee1d-73c1-4416-9d51-0daa0ce774e2.png)

### What you expected to happen

Exception while fetching data (/tagKeys) : null

### How to reproduce

Exception while fetching data (/tagKeys) : null

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Check your logs, we don't respond questions like this.
