### ISSUE TITLE
[Feature] [Eyes] Add option `--summary` for `license-eye dependency check`.

### ISSUE THREAD

**Issue by jmjoy** [apache/skywalking#10539]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now command `license-eye dependency resolve` support `--summary` option, which will generate the summary license file, but command `license-eye dependency check` not.

But in CI, the summary license file also need to be checked, the current method is to compare the generated license file from `resolve` with the original one, if `check` supports `--summary`, that would be much more convenient.

### Use case

Github action `apache/skywalking-eyes/dependency` supports check the summary license file.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment]
@kezhenxu94 How about the idea?

**Comment by kezhenxu94** [comment]
`check` is to check incompatible licenses, adding `--summary` to `check` command sounds like "the summary of incompatible licenses", if you wan to check the summary file, consider adding an option to `resolve` command like `--exit-code` , if the summary file changes after resolve command, set the exit code
