### ISSUE TITLE
Build multi architecture Docker images for Python agent 

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#10542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently we only have amd docker images for Python agent, for people who want to try it in arm machine like Apple m1 this is impossible now. Let’s build multi architecture docker images for Python agent. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
@jiang1997 you are interested in this?

**Comment by jiang1997** [comment]
> @jiang1997 you are interested in this?

 I am totally willing to do this.
