### ISSUE TITLE
table: alarm_record does not exist. OAP is running in 'no-init' mode

### ISSUE THREAD

**Issue by liuxin638507** [apache/skywalking#10540]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

v9.4.0 initializes a fresh startup with two copies of the oap, one of which is normal and the other is faulty，table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... Table: alarm_record does not exist. retry 3s later

### What you expected to happen

![image](https://user-images.githubusercontent.com/32058132/225236031-47c82aa3-a61a-4f3e-bd3c-137d2bc50283.png)
![image](https://user-images.githubusercontent.com/32058132/225235241-36f5faa1-7a04-4c42-b864-2ac4fe76fc75.png)

### How to reproduce

k8s helm start

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Check what is incompatible, otherwise, we don't know what happens.

**Comment by liuxin638507** [comment]
v9.4.0, using k8s deployment, es version 7.17.8, the initial startup will execute es-init.job, start two copies of oap service, one is normal, the other reported the error of the above screenshot, but I manually set the copy to 3, the newly added secondary will start normally, but with version 9.3.0, Two or more copies of an oap can start normally

**Comment by wu-sheng** [comment]
init.job should only be one pod only. I can't follow what you mean to others.

**Comment by qq280948982** [comment]
我也遇到了同样的问题，主要原因是有个初始化的 Job 跑不起来，因为里面有用到了 curlimages/curl 这个镜像，而被我们伟大的GFW给墙了所以拉不下来镜像，数据库就没有初始化因而就提示 table does not exist 了。但我愿为祖国建设事业奋斗的心怎可被小小的GFW阻挡，于是我按照如下的方式解决了：
1. 将整个chart拉下来
`helm pull oci://<国内可访问的镜像代理源>/apache/skywalking-helm --untar`

2. 修改 skywalking-helm/templates/_helpers.tpl ，将里面的 curlimages/curl 加上<国内可访问的镜像代理源>的地址前缀

3. helm upgrade skywalking-release ./skywalking-helm

这样 Job 就可以将镜像拉下来跑啦，又可以愉快的当牛马继续去搬砖了~
