### ISSUE TITLE
[Feature][BanyanDB-Java-Client] Support listing multi-ids in a single request

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#10559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The underlying server's gRPC specification of Property supports listing several entities through a single request. The java client limits the capacity, getting a single entity at a time. 

Now, we should implement the same behavior in the java client.

_Originally posted by @hanahmily in https://github.com/apache/skywalking/issues/10473#issuecomment-1468978642_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Should this be 0.4.0-RC0? Is BanyanDB server going to release 0.3.2 for this?
