### ISSUE TITLE
[Feature] Monitoring Redis Server

### ISSUE THREAD

**Issue by yswdqz** [apache/skywalking#10565]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Redis is an open source, in-memory data structure store, used as a database, cache, and message broker. It's very popular, so I thought it was necessary to add monitoring of Redis to SkyWalking.

The dataflow would be Redis Server -> redis_exporter -> OpenTelemetry Collector -> SkyWalking OTLP Receiver -> MAL engine.

### Steps
1.Discuss which metrics we should do for the Redis server.
2.Add Redis layer to OAP, and begin to set up dashboards.
3.Add Redis as a sub of the Database layer.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yswdqz** [comment]
@wu-sheng 
I think these metrics is enough:
 [metric doc](https://docs.google.com/document/d/1E975HrSey7Yj_4bWIqcXK9DQxMcLGFA2e1OsILdIDcY/edit)

**Comment by yswdqz** [comment]
Got it, I have edited the permission

**Comment by wu-sheng** [comment]
Just read it. I think it makes sense. Those are important metrics.

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking/pull/10655
