### ISSUE TITLE
[Feature] Live demo can be open source?

### ISSUE THREAD

**Issue by 2252603132** [apache/skywalking#10560]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Live demo can be open source

### Related issues

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
The demo is a deployment of showcase, https://skywalking.apache.org/docs/skywalking-showcase/next/readme/

**Comment by 2252603132** [comment]
thanks very much!



---Original---
From: "吴晟 Wu ***@***.***&gt;
Date: Mon, Mar 20, 2023 11:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/skywalking] [Feature] Live demo can be open source?(Issue #10560)




 
The demo is a deployment of showcase, https://skywalking.apache.org/docs/skywalking-showcase/next/readme/
