### ISSUE TITLE
[OSPP] [Feature] Unify query planner and executor in BanyanDB

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#10562]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, metrics from OAP and TopN generated from source metrics are both stored as a `Measure`. However, they are using different paths to read the data from the storage due to some historical reasons. Measure query is more complicated and comprehensive while TopN query is somehow ad-hoc. Then after finishing TopN streaming modules, we decide it is a good timing to fully unify the query planner and executor for Measure and TopN.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Pigeon377** [comment]
Hello @lujiajing1126 , I find this issue from ospp-2023 and be interested in this task. 
I hope to receive guidance on how to get started, because `banyand/measure` seems complicated(maybe i found the wrong package) and there seems to be little comment. I would greatly appreciate it if I could receive your guidance

**Comment by lujiajing1126** [comment]
> Hello @lujiajing1126 , I find this issue from ospp-2023 and be interested in this task. I hope to receive guidance on how to get started, because `banyand/measure` seems complicated(maybe i found the wrong package) and there seems to be little comment. I would greatly appreciate it if I could receive your guidance

Hello, can you reach me thru email? lujiajing@apache.org
