### ISSUE TITLE
[Bug] When the data of the last point is 0, there will be problems when displaying the table.

### ISSUE THREAD

**Issue by innerpeacez** [apache/skywalking#10564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

![image](https://user-images.githubusercontent.com/37059529/226281113-7fe53442-cb3f-44ae-aac6-57044b2143ab.png)

### What you expected to happen

Hope the last point is filtered out when it is 0

### How to reproduce

When the data of the last point is 0, there will be problems when displaying the table.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't have plan to exclude the latest value actually. Read https://github.com/apache/skywalking/issues/10501, that is the right way to do so. 0 sometimes means 0, it is meaningful
