### ISSUE TITLE
[Bug] Endpoint "SpringCloudGateway/sendRequest" in the trace isn't included in the Endpoint tab

### ISSUE THREAD

**Issue by hongshuai1994** [apache/skywalking#10570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

I started two services, a spring-cloud-gateway service and a spring-boot service, and the http request was forwarded to the spring-boot service through the spring-cloud-gateway service.

The spring-cloud-gateway service is connected to skywalking.
I copied the two plug-ins apm-spring-webflux-5.x-plugin-8.14.0.jar and apm-spring-cloud-gateway-2.1.x-plugin-8.14.0.jar to skywalking-agent.

After starting the two services and skywalking, you can see the trace in skywalking as shown in the figure below. In the entire trace, only the endpoint pointed by the arrow is not counted in the Endpoint tab. 

![image](https://user-images.githubusercontent.com/80237674/226578710-cb7c7d24-0db5-4850-81f9-14cabc0d9d9c.png)
![image](https://user-images.githubusercontent.com/80237674/226578860-c39af4d9-900a-4127-b00a-7462d3fe3b6c.png)
![image](https://user-images.githubusercontent.com/80237674/226579067-ba3b2996-d05c-4f84-b935-22f8f0487c1c.png)

### What you expected to happen

the endpoint pointed by the arrow should be counted in the Endpoint tab

### How to reproduce

Just follow the steps described in the question above

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Learn what is an endpoint in SkyWalking. Your question is wrong.

**Comment by hongshuai1994** [comment]
1. The endpoint is created when the span is created. Regardless of whether it is the endpoint you mentioned, as long as it is created, it should be counted in the Endpoint tab. This is no problem, right?
2. Since the endpoint is displayed in the trace, isn’t it ambiguous not to count the endpoint tab?
3. It is fine to close this discussion directly, or to say that there is a problem, but just close it without mentioning any specific problems?

**Comment by hongshuai1994** [comment]
The reason why I pay attention to whether this endpoint has statistics on the endpoint tab is because we want to add the following monitoring alarms.
The spring-cloud-gateway proxy request, the actual request is to the spring-boot service, if the spring-cloud-gateway reports an error, we need to know whether the gateway is wrong, or the proxied sping-boot service is wrong, so I modify Added core.oal and added the following indicators:
```
endpoint_exit_resp_code_abnormal_percent = from(Endpoint.*).filter(name == "SpringCloudGateway/sendRequest").percent((str->int)tag["http.status_code"] >= 400);
```
However, after using this indicator to add an alarm, there is no alarm when it should be alarmed. Therefore, to see why, I found that the above endpoint has not been counted in the endpoint tab, and I want to ask whether it should be counted? Is it because there is no statistics and there is no alarm?

**Comment by wu-sheng** [comment]
https://skywalking.apache.org/docs/main/next/en/concepts-and-designs/overview/

Endpoint. A path in a service for incoming requests, such as an HTTP URI path or a gRPC service class + method signature.

___

The reason I closed is that, you are assuming a concept based on your understanding, rather than project docs.

We can't afford to explain everything. And this is not an issue scope discussion.

**Comment by wu-sheng** [comment]
Have you even read what I posted? This is really no fun that you asked something, but you never read the reply.
I would highlight one last time, A path in a service for **incoming requests**.

**Comment by hongshuai1994** [comment]
With all due respect, just talking about the problem, all the responses to this issue are consulting and learning.
The first thing to make clear is that I have read each of your responses carefully. But I'd like to guess if you didn't read the question well. I know what endpoint means, and anyone who has a little two years of programming will know that even without any context, the word endpoint is not ambiguous. 
You only grasp the conceptual problem in the title, you may not carefully look at the content of the problem, then quickly reply. 
The core of the problem is: 
1. Obviously, the statistics in endpoint tab and endpoint field in trace are not in accordance with the conventional meaning of endpoint. So how to explain the problem that since the statistics are made, but the data are not matched ?
2. How to understand the endpoint in trace？
3. 
Of course, I appreciate your reply very much.
