### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Zeady** [apache/skywalking#10577]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Nginx Lua Agent (apache/skywalking-nginx-lua)

### What happened

In the case of high concurrency, the openresty log displays an error message indicating that the memory is insufficient and the shared content is set to 100 MB.  backend service is timed out.
error.log

tracer.lua:145: prepareForReport(): failed to push segment: no memory while logging request

### What you expected to happen

qps在1000情况下，可以正常上报数据，不影响openresty请求转发

### How to reproduce

test

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is not a proper issue report. There is nothing we could response.
