### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by why11xulei** [apache/skywalking#10573]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

my project originally used skywalking v8.2,now it upgraded to v9.3,when i query rest api like unsuccessfulservice,this problem occurred.
Elasticsearch exception [type=index_not_found_exception, reason=no such index [swnine_service_sla]]
(swnine is sw_namespace)
I wonder if switch to another index something changed
The existing indexes are as follows：swnine_records-all，swnine_zipkin_span，swnine_log，swnine_metrics-all，swnine_browser_error_log，swnine_ui_template，swnine_segment

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by think153** [comment]
hi, Have you solved the problem yet？
