### ISSUE TITLE
[Feature] support collect sql parameters when useServerPrepStmts in mysql

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#10589]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

when trace_sql_parameters is true in skywalking config and set useServerPrepStmts true in mysql，preparedstatment sql parameters can not be collected

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I am not following. I remember we have this config already.
What do I miss?

**Comment by xu1009** [comment]
useServerPrepStmt true,  jdbc will use ServerPreparedStatement instad of PreparedStatement build sql and execute, the ServerPreparedStatement overwrite some method, the mysql plugin only enahnce PreparedStatement

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-java/pull/489
