### ISSUE TITLE
[Bug] Exception while fetching data (/services) : null

### ISSUE THREAD

**Issue by chener999** [apache/skywalking#10582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

删除es索引后 重启sw 无法重建索引 只能重建部分索引  trace也无法使用   eg:Exception while fetching data (/services) : null

### What you expected to happen

如何正常使用

### How to reproduce

删除sw* 索引

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
And this kind of things is not an issue, use English to submit one on Discussion if you have to. AFAIK, this is out of maintainer's scope.
