### ISSUE TITLE
[Feature] 为什么没有登入界面

### ISSUE THREAD

**Issue by ak23173969** [apache/skywalking#10611]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

为什么没有登入界面，这样很不方便

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Why should have?
