### ISSUE TITLE
[Feature] xxl-job plugin upgrade

### ISSUE THREAD

**Issue by leon756** [apache/skywalking#10624]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In skywalking v8.7.0, the xxl-job plugin version is 2.2.0. 
And xxl-job 2.3.0 is not applicable.

### Use case

The `*JobHandlerMethodInterceptor` are not effective.

### Related issues

https://github.com/apache/skywalking/issues/9470

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you want to submit a pull request to expand the supported list, go ahead. You don't have to build an issue to track.
And what you posted is a little strange about `based on 8.7.0`. We only could accept a pull request from the latest codebase.

**Comment by leon756** [comment]
@wu-sheng I am not familiar with the latest one, and did not find where the `xxl-job plugin` placed.

**Comment by wu-sheng** [comment]
It is here, https://github.com/apache/skywalking-java/tree/main/apm-sniffer/apm-sdk-plugin/xxl-job-2.x-plugin, in a separate repository.

**Comment by leon756** [comment]
Thank you.
I found that the plugin has been updated in `skywalking-java` already.
