### ISSUE TITLE
[GsoC][BanyanDB] Add Overview page in UI

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#10634]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

## Background

SkyWalking BanyanDB is an observability database, aims to ingest, analyze and store Metrics, Tracing and Logging data.

The BanyanDB UI is a web interface provided BanyanDB server. It's developed with Vue3 and Vite3

## Objectives

The UI should have a user-friendly Overview page.
The Overview page must display a list of nodes running in a cluster.
For each node in the list, the following information must be shown:

- Node ID or name
- Uptime
- CPU usage (percentage)
- Memory usage (percentage)
- Disk usage (percentage)
- Ports(gRPC and HTTP)

The web app must automatically refresh the node data at a configurable interval to show the most recent information.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

jira: https://issues.apache.org/jira/browse/GSOC-251

**Comment by linktorahulraj** [comment]
Hello Hongtao, I am Rahul Raj, and I agree to participate in this project.

**Comment by hanahmily** [comment]
@linktorahulraj, any updates?
