### ISSUE TITLE
[Bug] ngx-skywalking-agent up data domain error

### ISSUE THREAD

**Issue by snake1817** [apache/skywalking#10656]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Nginx Lua Agent (apache/skywalking-nginx-lua)

### What happened

I added "nginx skywalking agent 0.6.0" to the openresty service in the k8s environment, and specified a domain name in "/etc/hosts". However, the "nginx skywalking agent" did not resolve the IP of the domain name as I specified.

### What you expected to happen

http://agentzh.org/misc/code/nginx/core/ngx_resolver.c.html#L357

### How to reproduce

i thionk /etc/hosts file first

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heyanlong** [comment]
@snake1817 As far as I know, nginx will not use /etc/hosts for domain name resolution, If you want to use it, maybe you can to use `dnsmasq` and to add `resolver 127.0.0.53;` to `server` block.

**Comment by snake1817** [comment]
ok i'm try do it

**Comment by wu-sheng** [comment]
Issue is only for tracking things being processed. Other questions, please move to discussion panel.
