### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by fengjianying** [apache/skywalking#10657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Can the parameter configuration "withCredentials" be made available when sending AJAX requests in the skywalking-client-js?

### Use case

In order to solve the cross-domain issue encountered when using skywalking-client-js, I introduced a gateway for forwarding. Now, the gateway forwarding requires user login information, which is implemented by carrying cookies. If "withCredentials: true" is not set, the front-end cannot carry user information, and the gateway will consider the user as not logged in, resulting in unable to perform forwarding.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No title, and nothing is about feature. 
This seems a discussion only.
