### ISSUE TITLE
[Bug] git submodule update fatal: could not get a repository handle for submodule 'skywalking-ui'

### ISSUE THREAD

**Issue by min918** [apache/skywalking#10675]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

when 
git submodule update
fatal: could not get a repository handle for submodule 'skywalking-ui'

### What you expected to happen

fatal: could not get a repository handle for submodule 'skywalking-ui'

### How to reproduce

git clone https://github.com/apache/skywalking.git
cd skywalking/
git submodule init
git submodule update
and then
fatal: could not get a repository handle for submodule 'skywalking-ui'

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Your network issue. Have nothing related to us.

**Comment by theDoc3602** [comment]
I have the same issue and I don't have any connection issues. Arrogant answer from the maintainer above.
