### ISSUE TITLE
[Feature] elasticsearch server monitoring

### ISSUE THREAD

**Issue by innerpeacez** [apache/skywalking#10681]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

SkyWalking currently does not support monitoring Elasticsearch. Elasticsearch is a popular full-text search system, and as one of the optional underlying storage options for SkyWalking, monitoring it would be very useful.

Data Flow:
Prometheus elasticsearch exporter -> OpenTelemetry Collector -> SkyWalking OTEL receiver (OTLP)

I have a few questions:

1. Should it be placed in the database menu?
2. I'm not sure how to add some tests. Could you give me some help?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
1. Yes, ElasticSearch is a database.
2. There are plenty of e2e tests for this. Take this recent PR as reference, https://github.com/apache/skywalking/pull/10655
