### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sEANzHAO622** [apache/skywalking#10703]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

sk8.1 版本 当我使用 sk agent 之后我 JAVA 的程序无法正常链接 Clickhosue

### What you expected to happen

我捕获了请求体发现其中多了一些东西
![image](https://user-images.githubusercontent.com/13655421/232948525-513ef37f-eee3-4e49-8b1f-97c1e62e8cdb.png)

这导致Clickhouse 服务器拒绝链接
![image](https://user-images.githubusercontent.com/13655421/232948604-700fef25-c58f-4a88-ba1e-e72bac2d8a8e.png)

请问有什么处理方案么

### How to reproduce

agent 版本 `apache-skywalking-apm-8.1.0`

clickhouse 客户端 

```xml
<dependency>
    <groupId>ru.yandex.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
    <version>0.3.1</version>
</dependency>
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
English is required, 8.1 is EOL for years.
