### ISSUE TITLE
[Feature] Support Jetty 11.x as the servlet container for Spring 6.x/Spring Boot 3.x

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#10707]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In https://github.com/apache/skywalking-java/pull/444, Spring 6.x support has been added while 
 Tomcat 10.x as the servlet container for Spring 6.x has been introduced in https://github.com/apache/skywalking-java/pull/286.

For Jetty, currently Spring 6.x is not supported due to the new `Jakarta` API. This feature is included in Jetty 11.x.

https://eclipse-foundation.blog/2021/03/24/eclipse-jetty-11-supports-the-big-bang/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Is there anyone going to own this?

**Comment by gglzf4** [comment]
Let me own this feature

**Comment by wu-sheng** [comment]
@xu1009 Your https://github.com/apache/skywalking-java/pull/517 only supports Jetty 11, is that working for the Tracing part as well?

**Comment by lujiajing1126** [comment]
> @xu1009 Your [apache/skywalking-java#517](https://github.com/apache/skywalking-java/pull/517) only supports Jetty 11, is that working for the Tracing part as well?

It cannot. I've run jetty-11.x-thread-pool-scenario locally.

![image](https://user-images.githubusercontent.com/2568208/236108606-f81e85fb-201e-46bf-ba8a-8f28375b45b2.png)

**Comment by lujiajing1126** [comment]
> Let me own this feature

Any update on this feature? @gglzf4

**Comment by xu1009** [comment]
> @xu1009 Your [apache/skywalking-java#517](https://github.com/apache/skywalking-java/pull/517) only supports Jetty 11, is that working for the Tracing part as well?

it just spport get jetty thread pool metric not for tracing

**Comment by gglzf4** [comment]
jetty 10&11 invalid for tracing，I am currently adapting

**Comment by wu-sheng** [comment]
We have 4 weeks lacking updates.  Is this worth to follow?

**Comment by wu-sheng** [comment]
Close as no one is following this for weeks.

**Comment by xu1009** [comment]
i can support this if no one is following

**Comment by wu-sheng** [comment]
> i can support this if no one is following

Changed the owner to you. Thanks.
