### ISSUE TITLE
Support nginx opentracing moudle or openresty lua

### ISSUE THREAD

**Issue by fyobe** [apache/skywalking#1071]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [X] Requirement
- [ ] Feature or performance improvement
___
### Requirement or improvement
- Support nginx opentracing moudle or openresty lua

**Comment by wu-sheng** [comment]
Right now, we have already supported collecting data from other agent/SDK. You can implement your own nginx SDK or plugin.

**Comment by wu-sheng** [comment]
And there is no `opentracing moudle` concept. Please read OpenTracing specification.

**Comment by wu-sheng** [comment]
If you have time to work with us(or me, btw I used to write nginx lua), I can help you on that. Ping me.

**Comment by wu-sheng** [comment]
Clear the milestone, if anyone wants to help, ping me.

**Comment by moonming** [comment]
hello, @wu-sheng , I am intersting in this feature.
nginx lua(OpenResty) can not act as grpc client now, so can I use HTTP instead of grpc to communicate with collector?
by the way, I am a newbie of skywalking, is there an agent for HTTP implementation that can refer to?
thanks.

**Comment by moonming** [comment]
inspired by https://github.com/SkyAPM/SkyAPM-php-sdk, I can use Go as an extension of Lua for grpc work.

**Comment by wu-sheng** [comment]
Right now, all agents(java, .net, nodejs, PHP) are all in gRPC :)

Right now, I think we should open HTTP in the gRPC server too. Could we talk on slack/maillist(English) ?

**Comment by JaredTan95** [comment]
> Right now, all agents(java, .net, nodejs, PHP) are all in gRPC :)
> 
> Right now, I think we should open HTTP in the gRPC server too. Could we talk on slack/maillist(English) ?

I already opened Http protocol in OAP-server for version 6.x like previous 5.x. And, I can contribute to the community soon.

**Comment by wu-sheng** [comment]
@JaredTan95  Could you push that pull request? I have begun the Nginx LUA subproject process.

**Comment by wu-sheng** [comment]
We wouldn't support opentracing, as user doesn't care about this.  We provided our native implementation.

We have finished the codes for Nginx and OpenResty, check here, https://github.com/apache/skywalking-nginx-lua
