### ISSUE TITLE
[Bug] build project error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain

### ISSUE THREAD

**Issue by mgyboom** [apache/skywalking#10727]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

According to the deployment documentation, the project failed to build successfully.

env:
jdk 11.0.19
maven 3.6.3
skywalking 9.2.0

```shel
[root@master skywalking]# ./mvnw clean package -Dmaven.test.skip
--2023-04-24 17:18:42--  https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.1.0/maven-wrapper-3.1.0.jar%0D
Resolving repo.maven.apache.org (repo.maven.apache.org)... 146.75.112.215
Connecting to repo.maven.apache.org (repo.maven.apache.org)|146.75.112.215|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 17:18:42 ERROR 404: Not Found.

Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```

### What you expected to happen

I expect the project to build successfully.

### How to reproduce

Executed according to the documentation：
https://github.com/apache/skywalking/blob/v9.2.0/docs/en/guides/How-to-build.md

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Typical network issue when use `mvnw`. This is your end issue.
