### ISSUE TITLE
[CI] Migrate from paths-filter to changed-files 

### ISSUE THREAD

**Issue by Superskyyy** [apache/skywalking#10737]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The dorny/paths-filter project we use in our CI to skip workflow steps is no longer actively maintained and @kezhenxu94 [suggested ](https://github.com/apache/skywalking/discussions/10604.) that we should replace it given its excessive warnings. Now I just found out a better alternative that can achieve the same but beyond simple filtering >>> https://github.com/tj-actions/changed-files

With this one we can save hours of wait time every week:
1. Omit unncessary CI runs within a single PR, i.e. doc polishing commits **since last successful workflow run** 
![image](https://user-images.githubusercontent.com/26076517/234744055-8be8ce08-379e-4ab9-843d-27c909da74b1.png)

2. build checkers to enforce the change of certain files (e.g. changelog.md) in some cases. 

I believe we only got two repos to refactor for now, correct me if I'm wrong @kezhenxu94 and let me know if there are other repos that would benefit from this upgrade (maybe java agent?):
- [x] OAP repo
- [ ] Python agent repo
- [ ] CLI

### Use case

Unnecessary CI workflows will no longer execute.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Added CLI to the list, though it uses getsentry/paths-filter, a forked of the GHA in problem

**Comment by Superskyyy** [comment]
This will be done before 17th, the settled date where GitHub starts to enforce node16

**Comment by kezhenxu94** [comment]
> This will be done before 18th, the settled date where GitHub starts to enforce node16.
> https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12

Do you have time to do that before 18th? I can help if needed

**Comment by Superskyyy** [comment]
> > This will be done before 18th, the settled date where GitHub starts to enforce node16.
> > [github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12)
> 
> Do you have time to do that before 18th? I can help if needed

I'm very busy this week but I'm pretty sure I can do this over weekend. I will let you know if I cannot make it in time.

**Comment by Nageshbansal** [comment]
Hey @Superskyyy @kezhenxu94 , has this issue been resolved? If not, I would like to give it a try and see if I can help.

**Comment by Superskyyy** [comment]
> Hey @Superskyyy @kezhenxu94 , has this issue been resolved? If not, I would like to give it a try and see if I can help.

Hi, the main repo is already migrated as you can see the draft PR is there. 

And this issue is a mission critical migration that we have to do very carefully, so it's not open for contribution. Please feel free to find other issues labeled with good first issue if you would like.
