### ISSUE TITLE
[Feature] Python agent support printing TID to logs

### ISSUE THREAD

**Issue by Superskyyy** [apache/skywalking#10734]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This is a simple but missing advanced feature that Java agent already supports, there is a TODO in the Python agent codebase for this. Should be very easy to implement (fewer than 10 lines of code?), so it's open for new contributors to try.

### Use case

User should be able to see output logs containing traceid, see https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/application-toolkit-logback-1.x/ 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ansuman-satapathy** [comment]
Hello! This seems like a good starting point for my open source contribution journey. Can you guide me how to solve this issue?

**Comment by Superskyyy** [comment]
> Hello! This seems like a good starting point for my open source contribution journey. Can you guide me how to solve this issue?

Hello there! Welcome to the SkyWalking community. To get started on implementing this feature, it would be the best if you could  try and understand how this feature works in our Java agent equivalent, then you should go to our Python agent implmentation of log reporter, where you will find most of the code already written to correlate logs with tracing contexts. 

As a result, you will need to write new code to use a [LoggerAdapter](https://docs.python.org/3/howto/logging-cookbook.html#context-info) to inject the current traceIDs (https://github.com/apache/skywalking-python/blob/master/skywalking/log/sw_logging.py) into the logs.

**Comment by Superskyyy** [comment]
> Thank you. I will try my best to solve this issue. I might ask some more questions in the future as I am quite new to all of this.

Cool, I will monitor this issue as you proceed.

**Comment by ansuman-satapathy** [comment]
Hello! I am getting the following error while building dependencies in maven. I think I am missing something here. Can you point me to some other resources from which I can learn about all of this?

![image](https://github.com/apache/skywalking/assets/94665724/994bb180-08d3-4daf-ae3f-61c65c41f628)

**Comment by wu-sheng** [comment]
How do you declare the version of the dependency? ${project.release.version} should be replaced by a specific released version.

**Comment by ansuman-satapathy** [comment]
Is this correct?
![image](https://github.com/apache/skywalking/assets/94665724/5ba54e4a-48b9-4126-90a9-1487eaec184c)

**Comment by wu-sheng** [comment]
I usually changed the pom.xml directly. Don't know much about setting this on IDEA UI.

**Comment by ansuman-satapathy** [comment]
Okay, I will try to learn more about this and get back to you.

**Comment by Superskyyy** [comment]
@ansuman-satapathy Updates?

**Comment by ansuman-satapathy** [comment]
> @ansuman-satapathy Updates?

Apologies for the delay. Actually I have been really busy with exams & college. But now my exams are over. So I will start doing this again. I hope you understand. Also If this issue is really important, please assign it to someone with more experience since I am really slow with it.

**Comment by Superskyyy** [comment]
> > @ansuman-satapathy Updates?
> 
> Apologies for the delay. Actually I have been really busy with exams & college. But now my exams are over. So I will start doing this again. I hope you understand. Also If this issue is really important, please assign it to someone with more experience since I am really slow with it.

Okay! Take your time, I will update here if anyone picks this up. Remember to put a note here if you decided to continue on this.

**Comment by mohitsatr** [comment]
Hi @ansuman-satapathy, are you still working on this one ?

**Comment by CodePrometheus** [comment]
@Superskyyy hi, please assign to me, I want to try it. BTW, I want to confirm whether this task allows skywalking/loggings.py to have the ability to output TIDs to logs?

**Comment by CodePrometheus** [comment]
@wu-sheng Hello Teacher Wu, please assign to me. I have implemented the python agent to print the traceId in the logs. I want to confirm whether it is the expected goal of the task. If so, I will immediately initiate a PR later.

**Comment by Superskyyy** [comment]
@CodePrometheus Hi, yes the feature you implemented sounds like on the point, please do raise the PR and I will take a look. Thanks a lot for your contribution.
