### ISSUE TITLE
[Bug] column alarm_record.alarm_message and events.message are too short

### ISSUE THREAD

**Issue by LangInteger** [apache/skywalking#10740]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I have a look at the oap server log that we recently setup and I see some errors:

- tail -n 100 ./apache-skywalking-apm-bin/logs/skywalking-oap-server.log

![aAavCCCPoh](https://user-images.githubusercontent.com/17768055/234820826-62801fb9-8891-460c-9cef-3496e860e885.jpg)

### What you expected to happen

The alarm message and event should be stored correctly

### How to reproduce

- setup the brand new apache-skywalking-apm-9.4.0 server & ui
- setup agents on your services thus they can report data to oap server
  - make your service name longer than 30 characters
  - it's something like the picture
  
![image](https://user-images.githubusercontent.com/17768055/234824888-2d8ca248-89b1-45fa-adee-784b9d949565.png)

- make your API response time longer than 1s
- the automatically triggered `service_resp_time_percentile_rule` alarm by configuration in `apache-skywalking-apm-bin/config/alarm-settings.yml` will produce alarm messages and events that cannot be stored properly 

![image](https://user-images.githubusercontent.com/17768055/234825150-045a7c4f-5c44-435d-8128-4b806ff6549a.png)

### Anything else

The autoconfigured alarm message template is of good quality and the length is acceptable while it only leaves less than 30 characters long for the service name. I think it will be better if we can make the default value longer as I can see alarm_message.id and events.id are both of length 512 😄

I think the two table are defined in classes:

- org.apache.skywalking.oap.server.core.analysis.metrics.Event
- org.apache.skywalking.oap.server.core.alarm.AlarmRecord 

Is the solution acceptable? Besides adding the length attribute to the `Column` annotation of the two fields, is there anything else needs to be done?

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
JDBC storage solution had been changed completely in 9.5.0.
What you report would happen but we wouldn't fix that as it is gone.
