### ISSUE TITLE
[Bug] log view empty problem

### ISSUE THREAD

**Issue by zhongwm** [apache/skywalking#10744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The question is how do I know if my log are collected? I'm not sure my log are reported and collected, I've set up the java-agent for a spring-boot application without error and no error appear in my agent logs dir and oap server logs dir.
 Thanks.

oap server 9.3.0
spring-boot 2.x app
java agent is of version 8.15.0

tracing view is ok
and logs have show up with correct traceId info.

### What you expected to happen

Log view should show logs instead of empty.

### How to reproduce

oap server 9.3.0
spring-boot 2.x app
java agent is of version 8.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Read docs. I don't know why you keep opening an issue.
This is not things work.
