### ISSUE TITLE
[Feature]  How do I use log view?

### ISSUE THREAD

**Issue by zhongwm** [apache/skywalking#10743]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Not clear how to use the log view in oap-server webapp, the log view is empty, I'm not sure my log are reported and collected, I set up the java-agent for a spring-boot application without error and no error appear in my agent logs dir and oap server logs dir.
It would be nice to add details on how to use the log view plus adding some details for java-agent log collect setup trouble shooting. Thanks.

### Use case

oap server 9.3.0 
spring-boot 2.x app
java agent is of version 8.15.0

tracing view is ok
and logs have show up with correct traceId info.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is not a feature.

**Comment by zhongwm** [comment]
I mean this can be a feature of the document.

**Comment by wu-sheng** [comment]
There is no such thing can or can't.
We have docs for Java agent collecting logs. You didn't read by yourself.
