### ISSUE TITLE
[Feature] Support OTLP Native Logging

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#10752]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

SkyWalking has OTLP log support through SkyWalking exporter, ref https://skywalking.apache.org/docs/main/next/en/setup/backend/log-otlp/

We should begin to consider whether we could have gRPC/HTTP native OTLP logging support as well.

### Use case

It should work similarly to the MAL engine. Various formats of logging would be transferred as the native format and pushed into the LAL engine.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
`receiver-otel` module may face some name confusing, as `enabledHandlers` and `enabledOtelRules` are actually only metrics oriented. Ref from a question, https://github.com/apache/skywalking/discussions/10747

**Comment by poo0054** [comment]
How should I configure the receiver-otel module? Isn’t there a vm by default? I want to monitor linux。

https://github.com/apache/skywalking/discussions/11259
