### ISSUE TITLE
[Feature] Support trace Grizzly webserver

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#10767]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://github.com/eclipse-ee4j/grizzly

The Grizzly NIO framework has been designed to help developers to take advantage of the Java™ NIO API,Grizzly’s goal is to help developers to build scalable and robust servers using NIO as well as offering extended framework components: Web Framework (HTTP/S), WebSocket, Comet, and more!

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you using this? This project is not updated nearly for a year.

**Comment by xu1009** [comment]
yes，today，other team use my agent，they use Grizzly web sever，and hope trace it
