### ISSUE TITLE
[Bug] ping msg will recover the property from register msg  in ServiceManagementHandler.java

### ISSUE THREAD

**Issue by lubberland** [apache/skywalking#10796]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

ServiceManagementHandler serviceReportProperties(InstanceProperties request)  and keepAlive(InstancePingPkg request)
 both use ServiceInstanceUpdate to update service_instance
but ping msg does not contain property 
so when handled keepAlive(), we lose property from serviceReportProperties()

### What you expected to happen

i do not know how to solve it

### How to reproduce

i do not know how to solve it

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
AFAIK, no it wouldn't. Instance properties are only overriding, rather than replacing.

**Comment by lubberland** [comment]
InstanceTraffic.java  entity2Storage()
```
        public void entity2Storage(final InstanceTraffic storageData, final Convert2Storage converter) {
            converter.accept(SERVICE_ID, storageData.getServiceId());
            converter.accept(NAME, storageData.getName());
            if (storageData.getProperties() != null) {
                converter.accept(PROPERTIES, GSON.toJson(storageData.getProperties()));
            } else {
                converter.accept(PROPERTIES, Const.EMPTY_STRING);
            }
            converter.accept(LAST_PING_TIME_BUCKET, storageData.getLastPingTimestamp());
            converter.accept(TIME_BUCKET, storageData.getTimeBucket());
        }
```
when ping msg,   
converter.accept(PROPERTIES, Const.EMPTY_STRING);
 i can not find properties in es  😭

**Comment by wu-sheng** [comment]
InstanceTraffic would call `combine(final Metrics metrics)` first, then flushing. Unless your storage has some issues in query, or OAP running in a improperly cluster setup.

**Comment by lubberland** [comment]
java agent sends register msg  every 5 minutes  and sends ping msg every 30 seconds

does combine() work ok for properties?

**Comment by wu-sheng** [comment]
That doesn't matter at all. You could debug codes on your own, I don't think there is black magic there.

**Comment by lubberland** [comment]
when there is no sessionCache for InstanceTraffic
1 、the service just started
2、the sessionCache was expired
then get a keepalive metrics from http interface or kafka consumer
```
private Metrics requireInitialization(Metrics metrics) {
        final Metrics cached = sessionCache.get(metrics);

        // All cached metrics, it at least had been written once.
        if (cached != null) {
            return cached;
        }

        // If the metrics do not have time bucket relative ID
        // it is treated as high dimensionality metrics.
        // Policy, always try load from the database when miss in the cache.
        if (!model.isTimeRelativeID()) {
            return null;
        }

        // When
        // (1) the time bucket of the server's latest stability status is provided
        //     1.1 the OAP has booted successfully
        //     1.2 the current dimensionality is in minute
        //     1.3 the OAP cluster is rebalanced due to scaling
        // (2) the metrics are from the time after the timeOfLatestStabilitySts
        // (3) the metrics don't exist in the cache
        // the kernel should NOT try to load it from the database.
        //
        // Notice, about condition (2),
        // for the specific minute of booted successfully, the metrics are expected to load from database when
        // it doesn't exist in the cache.
        if (timeOfLatestStabilitySts > 0 &&
            metrics.getTimeBucket() > timeOfLatestStabilitySts
            && cached == null) {
            // Return metrics as input to avoid reading from database.
            return metrics;
        }

        return null;
    }
```

requireInitialization will return metrics,  and do not load  from storage, do not call combine() ,then call  prepareBatchInsert() ,  the properties will be null

this is the pr https://github.com/apache/skywalking/pull/10841

**Comment by wu-sheng** [comment]
# Conclusion

The cluster setup us wrong. L1 to L2 aggregation is not working properly.
