### ISSUE TITLE
[Feature] Setup default `oap.storageType` as `postgresql` 

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#10809]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have `oap.storageType` in the skywalking-kubernetes helm setup. But, following the main repository, this value is absent and the default value is `H2`.
This could easily lead to new users failing to startup. Because `init` preparing + `no-init` OAP booting don't work for H2 in-memory mode, what `ini` OAP did would be gone as the container exits.

So, the better solution is, in the helm deployment, the `oap.storageType= postgresql` should be by default and automatically install a PG server.

And I am not sure whether PostgreSQL storage supports to link to an existing server and new installation for now?
I only noticed ElasticSearch relative settings, https://github.com/apache/skywalking-kubernetes#install-a-specific-version-of-skywalking-with-an-existing-elasticsearch

@kezhenxu94 @hanahmily @dashanji 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
I believe all features stated in this issue are implemented except for setting the default storage type to psql, see

https://github.com/apache/skywalking-kubernetes/blob/6df69f01882b4d58367687a661267d01e30e573c/chart/skywalking/values.yaml#L425-L441

the default storage type in Helm Chart is ES because that’s our recommended storage in production , why do we want to change it to psql now?

**Comment by kezhenxu94** [comment]
> But, following the main repository, this value is absent and the default value is `H2`.

This is not the case, we don’t even support h2 in Helm Chart, the default storage is ElasticSearch in Helm Chart

**Comment by wu-sheng** [comment]
Yes, let's make it by default.
Is this including server deployment as well?

**Comment by wu-sheng** [comment]
> > But, following the main repository, this value is absent and the default value is `H2`.
> 
> 
> 
> This is not the case, we don’t even support h2 in Helm Chart, the default storage is ElasticSearch in Helm Chart

That is strange. I had answered dozens of questions on Discussion channel due to H2 is activated and failed in booting.

**Comment by kezhenxu94** [comment]
> Yes, let's make it by default.
> Is this including server deployment as well?

Sure it includes a psql server installation

**Comment by wu-sheng** [comment]
As banyandb would become the default at the end of this year. We don't need to change this anymore.
