### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xinper** [apache/skywalking#10802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

why ui have no traceid 
![image](https://github.com/apache/skywalking/assets/27792128/d1691e66-0786-4764-a0bf-c144679a5f7d)
![image](https://github.com/apache/skywalking/assets/27792128/5b8b5280-1a59-4f74-a977-c023b6f09465)

### What you expected to happen

i dont know why have no trace id  ，i have follow the guide

### How to reproduce

how to resolve this problem ，whether the skywalking release is low

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
1. The graphql respond doens't include the trace, why this is a bug?
2. The 8.x is EOL for a year, we wouldn't do anything for that.
3. No trace ID logs are common. There are NOT all logs are in the tracing context.

**Comment by xinper** [comment]
i know this is not a bug，but i dont know why only trace id not respond，i need help or a guide /faq ，thanks！

**Comment by wu-sheng** [comment]
Discussion panel has many similar discussion already. There is nothing to FAQ.
You just naively thought all logs having relationship with tracing.

**Comment by wu-sheng** [comment]
As you said, you know this is not a big, still report one? Quite confused.
