### ISSUE TITLE
[Feature] Optimizing memory caching

### ISSUE THREAD

**Issue by WilliamShoww** [apache/skywalking#10813]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Skywalking version: 8.9.0
Server machine config: 4C + 8G
Description: I have found that during my usage, the OAPServer service tends to consume increasing amounts of memory, eventually leading to memory overflow.
I dumped the memory and analyzed it, and below are the screenshots for reference:
![image](https://github.com/apache/skywalking/assets/19343209/62c2fdad-6f9a-4601-977c-21e3d65ea773)
![image](https://github.com/apache/skywalking/assets/19343209/c16abe3b-23a5-45c3-8c83-99ae143dfc70)

### Use case

Optimizing memory caching，Preventing increasing memory usage.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> Optimizing memory caching，Preventing increasing memory usage.

This has nothing helpful. If you have anything to propose, you should take action and back to upstream about what should be changed with why and outcome.
Simply asking doesn't help.

**Comment by WilliamShoww** [comment]
> > Optimizing memory caching，Preventing increasing memory usage.
> 
> This has nothing helpful. If you have anything to propose, you should take action and back to upstream about what should be changed with why and outcome. Simply asking doesn't help.


Are you suggesting that I should submit a pull request to you?

**Comment by wu-sheng** [comment]
What do you want to do with a pull request?

**Comment by WilliamShoww** [comment]
> 

I don't want to do anything, I just feed back the problems I encountered to you, I hope your project will get better and better

**Comment by wu-sheng** [comment]
There is nothing we can do from this report. That is what I can say for now.
We don't have the magic to reduce memory costs.

**Comment by wu-sheng** [comment]
Only anomaly I can see is that, your alarming data seems extremely large, which should not happen by default.
Maybe you have large scale of endpoint candidates and you set alarm for all endpoints somehow.

<img width="825" alt="image" src="https://github.com/apache/skywalking/assets/5441976/9f7df6b1-292a-44f3-b865-c0329b86bb7d">

BTW, 8G means nothing for a large traffic env monitoring, and 8.9 is EOF for nearly 1 year by the upstream team.

Anyway, I would be OUT from here. As diagnosing your env is your responsibility, we shouldn't and can't do it from here.

**Comment by WilliamShoww** [comment]
> 

> Only anomaly I can see is that, your alarming data seems extremely large, which should not happen by default. Maybe you have large scale of endpoint candidates and you set alarm for all endpoints somehow.
> 
> <img alt="image" width="825" src="https://user-images.githubusercontent.com/5441976/238603286-9f7df6b1-292a-44f3-b865-c0329b86bb7d.png">
> BTW, 8G means nothing for a large traffic env monitoring, and 8.9 is EOF for nearly 1 year by the upstream team.
> 
> Anyway, I would be OUT from here. As diagnosing your env is your responsibility, we shouldn't and can't do it from here.

Yes, We monitor latency across all interfaces

**Comment by wu-sheng** [comment]
This is not about monitoring, this is about alerting rules. If so, there is nothing we can do, that is expected.

**Comment by WilliamShoww** [comment]
> 

alerting rules not many, not 10 items

**Comment by wu-sheng** [comment]
It is not about the rule itself. Once you set rules for endpoints, then the number of endpoints would cause this kind of OOM easily, especially since most users' don't group the endpoint in a reasonable size.
I have provided as much as I could. If you can't understand, I am afraid you have to read codes and understand how the alerting core works.
