### ISSUE TITLE
[Feature] skywalking-java support to decrypt password of kafka with SASL_SSL enabled.

### ISSUE THREAD

**Issue by GuiSong01** [apache/skywalking#10815]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When skywalking-java agent connects to a kafka cluster with SASL_SSL enabled, we need to config a plaintext paasword in agent.config of skywalking-java agent,there is a risk of password leakage. So, we need to config a encrypted password,skywalking-java support to decrypt password of kafka with SASL_SSL enabled.

### Use case

1.Skywalking-java support to decrypt password of kafka with SASL_SSL enabled.
2.The decryption interface is open to users by java SPI, and user can customize decryption policies so that the decryption policies does not have to commit into skywalking community.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> 1.Skywalking-java support to decrypt password of kafka with SASL_SSL enabled.

I am good with this

> 2.The decryption interface is open to users by java SPI, and user can customize decryption policies so that the decryption policies does not have to commit into skywalking community.

This may not be accepted. Interacting with user codes for features in the agent core would be very tricky. I would highly recommend don't do this.
The codes of the report plugin should be able to load any classes in the jars placed in the `/plugins`  folder. It is better if you could define a class name for an extension if that is really needed.

**Comment by GuiSong01** [comment]
> This may not be accepted. Interacting with user codes for features in the agent core would be very tricky. I would highly recommend don't do this.
The codes of the report plugin should be able to load any classes in the jars placed in the /plugins folder. It is better if you could define a class name for an extension if that is really needed.
Yes, I can define a class to implement decryption and place in the `/plugins`,but I need `kafka-reporter-plugin-xxx.jar` to call it,so I need to commit a code of java interface into `kafka-reporter-plugin-xxx.jar`,and provide default implemention that does nothing.

**Comment by GuiSong01** [comment]
> You don't need a default implementation, you just need to try to do `Class.forName` and execute the relative codes when class is found.

Good idea！
