### ISSUE TITLE
[Bug]  biz application does not reconnect to the oap server after oap reset.

### ISSUE THREAD

**Issue by loveGit99** [apache/skywalking#10819]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

- Running Environment:
      - skywalking-oap  8.7 
      -  application  connect to  oap server by  Nginx

-  issue description:
   1.   application connected to oap server
   2.   oap server reset 
   3.   application  skywaling-agent throw Error:     org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException:  UNAVAILABLE:   Network closed for unknown reason
   4.  application 's  log  show  TID:   Ignored_trace
   5.  reset application ,  the TID is normal

-  
   In order to reduce the impact on the application after  add or remove oap server nodes ,  so  we  set 
 a  nginx proxy address to SW_AGENT_COLLECTOR_BACKEND_SERVICES  .     
   
   When I  add some oap server nodes ,  sometimes,  I  can't  reset  application system,  but the application system doesn't known the new oap server nodes. 

    So,  I  don't  think  It is not a good way to set  oap servers for SW_AGENT_COLLECTOR_BACKEND_SERVICES directly.  

     If  the proxy setting is the cause of the issue,  how to solve it ?  

  Thanks

### What you expected to happen

 reconnect to  oap server cluster after oap server cluster reset.

### How to reproduce

   1.   application connected to oap server
   2.   oap server reset 
   3.   application  skywaling-agent throw Error:     org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException:  UNAVAILABLE:   Network closed for unknown reason
   4.  application 's  log  show  TID:   Ignored_trace
   5.  reset application ,  the TID is normal

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
The whole 8.7 is EOL. We don't respond for that version.
Always recommend latest versions of OAP and agents.
