### ISSUE TITLE
[skywalking-go] Custom configuration files do not take effect during hybrid compilation

### ISSUE THREAD

**Issue by ethan256** [apache/skywalking#10821]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Custom configuration files do not take effect in `skywalking-go`

### What you expected to happen

i want update `service_name:  test-service` and `sampler: 0.1` by config file.

### How to reproduce

write unittest as follow:

```
func TestLoadConfig(t *testing.T) {
	err := LoadConfig("./testdata/agent.yaml")
	assert.NoError(t, err)
	conf := GetConfig()
	assert.NotNil(t, conf)
	expected := StringValue{EnvKey: "SW_AGENT_SAMPLE", Default: "0.1"}
	assert.Equal(t, expected, conf.Agent.Sampler)
}
```

testdata/agent.yaml:

```
agent:
  service_name: test-service
  sampler: 0.1
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to fix this?

**Comment by lujiajing1126** [comment]
Completed via https://github.com/apache/skywalking-go/pull/40
