### ISSUE TITLE
[BanyanDB] Implement unify persistence data storage

### ISSUE THREAD

**Issue by HHoflittlefish777** [apache/skywalking#10839]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, [BanyanDB](https://github.com/apache/skywalking-banyandb) uses [Badger](https://github.com/dgraph-io/badger) for persistence storage, which has the following drawbacks. 

- Badger uses the mmap mode for storage. The mmap mode has some problems refer to https://db.cs.cmu.edu/mmap-cidr2022/. 
- The data organization mode of Badger is not suitable for BanyanDB. 
- Badger is designed for SSD optimization and has a relatively small scope of application. 

Therefore, to solve these problem, we can implement  unify persistence data storage.And we can benefit from it:

- Better data format for storage and query in APM scenarios. 
- Adapt to various hardware and s3 interfaces.
- Better IO mode, such as io-uring.
- Improve compaction performance and reduce data query latency.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I aligned the milestone between this and PR for 0.6

**Comment by tisonkun** [comment]
@HHoflittlefish777 how do you modularize the requirements of local storage for BanyanDB?

If Badger as an unmaintained solution with its mmap issue, a near drop-in solution can be trying to adopt [pebble](https://github.com/cockroachdb/pebble) which shares a similar design. Making a local-fs from scratch is a bit confusing for me >_<

**Comment by wu-sheng** [comment]
We have our design for local file structure, to improve performance. Nothing about badger  status.

**Comment by tisonkun** [comment]
@wu-sheng I noticed the design doc now - https://github.com/apache/skywalking-banyandb/pull/275

**Comment by HHoflittlefish777** [comment]
> @HHoflittlefish777 how do you modularize the requirements of local storage for BanyanDB?
> 
> If Badger as an unmaintained solution with its mmap issue, a near drop-in solution can be trying to adopt [pebble](https://github.com/cockroachdb/pebble) which shares a similar design. Making a local-fs from scratch is a bit confusing for me >_<

The goal is to replace the entire Badger, and BanyanDB will implement its own storage engine to adapt to the time serial data. The goals of this unified file system are as follows:

- Mask differences between different operating systems
- Mask the differences between different IOs, such as synchronous and asynchronous IOs
- Mask the difference between local and remote storage

Therefore，not only local storage : )
