### ISSUE TITLE
Fix format in mal and backend-vm-monitoring documents 

### ISSUE THREAD

**Issue by smartboy37597** [apache/skywalking#10836]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

When reading the document, I found some formatting and content problems.

### What you expected to happen

In the backend-vm-monitor.md document, there are some obvious formatting problems.
There is one area in the mal.md document that could be refined and contextually appropriate.

### How to reproduce

Open and read: 
https://skywalking.apache.org/docs/main/next/en/setup/backend/backend-vm-monitoring/
https://skywalking.apache.org/docs/main/next/en/concepts-and-designs/mal/

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
That's great, please go ahead and fix them. Usually, smaller stuff like fixing formatting in limited number of docs is not required to present as separate issues unless you are not sure how to improve them.

> Note - This is one of this year's ospp students (candidates)

**Comment by wu-sheng** [comment]
Please fix all through https://github.com/apache/skywalking/pull/10833

**Comment by Superskyyy** [comment]
> Please fix all through #10833

These two issue/prs are from two different individuals?

**Comment by wu-sheng** [comment]
OK, so many typo fixes.
