### ISSUE TITLE
Error opening zip file or JAR manifest missing

### ISSUE THREAD

**Issue by syllvin** [apache/skywalking#10868]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

 last line of my dockerfile like this: 
 ENTRYPOINT ["java","-javaagent:/agent/skywalking-agent.jar","-Dskywalking.agent.service_name=syllvin-mq","-Duser.timezone=GMT+08","-jar","app.jar"]
 
 and the result:
 Error opening zip file or JAR manifest missing : /agent/skywalking-agent.jar
 Error occurred during initialization of VM
 agent library failed to init: instrument

### What you expected to happen

Successful execution

### How to reproduce

make a dockerfile as above

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is not SkyWalking thing.
