### ISSUE TITLE
[Feature] Support access the tracer context in the spring gateway filter

### ISSUE THREAD

**Issue by darknesstm** [apache/skywalking#10862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In some cases, we need to determine the tenant ID of the current request based on certain information (such as domain name) in Spring Gateway. Usually, we customize a filter to implement this logic. However, after obtaining this information in the filter, due to the framework of WebFlux, it is currently impossible to directly pass it to downstream nodes through the context of SkyWalking. 

Therefore, relevant tool methods are needed to process the snapshot information stored in the ServerWebExchange, so that it can be automatically injected into the context of the subsequent link through the header information "sw8-correlation".

### Use case

```java
public class  TenantHandler implements GlobalFilter {

    // ...

    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        WebFluxSkyWalkingTraceContext.putCorrelation(exchange, "TenantId", getTenantIdByDomain(exchange.getRequest()));
        // ...
    }
}
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Hi, I knew what is the use case. What I don't follow up on is why the code changes are so huge. Many new things are added.
Here are two things at least should be done
1. We need a proposal to explain what exactly you changed.
2. We need a plugin test to verify this propagation of collaboration context is working. A -> Gateway -> B for example, you should build a collaboration context in A, and check that in B, also tag it in the test. Then the plugin test tool could verify it.

**Comment by darknesstm** [comment]
> 

In the latest commit, I have added plugin test cases and passed it in local.

then, so where should I write this proposal?

**Comment by wu-sheng** [comment]
Remove from next release, as we can't verify CI due to the contributor account issue.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-java/pull/539 has been merged.
