### ISSUE TITLE
[Feature] Add the maven plugin maven-compiler-plugin to specify the build version

### ISSUE THREAD

**Issue by weihubeats** [apache/skywalking#10875]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The maven.compiler.source property defined in the properties of the skywalking pom does not seem to be used, we can add the maven-compiler-plugin plugin to specify the compiled version to avoid compilers such as idea reading the default compiled version

![image](https://github.com/apache/skywalking/assets/42484192/37533b35-2c07-4f28-bd16-52f05ff121c5)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
What is the issue? I am not following the case.

**Comment by weihubeats** [comment]
Some of our code using jdk 11 syntax, for some local installation of jdk8 and jdk11 people, the project if you do not specify the use of 11 to compile, then idea may use the default jdk8 to compile thus leading to compile errors, if you want to solve this problem may need to manually change the idea in the compiled jdk version, due to many modules so the need to change the module is very much, so we can not consider the introduction of maven-compiler-plugin this plug-in to specify the compiled jdk version, there will be no such problems

Translated with www.DeepL.com/Translator (free version)

**Comment by wu-sheng** [comment]
@kezhenxu94 Don't we have this?

**Comment by kezhenxu94** [comment]
> The maven.compiler.source property defined in the properties of the skywalking pom does not seem to be used,

This is a convention naming in maven and this property will be automatically picked up by the maven-compiler-plugin.

> we can add the maven-compiler-plugin plugin to specify the compiled version to avoid compilers such as idea reading the default compiled version

As said above, you don't need to explicitly add maven-compiler-plugin, it's there, and the property name `maven.compiler.source` is automatically picked by it the plugin.

I remember IntelliJ also automatically change the JDK version based on the property `maven.compiler.source` so you actually don't need to do anything, it just works.

**Comment by weihubeats** [comment]
The source code I downloaded was compiled with 1.8 by default, and when I added `maven-compiler-plugin` it updated to 11 for me. `maven.compiler.sources` didn't seem to work

**Comment by kezhenxu94** [comment]
> > The source code I downloaded was compiled with 1.8 by default, and when I added `maven-compiler-plugin` it updated to 11 for me. `maven.compiler.sources` didn't seem to work
> 
> Any document from JetBrains describing the relationship between maven-compiler-plugin and IDEA configuration? I think they are different concepts

They are different concept but IntelliJ respects the maven compiler plugin 's settings of Java version, out of the box,

**Comment by wu-sheng** [comment]
Something wrong with your apache parent pom? I think this is there.

**Comment by weihubeats** [comment]
Skywalking parent uses the project's default
```
<parent>
        <groupId>org.apache</groupId>
        <artifactId>apache</artifactId>
        <version>29</version>
        <relativePath />
    </parent>
```
I did not change the source code, just added `maven-compiler-plugin`,Maven setting does not see a configuration parent

**Comment by kezhenxu94** [comment]
@weihubeats if you want to add the maven-compiler-plugin, I'm OK to accept that change if it fixes this kind of issue, and it doesn't no harm.

**Comment by weihubeats** [comment]
Ok, I will fix it
