### ISSUE TITLE
[Feature] Go auto-instrument agent support go-redis

### ISSUE THREAD

**Issue by jiekun** [apache/skywalking#10879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[go-redis](https://github.com/redis/go-redis) is a Golang Redis client for Redis Server and Redis Cluster, and it's widely used.

Since we have [skywalking-go](https://github.com/apache/skywalking-go) now, it might be good to cover this Redis client. There is no Redis client available on the [Supported Libraries](https://skywalking.apache.org/docs/skywalking-go/next/en/agent/support-plugins/#supported-libraries) now. 

Before start working on it, **I would like to have some supporters for this proposal.**

### Use case

Addressed in the description.

### Related issues

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

I think it's a good first issue for new community developers. So I would like to try it if we have supporters.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> I would like to have some sponsors for this proposal.

Could you explain what do you mean `sponsors`?

**Comment by jiekun** [comment]
> Could you explain what do you mean `sponsors`?

Sorry, it should be `supporter` here :) . I'm opening this issue:
- to see if someone has a **similar idea**.
- to avoid duplicate development efforts.
- to confirm with the community (our maintainers/reviewers) to see if it's worth developing it.

**Comment by wu-sheng** [comment]
There is no one working on this, as the project is super new. Plugins are open to add. And Redis plugin is good to have, because we already have Redis client lib supported in various other language agent implementations.

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-go/pull/55.

**Comment by jiekun** [comment]
> @jiekun Are you still planning to write more blogs about this?

Yes I have the following plan:
1. a blog post.
2. kafka / es client support.

I'm afk since 06.08, back to work on tuedsay.
