### ISSUE TITLE
[BanyanDB]  Improve Granularity of Index in Measure: Level up from Data Point to Series

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#10871]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Problem

Currently, the granularity of the index in `Measure` is at the data point level. This may lead to suboptimal performance in certain use cases, especially when dealing with large volumes of time series data(service_id in instances relevant metrics)

### Solution

We should enhance the granularity of the index in BanyanDB by leveling it up to each series. This change could improve query performance and storage efficiency.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
So, you are going to change all indices in Measure to the new index type?

**Comment by hanahmily** [comment]
> So, you are going to change all indices in Measure to the new index type?

Exactly. When it comes to measuring metrics, the secondary index is effective in grouping and aggregating data not just from our SkyWalking's reality, but also from other time series databases that have faced similar scenarios. Thus, a series-level index is more fitting than a datapoint-level index.
