### ISSUE TITLE
[Feature] use WebSphere Liberty develop skywalking agent plugin to compatible WebSphere traditional edition

### ISSUE THREAD

**Issue by weixiang1862** [apache/skywalking#10887]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

There are many traditional industries who are using websphere traditional edition are urgent to integrated there system to skywalking monitoring. However websphere  traditional edition is a commercial product，we can not hijack it due to ASF IP policy。

Recently，I found that ibm open source websphere core code on github under [open liberty](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java) and provider [WebSphere Liberty denpendency](https://mvnrepository.com/artifact/com.ibm.websphere.appserver.spi/com.ibm.websphere.appserver.spi.servlet) under Eclipse Public License 2.0.

here is some docs about different between websphere-liberty and traditional-websphere: 
- https://www.ibm.com/blog/websphere-liberty-different-from-traditional-websphere/

### Use case

The code in [open liberty](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java) repository is enough for us to build a skywalking java agent for tracing. Do you think we should hava a try? Does EPL2.0 break ASF IP policy？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
EPLv2 works for us as a plugin.

**Comment by wu-sheng** [comment]
Usually, it is in the `apm-sdk-plugin`, unless your codes could potentially have side-effect for other cases.
If your codes are only targeting `com.ibm.websphere.*`, it should be fine to be placed in default plugin folder.
