### ISSUE TITLE
[Feature] add sumLabeled @MeterFunction for mal sum downsampling

### ISSUE THREAD

**Issue by weixiang1862** [apache/skywalking#10885]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This is my scenario：
1. otel-collector scrape gateway metric endpoint in every 15S
2. skywalking mal engine calculate every http code count increasement in this 15s and downsampling by sum method
3. skywalking will persist this metric in meter_sum_xxxxxxxx table in value meter mode
```
metricsRules:
  - name: http_200_code_count
    exp: http_server_requests_seconds_count.tagEqual('status', '200').sum(['application']).increase('PT15S').service(['application'], Layer.GENERAL).downsampling(SUM)
  - name: http_404_code_count
    exp: http_server_requests_seconds_count.tagEqual('status', '404').sum(['application']).increase('PT15S').service(['application'], Layer.GENERAL).downsampling(SUM)
  ...
  ...
  ...
```

### Use case

I want to change my mal like this, the sum aggregate method use 'application' and 'status' as aggregate-by params. If skywalking meter system support sumlabeled function, this metric will be persisted in meter_sumlabeled_xxxxxxxx table in datatable meter mode. 

The  sumlabeled function is easy to extend under skywalking meter system excellent architecture design, and it can bring us benefits in query efficiency and storage economy.

```
metricsRules:
  - name: http_code_count
    exp: http_server_requests_seconds_count.sum(['application','status']).increase('PT15S').service(['application'], Layer.GENERAL).downsampling(SUM)
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by weixiang1862** [comment]
I notice that someone already submit this feature #10632 , sorry about this.
Am I using mal in wrong way and are there any ready-made mal function can support my scenario？

**Comment by wu-sheng** [comment]
@BFergerson was adding that, but we don't know what is the use case. Then, this should be OK to add for now.

**Comment by BFergerson** [comment]
@wu-sheng, you were actually right. It turned out I didn't need it. Glad someone found a use though.

**Comment by wu-sheng** [comment]
@weixiang1862 Are you going to open the pull request soon? Or should I move this to discussion only

**Comment by weixiang1862** [comment]
@wu-sheng yes, I will submit the pull request today. This is my first time participating in a open source project, thank you for the opportunity.
