### ISSUE TITLE
[Feature] [Python] Add Neo4j plugin

### ISSUE THREAD

**Issue by Jedore** [apache/skywalking#10898]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add Neo4j plugin to monitor the communication between [Neo4j python driver](https://github.com/neo4j/neo4j-python-driver) and Neo4j server.

### Use case

Yeah, our all projects are in Skywalking tracing. And our python project is migrating from HuaweiCloud GES to Neo4j, so we want to trace neo4j driver too.

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
So, this is a proposal for neo4j plugin in Java, right?

**Comment by Jedore** [comment]
In neo4j plugin, will collect multi neo4j version data, from `4.4.*` to `5.*.*`. 
So should I test every version case by adding multi `provider/consumer` for every version in `tests/plugin/data/sw_neo4j/docker-compose.yml`? Or there is any better solution ?
Sorry that I can't find multi version test case in `tests` module. And thanks a lot! 👨‍💻

**Comment by wu-sheng** [comment]
Have you read all the doc? https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/plugin-test/#test-case-configuration-files `support-version.list` is designed for multiple versions testing. Otherwise, how do we make things work today?

Especially these in the doc

> In some cases, the dependency service (usually a third-party server like the SolrJ server) is required to keep the same version as the client lib version, which is defined as ${test.framework.version} in pom. You may use ${CASE_SERVER_IMAGE_VERSION} as the version number, which will be changed in the test for each version.

**Comment by Jedore** [comment]
Thanks for your quick reply. 👍 
Now I understand more about the test framework.
