### ISSUE TITLE
[Feature] [Cluster] Node roles and discovery

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#10895]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

BanyanDB proposes to implement several roles for nodes. These roles include the following:

- Meta nodes that serve as coordinators and maintain the metadata about the cluster.
- Liaison nodes receive client requests and forward them to the appropriate data or query nodes for processing.
- Data nodes are responsible for storing the actual data of the database. They receive requests from liaison or query nodes and perform the necessary operations to modify or retrieve data
- Query nodes are responsible for processing queries, aggregating, and returning the results to the user. By separating query nodes from data nodes, the database can handle more queries without affecting data storage or retrieval performance

Nodes can discover each other through an embedded `etcd` instance provided by meta nodes. This `etcd` instance stores metadata about the cluster and enables nodes to communicate. By implementing these roles and discovery, BanyanDB is expected to transform into a distributed database with multiple nodes, rather than a single-node database.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HHoflittlefish777** [comment]
@hanahmily Is BanyanDB  realize Disaggregated Storage and Compute Architecture in the 0.5.0?

**Comment by hanahmily** [comment]
> @hanahmily Is BanyanDB  realize Disaggregated Storage and Compute Architecture in the 0.5.0?

No. We won't. 0.5.0 concentrates on the distributed system.

**Comment by HHoflittlefish777** [comment]
That means Load balancing, data replication and other feature about distributed system will realize in 0.5.0?

**Comment by hanahmily** [comment]
Most of them are included in 0.5.0. The full task list is at
https://github.com/apache/skywalking/milestone/179.

**Comment by HHoflittlefish777** [comment]
I would like to finish it, and should I finish https://github.com/apache/skywalking/issues/10907 first, which is base of it for we should use remote queue to send request?
