### ISSUE TITLE
[Feature] Adopt new MQE to replace the old static configuration on UI configuration.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#10914]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have a new key feature, [MQE](https://skywalking.apache.org/docs/main/next/en/api/metrics-query-expression/) has been added recently(9.5.0 milestone). It is a more flexible way to set metrics and similar to PromQL implementation.

@wankai123 had finished on replacement through #10913 

- [x] General Service
   - [x] Services (https://github.com/apache/skywalking/pull/10913)
   - [x] Virtual Database (https://github.com/apache/skywalking/pull/10913)
   - [x] Virtual Cache (https://github.com/apache/skywalking/pull/11098) https://github.com/apache/skywalking/pull/11151
   - [x] Virtual MQ (https://github.com/apache/skywalking/pull/11127)
- [x] Service Mesh @kezhenxu94 (https://github.com/apache/skywalking/pull/11161)
- [ ] Functions @smartboy37597
- [x] K8s @smartboy37597 https://github.com/apache/skywalking/issues/10914
- [x] Infra
  - [x] Linux (https://github.com/apache/skywalking/pull/11127)
  - [x] Windows (https://github.com/apache/skywalking/pull/11203)
- [x] AWS
  - [x] AWS-DynamoDB (https://github.com/apache/skywalking/pull/11093/)
  - [x] AWS-EKS, AWS-GATEWAY, AWS-S3 https://github.com/apache/skywalking/pull/11148
- [x] Browser @smartboy37597 https://github.com/apache/skywalking/pull/11220
- [x] Gateway https://github.com/apache/skywalking/pull/11148
- [x] Database (https://github.com/apache/skywalking/pull/11093/)
- [x] MQ @innerpeacez 
  - [x] https://github.com/apache/skywalking/pull/11184

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by smartboy37597** [comment]
Hello, I am interested in this feature and would like to complete the MQE replacement of the **Virtual MQ** and **Infra**.

**Comment by wankai123** [comment]
> Hello, I am interested in this feature and would like to complete the MQE replacement of the **Virtual MQ** and **Infra**.

Assigned, thank you.

**Comment by wu-sheng** [comment]
@Fine0830 We will need topology widgets(service topo, instance and endpoint dep) should support expression as well. By that, we should immigrate the configuration, and forward to removing the old configuration style. For dev stage, we need to support both ways like other widgets.

**Comment by wu-sheng** [comment]
Once we have https://github.com/apache/skywalking-booster-ui/pull/312 merged, all dashboards could be replaced by MQE based settings.

**Comment by wu-sheng** [comment]
So far, @smartboy37597 is finishing most of the replacement, but we may not finish all due to OpenFunction deployment.

**Comment by wu-sheng** [comment]
The OpenFuncion is going to be removed due to a lack of maintenance. After that, this is done.
