### ISSUE TITLE
[Feature] [BanyanDB] Remove ID Tag type

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#10945]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

ID-typed tags are no longer used by OAP. We can safely remove this in the related repos, including

- BanyanDB Java Client (planned in the upcoming v0.4.0)
- BanyanDB

**NOTE: Since BanyanDB is still in the stage of active development, backwards compatibility cannot be guaranteed.**

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I think we could have this in 0.4.0 client. No need for 0.4.0-rc2 anymore, right?

**Comment by lujiajing1126** [comment]
> I think we could have this in 0.4.0 client. No need for 0.4.0-rc2 anymore, right?

Yes. I think so. OAP is not using ID now.
