### ISSUE TITLE
Add mod revision check to write requests

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#10956]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

To ensure data integrity and consistency in BanyanDB, we must add a revision check for each write request. The revision check should be based on the `mod_revision` field of the resource instead of the `create_revision` field. This will ensure that the server validates the request based on the latest modification state of the resource. Additionally, when the validation fails, the client side should clear the metadata cache and reload the newest resource information to prevent future write request failures.

### Use Case

To implement this feature, we need to perform the following steps:

#### API 

- [ ]  **Update schema creation API**: Modify the schema creation API to return the `mod_revision` of the newly created resource in the response. This will allow the client side to store the revision information in the metadata cache after creating a new schema.
- [ ]  **Update schema updating API**: Modify the schema updating API to return the updated `mod_revision` of the affected resource in the response. This will allow the client side to update the metadata cache with the latest revision information after updating an existing schema.
- [ ] **Update API to include revision field**: Modify the existing API to add a new mod_revision field in the write request payload. This will allow clients to send the revision information along with the write request.

#### Server Side

- [ ] Create a server-side Pull Request (PR) that adds the logic to validate the `resource_mod_revision` field in the incoming write requests. The server should only accept the request if the provided `resource_mod_revision` matches the latest revision of the resource.

#### Client Side

- [ ]  **Store mod_revision in metadata cache**: Update the client-side logic to store the `mod_revision` value returned by the schema creation, updating, and getting API in the metadata cache. This will ensure that the client side has the latest revision information for future write requests.
- [ ]  **Handle cache updates on client-side**: Update the client-side logic to clear the metadata cache and reload the latest resource information when a write request is rejected due to a revision mismatch. This will ensure the client-side cache stays in sync with the server-side state.

#### Merging Procedure

1.  **Create new Docker image with server-side changes**: Once the server-side PR has been reviewed and tested, create a new Docker image that includes these changes by the CI job. This will facilitate integration testing of the feature with client-side and OAP changes.
2.  **Integrate client-side and OAP changes**: With the new Docker image available, merge the client-side, and OAP changes that utilize the updated API and revision checks. Ensure that the feature works as expected during the integration testing.
3.  **Merge server-side PR**: After successful integration testing, merge the server-side PR to make the revision check feature available in the main codebase.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
> If considering implement multi-version query future, mod_revision can be stored in resource data

As we previously discussed, the mod_revision will be stored along with the raw data. If I remember correctly, the number is an int64. You can simply append it to the original byte slice.

**Comment by wu-sheng** [comment]
For now, please respond to the error code as `expired revision` and the Java client could update the latest table structure automatically. Meanwhile, the data of the bulk with expired revision is expected to be lost directly.

For later, we could consider a timer/watcher to sync the latest structures of all tables with revisions to reduce the data lost possibilities. But, that is out of this issue scope.
