### ISSUE TITLE
[Bug] Showcase error

### ISSUE THREAD

**Issue by agardnerIT** [apache/skywalking#10987]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Showcase (apache/skywalking-showcase)

### What happened

Error: could not download oci://ghcr.io/apache/skywalking-kubernetes/skywalking-helm: manifest does not contain a layer with mediatype application/tar+gzip
make[1]: *** [Makefile:170: deploy] Error 1

### What you expected to happen

`helm install` works correctly

### How to reproduce

```
git clone https://github.com/apache/skywalking-showcase.git
cd skywalking-showcase
HELM_EXPERIMENTAL_OCI=1 make deploy.kubernetes
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Looks like you are using a very old Helm cli? Can you try upgrading to a newer one?

**Comment by agardnerIT** [comment]
Perfect. That solved it. Thank you!
