### ISSUE TITLE
[Bug] there's an endless loop in ElasticSearchScroller

### ISSUE THREAD

**Issue by XingyuFu** [apache/skywalking#10998]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I have a question for ElasticSearchScroller.
there's a while(true) in the code.
![6CE17380-C30C-4640-A83A-09C2F9C2850F](https://github.com/apache/skywalking/assets/19774938/261e779a-59d3-4d86-a6ca-dc97bc8a3551)
the total field in the response represents the total number of documents that match my search query.
if the batchSize is 5000, and the queryMaxSize is 10000.
And if we have 5100 documents for the query, so the total is 5100, it is bigger than search.getSize() and smaller than queryMaxSize.
And then we can't break from the while cycle.

### What you expected to happen

skywalking will query ES in an endless loop.

### How to reproduce

fill enough size data in ES, bigger than batch size and smaller than max size.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@kezhenxu94 You have a new implementation, could you check whether it is fixed?
