### ISSUE TITLE
[Feature] Support for Aerospike Java client Plugin

### ISSUE THREAD

**Issue by dd1k** [apache/skywalking#10992]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://github.com/aerospike/aerospike-server
Aerospike is a distributed, scalable NoSQL database.
java client address: https://github.com/aerospike/aerospike-client-java
Our  project is heavily used, and the relevant functions have been working properly online for one or two years.
So , I want to try implementing Aerospike Java Client  agent plugin.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to submit a pull request soon? Usually, you don't need a permission to submit a new plugin.
