### ISSUE TITLE
[Feature] skywalking-go agent support gozero microservices framework Plugin

### ISSUE THREAD

**Issue by guijunchen** [apache/skywalking#10993]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

goZero：A cloud-native Go microservices framework with cli tool for productivity.
github address: https://github.com/zeromicro/go-zero
docs address: https://go-zero.dev/en/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We only accept issues if you try to contribute plugin.
Too many plugins in various languages, it would burn the issue list.
Feel free to contribute when you are ready.
