### ISSUE TITLE
[Bug] skywalking-php Unable to capture connect information by using variables to connect Redis

### ISSUE THREAD

**Issue by zheyu1995** [apache/skywalking#10996]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

Code for using variables
```
<?php
echo '111';
{
    try {
      $client = new Redis();
      $host = "127.0.0.1";
      $port = "6379";
      $client->connect($host, $port, 1);
      $client->set('foo', '1111');
    } catch (RedisException $e) {
    }
}
echo "ok";
```
![image](https://github.com/apache/skywalking/assets/135955826/1047da22-48f9-4865-8091-d85b8479f6f4)

Code for Unused Variables
```
<?php

echo '111';

{
        $client = new Redis();
        $client->connect("127.0.0.1", 6379, 1);
        $client->set('foo', '1111');
}

echo "ok";
```
![image](https://github.com/apache/skywalking/assets/135955826/c103c8f9-5df4-44ba-805c-d2a54d681958)

### What you expected to happen

![image](https://github.com/apache/skywalking/assets/135955826/1e12210c-264f-41c9-bb01-790ee610d796)

### How to reproduce

```
<?php
echo '111';
{
    try {
      $client = new Redis();
      $host = "127.0.0.1";
      $port = "6379";
      $client->connect($host, $port, 1);
      $client->set('foo', '1111');
    } catch (RedisException $e) {
    }
}
echo "ok";
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment]
Because the $port is string, skywalking agent except it to int failed, I will adapt this case.
