### ISSUE TITLE
[Bug] helm install 4.4.0 version of the program to run after the terminal exit

### ISSUE THREAD

**Issue by liuxin638507** [apache/skywalking#10994]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Helm Chart (apache/skywalking-kubernetes)

### What happened

sywalking helm install 4.3.0 The naming line returns results quickly, but the terminal does not exit until all programs are running for version 4.4.0

### What you expected to happen

helm install skywalking  ./ -n skywalking -f values.yaml ，return the result  Too slow

Even with upgrade, it takes almost one minute for the terminal to return the result
![image](https://github.com/apache/skywalking/assets/32058132/0fd3c2e2-ccdc-4b92-ae6a-8605faf52a90)

### How to reproduce

helm 4.4.0 version return the result  Too slow

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
I don't see why it's a problem, OAP init job needs to be executed, which must take some time

**Comment by liuxin638507** [comment]
OAP init job takes time, but the service itself takes time to start, and should not be in the console does not return the result, I can not tell whether the service is normal return, and nothing has changed to perform the upgrade, still take a minute or so to occupy the console

**Comment by liuxin638507** [comment]
> I don't see why it's a problem, OAP init job needs to be executed, which must take some time

OAP init job takes time, but the service itself takes time to start, and should not be in the console does not return the result, I can not tell whether the service is normal return, and nothing has changed to perform the upgrade, still take a minute or so to occupy the console
