### ISSUE TITLE
SkyWalking agent version 8.8.0 is unable to generate TIDs (trace IDs) for RocketMQ 5.0

### ISSUE THREAD

**Issue by JackSlamDunk** [apache/skywalking#11007]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![a23cecdd8c51988ac798e7e8731d0a54](https://github.com/apache/skywalking/assets/58261759/ba9cf558-2435-46e9-9172-6089c75cb68d)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Don't spam the community channel.

**Comment by wu-sheng** [comment]
This is not a service support.You have asked on discussion channel.
