### ISSUE TITLE
[Bug]  helm install 4.4.0 The terminal does not exit, and the waiting time is too long

### ISSUE THREAD

**Issue by liuxin638507** [apache/skywalking#11015]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Helm Chart (apache/skywalking-kubernetes)

### What happened

helm install 4.4.0 The terminal does not exit, and the waiting time is too long,Should not take up the terminal's time, if more than one helm starts, it will crash

### What you expected to happen

helm install skywalking  ./ -n skywalking -f values.yaml

### How to reproduce

![image](https://github.com/apache/skywalking/assets/32058132/aee21d3a-0291-495c-a95f-e541a82485e2)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
It’s annoying to keep opening duplicate issues,
