### ISSUE TITLE
[Bug] helm uninstall 4.4.0 version is incomplete

### ISSUE THREAD

**Issue by liuxin638507** [apache/skywalking#11014]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Helm Chart (apache/skywalking-kubernetes)

### What happened

helm uninstall 4.4.0 version is incomplete, there are also job-related services

### What you expected to happen

[root@node-y1 skywalking]# helm ls -n skywalking
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
NAME      	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART                	APP VERSION
skywalking	skywalking	1       	2023-06-28 18:00:25.342977545 +0800 CST	deployed	skywalking-helm-4.4.0	           
[root@node-y1 skywalking]# helm uninstall skywalking   -n skywalking
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
release "skywalking" uninstalled
[root@node-y1 skywalking]# kubectl get pod -n skywalking
NAME                        READY   STATUS      RESTARTS   AGE
skywalking-oap-init-xjkzn   0/1     Completed   0          3m20s
[root@node-y1 skywalking]# kubectl get all -n skywalking
NAME                            READY   STATUS      RESTARTS   AGE
pod/skywalking-oap-init-xjkzn   0/1     Completed   0          3m26s

NAME                            COMPLETIONS   DURATION   AGE
job.batch/skywalking-oap-init   1/1           2m17s      3m26s

### How to reproduce

![image](https://github.com/apache/skywalking/assets/32058132/366dc2cc-cec5-4da3-81c0-c45bfb07f3f0)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by innerpeacez** [comment]
The job strategy is `before-hook-creation`, so it will not be deleted. ref to https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies
