### ISSUE TITLE
[Bug] can not query the instances when oap running over 1 day (mysql storage)

### ISSUE THREAD

**Issue by weixiang1862** [apache/skywalking#11023]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I use mysql as my skywalking develop environment, I found `JDBCMetadataQueryDAO.listInstances()` method returns empty when oap running over 1 day even though my otel collector report metrics continuously.

InstanceTraffic is not a timeRelativeID metric, so it always stay in the oldest table and wait for update util ttl delete it. In the following pic, instance was created and updated in `instance_traffic_20230628` but `instance_traffic_20230629` is empty：

![image](https://github.com/apache/skywalking/assets/16346644/3215f127-5d2b-466e-a263-26c11fdac856)

`JDBCMetadataQueryDAO.listInstances()` returns empty because `tableHelper.getTablesForRead` just returns `instance_traffic_20230629` which is calculate by duration, the following query running in an empty table:
```
@Override
@SneakyThrows
public List<ServiceInstance> listInstances(Duration duration,
                                               String serviceId) {
        final var results = new ArrayList<ServiceInstance>();

        final var minuteTimeBucket = TimeBucket.getMinuteTimeBucket(duration.getStartTimestamp());

---->   final var tables = tableHelper.getTablesForRead(
            InstanceTraffic.INDEX_NAME,
            duration.getStartTimeBucket(),
            duration.getEndTimeBucket()
        );
}
```

### What you expected to happen

Oap server can return instances running over 1 day.

### How to reproduce

1. running oap server in mysql storage mode
2. execute `queryInstances` query in the next day (we can adjust pc system time to mock one day pass)

### Anything else

I think we can fix this in two ways：
1. use `tableHelper.getTablesWithinTTL` replace `tableHelper.getTablesForRead` in listInstance method
2. create instance in todays table when instance traffic in

@wu-sheng Do you have any suggestions and which way is better？

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I think this is a bug. Instance is not time relative. It would stay like you described. But, the query is wrong.
Query should cover all available tables like query service.

@kezhenxu94 This looks like a bug of new JDBC implementation.

**Comment by kezhenxu94** [comment]
@weixiang1862 sounds like your first way works, replace with 'tableHelper.getTablesWithinTTL'. Do you want to open a pull request?

**Comment by weixiang1862** [comment]
> @weixiang1862 sounds like your first way works, replace with 'tableHelper.getTablesWithinTTL'. Do you want to open a pull request?

Yes, I will open it later
