### ISSUE TITLE
[Bug] the skywalking plugin do not fully support pulsar

### ISSUE THREAD

**Issue by Allen123Hao** [apache/skywalking#11028]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

I use pulsar，set consumer config。add negativeAckRedeliveryDelay，like this:
` 

           consumer = pulsarClient.newConsumer(Schema.STRING)
                    .consumerName("order-payment")
                    .topic(TOPIC_PAYMENT)
                    .subscriptionName("order-payment-sub")
                    .subscriptionType(SubscriptionType.Shared)
                    .enableRetry(true)
                    .negativeAckRedeliveryDelay(30, TimeUnit.SECONDS)
                    .deadLetterPolicy(DeadLetterPolicy.builder()
                            .maxRedeliverCount(3)
                            .retryLetterTopic(RETRY_LETTER_TOPIC_PAYMENT)
                            .deadLetterTopic(DEAD_LETTER_TOPIC_PAYMENT)
                            .build())
                    .messageListener(orderConsumer)
                    .subscribe();

`
when send message, the error occur:

java.lang.ClassCastException: class java.lang.String cannot be cast to class org.apache.skywalking.apm.plugin.pulsar.common.MessageEnhanceRequiredInfo (java.lang.String is in module java.base of loader 'bootstrap'; org.apache.skywalking.apm.plugin.pulsar.common.MessageEnhanceRequiredInfo is in unnamed module of loader org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader @2e4262d2)
\tat org.apache.skywalking.apm.plugin.pulsar.common.PulsarConsumerListenerInterceptor.lambda$afterMethod$cf935be7$1(PulsarConsumerListenerInterceptor.java:60)
\tat org.apache.pulsar.client.impl.ConsumerBase.callMessageListener(ConsumerBase.java:1147)
\tat org.apache.pulsar.client.impl.ConsumerBase.lambda$triggerListener$10(ConsumerBase.java:1113)
\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
\tat org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
\tat java.base/java.lang.Thread.run(Thread.java:833)

### What you expected to happen

if i not use skywalking locally, the application is normal。but when use skywalking,the error appearance.
my pulsar client is 3.0.0

### How to reproduce

use pulsar client 3.0.0, set consumer config lilke this:

`

       Consumer<String> consumer;
        try {
            consumer = pulsarClient.newConsumer(Schema.STRING)
                    .consumerName("order-payment")
                    .topic(TOPIC_PAYMENT)
                    .subscriptionName("order-payment-sub")
                    .subscriptionType(SubscriptionType.Shared)
                    .enableRetry(true)
                    .negativeAckRedeliveryDelay(30, TimeUnit.SECONDS)
                    .deadLetterPolicy(DeadLetterPolicy.builder()
                            .maxRedeliverCount(3)
                            .retryLetterTopic(RETRY_LETTER_TOPIC_PAYMENT)
                            .deadLetterTopic(DEAD_LETTER_TOPIC_PAYMENT)
                            .build())
                    .messageListener(orderConsumer)
                    .subscribe();
        } catch (PulsarClientException e) {
            log.error("init payment consumer exception",e);
            throw new BizException("init payment consumer exception",e);
        }

`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
It is better you could reach pulsar community. There should be more ppl watching there.
We(SkyWalking) host the plugins of Pulsar clients, but we didn't write it and maintain it.

But, from the docs, there isn't one declaring Pulsar 3 supported. https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/supported-list/

**Comment by Allen123Hao** [comment]
when I lower the pulsar-client version, the problem is solved.
