### ISSUE TITLE
[Bug] min duration in Statistics of trace view

### ISSUE THREAD

**Issue by pw151294** [apache/skywalking#11022]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

Description: I have identified an issue in the getSpanGroupData method of the Statistics.Vue file in Skywalking. The problem lies in the initialization of the minTime variable, which is set to 0. This leads to an incorrect calculation of the minTime value, as it remains 0 throughout the calculation process.

### What you expected to happen

Expected Result: The minTime value should be correctly calculated based on the data provided.
Actual Result: Due to the incorrect initialization of minTime to 0, the calculated minTime value is always 0, regardless of the actual data.

### How to reproduce

Navigate to the Statistics.Vue file in the Skywalking repository.
Locate the getSpanGroupData method.
Observe that the minTime variable is initialized to 0.
Expected Result: The minTime value should be correctly calculated based on the data provided.
Actual Result: Due to the incorrect initialization of minTime to 0, the calculated minTime value is always 0, regardless of the actual data.

### Anything else

Suggested Solution: To resolve this issue, I propose modifying the initialization of the minTime variable. Instead of setting it to 0, it should be initialized with a larger value, such as Infinity or a value that is guaranteed to be larger than any valid time value in the data set. This will ensure that the minTime value is correctly calculated during the process.
Code Snippet:
// Before modification
let minTime = 0;
// After modification
let minTime = Infinity;
Please let me know if you need any further information or if there are any suggested alternatives for addressing this issue. Thank you!

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please update the title according. It is blank now.

**Comment by wu-sheng** [comment]
Please submit a pull request if you have the fix. We will review and feedback.

**Comment by Fine0830** [comment]
Closed this via https://github.com/apache/skywalking-booster-ui/pull/294.
