### ISSUE TITLE
[Feature] support to trace redisson lock

### ISSUE THREAD

**Issue by peachisai** [apache/skywalking#11030]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

redisson plugin does not trace redisson lock.
I want to add local spans for tracing redisson lock

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you want to submit a pull request for that, do it.
You don't need a permission, we could discuss the details on the PR.

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-java/pull/567
