### ISSUE TITLE
[Feature] Support MongoDB Monitoring

### ISSUE THREAD

**Issue by weixiang1862** [apache/skywalking#11045]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

MongoDB is a popular document database, I hava do some works on mongodb monitoring and I want ask for a permit to contribute it to skywalking. Currently, it support mongodb single node、replSet、shard cluster monitoring. The mapping of mongodb and skywalking like the following table:
|MongoDB|skywalking|
|-----------|------------|
|cluster|Service|
|Node|Instance|
|ReplSet|Endpoint|

Data flow:
[mongodb exporter](https://github.com/percona/mongodb_exporter) -> OpenTelemetry Collector -> SkyWalking OTEL receiver (OTLP)

I hava following two questions:
1. whether it is appropriate monitoring replset as skywalking endpoint？
2. I want add a menu named MongoDB under database menu, is it ok？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Assigned to you.

**Comment by wu-sheng** [comment]
> whether it is appropriate monitoring replset as skywalking endpoint？

It should be `operation name`/`entity name` AFAIK. But I don't know whether you have that in the OTEL integration.

> I want add a menu named MongoDB under database menu, is it ok？

This is fine. But you should know, an important change about this is happening,
- https://github.com/apache/skywalking/pull/11005
- https://skywalking.apache.org/docs/main/next/en/ui/readme/#sidebar-menu-and-marketplace

@Fine0830 is working on that part.
@weixiang1862 You could work on other parts first, and you just need to update `ui-initialized-templates/menu.yaml`, and add the icon later. You should be good. You just can't see the menu for short term.

**Comment by wu-sheng** [comment]
Further, ReplSet should not be the endpoint. Endpoint is a concept of logic operation, like URI, gRPC service, Database table operations, etc.

**Comment by weixiang1862** [comment]
Ok, thanks for your remind.

**Comment by wu-sheng** [comment]
@weixiang1862 When do you plan to submit this?

**Comment by weixiang1862** [comment]
Sorry about this, I'm busy at my work this week, I think next week will be ok.

**Comment by weixiang1862** [comment]
Some work progress made in this week:
1. MongoDB Cluster
![36d6bc04660dd25738b997a3a35f561](https://github.com/apache/skywalking/assets/16346644/19461f06-882d-4f12-91c9-604c5dceb4f2)

3. MongoDB Node
![706eeb7f89bd2b38fbdae7736415b2a](https://github.com/apache/skywalking/assets/16346644/03a10a48-8bf5-4439-98b8-9dba40cfd2e5)


I will complete e2e case and docs in next week, any suggestions for above?

**Comment by wu-sheng** [comment]
Have you used the MQE? We are planning to remove the old(general) metric config soon.

**Comment by weixiang1862** [comment]
> Have you used the MQE? We are planning to remove the old(general) metric config soon.

Yes, I used MQE to build this dashboard. I noticed you mention it in issue list.

**Comment by wu-sheng** [comment]
Have you synced the latest commit? I think the dynamic menu is there. Have you tested the menu?

**Comment by weixiang1862** [comment]
> Have you synced the latest commit? I think the dynamic menu is there. Have you tested the menu?

Not yet, I will test this later.

**Comment by weixiang1862** [comment]
> What are `getLastTime` and `getLastTime error time` meaning? This seems not a term.

They are calculated from these metrics:

[mongodb_ss_metrics_getLastError_wtime_num](https://www.mongodb.com/docs/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.metrics.getLastError.wtime.num)

[mongodb_ss_metrics_getLastError_wtimeouts](https://www.mongodb.com/docs/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.metrics.getLastError.wtime.totalMillis)

[mongodb_ss_metrics_getLastError_wtime_totalMillis](https://www.mongodb.com/docs/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.metrics.getLastError.wtime.totalMillis)

It represent the number and cost time of getLastError command with [write concern](https://www.mongodb.com/docs/v6.0/reference/write-concern/#std-label-write-concern), which wait for other members of a replica set to acknowledge for write operation.

**Comment by wu-sheng** [comment]
OK, generally, I think it is good. 
Last check, the nodes are represented by Instance, right?

**Comment by weixiang1862** [comment]
> OK, generally, I think it is good. Last check, the nodes are represented by Instance, right?

Yes, node represent a mongodb instance.

**Comment by wu-sheng** [comment]
OK, let's wait for your PR ready to review.
