### ISSUE TITLE
[Feature] Insert into mysql speed is too slow, causing oap oom. 

### ISSUE THREAD

**Issue by ydyzxm** [apache/skywalking#11050]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

If the mysql database is used as the storage device, the mysql database is inserted slowly, causing oap service oom

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
That is not a thing we could help.
