### ISSUE TITLE
[Bug] BanyanDB ui unable to load icon

### ISSUE THREAD

**Issue by ButterBright** [apache/skywalking#11059]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

I tried deploying BanyanDB using Helm and accessed the UI at http://localhost/banyandb/dashboard. However, I noticed that the icon at the upper left corner was not displayed. Upon investigation, I discovered in  the console that the image URL was hardcoded.
![ui](https://github.com/apache/skywalking/assets/52878305/b4a34380-bdb2-483a-b6df-1784f37e69ff)
![console](https://github.com/apache/skywalking/assets/52878305/bd697aa4-329c-4cdb-835d-820f0ee72068)

### What you expected to happen

BanyanDB icon shows up.

### How to reproduce

To open the BanyanDB ui from a port other than 5173.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by WuChuSheng1** [comment]
Thank you for raising your question. In fact, the code hardcoded the path as http://localhost:5173/src/assets/banyandb_small.jpg. This will result in icon access failure if you change the deployment port number. Next, I will change it to a relative path to eliminate this issue. Thank you.
