### ISSUE TITLE
[Bug] BanyanDB ui type error

### ISSUE THREAD

**Issue by ButterBright** [apache/skywalking#11066]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

I encounter this error consistently whenever I access or refresh the ui page.
![error](https://github.com/apache/skywalking/assets/52878305/3871a56d-8d6a-447e-96be-8175741e9c91)

### What you expected to happen

Make the page error-free.

### How to reproduce

To access or refresh the ui page.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to contribute this?

**Comment by ButterBright** [comment]
I'm afraid not bacause I'm not familiar with vue. Thank you for considering me for the code contribution.

**Comment by WuChuSheng1** [comment]
I will contribute to this.
