### ISSUE TITLE
[Bug] percentiles are wrong if sampled values are small

### ISSUE THREAD

**Issue by lu-xiaoshuang** [apache/skywalking#11063]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

If values in a sample window are small, the percentiles are all zero.

<img width="866" alt="bug-1" src="https://github.com/apache/skywalking/assets/121755080/888d9995-717a-49f8-9c0a-94e2706ab63b">

<img width="911" alt="bug-2" src="https://github.com/apache/skywalking/assets/121755080/f5f6e14f-8c97-485e-8188-97b0df8f176a">

### What you expected to happen

percentiles should not be zero.

### How to reproduce

let values in a sample window be small.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You just give some graphs, we can't see what is wrong.

**Comment by wu-sheng** [comment]
If you want to.discuss calculation correction, please details of original data, otherwise, there is no point to follow

**Comment by lu-xiaoshuang** [comment]
I said that the percentile values is not correct.
