### ISSUE TITLE
[Feature] Support to collect ipv6 address

### ISSUE THREAD

**Issue by peachisai** [apache/skywalking#11061]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I noticed skywalking-java agent reports operation system info only collects ipv4 address。
If i disable ipv4 and only use ipv6,it will be show no-hostname。

    public static List<String> getAllIPV4() {
        if (IPV4_LIST == null) {
            IPV4_LIST = new LinkedList<>();
            try {
                Enumeration<NetworkInterface> interfs = NetworkInterface.getNetworkInterfaces();
                while (interfs.hasMoreElements()) {
                    NetworkInterface networkInterface = interfs.nextElement();
                    Enumeration<InetAddress> inetAddresses = networkInterface.getInetAddresses();
                    while (inetAddresses.hasMoreElements()) {
                        InetAddress address = inetAddresses.nextElement();
                        if (address instanceof Inet4Address) {
                            String addressStr = address.getHostAddress();
                            if ("127.0.0.1".equals(addressStr)) {
                                continue;
                            } else if ("localhost".equals(addressStr)) {
                                continue;
                            }
                            IPV4_LIST.add(addressStr);
                        }
                    }
                }
            } catch (SocketException e) {

            }
        }
        return IPV4_LIST;
    }

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you using IPv6 in product already?

**Comment by peachisai** [comment]
@wu-sheng 
emm... actually not。

**Comment by wu-sheng** [comment]
Then why are we adding this?
We prefer real use cases, I can't verify this as we don't use IPv6.

**Comment by peachisai** [comment]
@wu-sheng 
I can verify this by disposing ip address, now i only use ipv6 address in testing environment。
And i think many applications use ipv6 now。

**Comment by wu-sheng** [comment]
Many of where? I don't have feedback from the community about using this, actually.
If we could find real use cases, we can approve this.
