### ISSUE TITLE
[Bug] Jedis-2.x-3.x-plugin referenced a non-existent intercept class

### ISSUE THREAD

**Issue by xzyJavaX** [apache/skywalking#11064]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

` org.apache.skywalking.apm.plugin.jedis.v3.JedisClusterConstructorWithHostAndPortArgInterceptor`  was used as ` CONSTRUCTOR_WITH_HOSTANDPORT_ARG_INTERCEPT_CLASS`  in ` org.apache.skywalking.apm.plugin.jedis.v3.define.JedisClusterInstrumentation` , but this class no longer exists.It seems to have been deleted from this PR:https://github.com/apache/skywalking-java/pull/526

### What you expected to happen

No response

### How to reproduce

No response

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@xu1009 Could you confirm what is the case？

**Comment by xu1009** [comment]
yes，it is bug, the plugin test does not cover the jedisCluster

**Comment by xzyJavaX** [comment]
How to test JedisCluster?
