### ISSUE TITLE
PHP[Bug] Memory leak caused by unit test execution

### ISSUE THREAD

**Issue by mckue** [apache/skywalking#11075]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Environment: mac os ventura
PHP: php8.1
web framework: laravel9:v9.52.10
server status: Skywalking agent server not started
Problem Description:
Every time a unit test is run, a new PHP process is added and occupies 11 threads, thereby killing the PHP Storm PHP process

![image](https://github.com/apache/skywalking/assets/29243171/0aff3b53-fb7d-4205-97da-4961d1408370)

![image](https://github.com/apache/skywalking/assets/29243171/81e730e3-eb71-41fb-8c2d-d8cae552cf92)

Open files and ports：
/Users/carlin/www/yc-publish-api
/opt/homebrew/Cellar/php@8.1/8.1.19_1/bin/php
/opt/homebrew/Cellar/aspell/0.60.8/lib/libpspell.15.dylib
/opt/homebrew/Cellar/openldap/2.6.4/lib/liblber.2.dylib
/opt/homebrew/Cellar/libpq/15.3/lib/libpq.5.15.dylib
/opt/homebrew/Cellar/gettext/0.21.1/lib/libintl.8.dylib
/opt/homebrew/Cellar/tidy-html5/5.8.0/lib/libtidy.5.8.0.dylib
/opt/homebrew/Cellar/aspell/0.60.8/lib/libaspell.15.dylib
/opt/homebrew/Cellar/krb5/1.21/lib/libcom_err.3.0.dylib
/opt/homebrew/Cellar/icu4c/72.1/lib/libicuio.72.1.dylib
/opt/homebrew/Cellar/krb5/1.21/lib/libk5crypto.3.1.dylib
/opt/homebrew/Cellar/freetds/1.3.18/lib/libsybdb.5.dylib
/opt/homebrew/Cellar/openldap/2.6.4/lib/libldap.2.dylib
/opt/homebrew/Cellar/krb5/1.21/lib/libgssapi_krb5.2.2.dylib
/opt/homebrew/Cellar/argon2/20190702_1/lib/libargon2.1.dylib
/opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmp.10.dylib
/opt/homebrew/Cellar/krb5/1.21/lib/libkrb5support.1.1.dylib
/opt/homebrew/Cellar/libzip/1.9.2/lib/libzip.5.5.dylib
/opt/homebrew/Cellar/gd/2.3.3_5/lib/libgd.3.dylib
/opt/homebrew/Cellar/krb5/1.21/lib/libkrb5.3.3.dylib
/opt/homebrew/Cellar/openssl@1.1/1.1.1u/lib/libssl.1.1.dylib
/opt/homebrew/Cellar/pcre2/10.42/lib/libpcre2-8.0.dylib
/opt/homebrew/Cellar/curl/8.1.2/lib/libcurl.4.dylib
/opt/homebrew/Cellar/unixodbc/2.3.11/lib/libodbc.2.dylib
/opt/homebrew/Cellar/libsodium/1.0.18_1/lib/libsodium.23.dylib
/opt/homebrew/Cellar/brotli/1.0.9/lib/libbrotlidec.1.0.9.dylib
/opt/homebrew/Cellar/webp/1.3.0_1/lib/libsharpyuv.0.0.0.dylib
/opt/homebrew/Cellar/highway/1.0.4/lib/libhwy.1.0.4.dylib
/opt/homebrew/Cellar/openssl@1.1/1.1.1u/lib/libcrypto.1.1.dylib
/opt/homebrew/Cellar/sqlite/3.42.0/lib/libsqlite3.0.dylib
/opt/homebrew/Cellar/oniguruma/6.9.8/lib/libonig.5.dylib
/opt/homebrew/Cellar/libnghttp2/1.53.0/lib/libnghttp2.14.dylib
/opt/homebrew/Cellar/libidn2/2.3.4_1/lib/libidn2.0.dylib
/opt/homebrew/Cellar/rtmpdump/2.4+20151223_1/lib/librtmp.1.dylib
/opt/homebrew/Cellar/libssh2/1.11.0/lib/libssh2.1.dylib
/opt/homebrew/Cellar/brotli/1.0.9/lib/libbrotlicommon.1.0.9.dylib
/opt/homebrew/Cellar/libavif/0.11.1/lib/libavif.15.0.1.dylib
/opt/homebrew/Cellar/libpng/1.6.39/lib/libpng16.16.dylib
/opt/homebrew/Cellar/libtool/2.4.7/lib/libltdl.7.dylib
/opt/homebrew/Cellar/igbinary@8.1/3.2.14/igbinary.so
/opt/homebrew/Cellar/fontconfig/2.14.2/lib/libfontconfig.1.dylib
/opt/homebrew/Cellar/icu4c/72.1/lib/libicui18n.72.1.dylib
/opt/homebrew/Cellar/icu4c/72.1/lib/libicuuc.72.1.dylib
/opt/homebrew/Cellar/zstd/1.5.5/lib/libzstd.1.5.5.dylib
/opt/homebrew/Cellar/freetype/2.13.0_1/lib/libfreetype.6.dylib
/opt/homebrew/Cellar/xz/5.4.3/lib/liblzma.5.dylib
/opt/homebrew/Cellar/msgpack@8.1/2.2.0RC1/msgpack.so
/opt/homebrew/Cellar/jpeg-turbo/2.1.5.1/lib/libjpeg.8.2.2.dylib
/opt/homebrew/Cellar/lz4/1.9.4/lib/liblz4.1.9.4.dylib
/opt/homebrew/Cellar/libunistring/1.1/lib/libunistring.5.dylib
/opt/homebrew/Cellar/webp/1.3.0_1/lib/libwebp.7.1.6.dylib
/opt/homebrew/Cellar/libtiff/4.5.0/lib/libtiff.6.dylib
/opt/homebrew/Cellar/little-cms2/2.15/lib/liblcms2.2.dylib
/opt/homebrew/Cellar/brotli/1.0.9/lib/libbrotlienc.1.0.9.dylib
/opt/homebrew/Cellar/jpeg-xl/0.8.1_2/lib/libjxl.0.8.1.dylib
/opt/homebrew/Cellar/aom/3.6.1/lib/libaom.3.6.1.dylib
/opt/homebrew/Cellar/libvmaf/2.3.1/lib/libvmaf.1.dylib
/opt/homebrew/Cellar/redis@8.1/5.3.7/redis.so
/opt/homebrew/Cellar/openssl@3/3.1.1/lib/libssl.3.dylib
/opt/homebrew/Cellar/php@8.1/8.1.19_1/lib/php/20210902/opcache.so
/opt/homebrew/lib/php/pecl/20210902/swoole.so
/opt/homebrew/Cellar/openssl@3/3.1.1/lib/libcrypto.3.dylib
/opt/homebrew/Cellar/icu4c/72.1/lib/libicudata.72.1.dylib
/opt/homebrew/lib/php/pecl/20210902/skywalking_agent.so
/dev/urandom
/private/tmp/skywalking-agent.log
/Users/carlin/www/yc-publish-api/vendor/bin/phpstan
count=0, state=0xa
count=0, state=0xa
count=0, state=0xa
->0xb20b15b6f9240f2d
->0xb20b15b6f9240e65
->0xb20b15b6f9240f2d
/tmp/skywalking-agent/6003267100779.sock

php.ini configuration
[skywalking_agent]
; Enable skywalking_agent extension or not.
skywalking_agent.enable = On
; Log file path.
skywalking_agent.log_file = /tmp/skywalking-agent.log
; Log level: one of `OFF`, `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`.
skywalking_agent.log_level = INFO
; Address of skywalking oap server.
skywalking_agent.server_addr = 127.0.0.1:11800
; Application service name.
skywalking_agent.service_name = yc-publish-api

### What you expected to happen

Memory leak caused by unit test execution

### How to reproduce

Environment: mac os ventura
PHP: php8.1
web framework: laravel9:v9.52.10
server status: Skywalking agent server not started
Problem Description:
Every time a unit test is run, a new PHP process is added and occupies 11 threads, thereby killing the PHP Storm PHP process
. Observe process changes after executing unit tests

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment]
I think you should better turn off the `skywalking_agent.enable` by default.

As mention in <https://skywalking.apache.org/docs/skywalking-php/next/en/setup/service-agent/php-agent/readme/#configure>, it would be better to enable skywalking-agent on demand when running.
