### ISSUE TITLE
[Bug] The minute metric value has been overwritten when kafka consumer lag

### ISSUE THREAD

**Issue by hyhyf** [apache/skywalking#11087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Jdk 8, oap version 9.4.0, use kafka fetcher.
In my case, when kafka had a huge backlog, the metric from about the last 10 minute ago has been overwritten.

### What you expected to happen

I think the reason is org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker#requireInitialization:
`        if (timeOfLatestStabilitySts > 0 && 
                metrics.getTimeBucket() > timeOfLatestStabilitySts
                && cached == null) {
            // Return metrics as input to avoid reading from database.
            return metrics;
}`
This code skip the metric that need to load the database, beacuse consumer lag, the metric expired in the cache, but it still need combine and calculate.

### How to reproduce

kafka consumer backlog.

### Anything else

We should add a condition what the metric not in cache due to not expired.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
For minute metrics, we would not accept reload. It was there, and the performance is super bad, the load of DB is high.

This is a new feature, rather than a bug.

If you Kafka causes a super long latency(in several minutes), I believe that is your env issue, rather than ours.

**Comment by hyhyf** [comment]
> For minute metrics, we would not accept reload. It was there, and the performance is super bad, the load of DB is high.
> 
> This is a new feature, rather than a bug.
> 
> If you Kafka causes a super long latency(in several minutes), I believe that is your env issue, rather than ours.

Yes, i solved it by improving database performance, but i think someone also face this problem due to kafka consumer lag, so i report it :)
