### ISSUE TITLE
[Bug] config -Dskywalking.plugin.elasticsearch.trace_dsl=true doesn't work

### ISSUE THREAD

**Issue by guaguaguaxia** [apache/skywalking#11090]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

helm upgrade --install "${project_name}" \
  --set name="${project_name}" \
  --set deployname="${project_name}" \
  --set replicaCount=${replicaCount} \
  --set version="${app_version}" \
  --set resources.limits.memory="${limits_memory}" \
  --set resources.requests.memory="${requests_memory}" \
  --set pdb.enabled="true" \
  --set image.repository="registry-vpc.cn-hongkong.aliyuncs.com/zhidayilian-o2o/${project_name}"  \
  --set image.tag="${DATETIME}" \
  --set env.oap_opts="-javaagent:/skywalking-agent/skywalking-agent.jar -Dskywalking.agent.service_name=release::${project_name} -Dskywalking.collector.backend_service=skywalking-oap.oap.svc:11800 -Dskywalking.plugin.jdbc.trace_sql_parameters=true -Dskywalking.plugin.elasticsearch.trace_dsl=true" \
  lalachart/demo-release -n release

this is my helm command,i config the <-Dskywalking.plugin.elasticsearch.trace_dsl=true> but it doesn't work, i can't find the DSL in skywalking UI,**but  -Dskywalking.plugin.jdbc.trace_sql_parameters=true it's work**

![image](https://github.com/apache/skywalking/assets/18466048/de8655b6-ceeb-4d67-9c38-3db8880529ed)
in this picture there is no dsl

![image](https://github.com/apache/skywalking/assets/18466048/d600c236-6759-452f-95d1-8abbd8b7574f)
but i can see the mysql statement

could you tell me how can i troubleshoot this problem

### What you expected to happen

to see the dsl

### How to reproduce

i have no idea

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please determine this is failed in regular Java agent or helm.
The scope should be clear.
