### ISSUE TITLE
[Bug] Can't install helm on local k8s v 1.27.2

### ISSUE THREAD

**Issue by dodalovicgran** [apache/skywalking#11092]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Helm Chart (apache/skywalking-kubernetes)

### What happened

Tried to install as per [link](https://github.com/apache/skywalking-kubernetes#install-released-version-using-docker-helm-repository--430)

```bash
  ~ export SKYWALKING_RELEASE_VERSION=4.3.0  # change the release version according to your need
export SKYWALKING_RELEASE_NAME=skywalking  # change the release name according to your scenario
export SKYWALKING_RELEASE_NAMESPACE=default
➜  ~ echo $SKYWALKING_RELEASE_NAME
skywalking
➜  ~ echo $SKYWALKING_RELEASE_NAMESPACE
default
➜  ~ echo $SKYWALKING_RELEASE_NAMESPACE
➜  ~ echo $SKYWALKING_RELEASE_NAMESPACE=skywalking
default=skywalking
➜  ~ helm install "${SKYWALKING_RELEASE_NAME}" \
  oci://registry-1.docker.io/apache/skywalking-helm \
  --version "${SKYWALKING_RELEASE_VERSION}" \
  -n "${SKYWALKING_RELEASE_NAMESPACE}" \
  --set oap.image.tag=9.2.0 \
  --set oap.storageType=elasticsearch \
  --set ui.image.tag=9.2.0
Pulled: registry-1.docker.io/apache/skywalking-helm:4.3.0
Digest: sha256:34f9abc41924aabbe7c71a0e5b0c548b67e2b8d7093f19e21fa8927309f00e4a
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "elasticsearch-master-pdb" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
ensure CRDs are installed first
```

### What you expected to happen

i don't know. I'm junior at these stuff

### How to reproduce

see in what happened

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
This should be fixed in https://github.com/apache/skywalking-kubernetes/pull/98, please try `SKYWALKING_RELEASE_VERSION=4.4.0`

**Comment by dodalovicgran** [comment]
fails for some other reason. i think there's some issue with pod affinity, elasticsearch nodes are not booting up. 
Dunno
