### ISSUE TITLE
[Feature] Add component ID (5015) for Golang

### ISSUE THREAD

**Issue by ethan256** [apache/skywalking#11101]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

add componment ID(5015) for Golang framework [echo](https://github.com/labstack/echo).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't need an issue for this kind of simple PR actually. Feel free to open PR directly next time.

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking/pull/11102
