### ISSUE TITLE
oap-init job does not complete when `istio-injection` = `enabled` for a K8s namespace

### ISSUE THREAD

**Issue by eric-futureself** [apache/skywalking#11105]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Helm Chart (apache/skywalking-kubernetes)

### What happened

Istio blocks oap-init job from completing.

### What you expected to happen

Job completes.

### How to reproduce

Run helm install on a cluster, in a namespace where `istio-injection` is set to `enabled`.

### Anything else

See [Add `extraPodLabels` to `oapInit` so Job can have additional labels](https://github.com/apache/skywalking-kubernetes/pull/125)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by eric-futureself** [comment]
See the above PR - I just validated it works.

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-kubernetes/pull/125
