### ISSUE TITLE
[Bug] Repeated enhancement occurs in mysql-5.x-plugin.

### ISSUE THREAD

**Issue by xzyJavaX** [apache/skywalking#11106]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Both `org.apache.skywalking.apm.plugin.jdbc.mysql.v5.define.CacheIpsInstrumentation` and `org.apache.skywalking.apm.plugin.jdbc.mysql.v5.define.DriverInstrumentation` have enhanced the `connect` method of `com.mysql.jdbc.Driver` and `com.mysql.jdbc.NonRegisteringDriver`.
BTW, why do we need to enhance both `com.mysql.jdbc.Driver` and `com.mysql.jdbc.NonRegisteringDriver`? This sometimes leads to the method in interceptor being called twice.

### What you expected to happen

No response

### How to reproduce

No response

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We are not sure about that, but be careful when you want to remove something, it could be a bug trigger.
