### ISSUE TITLE
[Feature] A new cluster plugin based on multicast

### ISSUE THREAD

**Issue by weixiang1862** [apache/skywalking#11114]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, skywalking cluster mode all depend on external register center to discovery each self. I want develop a new cluster plugin with the multicast auto-discovery mechanism. 

Although multicast depends on network environment and only works in LAN, It can also bring benefits to user who are not familiar with nacos or zookeeper and make skywalking more lightweight in deployment. It is suitable for a simple network environment or a tiny company who are sensitive to infrastructure cost.

Multicast is widely used by other software for service auto discovery：
- dubbo（https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/registry/multicast/）
- hazelcast（https://docs.hazelcast.com/hazelcast/latest/clusters/discovering-by-multicast）
- activemq（https://activemq.apache.org/multicast-transport-reference）

@wu-sheng I think it is worth to do something on this, what do you think?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I am afraid this is too challenge for us to adopt the potential breaking.
With quickly growing of cloud native, why you still expect this kind of old things?

**Comment by weixiang1862** [comment]
> I am afraid this is too challenge for us to adopt the potential breaking. With quickly growing of cloud native, why you still expect this kind of old things?

You are right, it is truly an old thing. I will keep it locally, thanks.

**Comment by wu-sheng** [comment]
To everyone read this,
We are not sure the necessity to do this, as it brings new complexity at both ends, meanwhile, cloud native stack provides easier solution.

We don't think we still need to maintain this.
