### ISSUE TITLE
[Feature]  does skywalking want to support multiple plugins perform multiple enhancements to one method?

### ISSUE THREAD

**Issue by jiangyunpeng** [apache/skywalking#11117]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

at this moment, skywalking's enhancement rule is that if two independent plugin match same method and define distinct MethodsInterceptor, this last one will overwrite the fist one, it can't perform multiple enhancements to one method.

in our scenario except APM we want to use skywalking for some service govern, like auth、traffic limit and so on. so does skywalking want to support multiple plugins perform multiple enhancements to one method? 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lujiajing1126** [comment]
We are also using SW Agent in service government scenarios, e.g. xDS proxyless for routing, alibaba-sentinel integration etc. But we merge several interceptors into a single one.

Besides, for service gov. propose, InstMethodV1 or V2 are not sufficient.

**Comment by wu-sheng** [comment]
We don't guarantee we do or don't.
The cases you mentioned are not our cases.

**Comment by jiangyunpeng** [comment]
> We are using SW Agent in service government scenarios, e.g. xDS proxyless for traffic routing, alibaba-sentinel integration etc. But we merge several interceptors into a single one.
> 
> Besides, for service gov. purpose, PluginDefineV1 or V2 are not sufficient. You need to a customized one. So it is complicated to allow multiple interceptors based on various PluginDefinition versions.

Thanks for your reply
Was your refer to the project open source? 

So far, we use PluginDefineV1 implements some register/discover function, it works well, just the two functions(obverse and service govern) merge into a interceptor has bad smell
