### ISSUE TITLE
[Bug] Skywalking-showcase install fails to init storage (postgresql or Elasticsearch)

### ISSUE THREAD

**Issue by undrh2o** [apache/skywalking#11123]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Showcase (apache/skywalking-showcase)

### What happened

I've attempted to install the showcase to kubernetes with "make deploy.kubernetes" and also tried "make deploy.kubernetes  FEATURE_FLAGS=" that included postgresql instead of elasticsearch the result is the same, the oap pods fail to startup with the same error in the logs:

2023-07-20 18:25:59,848 org.apache.skywalking.oap.server.core.storage.model.ModelInstaller 43 [main] INFO  [] - table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later.

The Helm install of skywalking creates and init job which does work - but I can't get the showcase to work.

Platform is Kubernetes v1.27.3 1 control, 3 workers on Openstack 

### What you expected to happen

The showcase install should install and run correctly - perhaps the init job from the helm charts needs to be added to showcase?

### How to reproduce

make deploy.kubernetes

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
no-init had been explained many times in various discussion and PR.
Generally, it is init job doesn't run successfully, so everthing is waiting.

**Comment by undrh2o** [comment]
Do you care to point to the resolution?  I searched many times in many places dismissing the problem without pointing to the solution is not helpful

**Comment by wu-sheng** [comment]
The thing is the init-job in the deployment should be successful.
You need to retry that and check that.

**Comment by kezhenxu94** [comment]
> The Helm install of skywalking creates and init job which does work - but I can't get the showcase to work.
> 
> Platform is Kubernetes v1.27.3 1 control, 3 workers on Openstack
> 
> What you expected to happen
> 
> The showcase install should install and run correctly - perhaps the init job from the helm charts needs to be added to showcase?
> 
> 

The showcase is using the Helm Chart to install OAP so it’s literally added already, please make yourself clear, what do you mean by “init job not work”, it’s created and failed, or, it’s not even created,
