### ISSUE TITLE
[Bug] The uuid was not reset, which caused the dynamic configuration to not be updated

### ISSUE THREAD

**Issue by xzyJavaX** [apache/skywalking#11140]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

When registering `AgentConfigChangeWatcher` in dynamic configuration, there may be different `AgentConfigChangeWatchers` using the same `propertyKey`. Although there are currently no such cases in `skywalking-java`, but this situation should have been taken into consideration in the previous design. For example:
```
private final Map<String, List<WatcherHolder>> register = new HashMap<>();
```
The same key can correspond to multiple ` WatcherHolders` .
There is a logic in `org.apache.skywalking.apm.agent.core.conf.dynamic.ConfigurationDiscoveryService#getAgentDynamicConfig()`:
 ```        
 // Some plugin will register watcher later.
final int size = register.keys().size();
 if (lastRegisterWatcherSize != size) {
        // reset uuid, avoid the same uuid causing the configuration not to be updated.
        uuid = null;
        lastRegisterWatcherSize = size;
}
 ```       
The situation where the number of keys remains unchanged, but the number of ` WatcherHolders`  corresponding to keys increases, was not considered here. If some plugins will register watchers later, but the keys they use are the same as those in the previous register, then the uuid will not be reset and these configurations will not be updated.

### What you expected to happen

No response

### How to reproduce

No response

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> When registering AgentConfigChangeWatcher in dynamic configuration, there may be different AgentConfigChangeWatchers using the same propertyKey

Do you mean a watcher listening two keys with values? Why?

**Comment by xzyJavaX** [comment]
No, it's two watchers listening a keys with values. For example:
```
private final Map<String, List<WatcherHolder>> register = new HashMap<>();
```

**Comment by wu-sheng** [comment]
That seems unrealistic, why do that?

**Comment by wu-sheng** [comment]
I would say, the codes didn't consider a list although there is a list involved. 
It is OK you support that, but I am wondering what is the real use case? Which two watchers could work for one key?

**Comment by lujiajing1126** [comment]
> I would say, the codes didn't consider a list although there is a list involved. It is OK you support that, but I am wondering what is the real use case? Which two watchers could work for one key?

In our case, we want to share a single key acrosss plugins. For example, 

- `plugin.servlet_container.trace_http_parameters` for tomcat, jetty, etc.
- `plugin.redis.trace_parameters` for jedis, lettuce, redisson, etc.
- ...

In such cases, users don't need to care about what underlying libraries are actually used.

**Comment by wu-sheng** [comment]
OK, go ahead.
