### ISSUE TITLE
[Bug] Boolean match bug 

### ISSUE THREAD

**Issue by SWHHEART** [apache/skywalking#11156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The class of BooleanMath and BooleanNotEqualMatch，the first compare method.
It's almost always a mistake to compare two instances of java.lang.String or boxed types like java.lang.Integer using reference equality == or !=, because it is not comparing actual value but locations in memory.

### What you expected to happen

use equals() not == or !=

### How to reproduce

Update methods, using the equals api

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Which OAL could lead to this way? I was thinking we are only use `boolean` match.

**Comment by wu-sheng** [comment]
> [SWHHEART](https://github.com/SWHHEART) changed the title [Bug] Boolean match bug It's almost always a mistake to compare two instances of java.lang.String or boxed types like java.lang.Integer using reference equality == or !=, because it is not comparing actual value but locations in memory. [1 minute ago](https://github.com/apache/skywalking/issues/11156#event-9958658055)

Don't build a so long title, it is hard to read.

**Comment by SWHHEART** [comment]
I scanned it with sonar, and then looked at the official explanation, looking at the source code did not find that this method is used.But this is really a bad code

**Comment by wu-sheng** [comment]
If you want to submit a pull request to update/fix this, go ahead. To be honest, it is just a scanning thing, because no code would run into it.
So, are you going to submit a pull request?

**Comment by SWHHEART** [comment]
I will study the source code first, if there is an impact I will submit pr

**Comment by wu-sheng** [comment]
This is a nit, nothing specific, I will fix it.

**Comment by SWHHEART** [comment]
ok
