### ISSUE TITLE
[Feature] skywalking-java add configuration to ignore enhanced scanning for certain classes

### ISSUE THREAD

**Issue by hanbingleixue** [apache/skywalking#11160]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I hope to control whether to ignore type scans before enhancing certain classes through configuration rather than code。
![图片1](https://github.com/apache/skywalking/assets/27498485/028a0ecd-6b04-4a1e-aa0d-ee864f07ab63)

### Use case

When I want to ignore type scanning before enhancing certain classes, I need to modify the code, which is very inconvenient。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Why do you want that? Could you explain? We can't see the use cases.

**Comment by wu-sheng** [comment]
Remember, we only could accept common use cases, if this is your private or commercial reason only, it is hard to apply globally. If all are going to be configurable, it would be a disaster.

**Comment by hanbingleixue** [comment]
Dear Mr. Wu, I don't think what was expressed clearly in the previous text is that this is not a private use case, it is a best practice for us to use Bytebuddy.
We have found that using the ignore method to block some custom classes of enterprise programs (such as com. example) can have a beneficial impact on the startup time of Java programs (the impact of Java Agent startup time is often criticized by users).
In my opinion, this is not a private use case, and this configuration does not require customization, but rather provides users with an optional optimization method.
Of course, I also offer suggestions. If it is indeed helpful for Skywalking-Java, then I am also honored to contribute.

**Comment by wu-sheng** [comment]
But once you ignore those, the things like annotations and/or inheritance plugins, typical Spring annotations.
