### ISSUE TITLE
[Bug] oal add filter start error

### ISSUE THREAD

**Issue by RichardLiu0926** [apache/skywalking#11170]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Edit oal  server_sla =  from(Server.*).filter(responseCode not contain 40).percent(status == true);  Application startup error
<img width="1257" alt="image" src="https://github.com/apache/skywalking/assets/15844777/1f0da972-1c31-41a8-b400-844af41f2685">

### What you expected to happen

Configuration error or document error

### How to reproduce

Edit oal  server_sla =  from(Server.*).filter(responseCode not contain 40).percent(status == true);

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
respond Code had been removed for years.. Check the latest doc, I think. `rpcStatusCode` and `httpResponseStatusCode` are there only.

**Comment by RichardLiu0926** [comment]
Where can I check the latest documents?
