### ISSUE TITLE
[Feature] Support Frontend Log Aggregation

### ISSUE THREAD

**Issue by MaShizhen** [apache/skywalking#11173]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

While SkyWalking already provides powerful log collection and querying capabilities, there are still some limitations in terms of frontend log aggregation. We would like to propose adding support for frontend log aggregation in SkyWalking, allowing for better monitoring and analysis of log data generated by frontend applications. This enhancement would contribute to improved efficiency in troubleshooting and enhancing user experience.

### Use case

1. Enable frontend applications to report log data to SkyWalking and support aggregating multiple log messages into a single entry.
1. Provide flexible configuration options for setting rules and conditions for log aggregation.
1. Introduce a visual log aggregation analysis tool within the SkyWalking interface, enabling users to quickly view and analyze aggregated frontend log results.
1. Support exporting aggregated log data for further in-depth analysis and archiving.

By implementing this feature, we believe that SkyWalking will be better equipped to meet the monitoring and analysis needs of frontend applications, leading to enhanced efficiency in issue diagnosis and overall user satisfaction. We look forward to the consideration and implementation of this feature. Thank you.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to do this? And is this through client-js lib?

**Comment by wu-sheng** [comment]
> Provide flexible configuration options for setting rules and conditions for log aggregation.

Could you explain what log aggregation rule is about? The LAL is designed for log process and aggregation(metric extractor). What is new here?

**Comment by MaShizhen** [comment]
The skywalking-client-js is responsible solely for reporting error logs, while the aggregation, counting, and other operations on the reported log data are reliant on the backend. 

Below are examples of functionalities provided by Sentry:
![image](https://github.com/apache/skywalking/assets/31983261/e0f54611-cba3-4b26-a25a-f2f5811a51b3)

**Comment by wu-sheng** [comment]
How do you aggregate? We don't recommend postponed aggregation as it is super slow.
Could you demo how could you count users in current OAP architecture?

**Comment by wu-sheng** [comment]
@MaShizhen Any update? You open this issue for 5 days, but no further update.

**Comment by MaShizhen** [comment]
hi @wu-sheng. Thank you very much for your guidance and reply. My expectation for the log panel is to be able to achieve more detailed aggregation functions, and to be able to click on the record to view error information including stacks, etc., rather than simply counting the occurrence of the same error and displaying it as a metric on the dashboard . According to your valuable suggestions, I carefully read the relevant documents, and have a deeper understanding of the capabilities of LAL (Language Analysis Language). However, I've noticed that LAL may not meet the requirements of my more complex needs.

Based on this, am I understanding correctly? I may need to consider introducing other professional log analysis platforms to achieve the functions I need? Hope to get your further suggestions and guidance, thank you.

**Comment by wu-sheng** [comment]
I can't suggest anything until you share what is LAL missing, and what you want to add.
More importantly, why a new platform? If it is another platform, shouldn't it be a separate/independent project? What is Skywalking role in your design.

After all, I don't have a whole picture of your proposal.

**Comment by MaShizhen** [comment]
Sorry, I added the full description as below.

Background: I am currently working on implementing frontend error log reporting. Our selection criteria prioritize solutions that support both private deployment and high availability. After careful consideration, we, along with our backend colleagues, decided to opt for SkyWalking. It has proven to excel in both aspects, aligning well with our requirements. At present, we have successfully integrated frontend error log reporting with SkyWalking. However, we've identified some areas where the functionality appears to be lacking, as outlined below:

### Issue 1: Lack of Aggregation Support
Scenario: Frontend error logs can accumulate significantly, especially considering our daily user activity of 50,000 users. On average, each user generates one error log per day. Consequently, this results in approximately 50,000 error logs daily. Displaying every individual error log in the log panel would lead to an extensive list, making it challenging to navigate and analyze. To address this, we seek the ability to aggregate error logs. For instance, displaying only a single instance of the same error log per day would significantly reduce the length of the log panel's listing, enhancing ease of use.

**Example of current situation：**
![image](https://github.com/apache/skywalking/assets/31983261/add25a97-dccc-479a-b4bc-2082e7bdb5a6)
**the result i want**
![image](https://github.com/apache/skywalking/assets/31983261/483ecc9b-81ca-4d66-8a4d-069ca21fd1c2)

### Issue 2: The front-end log panel does not support search
Scenario: When a user reports that a white screen occurs when using the app, we need to search the user's log through the log panel to locate the problem.
We may discuss in this related issue post https://github.com/apache/skywalking/issues/3524
