### ISSUE TITLE
[helm chart] Add option to set ingressClass

### ISSUE THREAD

**Issue by fedaykin-b** [apache/skywalking#11185]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Helm Chart (apache/skywalking-kubernetes)

### What happened

I need to create an ingress for UI but I couldn't make it with your chart due to lack of support for the field `ingressClassName` in `ingress`

### What you expected to happen

IngressClassName was introduced in Kubernetes since version [1.18](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/), and your helm chart should support it.

### How to reproduce

```yaml
ingress:
  enabled: true
  ingressClassName: my-ingress # ignored
```

### Anything else

I already have fixed it in a private fork and want to contribute to your helm chart 😊

I want to know if you accept direct PR in case of fixes and minor improvements, or if any PR must be preceded by an issue.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This should be a feature, rather than a bug report.

**Comment by wu-sheng** [comment]
@fedaykin-b I has assigned this to you.

**Comment by wu-sheng** [comment]
cc @innerpeacez @dashanji for the context of the review.

**Comment by wu-sheng** [comment]
@fedaykin-b Are you going to do this? If not, I will close this.

**Comment by fedaykin-b** [comment]
Hi, I'm sorry, I got busy those days. The feature was already implemented? Can I do it?

**Comment by wu-sheng** [comment]
Yes, of course. Submit a pull request and link to here.
