### ISSUE TITLE
[Bug] Event widget doesn't carry correct input for filtering endpoints 

### ISSUE THREAD

**Issue by SimonHu1993** [apache/skywalking#11190]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

when i search the endpoints,i found the keywords still doesn't work.
[![pPVotN6.png](https://s1.ax1x.com/2023/08/08/pPVotN6.png)](https://imgse.com/i/pPVotN6)
the Browser version :Google Chrome 115.0.5790.170 (x86_64);
the oap version: 9.2.0-cb8845a;

https://github.com/apache/skywalking-rocketbot-ui/pull/432

### What you expected to happen

the Browser compatibility issues,
with 360 browser it works normally;
[![pPVo5uj.png](https://s1.ax1x.com/2023/08/08/pPVo5uj.png)](https://imgse.com/i/pPVo5uj)

### How to reproduce

queryEndpoints with keyword

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please check the latest version. It works on my Chrome 115.0.5790.170 on Apple arm64

<img width="1852" alt="image" src="https://github.com/apache/skywalking/assets/5441976/06509c6a-ec91-49c5-923d-53e801657ce3">

**Comment by SimonHu1993** [comment]
[![pPVb1G6.png](https://s1.ax1x.com/2023/08/08/pPVb1G6.png)](https://imgse.com/i/pPVb1G6)
i found the keyword has been defined as "".

**Comment by wu-sheng** [comment]
Your own screenshot is on the trace page. Check your own screenshot.

For event query, it works too.
<img width="1843" alt="image" src="https://github.com/apache/skywalking/assets/5441976/1ebf0bc4-718e-4972-9e49-c33bdcd17e65">


And I am using the latest, not your version. We don't provide any feedback or verification for the old version.

**Comment by SimonHu1993** [comment]
thanks!

**Comment by SimonHu1993** [comment]
9.2.0-cb8845a can fix with the code！
event.ts -》async getEndpoints
```
async getEndpoints(keyword?: string) {
      const serviceId = useSelectorStore().currentService
        ? useSelectorStore().currentService.id
        : "";
      if (!serviceId) {
        return;
      }
      const res: AxiosResponse = await graphql.query("queryEndpoints").params({
        serviceId,
        duration: useAppStoreWithOut().durationTime,
        keyword: keyword || '',
      });
```
[![pPVzKCd.png](https://s1.ax1x.com/2023/08/08/pPVzKCd.png)](https://imgse.com/i/pPVzKCd)
[![pPVzM8A.png](https://s1.ax1x.com/2023/08/08/pPVzM8A.png)](https://imgse.com/i/pPVzM8A)

**Comment by Fine0830** [comment]
I have found out, the `keyword` of endpoint query is wrong in the event widget. Could you submit a pr to fix this? @SimonHu1993

**Comment by wu-sheng** [comment]
@Fine0830 Which part is wrong?

**Comment by Fine0830** [comment]
When input keyword to search endpoints, the `keyword` parameter always is `""` in the endpoint query.

![1](https://github.com/apache/skywalking/assets/20871783/fa5146bd-fc3f-4576-ab09-00e6e97a4a87)

**Comment by wu-sheng** [comment]
Oh, you mean that part. Yes, that is a bug.
