### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tzszhzx** [apache/skywalking#11205]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

i used sky waling 8.16 ，i want to trace webflux and get the traceId,but is report nullpointException。
my application is webflux application，and  not use springmvc ，and not spring cloud gateway application.
1、i use the pom dependencies  1.apm-toolkit-trace   2.apm-toolkit-logback-1.x  3.apm-toolkit-webflux  
2、i use spring-boot-starter-webflux 3.1.2 、spring-webflux 5.3.18。
than i use 
`String traceId = WebFluxSkyWalkingOperators.continueTracing(exchange, TraceContext::traceId);`
but the traceId is N/A，and the log is
`ERROR 2023-08-10 14:28:14.504 reactor-http-nio-2 StaticMethodsInter : class[class org.apache.skywalking.apm.toolkit.webflux.WebFluxSkyWalkingOperators] after static method[continueTracing] intercept failure:null 
java.lang.NullPointerException
	at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:194)
	at org.apache.skywalking.apm.toolkit.activation.webflux.WebFluxSkyWalkingOperatorsInterceptor.afterMethod(WebFluxSkyWalkingOperatorsInterceptor.java:60)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInter.intercept(StaticMethodsInter.java:94)
	at org.apache.skywalking.apm.toolkit.webflux.WebFluxSkyWalkingOperators.continueTracing(WebFluxSkyWalkingOperators.java)
	at com.zo.auth.webflux.filter.TraceFilter.filter(TraceFilter.java:79)
	at org.springframework.web.server.handler.DefaultWebFilterChain.invokeFilter(DefaultWebFilterChain.java:127)
	at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:121)`

### What you expected to happen

how can i get the traceId in webflux，my configuration is error。i should to say in my application mybatis traceid can be trace to log。

### How to reproduce

can you tell me what can i do? thank you very much!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We would NOT debug it for you. Until you debug and find out the issue, there is nothing we could say. 

Generally, this means the current thread doesn't have a span to close.

**Comment by BothSavage** [comment]
> ### 询问前先搜索
> * [x] [我在问题](https://github.com/apache/skywalking/issues?q=is%3Aissue)中搜索过，没有发现类似的问题。
> 
> ### Apache SkyWalking 组件
> Java 代理 (apache/skywalking-java)
> 
> ### 发生了什么
> 我使用sky waling 8.16，我想跟踪webflux并获取traceId，但是报告nullpointException。 我的应用程序是webflux应用程序，并且没有使用springmvc，也不是spring cloud gateway应用程序。 1、我使用pom依赖项 1.apm-toolkit-trace 2.apm-toolkit-logback-1.x 3.apm-toolkit-webflux 2、我使用 spring-boot-starter-webflux 3.1.2 、spring-webflux 5.3.18。 比我用的 `String traceId = WebFluxSkyWalkingOperators.continueTracing(exchange, TraceContext::traceId);` 但是traceId是N/A，日志是 `ERROR 2023-08-10 14:28:14.504 reactor-http-nio-2 StaticMethodsInter : class[class org.apache.skywalking.apm.toolkit.webflux.WebFluxSkyWalkingOperators] after static method[continueTracing] intercept failure:null java.lang.NullPointerException at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:194) at org.apache.skywalking.apm.toolkit.activation.webflux.WebFluxSkyWalkingOperatorsInterceptor.afterMethod(WebFluxSkyWalkingOperatorsInterceptor.java:60) at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInter.intercept(StaticMethodsInter.java:94) at org.apache.skywalking.apm.toolkit.webflux.WebFluxSkyWalkingOperators.continueTracing(WebFluxSkyWalkingOperators.java) at com.zo.auth.webflux.filter.TraceFilter.filter(TraceFilter.java:79) at org.springframework.web.server.handler.DefaultWebFilterChain.invokeFilter(DefaultWebFilterChain.java:127) at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:121)`
> 
> ### 您期望发生什么
> 我如何获取webflux中的traceId，我的配置错误。应该说在我的应用程序mybatis中traceid可以跟踪到日志。
> 
> ### 如何重现
> 你能告诉我我能做什么吗？非常感谢！
> 
> ### 还要别的吗
> _没有反应_
> 
> ### 你愿意提交PR吗？
> * [ ] 是的，我愿意提交 PR！
> 
> ### 行为守则
> * [x] 我同意遵守该项目的[行为准则](https://www.apache.org/foundation/policies/conduct)

https://bothsavage.github.io/article/240121-skywaking

**Comment by lujiajing1126** [comment]
The issue is you have to enable the optional plugin "apm-spring-webflux-5.x-plugin"

If you check the test case, https://github.com/apache/skywalking-java/blob/main/test/plugin/scenarios/webflux-scenario/configuration.yml#L22, the optional plugin have been enabled.
