### ISSUE TITLE
[Feature] Ensuring the safety of stopSpan

### ISSUE THREAD

**Issue by xiaqi1210** [apache/skywalking#11214]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the agent, `createSpan` and `stopSpan` should appear in pairs. In fact, in many plugins, such as HttpClient, dubbo, etc., createSpan is in beforeMethod, while stopSpan is in afterMethod. There is a problem here. If createSpan fails, or an exception occurs in some code before createSpan, causing createSpan not to be executed, then stopping Span in afterMethod will be a dangerous action. This will cause the parentSpan to be stopped prematurely. This will lead to TraceContext being destroyed prematurely, causing chain tracking interruption, and will also cause NPE when the upper plugin calls stopSpan.

Therefore, a mechanism is needed to ensure that in this scenario, stopSpan can only stop the span created in the current Interceptor. Since beforeMethod and afterMethod must execute in the same Interceptor instance, a instance variable can be used to solve this problem. My idea is to create a base class and provide createSpan and stopSpan methods in the base class. Interceptors that need to ensure stopping the corresponding span can inherit this base class, and then call the base class methods to replace ContextManager's createSpan and stopSpan methods.

### Use case

1. Skywalking Agent 8.14.0, HttpClient-4.x-plugin
2. SpringBoot Application, Controller requestMapping is "/test_http_client", server port=8080
3. The logic in the Controller uses HttpClient to request another URL : "http://localhost:8080:8080/test" (This URL is invalid and contains 2 port)
4. start application, request URL: "http://localhost:8080/test_http_client"

**Based on the current situation:** 
in beforeMethod, new URL() (this operation is before createSpan) will throw an error because the URL is invalid. This causes the span to not be created, but afterMethod's stopSpan will still be executed. At this time, the span stopped is the one created by Tomcat. And because there is only one span left, after this span is stopped, the TracingContext object in ThreadLocal will also be deleted. Therefore, calling stopSpan in Tomcat plugin's afterMethod will produce an NPE. If there are other RPC calls after the HttpClient call, those RPC call chains can no longer be linked with this chain either.

**Based on my base class design:** 
When calling stopSpan, it will check if the span variable in the current Interceptor instance has a value. If not, it will be ignored. If there is a value, the stop operation will be performed.

### Are you willing to submit a pull request to fix this on your own?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you think more carefully, you will see you are wrong.
You can never check span available when stop, because the active span could be another plugin created.

V2 interceptor has provided you context to propagate span between before and after. But still stop will fail if the active span is not this span.

Think again. SkyWalking had been there for 8+ years, this had been proposed and rejected many times, **because this proposal is wrong**.

**Comment by xiaqi1210** [comment]
> If you think more carefully, you will see you are wrong. You can never check span available when stop, because the active span could be another plugin created.
> 
> V2 interceptor has provided you context to propagate span between before and after. But still stop will fail if the active span is not this span.
> 
> Think again. SkyWalking had been there for 8+ years, this had been proposed and rejected many times, **because this proposal is wrong**.

1. I'm very curious about the "active span could be another plugin created" scenario you mentioned - could you give an example? I'm thinking this scenario should be special, fixed, and determined by how a plugin is designed, right? 

2. For a plugin like HttpClient, it must create and stop span in the same interceptor, it's impossible for the stopped span to be created by another plugin. So in this case, if we want to avoid errors when stopping spans, don't we need to do something to ensure it? The question is just whether the scope of this refactoring is only for this plugin or making it more general.

**Comment by wu-sheng** [comment]
I really am tired to explain this scenario. Really not interesting. 

You are only describing a very simple case of one plugin being up and running, how about 
- Two plugins having a bug at the same time? 
- One plugin closes span twice but only creates one?
- A plugin creates a span, but B plugin fails to create a span, but tries to close A's span?
- A needs to create a span in two interceptors?

I can see, many many common cases you didn't think through. Anyway, I most likely would not follow this discussion anymore. I have at least been asked dozens of times about this in 8 years. Forgive me don't want to repeat it again.
