### ISSUE TITLE
[Feature] Implement Shard Topology Calculation and Caching in BanyanDB Liaison Nodes

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#11238]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In our current BanyanDB architecture, each liaison node has to constantly sync the shard topology, which has led to increasing maintenance complexity and overhead.

We propose an enhancement to the working of liaison nodes in BanyanDB that would simplify system maintenance and improve efficiency. The idea is to have each liaison node calculate the shard topology based on the information of online nodes at a given time. Post calculation, the result would be stored into the local cache of the liaison node.

This way, the incoming data can be navigated to the target node by leveraging the information from the local cache, eliminating the need for constant topology sync across different liaison nodes. This approach not only simplifies the maintenance but also optimizes the data traffic by making use of local cache.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lujiajing1126** [comment]
After some investigation, I purpose the following design.

Basically, consistent hashing algorithm will be adopted to calculate the destination data node for a specific shard of an entity based on the following reasons,

1. Stable: with a given online nodes at a given time, different liaison nodes can get a consistent hash ring and the sharding results are irrelevant to the order of incoming metadata registration.
2. Performance: through different algorithms may have different performance footprint. There are already some Industrial-grade implementations, such as jump hash, maglev consistent hashing, etc.

Concerning the weight, quoted from https://dgryski.medium.com/consistent-hashing-algorithmic-tradeoffs-ef6b8e2fcae8

> Consistent hashing algorithm vary in how easy and effective it is to add servers with different weights. That is, send more (or less) load to one server as to the rest. With a ring hash, you can scale the number of replicas by the desired load. This can increase memory usage quite considerably. Jump Hash and Multi-Probe consistent hashing are trickier to use and maintain their existing performance guarantees. You can always add a second “shadow” node that refers back to an original node, but this approach fails when the load multiple is not an integer. One approach would be to scale all node counts by some amount, but this increases both memory and lookup time.

## Rejected alternative

WRR or IWRR: https://en.wikipedia.org/wiki/Weighted_round_robin

The sharding result may be related to the order of incoming metadata registration, for example metrics-A, metrics-B may cause different topologoy even if different liaison node share the same member information of all data nodes.

**Comment by wu-sheng** [comment]
`persistent` or `consistent`? What do you mean `no need to be persistent`?

`wrr` means the data is saved according to the load or data volume of the nodes?
