### ISSUE TITLE
Inaccurate search results of service search

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#1123]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?

5.0.0-alpha

- Which company or project?

Devcloud of Huawei

- What happen?

I would find `codeciControllernotifyTaskRemoved` in Service Search. When I have input `codeciController`，there is no correct result to select.

![image](https://user-images.githubusercontent.com/1960537/39339622-61b25f98-49fc-11e8-8720-08563373a992.png)

**Comment by wu-sheng** [comment]
This search caused by elastic search word analysis, In default, SkyWalking is using `stop word`, which includes `.`, `,`,`/` etc. . Maybe you could set IKAnalysis to ES.
