### ISSUE TITLE
optimize the method Tags#ofKey using the computeIfAbsent function to retrieve the present key in JDK 8 

### ISSUE THREAD

**Issue by peachisai** [apache/skywalking#11239]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://github.com/apache/skywalking/assets/96932958/9123ab11-586d-4440-a1f8-e92ceee75b22)
Tags#ofKey method using concurrentHashMap computeIfAbsent to retrieve value,but in jdk 8,it will acquires lock even the key present。
![image](https://github.com/apache/skywalking/assets/96932958/1232bec0-3760-476a-9982-50e92c3b1a8e)
If we choose call get; if value does not exist, call computeIfAbsent,it could improve performance
and get the atomic behavior.
Here are my test results 
![image](https://github.com/apache/skywalking/assets/96932958/dfe251e7-49f2-4b6c-96cf-9f55a5b07a73)
![image](https://github.com/apache/skywalking/assets/96932958/b22d2eb7-681d-4bf4-b01c-6adcbc0a5f09)

![image](https://github.com/apache/skywalking/assets/96932958/4c2b8e29-07d3-4e87-b6ec-d6d8fe5cc90d)
the problem was solved in the higher jdk version.
eg jdk 17
![image](https://github.com/apache/skywalking/assets/96932958/a1e030bb-cbe0-4d47-a1bc-5596da97e908)

But it still has a 50 % gap in my local environment
![image](https://github.com/apache/skywalking/assets/96932958/a5332957-113b-4c46-a3b9-a2be6eacba5e)
![image](https://github.com/apache/skywalking/assets/96932958/42109166-a0d8-4199-9ce0-415eb562a6e1)

some plugins of java agent call the function frequently. so i think it would improve these performances.

### Use case

![image](https://github.com/apache/skywalking/assets/96932958/ff858b9c-496b-4aa0-b159-52337d07d8b3)

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
But when I am looking at JDK 11, it seems already changed. 

<img width="824" alt="image" src="https://github.com/apache/skywalking/assets/5441976/8d081b28-adb9-4736-97ed-fb5e770507f6">

Compared to this change, actually, if you move `Tags.ofKey` as a static field in the plugin, it should be much faster.

I don't think this change would help a lot AFAIK.

**Comment by peachisai** [comment]
> But when I am looking at JDK 11, it seems already changed.
> 
> <img alt="image" width="824" src="https://user-images.githubusercontent.com/5441976/261855549-8d081b28-adb9-4736-97ed-fb5e770507f6.png">
> Compared to this change, actually, if you move `Tags.ofKey` as a static field in the plugin, it should be much faster.
> 
> I don't think this change would help a lot AFAIK.

yes, if you use jdk version >= 9, it has fix it, but java agent is available for jdk 8-17,of course using static
field is the best way.

**Comment by wu-sheng** [comment]
Do you face real product env issues? Or just reading codes. If this is a real product env issue, I would like to suggest you send pull requests to fix relative plugins by staticizing the tags.

**Comment by peachisai** [comment]
> staticizing

I used to know this. Here's some reference 
https://bugs.openjdk.org/browse/JDK-8161372
https://stackoverflow.com/questions/26481796/concurrenthashmap-computeifabsent/38362627#38362627

I also willing to fix those by stiaticizing the tags

**Comment by peachisai** [comment]
> Do you face real product env issues? Or just reading codes. If this is a real product env issue, I would like to suggest you send pull requests to fix relative plugins by staticizing the tags.

I used to know this. Here's some reference
https://bugs.openjdk.org/browse/JDK-8161372
https://stackoverflow.com/questions/26481796/concurrenthashmap-computeifabsent/38362627#38362627

I also willing to fix those by stiaticizing the tags

**Comment by wu-sheng** [comment]
According to https://bugs.openjdk.org/browse/JDK-8161372, this is a bug. And they were considering backport this 

> Let's consider backporting this to 8u.

And when I refer to 8u(https://wiki.openjdk.org/display/jdk8u/Main), it has been released at **Jul 31, 2023**.

Have you checked the source codes of the latest JDK8 release?

**Comment by peachisai** [comment]
> According to https://bugs.openjdk.org/browse/JDK-8161372, this is a bug. And they were considering backport this
> 
> > Let's consider backporting this to 8u.
> 
> And when I refer to 8u(https://wiki.openjdk.org/display/jdk8u/Main), it has been released at **Jul 31, 2023**.
> 
> Have you checked the source codes of the latest JDK8 release?

I haven't, but i think it was resolved in jdk 9
![image](https://github.com/apache/skywalking/assets/96932958/ebbdaf10-5841-4602-b06c-bcb9cc2a3935)
https://bugs.openjdk.org/browse/JDK-8184907

And according the comment
![image](https://github.com/apache/skywalking/assets/96932958/6301ad9f-6b4e-4c58-ae6a-1e4546de8a01)
I reproduce the same results in jdk 11

**Comment by wu-sheng** [comment]
Read this 
<img width="1193" alt="image" src="https://github.com/apache/skywalking/assets/5441976/c3a26db5-2a56-446d-b489-033a7b83c080">

But I don't have to time to check all 8u release one by one.

**Comment by peachisai** [comment]
> According to https://bugs.openjdk.org/browse/JDK-8161372, this is a bug. And they were considering backport this
> 
> > Let's consider backporting this to 8u.
> 
> And when I refer to 8u(https://wiki.openjdk.org/display/jdk8u/Main), it has been released at **Jul 31, 2023**.
> 
> Have you checked the source codes of the latest JDK8 release?




> Read this <img alt="image" width="1193" src="https://user-images.githubusercontent.com/5441976/261861529-c3a26db5-2a56-446d-b489-033a7b83c080.png">
> 
> But I don't have time to check all 8u release one by one.

It seems haven't fix in jdk 8
![image](https://github.com/apache/skywalking/assets/96932958/50ca7440-066a-41a7-ac45-c7cdae028be5)
I download the latest jdk8 version  (Java SE 8u381)

![image](https://github.com/apache/skywalking/assets/96932958/9cd8028e-c36e-438d-92ec-785368ed68fe)
![image](https://github.com/apache/skywalking/assets/96932958/1e200a07-b973-4347-9334-bed78da578f2)

**Comment by wu-sheng** [comment]
OK, whatever, once you moved the tag init from the codes, you should be good.
