### ISSUE TITLE
[Feature] Java Agent MongoDb support report db_instance

### ISSUE THREAD

**Issue by hxd123456** [apache/skywalking#11252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Java Agent MongoDb support report db_instance
for mongodb plugin(3.x/4.x) can support get db_instance info ,but We did not obtain this attribute in the version

### Use case

Java Agent MongoDb support report db_instance

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I assigned this to you. Please send a pull request within weeks before agent 9.0 release.

**Comment by hxd123456** [comment]
> I assigned this to you. Please send a pull request within weeks before agent 9.0 release.

Okay, I will send pull request within this week
