### ISSUE TITLE
[Bug] Not supported JVM GC  Metrics in ZGC?

### ISSUE THREAD

**Issue by yueluo02** [apache/skywalking#11280]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

UI can not display JVM GC Time and Count metrics when server use zgc.
Look the picture.
![image](https://github.com/apache/skywalking/assets/125534535/390d6230-f101-42b0-81c0-ef18cfe66740)

### What you expected to happen

UI can  display JVM GC  metrics when server use zgc.

### How to reproduce

- `JDK 17` and JVM params: ` -XX:+UseZGC`
- Skywalking Version: 9.5.0(Agent,Server,UI are all 9.5.0)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please don't report a bug for a thing never declared support. This is a misinformation.
AFAIK, ZGC in JDK17 is not supported in Java agent 9.0, which is still on release voting. https://github.com/apache/skywalking-java/blob/main/changes/changes-9.0.0.md

**Comment by yueluo02** [comment]
> Please don't report a bug for a thing never declared support. This is a misinformation. AFAIK, ZGC in JDK17 is not supported in Java agent 9.0, which is still on release voting. [apache/skywalking-java@`main`/changes/changes-9.0.0.md](https://github.com/apache/skywalking-java/blob/main/changes/changes-9.0.0.md?rgh-link-date=2023-08-30T09%3A24%3A26Z)

I tagged the issue `bug` because I found that the pr had been merged. 
- https://github.com/apache/skywalking/issues/8411
- https://github.com/apache/skywalking/pull/8425
I found relevant discussion in 2022, so I subconsciously thought this feature was supported.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/pull/8425 is indicated its milestone, aka, release version.

**Comment by wu-sheng** [comment]
Merging doesn't mean you could use it unless you compiled from the source codes by yourself.
