### ISSUE TITLE
The topology is too long

### ISSUE THREAD

**Issue by liuxin638507** [apache/skywalking#11297]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The topology view after 9.3.0 is too long. Therefore, you are advised to display it in a centralized location or in optional mode

### Use case

![image](https://github.com/apache/skywalking/assets/32058132/cfabf48b-92d0-4d46-9bb5-c6401a632ea4)

### Related issues

A more intuitive centralized topology or optional display classification is recommended

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Don't submit the repeated issues.
We answered this before.
This means your system is not distributed at all. The global topology don't have meaning for you.

**Comment by wu-sheng** [comment]
Global topology is only a fancy dashboard view, it has nothing really matters for daily ops.
