### ISSUE TITLE
skywalking webapp 页面不显示

### ISSUE THREAD

**Issue by zhoushuai1119** [apache/skywalking#11292]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

使用阿里云服务器部署Skywlaking 9.5.0，jdk版本17，oapserver和webapp启动看日志正常启动，但是访问页面无法访问，排除防火墙和端口问题。
浏览器consloe显示static/js/monaco-editor-97fd89d3.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

### What you expected to happen

正常访问页面

### How to reproduce

使用Skywalking 9.5.0部署

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you are keeping doing this, we have to block you.
Please follow community requirements. 
If you need Chinese channel, we have opened slack channel for that.
