### ISSUE TITLE
[Bug] Custom alarm rules are overwritten by 'resource/alarm-settings.yml'

### ISSUE THREAD

**Issue by ZhengBing520** [apache/skywalking#11311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Starting OAP, it was found that the custom alarm rules did not take effect, and during debugging, it was found that they were overwritten by resource/alarm settings. yml;

The reasons are as follows:
1. When BootstrapFlow#notifyAfterCompleted starts, the ConfigmapConfigurationProvider starts before the AlarmModuleProvider
2. When the FetchingConfigWatcherRegister#start method is started, alarm rules will be initialized
3. When the AlarmModuleProvider#notifyAfterCompleted method is started, the AlarmRulesWatcher#notify method is called, but the settingsString remains unchanged
4. The next time the FetchingConfigWatcherRegister#configSync method is called, the alarm rules will not be updated

### What you expected to happen

If there are custom rules and they have already been initialized, alarm-settings.yml should not be overwritten

### How to reproduce

1. add env SW_CONFIGURATION=k8s-configmap, KUBECONFIG='path/kube.conf'
2. run OAPServerStartUp.java

### Anything else

org.apache.skywalking.oap.server.library.module.BootstrapFlow#notifyAfterCompleted

<img width="396" alt="d28f7adb49cc4aefce722edcb6d2f466" src="https://github.com/apache/skywalking/assets/32810704/f42c3f29-d539-4383-b310-d9f34ba3da5c">

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@wankai123 Could youb recheck this?

@ZhengBing520 Are you going to submit the fix?

**Comment by wankai123** [comment]
I think it's a bug, and can simply be fixed by adding some `if` codes before reading `alarm-settings.yml` and notify rules in `AlarmModuleProvider`

**Comment by ZhengBing520** [comment]
> @ZhengBing520 Are you going to submit the fix?
Yes, I am willing to submit this fix

**Comment by ZhengBing520** [comment]
> I think it's a bug, and can simply be fixed by adding some `if` codes before reading `alarm-settings.yml` and notify rules in `AlarmModuleProvider`

Yes, I initially thought the same way
![image](https://github.com/apache/skywalking/assets/32810704/0a3b2fb9-0f98-41e7-a83e-79e25322c1c4)

**Comment by ZhengBing520** [comment]
But there is a certain probability of the following events occurring.
![image](https://github.com/apache/skywalking/assets/32810704/3587acbd-dc19-4bbb-9d6b-05035d767c1f)

**Comment by wankai123** [comment]
try adding a `ReentrantLock` and `BoolFlag` for example:
```java
    @Override
    public void notify(ConfigChangeEvent value) {
        lock.lock();
        try {
            if (value.getEventType().equals(EventType.DELETE)) {
                settingsString = null;
                notify(new Rules());
            } else {
                settingsString = value.getNewValue();
                RulesReader rulesReader = new RulesReader(new StringReader(value.getNewValue()));
                Rules rules = rulesReader.readRules();
                notify(rules);
            }
            notifiedByDynamicConfig.set(true);
        } finally {
            lock.unlock();
        }
    }

    public void notifyBeyondDynamicConfig(Rules newRules) {
        lock.lock();
        try {
            if (notifiedByDynamicConfig.get()) {
                return;
            }
            notify(newRules);
        } finally {
            lock.unlock();
        }
    }
```

**Comment by ZhengBing520** [comment]
> try adding a `ReentrantLock` and `BoolFlag` for example:
> 
> ```java
>         @Override
>     public void notify(ConfigChangeEvent value) {
>         lock.lock();
>         try {
>             if (value.getEventType().equals(EventType.DELETE)) {
>                 settingsString = null;
>                 notify(new Rules());
>             } else {
>                 settingsString = value.getNewValue();
>                 RulesReader rulesReader = new RulesReader(new StringReader(value.getNewValue()));
>                 Rules rules = rulesReader.readRules();
>                 notify(rules);
>             }
>             notifiedByDynamicConfig.set(true);
>         } finally {
>             lock.unlock();
>         }
>     }
> 
>     public void notifyBeyondDynamicConfig(Rules newRules) {
>         lock.lock();
>         try {
>             if (notifiedByDynamicConfig.get()) {
>                 return;
>             }
>             notify(newRules);
>         } finally {
>             lock.unlock();
>         }
>     }
> 
>     /**
>      * Don't invoke before the module finishes start
>      */
>     private void notify(Rules newRules) {
> ```
This is a great solution, but I have an alternative that doesn't require using locks. Could you please help me see if it's feasible.

```java
BootstrapFlow(Map<String, ModuleDefine> loadedModules) throws CycleDependencyException, ModuleNotFoundException {
        this.loadedModules = loadedModules;
        startupSequence = new ArrayList<>();

        makeSequence();
        startupSequence.sort(Comparator.comparing(ModuleProvider::priority).reversed());
    }

# ModuleProvider.java
/**
     * {@code ModuleProvider}s with higher priorities will be started earlier
     *
     * @return the priority of this {@code ModuleProvider}.
     */
    public int priority() {
        return 0;
    }

# AlarmModuleProvider.java
@Override
    public int priority() {
        ModuleDefine moduleProviderHolder = (ModuleDefine) getManager().find(ConfigurationModule.NAME);
        return moduleProviderHolder.provider().priority() + 1;
    }

```
This piece of code can start successfully locally.

**Comment by wu-sheng** [comment]
We only have a dependency mechanism, priority mechanism is very tricky. Ideally, if two modules are not depending on each other, the booting seq should be random.

**Comment by wu-sheng** [comment]
The lock solution above, is nearly costing nothing, because after the boot stage, there is no race condition, only the watcher timer is running for the method.
So, it should be good enough.

**Comment by ZhengBing520** [comment]
> The lock solution above, is nearly costing nothing, because after the boot stage, there is no race condition, only the watcher timer is running for the method. So, it should be good enough.

I will use the solution with a lock. Thank you for your responses. @wu-sheng @wankai123
