### ISSUE TITLE
Do the versions of apm-tool-logback-1.x and skywalking-agent match?

### ISSUE THREAD

**Issue by xiaoyuwang1987** [apache/skywalking#11318]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

gateway4.0.0 Cannot be generated as traceid

### What you expected to happen

gateway4.0.0 Cannot be generated as traceid

### How to reproduce

gateway4.0.0 Cannot be generated as traceid

### Anything else

gateway4.0.0 Cannot be generated as traceid

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
As it is not documented supported, it is simply not supported. https://skywalking.apache.org/docs/skywalking-java/v9.0.0/en/setup/service-agent/java-agent/supported-list/

So, this is not a bug.
