### ISSUE TITLE
[Feature] Banyandb web-ui query data for last 15 minutes cannot be auto refreshe end-time

### ISSUE THREAD

**Issue by hailin0** [apache/skywalking#11312]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Banyandb web-ui query data for last 15 minutes cannot be auto refreshe end-time

https://github.com/apache/skywalking/assets/14371345/0e6e8f1c-3039-432e-af93-6f31d3953205

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zesiar0** [comment]
I found web-ui query data cannot be auto refresh not only for the last 15 minutes, but also other options also cannot be auto refresh. And I want to fix it, please assign this issue to me.
