### ISSUE TITLE
[Bug] The field "TimeBucket" in "EndpointTraffic" will not be updated

### ISSUE THREAD

**Issue by QQQJoker** [apache/skywalking#11321]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The field "TimeBucket" in "EndpointTraffic" will not be updated with the update of the record and will remain the value it was first created with.

### What you expected to happen

The field "TimeBucket" in "EndpointTraffic" is expected to be updated along with the record update.

### How to reproduce

To verify if the TimeBucket field in EndpointTraffic changes with record updates, you can follow these steps:

Select a specific HTTP request, it can be any simple HTTP request, such as a GET request.

Start your application and inject the SkyWalking Agent into your application based on the Agent's configuration.

Send the HTTP request, ensuring that the request reaches your application and is being monitored by the SkyWalking Agent.

Wait for half an hour, allowing enough time for SkyWalking to collect and process the data.

Send the same HTTP request again.

Open the SkyWalking console and navigate to the EndpointTraffic monitoring page.

Locate the Endpoint corresponding to your HTTP request in the EndpointTraffic page and check if the TimeBucket field has changed.

If the value of the TimeBucket field has changed, it indicates that the SkyWalking Agent is correctly updating and recording the EndpointTraffic. If the TimeBucket field remains the same, it could be due to configuration issues or other factors.

By performing this experiment, you can verify if the TimeBucket field in EndpointTraffic changes with record updates. This will help you confirm the behavior and configuration of the SkyWalking Agent in handling EndpointTraffic data.

### Anything else

oap-server v9.5.0

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is not a bug. Time bucket field is never updated by design.
