### ISSUE TITLE
[Feature] The max length of service_name and service_instance_name cloud be configured

### ISSUE THREAD

**Issue by life-** [apache/skywalking#11327]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The default maximum length of service_name and service_instance_name is 50. But 50 is too short if service_name started with group_name.

So is it possible to set the length of service_name and service_instance_name through configuration?

### Use case

add two configuration in agent.config file

```
agent.service_name#length=${SW_AGENT_NAME_MAX_LENGTH:50}
agent.instance_name#length=${SW_AGENT_INSTANCE_NAME_MAX_LENGTH:50}
```

In ConfigInitializer.java  file, check if these two params is configured

```java
// Convert the value into real type
final Length lengthDefine = field.getAnnotation(Length.class);
if (lengthDefine != null) {                                                                                                                                   
    int lengthLimited = lengthDefine.value();                                                                                                                 
    String lengthKey = String.format("%s#length", configKey);                                                                                                 
    if (properties.containsKey(lengthKey)) {                                                                                                                  
        lengthLimited = Math.max(lengthLimited, Integer.valueOf(properties.getProperty(lengthKey, "0")));                                                     
    }                                                                                                                                                         
    if (propertyValue.length() > lengthLimited) {                                                                                                             
        StringUtil.cut(propertyValue, lengthLimited);                                                                                                         
        System.err.printf("The config value will be truncated , because the length max than %d : %s -> %s%n", lengthDefine.value(), configKey, propertyValue);
    }                                                                                                                                                         
}
```

### Related issues

[Here](https://github.com/apache/skywalking/discussions/11324) is the discussion about this function.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This had been discussed https://github.com/apache/skywalking/discussions/11324.

@life- Actually, you don't have to recreate an issue. A resolved discussion is good enough before sending a pull request.
