### ISSUE TITLE
[BanyanDB] Unified memory data structure and memory tracking

### ISSUE THREAD

**Issue by sollhui** [apache/skywalking#11338]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Memory Data Structure
Memory management is an important part of databases, and a unified memory structure can better achieve memory management and read/write. At the same time, memory alignment and padding can be used to optimize performance.

### Memory tracking
It is necessary to monitor the allocation and recycling of memory, and reasonable strategies can be made based on the usage of memory, such as canceling certain queries to avoid OOM situations, which greatly helps with the stability of the database.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@hanahmily Please be clear about the milestone.

The only known key feature for 0.5 is new file structure to replace the kv system.

**Comment by HHoflittlefish777** [comment]
Anyone who interested in it can discuss it and have a try.

**Comment by caicancai** [comment]
hi, is there a specific project design document I can see

**Comment by wu-sheng** [comment]
> hi. Is there a specific project design document to understand this part of the work ？

The project is in the dev stage, iterate fast by the initial team. The best way is getting started from reading the current project docs and codes first, and understand how it works with SkyWalking OPA/backend server.

**Comment by wu-sheng** [comment]
General docs are available here, https://skywalking.apache.org/docs/skywalking-banyandb/next/readme/. But it doesn't include TODO and WIP things.

**Comment by caicancai** [comment]
> > hi. Is there a specific project design document to understand this part of the work ？
> 
> The project is in the dev stage, iterate fast by the initial team. The best way is getting started from reading the current project docs and codes first, and understand how it works with SkyWalking OPA/backend server.

Thank you for your reply. I'll take a look at the code, see if I can help

**Comment by hanahmily** [comment]
The memory tracker is tracked by #12798

**Comment by hanahmily** [comment]
The unified memory data structure presents significant challenges for a Golang-based application. Therefore, I am closing this issue.
