### ISSUE TITLE
[Bug] The display height of the link tree structure on the right side of the trace module in skywalking is too low to display the complete number structure.

### ISSUE THREAD

**Issue by errorwhy** [apache/skywalking#11344]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

In the trace module of skywalking, when the number of traces in the left trace list is small, the display height of the right link tree structure is too low to display the complete number structure.
![Snipaste_2023-09-20_11-10-28](https://github.com/apache/skywalking/assets/76686791/f54028d7-4d1a-43b4-917a-1aace77ac6b2)

### What you expected to happen

In the project code d3-trace-tree. ts file, the dom calculation height displayed in the tree structure is too low. A minimum height of approximately 500px should be set to facilitate users to view the complete tree structure
![Snipaste_2023-09-20_11-20-19](https://github.com/apache/skywalking/assets/76686791/c3247b38-980e-481c-a36f-b6e5e135bc56)

### How to reproduce

When the number of traces on the left side is small, click the tree structure button on the right to view and reproduce the problem
![Snipaste_2023-09-20_11-22-48](https://github.com/apache/skywalking/assets/76686791/7ea69117-9f9e-4654-b1e8-3720c28a8514)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I just tried query based on traced-ID and service, there is only one segment on the left side list, it seems working well.

<img width="1916" alt="image" src="https://github.com/apache/skywalking/assets/5441976/7110212c-9216-472d-aa8e-83eadf87a0bb">


What are the differences on your side? Are you using the latest version? You could try this as well on skywalking.apache.org#demo through your local browser.

**Comment by errorwhy** [comment]
Please click on the tree button on the right
![Snipaste_2023-09-20_11-32-57](https://github.com/apache/skywalking/assets/76686791/a850f83c-b18c-4b64-a5c4-321e42ffac62)

**Comment by heyanlong** [comment]
<img width="1437" alt="image" src="https://github.com/apache/skywalking/assets/3367958/e10b1d0c-29c2-4949-b0af-7928653f2dc0">
I got this problem and I tried to fix it

**Comment by wu-sheng** [comment]
@errorwhy I see, you mean only the tree mode.

@heyanlong Should I assign to you for the fix?

**Comment by heyanlong** [comment]
> @errorwhy I see, you mean only the tree mode.
> 
> @heyanlong Should I assign to you for the fix?

@wu-sheng Ok 👌

**Comment by wu-sheng** [comment]
cc @Fine0830
