### ISSUE TITLE
The call chain icons can not updated after change the service[Bug] 

### ISSUE THREAD

**Issue by zhourunjie1988** [apache/skywalking#11357]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

Located in the **trace** tab, if you are currently viewing the **tree** diagram, the call chain icons can not updated after change the service.
![image](https://github.com/apache/skywalking/assets/61196609/192a11c0-519e-4aaa-81b5-09a976584f97)

### What you expected to happen

Maybe In this file _src/views/dashboard/related/trace/components/Tree.vue_, the list value should be changed to **computed property**. 
```typescript
// original code
const list = ref<string[]>([]);
onMounted(() => {
    list.value = Array.from(new Set(props.data.map((i: Span) => i.serviceCode)));
})

// modify
const list = computed(() => Array.from(new Set(props.data.map((i: Span) => i.serviceCode))));
``` 

### How to reproduce

First check the tree diagram of a certain trace, then switch to another service and click search. At this time, you can see that the call chain icons have not been updated.
![image](https://github.com/apache/skywalking/assets/61196609/7a418b9e-5cfb-4d78-bbc4-90fb0101d7b4)

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Fine0830** [comment]
Could you submit a pr to fix this? @zhourunjie1988

**Comment by zhourunjie1988** [comment]
> Could you submit a pr to fix this? @zhourunjie1988

ok, I have submitted a pr to the skywalking-booster-ui project.
