### ISSUE TITLE
[Bug] zipkin http interface, successful processing should return 202 status code instead of 200 status code

### ISSUE THREAD

**Issue by jiewang-2023** [apache/skywalking#11355]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

We used dapr to send the tracing data to Skywalking OAP in zipkin format, and found that the HTTP status code responded by Skywalking OAP was not 202, but 200.
  The official Zipkin protocol specifies returning a 202 status code. If the Dapr component determines that the status code is not 202, it determines that the sending failed.

zipkin official http protocol format 
https://zipkin.io/zipkin-api/#/default/post_spans
![image](https://github.com/apache/skywalking/assets/45024884/b8c72c8f-136a-407d-b33d-d1efdfb5e826)

### What you expected to happen

I used the curl command to test and found that Skywalking oap responded with a 200 status code, and we expected the status code to be 202
![image](https://github.com/apache/skywalking/assets/45024884/500b9b7e-7f84-42b4-b88e-f87cc8977653)

It is recommended to refer to the openzipkin repo
https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin2/server/internal/ZipkinHttpCollector.java

### How to reproduce

Push zipkin format data to Skywalking OAP's zipkin data receiving interface (http://{ip}:9411/api/v2/spans)

curl --location 'http://ip:9411/api/v2/spans' --header 'Content-Type: application/json' --data '[
  {
        "timestamp": 1695376149000000,
        "duration": 1570,
        "traceId": "5c818da0ee3b151e4568c56935063d72",
        "id": "f2bbd1c4511ad87a",
        "name": "/v1.0/metadata",
        "kind": "CLIENT",
        "localEndpoint": {
            "serviceName": "hello-tracing"
        },
        "tags": {
            "dapr.api": "GET /v1.0/metadata",
            "dapr.protocol": "http",
            "dapr.status_code": "200",
            "otel.library.name": "dapr-diagnostics",
            "service.name": "hello-tracing"
        }
    }
]'

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please update title. You submit an empty title issue.
