### ISSUE TITLE
[Feature] Helm Chart support Skywalking 9.6.0

### ISSUE THREAD

**Issue by omegazeng** [apache/skywalking#11352]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Read the doc, you could set the version number.
