### ISSUE TITLE
[Feature] Support for Auto-Injection of traceId in JsonLayout for log4j2

### ISSUE THREAD

**Issue by yankooo** [apache/skywalking#11361]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Is your feature request related to a problem? Please describe.

Currently, `apm-toolkit-log4j-2.x` only supports the auto-injection of `traceId` for logs using `PatternLayout`. As a result, logs that use `JsonLayout` do not include the `traceId`, which makes tracing of log events challenging when logs are in JSON format.

https://logging.apache.org/log4j/2.x/manual/layouts.html#JSONLayout

### Feature Description

It would be beneficial to enhance `apm-toolkit-log4j-2.x` to support the auto-injection of `traceId` in logs using `JsonLayout`. This feature would ensure that `traceId` is included in log events, regardless of whether `PatternLayout` or `JsonLayout` is used, thus making the tracing of log events consistent across different log formats.

### Describe alternatives you've considered

A workaround for this issue is to manually insert the `traceId` into each log event that uses `JsonLayout`. However, this approach is not optimal, as it requires additional coding effort and can lead to inconsistencies in how `traceId` is included in log events.

### Additional context

Enabling support for auto-injection of `traceId` in `JsonLayout` will be highly advantageous for applications that rely on JSON-formatted logs, and it will enhance the adaptability and usability of Skywalking APM in varied logging environments.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@yankooo Do you have an estimated time for this?

**Comment by wu-sheng** [comment]
No update in 2 weeks. This seems a feature suggestion only.
