### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NecoLiang** [apache/skywalking#11376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I according to the official documentation to the introduction of the "github.com/apache/skywalking-go", after the project go build out of the question, prompt is as follows:
/ github.com/aliyun/alibaba-cloud-sdk-go@v1.61.1704/sdk/errors/server_error.go:21:2: zip: not a valid zip file;
/ github.com/spf13/viper@v1.16.0/internal/encoding/toml/codec.go:4:2: zip: not a valid zip file;
/ github.com/prometheus/client_golang@v1.12.2/prometheus/process_collector_other.go:20:2: zip: not a valid zip file
How can I solve this problem

### What you expected to happen

I hope after introducing "github.com/apache/skywalking-go" according to the official document, implement new build command can success enabled SKW monitoring

### How to reproduce

In macos go engineering introduction "github.com/apache/skywalking-go", and then execute the go build

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I said, post this in the discussion.
