### ISSUE TITLE
After integrating Skywalking agent with Springcloud gateway 4, traceid cannot be printed

### ISSUE THREAD

**Issue by xiaoyuwang1987** [apache/skywalking#11398]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

![image](https://github.com/apache/skywalking/assets/24749103/d134a297-b864-45a4-b59c-76fc9eec9301)
日志不会从gateway开始生成，用的agent版本9.0.0，服务集成apm-toolkit-logback-1.x也是9.0.0

### What you expected to happen

如何解决

### How to reproduce

想要日志从网关开始查起

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Gateway 4.x is not supported. No one supported a PR about this.

**Comment by wu-sheng** [comment]
All supported things are listed here. https://skywalking.apache.org/docs/skywalking-java/v9.0.0/en/setup/service-agent/java-agent/supported-list/

And please use English next time. We would not follow Chinese issue on GitHub. Only Slack CN channel is recommended for Chinese.

**Comment by JustUse** [comment]
> Gateway 4.x is not supported. No one supported a PR about this.

when can skywalking-java-agent support gateway 4.x , do you have any plan?

**Comment by BothSavage** [comment]
> > 不支持网关 4.x。没有人支持关于此事的公关。
> 
> skywalking-java-agent什么时候可以支持gateway 4.x，你们有什么计划吗？

https://bothsavage.github.io/article/240121-skywaking

**Comment by BothSavage** [comment]
> ### 询问前先搜索
> * [x] [我在问题](https://github.com/apache/skywalking/issues?q=is%3Aissue)中搜索过，没有发现类似的问题。
> 
> ### Apache SkyWalking 组件
> Java 代理 (apache/skywalking-java)
> 
> ### 发生了什么
> ![图像](https://private-user-images.githubusercontent.com/24749103/274176330-d134a297-b864-45a4-b59c-76fc9eec9301.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzU0MDEsIm5iZiI6MTcwNTc3NTEwMSwicGF0aCI6Ii8yNDc0OTEwMy8yNzQxNzYzMzAtZDEzNGEyOTctYjg2NC00NWE0LWI1OWMtNzZmYzllZWM5MzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE4MjUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZWJiNDQ4NmFlMjZkOGQzZjFlZTRkNDc1MjRlZGI4NjlkMDg5ZWY0Njg3MGIwMzA0MTVlZDM5OTlhNmJjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BdC_rWL5t9apbewxFCcFwSE6fFGmo1MUIwI7aaxw1kc) 日志不会从网关生成开始，使用的代理版本9.0.0，服务集成apm-toolkit-logback-1.x也是9.0.0
> 
> ### 您期望发生什么
> 如何解决
> 
> ### 如何重现
> 想要的日志从网关开始查起
> 
> ### 还要别的吗
> _没有反应_
> 
> ### 您愿意提交拉取请求来自行修复吗？
> * [x] 是的，我愿意自己提交拉取请求！
> 
> ### 行为守则
> * [x] 我同意遵守该项目的[行为准则](https://www.apache.org/foundation/policies/conduct)

https://bothsavage.github.io/article/240121-skywaking
