### ISSUE TITLE
[Bug] Some classes use shaded version of Guava's `Charsets` class

### ISSUE THREAD

**Issue by Marcono1234** [apache/skywalking#11435]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The following classes use a shaded / repackaged version of Guava's `Charsets` class. I assume this was done by accident (possibly due to IDE completion) since Guava also seems to be a dependency.

- https://github.com/apache/skywalking/blob/1a27da5727303738b554780906838e73af008e42/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/profiling/ebpf/storage/EBPFProcessProfilingScheduleDispatcher.java#L22
- https://github.com/apache/skywalking/blob/1a27da5727303738b554780906838e73af008e42/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/profiling/ebpf/storage/EBPFProfilingDataRecord.java#L22
- https://github.com/apache/skywalking/blob/1a27da5727303738b554780906838e73af008e42/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/source/EBPFProcessProfilingSchedule.java#L22

As side note: These usages of `Charsets` can probably also be replaced with JDK's [`StandardCharsets`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/charset/StandardCharsets.html) added in Java 7.

### What you expected to happen

`com.google.common.base.Charsets` or `
java.nio.charset.StandardCharsets` should be imported

### How to reproduce

_not applicable, see description above_

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This class is from Armeria project, not us.
If you feel there is an issue, please report to them.
