### ISSUE TITLE
[Feature][UI] Implement a dark theme

### ISSUE THREAD

**Issue by Fine0830** [apache/skywalking#11453]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Enhance UI themes, implement switching between dark and light themes.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If this works well, we could pick dark by default, or pick browser/OS style.
