### ISSUE TITLE
[Bug] SkyWalking Java Agent performance degradation after upgrading to 9.0

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#11460]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

After upgrading to SW 9.0, we've observed increasing application start-up in the production cluster.

For the same application, using two different Agent versions,

- SW Agent 9.0: `2023-10-26 19:12:37.143 [main] INFO  com.wosai.middleware.Application.logStarted - Started Application in 10.733 seconds (JVM running for 21.072)`
- SW Agent 8.15: `2023-10-26 19:18:12.700 [main] INFO  com.wosai.middleware.Application.logStarted - Started Application in 10.538 seconds (JVM running for 16.828)`

### What you expected to happen

Roughly the same start-up time and CPU consumption.

### How to reproduce

Run a Java application with 8 and 9.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Basically I wouldn't be surprised of this, considering what was changed for 9.0.0 kernel. 
It is a tradeoff to make instrumentation classes predictable, it affects booting and weave performance.

**Comment by wu-sheng** [comment]
You could try the version without the change, I believe the latency will be gone.

**Comment by lujiajing1126** [comment]
After some investigation, I found that 

```java
.with(AgentBuilder.DescriptionStrategy.Default.POOL_FIRST);
```

changing this strategy leads to almost double CPU usage during the startup. What is the motivation for the change from https://github.com/apache/skywalking-java/pull/561? @kylixs

**Comment by wu-sheng** [comment]
What was the value by default?

**Comment by lujiajing1126** [comment]
> What was the value by default?

HYBRID

**Comment by kylixs** [comment]
@lujiajing1126 The POOL_FIRST solution is to solve the retransform failure problem by obtaining the original bytecode and reprocessing it.  
What is the approximate number of classes that need to be enhanced in this case? Are multiple Agents to be mounted?

**Comment by lujiajing1126** [comment]
> @lujiajing1126 The POOL_FIRST solution is to solve the retransform failure problem by obtaining the original bytecode and reprocessing it.

I see.

> Are multiple Agents to be mounted?

No.

> What is the approximate number of classes that need to be enhanced in this case? 

As shown in the logs, 79 in total.

**Comment by kylixs** [comment]
@lujiajing1126 Please try this patch: https://github.com/apache/skywalking-java/pull/634

**Comment by kylixs** [comment]
@lujiajing1126 Please try about new solution: https://github.com/apache/skywalking-java/pull/637
