### ISSUE TITLE
[Feature] skywalking-nginx-lua，must be configed in each location，can global config once and use for all location？

### ISSUE THREAD

**Issue by jxplus** [apache/skywalking#11477]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

skywalking-nginx-lua，must be configed in each location，can global config once and use for all location？

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I am afraid not. This is not controlled by us, it is Nginx style thing.

And this is a discussion, not a feature owned by someone. Closing.
