### ISSUE TITLE
[Feature] Selection Algorithm for Merge Operation

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#11473]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

dependent #11472 

This issue proposes an algorithm for selecting eligible parts for the tiered merge operation. The algorithm is based on sorting parts by their minimum timestamp and size, and it focuses on merging only adjacent parts to optimize the merging process and minimize I/O operations.

The algorithm does not consider data deletion as a factor in the selection process, as Time-To-Live (TTL) is assumed to handle data expiry and deletion effectively.

- **Timestamp-Based Sorting**: The algorithm should sort the parts based on their minimum timestamp, ensuring chronological order.
- **Size-Based Sorting**: Along with the timestamp, the size of the parts should also be a factor in sorting and selection. Smaller parts will be prioritized for merging to larger ones.
- **Adjacent Merging**: The algorithm will merge only adjacent parts, maintaining the order and minimizing unnecessary I/O operations.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HHoflittlefish777** [comment]
Plaese assign to me.

**Comment by hanahmily** [comment]
Fixed by https://github.com/apache/skywalking-banyandb/pull/371
