### ISSUE TITLE
[Feature] [TSDB]Stream column storage

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#11474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This issue proposes a new columned-base storage for the Stream module as #11472 

Measure and Stream are two different approaches for handling data. Stream does not require a `Field` file, while Measure does. Measure has a buffer that allows it to identify and remove duplicate data points, whereas Stream does not have this capability. Incoming data is written to a batch and immediately flushed onto the disk in Measure.

Since both modules will share basic operations, this task will begin after implementing #11472.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ButterBright** [comment]
Hi, I'm interested in this issue. May I have a try?
