### ISSUE TITLE
[Bug]  php don't have endponit  info

### ISSUE THREAD

**Issue by aclstack** [apache/skywalking#11486]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

i use docker images start skywaking  and skywaking-ui
docker run --name oap --restart always -d -p 11800:11800 -p 12800:12800  apache/skywalking-oap-server:9.5.0
docker run --name oap-ui --restart always -d -p 12580:8080 -e SW_OAP_ADDRESS=http://192.168.9.247:12800 apache/skywalking-ui:9.5.0

in php container, this php info is 
php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
gd
hash
iconv
igbinary
json
libxml
mbstring
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
skywalking_agent
sockets
sodium
SPL
ssh2
standard
swoole
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

skywalking_agent.ini
extension=skywalking_agent.so

skywalking_agent.enable=On
skywalking_agent.skywalking_version=9
skywalking_agent.log_level=Debug
skywalking_agent.log_file=/tmp/sky.log
skywalking_agent.server_addr=192.168.9.247:11800

php code: 2.php
<?php
  $http = new Swoole\Http\Server('0.0.0.0', 9999);

$http->on('Request', function ($request, $response) {
    $response->header('Content-Type', 'text/html; charset=utf-8');
    $response->end('<h1>Hello Swoole. #' . rand(1000, 9999) . '</h1>');
});

$http->start();

skywalking_agent.log
2023-11-02T07:03:11.569411Z  INFO skywalking_agent::module: Starting skywalking agent service_name="hello-skywalking" service_instance="85973406911653529770130878522534491500@172.17.0.4" skywalking_version=9 heartbeat_period=30 properties_report_period_factor=10
2023-11-02T07:03:11.571008Z DEBUG skywalking_agent::worker: Starting worker...
2023-11-02T07:03:11.571160Z DEBUG skywalking_agent::worker: Bind unix stream socket_file="/tmp/skywalking-agent/60925fb1b3167.sock"
2023-11-02T07:03:11.571336Z DEBUG skywalking_agent::reporter::reporter_grpc: Create Endpoint url="http://192.168.9.247:11800"
2023-11-02T07:03:11.571366Z DEBUG skywalking_agent::reporter::reporter_grpc: Skywalking TLS info enable_tls=false ssl_trusted_ca_path="" ssl_key_path="" ssl_cert_chain_path=""
2023-11-02T07:03:11.575336Z  INFO connect: skywalking_agent::reporter::reporter_grpc: Skywalking server connected uri="http://192.168.9.247:11800/"
2023-11-02T07:03:11.575381Z  INFO skywalking_agent::reporter::reporter_grpc: Worker is ready...
2023-11-02T07:03:11.576111Z DEBUG skywalking_agent::worker: Report instance properties props=Properties { inner: {"Process No.": ["127"], "language": ["php"], "ipv4": ["172.17.0.4"], "hostname": ["766b2c633708"], "OS Name": ["Linux"]} }

skywalking_agent info
version => 0.7.0
authors => Apache Software Foundation:jmjoy <jmjoy@apache.org>:Yanlong He <heyanlong@apache.org>

Directive => Local Value => Master Value
skywalking_agent.authentication => no value => no value
skywalking_agent.enable => 1 => 1
skywalking_agent.enable_tls => 0 => 0
skywalking_agent.enable_zend_observer => 0 => 0
skywalking_agent.heartbeat_period => 30 => 30
skywalking_agent.kafka_bootstrap_servers => no value => no value
skywalking_agent.kafka_producer_config => {} => {}
skywalking_agent.log_file => /tmp/sky.log => /tmp/sky.log
skywalking_agent.log_level => Debug => Debug
skywalking_agent.properties_report_period_factor => 10 => 10
skywalking_agent.reporter_type => grpc => grpc
skywalking_agent.runtime_dir => /tmp/skywalking-agent => /tmp/skywalking-agent
skywalking_agent.server_addr => 192.168.9.247:11800 => 192.168.9.247:11800
skywalking_agent.service_name => hello-skywalking => hello-skywalking
skywalking_agent.skywalking_version => 9 => 9
skywalking_agent.ssl_cert_chain_path => no value => no value
skywalking_agent.ssl_key_path => no value => no value
skywalking_agent.ssl_trusted_ca_path => no value => no value
skywalking_agent.worker_threads => 0 => 0

when i access  127.0.0.1:9999   i can see service name : hello-skywalking
i'm into hello-skywalking don't find endpoints 
![image](https://github.com/apache/skywalking/assets/17819228/58fced04-d2b1-4c68-8416-b3c30c998ef1)
![image](https://github.com/apache/skywalking/assets/17819228/cbaeb4dc-bdc0-40b4-a802-338215c42881)

### What you expected to happen

find Endpoint info

### How to reproduce

php code 
2.php
<?php
  $http = new Swoole\Http\Server('0.0.0.0', 9999);

$http->on('Request', function ($request, $response) {
    $response->header('Content-Type', 'text/html; charset=utf-8');
    $response->end('<h1>Hello Swoole. #' . rand(1000, 9999) . '</h1>');
});

$http->start();

php 2.php

curl 127.0.0.1:9501/

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You at least should be format your question in a good way.
This is not a practice of asking for a help.
