### ISSUE TITLE
[Bug]  The 'findEndpoint' method 'limit' condition does not work when using Elasticsearch storage

### ISSUE THREAD

**Issue by ding-9** [apache/skywalking#11487]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The 'Endpoint' page returns more than 20 pieces of data, with the storage policy configured as elasticsearch.

[MetadataQueryEsDAO.java#L278](https://github.com/apache/skywalking/blob/19a7fa525d38bf2aaf407c38d70d0d8c75cc3359/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/query/MetadataQueryEsDAO.java#L278)

The 'scroll' query way actually returns all the hit data.

### What you expected to happen

The 'limit' condition can work.

### How to reproduce

make a 'findEndpoint' query and specify a smaller 'limit'.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@kezhenxu94 I saw you created a fix branch. Is that verified?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 I saw you created a fix branch. Is that verified?

I hardly forgot the branch I created, just opened a pull request here https://github.com/apache/skywalking/pull/11523
