### ISSUE TITLE
[NGINX LUA] support record traceid into nginx access log in 0.6.0?

### ISSUE THREAD

**Issue by jxplus** [apache/skywalking#11480]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I saw this discuss in year 2021, and now support or not?

### Related issues

https://github.com/apache/skywalking/issues/7582

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No one is working on newer Nginx plugin. It is what it is now until new active contributor showing up.
