### ISSUE TITLE
[Feature]  Optimize Index Definition for BanyanDB Module in OAP

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#11497]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The current index definition for the BanyanDB module in OAP needs optimization to increase efficiency and improve performance. This issue focuses on moving different identifiers from `indexRule` to `Entity` in `Measure` and simplifying the `network_address_alias` entity.

**Details:**

1. **Common Metrics**: Move `service_id` from `indexRule` to `Entity` in `Measure`. This change will streamline the process of accessing the service information by centralizing the identifiers into `Entity` within `Measure`.

2. **Relation Metrics**: Move `service_id`, `instance_id`, and `endpoint_id` to `Entity`. By moving these identifiers to `Entity`, we can improve the retrieval of relation metrics and enhance the overall performance of the system.

3. **Network_address_alias**: Retain only `last_update_time_bucket`. Simplifying the `network_address_alias` will reduce unnecessary complexity and improve efficiency.

The proposed changes are expected to optimize the index definitions, improve the system's performance, and simplify the overall structure of the BanyanDB module in OAP.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
So, this is only OAP side code change, and the protocol between OAP and DB is stable.

**Comment by wu-sheng** [comment]
@hanahmily I removed this from 9.7 as it seems not required in the version.

**Comment by wu-sheng** [comment]
According to the latest discussion, we need to make BanyanDB APIs and implementation support accept multiple series definitions, rather than one. Each series definition could have multiple fields. This could provide better query support in following typical scenarios
1. Query metrics by ts and entity ID.
2. Store all query relative fields in one file. Nowadays, some are in series ID files, and others are in the tags family.

FYI @hanahmily

**Comment by hanahmily** [comment]
1,2 are fixed by removing the indexed data from the data storage. 3 is moved to #12638
