### ISSUE TITLE
[Feature] Implement Inverted Index for SeriesDatabase

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#11496]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This issue proposes improvements to the SeriesDatabase by implementing an inverted index. The goal of this enhancement is to ensure that the order of tags in the `Entity` does not affect the query speed. In addition, it aims to introduce a cache to prevent unnecessary data from entering the index. This cache will be implemented using fastcache, automatically evicting old or rarely used SeriesIDs.

1. **Inverted Index**: Implementing an inverted index in SeriesDatabase will optimize query speed, making it independent of the order of tags in `Entity`.

2. **Cache Optimization**: Introducing a cache will prevent irrelevant data from entering the index. This will be implemented using fastcache, known for its automatic eviction of old or rarely used SeriesIDs, thus optimizing the memory usage for small-size values.

The proposed changes aim to enhance the performance of the SeriesDatabase in terms of query speed and memory usage.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zesiar0** [comment]
please assign to me, thanks.

**Comment by lujiajing1126** [comment]
> please assign to me, thanks.

Assigned to u
