### ISSUE TITLE
[Feature] Support to search by the parent name of Measure

### ISSUE THREAD

**Issue by LinuxSuRen** [apache/skywalking#11502]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

As you can see, it can only search by the child item's name instead of the parent name.

![image](https://github.com/apache/skywalking/assets/1450685/7170d5b8-f27a-4026-9286-1c2babcf8c3b)
![image](https://github.com/apache/skywalking/assets/1450685/eaeabd10-fac7-4e63-945b-bdecd6a61b1a)
https://github.com/apache/skywalking-banyandb/blob/4e92c42997ee64e449bb86fd8478420eff20772b/ui/src/components/Aside/index.vue#L251

### Use case

I wish the parent name is searchable. Of course, I'm still a newbie of BanYanDB. Please corrrect me if I misunderstand anything. Thanks for your time.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
What does this screenshot mean? The style looks like BanyanDB UI, but the name doesn't make sense.

Could you be more clear about what is being proposed to change?

**Comment by LinuxSuRen** [comment]
The screenshots come from BanYanDB UI. The name was generated randomly. I just try to search the measure items by name. I found out it does not work well. I seems only search the child item's name acoording to the source code.

**Comment by wu-sheng** [comment]
When you test and send a pull request, please make sure you don't put the random data. The easiest way is to run OAP on the BanyanDB, and see the measure. After all, OAP + BanyanDB is the primary use case so far, and will be for a very long time.
