### ISSUE TITLE
[Feature] when support nginx-opentracing ?

### ISSUE THREAD

**Issue by jxplus** [apache/skywalking#11513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

when use nginx-opentracing , need a skywalking-tracer。
I’m afraid not support now, and has the plan to support it?

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
OpenTracing is dead. And we don't support that.
