### ISSUE TITLE
[Feature] [SWCK] Integrate with opensearch storage types in Storage CRD

### ISSUE THREAD

**Issue by hwzhuhao** [apache/skywalking#11542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Since skywalking has supported and tested the following versions of OpenSearch:
1.1.0, 1.3.10
2.4.0, 2.8.0
Can we provide a storage type like opensearch to better integrate it ?

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you want to submit the codes, go ahead.

**Comment by wu-sheng** [comment]
I closed this, as this feature is up to you. We are not tracking and promised to have this in any milestone.

Once you submit a pull request, we will assign the review and milestone.
