### ISSUE TITLE
[Feature] Skywalking agent plugin to support resilence4j

### ISSUE THREAD

**Issue by liyunshan123** [apache/skywalking#11540]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We use skywalking as the trace system, and our project use resilence4j as the circuit breaker,  I found that our trace chain only has the top layer of data，while I remove the dependence of resilece4j, skywalking works well. resilence4j is a popular circuit breaker，so I sugguest that develop the plugin to support resilece4j.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> so I sugguest that develop the plugin to support resilece4j.

Sorry. SkyWalking community's maintainer doesn't take part in this kind of feature request. If you want to develop and contribute this plugin to upstream, we will review it.
