### ISSUE TITLE
[Bug] Excuse me, after Docker Compose upgraded Apache/skywalking oap server to version 9.6.0, Apache/skywalking ui to version 9.6.0, and skywalking agent to version 9.0.0, has anyone encountered the issue of skywalking agent and oap being unable to communicate? The previous versions of Apache/skywalking oap server, Apache/skywalking ui, and skywalking agent were both 8.6.0 and 8.9.0, which are normal for use

### ISSUE THREAD

**Issue by cfy3133** [apache/skywalking#11550]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Skywalking oap and skywalking agent cannot connect and communicate

### What you expected to happen

Skywalking oap and Skywalking agent can connect and communicate normally

### How to reproduce

The yaml configuration file for Docker Compose startup with issues after upgrade is as follows:
version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - skywalking
    environment:
      TZ: Asia/Shanghai
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

  oap:
    image: apache/skywalking-oap-server:9.6.0
    container_name: oap
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - "1234:1234"
      - "11800:11800"
      - "12800:12800"
    networks:
      - skywalking
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      JAVA_OPTS: "-Xms2048m -Xmx2048m"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

  ui:
    image: apache/skywalking-ui:9.6.0
    container_name: ui
    restart: always
    depends_on:
      - oap
    links:
      - oap
    ports:
      - "28080:8080"
    networks:
      - skywalking
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: http://oap:12800
      SW_HEALTH_CHECKER: default
      SW_TIMEOUT: 200000
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

networks:
  skywalking:
    driver: bridge

The yaml configuration file for the Docker Compose startup without any issues before upgrading is as follows:
version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - skywalking
    environment:
      TZ: Asia/Shanghai
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

  oap:
    image: apache/skywalking-oap-server:8.6.0
    container_name: oap
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - "1234:1234"
      - "11800:11800"
      - "12800:12800"
    networks:
      - skywalking
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      JAVA_OPTS: "-Xms2048m -Xmx2048m"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

  ui:
    image: apache/skywalking-ui:8.6.0
    container_name: ui
    restart: always
    depends_on:
      - oap
    links:
      - oap
    ports:
      - "28080:8080"
    networks:
      - skywalking
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: http://oap:12800
      SW_HEALTH_CHECKER: default
      SW_TIMEOUT: 200000
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

networks:
  skywalking:
    driver: bridge

The startup command is as follows:
java -javaagent:./agent/skywalking-agent.jar -Dskywalking.agent.service_name=test -Dskywalking.collector.backend_service=192.168.3.100:11800 -jar LiuMa-1.3.1.jar >/tmp/skywaling.out 2>&1 &

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This may be a discussion only. And we would not be able to debug for you. The content is formated badly.
