### ISSUE TITLE
Suspect that the service is using Skywalk-agent causing memory inflation

### ISSUE THREAD

**Issue by xiaoyuwang1987** [apache/skywalking#11557]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Project joined Skywalk-agent found very eat memory？
Looking at the memory address, there is a 1.5G jar loaded with a lot of agents is jar

### What you expected to happen

Whether the loaded skywalking-agent.jar can be reduced

### How to reproduce

thank you

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Not enough details. Maybe something has bugs, such as plugin incompatible.

**Comment by wu-sheng** [comment]
What you posted doesn't help in any case. We don't have magic.
