### ISSUE TITLE
[Bug] db.instance is incorrect in PostgreSQL plugin

### ISSUE THREAD

**Issue by mitht** [apache/skywalking#11552]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Trace postgresql sql data using agent 8.14.0;
Database connection address:

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/testdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true

The database is testdb, but
db.instance:Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true

<img width="1663" alt="image" src="https://github.com/apache/skywalking/assets/29425860/f54c6df9-d077-4c77-9f3a-9a33cb586741">

### What you expected to happen

db.instance=testdb

### How to reproduce

agent: apache-skywalking-java-agent-8.14.0
apm: apache-skywalking-apm-bin-9.3

springBoot version: 2.6.6
postgres version: 12

 <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.2.16</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.18</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.2</version>
        </dependency>

### Anything else

Every time

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You could debug `PostgreSQLURLParser` to find out the reason.

**Comment by mitht** [comment]
> 您可以调试一下`PostgreSQLURLParser`，找出原因。

Thank you for your answer

edit:

    protected URLLocation fetchDatabaseNameIndexRange() {
        String protocol = url.split("//")[0];
        String address = url.split("//")[1];
        String ip = address.split(":")[0];
        String port_db_url = address.split(":")[1];
        String port = port_db_url.split("/")[0];
        String db_left = protocol + "//" + ip + ":" + port + "/";
        return new URLLocation(db_left.length(), url.length());
    }

<img width="1565" alt="image" src="https://github.com/apache/skywalking/assets/29425860/5c698696-5fbe-499e-a521-ff9b5d262910">

**Comment by wu-sheng** [comment]
I can see a patch to fix this. https://github.com/apache/skywalking-java/pull/649
