### ISSUE TITLE
trace do not show clickhouse sql

### ISSUE THREAD

**Issue by k8ses** [apache/skywalking#11563]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

   I use skywalking java agent collect java service metrics data . Then I watch the data through skywalking ui. I find there is only msql preparestatement sql , no clickhouse sql.
   I try a lot of configure . But it did not work. And there is no document to teach me what should I do.

### What you expected to happen

trace show clickhouse sql.

### How to reproduce

Skywalking version:9.4.0
java agent version:9.0.0
Skywalking ui:9.4.0
datasource is spring.datasource.dynamic

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We never tested Spring datasource for this. It could be different. But I would not say it is a bug. Too many scenarios.

You should verify and test locally, and learn to debug plugins.

**Comment by k8ses** [comment]
https://github.com/apache/skywalking/issues/11563#issuecomment-1816230042

Thank you . I find the resaon. Spring dynamic datasource does not must be setted the jdbc driver. I set it, then I detect the sql.
