### ISSUE TITLE
[Feature] 使用自己接口定义的错误code码来判断接口调用是否成功 

### ISSUE THREAD

**Issue by hujiayi0126** [apache/skywalking#11562]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我希望在core.oal文件中增加一个根据接口的自定义状态码来来判断接口调用是否成功

### Use case

我希望在core.oal文件中增加一个根据接口的自定义状态码来来判断接口调用是否成功

### Related issues

我希望在core.oal文件中增加一个根据接口的自定义状态码来来判断接口调用是否成功

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't accept Chinese on Github. Are you keeping doing
