### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aunsy-com** [apache/skywalking#11583]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Server Side Agent (apache/skywalking-nodejs)

### What happened

when sending http request in my nodejs project，I need to set http request header Connection: close，the trace log will be sent to skyworking.

I think the problem is in function HttpPlugin.prototype.interceptClientRequest:
1. wrapEmit(span, req, true, 'close'): when http request header Connection: keep-alive, the "close" event will not be emitted
2. wrapEmit(span, res, false): this line change to wrapEmit(span, res, false, 'end') , the trace log will be sent to skyworking too

### What you expected to happen

I don't want to set http request header Connection: close, and the trace log will be sent to skyworking

### How to reproduce

1. Setting http request header Connection: keep-alive, the trace log will not be sent to skyworking

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
> 2\. wrapEmit(span, res, false): this line change to wrapEmit(span, res, false, 'end') , the trace log will be sent to skyworking too

Can you send a pull request?
