### ISSUE TITLE
The latest instance details cannot be queried.[Bug] 

### ISSUE THREAD

**Issue by mitht** [apache/skywalking#11594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Start a service and add the -javaagennt agent. After a period of time, restart the service. The latest instance details cannot be queried.

7e02d11e9d344d79a12fbf5eb8f3ad1e@172.16.23.1 is the latest instance

![image](https://github.com/apache/skywalking/assets/29425860/026dab5b-5fcf-4d5d-8956-d1417946a56a)

Second to last display details

![image](https://github.com/apache/skywalking/assets/29425860/fa52e436-c66a-4634-98c7-4b90f51eb1ef)

after several hours

<img width="1399" alt="image" src="https://github.com/apache/skywalking/assets/29425860/b559906e-aed7-44d1-8f92-722f9410d051">

### What you expected to happen

Show detailed data

### How to reproduce

Restart the service and view detailed data of the latest instance;
version used:
apache-skywalking-apm-9.3.0
apache-skywalking-java-agent-8.14.0

### Anything else

every time

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please verify with the latest release first.
