### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GuoHaoZai** [apache/skywalking#11602]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

spring cloud gateway traceId repeated 

### What you expected to happen

Don’t want duplicate traceIds to appear

### How to reproduce

The spring cloud gateway component use skywalking and uses the latest apm-spring-cloud-gateway-3.x-plugin and apm-spring-cloud-gateway-2.1.x-plugin. Just print the traceId.
note: The number of netty threads is greater than 2, and the concurrency is greater than 1

### Anything else

https://github.com/apache/skywalking/issues/6842

because apm-spring-cloud-gateway-3.x-plugin and apm-spring-cloud-gateway-2.1.x-plugin `NettyRoutingFilterInterceptor#afterMethod` lost `ContextManager.stopSpan();`

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Same answer like 3 years ago.
We can't afford to test for every use cases of plugin.
You need to debug first.

**Comment by GuoHaoZai** [comment]
I was fixed it in our project to override `NettyRoutingFilterInterceptor`. Just want to feedback to commuity.

**Comment by GuoHaoZai** [comment]
> Same answer like 3 years ago. We can't afford to test for every use cases of plugin. You need to debug first.

I was fixed it in our project to override NettyRoutingFilterInterceptor. Just want to feedback to commuity.

**Comment by wu-sheng** [comment]
Then you don't need a duplicate issue, Submit a pull request with verified tests. 
Very appreciated.

**Comment by XTUxiongda** [comment]
> > Same answer like 3 years ago. We can't afford to test for every use cases of plugin. You need to debug first.
> 
> I was fixed it in our project to override NettyRoutingFilterInterceptor. Just want to feedback to commuity.

the span created in org.apache.skywalking.apm.plugin.spring.cloud.gateway.v3x.NettyRoutingFilterInterceptor is closed in org.apache.skywalking.apm.plugin.spring.cloud.gateway.v3x.HttpClientFinalizerSendInterceptor。how you fixed it?
