### ISSUE TITLE
[Feature] Quick start shell for latest release

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#11619]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

With the expected release date of BanyanDB 0.6, which is the first complete-feature version for it, and SkyWalking with UI are stable enough. So, I think, it is time.

We could have a `curl and go` scrip, such as `curl -sSL https://skywalking.apache.org/quickstart.sh | bash -s`. This should actually pick the latest release(not alpha/beta/rc) from Maven Central, https://central.sonatype.com/artifact/org.apache.skywalking/server-starter

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@hanahmily Could you propose what is recommended for the version of BanyanDB? We could hard coded for now, until you have a better solution.

**Comment by hanahmily** [comment]
From my perspective, BanyanDB 0.6 will be a proper release for this combination.

**Comment by wu-sheng** [comment]
> From my perspective, BanyanDB 0.6 will be a proper release for this combination.

Is there a recommended version for this script? After 0.6, should be pick the latest stable release? Or, we should lock the version to avoid uncertain breaks?

**Comment by wu-sheng** [comment]
@mrproliu I think the timeline of BanyanDB fits the expectation to deliver this on v10. @hanahmily shared with me, the database 0.6 is ready on early March. Then we could build this and showcase/demo are expected to update as well.

**Comment by wu-sheng** [comment]
@mrproliu I have re-assigned this to @kezhenxu94 as BanyanDB is reaching release. I hope this could be ready before that.
FYI @hanahmily

**Comment by kezhenxu94** [comment]
We have a quick start for docker-compose here https://github.com/apache/skywalking/tree/master/docker#quickstart , what do you think if we adjust that to make it possible to use either BanyanDB or ElasticSearch? Adding a dedicated script to start in non-Docker sounds an unnecessary maintaining workload, WDYT @wu-sheng

**Comment by wu-sheng** [comment]
> We have a quick start for docker-compose here https://github.com/apache/skywalking/tree/master/docker#quickstart , what do you think if we adjust that to make it possible to use either BanyanDB or ElasticSearch? Adding a dedicated script to start in non-Docker sounds an unnecessary maintaining workload, WDYT @wu-sheng

That version is good. Besides code details, I want to add a OAP and BanyanDB version-locked distro and host that on skywalking.a.o, mostly to avoid GitHub download block and help people to login on our website.

**Comment by wu-sheng** [comment]
The expected workflow is `curl -sSL https://skywalking.apache.org/quickstart.sh | bash -s`. That is the proposal. Feel free to use existing resources.

**Comment by wu-sheng** [comment]
Done through https://skywalking.apache.org/docs/main/next/en/setup/backend/backend-docker/#start-the-storage-oap-and-booster-ui-with-docker-compose
