### ISSUE TITLE
How do I block a large amount of Redisson/PING

### ISSUE THREAD

**Issue by Erozzc0** [apache/skywalking#11614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I set agent. trace. ignore in JVM startup_ Path='*Redisson/PING*', but obviously it doesn't work
![1701250987276](https://github.com/apache/skywalking/assets/152385411/27739145-2f1b-416a-83bb-bcbf92d439fd)

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
How do you set up ignore?

**Comment by Erozzc0** [comment]
> 你如何设置忽略？

here is how I set it up: 
java - javaagent: / usr/skywalking/agent/skywalking-agent.jar=agent.service_name=test,agent.trace.ignore_path='*Redisson/PING*'
This endpoint is used by my application to detect redis

**Comment by wu-sheng** [comment]
Your setup is wrong. Please follow the docs.

**Comment by Erozzc0** [comment]
> 您的设置错误。请按照文档进行操作。

I just set it according to the document, may I ask whether the parameter is wrong or the url is wrong

**Comment by woshiyigekuailede** [comment]
> > 您的设置错误。请按照文档进行操作。
> 
> I just set it according to the document, may I ask whether the parameter is wrong or the url is wrong

May I ask how you finally set it
