### ISSUE TITLE
[Bug] Trace associates with Log widget

### ISSUE THREAD

**Issue by Fine0830** [apache/skywalking#11621]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

The service parameter is wrong when the view dump from Trace to Log widget by clicking the button of `View Logs`

### What you expected to happen

The service parameter is correct.

### How to reproduce

Clicking the button of `View Logs` on Trace widget.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This time is trace->log link?

**Comment by wu-sheng** [comment]
This time is viewing logs from trace side?

**Comment by Fine0830** [comment]
> This time is viewing logs from trace side?

Yes, follow up on https://github.com/apache/skywalking-booster-ui/pull/343#issuecomment-1835778402
