### ISSUE TITLE
[Bug] layout issie on the Log view from trace span page

### ISSUE THREAD

**Issue by zywayh** [apache/skywalking#11630]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

![WX20231206-105939@2x](https://github.com/apache/skywalking/assets/24758651/4c69eef1-0742-412c-90d4-1c7976d4d148)
I found a UI bug. In the "Trace" tab, when locating the requested interface and checking the related logs, the first item in the log information is compressed to a very small size, making it look messy.

### What you expected to happen

I would like the TraceID to be displayed in a single line or only show a portion of it, instead of each letter appearing on a separate line.

### How to reproduce

I found an interface request. Clicking into it and checking the related logs should reproduce the issue.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zywayh** [comment]
version 9.7.0-066457b

**Comment by Fine0830** [comment]
I don't reproduce this and It works on my side.

https://github.com/apache/skywalking/assets/20871783/354a1433-8d7f-44fa-8ff8-8669a35e7c71

**Comment by wu-sheng** [comment]
If you changed the source codes, you are on your own.

**Comment by Fine0830** [comment]
Uhh, it can be reproduced by viewing span related logs.

https://github.com/apache/skywalking/assets/20871783/e2290be9-d54c-4552-8ae8-ce2bc55809e0
