### ISSUE TITLE
[Bug] SkyWalking Java Agent failed to work with Arthas in some cases

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#11651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

When instrumented with SW Java Agent and then run "watch" with Arthas. Different errors reported for different classes:

For example, with Java Agent 9.1.0, watching `redis.clients.jedis.Jedis` reported `UnsupportedOperationException`,

![image](https://github.com/apache/skywalking/assets/2568208/3624ec72-3bd1-4964-b113-2795e849ee62)

With both 9.1.0 and 9.0.0, watching `org.apache.kafka.clients.producer.KafkaProducer` reported `TypeNotPresentException`,

![image](https://github.com/apache/skywalking/assets/2568208/25182c49-3cb8-4c55-9220-263ee6deabd2)

### What you expected to happen

No Error Happened

### How to reproduce

You may use Jedis 3.1.0 to test the former case and use Kafka-clients 3.1.2 to reproduce the latter one.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lujiajing1126** [comment]
@kylixs Any idea?

**Comment by wu-sheng** [comment]
Is this some issue of Arthas? As the new auxiliary class, it is not available for Arthas

**Comment by kylixs** [comment]
@lujiajing1126 Can you provide a demo to reproduction problem? Better put it on github

**Comment by lujiajing1126** [comment]
cc @xzyJavaX would help prepare demos

**Comment by xzyJavaX** [comment]
@kylixs https://github.com/xzyJavaX/dynamic-redefine-test. With java agent 9.1.0 to start, then start Arthas. Then
`watch redis.clients.jedis.Jedis get -x 1`
`watch org.apache.kafka.clients.producer.KafkaProducer send -x 1`

**Comment by kylixs** [comment]
OK, let me have a look.
