### ISSUE TITLE
memory has been growing very slowly

### ISSUE THREAD

**Issue by sanhe-qigai** [apache/skywalking#11664]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

My project is deployed in a k8s container. 
After using sk, I found that the memory has been growing very slowly. Is this normal?

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No, there's a quick answer. Most likely, maybe some plugins have incompatible issue. 
But you need to find on your own, such as traces are not collected, and/or trace is alway incomplete.
