### ISSUE TITLE
java argnet causes memory to grow infinitely 

### ISSUE THREAD

**Issue by sanhe-qigai** [apache/skywalking#11667]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

argnet will cache the monitoring information in the machine memory and then report it asynchronously.
 Have you ever encountered a case where the machine memory grows infinitely due to this?

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Why do you repeated open things? I had replied to you. Locking.
