### ISSUE TITLE
[Bug] skywalking-client-js data is not present inside skywalking-ui browser dashboards

### ISSUE THREAD

**Issue by marcanpilami** [apache/skywalking#11662]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Client Side Agent (apache/skywalking-client-js)

### What happened

I set up the JS library (inside a React app but this may not be relevant). Data is pushed correctly to the OAP server by the browser (HTTP 200, and data is present inside the OpenSearch database).

However, the data cannot be seen inside the browser layer dashboards of the UI. Trace data can however be seen inside the traces of other components (in my case a java agent for the application backend), so data is here, and the trace id is well understood.

Version: latest. (0.10.0).

### What you expected to happen

I would expect the browser layer dashboard to show my traces and errors.

### How to reproduce

It should work with any default configuration, here given as a React hook run on startup in the root component:
```js
useEffect(() => {
        if (window.APP_APIM_ENABLED) {
            ClientMonitor.register({
                collector: window.APP_APIM_URL,
                service: window.APP_APIM_PROJECT_NAME,
                pagePath: '/app',
                serviceVersion: 'v1.0.0',
                useFmp: true,
                enableSPA: true,
                noTraceOrigins: [],
                customTags: [],
                traceTimeInterval: 1000,
            });
        }
    },
        [] // on startup only.
    );
```

### Anything else

It seems the dashboards look for data in the BROWSER layer, but the JS library reports its spans as HTTP layer, hence the lack of data. Is this mismatch voluntary, or does it mean the BROWSER layer is for something else entirely? I have not found a way to overload the JS layer constant to test this hypothesis.

If this is simply a matter of changing the constant or making it configurable, I'm open to submitting a PR.

And.. thanks a lot for all your hard work on Skywalking!

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Besides traces, the metrics should be reported as well, which should be able to create browser layer service.

**Comment by marcanpilami** [comment]
The metrics do not seem to be sent. (when i look inside the browser dev tool network pane, there are only calls to `v3/segments`). This may be related to the fact I'm using a React SPA. I have left `autoTracePerf` unset, so default value `true` should apply.

**Comment by marcanpilami** [comment]
Just to be sure I have changed my configuratin not to use FMP and with `autoTracePerf` explictely to true, no changes.

```js
ClientMonitor.register({
                collector: window.APP_APIM_URL,
                service: window.APP_APIM_PROJECT_NAME,
                pagePath: '/app',
                serviceVersion: 'v1.0.0',
                useFmp: false,
                autoTracePerf: true,
                enableSPA: true,
                noTraceOrigins: [],
                customTags: [],
                traceTimeInterval: 1000,
            });
```

Actually it seems that metrics collection is disabled in SPA mode:

```ts
if (!this.customOptions.enableSPA) {
      this.performance(this.customOptions);
    }
```

(from monitor.ts)

**Comment by wu-sheng** [comment]
If you could provide a reproducible demo, @Fine0830 may be able to have a look.

**Comment by marcanpilami** [comment]
Thanks. However it may not be needed. If I manually add a call to `ClientMonitor.performance(ClientMonitor.customOptions);` just after `ClientMonitor.register(...)` it works. It seems `autoTracePerf` is willigly ignored when `enableSPA` is `true`. 

I believe it is worth adding a line to the documentation like "using enableSPA will disable automatic performance monitoring, call manually ClientMonitor.performance is you wish to re-enable it". (it would be a shame for users to miss this, as there is explicit support for SPAs inside ClientMonitor.performance so they should be encouraged to activate it). It may also be interesting to say in the doc why it is disabled by default in SPAs - for this I have no idea.

Beside this doc enhancement, I think this issue may be closed. Thanks a lot for your help!

**Comment by wu-sheng** [comment]
> It may also be interesting to say in the doc why it is disabled by default in SPAs - for this I have no idea.

@Fine0830 Could you confirm this when you have time?

**Comment by Fine0830** [comment]
Here is the guideline about the SPA scene. https://github.com/apache/skywalking-client-js?tab=readme-ov-file#spa-page

**Comment by marcanpilami** [comment]
If I may, if you follow these guidelines you will encounter the issue I'm talking about. Part 1 "Enable SPA automatic parsing" actually only reports traces, not metrics nor errors. This is were I would add the mention I'm proposing above. (and I would also add it to the parameter table).

**Comment by Fine0830** [comment]
If the `enableSPA` is true in the register method, it's essential to use `setPerformance` to monitor performance metrics. This won't affect tracing and logging functionalities.

Regarding `autoTracePerf`, it doesn't directly relate to enabling SPA (`enableSPA`). It depends on whether performance metrics need to be monitored automatically.
