### ISSUE TITLE
[Bug] SkyWalking 不支持Ignite

### ISSUE THREAD

**Issue by god8816** [apache/skywalking#11679]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

项目集成Ignite没有问题，然后发布到生产环境有skywalking。报错信息： Cause: java.sql.SQLException: class org.apache.ignite.IgniteCheckedException: org.apache.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to org.h2.jdbc.JdbcPreparedStatement
; class org.apache.ignite.IgniteCheckedException: org.apache.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to org.h2.jdbc.JdbcPreparedStatement; nested exception is java.sql.SQLException: class org.apache.ignite.IgniteCheckedException: org.apache.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to org.h2.jdbc.JdbcPreparedStatement
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:259)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)

### What you expected to happen

skywalking不支持Ignite

### How to reproduce

工程集群ignite 使用jdbc模式在skywalking环境，即可出现问题

### Anything else

没有

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't declare we support Ignite. And also, we don't debug plugins because they are from hundreds of people globally. If there is a cast issue, try to debug on your own.

Also, we don't support discussions in Chinese on Github. If you have troubles in English discussion, please choose Slack CN channel.
