### ISSUE TITLE
[Bug] skywalking agent 

### ISSUE THREAD

**Issue by wangkang4** [apache/skywalking#11675]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

java agent version：9.0.0
arthas：3.7.1
The arthas retransform command is used to hot-load the class file. A retransform error message is displayed. java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces

### What you expected to happen

The arthas hot-load class file function is not affected.

### How to reproduce

![3221702973608_ pic](https://github.com/apache/skywalking/assets/52090273/5f8c049e-4640-4838-a56c-da38706a327d)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
duplicated reported.

**Comment by wu-sheng** [comment]
follow https://github.com/apache/skywalking/issues/11651

**Comment by wangkang4** [comment]
Hello, does skywalking support arthas' retransform command? After the configuration of agent.is_cache_enhanced_class and agent.class_cache_mode is enabled, the redefine command is successfully executed, but the retransform command fails. Using the jad command, you found that skywalking added properties and methods to the class.

**Comment by wu-sheng** [comment]
We don't support it officially. As you can see on https://github.com/apache/skywalking/issues/11651, someone may have an interest in doing as best as they can. You could try that PR version.

**Comment by lujiajing1126** [comment]
> Hello, does skywalking support arthas' retransform command? After the configuration of agent.is_cache_enhanced_class and agent.class_cache_mode is enabled, the redefine command is successfully executed, but the retransform command fails. Using the jad command, you found that skywalking added properties and methods to the class.

IIRC, IS_CACHE_ENHANCED_CLASS flag has been removed since SkyWalking Agent 9.0

**Comment by wangkang4** [comment]
arthas' hot-load class file commands, such as redefine and retransform, are not currently supported by the services monitored by skywalking, right?

**Comment by wangkang4** [comment]
> > Hello, does skywalking support arthas' retransform command? After the configuration of agent.is_cache_enhanced_class and agent.class_cache_mode is enabled, the redefine command is successfully executed, but the retransform command fails. Using the jad command, you found that skywalking added properties and methods to the class.
> 
> IIRC, IS_CACHE_ENHANCED_CLASS flag has been removed since SkyWalking Agent 9.0

How to modify skywalking javaagent to support arthas hot load class command, is there a case code?

**Comment by lujiajing1126** [comment]
> > > Hello, does skywalking support arthas' retransform command? After the configuration of agent.is_cache_enhanced_class and agent.class_cache_mode is enabled, the redefine command is successfully executed, but the retransform command fails. Using the jad command, you found that skywalking added properties and methods to the class.
> > 
> > 
> > IIRC, IS_CACHE_ENHANCED_CLASS flag has been removed since SkyWalking Agent 9.0
> 
> How to modify skywalking javaagent to support arthas hot load class command, is there a case code?

As you may notice in https://github.com/apache/skywalking-java/pull/659, we are still working on this topic. I suppose after that PR, we may stabilize this feature.

Feel free to test [this PR](https://github.com/apache/skywalking-java/pull/659) for your use cases. Feedback is welcome.

**Comment by wangkang4** [comment]
Is arthas' redefine and retransform commands not currently supported for modifying the target class? Because skywalking's javaagent adds a few new methods to the target class.

**Comment by wangkang4** [comment]
> > > > Hello, does skywalking support arthas' retransform command? After the configuration of agent.is_cache_enhanced_class and agent.class_cache_mode is enabled, the redefine command is successfully executed, but the retransform command fails. Using the jad command, you found that skywalking added properties and methods to the class.
> > > 
> > > 
> > > IIRC, IS_CACHE_ENHANCED_CLASS flag has been removed since SkyWalking Agent 9.0
> > 
> > 
> > How to modify skywalking javaagent to support arthas hot load class command, is there a case code?
> 
> As you may notice in [apache/skywalking-java#659](https://github.com/apache/skywalking-java/pull/659), we are still working on this topic. I suppose after that PR, we may stabilize this feature.
> 
> Feel free to test [this PR](https://github.com/apache/skywalking-java/pull/659) for your use cases. Feedback is welcome.

为什么使用skywalking的javaagent会生成很多带有$的类？使用arthas的trace命令查看调用链，发现执行的都是那些生成的代理类.
![WechatIMG328](https://github.com/apache/skywalking/assets/52090273/9da8e7f5-2fe8-474a-9254-1c1684e459bc)

![WechatIMG326](https://github.com/apache/skywalking/assets/52090273/badeabd7-837b-41b7-82e8-3c23bbe69811)

**Comment by wu-sheng** [comment]
That is why your codes could be traced and monitored.
Your codes are changed by the agent.
