### ISSUE TITLE
[Bug]  java.sql.SQLSyntaxErrorException: Unknown column 'table_name' in 'where clause'

### ISSUE THREAD

**Issue by 137-zwq** [apache/skywalking#11685]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Skywalking version 9.7 initializes the database, database version 8.0

### What you expected to happen

Skywalking9.7 Normal initialization

### How to reproduce

Skywalking version 9.7 initializes the database, database version 8.0

### Anything else

![QQ截图20231221231638](https://github.com/apache/skywalking/assets/64053611/0a0e9c2d-24c3-4505-b1c1-c5d2f11e4388)

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you running the 9.7 OAP on 9.6 initialized SQL database?

**Comment by 137-zwq** [comment]
> Are you running the 9.7 OAP on 9.6 initialized SQL database?

No, I am using Skywalking9.7, a newly initialized database with version 8.0.28. I have not used version 9.6 before

**Comment by wu-sheng** [comment]
Let's wait for @wankai123 to check when he has time.

**Comment by 137-zwq** [comment]
The problem of deleting and recreating a new database has not occurred.

**Comment by wu-sheng** [comment]
Then, it seems that the database is not clean. Closing for now.
