### ISSUE TITLE
[Bug] The database statement is too long and cannot be fully displayed when copied

### ISSUE THREAD

**Issue by cfy3133** [apache/skywalking#11703]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

The database statement is too long and cannot be fully displayed when copied

### What you expected to happen

Database statement is too long, copying it shows comprehensive information

### How to reproduce

Slow queries were detected in Virtual Database Service, and when the number of copied statement fields reached 200, incomplete information display occurred during copying

### Anything else

![1703753177339](https://github.com/apache/skywalking/assets/43978367/d33bacce-f898-4358-b1af-b23abf026902)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Fine0830** [comment]
I didn't reproduce this issue.

**Comment by wu-sheng** [comment]
This is not about copied. Your SQL statement is truncated when it was collected by the agent.
