### ISSUE TITLE
日志提供一个查询上下文的功能

### ISSUE THREAD

**Issue by zhaomingcheng01** [apache/skywalking#11708]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

日志提供一个查询上下文的功能

### Use case

目前日志功能就差一个查询上下文的功能
<img width="920" alt="Snipaste_2023-12-29_14-33-12" src="https://github.com/apache/skywalking/assets/46734892/34d989a9-a6c9-4c8b-b5bf-2ca21457dcd9">

### Related issues

没有

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
You will have to use English in public communication on GitHub. And to propose new features you will need to go through the SWIP process. like this one https://github.com/apache/skywalking/discussions/11677
