### ISSUE TITLE
能好好弄一弄中文文档不，中国人弄的还全是英文

### ISSUE THREAD

**Issue by workwith** [apache/skywalking#11717]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
We even provided AI to answer your questions in any language, what do you expect? If you would like to provide the translation, go ahead and I will help you to ingest it.
