### ISSUE TITLE
[Bug] skywalking-go 无法增强返回自定义类型的方法

### ISSUE THREAD

**Issue by Ruff-nono** [apache/skywalking#11738]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

在开发rocketMQ插件时，报错
/tmp/go-build612827965/b348/skywalking_delegator.go:46:10: cannot use nil as ConsumeResult value in return statement
/tmp/go-build612827965/b348/skywalking_delegator.go:59:9: cannot use nil as ConsumeResult value in return statement
/tmp/go-build612827965/b348/skywalking_delegator.go:80:13: cannot use nil as ConsumeResult value in assignment

### What you expected to happen

增强方法func (pc *pushConsumer) consumeInner(ctx context.Context, subMsgs []*primitive.MessageExt) (ConsumeResult, error)位于pushconsumer.go
而type ConsumeResult int定义在consumer.go文件中
在FilterAndEdit -> EnhanceParameterNames时，无法判断出真实类型，DefaultValueAsString返回为"nil"

### How to reproduce

增强方法返回值为自定义类型且为int时，增强文件的返回默认值会类型错误
{
			PackagePath: "consumer",
			At: instrument.NewMethodEnhance("*pushConsumer", "consumeInner",
				instrument.WithArgsCount(2),
				instrument.WithArgType(0, "context.Context"),
				instrument.WithArgType(1, "[]*primitive.MessageExt"),
				instrument.WithResultCount(2),
				instrument.WithResultType(0, "ConsumeResult"),
				instrument.WithResultType(1, "error")),
			Interceptor: "ConsumeInnerInterceptor",
		}
增强返回如
if invocation.isContinue {
		if invocation.returnValues[0] != nil {
			*ret_0 = (invocation.returnValues[0]).(ConsumeResult)
		} else {
			*ret_0 = nil
     }
}

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please submit an issue in English. 
If you need Chinese discussion, please go to Slack CN Channel.
