### ISSUE TITLE
[Feature] Can traceId in skywalking be replaced by a unique value in the business

### ISSUE THREAD

**Issue by liufeng2311** [apache/skywalking#11746]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Can traceId in skywalking be replaced by a unique value in the business，

### Use case

I want to manually set the value of traceId in the business, and the uniqueness of traceId is guaranteed by our business

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Not an issue or feature. We never declared this could be done.
