### ISSUE TITLE
[Bug] ui white screen

### ISSUE THREAD

**Issue by zchengz** [apache/skywalking#11742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

When I use "npm run dev" to start the UI, there is a white screen, and the interface "http://localhost:3000/graphql" shows an error message: "Validation error of type FieldUndefined: Field 'getMenuItems' in type 'Query' is undefined @ 'getMenuItems'".
oap server  is normal.
![微信截图_20240109162038](https://github.com/apache/skywalking/assets/57397259/c74b9fc6-f2f9-4c1e-9186-c54ed00cbf86)

### What you expected to happen

I hope you can help me solve this problem.

### How to reproduce

git clone https://github.com/apache/skywalking-booster-ui.git
npm install
npm run dev

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please debug first. This usually means, your oap server is not booted successfully.

**Comment by wu-sheng** [comment]
If you use latest, you should know the codes and details.
Otherwise, use the release versions.

**Comment by zchengz** [comment]
ui 我使用的是master分支,oap 同样是master分支,oapserver我认为是正常的，因为我debug断点进入到了com.linecorp.armeria.server.graphql.DefaultGraphqlService#executeGraphql
![Uploading 1111.png…]()

**Comment by zchengz** [comment]
Ui I use the master branch, oap is also the master branch, oapserver I think is normal, because I debug breakpoint into the com.linecorp.armeria.server.graphql.DefaultGraphqlService#executeGraphql
![Uploading 1111.png…]()

**Comment by wu-sheng** [comment]
Use English on Github please. CN channel is in the slack.

And we don't provide debug and dev support from basic. Sorry. We can't afford that.

**Comment by zchengz** [comment]
Okay, I'll try 9.7.0 again.
