### ISSUE TITLE
[Bug] 数据计算方法和逻辑是什么

### ISSUE THREAD

**Issue by asdw123456wdsa** [apache/skywalking#11744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

![7048482585225](https://github.com/apache/skywalking/assets/156080732/d259cfd8-6476-4423-8248-c1d20797b2cd)
![7048483045958](https://github.com/apache/skywalking/assets/156080732/16c17fce-3e33-46f6-a09d-ed6e637c64fa)
![7048483368875](https://github.com/apache/skywalking/assets/156080732/a73494be-aab0-434a-b1fd-c331d102be27)
为什么两天延迟的数据和单天无法关联，延迟数据的计算方法或者逻辑是什么呢

### What you expected to happen

数据计算方法或逻辑情况是什么

### How to reproduce

![7048482585225](https://github.com/apache/skywalking/assets/156080732/d259cfd8-6476-4423-8248-c1d20797b2cd)
![7048483045958](https://github.com/apache/skywalking/assets/156080732/16c17fce-3e33-46f6-a09d-ed6e637c64fa)
![7048483368875](https://github.com/apache/skywalking/assets/156080732/a73494be-aab0-434a-b1fd-c331d102be27)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Chinese discussion should move to slack CN channel.
