### ISSUE TITLE
[Feature] add Support for RocketMQ newAPI `rocketmq-client-java`

### ISSUE THREAD

**Issue by CzyerChen** [apache/skywalking#11752]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Since RocketMQ5.0, the RocketMQ community promotes the new AP that consumer different from `rocketmq-clients`.
Now it has been tested that the producer can be tracked with apis in `rocketmq-client-java`, but the consumer cannot.
[introdcution about new Rocketmq API ](https://github.com/apache/rocketmq-clients/blob/master/java/README-CN.md)

### Use case

The JAVA project produces and consumes message with apis  in `rocketmq-client-java`, and the Rocketmq request tracing works.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Is the webflux-webclient-6.x/httpexchange going to submit shortly?

**Comment by CzyerChen** [comment]
> Is the webflux-webclient-6.x/httpexchange going to submit shortly?

yes

**Comment by CzyerChen** [comment]
Have a problem that how to recover context when sending messages one by one and consuming messages in batches.
Normally, Producer sends one message and MessageListener consumes Individually, so the producer is exit and consumer is entry, they matched to show the context.
A produced one, and A consumed one.
<img width="253" alt="image" src="https://github.com/apache/skywalking/assets/22817918/f9989b8c-95d4-4148-adb7-f7fdf8c5b9ad">

But several producers send messages to different topics and  `SimpleConsumer`( provided in `rocketmq-client-java`) consumes messages with many topics manually in batches, whether the initial producer and consumer have to be referred.
A produced one and produced one, and B consumed two in batches
<img width="299" alt="image" src="https://github.com/apache/skywalking/assets/22817918/8b9e25e0-c9c8-42fd-a865-1611c197fc56">

**Comment by wu-sheng** [comment]
What is the question? Do you mean from the consuming side, a batch include mutiple references?

**Comment by CzyerChen** [comment]
yes, MQ consuming in batches that triggered by API or scheduled job. 
The single message consumed now mark as an entry span and refer to the producer the exit span, do batch consuming case have to be the entry span and refer to the producers, or just be a local span to show the action. If local span, the trace between the producer and consumer will be lost.
