### ISSUE TITLE
 several fixes after 9.2 and configuration discussion are there. The last one is #11686, discussion source, #11680

### ISSUE THREAD

**Issue by liucx1201** [apache/skywalking#11795]
> 9.2 之后有一些修复和配置讨论。最后一篇是#11686，讨论源，#11680

@wu-sheng I just upgraded to 9.5.0 and still reported this issue
![20240118111409](https://github.com/apache/skywalking/assets/40434832/c4f879de-9c38-406a-a1d5-008f4cecd833)

_Originally posted by @liucx1201 in https://github.com/apache/skywalking/issues/11794#issuecomment-1897707536_

**Comment by wu-sheng** [comment]
The fix is in the v10 only. And 9.5 doesn't include that.

**Comment by liucx1201** [comment]
I don't understand what version is supported?
@wu-sheng

**Comment by 344310362** [comment]
> The fix is in the v10 only. And 9.5 doesn't include that.

why in master branch ，is still exists
