### ISSUE TITLE
Webapp supports IP binding

### ISSUE THREAD

**Issue by sboesebeck** [apache/skywalking#11793]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

For security reasons, I'd like to hide the webapp behinde some kind of reverse proxy. Unfortunately there is no way to have the webapp listen to localhost, it always binds to all available interfaces.

### What you expected to happen

when providing serverIP or bindIP to the application.yml, the webapp should only bind to that ip address.

### How to reproduce

try to set the binding ip of the webapp

### Are you willing to submit a pull request to fix on your own?

- [] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Yes, we don't support that. If you want to provide a pull request to add this, welcome. 
But this is not a bug.

**Comment by sboesebeck** [comment]
oh. ok... but why is that not supported? Where is the benefit of not being able to configure that? Did I miss something?

Thanks,

Stephan

**Comment by wu-sheng** [comment]
No benefit, just no one did.
That is how open source works, who needs this is the one adding it.

**Comment by wu-sheng** [comment]
No one picked this up. Close for now.
