### ISSUE TITLE
[Feature] add consul/etcd discover in skywalking-go

### ISSUE THREAD

**Issue by vearne** [apache/skywalking#11825]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

skywalking-go uses grpc to report monitoring information. When it is used in production, it should support discovery of skywalking-oap-server from consul or etcd

### Use case

1. skywalking-oap-server is registered in consul or etcd
2. The business app discovers the skywalking-oap-server instance list from consul or etcd
3. The business app requests the skywalking-oap-server instance through grpc and reports monitoring data.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Sorry, we would accept service discovery in agent.
In today's cloud native issue, dns and mesh service are main stream.
You could consider that.

**Comment by wu-sheng** [comment]
More importantly, you are going to introduce more libs, that isn't our plan.
