### ISSUE TITLE
[Bug] skywalking-php-agent  Doesn’t it support performance profiling? There’s no data.

### ISSUE THREAD

**Issue by wuqs** [apache/skywalking#11849]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

When I wanted to test performance profiling, I didn’t even count it.

### What you expected to happen

When I wanted to test performance profiling, I didn’t even count it.

### How to reproduce

When I wanted to test performance profiling, I didn’t even count it.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
PHP doesn't support profiling AFAIK. 
Only Java and Python support that.
