### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by bbz525** [apache/skywalking#11841]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

![1706518098892](https://github.com/apache/skywalking/assets/26547423/6f79b30e-9489-4a47-8a37-ce47799a72ae)
 tag v8.9 is not in any branch,what happen?

### What you expected to happen

explain what happen,how i get the tag code?

### How to reproduce

i dont know

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If there is not a branch that matches the tag, it will be shown by this. That is a known problem of GitHub. You don't need to worry about that.
