### ISSUE TITLE
[Bug] incorrect span segment when enhancing the Gin framework

### ISSUE THREAD

**Issue by Ruff-nono** [apache/skywalking#11852]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

span will be created by the first HandlerFunc and closed by the last HandlerFunc, and cause incorrect SegmentID and SpanId in the gin middware

```
middleware before | {"SW_CTX": "[Your_ApplicationName,ef34293ac00111eea77d2672e7982bed@172.27.200.74,ef322f52c00111eea77d2672e7982bed.82.39184361106090001,ef322f52c00111eea77d2672e7982bed.82.39184361106090002,0]"}
middleware after | {"SW_CTX": "[Your_ApplicationName,ef34293ac00111eea77d2672e7982bed@172.27.200.74,N/A,N/A,-1]"}

```

### What you expected to happen

handle the create and end span correctly

### How to reproduce

using Gin middleware methods

```
g.Use(func(c *gin.Context) {
logger.Info("middleware before")
c.Next()
logger.Info("middleware after")
}
```

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> span will be created by the first HandlerFunc and closed by the last HandlerFunc,

What was wrong? This sentence is not clear.

**Comment by Ruff-nono** [comment]
> > span will be created by the first HandlerFunc and closed by the last HandlerFunc,
> 
> What was wrong? This sentence is not clear.

I found that the Gin plugin has been changed to `func (c *Context) Next()`. However, this method will be handled multiple times by multiple middleware handlerFuncs in the route. 
As a result, CreateEntrySpan is called every handlerFuncs and propagated by `Invocation.SetContext()` closed by the last handlerFunc, causing the segment to be incorrectly interrupted prematurely when customizing Gin middleware.

**Comment by wu-sheng** [comment]
Could you put a graph to explain this? You are using an instance level dynamic field, this should not be helpful is a handler instance repeatedly used in the process.

**Comment by wu-sheng** [comment]
I could understand your case now, then, when the context gets reset in the after? Is it caused by `stop span` at the end of `#Next`, or somewhere else?

**Comment by Ruff-nono** [comment]
because every middleware handlerFuncs could call `#Next`,  then it will call `#CreateEntrySpan` in `#BeforeInvoke` and call `span.End()` in `#AfterInvoke` many times,  but after `span.End()` first be Called by the last middleware handlerFunc,  the TracingContext in current goroutine will be cleared, so the other handlerfuncs cannot get the TraceContext for use.

![image](https://github.com/apache/skywalking/assets/38658935/cdf79f05-ffa3-47c2-95da-7f297d186763)

**Comment by wu-sheng** [comment]
OK, then there is typically solution for this, you should put a counter in the context of the chain. This counter increases one in before and minus one in after. Then, create span when the counter created, and stop span when counter back to zero.

Note, the counter should be kept in the request context.
