### ISSUE TITLE
[Bug] skywalking agent randomly occupies some ports during runtime.

### ISSUE THREAD

**Issue by kamyuk** [apache/skywalking#11868]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

In my configuration file, there is no setting for ports 50990, 50991, and 50992. However, during runtime, I observed that SkyWalking is occupying these three ports. As a result, other services configured to use these ports are unable to start.

### What you expected to happen

to fix the port setting

### How to reproduce

check the TCP port occupancy

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Any outbound rpc will use a random port. That is how rpc works.

**Comment by Superskyyy** [comment]
This is by design on the gRPC side, you may can force using a source port but that is in general a limited usecase, since grpc already picks a random unused port. You normally just need to make sure you bind other specific ports in advance.

**Comment by kamyuk** [comment]
> This is by design on the gRPC side, you may can force using a source port but that is in general a limited usecase, since grpc already picks a random unused port. You normally just need to make sure you bind other specific ports in advance.

Thanks！
