### ISSUE TITLE
[Feature] where store the sevice name and instance name  list?

### ISSUE THREAD

**Issue by taoyang987** [apache/skywalking#11865]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

i explore the log data with kibana from sw_log index.
in the index ,there is only  sevice id and instance
where store the sevice name and instance name  list?
if the name filed also in the index ,it will be very readable from kinbana
![WX20240203-151214@2x](https://github.com/apache/skywalking/assets/872386/b677d37c-8e63-448e-880b-cdaa3ec140ec)

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Don't use issues for question, that is not a good practice. I had moved one to discussion. this is on your own.
