### ISSUE TITLE
virtual database query

### ISSUE THREAD

**Issue by ms787277296** [apache/skywalking#11872]
![image](https://github.com/apache/skywalking/assets/29354555/576c6178-c4ea-49cf-a74e-ae2dcf76ee80)
we use this config in our project, but oap seems fail to detect mysql. 
![image](https://github.com/apache/skywalking/assets/29354555/37a92495-c6e7-4522-ac8e-64428ed8f8d2)
the correct chain is below:
![image](https://github.com/apache/skywalking/assets/29354555/2cba60a7-5a94-4e0d-9398-614907a2bd93)
can you give me a suggestion. Thanks a lot

_Originally posted by @ms787277296 in https://github.com/apache/skywalking/discussions/11858#discussioncomment-8360146_

**Comment by wu-sheng** [comment]
https://skywalking.apache.org/docs/main/next/en/setup/service-agent/virtual-database/

Virtual database is detected by this. Check your original spans.
