### ISSUE TITLE
[Feature] Add hierarchy for RabbitMQ layer

### ISSUE THREAD

**Issue by peachisai** [apache/skywalking#11926]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

As skywalking 10 supporting service hierarchy , RabbitMQ layer could be related from span peer and k8s service to RabbitMQ monitoring  

### Use case

skywaling-showcase

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@peachisai If you have any uncertain questions about building hierarchy please let me and @wankai know.

**Comment by peachisai** [comment]
@wu-sheng  @wankai123 
![image](https://github.com/apache/skywalking/assets/96932958/6e9d10f3-6ebf-4ac6-a472-66fc34626bef)
This is my question
Rule:
![image](https://github.com/apache/skywalking/assets/96932958/7e9dd9bf-3aa1-4098-9308-2c65c762e069)
Showcase:
![image](https://github.com/apache/skywalking/assets/96932958/063d55ba-7301-4e41-9bb0-512acacbd9f7)
![image](https://github.com/apache/skywalking/assets/96932958/d1a2ff30-5a46-4f84-b526-9ea259160317)

Should I pull an another PR about changing ```skywalking-showcase```  ```RabbitMQ monitoring``` service name to 
`rabbitmq.skywalking-showcase` for building the relationship from ```RabbitMQ monitoring``` to ```k8s```layer?

**Comment by peachisai** [comment]
> @peachisai If you have any uncertain questions about building hierarchy please let me and @wankai know.

Ok , I will. BTW, you seems @ an another irrelavant  person :D

**Comment by wu-sheng** [comment]
I think name should be changed to align with the hierarchy detection mechanism requirements, as same as RocketMQ did.
