### ISSUE TITLE
[Feature] Add hierarchy to Kafka monitoring

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#11929]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have Kafka server monitoring and agent plugins(Java) for Kafka, and k8s monitoring, we should consider to add hierarchy support for Kafka.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@peachisai I think this could be processed before https://github.com/apache/skywalking/issues/11926 as Kafka is more popular. WDTY?

**Comment by peachisai** [comment]
> @peachisai I think this could be processed before #11926 as Kafka is more popular. WDTY?

As RabbitMQ Hierarchy is nearly completed, I will set about doing Kafka showcase after RabbitMQ.
To consider resouces that Kafka  showcase will replace RabbitMQ showcase by default setting, Is It ?

**Comment by wu-sheng** [comment]
> As RabbitMQ Hierarchy is nearly completed, I will set about doing Kafka showcase after RabbitMQ.

Please go ahead.

> To consider resouces that Kafka showcase will replace RabbitMQ showcase by default setting, Is It ?

We could have both, most importantly, we need to change the demo application codes and relative deployment, which could make Kafka in the topology and virtual MQ.
