### ISSUE TITLE
very much hope skywalking supports clickhouse

### ISSUE THREAD

**Issue by sglztc** [apache/skywalking#11924]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Because the company uses clickhouse for storage, can skywalking support clickhouse? The performance of clickhouse is relatively good. In the past few days, it has been quite a lot of work to transform the storage into clickhouse. Is there any recommendation on the official website for transformation, or allow other people to merge it. It's also okay to go to a specific branch for reference. There is currently nothing in this area. Regarding storage, clickhouse is used.

### What you expected to happen

I very much hope that the official can support clickhouse. This is also the voice of many people. Most observable projects currently use clickhouse, or the official allows others to merge it into a specific branch for reference. Currently, there is nothing about using clickhouse for storage.

### How to reproduce

I very much hope that the official can support clickhouse. This is also the voice of many people. Most observable projects currently use clickhouse, or the official allows others to merge it into a specific branch for reference. Currently, there is nothing about using clickhouse for storage.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
There is no official team to do this. This is very clear for years.
We have decided to move on our own database, BanyanDB.

If you want to do something, go ahead, and contribute to help others.

**Comment by wu-sheng** [comment]
We never rejected a pull request about it. No one takes the maintenance responsibility. No pull request happens.

**Comment by cxntsh** [comment]
We have initially implemented some ideas. If you want to have further communication, you can send me an email.

**Comment by sglztc** [comment]
请问你们已经实现了clickhouse存储吗？这块的代码可以分享一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/skywalking"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月24日(星期六) 晚上8:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/skywalking] very much hope skywalking supports clickhouse (Issue #11924)





 
We have initially implemented some ideas. If you want to have further communication, you can send me an email.

**Comment by wu-sheng** [comment]
@sglztc Your comments have been deleted, all discussions on GitHub need to be in English. Slack CN channel is for Chinese.

**Comment by sglztc** [comment]
> We have initially implemented some ideas. If you want to have further communication, you can send me an email.

thanks

**Comment by sglztc** [comment]
What is the specific reason why clickhouse storage is not supported? Are there any pitfalls in this area so that I can avoid it when designing? Very much looking forward to the author's answer.

**Comment by sglztc** [comment]
> We have initially implemented some ideas. If you want to have further communication, you can send me an email.

Can you share the table design of this piece? We can implement the code ourselves.

**Comment by wu-sheng** [comment]
> What is the specific reason why clickhouse storage is not supported? Are there any pitfalls in this area so that I can avoid it when designing? Very much looking forward to the author's answer.

I think I have said this very clearly. There isn't a thing about `why`. No one is actually contributing and maintaining this in the upstream. Do you know who wants to do this? You said we rejected something, but we didn't.

**Comment by sglztc** [comment]
> > What is the specific reason why clickhouse storage is not supported? Are there any pitfalls in this area so that I can avoid it when designing? Very much looking forward to the author's answer.
> 
> I think I have said this very clearly. There isn't a thing about `why`. No one is actually contributing and maintaining this in the upstream. Do you know who wants to do this? You said we rejected something, but we didn't.

Hello, teacher wu-sheng, you have misunderstood me. What I want to know is are there any pitfalls in the process of adapting to clickhouse? I would like to know some specific reasons why clickhouse is not supported, because we are currently doing research and implementation in this area to avoid taking some detours. Do I only need to implement storage-clickhouse-plugin to use clickhouse storage? Do you still need to do a deeper transformation?

**Comment by wu-sheng** [comment]
> What I want to know is are there any pitfalls in the process of adapting to clickhouse? 

I don't know that.

> I would like to know some specific reasons why clickhouse is not supported, because we are currently doing research and implementation in this area to avoid taking some detours

The only reason is what I mentioned. No one shows up to say they will implement it and maintain the implementation to make sure it is product ready.

> Do I only need to implement storage-clickhouse-plugin to use clickhouse storage? Do you still need to do a deeper transformation?

I have no idea about the clickhouse. From the design perspective, SkyWalking exposes the module APIs for making implementation easier. So, yes, we hope you only need to implement that.
The reality is on the other side, sometimes, you will need annotations or some advanced flags on the kernel level to make the performance good. You can see Elasticsearch and JDBC relative flags are in the core module codes.

___

So, you can see, every time, clickhouse relative discussions fall into the same hole. People want me or someone in the SkyWalking maintenance team to tell, but the truth is we as a group neither know the clickhouse, nor use it.
So, there is no magic and short path. You have to understand both SkyWalking OAP kernel/details and the features of ClickHouse, and write design, coding and run performance tests to prove that this new storage option really is good.

**Comment by wu-sheng** [comment]
The existing offering is being kept private and commercial only, which also shows up, it would not be that easy.
So, you have to make your decision. I could only join the discussion if you are going to donate this to upstream and have at least two committers taking responsibility to maintain them, once it lacks maintenance, it will be removed like IoTDB and InfluxDB storage options. That is how open source community works.

**Comment by sglztc** [comment]
> > What I want to know is are there any pitfalls in the process of adapting to clickhouse?
> 
> I don't know that.
> 
> > I would like to know some specific reasons why clickhouse is not supported, because we are currently doing research and implementation in this area to avoid taking some detours
> 
> The only reason is what I mentioned. No one shows up to say they will implement it and maintain the implementation to make sure it is product ready.
> 
> > Do I only need to implement storage-clickhouse-plugin to use clickhouse storage? Do you still need to do a deeper transformation?
> 
> I have no idea about the clickhouse. From the design perspective, SkyWalking exposes the module APIs for making implementation easier. So, yes, we hope you only need to implement that. The reality is on the other side, sometimes, you will need annotations or some advanced flags on the kernel level to make the performance good. You can see Elasticsearch and JDBC relative flags are in the core module codes.
> 
> So, you can see, every time, clickhouse relative discussions fall into the same hole. People want me or someone in the SkyWalking maintenance team to tell, but the truth is we as a group neither know the clickhouse, nor use it. So, there is no magic and short path. You have to understand both SkyWalking OAP kernel/details and the features of ClickHouse, and write design, coding and run performance tests to prove that this new storage option really is good.

thanks

**Comment by sglztc** [comment]
By analyzing the storage source code of jdbc and elasticsearch, we can find that it is feasible to use clickhouse for storage. We can learn from elasticsearch storage and use clickhouse large-width table design to give full play to the multi-column advantages of clickhouse. It is still under continuous development. I hope it will give some inspiration to developers who are using clickhouse as storage.Personal suggestions are welcome to discuss together.

**Comment by wu-sheng** [comment]
Once you have a proposal about implementation details, please go for discussion to explain your design.
If you want further to make this in upstream(if accepted), you need to prepare SWIP.

**Comment by hxd123456** [comment]
> By analyzing the storage source code of jdbc and elasticsearch, we can find that it is feasible to use clickhouse for storage. We can learn from elasticsearch storage and use clickhouse large-width table design to give full play to the multi-column advantages of clickhouse. It is still under continuous development. I hope it will give some inspiration to developers who are using clickhouse as storage.Personal suggestions are welcome to discuss together.

Hello, I have been researching the implementation of this aspect recently. Do you have any more details, such as the ddl for segments? I have searched for statements used by other implementers. 
`CREATE TABLE skywalking.segment
(
    `segment_id` String,
    `trace_id` String,
    `service_id` LowCardinality(String),
    `service_instance_id` LowCardinality(String),
    `endpoint_name` String,
    `endpoint_component_id` LowCardinality(String),
    `start_time` DateTime64(3),
    `end_time` DateTime64(3),
    `latency` Int32,
    `is_error` Enum8('success' = 0, 'error' = 1),
    `data_binary` String,
    INDEX idx_endpoint_name endpoint_name TYPE tokenbf_v1(2048, 2, 0) GRANULARITY 1,
    PROJECTION p_trace_id
    (
        SELECT 
            trace_id,
            groupArrayDistinct(service_id),
            min(start_time) AS min_start_time,
            max(start_time) AS max_start_time
        GROUP BY trace_id
    )
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(start_time)
ORDER BY (start_time, service_id, endpoint_name, is_error)
TTL toDateTime(start_time) + toIntervalDay(10)`
Is this solution feasible? Looking forward to your answer
