### ISSUE TITLE
[Feature] Add Pulsar monitoring to the showcase

### ISSUE THREAD

**Issue by CodePrometheus** [apache/skywalking#11939]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We could consider adding pulsar in showcase.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I think Pulsar hierarchy detection is not added too.

**Comment by wu-sheng** [comment]
@CodePrometheus Any update on this?

**Comment by CodePrometheus** [comment]
> @CodePrometheus Any update on this?

Still in local testing, it may take some more time, thx.

**Comment by CodePrometheus** [comment]
Feature is complete, let me close it.
