### ISSUE TITLE
[Feature] Add Kafka monitoring to the showcase

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#11930]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We are missing Kafka in the showcase, we should consider adding it. Meanwhile, currently, we are using ActiveMQ in the showcase app demo, we should replace it with Kafka, and add demo for https://github.com/apache/skywalking/issues/11929 as well.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@peachisai PTAL.

**Comment by wu-sheng** [comment]
@peachisai Any update about this?

**Comment by peachisai** [comment]
> @peachisai Any update about this?

Sorry for this, I'm preparing for a test , so I don't have time to do it these months

**Comment by wu-sheng** [comment]
> > @peachisai Any update about this?
> 
> Sorry for this, I'm preparing for a test , so I don't have time to do it these months

Good luck for that. I am closing this for now, as it is not being processed.
