### ISSUE TITLE
[BanyanDB] some tests are missing in convert package in skywalking-banyandb

### ISSUE THREAD

**Issue by sivasathyaseeelan** [apache/skywalking#11942]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, there are some tests are missing in convert package in skywalking-banyandb

### Use case

The proposed solution is to address this by adding the necessary tests for the files in the engine package, which would help in detecting bugs early, supporting CI/CD, reducing debugging time, providing safety for this codebase etc...

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Which parts? Have you talked with @hanahmily

**Comment by sivasathyaseeelan** [comment]
> Which parts? Have you talked with @hanahmily

I didn't talk with @hanahmily, but while going through the code base I found some tests are missing in [convert](https://github.com/apache/skywalking-banyandb/tree/main/pkg/convert).

**Comment by hanahmily** [comment]
I appreciate your finding and welcome you to contribute to this task.  

It's a good starting task to help you become familiar with the project.
