### ISSUE TITLE
[BanyanDB] UI improvement needed in Not Found View

### ISSUE THREAD

**Issue by sivasathyaseeelan** [apache/skywalking#11964]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

#### Issue
Not found View is plain and it become difficult for the users to navigate when they land up on such situations.

#### Relevant Images
![Not Found View](https://github.com/apache/skywalking/assets/95441117/6e5a17ac-fb94-443c-a400-c935e542f327)

#### Solution
Adding a navbar and styling this page will create a better user experience

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
FYI @hanahmily

**Comment by hanahmily** [comment]
That's a good find. This page will create a centered 404 message with a "Go Home" button redirecting the user to the home page. Could you contribute to it?

**Comment by CodePrometheus** [comment]
In skywalking-ui, there is a similar situation.
<img width="400" alt="image" src="https://github.com/apache/skywalking/assets/66550292/2ea796af-c94d-49c2-b51d-3f9b8946c5f8">

**Comment by wu-sheng** [comment]
> In skywalking-ui, there is a similar situation.
> 
> <img width="400" alt="image" src="https://github.com/apache/skywalking/assets/66550292/2ea796af-c94d-49c2-b51d-3f9b8946c5f8">
> 
> 

This is by design. What is the issue?

**Comment by sivasathyaseeelan** [comment]
> That's a good find. This page will create a centered 404 message with a "Go Home" button redirecting the user to the home page. Could you contribute to it?

@hanahmily, I am working on this issue. I will raise a PR when it is done!

**Comment by sivasathyaseeelan** [comment]
@wu-sheng, I think this issue has been resolved. Can we close this?
