### ISSUE TITLE
[BanyanDB-UI] Default Time Range for Querying Data 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#11973]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When selecting a certain stream or measure, it always shows a fixed time range. I would like it to default to the last 15 minutes.

<img width="1328" alt="image" src="https://github.com/apache/skywalking/assets/1960537/a7bd9916-7670-4467-b048-64c1748237ab">

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Sylvie-Wxr** [comment]
Hi @hanahmily , I am interested working on this issue.

**Comment by lujiajing1126** [comment]
> Hi @hanahmily , I am interested working on this issue.

Assigned to you
