### ISSUE TITLE
[BanyanDB-UI] Beautify Some Pages

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#11977]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

## Remove Unused Buttons

Remove the buttons in the red box.

<img width="1596" alt="image" src="https://github.com/apache/skywalking/assets/1960537/a81a1e43-1736-4ae4-84ae-7bac7aec7a78">

## Use the BanyanDB Icon as the Browser's Ico

Please use an image in "asserts" to replace the vue's default icon.

<img width="189" alt="image" src="https://github.com/apache/skywalking/assets/1960537/b9b66522-06fb-4ac6-93d7-844880b78aeb">

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Muyu-art** [comment]
导师你好，我是范茂茂，我可以先解决这个issue

**Comment by Sylvie-Wxr** [comment]
I am interested in taking this task~ Can assign this to me.
