### ISSUE TITLE
[Feature] [BanyanDB-UI] Add Measure IndexRule and IndexRuleBinding Pages

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#11979]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The "Stream" Page has supported reading, editing, and deleting IndexRule and IndexRuleBinding, as the screenshot shows:

<img width="764" alt="image" src="https://github.com/apache/skywalking/assets/1960537/1405715c-221b-47fc-a2f9-23594fee8c4d">

This proposal aims to introduce operations for reading, editing, and deleting below resources:

1. IndexRule
2. IndexRuleBinding
3. [TopNAggregation](https://github.com/apache/skywalking-banyandb/blob/main/docs/api-reference.md#banyandb-database-v1-TopNAggregation). It's an additional resource that does not exist in the "Stream".

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Sylvie-Wxr** [comment]
I am interested in taking this task~ Please assign to me.
