### ISSUE TITLE
[Bug] RestResponseInterceptor 的http返回状态码处理

### ISSUE THREAD

**Issue by hepengju** [apache/skywalking#11998]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

问题：当使用RestTemplate调用第三方接口时，如果对方返回的状态码不是Http规范的状态码枚举值报错非常参数异常（比如调用飞书发送消息接口，部分场景返回状态码 444）：

// 内部通过valueOf转换为HttpStatus，转换失败抛出非法参数异常
int statusCode = response.getStatusCode().value();  
==> 
// 直接获取原始状态码
int statusCode = response.getRawStatusCode();  

### What you expected to happen

如果对方返回的状态码不是Http规范的状态码，程序继续运行

### How to reproduce

无需复现，查看下源码即可明白

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No Chinese discussion on GitHub.
