### ISSUE TITLE
skywalking GRPCLog日志查询中使用自定义标签（Use custom tags on the log query page）

### ISSUE THREAD

**Issue by wranglerlmx** [apache/skywalking#11991]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在链路追踪页面通过官方文档方式正确配置：SW_SEARCHABLE_TAG_KEYS 属性即可实现按照标签查询目标内容。
<img width="897" alt="未命名" src="https://github.com/apache/skywalking/assets/35132650/8a00c56a-2f62-4926-8f9e-d1e87dc5d6ec">

但是在日志页签下是无法按照自定义标签查询日志内容的（大大降低了 tag 原始的设计初衷：通过 tag 查询关联日志内容）。
通过对 agent 源码的检查，发现 GRPCLog 日志收集内部写死了仅上传：level、logger、thread 三个标签到 skywalking 服务器上。**所以即使配置了 SW_SEARCHABLE_ALARM_TAG_KEYS 依然无法按照标签查询日志**。
<img width="917" alt="未命名" src="https://github.com/apache/skywalking/assets/35132650/200723d3-6738-4e7e-82c8-79b9aa93a1b1">

实现方案：修改探针中 apm-toolkit-activation 对应包中的 GRPCLogAppenderInterceptor 实现类 transform() 方法中，添加自定义标签。再在 SW_SEARCHABLE_ALARM_TAG_KEYS 中配置该标签。即可实现查询。
<img width="993" alt="未命名" src="https://github.com/apache/skywalking/assets/35132650/b74e9f66-d64d-443d-ad2c-598d4ea7d70e">

**建议官方在探针中添加可以灵活记录自定义标签的方法，配合 apm-toolkit-xxx  使用。（It is recommended that the official add a method to record custom tags flexibly in the probe, which can be used in conjunction with apm-toolkit-xxx！！！）**

### Use case

日志页签下是无法按照自定义标签查询日志内容的（大大降低了 tag 原始的设计初衷：通过 tag 查询关联日志内容）

### Related issues

建议官方在探针中添加可以灵活记录自定义标签的方法，配合 apm-toolkit-xxx  使用。（It is recommended that the official add a method to record custom tags flexibly in the probe, which can be used in conjunction with apm-toolkit-xxx！！！）

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No Chinese discussion on GitHub. If you want to be in Chinese, go to CN slack channel.
