### ISSUE TITLE
Properties page not loading up in skywalking banyandb UI

### ISSUE THREAD

**Issue by sksDonni** [apache/skywalking#12007]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

The properties page of skywalking banyanDB is not loading due to some error with the route parameter when we interact with the side panel. 
Screen grab of the current behaviour - 

Uploading Screen Recording 2024-03-12 at 2.01.42 AM.mov…

### What you expected to happen

The properties page loads up with data of the property being listed.

### How to reproduce

Build skywalking banyanDB with the most recent changes to the main branch. Create a property under any group with the catalog flag set to `CATALOG_UNSPECIFIED`. 

### Anything else

Env and data which can be useful for reproducing the issue-

Env = Mac M1
Go version - go version go1.22.0 darwin/arm64
Node version - 20.9
NPM version - 10.1.0

The error in the console-
```
index.d92c580a.js:1 Error: Missing required param "pathMatch"
    at Object.l [as stringify] (index.d92c580a.js:9:7089)
    at Object.u [as resolve] (index.d92c580a.js:9:10432)
    at m (index.d92c580a.js:9:18117)
    at M (index.d92c580a.js:9:18859)
    at Object.w [as push] (index.d92c580a.js:9:18485)
    at Q (index.22e26f47.js:1:7185)
    at onClick (index.22e26f47.js:1:15799)
    at Fi (index.d92c580a.js:1:14597)
    at da (index.d92c580a.js:1:14676)
    at e$ (index.d92c580a.js:1:16713)
 ```
data -
```
>>> ./bydbctl group get -g sw_metric
<<< Using config file: /Users/sukrutha/.bydbctl.yaml
group:
  catalog: CATALOG_UNSPECIFIED
  metadata:
    createRevision: "8"
    group: ""
    id: 0
    modRevision: "8"
    name: sw_metric
  resourceOpts:
    blockInterval:
      num: 2
      unit: UNIT_HOUR
    segmentInterval:
      num: 1
      unit: UNIT_DAY
    shardNum: 2
    ttl:
      num: 7
      unit: UNIT_DAY
  updatedAt: null
```

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
The screen grab was not uploaded in the issue. And assigned to you.
