### ISSUE TITLE
[Feature][javaagent][es-plugin] Optimize the handling of the `xxxAsync` method span

### ISSUE THREAD

**Issue by JorringHsiao** [apache/skywalking#12010]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, both synchronous method (ex. **org.elasticsearch.client.RestHighLevelClient#`search`**) and asynchronous method (ex. **org.elasticsearch.client.RestHighLevelClient#`searchAsync`**) complete the span after the method call completes. 

This is normal for synchronous methods, *however for asynchronous methods, the elapsed time in its span is incorrect*.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you want to enhance that, you could mark span as async mode, and close in the callback.

**Comment by wu-sheng** [comment]
As usual, this is not covered by maintainers. Feel free to contribute.
