### ISSUE TITLE
[Bug] php agent cant report 

### ISSUE THREAD

**Issue by pan269** [apache/skywalking#12034]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

使用php-fpm时，无法上报，日志里面显示
ERROR shutdown: skywalking_agent::channel: channel send failed err=No such file or directory (os error 2)

### What you expected to happen

我希望使用php-fpm时能正常上报

### How to reproduce

php版本7.4  angent版本0.7.0 直接按照扩展后使用fpm模式运行均可触发

### Anything else

发生错误的原因是socket_file文件生成以后被删除了
在worker.rs 中去除 这一段 WorkerExitGuard的drop就可以修复这个问题，
![image](https://github.com/apache/skywalking/assets/6386193/b4d78ca0-7ec8-422c-b6be-ff26fb025aef)
不过这样会导致之前的sock文件一直残留在那里

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Use the English on GitHub communication, please.  Please submit a new one in English.
