### ISSUE TITLE
[Bug] SkyWalking Operator helm does not yet include the CRD for BanyanDB.

### ISSUE THREAD

**Issue by yswdqz** [apache/skywalking#12040]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Helm Chart (apache/skywalking-helm)

### What happened

When installing the SWCK operator using Helm, a CRD called 'BanyanDB' is required. However, this CRD is not directly provided in the Helm charts. Currently, it can only be installed by executing make -C operator install from the root path of SWCK.

<img width="1027" alt="image" src="https://github.com/apache/skywalking/assets/74546965/07b58cbf-8079-4aea-8efa-50de6ad3851c">

### What you expected to happen

'BanyanDB' crd will automaticly install when we install the SWCK operator using Helm.

### How to reproduce

Installing the SWCK operator using Helm without running make install in the SWCK root directory.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We need to check whether this is a SWCK issue or helm repo or banyandb helm repository.

**Comment by wu-sheng** [comment]
This is addressed helm needs a new release and align with swck latest updates, e.g. CRD.

**Comment by junit** [comment]
Have you solved it？

**Comment by dashanji** [comment]
Fix in https://github.com/apache/skywalking-helm/pull/146
