### ISSUE TITLE
[Bug] Hybird Compilation Issue with SkyWalking Go on Windows

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#12068]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Go Agent (apache/skywalking-go)

### What happened

When using the Go Agent to attempt hybrid compilation on an existing project in the Windows platform, an error message will be prompted, causing the Hybird compilation operation to fail.
![image (1)](https://github.com/apache/skywalking/assets/3417650/513c94d3-ab06-4445-9184-a093342c886a)

### What you expected to happen

On the Windows platform, user can use Go Agent to hybrid complete the project.users

### How to reproduce

1. Download the latest released go agent from [website](https://skywalking.apache.org/downloads/#GoAgent)
2. Build the project by [documentation](https://skywalking.apache.org/docs/skywalking-go/next/en/setup/gobuild/).

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mrproliu** [comment]
> Is this provided for students? I saw milestone is set, which may be released in 3-5 months?

Currently, there is no confirmed anyone available to handle it. I am clear the milestone now.

**Comment by wu-sheng** [comment]
> This is a good first issue for OSPP students to try out and get familiar with the contribution process at SkyWalking.
> 
> Hint: windows uses backslash \ to separate paths.

I think @mrproliu has added skywalking-go toolkit as OSPP task. This is open for other volunteers. We have 8 tasks for OSPP, maybe 1 more is available.

**Comment by Superskyyy** [comment]
> > This is a good first issue for OSPP students to try out and get familiar with the contribution process at SkyWalking.
> > Hint: windows uses backslash \ to separate paths.
> 
> I think @mrproliu has added skywalking-go toolkit as OSPP task. This is open for other volunteers. We have 8 tasks for OSPP, maybe 1 more is available.

Yeah I just mean this one can be an entry level task for potential candidates to try, this one involves minimal changes and not really blocking to many users.

**Comment by wu-sheng** [comment]
@mrproliu You could assign this to your toolkit task candidates to verify their basic capabilities. I think for students, Windows is not an issue.

**Comment by fzc721216** [comment]
If this issue is not a reserved task for OSPP, I can try to fix it.

**Comment by wu-sheng** [comment]
> If this issue is not a reserved task for OSPP, I can try to fix it.

This is not assigned to anyone AFAIK.

**Comment by fzc721216** [comment]
Okay, thank you for the answer

**Comment by Superskyyy** [comment]
> Okay, thank you for the answer

Feel free to do it. Assigned to you.

**Comment by ShyunnY** [comment]
I want to try it as my first entry-level task in `skywalking-go`, thanks  :)

**Comment by mrproliu** [comment]
> I want to try it as my first entry-level task in `skywalking-go`, thanks  :)

Welcome!

**Comment by Soce1lo** [comment]
Hello! I’m very interested in giving this issue a try as a way to practice and get more familiar with skywalking-go. Would it be possible for me to work on this, perhaps in collaboration with the current assignee? I'm eager to contribute and learn more. Thanks!

**Comment by Superskyyy** [comment]
Close as fixed, thanks for the contribution.
