### ISSUE TITLE
[Bug] Tag family not showing up

### ISSUE THREAD

**Issue by Sylvie-Wxr** [apache/skywalking#12062]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

When adding tag in BanyanDB web app, the tag family is not showing up. Hence, user is unable to add tag in Web App. 

![bug](https://github.com/apache/skywalking/assets/129717259/3b147120-2005-478a-a650-bb7209439dc9)
 

### What you expected to happen

Tag family should show up. Or allow `empty` tag family when adding tag. 

### How to reproduce

Go to BanyanDB Web App. Create Measure, then add tag. 

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
@Sylvie-Wxr Is there any update?

**Comment by Sylvie-Wxr** [comment]
I found that this actually requires entering the tag family first, and then you can select from the dropdown, so the function is not problematic. It's just not very intuitive. I'll go ahead and close the issue first.

**Comment by Sylvie-Wxr** [comment]
I found that this actually requires entering the tag family first, and then you can select from the dropdown, so the function is not problematic. It's just not very intuitive. I'll go ahead and close the issue first.
