### ISSUE TITLE
[Bug]  skywalking-showcase docker deployment has some incorrect parts

### ISSUE THREAD

**Issue by yswdqz** [apache/skywalking#12077]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Showcase (apache/skywalking-showcase)

### What happened

1. rocketmq-feature seems incorrect:
<img width="905" alt="image" src="https://github.com/apache/skywalking/assets/74546965/453f26fe-2486-4fa0-92f3-efe43e21599d">
I believe that a feature should utilize a common OAP(such as single-node) instead of spinning up a new one. Additionally, there are issues with the configuration of this OAP. 

2. whether we need to expose this port?
<img width="965" alt="image" src="https://github.com/apache/skywalking/assets/74546965/9090f8f7-aeda-4b8e-9cec-87f22c302de3">

3. oap dependency
<img width="496" alt="image" src="https://github.com/apache/skywalking/assets/74546965/974c244e-d217-434f-b9f0-bf8a3b1c5915">
Some feature depend on oap. However, in some cases, we only need these services and do not require the built-in OAP.

and also, some config files use oap as host: 
<img width="887" alt="image" src="https://github.com/apache/skywalking/assets/74546965/8cd4c623-9394-482b-8755-3ddbc130c116">
so we can't easily edit Makefile to change oap address.
<img width="874" alt="image" src="https://github.com/apache/skywalking/assets/74546965/2ad3db87-bf2d-4b04-9b9e-5defcad7cf68">

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@kezhenxu94 Could you guide @yswdqz about this? We may need to polish showcase.

**Comment by kezhenxu94** [comment]
> 1. rocketmq-feature seems incorrect:
> 
> <img alt="image" width="905" src="https://private-user-images.githubusercontent.com/74546965/320372769-453f26fe-2486-4fa0-92f3-efe43e21599d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTkyNTksIm5iZiI6MTcxMjU1ODk1OSwicGF0aCI6Ii83NDU0Njk2NS8zMjAzNzI3NjktNDUzZjI2ZmUtMjQ4Ni00ZmEwLTkyZjMtZWZlNDNlMjE1OTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA2NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjM2IzOWJjNmFhZWUyYWRlN2E4YTJlZmM1YmQ0NDU0MGQ2OTE4NGRhMjk4Y2I3NzQxMzQwNzJhMTg0MjdlM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lquFeeCdN7A5JyD69XwqxEIW-BC6ZnF-uNx7Ukeo_Oc"> I believe that a feature should utilize a common OAP(such as single-node) instead of spinning up a new one. Additionally, there are issues with the configuration of this OAP.

Nice catch! I think we can fix this by simply removing the OAP section in this docker compose file.

> 2. whether we need to expose this port?
> 
> <img alt="image" width="965" src="https://private-user-images.githubusercontent.com/74546965/320374139-9090f8f7-aeda-4b8e-9cec-87f22c302de3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTkyNTksIm5iZiI6MTcxMjU1ODk1OSwicGF0aCI6Ii83NDU0Njk2NS8zMjAzNzQxMzktOTA5MGY4ZjctYWVkYS00YjhlLTljZWMtODdmMjJjMzAyZGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA2NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwN2FjYjNhNDkxOGJkM2RiMjQ0ZmU5MjEyOThiM2M3NDg1ZmQ2NjdkZDYzYThmYjFjNWU3ZDE4ZTM0OWEyZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L4B8mNfInUIeT3AXJJJAjXCPflqEzUvEVw4sTdEBDvM">

This is not mandatory as we have a loadgen to trigger traffic, however, if users want to manually trigger traffic, they can open this port in their browser.

> 3. oap dependency
> 
> <img alt="image" width="496" src="https://private-user-images.githubusercontent.com/74546965/320374564-974c244e-d217-434f-b9f0-bf8a3b1c5915.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTkyNTksIm5iZiI6MTcxMjU1ODk1OSwicGF0aCI6Ii83NDU0Njk2NS8zMjAzNzQ1NjQtOTc0YzI0NGUtZDIxNy00MzRmLWI5ZjAtYmY4YTNiMWM1OTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA2NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYmM5YjMxODliMDdlZWMwNjFiNmYwZDFkYzU4YmZmNTRjZGQwNjAyZGNlY2MzY2E1ZjIyMTc0OTk0OWEzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sMEVeL07fpF7ged9QCTAQbV84xJDdtCoQwBFioGvtwI"> Some feature depend on oap. However, in some cases, we only need these services and do not require the built-in OAP.

Can you elaborate? OAP is required to be up and running for those components that need to talk to OAP, in your screenshot, the vm exporter needs to send data to OAP so it needs to wait for OAP's readiness.

> and also, some config files use oap as host: <img alt="image" width="887" src="https://private-user-images.githubusercontent.com/74546965/320376116-8cd4c623-9394-482b-8755-3ddbc130c116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTkyNTksIm5iZiI6MTcxMjU1ODk1OSwicGF0aCI6Ii83NDU0Njk2NS8zMjAzNzYxMTYtOGNkNGM2MjMtOTM5NC00ODJiLTg3NTUtM2RkYmMxMzBjMTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA2NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MDM2NzY0N2JjMzc5ODkxNTE1YWNjMGNmYjI2NmMxYjRhZDM2OWM4YTY5NDlkYjhjMmEyZjhjZTZmOWIyMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WsRYZXCM1anjGoGiBEoJNxbksBO11I3hEqhWz3KnZcI"> so we can't easily edit Makefile to change oap address. <img alt="image" width="874" src="https://private-user-images.githubusercontent.com/74546965/320376621-2ad3db87-bf2d-4b04-9b9e-5defcad7cf68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTkyNTksIm5iZiI6MTcxMjU1ODk1OSwicGF0aCI6Ii83NDU0Njk2NS8zMjAzNzY2MjEtMmFkM2RiODctYmYyZC00YjA0LTliOWUtNWRlZmNhZDdjZjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA2NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NWExMDQxNTRiNjY2OWZkNTFmMDlhNTcyZjM0YmJhNWI5YzY2NmJmMTMxYzdlNWUwZDljYjdiNmViODUzNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YEkHZ72pdniuIGVAkvgioV3qx0jgZTUslYOct0sG4Cs">

Good catch, this can be replace with the env var `BACKEND_SERVICE`.

Will you file a pull request @yswdqz ?

**Comment by yswdqz** [comment]
Yes, but I might not have much time recently. I'll submit the PR over the weekend.

**Comment by yswdqz** [comment]
> Can you elaborate? OAP is required to be up and running for those components that need to talk to OAP, in your 
> screenshot, the vm exporter needs to send data to OAP so it needs to wait for OAP's readiness

Maybe we just need VM-monitor feature, and I just want run with "make deploy.docker FEATURE_FLAGS=vm"(not  FEATURE_FLAGS=vm,single-node)

**Comment by kezhenxu94** [comment]
> > Can you elaborate? OAP is required to be up and running for those components that need to talk to OAP, in your
> > screenshot, the vm exporter needs to send data to OAP so it needs to wait for OAP's readiness
> 
> Maybe we just need VM-monitor feature, and I just want run with "make deploy.docker FEATURE_FLAGS=vm"(not FEATURE_FLAGS=vm,single-node)

This doesn't make sense as this is a "skywalking" showcase, we don't bother to make it work without skywalking

**Comment by yswdqz** [comment]
> 
> This doesn't make sense as this is a "skywalking" showcase, we don't bother to make it work without skywalking


Sorry, my expression was not very clear. 
My meaning is, some people (including myself) may want to import data into an external OAP, rather than using a single-node.

**Comment by wu-sheng** [comment]
> 
> 
> > 
> 
> > This doesn't make sense as this is a "skywalking" showcase, we don't bother to make it work without skywalking
> 
> 
> 
> 
> 
> Sorry, my expression was not very clear. 
> 
> My meaning is, some people (including myself) may want to import data into an external OAP, rather than using a single-node.

That is not showcase. We don't need to consider that.
