### ISSUE TITLE
[Bug] Windows Metrics Name -- "Swap" => "Virtual Memory"

### ISSUE THREAD

**Issue by lagagain** [apache/skywalking#12105]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Windows metrics that include `swap` are from 'virtual memory', but swap is not equal to virtual memory.

With [MSINFO32.exe](https://www.techtarget.com/searchenterprisedesktop/tip/Learn-native-Windows-10-virtual-memory-management-methods), we could see resources' current status, including physical memory and virtual memory and page file size.

As I know, [Virtual Memory] = [Physical Memroy] + [Swap].
And Zabbix Agent read swap number is page file.

### What you expected to happen

Rename metrics:
- memory_swap_free => memory_virtual_memory_free 
- memory_swap_total => memory_virtual_memory_total
- memory_swap_percentage => memory_virtual_memory_percentage

(There is two 'memory' in each metry, so may have another better name.)

### How to reproduce

remove document or table - ui_template_Windows-Service - in database, or using empty database.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> And Zabbix Agent read swap number is page file.

What does this mean?

**Comment by lagagain** [comment]
> > And Zabbix Agent read swap number is page file.
> 
> What does this mean?

I found this problem is because the value in Zabbix Dashboard different from SkyWalking Monitor.
In Zabbix, the labels are 'Free swap space', 'Total swap space', 'Free swap space in %'
