### ISSUE TITLE
[Bug] UI: optimize search reset in  marketplace menu

### ISSUE THREAD

**Issue by CzyerChen** [apache/skywalking#12127]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

<img width="1011" alt="image" src="https://github.com/apache/skywalking/assets/22817918/9a8f340e-1b87-4ee6-b9a3-94b0e8121dcb">

1、First in, highlight the first card
2、Search something, highlight the first one after filter
3、Clear and search, still highlight the last search --> It may be better to highlight the first card like the first time

### What you expected to happen

Hope that
3、Clear and search, highlight the first card like first in rather than the last highlight

### How to reproduce

1、First in, highlight the first card
2、Search something, highlight the first one after filter
3、Clear and search, see the highlighted card

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
fyi @Fine0830
