### ISSUE TITLE
[Bug] Feign uses Okhttp connection pool, resulting in long display time for Skywalking UI

### ISSUE THREAD

**Issue by xiaozichen** [apache/skywalking#12139]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

aop: 8.9.1
ui: 8.9.1
agent: 8.13.0
springCloudAlibaba: 2021.0.1.0

The use of feign and Okhttp connection pools in microservices leads to connection reuse, resulting in a long display time in the UI
![image](https://github.com/apache/skywalking/assets/24701842/5fb5ca23-d778-4ecf-b339-85121388cd17)

### What you expected to happen

request time is to long

### How to reproduce

The feign request has ended, and the time of the connection thread should not be taken, but rather the time when the call ended

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Why are you keeping opening mew things?

**Comment by wu-sheng** [comment]
Close as duplicate.
