### ISSUE TITLE
[Feature] please ,can you tell you ,what issue? 

### ISSUE THREAD

**Issue by xiaozichen** [apache/skywalking#12141]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://github.com/apache/skywalking/issues/12139#issuecomment-2068330194

### Use case

please

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I have kept one open for discussion. If you keep doing this, I will have to block you.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/discussions/12137
