### ISSUE TITLE
[Bug] in java 8, Can't split endpoint id into 2 parts in Virtual Cache query trace detail

### ISSUE THREAD

**Issue by ibingdian** [apache/skywalking#12145]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

In version 9.3.0 . use java8. 
When i query Virtual cache Slow Statements trace detail , I got this error : "Exception while fetching data (/endpoint) : Can't split endpoint id into 2 parts, b883efe43a8e45baae72dfd3b040c2bf.80.16843019257611193"。

how to fix the problem in java 8, my Issue is similer to https://github.com/apache/skywalking/discussions/10818

### What you expected to happen

the endpointid could cause the error

### How to reproduce

I click this "查看相关trace".
![1713780300898](https://github.com/apache/skywalking/assets/13306569/9fe72b70-cfcf-4ecf-b2a7-56ad46e41136)

then i got this error.
![1713780141050](https://github.com/apache/skywalking/assets/13306569/3c059c6b-0871-439e-840c-2cea63d3b98d)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
9.3 is super old. Upgrade to latest.

**Comment by ibingdian** [comment]
we can only use java 8 , if Upgrade ,the java 8 not support

**Comment by ibingdian** [comment]
> 9.3 is super old. Upgrade to latest.

we can only use java 8 , if Upgrade skywalking ,the java 8 not support

**Comment by wu-sheng** [comment]
SkyWalking doesn't maintain in that way. I can't tell which commits are relative fixes.
