### ISSUE TITLE
No traceId In trace page sometimes

### ISSUE THREAD

**Issue by candyleer** [apache/skywalking#1215]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  master latest
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/11530760/39927587-5e5c59b0-5565-11e8-8ae5-e6b3d50decb3.png)

request
```
http://localhost:8000/api/trace
```
params
```
{"variables":{"condition":{"queryDuration":{"start":"2018-05-11 2133","end":"2018-05-11 2148","step":"MINUTE"},"paging":{"pageNum":1,"pageSize":20,"needTotal":true}}},"query":"\n  query BasicTraces($condition: TraceQueryCondition) {\n    queryBasicTraces(condition: $condition) {\n      traces {\n        key: segmentId\n        operationName\n        duration\n        start\n        isError\n        traceIds\n      }\n      total\n    }\n  }\n"}
```
response
```
{"data":{"queryBasicTraces":{"traces":[{"key":"129.71.15260465125720000","operationName":"test","duration":2434,"start":"1526046512572","isError":false,"traceIds":[]},{"key":"129.99.15260465124670000","operationName":"httpasyncclient/local","duration":2650,"start":"1526046512475","isError":false,"traceIds":[]},{"key":"129.70.15260465045920000","operationName":"http_async","duration":8130,"start":"1526046504605","isError":false,"traceIds":[]},{"key":"128.71.15260463138370000","operationName":"test","duration":2360,"start":"1526046313837","isError":false,"traceIds":["128.70.15260463128650001"]},{"key":"128.95.15260463137540000","operationName":"httpasyncclient/local","duration":2456,"start":"1526046313768","isError":false,"traceIds":["128.70.15260463128650001"]},{"key":"128.70.15260463128630000","operationName":"http_async","duration":965,"start":"1526046312872","isError":false,"traceIds":["128.70.15260463128650001"]},{"key":"127.73.15260460367340000","operationName":"test","duration":2006,"start":"1526046036734","isError":false,"traceIds":["127.72.15260460367160001"]},{"key":"127.102.15260460367290000","operationName":"Queue/channel-local","duration":2010,"start":"1526046036730","isError":false,"traceIds":["127.72.15260460367160001"]},{"key":"127.72.15260460367160000","operationName":"http_async","duration":20,"start":"1526046036716","isError":false,"traceIds":["127.72.15260460367160001"]},{"key":"127.71.15260460258600000","operationName":"test","duration":2427,"start":"1526046025860","isError":false,"traceIds":["127.70.15260460251120001"]},{"key":"127.94.15260460258000000","operationName":"Queue/channel-local","duration":2510,"start":"1526046025805","isError":false,"traceIds":["127.70.15260460251120001"]},{"key":"127.70.15260460251100000","operationName":"http_async","duration":732,"start":"1526046025122","isError":false,"traceIds":["127.70.15260460251120001"]},{"key":"126.79.15260459222620000","operationName":"test","duration":2011,"start":"1526045922262","isError":false,"traceIds":["126.79.15260459222620001"]},{"key":"126.109.15260459222570000","operationName":"Queue/channel-local","duration":2016,"start":"1526045922258","isError":false,"traceIds":["126.78.15260459222460001"]},{"key":"126.78.15260459222460000","operationName":"http_async","duration":20,"start":"1526045922246","isError":false,"traceIds":["126.78.15260459222460001"]},{"key":"126.76.15260458893100000","operationName":"test","duration":2439,"start":"1526045889310","isError":false,"traceIds":["126.76.15260458893100001"]},{"key":"126.103.15260458892350000","operationName":"Queue/channel-local","duration":2527,"start":"1526045889239","isError":false,"traceIds":["126.75.15260458884270001"]},{"key":"126.75.15260458884260000","operationName":"http_async","duration":919,"start":"1526045888435","isError":false,"traceIds":["126.75.15260458884270001"]},{"key":"125.79.15260456986460004","operationName":"${server.error.path:${error.path:/error}}","duration":9,"start":"1526045698646","isError":true,"traceIds":["125.79.15260456986460005"]}],"total":19}}}
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by hanahmily** [comment]
There is no `traceId` in response data. Can @peng-yongsheng help to handle this?

**Comment by wu-sheng** [comment]
How could this cause that? Can you be more specific?

**Comment by candyleer** [comment]
the `TraceSegment` save in es, but the `global_trace` is on the way to save to es. so some trace don't have global trace id.

**Comment by wu-sheng** [comment]
> the TraceSegment saved in es, but the global_trace is on the way to save to es. so some trace don't have global trace id.should wait for a moment

But the time is uncertain, it depends on the throughput. Do you have some ideas? From my experience, look like hard to say, except to do query multiple time, and filter half-save data.

**Comment by peng-yongsheng** [comment]
Delay times will be more and more longer when collector received too much segments. I suggest that setting the start time at the 20 seconds before when query trace information.

**Comment by wu-sheng** [comment]
+1 FYI @hanahmily

**Comment by wu-sheng** [comment]
but only effect default query.

**Comment by hanahmily** [comment]
Segment without trace id is invalid data which should be removed in response. If more and more segments that are received concurrently by collectors would increase latency, 20 second is perhaps insufficent.

**Comment by wu-sheng** [comment]
> Segment without trace id is invalid data which should be removed in response. If more and more segments that are received concurrently by collectors would increase latency, 20 second is perhaps insufficent.

@hanahmily This is caused by no database(ElasticSearch) transaction guarantee. These info belongs two types(tables). So, if backend does query in this way, they have to query again and again, that will cause the performance concern. Do you have any suggestion?

**Comment by hanahmily** [comment]
>  These info belongs two types(tables)

Convert two types to one? If all fields of the result are coming from one type, there's not inconsistent.

**Comment by wu-sheng** [comment]
@peng-yongsheng have any chance to do so? At least in es, I assume it is possible.

**Comment by wu-sheng** [comment]
Do we have plans to do any upgrades about this? Or should I put this into `TODO` or `help wanted`?

**Comment by wu-sheng** [comment]
I push this into further discussion. No good plan.

**Comment by wu-sheng** [comment]
6.x release, no feedback.
