### ISSUE TITLE
[Feature] provides sample option in python agent

### ISSUE THREAD

**Issue by tsonglew** [apache/skywalking#12155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Support sample option like `SW_AGENT_SAMPLE` in java agent

### Use case

Reduce the trace storage load

### Related issues

#5997

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
fyi @Superskyyy

**Comment by CodePrometheus** [comment]
Could you briefly describe your idea? Is it possible to dynamically update the value of sample based on the configuration file?

**Comment by wu-sheng** [comment]
> Could you briefly describe your idea? Is it possible to dynamically update the value of sample based on the configuration file?

@CodePrometheus Could you be more specific about this? What do you mean based on file?

The above logic seems to be as same as Java agent sampling.

**Comment by CodePrometheus** [comment]
> @CodePrometheus Could you be more specific about this? What do you mean based on file?
> 
> The above logic seems to be as same as Java agent sampling.

Yes, the above logic is similar to the existing `sample_n_per_3_secs` in Java agent. I want to refer to dynamic configuration, ref https://github.com/apache/skywalking/issues/6114

**Comment by wu-sheng** [comment]
I am not sure whether python agent supports dynamic configuration in the kernel already? @Superskyyy

**Comment by CodePrometheus** [comment]
> I am not sure whether python agent supports dynamic configuration in the kernel already? @Superskyyy

Currently, this capability is not implemented in python-agent.

**Comment by wu-sheng** [comment]
@tsonglew Are you going to add this too?

**Comment by tsonglew** [comment]
> @tsonglew Are you going to add this too?

Yes, I will create another mr for config change events

**Comment by wu-sheng** [comment]
Is there any update about this feature?

**Comment by tsonglew** [comment]
I'm still working on it. I will make it done within three weeks.
