### ISSUE TITLE
[BanyanDB-Server] Improve sorting and filtering performance of Stream 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12160]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The current filtering and sorting operations scan through all parts to locate a single record in a loop. As the number of parts increases, this method can cause delays and slow down the scanning process. 

To resolve this issue, the operations should refer to the standard query, which leverages the tsTableIterator to scan parts only once.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Is this in 0.6 or next 0.7?

**Comment by hanahmily** [comment]
> Is this in 0.6 or next 0.7?

It will be in the next one, so I didn't tag it as 0.6.
