### ISSUE TITLE
[Feature] 是否可以实现多个Tracing链路信息合成

### ISSUE THREAD

**Issue by wl2027** [apache/skywalking#12177]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

OpenTracing中最大单位是单个链路,但是像一些工作流或状态机这类的操作往往都是多个链路组合,如果想组合起来观测这种流转状态,除了在链路上标记业务的key,还有别的实现将多个tracing组合成简单直观数据流的方式吗?类似工作流中的办理日志这类,不过是办理链路的日志这样

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you need Chinese discussion, go to slack CN channel.
