### ISSUE TITLE
Is it time to reconsider agentmain?

### ISSUE THREAD

**Issue by renwanqian** [apache/skywalking#12199]
No, we are not using that. If you have interests, read the document about the differences. We need to change class structure, so agentmain is not the option.

_Originally posted by @wu-sheng in https://github.com/apache/skywalking/issues/3326#issuecomment-524740175_

**Comment by wu-sheng** [comment]
No, we are not.

**Comment by renwanqian** [comment]
datadog's agent has implemented dynamic instrumentation, it works, and wonderful!
so, i think it's time to reconsider agentmain

**Comment by wu-sheng** [comment]
Datadog is a company, what they want to do or did are from commercial driven.

This is not a factor for us.

**Comment by renwanqian** [comment]
The dynamic instrumentation will be a perfect feature.
On the one hand, it enables the applications to be traced without restarting, on the other hand, it enables the configurations to be dynamically updated at any time. Although there is Configuration Discovery, but it supports too few keys.
It will be a great way of removing barriers for tracing.
