### ISSUE TITLE
skywalking无法追踪springboot actuator/health每个阶段的耗时，只有一个总耗时，skywalking是不支持吗

### ISSUE THREAD

**Issue by john1337** [apache/skywalking#12197]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

skywalking无法追踪springboot actuator/health每个阶段的耗时，只有一个总耗时，skywalking是不支持吗，无法跟踪nacos client的请求耗时

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No Chinese discussion on github, use slack CN channel, nd discussion panel only.
