### ISSUE TITLE
[Feature] Add URLParser for Derby/Sybase/SQLite/DB2/OceanBase

### ISSUE THREAD

**Issue by CzyerChen** [apache/skywalking#12207]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

current DB types in URLParser :
- MYSQL
- ORACLE
- H2
- POSTGRESQL
- MARIADB
- MSSQL
- KYLIN
- IMPALA
- CLICKHOUSE

I want to add  URL parsing types:
- Derby
- Sybase
- SQLite
- DB2
- OceanBase

### Use case

When the database connection pool  connecting to `Derby/Sybase/SQLite/DB2/OceanBase`, JDBC URL can be parsed and the monitoring meters can be reported.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Can we make sure the only gap for tracing these databases JDBC access are about this?
Because AFAIK, if we don't add instrument for driver explicitly, the connection info is still missing.

**Comment by CzyerChen** [comment]
> Can we make sure the only gap for tracing these databases JDBC access are about this?
> Because AFAIK, if we don't add instrument for driver explicitly, the connection info is still missing.

None of these databases have plugins to track SQL statements now, and adding these URLParsers can make connection pools report pool metrics of these databases successfully.
<img width="911" alt="image" src="https://github.com/apache/skywalking/assets/22817918/1261d60b-2b39-4c73-b097-5247771ba200">

Meanwhile, for database connection pools like druid/c3p0, it is necessary to optimized the part on obtaining `ConnectionInfo` of the database that have not yet implemented monitoring to avoid NPE.

**Comment by wu-sheng** [comment]
> None of these databases have plugins to track SQL statements now, and adding these URLParsers can make connection pools report pool metrics of these databases successfully.

So, this is for meter plugin enhancement. Please update docs here as well, https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/supported-list/#meter-plugins, to list all supported database.

**Comment by CzyerChen** [comment]
> https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/supported-list/#meter-plugins

OK.

**Comment by gd911314** [comment]
May I inquire if Oracle is monitored directly rather than via a Java agent? Additionally, could you provide information on how the metrics are displayed and whether there is any available tutorial or documentation regarding this process?

**Comment by wu-sheng** [comment]
What fo you mean by directly rather than agent? Here are agent analysid codes.
