### ISSUE TITLE
Look someone to contribute Python SDK

### ISSUE THREAD

**Issue by liuwei881** [apache/skywalking#1221]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liuwei881** [comment]
sky walking是否提供python 的api?

**Comment by wu-sheng** [comment]
You could see from the readme. SkyWalking is supporting multiple languages, Java, .NET, Nodejs. Go is still ongoing. But you should understand , we didn't provide API for each language, the cummunity did.

Such as: Java from several developers, I just lead. @liuhaoyang leads the .NET. @ascrutae leads the nodejs. So if you want a python version, you could create one, and we can work together.

For multiple languages, SkyWalking provided protocol support: 
![image](https://user-images.githubusercontent.com/5441976/39981426-22a32a5a-5783-11e8-9b1e-705279f6669a.png)
These two protocols should be supported by every language.

**Comment by wu-sheng** [comment]
New protocols are here. https://github.com/apache/skywalking/blob/master/docs/en/protocols/README.md

**Comment by kezhenxu94** [comment]
https://github.com/apache/skywalking-python
