### ISSUE TITLE
[Bug] common.v3 complie error

### ISSUE THREAD

**Issue by echo20222022** [apache/skywalking#12214]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

compile error with org.apache.skywalking.apm.network.common.v3, not package and classes

### What you expected to happen

compile passed.

### How to reproduce

download the newest java agent source code, and compile it, error. and the org.apache.skywalking.apm.network.common.v3 is a inner package, it feels very bad.

i want ask the author, how to compile the code , 

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Don't know what are you talking about. Follow the compiling docs, rather than doing without enough context.

**Comment by woshiqiuxiaoyan** [comment]
我下下来也找不到这个包，他们怎么找到的神奇
