### ISSUE TITLE
[Bug] skywalking did not work with elasitcsearch 8.13+

### ISSUE THREAD

**Issue by ldcsaa** [apache/skywalking#12224]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

skywalking would start fail, while uses `elasticsearch 8.13.x` as backend storage, and it's OK while uses `elasticsearch 8.12.x` as backend storage

### What you expected to happen

Is OK while uses `elasticsearch 8.13.x` as backend storage.

### How to reproduce

 just start skywalking uses `elasticsearch 8.13.x` as backend storage.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I think we don't test for that. @kezhenxu94 right?

**Comment by kezhenxu94** [comment]
@ldcsaa can you share how OAP failed? Looks like all tests passed in https://github.com/apache/skywalking/pull/12227
