### ISSUE TITLE
[BanyanDB-Server] Optimizing the Shard Allocation Algorithm  

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

The current shard allocation algorithm in BanyanDB needs to be more efficient. All shards from all groups are put into the same allocation bucket, which can lead to uneven data distribution across shards, potentially impacting performance and scalability

Optimizing this algorithm could improve load balancing, reduce hotspots, and enhance system performance.

### What you expected to happen

Nan

### How to reproduce

Nan

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lujiajing1126** [comment]
It could be a feature rather than a bug?

**Comment by stone-98** [comment]
Can I try to handle this problem?

**Comment by wu-sheng** [comment]
> Can I try to handle this problem?

Do you have enough experience and knowledge for this feature and SkyWalking?

**Comment by stone-98** [comment]
> > Can I try to handle this problem?
> 
> Do you have enough experience and knowledge for this feature and SkyWalking?

I'm not familiar with SkyWalking right now, and I want to learn it. Sorry, I misunderstood this feature, and it might be a bit difficult for me. I'll start with simpler issues.

**Comment by wu-sheng** [comment]
It is better you could try all these out, before ask for issue/feature assignments.

What list here are mostly not that easy. So, we don't tag them good first issue.
