### ISSUE TITLE
[Feature] skywalking-php defined instance name

### ISSUE THREAD

**Issue by Almot77** [apache/skywalking#12243]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I have release customize instance_name in **skywalking-php,** maybe it will be useful
I'm not Rust programmer, sorry for miss guidelance

https://github.com/Almot77/skywalking-php/commit/2f2d2d503d8be49bdf577d42a4bc703825776592

Add two options to skywalking_agent.ini:

; Defined agent instance name
skywalking_agent.instance_name = myservername
; Use hostname as agent instance name
skywalking_agent.use_hostname_as_instance_name = On

If two options both enabled - second has higher priority.

### Use case

instance_name has rnd + ip address, i defined it in config or use hostname.
If you have one instance on host and multiple hosts - it would be comfortably.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Almot77** [comment]
$HOSTNAME is a Bash variable that's set automatically.
But it's not a Bash environment variable (i. e. it's not passed in environment to child processes). One can check this by looking at env output

$ echo $BASH_VERSION
5.1.16(1)-release
$ echo $HOSTNAME
srvdocker03
$ env | grep HOSTNAME
$

**Comment by jmjoy** [comment]
The `php-fpm.conf` also should enable the pool configuration item, such as `env[HOSTNAME] = $HOSTNAME`.

Since users can set `php.ini` through environment variables, there is no need to consider what shell the user is using, what the environment is like, and so on.

**Comment by Almot77** [comment]
Okay, you close. 
But we **havent't now** skywalking_agent.instance_name option, right ? )
May be you add it in next release ?

**Comment by wu-sheng** [comment]
You could continue the discussion if needed.

**Comment by Almot77** [comment]
Leave only skywalking_agent.instance_name option:
[https://github.com/Almot77/skywalking-php/tree/defined_instance_name](url)

**Comment by jmjoy** [comment]
Welcome to PR.

**Comment by wu-sheng** [comment]
Added by https://github.com/apache/skywalking-php/pull/111

**Comment by Almot77** [comment]
Thank you! My first open source PR and contribute :)
