### ISSUE TITLE
[Feature] Support to query relation metrics through PromQL

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#12245]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[PromQL Service](https://skywalking.apache.org/docs/main/next/en/api/promql-service/#supported-metrics-scopehttpsgithubcomapacheskywalkingtree19a2395a9ebbf7dca1bcf7aefba0c1819aad7214oap-serverserver-coresrcmainjavaorgapacheskywalkingoapservercorequeryenumerationscopejavacatalog) doesn't support metrics of relation between services, instances or endpoints.

### Use case

User could use this to build dashboards to show metrics from the lines on the topology or manually click.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@CzyerChen @weixiang1862 @yswdqz Any of you has interest in implementing this?

**Comment by wu-sheng** [comment]
> I am new to this repo - would like to pick this up. 
> 
> Can you add some more verbose details of what is required as part of the feature?

This is not easy. Do you read most of SkyWalking codebases?

**Comment by theboywholived** [comment]
I will have to do that. I am brand-new to this repo.

**Comment by wu-sheng** [comment]
I would say, you could consider to implement this. But don't be in urgent.

This requires you to have good understanding of the whole system.

**Comment by theboywholived** [comment]
I would like to take a shot at this. I will go through the docs and readme. Is there anything else you suggest me to do? Or a similar MR for a different Query language?

**Comment by wu-sheng** [comment]
You could do as following
1. Get familiar with project, and how to run showcase. https://skywalking.apache.org/docs/skywalking-showcase/next/readme/
2. Learn MQE about the protocol and native UI for relative metrics.
3. Learn PromQL service, and workflow.
4. Try to implement this.

**Comment by theboywholived** [comment]
Okay, let me do as you recommend.

**Comment by theboywholived** [comment]
@wu-sheng I only have 16 GB RAM in my mac, I am not able to run showcase:
`Release "demo" does not exist. Installing it now.`
It's stuck on this step with RAM Utilization spiking up.

Is there another alternative?

**Comment by wu-sheng** [comment]
You need to run necessary components only. Don't run the default. It includes all features.

**Comment by wu-sheng** [comment]
@yswdqz told me, he will work on this from June 2nd/3th.
