### ISSUE TITLE
[BanyanDB-Distrbuted] Duplicated data on Scaling Up

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12255]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

There may be some duplicated data that occurred after scaling up the data nodes.

![image](https://github.com/apache/skywalking/assets/1960537/55089442-6e62-4373-bd4d-73aba7e0e78a)

### What you expected to happen

No duplicated data.

### How to reproduce

Scaling up data nodes without shutting down the OAP server.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Within our discussion, we agreed that we should propagate the persistent timestamp back to liaison node from data node. The query aggregation could use that to pick the latest data.

**Comment by Superskyyy** [comment]
Hi, is this problem specific to OAP usage or it can happen whenever banyandb itself scales up?

**Comment by hanahmily** [comment]
> Hi, is this problem specific to OAP usage or it can happen whenever banyandb itself scales up?

It happens in such a scenario that several duplicated data, which have the same entity value and timestamp, are written when data nodes scale up.
