### ISSUE TITLE
[Feature] Create Fastify Plugin 🖲️ 

### ISSUE THREAD

**Issue by sajid-nymcard** [apache/skywalking#12284]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

NodeJS agent skywalking plugin for fastify server. 

### Use case

I want skywalking to trace on my nodejs fastify server. I'm using graphql on fastify [nodejs]. 

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Hi, as many of this kind of requests, we don't follow this.

We only provide dev docs, and pull request review.
