### ISSUE TITLE
[Bug] SkyWalking Java Agent 9.2 Docker image missing in the hub

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#12282]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

![image](https://github.com/apache/skywalking/assets/2568208/8fcfa88b-7f6e-4e48-9192-22ce10aad214)

### What you expected to happen

The 9.2 images exist

### How to reproduce

...

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I have pushed all images for Java agent 9.2.0
