### ISSUE TITLE
[SkyWalking UI] Introduce Flame Graph to the Trace Profiling

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#12309]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, SkyWalking's Trace Profiling feature allows users to understand where the performance bottlenecks of the current program are. However, sometimes using a tree structure to display stacks is not very intuitive, so I recommend that we introduce flame graphs for this purpose(as a new tab). Additionally, On/CPU Profiling based on eBPF has already proven this point well; using flame graphs can also effectively help users understand the call process.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@CodePrometheus Is there any progress about this?

**Comment by CodePrometheus** [comment]
> @CodePrometheus Is there any progress about this?

Still working on it, I'll create a PR when ready.

**Comment by wu-sheng** [comment]
@CodePrometheus It has been a while, are you still working on this?

**Comment by CodePrometheus** [comment]
> @CodePrometheus It has been a while, are you still working on this?

I've been busy with work and other things recently, let me try my best to complete this feature in July.
