### ISSUE TITLE
[Bug] [BanyanDB] Metrics breaks periodically 

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#12312]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

Since we switched demo database to BanyanDB, most things work well, but I noticed this kind of metric breaking.

<img width="1891" alt="image" src="https://github.com/apache/skywalking/assets/5441976/3c144b33-6cf7-4afa-ae56-eb470604ff54">

Meanwhile, this only happens on minute level, 

<img width="1544" alt="image" src="https://github.com/apache/skywalking/assets/5441976/b32ebab5-0fbf-44c7-93a9-54b8c2500de1">

All services/pods of demo env seem normal

![image](https://github.com/apache/skywalking/assets/5441976/220e6076-3ac6-4f59-bf65-8dc06859292b)

But we noticed this error happens periodically too in the OAP pod logs.

<img width="1495" alt="image" src="https://github.com/apache/skywalking/assets/5441976/e0a9bcfa-fea7-452d-8e9d-c9d638470dcb">

I also checked the BanyanDB client codes, although we don't expose the configuration to BanyanDB provider(@lujiajing1126 we should expose), but the default value is 50m. 
But this error log says, ~5m. So, @hanahmily @lujiajing1126 @ButterBright Is the server missing the configurations? And could you check whether there is other reason to make metrics breaking.

### What you expected to happen

Make metrics continuously flush into the storage.

### How to reproduce

I didn't reproduce this, but observe this on demo env.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
Seems like a client side problem, the 50MB didn't take effect.

**Comment by wu-sheng** [comment]
I didn't check that deeply. But it seems existing in the default constructor. Doesn't it?

**Comment by hanahmily** [comment]
I checked the client, and it seems that the error cannot be from the BanyanDB client.

<img width="1013" alt="image" src="https://github.com/apache/skywalking/assets/1960537/783c4ab5-30e7-4ce8-a9d5-2f5339cbbddd">

The error is related to the 'getCompressedBody' function, but the client should always use the 'getUncompressedBody' instead. BTW, `maxInboundMessageSize` is 50MB even though the client doesn't use it here.

**Comment by wu-sheng** [comment]
@wankai123 Let us bump up otel collectoe first. This seems irrelevant with DB.
