### ISSUE TITLE
[Rover] eBPF Access Log Module can not work

### ISSUE THREAD

**Issue by larrying** [apache/skywalking#12324]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

An exception occurred when using the eBPF function. For error details, see the attachment.
The version information used is as follows：
oap: 10.0.1
rover: 0.6.0
os：redhat8
kernel version: 4.18.0-372.9.1.e18.x86-64
![aae9a8b8ebe2446514005b9bfe3248b0](https://github.com/apache/skywalking/assets/31137045/3a852a26-0768-4e10-afcb-6a445dd89cc3)

### What you expected to happen

The most likely reason is that rover does not support this kernel version

### How to reproduce

If you use this kernel version, this exception may occur

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mrproliu** [comment]
Close this issue because it has been fixed.
