### ISSUE TITLE
[Bug] Install docs out of date

### ISSUE THREAD

**Issue by agilob** [apache/skywalking#12334]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I clicked on "Get started"  link from this page https://skywalking.apache.org/team/ and landed on 404 page https://github.com/apache/skywalking/blob/master/docs/en/guides/README.md

### What you expected to happen

Did not expect 404 page

### How to reproduce

Click https://skywalking.apache.org/team/

### Anything else

Also, why starting instructions are on a `/team` page? That link should be on a home page or wiki.

Opening issues in https://github.com/apache/skywalking-website is not open to public, so I'm opening it here :shrug: 

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
That link will point to a contribution docs only.

If you learn the project, you need go to docs page and choose the component docs.

Showcase and SkyWalking main docs are your start.

https://skywalking.apache.org/docs/#SkyWalking
