### ISSUE TITLE
Optimize the Trace widget for error nodes

### ISSUE THREAD

**Issue by Fine0830** [apache/skywalking#12330]
### Discussed in https://github.com/apache/skywalking/discussions/12329

<div type='discussions-op-text'>

<sup>Originally posted by **ZKANGGIT** June 13, 2024</sup>
<img width="619" alt="企业微信截图_1718265899524" src="https://github.com/apache/skywalking/assets/36831988/c871000f-771b-4201-926a-69a1979742e4">

The node that reports the error is inconspicuous and difficult to find</div>

**Comment by wu-sheng** [comment]
@Fine0830 Are you going to fix this soon?

**Comment by Fine0830** [comment]
> @Fine0830 Are you going to fix this soon?

Yes, I am.
