### ISSUE TITLE
[Bug]Skywalking-oap run WARN  [] - Unsupported metrics service_percentile

### ISSUE THREAD

**Issue by songyanping** [apache/skywalking#12344]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

describe:
Skywalking ui [Service Response Time Percentile (ms)] not data.
![sky](https://github.com/apache/skywalking/assets/17720358/6aaf4f5a-8ff1-4be6-a6b8-9ea3938fd883)
 Skywalking oap log output: WARN  [] - Unsupported metrics service_percentile

version info：
oap: v10.0.0 
ui: v10.0.0,
storageType: elasticsearch v.8.11
java agent: v9.2   

logs：
Running Mode                               |   no-init       
TTL.metrics                                |   2             
TTL.record                                 |   2             
Version                                    |   10.0.0-c92a6a3
module.agent-analyzer.provider             |   default       
module.ai-pipeline.provider                |   default       
module.alarm.provider                      |   default       
module.aws-firehose.provider               |   default       
module.cluster.provider                    |   kubernetes    
module.configuration-discovery.provider    |   default       
module.configuration.provider              |   none          
module.core.provider                       |   default       
module.debugging-query.provider            |   default       
module.envoy-metric.provider               |   default       
module.event-analyzer.provider             |   default       
module.log-analyzer.provider               |   default       
module.logql.provider                      |   default       
module.promql.provider                     |   default       
module.query.provider                      |   graphql       
module.receiver-browser.provider           |   default       
module.receiver-clr.provider               |   default       
module.receiver-ebpf.provider              |   default       
module.receiver-event.provider             |   default       
module.receiver-jvm.provider               |   default       
module.receiver-log.provider               |   default       
module.receiver-meter.provider             |   default       
module.receiver-otel.provider              |   default       
module.receiver-profile.provider           |   default       
module.receiver-register.provider          |   default       
module.receiver-sharing-server.provider    |   default       
module.receiver-telegraf.provider          |   default       
module.receiver-trace.provider             |   default       
module.service-mesh.provider               |   default       
module.storage.provider                    |   elasticsearch 
module.telemetry.provider                  |   none          
oap.external.grpc.host                     |   0.0.0.0       
oap.external.grpc.port                     |   11800         
oap.external.http.host                     |   0.0.0.0       
oap.external.http.port                     |   12800         
oap.internal.comm.host                     |   0.0.0.0       
oap.internal.comm.port                     |   11800  

2024-06-19 08:48:24,886 org.apache.skywalking.oap.server.core.alarm.provider.expr.rt.AlarmMQEVisitor 169 [pool-13-thread-1] WARN  [] - Unsupported metrics service_percentile
2024-06-19 08:49:09,934 org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer 91 [pool-10-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.
2024-06-19 08:49:24,886 org.apache.skywalking.oap.server.core.alarm.provider.expr.rt.AlarmMQEVisitor 169 [pool-13-thread-1] WARN  [] - Unsupported metrics service_percentile
2024-06-19 08:49:24,886 org.apache.skywalking.oap.server.core.alarm.provider.expr.rt.AlarmMQEVisitor 169 [pool-13-thread-1] WARN  [] - Unsupported metrics service_percentile

### What you expected to happen

Skywalking ui [Service Response Time Percentile (ms)] can display charts.

### How to reproduce

nil

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You should use the out of date dashboard templates.
We updated it to adopt new percentile.

Read change logs and update the templates(or re-init).
