### ISSUE TITLE
[Bug] start BanyanDB uses the cluster mode error, register node timeout, retrying

### ISSUE THREAD

**Issue by wzqiang1332** [apache/skywalking#12358]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

- BanyanDB Startup error
When BanyanDB uses the cluster mode to specify the etcd cluster for startup, it continuously displays a timeout error for registering nodes. My ETCD cluster consists of 3 nodes. BanyanDB can start if I specify any one of the nodes in the cluster, but if I follow the official documentation to specify all 3 nodes, it always reports an error.

- command
-- ./banyand-server-static data liaison storage --etcd-endpoints 172.17.0.65:2379,172.17.0.66:2379,172.17.0.67:2379  error
-- ./banyand-server-static data liaison storage --etcd-endpoints 172.17.0.65:2379 success

- verion
- - OS: Centos7.9
- - BanyanDB: 0.6.1
- - etcd: 3.3.11
<img width="1120" alt="1B8296B0-68EA-4fb8-89F2-908BF60CE50D" src="https://github.com/apache/skywalking/assets/20432873/1b7ebc77-c75f-478c-b422-1262ba9fec7d">
<img width="1257" alt="85AB0008-9A79-4702-A374-ED87CA4D8812" src="https://github.com/apache/skywalking/assets/20432873/7f3099d2-bf8f-483c-a93a-322911964fce">
<img width="458" alt="F16B509B-3F4B-4b79-8E76-2AD2DD1A73CC" src="https://github.com/apache/skywalking/assets/20432873/8d4ca895-5c0a-496c-ae92-e00f5aee4d27">

### What you expected to happen

The cluster mode starts normally

### How to reproduce

Start BanyanDB using the etcd cluster

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You missed the title of the issue.

**Comment by hanahmily** [comment]
It has been fixed by https://github.com/apache/skywalking-banyandb/pull/473. @wzqiang1332, could you please check it out?

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-banyandb/pull/474 should be important too.

Please use the latest codebase/image.
