### ISSUE TITLE
[Feature] miss mvc-annotation-6.x-plugin

### ISSUE THREAD

**Issue by friendlytkyj** [apache/skywalking#12361]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

if I use the latest spring-boot 3.3.0, @RestController and @GetMapping can't be collect HTTP_HEADER by agent, I guess agent not support spring 6.x.
so, if I use the spring-boot 2.7.x, spring version is 5.x, the agent-java can collect HTTP_HEADER.

### Use case

SW_PLUGIN_HTTP_INCLUDE_HTTP_HEADERS=host,user-agent,X-Forwarded-For

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If something is not supported, then it it what it is.

If someone wants to contribute that, go ahead.
