### ISSUE TITLE
[Bug] WebFluxSkyWalkingTraceContext.traceId(exchange) 无效

### ISSUE THREAD

**Issue by 6LWa6ZKx** [apache/skywalking#12373]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

从这里获取的最新文档中
[](url)
实际使用中`String traceId = WebFluxSkyWalkingTraceContext.traceId(exchange);`并无法获取到想要的内容，似乎文档有差异？

### What you expected to happen

获取到TraceId。

### How to reproduce

参考文档：
https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/application-toolkit-webflux/#fetch-trace-context-relative-ids

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We use English to discuss on Github.
Close it.

And what you are facing just a discussion, not an issue. Use discussion to see who has experiences about your use cases.
