### ISSUE TITLE
Remove kapa.ai bot from website due to ASF Policy team requires

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#12407]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

@Superskyyy Please remove it, and could you try to connect with Kapa team about this? Whether they could connect with ASF policy team and try to fix this?

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
Other ASF projects are still using it. Let me contact kapa for assistance on this. Our users will hate to see it go away.

**Comment by justinmclean** [comment]
Other ASF projects should not be using it and have also been asked to remove it.

**Comment by justinmclean** [comment]
Any progress on this?

**Comment by wu-sheng** [comment]
Removed
