### ISSUE TITLE
[BanyanDB-Server] Object Pool Tracker 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12443]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The underlying storage module uses multiple object pools to reduce memory usage and minimize the frequency of garbage collection. However, if certain operations do not properly release unused objects, there is a risk of pool overflow.

I propose adding a pool tracker to keep track of each pool's number and size. The testing system could use this tracker to detect potential pool leaks, and the observability module could also monitor them.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is good for increasing the operational capability. Let's do that.
