### ISSUE TITLE
[Feature] UI ServiceLoad

### ISSUE THREAD

**Issue by Minstrelyy** [apache/skywalking#12451]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Is the ServiceLoad in the UI the sum of the values ​​for each instance or the average?I now expect to use the CPM value to implement K8S HPA, but I found that the CPM value does not meet my expectations. The expected value of my concurrent test results should be 80,000, but the value on the UI interface is only 40,000

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
It is. If it is wrong, then maybe you don't set up cluster coordinator correctly.
Then dirty write correctly.

**Comment by Minstrelyy** [comment]
How do I configure the cluster coordinator?I found that there are two instances below, and the average value added together is equal to the ServiceLoad value

**Comment by wu-sheng** [comment]
Follow the docs. They are there.
