### ISSUE TITLE
[Enhancement] BanyanDB Zipkin Module Set Service as Entity

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12471]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The banyandb Zipkin module uses `spanId` as the entity, which causes high cardinality issues that impact query performance. The segment module suggests that the service name is a better option for the entity.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We should keep ID unchanged(`new StorageID().append(TRACE_ID, traceId).append(SPAN_ID, spanId);` but use different series IDs, right?

**Comment by hanahmily** [comment]
> We should keep ID unchanged(`new StorageID().append(TRACE_ID, traceId).append(SPAN_ID, spanId);` but use different series IDs, right?

Exactly. we should shardingkey annotation to mark the service name.
