### ISSUE TITLE
[Feature] BanyanDB Stream Query Sort By Time

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12472]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The queries for the stream should sort data based on the native timestamp to improve efficiency. DAOs should set the `IndexRule` to nil when they need timestamp-based order.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This should be a quick fix, could you submit this directly?

**Comment by wu-sheng** [comment]
Two relative fixes at client drive side
- https://github.com/apache/skywalking-banyandb-java-client/pull/66
- https://github.com/apache/skywalking-banyandb-java-client/pull/67
