### ISSUE TITLE
[Bug] X url on website hasn't been updated.

### ISSUE THREAD

**Issue by BishalJena** [apache/skywalking#12499]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

<img width="544" alt="Screenshot 2024-08-01 at 7 21 00 PM" src="https://github.com/user-attachments/assets/c16dc94a-7b7e-40a8-8274-ef5e6d7a2edb">

### What you expected to happen

It should be updated to X logo and x.com link

### How to reproduce

Scroll down to footer and hover over the twitter bird logo.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to fix? Twitter was there for years.

**Comment by BishalJena** [comment]
I think it'll be fixed in skywalking-website repo, not this repo. Am i right?

**Comment by wu-sheng** [comment]
Yes, it is there.

**Comment by BishalJena** [comment]
my bad, i couldn't find where it is in this skywalking repo. can you point me where it is?

**Comment by BishalJena** [comment]
I found it in skywalking-website repo. I'll raise PR on there. You may close this issue.
Thank you!
