### ISSUE TITLE
[JavaClient][OAP]  Improve Index Performance By Setting "no_sort"

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12507]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

BanyanDB IndexRule supports the option to set `no_sort` to exclude sorted tables from the underlying index files. This field should be set to 'true' if the data does not need to be sorted based on a specific index.

For the **Java client**, sync the proto file to include support for this field.
For **OAP**, set this field to true for indexes that do not require sorting support.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I am not sure how to use this in OAP.
AFAIK, there isn't proper setting in OAP model to describe this.

**Comment by wu-sheng** [comment]
`@BanyanDB.NoSort` could be considered. 

Possible use cases should be as same as `@ElasticSearch.DisableDocValues` annotation, introduced in #12741
1. Value column of metrics.
2. Conditions of logs and traces(skywalking and zipkin) exclude latency and timestamp, which are used in sorting.
3. All searchable field in metadata(*_traffic)

@hanahmily Please check both sides. I think separating two storage with making this concept more clear.

**Comment by wu-sheng** [comment]
@mrproliu As you have more time, please take a look at this after #12685
We should consider `@BanyanDB.Sortable` annotation because it seems all tag fields of BanyanDB. Only the tag is being used for query(e.g. latency in segment), we should add this annotation to activate it.
