### ISSUE TITLE
[Bug] spring cloud gateway 4 拓扑不正确

### ISSUE THREAD

**Issue by wk4212** [apache/skywalking#12515]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

网关和网关后面的服务出现并列的情况
![Uploading 微信图片_20240808190826.png…]()

### What you expected to happen

在拓扑图中，demo-order 服务应该出现在 demo-gateway 网关的后面

### How to reproduce

**gate-way项目的pom如下**

spring boot 3.2.4 + spring-cloud-starter-gateway 4.1.5 + spring-cloud-starter-alibaba-nacos-discovery 2023.0.1.0

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-gateway</artifactId>
    <version>4.1.5</version>
</dependency>

<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
</dependency>

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-loadbalancer</artifactId>
</dependency>

**plugins目录下已经拷贝了相关的jar**
apm-spring-cloud-gateway-4.x-plugin-9.3.0.jar
apm-spring-webflux-6.x-plugin-9.3.0.jar

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't accept Chinese on GitHub. If you prefer that, go for slack CN channel.

Ask questions in English should use discussion rather than issues.

Gateway is complex, your way of asking doesn't work for anyone.
There is no point of guessing your scenario.

**Comment by Camio1945** [comment]
I have the same problem. I will open a new issue in English.

**Comment by wu-sheng** [comment]
You could open a discussion. As we explained a lot, we can't check all your plugin use cases.
You could answer your questions, but would not debug for yoi.

**Comment by Camio1945** [comment]
I opened a discussion here: [https://github.com/apache/skywalking/discussions/12675](https://github.com/apache/skywalking/discussions/12675)
