### ISSUE TITLE
[BanyanDB] Package ctl binary separatedly.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#12510]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

DB ctl tool is included in server binary and image, which is not convenient and easier to trggier cli.

### Use case

We should package ctl out of database server binary with signed asc and sha code.
Then, from the experience of OAP, we should not include ctl in the server image too.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
> Then, from the experience of OAP, we should not include ctl in the server image too.

The health-checking procedure depends on bydbctl to check the health of HTTP and gRPC services. Should we add a bydbctl sidecar to each node? What are your main concerns about incorporating bydbctl?

**Comment by wu-sheng** [comment]
Recently, we add simply http endpoint in OAP for health check to simplify this case.

You should consider that too. Rely on ctl Makes things tricky.

https://skywalking.apache.org/docs/main/next/en/api/health-check/

For k8s, we don't need that complex and complete health check. It should be simply true or false.

**Comment by wu-sheng** [comment]
> What are your main concerns about incorporating bydbctl?

- Lower cve maintenance in deployment. Less is better from my past years experiences.
- Healthy check should be easy and to be done through http endpoint. It limits features, but k8s pod check doesn't need those. We will be able to use ctl when we need it.
