### ISSUE TITLE
[Bug] skywalking-agent can not send trace info to otel-collector

### ISSUE THREAD

**Issue by yujianweilai** [apache/skywalking#12578]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

My situation:
Previously, we used skywalking-agent to transport trace data to skywalking-server. Now I used  otel-collector + jaeger instead of skywalking-server.  I  hope that  the skywalking-agent send the tracing data to otel-collector, and then otel-collector forwards it to jaeger for storage and display.
The problem is that the tracing data cannot be passed to otel-collector.
My configuration:
/otel-collector/
![image](https://github.com/user-attachments/assets/de83f5ab-aed4-4c04-86ff-86f23b824986)
/skywalking-agent config/
[root@cx-gateway-service-4100-6b6bdd45cc-pvj98 /]# env|grep SW
SW_LOGGING_DIR=/var/log/cx-gateway-service
SW_AGENT_NAME=cx-gateway-service
SW_AGENT_COLLECTOR_BACKEND_SERVICES=10.100.220.63:11800 # IP 10.100.220.63 is one of otel-collector node address
SW_LOGGING_MAX_HISTORY_FILES=50

Software Version:
skywalking-agent： 8.0.1
otel-collector： 0.85.0

### What you expected to happen

According to the official documentation(https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.85.0/receiver/skywalkingreceiver/README.md),  when OTEL interconnects with Skywalking, there are few configuration steps. I don't know what steps I'm missing ？ Expect help from experts ，Thanks

### How to reproduce

none

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Wasn't I clear enough? No, we don't support that.

**Comment by wu-sheng** [comment]
You are referring to otel docs, that is not our landscapes. otel community maintains that. Reach then if you need.

**Comment by yujianweilai** [comment]
> Wasn't I clear enough? No, we don't support that.

got it , sorry  i should not submit this issue in skywalking github.
