### ISSUE TITLE
[Bug] BanyanDB Module in OAP Not Using Native Term Searching

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12592]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I've noticed that the BanyanDB module in OAP does not utilize the database's native term searching for certain scenarios, particularly endpoint name matching. It would be beneficial to incorporate native term searching and add annotation to mark the index rule for analyzing those tags. This enhancement would improve the module's functionality in handling endpoint name matching.

In the table creation procedure, to set the [analyzer](https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/model/v1/query.proto#L65) to the indexRule. We should use the [simple](https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L180) analyzer.

Query operation should use the [match](https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/model/v1/query.proto#L65) binary operator to search the index.

### What you expected to happen

Nan

### How to reproduce

Nan

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@wankai123 We need to fix this when use the new client lib.
