### ISSUE TITLE
[Feature] Improve "events_minute" query for BanyanDB

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12638]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The alarm module has a feature to retrieve relevant events related to an alarm event. However, the query has the following flaws:

1. No time range: This will cause the query to scan all the segments, even though most segments might not contain the target data.
2. Repeated scanning of `start_time` and `end_time`: The alarm event generates an identical time range for all the services. Despite this, the query still scans this time range for each service, leading to unnecessary scanning.

Solutions:

1. Obtain the time range from the "start_time" and "end_time" query conditions.
2. Extract the "start_time" and "end_time" from the service filter.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@wankai123 I think this is an easy fix.

**Comment by hanahmily** [comment]
Based on #11497, we should move `represent_service_id` and `represent_service_instance_id` to the series_id array. The final series_id is ["represent_service_id", "represent_service_instance_id", "address"]

**Comment by wu-sheng** [comment]
> Based on #11497, we should move `represent_service_id` and `represent_service_instance_id` to the series_id array. The final series_id is ["represent_service_id", "represent_service_instance_id", "address"]

<3> is fixed through https://github.com/apache/skywalking/pull/12652
