### ISSUE TITLE
[Feature] Non-Time-Series "Measure"  

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12677]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I propose introducing a non-time-series "measure" for storing certain types of data where the time dimension is irrelevant. The primary aim of this measure is to improve performance, particularly for service, instance, endpoint, and process traffic.

Currently, time-series data structures are used even when the time component is not significant, which results in unnecessary overhead when querying and storing data. By implementing a new non-time-series measure where all relevant data is stored in the series index, we can optimize performance and reduce complexity for specific use cases.

1. Add "non-time-series" field to "Measure"  that focuses on the series index for storing the necessary data fields. 
2. Series Index as Primary Storage. Instead of storing values in a time-series format (i.e., with timestamps), the data could be stored primarily in the series index. 

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please submit an issue to track OAP side changes. We should adopt this as validate it on demo env.
This should be a significant change in 0.8.
