### ISSUE TITLE
[Bug] failed to build from source v10.1.0 caused by apm-webapp

### ISSUE THREAD

**Issue by xiaozongyang** [apache/skywalking#12689]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

1. I try to build apache skywalking from source following [this guide](https://github.com/apache/skywalking/blob/master/docs/en/guides/How-to-build.md#building-from-github). 

The build failed with following error message
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (npm ci) on project apm-webapp: Failed to run task: 'npm ci --registry=https://registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :apm-webapp
```

2. I execute this command (`npm ci --registry=https://registry.npmjs.org`) in `apm-webapp` folder and got this message
```
npm ERR! code EUSAGE
npm ERR!
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
npm ERR!
npm ERR! Clean install a project
npm ERR!
npm ERR! Usage:
npm ERR! npm ci
npm ERR!
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [-E|--save-exact] [-g|--global]
npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR!
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR!
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/minimax/.npm/_logs/2024-10-10T13_19_54_983Z-debug-0.log
```

### What you expected to happen

build success and get skywalking binaries

### How to reproduce

follow this guide https://github.com/apache/skywalking/blob/master/docs/en/guides/How-to-build.md#building-from-github

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Usually this is caused by you network(npm part). We have built this through GitHub CI(image you are using) and my local desktop.

**Comment by xiaozongyang** [comment]
@wu-sheng Thanks for your reply. So what is the actual path that excuted the `npm` command? I guess is `skywalking-ui` but the error messages provided by maven is `:apm-webapp` which is confusing.

By the way, how to ensure the cause is network issue?

**Comment by xiaozongyang** [comment]
I found the variable `ui.path` in `apm-webapp/pom.xml` and I will try to execute npm command manually

**Comment by xiaozongyang** [comment]
Yep, I'm behind of a https_proxy and I also try to build with other china mirrors. But I can only build sucessfuly with registry `registry.npmjs.org`. 

Thanks again! I change my proxy and slove this issue!
