### ISSUE TITLE
[Bug] Failed to install skywalking helm chart v4.6.0 with banyandb 0.7.0

### ISSUE THREAD

**Issue by benjaminhuo** [apache/skywalking#12694]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Helm Chart (apache/skywalking-helm)

### What happened

Failed to install skywalking helm chart 4.6.0 with banyandb 0.7.0 following instructions in https://github.com/apache/skywalking-helm/tree/master

### What you expected to happen

Install complete following instructions in https://github.com/apache/skywalking-helm/tree/master

### How to reproduce

```shell
export SKYWALKING_RELEASE_VERSION=4.6.0  # change the release version according to your need
export SKYWALKING_RELEASE_NAME=skywalking  # change the release name according to your scenario
export SKYWALKING_RELEASE_NAMESPACE=default  # change the namespace to where you want to install SkyWalking

helm install "${SKYWALKING_RELEASE_NAME}" \
  oci://registry-1.docker.io/apache/skywalking-helm \
  --version "${SKYWALKING_RELEASE_VERSION}" \
  -n "${SKYWALKING_RELEASE_NAMESPACE}" \
  --set oap.image.tag=10.1.0 \
  --set oap.storageType=banyandb \
  --set ui.image.tag=10.1.0 \
  --set elasticsearch.enabled=false \
  --set banyandb.enabled=true \
  --set banyandb.image.tag=0.7.0
```

The notes said :
The BanyanDB(>=0.7.0) is not compatible with the BanyanDB Helm Chart(<0.3.0) which was referred by the SkyWalking Helm Chart(<4.7.0). Meanwhile, BanyanDB(>=0.7.0) requires OAP 10.1.0+. If you want to use BanyanDB(>=0.7.0) as storage solution, you have to use the BanyanDB Helm Chart(>=0.3.0) or SkyWalking Helm Chart(>=4.7.0).

But there is no SkyWalking Helm Chart 4.7.0

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You need to wait for Helm 4.7, which is pending on banyandb helm 0.3

**Comment by wu-sheng** [comment]
This conflict in the notice is intentional, not a bug or document issue. If you pick the latest of helm from source, which is using banyandb helm 0.3-rc, it will work.

**Comment by wu-sheng** [comment]
You could watch here, https://lists.apache.org/thread/yvhkyjp3x9pct2ks1b4sscw6bk1bxnm0

**Comment by wu-sheng** [comment]
Update, helm 4.7 is out

-> https://hub.docker.com/r/apache/skywalking-helm/tags
