### ISSUE TITLE
[Bug] NoClassDefFoundError: Lorg/sonatype/plexus/build/incremental/BuildContext;

### ISSUE THREAD

**Issue by andotorg** [apache/skywalking#12702]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

skywaling-java build error  tips: `NoClassDefFoundError: Lorg/sonatype/plexus/build/incremental/BuildContext;`

### What you expected to happen

build success!

### How to reproduce

Pull the latest main branch code and use `mvn clean compile - Dmaven.test.skip=true` to build it!

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I think this is your maven issue? This is not in skywalking dependency path.

**Comment by andotorg** [comment]
No, I replaced it
```xml
<plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${maven-resource-plugin.version}</version>
                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
```
replace
```xml
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-remote-resources-plugin</artifactId>
                <version>${maven-resource-plugin.version}</version>
            </plugin>
```

**Comment by andotorg** [comment]
I'll replace it,  compiles  sucess

**Comment by wu-sheng** [comment]
I don't know what you expect by saying this replacement. We don't need that in our local and GH CI env. If you need that, that is your network or dev env(some intranet setup) issue.

**Comment by andotorg** [comment]
ok
