### ISSUE TITLE
[Feature] AOT consideration

### ISSUE THREAD

**Issue by c-ramin** [apache/skywalking#12713]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Hello, 
Assembly loading no longer works in AOT. 
When using AddSkyAPM it does not work. 
Is there an AOT integration planned for skyApm.net ?

Best regards

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I think we are asking in a wrong place. SkyAPM is not a part of SkyWalking. It is a 3rd part org which provides SkyWalking compatible ecosystem projects, agents and tools.

**Comment by c-ramin** [comment]
Ah yes, my apologies. I was mistaken. You can close. Best regards
