### ISSUE TITLE
[Bug] TestClient for fastapi cause the req.client None error

### ISSUE THREAD

**Issue by CharlieSeastar** [apache/skywalking#12733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

sw-fastapi plugin fail to set span.peers when using Fastapi TestClient

### What you expected to happen

Fastapi TestClient work properly

### How to reproduce

Adding decorator `@trace` to a custom middleware in Fastapi, and use TestClient to invoke any router.
in custom_middleware.py
```
class RequestAroundMiddleware(BaseHTTPMiddleware):
    def __init__(self, app, dispatch=None) -> None:
        super().__init__(app=app, dispatch=dispatch)

    @trace("request_around")
    async def dispatch(self, request: Request, call_next):
        return await call_next(request)

```
in test_demo.py
```
from fastapi.testclient import TestClient
def test_read_main():
    from main import app
    client = TestClient(app)
    response = client.get("/health")
    assert response.status_code == 200
```
run `pytest`
then 
```
async def create_span(self, method, scope, req, send, receive):
        carrier = Carrier()
    
        for item in carrier:
            if item.key.capitalize() in req.headers:
                item.val = req.headers[item.key.capitalize()]
    
        span = NoopSpan(NoopContext()) if config.ignore_http_method_check(method) \
            else get_context().new_entry_span(op=dict(scope)['path'], carrier=carrier, inherit=Component.General)
    
        with span:
            span.layer = Layer.Http
            span.component = Component.FastAPI
>           span.peer = f'{req.client.host}:{req.client.port}'
E           AttributeError: 'NoneType' object has no attribute 'host'
```
in skywalking/plugins/sw_fastapi.py  line  59

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
I’m not sure why you want to trace a TestClient? I think `TestClient` is for test only and don’t have a peer as expected

**Comment by kezhenxu94** [comment]
OK make sense
