### ISSUE TITLE
[Feature] Use vmlinux.h to compile BPF code, thereby improving the dependency issues in the compilation process

### ISSUE THREAD

**Issue by tsint** [apache/skywalking#12775]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, the compilation of skywalking-rover depends on many system header files and some kernel header files, making the compilation environment complex. By introducing the vmlinux.h file, the dependencies of the compilation can be greatly simplified, while also speeding up the packaging and compilation process.

### Use case

Replace `#include <linux/sched.h>` and `#include <stddef.h>` with `#include "vmlinux.h"`

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@mrproliu Please check this whether we are accepting this.

**Comment by mrproliu** [comment]
At the first, I have try to do this, but including "vmlinux.h" file will break the Apache license issue. That's why I have to avoid this way.

**Comment by tsint** [comment]
The Beyla project also uses the Apache license and includes vmlinux.h (see https://github.com/grafana/beyla/blob/main/bpf/headers/vmlinux_amd64.h).

**Comment by wu-sheng** [comment]
ASF has different requirements when we copy things. Another project uses APLv2 doesn't mean it fits ASF requirements.
