### ISSUE TITLE
[Bug] agent启动spring boot应用无法使用jmx

### ISSUE THREAD

**Issue by niuhutao** [apache/skywalking#12786]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

idea 2024.2
jdk 21
spring boot 3.x
sw 10.x
idea启动spring boot项目添加 sw agent后无法使用jmx
去掉sw agent或手动配置jmx可用

### What you expected to happen

希望sw agent兼容jmx

### How to reproduce

.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please use Slack CN channel if you need to discuss in Chinese.
