### ISSUE TITLE
[Feature] need metrics which rabbitmq-prometheus plugin provides

### ISSUE THREAD

**Issue by amolngt** [apache/skywalking#12799]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

rabbitmq-prometheus plugin gives us rabbitmq_queue_messages_unacked, rabbitmq_channel_messages_delivered_total, etc **queues wise.** 

But these metrics are not working in skywalk while creating rules. Is there anything we can do here ?

### Use case

![Screenshot from 2024-11-25 15-37-37](https://github.com/user-attachments/assets/5cc75e26-901e-479b-ae8c-318c55bd9553)
![Screenshot from 2024-11-25 15-37-06](https://github.com/user-attachments/assets/fa52f7a7-f458-444f-94e4-0747ccdf92ae)

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Again, I have answered that on discussion. Don't keep opening new issues.

This is only your question, not our issue.

**Comment by wu-sheng** [comment]
This is open source community. Please respect people here, be patient, and don't create too much noise.

Maybe you have your own time requirements, but that is not ours. And we don't get paid to do this.

**Comment by wu-sheng** [comment]
Ref https://github.com/apache/skywalking/discussions/12784#discussioncomment-11370742
