### ISSUE TITLE
[Bug] Dubbo 3.3.x Call-Chain not correct

### ISSUE THREAD

**Issue by ldcsaa** [apache/skywalking#12791]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

While applications upgrade to Dubbo 3.3.x , the Call-Chain of consumer & provider would break .

### What you expected to happen

Call-Chain would not break

### How to reproduce

Just start  Dubbo 3.3.x consumer & provider , and invoke make any remote call , then watch the skywalking-ui topology graph .

The actual call-chain is: `User` -> `hp-demo-buff-skywalking` -> `hp-demo-infra-skywalking-service`
![image](https://github.com/user-attachments/assets/0b002cb2-94cf-46b0-8cad-c7cfa0f26688)

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please reach Dubbo community. We just host plugins for the project, and the plugins were contributed by them.

It seems they added new async mechanism or/and new way of doing rpc, the previous plugn is not compatible anymore.

**Comment by ldcsaa** [comment]
> Please reach Dubbo community. We just host plugins for the project, and the plugins were contributed by them.
> 
> It seems they added new async mechanism or/and new way of doing rpc, the previous plugn is not compatible anymore.

Does next version of skywalking would fix this program ?

**Comment by wu-sheng** [comment]
As I said, we are not the one maintaining this. Please reach Dubbo community, there should be someone there familiar with this part.

**Comment by wu-sheng** [comment]
Plugins are from global contributors. We just tested declared versions, and released with our agent core.

So, you have to reach the original community.
