### ISSUE TITLE
[Bug]  The same service instance is displayed multiple times.

### ISSUE THREAD

**Issue by wzqiang1332** [apache/skywalking#12801]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

skywalking:  10.1.0
banyandb:  0.7.1
The same service instance is displayed multiple times. 
During the development phase, services are frequently released, with the same IP port and instance ID, but different process IDs.
The serviceId is the same, and every time it is re-published, there will be one more serviceInstance in the instance list.
How do I make the same instanceId display only one record
<img width="597" alt="e53e1278ea18e3f87b211495e098cc72" src="https://github.com/user-attachments/assets/59757271-570f-407f-bdfb-040ef343afcf">
<img width="1203" alt="f9cdf779c00872b3ddade6bb019468c2" src="https://github.com/user-attachments/assets/cd2a3e71-5cdc-4dbc-b7a7-8c5079899311">

### What you expected to happen

same instanceId display only one record

### How to reproduce

When an application service is published multiple times using the same configuration

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We didn't see that on the demo and local. Could you verify whether there is duplicate data in the database? And debug to check whether database responds correctly?

**Comment by wzqiang1332** [comment]
> We didn't see that on the demo and local. Could you verify whether there is duplicate data in the database? And debug to check whether database responds correctly?

Don't know much about banyandb's internal data structure, which data in the database do you want to check?

![image](https://github.com/user-attachments/assets/d994a68b-6f32-4d49-8c19-ea77725d612c)

**Comment by wu-sheng** [comment]
You should query for service instance traffic to get that list.
Please the time range correctly.

**Comment by wzqiang1332** [comment]
In the end, the cause of the problem was not found. Once we cleared banyandb and restarted skywalking, instance couldn't be queried.
<img width="1258" alt="d793fe62729ddc04ca96d1ec41df09f9" src="https://github.com/user-attachments/assets/0670e943-8b01-4c62-a77c-749faa572236">
<img width="1117" alt="a9150f6d26ef28664f38757fa50c0d07" src="https://github.com/user-attachments/assets/1f2bde98-2266-4ded-aa3b-55f2980fb31a">
<img width="1266" alt="d732858b4e5b6a6c1107066971889a6b" src="https://github.com/user-attachments/assets/ec010a39-b53f-4ca6-8a91-dd7f6b740026">
<img width="1265" alt="e810496ccd81f407a5779a5e4111ddbe" src="https://github.com/user-attachments/assets/4dfda1a9-cb0b-4304-99e2-e5f9b2cd1205">

**Comment by wu-sheng** [comment]
I looks like you mismatch versions. Latest dev BanyanDB is not working for 10.1 OAP.

**Comment by wzqiang1332** [comment]
3Q. No errors were reported on the first deployment. Delete banyandb's data, and then restart and report  error.  The banyand package under oap-lib is definitely version 0.7.0, so I tried it with 0.7.0

**Comment by wu-sheng** [comment]
That doesn't make sense. I don't know what happens at your end. But your description seems not about ours, it is more about your side.

**Comment by wzqiang1332** [comment]
The overall process is as follows: 
1. the initial deployment using skywalking10.1.0+banyandb0.7.1 was successful, but serviceInstance was found to be repeated. 
2. After clearing banyandb's data and re-initialization, an error has been reported and cannot be solved. 
3. banyandb switch 0.7.0 is still the same problem. 
Finally replace elasticsearch,  it's back to normal now. We would very much like to try banyandb as a storage for skywalking, but the process of docking is too tortuous
