### ISSUE TITLE
[Bug] webflux trace is seperated,there are mutilple traces but actual is only one trace

### ISSUE THREAD

**Issue by wild46cat** [apache/skywalking#12817]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

when I use skywaling to trace webflux ,I found that if the return type is Mono<T> ,then the trace is broken.
like this:
![image](https://github.com/user-attachments/assets/2ce53678-d388-4430-ac73-f963bb2e42ea)

as the screenShot shows that:
what I need is  opeartion from web request to redis,is only one trace.

this is my code:
@GetMapping("/getValue")
    public Mono<String> getValue() {
        return redisTemplate.opsForValue().get("test").doOnSuccess(result -> System.out.println("Data read from Redis: " + result));
    }

### What you expected to happen

What I expected is that  it could be only one trace, not seperate.
only show the webflux request is best (I know I could remove the plugin mvc-annotation in plugins folder).

### How to reproduce

every time.

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You may need this.

https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/application-toolkit-webflux/

**Comment by wild46cat** [comment]
I had readed the document.
but there is still problem.
![image](https://github.com/user-attachments/assets/81a691b5-c171-49d7-b7a8-62b44bb08701)

as the picture shown:
lettuce can't be merged into the  the same trace.

here is my code:
    @GetMapping("getValue12")
    public Mono<String> getValue12() {
        return Mono.subscriberContext()
                .flatMap(ctx -> WebFluxSkyWalkingOperators.continueTracing(ctx, () -> {
                    return redisTemplate.opsForValue().get("test");
                }));
    }
    
I think maybe I have found a problem about webflux.

**Comment by wild46cat** [comment]
by the way, I have removed 
**apm-springmvc-annotation-3.x-plugin-9.3.0
apm-springmvc-annotation-4.x-plugin-9.3.0
apm-springmvc-annotation-5.x-plugin-9.3.0
apm-springmvc-annotation-6.x-plugin-9.3.0
apm-springmvc-annotation-commons-9.3.0**
these jars into option-plugins folder ,did this have effect?

**Comment by wu-sheng** [comment]
Personally, I don't know this as I am not working in Java application for a long time. Also, plugins are complex in Java ecosystem, there are various use cases.

Still, when you find out a plugin issue, you need to debug the codes and find out why. Usually case like this is caused by thread-switch issue. The plugins don't cover all cases. 

But we don't have people to debug all plugins, as we are the ones wrote these. They are from world wide. We just verify through provided plugin test cases, nothing more.

**Comment by wild46cat** [comment]
I really appreciate your honesty. I will carefully debug and try to find the cause of the problem.

**Comment by wu-sheng** [comment]
> I really appreciate your honesty. I will carefully debug and try to find the cause of the problem.

This has been resolved by @wuwen5 via https://github.com/apache/skywalking-java/pull/788
