### ISSUE TITLE
[Bug] dial tcp 103.246.246.144:443: i/o timeout

### ISSUE THREAD

**Issue by qianghong000** [apache/skywalking#12841]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Error: failed to do request: Head "https://registry-1.docker.io/v2/apache/skywalking-helm/manifests/4.7.0": dial tcp 103.246.246.144:443: i/o timeout

### What you expected to happen

Please provide me with a link to download the skywalking-helm: 4.7.0 released version of the chart

### How to reproduce

Please provide me with a link to download the skywalking-helm: 4.7.0 released version of the chart

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Again, network issue is not upstream concern. That is your local/private network.
