### ISSUE TITLE
[Bug] Skywalking-ui->虚拟数据库查看Slow Statements 中的Trace报错，Can't split endpoint id into 2 parts, 

### ISSUE THREAD

**Issue by Cypher-lzx** [apache/skywalking#12883]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

![1](https://github.com/user-attachments/assets/785d22e6-dba6-4a7a-a246-a0380ab8c417)
![2](https://github.com/user-attachments/assets/db02c940-2ad5-45cf-9ca4-d469b52d434b)
Skywalking-ui中点击虚拟数据库，选择Slow Statements，然后点击[查看相关Trace]，出现错误

### What you expected to happen

版本不匹配

### How to reproduce

skywalking apm版本9.4.0，java-agent版本9.3.0，mysql版本5.7.26

### Anything else

java-agent的插件包
![3](https://github.com/user-attachments/assets/24e259f3-56a0-4940-9856-3fdb8930e07b)
![4](https://github.com/user-attachments/assets/b816e810-494c-453b-ac6d-e24c5ad93ee9)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Close as duplicated. I explained. Please don't create noices.

**Comment by wu-sheng** [comment]
Same as https://github.com/apache/skywalking/issues/12881

**Comment by wu-sheng** [comment]
English only on GitHub as mentioned too.

**Comment by wu-sheng** [comment]
This is backend/UI error. Your agent version doesn't matter at all. You need to upgrade backend and UI.
