### ISSUE TITLE
[Bug] skywalking go test/plugin/run.sh execute fail error

### ISSUE THREAD

**Issue by alexwn** [apache/skywalking#12889]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I modify the source code of plugins of http module, and I want to test it, when I execute command "skywalking-go/test/plugins/run.sh http", throw this error:
![图片](https://github.com/user-attachments/assets/9a4bcba9-e4f4-4a4f-b9fd-2cd1a2982963)
I have execute this command success two times, and when I execute again, it's always fail.

### What you expected to happen

check the test/plugins/run.sh script, fix this error

### How to reproduce

execute this script skywalking-go/test/plugins/run.sh http

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
All these verified through GH CI.
This could be env diff or some network issue.

Please keep in original issue, new one doesn't make sense.
