### ISSUE TITLE
[Bug] The endpoint topology graph page queries a large amount of unrelated endpoint information.

### ISSUE THREAD

**Issue by Super-Lu** [apache/skywalking#12880]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

When the depth is greater than 2, the topology graph queries all link information of virtual endpoints. When dealing with a large amount of data, the topology graph cannot be viewed, and the interface will return the following error: 'More than 15,000 'grammar' tokens have been presented. To prevent Denial Of Service attacks, parsing has been cancelled. 

### What you expected to happen

When switching to the current depth to initiate a query on the endpoint topology graph page, it carries the list of endpoint IDs found in this query to the parameters of the next query. If the result of the first query includes the virtual node 'User', the second query will retrieve all link topology information under the ID of the virtual endpoint. However, these topology information are all unrelated to the target endpoint.

### How to reproduce

I think the query logic in the front-end code should be modified. I have tested this locally and the results are promising, but the modification requires further discussion. The proposed modification is to filter out the IDs of virtual endpoints named 'User' from the parameters of the next query if they were included in the results of the previous query.

And I understand that once the query reaches the virtual endpoint 'User', it should stop further querying as virtual endpoints are considered starting points.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Super-Lu** [comment]
Query url: /graphql
Error response:
{
    "errors": [
        {
            "message": "More than 15,000 'grammar' tokens have been presented. To prevent Denial Of Service attacks, parsing has been cancelled.",
            "locations": [
                {
                    "line": 3793,
                    "column": 99
                }
            ],
            "extensions": {
                "classification": "InvalidSyntax"
            }
        }
    ]
}

**Comment by wu-sheng** [comment]
> And I understand that once the query reaches the virtual endpoint 'User', it should stop further querying as virtual endpoints are considered starting points.

yes, this is correct. If you have already changed the codes, you could submit a PR, we could review that.

**Comment by Super-Lu** [comment]
> > And I understand that once the query reaches the virtual endpoint 'User', it should stop further querying as virtual endpoints are considered starting points.
> 
> yes, this is correct. If you have already changed the codes, you could submit a PR, we could review that.

ok
