### ISSUE TITLE
[Bug]  Can't split endpoint id into 2 parts, 4a5227f4e8004b61b4b1584fcfbec990.125.17345973417325601

### ISSUE THREAD

**Issue by Cypher-lzx** [apache/skywalking#12881]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

<img width="929" alt="微信图片_20241219174805" src="https://github.com/user-attachments/assets/7255284d-b593-4efc-ac1e-bb6129ec2db0" />
![微信截图_20241219174828](https://github.com/user-attachments/assets/39fcf46f-961b-42b3-9d5d-3412b7be8b49)

### What you expected to happen

No Error

### How to reproduce

apache-skywalking-apm-9.4.0.tar.gz，apache-skywalking-java-agent-9.3.0.tgz，Skywalking一直是9.4.0版本，从未升级，期间清理了service_traffic表与top_n_database_statement表，service_traffic表做了部分清理，保留了需要使用的服务，top_n_database_statement表全部清理。

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
9.4 is too old, we are not debugging its issue anymore. The latest release is 10.1.0. We are working forward to 10.2.0 only.

**Comment by wu-sheng** [comment]
And note, I answer this once only, please use English on GitHub. If you need to talk in Chinese, join slack CN channel.
