### ISSUE TITLE
[Bug] go agent http plugin response 500 status but not set span error

### ISSUE THREAD

**Issue by alexwn** [apache/skywalking#12882]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Go Agent (apache/skywalking-go)

### What happened

The HTTP request returns a status code of 4xx or 5xx, but the span is not marked as an error in the Skywalking UI

### What you expected to happen

1. When the HTTP request returns a status code of 4xx or 5xx, span is marked as an error
2. The Skywalking Go toolkit provides a method to manually set whether the span is incorrect, for example: trace.Error(err)

### How to reproduce

Use the native HTTP server of Go to process requests. When the HTTP status returned by the request is 4xx or 5xx, span will not be marked as an error

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@alexwn Are you going to submit a pull request to add this?

I can see the status code tag is set, but no status is set.
https://github.com/apache/skywalking-go/blob/988702ef41b9d9075ff060b5bba54d97a94fab9c/plugins/http/server_intercepter.go#L61

**Comment by mrproliu** [comment]
> When the HTTP request returns a status code of 4xx or 5xx, span is marked as an error.

For now, the Go agent only sets the response status code into the span as a tag. Can you check if the tag is in the error span? Then I think we can set the error when the response status code is bigger or equals `400`. 

> The Skywalking Go toolkit provides a method to manually set whether the span is incorrect, for example: trace.Error(err)

It can be added.

**Comment by alexwn** [comment]
1、I'm not sure I can fix it
2、http status code is set, but span error flag is false, see the attach file
![skywalking-go-error](https://github.com/user-attachments/assets/52cf2371-f167-4b73-8ba4-8a8f6777641e)

**Comment by alexwn** [comment]
maybe like this:
![image](https://github.com/user-attachments/assets/6f73e9c9-a5b8-4831-8d17-5860161c020e)

**Comment by wu-sheng** [comment]
Yes, the plugin codes should be like this. The toolkit needs more changes, but still be easy. Add a method in the toolkit and add a new interceptor for that.

**Comment by mrproliu** [comment]
There is [an `Error` method in the span](https://github.com/apache/skywalking-go/blob/main/plugins/core/tracing/span.go#L138-L139). You can use this directly. But if the parameters are empty, it may cause an error (the `Error` method will invoke `Log` to add the log from the parameter). You could add a check in the `Log` method.

**Comment by wu-sheng** [comment]
I think we should expose a new `error` for that.

**Comment by mrproliu** [comment]
Sure. @alexwn would you like to contribute this issue?

**Comment by alexwn** [comment]
ok, I'd like to try to fix it, I haven't done this before, if I have any questions, hope you can help me. -_-
this bugfix at 0.5.0 Tag?

**Comment by mrproliu** [comment]
this bugfix at 0.6.0 tag. If you have any questions, you can leave a message here.

**Comment by wu-sheng** [comment]
Your codes will go straight into main branch and included in the 0.6 release after merged.

**Comment by alexwn** [comment]
get it

**Comment by alexwn** [comment]
![image](https://github.com/user-attachments/assets/41d81f5c-03e3-4477-99be-ead770f2ef81)
I want to add a func to toolkit like trace.Error(...string), this method invoke current active span's Error(...string) method, to set span error. But in toolkit/trace/api.go all method is empty. My question is how should I add the trace.Error(...string) method implementation.

**Comment by mrproliu** [comment]
You can added a new method interceptor [following this documentation](https://github.com/apache/skywalking-go/blob/main/docs/en/development-and-contribution/development-guide.md). And the toolkit-related plugin is under this directory: https://github.com/apache/skywalking-go/tree/main/plugins/toolkit-activation/trace.

**Comment by alexwn** [comment]
![image](https://github.com/user-attachments/assets/6dc5ef51-b837-4ae6-b552-e38e1b439e7f)
![image](https://github.com/user-attachments/assets/154913f5-2c94-4699-b05d-ae76240e34cd)
Is that OK like this? How should I test this?

**Comment by mrproliu** [comment]
You still need to do the following things: 
1. Declare a method interceptor point: https://github.com/apache/skywalking-go/blob/main/docs/en/development-and-contribution/development-guide.md#instrument-point
2. Update the existing toolkit plugin test code: https://github.com/apache/skywalking-go/blob/main/docs/en/development-and-contribution/write-plugin-testing.md

**Comment by wu-sheng** [comment]
Toolkit should have test scenarios included, you could follow the docs, and add new tests for your new methods.

**Comment by alexwn** [comment]
![image](https://github.com/user-attachments/assets/a0d76e71-f350-4744-ae1a-d746c087d547)
execute runs.sh http, throw some error, I don't know what should I do

**Comment by CodePrometheus** [comment]
> ![image](https://private-user-images.githubusercontent.com/67748901/397917227-a0d76e71-f350-4744-ae1a-d746c087d547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NzU1NTcsIm5iZiI6MTczNDc3NTI1NywicGF0aCI6Ii82Nzc0ODkwMS8zOTc5MTcyMjctYTBkNzZlNzEtZjM1MC00NzQ0LWFlMWEtZDc0NmMwODdkNTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEwMDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OTVkOTg3MTUyZmY3NWQ3ZTJkZmI5NDllN2E1YzUyZTkwZTViNzVjMjQ0NTNkN2U1ZWQyNDJhZDk5ZDhlYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U9-r0zY0E5JtNDdXKVqV-8T7XE9xkh6ucncxYGcCthc) execute runs.sh http, throw some error, I don't know what should I do

Please use v4.x version of yq https://github.com/mikefarah/yq/releases.

**Comment by alexwn** [comment]
> > ![image](https://private-user-images.githubusercontent.com/67748901/397917227-a0d76e71-f350-4744-ae1a-d746c087d547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NzU1NTcsIm5iZiI6MTczNDc3NTI1NywicGF0aCI6Ii82Nzc0ODkwMS8zOTc5MTcyMjctYTBkNzZlNzEtZjM1MC00NzQ0LWFlMWEtZDc0NmMwODdkNTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEwMDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OTVkOTg3MTUyZmY3NWQ3ZTJkZmI5NDllN2E1YzUyZTkwZTViNzVjMjQ0NTNkN2U1ZWQyNDJhZDk5ZDhlYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U9-r0zY0E5JtNDdXKVqV-8T7XE9xkh6ucncxYGcCthc) execute runs.sh http, throw some error, I don't know what should I do
> 
> Please use v4.x version of yq https://github.com/mikefarah/yq/releases.

ok, resolved

**Comment by alexwn** [comment]
![image](https://github.com/user-attachments/assets/6ea737b0-e43e-4327-8df8-99d3904aa9c6)
pending here long time, is there any problem?

**Comment by wu-sheng** [comment]
This is pulling docker image from github image repo(ghcr.io). Please check whether you need some proxy?

**Comment by alexwn** [comment]
![image](https://github.com/user-attachments/assets/4817fc52-3da1-49c2-ba49-db40a62eef59)
![image](https://github.com/user-attachments/assets/4b65699a-223b-4380-b3ee-ecd6255a79d7)
I set the docker registry mirrors, but still access "https://registry-1.docker.io/v2/", what should I do?

**Comment by wu-sheng** [comment]
Sorry, I don't know that. I don't need docker proxy. And docker.io is different from ghcr.io repo. ghcr.io is hosted by GitHub.

https://github.com/apache/skywalking-agent-test-tool/pkgs/container/skywalking-agent-test-tool%2Fmock-collector

**Comment by alexwn** [comment]
I can access ghcr.io, although it's a little slow. I have pulled this image.
![image](https://github.com/user-attachments/assets/442c0368-edc0-4dce-a801-dfc617a81c62)
but next step "building service" to access "https://registry-1.docker.io/v2/", this is a big problem, I can't access this site at my home and my office.
![image](https://github.com/user-attachments/assets/755f9ba2-f13a-4213-9c38-73da8fbdb57f)

**Comment by alexwn** [comment]
![图片](https://github.com/user-attachments/assets/02ca50da-27e6-4f63-80ed-304320e50978)
I have executed command "test/plugins/run.sh http" success two times, and I modify this expected.yml, and execute run.sh again, throw this error
![图片](https://github.com/user-attachments/assets/9eb1271b-6f19-4a7f-b87c-5943018cf269)
What should I do?

**Comment by mrproliu** [comment]
If you have updated the interceptor code, I think the `iserror` should be updated to `true` in the span? 
`iserror` field means the span contains an error or not. When you invoke `span.Error()`, the agent would mark this field(`iserror`) as `true`.

**Comment by alexwn** [comment]
> If you have updated the interceptor code, I think the `iserror` should be updated to `true` in the span? `iserror` field means the span contains an error or not. When you invoke `span.Error()`, the agent would mark this field(`iserror`) as `true`.
I already set this isError by span.Error() method, and I already excute "./run.sh http" command success two times, but execute the third times and more, always fail.
I think it's script's or env or something error, I don't know, the error message is "/bin/sh -c go mod tidy" failed
![图片](https://github.com/user-attachments/assets/b5e34719-7045-4dc5-ad2d-902d197a0d7a)

**Comment by mrproliu** [comment]
If the `go mod tidy` triggers the error, I think it's related to the network issue. You can create a PR for the skywalking-go project, the CI will check all the plugins.

**Comment by wu-sheng** [comment]
Relative PR https://github.com/apache/skywalking-go/pull/212
