### ISSUE TITLE
Replace Caffeine with new expired mechanism in zipkin receiver

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#1358]
In the initial version of Zipkin receiver, we use Caffeine as the buffer and use Caffeine expire mechanism to make sure trace finished.

But through my tests in #1273, it didn't work well. A lot of traces finished by Caffeine, but actually, look like it isn't time up.

So, I will look deeper, to see what happens, and try to replace Caffeine with our own codes.

FYI @adriancole

**Comment by adriancole** [comment]
thanks for the ping

**Comment by ben-manes** [comment]
fyi, you can set a scheduler thread to expire from the cache regardless of activity. By default the cache relies on user activity to trigger its periodic maintenance. For prompt expiration you can use the JDK9+ provided scheduling thread, e.g. `Caffeine.scheduler(Scheduler.systemScheduler())`. This will then schedule a single task based on the next expiration event in the internal queue. That task will then call `Cache.cleanUp()` to perform maintenance and evict as needed.
