### ISSUE TITLE
Run more tests in Zipkin examples

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#1359]
In #1273 , I just test sleuth MVC example only. That is definitely not enough. 

@adriancole What other example projects do you suggest to run by us?  Could you put the repo URLs at here?

And through these tests, maybe we could discuss more about other suggestion/optional tags in Zipkin, which could help SkyWalking collectors to run analysis better.

**Comment by adriancole** [comment]
https://github.com/openzipkin?utf8=✓&q=example&type=&language= has a bunch
of similar projects

https://github.com/spring-cloud-samples/brewery is a more involved app

also I think envoy has a zipkin example project.

https://github.com/envoyproxy/envoy/tree/master/examples/zipkin-tracing

**Comment by zoidbergwill** [comment]
I had issues recently, trying to use this with Zipkin traces, because of how many spans I was sending at a time to skywalking's collector, if I lowered the amount it was happy. Maybe I should open a separate ticket though.

**Comment by wu-sheng** [comment]
> I had issues recently, trying to use this with Zipkin traces, because of how many spans I was sending at a time to skywalking's collector, if I lowered the amount it was happy. Maybe I should open a separate ticket though.

I think there are two things need to be done
1. The buffer I used in this receiver, sometimes expired the data before expected, so some trace are broken.
1. No cluster mode supported. Will face the limit after all.

That is why we said this is an incubator feature. :)  We are welcome you to take part in, work with us to fix this issue.
