### ISSUE TITLE
checkstyle codestyle inconsistent

### ISSUE THREAD

**Issue by zone1511** [apache/skywalking#1475]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Feature or performance improvement

___
### Requirement or improvement
- Right now checkstyle didnt enforce all codestyle required stored in codestyle.xml, for example, Annotation should be wrapped as mention in codestyle.xml `<option name="METHOD_ANNOTATION_WRAP" value="1"/>` However, there are many code violated this requirement. For example in code `org.apache.skywalking.apm.plugin.jdbc.mysql.define.CallableInstrumentation` 
```java
 @Override protected ConstructorInterceptPoint[] getConstructorsInterceptPoints() {
```
the Annotation is in the same line as the method which violated the `METHOD_ANNOTATION_WRAP` requirement in codestyle.xml.
Is there any plan to sync checkstyle and codestyle?

**Comment by zone1511** [comment]
@wu-sheng I expected there is alot of files being involved. the good timing to do such task is just before release the software and after code has been freezed

**Comment by wu-sheng** [comment]
@zone1511 I just removed the milestone of this issue. Hope you will find time to or community will help on this.
