### ISSUE TITLE
Does it support thrift?

### ISSUE THREAD

**Issue by zkcarterlau** [apache/skywalking#1534]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [☑️] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

My WebApp calls ServerApp through thrift and I tried to trace the call chain using skywalking.I found WebApp only in topology,but no ServerApp.However I could trace both WebApp and ServerApp when I used springcloud instead of thrift.Does the "Java auto instrumentation agent" support thrift?
![1533782368067](https://user-images.githubusercontent.com/12164596/43874840-84ea3f10-9bc0-11e8-97ff-94d7241561bd.jpg)

**Comment by zkcarterlau** [comment]
Thanks, I'll close it.

**Comment by wu-sheng** [comment]
This is a requirement, someone may be interested to do. Let's keep this open.

**Comment by geektcp** [comment]
Skywalking does not support now , I can build this plugin and contribute .

**Comment by liuhaoXD** [comment]
Since there are no mechanisms like interceptor or custom metadata in Thrift, I think it's quite a tough work to pass trace info transparently <-_->

**Comment by wu-sheng** [comment]
> Since there are no mechanisms like interceptor or custom metadata in Thrift, I think it's quite a tough work to pass trace info transparently <-_->

If there is nothing like that, I think it is hard to do the auto instrumentation.

**Comment by liuhaoXD** [comment]
I have got a trick idea to pass customize info across thrift client and server.. A new PR will be committed after all developing done and proved work well. 
[ref](https://fredal.xin/hunter-with-thrift)

**Comment by dmsolr** [comment]
> I have got a trick idea to pass customize info across thrift client and server.. A new PR will be committed after all developing done and proved work well.
> [ref](https://fredal.xin/hunter-with-thrift)

we need to consider one thing if we custom/enhance the `TProtocol` that means users need to use our plugin at one time.

I have tried it, and it is pending now.

**Comment by wu-sheng** [comment]
If thrift has the same feature like gRPC forward compatbility, such as providing an extra field as the last field, it may work with lower risk. Otherwise, we have to ask user to provide this field name explicitly.
