### ISSUE TITLE
源代码不完整

### ISSUE THREAD

**Issue by hplf** [apache/skywalking#1555]
老哥，master分支缺少代码，比如TraceSegmentObject这个类就没有，既然开源了，为什么不把完整代码放出来呢？

**Comment by seasonouc** [comment]
I also think  so . @wu-sheng  
![image](https://user-images.githubusercontent.com/5309752/58947992-beb9ea00-87bb-11e9-9fa1-8c6a5ced10b6.png)
there absent some source code,is it really a open source?

**Comment by wu-sheng** [comment]
Again. Follow the document, you don't read the document, just do assumption.
