### ISSUE TITLE
Vertical dimension sort by time between threads

### ISSUE THREAD

**Issue by tuohai666** [apache/skywalking#1657]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement
___
### Requirement or improvement
The picture below is from a tracing in Sharding-Sphere:

![1a](https://user-images.githubusercontent.com/24643893/45343412-64488000-b5d3-11e8-93c1-4a09bde78936.png)

There are 4 threads appear in this tracing: the main thread, Sharding-Sphere-0, Sharding-Sphere-1, Sharding-Sphere-2.
The tracing order in main thread is correct: parsing -> getConnection -> executeSQL -> close.
But it's disordered between threads: Sharding-Sphere-0, Sharding-Sphere-1, Sharding-Sphere-2 should happen after getConnection while before close.
I believe skywalking didn't sort tracing beween threads, and this kind of sort is the requirement.

**Comment by wu-sheng** [comment]
Yes, this feature is still missing. I don't know, maybe 6.0.0-RC to fix this? @peng-yongsheng thoughts?

**Comment by wu-sheng** [comment]
Closing. We have shardingsphere plugin from the official team, today.
