### ISSUE TITLE
It didn't work monitoring the sharding-jdbc2.0.3

### ISSUE THREAD

**Issue by kyrotiko** [apache/skywalking#1660]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I have run skywalking on linux system and erverything is healthy, my purpose is to monitoring the sharding-jdbc,But it didn't work.The only traces skywalking received are dubbo and some mysql performance logs,My sharding-jdbc version is 2.0.3 and skywalking version 5.0.0-beta2. Is there extra things I supposed to do ? waitting your reply,thanks
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I hope ShardingSphere community can take care of this, @tuohai666 @terrymanu @tristaZero 

This is no test case in our automatic test repo, https://github.com/SkywalkingTest/agent-integration-test-report . You should submit yours to keep users clear, which versions are supported.

**Comment by terrymanu** [comment]
Sharding-Sphere only integrated with skywalking on 1.x, for 2.x and 3.x, it does not implement yet. We will integrate 2.x soon, and integrate 3.x after 3.0.0 stable version release.

**Comment by wu-sheng** [comment]
We have supported the latest shardingsphere 3.x and 4.x
