### ISSUE TITLE
When is the support for reactor netty HttpClient?

### ISSUE THREAD

**Issue by github-edu** [apache/skywalking#1684]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
    [https://github.com/apache/incubator-skywalking/blob/5.x/docs/Supported-list.md](https://github.com/apache/incubator-skywalking/blob/5.x/docs/Supported-list.md)

`reactor.ipc.netty.http.client.HttpClient#request`

When is the support for reactor netty HttpClient?

```xml
<dependency>
    <groupId>io.projectreactor.ipc</groupId>
    <artifactId>reactor-netty</artifactId>
    <version>0.7.8.RELEASE</version>
</dependency>

```

I have tried to extend the `reactor netty http plugin` with reference to `apache httpclient plugin`, but it failed. I think the code of the plugin is not big. When can you support this?

My application architecture：

MicroService1, 2, 3 ... (SpringBoot, Feign, Skywalking agent)   ->  Spring Cloud Gateway (reactory netty, Skywalking agent) -> Service Providers (SpringBoot, Skywalking agent)
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ascrutae** [comment]
Just assign to me, I will support it in next version

**Comment by imlaotse** [comment]
3ks

**Comment by Anda-JasonSu** [comment]
I need it too.....

**Comment by wu-sheng** [comment]
@ascrutae I have just moved this from 5.1.0 to 6.0.0-beta.

**Comment by wu-sheng** [comment]
@JaredTan95 Which version should we set? GA or 6.1? I noticed different milestones in issue and pr.

**Comment by wu-sheng** [comment]
Keep this milestone matching the #2087 . Move to 6.1 for now.

**Comment by wu-sheng** [comment]
Spring Cloud Gateway 2.1.x is already supported.

**Comment by Anda-JasonSu** [comment]
@wu-sheng thanks, hhh
