### ISSUE TITLE
Design for web performance's data structure.

### ISSUE THREAD

**Issue by kkroy-zs** [apache/skywalking#1708]
There is an idea for skywalking to collect web-page's performance datas.

Design for web performance's data structure.

# Data Structure
* Resource
	* Detail Infomation of Page Load
		* Unload
		* Redirect
		* Cache
		* DNS
		* TCP
		* Request
		* Response
		* Dom
		* Page
		* Network
		* Page Load
		* Page Render
* Request & Response
	* Response Duration
	* Request Type(HTTP/HTTPS)
	* Request Method
	* Page URL
* Exception
	* Exception Type
	* URL
	* Call Stack
* Data Storage
	* Storage
		* Local Storage
		* Session Storage
		* Indexed DB
		* Web SQL
		* Cookies
	* Cache
		* Cache Storage
		* Application Cache
	* Application
		* Manifest
		* Service Workers
		* Clear storage
* Operator
	* Visitor IP
	* ISP Name
* Common
	* Capture Time
	* Operation System
	* Device Type
	* Browser
		* Name
		* Version
	* Geo
	* Session ID
	* Network Mode

# Data acquirement method
**Inject type**: Inject Javascript scriptlet into webpage. Asynchronize load the scriptlet.
**Interactive mode**: Use gRPC-web to make browser clients access the gRPC service.

**Comment by wu-sheng** [comment]
Wow!! This is a very big forward step for SkyWalking. @peng-yongsheng @hanahmily @liuhaoyang @ascrutae I invite all of you into this ticket. Let's find out which source and what kind of protocol we can provide for the browser side.

This fits version6 design core very much. We finally meet the extension at Browser.

**Comment by wu-sheng** [comment]
The first step, we need to design the **source** and **gRPC service** for browser side. @kkroy-zs Do you have something in mind about which services backend provided to receive your metric? That relates to which kinds of data you could uplink in single one request, and which kinds of data should be in a group? I am looking forward to your proposal and idea.

**Comment by wu-sheng** [comment]
FYI @liuhaoyang @terrymanu @terrymanu You may begin to think about database **Source** and **Metric Service** too. Count on you.

**Comment by liuhaoyang** [comment]
I have reservations about using gRPC in javascript. We have done this before, but we have encountered compatibility issues with gRPC. In our practice, the performance of http  is enough.

**Comment by wu-sheng** [comment]
For backend performance, read our document to get some idea
1. Our backend analysis based on OAL, https://github.com/apache/incubator-skywalking/blob/master/docs/en/concepts-and-designs/oal.md @kkroy-zs It is easy to understand, I think.
1. For the browser side, I recommend you to read the scope definition doc, https://github.com/apache/incubator-skywalking/blob/master/docs/en/concepts-and-designs/scope-definitions.md . We need to define the browser scopes first.

**Comment by wu-sheng** [comment]
> I have reservations about using gRPC in javascript. We have done this before, but we have encountered compatibility issues with gRPC. In our practice, the performance of http is enough.

@liuhaoyang Sorry, I don't mean using gRPC as service. I am OK with HTTP, and think it is good enough too.

**Comment by terrymanu** [comment]
> FYI @liuhaoyang @terrymanu @terrymanu You may begin to think about database **Source** and **Metric Service** too. Count on you.

@wu-sheng Yes, it is really good metric list. I will tell our DBA team to evaluate soon.

**Comment by wu-sheng** [comment]
@liuhaoyang Do you have any metric suggestion? I have known you have some experiences about this.

**Comment by kkroy-zs** [comment]
> For backend performance, read our document to get some idea
> 
> 1. Our backend analysis based on OAL, https://github.com/apache/incubator-skywalking/blob/master/docs/en/concepts-and-designs/oal.md @kkroy-zs It is easy to understand, I think.
> 2. For the browser side, I recommend you to read the scope definition doc, https://github.com/apache/incubator-skywalking/blob/master/docs/en/concepts-and-designs/scope-definitions.md . We need to define the browser scopes first.

@wu-sheng OK, I'll read it first to build up the imaginations of the services.
Otherwise, Due to the datas' structrue, there also have some statistics-dimensions which is base on the acquired web-datas must be considered. When I washed out the metric of statistics-dimensions, I will post it here too.

**Comment by wu-sheng** [comment]
When you are ready, post the draft here. Thanks. Interesting proposal.

**Comment by hanahmily** [comment]
Great work! In my own opinion, @kkroy-zs 's work is going to open up a new and important area for skywalking.
I have to say the data of the webpage is much more complicated than backend. The resource request, such as ajax request, is similar to backend service and could be easily handled by oap-server. But the page performance data, such as page loading time, is a very new world for skywallking. We should make some major changes to receive such data.

**Comment by wu-sheng** [comment]
> Great work! In my own opinion, @kkroy-zs 's work is going to open up a new and important area for skywalking.
I have to say the data of the webpage is much more complicated than backend. The resource request, such as ajax request, is similar to backend service and could be easily handled by oap-server. But the page performance data, such as page loading time, is a very new world for skywallking. We should make some major changes to receive such data.

@hanahmily Yes. Changes are definitely required. But I think core is easy to extend to support new source/scope. But I totally agree with you, design those source/scope is a challenge.

**Comment by liuhaoyang** [comment]
> @wu-sheng OK, I'll read it first to build up the imaginations of the services.
> Otherwise, Due to the datas' structrue, there also have some statistics-dimensions which is base on the acquired web-datas must be considered. When I washed out the metric of statistics-dimensions, I will post it here too.

Looking forward to your draft, we will discuss it together after you post it.

**Comment by peng-yongsheng** [comment]
Too many sources, which metrics should to aggregate and show on the UI is the first task.

**Comment by peng-yongsheng** [comment]
@kkroy-zs is a frontend developer, he also can devlope our UI. And he is a java developer.

**Comment by wu-sheng** [comment]
We definitely welcome all kinds of contributions. Consider priority and workloads. Let's make this work step by step.

**Comment by kkroy-zs** [comment]
> We definitely welcome all kinds of contributions. Consider priority and workloads. Let's make this work step by step.

As my data structure listed, there are so many data can be gathered. Which one is important to Sky-walking? This is the first step to be considered things, I think. Some index of the data in the list, after all,  only affect the performance of the front-end. As you said, the work should be done step by step.

Now, I'm a front-end engineer, and I also worked at back-end. I think I can hold this front-end's things. And, I have been creating the project for this idea.

**Comment by wu-sheng** [comment]
Any update for this? @kkroy-zs If still don't have an update in next two weeks, I will remove the milestone.

**Comment by wu-sheng** [comment]
No update in 5 months, closing.
