### ISSUE TITLE
Support peer in Entry span in agent model and backend topology analysis

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#1805]
@ascrutae Now, only exit span supports `#peer`, but in MQ scenario, when there is no reference in message, backend needs MQ peer(ip, hostnamt) to make topology map better.

So, please add peer, representing MQ address, in Entry span. Then backend could support to build a new service relation source based on this.

**Comment by ascrutae** [comment]
I think this demand is not worth doing for three reasons. First, the user installs the agent on the production side. Then he usually installs the agent on the consumer side. Secondly, the API changes quite a bit. I think that we can do a change if someone require. Finally there need build lots of span to  IP in some MQ plugin.

**Comment by wu-sheng** [comment]
OK. Then I am tagging this as `help wanted` and no milestone.

**Comment by wu-sheng** [comment]
This becomes a required feature. Because in zookeeper watcher scenario, we need this. @ascrutae 

ref #2211
