### ISSUE TITLE
Executing order of constructor interception issue

### ISSUE THREAD

**Issue by honganan** [apache/skywalking#1935]
Hi, I think there may be a bug in constructor interception about executing order. According to the comments in class `InstanceConstructorInterceptor`, the interceptor will called before the origin constructor invocation. But when I test it I found my origin constructor called first, and then the interceptor `onConstruct` method.
what I found is bytebuddy supports both two orders, before or after. What makes the difference is `intercept(A.andThen(B))`, for example(refer to L30 ClassEnhancePluginDefine.java):
1) origin constructor first, then the intercept method:
```java
newClassBuilder = newClassBuilder.constructor(constructorInterceptPoint.getConstructorMatcher()).intercept(SuperMethodCall.INSTANCE
                    .andThen(MethodDelegation.withDefaultConfiguration()
                        .to(new ConstructorInter(constructorInterceptPoint.getConstructorInterceptor(), classLoader))
                    )
                );
```
2) the intercept method first, then the origin constructor
```java
newClassBuilder = newClassBuilder.constructor(constructorInterceptPoint.getConstructorMatcher()).intercept(MethodDelegation.withDefaultConfiguration()
                    .to(new ConstructorInter(constructorInterceptPoint.getConstructorInterceptor(), classLoader))
                    .andThen(SuperMethodCall.INSTANCE)
                );
```

**Comment by honganan** [comment]
I think we can change the api in `InstanceConstructorInterceptor` from one method`onConstruct` to two: `beforeConstruct` and `afterConstruct`. But I am not sure if this is suitable.

**Comment by honganan** [comment]
It works, If you don't use `@This` or `@SuperCall` in the interceptor.
I have a test like this, and this could run correctly:
```java
public class ConstructInstrumentation1 {
    public static void main(String[] args) {
        TypePool typePool = TypePool.Default.ofClassPath();
        new ByteBuddy()
            .rebase(typePool.describe("cn.iocoder.learning.bytebuddy.Dog").resolve(), // do not use 'Bar.class'
                ClassFileLocator.ForClassLoader.ofClassPath())
            .constructor(takesArgument(0, String.class))
            .intercept(to(MyConstructInterceptor.class).andThen(SuperMethodCall.INSTANCE)) // This makes the difference!
            .make()
            .load(ConstructInstrumentation1.class.getClassLoader(), INJECTION);

        new Dog("huang").hello();
    }
}

public class MyConstructInterceptor {
    @RuntimeType
    public static void intercept(@AllArguments Object[] allArguments) throws Exception {
        System.out.println("interceptor");
    }
}

public class Dog {
    private String name;
    public Dog(String name) {
        this.name = name;
        System.out.println("constructor");
    }

    public void hello() {}
}
```
and the output is:
```java
interceptor
constructor
```

**Comment by wu-sheng** [comment]
Thanks. Make sense. No `@this` could be accessed before the constructor. My suggestion is we could support another kind of inter, maybe called `ConstructorHijackInter`. In that, you could do intercept before the constructor, and no **this**. 

What do you think? Also, another question is, do you have any scenario which needs this kind of inter? SkyWalking doesn't have right now, I think.

**Comment by wu-sheng** [comment]
FYI @ascrutae I think you should know this. Interesting proposal.

**Comment by honganan** [comment]
We have a scenario, I want to change a field which setting in the constructor to it's super type. So that we can enhance the super type once instead of enhance many sub types.
what we get in constructor is an anonymous subtype, and there is no `setter` method to change this field when after constructor.

**Comment by wu-sheng** [comment]
OK. Then `ConstructorHijackInter` should work, provide `ConstructorHijackInter#beforeConstructor`, right?

**Comment by honganan** [comment]
Yes, I will send a PR today or tomorrow.

**Comment by wu-sheng** [comment]
Good to know. Thanks.

**Comment by honganan** [comment]
SkyWalking is an excellent project. And I thinks it needs more enterprise concrete practice to help it be better. We consult it's design and part of code to improve our APM system. And we have more idea. Do you have any more efficient communication way. Gitter?

**Comment by wu-sheng** [comment]
For English, yes. gitter room, https://gitter.im/OpenSkywalking/Lobby

**Comment by honganan** [comment]
I add the new feature but when I test I found it can't be used to enhance one constructor with the `ConstructInter`. It seems `ConstructInter` and `ConstructHijackInter` is conflict with each other. I am studying on it. FYI.

**Comment by wu-sheng** [comment]
Thanks for sharing. This is new and unexpected.

**Comment by wu-sheng** [comment]
Is there any update in here?

**Comment by honganan** [comment]
Sorry for missing the reply messages. To achieve this feature we need to use `ConstructHijackInter` to replace `ConstructInter` as they can not be coexistence with each other. 

But to do this we need to change all Plugins' interface methods from `onConstruct` to `beforeConstruct` and `afterConstruct`. I think this extensive changes **should be appraised**. And I will test the `ConstructHijackInter`'s stability first.

**Comment by wu-sheng** [comment]
I think we don't need replace, because most people don't need to change argument of construct. Instead, we could provide a new interception way, what do you think?

**Comment by honganan** [comment]
A new interface is available. As there are incompatible, the main logic in `ClassEnhancePluginDefine` should be:
```java
if (existedConstructorInterceptPoint) {
    ...
} else if (existedConstrucotrHijackInterceptPoint) {
    ...
}
if (existedConstructorInterceptPoint && existedConstrucotrHijackInterceptPoint) {
    logger.warn("...")
}
```
If you thought would be ok, I will send a PR moment later.

**Comment by wu-sheng** [comment]
Basically, this is totally fine. As a widely used project, we have a support old interface, especially most users don't need the new feature at this moment.

I am going to opem this issue, again. In case you will submit pull request.

**Comment by wu-sheng** [comment]
No update. I will wait for someone to submit a pull request.
