### ISSUE TITLE
how to install skywalking as windows service?

### ISSUE THREAD

**Issue by zpc870921** [apache/skywalking#1939]
how to install skywalking as windows service?

**Comment by wu-sheng** [comment]
@zpc870921 I think you can't for now.

@liuhaoyang I think maybe could provide this?

**Comment by zpc870921** [comment]
Oh,I see,Thanks!

**Comment by liuhaoyang** [comment]
@zpc870921 You can use [winsw](https://github.com/kohsuke/winsw) wrap oap-service to windows service

**Comment by jsbxyyx** [comment]
@zpc870921 you can use nssm https://www.cnblogs.com/TianFang/p/7912648.html

**Comment by dasajia2lang** [comment]
someone using winsw or nssm install service success?i can install success,but not run success
