### ISSUE TITLE
Print traceId to log4j2 failed

### ISSUE THREAD

**Issue by ASCE1885** [apache/skywalking#1997]
My App using log4j2 for logging, and set

```xml
Log4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
```

in this way, [%traceId] prints `TID:N/A`, will SkyWalking plans to support AsyncLoggerContextSelector in log4j2?

**Comment by wu-sheng** [comment]
@candyleer Would you take care of this? Whether in beta release based on you.

**Comment by ASCE1885** [comment]
@wu-sheng I enhanced `org.apache.logging.log4j.ThreadContext`  and intercept method `getImmutableContext` and `getContext`,before this two method called,I printed `traceid` to mdc. In this way,it both supports sync and async mode of log4j2.

```java
@Override
public void beforeMethod(Class clazz, Method method, Object[] allArguments, Class<?>[] parameterTypes, MethodInterceptResult result) {
        ThreadContext.put("SW-", "TID:" + ContextManager.getGlobalTraceId());
}
```

**Comment by wu-sheng** [comment]
I prefer you could contribute this as optional plugin. Do you have interests to do that?

**Comment by wu-sheng** [comment]
@candyleer what do you think?

**Comment by ASCE1885** [comment]
> I prefer you could contribute this as optional plugin. Do you have interests to do that?

I will create a pull requests later, if @candyleer haven't develop this feature yet.As for the location of this feature's code, in order to keep consistent with logback's mdc, I think it may be better to still in `apm-toolkit-log4j-2.x-activation` plugin:

![image.png](https://upload-images.jianshu.io/upload_images/191937-e6bb6f41cc9ec593.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240))

**Comment by wu-sheng** [comment]
Do you depend on anything in tookit activation? Toolkit activation is an auto actived plugin, so that means, this log plugin always works, which could affect user's existing log analysis system. That is why I suggest to put it in the optional plugin.

I am not very familiar with MDC, so maybe I am wrong. The principle is don't affect user's existing log.

**Comment by ASCE1885** [comment]
@wu-sheng it does not depend on anything in tookit activation.
@candyleer just like logback mdc, in log4j2.xml is `%X{SW-TraceId}` not the original `%traceId`.
Of cource `SW-TraceId` can change to any word, but prefix it with `SW-` will minimize the possibility of conflict with user's log system,reference from Spring Cloud Sleuth's `%X{X-B3-TraceId}`,`%X{X-B3-SpanId}`, `%X{X-B3-ParentSpanId}`.

so where do you think this feature should be located in the project?

**Comment by wu-sheng** [comment]
> it does not depend on anything in tookit activation.

If not, I prefer a new optional plugin in `apm-sniffer/optional-plugins`/log4j2-plugin .  The compiled jar should be located in `agent/optional-plugins`. So it means, this plugin would work in default, you need to copy it to `plugins` folder for making it works.

Also, you need to write document linked here, https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#plugins

Ref another optional plugin document, https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/agent-optional-plugins/trace-ignore-plugin.md

**Comment by wu-sheng** [comment]
No Update.
