### ISSUE TITLE
Grafana integration

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#2053]
@JaredTan95 @TinyAllen @hanahmily 

We have known, [Grafana](https://github.com/grafana/grafana) is a beautiful monitoring. @hanahmily used to propose to use it as SkyWalking native UI, after evaluation, we said **NO** at that moment, because, it wouldn't support component interop very well, no trace and topology supported.

Now, we already SkyWalking native UI and @TinyAllen RocketBot, both are cool. 

**How about we bring Grafana into our ecosystem?**

Of course, still no trace and topology(I assume, need to recheck), at least we could have all metrics.

For supporting that, I think we should 
1. Evaluate how to do integration, is our graphQL APIs powerful enough? If yes, greate. Otherwise, Which kinds of API should we support?
1. Try to provide a Grafana setting files in the main repo or separated repo.

**Comment by wu-sheng** [comment]
RocketBot has provided customize feature, this is not required.

**Comment by timchenxiaoyu** [comment]
原生的ui 和 grafana 还是有差距的
