### ISSUE TITLE
Exception::org.apache.skywalking.apm.plugin.elasticsearch.v5.ElasticSearchEnhanceInfo.transportAddresses

### ISSUE THREAD

**Issue by ychandu** [apache/skywalking#2110]
`ERROR 2018-12-31 13:28:15:414 InstMethodsInter : class[class org.elasticsearch.action.TransportActionNodeProxy] before method[execute] intercept failure java.lang.NullPointerException at org.apache.skywalking.apm.plugin.elasticsearch.v5.ElasticSearchEnhanceInfo.transportAddresses(ElasticSearchEnhanceInfo.java:51) at org.apache.skywalking.apm.plugin.elasticsearch.v5.TransportActionNodeProxyInterceptor.beforeMethod(TransportActionNodeProxyInterceptor.java:53) at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82) at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java) at org.elasticsearch.client.transport.TransportProxyClient.lambda$execute$0(TransportProxyClient.java:60) at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:252) at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60) at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:381) at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:407) at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:396) at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1254) at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.getAliases(AbstractClient.java:1321)`

**Comment by ascrutae** [comment]
This is very strange question, and the log show that the es plugin cannot found `TransportClientNodesService` object what it store all es nodes information. 
Could you give me a simple demo?  because the [demo](https://gist.github.com/ascrutae/7aaa807fe253544de681c28df89663c1) cannot reproduce this issue.

**Comment by ascrutae** [comment]
Just for topology.  Skywalking attempt to builds the mapping relationship between IP and Application to generate the topology

**Comment by wu-sheng** [comment]
> I am getting this issue inside agent, why agent needs es nodes info?

In topology, we need es ip addresses to represent the node, right? That the plugin is trying to do, fetch that info in building span.

**Comment by wu-sheng** [comment]
@ychandu Any demo codes could help us to locate this issue?

**Comment by spark8103** [comment]
my elasticsearch use v6.3, This problem also occurs

**Comment by wu-sheng** [comment]
> my elasticsearch use v6.3, This problem also occurs

Please follow the context, if you have things we could use locate the issue, please submit to here.
