### ISSUE TITLE
spring config trace info error

### ISSUE THREAD

**Issue by mbao** [apache/skywalking#2314]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
There is no trace info of spring cloud config server. 
After debugging, I find that spring cloud config will call two controller method for one request, but after first method finish,RESPONSE_KEY_IN_RUNTIME_CONTEXT is removed, so response is null when next called.
I don't know if this is a bug or there is something error in my using.

![wx20190304-180310](https://user-images.githubusercontent.com/866459/53726286-9ebb1780-3ea8-11e9-8792-674b8d7e085d.png)
![image](https://user-images.githubusercontent.com/866459/53726319-ad093380-3ea8-11e9-903f-5ef50490cf60.png)

**Comment by wu-sheng** [comment]
Why call the method twice?

cc @ascrutae We need to avoid this issue, but I just don't know why this happens.

**Comment by wu-sheng** [comment]
@ascrutae Look like, runntime context should be stack based for each key? I am not sure yet.

**Comment by mbao** [comment]
> Why call the method twice?
> 
> cc @ascrutae We need to avoid this issue, but I just don't know why this happens.

Not one method twice, but one controller method with annotation RequestMapping calls another one with that annotation.

**Comment by wu-sheng** [comment]
I think that is the exact case. You call between controllers.

**Comment by ascrutae** [comment]
This case is more common in some business environment, I will try to fix it in this version.

**Comment by wu-sheng** [comment]
Fixed in 6.1.0
