### ISSUE TITLE
How to make receiver settings more reasonable

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#2322]
This discussion starts with my envoy receiver PR review, https://github.com/apache/incubator-skywalking/pull/2321#pullrequestreview-211287390

@peng-yongsheng and I both agree, we are going to have more receivers, which is great because that is the OAP designed for. But many receivers make the release source/dist tar a little different, or confused to end users or new developers.

At here, we are looking for some solution could turn receiver on/off elegantly, maybe through start up command args or system env, or maybe use a different setting style by extending the module management core. This is open question.

The core requirement for this, is we are supporting receivers from different sources, agent(java), istio, envoy metric, and also expected clr receiver from @liuhaoyang . More and more would be coming, considering I and @JaredTan95 @TinyAllen have several online meetings, talking about RocketBot project donation, which project provide UI customization in the latest dev version. This feature will accelerate the new receiver's coming.(Core extension is ready in most cases)

We very appreciate all @apache/skywalking-committers feedback on this.

**Comment by peng-yongsheng** [comment]
### Current configuration
#### Turn on
* receiver-register
* receiver-trace
* receiver-jvm
* service-mesh
* istio-telemetry
#### Turn off
* receiver_zipkin

I didn't find any rules or principles. Let me make a suggestion:
Turn on: The receive data is from our agent.
Turn off: The receive data if from other util or system.

**Comment by wu-sheng** [comment]
I am thinking of something else than the principle. 

I think we can't say `turn on` agent only is the right call, because, in our document, we call ourself observability analysis platform and have capabilities to process and visualize multiple formats. We started the project by javaagent, doesn't mean it must be agent working, especially we have other languages. As far as I known, @liuhaoyang will provide .NET CLR receiver soon, maybe in 6.1.0

But we can say one thing, we could run in multiple scenarios
1. Language agent.
1. Service Mesh.
1. Envoy.
1. Zipkin

In these three modes, we have certain receivers and `application.yml`, right? Could we consider to deliver different startup scripts to run in different modes?
- `startup-in-language-agent-mode.sh`, Trace, JVM, CLR, register on.
- `startup-in-mesh-mode.sh`, istio, mesh, envoy, register on.
- `startup-in-proxy-mode.sh`, only envoy on.
- `startup-in-zipkin.sh`,  zipkin and trace on.

And, with
- `startup-all.sh` with all receivers on(only turn zipkin-off, because it is not production ready, this is a clear principle). This is for quick-start and docker entry.

If we have this, we could have a clear document why we open these receiver, and which scenario requests us to open.

**Comment by liuhaoyang** [comment]
I prefer to use environment variables as receiver switches, providing a XXX_RECEIVER_ENABLE environment variable switch for each receiver. This will be very convenient in the container.

**Comment by wu-sheng** [comment]
I am +1 for env variable. But we still need default way, and typical scenarios, right?

**Comment by peng-yongsheng** [comment]
`Our agent` is not just means java agent. I emphasize that write by **Our**.

**Comment by wu-sheng** [comment]
Why are our agents more special than other adopt protocol? I don't understand. We are keeping saying we are analysis platform, why a platform treat different formats based on this rule?

I still want to argue for group by scenarios, not our protocols or other protocols.

**Comment by wu-sheng** [comment]
Also, our agents could be complex too. Such as, we could have a istio adaptor and envoy filter. They are our agents. 

Since that happens, we are back to the start line, again. Sadly.

**Comment by wu-sheng** [comment]
No decision made. Closing.
