### ISSUE TITLE
When Skywallking supports MSSQL ?

### ISSUE THREAD

**Issue by Aaronyu111** [apache/skywalking#2340]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1 ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Currently our company use MSSQL , so I want to know when the MSSQL plugin will be supported ? thanks
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0.0GA , JRE1.8.062
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We are welcome the contribution. Right now, I don't know any one is working on this.

**Comment by guojie0701** [comment]
me too ,   our  business need to support sqlserver too.

**Comment by IluckySi** [comment]
I plan to support if now there is no one working on it ~

**Comment by spark8103** [comment]
me too , our business need to support sqlserver too.

**Comment by maurodouglas** [comment]
is there anyone working on this ?

**Comment by wu-sheng** [comment]
Still in `help wanted`, I don't know anyone is doing this.

**Comment by yangfande362** [comment]
still have no support with sqlserver?

**Comment by wu-sheng** [comment]
@yangfande362 Don't see anyone is contributing this plugin.
