### ISSUE TITLE
span lost using es storage

### ISSUE THREAD

**Issue by ywf4026** [apache/skywalking#2406]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?

![image](https://user-images.githubusercontent.com/3722641/55046561-049c5880-507d-11e9-9f77-42e262aff335.png)

Click through traceid, some spans lost
![image](https://user-images.githubusercontent.com/3722641/55047155-be47f900-507e-11e9-8922-29dee7aa20b3.png)

From above gragh, some spans are independent because of its parent span is lost.
But in trace page, the lost spans can be searched 

Anyway, using h2 storage has no problem.

So Could you give me some suggestions to find the problem, I'm confused.

thanks

**Comment by wu-sheng** [comment]
Are you meaning span or segment? There is no difference between H2 and ElasticSearch.

**Comment by wu-sheng** [comment]
Are you running in multiple threads? Or async thread scenario? It looks like the context is not being clear right.

**Comment by ywf4026** [comment]
@wu-sheng 
span ,  multiple threads

**Comment by wu-sheng** [comment]
Span can't be lost. That is certain. Multiple threads mean multiple segments.

**Comment by ywf4026** [comment]
it's strange, change to h2 storage is ok

**Comment by wu-sheng** [comment]
You may just be misguided. Storage can't change this in any case, most likely, this is caused by multiple threads running in an unpredictable way.

**Comment by ywf4026** [comment]
thanks, I'll see it again

**Comment by ywf4026** [comment]
@wu-sheng
I replay this issue by running different task in one threadpool

code is below

![image](https://user-images.githubusercontent.com/3722641/55141741-0eee4d80-5176-11e9-9c5f-26c4ccc92f9b.png)

if n is greater, the trace graph will not be consistent.

![image](https://user-images.githubusercontent.com/3722641/55142086-c3886f00-5176-11e9-8947-c1cb9d2c4f8b.png)

**Comment by wu-sheng** [comment]
You are using the annotation in the wrong scenario. This annotation works for a new thread and run scenario.

**Comment by ywf4026** [comment]
> You are using the annotation in the wrong scenario. This annotation works for a new thread and run scenario.

I use the annotation followed by document
https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-trace-cross-thread.md

![image](https://user-images.githubusercontent.com/3722641/55204759-2deaef00-520b-11e9-89ff-6a5bc56dbcf6.png)

**Comment by wu-sheng** [comment]
But that example is showing you to create a new thread, rather than use thread pool. Big difference.

**Comment by ywf4026** [comment]
> to creat

I found the cause. It's the limit size(20) when es query segments by traceid if having more then 20 segments.

![image](https://user-images.githubusercontent.com/3722641/55213422-2e48b180-522e-11e9-9461-51f76f9cac14.png)


I adjust the size to 100, then the trace graph is ok.

Anyway, how to set the size may be a quesiton.

**Comment by wu-sheng** [comment]
Why do you have so many segments? A batch process? cc @peng-yongsheng What do you think about this?

**Comment by ywf4026** [comment]
Yes, a batch process, involves many threads

**Comment by wu-sheng** [comment]
This is new to me. Maybe we need open this as config item.

**Comment by peng-yongsheng** [comment]
@wu-sheng This is the first issue he found, and should not be the only one. One by one invoke or less batch invoke is conformity with the orginal design. But too many batch asynchronous threads is ignored.

**Comment by wu-sheng** [comment]
What do you mean about original design? I am a little confused. 

I think tracing a batch task is not a very common use case, but at the trace data level, they are well organized. Right now, the impact is we can't query all of them in before.

**Comment by peng-yongsheng** [comment]
We are not discuss about **batch asynchronous threads**, we just discussed how to support **asynchronous threads**, right?

**Comment by wu-sheng** [comment]
> We are not discuss about batch asynchronous threads, we just discussed how to support asynchronous threads, right?

I don't intend to start any discussion. I am just asking, if a trace has more than 20 segments, then what we should do in query. Do we provide config to make query available?

I think asynchronous is another complex topic.

**Comment by peng-yongsheng** [comment]
> > We are not discuss about batch asynchronous threads, we just discussed how to support asynchronous threads, right?
> 
> I don't intend to start any discussion. I am just asking, if a trace has more than 20 segments, then what we should do in query. Do we provide config to make query available?
> 
> I think asynchronous is another complex topic.

Agree with you, we don't known what the limit size is suitable, add a config item to support this first. 
I just notice that there will be other issues.

**Comment by wu-sheng** [comment]
> Agree with you, we don't known what the limit size is suitable, add a config item to support this first.
I just notice that there will be other issues.

Yes. I noticed those too :) So could you send a PR to fix those? I think we need some mechanism to make them consistently.

**Comment by peng-yongsheng** [comment]
> > Agree with you, we don't known what the limit size is suitable, add a config item to support this first.
> > I just notice that there will be other issues.
> 
> Yes. I noticed those too :) So could you send a PR to fix those? I think we need some mechanism to make them consistently.

OK

**Comment by wu-sheng** [comment]
@peng-yongsheng Thanks. I will leave this as an issue to you.

**Comment by wu-sheng** [comment]
@JaredTan95 Could you work on this?
