### ISSUE TITLE
Increase the test coverage rate

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#2438]
Today, SkyWalking's tests are mostly around integration tests, which are benifit for end users. Now we hope through this, people from community could help on Unit Tests.

JUnit and Mockito are provided. This is a good start for everyone wants to contribute codes. When you submit test cases PR, please ref to this issue.

**Comment by wu-sheng** [comment]
Also, in this kind of pull request, we don't limit how many test cases you provide. Even one new test case, which could effectively test one more line, it will be acceptable. Just try your best to make tests more sense.

**Comment by flycash** [comment]
Where can I find the code coverage report?

**Comment by wu-sheng** [comment]
The coverage is here, https://coveralls.io/github/apache/skywalking

**Comment by wu-sheng** [comment]
Update here, we are only just increasing the test case coverage, we are doing more.

- [x] @kezhenxu94 set up the Jenkins of ASF for power test env.
- [ ] @ascrutae lead the agent test in Jenkins jobs of every PR when necessary
- [ ] @kezhenxu94 lead the e2e test, make agent/backend integration test done in every PR.

**Comment by wu-sheng** [comment]
We have e2e tests fro single node w/ H2 and cluster mode w/ ES. We are trying to build more. Including MySQL storage tests, alarm tests, and aggregation accuracy tests.

**Comment by wu-sheng** [comment]
After #3561, we have 30%+ coverage now.

**Comment by wu-sheng** [comment]
~~@ascrutae lead the agent test in Jenkins jobs of every PR when necessary~~

This task is lead by @dmsolr on #3528. Ownership replaced.

**Comment by wu-sheng** [comment]
Agent autotest framework has been provided, and 300+ test cases have been added. Seems working well. Just working for @dmsolr to provide the official documents, rather than guide users to do that one by one.

**Comment by wu-sheng** [comment]
# Status update
All important tests have been provided in the master branch and PR process already. This issue will keep open if any contributor wants to help about the Unit Tests.
