### ISSUE TITLE
Look volunteers to translate(sync) English documents to Chinese

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#2441]
The new Chinese document is at 
- https://github.com/SkyAPM/document-cn-translation-of-skywalking 

We are welcome the contributions. 

cc @brucewu-fly @kezhenxu94 @JaredTan95 I closed the old one.

**Comment by thelight1** [comment]
I want to do it , what should I do?

**Comment by kezhenxu94** [comment]
> I want to do it , what should I do?

Hi @thelight1,  please refer to this issue SkyAPM/document-cn-translation-of-skywalking#3

**Comment by thelight1** [comment]
ok, I want to translate the files in directory [protocols](https://github.com/apache/incubator-skywalking/tree/master/docs/en/protocols)

**Comment by kezhenxu94** [comment]
Hi @wu-sheng I suggest **lock this conversation** to guide the contributors to [SkyAPM/document-cn-translation-of-skywalking](https://github.com/SkyAPM/document-cn-translation-of-skywalking) , what do you think

![image](https://user-images.githubusercontent.com/15965696/55871459-3a812700-5bbd-11e9-8801-1d4883cf0f7c.png)

**Comment by wu-sheng** [comment]
@kezhenxu94 done. All discussion should move to new repo.
