### ISSUE TITLE
i want monitor c and c++, what can i do?

### ISSUE THREAD

**Issue by coki230** [apache/skywalking#2443]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
-  Feature or performance improvement

___

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

i want to know does it have a method or proposal to monitor the c and c++

**Comment by wu-sheng** [comment]
You could build a c/c++ SDK based on SkyWalking protocol, it is open and friendly to other languages.

**Comment by coki230** [comment]
thank you very much. do you have any book which learn APM or skywalking to recommend

**Comment by wu-sheng** [comment]
@coki230 Assuming you could read Chinese(from your profile), I used to write part of this book, https://item.jd.com/12498217.html, to talk about Observability in general.

**Comment by wu-sheng** [comment]
@dio The community is calling you :P

**Comment by coki230** [comment]
@wu-sheng thanks, It's a great help to me.
