### ISSUE TITLE
Use the @TraceCrossThread annotation to solve the problem that call chains cannot be traced when asynchronous calls are made, but it has no effect.

### ISSUE THREAD

**Issue by dsw1985815** [apache/skywalking#2444]
Use the @TraceCrossThread annotation to solve the problem that call chains cannot be traced when asynchronous calls are made, but it has no effect.

1. I created the SearchThread class to implement the Callable interface and annotated it with @TraceCrossThread

2. I used FutureTask to make asynchronous calls in my method，but the call chain is break

3.i tried version 5 and version 6 have the same problem

Details are in line 166 of the code SignflowSearchApiImpl 144
[code.zip](https://github.com/apache/incubator-skywalking/files/3042480/code.zip)

**Comment by IanCao** [comment]
@dsw1985815 could u provide a demo that can run directly

**Comment by wu-sheng** [comment]
No update in one month.
