### ISSUE TITLE
SkyWalking about JVM monitoring

### ISSUE THREAD

**Issue by brentoncao** [apache/skywalking#2468]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
-Hello, at present, I found that there are only four types of jvm information detected by SkyWalking. Can I monitor the thread pool?

**Comment by wu-sheng** [comment]
Right now, we haven't. The contribution is welcome.

**Comment by brentoncao** [comment]
ok，thank you~

**Comment by flycash** [comment]
What do you want to know from monitoring thread pool? @brentoncao Number of thread? The number of tasks in blocking queue? Or execution time?

**Comment by brentoncao** [comment]
@flycash  In addition to the above points, I also want to monitor the status of the current thread. Of course, it is better that can monitor more thread pool related information.

**Comment by wu-sheng** [comment]
@jason8888888 Thread analysis is different issue with this context. We are going to provide thread dump analysis with distributed tracing in the production environment in 7.0.0.

**Comment by wu-sheng** [comment]
@jason8888888 We have better solution about the profiling. The number of threads has been watched in the 8.1.0 release.
