### ISSUE TITLE
[Agent] Provide plugin for Solr-7.x

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#2501]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
- it will provide a sniffer plugin include solrj and solr.

**Comment by wu-sheng** [comment]
Welcome the contribution for the new plugin.

**Comment by dmsolr** [comment]
Coming soon. :-)

**Comment by wu-sheng** [comment]
Please notice this, https://github.com/SkyAPMTest/agent-auto-integration-testcases. Automatic tests are highly recommended to provide with your plugin pull request before we do code review. That test is the strong proof to help the project team accepts your new plugin.

**Comment by dmsolr** [comment]
I get it. thanks for your tips.

**Comment by dmsolr** [comment]
how difficult about auto-testcases.  : (

**Comment by wu-sheng** [comment]
Which part is different for you? Do you face any issue? Cc @ascrutae

**Comment by dmsolr** [comment]
I don't have any experience on docker. but it is ok, I think.

**Comment by wu-sheng** [comment]
Yes. Docker is required. But basically, it reduced the difficulties because of docker.
