### ISSUE TITLE
kafka agent plugin not work properly

### ISSUE THREAD

**Issue by jadezhong** [apache/skywalking#2505]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- How to solve this problem?

___
### Bug
- OS: CentOS
- JRE: 1.8
- Skywalking: 6.0.0-GA
- Spring Cloud: Edgware.SR4
- Spring Kafka: 1.3.8-RELEASE

when sending message, org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(long offset, boolean isControlRecord, long timestamp, ByteBuffer key,
                                  ByteBuffer value, Header[] headers), throw IllegalArgumentException, error message is "Magic v1 does not support record headers"

___
### Requirement or improvement
- N/A

**Comment by wu-sheng** [comment]
The log is very clear, your Kafka doesn't support header. We need Kafka 0.11.0.0 -> 1.0, see https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md

**Comment by jadezhong** [comment]
yes, the underlying kafka-clients is ver 0.11.0.2
