### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by liuyongtao** [apache/skywalking#2507]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- whern 
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- when I download  SkyWalking releases 6.0.0，run startup on windows，it shows that

"WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.reflectasm.AccessClassLoader (file:/D:/d/%e6%b5%8b%e8%af%95%e9%a1%b9%e7%9b%ae/apache-skywalking-apm-incubating-6.0.0-GA/apache-skywalking-apm-incubating/oap-libs/reflectasm-1.11.7.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.reflectasm.AccessClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release"

is my JDK version too higher? my jdk is 
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**Comment by liuyongtao** [comment]
SkyWalking  release version 6.0.0-GA

**Comment by wu-sheng** [comment]
Yes, we only run this in JRE 8, maybe 9 is ok. I am not sure about the status of 11. If you have interests to contribute, we are welcome to support running OAP in JRE 11 or higher.
