### ISSUE TITLE
I use okhttp as dubbo rpc module, the trace was mess (当我用okhttp作为dubbo的底层通信模块时，调用链会出现分叉的现象)

### ISSUE THREAD

**Issue by zxbu** [apache/skywalking#2512]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking

- What happen?
I use okhttp as dubbo rpc module, the trace was mess (当我用okhttp作为dubbo的底层通信模块时，调用链会出现分叉的现象)

one rpc will cause two trace 

![image](https://user-images.githubusercontent.com/32785355/56642987-4683e300-66ab-11e9-904c-ecec8a12e280.png)

**Comment by wu-sheng** [comment]
I don't know much about the dubbo + okhttp. If there is async, you need a new plugin to deal with it.

**Comment by wu-sheng** [comment]
I don't know what the trace should be, so even you show me the graph, I have no clue. Sorry.

**Comment by zxbu** [comment]
It was a simple dubbo rpc like a -> b.
so  the trace should be  like this pic: 

![image](https://user-images.githubusercontent.com/32785355/56643544-67006d00-66ac-11e9-867b-083b39b6bb58.png)


Actually, I use a async http invoke in dubbo. 
My solution is remove the okhttp plugin, it worked.
Thank you for your reply, you can close issue if need.

**Comment by wu-sheng** [comment]
I am closing. If you active http async, because dubbo plugin doesn't know async, then this shows as two rpc calls. That is why we provide this convenient way to remove some plugin.
