### ISSUE TITLE
Can apm-trace-ignore-plugin ignore path with given plugin ?

### ISSUE THREAD

**Issue by zxbu** [apache/skywalking#2513]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug

- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
Sometimes, I hope ignore path with given plugin, not for all plugins.
Such as: I will ignore path `/aaa`  only for okhttp plugin, and httpClient plugin not affected.

**Comment by wu-sheng** [comment]
Fisrt of all, this is trace ignore, not span ignore. Http client libs are exit spans, which can affect te trace.
