### ISSUE TITLE
ServiceAndEndpointRegisterClient running, status:CONNECTED.

### ISSUE THREAD

**Issue by 3tem** [apache/skywalking#2514]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___

   centos 7 and jre1,8

  The startupagent  started reporting an error , demo is SpringBoot project 
  the log is info :
   Selected collector grpc service running, reconnect:false. 
  ServiceAndEndpointRegisterClient running, status:CONNECTED. 

The server port has access

**Comment by wu-sheng** [comment]
This is the normal log. It says, running, in debug level.
