### ISSUE TITLE
InstanceMethodsInterceptPoint to  enhance a abstract class's abstract method

### ISSUE THREAD

**Issue by IAMTJW** [apache/skywalking#2516]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
I want use InstanceMethodsInterceptPoint to  enhance a abstract class's abstract method，but it's not effective

___
### Question
- What do you want to know?
Is the InstanceMethodsInterceptPoint not support  the abstract class the abstract method?

**Comment by wu-sheng** [comment]
It is an abstract method, you can't enhance that :) JVM rule. If you mean all sub classes who implement this method, maybe try `HierarchyMatch`
