### ISSUE TITLE
Track seata/SkyWalking integration step1

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#2523]
Hi @zhaoyuguang @kezhenxu94

This issue has been created only for tracking the status of integration work, based on this [conclusion](https://github.com/seata/seata/issues/714#issuecomment-486605181)

I hope we could finish this in 6.2 release, at least step 1, which should at least one month later.

Let's separate the tasks, please reply which part you will lead. And link further PRs to this issue.

Thanks.

cc @CoffeeLatte007

**Comment by kezhenxu94** [comment]
I'll take the works related to TransactionManager (TM) and parts of TransactionCoordinator (TC)

**Comment by wu-sheng** [comment]
No longer active anymore.
