### ISSUE TITLE
skywalking suppport xxl-job

### ISSUE THREAD

**Issue by IAMTJW** [apache/skywalking#2527]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Feature or performance improvement

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

Is  it support xxl-job like elastic-job?

**Comment by wu-sheng** [comment]
No, but a contribution is welcome.

**Comment by wu-sheng** [comment]
You could inform the xxl-job project team to contribute this to SkyWalking. I have plenty of plugins come in this way.

**Comment by IAMTJW** [comment]
OK，I will try

**Comment by wu-sheng** [comment]
I think you have found our plugin development document, right?

**Comment by IAMTJW** [comment]
> I think you have found our plugin development document, right?

I am using skywalking and learning something about it，and I have konwn how elastic-job work and I may know how to develope the xxl-job

**Comment by wu-sheng** [comment]
@IAMTJW Why closing this?

**Comment by wu-sheng** [comment]
Let's keep this issue open, until PR https://github.com/apache/skywalking/pull/2537 merged.

**Comment by leon756** [comment]
@tian-junwei 
Does xxl-job 2.4.0 work?
> p.s. skywalking version: 8.7.0
