### ISSUE TITLE
 does skywalking support elasticsearch 7?

### ISSUE THREAD

**Issue by imkiven** [apache/skywalking#2529]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion

___
### Question
- What do you want to know?
 does skywalking support elasticsearch 7?

**Comment by wu-sheng** [comment]
Plugin or Storage?

**Comment by imkiven** [comment]
> Plugin or Storage?

both or either or neither?

**Comment by wu-sheng** [comment]
We haven't any of them. But
- For the plugin, we welcome the contribution.
- For storage, we can't accept, because 6.3+ is already very new to the community.

**Comment by hellxz** [comment]
Does Skywalking 6.2 supported Elasticsearch 7.x  now? @wu-sheng

**Comment by wu-sheng** [comment]
We have clear documents about version supported
