### ISSUE TITLE
5.0.0-GA upgraded to 6.0.0-GA

### ISSUE THREAD

**Issue by xiaoni157** [apache/skywalking#2532]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Our company now USES 5.0.0-GA, and then wants to change to 6.0.0-GA version. Is the es version of aliyun still compatible with 5.5.3 version? I cannot pass the local test, must I force to upgrade to 6.3.2?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You could refer this way. But you have to re-implement the storage. It is not Apache release.

https://github.com/SkyAPM/SkyWalking-With-Es5x-Storage

**Comment by wu-sheng** [comment]
In official release, ElasticSearch 6.x is required.
