### ISSUE TITLE
Performance test report

### ISSUE THREAD

**Issue by xjhuiw** [apache/skywalking#2549]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
  
   Is there a performance test report?

**Comment by wu-sheng** [comment]
Chinese version.
- official, https://skyapmtest.github.io/Agent-Benchmarks/README_zh.html
- 3rd party
https://github.com/apache/skywalking/issues/1596#issuecomment-418946050
https://upload-images.jianshu.io/upload_images/14516896-c3c5b7633d0577f8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1000/format/webp
