### ISSUE TITLE
 GraphQL  not support "Long" type

### ISSUE THREAD

**Issue by cheetah012** [apache/skywalking#2552]
- Why do you submit this issue?
- [1 ] Question or discussion
___
### Question
aggregation.graphqls
alarm.graphqls
metric.graphqls
top-n-records.graphqls
trace.graphqls
containing "long" type，but GraphQL  not support "Long" type,
When using idea, type checks report errors

**Comment by wu-sheng** [comment]
@hanahmily inform me, the `Long` is a new type in our Resolver. You could find it in the implementation.
