### ISSUE TITLE
Sample implementation for Opentracing for Skywalking

### ISSUE THREAD

**Issue by vanjikumaran** [apache/skywalking#2555]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ X] Feature or performance improvement

___
### Question
- Currently, The documented does not provide much more information on the usage or sample implementation on openTracing [1]; Is there any sample that been already implemented?
 

[1] https://github.com/apache/skywalking/blob/e93b3f0d16fd1b28e6342e4e179f313922e33757/docs/en/setup/service-agent/java-agent/Opentracing.md

**Comment by wu-sheng** [comment]
OpenTracing just asked the implementor to provide the tracer and related APIs. So, only this related to SkyWalking API.

SkyWalking-OT is a bridge, you still need to install the agent. In SkyWalking, we only recommend you to use OT when you want to add you new local span.

**Comment by wu-sheng** [comment]
Don't use OT API instrument lib and OT API to instrument RPC. We have plenty auto-instrumentation plugins, which will work better and no code injection.
