### ISSUE TITLE
Skywalking 6.0.0-GA agent does not work properly with Spring Cloud Gateway

### ISSUE THREAD

**Issue by SataQiu** [apache/skywalking#2556]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
   How to make the SkyWalking agent work properly with SpringCloud Gateway project.
___
### Bug
- Which version of SkyWalking, OS and JRE?
   SkyWalking Version: 6.0.0-GA
   OS: Ubuntu 18.04.2 LTS (amd64)
   JDK: 1.8.0_202

- Which company or project?

- What happen?
I created a Spring Cloud Gateway project and it worked.
But when I added the SkyWalking agent to the JVM startup parameter list, the project could not boot.

Some error like this:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc369565058, pid=9828, tid=140477338953472
#
# JRE version: Java(TM) SE Runtime Environment (8.0_11-b12) (build 1.8.0_11-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.11-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x00007fc369565058
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/shida/sts-space/SpringGW/hs_err_pid9828.log
Compiled method (c1)   21610 3306       1       sun.invoke.util.ValueConversions::identity (2 bytes)
 total in heap  [0x00007fc3558ad390,0x00007fc3558ad600] = 624
 relocation     [0x00007fc3558ad4b0,0x00007fc3558ad4d0] = 32
 main code      [0x00007fc3558ad4e0,0x00007fc3558ad540] = 96
 stub code      [0x00007fc3558ad540,0x00007fc3558ad5d0] = 144
 scopes data    [0x00007fc3558ad5d0,0x00007fc3558ad5d8] = 8
 scopes pcs     [0x00007fc3558ad5d8,0x00007fc3558ad5f8] = 32
 dependencies   [0x00007fc3558ad5f8,0x00007fc3558ad600] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
```
Here is my sample project: https://github.com/SataQiu/SpringGW

Dump log: https://github.com/SataQiu/SpringGW/blob/master/hs_err_pid16982.log

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You could follow the pull request related to this.
