### ISSUE TITLE
skywalking 6.0.0-GA collector start failed.

### ISSUE THREAD

**Issue by xiaoni157** [apache/skywalking#2557]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.0.0-GA
ES ali cloud 6.3.2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

![image](https://user-images.githubusercontent.com/24448049/56890893-5174b400-6aad-11e9-9259-f5ba8ec63dee.png)

This is my application.yml file.
![image](https://user-images.githubusercontent.com/24448049/56891051-c47e2a80-6aad-11e9-9c0c-c1517e61ea1b.png)

**Comment by wu-sheng** [comment]
I don't know why you can't ali Cloud Elasticsearch. Please check by yourself.

**Comment by xiaoni157** [comment]
If I want to use ali Cloud, is there any problem with my configuration?

**Comment by wu-sheng** [comment]
That part I don't know...
