### ISSUE TITLE
Can I configure alarm rules through the UI? Customize alarms through the UI?

### ISSUE THREAD

**Issue by xjhuiw** [apache/skywalking#2558]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Can I configure alarm rules through the UI? Customize alarms through the UI?

Can only be fixed  Config/ Alarm -settings.yml Configuration Alert?    

Can be configured with multiple Alarm -settings.yml ? 

Is there an alarm message or email to notify the relevant person?

**Comment by wu-sheng** [comment]
> Can I configure alarm rules through the UI? Customize alarms through the UI?

Can't, today.

> Can only be fixed Config/ Alarm -settings.yml Configuration Alert?

I don't understand this question.

> Can be configured with multiple Alarm -settings.yml ?

No. Why do you need multiple files?

> Is there an alarm message or email to notify the relevant person?

Please use webhook in the alarm module.  You could do anything in there. Based on ASF 2.0, I can't use commercial message protocol.

**Comment by xjhuiw** [comment]
For the second question
Excuse me, I want to express the alarm rules that must be configured in this file?

**Comment by xjhuiw** [comment]
How to use webhook  ? Can provide the use of the document connection address
?

**Comment by wu-sheng** [comment]
> For the second question
Excuse me, I want to express the alarm rules that must be configured in this file?

Yes. Right now it is.

> How to use webhook ? Can provide the use of the document connection address?

It is already included in `alarm-settings.yml`. such as
```
webhooks:
  - http://127.0.0.1/notify/
```

The target endpoint could receive the alarm message in HTTP request body in JSON format.

**Comment by xjhuiw** [comment]
thank you very much

I queried the relevant information, for example.   https://skywalking.apache.org/zh/blog/2019-01-03-monitor-microservice.html

**Comment by xjhuiw** [comment]
The target endpoint could receive the alarm message in HTTP request body in JSON format.

Can I configure alarm message to send through the UI?

**Comment by wu-sheng** [comment]
> How to use webhook ? Can provide the use of the document connection address?

No, you can't.

**Comment by xjhuiw** [comment]
If you dynamically modify alarm-settings.yml, do you need to restart the service?

**Comment by wu-sheng** [comment]
> If you dynamically modify alarm-settings.yml, do you need to restart the service?

Right now, Yes.
