### ISSUE TITLE
Standardize Time in SkyWalking

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#2560]
Hi

Today, SkyWalking time mechanism relied on the agent, backend, and UI in the same time zone, but still facing issues. Because of the time in agent traces, it is hard to make it accurate in the query.

In 6.2, I want to do this, which related to agent, backend and UI changes.
1. Agent reports its timezone in register and heartbeat, in default, treated as backend timezone for back-forward compatible. But I hope Java, .net, nodejs, php, go agents could adopte this. @ascrutae @liuhaoyang @hanahmily @heyanlong
1. Service Mesh receiver, especially istio and envoy receiver need to transfer time based on timezone in the timestamp. @hanahmily 
1. OAP backend will transfer time format to UTC-0 always and save in storage.
1. OAP query parameter and result are all based on UTC-0, UI needs to change time visualization based on browser timezone. Also, because of this, I think no need to choose timezone anymore. @TinyAllen

**Comment by hanahmily** [comment]
> Agent reports its timezone in register and heartbeat, in default, treated as backend timezone for back-forward compatible. But I hope Java, .net, nodejs, php, go agents could adopte this.
If we use gRPC, I think the best practice is that at the first segment of streaming the agent is designed to report timezone.
> Service Mesh receiver, especially istio and envoy receiver need to transfer time based on timezone in the timestamp. @hanahmily <https://github.com/hanahmily>For service mesh, eg. istio mixer,envoy, there’s no chance to grab timezone of senders. But a good news for us is they are both deployed in docker whose default timezone is GTM(UTC-0), especially envoy’s access log is [designed to support it](https://github.com/envoyproxy/envoy/issues/3546 <https://github.com/envoyproxy/envoy/issues/3546>).So the details should be declared in our documents.

**Comment by wu-sheng** [comment]
> If we use gRPC, I think the best practice is that at the first segment of streaming the agent is designed to report timezone.

But it will break all agent protocol, which will be a disaster. See what happens in 5.0->6.0, some agents are still not fitting the new protocol. I really don't want to do that.

**Comment by hanahmily** [comment]
It seems an extension far more than a breaking. I means if the agent has adopted the new protocol cloud send timezone, other agent could use old ways to send data. In other word, the oap makes an assumption that all data received is belonging to GTM unless it gets the exact timezone of the agent.

**Comment by wu-sheng** [comment]
> It seems an extension far more than a breaking. I means if the agent has adopted the new protocol cloud send timezone, other agent could use old ways to send data. In other word, the oap makes an assumption that all data received is belonging to GTM unless it gets the exact timezone of the agent.

Then you need to extend all agent protocol as 6.0 did. Because all agent protocols include time. Also,y, you should known, in gRPC/protobuf, the naming will become very hard. Because span/segment need to be renamed again.

**Comment by wu-sheng** [comment]
>  In other word, the oap makes an assumption that all data received is belonging to GTM unless it gets the exact timezone of the agent.

@hanahmily You can't. Because old agents base on OS time only.

**Comment by hanahmily** [comment]
lol…
What we discussed is not a same thing. I proposed a common practice, not refer any existing API. If the API we will extend is base on streaming what I propose will work.

**Comment by hanahmily** [comment]
How to handle them? If we document if user change os time to GTM, the OAP will work fine?

**Comment by wu-sheng** [comment]
> What we discussed is not a same thing. I proposed a common practice, not refer any existing API. If the API we will extend is base on streaming what I propose will work.

Not all APIs are based on streaming, just trace API does. We could extend the protocol, by adding a new field and hope gRPC works. It will relate to
- Register service/instance/endpoint
- Trace
- JVM/CLR
- Heartbeat

> How to handle them? If we document if user change os time to GTM, the OAP will work fine?

That is the issue. We haven't a perfect way to handle it, especially at trace page. That is why I proposed this. Because the browser time zone can't be in the time zone. We must find a way to do time  format Standardization.

**Comment by hanahmily** [comment]
> That is the issue. We haven't a perfect way to handle it, especially at trace page. That is why I proposed this. Because the browser time zone can't be in the time zone. We must find a way to do time format Standardization.
> 

So we should document it well. If OAP save data as UTC, some user might not query data when upgrade their backend. There’re a lot of issues about the same thing in Prometheus community event though maintainers have document it and provide FAQ.

**Comment by wu-sheng** [comment]
> So we should document it well. If OAP save data as UTC, some user might not query data when upgrade their backend. There’re a lot of issues about the same thing in Prometheus community event though maintainers have document it and provide FAQ.

No, it wouldn't. That is whole point of this proposal. Because UI will adopt the client side timezone. Query time and result time are based on UTC, and UI changes it to browser timezone. 
Make sense?

**Comment by hanahmily** [comment]
I doubt it…
For a scenario that local Chinese team have a plan to upgrade skywalking. If their old OAP instances use UTC+8. Data sending time is 8:00:00(UTC+8), the new OAP save as 8:00:00(UTC+0).If end user also in the same timezone, the UI transform query time 8:00:00(UTC+8) to 0:00:00(UTC+0). So the user can not query any data.

Yes. the proposal have point out that the agent should report timezone. But If we want provide some backward compatibility that’s what we should figure out.How to fix it? the user should set OAP instance to use UTC that should be well documented for upgrading.

For service mesh, eg. istio mixer,envoy, there’s no chance to grab timezone of senders. But a good news for us is they are both deployed in docker whose default timezone is UTC, especially envoy’s access log is [designed to support it](https://github.com/envoyproxy/envoy/issues/3546 <https://github.com/envoyproxy/envoy/issues/3546>).So the details should be declared in our documents.

**Comment by wu-sheng** [comment]
> For a scenario that local Chinese team have a plan to upgrade skywalking. If their old OAP instances use UTC+8. Data sending time is 8:00:00(UTC+8), the new OAP save as 8:00:00(UTC+0).If end user also in the same timezone, the UI transform query time 8:00:00(UTC+8) to 0:00:00(UTC+0). So the user can not query any data.

Yes. But I think I have no idea to support the upgrade. From I known, @peng-yongsheng ongoing PR to improve the delete performance, most likely break the whole ElaticSearch back-forward compatible. :)

> So the details should be declared in our documents.

That is true.

**Comment by wu-sheng** [comment]
I and @peng-yongsheng deep dive on this yesterday. Turn out, we both misunderstand one API in Java. Timestamp(System.currentTimeMillis) is UTC-0 based, no time zone involved.

So, this issue should be closed, and become two separated things.
1. [BUG] #2586 UI bug, needs to be fixed. @TinyAllen 
1. [FEATURE] #2594 Backup supports setting time zone manually to override OS settings. cc @peng-yongsheng @hanahmily
