### ISSUE TITLE
endpoint页面报错

### ISSUE THREAD

**Issue by appregidc** [apache/skywalking#2561]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug
___
### Bug
- Which version of SkyWalking, OS and JRE?
    6.0GA  CentOS Linux release 7.4.1708 (Core) 
    java version "1.8.0_101"
    Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
   Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

- Which company or project?
   glodon
- What happen?
      在部署使用一段时间后，打开endpoint页面报错，报错如下：
      Exception while fetching data (/queryBasicTraces) : Elasticsearch exception 
      [type=parsing_exception, reason=[match_phrase] query does not support [zero_terms_query]]
      同时 Top 20 Slow Traces 看不到任何数据

**Comment by wu-sheng** [comment]
English only, 6.1 is on the way, please retry there.

**Comment by appregidc** [comment]
thks, when 6.1 will release?
