### ISSUE TITLE
[Agent] Provide plugin for Apache CXF

### ISSUE THREAD

**Issue by suizhe** [apache/skywalking#2562]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
-  Requirement

Are there plans to provide plugin for Apache CXF？

**Comment by wu-sheng** [comment]
We are always welcome to new plugin contribution. You could try to build one and contribute to the community. We have well-documented steps to do so.

**Comment by suizhe** [comment]
Could you please provide the document for developing  plugins.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/blob/master/docs/en/guides/README.md#project-extensions
