### ISSUE TITLE
A async rpc agent plugin can not work

### ISSUE THREAD

**Issue by liucyu** [apache/skywalking#2565]
### Question
I wrote a rpc agent plugin, and the Interceptor method will return null result when i use the async mode. so the `ContextManager.stopSpan();` in afterMethod will throw NullPointerException and the ui cannot display the trace chain. so how can I solve this question
??
![image](https://user-images.githubusercontent.com/13191643/56951139-a249e280-6b69-11e9-9c87-c029f5cb63aa.png)

**Comment by wu-sheng** [comment]
Please learn from Vert.x and gRPC stream plugins. Async and sync are working in a different way.

**Comment by liucyu** [comment]
Is there any documentation for reference? grpc or vert.x has no comments, it is difficult to understand what he wants to express @wu-sheng

**Comment by wu-sheng** [comment]
For APIs, we have detailed documents about plugin development. What else do you need? Across thread is comples, you need to decide
1. Use capture/continued(grpc stream)
Or
2. Set span async and finish in another thread(vert.x)

I can't give a simple choose. You need understand trace and APIs.
