### ISSUE TITLE
OpenTracing support for version 0.32.0

### ISSUE THREAD

**Issue by vanjikumaran** [apache/skywalking#2569]
- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [X ] Requirement
- [ X] Feature or performance improvement

___
### Question
Currently based on the code Skywalking support 0.30.0 [1], however, on the new OpenTracing version 0.31.0 and 0.32.0  release there are multiple different changes made... especially BaseSpan and ActiveSpan are simplified into a single Span class and Scope replaces ActiveSpan. 

[1]
https://github.com/apache/skywalking/blob/master/apm-application-toolkit/apm-toolkit-opentracing/pom.xml#L31

- What happen?

Since the APIs are not backward compatibility on, Applications using the OpenTracing with the newest version not able to use the OpenTracing Extention of the Apache Skywalking and getting Caused by: java.lang.ClassNotFoundException: io.opentracing.ActiveSpan error.

**Comment by wu-sheng** [comment]
We don't support that as people(contributors) are more interesting in our auto-instrumentation agents. Few use OpenTracing, only some use OpenTracing API to adapt their business APIs, such as add some Local Spans only.

Could you tell me why you need the OT API?

We could accept the upgrade Pull Request, but I don't think any core team member(PMC or committer) is working on this.

**Comment by wu-sheng** [comment]
Even you use OT API, you are still talking to agent core directly. Meaning, you must make sure your way of using OT API is compatible with the mechanism of agent tracing context runs.

**Comment by vanjikumaran** [comment]
I am currently in the process for writing the [OT extension](https://github.com/ballerina-platform/ballerina-observability) for the integration network/integration programming called ballerina [[1]
](http://ballerina.io); The language support native OT support thus, I wanted to include the apache skywalking as a part of the extension available. Going forward, What is your recommendation? Using only the agent does not give the whole tracing feature that available OOB via ballerina.

[1] http://ballerina.io 
[2] https://github.com/ballerina-platform/ballerina-observability

**Comment by wu-sheng** [comment]
SkyWalking wouldn't provide SDK in short term, because no one really try to do and use that. Most tracing and observability should be able to be done by agent, because it is injecting tracing codes too. 
We are supporting most popular RPC frameworks.
> Using only the agent does not give the whole tracing feature that available OOB via ballerina.

Could you explain more about why does not support? What is the difference between ballerina and gRPC generation mechanism?

**Comment by wu-sheng** [comment]
With OT/OC merged, there is pointless to upgrade OT. If anyone has interests, consider playing with open telemetry.

**Comment by vanjikumaran** [comment]
Thanks @wu-sheng
