### ISSUE TITLE
Add support GraalVM

### ISSUE THREAD

**Issue by leotu** [apache/skywalking#2573]
Not found any documentation it could support  GraalVM
(https://www.graalvm.org/)
Recently I am working hard on Quarkus (https://quarkus.io), hope both Skywalking and Quarkus work togather well.

**Comment by wu-sheng** [comment]
What kind of support do you need?

**Comment by wu-sheng** [comment]
I am interesting in this, but never get my hand on that. So, i need your helps. 
We could take directly on slack too. If you want.

**Comment by flycash** [comment]
I am happy to help to provide this feature. But I need some help.
I look up the source code about monitoring Hotspot and want to take those code as a reference.
However, I didn't find any plugin named like 'jvm-plugin' or 'hotspot-plugin'.
Where can I find the code about monitoring the JVM?

**Comment by wu-sheng** [comment]
> Where can I find the code about monitoring the JVM?

What are these? Could you give me some examples?

**Comment by flycash** [comment]
Now we collect the GC and JVM heap information showed in the dashboard. I want to know where the code about collecting that information is.
I know that it was read from the GC log, is that right?

**Comment by wu-sheng** [comment]
`org.apache.skywalking.apm.agent.core.jvm.JVMService` collects the JVM/GC info. 

Pay attention to CPU/Memory/GC providers, they are JVM vendors related. If you try to build the test cases on those, you will see we may not support some JVM vendor, yet. But it is easy to extend.

**Comment by wu-sheng** [comment]
@flycash Any update about this VM?

**Comment by kezhenxu94** [comment]
I just tested on a Graal VM and the CPU/Memory/GC providers seem to work well without compatibility issue (see screenshot below), and this issue is rather stale, we'll close this if no further response from @leotu and @flycash 

![image](https://user-images.githubusercontent.com/15965696/66213546-9652e580-e6f2-11e9-80e2-769799fcacd6.png)

**Comment by wu-sheng** [comment]
Wait 72 hours for update.

**Comment by kezhenxu94** [comment]
Closing, feel free to comment here if you @leotu and @flycash have further information

**Comment by xiaozaiyuji** [comment]
> I just tested on a Graal VM and the CPU/Memory/GC providers seem to work well without compatibility issue (see screenshot below), and this issue is rather stale, we'll close this if no further response from @leotu and @flycash
> 
> ![image](https://user-images.githubusercontent.com/15965696/66213546-9652e580-e6f2-11e9-80e2-769799fcacd6.png)

How did you do this by GraalVM ? Do you test with spring native ?

**Comment by xiaozaiyuji** [comment]
> and this issue is rather stale, we'll close this if no further response from @leotu and @flycash

https://github.com/oracle/graal/issues/5912

> I just tested on a Graal VM and the CPU/Memory/GC providers seem to work well without compatibility issue (see screenshot below), and this issue is rather stale, we'll close this if no further response from @leotu and @flycash
> 
> ![image](https://user-images.githubusercontent.com/15965696/66213546-9652e580-e6f2-11e9-80e2-769799fcacd6.png)

@kezhenxu94 Can you help me to test with native-image? I get a explain from graal this is not support,by this https://github.com/oracle/graal/issues/5912

**Comment by xiaozaiyuji** [comment]
@wu-sheng  I think we should think about skywalking support for spring-native ,this is a challenge for us.I find this changed so much.

**Comment by wu-sheng** [comment]
There is no should or should not. If there isn't anyone to do, nothing happens.

**Comment by xiaozaiyuji** [comment]
> There is no should or should not. If there isn't anyone to do, nothing happens.

I will try to find it, If I find the solution，I will try to let skywalking support it.
