### ISSUE TITLE
ERROR: pull access denied for skywalking/oap, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by leighyu1983** [apache/skywalking#2575]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Bug

___
### Question
Bad support on docker
___
### Bug
- Which version of SkyWalking, OS and JRE?
Latest version 

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Error "ERROR: pull access denied for skywalking/oap, repository does not exist or may require 'docker login'", when installing skywalking using docker-compose up.

**Comment by wu-sheng** [comment]
Our images have been moved to apache.

- skywalking/base -> apache/skywalking-base
- skywalking/oap -> apache/skywalking-oap-server
- skywalking/ui -> apache/skywalking-ui
