### ISSUE TITLE
 How to monitor the specified http request

### ISSUE THREAD

**Issue by qq297910962** [apache/skywalking#2576]
I just want to monitor the specified http request, not all.What should I do?

**Comment by wu-sheng** [comment]
We don't have that in default. We monitot all, with exclusion rules.

**Comment by qq297910962** [comment]
Thank you for your reply.How is the exclusion rule used? I want to exclude eureka request

**Comment by wu-sheng** [comment]
Read agent deployment doc. There is ignore plugin there.
