### ISSUE TITLE
 If the amount of stored data is too large, it will affect query efficiency？

### ISSUE THREAD

**Issue by xjhuiw** [apache/skywalking#2577]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Can you clean up or expire some data if the amount of stored data is too large?

**Comment by wu-sheng** [comment]
TTL is provided, it will delete expired data automatically.
