### ISSUE TITLE
Http request consumption time is all 0ms

### ISSUE THREAD

**Issue by qq297910962** [apache/skywalking#2578]
![image](https://user-images.githubusercontent.com/39329230/57189451-8cf5ff00-6f41-11e9-93e7-047fb0ecbd98.png)

Why is the monitored http request consumption time 0ms?
In fact they can't be 0ms.
![image](https://user-images.githubusercontent.com/39329230/57189481-cd557d00-6f41-11e9-95af-fc3ae0e3d919.png)
But the time monitored by jdbc is normal.
What is the reason？

**Comment by wu-sheng** [comment]
I think you have to debug the codes by yourself. I don't know why.
