### ISSUE TITLE
print error while startup: "java.lang.ArithmeticException: / by zero"

### ISSUE THREAD

**Issue by xiaoni157** [apache/skywalking#2581]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.0.0-GA
ES ali cloud 6.3.2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

![image](https://user-images.githubusercontent.com/24448049/57190874-faaa2700-6f51-11e9-9e14-dc2b010da56a.png)

**Comment by wu-sheng** [comment]
I think you delete the storage, but the agent has not restarted.

**Comment by xiaoni157** [comment]
Does that mean all my projects need to be restarted?

**Comment by wu-sheng** [comment]
For now, Yes.

**Comment by xiaoni157** [comment]
OK,Let me try.
