### ISSUE TITLE
database

### ISSUE THREAD

**Issue by tanheping** [apache/skywalking#2585]
Hello, I 'm using skywalking v6.1
I don't have a database for this service
As shown below:
![image](https://user-images.githubusercontent.com/17920353/57192075-1a941780-6f5f-11e9-9592-c753f2c74107.png)

**Comment by wu-sheng** [comment]
Database is a different dashboard.

**Comment by wu-sheng** [comment]
Database is not a service.

**Comment by tanheping** [comment]
What does this value mean

**Comment by wu-sheng** [comment]
There is a database dashboard in your page, the database is there
