### ISSUE TITLE
The time shown in Trace page, is incorrect

### ISSUE THREAD

**Issue by liuqinyu88** [apache/skywalking#2586]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please provide which part is incorrect?

**Comment by liuqinyu88** [comment]
![%BKMPK%9AQ% 36L92}7K7HT](https://user-images.githubusercontent.com/50103321/57192611-f804fd00-6f64-11e9-80bd-7ce53633e1c8.png)
获取的结果集跟我筛选的不一致

**Comment by liuqinyu88** [comment]
![%BKMPK%9AQ% 36L92}7K7HT](https://user-images.githubusercontent.com/50103321/57192897-37811880-6f68-11e9-9e42-6d8e673484af.png)
The time of the result set is inconsistent with the time of my filtering

**Comment by wu-sheng** [comment]
That ref to #2560 . When your time in agent, oap and browser are not same, this happens. If you feel interests, could join that one

**Comment by wu-sheng** [comment]
I rechecked the #2560 , this is just a UI bug. @TinyAllen 

This time should be formatted based on selected UTC time in query condition.

**Comment by wu-sheng** [comment]
Fixed in UI
