### ISSUE TITLE
about cluster setting zookeper

### ISSUE THREAD

**Issue by Stephen-sen** [apache/skywalking#2588]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
from document I see I can use zookeper manager skywalking cluster。I also config it。but I 
 still didn't undstand what is work. what is the difference between skywalking and load balancing.
if I want it's work in  load balancing,shoud I config nginx or some other tool？
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Cluster management is for backend running in cluster mode. Load balance is not its design goal. Use envoy, nginx or other lb.

**Comment by Stephen-sen** [comment]
what you mean is when one node Downtime，other node still can provide services? but Each node can provide services regardless of whether the cluster is configured or not. so I want to known cluster‘s Effect。

**Comment by wu-sheng** [comment]
No, that is load balance responsibilities, oap cluster management is for inside communication. Oap node needs to talk with each other.
