### ISSUE TITLE
v6.1  Exist cycle module dependencies

### ISSUE THREAD

**Issue by qq297910962** [apache/skywalking#2591]
![image](https://user-images.githubusercontent.com/39329230/57195528-4d053b00-6f86-11e9-953b-e7936b8b3923.png)
Version changed to 6.1.
Today apache just updated the download package.
The above error occurred when I started it.
What is the reason？

**Comment by wu-sheng** [comment]
You are using the old setting file to start 6.1

**Comment by qq297910962** [comment]
Thank you very much for answering this fast.I successfully started.
But I still have a question I would like to ask you. Will the elasticsearch data used in my previous version affect the current version?
Should I clear the previous ES data?
