### ISSUE TITLE
Docker and K8s settings for 6.1

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#2592]
- https://github.com/apache/skywalking-docker
- https://github.com/apache/skywalking-kubernetes

**Comment by wu-sheng** [comment]
Docker provided. https://github.com/apache/skywalking-docker/tree/master/6/6.1

**Comment by hanahmily** [comment]
k8s https://github.com/apache/skywalking-kubernetes/tree/master/helm-chart/6.1.0
