### ISSUE TITLE
How to identify a span failure？

### ISSUE THREAD

**Issue by huangpang** [apache/skywalking#2599]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question

How to identify a span failure？

I used opentracing to create a custom span

But I haven't found a way to set the state.

I tried several ways, but none of them worked.
version: 6.0.0-GA
```
        span.setTag("error",true);
        span.setTag("isError",true);

        org.apache.skywalking.apm.toolkit.trace.ActiveSpan.tag("is error","true");
        org.apache.skywalking.apm.toolkit.trace.ActiveSpan.tag("isError","true");
```
![微信图片编辑_20190506134730](https://user-images.githubusercontent.com/31001984/57208683-b5483100-7007-11e9-90c5-b9523abbc10d.jpg)

**Comment by wu-sheng** [comment]
Error is an API for agent. `ActiveSpan#tag` doesn't support to do that. 
If you want that, try to contribute
1. Add `ActiveSpan#error`in toolkit
1. Call `AbstractSpan#errorOccurred` in the toolkit activation.

**Comment by huangpang** [comment]
Because we're trying to associate the system with skywalking.

The realization of this function is expected.

Thank you

**Comment by wu-sheng** [comment]
You could work on this and submit a new pull request. We will be glad to review and help you merge into the main codebase.

**Comment by wu-sheng** [comment]
@huangpang New APIs provided.
