### ISSUE TITLE
the number of span is always 9

### ISSUE THREAD

**Issue by zxbu** [apache/skywalking#2600]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
SkyWalking version: 6.1

- What happen?
The number of span at Rocketbot trace page is always 9
![pic](https://user-images.githubusercontent.com/32785355/57208759-0526f800-7008-11e9-9359-9c476849450c.jpg)

**Comment by wu-sheng** [comment]
Yes, see #2582 . Will be fixed and pull request is welcome.
