### ISSUE TITLE
why my custom agent plugin has no compile in skywalking-agent/plugins directory

### ISSUE THREAD

**Issue by liucyu** [apache/skywalking#2603]
### Question
I wrote a custom plugin. When I compiled it, I could see my plugin information in the output log, but I didn't find the corresponding jar package under the directory. Here are the steps I took to write the plugin
![image](https://user-images.githubusercontent.com/13191643/57211073-8f278e80-7011-11e9-8ddd-fc86d73088ec.png)
![image](https://user-images.githubusercontent.com/13191643/57211109-a9fa0300-7011-11e9-94a8-b7fb252f67c5.png)
![image](https://user-images.githubusercontent.com/13191643/57211121-b5e5c500-7011-11e9-8654-9340d79482b4.png)
![image](https://user-images.githubusercontent.com/13191643/57211141-c9912b80-7011-11e9-8592-94959fc05f96.png)
![image](https://user-images.githubusercontent.com/13191643/57211156-d44bc080-7011-11e9-9353-8f81448bac08.png)
![image](https://user-images.githubusercontent.com/13191643/57211180-efb6cb80-7011-11e9-8e9f-2076daf6a067.png)
What should I do to be correct?

**Comment by wu-sheng** [comment]
I am not sure. I only could suggest checking pom.xml between yours and SkyWalking existing plugins.
Jar is copied based on pom.xml setting.

**Comment by liucyu** [comment]
I also can not find the ./dist directory on my project when i compiled the project
![image](https://user-images.githubusercontent.com/13191643/57212585-c482ab00-7016-11e9-9ee2-b8d55c342d25.png)

**Comment by wu-sheng** [comment]
I am confusing too....from your logs, I even can't see dist module active.

**Comment by liucyu** [comment]
When I execute the `mvn compile -Dmaven.test.skip=true` command, it fails, but when it is replaced with `mvn package -Dmaven.test.skip=true`, it works

**Comment by wu-sheng** [comment]
Compile means compiling source codes, that is all. Package means generating the dist tar. These are maven definitions, in all Java projects.

**Comment by liucyu** [comment]
yes ，i copied it from the Internet without looking at it.
