### ISSUE TITLE
When backEnd stop , application trigger outOfMemory

### ISSUE THREAD

**Issue by likeonechild** [apache/skywalking#2604]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [1] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0.0-GA
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
When backEnd stop , application outofMemory
___
![1557125683](https://user-images.githubusercontent.com/19264156/57211227-1d9c1000-7012-11e9-9a02-3edb881c742e.png)
![1557125699(1)](https://user-images.githubusercontent.com/19264156/57211287-49b79100-7012-11e9-9f1e-de909a19b4da.png)
![1557125725(1)](https://user-images.githubusercontent.com/19264156/57211296-50460880-7012-11e9-9acd-95138472e135.png)

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
There is a buffer cache in agent, so, you need to make sure at least there is enough memory space for it. Or, you could set the buffer size smaller. 37M shouldn't trigger OOM.
