### ISSUE TITLE
dashboard page data

### ISSUE THREAD

**Issue by WinsonOne** [apache/skywalking#2614]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- at first,I can see Calls HeatMap,Response Time chart data in dashboard when the time range Last 15 minutes,but with more service upload trace data,I can't see the last 15 minutes data

**Comment by wu-sheng** [comment]
Check your ElasticSearch and OAP server, whether they have a performance issue.

**Comment by WinsonOne** [comment]
thx
