### ISSUE TITLE
Topology node type error 

### ISSUE THREAD

**Issue by mbao** [apache/skywalking#2617]
- Why do you submit this issue?
- [ ] Question or discussion

___
### Question

Topology node type error.
 Node type is set by componentId of the  last serviceRelationServerCall  has the same  target sequence    in   TopologyBuilder.build method. When the node is a rabbitMQ consumer and sequence of rabbitMQ service has a large start such as 9, serviceRelationServerCall ,of which the componentId is 53, is likely to be the last  serviceRelationServerCall. The node type will be rabbitmq-consumer and shown as unknown in  topology. I think this serviceRelationServerCall should be filtered.

**Comment by wu-sheng** [comment]
What do you mean a large start? I am not following.

**Comment by mbao** [comment]
> What do you mean a large start? I am not following.

When using Mysql, serviceRelationServerCalls is sorted by entity_id as a result of group by.
So  entity_id sorted like 0xxxx 1xxxx 2xxx ...9xxx.
![image](https://user-images.githubusercontent.com/866459/57271985-1df4e380-70c4-11e9-8a2a-7022746de9fa.png)

**Comment by wu-sheng** [comment]
Then? Why sort affect the result?

**Comment by mbao** [comment]
> Then? Why sort affect the result?
`if (nodes.containsKey(target.getSequence())) {
                nodes.get(target.getSequence()).setType(componentLibraryCatalogService.getComponentName(serverCall.getComponentId()));
            }`
In build method of TopologyBuilder,  last of  sorted serviceRelationServerCalls is used to get the Type.
Maybe  it is enough just to say componentId such like 53(rabbitmq-consumer) should not be used to set the node type.  Other words just describe the condition I came across.

**Comment by wu-sheng** [comment]
If your concern is `componentId`, you could follow #2534 . Component id is going to be removed in the future. `source + dest` will be the entity id only.

The number of componentId represents nothing, it is just based on the contribution sequence. So logic should not base on that.
