### ISSUE TITLE
doc_Trace Data Protocol v2_error

### ISSUE THREAD

**Issue by coki230** [apache/skywalking#2620]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Bug
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.x
- Which company or project?
doc
- What happen?
the doc of "Trace Data Protocol v2", i was confused by the sentence of "After you have trace id and trace instance id, you could send traces and metric. Now we have".
i think it may be "After you have service id and service instance id, you could send traces and metric. Now we have"

**Comment by wu-sheng** [comment]
Yes, please send a pull request to fix it.

**Comment by coki230** [comment]
ok
