### ISSUE TITLE
A problem with cluster mode

### ISSUE THREAD

**Issue by xiaoni157** [apache/skywalking#2624]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What does port 12800 do? Can agent connect directly to port 12800?
If not, in cluster mode, the agent directly connected to port 11800 needs to set up each collector, which is unfriendly to adding new collectors.
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.0.0-GA
ES ali cloud 6.3.2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
agent.config:
![image](https://user-images.githubusercontent.com/24448049/57286611-32e36e00-70e8-11e9-9262-c799e11049f6.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> What does port 12800 do? Can agent connect directly to port 12800?

Why connect 12800? In 6.x, we connect gRPC port directly. rest is for UI.

> If not, in cluster mode, the agent directly connected to port 11800 needs to set up each collector, which is unfriendly to adding new collectors.

You have a lot of load balance tools, SkyWalking don't want to build it, and you don't need us to do so.
Deploy Envoy, Nginx or any load balance which supports HTTP2/gRPC.

**Comment by xiaoni157** [comment]
GRPC port 11800 12800 is http2 port?

**Comment by wu-sheng** [comment]
gRPC is HTTP2, rest is HTTP1.

**Comment by xiaoni157** [comment]
ok,thanks.
