### ISSUE TITLE
IDs can't be null???

### ISSUE THREAD

**Issue by swhr0903** [apache/skywalking#2627]
skywalking6.1 

2019-05-07 18:23:59,851 - graphql.execution.SimpleDataFetcherExceptionHandler -592294 [qtp1377160602-47] WARN  [] - Exception while fetching data (/cpm) : IDs can't be null
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | java.lang.RuntimeException: IDs can't be null
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.apache.skywalking.oap.server.core.query.MetricQueryService.getValues(MetricQueryService.java:61) ~[server-core-6.1.0.jar:6.1.0]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.apache.skywalking.oap.query.graphql.resolver.MetricQuery.getValues(MetricQuery.java:53) ~[query-graphql-plugin-6.1.0.jar:6.1.0]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.apache.skywalking.oap.query.graphql.resolver.MetricQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:6.1.0]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar:?]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) [graphql-java-8.0.jar:?]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) [graphql-java-8.0.jar:?]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at graphql.execution.Execution.executeOperation(Execution.java:158) [graphql-java-8.0.jar:?]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at graphql.execution.Execution.execute(Execution.java:100) [graphql-java-8.0.jar:?]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at graphql.GraphQL.execute(GraphQL.java:558) [graphql-java-8.0.jar:?]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) [graphql-java-8.0.jar:?]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at graphql.GraphQL.executeAsync(GraphQL.java:470) [graphql-java-8.0.jar:?]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at graphql.GraphQL.execute(GraphQL.java:401) [graphql-java-8.0.jar:?]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.execute(GraphQLQueryHandler.java:87) [query-graphql-plugin-6.1.0.jar:6.1.0]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.apache.skywalking.oap.query.graphql.GraphQLQueryHandler.doPost(GraphQLQueryHandler.java:81) [query-graphql-plugin-6.1.0.jar:6.1.0]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:54) [library-server-6.1.0.jar:6.1.0]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:101) [library-server-6.1.0.jar:6.1.0]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:105) [library-server-6.1.0.jar:6.1.0]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
apm_skywalking_oap01.1.js7529nm5uvk@clnt-app-1    | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by wu-sheng** [comment]
@swhr0903 Could you describe how this happens? 

@TinyAllen I think this is a UI bug.

**Comment by swhr0903** [comment]
不好意思，我的英文不是很好，我还是用中文描述吧

我用的是skywalking6.1，两个oap节点，zookeeper用的3.4.14,es用的6.5，两个master/data节点，两个client节点，oap接入client节点，跑在docker swarm下

跑起来后就时不时抛出以上错误，页面上刷新一下有数据，一下没有数据

**Comment by wu-sheng** [comment]
I think you need to check the performance of ElasticSearch. Usually, ElasticSearch cost more CPU then OAP server.

My guess, you can't get the metadata(service/service instance/endpoint) list, then when query metric happens, this exception happens.

**Comment by zhangwenliang012** [comment]
你好，这个问题解决了吗，我也遇见了

**Comment by swhr0903** [comment]
没有，我想应该不是es的问题，我的es接入了logstash和kibana都很正常

**Comment by gledsonrabelo** [comment]
Same problem here too :(

**Comment by wu-sheng** [comment]
I have explained many times, then again, this error doesn't harm anything. This is just UI query data without checking some conditions. No need to worry. If someone has time, could find out which query has this issue and fix it.
