### ISSUE TITLE
[help wanted] is there a way to make agent delete the OLD log files?

### ISSUE THREAD

**Issue by polaris952** [apache/skywalking#2633]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does skywalking has logging configuration item such as log4j 'MaxBackupIndex' to make it delete the OLD log files?
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywaling 6.0GA under Ubuntu
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We don't have this. Contribution is welcome.

**Comment by polaris952** [comment]
> We don't have this. Contribution is welcome.

thank  you for your reply, is it possible to simply disable agent logging?

**Comment by wu-sheng** [comment]
Read the agent setup document.

**Comment by polaris952** [comment]
> Read the agent setup document.

I went through the setup docs, seems there is nothing mentioned about disable log output.
