### ISSUE TITLE
6.1版本拓扑图不显示

### ISSUE THREAD

**Issue by yedong7018** [apache/skywalking#2639]
![Upload
![TIM图片20190509154803](https://user-images.githubusercontent.com/45445126/57436235-e1ff8100-7271-11e9-81e9-9f3a344149dd.png)
ing TIM图片20190509154754.png…]()

**Comment by wu-sheng** [comment]
English only. And we need detail

**Comment by yedong7018** [comment]
![1](https://user-images.githubusercontent.com/45445126/57436413-360a6580-7272-11e9-876a-ffb3b90e875f.png)
![2](https://user-images.githubusercontent.com/45445126/57436421-39055600-7272-11e9-98ed-0356eea00cba.png)

**Comment by wu-sheng** [comment]
@TinyAllen Do you know why trigger this?
