### ISSUE TITLE
Question Regarding Skywalking UI Usage

### ISSUE THREAD

**Issue by indraneelbaronia** [apache/skywalking#2642]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I am working on my final year project and have my dataset ready. My dataset is consists of server metrics like cpu_usage, byte_written, byte_read etc in csv format . Is it possible to use just the Skywalking UI to visualize the data from my dataset ? If so please point me in the right direction.
Thanks in advance.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> I am working on my final year project and have my dataset ready. My dataset is consists of server metrics like cpu_usage, byte_written, byte_read etc in csv format . Is it possible to use just the Skywalking UI to visualize the data from my dataset ? If so please point me in the right direction.
Thanks in advance.

If this is your direction, I prefer you to give kibana or grafana a try. Those are much easier tools to do this. Hope this helps.
