### ISSUE TITLE
SkyWalkingUI: page /trace  has a conflict with actuator's api

### ISSUE THREAD

**Issue by KAMIJYOUDOUMA** [apache/skywalking#2646]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- The UI has a page /trace,and the actuator has an api with the same path.When I refresh the page,something wrong will happen.How about renaming the trace page?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Fixed.
