### ISSUE TITLE
mongo-java-driver-3.8.2

### ISSUE THREAD

**Issue by rainleon** [apache/skywalking#2649]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is this mongo version supported?
```
<dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.8.2</version>
        </dependency>
```
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking:6.1.0, OS centos7 and JRE 1.8.131?
- Which company or project?
tongdao financial.
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
With 3.8.2 mongo-java-driver, agent not work.Is this supported ?

```
<dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.8.2</version>
        </dependency>
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

How to avoid this?

**Comment by wu-sheng** [comment]
We have just tested 3.4-3.6 mongodb, according to this. https://github.com/SkyAPMTest/agent-integration-test-report#mongodb

I think the driver lib updates. 

@rainleon we are welcome you to contribute fix to support high versions

**Comment by rainleon** [comment]
Yeah,get it . I will try it later. Also this link: https://github.com/SkyAPMTest/agent-integration-test-report#mongodb is very helpful, but is not easy to find . 😄

**Comment by wu-sheng** [comment]
@rainleon Yes, as project covers tracing, APM and service mesh observability, document tree is a little deep.

**Comment by dasonXu** [comment]
hi do you solve this question? the plugin use mongo-driver version is 3.4.2, i find the difference bteween 3.8.2 and 3.42 ,the plugin is intercepted the method of Mongo.Class ,but is was removed is 3.8.2 ,and the new version use an inner class to operate the mongo ,it is hard to create a proxy class

**Comment by wu-sheng** [comment]
@dasonXu Inner class is definitely possible to intercept. Would you like to send a pull request to support new versions? You could find the real class name of that inner class in jar, usually including `AClass$InnerClass`.

**Comment by dasonXu** [comment]
thanks for your tip,i'll try
