### ISSUE TITLE
I added A hessian plugin, and the UI shows Component:N/A?

### ISSUE THREAD

**Issue by xiaoni157** [apache/skywalking#2650]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I added A hessian plugin, and the UI shows Component:N/A?
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.0.0-GA
ES ali cloud 6.3.2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
I define a OfficialComponent and then reference it.
![image](https://user-images.githubusercontent.com/24448049/57502126-e03ec780-731c-11e9-8466-b167a47b2f6c.png)
![image](https://user-images.githubusercontent.com/24448049/57502131-e59c1200-731c-11e9-964f-de15e0aa613c.png)
![image](https://user-images.githubusercontent.com/24448049/57502214-49263f80-731d-11e9-83f3-5bfa052c67e9.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
SkyWalking doesn't provide an official hessian plugin.

**Comment by xiaoni157** [comment]
I know, I wrote it myself, and then I can't show it in the call chain

**Comment by wu-sheng** [comment]
Read the plugin development guide, there is a paragraph to tell you how to set up component-libraries.yml, this is based on that.

**Comment by xiaoni157** [comment]
Okay, I did it. Thank you
