### ISSUE TITLE
Improve Zipkin<->SkyWalking integration

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#2653]
Today's analysis process, in the easy scenario, really could transfer spans to SkyWalking trace. We used to demo it. Such as

- https://twitter.com/adrianfcole/status/1007625470886567936

I am welcome to have a deeper discussion on improving this feature. But please notice, as an APM, we have less flexible in span tags and the spans of each trace. Meaning, if you want to have the SkyWalking topology, metrics, and alarm, you need to have logically the same raw data.

Right now, the major issues of Zipkin receiver, not production ready are
1. Cluster mode is not supported. Because Zipkin sends trace through span by span. But the whole analysis needs the whole trace to build SkyWalking segments. One segment means all spans of one trace in one process(or thread). But in `ZipkinSkyWalkingTransfer#doTransfer`, it uses `CacheFactory.INSTANCE`, which use `CaffeineSpanCache` to cache the span with timeout mechanism. The `CaffeineSpanCache` use memory cache. In production and cluster mode, this cache should be a distributed cache env, and each trace timeout should be controlled by one OAP instance. Such as always let the OAP instance, who received the root span, to process the timeout and analysis the whole trace.
2. `CaffeineSpanCache#onRemoval` is the entrance based on timeout to assume the whole trace has been received, which could begin to analysis in `Zipkin2SkyWalkingTransfer`. The transfer process in `SegmentBuilder#build` including the complex steps, which I am not sure ready and suitable for everyone.

I think you have read https://github.com/SkyAPM/zipkin-skywalking , actually, that document is wrote by me and @adriancole back to the back we were building this feature as step one.

So, you need to fix the above two issues.

Also, when we came into SkyWalking 6.x, we have a better solution than analysis of the whole trace. 

The following suggestion should have better performance in trace analysis, but you need to understand SkyWalking more.
When `needAnalysis=false` today, the trace/span have been saved in storage already, and query has been supported. So, the things we left are topology and metrics, these two actually are the same thing. **Build scopes**. You could read `MultiScopesSpanListener#parseEntry`, `MultiScopesSpanListener#parseExit` and `MultiScopesSpanListener#build`. Especially the `#build` method. If you have read SkyWalking OAL document, you should know, SkyWalking analysis core receives the scopes. 
In Zipkin receiver, we could only process span having `remoteEndpoint`, matching the client span <-> server span, instead of building the whole trace. Build the service, service instance, endpoint and relationship scopes. This could significantly reduce the memory cost of distributed cache in issue(1). But you still need that the cache.

**Comment by tmichnik1981** [comment]
I found some inconsistency regarding Zipkin spans. 
I am testing with a setting `needAnalysis=true`. I see that tracing is not visible.
It turned out skywalking queries   index **zipkin_span** which is empty.

On the other hand, when needAnalysis=false, `org.apache.skywalking.oap.server.receiver.zipkin.trace.SpanForward#send` is called and spans are being saved to  **zipkin_span**.

Should  **zipkin_span** be populated with spans or we should rather query some other index when browsing tracing?

I see that in `org.apache.skywalking.oap.server.core.query.TraceQueryService` a decision is made which DAO to load. Of course in my case Zipkin storage is on so `org.apache.skywalking.oap.server.storage.plugin.zipkin.elasticsearch.ZipkinTraceQueryEsDAO` is loaded.

```
   private ITraceQueryDAO getTraceQueryDAO() {
        if (traceQueryDAO == null) {
            this.traceQueryDAO = moduleManager.find(StorageModule.NAME).provider().getService(ITraceQueryDAO.class);
        }
        return traceQueryDAO;
    }
```

**Comment by wu-sheng** [comment]
I think this is a wrong description in document, when I submit span storage implementation. If analysis is true, there is no need to switch to zipkin elasticsearch, keep as elasticsearch.

**Comment by wu-sheng** [comment]
I think this is a wrong description in document, when I submit span storage implementation. If analysis is true, there is no need to change storage.

**Comment by adriancole** [comment]
I could understand this description easily. nice

**Comment by tmichnik1981** [comment]
Hi,
We have a problem with relations between particular spans.
I my scenario a tracing consists of 3 spans: 2 CLIENT kind, 1 SERVER kind.

Calls tree looks like that: 1 client span (id=74a5bdd765145dd2) -->  2 client span (id=76b8e4cf36177665, parent=74a5bdd765145dd2) -->  3 server span (id=d6762f661eb4de16, parent=76b8e4cf36177665).

In Zipking server, spans are presented correctly whilst in Skywalking, CLIENT spans are not connected to each other.
root --> 1 client span (id=74a5bdd765145dd2)
root --> 2 client span (id=76b8e4cf36177665, parent=74a5bdd765145dd2) --> 3 server span (id=d6762f661eb4de16, parent=76b8e4cf36177665)
 
I believe I found a suspicious piece of code. In `org.apache.skywalking.oap.server.receiver.zipkin.analysis.transform.SegmentBuilder#initSpan`
there is a switch which assumes that there might be built a reference only when  **SERVER** span arrives:
```
 switch (kind) {
            case CLIENT:
                spanBuilder.setSpanType(SpanType.Exit);
                String peer = getPeer(parentSpan, span);
                if (peer != null) {
                    spanBuilder.setPeer(peer);
                }
                clientSideSpan = new ClientSideSpan(span, spanBuilder);
                clientPartSpan.put(span.id(), clientSideSpan);
                break;
            case SERVER:
                spanBuilder.setSpanType(SpanType.Entry);
                this.buildRef(spanBuilder, span, parentSegmentSpan, parentSpan);
                break;
            case CONSUMER:
                spanBuilder.setSpanType(SpanType.Entry);
                this.buildRef(spanBuilder, span, parentSegmentSpan, parentSpan);
                break;
            case PRODUCER:
                spanBuilder.setSpanType(SpanType.Exit);
                peer = getPeer(parentSpan, span);
                if (peer != null) {
                    spanBuilder.setPeer(peer);
                }
                clientSideSpan = new ClientSideSpan(span, spanBuilder);
                clientPartSpan.put(span.id(), clientSideSpan);
                break;
            default:
                spanBuilder.setSpanType(SpanType.Local);
        }
```
[sample-tracing-1.txt](https://github.com/apache/skywalking/files/3181511/sample-tracing-1.txt)

![skywalking-ui-1](https://user-images.githubusercontent.com/4050114/57758728-a8f36080-76f8-11e9-91c4-f4ab26b87d8a.png)
![zipkin-server-ui-1](https://user-images.githubusercontent.com/4050114/57758740-b0b30500-76f8-11e9-9759-9dfaec44bee5.png)

**Comment by wu-sheng** [comment]
One client span is a parent of another client span? I definitely was expecting this happens. SkyWalking segments expect, exit span(client) always matches entry span(server), and for an RPC, only one exit and one entry.

**Comment by tmichnik1981** [comment]
But how to handle a case when within application A we may have a couple of steps and each step (component) generate its own span and finally one of them will generate a http request to application B?

component A (app A) -> component B (app A) -> component C (app A) -> http GET -> component A (app B)

Is it possible possible to generate the correct relations and present a tree on Tracing tab (Gui)?

**Comment by wu-sheng** [comment]
In the current analysis codes, I will say it is hard. Transfer zipkin span to SkyWalking segment has too many limits. That is why I submit the `no-analysis` mode. 

In my mind, I prefer to build new analysis codes based on `no-analysis` mode, meaning, still saving span directly, and build the trace only in query stage. Becaust at that moment, no need to worry about client/server side spans, just build trace segment and segment ref. And only require client/server matching to do analysis, in your case, only try to identify these two spans(`component C (app A) -> http GET -> component A (app B)`), then metrics are generated by these two.

By the way, in SkyWalking native format and agent, we don't need to process this, we will merge component A->C(if they are all RPC client library instrumentations) automatically. We call it StackBasedSpan.

If you want to quick deep dive talk, Join #skywalking channel at [Apache Slack](https://join.slack.com/t/the-asf/shared_invite/enQtNDQ3OTEwNzE1MDg5LWY2NjkwMTEzMGI2ZTI1NzUzMDk0MzJmMWM1NWVmODg0MzBjNjAxYzUwMjIwNDI3MjlhZWRjNmNhOTM5NmIxNDk)

**Comment by tmichnik1981** [comment]
Hi,

So basically you are suggesting, to switch off analyzing  (**needAnalysis=true**) and of course to set up storage to  **zipkin-elasticsearch** and to rely on results of `org.apache.skywalking.oap.server.storage.plugin.zipkin.elasticsearch.ZipkinTraceQueryEsDAO`?

This will work but in the same we are losing other extra features like Topology. Am I right?

**Comment by wu-sheng** [comment]
> This will work but in the same we are losing other extra features like Topology. Am I right?

Yes. That is the part we should build, to replace the current one. Are you interested in deep dive in this about how to generate topology and metrics based on Zipkin spans? I have basic ideas, but there are coding and testing stuff need to be done.

**Comment by Duncan-tree-zhou** [comment]
Hi,
I am interesting with this enhancement because i am working on the AMP service for our application, and it build up with internal framework which had zipkin reporter native code. Tell me if there are something i can help, and which is helping myself.

**Comment by wu-sheng** [comment]
@Duncan-tree-zhou I have list them in this issue. We could discuss more details if you have some questions.

**Comment by Duncan-tree-zhou** [comment]
@wu-sheng here are my questions:
1. how many ways we can solve this problem.
  - for my understanding, to compose and transform zipkin traces into skywalking segments is the way with least modification.
  - are there any other way to implement the enhancement?
2. if we chose a way, how many functionalities we should implement to complete the integration.
  - let's say to transform the zipkin format to segments. We should implement a transformer. Is it enough to make work? 
3. what is the prolems and primary concerns ( in different dimension and details) to implement the functionalities?
  - let's say to implement the transformer. how may attrs zipkin format has and how may attrs sykwalking format has. how to map the attrs. Maybe we can draw a table to the maping and find out like which attrs are required but zipkin format not provided etc.

**Comment by wu-sheng** [comment]
> for my understanding, to compose and transform zipkin traces into skywalking segments is the way with least modification.

We could save Zipkin trace by using span based, rather than segment of SkyWalking. I have implemented it, which is much friendly to Zipkin. Read this, https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#elasticsearch-6-with-zipkin-trace-extension

The reason I proposed this, is Zipkin trace can't transfer to SkyWalking segments perfectly. That is why we put in the document, analysis is not production ready.

> are there any other way to implement the enhancement?

The most important enhancement are analysis metrics from zipkin span. This means, match zipkin client-server span and generated SkyWalking scopes(Service, ServiceRelation, etc.), like `SourceBuilder` used by `MultiScopesSpanListener`.

> let's say to transform the zipkin format to segments. We should implement a transformer. Is it enough to make work?

This may be not necessary.

> what is the prolems and primary concerns ( in different dimension and details) to implement the functionalities?

I think mostly is in OAP cluster mode. Zipkin spans of a trace could be sent to the different instances in an uncertain time, so, we need to make client/server match perfectly.  Such as using Redis Cluster to be central cache?(Maybe only)

**Comment by Duncan-tree-zhou** [comment]
> The most important enhancement are analysis metrics from zipkin span. This means, match zipkin client-server span and generated SkyWalking scopes(Service, ServiceRelation, etc.), like SourceBuilder used by MultiScopesSpanListener.

for my understanding, zipkin reporter did not collect metrics information(since zipkin did not support to collect matrics data).  if you have no hand you can't make a fist. so i think maybe you can recomend users to use a matrix agent to collection the matrix data?

> I think mostly is in OAP cluster mode. Zipkin spans of a trace could be sent to the different instances in an uncertain time, so, we need to make client/server match perfectly. Such as using Redis Cluster to be central cache?(Maybe only)

I am not understanding that if SW had save the zipkin spans in db(like es). why a central cache is needed? why the storage can't be the data central?

**Comment by Duncan-tree-zhou** [comment]
And I am trying to implement the SW agents for components of our framework . They remake many wheels like the Driver/rpc/webdispatcher etc. It looks like that to implement agents is the easier way to work out. The Skywalking agent SDK is really very good.

**Comment by wu-sheng** [comment]
> for my understanding, zipkin reporter did not collect metrics information(since zipkin did not support to collect metrics data). if you have no hand you can't make a fist. so i think maybe you can recomend users to use a metrics agent to collection the metrics data?

I mean analysis metrics from traces, like we did from SkyWalking traces. We just don't have JVM.

> I am not understanding that if SW had save the zipkin spans in db(like es). why a central cache is needed? why the storage can't be the data central?

Save as above, I was talking about `analysis metrics from Zipkin trace`.

> And I am trying to implement the SW agents for components of our framework . They remake many wheels like the Driver/rpc/webdispatcher etc. It looks like that to implement agents is the easier way to work out. The Skywalking agent SDK is really very good.

In most cases, I think agent plugin should be much better, and have better performance.

**Comment by Duncan-tree-zhou** [comment]
> I mean analysis metrics from traces, like we did from SkyWalking traces. We just don't have JVM.
Are there any articles or docs to discrip how Skywalking analysis the metrics of traces in cluster mode?

**Comment by wu-sheng** [comment]
> Are there any articles or docs to discrip how Skywalking analysis the metrics of traces in cluster mode?

No, I am afraid. But in the short version, SkyWalking has special header and segment formats, very different with Zipkin span based. It is designed particularly for APM, rather than tracing. 
I think you can't learn from those about how to analysis Zipkin span. `MultiScopesSpanListener` to `SourceBuilder` is still the best refer. You need to analysis spans, and get all Scopes of SkyWalking, and send them OAL engine. This feature requires clear understanding of what is SkyWalking OAP and OAL scripts.

**Comment by yangyshdan** [comment]
Hi, I just came across this interesting issue, because we are hitting this problem when we are evaluating Skywalking for our production environment for the zipkin client.  

I think the core problem is that, in the distributed OLA envirnoment, one single OLA needs to collect all the span information in order to calculate the segment informatoin. I have a draft work-around idea, and would like to discuss here. 

Lets say, we put a Kafka broker in the middle of zipkin and skywalking OLA, and all span informaiton with the same traceid is routed to the same partitoin of the Kafka topic, and all the messages of one particular partition will be delivered to the same OLA node. Will this solution solve the problem in certain degree?  Dear @wu-sheng, looking forward for your response. Thanks.

**Comment by wu-sheng** [comment]
> Will this solution solve the problem in certain degree?

I wouldn't recommend to do that. Because, if you dig a little deeper, you will find there is another issue, which is the Zipkin span could include optional tags. Meaning, you can't guarantee the segment built successfully.

I think I have proposed the design, you could build OAL Source(s) from Zipkin spans directly, about how to built that, I recommend Redis or Kafka(MQ) to find the client/server span match. You don't need the whole segment and trace.

Then for trace details, using current SkyWalking ElasticSearch Zipkin storage.

Look forward we could do this in this repo.

**Comment by yangyshdan** [comment]
> > Will this solution solve the problem in certain degree?
> 
> I wouldn't recommend to do that. Because, if you dig a little deeper, you will find there is another issue, which is the Zipkin span could include optional tags. Meaning, you can't guarantee the segment built successfully.
> 
> I think I have proposed the design, you could build OAL Source(s) from Zipkin spans directly, about how to built that, I recommend Redis or Kafka(MQ) to find the client/server span match. You don't need the whole segment and trace.
> 
> Then for trace details, using current SkyWalking ElasticSearch Zipkin storage.
> 
> Look forward we could do this in this repo.

Thanks for the reply. I am a little confused . From what you described earlier: "I think mostly is in OAP cluster mode. Zipkin spans of a trace could be sent to the different instances in an uncertain time, so, we need to make client/server match perfectly. Such as using Redis Cluster to be central cache?(Maybe only)", I think you have implemented most of the feature. The only thing left behind is how to gurantee that all the span information are sent to the same OAP node? If so, then yes we can focus on thinking about how to implement this one.

**Comment by wu-sheng** [comment]
> Such as using Redis Cluster to be central cache?(Maybe only)"

Maybe, but I think only RPC related span should be cached. The most important thing is, how do you prepare to make match happen. The match rule should be `parent-span` and `current-span` matched, and those two spans belonging to different services(instances).

> I think you have implemented most of the feature. 

I think the status is
1. Trace persistent and query based on Zipkin native format, rather than using SkyWalking's. This is good.
1. Old analysis, `zipkin span -> skywalking segment` should be removed, not stable and much useful.
1. OAL analysis engineer and source definitions are there and making analysis much easier. You just need to assemble the source(s) and send it to the dispatcher.

> The only thing left behind is how to guarantee that all the span information are sent to the same OAP node? If so, then yes we can focus on thinking about how to implement this one.

That is one important part, and yes, we need to focus on this solution.

**Comment by yangyshdan** [comment]
>  The most important thing is, how do you prepare to make match happen. The match rule should be parent-span and current-span matched, and those two spans belonging to different services(instances).

Let me confirm, the only reason that we need to match the spans in zipkin but no need to match the spans in skywalking native spans is because, skywalking native spans' spanid can tell the sequence of spans made from the single segment,  while zipkin can not tell the SERVER spans' sequence without knowing the timestamp of CLIENT spans. Is that correct?

> That is one important part, and yes, we need to focus on this solution.

I have a quick way solving the problem.  I can setup a proxy layer for the span receiver, and based on the trace id, we can route the span to the target node for processing. The theory is kind of consistent hash ring. Do you agree for the quick solution?

**Comment by wu-sheng** [comment]
> Let me confirm, the only reason that we need to match the spans in zipkin but no need to match the spans in skywalking native spans is because, skywalking native spans' spanid can tell the sequence of spans made from the single segment, while zipkin can not tell the SERVER spans' sequence without knowing the timestamp of CLIENT spans. Is that correct?

This is for one, the other is, you can't tell the `server` span's parent is `client` span, because you could have `server` span as `server` span's parent, such as `Tomcat` span as `SpringMVC` span's parent.

> I have a quick way solving the problem. I can setup a proxy layer for the span receiver, and based on the trace id, we can route the span to the target node for processing. The theory is kind of consistent hash ring. Do you agree for the quick solution?

You could, but how much memory do you expect to cost, and how long timeout should be set, because you never know, there will or will not more span coming.
