### ISSUE TITLE
in dashborad tab service,no data specified pid service

### ISSUE THREAD

**Issue by ben900120** [apache/skywalking#2656]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [* ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
in dashborad tab service,no data specified pid service,but it has data in total
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0 GA centos 7 jdk 1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
in dashborad  service tab,no data in specified pid service(Throughput,Response Time
,SLA),but it has data in avg data below.
![image](https://user-images.githubusercontent.com/15445096/57601423-07043480-758f-11e9-85d0-aa54fb1dcea5.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I can't tell what is happening from your very few words. You need to dig why first, and then we discuss.

For new users, please use the latest release, right now, it is 6.1

**Comment by ben900120** [comment]
> I can't tell what is happening from your very few words. You need to dig why first, and then we discuss.
> 
> For new users, please use the latest release, right now, it is 6.1

sorry for my poor english.the problem is no data in right,but in the buttom it has data(throughput and so on)
![image](https://user-images.githubusercontent.com/15445096/57601864-3a938e80-7590-11e9-8d3b-fa8a96b1ea7d.png)

**Comment by wu-sheng** [comment]
I got your question, but I haven't answer. So I suggest you to use 6.1, if you are new user.
Also, query is not complex, you could debug and find out why.

**Comment by ben900120** [comment]
> I got your question, but I haven't answer. So I suggest you to use 6.1, if you are new user.
> Also, query is not complex, you could debug and find out why.

谢谢大牛的热心回答，我的确是个新手，我想问下6.0升级到6.1是否直接覆盖文件即可，还是有其他步骤，貌似没有看到相关的升级文档。

**Comment by wu-sheng** [comment]
Delete all indexes in ElasticSearch, shutdown OAP and all application under the monitoring. Then reboot the whole envrioment.
