### ISSUE TITLE
在用skywalking 6.1的时候访问追踪栏目，在浏览器F5刷新导致出现Whitelabel Error Page

### ISSUE THREAD

**Issue by zhangy-bs** [apache/skywalking#2662]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

在用skywalking 6.1的时候访问追踪栏目，在浏览器F5刷新导致出现Whitelabel Error Page

浏览器显示如下：

**Whitelabel Error Page**
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue May 14 13:42:04 CST 2019
There was an unexpected error (type=Unauthorized, status=401).
Full authentication is required to access this resource.

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Fixed in master. English only.
