### ISSUE TITLE
程序宕机crash tomcat idea中运行 

### ISSUE THREAD

**Issue by ronghuaxiang** [apache/skywalking#2667]
spring程序中如果有@Scheduled 注解的定时任务、
程序就会崩溃退出并生成hs_err_pid69532.log文件
文件内容：

Register to memory mapping:

RAX=0x00000007b8c026e0 is an oop
com.hqew.search.task.SearchInfoTask$$Lambda$591/465070330 
 - klass: 'com/hqew/search/task/SearchInfoTask$$Lambda$591'
RBX=0x00000007c01c5488 is pointing into metadata
RCX=0x00000000029a6200 is at begin+12 in a stub
MethodHandle::interpreter_entry::_linkToStatic [0x00000000029a61f4, 0x00000000029a6218[ (36 bytes)
RDX=0x0000000722132900 is an oop
java.lang.invoke.DirectMethodHandle$Accessor 
 - klass: 'java/lang/invoke/DirectMethodHandle$Accessor'
RSP=0x000000001b59e340 is pointing into the stack for thread: 0x0000000029538000
RBP=0x0000000000000000 is an unknown value
RSI=0x000000002cb38f48 is pointing into metadata
RDI=0x0000000000dd1c02 is an unknown value
R8 =0x00000007b8c025e0 is an oop
java.lang.invoke.BoundMethodHandle$Species_L 
 - klass: 'java/lang/invoke/BoundMethodHandle$Species_L'
R9 =0x0000000722150508 is an oop
java.lang.invoke.MemberName 
 - klass: 'java/lang/invoke/MemberName'
R10=0x000000079169f4c0 is an oop
[Ljava.lang.Object; 
 - klass: 'java/lang/Object'[]
 - length: 1
R11=0x0000000003da3a80 is at entry_point+0 in (nmethod*)0x0000000003da3910
R12=0x0000000000000000 is an unknown value
R13=0x000000001b59e330 is pointing into the stack for thread: 0x0000000029538000
R14=0x0000000000000001 is an unknown value
R15=0x0000000029538000 is a thread

Stack: [0x000000001b4a0000,0x000000001b5a0000],  sp=0x000000001b59e340,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

**Comment by wu-sheng** [comment]
English only. Please submit a new issue.
