### ISSUE TITLE
crash tomcat spring mvc  (@Scheduled task)

### ISSUE THREAD

**Issue by ronghuaxiang** [apache/skywalking#2668]
tomcat spring mvc @Scheduled task、
app crash hs_err_pid69532.log file

VM state:not at safepoint (normal execution)
VM Mutex/Monitor currently owned by a thread: None

file content：

Register to memory mapping:

RAX=0x00000007b8c026e0 is an oop
com.hqew.search.task.SearchInfoTask$$Lambda$591/465070330 
 - klass: 'com/hqew/search/task/SearchInfoTask$$Lambda$591'
RBX=0x00000007c01c5488 is pointing into metadata
RCX=0x00000000029a6200 is at begin+12 in a stub
MethodHandle::interpreter_entry::_linkToStatic [0x00000000029a61f4, 0x00000000029a6218[ (36 bytes)
RDX=0x0000000722132900 is an oop
java.lang.invoke.DirectMethodHandle$Accessor 
 - klass: 'java/lang/invoke/DirectMethodHandle$Accessor'
RSP=0x000000001b59e340 is pointing into the stack for thread: 0x0000000029538000
RBP=0x0000000000000000 is an unknown value
RSI=0x000000002cb38f48 is pointing into metadata
RDI=0x0000000000dd1c02 is an unknown value
R8 =0x00000007b8c025e0 is an oop
java.lang.invoke.BoundMethodHandle$Species_L 
 - klass: 'java/lang/invoke/BoundMethodHandle$Species_L'
R9 =0x0000000722150508 is an oop
java.lang.invoke.MemberName 
 - klass: 'java/lang/invoke/MemberName'
R10=0x000000079169f4c0 is an oop
[Ljava.lang.Object; 
 - klass: 'java/lang/Object'[]
 - length: 1
R11=0x0000000003da3a80 is at entry_point+0 in (nmethod*)0x0000000003da3910
R12=0x0000000000000000 is an unknown value
R13=0x000000001b59e330 is pointing into the stack for thread: 0x0000000029538000
R14=0x0000000000000001 is an unknown value
R15=0x0000000029538000 is a thread

Stack: [0x000000001b4a0000,0x000000001b5a0000],  sp=0x000000001b59e340,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

**Comment by wu-sheng** [comment]
Please post some demo codes here.

**Comment by ronghuaxiang** [comment]
`@Component
public class SearchInfoTask{
	
	private static Logger LOG = LogManager.getLogger(SearchInfoTask.class);

	//redis
	@Resource
	private IRedis redis;

    @Scheduled(cron="0/300 * * * * ?") //300秒执行一次
    public void loadBrandValue() {
        redis.getRedis().execute((RedisCallback) redisConnection -> {
            Map<byte[], byte[]> datas = redisConnection.hGetAll(BrandValue.getBytes());
            if(datas != null){
                datas.forEach((k,v)->{
                    if(v!=null&&k!=null){
                        String k1 = new String(k);
                        String v1 = new String(v);
                        CacheInfoUtil.putBrandValue(k1,v1);
                        CacheInfoUtil.putKeywordBrand(k1);
                    }
                });
            }
            return null;
        });
    }`

**Comment by zhaoyuguang** [comment]
How is it different from https://github.com/apache/skywalking/issues/2669 . Can we discuss in this issue only?

**Comment by wu-sheng** [comment]
Close #2669

**Comment by zhaoyuguang** [comment]
@ronghuaxiang I need a more detailed environment to reproduce this problem.
Can you point me out where I am doing wrong?
SkyWalking agent:master(with optional-plugins)
spring-boot-starter-web:2.1.2.RELEASE
spring-data-redis:2.1.2.RELEASE
lettuce-core:5.1.0.RELEASE(i use lettuce)
case:https://github.com/zhaoyuguang/sky-case/blob/master/src/main/java/test/zhaoyuguang/cases/component/SearchInfoTask.java
No crash occurred, schedule is normal.
![image](https://user-images.githubusercontent.com/10150229/57748452-91be6e00-770c-11e9-82c2-0d94e80c2027.png)

**Comment by wu-sheng** [comment]
No update in one week. closing.
