### ISSUE TITLE
the history data in service_instance_inventory will not be deleted while ttl is set in application.yml

### ISSUE THREAD

**Issue by ben900120** [apache/skywalking#2671]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
the history data in service_instance_inventory will not be deleted while ttl is set in application.yml.so when i select a long time duration in  service tab,it will display too many expired service name choices with different pid.is it a bug or how can i delete the history service_instance_inventory?
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0GA  centos 7  jdk1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
![image](https://user-images.githubusercontent.com/15445096/57744060-308d9f00-76fa-11e9-8ca3-3f1189e52f27.png)

**Comment by wu-sheng** [comment]
We don't delete inventory metadata.

**Comment by ben900120** [comment]
> We don't delete inventory metadata.

can i delete inventory metadata in mannul?

**Comment by wu-sheng** [comment]
> can i delete inventory metadata in mannul?

This is an open source project. You can do anything you want.
