### ISSUE TITLE
Elasticsearch exception

### ISSUE THREAD

**Issue by zhangy-bs** [apache/skywalking#2672]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
   Why are there conflicts？Does it matter？
___
### Bug
- Which version of SkyWalking, OS and JRE?
   OS: centos 7.4
   ES: 6.6.0  [three node]
   ZK: 3.4.14 [three node]
   Skywalking: 6.1.0 [three node]
- Which company or project?

- What happen?
   org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker - 113 [DataCarrier.REGISTER_L2.BulkConsumePool.0.Thread] ERROR [] - Elasticsearch exce
ption [type=version_conflict_engine_exception, reason=[type][tenant-service_0_0]: version conflict, current version [259191] is different than the one provided [259190]]

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is OK, because we use Optimistic Lock. So it fails sometimes.
