### ISSUE TITLE
Why those instances are down still show in the UI?

### ISSUE THREAD

**Issue by Albert-Hugo** [apache/skywalking#2674]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
 Question 
___
### Question
- What do you want to know?
Why those instances are down still show in the UI? Every time restart the server , the UI will add a new instance . When will it be removed, or how ?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Never. Because you could query data even in several months. We don't delete them. Agent provided uuid setting, to make sure no new instance generated.
