### ISSUE TITLE
6.1.0 webapp add context-path for proxy fail

### ISSUE THREAD

**Issue by JustUse** [apache/skywalking#2675]
hello , I want to add context-path for webapp, then i can use nginx to proxy it. Unfortunately, it fail.
I modify the webapp/webapp.yml as follow.

server:
  port: 8080
  context-path: /skywalking

**Comment by wu-sheng** [comment]
Js codes can't access your new context. Change codes id you want.

**Comment by JustUse** [comment]
> Js codes can't access your new context. Change codes id you want.

Is there no some solutions now?

**Comment by wu-sheng** [comment]
We don't have plan to provide such feature. Not relate to project goals.

**Comment by arimon-arvind-das** [comment]
won't it create issues if I want to push my frontend application being served at port 80 but skywalking is running at 8080. The browser will start throwing CORS issue. I think it is a general use case. 
Currently all the UI loads directly from root context, an additional context configuration should be there. meanwhile this could be done by doing changes  in the code.

**Comment by tencentemr** [comment]
应该有个对策给这个场景。绝大多数公司都有安全限制。对外端口80这种都是严格控制不是任意服务可以独享的。常规情况下，多服务都是经80匹配location转发到后端服务。这是很基础的需求。
