### ISSUE TITLE
Merge multiple requests with different @PathVariable into same EndPoint

### ISSUE THREAD

**Issue by galaxyyao** [apache/skywalking#2676]
- Why do you submit this issue?
- [ x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
[Summary]
Is it possible to merge multiple requests with different @PathVariable into same EndPoint?

[Detail]
There are some requests which share a part of common path. These requests are only different in the last URL parameter.
eg.
/app/method/1001
/app/method/1002
/app/method/1003
my target:
I wonder if they can all be logged in endpoint /app/method.

**Comment by wu-sheng** [comment]
We have supported this in SpringMVC plugin, if you set the annotation as `/app/method/{id}` in spring annotation.

**Comment by qixiaobo** [comment]
We also meet this problem like  @galaxyyao
