### ISSUE TITLE
SkyWalking log clear

### ISSUE THREAD

**Issue by brentoncao** [apache/skywalking#2678]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Hello, may I ask if SkyWalking log cleanup is configured? Automatic cleanup discovery does not work.

**Comment by wu-sheng** [comment]
We don't have this if someone wants to contribute, welcome.

**Comment by brentoncao** [comment]
ok, got it~

**Comment by brentoncao** [comment]
Hello，does SkyWalking have a configuration to turn off log printing? Now print a lot of logs and fill up the memory, including the agent.

**Comment by wu-sheng** [comment]
Our document has included that.

**Comment by brentoncao** [comment]
Thanks~

**Comment by wu-sheng** [comment]
Duplicate with #2633
