### ISSUE TITLE
6.1.0  sw-ui Trace 分页查询问题

### ISSUE THREAD

**Issue by pfthink** [apache/skywalking#2680]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Question
Trace 分页查询 输入数字后 查询 每次拼接1  导致无法正常查询。
![image](https://user-images.githubusercontent.com/31644641/57769175-d9aab880-773f-11e9-9eaa-8a4db87c9626.png)

![image](https://user-images.githubusercontent.com/31644641/57769238-fa730e00-773f-11e9-8b07-2beb4daa63fe.png)

**Comment by wu-sheng** [comment]
Please submit English issue.
