### ISSUE TITLE
trace页面刷新报错

### ISSUE THREAD

**Issue by eare** [apache/skywalking#2685]
官方demo地址http://106.75.237.45:8080/，进入到trace页面，点击浏览器刷新按钮，提示status=401

![1](https://user-images.githubusercontent.com/16799371/57823378-cc3a1080-77c9-11e9-8f89-81e124323c5e.png)

**Comment by wu-sheng** [comment]
English only. And fixed. Please search before you submit an issue, and only based on a demo.
