### ISSUE TITLE
my project was crashed when using skywalking agent

### ISSUE THREAD

**Issue by FeiyuCloud** [apache/skywalking#2686]
目前生产环境每秒100并发的请求，但并不是每个服务都会被crash，一些大请求的服务没有被crash，反而一些小请求的服务被crash了

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f19e85e6350, pid=2410, tid=139750430967552
#
# JRE version: OpenJDK Runtime Environment (7.0_131) (build 1.7.0_131-mockbuild_2017_02_13_17_01-b00)
# Java VM: OpenJDK 64-Bit Server VM (24.131-b00 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.6.9
# Distribution: CentOS Linux release 7.3.1611 (Core) , package rhel-2.6.9.0.el7_3-x86_64 u131-b00
# Problematic frame:
# C  0x00007f19e85e6350
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/jvm-2410/hs_error.log
Compiled method (nm)  175702  812     n       java.lang.Class::isInstance (native)
 total in heap  [0x00007f1a543504d0,0x00007f1a54350860] = 912
 relocation     [0x00007f1a543505f0,0x00007f1a54350648] = 88
 main code      [0x00007f1a54350660,0x00007f1a54350860] = 512
Compiled method (c2)  175702 2940             java.lang.invoke.LambdaForm$NamedFunction::invoke_L_L (28 bytes)
 total in heap  [0x00007f1a5449c7d0,0x00007f1a5449cab8] = 744
 relocation     [0x00007f1a5449c8f0,0x00007f1a5449c918] = 40
 main code      [0x00007f1a5449c920,0x00007f1a5449c9a0] = 128
 stub code      [0x00007f1a5449c9a0,0x00007f1a5449c9d8] = 56
 oops           [0x00007f1a5449c9d8,0x00007f1a5449c9e0] = 8
 scopes data    [0x00007f1a5449c9e0,0x00007f1a5449ca28] = 72
 scopes pcs     [0x00007f1a5449ca28,0x00007f1a5449ca88] = 96
 dependencies   [0x00007f1a5449ca88,0x00007f1a5449ca90] = 8
 handler table  [0x00007f1a5449ca90,0x00007f1a5449caa8] = 24
 nul chk table  [0x00007f1a5449caa8,0x00007f1a5449cab8] = 16

**Comment by wu-sheng** [comment]
English only. We need you to address why this happens. I can't tell you why.

**Comment by FeiyuCloud** [comment]
some projects used agent, qps/tps 100,  but not all the proejcts crashed,  only several projects crashed
the error msg:
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00007f19e85e6350, pid=2410, tid=139750430967552
JRE version: OpenJDK Runtime Environment (7.0_131) (build 1.7.0_131-mockbuild_2017_02_13_17_01-b00)
Java VM: OpenJDK 64-Bit Server VM (24.131-b00 mixed mode linux-amd64 compressed oops)
Derivative: IcedTea 2.6.9
Distribution: CentOS Linux release 7.3.1611 (Core) , package rhel-2.6.9.0.el7_3-x86_64 u131-b00
Problematic frame:
C 0x00007f19e85e6350
Compiled method (nm) 175702 812 n java.lang.Class::isInstance (native)
total in heap [0x00007f1a543504d0,0x00007f1a54350860] = 912
relocation [0x00007f1a543505f0,0x00007f1a54350648] = 88
main code [0x00007f1a54350660,0x00007f1a54350860] = 512
Compiled method (c2) 175702 2940 java.lang.invoke.LambdaForm$NamedFunction::invoke_L_L (28 bytes)
total in heap [0x00007f1a5449c7d0,0x00007f1a5449cab8] = 744
relocation [0x00007f1a5449c8f0,0x00007f1a5449c918] = 40
main code [0x00007f1a5449c920,0x00007f1a5449c9a0] = 128
stub code [0x00007f1a5449c9a0,0x00007f1a5449c9d8] = 56
oops [0x00007f1a5449c9d8,0x00007f1a5449c9e0] = 8
scopes data [0x00007f1a5449c9e0,0x00007f1a5449ca28] = 72
scopes pcs [0x00007f1a5449ca28,0x00007f1a5449ca88] = 96
dependencies [0x00007f1a5449ca88,0x00007f1a5449ca90] = 8
handler table [0x00007f1a5449ca90,0x00007f1a5449caa8] = 24
nul chk table [0x00007f1a5449caa8,0x00007f1a5449cab8] = 16

**Comment by wu-sheng** [comment]
What is the difference between crash and uncrash? Have you tried to remove plugins?

**Comment by wu-sheng** [comment]
We need you to address the issue first, then we could discuss how to solve the issue.

**Comment by FeiyuCloud** [comment]
when i removed agent, my projects were runing  well

**Comment by wu-sheng** [comment]
This is unhelpful. I know this is caused by agent, but how and which part? Agent is complex, this could only be solved if you try to find out why.
Such as,
1. Try to remove all plugins, but still attaches the agent
2. Choose the plugin one by one, and add it back to plugin folder, and reboot.

**Comment by wu-sheng** [comment]
No update in 9days.
