### ISSUE TITLE
the plugin runtime exception

### ISSUE THREAD

**Issue by liucyu** [apache/skywalking#2687]
### Question
- when i wrote the plugin and found an exception after successful compilation and running.
and i checked the code and found no errors.Can anyone tell me which step is wrong?
and the skywalking version is 6.1.0.
![image](https://user-images.githubusercontent.com/13191643/57824617-35238780-77ce-11e9-85aa-85b0bb8b8b98.png)
![image](https://user-images.githubusercontent.com/13191643/57824630-41a7e000-77ce-11e9-8310-ca99a7e44696.png)
![image](https://user-images.githubusercontent.com/13191643/57824641-4ec4cf00-77ce-11e9-96c5-b0fb127b85b8.png)
![image](https://user-images.githubusercontent.com/13191643/57824679-6b610700-77ce-11e9-9988-2f33af6a3d99.png)

**Comment by wu-sheng** [comment]
Your plugin, your private codes, I am not sure how could I fix that. 
I could only suggest you, cross check between existing plugin, and jar you built.
