### ISSUE TITLE
I want to upgrade the v6.0.0-GA version to v6.1.0. Does the corresponding agent also need to be upgraded?

### ISSUE THREAD

**Issue by liyongfa0311** [apache/skywalking#2689]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think right now, you have to follow the changes by yourself. We provide change logs. The upgrade is not the high priority for the project. From I know, no committer was working on this. 

With new features keeping added into the project, the upgrade document is hard to provide.
