### ISSUE TITLE
Dashboard data is incomplete！

### ISSUE THREAD

**Issue by ns500** [apache/skywalking#2690]
### Question
I can see a lot of service registrations coming up on the UI

Instance can also see some data, but global/service/endoint does not have any data, so I wonder where the configuration is wrong?

I'm using version 6.1，The client app/agent is deployed to k8s, skywalking oap/ui  is deployed to VM.
app：Spring mvc

**Comment by wu-sheng** [comment]
Read the document carefully. Whoch time zone of your k8s. I assume utc 0. Choose utc from UI or change oap timezone.
