### ISSUE TITLE
About Debug APM agent.

### ISSUE THREAD

**Issue by wayilau** [apache/skywalking#2691]
If i want to debug the javaagent, I want to make sure whether the plugin works fine.  What should i do ? just use the SkyAPMTest? or is there another way to make sure the reason directly?

**Comment by wu-sheng** [comment]
You could add plugin source codes(or skywalking source codes) to your debug project(being monitored one). Or use remote debug(IDEA provided)

I assume you know Chinese, read http://skywalking.apache.org/zh/blog/2019-01-24-skywalking-remote-debug.html

**Comment by wayilau** [comment]
great, thanks.

**Comment by wayilau** [comment]
btw, this way can debug the apps ,but also i want to debug agent self. when remote debug started, agent has already passed.

**Comment by wu-sheng** [comment]
> btw, this way can debug the apps ,but also i want to debug agent self. when remote debug started, agent has already passed.

No, it wouldn't. Open the `suspend=Y` to your application argument. The application VM will wait for you to attach the agent, then continue to do everything. :)

**Comment by wayilau** [comment]
> > btw, this way can debug the apps ,but also i want to debug agent self. when remote debug started, agent has already passed.
> 
> No, it wouldn't. Open the `suspend=Y` to your application argument. The application VM will wait for you to attach the agent, then continue to do everything. :)

It really works find. thanks a lot .

**Comment by heihaozi** [comment]
The new blog url is [https://skywalking.apache.org/zh/2019-01-24-skywalking-remote-debug/](https://skywalking.apache.org/zh/2019-01-24-skywalking-remote-debug/).
