### ISSUE TITLE
 is Sw6.x compatible with ElasticSearch 5.x

### ISSUE THREAD

**Issue by BrownWei** [apache/skywalking#2696]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Is it possible to use ElasticSearch as a storage medium for data storage in the 6.x version, is it compatible with ElasticSearch 5.x?
So we use the ElasticSearch 5.x version online, upgrading is a difficult task.

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You could take a reference from here, https://github.com/SkyAPM/SkyWalking-With-Es5x-Storage 

This repository is not updated for a while. But you can get the idea about how to support ElasticSearch 5.
