### ISSUE TITLE
Provide plugin for ShardingSphere 4.0.0-RC1

### ISSUE THREAD

**Issue by tuohai666** [apache/skywalking#2699]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

Provide plugin for ShardingSphere 4.0.0-RC1 of which the API is different from 3.0.0.

**Comment by wu-sheng** [comment]
@ascrutae Please run test case and review.
