### ISSUE TITLE
How can I customize the instance name 

### ISSUE THREAD

**Issue by liucyu** [apache/skywalking#2700]
Qestion
- Where can I configure the instance name?  like "servicename + ip" or sth

![image](https://user-images.githubusercontent.com/13191643/57901909-906e7c00-7899-11e9-83f7-ad711c29e6b9.png)

**Comment by wu-sheng** [comment]
Right now, you can't. You could choose service, then select the instance belonging to it.

**Comment by liucyu** [comment]
Will you consider implementing this feature in the future? like The First column is cluster name  and the second column is service name blow the cluster @wu-sheng

**Comment by wu-sheng** [comment]
You are asking about two things.

> Will you consider implementing this feature in the future?

Doing this will break the protocol. I assume no one will do that in the short term. Adjusting protocols need to coordinate all agents to upgrade or set up backend compatible.

> like The First column is cluster name and the second column is service name blow the cluster

What is the context of this? We haven't done anything about the cluster, we provide service and service instance, which two should not be replaced.
