### ISSUE TITLE
监控面板的拓扑图内各节点的图标不一致 Tomcat SpringCloud

### ISSUE THREAD

**Issue by gaofeng36599** [apache/skywalking#2703]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
监控面板的拓扑图内各节点图标不一致：
 1.图标不一致有的显示Tomcat的图标有的显示Spring的图标
 2.点击各节点详细面板上类型不一致，有的显示Tomcat有的显示SpringCloud
 3.选择不同时间段，相同的节点展示的图标也不一致
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only. Component images will be changed by following https://github.com/apache/skywalking/pull/2654
