### ISSUE TITLE
Is there a plan to support Python?

### ISSUE THREAD

**Issue by leafonsword** [apache/skywalking#2705]
Python is another popular language, does skywalking plan supporting Python?

**Comment by wu-sheng** [comment]
I don't know. There is no SkyWalking supporting this or not. This depends on the community. If you want to build a python project, I am happy to help.

The .net, php, nodejs. go agents are all from community.

**Comment by wu-sheng** [comment]
Like we posted at https://github.com/apache/skywalking/issues/1221
