### ISSUE TITLE
Component icon display error in topology diagram

### ISSUE THREAD

**Issue by gaofeng36599** [apache/skywalking#2707]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
The same environment shows Tomcat icons and spring MVC icons
For example, F12 intercepts messages as follows：
1.{"data":{"topo":{"nodes":[{"id":"1","name":"User","type":"USER","isReal":false},{"id":"5","name":"business-account","type":"**SpringMVC**","isReal":true}
2.{"data":{"topo":{"nodes":[{"id":"1","name":"User","type":"USER","isReal":false},{"id":"5","name":"business-account","type":"**Tomcat**","isReal":true}
- [ ] Bug
- [ ] Requirement
The same environment shows the same icon (node type)
- [ ] Feature or performance improvement
Thank you
___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by gaofeng36599** [comment]
According to different time conditions, the node icons are also different.
Click on the node and the details are of different types: 1. Tomcat; 2. Spring MVC

**Comment by wu-sheng** [comment]
Component images will be changed by following #2654

**Comment by chinaldp** [comment]
What does isReal mean, and what does it use to mark an application being called？
