### ISSUE TITLE
Provide plugin for spring-cloud-gateway 2.0.x

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/skywalking#2711]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement
___
### Requirement or improvement
Provide plugin for spring-cloud-gateway 2.0.x, Which use `reactor-netty` API is different from 2.1.x

**Comment by ygsama** [comment]
I want to know if  SkyWalking-6.1 don't support spring-cloud-gateway 2.1.1 ? 
If it is , I need to wait a few days or do it myself ?

**Comment by wu-sheng** [comment]
The Gateway will be merged today, https://github.com/apache/skywalking/pull/2517

**Comment by SataQiu** [comment]
@wu-sheng @zhaoyuguang 
I found that our spring cloud gateway 2.1.x plugin is named `gateway-2.x-plugin`. 
Is there any ambiguity here? 
Should we use `2.1.x` instead of `2.x` ?
If yes, I would like to do this.

**Comment by wu-sheng** [comment]
I am waiting @zhaoyuguang to make the decision. How does he want to put the new plugin of 2.0.x

**Comment by zhaoyuguang** [comment]
I will try to finish it in next milestone, if you have interests, contributions are welcome @SataQiu. Because I think `2.0.x`  can be finished  in 2.x, so I named it.

**Comment by wu-sheng** [comment]
> Because I think 2.0.x can be finished in 2.x, so I named it.

Make sense. Rename it if necessary, such as 2.0.x is very incompatible with 2.1.x, like using a totally different way to intercept.

**Comment by zhaoyuguang** [comment]
> > Because I think 2.0.x can be finished in 2.x, so I named it.
> 
> Make sense. Rename it if necessary, such as 2.0.x is very incompatible with 2.1.x, like using a totally different way to intercept.

OK

**Comment by wu-sheng** [comment]
@zhaoyuguang If you are trying to do this in 6.3.0, please set the milestone.
