### ISSUE TITLE
service cpm的统计在service instance 时间不同步的情况下，其准确性如何？

### ISSUE THREAD

**Issue by zhousiliang163** [apache/skywalking#2716]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
service cpm的统计在service instance 时间不同步的情况下，其准确性如何？
___

**Comment by wu-sheng** [comment]
English only. Your time is not accurate, what is the relationship with us?

**Comment by zhousiliang163** [comment]
> 
> 
> English only. Your time is not accurate, what is the relationship with us?
If time synchronization is not taken into account, then service CPM statistics are very wrong.

**Comment by wu-sheng** [comment]
Time sync is a very common issue in a distributed system. If you care time-related metric, you should set the sync.
