### ISSUE TITLE
i use Idea to locally debug skywalking, but cannot open UI

### ISSUE THREAD

**Issue by jzhahaha** [apache/skywalking#2717]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- What do you want to know?

i want to locally debug skywalking . i started the OAPServerStartUp.class  , then started the ApplicationStartUp.class ,  but i cannot open the web UI. So i want to know what else i should to do.

![image](https://user-images.githubusercontent.com/40509002/57996183-957d3680-7af8-11e9-8e16-78718d320630.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?
version skywalking-6.0.0-GA

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If you want to debug UI, go to RocketBot UI repo, there is document there to guide you run UI in debug mode.
