### ISSUE TITLE
Provide plugin for kafka-v2-plugin

### ISSUE THREAD

**Issue by Mars626** [apache/skywalking#2720]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0GA

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
i try to sent message by kafka-clients-2.0.1 ,but fail，because of exception in kafka-clients-2.0.1 jar：
“  if (magic < RecordBatch.MAGIC_VALUE_V2 && headers != null && headers.length > 0)
                throw new IllegalArgumentException("Magic v" + magic + " does not support record headers");” in class MemoryRecordsBuilder
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ascrutae** [comment]
I am going to provide this plugin

**Comment by wu-sheng** [comment]
@Mars626 If you have interests, contributions are welcome.

**Comment by Mars626** [comment]
> I am going to provide this plugin

thanks for your help

**Comment by wu-sheng** [comment]
@ascrutae I think you should fix this in 6.3.0

**Comment by wu-sheng** [comment]
@zhaoyuguang Could you help on this?

**Comment by zhaoyuguang** [comment]
> @zhaoyuguang Could you help on this?

I am very interested in kafka, but I will try to finish it at 6.4.0, if other people are interested, welcome.

**Comment by dmsolr** [comment]
@zhaoyuguang Do you work in progress that? May I join in?

**Comment by wu-sheng** [comment]
I think he hasn't. Welcome to do. FYI @zhaoyuguang

**Comment by zhaoyuguang** [comment]
I haven't do it yet. Welcome to contribute.

**Comment by stalary** [comment]
I have completed a v-2 plugin that has been used in the test environment. I may consider submitting it in the future

**Comment by wu-sheng** [comment]
@stalary Welcome the contributions. We are closing to 6.4.0 release, if you want, please consider to submit pull request before that.

**Comment by stalary** [comment]
> @stalary Welcome the contributions. We are closing to 6.4.0 release, if you want, please consider to submit pull request before that.

Ok, I will submit it as soon as possible
