### ISSUE TITLE
build prokect fail

### ISSUE THREAD

**Issue by king-john** [apache/skywalking#2721]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
when i Run ./mvnw clean package -DskipTests to build project has this error .
![image](https://user-images.githubusercontent.com/19261919/58026296-bb322c00-7b48-11e9-8917-87c0804ec892.png)
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This error doesn't hurt the build, I think.

**Comment by king-john** [comment]
但是它就卡住了，是继续等待？

**Comment by wu-sheng** [comment]
Make sure your network is good enough. Someone reported npm build failure because of that.

**Comment by king-john** [comment]
OK，thank you
