### ISSUE TITLE
skywalking agent support label select

### ISSUE THREAD

**Issue by SataQiu** [apache/skywalking#2723]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
Whether the agent can be assigned Labels, and then we can screen the measurement data we care about based on the Label Selector. 
For example, when the agent is started, `app:redis` label is passed in. 
Then we can query the data from this agent by specified label `app:redis` .
It's like k8s Pod management.

If it makes sense, I'm willing to try.

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Do you want to search service name by label(s) from UI?

Right now, in the register protocol, we have tags and properties
```grpc
message Service {
    string serviceName = 1;
    repeated KeyStringValuePair tags = 3;
    repeated KeyStringValuePair properties = 4;
}

message ServiceInstance {
    int32 serviceId = 1;
    string instanceUUID = 2;
    int64 time = 3;
    repeated KeyStringValuePair tags = 4;
    repeated KeyStringValuePair properties = 5;
}
```

What do you mean by label? And if you set labels(s) on instance differently, what is the expected result?

**Comment by SataQiu** [comment]
What I want to achieve is to be able to screen the services I am interested in through the label selector, and show their topology, their tracing data (if any). This gives us the flexibility to present topological information at different scales. 
Have we implemented similar functionality on the backend? But I don't see it on the UI, right?

**Comment by SataQiu** [comment]
![图片](https://user-images.githubusercontent.com/9354727/58067783-45b67200-7bc1-11e9-997a-24acab2a8e06.png)

**Comment by wu-sheng** [comment]
If you are talking about multiple service filter topology, then this is a much bigger feature enhanced than I expected. 

> Have we implemented similar functionality on the backend? But I don't see it on the UI, right?

Right now, we only have two kinds of topology query.
1. One service topology. One level dependency(direct parent and child)
1. Global topology including all services.

If you want to filter services based on backend query, then you need to change lots of things.

**Comment by SataQiu** [comment]
Yes, I also think it's a Big Job. But I think it's a very meaningful thing. 
My initial point of departure was to provide subviews to users through this feature, because more users only care about the services they deploy and use. We can tag the services with user attributes and use them for filtering.
However, I find that if we implement this feature, our queries will become more flexible and easier to integrate with other systems. 
I hope that I can try not to change the original thing, only to achieve this through extension.
Looking forward to your Suggestions!

**Comment by wu-sheng** [comment]
> However, I find that if we implement this feature, our queries will become more flexible and easier to integrate with other systems.

Yes. But meanwhile, we have to face the performance concerns. The reason why we design the query API in the current way, is making sure the query latency measurable. 

> I hope that I can try not to change the original thing, only to achieve this through extension.
Looking forward to your Suggestions!

There are two major challenges
1. How to query metadata. Service is an atomic object but based on instance register. So how do you plan to make tag exists in service level. And how do you make sure it is reasonable.
1. Query topology based on each service, and merged them on UI. If the performance is acceptable. The master branch UI topology is just changed. It supports query topology(one depth level) when you choose one at the left.

**Comment by wu-sheng** [comment]
No update in one month.
