### ISSUE TITLE
 is there a convenient Extension mechanism

### ISSUE THREAD

**Issue by solomon4github** [apache/skywalking#2729]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

 Hello, I am new in skywalking, and wondering if there is a convenient Extension mechanism, for collecting custom metrics by agent , pass it to the collector, and display it on UI . for example , to collect custom exception count , or custom code in response body.

**Comment by wu-sheng** [comment]
You need to learn.
1. New Receiver, like existing receivers.
1. OAL extension, like all existing scope objects.
1. GraphQL query extension.
1. UI extension.

We are an APM tool, so there is no as easy as `config and go`. We always need to understand the data relationship. 
I highly recommend you to read the concept introduction, https://github.com/apache/skywalking/blob/master/docs/en/concepts-and-designs/README.md
