### ISSUE TITLE
index page chinese word fix?

### ISSUE THREAD

**Issue by yimeng** [apache/skywalking#2733]
chinese version url: https://skywalking.apache.org/zh/

分布式系统的应用程序性能监视工具，专为微服务、云本机架构和基于容器（Docker、K8s、Mesos）架构而设计。

change the word 云本机 to 云原生？

**Comment by wu-sheng** [comment]
Submit a pull request to https://github.com/apache/skywalking-website/blob/master/docs/zh/README.md . Thanks.
