### ISSUE TITLE
class[class com.mongodb.MongoClient] before method[execute] intercept failure java.lang.NullPointerException

### ISSUE THREAD

**Issue by programmerCs** [apache/skywalking#2738]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [* ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by programmerCs** [comment]
the mongodb driver version is 3.2.2

**Comment by programmerCs** [comment]
![image](https://user-images.githubusercontent.com/33591843/58223011-8db4d080-7d4a-11e9-8005-a2c6fa00f91e.png)

**Comment by wu-sheng** [comment]
We need a simple demo to reproduce the error.

**Comment by wu-sheng** [comment]
Also, please be adviced, your version is not supported yet. https://github.com/SkyAPMTest/agent-integration-test-report#mongodb

**Comment by programmerCs** [comment]
I has find the problem. the problem is in org.apache.skywalking.apm.plugin.mongodb.v3.MongoDBMethodInterceptor#onConstruct method.
if mongodb driver version 3.2.x.
the code cluster.getDescription().getServerDescriptions() will throw java.lang.NoSuchMethodError: com.mongodb.connection.ClusterDescription.getServerDescriptions()Ljava/util/List
because  ClusterDescription.getServerDescriptions() is since mongodb driver 3.3

**Comment by wu-sheng** [comment]
Yes. Like I said, from the supported list, we haven't supported in 3.2.x, if you want, I think you need set a pull request to add a new plugin, also add witness class for the current plugin to avoid this error.

**Comment by programmerCs** [comment]
![image](https://user-images.githubusercontent.com/33591843/58308026-fc6d5900-7e32-11e9-926d-fe08ba021933.png)
I use cluster.getDescription().getAll() and it works fine

**Comment by programmerCs** [comment]
sorry I didn't look carefully.thank for your answering

**Comment by wu-sheng** [comment]
MongoDB 3.2.x driver is not supported.
