### ISSUE TITLE
Is it possible to debug via the idea local startup source?

### ISSUE THREAD

**Issue by xjhuiw** [apache/skywalking#2740]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?

![image](https://user-images.githubusercontent.com/35231463/58228032-ddea5d80-7d5f-11e9-9198-58a12e107dc3.png)

Download v6.1 source code There is no network.common package.   Is it possible to debug via the idea local startup source?

**Comment by wu-sheng** [comment]
The compiling document has talked this clear. Read the document please.
