### ISSUE TITLE
I restart the same application ,the Instance is different，I want to see the same ,how I can do

### ISSUE THREAD

**Issue by yh1968684316** [apache/skywalking#2741]
I have one java application . then run 'java -javaagent:/usr/local/src/agent/skywalking-agent.jar -jar /usr/local/src/server.jar'(agent.config  agent.service_name=server), the instance is server-pid:11815@localhost;after restart ,the instance is server-pid:12114@localhost.I think they are the same application,I should have seen a continuous record, not two...Did I overlook anything?So what should I do?

**Comment by wu-sheng** [comment]
You could follow agent setup document to set UUID manually, then the instance name wouldn't change. But the side effect will be, the PID most likely would be wrong.
