### ISSUE TITLE
where is NeedSnifferActivation annotaion handled?

### ISSUE THREAD

**Issue by zhousiliang163** [apache/skywalking#2743]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
where is NeedSnifferActivation annotaion handled? is annotation processer defined?
___

**Comment by wu-sheng** [comment]
Nowhere. This is an annotation for dev. Check the source codes.
```java
/**
 * The <code>NeedSnifferActivation</code> annotation is flag for reader and maintainers,
 * which represents this method should be activated/intercepted in sniffer.
 *
 * @author wusheng
 */
@Target({ElementType.METHOD, ElementType.CONSTRUCTOR})
@Retention(RetentionPolicy.SOURCE)
public @interface NeedSnifferActivation {
    String value() default "What should interceptor do?";
}
```
