### ISSUE TITLE
I want to know if SkyWalking-6.1 don't support spring-boot 2.0 ?

### ISSUE THREAD

**Issue by chenqi45** [apache/skywalking#2763]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We are instrumenting the RPC frameworks and libs. Spring boot has nothing related to our interests. We just make sure we don't conflict with Spring framework.

Please read the document and supported list, we have a full list there.
