### ISSUE TITLE
metric of cpu usagePercent is still 0.

### ISSUE THREAD

**Issue by zhousiliang163** [apache/skywalking#2765]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
version:6.0-GA;
os:windows
jre:1.8
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
![图片](https://user-images.githubusercontent.com/7529190/58417814-9134b880-80b8-11e9-94f8-9db68a3ef8fd.png)

**Comment by wu-sheng** [comment]
![image](https://user-images.githubusercontent.com/5441976/58421033-83376580-80c1-11e9-9613-6c52062a469e.png)
We have the metrics of CPU in SkyWalking 6.1

**Comment by zhousiliang163** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/5441976/58421033-83376580-80c1-11e9-9613-6c52062a469e.png)
> We have the metrics of CPU in SkyWalking 6.1

Look at source code,v6.1 is ok,it has been repaired.
