### ISSUE TITLE
Failed to deserialize DefaultAopProxyFactory 

### ISSUE THREAD

**Issue by mattwmj** [apache/skywalking#2768]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I am using SkyWalking with Spring cloud, Spring Boot, Spring OAuth2 Client and Spring Session with JDBC store. 
java.io.InvalidClassException: org.springframework.aop.framework.DefaultAopProxyFactory; local class incompatible  happened when more than one oauth client instance in the cloud.

I suspect that:

Spring OAuth2 Client stores DefaultOAuth2ClientContext (which contains DefaultAopProxyFactory) in session during authentication process. When SkyWalking enhance DefaultAopProxyFactory , the serializationUID is different on each service node. If node1 serialize DefaultAopProxyFactory  and store it in store, when node2 try to deserialize DefaultAopProxyFactory from session store, InvalidClassException happens.

I want to know whether this is true and what I can do?
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.1.0 Linux/Windows Oracle Java8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We don't manipulate `OAuth2` from I known. We just enhance `AopProxyFactoryInstrumentation` itself.

**Comment by mattwmj** [comment]
> We don't manipulate `OAuth2` from I known. We just enhance `AopProxyFactoryInstrumentation` itself.

I think it is oauth2 serialized a DefaultAopProxyFactory instance into session. Does SkyWalking enhance DefaultAopProxyFactory? Could enhancement cause different serializationUID on different nodes?
FYI， In Spring source code, DefaultAopProxyFactory is serializable and has no serializationUID.

**Comment by mattwmj** [comment]
FYI, I found private static final String ENHANCE_CLASS = "org.springframework.aop.framework.DefaultAopProxyFactory" in org.apache.skywalking.apm.plugin.spring.patch.define.AopProxyFactoryInstrumentation.
Does that mean SkyWalking enhances DefaultAopProxyFactory?
Since DefaultAopProxyFactory is serializable and has not specified serializationUID, could SkyWalking agent do something to avoid this serial/deserialization exception?

**Comment by wu-sheng** [comment]
That is not your bean. It is Spring intetnal factory. I don't think you really use that.

**Comment by mattwmj** [comment]
I don't use that directly, but I use spring oauth2 and I believe that spring oauth2 stores DefaultAopProxyFactory in session store.
FYI, I look into the binary bytes that serialized in the session store with attribute named 'scopedTarget.oauth2ClientContext'.  It show:

org.springframework.aop.framework.DefaultAopProxyFactory?鱲TP嘵 L _$EnhancedClassField_wsq

I think this proves that an instance of DefaultAopProxyFactory is enhanced by Skywalking and serialized into session store by spring oauth2 and spring session.

**Comment by wu-sheng** [comment]
Yes, I can confirm we enhanced the `DefaultAopProxyFactory`, but why do you save this `DefaultAopProxyFactory` into the session?

**Comment by mattwmj** [comment]
I do not. 
I use Spring Oauth2 and I think it saves DefaultAopProxyFactory into the session. 
I will raise an issue in spring-security-oauth repository to get confirmation.

But since DefaultAopProxyFactory implements Serializable interface, I think potentially it could be serialized. If SkyWalking agent enhancement changes the serializationUID of the class, then InvalidClassException could happen when deserialized on another jvm.

**Comment by wu-sheng** [comment]
> But since DefaultAopProxyFactory implements Serializable interface, I think potentially it could be serialized. If SkyWalking agent enhancement changes the serializationUID of the class, then InvalidClassException could happen when deserialized on another jvm.

SkyWalking just add a new field and new interface with two methods(set/get). But Byte Buddy may add a static field if I remember right. Would that harm?

**Comment by mattwmj** [comment]
I think that any changes on java class structure would changed calculated serializationUID of that class.

IMHO if the added methods/interface/fields are with different name on different jvm, it could cause different serializationUID and cause exception when serialize/deserialize on different jvm.

On the other hand, I also feel that it is wierd that Spring OAuth stores DefaultAopProxyFactory into the session.

**Comment by mattwmj** [comment]
FYI

https://github.com/spring-projects/spring-security-oauth/issues/1684

**Comment by mattwmj** [comment]
Also, is it possible for SkyWalking to add static serialize UID that consistent to the original class when enhance serializable classes?

**Comment by wu-sheng** [comment]
> Also, is it possible for SkyWalking to add static serialize UID that consistent to the original class when enhance serializable classes?

We don't do that, because it meaningless for us, and could cause more issue. Also from my experience, this ID should not require updated even SkyWalking change the class structure.

**Comment by mattwmj** [comment]
> > Also, is it possible for SkyWalking to add static serialize UID that consistent to the original class when enhance serializable classes?
> 
> We don't do that, because it meaningless for us, and could cause more issue. Also from my experience, this ID should not require updated even SkyWalking change the class structure.

I understand.
I want to ask question about Byte Buddy and enhancement used in SkyWalking agent. Do you know that enhancement generates any random named fields or methods on DefaultAopProxyFactory? If does, is there anyway I can avoid random name. Since I think theoretically, enhanced classes with exactly same fields and methods would have same serialization version uid.

**Comment by wu-sheng** [comment]
> I want to ask question about Byte Buddy and enhancement used in SkyWalking agent. Do you know that enhancement generates any random named fields or methods on DefaultAopProxyFactory? If does, is there anyway I can avoid random name. Since I think theoretically, enhanced classes with exactly same fields and methods would have same serialization version uid.

It will generate a dynamic field by SkyWalking, with `EnhancedInstance` interface. Right now, we can't avoid them, because a lot of plugins depend on it to keep high performance.
