### ISSUE TITLE
apm-agent-core maven pom file shade-plugin define bug

### ISSUE THREAD

**Issue by sk163** [apache/skywalking#2769]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [√ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
lines 58-60
<shade.org.apache.commons.source>org.apache.commons</shade.org.apache.commons.source>
        <shade.org.apache.commons.target>${shade.package}.**${shade.org.apache.http.source}**
        </shade.org.apache.commons.target>

--> 

<shade.org.apache.commons.source>org.apache.commons</shade.org.apache.commons.source>
<shade.org.apache.commons.target>${shade.package}.**${shade.org.apache.commons.source}**
        </shade.org.apache.commons.target>

**Comment by wu-sheng** [comment]
Could you submit a pull request to fix?

**Comment by wu-sheng** [comment]
Could you submit a pull request to fix it? And remove 
```
        <shade.org.apache.http.source>org.apache.http</shade.org.apache.http.source>
        <shade.org.apache.http.target>${shade.package}.${shade.org.apache.http.source}</shade.org.apache.http.target>
```
We don't depend on `org.apache.http` today.

**Comment by wu-sheng** [comment]
Fixed.
