### ISSUE TITLE
ModuleManager.init method  performance improvement

### ISSUE THREAD

**Issue by zhousiliang163** [apache/skywalking#2772]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
![图片](https://user-images.githubusercontent.com/7529190/58457878-5aaf7a00-815a-11e9-81d7-526d57406e6b.png)
![图片](https://user-images.githubusercontent.com/7529190/58458262-5768be00-815b-11e9-95db-b3ea328179e3.png)

**Comment by wu-sheng** [comment]
First of all, all things need to be English, including snapshot. Then if you are talking about performance, then learn from #2766 . We need proof of performance improvement. Do benchmark if this really makes sense.

**Comment by wu-sheng** [comment]
You need to consider the execution times in real scenario. From my understanding, this is only related to startup and invoke limited times.
