### ISSUE TITLE
which version of ElasticSearch should I use best when I use SkyWalking-6.1.0

### ISSUE THREAD

**Issue by xiongshiyan** [apache/skywalking#2777]
- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- which version of ElasticSearch  should I use best when I use SkyWalking6.1.0

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.1.0

- Which company or project?
zytx

- What happen?
I donot know how to choose the best matching version of dependent components, where can I get related links or information?

**Comment by wu-sheng** [comment]
We have shown the versions of storage in backend storage setup document.

**Comment by xiongshiyan** [comment]
could you give a link? thanks

**Comment by wu-sheng** [comment]
We have links in homepage linking to all recommended document.
