### ISSUE TITLE
SkyWalking cluster problem

### ISSUE THREAD

**Issue by brentoncao** [apache/skywalking#2779]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Hi，SkyWalking builds a cluster with three machines, one of which is down, the other ones will report an error, not available, is there a problem with the configuration, or the SkyWalking cluster itself is strongly associated？

**Comment by wu-sheng** [comment]
That one down means no available process? SkyWalking cluster will wait if the target registered in zk/consule or detected by k8s API server.
