### ISSUE TITLE
does skywalking surpport Vert.x3.x Or Jersey with Vert.x?

### ISSUE THREAD

**Issue by xiongshiyan** [apache/skywalking#2780]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [x] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
does skywalking surpport Vert.x3.x Or Jersey with Vert.x?
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.1.0
- Which company or project?
zytx
- What happen?

I want to know if skywalking supports Vert.x3.x Or Jersey with Vert.x?

**Comment by wu-sheng** [comment]
Please read supported list. I think vertx is there.

**Comment by xiongshiyan** [comment]
As I've seen, Vert.x Ecosystem is in the support list, but access URLs cannot be detected.

**Comment by wu-sheng** [comment]
You could check with test codes here. https://github.com/SkyAPMTest/agent-auto-integration-testcases . There are event bus and web cases tested.

**Comment by xiongshiyan** [comment]
Ok,Thanks

**Comment by qxo** [comment]
On my test skywalking vertx plugin was not work as it should be.
And It's hard make the plugin work  without change apm-agent-core

**Comment by wu-sheng** [comment]
Why do you change core? If you have unsupported scenario, submit an issue and discuss in abstract way. Please don't connect to vertx code, we need clear scenario.

**Comment by xiongshiyan** [comment]
我的项目使用了vertx+jersey，jersey作为表现层的接口框架，通过提供类似Spring的注解来表达URI。例如@path，@get，@post等。我集成skywalking的agent之后，能发现这个service，但是不能发现endpoint，所以我怀疑是skywalking不支持jersey，因为我另外一个项目纯使用vertx web是没问题的。如果skywalking真不支持jersey，请问开发支持jersey的插件有流程文档吗？
