### ISSUE TITLE
SkyWalking topology problem

### ISSUE THREAD

**Issue by ChinaSilence** [apache/skywalking#2781]
___
### Bug
- question: topology page show nothing
- code version: master branch
- deploy type: docker

![](https://user-images.githubusercontent.com/12091906/58601474-80a06000-82bb-11e9-909b-b1f01096bb9f.png)

![](https://user-images.githubusercontent.com/12091906/58601492-8dbd4f00-82bb-11e9-8d6c-1a1e8cf016f0.png)

**Comment by wu-sheng** [comment]
For master, it is just a development branch, it is not like release, which is stable. And for branch and next release(6.2), the topology API changed, so UI needs to udpate. I think you don't update the submodule
