### ISSUE TITLE
SkywalkingUI property undefined bug

### ISSUE THREAD

**Issue by yuyujulin** [apache/skywalking#2784]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

Skywalking 6.1.0, Windows 10,  JRE8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

1. download Skwwalking 6.1.0 from apache.
2. click start.bat
3. enter http://localhost:8080 on Browser, enter admin and admin
4. Click Dashboard and Alarm button,  there will be some errors like the following

```
dashboard-service.ts:92 Uncaught (in promise) TypeError: Cannot read property 'getEndpoints' of undefined
alarm.ts:69 Uncaught (in promise) TypeError: Cannot read property 'items' of undefined

```

![1](https://user-images.githubusercontent.com/4941575/58606936-1f36bc00-82d0-11e9-82a1-d41fd643c5cb.jpg)

I reckon, it may be caused by no services in OAP.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
These are small bugs of UI. cc @TinyAllen I think we need to support when service or service instance is not there.

**Comment by carlvine500** [comment]
I find the same problem ￼, and I can see nothing after running skywalking oap&ui .￼
![C7318328-ADB3-422F-B9F9-6AC41B916D8E](https://user-images.githubusercontent.com/7055460/59662565-cdeb5f80-91df-11e9-9dbc-0e5b3a30e255.png)

**Comment by jatin85** [comment]
same above issue i am getting "Cannot read property 'getEndpoints' of undefined"

**Comment by IronCity** [comment]
I found this problem too, I can see nothing after running skywalking oap&ui .￼
