### ISSUE TITLE
my skywalking6.1.0 UI could not display service Name  but can display tracing things 

### ISSUE THREAD

**Issue by jinxingit** [apache/skywalking#2788]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
why my skywalking6.1.0 UI could not display service Name  but can display tracing things 

dashboad:

![dashbord-en](https://user-images.githubusercontent.com/7247638/58625389-fbda3400-8304-11e9-85b3-0a924dc82bfe.png)

tracing:
![tracing-en](https://user-images.githubusercontent.com/7247638/58625434-0dbbd700-8305-11e9-9bb1-2806353c7685.png)

I use set up Backend and UI by quick start way and docker-compose way. all of the ways do not work.

my project is https://github.com/SkyAPMTest/skywalking-live-demo 
but it's not like online demo http://106.75.237.45:8080/

java agent config file :
![image](https://user-images.githubusercontent.com/7247638/58625943-1a8cfa80-8306-11e9-8b5b-f61012ea56ec.png)

should I set up skywalking in another way? 
help me please

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please the first line of setup document. Set up the timezone right, or choose the right time zone at UI.
