### ISSUE TITLE
Can I delete the index of es segment?

### ISSUE THREAD

**Issue by xiaoni157** [apache/skywalking#2793]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I set the expiration time of es as two days. Is the segment data saved for two days or accumulated all the time? Can I delete it?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by IanCao** [comment]
please Querying documents 
https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/ttl.md
this will help you

**Comment by xiaoni157** [comment]
![image](https://user-images.githubusercontent.com/24448049/58680412-3510b380-839a-11e9-8b32-ca64c2d5b1ec.png)
I'm setting it up normally, and my question is whether the segment index data will be deleted

![image](https://user-images.githubusercontent.com/24448049/58680451-5e314400-839a-11e9-855d-964ea6354cbf.png)

**Comment by xiaoni157** [comment]
I know the monitoring data of es will be deleted, but I don't know whether the segment data will be continuously increased

**Comment by IanCao** [comment]
the segment index data will be deleted

**Comment by xiaoni157** [comment]
If I delete this index, will there be any other problems besides the data being deleted?

**Comment by IanCao** [comment]
the collector can not work after u delete that index

**Comment by xiaoni157** [comment]
ok,thanks
