### ISSUE TITLE
一个 tomcat 里面部署多个 war 包，进行启动，会有不同的应用实例。如何区分采集到的数据来至不同的应用?

### ISSUE THREAD

**Issue by cyloer** [apache/skywalking#2798]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only.
