### ISSUE TITLE
Deploy multiple war packages in a tomcat, start them, and there will be different application instances. How to distinguish the collected data from different applications? 

### ISSUE THREAD

**Issue by cyloer** [apache/skywalking#2799]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read our first line of the project introduction.
> SkyWalking: an APM(application performance monitor) system, especially designed for microservices, cloud native and container-based (Docker, Kubernetes, Mesos) architectures.

In micros-service, container-based, no one uses this deployment solution. So in default, we don't support this. We treat one OS process as one service instance only.
You could change source codes to do, but for use, I think it doesn't fit the goals.
