### ISSUE TITLE
like this ： -javaagent:/path/to/skywalking-agent.jar=agent.application_code=31200,logging.level=debug  I want to know what problems to solve？

### ISSUE THREAD

**Issue by cyloer** [apache/skywalking#2800]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If you want to submit a question, please describe clearly. I have no clue what you want to say.
