### ISSUE TITLE
gateway-2.x-plugin use in skywalking 6.1.0

### ISSUE THREAD

**Issue by GreyZeng** [apache/skywalking#2814]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.1
- Which company or project?
Spring cloud Gateway

in skywalking-6.1.0 
the plugin:
https://github.com/apache/skywalking/tree/98b495ebcc6f3eff3fa16d48f166f64527e59024/apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud
is not in option-plugins

and I want use the plugin(gateway-2.x-plugin) in 6.1.0

so , I  package the maven project by exec under apm-sniffer:

mvn clean package -Dmaven.test.skip

BUT: 

Failed to execute goal on project apm-agent-core: Could not resolve dependencies for project org.apache.skywalking:apm-agent-core:jar:6.2.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.skywalking:apm-network:jar:6.2.0-SNAPSHOT, org.apache.skywalking:apm-util:jar:6.2.0-SNAPSHOT, org.apache.skywalking:apm-datacarrier:jar:6.2.0-SNAPSHOT: Could not find artifact org.apache.skywalking:apm-network:jar:6.2.0-SNAPSHOT in aliyunmaven (https://maven.aliyun.com/repository/public)
___
### Requirement or improvement
 Can I use the plugin(gateway-2.x-plugin) in 6.1.0, if I can't , How can I use the gateway-2.x-plugin

**Comment by wu-sheng** [comment]
You need to build the whole project. This is simple maven usage.

**Comment by GreyZeng** [comment]
> You need to build the whole project. This is simple maven usage.

I pull skywalking master branch and exec :
mvn clean install -Dmaven.test.skip
under the whole project , but:
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project apm-network: Compilation failure: Compilation failure:
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/InstanceResetCommand.java:[21,48] package org.apache.skywalking.apm.network.common does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[21,1] package org.apache.skywalking.apm.network.common does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Serializable.java:[21,48] package org.apache.skywalking.apm.network.common does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/InstanceResetCommand.java:[34,29] package Command does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[30,26] package Command does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[45,12] package Command does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Serializable.java:[27,12] package Command does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/ServiceResetCommand.java:[21,48] package org.apache.skywalking.apm.network.common does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/ServiceResetCommand.java:[34,29] package Command does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/EndpointResetCommand.java:[21,1] package org.apache.skywalking.apm.network.common does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/EndpointResetCommand.java:[35,29] package Command does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/NetworkResetCommand.java:[21,1] package org.apache.skywalking.apm.network.common does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/NetworkResetCommand.java:[35,29] package Command does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[21,1] package org.apache.skywalking.apm.network.common does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[34,29] package Command does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Deserializable.java:[21,48] package org.apache.skywalking.apm.network.common does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Deserializable.java:[27,22] cannot find symbol
[ERROR]   symbol:   class Command
[ERROR]   location: interface org.apache.skywalking.apm.network.trace.component.command.Deserializable
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[35,31] cannot find symbol
[ERROR]   symbol:   variable Command
[ERROR]   location: class org.apache.skywalking.apm.network.trace.component.command.BaseCommand
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[37,27] package KeyStringValuePair does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[37,48] cannot find symbol
[ERROR]   symbol:   variable KeyStringValuePair
[ERROR]   location: class org.apache.skywalking.apm.network.trace.component.command.BaseCommand
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/EndpointResetCommand.java:[40,27] package KeyStringValuePair does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/EndpointResetCommand.java:[40,48] cannot find symbol
[ERROR]   symbol:   variable KeyStringValuePair
[ERROR]   location: class org.apache.skywalking.apm.network.trace.component.command.EndpointResetCommand
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/NetworkResetCommand.java:[40,27] package KeyStringValuePair does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/NetworkResetCommand.java:[40,48] cannot find symbol
[ERROR]   symbol:   variable KeyStringValuePair
[ERROR]   location: class org.apache.skywalking.apm.network.trace.component.command.NetworkResetCommand
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[39,27] package KeyStringValuePair does not exist
[ERROR] /C:/workspace/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[39,48] cannot find symbol
[ERROR]   symbol:   variable KeyStringValuePair
[ERROR]   location: class org.apache.skywalking.apm.network.trace.component.command.TraceIgnoreCommand
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apm-network

**Comment by wu-sheng** [comment]
Please follow our compiling document.

**Comment by zhuangsheng** [comment]
I used apm-spring-cloud-gateway-2.x-plugin-6.2.0-SNAPSHOT.jar  in  plugins/  but ERROR 

`ERROR 2019-06-27 11:52:53:902 elastic-6 InstMethodsInter :  class[class reactor.netty.http.server.HttpServerOperations] before method[status] intercept failure
java.lang.ClassCastException: java.lang.Integer cannot be cast to io.netty.handler.codec.http.HttpResponseStatus
	at org.apache.skywalking.apm.plugin.spring.webflux.v5.StatusInterceptor.beforeMethod(StatusInterceptor.java:32)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
	at reactor.netty.http.server.HttpServerOperations.status(HttpServerOperations.java)
	at org.springframework.http.server.reactive.ReactorServerHttpResponse.applyStatusCode(ReactorServerHttpResponse.java:80)
	at org.springframework.http.server.reactive.AbstractServerHttpResponse.lambda$null$6(AbstractServerHttpResponse.java:221)
	at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
	at reactor.core.publisher.FluxConcatIterable$ConcatIterableSubscriber.onComplete(FluxConcatIterable.java:146)
	at reactor.core.publisher.FluxConcatIterable.subscribe(FluxConcatIterable.java:60)
	at reactor.core.publisher.MonoIgnoreElements.subscribe(MonoIgnoreElements.java:37)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
	at org.springframework.http.server.reactive.ChannelSendOperator$WriteBarrier.onNext(ChannelSendOperator.java:182)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1505)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
	at reactor.core.publisher.MonoSubscriberContext.subscribe(MonoSubscriberContext.java:47)
	at reactor.core.publisher.FluxSourceMonoFuseable.subscribe(FluxSourceMonoFuseable.java:38)
	at org.springframework.http.server.reactive.ChannelSendOperator.subscribe(ChannelSendOperator.java:75)`
