### ISSUE TITLE
can not get service info

### ISSUE THREAD

**Issue by GreyZeng** [apache/skywalking#2818]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.1.0

- Which company or project?
Spring boot

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
same version of skywalking
same spring boot project
use h2 database

A machine 
uname -r
4.9.0-3-amd64
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

B machine info:
uname -r
4.9.0-3-amd64
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

run spring boot in B machine:
nohup java -javaagent:/data/apps/skywalking/skywalking-agent.jar -jar echo.jar &

every thing is ok, we can see the info in web page

run spring boot in A machine:
nohup java -javaagent:/data/apps/skywalking/skywalking-agent.jar -jar echo.jar &

web is ok, but it can not show any service info

some error info:

{"errors":[{"message":"Variable 'serviceId' has coerced Null value for NonNull type 'ID!'"}]}

{"data":{},"errors":[{"message":"Exception while fetching data (/sla) : IDs can't be null"},{"message":"Exception while fetching data (/nodeCpm) : IDs can't be null"},{"message":"Exception while fetching data (/nodeLatency) : IDs can't be null"},{"message":"Exception while fetching data (/cpmS) : IDs can't be null"},{"message":"Exception while fetching data (/latencyS) : IDs can't be null"},{"message":"Exception while fetching data (/cpmC) : IDs can't be null"},{"message":"Exception while fetching data (/latencyC) : IDs can't be null"}]}

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please check your time and timezone.

**Comment by GreyZeng** [comment]
> Please check your time and timezone.
A machine
date -R
Tue, 04 Jun 2019 11:31:18 +0800

B machine 

date -R
Tue, 04 Jun 2019 11:31:55 +0800

**Comment by wu-sheng** [comment]
Check the data in ElasticSearch. It shows you the timestamp.

**Comment by GreyZeng** [comment]
i use h2

**Comment by GreyZeng** [comment]
> Check the data in ElasticSearch. It shows you the timestamp.

i use h2
