### ISSUE TITLE
alarm webhooks doesn't work

### ISSUE THREAD

**Issue by chenyh017** [apache/skywalking#2819]
I have already configured the webhooks. It also  had appeared several alarm informations too.But it didn't send any request to the webhhook the I had configured.It fthis is a bug or my configuration was wrong.Hoping for answer!Thanks!

the follow tow pictures is my webhooks configuration and alarm informations
![image](https://user-images.githubusercontent.com/15885112/58856236-b5a21d80-86d4-11e9-8454-7a1e8a5d85a9.png)

![image](https://user-images.githubusercontent.com/15885112/58856349-06197b00-86d5-11e9-8ef6-3c37e2b0968d.png)

**Comment by wu-sheng** [comment]
Webhook is very easy implementation. Could you try to debug? Last time I checked, it works.

**Comment by liushangdev** [comment]
@chenyh017  你的问题解决了吗,我也遇到同样的问题
