### ISSUE TITLE
if setup ttl both core:default and storage:elasticsearch on application.yml then which one will effective

### ISSUE THREAD

**Issue by lintghi** [apache/skywalking#2821]
application.yml

core:
  default:
    .....
    # Set a timeout on metric data. After the timeout has expired, the metric data will automatically be deleted.
    recordDataTTL: ${SW_CORE_RECORD_DATA_TTL:90} # Unit is minute
    minuteMetricsDataTTL: ${SW_CORE_MINUTE_METRIC_DATA_TTL:90} # Unit is minute
    hourMetricsDataTTL: ${SW_CORE_HOUR_METRIC_DATA_TTL:36} # Unit is hour
    dayMetricsDataTTL: ${SW_CORE_DAY_METRIC_DATA_TTL:45} # Unit is day
    monthMetricsDataTTL: ${SW_CORE_MONTH_METRIC_DATA_TTL:18} # Unit is month
storage:
  elasticsearch:
    ......
    # Those data TTL settings will override the same settings in core module.
    recordDataTTL: ${SW_STORAGE_ES_RECORD_DATA_TTL:7} # Unit is day
    otherMetricsDataTTL: ${SW_STORAGE_ES_OTHER_METRIC_DATA_TTL:45} # Unit is day
    monthMetricsDataTTL: ${SW_STORAGE_ES_MONTH_METRIC_DATA_TTL:18} # Unit is month

**Comment by wu-sheng** [comment]
Are you using master? Are you familiar with SkyWalking? Master is a dev branch.
We have described this in ttl document. Please read

**Comment by wu-sheng** [comment]
Elasticsearch ttl works. Again, make sure you understand whay skywalking is doing if you try master branch.

**Comment by lintghi** [comment]
sorry for the delay.  yes, using master.  understand now

**Comment by wu-sheng** [comment]
@lintghi Master ES storage is not stable, we are keeping fixing bugs in these days.
