### ISSUE TITLE
WebUI doesn't display very well for long package name

### ISSUE THREAD

**Issue by lintghi** [apache/skywalking#2822]
suggest:  show like "org.apache.skywalking.apm.util.ConfigInitializer" as  "o.a.s.a.u.ConfigInitializer"

![搜狗截图20190604121129](https://user-images.githubusercontent.com/2133947/58870983-c4e49380-86f3-11e9-9332-03d67cd68ec1.png)

![搜狗截图20190604121855](https://user-images.githubusercontent.com/2133947/58870268-784c8880-86f2-11e9-8ca2-29fa808e8f52.png)

**Comment by wu-sheng** [comment]
This is an improvement suggestion. @TinyAllen please see what you can do.

**Comment by TinyAllen** [comment]
The tooltip function already exists. Why do abbreviations ？May increase the difficulty of identification?
