### ISSUE TITLE
Let the entrySpan setPeer method support the topo diagram

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/skywalking#2823]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
In the zookeeper plugin, the watcher event is considered to be an entrySpan, but whether or not the peer is added will be considered a user call. See for details.
At MultiScopesSpanListener::parseEntry method
![image](https://user-images.githubusercontent.com/10150229/58874106-7c7ca400-86fa-11e9-93fb-e8a02845dee5.png)
I want to modify the judgment here, judge that there is no refCount, and there is no peer, it is the user behavior.
Is there a better way?

**Comment by wu-sheng** [comment]
That makes sense. But you should add this in plugin dev document. In entry span, only add peer when there is a server side, such as MQ.
