### ISSUE TITLE
Dynamic Configuration Apollo Support

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#2825]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement

related issue: #2816 #2810 

[Apollo](https://github.com/ctripcorp/apollo) is another popular configuration center, we'd better support it as well, I'm familiar with Apollo and I'd like to contribute on this feature :-)

**Comment by wu-sheng** [comment]
Appollo is new, so you need dependency and license check. I will out of work in 4 days, just access GitHun from cellphone.

**Comment by kezhenxu94** [comment]
> Appollo is new, so you need dependency and license check. I will out of work in 4 days, just access GitHun from cellphone.

Got it, hope things going well to you :-)

**Comment by JaredTan95** [comment]
👍 You are responding so quickly.

**Comment by R1hug0** [comment]
woo, nice idea!
