### ISSUE TITLE
Question about REST API Show on UI

### ISSUE THREAD

**Issue by ShakespeareFeng** [apache/skywalking#2833]
___
### Question
-  应用现有的api接口定义风格如: apihost.com/show/xxx ；由于path的xxx 参数不同，导致同一个接口在ui展示上，endpoint显示为多个，展示如下。

<img width="295" alt="WechatIMG19" src="https://user-images.githubusercontent.com/16386529/59015058-a3f57d00-8870-11e9-8918-876f919f2ab7.png">

### 背景
-  skywalking 版本6.1.0 

___
### Requirement or improvement
- 请问如何配置可以聚合一下展示呢？

**Comment by wu-sheng** [comment]
English only. This is not supported by configuration. You need to change sources of the plugin you used.
