### ISSUE TITLE
cannot build UI webapp, both on Windows and Linux

### ISSUE THREAD

**Issue by antoni-g** [apache/skywalking#2847]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

Current dev branch building, Windows 10 and also Ubuntu, both using JDK 8

- Which company or project?

Personal exploration for potential deployment

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

I have run the UI locally. However, I cannot build the entire project as the UI continously fails to building. I have tried this with multiple versions of Node (8.x.x to 11.x.x) and both on Windows 10 via Bash and Ubuntu. They all produce the same results. I know others have had this issue. I am mainly asking this issue for those who have had this and solved it, as there is no solution seemingly available. Build documents are being followed exactly, and all requisite programs have been cleaned and re-installed.

running ```./mvnw clean package -DskipTests``` produces the following output:

```ruby
...
[INFO] apm-webapp ......................................... FAILURE [03:19 min]
[INFO] apache-skywalking-apm 6.2.0-SNAPSHOT ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:03 min
[INFO] Finished at: 2019-06-10T20:28:21Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm run build) on project apm-webapp: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apm-webapp
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

A solution to this as I am otherwise unable to build the project.

**Comment by wu-sheng** [comment]
Is your network good? You could check our CI, we build the UI and whole project every time, and it must pass before merge. Also, in ASF, we checked the release compiling too.

**Comment by antoni-g** [comment]
Hi, 

To follow up after a whole night of debugging, I have found something. I do not know how to solve it, but certain internet networks can have a firewall configured that can block a specific port and not allow downloads for specific packages. I have found some solutions for other applications and tutorials where people have the same ```ruby Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm run build)``` which involve opening a specific port, but I do not know enough about networking to suggest this at my work. 

I fixed this by trying to compile at home, which had no problems. This network problem is unfortunately obfuscated by the not-so-helpful error messaging.

I know this is a common issue for many people from seeing the issues here, so I suggest to anyone if you do run into this issue to not fret and reinstall your node, npm versions etc. First try it on another network.

**Comment by wu-sheng** [comment]
@antoni-g Thanks so much for your detailed feedback. Also, you could try NPM mirror. There are some services provided by big enterprise or cloud vendor, but only in China as far as I know.

**Comment by xiaoy00** [comment]
I also cant package skywalking-ui,  same error as @antoni-g . 
then i uninstall npm and nodejs on my windows. 
it have a differrent error. 

`[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm install) on project apm-webapp: Failed to run task: 'npm install --registry=https://registry.npmjs.org/' failed. `

this is the debug.log 

`12748 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...qFGFLKaXNmJJmAWy\nEBk'
12748 verbose stack     at JSON.parse (<anonymous>)
12748 verbose stack     at parseJson (D:\JavaWork\apache-skywalking-apm-6.3.0\skywalking-ui\node\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-better-errors\index.js:7:17)
12748 verbose stack     at consumeBody.call.then.buffer (D:\JavaWork\apache-skywalking-apm-6.3.0\skywalking-ui\node\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
12748 verbose stack     at <anonymous>
12748 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
12749 verbose cwd D:\JavaWork\apache-skywalking-apm-6.3.0\skywalking-ui
12750 verbose Windows_NT 10.0.15063
12751 verbose argv "D:\\JavaWork\\apache-skywalking-apm-6.3.0\\skywalking-ui\\node\\node.exe" "D:\\JavaWork\\apache-skywalking-apm-6.3.0\\skywalking-ui\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "--registry=https://registry.npmjs.org/"
12752 verbose node v8.9.4
12753 verbose npm  v5.6.0
12754 error Unexpected end of JSON input while parsing near '...qFGFLKaXNmJJmAWy\nEBk'
12755 verbose exit [ 1, true ]`

**Comment by antoni-g** [comment]
https://github.com/eirslett/frontend-maven-plugin/issues/548

I found this issue to be helpful in resolving it

the package by eirslett referenced in skywalking (and many other applications) is specifically problematic for many users and the solution is obfuscated by the error messaging.

**Comment by zxeoc** [comment]
Another similar but not exactly the same problem:

> ...
[INFO] Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
[INFO] ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
[INFO] Error: Missing binding /path/to/skywalking/skywalking-ui/node_modules/node-sass/vendor/linux-x64-57/binding.node
[INFO] Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
[INFO] 
[INFO] Found bindings for the following environments:
[INFO]   - Linux 64-bit with Node.js 13.x
[INFO] 
[INFO] This usually happens because your environment has changed since running `npm install`.
[INFO] Run `npm rebuild node-sass` to download the binding for your current environment.
[INFO]     at module.exports (/path/to/skywalking/skywalking-ui/node_modules/node-sass/lib/binding.js:15:13)
...


The "Error: Missing binding" line indicate that node-sass didn't access the binding file. Downloading the file manually solve the problem.
