### ISSUE TITLE
Time series ElasticSearch implementation bug of record type

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#2851]
As the following screenshot shows, the segment(also alarm and other record types) don't create index by day, but in hour wrongly. 
![image](https://user-images.githubusercontent.com/5441976/59246051-b5ae9a00-8c4d-11e9-9f11-829f86ef0373.png)

This needs to be fixed and make sure the TTL works for it(not working today, possible because of wrong table name).

**Comment by peng-yongsheng** [comment]
Done.
