### ISSUE TITLE
use docker compose,it can not work ,org.elasticsearch.index.IndexNotFoundException: no such index

### ISSUE THREAD

**Issue by seasonouc** [apache/skywalking#2854]
https://github.com/apache/skywalking/blob/ce0513307aba846e4568b6fc5e949cd9426ca10a/docker/docker-compose.yml#L20

**Comment by wu-sheng** [comment]
What do you mean? SkyWalking create index automatically.

**Comment by seasonouc** [comment]
but when I execute the docker compose ,I can not see the data reported.when I see the log,it still log error

**Comment by wu-sheng** [comment]
I am not sure what the case. Could you show the log?
