### ISSUE TITLE
 OAP-backend throw NPE when choose all option to display alarm

### ISSUE THREAD

**Issue by flyingrainsky** [apache/skywalking#2865]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
 OAP-backend throw NPE when choose all option to display alarm
___
### Requirement or improvement
- check sql condition of scope in H2AlarmQueryDAO and MySQLAlarmQueryDAO

**Comment by wu-sheng** [comment]
Please search the issue first, this has been fixed.
