### ISSUE TITLE
  How to set alert for endpoint of specified service?

### ISSUE THREAD

**Issue by zhousiliang163** [apache/skywalking#2869]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

**Comment by wu-sheng** [comment]
Have you read the OAP server setup document? https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-setup.md

> 11. Alarm. Alarm provides a time-series based check mechanism. You could set alarm rules targeting the analysis oal metrics objects.

This includes the details.

**Comment by zhousiliang163** [comment]
> 
> 
> Have you read the OAP server setup document? https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-setup.md
> 
> > 1. Alarm. Alarm provides a time-series based check mechanism. You could set alarm rules targeting the analysis oal metrics objects.
> 
> This includes the details.


I do.But there is no mention of how to configure endpoint under specified service.
Not currently supported?

**Comment by wu-sheng** [comment]
> I do.But there is no mention of how to configure endpoint under specified service.
Not currently supported?

There is no such thing currently, I think.

**Comment by zhousiliang163** [comment]
> 
> 
> > I do.But there is no mention of how to configure endpoint under specified service.
> > Not currently supported?
> 
> There is no such thing currently, I think.



The endpoint under multiple services may be the same name

**Comment by wu-sheng** [comment]
> The endpoint under multiple services may be the same name

Yes. Maybe. I mean, we don't support it.
