### ISSUE TITLE
"apm-agent-5.0" lead to "SIGSEGV (0xb) at pc=0x0000000400000000, pid=14750, tid=140204925077248"

### ISSUE THREAD

**Issue by 18738529936** [apache/skywalking#2872]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why "apm-agent-5.0" can lead to My Java Application crash
___
### Bug
- Which version of SkyWalking, OS and JRE?
apm-agent-5.0/skywalking, OS:CentOS release 6.7 (Final), JRE version: Java(TM) SE Runtime Environment (8.0_25-b17) (build 1.8.0_25-b17)
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
When I request my service in POST sometimes, the crash will be found.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Now I removed the config from my start.sh, the application is going well.

**Comment by wu-sheng** [comment]
I am not familiar with this error. And don't know why.

**Comment by wu-sheng** [comment]
Have to set the core dump? Maybe there is a clue there.

**Comment by 18738529936** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    

    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        见信好！
                异常时生成的hs_err_pid.log及core dump文件在附件中，请查收。        根据core dump中“Core was generated by `/home/app/JDK1.8/bin/java -Dagent.application_code=cfs-dubbo-provider -javaagen'.Program terminated with signal 6, Aborted.#0  0x0000003371432625 in ?? ()”推测是由于启动脚本中增加的“-javaagent:/home/app/apm-agent-5.0/skywalking-agent.jar”引起的异常。        在启动脚本中去掉此配置之后，应用已正常，请知悉。
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2356999674
                            
                    
                        
                            
                                    2356999674@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 6/14/2019 13:27，吴晟 Wu Sheng<notifications@github.com> wrote： 


Have to set the core dump? Maybe there is a clue there.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wu-sheng** [comment]
@18738529936 I don't know how to respond. As an open source project, we need you to take part in. We are providing possible helps to work with you.

**Comment by wzhangNJ** [comment]
@id-zhq Have you solved this problem？

**Comment by Superskyyy** [comment]
> @id-zhq Have you solved this problem？We also encounter this situation.

It could be related to JDK version or implementation, try switch and see if the problem persist.

**Comment by wzhangNJ** [comment]
I solved , threadpool Component & slf4j cause exception
