### ISSUE TITLE
I can't find the article  “Performance Test”.

### ISSUE THREAD

**Issue by gzshilu** [apache/skywalking#2876]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 I found the article **‘Performance Test’** in docs some time ago.but can't find int now because the old link can't be opened.  Can you give it to me? many thanks.

**Comment by wu-sheng** [comment]
Go to agent setup document. They are at the bottom of the page.

**Comment by gzshilu** [comment]
many thanks , i found it  now.
