### ISSUE TITLE
To make the BufferStratrgy configurable

### ISSUE THREAD

**Issue by tzy1316106836** [apache/skywalking#2877]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
When I want to change the BufferStrategy, I need to modify the code and get a new jar. Can it be made configurable?

**Comment by wu-sheng** [comment]
What strategy do you want? It is binding the implementation.

**Comment by tzy1316106836** [comment]
Before sending the data, the segment data was saved in the buffer. The buffer supports several strategy when buffer is full, such as BLOCKING,OVERRIDE,IF_POSSIBLE, and the Default is BLOCKING. When I make a jar package, the BufferStragy can not modify, this can not meet all requirements. So I want to make it configurable.

**Comment by wu-sheng** [comment]
That is meanless. And for agent, the default is not blocking. Please read the codes. 
We have chosen the most reasonable one. Why need config to make unexpected result?
