### ISSUE TITLE
程序包org.apache.skywalking.apm.network.common不存在

### ISSUE THREAD

**Issue by yuanx1** [apache/skywalking#2883]
import org.apache.skywalking.apm.network.common.Command;确实不存在～！

**Comment by yuanx1** [comment]
导致编译报错～！

**Comment by kezhenxu94** [comment]
> import org.apache.skywalking.apm.network.common.Command;确实不存在～！

@yuanx1 ENGLISH ONLY PLEASE.

And read the documentation (How to Build) carefully, they are automatically generated by protoc, read the documentation

**Comment by yuanx1** [comment]
@kezhenxu94  Thank you~!

**Comment by yuanzhehong111** [comment]
@yuanx1          I want to know how you solved it . thank you.

**Comment by MajaChen** [comment]
I am pretty sure that this problem is caused by submodule not being init;
enter the base directory,and execute:
git submodule init
git submodule upadte

these commands will download code for proto

**Comment by CzyerChen** [comment]
I got the problem, and solved in this way.
1. remove related submodule dirs which you can see from config file.
some of them may be blank.
.gitmodules
```text
[submodule "apm-protocol/apm-network/src/main/proto"]
	path = apm-protocol/apm-network/src/main/proto  -----here
	url = https://github.com/apache/skywalking-data-collect-protocol.git
[submodule "oap-server/server-query-plugin/query-graphql-plugin/src/main/resources/query-protocol"]
	path = oap-server/server-query-plugin/query-graphql-plugin/src/main/resources/query-protocol  -----here
	url = https://github.com/apache/skywalking-query-protocol.git
[submodule "test/e2e-v2/java-test-service/e2e-protocol/src/main/proto"]
	path = test/e2e-v2/java-test-service/e2e-protocol/src/main/proto  -----here
	url = https://github.com/apache/skywalking-data-collect-protocol.git
[submodule "skywalking-ui"]
	path = skywalking-ui  -----here
	url = https://github.com/apache/skywalking-booster-ui.git

```
2. do `git  submodule init` and `git submodule update` again. Make sure that the submodule dirs are not blank
3. then follow the instruction to  do `./mvnw clean package -Dmaven.test.skip`. 
Hope you success
