### ISSUE TITLE
An additional alarm

### ISSUE THREAD

**Issue by xiaowei-ww** [apache/skywalking#2889]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ * ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can you provide warning notice?Such as nails, text messages, emails and so on.

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
I hope to have this function, hope the official add.

**Comment by wu-sheng** [comment]
> Can you provide warning notice?Such as nails, text messages, emails and so on.

We have webhook already. You could easily implement by yourself.
