### ISSUE TITLE
elasticserarch crashed

### ISSUE THREAD

**Issue by ywf4026** [apache/skywalking#2890]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

es runs a long time, and I think it was crashed by oom.
My es memory config is 2G, es version is 6.5.4, oap version is 6.0.0-GA.

Here is the gc log info when es crashed:
![image](https://user-images.githubusercontent.com/3722641/59591973-a930b280-9121-11e9-86fc-d112588aef7d.png)

Here is the heap info when es crashed:
![image](https://user-images.githubusercontent.com/3722641/59591596-dd57a380-9120-11e9-993d-069b58cfe52d.png)

How can I find the cause?
thanks!

**Comment by wu-sheng** [comment]
Could you try our master branch? We are aware of this when your ES is in limited resources. So we change the implementation now.

**Comment by ywf4026** [comment]
thanks, I will try master branch.
May I know which pr fixed this problem?

**Comment by wu-sheng** [comment]
This is not a change. It is a feature improvement through several PRs.
