### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by yuanx1** [apache/skywalking#2892]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project apm-util: Compilation failure: Compilation failure:

**Comment by kezhenxu94** [comment]
> Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project apm-util: Compilation failure: Compilation failure:

@yuanx1 can you please attach more error message?

**Comment by yuanx1** [comment]
@kezhenxu94 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.737 s
[INFO] Finished at: 2019-06-18T08:44:02+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project apm-util: Compilation failure: Compilation failure: 
[ERROR] 不再支持源选项 6。请使用 7 或更高版本。
[ERROR] 不再支持目标选项 6。请使用 7 或更高版本。
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apm-util

**Comment by yuanx1** [comment]
Run ./mvnw clean package -DskipTests

**Comment by wu-sheng** [comment]
Are you using JDK8 or JDK11(I guess this)?

**Comment by yuanx1** [comment]
JDK8

**Comment by wu-sheng** [comment]
Why a JDK8 doesn't allow compile in Java6 level? I don't know that before.
