### ISSUE TITLE
Dynamic configuration Redis support

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/skywalking#2894]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

### Requirement or improvement

Since dynamic configuration is supported in #2810, I'll provide a Redis implementation.

**Comment by wu-sheng** [comment]
I am not sure redis is a good one to do register center. There are plenty of them already, I think the user could easily implement their own. Could you just ignore this?

**Comment by zhaoyuguang** [comment]
OK
