### ISSUE TITLE
Dynamic Configuration Consul support

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/skywalking#2895]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

### Requirement or improvement

Since dynamic configuration is supported in #2810, I'll provide a Consul implementation.

**Comment by wu-sheng** [comment]
Haha, you are going to implement all possible implementations I listed there. :P
