### ISSUE TITLE
Is it possible to have the function of Apdex

### ISSUE THREAD

**Issue by smooth00** [apache/skywalking#2904]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
Is it possible to have the function of Apdex? Skywalking is a wonderful product, but what a pity that I have not found the  Apdex (Application Performance Index).  We pretty need this function because we often use it to evaluate our software performance such as "satisified, tolerating, frustrated", etc. 
To make my description clear, in below/uploaded is an example of our normal use:
![1](https://user-images.githubusercontent.com/43713947/59689855-f6408180-9212-11e9-8ef7-a3c5c26a8d0d.png)

**Comment by wu-sheng** [comment]
Contributions are welcome, we have no plan to do this yet.

**Comment by smooth00** [comment]
Thank you all the same.

**Comment by wu-sheng** [comment]
Apdex function will be added in 6.6.0 release. If no one contributed before that, the committer team will do. @Fine0830 @x22x22 @TinyAllen I will coordinate this at the UI side too.

**Comment by hanahmily** [comment]
Add #3822 to address this issue.
