### ISSUE TITLE
storage 配置mysql后，collector启动不起来

### ISSUE THREAD

**Issue by Abigdataexplorer** [apache/skywalking#2906]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- storage 配置mysql后，collector启动不起来

**Comment by wu-sheng** [comment]
English only. We have documents to describe the MySQL storage already.

**Comment by Abigdataexplorer** [comment]
Can you share the connection about mysql do storage article? thank you

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#mysql

I highly recommend you to read all document.

**Comment by yaohuan** [comment]
If the configuration is correct,The Installation path of Skywalking  cannot contain spaces, for example D:\Program Files\apache-skywalking-apm-bin will fail,D:\apache-skywalking-apm-bin will succeed.

**Comment by yaohuan** [comment]
> Please answer these questions before submitting your issue.
> 
> * Why do you submit this issue?
> * storage 配置mysql后，collector启动不起来

安装路径有空格就会出现CMD窗口一闪而过，启动不起来。
