### ISSUE TITLE
[BUG] Can not locate agent jar file

### ISSUE THREAD

**Issue by zou79189747** [apache/skywalking#2907]
when i use grpc register service find a problem，in my project add pom
<dependency>
    <groupId>org.apache.skywalking</groupId>
    <artifactId>apm-agent-core</artifactId>
    <version>6.1.0</version>
</dependency>
and apm-agent-core.jar in WEB-INF/lib/
use main func run GRPCChannelManager connect success
but build my project as war in tomcat run connect fair  
error:Can not locate agent jar file
i found AgentPackagePath.findPath use ClassLoader.getSystemClassLoader.getResource get URL
in my project return null so get error:Can not locate agent jar file
i change this code to 
URL resource = ClassLoader.getSystemClassLoader().getResource(classResourcePath); 
if (resource == null) {
   resource = AgentPackagePath.class.getClassLoader().getResource(classResourcePath); 
}
in tomcat run connect success
but i am not sure this way is the best  can your give me some suggest

**Comment by wu-sheng** [comment]
Don't put agent.jar or any other SkyWalking plugin jars in your classpath. SkyWalking loads them automatically.

**Comment by zou79189747** [comment]
我这边的场景是全链路分析，有C写的网关，有java写的微服务，java微服务那快没什么问题直接-javaagent就可以了，但是C这边我们的方案是 通过一个掉用一个java后台提过的http接口来注册服务， 该接口调用skywalking grpc 来注册服务，提过java接口的后台是一个web工程，且在tomcat catalin.bat里面没有使用-javaagent ，这个场景下我就引用了apm-agent-core这个依赖，调用doServiceRegister注册服务，然后在tomcat环境下 报Can not locate agent jar file这个错，调试发现URL resource = ClassLoader.getSystemClassLoader().getResource(classResourcePath); resource为null ,想请问一下这个场景我修改源码有问题吗，还是有其他更好的方式解决

**Comment by wu-sheng** [comment]
English only. I have said what is the issue. `-javaagent` is also needed in Tomcat, and don't put agent in Tomcat lib or your application lib, a.k.a. not in any classpath of JVM.

**Comment by zou79189747** [comment]
thanks ! as you said do , it is ok now.  but this way i have to use skywalking in my web project , this data is not needed

**Comment by wu-sheng** [comment]
> thanks ! as you said do , it is ok now. but this way i have to use skywalking in my web project , this data is not needed

What do you mean `data is not needed`? Confusing.

**Comment by zou79189747** [comment]
I don't need use skywalking to monitor the web project , if add -javaagent in tomcat  , it will send my web project monitor data to ES , like Service 、ServiceInstance 、segment , this datas is no use to me.

**Comment by wu-sheng** [comment]
I am totally lost. If you don't need, why add SkyWalking there? Why ask a question in SkyWalking community?

**Comment by zou79189747** [comment]
I use SkyWalking in other Microservices ，In this web project just provide restful Interface to Third party，help them  register service 、serviceInstance  and send trace segment to skywalking storage ，this web project it's not must be monitor

**Comment by wu-sheng** [comment]
The same question, if you don't need it, just don't attach the agent to JVM.

Are you asking severl web apps in one Tomcat container? Some are monitoring targets, others are not? I am just guessing because you don't give me a very clear context.
