### ISSUE TITLE
Whether to support historical data query for a specified time period

### ISSUE THREAD

**Issue by joewee** [apache/skywalking#2909]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Whether to support historical data query for a specified time period
___
### Bug
- Which version of SkyWalking, OS and JRE?
   6.1.0
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We supported historical query of all from day one. I am not following your question.
