### ISSUE TITLE
Agent's logs appear in app's logs

### ISSUE THREAD

**Issue by pmq5205209** [apache/skywalking#2916]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

We use skywalking 6.1.0. We find agent's logs appear is app's logs. 
![图片](https://user-images.githubusercontent.com/19252220/59832383-54d24080-9376-11e9-8dbc-815f8619fe0f.png)
From the image , we can see that the logs is belong to io.grpc.netty.NettyClientHandler. Besides, I find the class of printing the logs is io.netty.handler.codec.http2.Http2FrameLogger.

**Comment by wu-sheng** [comment]
Read this. https://github.com/apache/skywalking/blob/master/docs/en/FAQ/Too-many-gRPC-logs.md 
Just simply filter it.
