### ISSUE TITLE
ModuleProvider is reloaded many times

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#2918]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I noticed that we call `ServiceLoader.load(ModuleProvider.class)` by every modules. In my memory, it will reload the `services` and re-instance.
I am not sure that is really required. Maybe we load the service once.

[ModuleDefine#perpare(...)](
https://github.com/apache/skywalking/blob/master/oap-server/server-library/library-module/src/main/java/org/apache/skywalking/oap/server/library/module/ModuleDefine.java#L63)

**Comment by wu-sheng** [comment]
This is a bug, we only need load once. Would do fix this?

**Comment by dmsolr** [comment]
Yes, i could.
