### ISSUE TITLE
In ElasticSearch,Why segment index don't create with date

### ISSUE THREAD

**Issue by zou79189747** [apache/skywalking#2919]
use elasticsearch to store data, every day trace  data is very large and save time is very long , skywalking just use one segment index to save trace data ,when data more and more , it will be a problem, so guys , how to resolve? Normally create index with date ,one day one index eg: segment_2019-06-21

**Comment by wu-sheng** [comment]
Read master document and codes, this change has been done.

**Comment by zou79189747** [comment]
ok ，thinks！
