### ISSUE TITLE
6.1.0 Mac OS the UI can display service trace info while console log TID:N/A

### ISSUE THREAD

**Issue by albertcoolsea** [apache/skywalking#2921]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
 Question or discussion

___
### Question
- What do you want to know?
6.1.0 Mac OS the UI can display service trace info while console log TID:N/A
so,is the tracing inactive? or some other problems cause the situation?
how to solve it ,thakns!
___

**Comment by wu-sheng** [comment]
N/A means this is no active tracing context. Maybe you are using this in an async thread.
