### ISSUE TITLE
Can skywalking integrate with logstash or kafka?

### ISSUE THREAD

**Issue by tianma0314** [apache/skywalking#2924]
### Question
- now the skywalking's data is stored in es,but we think  it's too slow to export data to hive,so could you please tell me if sw can integrate with logstash or kafka?thta's may be faster.
and if the answer is 'yes',is there any demo?or just give me some train of thought,thanks a lot

**Comment by wu-sheng** [comment]
What kinds of data do you want to export? Is ElasticSearch still being used for SkyWalking UI?

**Comment by dmsolr** [comment]
i think mq is unfriendly for ad-hoc query.

**Comment by tianma0314** [comment]
> What kinds of data do you want to export? 
some field name as follows:
traceId
segmentId
spanId
parentSpanId
refs
serviceCode
startTime
endTime
endpointName
type
peer
component...and so on

>Is ElasticSearch still being used for SkyWalking UI?
I know that es perfomes the role as the metastore of SW, so...maybe it's used for UI,not sure,I am fresh ,sorry for that...

**Comment by tianma0314** [comment]
> i think mq is unfriendly for ad-hoc query.

we are building a data warehouse on hive, we need some data from skywalking,but I tried es-hive integration,it was too slow,so I am looking for some other ways like kafka or logstash->kafka

**Comment by wu-sheng** [comment]
Then this is not going to work easily. Hive can't and shouldn't be considered as SkyWalking storage. If you understand SkyWalking aggregates models, you should know why.

From your reply, you are treating SkyWalking ad simple tracing system, it isn't. Read our development document of storage extension, we highlight the required features of storage.
