### ISSUE TITLE
Can skywalking add support to start agents after the VM has started？

### ISSUE THREAD

**Issue by bugmakesprogress** [apache/skywalking#2929]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

We have many project wants to use skywalking. However, there will be too many agent.config files if one project with one config file. So can skywalking add support to start agents after the VM has started? By doing so I can define agent.config in my application.
eg:
        System.setProperty("skywalking.agent.service_name","config_tes");
        System.setProperty("skywalking.agent.sample_n_per_3_secs","-1");
        System.setProperty("skywalking.collector.backend_service","ip:port");
        System.setProperty("skywalking.logging.level","ERROR");

Key word: Agent-Class 
https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/package-summary.html
Starting Agents After VM Startup

**Comment by wu-sheng** [comment]
No, we can't. Config file could be used in default. Using system properties and env to override.
You get the bootstrap sequence wrong.

**Comment by dmsolr** [comment]
you can config it by VM argument in launching script.

starting Agent after VM startup and before your main method.
