### ISSUE TITLE
skywalking UI showing service count is 0 , one agent is configured.

### ISSUE THREAD

**Issue by jatin85** [apache/skywalking#2942]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
I have setup the apache skywalking on my local VM box  on which docker conatiner is running which having the skywalking agent and VM having backend and UI running.
But that agent service is not visible in skywalking UI.
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If you have verified there is data in storage, read the first line of setup document, make sure your time and time zone of agent and OAP are as same as your browser. Or set browser UTC time(in UI) to match those.
