### ISSUE TITLE
Lots of null pointer execeptions after lose of ES data

### ISSUE THREAD

**Issue by evanxuhe** [apache/skywalking#2945]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

### Bug
- Which version of SkyWalking, OS and JRE?
Lots of null pointer execeptions after lose of ES data
Because of some reasons, es data is lost while there are lots of errors repoted in oap.
After debug to oap. I found that it is because ```serviceInventoryCache.get(sourceBuilder.getSourceServiceId())```return null and after that call get Name.
**I assume it is because es has lost the instance inventory but agent still cache its instance id info and send to oap. obviously. no instance id exits in oap now.**
And i think that **oap and agent should abondon all the out-of-date segment  rather than throw exceptions ,and rebuild trace info  or recreate instance info in oap considering es data has been lost**. If my understanding is right? And if there is some method to make all agents clear cached segments before.

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

## log info
```
2019-06-25 17:18:47,350 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMSourceDispatcher - 51 [grpc-default-executor-60] WARN  [] - Can't found service by service instance id from cache, service instance id is: 632
2019-06-25 17:18:47,352 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 114 [grpc-default-executor-67] ERROR [] - null
java.lang.NullPointerException: null
2019-06-25 17:18:47,357 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 114 [grpc-default-executor-67] ERROR [] - null
java.lang.NullPointerException: null
2019-06-25 17:18:47,360 - org.apache.skywalking.oap.server.core.remote.client.GRPCRemoteClient - 182 [DataCarrier.GRPCRemoteClient.Consumser.0.Thread] WARN  [] - Remote client block times over 60 seconds.
2019-06-25 17:18:47,360 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 114 [grpc-default-executor-67] ERROR [] - null
java.lang.NullPointerException: null
2019-06-25 17:18:47,365 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 114 [grpc-default-executor-67] ERROR [] - null
java.lang.NullPointerException: null
2019-06-25 17:18:47,369 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 114 [grpc-default-executor-67] ERROR [] - null
```
nulll pointer exception throwed in getName () in first line below inorg.apache.skywalking.oap.server.receiver.trace.provider.parser.listener.endpoint.MultiScopesSpanListener
```java
        sourceBuilder.setSourceServiceName(serviceInventoryCache.get(sourceBuilder.getSourceServiceId()).getName());
        sourceBuilder.setSourceServiceInstanceName(instanceInventoryCache.get(sourceBuilder.getSourceServiceInstanceId()).getName());
        sourceBuilder.setSourceEndpointName(endpointInventoryCache.get(sourceBuilder.getSourceEndpointId()).getName());
        sourceBuilder.setDestServiceName(serviceInventoryCache.get(sourceBuilder.getDestServiceId()).getName());
        sourceBuilder.setDestServiceInstanceName(instanceInventoryCache.get(sourceBuilder.getDestServiceInstanceId()).getName());
        sourceBuilder.setDestEndpointName(endpointInventoryCache.get(sourceBuilder.getDestEndpointId()).getName());
```

![image](https://user-images.githubusercontent.com/24379174/60086506-c0991c80-976d-11e9-90d4-7432e7558528.png)

**Comment by wu-sheng** [comment]
It is the reason you said. We don't support hot-auto-reboot agent to trigger register. Maybe in the next several versions.

**Comment by evanxuhe** [comment]
> It is the reason you said. We don't support hot-auto-reboot agent to trigger register. Maybe in the next several versions.

Oh It is pity. I think it will be better. 
After. I will try to find some methods to fix it .Cause **it may be a nightmare if oap lose ES data, especially in product env.**
Cause i have deployed sw into dev env and I cant force everyone to reboot. And after losing es data. incredible amount of error data pouring in.
What's more another problem may be related to this.
lot of question marks may be due to lose of instance info before in ES.

![image](https://user-images.githubusercontent.com/24379174/60089912-0d7ff180-9774-11e9-9210-75a605720533.png)

**Comment by wu-sheng** [comment]
We have plan, but still work in progress. 4 inventory indexes are only thing required safe. From our practices, we don't face that seriously. So PR works not that fast.

**Comment by wu-sheng** [comment]
If there is no entry span happens in a node, or component does not have icon in UI. Question mark shows up.

**Comment by evanxuhe** [comment]
> If there is no entry span happens in a node, or component does not have icon in UI. Question mark shows up.

I am quite sure there are entry span, like http request. but some apps displays normaly as springmvc while some can't catch entry request. I am confused about this. I wanna know it may be related to the data lack of ES stored before?

**Comment by wu-sheng** [comment]
I am not sure, actually. You have to dig the data stored in ES, and find out why.
