### ISSUE TITLE
UI http://example/trace refresh 401

### ISSUE THREAD

**Issue by Arugal** [apache/skywalking#2948]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
 6.1.0
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

<img width="1674" alt="step1" src="https://user-images.githubusercontent.com/26432832/60154088-e5969980-9818-11e9-875a-d6be25d192b8.png">
<img width="1676" alt="step2" src="https://user-images.githubusercontent.com/26432832/60154094-e8918a00-9818-11e9-8a40-52da86ed5590.png">

**Comment by wu-sheng** [comment]
Please search error before submit a new one. We have fixed this in master several weeks ago.
