### ISSUE TITLE
调用链追踪时间总时间数有问题

### ISSUE THREAD

**Issue by pengzhoushuo** [apache/skywalking#2951]
你好，我的login方法是数据库操作 + redis操作 + HttpClient远程调用另一个系统的Rest接口，
但在追踪功能中不展示HttpClient调用的节点操作。
如下图：
<img width="707" alt="1" src="https://user-images.githubusercontent.com/18159632/60179386-2b228900-9850-11e9-96fc-3c703decee9c.png">
<img width="688" alt="2" src="https://user-images.githubusercontent.com/18159632/60179396-2e1d7980-9850-11e9-84da-6753b6f167a5.png">
<img width="685" alt="3" src="https://user-images.githubusercontent.com/18159632/60179411-31186a00-9850-11e9-8fa7-f24fd82ffeee.png">
<img width="695" alt="4" src="https://user-images.githubusercontent.com/18159632/60179416-32e22d80-9850-11e9-8be8-0e7306f06683.png">

总时间是：1738 ms
将每个节点加起来是 100多ms
剩下1000多ms的操作不知道花在什么操作上了，代码是HttpClient调用另一系统的Rest接口了，但未展示出来。请问下这个是bug吗？

**Comment by wu-sheng** [comment]
English only.
