### ISSUE TITLE
set storage provider to mysql collector error.

### ISSUE THREAD

**Issue by ccvcd** [apache/skywalking#2958]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking6.1.0 windows10 jdk1.8 mysql5

- What happen?
set storage provider to mysql collector error.
find "Specified key was too long; max key length is 767 bytes." message in "skywalking-oap-server.log " file.

**Comment by ccvcd** [comment]
if mysql charset set UTF8 will appear this error.

**Comment by litaiqing** [comment]
mysql5.6有问题

**Comment by litaiqing** [comment]
> mysql5.6有问题

正如楼主说的设置为非UTF编码就OK了，不过还是去掉300的索引吧，真滴想不通255的索引还不够用？
