### ISSUE TITLE
Chinese garbled of alarm message 

### ISSUE THREAD

**Issue by unhappydepig** [apache/skywalking#2967]
- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking6.1.0
- Which company or project?
zdp
- What happen?
I configure Chinese warning message in alarmRule, But the message I received on the server is garbled.
![image](https://user-images.githubusercontent.com/5573215/60378180-2842b680-9a51-11e9-8561-bd451a43eee2.png)
By looking at the source code[org.apache.skywalking.oap.server.core.alarm.provider.WebhookCallback ], I learned that we used StringEntity to transfer information, but did not specify the encoding.
![image](https://user-images.githubusercontent.com/5573215/60378202-925b5b80-9a51-11e9-908a-147cb7448821.png)

**Comment by wu-sheng** [comment]
All SkyWalking codes and settings are in UTF-8 by default. So we don't set those explicitly. Which encoding are .you using at server side?

**Comment by unhappydepig** [comment]
The charset for my server is UTF-8 and runs the test case. When I manually specify the encoding format as UTF-8. The server can respond normally.
![image](https://user-images.githubusercontent.com/5573215/60379073-e456ae00-9a5e-11e9-9b2d-8151059d0471.png)

At the same time I noticed. If no charset is specified, the default encoding format of “StringEntity” is “HTTP.DEF_CONTENT_CHARSET” and the variable defaults to “ISO-8859-1”
![image](https://user-images.githubusercontent.com/5573215/60379103-41eafa80-9a5f-11e9-910c-e5407cae7a88.png)

![image](https://user-images.githubusercontent.com/5573215/60379132-dc4b3e00-9a5f-11e9-8b4b-a02142df893f.png)

**Comment by wu-sheng** [comment]
We are open to accepting your pull request, please submit you.

**Comment by wu-sheng** [comment]
@unhappydepig, Will you submit a pull request to fix this?
