### ISSUE TITLE
SpringMVC plugin not support servlet-api-2.5

### ISSUE THREAD

**Issue by JoshShaw** [apache/skywalking#2975]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- SkyWalking 6.1.0
- OS CentOS
- JRE 1.8

- What happen?
A springMVC webapp project is running with a Web Container. In my case, it is running with Weblogic11g which is implemented based on servlet-api-2.5. I had review the source code of springmvc plugin and found out it is implemented based on servlet-api-3.0.1.
Therefore, when `org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.AbstractMethodInterceptor.afterMethod ` calls `HttpServletResponse.getStatus()`, it will throw NoSuchMethodException.

**Comment by wu-sheng** [comment]
I think we need a `witness class` to set two interceptors for different servlet-api versions.

**Comment by candyleer** [comment]
A simple way is to add a judgement for `HttpServletResponse. getStatus ` if it is exists ,I can solve this.

**Comment by wu-sheng** [comment]
> A simple way is to add a judgement for HttpServletResponse. getStatus if it is exists ,I can solve this.

What kind of judgement? Doing a refactor checker?

**Comment by candyleer** [comment]
I mean just add a `if`,such as 
![image](https://user-images.githubusercontent.com/11530760/61388341-5269f480-a8ea-11e9-8e53-0179b28b4be2.png)
cause for servlet below version 3 just not have `getStatus` method which we used ,this method will effect `springMvc`,`tomcat`,`jetty`.

So in servlet2.5,we just ignore the status judge and stop span .

**Comment by wu-sheng** [comment]
OK, that is a tricky thing to JVM, using a fast fail to acoid the issue. I guess it should work.

Please test it, if pass as expected, submit the PR.

**Comment by wu-sheng** [comment]
Fixed.
