### ISSUE TITLE
Improve backend operability

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#2977]
There're some feedbacks from the community about how to monitor or debug online. So I create this issue to trace a series of PRs to improve operability.

 - [ ] self-monitoring, monitoring/alerting key metrics of OAP and Storage.
 - [ ] searching metadata(service, instance and endpoint) without duration, that help operator to find when/in which time duration the data is available.

If anyone has some thoughts, I'm open to your new ideas about this topic, thanks.

**Comment by wu-sheng** [comment]
I think we have metrics for OAP self-observability. Which metrics are you proposing?

**Comment by hanahmily** [comment]
Now I supported prometheus exporter format, for o11y available, we should deploy prometheus server with oap backend.
Using another o11y tool to observe a o11y tool is little wired, and especially their capability overlaps.

So my plan is fetching current self-metrcs + storage-metrics(es cpu,mem,gc etc) to oap receiver, then use graphql to query
a time series result.



Hongtao Gao

Apache SkyWalking && Apache ShardingSphere
Twitter, @hanahmily

**Comment by wu-sheng** [comment]
So, you are proposing an ES storage implementation for metrics? and query extension for that?

**Comment by wu-sheng** [comment]
Do you want to set up a new OAP to do that? Or just using the current OAP to storage and read?

**Comment by hanahmily** [comment]
yes, I intend to extend ES storage to support new metrics that don't belong to OAL.

but current query schema is enough for those metrics, well, I’m going to proposal some new query
for metadata though.

**Comment by hanahmily** [comment]
I hope they will be part of current OAP.

**Comment by wu-sheng** [comment]
Please be advised, the telemetry is a very basic module, even core depends on it, so you can't call storage module services.

**Comment by hanahmily** [comment]
Got it. That means if I invoke storage in telemetry, maybe there will be a cycle dependency, right?

So my current idea is to create a new receiver, that pull the metrics from telemetry through local network or api.

Can it work, or not?

**Comment by wu-sheng** [comment]
@hanahmily I am moving this to 6.5 again, as it is not updated recently.
