### ISSUE TITLE
nacos dose not has the impl of ModuleProvider so it will be interdict by ProviderNotFoundException: cluster module no provider exists.

### ISSUE THREAD

**Issue by Dauber01** [apache/skywalking#2978]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Which version are you using? Nacos is new in 6.2.0.

**Comment by Dauber01** [comment]
6.1.0,thank you for your response

**Comment by wu-sheng** [comment]
For each version, read document in that tag. Master branch doc is for latest codes.

**Comment by Dauber01** [comment]
sorry, i have read zhe doc for index page ,but not for 6.x branch

**Comment by wu-sheng** [comment]
I guess so. Choose tag, we don't have branch for each version.

**Comment by Dauber01** [comment]
i know now ,thank you
