### ISSUE TITLE
  Some log buried points have problems

### ISSUE THREAD

**Issue by zhousiliang163** [apache/skywalking#2979]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking:v6.1.0
jre:1.8

- What happen?

follow:
![图片](https://user-images.githubusercontent.com/7529190/60432555-29343d80-9c35-11e9-8c0f-8a498cead040.png)
when log buried points,their name is not same at the place marked in the picture.
When it leads to problem tracking, it's not good.

**Comment by wu-sheng** [comment]
What is log buried point?

**Comment by wu-sheng** [comment]
You mean the log class name? You could send a pull request to fix this.

**Comment by wu-sheng** [comment]
In oss project, we are looking forward everyone to take part in.

**Comment by zhousiliang163** [comment]
> 
> 
> You mean the log class name? You could send a pull request to fix this.

Yes.I will fix it
