### ISSUE TITLE
Pulling oap (skywalking/oap:). ERROR

### ISSUE THREAD

**Issue by DavenAaron** [apache/skywalking#2981]
Pulling oap (skywalking/oap:)...
Trying to pull repository docker.io/skywalking/oap ...
ERROR: repository docker.io/skywalking/oap not found: does not exist or no pull access

**Comment by kezhenxu94** [comment]
@DavenAaron seems you are finding `apache/skywalking-oap-server`

https://hub.docker.com/r/apache/skywalking-oap-server

```shell
docker pull apache/skywalking-oap-server
```
