### ISSUE TITLE
why OAPServerStartUp will be killed multiple times？

### ISSUE THREAD

**Issue by ljh205sy** [apache/skywalking#2985]
ps -ef | grep "org.apache.skywalking.oap.server.starter.OAPServerStartUp" | grep -v grep | awk '{print $2}' | xargs kill -9

I will kill multiple times but the process start go on， how  to kill this processing?

**Comment by zhaoyuguang** [comment]
ps -ef | grep "skywalking-webapp.jar" | grep -v grep | awk '{print $2}'| xargs kill -9
