### ISSUE TITLE
Does apm-toolkit-log4j-1.x has a central warehouse?

### ISSUE THREAD

**Issue by zhousiliang163** [apache/skywalking#2990]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Do we use maven to install it,before i want to use apm-toolkit-log4j-1.x plugin?

**Comment by wu-sheng** [comment]
You could easily search it on Maven Central. 
https://mvnrepository.com/artifact/org.apache.skywalking/apm-application-toolkit
