### ISSUE TITLE
apache/skywalking-oap-server:6.2 images in docker hub is not found

### ISSUE THREAD

**Issue by daigong** [apache/skywalking#2991]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
 docker hub images not found
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.2

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
when I pull apache/skywalking-oap-server:6.2.0, it's not found

use dockerfile in github is ok

**Comment by hanahmily** [comment]
In short it have not been pushed to DockerHub.

Docker image is not a part of Apache Release. I usually push it in a week
after official release.

Please subscribe development mail list then you can get notification when
it's available

**Comment by daigong** [comment]
thanks 👍
