### ISSUE TITLE
[segmentId] was copied on dashboard page but [traceId] is actually useful for seaching trace

### ISSUE THREAD

**Issue by WangSZ** [apache/skywalking#2993]
### Requirement or improvement
As you see ,I need traceId to search ,but I got segmentId copied on dashboard. I think traceId should be in the clipboard

![image](https://user-images.githubusercontent.com/1385039/60568590-dc20aa80-9d9f-11e9-91e5-b470a50e2cba.png)

![image](https://user-images.githubusercontent.com/1385039/60568829-800a5600-9da0-11e9-8de5-930686a18932.png)

**Comment by wu-sheng** [comment]
Yes, this is a bug.

**Comment by wu-sheng** [comment]
@TinyAllen `traceIds` is the one you should copy in UI. Pick the first one, please.

**Comment by luzhen328** [comment]
I think the copy function should remain the same, but you can jump to the trace UI by clicking endpoint and search by traceId.

**Comment by wu-sheng** [comment]
No, segment ID can't be used in trace query, which is the original design of the copy.

We have some alternative ways, but still, this should be tagged as a bug.
