### ISSUE TITLE
 the server could not find the requested resource

### ISSUE THREAD

**Issue by akshayrathod2** [apache/skywalking#2995]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Bug
___
### Bug
- version of skywalking is 6.0.0-GA

- What happen?
I am trying to install skywalking using helm chart
I downloaded repo and tried installing
```[root@ip-10-3-4-248 6.0.0-GA]# pwd
/root/skywalking-kubernetes/helm-chart/6.0.0-GA
[root@ip-10-3-4-248 6.0.0-GA]# ls
skywalking
[root@ip-10-3-4-248 6.0.0-GA]# helm install skywalking/ --name sky
Error: release sky failed: the server could not find the requested resource```


___
### Requirement or improvement
- I want to install and monitor workload of my service

**Comment by wu-sheng** [comment]
I think this is in discussion in slack already. Why report again?
