### ISSUE TITLE
is is possible stop and start skywalking without restarting application server

### ISSUE THREAD

**Issue by zheyiyi** [apache/skywalking#2996]
is it possible stop and start skywalking without restarting application server

**Comment by wu-sheng** [comment]
You don't need to do that. Why are you asking this?

**Comment by zheyiyi** [comment]
I just thought that if i don't want to collect trace and I don't need to stop application server and remove skywalking

**Comment by zheyiyi** [comment]
> You don't need to do that. Why are you asking this?

I just thought that if i don't want to collect trace and I don't need to stop application server and remove skywalking

**Comment by wu-sheng** [comment]
The agent change application codes automatically. So, you can't make it undo at the runtime.
