### ISSUE TITLE
when oapService and UI restart,the UI do not display the agent services

### ISSUE THREAD

**Issue by shinelon** [apache/skywalking#2997]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I deployed skywalking6.2.0(official releases) ,storage is elasticsearch ,the UI Dashboard has more then 10 agent services.

when  restart oapService and webappService(UI service)  ,do not restart agent services.
the UI Dashboard has nothings

the agent status is CONNECTED 
agent logs ： 
DEBUG 2019-07-04 09:35:48:879 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2019-07-04 09:35:50:543 DataCarrier.DEFAULT.Consumser.0.Thread TraceSegmentServiceClient :  11 trace segments have been sent to collector. 

___
after  restart the agent service ,the UI Dashboard has data again
___
### Requirement or improvement
-When restart oapService and webappService(UI service) , How to avoid restart agent service?

**Comment by wu-sheng** [comment]
This log seems normal. But which storage are you using? Since you are talking about a reboot, the OAP runs in H2 storage default, which is an in-memory DB. The metadata lost, and no data will show unless you reboot the agent. Also, in this case, should be able to see many NPE(s) in OAP logs.

**Comment by shinelon** [comment]
I deployed skywalking6.2.0(official releases) ,storage is elasticsearch

**Comment by wu-sheng** [comment]
Then reboot is irrelevant. We reboot our service routinely, nothing happens. Please pay attention to your ElasticSearch status.
