### ISSUE TITLE
SkyWalking 6.2.0 data display error in the Database dashboard.

### ISSUE THREAD

**Issue by luzhen328** [apache/skywalking#2998]
### Bug
- SkyWalking 6.2.0

![skywalking ui bug](https://user-images.githubusercontent.com/2679913/60634907-463e5b80-9e43-11e9-99c1-dad87d591418.jpg)

1. Database ResponseTime unit error.
1. Database SLA unit error，Should be divided by 100.

**Comment by wu-sheng** [comment]
> Database SLA unit error，Should be divided by 100.

Yes, this is confirmed to be a bug.

> Database ResponseTime unit error.

I assume yes. @TinyAllen I don't think we have a duration less than 1ms, so this should be a bug, please confirm.
