### ISSUE TITLE
SkyWalking 6.2.0 service dashboard CPM data display differently ?

### ISSUE THREAD

**Issue by luzhen328** [apache/skywalking#2999]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- SkyWalking 6.2.0
![skywalking ui bug](https://user-images.githubusercontent.com/2679913/60636481-30cc3000-9e49-11e9-9022-ebed76c7d910.jpg)

Why does the CPM data display differently?

**Comment by wu-sheng** [comment]
First is frontend avg, so instance's top is backend avg. I think only you have data access to check.

**Comment by wu-sheng** [comment]
Backend use storage avg function, very simple one, you could recheck the data to see what happens.

**Comment by wu-sheng** [comment]
One more thing, please recheck your OAP logs and ES status, today, we are using ES bulk to update metrics, if there is error there, maybe the data would be updated accurately, as for instance and service CPMs are different raw data.
