### ISSUE TITLE
Is there a plan to support Elasticsearch  7.X?

### ISSUE THREAD

**Issue by guanfengchen** [apache/skywalking#3000]
### Question
- Is there a plan to support Elasticsearch  7.X?

**Comment by wu-sheng** [comment]
Duplicate as before. ElasticSearch 6 is new already. We haven't plan to upgrade in short term

**Comment by guanfengchen** [comment]
你好,
我在github上下了源代码在学习，现在有个问题，不知道你有没有时间可以帮忙一下。
在agent这边，我看到有很多的plugin
这些plugin是怎样加载到代码中，别切在代码上面实现拦截的呢？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 吴晟 Wu Sheng <notifications@github.com>
发送时间: Thursday, July 4, 2019 1:51:22 PM
收件人: apache/skywalking
抄送: guanfengchen; Author
主题: Re: [apache/skywalking] Is there a plan to support Elasticsearch 7.X? (#3000)


Duplicate as before. ElasticSearch 6 is new already. We haven't plan to upgrade in short term

―

**Comment by wu-sheng** [comment]
All issues in English. And if you are learning open source project, you should read source codes. All features are there

**Comment by wu-sheng** [comment]
We can't support to teach everyone step by step. That is unrealistic.
