### ISSUE TITLE
is it Ok for alarm structure in cluster mode

### ISSUE THREAD

**Issue by Justice-love** [apache/skywalking#3003]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
use java schedule to design alarm plugin whether face some problem in cluster mode? or I don't understand the whole architecture
```java
    public void start(List<AlarmCallback> allCallbacks) {
        LocalDateTime now = LocalDateTime.now();
        lastExecuteTime = now;
        Executors.newSingleThreadScheduledExecutor().scheduleAtFixedRate(() -> {
            try {
                List<AlarmMessage> alarmMessageList = new ArrayList<>(30);
                LocalDateTime checkTime = LocalDateTime.now();
                int minutes = Minutes.minutesBetween(lastExecuteTime, checkTime).getMinutes();
                boolean[] hasExecute = new boolean[] {false};
                runningContext.values().forEach(ruleList -> ruleList.forEach(runningRule -> {
                    if (minutes > 0) {
                        runningRule.moveTo(checkTime);
                        /**
                         * Don't run in the first quarter per min, avoid to trigger false alarm.
                         */
                        if (checkTime.getSecondOfMinute() > 15) {
                            hasExecute[0] = true;
                            alarmMessageList.addAll(runningRule.check());
                        }
                    }
                }));
                // Set the last execute time, and make sure the second is `00`, such as: 18:30:00
                if (hasExecute[0]) {
                    lastExecuteTime = checkTime.minusSeconds(checkTime.getSecondOfMinute());
                }

                if (alarmMessageList.size() > 0) {
                    allCallbacks.forEach(callback -> callback.doAlarm(alarmMessageList));
                }
            } catch (Exception e) {
                logger.error(e.getMessage(), e);
            }
        }, 10, 10, TimeUnit.SECONDS);
    }
```
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Why do you think there is issue in cluster mode? How does alarm cause conflicts with cluster? I am not following.

**Comment by Justice-love** [comment]
> Why do you think there is issue in cluster mode? How does alarm cause conflicts with cluster? I am not following.

in cluster mode, every service instance may  check the alarm rule and  callback send the alarm message.

**Comment by Justice-love** [comment]
such as i want to receive one alarm message in 2 minutes but i receive two same messages actually

**Comment by wu-sheng** [comment]
I don't think you could receive two same messages. It could be alarming for different entities. I think you have understood the data flow.

**Comment by Justice-love** [comment]
this class? `AlarmStandardPersistence`

**Comment by wu-sheng** [comment]
Read how we do distributed aggregration. Don't guess what we are doing.

**Comment by Justice-love** [comment]
Thanks, I will learn it.
