### ISSUE TITLE
The webapp shows no graph.

### ISSUE THREAD

**Issue by tedinGH** [apache/skywalking#3006]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [√ ] Bug
___

### Bug
- Which version of SkyWalking, OS and JRE?
 6.2.0、windows 10 1903、build 1.8.0_171-b11 
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

I ran _**C:\xxx\apache-skywalking-apm-bin\bin\startup.bat**_ then ran my project with vm args with **_-javaagent:C:\xxx\apache-skywalking-apm-bin\agent\skywalking-agent.jar=agent.service_name=service-a_** in sts4.3. Then I visited http://localhost:8080/, none of graphs were shown, chrome network showed that two responses with the body 
```
{
	"errors": [{
		"message": "Invalid Syntax"
	}]
} 
```
which request payload is
```
{
	"query": "query queryData() {}",
	"variables": {
		"serviceId": "3",
		"endpointId": "",
		"endpointName": "",
		"instanceId": "3",
		"databaseId": "",
		"duration": {
			"start": "2019-07-05 1047",
			"end": "2019-07-05 1102",
			"step": "MINUTE"
		}
	}
}
```
and the skywalking-oap-server.log recorded that
```
2019-07-05 11:32:57,661 - graphql.GraphQL - 507 [qtp1502668485-54] WARN  [] - Query failed to parse : 'query queryData() {}'
2019-07-05 11:32:57,730 - graphql.GraphQL - 507 [qtp1502668485-54] WARN  [] - Query failed to parse : 'query queryData() {}'
```

**Comment by wu-sheng** [comment]
You need to check oap log.

**Comment by wu-sheng** [comment]
Set up the env at local with h2 by following quick start. Then dive into more complex way.

**Comment by wu-sheng** [comment]
First, check service and endpoint numbers on UI.

**Comment by tedinGH** [comment]
> Set up the env at local with h2 by following quick start. Then dive into more complex way.

Do I have to configure anything before running startup.bat ?
Quick start says that 

> Storage, use H2 by default, in order to make sure, don't need further deployment.

And version 6.1.0 is fine as what I did in 6.2.0



> First, check service and endpoint numbers on UI.

The dashboard bar shows right info including optional services, endpoints and instances.
The trace page is able to show requests as well.

**Comment by tedinGH** [comment]
@

**Comment by ycrxun** [comment]
I used the 6.2.0 webapp and the 6.2.0 oap , I'm got the same result, but I used 6.1.0 webapp, 6.2.0 oap, it's working for me.

**Comment by wu-sheng** [comment]
You need to delete all indexes when uograde to 6.2.0. We indicate it clearly in changlog.

**Comment by wu-sheng** [comment]
For UI 6.1.0, I don't believe it is working for 6.2.0. We changed the topology query API, how is possible it still working?

**Comment by tedinGH** [comment]
> You need to delete all indexes when uograde to 6.2.0. We indicate it clearly in changlog.

I did't used ES, the storage implement is h2 by default.

**Comment by zengxiaowengit** [comment]
hello, guys, when I use docker image apache/skywalking-oap-server:6.2.0  and the same version skywalking-ui,  Storage, use H2 by default, it's also no any graph and /grahql result is:

-  message: "Invalid Syntax".

how did you resolve this problem?
thanks.

**Comment by wu-sheng** [comment]
Are you using OLD UI?

**Comment by zengxiaowengit** [comment]
I'm using these docker version: 

apache/skywalking-oap-server:6.2.0
apache/skywalking-ui:6.2.0

, is this wrong?

**Comment by tedinGH** [comment]
> Are you using OLD UI?
No.I tried it on rhel, the same package was working fine although it seems like a little bit delayed for minutes on registration.

**Comment by wu-sheng** [comment]
Register is async mode.

**Comment by zengxiaowengit** [comment]
@wu-sheng I have tested serveral times with 6.2.0, but this problem didn't change at all.
I meet this 2 problems in oap server. one warning and an runtimeException.
thanks. 
![skywalking](https://user-images.githubusercontent.com/9106957/60862188-6741ea80-a24f-11e9-83be-82f8c568abf6.png)

**Comment by wu-sheng** [comment]
ID can't be NULL is not related to any feature. We explain a lot of times.

**Comment by zengxiaowengit** [comment]
@wu-sheng 
may be It's because I use spring cloud gateway in my project. although I just directly test the service api, gateway also post the trace data into oap server. when I add the optional-plugins/apm-spring-cloud-gateway-2.x-plugin-6.2.0.jar into my microservice agent  plugin directory, now I can see chart in Topology and Trace menu, but can't see chart in Dashboard.

-  What I can do with this situation?

Thanks.

**Comment by wu-sheng** [comment]
If you can see in topo, there should have been in dashboard. From my understanding.

**Comment by MoDann** [comment]
Me too, both topology and track have chart, only the dashboard has no chart，graphql response is
```
{"errors":[{"message":"Invalid Syntax"}]}
```

**Comment by zengxiaowengit** [comment]
> Me too, both topology and track have chart, only the dashboard has no chart，graphql response is
> 
> ```
> {"errors":[{"message":"Invalid Syntax"}]}
> ```

Yes. I also meet the same questions. what frameworks do you use? springboot OR spring cloud webflux?
we can check it together.

**Comment by MoDann** [comment]
I am using SpringBoot. The previous local and personal server testing is no problem, the test environment on the emergence of such problems.

**Comment by wu-sheng** [comment]
Check time and time zone settings. Many users miss that reminder at the first line of setup document.
