### ISSUE TITLE
SkyWalking 6.2.0 topology ui, Why does the data display is different?

### ISSUE THREAD

**Issue by luzhen328** [apache/skywalking#3007]
### Question
- SkyWalking 6.2.0
![skywalking](https://user-images.githubusercontent.com/2679913/60701376-259f0000-9f2e-11e9-9dad-88e67eb9b3ba.jpg)

Why are the two data different?

**Comment by wu-sheng** [comment]
Based on edge(line) metrics and node metrics. They are different.

**Comment by luzhen328** [comment]
How to understand it?
