### ISSUE TITLE
Question about  tenant isolation ?

### ISSUE THREAD

**Issue by wayilau** [apache/skywalking#3008]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

As the title I want to know more about the tenant isolation.  If i should deploy more sets skywalking for defferent tenant ? or i only use one skywalking to support all the tenants applications?  Now i see that in the UI it is not support tenant isolation  data isolation.

**Comment by wu-sheng** [comment]
SkyWalking doesn't include that.
