### ISSUE TITLE
SkyWalking 6.2.0 JVM Heap chart display problem.

### ISSUE THREAD

**Issue by luzhen328** [apache/skywalking#3010]
### Requirement
- SkyWalking 6.2.0
- JDK 1.7
![skywalking](https://user-images.githubusercontent.com/2679913/60702967-0b1b5580-9f33-11e9-8608-3652d8c1e2cf.jpg)
Can you change free to used ？

**Comment by wu-sheng** [comment]
@TinyAllen Which metrics names are using here?

**Comment by wu-sheng** [comment]
This is free(not used), UI calculates from backend used.
