### ISSUE TITLE
SkyWalking 6.2.0 JVM Non-Heap chart, the free is negative number.

### ISSUE THREAD

**Issue by luzhen328** [apache/skywalking#3011]
### Bug
- SkyWalking 6.2.0
- JDK 1.7
![skywalking-2](https://user-images.githubusercontent.com/2679913/60703232-e378bd00-9f33-11e9-8f3e-55c2a763cacd.jpg)
Why is it negative number?

**Comment by wu-sheng** [comment]
What the storage says? I don't know why is negative.

**Comment by wu-sheng** [comment]
No update in one week.
