### ISSUE TITLE
UI can‘t refresh automatically after changing Current Endpoint and Current Instance drop-down box.

### ISSUE THREAD

**Issue by luzhen328** [apache/skywalking#3012]
### Requirement or improvement
- SkyWalking 6.2.0
![skywalking](https://user-images.githubusercontent.com/2679913/60706411-fabba880-9f3b-11e9-96f7-8a7571390e32.jpg)

UI can‘t refresh automatically after changing Current Endpoint and Current Instance drop-down box.

**Comment by wu-sheng** [comment]
What do you mean can't? Can you explain a little?

**Comment by luzhen328** [comment]
> 
> 
> What do you mean can't? Can you explain a little?

1. The Endpoint charts can't refresh automatically after changing Current Endpoint drop-down box.
2. The Instance charts can't refresh automatically after changing Current Instance drop-down box.

**Comment by wu-sheng** [comment]
@TinyAllen Please help on check. Appreciate.
