### ISSUE TITLE
The Current Endpoint and Current Instance drop-down list items are too short to display

### ISSUE THREAD

**Issue by luzhen328** [apache/skywalking#3013]
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
![skywalking](https://user-images.githubusercontent.com/2679913/60710488-66eeda00-9f45-11e9-9fb0-3eeaa6e6fcc5.jpg)
The Current Endpoint and Current Instance drop-down list items are too short to display.

**Comment by wu-sheng** [comment]
You could click the </> to show.
