### ISSUE TITLE
org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.HistoryDeleteEsDAO 的 57行 retrievalIndexByAliases 方法已经把 namespace 加上了 72行的 deleteIndex 方法又加了一遍namespace

### ISSUE THREAD

**Issue by NaOH-nagao** [apache/skywalking#3014]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by NaOH-nagao** [comment]
org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.HistoryDeleteEsDAO 的 57行 retrievalIndexByAliases 方法已经把 namespace 加上了 72行的 deleteIndex 方法又加了一遍namespace
6.2.0 版本

**Comment by wu-sheng** [comment]
We need issue and pull request in English. Could you change it?

**Comment by Arugal** [comment]
Don't quite understand what the problem is
https://github.com/apache/skywalking/blob/b21db17148df12f34a13a2b1693e009e11e8d7a2/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/base/HistoryDeleteEsDAO.java#L49-L80

**Comment by wu-sheng** [comment]
From my understanding, #retrievalIndexByAliases method return value, should not add namespace as prefix, because deleteIndex will add automatically.

Also, in this change, make sure TimeSeriesUtils.indexTimeSeries still work.
