### ISSUE TITLE
Some questions about timeseries

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#3015]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

1. I notice that TimeSeries will create more serveral times indexes in ES-storage-plugin. I my learned, too many indexes is very expensive, especily in small ES cluster.

2. Downsampling.Hour means sampling one point very hour. That is Downsampling.Hour will sample less data than Downsampling.Second, right? If true, why does Downsampling.Hour need to be split into more slices(indexes)?

**Comment by wu-sheng** [comment]
1. Elasticsearch storage is never designed for small scale case. We change it for improving stability, which if you used the 6.1.0 or before in high payload is very obvious.
1. Downstream is just about dataset size, but it has same write and read frequency. 

The key of this change is delete impact, which will make elasticsearch crash easier than more indexes. Also, feel free to disable month level downstream, I personally don't think it is necessary, it is there just for keep UI and functions consistently and perfectly for new users

**Comment by dmsolr** [comment]
thanks for your comment.
