### ISSUE TITLE
Is this a bug for cluster-etcd-plugin queryRemoteNodes?

### ISSUE THREAD

**Issue by Arugal** [apache/skywalking#3018]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
```EtcdCoordinator``` sets all ```RemoteInstance``` to ```isSelf = true``` https://github.com/apache/skywalking/blob/b21db17148df12f34a13a2b1693e009e11e8d7a2/oap-server/server-cluster-plugin/cluster-etcd-plugin/src/main/java/org/apache/skywalking/oap/server/cluster/plugin/etcd/EtcdCoordinator.java#L71

https://github.com/apache/skywalking/blob/b21db17148df12f34a13a2b1693e009e11e8d7a2/oap-server/server-cluster-plugin/cluster-zookeeper-plugin/src/main/java/org/apache/skywalking/oap/server/cluster/plugin/zookeeper/ZookeeperCoordinator.java#L80-L87

https://github.com/apache/skywalking/blob/b21db17148df12f34a13a2b1693e009e11e8d7a2/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/remote/client/RemoteClientManager.java#L197-L206

**Comment by wu-sheng** [comment]
I think so. We need to fix this.

**Comment by wayilau** [comment]
I will fix this.
