### ISSUE TITLE
How to deploy the cluster mode of skywalking collector? Is there any related documentation?

### ISSUE THREAD

**Issue by weipengd** [apache/skywalking#3022]
How to deploy the cluster mode of skywalking collector? Is there any related documentation?

**Comment by wu-sheng** [comment]
We have a very clear link in readme. Do you read that?

**Comment by weipengd** [comment]
Didn't find it, can you send it?



dongweipeng_927@126.com
 
From: 吴晟 Wu Sheng
Date: 2019-07-08 15:43
To: apache/skywalking
CC: code_rsk; Author
Subject: Re: [apache/skywalking] How to deploy the cluster mode of skywalking collector? Is there any related documentation? (#3022)
We have a very clear link in readme. Do you read that?

**Comment by wu-sheng** [comment]
Read this repo readme. Read all document. Don't guess please.

**Comment by weipengd** [comment]
ok



dongweipeng_927@126.com
 
From: 吴晟 Wu Sheng
Date: 2019-07-08 15:52
To: apache/skywalking
CC: code_rsk; Author
Subject: Re: [apache/skywalking] How to deploy the cluster mode of skywalking collector? Is there any related documentation? (#3022)
Read this repo readme. Read all document. Don't guess please.
