### ISSUE TITLE
Does Skywalk .Net agent supports APM activities of Windows services?

### ISSUE THREAD

**Issue by manojkumar542** [apache/skywalking#3025]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does Skywalk .Net agent supports APM activities of Windows services?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
.net agent is not official Apache project. Please submit issue to their repo.

**Comment by wu-sheng** [comment]
FYI @liuhaoyang
