### ISSUE TITLE
There are no graph on the dashboard, but the rest of the data is normal.

### ISSUE THREAD

**Issue by MoDann** [apache/skywalking#3026]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ √] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.2.00， CentOS6， jdk1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

When upgrading skywalking from 6.1.00 to 6.2.00, the index information of es is cleared first, then skywalking is upgraded and agents are restarted.The data in the UI dashboard cannot be displayed, but other parts of are displayed normally. And the skywalking-oap-server.log recorded that
```
2019-07-08 19:35:47,325 - graphql.GraphQL - 507 [qtp1168079523-56] WARN  [] - Query failed to parse : 'query queryData() {}'
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I guess you didn't upgrade UI. Notice changlog, we provide new topology query protocol.
