### ISSUE TITLE
 Can skywalking monitor hystrix?

### ISSUE THREAD

**Issue by M-make** [apache/skywalking#3028]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can skywalking monitor hystrix? 
If skywalking is available, can you provide the corresponding document?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by M-make** [comment]
I can't find the relevant documentation

**Comment by kezhenxu94** [comment]
> Can skywalking monitor hystrix?

please refer to the [supported-list](https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md)

> I can't find the relevant documentation

@M-make please, documentations definitely exist, please [search](https://github.com/apache/skywalking/search?q=hystrix] before opening an issue
