### ISSUE TITLE
Why is the configuration database access and jvm gc alarms have no effect?

### ISSUE THREAD

**Issue by liyongfa0311** [apache/skywalking#3029]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want a database access and GC timeout alert, but no alarms come out after the threshold is reached.There are no problems with service related and endpoint related alarms.
___
### Bug
- Which version of SkyWalking, OS and JRE?
CentOS 7
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
The following is my configuration information
![image](https://user-images.githubusercontent.com/30169249/60876906-5dc87a80-a26f-11e9-877f-6832846b5d06.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liyongfa0311** [comment]
![image](https://user-images.githubusercontent.com/30169249/60877085-b3048c00-a26f-11e9-8324-a87145d39607.png)

**Comment by wu-sheng** [comment]
Where do you find the metrics names?

**Comment by liyongfa0311** [comment]
In this oal file https://github.com/apache/skywalking/blob/v6.1.0/oap-server/generated-analysis/src/main/resources/official_analysis.oal     
Linked by the oal documentation introduction

**Comment by wu-sheng** [comment]
Database access alarm is a part of service alarm, I think.

**Comment by wu-sheng** [comment]
Your rule name needs being ended with _rule, I think. Please check the logs?

**Comment by liyongfa0311** [comment]
I am very sorry that I made such a simple error on the gc configuration, but my database access configuration does not have this error. Can't I get a database-only alarm?

**Comment by liyongfa0311** [comment]
I see that the database access data in es does have a configuration threshold.

**Comment by liyongfa0311** [comment]
I have checked that the data of database access  in es has exceeded the configured threshold.

**Comment by wu-sheng** [comment]
For database, you could use service name filter. Do you know it?

**Comment by liyongfa0311** [comment]
Do I need to change metrics-name to service_resp_time ? Where is  using the database_access_resp_time?

**Comment by wu-sheng** [comment]
Metrics name comes from OAL only. There is entity name of DB for filter.

**Comment by liyongfa0311** [comment]
I didn't understand what you mean. Can I get a database access timeout alert through configuration?

**Comment by wu-sheng** [comment]
> Can I get a database access timeout alert through configuration?

What is the timeout in JDBC? Do you understand what are you asking?

**Comment by liyongfa0311** [comment]
I want to get slow sql alarm through skywalking，so can I get a  alert that the timeout of database access through configuring alarm-settings.yml?

**Comment by wu-sheng** [comment]
> I want to get slow sql alarm through skywalking，so can I get a alert that the timeout of database access through configuring alarm-settings.yml?

No, we don't have that. TopN is not a metrics type, it is TopN type.
