### ISSUE TITLE
How to add errors per minute graph along with throughput and response times in skywalking UI

### ISSUE THREAD

**Issue by manojkumar542** [apache/skywalking#3031]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to add errors per minute graph along with throughput and response times in skywalking UI
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@TinyAllen I think you may need to add a developer document to guide, if you have time.

**Comment by wu-sheng** [comment]
OAL Metrics and UI have supported to set by users.
