### ISSUE TITLE
Unable to read service from Tomcat8

### ISSUE THREAD

**Issue by Anbool** [apache/skywalking#3040]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Tomcat 8.5.42

- SkyWalking 6.2.0

  ![](https://i.30mo.com/2019/07/10/51x.png)

  I have changed the Tomcat configuration file catalina.sh, but still can't read the service, always 0, I tried to find the answer from Google, there is no solution. Please help me, thank you.

**Comment by wu-sheng** [comment]
Follow the first line of the setup document.

![image](https://user-images.githubusercontent.com/5441976/60949618-8b292d00-a330-11e9-9351-18491ce48dcd.png)

Or set the time and timezone right of your env.

Please search issue before you submit a duplicated one.

**Comment by Anbool** [comment]
I have already solved this problem, thank you very much. I tried searching, but my English is not good, so sorry.
