### ISSUE TITLE
org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - method [PUT], host [http://localhost:9200], URI [/_template/alarm_record], status line [HTTP/1.1 400 Bad Request]

### ISSUE THREAD

**Issue by junxchen** [apache/skywalking#3041]
Question

es 5.6.16
skyWalking 6.2.0

start skyWalking error

org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - method [PUT], host [http://localhost:9200], URI [/_template/alarm_record], status line [HTTP/1.1 400 Bad Request]

**Comment by wu-sheng** [comment]
Read document. Your es version is wrong.
