### ISSUE TITLE
How can we dynamically reload plugin at run time while backend application is running.

### ISSUE THREAD

**Issue by divya711** [apache/skywalking#3042]
While backend java application is running i want to reload the updated plugin at the same time if you have any solution please answer.

**Comment by wu-sheng** [comment]
We don't support that.

**Comment by divya711** [comment]
Is the above mention problem is possible by using classloader or any other way if you have any idea about that please tell me.
One of the possible solution i got by using Java Watchservice to auto reload properties is it the correct way i can solve?

**Comment by wu-sheng** [comment]
If you know how JVM, javaagent and skywalking work, you will find this does not like your mentioned way.

**Comment by wu-sheng** [comment]
If you want to change a property value, it is easy, but reload plugin is totally different.

**Comment by divya711** [comment]
yes i am asking about reload the plugin.
In order to load a plugin, you have used classloader so if I improvise the code to reload on certain condition when any plugin update is it work?

**Comment by wu-sheng** [comment]
That is not the case. You think this too simple
