### ISSUE TITLE
Why networkAddress insert ServiceInventory and ServiceInstanceInventory?

### ISSUE THREAD

**Issue by 1923982924** [apache/skywalking#3043]
The networkAddress is registered on network_address_inventory, and is it registered on ServiceInventory and ServiceInstanceInventory? Service is registered on ServiceInventory, ServiceInstance is registered on ServiceInstanceInventory, if networkAddress is only registered on network_address_inventory , it's nice to manager.

**Comment by wu-sheng** [comment]
If you read codes deeper, it is not better, it is more complex. Such as, how to get topology including DB?
