### ISSUE TITLE
添加显示到界面上的信息有多个字段怎么处理

### ISSUE THREAD

**Issue by wh199609** [apache/skywalking#3044]
日志打印模式能像logback这样（logger.debug("Processing trade with id: {} and symbol : {} ", id, symbol);）打印出来吗？  或者有其它的没看到的不用多个字符串拼接的方法吗？用ActiveSpan.tag方法用多个字符串拼接会对程序性能有影响，有其它方法吗

**Comment by wu-sheng** [comment]
English only. Your description is not clear.
