### ISSUE TITLE
skywalking doesn't perform fsync operations on elasticsearch

### ISSUE THREAD

**Issue by EightMonth** [apache/skywalking#3045]
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 6.1, OS centOS 7, JRE JDK 8, ES 6.5

- What happen?
i see that when using skywalking + elasticsearch, skywalking doesn't perform fsync operations on elasticsearch, which make elasticsearch translog is very large.
at the same time .
skywalking doesn't allow users set it via application.yml

**Comment by wu-sheng** [comment]
Put a pull request of code changes if you want to talk about some setting.
