### ISSUE TITLE
Do we have a roadmap?

### ISSUE THREAD

**Issue by qudongfang** [apache/skywalking#3052]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Do we have a roadmap? I'd like to know the plan and where are we going.

**Comment by wu-sheng** [comment]
SkyWalking is community driven. We are forwarding our committers and contributors want. So just follow the design goals and we are open to the changes.

We don't set roadmap for the project, basically.

**Comment by qudongfang** [comment]
> SkyWalking is community driven. We are forwarding our committers and contributors want. So just follow the design goals and we are open to the changes.
> 
> We don't set roadmap for the project, basically.

Got it. Thanks for your response.
