### ISSUE TITLE
ContextManager.activeSpan() API usage error

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/skywalking#3055]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- 
Look the code. such as:
![image](https://user-images.githubusercontent.com/10150229/61099499-1d4a4600-a495-11e9-9773-f417d6621d44.png)
![image](https://user-images.githubusercontent.com/10150229/61099508-29360800-a495-11e9-9f47-d8416577fc24.png)
The code uses `ContextManager.activeSpan()` to determine if there is an active span in the current thread, which will cause NPE when no active span. The correct approach should be `ContextManager.isActive()` 

I am right?

**Comment by wu-sheng** [comment]
Yes. I think so.
