### ISSUE TITLE
I want to simulate sending metrics data to the Skywalking 6.2 server by gRPC。

### ISSUE THREAD

**Issue by AirTrioa** [apache/skywalking#3056]
I want to simulate sending metrics data to the Skywalking 6.2 server by gRPC and achieve the kind of effect that is realistic in the topology. At present, I am going to write a main function to simulate, the first step of registration and the third step of survival are no problem, the second step is not very understanding, I hope you can help me.

Github Reference:https://github.com/SkyAPM/document-cn-translation-of-skywalking/blob/master/docs/zh/6.2.0/protocols/Trace-Data-Protocol-v2.md

**Comment by wu-sheng** [comment]
Are you looking for `org.apache.skywalking.oap.server.receiver.trace.mock.AgentDataMock`?
