### ISSUE TITLE
针对追踪数据和SQL语句数据二次分析

### ISSUE THREAD

**Issue by lichengliang1** [apache/skywalking#3059]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
我想知道怎么拿到数据做二次分析。如果从ES中或MYSQL中拿数据的话，能否给份文档？还有怎样才能收集到所有SQL语句
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking目前使用的是6.2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dmsolr** [comment]
to lanuch oap using debug, will print sql statement.

**Comment by lichengliang1** [comment]
print sql statement 是否持久化了？

**Comment by dmsolr** [comment]
If you set logger.level = debug, you can find those in log file. 
All SQL statements is executed by OAP which those are logged on log file.

**Comment by wu-sheng** [comment]
English only.
