### ISSUE TITLE
Why can't I find the module "apm-collector/apm-collector-remote/collector-remote-grpc-provider"?

### ISSUE THREAD

**Issue by luzhen328** [apache/skywalking#3060]
### Question
- SkyWalking 6.2.0
![skywalking](https://user-images.githubusercontent.com/2679913/61107521-af147c00-a4b2-11e9-9d05-2429a5e41b79.jpg)

Why can't I find the module "apm-collector/apm-collector-remote/collector-remote-grpc-provider"?

**Comment by dmsolr** [comment]
Do you run `mvn compile` first?

**Comment by wu-sheng** [comment]
Eclipse is hard to me.
