### ISSUE TITLE
TraceID可以增加复制功能吗？

### ISSUE THREAD

**Issue by litaiqing** [apache/skywalking#3062]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ✔] Feature or performance improvement
___
### Requirement or improvement
TraceID可以增加复制功能吗？
![image](https://user-images.githubusercontent.com/11313291/61121091-f578d380-a4d0-11e9-823d-fda2727c1883.png)

**Comment by wu-sheng** [comment]
English only, please
