### ISSUE TITLE
Service cluster plugin bug

### ISSUE THREAD

**Issue by arugal** [apache/skywalking#3069]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When the node is set to ```Receiver``` mode, ```#registerRemote``` is not invoker and the ```ZookeeperCoordinator#queryRemoteNodes NacosCoordinator#queryRemoteNodes ConsulCoordinator#queryRemoteNodes``` return empty list,at this point ```MetricsRemoteWorker``` will not work properly, right?
https://github.com/apache/skywalking/blob/1d13d735bbc1db1edd5a70b92b6bffd40bd9e4cc/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/CoreModuleProvider.java#L177-L180
https://github.com/apache/skywalking/blob/1d13d735bbc1db1edd5a70b92b6bffd40bd9e4cc/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/remote/client/RemoteClientManager.java#L91-L93
https://github.com/apache/skywalking/blob/1d13d735bbc1db1edd5a70b92b6bffd40bd9e4cc/oap-server/server-cluster-plugin/cluster-zookeeper-plugin/src/main/java/org/apache/skywalking/oap/server/cluster/plugin/zookeeper/ZookeeperCoordinator.java#L32-L91
https://github.com/apache/skywalking/blob/1d13d735bbc1db1edd5a70b92b6bffd40bd9e4cc/oap-server/server-cluster-plugin/cluster-nacos-plugin/src/main/java/org/apache/skywalking/oap/server/cluster/plugin/nacos/NacosCoordinator.java#L35-L79
https://github.com/apache/skywalking/blob/1d13d735bbc1db1edd5a70b92b6bffd40bd9e4cc/oap-server/server-cluster-plugin/cluster-consul-plugin/src/main/java/org/apache/skywalking/oap/server/cluster/plugin/consul/ConsulCoordinator.java#L47-L89

**Comment by wu-sheng** [comment]
> When the node is set to Receiver mode, #registerRemote is not invoker and the ZookeeperCoordinator#queryRemoteNodes NacosCoordinator#queryRemoteNodes ConsulCoordinator#queryRemoteNodes return empty list,at this point MetricsRemoteWorker will not work properly, right?

This is a bug for those coordinators. We add this in k8s coordinator, but miss to check others. `registerRemote` should not be called in `receiver` mode, that is correct, but the queryList should still work.

**Comment by wu-sheng** [comment]
FYI @peng-yongsheng

**Comment by wu-sheng** [comment]
@arugal Are you going to fix this?

**Comment by arugal** [comment]
Now I have an idea, all schemas register nodes, add a ```role``` attribute to ```RemoteInstance``` to mark it, and finally filter it in ```RemoteClientManager``` and ```DataTTLKeeperTimer```

**Comment by wu-sheng** [comment]
Check how `ClusterModuleKubernetesProvider` did. You will notice, we don't need to change that :)

**Comment by arugal** [comment]
I will fix this
