### ISSUE TITLE
ThreadLocal need not to remove?

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#3071]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

There is not auto remove in `GlobalIdGenerator`. So It will lead to memory lack, I think.

https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/ids/GlobalIdGenerator.java#L54

**Comment by wu-sheng** [comment]
This threadlocal wouldn't cause leak. Because it is removed if thread is gone, and also always necessary when trace is there.

**Comment by kezhenxu94** [comment]
@dmsolr FYI, here is what the [JavaDoc (Jdk 1.7)](https://docs.oracle.com/javase/7/docs/api/java/lang/ThreadLocal.html) says
> Each thread holds an implicit reference to its copy of a thread-local variable as long as the thread is alive and the ThreadLocal instance is accessible; after a thread goes away, all of its copies of thread-local instances are subject to garbage collection (unless other references to these copies exist).
