### ISSUE TITLE
where is admin configuration in the 6.2 version of Binary Distribution (Linux) version ? 

### ISSUE THREAD

**Issue by zolozhang** [apache/skywalking#3078]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- What do you want to know?

where is admin configuration , how to enable the login in page ? 
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 6.2 , downloaded the Binary Distribution (Linux) version from 
http://skywalking.apache.org/downloads/

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read changelog, it has been removed.

**Comment by zolozhang** [comment]
Noted. 3ks a lot .
