### ISSUE TITLE
the oap server can not get instance when i put it into docker

### ISSUE THREAD

**Issue by xvjialing** [apache/skywalking#3085]
![image](https://user-images.githubusercontent.com/15673470/61205000-6b737980-a721-11e9-96d6-874e5adf4b30.png)
is there anyway to set client ip and server ip

**Comment by wu-sheng** [comment]
Search before submitting a new issue. Ignore this exception.

**Comment by xvjialing** [comment]
@wu-sheng i have already set collector.backend_service=${SW_AGENT_COLLECTOR_BACKEND_SERVICES:192.168.31.48:11800} ,but it does not  effect

**Comment by wu-sheng** [comment]
Do you check the time and timezone? It is important, we put it at the first line of setup document.
