### ISSUE TITLE
skymalking的javaagent

### ISSUE THREAD

**Issue by tsnamli** [apache/skywalking#3086]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Exception while fetching data (/getTopNServiceThroughput) : Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only. This is a simply es error. Check your es.

**Comment by tsnamli** [comment]
[root@localhost logs]# ps xH|grep 3086
30010 pts/0    R+     0:00 grep --color=auto 3086
我并没有发现这个线程。
我使用的版本为 elasticsearch-5.6.10  apache-skywalking-apm-incubating6.0

**Comment by tsnamli** [comment]
那么我想要选择 mysql作为 skywalking的后端存储，我在网上看到 他们使用 mysql.jar的包。请问有什么好的教程么 。

**Comment by tsnamli** [comment]
大神您好！
经过一系列捣鼓之后，我又使用mysql作为skywalking的后端存储，但是 它和  es 出现了相同的问题。（skywalking 和 后端存储在一台机器上）


我使用navicat查看 mysql的数据表中 有一些数据。查看agent的日志也没有报错。

但当我查看 skywalking的 weblog.log   有如下报错。

Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)







在 2019-07-15 18:10:37，"吴晟 Wu Sheng" <notifications@github.com> 写道：


Closed #3086.
