### ISSUE TITLE
> i think mq is unfriendly for ad-hoc query.

### ISSUE THREAD

**Issue by yogaling** [apache/skywalking#3087]
> i think mq is unfriendly for ad-hoc query.

we are building a data warehouse on hive, we need some data from skywalking,but I tried es-hive integration,it was too slow,so I am looking for some other ways like kafka or logstash->kafka

We have the same problem！

**Comment by wu-sheng** [comment]
You could implement the storage by yourself. Today, we have metrics exporter.
