### ISSUE TITLE
can i ignore trace mq message like kafka?

### ISSUE THREAD

**Issue by yogaling** [apache/skywalking#3089]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- can i ignore trace mq message like kafka?

**Comment by wu-sheng** [comment]
You are keeping submitting issues, rather than read documents. We have clear supported list there.

**Comment by wu-sheng** [comment]
You shouldn't do that. Read the document please.

**Comment by yogaling** [comment]
3q!
