### ISSUE TITLE
parentSegmentId question

### ISSUE THREAD

**Issue by zou79189747** [apache/skywalking#3094]
a request pass 3 node , first node use java agent ,second node use nodejs agent， third node use java agent。but on trace page the chart is incomplete。I found the nodejs agent sent span data have a problem that the parentSegmentId in refs  equal trace_id , I think parentSegmentId should be the first node sent segmentId , but it's not ,why?

**Comment by wu-sheng** [comment]
Ask this at nodejs agent project. It isn't skywalking issue.

**Comment by wu-sheng** [comment]
Header has two versions protocol. I don't know whether it upgraded in nodejs agent. SkyWalking java agent has compatible mode with v5 header.

Read setup document.

**Comment by zou79189747** [comment]
In Java agent the config agent.active_v2_header default is true , I want to check SkyAPM-nodejs config ,but 
 so many page url return 404 in SkyAPM-nodejs document ,I can't find the config list  ,I create a new issue in nodejs agent project , but that project looks like inactive，I'm not sure  I will get answer. And can you show me the url about v5 header

**Comment by wu-sheng** [comment]
In java agent, v5 header is `agent.active_v1_header`. cc @ascrutae
