### ISSUE TITLE
Metrics exporter  我该怎么使用这个功能

### ISSUE THREAD

**Issue by lichengliang1** [apache/skywalking#3097]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
需要我搭建一个GRPC服务来接收这些数据吗？
这些数据包含链路追踪数据和SQL语句吗？

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking6.2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only.

**Comment by lichengliang1** [comment]
能把英语文档发过来看下吗？

**Comment by JaredTan95** [comment]
> 能把英语文档发过来看下吗？

Example refs： https://github.com/JaredTan95/grpc-spring-boot-example/tree/master/grpc-sw-exporter-collecotr

**Comment by Lovnx** [comment]
> > 能把英语文档发过来看下吗？
> 
> Example refs： https://github.com/JaredTan95/grpc-spring-boot-example/tree/master/grpc-sw-exporter-collecotr

这个项目不能看了呢
