### ISSUE TITLE
Skywalking timerange

### ISSUE THREAD

**Issue by sartizera** [apache/skywalking#3099]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hi, First skywalking is great and i am studying the tool to apply it in the company, i am from brazil and work in company Algar Telecom, but i have a question, the timerange only brings me the recent data, but i wanted data for example 7 day ago, and the impression i have is that older data he's throwing away or not showing me, would i have to put hi to bring me older data somewhere? i saw in github that you put in support, time, day, and a month, but i can not get it to bring in old data and I neede it, how do I do it? 
For example, i put to filter the date yesterday in a schedule to get the data today, but what is happening is that the only bringing this day, i have been studying the tool a few days and as a lay person wanted to know, i need to set something up, or this is really a bug? 
If you want, i could send prinscreen.
I would be very grateful if you guys could help me, thank u.

**Comment by kezhenxu94** [comment]
Hi @sartizera, SkyWalking deletes the data older than a given time automatically,.[search TTL](https://github.com/apache/skywalking/search?utf8=%E2%9C%93&q=ttl&type=) to find out how to set a longer time that SkyWalking keeps data

**Comment by sartizera** [comment]
What exactly would TTL be?  I'm a little inexperienced with IT


On 16 Jul 2019, at 8:52 PM, kezhenxu94 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @sartizera<https://github.com/sartizera>, SkyWalking deletes the data older than a given time automatically,.search TTL<https://github.com/apache/skywalking/search?utf8=%E2%9C%93&q=ttl&type=> to find out how to set a longer time that SkyWalking keeps data

**Comment by wu-sheng** [comment]
> What exactly would TTL be?  I'm a little inexperienced with IT

TTL = data Time To Live. Observability should not be saved always. https://github.com/apache/skywalking/blob/5036e8334301322d49973005cd98513c17b0f28f/docs/en/setup/backend/ttl.md

Always, which storage are you using? Different dimensions and types of data have different TTL. Read the document, then you could change it at yaml.

**Comment by sartizera** [comment]
I change today to mysql

Sent from my iPhone

On 16 Jul 2019, at 9:57 PM, 吴晟 Wu Sheng <notifications@github.com<mailto:notifications@github.com>> wrote:


What exactly would TTL be? I'm a little inexperienced with IT

TTL = data Time To Live. Observability should not be saved always. https://github.com/apache/skywalking/blob/5036e8334301322d49973005cd98513c17b0f28f/docs/en/setup/backend/ttl.md

Always, which storage are you using? Different dimensions and types of data have different TTL. Read the document, then you could change it at yaml.

**Comment by wu-sheng** [comment]
Read the document I posted, it is there. MySQL storage follows the default TTL settings. Notice the unit.

**Comment by sartizera** [comment]
thank u, appreciate it this conversation.
