### ISSUE TITLE
远程加载agent jar

### ISSUE THREAD

**Issue by toread** [apache/skywalking#3102]
- [ 远程加载 agent的jar包] Requirement
### Requirement or improvement
期望 agent lib包单独放在一个地方维护。加载的时候可以通过网络的方式加载此jar包。
这样如果扩展包有bug可以直接放在一个地方加载即可。简化重复部署的可能性。

**Comment by wu-sheng** [comment]
English only. And the thing you asking is violating the Apache rules. We do not belong a vendor, this is a community.
