### ISSUE TITLE
I want to know what conditions are required to form a node in a topology diagram.

### ISSUE THREAD

**Issue by AirTrioa** [apache/skywalking#3103]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
I want to know what conditions are required to form a node in a topology diagram.

Now, I registered services and instances in SW, sent HTTP requests from SW6 to Spring MVC with probes, and sent some data to SW, but did not form a topology map on the page. So, can you tell me what it takes to form a node in the topology?

**Comment by wu-sheng** [comment]
That is complex. You should read codes. If you run an open source project compatible with skywalking, I could help.
