### ISSUE TITLE
How  set SkyWalking OAP server to  use  mysql  in docker version ?

### ISSUE THREAD

**Issue by zolozhang** [apache/skywalking#3107]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How  set SkyWalking OAP server to  use  Mysql  in docker version ? 
1.Switch to the Mysql 
2.Mysql datasource configuration 
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.2.0 

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
In Apache, we can't today. Because we can't include MySQL driver due to GPL licensed. You have to build the image by yourself.

**Comment by zolozhang** [comment]
OK  . 3KS  a lot .

**Comment by Bbigdataexplorer** [comment]
Does skywalking have a community group? Join the community group to learn more about SkyWalking

**Comment by wu-sheng** [comment]
> Does skywalking have a community group? Join the community group to learn more about SkyWalking

Read root readme, we have listed the channels there.
