### ISSUE TITLE
About oap starter assert.

### ISSUE THREAD

**Issue by wayilau** [apache/skywalking#3111]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [] Feature or performance improvement

___

In the code ModuleManager, method assertPreparedStage called by manager.find(). I think find executed behind init method, also they run in the same thread as main thread. is this must assert ?

**Comment by wu-sheng** [comment]
Yes, because `#find` should only happen after init stage. **Init** should not count on the dependencies.
