### ISSUE TITLE
After the SamplingService is running at the agent, how to ensure the integrity of trace?

### ISSUE THREAD

**Issue by pmq5205209** [apache/skywalking#3113]
After the SamplingService is running at the agent, how to ensure the integrity of trace?
Before a entrySpan created, it will be judged that whether the request has a header whose key is "sw6" or "sw3". If the answer is yes, the entrySpan will be forced to sample. However, exitSpans will never be forced to sample. 
According to my understanding, it is only be ensured that the tracing information need to be receiced after been sended across the request header.

**Comment by wu-sheng** [comment]
Sample is context based. No span based. You misunderstand.
