### ISSUE TITLE
这是赤果果的歧视国人英语水平低的运维人员,没有中文部署文档

### ISSUE THREAD

**Issue by xbw1220** [apache/skywalking#3114]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We have one. Could you be polite?  You even don't ask.

And English is foundation required and for more people.

**Comment by xbw1220** [comment]
无形舔狗,最为致命


> We have one. Could you be polite? You even don't ask.
> 
> And English is foundation required and for more people.
