### ISSUE TITLE
oap-server log:Remote client block times over 60 seconds

### ISSUE THREAD

**Issue by wanghuiqi** [apache/skywalking#3116]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug

___
### Question
- What do you want to know?
Why does oap-server keep printing this log?
![image](https://user-images.githubusercontent.com/27945132/61505085-33658280-aa10-11e9-8874-10a99ea9a090.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?
oap-server:6.1.0 kubernetes linux alpine openjdk1.8
- Which company or project?
oap-server
- What happen?
I deployed the skywalking cluster in k8s and it started working fine but after a few minutes one of the nodes frantically printed the following logs and then the data in the UI could not be displayed
![image](https://user-images.githubusercontent.com/27945132/61505339-06fe3600-aa11-11e9-96df-36ade145ded4.png)
![image](https://user-images.githubusercontent.com/27945132/61505368-1f6e5080-aa11-11e9-82ce-6dc137e9a5f6.png)

**Comment by wu-sheng** [comment]
For blocking, I don't know. But in master branch, we set timeout in 10 seconds. Block should be ignored by that. But you need to be careful why your target is blocked, meaning no-response. Is your another OAP node dead? Or Really blocking because of storage(ES) performance?

**Comment by wanghuiqi** [comment]
> For blocking, I don't know. But in master branch, we set timeout in 10 seconds. Block should be ignored by that. But you need to be careful why your target is blocked, meaning no-response. Is your another OAP node dead? Or Really blocking because of storage(ES) performance?


![image](https://user-images.githubusercontent.com/27945132/61505997-49c10d80-aa13-11e9-9994-9bba18198558.png)
It's the performance of the ES,thank you!
