### ISSUE TITLE
Is there any eclipse-code-style file for SkyWalking web shared ?

### ISSUE THREAD

**Issue by qxo** [apache/skywalking#3126]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is there any eclipse-code-style file for SkyWalking web shared ?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
No we don't have now, most of us use IntelliJ IDEA

**Comment by wu-sheng** [comment]
I think most of all committers/contributors are using IntelliJ today.
