### ISSUE TITLE
Each Request displays twice

### ISSUE THREAD

**Issue by evanxuhe** [apache/skywalking#3141]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
Reason and how to fix it
___
### Bug
- Which version of SkyWalking, OS and JRE?
**Skywalking 6.2.0
SpringBoot 1.5.9
undertow-core 2.0.9**
- Which company or project?

- What happen?
like this, for each request, there are both two traces info 
**one is /apm/post/{mypath}
another one is /apm/post/1563774429** following
What's more there are some rules
- **traceId**
 trace Id of  /apm/post/{mypath} always ends with **000001**
While trace Id of  /apm/post/1563774429 always ends auto increasingly from 0003 00005 0007 to 000017
- **component Type**
/apm/post/{mypath} is **http-SpringMVC**
/apm/post/1563774429 is **http-http**

![image](https://user-images.githubusercontent.com/24379174/61609099-97de4700-ac87-11e9-81c1-c8bc649d1a42.png)
![image](https://user-images.githubusercontent.com/24379174/61610086-982c1180-ac8a-11e9-9890-08dc9e8c4e45.png)
![image](https://user-images.githubusercontent.com/24379174/61610157-daede980-ac8a-11e9-8071-6d452dc2dc7c.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think I have explained this multiple times. The Simple way, remove your Container plugin(Tomcat/Undertow), because you are using async mode between container and SpringMVC.

**Comment by evanxuhe** [comment]
> I think I have explained this multiple times. The Simple way, remove your Container plugin(Tomcat/Undertow), because you are using async mode between container and SpringMVC.

Thank U. :+1::+1::+1:
Sorry for that I didnt't understand your points before. I will try it later
