### ISSUE TITLE
if load balance implement at the agent client, do you have some suggest?

### ISSUE THREAD

**Issue by zhousiliang163** [apache/skywalking#3151]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Which load balance?

**Comment by zhousiliang163** [comment]
> 
> 
> Which load balance?

I want to do the load balance for backend server by agent client. if backend server is cluster mode by zookeeper,i can get backend server address by zookeeper.do you think?

**Comment by wu-sheng** [comment]
You can't guarantee which coordinator used at server side, and it is unwise to put so many clients at agents. There are plenty of load balance there, nginx, envoy, kong etc.

Also, in many production env, agents and OAP backends are deployed in different zones or VPCs, zookeeper style load balance is not working.

**Comment by zhousiliang163** [comment]
> 
> 
> You can't guarantee which coordinator used at server side, and it is unwise to put so many clients at agents. There are plenty of load balance there, nginx, envoy, kong etc.
> 
 if i use nginx for oap load balance,but how do the load balance for nginx when nginx is large load?

**Comment by wu-sheng** [comment]
> if i use nginx for oap load balance,but how do the load balance for nginx when nginx is large load?

How do you do for a Gateway? It is the same scenario.

**Comment by zhousiliang163** [comment]
> 
> 
> > if i use nginx for oap load balance,but how do the load balance for nginx when nginx is large load?
> 
> How do you do for a Gateway? It is the same scenario.

by the DNS

**Comment by wu-sheng** [comment]
It is same always
