### ISSUE TITLE
It's didn't work monitoring the mongodb client at the version 3.8.4 ,do you  have the plan to support it ?

### ISSUE THREAD

**Issue by freezek** [apache/skywalking#3153]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question

It's didn't work monitoring the mongodb at the client version 3.8.4 , do you  have the plan to support it ?
___

**Comment by wu-sheng** [comment]
All plugins are built by the community. Tons of versions and frameworks out there, we don't know.

**Comment by wu-sheng** [comment]
If it is not on supported list, then not supported yet.
