### ISSUE TITLE
Can SkyWalking-agent set Can-Redefine-Classes and Can-Retransform-Classes is true?

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/skywalking#3155]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
 - [x] Discussion

___
### Discussion
- Can SkyWalking-agent set Can-Redefine-Classes and Can-Retransform-Classes is true?
In some cases, the enhancement of SkyWalking will fail;
The first java agent, he only enhances the original java class, and transform is true.
The second is SkyWalking-agent, Can-Retransform-Classes is false
Look at JVMTI  the `Transformations are applied in the following order`
![image](https://user-images.githubusercontent.com/10150229/61763021-735ca900-ae06-11e9-9792-d90311ef1ae3.png)
So the SkyWalking-agent transform will be invalidated.
So can we open Can-Retransform-Classes?
What if set Can-Retransform-Classes is true? Is it better to `set true it` with the set `Can-Redefine-Classes` also true?

**Comment by wu-sheng** [comment]
I think it is OK to open it, as we are doing nothing about retransform and redefine, but maybe other agents want.

**Comment by zhaoyuguang** [comment]
OK, I will finish it.

**Comment by wu-sheng** [comment]
@zhaoyuguang When will you send the PR?

**Comment by zhaoyuguang** [comment]
Apologize to wait a long time 😹

**Comment by wu-sheng** [comment]
No problem. I just don't want this requirement is excluded out of the next release.
