### ISSUE TITLE
500 errors occur when the response time of a request exceeds 10 seconds

### ISSUE THREAD

**Issue by luzhen328** [apache/skywalking#3158]
### Bug
- SkyWalking 6.2.0
- Elasticsearch 6.4.3
![sk](https://user-images.githubusercontent.com/2679913/61773265-dc541900-ae26-11e9-8b2d-2e68bf19067b.jpg)
Response:
{"timestamp":1563952660681,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"GENERAL"}

**Comment by wu-sheng** [comment]
This error means your webapp can't access OAP backend, anything more. :)
