### ISSUE TITLE
中国人做的开源项目没有中文文档，表示不理解

### ISSUE THREAD

**Issue by Skqing** [apache/skywalking#3166]
中国人做的开源项目没有中文文档，表示不理解。
虽然Apache要求官方语言是英文，但是作为一个中国人主导的开源项目，连自己的语言文档都没有，不理解。

dubbo也是顶级开源项目人家照样有中文文档。

世界该变天了，不是一定要以英文为主。

**Comment by wu-sheng** [comment]
If you read the issue page, there is a Chinese document there. SkyWalking doesn't have full time developers like Alibaba did, so we just have things the community provided. That is all.

![image](https://user-images.githubusercontent.com/5441976/61858366-894a9680-aef8-11e9-90bd-0813566c63bd.png)

You are leading topic to unrelated thing.

**Comment by jingj5** [comment]
瞎P，为了这个也提ISSUE，中国人不狭隘的。人家好好的开源，你爱玩就玩，不爱玩就别BB，或者你有闲时，就自己去翻译。
