### ISSUE TITLE
Java agent support undertow RoutingHandler

### ISSUE THREAD

**Issue by aiyanbo** [apache/skywalking#3172]
- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
In current, Java agent will trace the undertow requests and the span's `operationName` is the request path. But the RESTful APIs has path parameter, We need support one `Routing` as one Skywalking `Endpoint`.

Endpoint changes:
**Before**: /projects/1/users
**After**: /projects/{projectId}/users

**Comment by wu-sheng** [comment]
Doesn't it auto override by SpringMVC?

**Comment by aiyanbo** [comment]
In my project is not using SpringMVC. Just run `Undertow` as an instance.

**Comment by wu-sheng** [comment]
Got it.

**Comment by kezhenxu94** [comment]
Resolved by #3173

**Comment by wu-sheng** [comment]
@kezhenxu94 Please make sure the milestone is set when you close issue.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 Please make sure the milestone is set when you close issue. Otherwise, we may lose something in changelogs.

Sorry I missed that, thanks for pointing this out 😄
