### ISSUE TITLE
batch insert es with error

### ISSUE THREAD

**Issue by qlql489** [apache/skywalking#3177]
- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
we use version 6.2, storage choose baidu's es service ,but  alter  running about  8 hours,   the opa log show  bulk error, es  input qps about 2000,  we  just access 3 services,  alter restart oap 3 time  still bulk error,  we swith  to version 6.1, the es config is not change,  and no error appear, now we already access about 70 services, so what's  the most likely reason of bulk error ?   and  if we want to change to version 6.2 , is the agent need to change?  what's  the  step?

error log from class
`org.apache.skywalking.oap.server.library.client.elasticsearchBulk.ElasticSearchClient:311  -  Bulk 9421  executed with failures
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Are you switching to a new ElasticSearch cluster when you upgrade to 6.2 from 6.1? It is not compatible. If this goes w/ payload(service number), have you read this? https://github.com/apache/skywalking/blob/master/docs/en/FAQ/ES-Server-FAQ.md

**Comment by qlql489** [comment]
we use 6.2 first ,alfter bulk error,  we clear all ElasticSearch's data and change to 6.1

**Comment by wu-sheng** [comment]
Have you set the batch configurations to ES? I think that should help.

**Comment by qlql489** [comment]
oap  set concurrentRequests:6 ,   6.1 and 6.2 's configuration is same 
 i want to kown  if we update to 6.2 form 6.1 ,do we need to update agent version

**Comment by wu-sheng** [comment]
Update, no, I think. But reboot is required, due to the es storage erased.

**Comment by qlql489** [comment]
reboot  oap  or our service

**Comment by wu-sheng** [comment]
You upgrade OAP, so reboot yes. Also services w/ agent need to reboot.

**Comment by qlql489** [comment]
thanks
