### ISSUE TITLE
Listener timeout after waiting for [30000] ms

### ISSUE THREAD

**Issue by xiaoni157** [apache/skywalking#3180]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
![image](https://user-images.githubusercontent.com/24448049/62018275-a0d19a00-b1ec-11e9-8a29-1ed20710af21.png)
![image](https://user-images.githubusercontent.com/24448049/62018343-e2fadb80-b1ec-11e9-980d-59bdf22c267b.png)

What's the reason for this?What can I do to avoid this mistake?
Background: the address of our ali cloud ecs machine was changed, and then the collector service was restarted after a period of time, and the agent only had one service restarted.

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
That is as it said... ElasticSearch doesn't response.

**Comment by xiaoni157** [comment]
We also have a machine connected to this es, which can work normally all the time

**Comment by wu-sheng** [comment]
Then, you should check the version, auth. or anything affecting the es connectable. There is nothing special there.

**Comment by xiaoni157** [comment]
Are you saying that we failed to connect with es successfully?

**Comment by wu-sheng** [comment]
From the log, yes. This is just a very simple query to es, but can't access.

**Comment by xiaoni157** [comment]
Version, address, username and password are all correct. What else might be the reason?

**Comment by wu-sheng** [comment]
I am not sure then. SkyWalking is just supporting easy auth. Please check whether it fits your server side. Have you read this? https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#about-authentication

**Comment by xiaoni157** [comment]
I changed the log level to debug and found the logs. I guess it's the reason for the cache (mesh-buffer, trace-buffer).
![image](https://user-images.githubusercontent.com/24448049/62020598-37ef1f80-b1f6-11e9-91be-e4483978de66.png)

![image](https://user-images.githubusercontent.com/24448049/62020539-f6f70b00-b1f5-11e9-94aa-b392318c1fb0.png)

**Comment by JustinGedehuo** [comment]
I've seen this problem before, and the solution is set the elasticsearch RestClient.builder socketTimeOut，Specific setting method asks baidu。
