### ISSUE TITLE
Skywalking CPU 100%

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3182]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ 1 ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
skywalking后台CPU%，部署的单机，存储使用ES，也是单机。ES的CPU、内存以及状态都正常。
本来想执行jstack查看skywalking进程的线程状态，但是执行后报错：
`[root@iZbp1d40aso0xvdm5qgsawZ ~]# jstack 12145 | more
12145: Unable to open socket file: target process not responding or HotSpot VM not loaded
The -F option can be used when the target process is not responding`
skywalking后台的日志一直打印：
`2019-07-29 12:50:02,964 - org.elasticsearch.client.RestClient - 65 [I/O dispatcher 1] WARN  [] - request [POST http://172.16.4.52:9200/register_lock/type/16/_update?refresh=true&version=16117&timeout=1m] returned 1 warnings: [299 Elasticsearch-6.7.2-56c6e48 "Usage of internal versioning for optimistic concurrency control is deprecated and will be removed. Please use the `if_seq_no` and `if_primary_term` parameters instead. (request for index [register_lock], type [type], id [16])"]
`
运行环境：
jdk版本：1.8.0_211-b12
Skywalking版本：6.2.0

**Comment by wu-sheng** [comment]
English only.
