### ISSUE TITLE
skywalking oapServer CPU 100%

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3184]
The Question is as follow：
skywalking oapServer CPU is  in 100% by standalone mode. The storage is ElasticSearch by standalone mode。CPU & Memory。
I want to use jstack, but give me some error messages: `[root@iZbp1d40aso0xvdm5qgsawZ ~]# jstack 12145 | more 12145: Unable to open socket file: target process not responding or HotSpot VM not loaded The -F option can be used when the target process is not responding`
skywalking oapServer log：
`2019-07-29 12:50:02,964 - org.elasticsearch.client.RestClient - 65 [I/O dispatcher 1] WARN [] - request [POST http://172.16.4.52:9200/register_lock/type/16/_update?refresh=true&version=16117&timeout=1m] returned 1 warnings: [299 Elasticsearch-6.7.2-56c6e48 "Usage of internal versioning for optimistic concurrency control is deprecated and will be removed. Please use the if_seq_noandif_primary_termparameters instead. (request for index [register_lock], type [type], id [16])"]`

Runtime Environment：
jdk version：1.8.0_211-b12
Skywalking version：6.2.0

**Comment by wu-sheng** [comment]
`Unable to open socket file: target process not responding` this shows your file handler number has been limited. This is a Linux OS error.

Standalone mode depends on how powerful your VM is, how many CPU and memory for OAP and ES?
