### ISSUE TITLE
should we remove the docker folder as it is replaced

### ISSUE THREAD

**Issue by stevehu** [apache/skywalking#3190]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

We have an official repository for the docker images and compose at https://github.com/apache/skywalking-docker and it works perfectly. Should we remove the docker folder in this repository? Our developers have tried the docker folder and couldn't find the images published to the docker hub. 

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The docker file in this repo is for development only. Build the current version to an image for the developer.

**Comment by wu-sheng** [comment]
We need to use `cmake` to build the image locally.

**Comment by stevehu** [comment]
Got it. In this case, should we add a README.md to the folder to clearly state the purpose? Most users will try to start it and find it doesn't work out of the box. In the readme, we can direct them to the right docker repository if they just want to set up a development environment. I can create a PR for it.

**Comment by wu-sheng** [comment]
Yes. That makes sense. Would you like to submit a pull request?
