### ISSUE TITLE
Did webapp security removed in 6.2?

### ISSUE THREAD

**Issue by bhui** [apache/skywalking#3195]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want keep my webapp security. Do not show the content before user logined.
I add this to webapp.yml like the older version style. 
But it doesn't work.
```
security:
  user:
    admin:
      password: admin
```
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.2,ubuntu, jdk1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read the changelog, https://github.com/apache/skywalking/blob/master/CHANGES.md, we removed the login, due to Security vulnerabilities reported. We don't have committers to make sure it works, so removed.

**Comment by bowenliang123** [comment]
Any plan for bringing back the login back to Skywalking webapp ui?
We don't want the webapp pages are accessible for anonymous visits.

**Comment by wu-sheng** [comment]
You could build your login easily. Today, no contributor is trying to bring it back in a security way.

**Comment by meua** [comment]
We can only build our own secure login method through OAuth2 and other means. Won't skywalking build its own secure login in reverse?

**Comment by wu-sheng** [comment]
We could accept contributions to make login back. It is removed because have to. Because old one is not security
