### ISSUE TITLE
skywalking ttl

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3202]
I want to know which one will take effect when default ttl and elasticsearch ttl are present？
`

core:
  default:
    # Mixed: Receive agent data, Level 1 aggregate, Level 2 aggregate
    # Receiver: Receive agent data, Level 1 aggregate
    # Aggregator: Level 2 aggregate
    role: ${SW_CORE_ROLE:Mixed} # Mixed/Receiver/Aggregator
    restHost: ${SW_CORE_REST_HOST:0.0.0.0}
    restPort: ${SW_CORE_REST_PORT:12800}
    restContextPath: ${SW_CORE_REST_CONTEXT_PATH:/}
    gRPCHost: ${SW_CORE_GRPC_HOST:0.0.0.0}
    gRPCPort: ${SW_CORE_GRPC_PORT:11800}
    downsampling:
    - Hour
    - Day
    - Month
    enableDataKeeperExecutor: ${SW_CORE_ENABLE_DATA_KEEPER_EXECUTOR:true}
    recordDataTTL: ${SW_CORE_RECORD_DATA_TTL:90} # Unit is minute
    minuteMetricsDataTTL: ${SW_CORE_MINUTE_METRIC_DATA_TTL:90} # Unit is minute
    hourMetricsDataTTL: ${SW_CORE_HOUR_METRIC_DATA_TTL:36} # Unit is hour
    dayMetricsDataTTL: ${SW_CORE_DAY_METRIC_DATA_TTL:7} # Unit is day
    monthMetricsDataTTL: ${SW_CORE_MONTH_METRIC_DATA_TTL:1} # Unit is month
storage:
  elasticsearch:
    nameSpace: ${SW_NAMESPACE:"skywalking-es"}
    clusterNodes: ${SW_STORAGE_ES_CLUSTER_NODES:1.1.1.1:9200,1.1.1.2:9200,1.1.1.3:9200}
    indexShardsNumber: ${SW_STORAGE_ES_INDEX_SHARDS_NUMBER:2}
    indexReplicasNumber: ${SW_STORAGE_ES_INDEX_REPLICAS_NUMBER:0}
    recordDataTTL: ${SW_STORAGE_ES_RECORD_DATA_TTL:7} # Unit is day
    otherMetricsDataTTL: ${SW_STORAGE_ES_OTHER_METRIC_DATA_TTL:7} # Unit is day
    monthMetricsDataTTL: ${SW_STORAGE_ES_MONTH_METRIC_DATA_TTL:1} # Unit is month
    bulkActions: ${SW_STORAGE_ES_BULK_ACTIONS:2000} # Execute the bulk every 2000 requests
    bulkSize: ${SW_STORAGE_ES_BULK_SIZE:20} # flush the bulk every 20mb
    flushInterval: ${SW_STORAGE_ES_FLUSH_INTERVAL:10} # flush the bulk every 10 seconds whatever the number of requests
    concurrentRequests: ${SW_STORAGE_ES_CONCURRENT_REQUESTS:2} # the number of concurrent requests
    metadataQueryMaxSize: ${SW_STORAGE_ES_QUERY_MAX_SIZE:5000}
    segmentQueryMaxSize: ${SW_STORAGE_ES_QUERY_SEGMENT_SIZE:200}
`

**Comment by wu-sheng** [comment]
The document has said that. If ElasticSearch is set as storage, then core TTL will be ignored.

**Comment by SevenBlue2018** [comment]
https://github.com/apache/skywalking/blob/5036e8334301322d49973005cd98513c17b0f28f/docs/en/setup/backend/ttl.md
This document has not said that.

**Comment by wu-sheng** [comment]
How do you understand this?  
![image](https://user-images.githubusercontent.com/5441976/62348965-f41b5380-b530-11e9-8e20-3be031183e72.png)

I think it is clear enough. If you want, submit a pull request to add new words.

**Comment by 1346735074** [comment]
May I ask which parameter is set to control the days of retained data of sky's es

**Comment by wu-sheng** [comment]
@1346735074 Read the document posted above, it is all there.

**Comment by 1346735074** [comment]
@wu-sheng Yes, I have read this document, but it is not clear that it is controlled by that parameter

**Comment by wu-sheng** [comment]
@1346735074 Like the doc said, there are several, not just one single parameter.

**Comment by 1346735074** [comment]
@wu-sheng Yes, because of multiple parameters, it is not clear which parameter can achieve the desired effect, the comments are not obvious
```
recordDataTTL： $ {SW_STORAGE_ES_RECORD_DATA_TTL：7} ＃单位为天
    otherMetricsDataTTL： $ {SW_STORAGE_ES_OTHER_METRIC_DATA_TTL：45} ＃单位为天
    monthMetricsDataTTL： $ {SW_STORAGE_ES_MONTH_METRIC_DATA_TTL：18} ＃机组是月
```

**Comment by wu-sheng** [comment]
@1346735074 Because there are several dimensionalities. Such as 
1. The metrics data in month level, it is impossible to set the TTL as day to control it, right?
1. The record including alarm and trace details, so it is huge data, it can't be kept as same as metrics usually. 

So there are 3 kinds of TTL settings.

**Comment by 1346735074** [comment]
@wu-sheng Well, I want to know what these three parameters mean，
recordDataTTL
otherMetricsDataTTL
monthMetricsDataTTL

**Comment by wu-sheng** [comment]
@1346735074 Do you basically know how SkyWalking save data?
1. Record type, trace segment, alarm
1. Metrics in different dimensionalities. Minute, Hour, Day, Month.
1. Inventory. Metadata. Can't be erased by TTL.

recordDataTTL -> (1), otherMetricsDataTTL -> (2) in Minute, Hour, Day, monthMetricsDataTTL -> (2) in monthMetricsDataTTL.

**Comment by 1346735074** [comment]
@wu-sheng Do the following Settings refer to 7 days of failure clearance?
```
    recordDataTTL： $ {SW_STORAGE_ES_RECORD_DATA_TTL：7} ＃单位为天
    otherMetricsDataTTL： $ {SW_STORAGE_ES_OTHER_METRIC_DATA_TTL：45} ＃单位为天
    monthMetricsDataTTL： $ {SW_STORAGE_ES_MONTH_METRIC_DATA_TTL：18} ＃机组是月
```

**Comment by wu-sheng** [comment]
I don't understand your question.

**Comment by 1346735074** [comment]
@wu-sheng If 7 days are set to clear the data of es, what are the corresponding Settings of these three parameters

**Comment by 1346735074** [comment]
@wu-sheng The default of these three parameters is how long to clear es

**Comment by wu-sheng** [comment]
I have given you an explanation of the kinds of data. Why are you keeping asking? Have you read the whole document? You need to understand the system first. I think you are just guessing.

**Comment by SevenBlue2018** [comment]
![image](https://user-images.githubusercontent.com/11767168/63067530-02f70280-bf42-11e9-8ca4-c31d07835a3a.png)
![image](https://user-images.githubusercontent.com/11767168/63067612-5d905e80-bf42-11e9-9c19-27d57024fb46.png)
I think the ttl rule does not take effect.I have read the documentation but still don't understand.I need your help, thank you.
