### ISSUE TITLE
skywalking UI no data

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3210]
![image](https://user-images.githubusercontent.com/11767168/62409228-b852bd80-b606-11e9-90fa-eb7b94ecc29c.png)
Why this console has no any data?

**Comment by SevenBlue2018** [comment]
![image](https://user-images.githubusercontent.com/11767168/62409285-4c248980-b607-11e9-8b23-9fef45ec5482.png)

**Comment by wu-sheng** [comment]
Why do you query so large page size? This size could trigger elasticsearch error, if you want that, change elasticsearch settings.

**Comment by SevenBlue2018** [comment]
change what?

**Comment by SevenBlue2018** [comment]
I has changed the time but it does not work
