### ISSUE TITLE
Elasticsearch index was not created for each day

### ISSUE THREAD

**Issue by yijiuping** [apache/skywalking#3214]
The issue we have encountred is we cannot see any trace logs after 2019-08-04 23:59:59, and I checked the elasticsearch index segment, but I can only see the name segment-20190804 there.  I also checked the creation time of segment-20190804, it was created in 2019-08-04 00:02. Whether we expected to see the segment-20190805 or not? 

BTW, we are using the latest version 6.2.0.

**Comment by wu-sheng** [comment]
How long have you used the 6.2.0? How many days? Check other indexes, such as service_p99.

**Comment by yijiuping** [comment]
>  How long have you used the 6.2.0? How many days? Check other indexes, such as service_p99.

Thanks for your quick response!! We upgraded our deployment from 6.1.0 to 6.2.0 in July, acutually, we just using it for two weeks, and not always can get the trace logs. I want to find out the reason and fix it.  As your guidence, I checked the indices in ES, I can see blow list: service_p99-20190804
service_p99_hour-20190804
service_p99_month-201907
service_p99_day-20190804

**Comment by wu-sheng** [comment]
First, if upgrade happens, have you removed all elasticsearch indexes? Auto created based on elasticsearch template. From you posted, the indexes can't be created, the existing is created by bootstrap.

So make sure your elasticsearch index have been removed.

**Comment by yijiuping** [comment]
> First, if upgrade happens, have you removed all elasticsearch indexes? Auto created based on elasticsearch template. From you posted, the indexes can't be created, the existing is created by bootstrap.
> 
> So make sure your elasticsearch index have been removed.

We reinstalled ES, SkyWalking OAP and SkyWalking Agent from stratch, the indexes were auto created by SkyWalking 6.2.0.  Do you mean it's not the standard way?

**Comment by wu-sheng** [comment]
Re-install could trigger index creation, yes. But after the first day, the index creation is based on ElasticSearch template, which we created too, by using the old index name, such as `service_p99`. Check your ElasticSearch template setting, to see whether it is there.

**Comment by yijiuping** [comment]
> Re-install could trigger index creation, yes. But after the first day, the index creation is based on ElasticSearch template, which we created too, by using the old index name, such as `service_p99`. Check your ElasticSearch template setting, to see whether it is there.

Thanks for your guidence! We missed the templates creation step! I cannot find the guide about this step, can you provide us an URL?

**Comment by wu-sheng** [comment]
Template created through codes when OAP start up. If you can't find it in ES, I think maybe you have the old indexes which are sharing the same names.

**Comment by yijiuping** [comment]
> Template created through codes when OAP start up. If you can't find it in ES, I think maybe you have the old indexes which are sharing the same names.

I just checked the ES templates, they are all created by default. :)

**Comment by wu-sheng** [comment]
Then the index should be created when data flows in. It is created based on your metrics/segments etc. If you can't create, maybe something forbids you, I heard (but not be sure), some ElasticSearch service(such as in AliCloud), they have options to disable this auto index creation.

**Comment by yijiuping** [comment]
> Then the index should be created when data flows in. It is created based on your metrics/segments etc. If you can't create, maybe something forbids you, I heard (but not be sure), some ElasticSearch service(such as in AliCloud), they have options to disable this auto index creation.

:( We are using AliCloud. I will confirm it. Thank you very much!!!
