### ISSUE TITLE
ui display failure in mac+chrome

### ISSUE THREAD

**Issue by zhang98722** [apache/skywalking#3217]
![企业微信截图_8b45180f-4905-4d62-b5a3-01dd5a06dff2(1)](https://user-images.githubusercontent.com/7775417/62441316-21ad0a80-b786-11e9-869b-227545485811.png)
![企业微信截图_15649832485887](https://user-images.githubusercontent.com/7775417/62441317-2245a100-b786-11e9-8780-53d00ab51cc8.png)

**Comment by wu-sheng** [comment]
What is the issue? Layout?

**Comment by zhang98722** [comment]
![QQ截图20190805135130](https://user-images.githubusercontent.com/7775417/62441812-2c689f00-b788-11e9-8134-eda4cac66f41.png)

here is the right version in window chrome

---

i extend the httpclient agent to log request body and response body
but the layout of trace log not work properly

**Comment by wu-sheng** [comment]
In my chrome(Mac too), when it shows a long tag, it looks like this way, flowing to another line. Are you tagging value without any whitespace? Scrolling is not the thing we expected.
![image](https://user-images.githubusercontent.com/5441976/62442822-b2d2b000-b78b-11e9-8e91-42fb5e7ca9d2.png)

**Comment by wu-sheng** [comment]
Also, this feature is added by you, so you need to fix on your own env. We can't make our UI suitable for every env, you could send a pull request to fix that, but I would recommend you to use whitespace and change a new line.
