### ISSUE TITLE
Support Gateway w/o agent

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#3218]
Today, we asked for agents in every node, but in reality, we may not have suitable agents, due to language or plugin. So in the backend, we should provide a way to tell the analysis core, there is a gateway or proxy to represent as a load balancer for multiple services.

We should add setting about trace-receiver, also active as dynamic configuration. We should list
1. Proxy service name.
1. IP(host name) list under all proxy service.
1. Generate service and service instance for each service and its IP.
1. Change A->B(when there is no agent in the proxy), to A -> proxy -> B, meaning while `A -> peer` as A to proxy as the client-side and service incoming metrics, `ref -> B` as proxy to B server-side metrics and service incoming metrics.

**Comment by PrettyJerry** [comment]
YES !!! Frankly speaking, this feature is great, especially in the production env, which is a landmark feature.

**Comment by guojie0701** [comment]
I'm looking forward to this feature very much. Thank you very much,  so many proxy and gateway in our production environment just like nginx / openresty / haproxy / api-gw  ，really hell.   thanks .

**Comment by wu-sheng** [comment]
Anyone watching here, #3308 is going to be merged soon, if you have interests, welcome to use the master branch to test.
