### ISSUE TITLE
What's the fullname for "JDBI" ?

### ISSUE THREAD

**Issue by qxo** [apache/skywalking#3223]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What's the fullname for "JDBI" ?
ref: https://github.com/apache/skywalking/blob/5e8410834de20254c2bdab2d86cdbfd79d600904/apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/trace/CallableStatementTracing.java#L40
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
It is a historical issue. In Java, we used to call it JDBC, but the instrumentations of Database access are targeting the JDBC interface, so be called as JDBI(JDBC-Interface), but today it is totally not the case:)

Old name mismatch today's name. But considering the forward-compatible, we haven't any change to change it.

**Comment by wu-sheng** [comment]
Btw, OpenTracing calls this JDBI too, even I don't think it doesn't make much sense.

**Comment by qxo** [comment]
ok, thanks:)
