### ISSUE TITLE
skywalking gc info

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3227]
![image](https://user-images.githubusercontent.com/11767168/62620001-b5c7cf00-b94a-11e9-9e26-1f4dfa3c50fa.png)
I do not know what means? How long gc count will be reseted?

**Comment by wu-sheng** [comment]
Based on the duration you selected

**Comment by SevenBlue2018** [comment]
I do not select any duration in this page.

**Comment by SevenBlue2018** [comment]
This page means the instance gc info, it has not any duration to be selected.

**Comment by wu-sheng** [comment]
Why do you say so? Every page has duration in the right bottom of page

**Comment by SevenBlue2018** [comment]
![image](https://user-images.githubusercontent.com/11767168/62621271-0ab91480-b94e-11e9-9aaf-acb2ad36ec4b.png)
Where the duration of this page?

**Comment by wu-sheng** [comment]
Right bottom. Always in every page

**Comment by SevenBlue2018** [comment]
Please see the picture. I do not change any thing. This picture has no the duration.

**Comment by wu-sheng** [comment]
I am not following the question. I don't understand what does your screenshot mean.

Query condition includes duration, why you focus on graph only?  There is no reset thing.

**Comment by SevenBlue2018** [comment]
First, this page has no the duration.Second, I just want to know what the gc count means.

**Comment by wu-sheng** [comment]
I still can't get your point.. What you call this?
![image](https://user-images.githubusercontent.com/5441976/62624767-6091ba80-b956-11e9-9053-708ad3d639f6.png)
