### ISSUE TITLE
Add option to start/stop collecting sql parameter

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#323]
cc @ascrutae @pengys5 

I want to add this feature, after we have config downstream mechanism.

**Comment by wu-sheng** [comment]
Based on #325

**Comment by wu-sheng** [comment]
cc  @aliluyahoho

**Comment by foxracle** [comment]
Add option to start/stop collecting sql parameter is a good feature whatever it is configured in the agent side or it is downstreaming from collector. I want to know the feature's current progress, or where I can start from to implement it by myself for a java newbie like me ;)

**Comment by wu-sheng** [comment]
> I want to know the feature's current progress

No, tag **TBD** means on one is doing this.

**Comment by wu-sheng** [comment]
Supported in 6.2.0 by @kezhenxu94
