### ISSUE TITLE
Support configurable agent-config to config logging format and output where

### ISSUE THREAD

**Issue by mm23504570** [apache/skywalking#3231]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
I wish config log format and always output to system.out.   Not output a file. 

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.3.0. k8s
- Which company or project?
ShuiDi Company
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Can we provider the configurable entry?  like logback or log4j2?

**Comment by wu-sheng** [comment]
This is an easy one to contribute. Welcome to submit a pull request.
