### ISSUE TITLE
skywalking alarm

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3232]
![image](https://user-images.githubusercontent.com/11767168/62708330-c39e5280-ba25-11e9-8b9a-5c789416d6d9.png)
I want to send the message to dingding service. For example, curl 'https://oapi.dingtalk.com/robot/send?access_token=*****' -H 'Content-Type: application/json' -d '{"msgtype": "text", "text": {"content": "test"}}'.I do not know how can I send this message in this format.

**Comment by kezhenxu94** [comment]
> I want to send the message to dingding service. For example, curl 'https://oapi.dingtalk.com/robot/send?access_token=*****' -H 'Content-Type: application/json' -d '{"msgtype": "text", "text": {"content": "test"}}'.I do not know how can I send this message in this format.

You cannot directly configure the DingTalk OpenAPI as the alarm webhook, you'll need to provide your own web API service and adapt the alarm message (of SkyWalking) to the message type of DingTalk

**Comment by SevenBlue2018** [comment]
![image](https://user-images.githubusercontent.com/11767168/62709037-2e03c280-ba27-11e9-99bc-10e995210d1b.png)
Now the alarm rule has been effected, but it does not send the alarm message. I want to read the log info to sort out problems, but I do not see any alarm log.

**Comment by SevenBlue2018** [comment]
@kezhenxu94 Thank you, I see.

**Comment by SevenBlue2018** [comment]
Now the alarm rule has been effected, but it does not send the alarm message. I want to read the log info to sort out problems, but I do not see any alarm log.
