### ISSUE TITLE
Skywalking UI

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3234]
![image](https://user-images.githubusercontent.com/11767168/62752643-f0408180-ba9a-11e9-8a27-78d0a8868edc.png)
There is no data on the page. I checked the UI log and found the error message "java.net.SocketTimeoutException: Read timed out". There is no error data on the OAP Server log. I checked that the system indicators were all right.

**Comment by wu-sheng** [comment]
I can't tell why as you said others are well. I think you have to locate why by yourself. first. My guess, your storage, maybe es, is not working well.

**Comment by SevenBlue2018** [comment]
I restarted the es and adjusted the paramters of the jvm. Now OAP Server log always prints the null pointer exceptions.
![image](https://user-images.githubusercontent.com/11767168/62762691-4671ec80-babc-11e9-8349-4701b47d06d8.png)
I do not know the reason.

**Comment by SevenBlue2018** [comment]
Only a few applications are shown on the UI page. I checked the logs of one of the another applications as follows:
![image](https://user-images.githubusercontent.com/11767168/62762954-e596e400-babc-11e9-9a90-e8d3d55f93fd.png)
It looks normal from the log, but you don't see the application on the page.

**Comment by SevenBlue2018** [comment]
Now I see the application on the page coming out again.The null pointer in the log is abnormally missing.

**Comment by SevenBlue2018** [comment]
Now I see the application on the page coming out again.The null pointer in the log is abnormally missing.
![image](https://user-images.githubusercontent.com/11767168/62766560-5510d180-bac5-11e9-9a53-603516ea96f5.png)
