### ISSUE TITLE
When can it be compatible with 7.0 + es

### ISSUE THREAD

**Issue by 1346735074** [apache/skywalking#3235]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

When can it be compatible with 7.0 + es
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No plan yet. We are not chasing the latest version. It is not very friendly to change this in high frequency.
