### ISSUE TITLE
restart k8s oap cluster make some agents disconnect with oap

### ISSUE THREAD

**Issue by qlql489** [apache/skywalking#3238]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
we set oap with k8s cluster use 3 nodes,  after access more agent  we want to increase to 5 nodes ,but  aflter restart oap service ,a lots of agent log show error, they can't connect to opa, aflter restart agent , it goes right,   the error  logs show:

WARN 2019-08-09 20:50:40:484 DataCarrier.DEFAULT.Consumser.0.Thread GRPCStreamServiceStatus :  Collector traceSegment service doesn't response in 100955 seconds.

when restart oap  we need to  restart all agents?   or  what is the safe way to expand oap server's number
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.2.0
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Could you test 6.3.0 first? There is a bug in 6.2.0-, fixed by @kezhenxu94

**Comment by wu-sheng** [comment]
` Collector traceSegment service doesn't response ` also means, server-side is not active.
