### ISSUE TITLE
With Elasticsearch, Too Many Read request in service_instance_inventory

### ISSUE THREAD

**Issue by daigong** [apache/skywalking#3251]
Please answer these questions before submitting your issue.

### Question
- What do you want to know?
I have 50+ services、150+ Endpoints，the Search Rate of service_instance_inventory index in es is 600+ , is it normal ?
___
### Bug
- Which version of SkyWalking, OS and JRE?
Ubuntu 1404、JDK8、Skywalking 6.3.0
- Which company or project?
Mxnavi
- What happen?
Nothing wrong，Just Search Rate is keeping high

**Comment by wu-sheng** [comment]
For the search rate, it related to shard and query TPS. But in my understanding, cache should stop most of the query. I am not sure why.

**Comment by daigong** [comment]
> For the search rate, it related to shard and query TPS. But in my understanding, cache should stop most of the query. I am not sure why.

I close web ui，it maybe calculate p99、p95 ....
