### ISSUE TITLE
How can I configure ACK in zookeeper-cluster

### ISSUE THREAD

**Issue by xiangyanggong** [apache/skywalking#3256]
Please answer these questions before submitting your issue.

___
### Question
In my Env, ZK was set ACL, if I don't configure it, I can get this error： "KeeperErrorcode=NoAuth for /skywalking" when starting skywalking. I checked document, but I can't find corresponding entry in:

zookeeper:
  nameSpace: ${SW_NAMESPACE:""}
  hostPort: ${SW_CLUSTER_ZK_HOST_PORT:localhost:2181}
  #Retry Policy
  baseSleepTimeMs: ${SW_CLUSTER_ZK_SLEEP_TIME:1000} # initial amount of time to wait between retries
  maxRetries: ${SW_CLUSTER_ZK_MAX_RETRIES:3} # max number of times to retry
  internalComHost: 172.10.4.10
  internalComPort: 11800

### Bug
- Which version of SkyWalking, OS and JRE?
V6.2.0

**Comment by dmsolr** [comment]
As I know, we don't support this now.

**Comment by wu-sheng** [comment]
We don't support. If you want, submit pull request w/ explanation.
