### ISSUE TITLE
sample propagation when root service not sampling

### ISSUE THREAD

**Issue by ralphgj** [apache/skywalking#3259]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hi, I found that agent not handle the condition when sample equals 0 in ContextCarrier. So I can't decide the sample of whole trace through the root service's sample just like [brave](https://github.com/openzipkin/brave). How to solve this situation?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean sample == 0? What is the point? Tracing based on root sample is default and always in this way, you don't need to set.

**Comment by ralphgj** [comment]
Assume in this scene，the service dependency: A -> B -> C. When A not sampling, the B should not sampling too. But now sampling==0 in A will not be propagated to B, so we will get an incomplete trace.

**Comment by wu-sheng** [comment]
No, in SkyWalking that is not right. If service A sampled, then service B should always be sampled, but if A is not, then B even doesn't know A existing, it chooses based on its own sampling mechanism.

SkyWalking not sampled means agent running in mini payload, no actual data. We don't support the case you are saying.

In SkyWalking 100% sampling is recommended.

**Comment by ralphgj** [comment]
Do you consider supporting the case in the future?

**Comment by wu-sheng** [comment]
> Do you consider supporting the case in the future?

I don't think so, that is not fitting APM requirement. Most cases, we need whole traces to get accurate metrics.

**Comment by ralphgj** [comment]
Thanks.

**Comment by pkxiuluo** [comment]
we must manage to discard some data when sometimes we can't afford the cost, But we dont want the tracing break.
Either agent-sample or bankend-sample will lead to this.
Would you please reconsider  @ralphgj   proposal。

**Comment by wu-sheng** [comment]
@pkxiuluo I can't see anything changed, if you have more to discuss, open a new discussion rather than comments in a very old one.

**Comment by pkxiuluo** [comment]
sorry , problem is not exist.
After I checked backend-sample carefully.
I found that the sample algorithms use traceId hash as sample factor.
And that can guarantee the trace tree not break。

related code:
org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.TraceSegmentSampler#shouldSample

```
public boolean shouldSample(String traceId) {
 return Math.abs(traceId.hashCode()) % 10000 < traceSampleRateWatcher.getSampleRate();
}
```
