### ISSUE TITLE
recordDataTTL do not work

### ISSUE THREAD

**Issue by xiongrl** [apache/skywalking#3263]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
recordDataTTL notwork！
-  storage:
      elasticsearch:
  	recordDataTTL: 45

```java
   RecordStreamProcessor.create(){
     Model model = modelSetter.putIfAbsent(recordClass, stream.scopeId(),
                new Storage(stream.name(), true, true, Downsampling.Second), true);
  }

 public class ElasticsearchStorageTTL implements StorageTTL {
    @Override public TTLCalculator calculator(Downsampling downsampling) {
        switch (downsampling) {
            case Month:
                return new MonthTTLCalculator();
            case Hour:
                return new EsHourTTLCalculator();
            case Minute:
                return new EsMinuteTTLCalculator();
            default:
                return new DayTTLCalculator();
        }
    }
}  
public class DayTTLCalculator implements TTLCalculator {

    @Override public long timeBefore(DateTime currentTime, DataTTLConfig dataTTLConfig) {
        return Long.valueOf(currentTime.plusDays(0 - dataTTLConfig.getDayMetricsDataTTL()).toString("yyyyMMdd"));
    }
}
```

**Comment by xiongrl** [comment]
commit

**Comment by wu-sheng** [comment]
What is your problem? TTL of ES is day related.

**Comment by xiongrl** [comment]
storage:
   elasticsearch:
       recordDataTTL: 45

trace data was deleted once every two days.

2019-08-13 00:02:03,809 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 161 [pool-17-thread-1] DEBUG [] - delete skywalking_segment-20190811 index finished, isAcknowledged: true

**Comment by wu-sheng** [comment]
OK. Get your point. Are you saying the TTL of the record is using TTL of day metrics, right?

**Comment by xiongrl** [comment]
yes

**Comment by wu-sheng** [comment]
ES and other storages have this same issue. Reporting bug to @peng-yongsheng

**Comment by wu-sheng** [comment]
Fixed. @xiongrl Could you recheck the master branch, and recheck at your env?
