### ISSUE TITLE
The values of Global Percent Response are illogical.

### ISSUE THREAD

**Issue by tedinGH** [apache/skywalking#3267]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Bug
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.3.0, Red Hat Enterprise Linux Server release 6.1 (Santiago), Java(TM) SE Runtime Environment (build 1.8.0_171-b11)

- What happen?
![QQ截图20190814164552](https://user-images.githubusercontent.com/7204092/63007810-ef9d5600-beb3-11e9-8f1a-8f8e0a94939b.jpg)

Obviously, the values are illogical.
BTW, which I use is the Linux Binary Distribution.

**Comment by wu-sheng** [comment]
First, upgrade version to 6.3.0, we noticed dirty read in prev release when ElasticSearch is not powerful enough. Then, make your your ElasticSearch bulk settings are right, otherwise, you will lose the update randomly.
