### ISSUE TITLE
can we filter by namespace(setting in agent.config) in skywalking UI?

### ISSUE THREAD

**Issue by makingtime** [apache/skywalking#3269]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [×] Question or discussion

___
### Question
- What do you want to know?
can we filter by namespace(setting in agent.config) in skywalking UI?
for example:
	in topology page, if we choose "dubbo-app-1", then only components(consumers/providers...) in "dubbo-app-1" will show in topology.

if not, what's the usage of this "namespace" setting?

**Comment by wu-sheng** [comment]
No. Namespace is for isolation, not tenancy.
