### ISSUE TITLE
6.2release upgrade to 6.3question

### ISSUE THREAD

**Issue by wentjiang** [apache/skywalking#3271]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?
I want to upgrade my prod env 6.2 to 6.3 ,i test on QA env ,but there are some element lose on web page ,
I want know ,how can I upgrade my skywalking smoothly?
___

**Comment by wu-sheng** [comment]
All upgrade before 6.3.0 running, the safest way is reboot agents. Or use blue-green deployment solution. Move the target service to 6.3.0 when it is OK to reboot.

After 6.3.0 agent deployed, read this, https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-setup.md#agent-hot-reboot-trigger-mechanism-in-oap-server-upgrade
