### ISSUE TITLE
Skywalking UI blank

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3276]
![image](https://user-images.githubusercontent.com/11767168/63148178-f69ea280-c032-11e9-843a-2ccdc3f91007.png)
Why is the area in the box blank?

**Comment by SevenBlue2018** [comment]
I see that the response data is normal.

**Comment by wu-sheng** [comment]
You have to do some UI debug, my guess, traces break somehow, and UI can't show up.

**Comment by TinyAllen** [comment]
@SevenBlue2018 Can you give me your response body data, l think it may has a broken link in it.

**Comment by SevenBlue2018** [comment]
![image](https://user-images.githubusercontent.com/11767168/63350772-9be9ab80-c390-11e9-806d-c3caee459b78.png)

**Comment by wu-sheng** [comment]
@SevenBlue2018 Copy the JSON to a file and uploaded. We need the whole text to debug and find out why.

**Comment by SevenBlue2018** [comment]
ok

**Comment by SevenBlue2018** [comment]
[SKywalking UI Data.txt](https://github.com/apache/skywalking/files/3523327/SKywalking.UI.Data.txt)

**Comment by wu-sheng** [comment]
@TinyAllen When you have time, please try to debug why.

**Comment by TinyAllen** [comment]
![image](https://user-images.githubusercontent.com/19775780/63757471-aeae3400-c8ec-11e9-8228-8341299cd897.png)

![image](https://user-images.githubusercontent.com/19775780/63757439-a2c27200-c8ec-11e9-8a96-458ca93f979d.png)

The root span can't has refs ,so it is a broken trace

**Comment by lmx1989219** [comment]
@wu-sheng   
@TinyAllen i get the same questions.
![image](https://user-images.githubusercontent.com/9464485/125154059-9cf57300-e18a-11eb-8a78-d3467799c3b1.png)
