### ISSUE TITLE
The skywalking oap server  cpu is too high to reach 100%

### ISSUE THREAD

**Issue by liyongfa0311** [apache/skywalking#3281]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
skywalking oapServer CPU is in 100% by standalone mode.I am adding 20 service monitors,
What do I need to do to get the CPU usage down?
___
### Bug
- Which version of SkyWalking, OS and JRE?
 CentOS7.3
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
How many CPUs? Which storage? How many agent instances?

**Comment by liyongfa0311** [comment]
4 core cpu，all reach 100%,8g ,abount 40 agent instances,I used jstack to find that there are a lot of threads waiting in the state.

**Comment by wu-sheng** [comment]
SkyWalking version? I am wondering the storage, do you use Elasticsearch cluster?

**Comment by liyongfa0311** [comment]
the skywalking that I used is 6.2.0 and I use Es cluster,, the machine of es is 16c32g

**Comment by wu-sheng** [comment]
Try 6.3.0, it will reduce some payload to OAP. But to be honest, 4c simple node OAP for 40 node agents, looks like not powerful enough. SkyWalking does aggregations inside OAP by using internal stream computing core, it is not a simple collector to receive and save.

Also, check your ES status, and our recommendations about ES bulk settings.
