### ISSUE TITLE
Modify agent log path

### ISSUE THREAD

**Issue by lvchhenyang** [apache/skywalking#3282]
Please  answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
[Here](https://github.com/apache/skywalking/tree/master/docs/en/setup/service-agent/java-agent#table-of-agent-configuration-properties) are the options, you can find the option to change the log path and log file name
