### ISSUE TITLE
How to do agent hot loading

### ISSUE THREAD

**Issue by spurtAndy** [apache/skywalking#3285]
as title

**Comment by kezhenxu94** [comment]
We don't support this

**Comment by spurtAndy** [comment]
3Q

**Comment by wncboy** [comment]
Is the current version still not supported?

**Comment by wu-sheng** [comment]
The conclusion had been there for years. This is not just not supported yet, instead, we decided for better performance rather than supporting this.
This is a decision made tradeoff.

**Comment by wncboy** [comment]
> The conclusion had been there for years. This is not just not supported yet, instead, we decided for better performance rather than supporting this.
> This is a decision made tradeoff.

Okay, Thanks
