### ISSUE TITLE
Is there any plan for the C++ client ?

### ISSUE THREAD

**Issue by BinWu1989** [apache/skywalking#3288]
@wu-sheng Dear WuSheng ,

As the official document, currently skywalking doesn't have an client for C++ ,Is there any plan to support C++ in the near furture?

**Comment by wu-sheng** [comment]
We don't have core maintainer in C++. Are you interested in this?

Duplicated #2443

**Comment by BinWu1989** [comment]
sorry ,I am a java developer, Just make confirmation if there any c++ client in schedule ,As we need to choose a plan that need to take C++ application into consideration

**Comment by wu-sheng** [comment]
No, we don't have that. If you have C++ developer, I would recommend you to use go2sky as a good example.
