### ISSUE TITLE
rest protocol of dubbo not supported

### ISSUE THREAD

**Issue by SamPeng87** [apache/skywalking#3294]
Which version of SkyWalking, OS and JRE?
skywalking-agent.jar:6.3.0
linux
JRE 8

What happen?
exception throwed while calling dubbo service through rest protocol.

Caused by: javax.ws.rs.ProcessingException: java.lang.IllegalArgumentException: The attachments of RpcContext must not contain ',' or '=' when using rest protocol

I see dubbo RxContext source, is force not allow use ','  or '='.

SkyWalking protocol v2 use base64 encoding.it maybe have char '=' in string endding

**Comment by wu-sheng** [comment]
I don't know why Dubbo rest doesn't support this. It is common in HTTP, as you can see, this header has no issue in other REST frameworks. Could you submit an issue at Dubbo, and we could start a discussion at there?

**Comment by SamPeng87** [comment]
I think this dubbo rest protocol claim this format。this code exist more year~

then，I review skywarking source， this problem happen becase BASE64。

this class define common BASE64 format，but this is used for resolve jre 6 no base64 encoder。

maybe use urlencode can resolve this problem？

**Comment by wu-sheng** [comment]
We can't change the format, my question is about why. BASE64 is working in most frameworks, and what is the issue of Dubbo REST.

**Comment by wu-sheng** [comment]
5 languages agents are sharing this protocol, so we can't see any chance to change it, and I am open to talk about why this is an issue to Dubbo. Because in REST, the peer side could be an un-dubbo service, if they put `=` in the header value, it looks like a break too.

Would not this an issue to Dubbo rather than to SkyWalking?

There is a lot of `=` existing in HTTP header, ref a simple blog, https://code.tutsplus.com/tutorials/http-headers-for-dummies--net-8039

**Comment by SamPeng87** [comment]
yes,i know your mean.but some people use dubbo rest,I think we can't wait dubbo fixbug.I recognition this is dubbo rest problem。ok,I will review dubbo source. close this issue，and try submit an issue at Dubbo。we like this project，and we have 40 micro service。so we need one trace service used quick。maybe we only fork skywalking quick fix this problem and wait dubbo fix this bug

**Comment by SamPeng87** [comment]
Oh，I see because we use Dubbo-Attachments this head to pass trace info。this is have some limit。
dubbo RpcContextFilter limit this header not use , and =。I think this head have many of other effect。this code have exist more year。

https://github.com/apache/skywalking/commit/2f86b1b3ee58e09b576f6d0d641e7a40b593abba

this commit resolve this problem？

**Comment by SamPeng87** [comment]
Oh, We use dubbo 2.6.6..this hava problem? I think this exception not because version.dubbo master branch have this limit too.

**Comment by wu-sheng** [comment]
You are thinking Dubbo ecosystem would not change, but ask SkyWalking to change, I am afraid this is not going to happen. In reality, the only way is to keep this in public discussion, especially in Dubbo community, because they set the limits, right?

**Comment by wu-sheng** [comment]
Please forward this issue to Dubbo, and let's talk what happens. SkyWalking can't change header protocol, it is public and even sealed. This is the protocol level for us. From my perspective, I could help you to argue with Dubbo community, rather than change the protocol. 

SkyWalking relies on our protocol stable very much. Dubbo community would not change protocol easily too, but this limit should not a protocol level thing.

**Comment by SamPeng87** [comment]
yes，I review dubbo rest source。dubbo rest ‘s Attachments is not a good implement。I know why this is happen now。。this not skywalking problem。。。you are right。and review own code。 We only use common method call something，is a great implement。ok，I subbmit issue or pr for dubbo。thank your help。

**Comment by Lumia001** [comment]
Surprisingly ! 
 I meet the same problem......In dubbo's rest protocal, before the RpcContextFilter of implements ContainerRequestFilter  sets header's k/v into  RpcContext's Attachment, require value must be contain '=' or ',' .

For this situation, I can't give up dubbo' rest protocal or SW. 

So, make something to figure it out.

Here is a complete and perfect solution !

First:
---------------------part one---------------------------
@Provider
@Priority(Priorities.HEADER_DECORATOR )
public class SwClientFilter implements ClientRequestFilter {

    @Override
    public void filter(ClientRequestContext requestContext) throws IOException {
        for (Map.Entry<String, String> entry : RpcContext.getContext().getAttachments().entrySet()) {
            if (entry.getKey().equals("sw6")){
                String value = entry.getValue();
                String replaceAll= value.replaceAll("=", "%");
                entry.setValue(replaceAll);
                return;
            }
        }
    }
}

-----------------------------part two.--------------------------
@Provider
@Priority(Integer.MIN_VALUE + 20)
public class SwContainerFilter implements ContainerRequestFilter {

    @Override
    public void filter(ContainerRequestContext requestContext) {
        for (Map.Entry<String, String> entry : RpcContext.getContext().getAttachments().entrySet()) {
            if (entry.getKey().equals("sw6")){
                String value = entry.getValue();
                String replaceAll= value.replaceAll("%", "=");
                entry.setValue(replaceAll);
                return;
            }
        }
    }
}


Then:

add custom filter in <dubbo:protocal extension="........................">



Welcom to try it ~

**Comment by wu-sheng** [comment]
@Lumia001 We explained this, and Dubbo should have fixed this. Check the linked commit id

**Comment by Lumia001** [comment]
It seems to be no. 
Recently, I did upgrade dubbo's version from Dubbox-2.8.4 to  apache-dubbo-2.7.7. Both of them have the same limit.

Here is Apache Dubbo-2.7.7's source.
------------------------------------------------------------
@Override
    public void filter(ClientRequestContext requestContext) throws IOException {
        int size = 0;
        for (Map.Entry<String, Object> entry : RpcContext.getContext().getObjectAttachments().entrySet()) {
            String key = entry.getKey();
            String value = (String) entry.getValue();
            if (illegalHttpHeaderKey(key) || illegalHttpHeaderValue(value)) {
                throw new IllegalArgumentException("The attachments of " + RpcContext.class.getSimpleName() + " must not contain ',' or '=' when using rest protocol");
            }

            // TODO for now we don't consider the differences of encoding and server limit
            if (value != null) {
                size += value.getBytes(StandardCharsets.UTF_8).length;
            }
            if (size > MAX_HEADER_SIZE) {
                throw new IllegalArgumentException("The attachments of " + RpcContext.class.getSimpleName() + " is too big");
            }

            String attachments = key + "=" + value;
            requestContext.getHeaders().add(DUBBO_ATTACHMENT_HEADER, attachments);
        }
    }

**Comment by wu-sheng** [comment]
That commit is only 16 days ago. I doubt whether it is in your release.

**Comment by Lumia001** [comment]
If so, try removing it the next time my upgrade.

Thank your response a lot.
