### ISSUE TITLE
no service in skywalking-ui

### ISSUE THREAD

**Issue by wurenny** [apache/skywalking#3295]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- no Service data found in skywalking ui

___
### Env
- Which version of SkyWalking, OS and JRE?
skywalking + ui : 6.3
elasticsearch: 6.4.2
os: centos 7
jre: 1.8.0_222

- What happen?
following the document: https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md
i set agent.service_name and collector.backend_service in config/agent.config, and run a simple helloworld jar app such as :
java -javaagent:/opt/res/skywalking-agent/skywalking-agent.jar -jar /root/demo/app.jar
i only found "Endpoint" data in skywalking ui, no "Service" data
![image](https://user-images.githubusercontent.com/6622574/63354706-8b88ff00-c397-11e9-8e4f-15810755f587.png)

**Comment by wu-sheng** [comment]
Search the issue before submit duplicated one. Your timezone or time is not right of your ENV.

**Comment by wurenny** [comment]
@wu-sheng i just set the timezone for oap and ui, then restart them, but it not works, i still need to set the timezone at broswer ui page so that i see the Service data:
``` shell
# kubectl -n monitoring exec skywalking-ui-54c666c87d-8gf4j date       
Tue Aug 20 23:39:48 CST 2019
# kubectl -n monitoring exec skywalking-oap-d77fb5d7d-mgcwp date
Tue Aug 20 23:39:59 CST 2019
```
i use elasticsearch for storage, do i need to set the timezone for elasticsearch cluster yet?

thanks.

**Comment by wu-sheng** [comment]
Easy way to confirm, check the metrics data in your ElasticSearch, if it shows wrong( for pod, most likely in UTC0 by default), you don't do that successfully.

**Comment by wurenny** [comment]
@wu-sheng metric data is UTC, and i set all node's timezone in elasticsearch cluster, then delete all indexes, restart oap server(rebuild), but the UI still stays UTC~~
![image](https://user-images.githubusercontent.com/6622574/63366486-6f438d00-c3ac-11e9-9bd3-ba185660cd4e.png)
 
i think it's no matter to es, skywalking should write data to elasticsearch with timezone

**Comment by wu-sheng** [comment]
UTC zone is pure docker story :) Or if you have the customized image, you could set timezone to JVM.

**Comment by wurenny** [comment]
@wu-sheng i rememberd i had to give my answer: 
last week, i verified that it's not work if running skywalking docker image with volume mounting host path /etc/localtime (-v/--volume in docker).
**JVM timezone only works when specifying the TZ env var**

**Comment by wu-sheng** [comment]
@wurenny That is docker or k8s story :) Not SkyWalking's. My own use case is staying in UTC-0, so, I don't know what happens.

**Comment by wurenny** [comment]
@wu-sheng Yes, exactly, it's jvm-timezone's story~
