### ISSUE TITLE
MySQL PreparedStatement execute method been enhanced twice

### ISSUE THREAD

**Issue by honganan** [apache/skywalking#3296]
I may found a bug for MySQL `PreparedStatement.execute()` method enhancement when I am 
imitating MySQL enhancement In class 
`apm-sniffer/apm-sdk-plugin/mysql-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mysql/v5/define/PreparedStatementInstrumentation.java`
The phenomenon is the interceptor of `execute()` method executed twice.

After study I may known how this happend. When trying to enhance a subclass which inherite a method from it's parent class, Bytebuddy will copy this method to this subclass. In case of the parent class enhanced first, then copy it to subclass and the twice enhancement happened.(refer to:https://github.com/raphw/byte-buddy/issues/622)

In our situation the `PreparedStatementInstrumentation` enhanced `execute()` method in 
`com.mysql.jdbc.PreparedStatement` 
and 
`com.mysql.jdbc.JDBC42PreparedStatement`
But `execute()` method in `JDBC42PreparedStatement` is inherited from `PreparedStatement`.

**Comment by wu-sheng** [comment]
See `DeclaredInstanceMethodsInterceptPoint`. Look like `JDBC42PreparedStatement` need this kind of interceptPoint. Would you submit a pull request to fix this?

cc @candyleer

**Comment by honganan** [comment]
Yes，glad to
