### ISSUE TITLE
tomcat webapp startup report exception

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3304]
tomcat webapp startup ,the agent logs display follow exceptions, why?
<img width="766" alt="Snipaste_2019-08-22_14-18-43" src="https://user-images.githubusercontent.com/52440226/63490658-c69a4800-c4e7-11e9-8ab0-f2b1bdab071f.png">

**Comment by kezhenxu94** [comment]
@webb2019 check that you oap server starts up successfully and is reachable from the agent

**Comment by webb2019** [comment]
> @webb2019 check that you oap server starts up successfully and is reachable from the agent

I set log level to debug ,and  find agent can connect OAP, but disconect later quickly. do you know other reasons invoke this issue. thanks .
<img width="909" alt="Snipaste_2019-08-22_16-57-14" src="https://user-images.githubusercontent.com/52440226/63501614-84303580-c4fe-11e9-8999-ad6009e4df24.png">
