### ISSUE TITLE
Provide plugin for Apache Cassandra

### ISSUE THREAD

**Issue by stone-wlg** [apache/skywalking#3305]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

### Requirement or improvement
[Provide plugin for Apache Cassandra](http://cassandra.apache.org/)

**Comment by kezhenxu94** [comment]
We don't have such plugin for now, and contribution is welcome :)

**Comment by stone-wlg** [comment]
I have done it, but i don't know the git flow. :)

**Comment by kezhenxu94** [comment]
Take a look at [how to create a pull request](https://help.github.com/en/articles/creating-a-pull-request#targetText=On%20GitHub%2C%20navigate%20to%20the,menu%2C%20click%20New%20pull%20request.) , that's general steps to contribute, as for plugin contribution, we'll need extra steps, creating auto tests for your plugin, documentations can be found [here](https://github.com/SkyAPMTest/agent-auto-integration-testcases)

**Comment by stone-wlg** [comment]
Should i create a new branch like: feature/cassandra-v3-plugin, and push it, then ask someone to merge it?

**Comment by kezhenxu94** [comment]
> Should i create a new branch like: feature/cassandra-v3-plugin, and push it, then ask someone to merge it?

It's not forcefully that you **should** create a new branch, but I think it's a good practice, so just create a new branch, and refer to [this](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) to create a pull request, then we'll review and merge if everthing is good.

Please remember that before merging you pull request, the auto test is required and you should create an auto test in the test repo: http://github.com/SkyAPMTest/agent-auto-integration-testcases

**Comment by wu-sheng** [comment]
@stone-wlg You need to fork this repo, then you have stone-wlg/skywalking. You could do anything there, then submit pull request to this main repo. As you are not a committer, so fork is the only option.

**Comment by stone-wlg** [comment]
Ok, thanks.

**Comment by kezhenxu94** [comment]
resolved by #3410
