### ISSUE TITLE
OAP Servers logs display errors likes ,who can help me how to resolving?

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3307]
I cant how to do.
<img width="876" alt="Snipaste_2019-08-22_17-20-56" src="https://user-images.githubusercontent.com/52440226/63503237-b000ea80-c501-11e9-8d5d-18b716142f44.png">

**Comment by wu-sheng** [comment]
Your slow SQL is too long, even over 2000 chars. Right now, we didn't process this to limit the length. I think we could do that.

**Comment by wu-sheng** [comment]
Could you try to enhance this? And send a pull request to fix?

**Comment by webb2019** [comment]
> Your slow SQL is too long, even over 2000 chars. Right now, we didn't process this to limit the length. I think we could do that.

thanks.

**Comment by webb2019** [comment]
> Could you try to enhance this? And send a pull request to fix?

Ok, I'll try

**Comment by wu-sheng** [comment]
Check `MultiScopesSpanListener#L164`
> statement.setStatement(tag.getValue());

Add a config item in `TraceServiceModuleConfig`, named `MAX_SLOW_SQL_LENGTH`, and trim the string at above place.

This should be an easy and your first pull request.

**Comment by webb2019** [comment]
hi, I found another column "DATA_BINARY"  limit VARCHAR(20000), can't insert into table segment .
how to resolve this problem best?
<img width="912" alt="Snipaste_2019-08-23_11-36-03" src="https://user-images.githubusercontent.com/52440226/63565222-a4153700-c59a-11e9-9312-3a630b698710.png">

**Comment by wu-sheng** [comment]
@webb2019 Replied you at #3309
