### ISSUE TITLE
OAP "DATA_BINARY"  limit VARCHAR(20000), can't insert into table segment .

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3309]
hi, I found another column "DATA_BINARY"  limit VARCHAR(20000), can't insert into table segment .
how to resolve this problem best?
<img width="912" alt="Snipaste_2019-08-23_11-36-03" src="https://user-images.githubusercontent.com/52440226/63565222-a4153700-c59a-11e9-9312-3a630b698710.png">

_Originally posted by @webb2019 in https://github.com/apache/skywalking/issues/3307#issuecomment-524160361_

**Comment by wu-sheng** [comment]
In `MySQLTableInstaller#getColumnType`, we should change the type to MEDIUMTEXT, when the `scope==DefaultScopeDefine.SEGMENT` and `name==SegmentRecord#DATA_BINARY`.

I think you should be able to fix this :) Send another pull request, please.
