### ISSUE TITLE
OAP  : Unique index or primary key violation: "PRIMARY_KEY_1 ON PUBLIC.ALARM_RECORD(ID) )

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3310]
we have three tomcats deploy on one server instance  , each tomcat had three webapps with agent  .
how to resolve this error.  thanks! 
<img width="911" alt="Snipaste_2019-08-23_13-25-25" src="https://user-images.githubusercontent.com/52440226/63569203-f65e5400-c5aa-11e9-9d5a-ec817c8113d5.png">

**Comment by wu-sheng** [comment]
I am not sure how this happens, the ID should be `time_bucket + scope + id`, which should not conflict in a minute.

**Comment by wu-sheng** [comment]
What happen?
