### ISSUE TITLE
why my skywalking show trace so simple 

### ISSUE THREAD

**Issue by xingzt** [apache/skywalking#3312]
when i use skywalking to trace my services，the UI like this picture ：
![微信图片_20190823184657](https://user-images.githubusercontent.com/48975195/63588312-c4fc7d00-c5d8-11e9-91b3-431a7ee5455f.jpg)

but i want the trace that i can know “checkUserInfo” do what ,like connect mysql.

why my trace depth is so simple? i use it error?

**Comment by kezhenxu94** [comment]
@xingzt the "Mysql/JDBI/PreparedStatement…" represents that your service connects to MySQL, the fact that it's red represents that there's error when executing SQL, you can click it to show the detail, such as error message and the SQL it tries to execute
