### ISSUE TITLE
DEADLOCK occurs while starting application with skywalking agent

### ISSUE THREAD

**Issue by anyuan95** [apache/skywalking#3319]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug ( not sure )
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- JDK: Oracle JDK 1.8.0_191
- OS: CentOS 7.5, in docker containers
- Skywalking: 6.1.0-SNAPSHOT

### Problem scenario: 
I use the following command to start a java application in a docker container (as the main process):
```
java -javaagent:/usr/local/agent/skywalking/skywalking-agent.jar -javaagent:/usr/local/agent/pinpoint/pinpoint-bootstrap-1.6.2.jar -Duser.home=/data/ -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=dev -jar /myApplication.jar
```
For some reason, I had to use skywalking and pinpoint at the same time.
The command above usually runs correctly, but sometimes DEADLOCK occurs in the main java process.
![image](https://user-images.githubusercontent.com/28748124/63649692-5f90c380-c773-11e9-85c3-59f9f18d5f73.png)

And here is the full JSTACK log.
[jstack-74.log](https://github.com/apache/skywalking/files/3538104/jstack-74.log)

I wonder if it was caused by the use of two probes at the same process.
This problem has appeared 5 times in the last 300 deployments.

Look forward to your kind reply.

**Comment by wu-sheng** [comment]
I wouldn't recommend you use two APM agents together. I have no experience in this case. Deadlock is occasionally caused by startup sequence, which is hard to tell.

From your log, it looks like gRPC conflicts.
