### ISSUE TITLE
H2 storeage table lost

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3322]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
after an weekend ，oap server lost all h2 tables  in our serious enviroment .  where is the problem?
<img width="735" alt="Snipaste_2019-08-26_09-57-12" src="https://user-images.githubusercontent.com/52440226/63660762-8ccc8880-c7ea-11e9-8c1a-aaf912ee9d1b.png">
<img width="714" alt="Snipaste_2019-08-26_09-57-26" src="https://user-images.githubusercontent.com/52440226/63660764-8d651f00-c7ea-11e9-8cdb-61069fabbcd3.png">
<img width="742" alt="Snipaste_2019-08-26_09-57-41" src="https://user-images.githubusercontent.com/52440226/63660765-8d651f00-c7ea-11e9-80cb-3baacc48bea7.png">
<img width="697" alt="Snipaste_2019-08-26_09-57-55" src="https://user-images.githubusercontent.com/52440226/63660766-8dfdb580-c7ea-11e9-9a85-9ea90fc12701.png">

**Comment by wu-sheng** [comment]
First of all, H2 is not for long time running, it is for demo only. Also, in default, H2 is running in momery mode. If you are expecting it is running in a more stable way, change H2 to server mode.

**Comment by wu-sheng** [comment]
With OOM or some mechanism/bug inside H2, this may happen. I am not sure. But this is not the usual case.
