### ISSUE TITLE
Got error on startup

### ISSUE THREAD

**Issue by lintghi** [apache/skywalking#3324]
`Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://es-node-1:9200], URI [/skw_alarm_record-20190826?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [skw_alarm_record-20190826] as the final mapping would have more than 1 type: [doc, type]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [skw_alarm_record-20190826] as the final mapping would have more than 1 type: [doc, type]"},"status":400}`

application.yml: 
storage: elasticsearch:  nameSpace: ${SW_NAMESPACE:"skw"}

Skywalking: 6.3.0
Elasticsearch: 6.3.2

**Comment by wu-sheng** [comment]
Do you upgrade from old version?

**Comment by lintghi** [comment]
> Do you upgrade from old version?

no. i install it in a new env.

**Comment by lintghi** [comment]
> Do you upgrade from old version?

i also found this issue on 6.2.0 and 6.1.0

**Comment by wu-sheng** [comment]
I don't think this is the normal case. Have you cleared the ES every time? After you changed version.

**Comment by lintghi** [comment]
I cleared and i try to change other value of storage: elasticsearch: nameSpace, but got the same result.

**Comment by lintghi** [comment]
this issue is disappear when using a fresh ES. but if use an ES inited skywalking indexs, even if delete all that indexs it also error when oapServiceInit.sh

**Comment by wu-sheng** [comment]
I don't have a clue, sorry.
