### ISSUE TITLE
why don't use agentmain？

### ISSUE THREAD

**Issue by spurtAndy** [apache/skywalking#3326]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What is your question? What is agent main?

**Comment by spurtAndy** [comment]
i want hot loading agent. Java SE6 began to provide a way to add agents dynamically after an application's VM was started, known as agentmain

**Comment by wu-sheng** [comment]
No, we are not using that. If you have interests, read the document about the differences. We need to change class structure, so agentmain is not the option.

**Comment by spurtAndy** [comment]
ok，3Q

**Comment by gaoweijie** [comment]
> No, we are not using that. If you have interests, read the document about the differences. We need to change class structure, so agentmain is not the option.
---------------------------------------------------My question ------------------------------------------------
Our department leader hopes to be able to use the hot deployment method very much, so that we can quickly promote this system to the merchants. 
Question1: 
         So is there any way to achieve hot deployment? Such as  modify source code from "premain" to "agentmain"?  Or modify startup mode?  Or modify the configuration file? 
Can you provide relevant documents of hot deployment?

Question2: 
         Do you have any plan to upgrade the version to solve the hot deployment problem？

**Comment by wu-sheng** [comment]
@gaoweijie You are asking questions in the wrong way. In the community, we discuss things from the tech perspective, we have no interest in your internal requirements. Those are not our responsibilities.

**Comment by gaoweijie** [comment]
> @gaoweijie You are asking questions in the wrong way. In the community, we discuss things from the tech perspective, we have no interest in your internal requirements. Those are not our responsibilities.

Yes, you are right.It was my fault to describe the need and background. I just want to learn from you whether it is possible to transform skywalking into a hot deployment system from the tech perspective.

Here's what I've done：
![image](https://user-images.githubusercontent.com/8943447/96693149-75bb0380-13b9-11eb-9f82-88eadd8cb80f.png)

I  have finished the agent jar by maven.
I can really attach the target  pid and jvm information.

![image](https://user-images.githubusercontent.com/8943447/96693550-f5e16900-13b9-11eb-8c04-858f089d6a84.png)
![image](https://user-images.githubusercontent.com/8943447/96693681-1a3d4580-13ba-11eb-8ade-d0fb150c651b.png)

There is no error log, and the web requests are all 200 response codes.

So I'm confused. What's the problem.

**Comment by wu-sheng** [comment]
I think I have replied last time, https://github.com/apache/skywalking/issues/3326#issuecomment-524740175

**Comment by gaoweijie** [comment]
ok thanks~
