### ISSUE TITLE
No span will be created when use HttpAsyncCient plugin

### ISSUE THREAD

**Issue by liyanyan-dev** [apache/skywalking#3327]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
When I use httpAsyncCient for link tracking, I don't create span at all.Because ContextManager.isActive()  is false in SessionRequestConstructorInterceptor.onConstruct ，subsequent program logic cannot execute create span opertation.How to use httpAsyncCient plugin to for link tracking？

My Demo Code：
 public class HttpAsyncClient {
    public static void main(String[] args) throws Exception {
        /**
         * http://hc.apache.org/httpcomponents-asyncclient-dev/examples.html
         */
        CloseableHttpAsyncClient httpclient = HttpAsyncClients.createDefault();
        try {
            httpclient.start();
            HttpGet request = new HttpGet("http://httpbin.org/get");
            Future<HttpResponse> future = httpclient.execute(request, null);
            Thread.sleep(5000);
            System.out.println("after...");
            HttpResponse response = future.get();
            System.out.println("Response: " + response.getStatusLine());
            System.out.println("Shutting down");
        } finally {
        //  httpclient.close();
        }
        System.out.println("Done");
}

### Bug
- Which version of SkyWalking, OS and JRE?
  SkyWalking: v6.2.0

**Comment by liyanyan-dev** [comment]
Add：
SkyWalking: v6.2.0

**Comment by wu-sheng** [comment]
@ascrutae Please take a look.

**Comment by wu-sheng** [comment]
I have taken a look, you are using `#Main`, which could finish before agent registered. So basically, this is not SkyWalking use case. SkyWalking is application performance monitoring, application means a server, not a simple main func.
