### ISSUE TITLE
error,bytes can be at most 32766 in length

### ISSUE THREAD

**Issue by lmzhizhe** [apache/skywalking#3328]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Question or discussion
Bug

___
### Question
- What do you want to know?
I got this error,buy I can not update 6.2.0 to 6.3.0，what can I do？

Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 32769

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.2.0   centos7.4  java8
- Which company or project?
vivo
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
`Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 32769`

`[DEBUG][o.e.a.b.TransportShardBulkAction] [all_p90_month-201908][0] failed to execute bulk item (update) BulkShardRequest [[all_p90_month-201908][0]] containing [update {[all_p90_month-201908][type][201908], doc_as_upsert[false], doc[index {[null][null][null], source[n/a, actual length: [32kb], max length: 2kb]}], scripted_upsert[false], detect_noop[true]}]
java.lang.IllegalArgumentException: Document contains at least one immense term in field="detail_group" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[48, 44, 55, 50, 49, 48, 55, 50, 57, 124, 49, 44, 50, 53, 54, 49, 52, 56, 53, 124, 50, 44, 57, 49, 52, 57, 54, 50, 124, 51]...', original message: bytes can be at most 32766 in length; got 32769`

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by peng-yongsheng** [comment]
@lmzhizhe Bug had been fixed. 

Change the PXX index column type by using elastic api:  [updating-field-mappings](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-put-mapping.html#updating-field-mappings).

**Comment by peng-yongsheng** [comment]
@lmzhizhe The index template also need to change the data type. [Template API](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-templates.html)

**Comment by lmzhizhe** [comment]
> @lmzhizhe The index template also need to change the data type. [Template API](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-templates.html)

They are so many indexs，I can not update one by one,Can I delete all indexs from es and restart skywalking?

**Comment by lmzhizhe** [comment]
> @lmzhizhe The index template also need to change the data type. [Template API](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-templates.html)

Can I delete all index template?  The template will be created again after I deleted all index template?
