### ISSUE TITLE
Not getting any data from oap server for nodejs application

### ISSUE THREAD

**Issue by ukrocks007** [apache/skywalking#3334]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ X ] Question or discussion
- [ X ] Bug
- [ ] Requirement
- [ X ] Feature or performance improvement

___
### Question
- Skywalking UI is not showing any data with node js application.

___
### Bug
- Build docker images with latest code and used docker for running on mac

- OAP server starts and shows the UUID mentioned in the nodejs application.

- UI starts and gets connected with OAP Server.
___
### Requirement or improvement
- Please give a small demo of Skywalking UI with node application...

**Comment by wu-sheng** [comment]
Submit at nodejs project.
