### ISSUE TITLE
The cpu value is different from the actual usage value

### ISSUE THREAD

**Issue by liyongfa0311** [apache/skywalking#3335]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
My java application consumes about 250% cpu. The server is a 4-core 8G.But the cpu in the UI is only about 3%.
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 6.1.0 OS:centOS7.3 JRE 1.8_202
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
the UI 
![image](https://user-images.githubusercontent.com/30169249/63689622-0725f880-c83d-11e9-9777-c885051ca1c1.png)
the ES
![image](https://user-images.githubusercontent.com/30169249/63689699-43f1ef80-c83d-11e9-84be-244ec079b915.png)
the Server
![image](https://user-images.githubusercontent.com/30169249/63689795-84516d80-c83d-11e9-90c3-4ab946b2c714.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Try the latest release.
