### ISSUE TITLE
@lmzhizhe The index template also need to change the data type. [Template API](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-templates.html)

### ISSUE THREAD

**Issue by lmzhizhe** [apache/skywalking#3336]
Can I delete all index template? The template will be created again when I restart the skywalking?

_Originally posted by @peng-yongsheng in https://github.com/apache/skywalking/issues/3328#issuecomment-524769333_

**Comment by wu-sheng** [comment]
Don't open a new issue for an existing one. You could delete all indexes and templates, also reboot the agents.

**Comment by lmzhizhe** [comment]
> Don't open a new issue for an existing one. You could delete all indexes and templates, also reboot the agents.
what will happen  If I only delete all the templates and do not reboot the agents?  I can not reboot all agent。I just can reboot the oap !
