### ISSUE TITLE
vertx plugin bug

### ISSUE THREAD

**Issue by wentjiang** [apache/skywalking#3338]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] plugin
- [X] Bug
- [X] vertx
 
___
### Bug
- Which version of SkyWalking, OS and JRE?
V6.2.0 jdk8

- What happen?
my project use vertx v3.4 ,the agent log show 
java.lang.NullPointerException
	at org.apache.skywalking.apm.plugin.vertx3.HttpServerResponseImplEndInterceptor.beforeMethod(HttpServerResponseImplEndInterceptor.java:39)
I review code and debug, the context is null, so I find there are not use class io.vertx.ext.web.impl.RouterImpl in my project 
finally,I solve it by I create io.vertx.core.http.impl.ServerConnection enhance, it works healthy

**Comment by kezhenxu94** [comment]
Thanks for reporting, @wentjiang since you have already found the solution, will you send a pull request to fix the bug?

**Comment by wu-sheng** [comment]
FYI @BFergerson
