### ISSUE TITLE
How to gracefully close skywalking

### ISSUE THREAD

**Issue by M-make** [apache/skywalking#3342]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to gracefully close skywalking
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by M-make** [comment]
I always jps -l  then kill -9 pid

**Comment by wu-sheng** [comment]
Same here. No special shut down.
