### ISSUE TITLE
Why is the shard of the register_lock index single-sliced

### ISSUE THREAD

**Issue by HackerRookie** [apache/skywalking#3343]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why is the shard of the register_lock index single-sliced.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Es a node down register_lock is not available
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We are using it as an unique seq creator. Not for metadata storage. Distributed lock is bad for performance.

**Comment by HackerRookie** [comment]
The availability of skywalking will be reduced because of this. Is it necessary to solve this problem in 6.4.0 milestone?

Whether the es consistency feature can be satisfied。
Zk or redis to implement distributed lock instead

**Comment by HackerRookie** [comment]
> We are using it as an unique seq creator. Not for metadata storage. Distributed lock is bad for performance.

@wu-sheng The availability of skywalking will be reduced because of this. Is it necessary to solve this problem in 6.4.0 milestone?

Whether the es consistency feature can be satisfied。
Zk or redis to implement distributed lock instead

**Comment by wu-sheng** [comment]
No plan to do this, yet. Zk is low performance too.

**Comment by wu-sheng** [comment]
You could do anything you want. We haven't plan to do that. Adding another component is not good for end user. It is not that necessary.

**Comment by HackerRookie** [comment]
> You could do anything you want. We haven't plan to do that. Adding another component is not good for end user. It is not that necessary.

tks
