### ISSUE TITLE
 Can I create only one index when I select storage medium as elasticsearch?

### ISSUE THREAD

**Issue by M-make** [apache/skywalking#3344]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

When I use es as a storage medium, it builds a lot of indexs.
 Can I create only one index when I select storage medium as elasticsearch?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No, you can't. There are many types of metrics there.
