### ISSUE TITLE
Have two prefixes when Skywalking oap delete expired data

### ISSUE THREAD

**Issue by liyanyan-dev** [apache/skywalking#3347]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [√ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Why do I get two prefixes when Skywalking oap delete expired data?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  SkyWalking v6.2.0

- Which company or project?
- What happen?
  **Skywalking oap log error:**
 ![log](https://user-images.githubusercontent.com/54348450/63756673-5591d080-c8eb-11e9-8007-9f771dafda40.png)

  **config/application.yml:**
   
  ![config](https://user-images.githubusercontent.com/54348450/63756890-bb7e5800-c8eb-11e9-9245-482919b891d0.png)
 
  **index in es:**
   
![image](https://user-images.githubusercontent.com/54348450/63757060-0c8e4c00-c8ec-11e9-93db-363948296aba.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Fixed in 6.3.0
