### ISSUE TITLE
Final method [final java.util.List org.springframework.data.jpa.repository.support.SimpleJpaRepository.saveAll$original$sxMMY1Oe$accessor$R7skPnjw(java.lang.Iterable)] cannot get proxied via CGLIB: Calls to this method will NOT be routed to the target instance and might lead to NPEs against uninitialized fields in the proxy instance.

### ISSUE THREAD

**Issue by chenwr** [apache/skywalking#3348]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

   always print such logs when using cglib proxy and apm-spring-annotation-plugin-6.1.0.jar plugin (optional-plugin), can reproduce when target class source code is annotated with  Service/Repository/Component . so consider shall we find a way to fix it .

  during debug found the instrumented classes by bytebuddy generate two additional methods  such as follows beside the original one (findAll) in source code .since the cglib cannot proxy the final method , then print the log  .
private java.lang.Iterable com.xxx.PrismService.findAll$original$svMDajua() .  
final java.lang.Iterable com.xxx.PrismService.findAll$original$svMDajua$accessor$BgilbiaM()

  refer to : org.springframework.aop.framework.CglibAopProxy#doValidateClass

![image](https://user-images.githubusercontent.com/9836134/63756230-93422980-c8ea-11e9-93e3-25ae3045c8ed.png)

**Comment by wu-sheng** [comment]
@candyleer please take a look.

@chenwr do you recheck latest release? 6.3.0 or master.

**Comment by chenwr** [comment]
I tried with v6.3.0 and latest master (v6.4.0-SNAPSHOT) ,the issue still exists . the root cause should be the way we are using bytebuddy that generate the final method . if can find another way without final method generated should resolve .
![image](https://user-images.githubusercontent.com/9836134/63829724-deb51000-c99c-11e9-8891-cdd83ff7fe75.png)

**Comment by wu-sheng** [comment]
@chenwr This is the root cause, but your suggestion is not the solution. The right one is adding a fix plugin to Spring core, ignore the generated method.

**Comment by candyleer** [comment]
this issue always exists in spring because `bytebuddy` will generate `final` method, It will not affect the running of the program.

**Comment by candyleer** [comment]
@chenwr  does this will produce any side effect?

**Comment by wu-sheng** [comment]
@candyleer @chenwr 

If it doesn't stop the codes, I would say this is nothing serious to be worried.

**Comment by chenwr** [comment]
@wu-sheng @candyleer  I tried (including the case when the method is also annotated with Transactional ),didn't find side effect . mainly because when introducing into tracing system, biz application developers has concerns about the unstable factor . if consider it is not big issue then close is ok .
