### ISSUE TITLE
 globalTaskExecutor-34 InstMethodsInter :  class[class com.mongodb.MongoClient] before method[execute] intercept failure java.lang.NullPointerException

### ISSUE THREAD

**Issue by encodingl** [apache/skywalking#3349]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.3  os centos 7 jre 1.8  mongodb 4.0

- What happen?
skywalking agent report error as follows:
```
ERROR 2019-08-27 10:09:50:829 globalTaskExecutor-17 InstMethodsInter :  class[class com.mongodb.MongoClient] before method[execute] intercept failure
java.lang.NullPointerException
```

**Comment by wu-sheng** [comment]
Please check supported list.
