### ISSUE TITLE
Es Validation Failed，id is too long

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#3351]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can you add an advance judgment on id, otherwise the insert will keep retrying to report the error.
Besides, is it possible to improve the error information? I am not sure where the id is too long
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The right one to avoid this, is to set length limit at operation name at agent side. Otherwise, it is too complex. Are you interested in contributing this?

**Comment by stalary** [comment]
I encountered this problem because base64 was passed in the request, and I haven't found out which plugin caused it, and I've been trying to fix it recently

**Comment by wu-sheng** [comment]
We don't need to find this out. Because this is mostly because of length of endpoint/operationName. We could change core APIs(ContextManager#createXXXSpan), make sure the operation name is not too long.

Do you get my point?

**Comment by stalary** [comment]
ok, I’ve got it, I will resolve it.

**Comment by wu-sheng** [comment]
Looking forward you are the 150th contributor of our main repo.

**Comment by wu-sheng** [comment]
Fixed by #3357
