### ISSUE TITLE
How to get the traceId in logback's LogstashTcpSocketAppender

### ISSUE THREAD

**Issue by hanlubiao** [apache/skywalking#3352]
### Question
how can I get the traceId in logback's LogstashTcpSocketAppender please

**Comment by wu-sheng** [comment]
There are a lot of appenders there. We have given your the typical examples, you should be able to do a new one, and contribute to the community.

**Comment by wu-sheng** [comment]
Added.

**Comment by hanlubiao** [comment]
thank you!
