### ISSUE TITLE
The link is incomplete

### ISSUE THREAD

**Issue by xiangyanggong** [apache/skywalking#3354]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
In my project , I fount some link is incomplete, so I want to be sure whether it will lead to this when creating new thread in one process. 
![图片](https://user-images.githubusercontent.com/53589709/63817901-055d5180-c971-11e9-9fc7-8d9dbfe7c981.png)
I test it. case1 is ok, but case2 lead to the link incomplete.
If my understanding or usage about SW is right. It means that I must develop plugins for every micro service about cross thread. I think it's too complex. or am I wrong?

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Check the appplication toolkit, there is an annotation(in a toolkit lib) for this. You don't need to develop plugin.

**Comment by xiangyanggong** [comment]
ok,thans!
