### ISSUE TITLE
How about the ability of skywalking UI to isolate the namespace data set by several different projects?

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3356]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
What is the purpose of the agent.namespace parameter in the agent.config file?Can multiple different projects, with different namespace, be filtered by UI?However, no filter condition on namespace is found on the UI

**Comment by wu-sheng** [comment]
namespace is designed for isolation two SkyWalking environment. You are talking about tenancy, do don't have that today.
