### ISSUE TITLE
Many agents have been deployed. How to upgrade agent?

### ISSUE THREAD

**Issue by spurtAndy** [apache/skywalking#3360]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Many agents have been deployed. How to upgrade agent?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No such mechanism. Protocol is compatible in all 6.x versions, you could update when you need reboot the applications.
