### ISSUE TITLE
 package skywalking-ui error

### ISSUE THREAD

**Issue by xiaoy00** [apache/skywalking#3361]
I also cant package skywalking-ui,  same error as @antoni-g . 
then i uninstall npm and nodejs on my windows. 
it have a differrent error. 

`[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm install) on project apm-webapp: Failed to run task: 'npm install --registry=https://registry.npmjs.org/' failed. `

this is the debug.log 

`12748 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...qFGFLKaXNmJJmAWy\nEBk'
12748 verbose stack     at JSON.parse (<anonymous>)
12748 verbose stack     at parseJson (D:\JavaWork\apache-skywalking-apm-6.3.0\skywalking-ui\node\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-better-errors\index.js:7:17)
12748 verbose stack     at consumeBody.call.then.buffer (D:\JavaWork\apache-skywalking-apm-6.3.0\skywalking-ui\node\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
12748 verbose stack     at <anonymous>
12748 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
12749 verbose cwd D:\JavaWork\apache-skywalking-apm-6.3.0\skywalking-ui
12750 verbose Windows_NT 10.0.15063
12751 verbose argv "D:\\JavaWork\\apache-skywalking-apm-6.3.0\\skywalking-ui\\node\\node.exe" "D:\\JavaWork\\apache-skywalking-apm-6.3.0\\skywalking-ui\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "--registry=https://registry.npmjs.org/"
12752 verbose node v8.9.4
12753 verbose npm  v5.6.0
12754 error Unexpected end of JSON input while parsing near '...qFGFLKaXNmJJmAWy\nEBk'
12755 verbose exit [ 1, true ]`

_Originally posted by @xiaoy00 in https://github.com/apache/skywalking/issues/2847#issuecomment-525592383_

**Comment by wu-sheng** [comment]
Your network issue. Nothing more. Package has been rechecked every commit merging.
