### ISSUE TITLE
Failed during checkstyle configuration

### ISSUE THREAD

**Issue by wuxingye** [apache/skywalking#3363]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
every time i wanna compile apm-sniffer module, error below:

cannot initialize module TreeWalker - cannot initialize module ImportControl - illegal value 'apm-checkstyle/importControl.xml' for property 'file': com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: apm-checkstyle/importControl.xml

how to compile one module, but whole? thx
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by stalary** [comment]
Did you compile according to the compilation guide

**Comment by wu-sheng** [comment]
That is maven thing. Not skywalking thing.

**Comment by kezhenxu94** [comment]
@wuxingye if you want to compile a single module of SkyWalking project, please follow the [documentation](https://github.com/apache/skywalking/blob/master/docs/en/guides/How-to-build.md#advanced-compile), double check the documentation next time before submitting an issue :)

**Comment by wuxingye** [comment]
> @wuxingye if you want to compile a single module of SkyWalking project, please follow the [documentation](https://github.com/apache/skywalking/blob/master/docs/en/guides/How-to-build.md#advanced-compile), double check the documentation next time before submitting an issue :)

it works, thx
