### ISSUE TITLE
elasticsearch.client.ResponseException: too many requests

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3364]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
 Skywalking is not long in learning to use it.Find the following problems, how to solve?

<img width="919" alt="Snipaste_2019-08-28_18-14-30" src="https://user-images.githubusercontent.com/52440226/63847315-200ae700-c9c0-11e9-8bbc-45208a4079c7.png">

**Comment by wu-sheng** [comment]
Read FAQ or storage setup document. It is there already.
