### ISSUE TITLE
if one backend_service the  agent may be  never reconnect

### ISSUE THREAD

**Issue by xiongrl** [apache/skywalking#3366]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

 ```java
org.apache.skywalking.apm.agent.core.remote.GRPCChannelManager
   @Override
    public void run() {
        logger.debug("Selected collector grpc service running, reconnect:{}.", reconnect);
        if (reconnect) {
            if (grpcServers.size() > 0) {
                String server = "";
                try {
                    int index = Math.abs(random.nextInt()) % grpcServers.size();
                    if (index != selectedIdx) {
                        selectedIdx = index;
 ```
only one   grpcServer  so grpcServers.size()  = 1
First reconnection  set  selectedIdx   = 1   if connection fail ;
The second reconnection  if  1 !=1  (code if (index != selectedIdx))  never to reconnection

**Comment by kezhenxu94** [comment]
The bug should be fixed in 6.3.0, #3181 and #3240 , please try the master branch @xiongrl

**Comment by kezhenxu94** [comment]
@xiongrl #3181 is included in version 6.3.0, while #3240 is not and will be included in next version

**Comment by xiongrl** [comment]
thx

**Comment by kanouken** [comment]
version   7.0.0 +    can  reproduce this issue again  。。。
