### ISSUE TITLE
How to setup istio to send metrics to skywalking

### ISSUE THREAD

**Issue by ceastman-ibm** [apache/skywalking#3374]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to setup istio to send metrics to skywalking? I found this link but there is no information here: https://github.com/apache/skywalking/blob/master/docs/en/setup/istio/README.md this links to https://github.com/apache/skywalking-kubernetes#setup-istio-to-send-metrics-to-oap which also has no information.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Yes. I just bring it by through #3376.
