### ISSUE TITLE
ServiceAndEndpointRegisterClient execute fail

### ISSUE THREAD

**Issue by kanon123** [apache/skywalking#3378]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√]Bug
___
### Bug
- Which version of SkyWalking, OS and JRE?
 SkyWalking 6.3
 Java(TM) SE Runtime Environment (build 1.8.0_152-b16)

- What happen?
skywalking-api.log error message.

![image](https://user-images.githubusercontent.com/19640723/64008017-d77e3580-cb47-11e9-9a87-e133df339db3.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The log shows clear, timeout. The server side has no response in 10s.
