### ISSUE TITLE
witnessClasses can support not including the specified class?

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#3379]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
I want to start the plugin when one class exists but no other class exists

**Comment by wu-sheng** [comment]
No such thing. Read how classloader works you will know why.
