### ISSUE TITLE
on the trace UI, shoud add a way for which user can copy the trace_id

### ISSUE THREAD

**Issue by qxo** [apache/skywalking#3386]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
on the trace UI, shoud add a way for which user can copy the trace_id
such as: 
1. double click trace_id select  for copy to clipboard
ref: https://github.com/apache/skywalking-rocketbot-ui/blob/master/src/views/components/trace/trace-detail.vue

2. add trace_on spanInfo page:
https://github.com/apache/skywalking-rocketbot-ui/blob/master/src/views/components/trace/trace-detail-chart-table.vue

With the trace_id, we can do further analysis on the backend database

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Contribution is welcome.

**Comment by x22x22** [comment]
ok, I  waill finish.

**Comment by x22x22** [comment]
I saw this feature and implemented it.

![image](https://user-images.githubusercontent.com/3389949/64221205-977bd180-cefe-11e9-8428-f9056cfd2e72.png)

**Comment by wu-sheng** [comment]
I think this has been provided, AFAIK. Because the demo page has included this already.
