### ISSUE TITLE
Can the page of  "Span Info" be expanded manually?

### ISSUE THREAD

**Issue by zhaoxunyong** [apache/skywalking#3396]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

I wanna check for the exceptions of the "Span Info",  I can't see the full information  because the page so small, is it possible to expand manually?

![Snip20190903_1](https://user-images.githubusercontent.com/8733266/64143121-49ed5f00-ce41-11e9-8f1f-8fd6fff0b6e0.png)

**Comment by wu-sheng** [comment]
This is good improvement. Contributions are welcome.

**Comment by x22x22** [comment]
Can you describe the requirements in detail?If you can, please take a screenshot, thank you!

**Comment by x22x22** [comment]
ok, I will finish.

**Comment by x22x22** [comment]
I think manual extension is not convenient. It is better to add a button to pop up a dialog box large enough. What do you think?
@zhaoxunyong

**Comment by x22x22** [comment]
> I think manual extension is not convenient. It is better to add a button to pop up a dialog box large enough. What do you think?
> @zhaoxunyong

or  Or add a button that automatically changes the box to the size of the content and retracts to its original size.

**Comment by zhaoxunyong** [comment]
@x22x22 I remembered the previous version has a right arrow on the top right corner, I can expand it manually.

> I think manual extension is not convenient. It is better to add a button to pop up a dialog box large enough. What do you think?
> @zhaoxunyong



> I think manual extension is not convenient. It is better to add a button to pop up a dialog box large enough. What do you think?
> @zhaoxunyong

I remembered the previous version has a right arrow on the top right corner, I can expand it manually.

**Comment by zhaoxunyong** [comment]
I remembered the previous version has a right arrow on the top right corner, I can expand it manually.

**Comment by zhaoxunyong** [comment]
> > I think manual extension is not convenient. It is better to add a button to pop up a dialog box large enough. What do you think?
> > @zhaoxunyong
> 
> Or add a button that automatically changes the box to the size of the content and retracts to its original size.

It's good idea~

**Comment by x22x22** [comment]
@zhaoxunyong see https://github.com/apache/skywalking-rocketbot-ui/pull/152

**Comment by zhaoxunyong** [comment]
> @zhaoxunyong see [apache/skywalking-rocketbot-ui#152](https://github.com/apache/skywalking-rocketbot-ui/pull/152)

Great, you're so efficient!

**Comment by wu-sheng** [comment]
I just tag this as the last feature PR in 6.4.0, if this could get approve by @TinyAllen
