### ISSUE TITLE
Custom exceptions

### ISSUE THREAD

**Issue by muyun12** [apache/skywalking#3400]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
as below:
![image](https://user-images.githubusercontent.com/14314544/64156192-e37b3780-ce66-11e9-930a-f622e567720e.png)

Use custom exceptions for business process control in projects.

How to ignore or exclude this part of the request when calculating the **SLA**, or handle it as successful when reporting.

**Comment by wu-sheng** [comment]
Today, we don't have a consistent mechanism to deal with this. You could only do that by changing plugin source codes. For me, using Exception to propagate error is easy but not good practice.

**Comment by muyun12** [comment]
Thanks!

**Comment by muyun12** [comment]
> Today, we don't have a consistent mechanism to deal with this. You could only do that by changing plugin source codes. For me, using Exception to propagate error is easy but not good practice.

Thanks!
