### ISSUE TITLE
docker hub文档上单词拼写错误

### ISSUE THREAD

**Issue by WildWolfBang** [apache/skywalking#3401]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
standlone --> standalone
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
https://hub.docker.com/r/apache/skywalking-oap-server  
webpage has wrong word name "standlone"
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by hanahmily** [comment]
done.
