### ISSUE TITLE
why is realized in the collector doServiceAndNetworkAddressMappingRegister, and angent implementations have not call it?

### ISSUE THREAD

**Issue by xsisno1** [apache/skywalking#3403]
Why is realized in the collector doServiceAndNetworkAddressMappingRegister, and angent implementations have not call it?

**Comment by wu-sheng** [comment]
But agent doesn't need to.

**Comment by xsisno1** [comment]
Now we have a problem here, that is, multiple dubbo services are connected to agent. One dubbo service relies on other dubbo services. When tracking the link, it is found that collector cannot connect multiple dubbo services connected to agent.

**Comment by xsisno1** [comment]
> But agent doesn't need to.
Now we have a problem here, that is, multiple dubbo services are connected to agent. One dubbo service relies on other dubbo services. When tracking the link, it is found that collector cannot connect multiple dubbo services connected to agent.

**Comment by wu-sheng** [comment]
I am not following your meaning. This API is even not designed for java agent side.

**Comment by xsisno1** [comment]
> I am not following your meaning. This API is even not designed for java agent side.
我们现在碰到一个问题，我们接入了二个dubbo服务，其中一个dubbo服务中调用了另一个dubbo服务，我们在skywalking-ui中看到这两个dubbo服务都注册到collector中了，但在拓扑图上看到两个dubbo服务并没有产生调用关系，而在调用链中产生了新的结点。这样就无法真正做到全链路监控了。

**Comment by wu-sheng** [comment]
@xsisno1 If you are keeping talking in Chinese, I will stop to reply. It is on Apache repo and issue, we should use English.

**Comment by xsisno1** [comment]
> @xsisno1 If you are keeping talking in Chinese, I will stop to reply. It is on Apache repo and issue, we should use English.

We now have a problem with two dubbo services, one of which calls the other dubbo service, and we see in skywalking-ui that both dubbo services are registered with collectors, but on the topology diagram we see that the two dubbo services do not generate a calling relationship, and new nodes are created in the call chain. So you can't really do full link monitoring.

**Comment by wu-sheng** [comment]
I don't remember we change Dubbo plugin, you should verify, whether there is header propagate across dubbo rpc? You could use remote debug to find out.

**Comment by xsisno1** [comment]
> I don't remember we change Dubbo plugin, you should verify, whether there is header propagate across dubbo rpc? You could use remote debug to find out.

The problem has been solved. It is our configuration problem. Thank you for your help
