### ISSUE TITLE
The methods in the static class can't intercept

### ISSUE THREAD

**Issue by liyanyan-dev** [apache/skywalking#3404]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I wrote a plugin to intercept some of the methods in our custom protocol to achieve link tracking; I found that static methods and constructors, ordinary methods  in non-static classes can be intercepted correctly, but methods in static classes can not intercept, and The enhanced log of the static class is also not found in the agant's debug log. Is it not supported for static class enhancements?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywakling v6.2.0 jdk8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Static method is supported We have enhanced already in the existing plugin. You could search the codes easily. As it is your private class, you have to find out why by yourself.
