### ISSUE TITLE
oapService heap OOM

### ISSUE THREAD

**Issue by jadezhong** [apache/skywalking#3405]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
oapService heap oom, 11800 port crash.
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 6.3.0
CentOS 7.x, JDK 1.8, 8C CPU, 16G RAM

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Recently oapServcie heap OOM and 11800 crash after running about 1 day, to investigate it, we open jmx on oapService and monitor it using jConsole. this morning the issue happened again, and in jConsole we saw heap size expenential growth in heap chart, and saw lots of grpc-default-executor-* in thread chart.
PS. during that period, ElasticSearch is in heavy loaded, some ElasticSearch related timeout in log.
We set "-Xms6144m -Xmx6144m" in oapService.sh, use ElasticSearch and ZooKeeper.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by jadezhong** [comment]
![堆内存](https://user-images.githubusercontent.com/49858897/64223290-f09b3380-cf05-11e9-9830-7a353daea040.PNG)

**Comment by jadezhong** [comment]
![线程](https://user-images.githubusercontent.com/49858897/64223302-fa249b80-cf05-11e9-9438-f7a4534139b1.PNG)

**Comment by wu-sheng** [comment]
Read master, `gRPCThreadPoolSize` and `gRPCThreadPoolQueueSize` configs are provided today.

**Comment by jadezhong** [comment]
cloud you please do a hotfix on 6.3.0, just compared master and 6.3.0, too many changes made, hard to fix the issue

**Comment by jadezhong** [comment]
@wu-sheng

**Comment by jadezhong** [comment]
@wu-sheng cloud you please do a hotfix on 6.3.0, just compared master and 6.3.0, too many changes made, hard to fix the issue

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/64235253-85178d00-cf2a-11e9-8e63-76a387c5c458.png)

**Comment by jadezhong** [comment]
@wu-sheng check out the snapshot above, only sync code from master for these source file is required? any other source files need to modify?

**Comment by wu-sheng** [comment]
@jadezhong We have no hotfix release plan today. 6.4.0 is under testing, should release in two weeks.
