### ISSUE TITLE
How do I dynamically add plug-ins to the agent？

### ISSUE THREAD

**Issue by spurtAndy** [apache/skywalking#3407]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
How do I dynamically add plug-ins to the agent？

.

**Comment by wu-sheng** [comment]
We don't support that. It is very dangerous in production env, highly recommend don't use in this way.

**Comment by spurtAndy** [comment]
ok，thanks
