### ISSUE TITLE
why I update skywalking 6.1 to 6.3 , the call link of some services could not be collected

### ISSUE THREAD

**Issue by liyongfa0311** [apache/skywalking#3412]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
I found that after I upgraded the collector to 6.3, the call link of some services could not be collected.This is true for agents with 6.1 and 6.3 versions of the service. No abnormal log. 
Only see tracking with Eureka, no tracking between services calls
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dmsolr** [comment]
Has the agent been upgraded? Because the protocol upgrades at 6.2.

**Comment by liyongfa0311** [comment]
the agent had updated

**Comment by liyongfa0311** [comment]
![Uploading image.png…]() why?

**Comment by liyongfa0311** [comment]
![image](https://user-images.githubusercontent.com/30169249/64252773-60cda780-cf4e-11e9-8622-6dfe7516250c.png)  why?

**Comment by dmsolr** [comment]
#3408

**Comment by wu-sheng** [comment]
I don't think this related to that PR. That PR is for being compatible more versions only. Do you erase the es and then update and reboot agents after that?

**Comment by liyongfa0311** [comment]
Yes,I erase the es and then update collector ,but I don't stop the service, I  update the agent and restart service after the above process

**Comment by wu-sheng** [comment]
I recommend you to use a real new env to test first. There is not related issue says 6.3.0 is not working like you said. I can't verify what happens in your uograde process.
