### ISSUE TITLE
Unbalanced  Data

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3420]
May I ask what is the reason?
![image](https://user-images.githubusercontent.com/11767168/64329638-2ae9fb00-d002-11e9-8f68-349f2ef06d6d.png)
Version 6.3.0

**Comment by wu-sheng** [comment]
This means, you have a plugin not working well. Hard to tell which one.

**Comment by wu-sheng** [comment]
You need to check your typical trace in a test env first, make sure the trace is working as expected. And find out which span(plugin) is the first breaks.
