### ISSUE TITLE
i can't see trace list on trace ui,what's promble ?

### ISSUE THREAD

**Issue by monkeyAlwaysWin** [apache/skywalking#3421]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ 1] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
es 6.5.4 cluster 500ssd 8g memory 4cpu
skywalking 6.3.0 oapserver 4g,webserver 2g

![image](https://user-images.githubusercontent.com/13635500/64333632-8bc90180-d009-11e9-8761-2f064c929232.png)

**Comment by wu-sheng** [comment]
Maybe some data breaks, such ref segment is missing. We have a fix in master branch, provided in 6.4.0.
