### ISSUE TITLE
Istio Metric data now showing on Skywalking dashboard on EKS cluster.

### ISSUE THREAD

**Issue by nandhyala** [apache/skywalking#3422]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by nandhyala** [comment]
After installed Skywalking on EKS Kubi am not seeing data on Skywaking dashboad

**Comment by wu-sheng** [comment]
Do you set the mixer adopter or open als?

**Comment by nandhyala** [comment]
I have followed this document https://github.com/apache/skywalking-kubernetes/tree/master/archive to install Skywalker on EKS.

**Comment by nandhyala** [comment]
I have installed below yaml file tto push metrics into Skywalking.

skywalking-kubernetes/archive/6/6.0.0-beta/istio.

01-metrictemplate.yml
02-skywalingadapter.yml
03-operator_cfg.yml

**Comment by nandhyala** [comment]
@wu-sheng ,

Is there any other steps to set mixer adopter ? Can you please help me on this issue.

**Comment by nandhyala** [comment]
@wu-sheng ,

As part of istio setup we have installed Prometheus for istio on eks.

**Comment by wu-sheng** [comment]
Do you run this? https://github.com/apache/skywalking-kubernetes/tree/master/archive#setup-istio-to-send-metric-to-oap-1 

Istio mixer adopter should be config. And you could check istio mixer log.

**Comment by nandhyala** [comment]
Thanks for replying @wu-sheng ,Yes i have performed below url all steps on EKS/Istio but still i dont see istio metrics on Skywalking dash board.

**Comment by nandhyala** [comment]
followed url steps : https://github.com/apache/skywalking-kubernetes/tree/master/archive#setup-istio-to-send-metric-to-oap-1

**Comment by wu-sheng** [comment]
If you are familiar with istio, you need to learn about istio mixer, check the istio mixer logs, at least, you make sure mixer bypass adopter is working.

**Comment by nandhyala** [comment]
I found the issue and now able to see data on skywalking.
issue is not able to communicate on 11800 port for oap service.

**Comment by nandhyala** [comment]
Thanks @wu-sheng

**Comment by Devavrt1234** [comment]
HI I wanted to setup skywalking on eks cluster can anyone provide latest docs on this
