### ISSUE TITLE
Could we add more metric tags for separating them by service, endpoint or instance?

### ISSUE THREAD

**Issue by stone-wlg** [apache/skywalking#3423]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Right now, metrics as blow:
metrics_aggregation{sw_backend_instance="standalone",metricName="all_heatmap",level="2",dimensionality="month",} 3.0
metrics_aggregation{sw_backend_instance="standalone",metricName="service_instance_cpm",level="1",dimensionality="min",} 7.0
metrics_aggregation{sw_backend_instance="standalone",metricName="database_access_p99",level="2",dimensionality="hour",} 12.0
metrics_aggregation{sw_backend_instance="standalone",metricName="endpoint_sla",level="1",dimensionality="min",} 7.0
metrics_aggregation{sw_backend_instance="standalone",metricName="service_resp_time",level="2",dimensionality="hour",} 3.0

- Could we add more metric tags for separating them by service, endpoint or instance? ex:
metrics_aggregation{sw_backend_instance="standalone",metricName="service_instance_cpm",level="1",dimensionality="min",service="book-svc",} 7.0

**Comment by wu-sheng** [comment]
Why do you want this? Self telemetry is about checking the health and payload, rather than exporting. There is an exporter module, if you want, implement that to Prometheus.

**Comment by wu-sheng** [comment]
If you want, we could discuss about the contribution plan for that exporter, but don't use telemetry for this.
