### ISSUE TITLE
When will sw team release 6.4.0？

### ISSUE THREAD

**Issue by gzshilu** [apache/skywalking#3425]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
1 When sw team plans to release 6.4.0？We are looking forward to the new features of version 6.4.0.
2 I want to know more about background authentication document. When will sw team improve 'backend-token-auth.md' ?

Thanks!

**Comment by wu-sheng** [comment]
Mail list: dev@skywalking.apache.org. Mail to dev-subscribe@skywalking.apache.org, follow the reply to subscribe the mail list.

Go to there, release process only happens there.

> 2 I want to know more about background authentication document. When will sw team improve 'backend-token-auth.md' ?

No such thing today. If you want, we could accept contribution by copying codes from 5.x.
