### ISSUE TITLE
how transmit traeid when customize filter in springcloud gateway?

### ISSUE THREAD

**Issue by csullh** [apache/skywalking#3427]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
### Question
- What do you want to know?
   when I customize filter in springcloud gateway 2.1.4,in the filter ,I modify the request header,add some paramters, the tracieid can not transmit.
   if I do not modify the request header,the tracieid can  transmit.
   how can I resolve it?

**Comment by wu-sheng** [comment]
Please check the header, there is a key named `sw6` in it. If you filter works in sync mode, that is the only thing you should do. You mentioned about modify header, so, somehow, skywalking header is not injected or overrided by your OP. 

@zhaoyuguang could you follow up? I wouldn't wait this for 6.4.0, so tagged as 6.5.0

**Comment by wu-sheng** [comment]
Discuss should be in #3411
