### ISSUE TITLE
Not able to see new created service(istio) details on skywalking dashboard.

### ISSUE THREAD

**Issue by nandhyala** [apache/skywalking#3430]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by nandhyala** [comment]
I see old istio EKS services on dashboard only not able to see new created services on Skywalking dashboard.

**Comment by wu-sheng** [comment]
Why submit the same issue? SkyWalking doesn't monitor service create. You need to change mixer.

**Comment by nandhyala** [comment]
@wu-sheng ,This is total new issue,I am able to see data on skywaalking dashboard after fixing the port issue ,But i see only old service data metrics on skywalking not for new created services data metrics on skywalking dashboard.

**Comment by wu-sheng** [comment]
Give more traffic to new service. That is what you should do.

**Comment by nandhyala** [comment]
yes i pushed  lot of traffic on new created services ..I am using sample bookinfo workshop demo application testing.

**Comment by wu-sheng** [comment]
We are using the same thing too. You may need to check oap debug logs. First check whether receive mixer report of your new service.

Mixer solution is pretty simple one.

**Comment by nandhyala** [comment]
sure @wu-sheng I will check and update you if i find any thing.

**Comment by nandhyala** [comment]
I see new service entires on oap pods logs.

kubectl logs oap-deployment-55d555847c-rt8sb -n skywalking |grep -i productpage

destServiceInstance: "kubernetes://productpage-v1-5bc744779-k5vt7.default"
endpoint: "http/GET//productpage"
      string_value: "productpage-v1"
      string_value: "/productpage"
      string_value: "kubernetes://productpage-v1-5bc744779-k5vt7.default"

**Comment by nandhyala** [comment]
I see below exception on mixer logs . @wu-sheng  do you have any idea on below exception.

kubectl logs -n istio-system -l istio-mixer-type=telemetry -c mixer | grep "newlog" | grep -v '"destination":"telemetry"' | grep -v '"destination":"pilot"' | grep -v '"destination":"policy"' | grep -v '"destination":"unknown"'

	* action='newlogstdio.rule.istio-system[0]': Handler not found: handler='newhandler.stdio'
	* rule=newlogstdio.rule.istio-system: No valid actions found in rule
	* action='newlogstdio.rule.istio-system[0]': Handler not found: handler='newhandler.stdio'
	* rule=newlogstdio.rule.istio-system: No valid actions found in rule
	* action='newlogstdio.rule.istio-system[0]': Handler not found: handler='newhandler.stdio'
	* rule=newlogstdio.rule.istio-system: No valid actions found in rule
	* action='newlogstdio.rule.istio-system[0]': Handler not found: handler='newhandler.stdio'
	* rule=newlogstdio.rule.istio-system: No valid actions found in rule

and

019-09-06T18:11:25.897537Z	error	error creating instance: destination='metric.template.istio-system:sw.handler.istio-system(swadapter.adapter.istio-system)', error='fieldEncoder: dimensions - fieldEncoder: value - lookup failed: 'request.time''
2019-09-06T18:11:25.897661Z	error	api	Report failed: 1 error occurred:
	* fieldEncoder: dimensions - fieldEncoder: value - lookup failed: 'request.time'


gc 6531 @761402.694s 0%: 0.009+4.2+0.018 ms clock, 0.057+0.54/5.7/15+0.11 ms cpu, 19->19->10 MB, 20 MB goal, 6 P
2019-09-06T18:11:35.896534Z	error	error creating instance: destination='metric.template.istio-system:sw.handler.istio-system(swadapter.adapter.istio-system)', error='fieldEncoder: dimensions - fieldEncoder: value - lookup failed: 'request.time''
2019-09-06T18:11:35.896622Z	error	api	Report failed: 1 error occurred:
	* fieldEncoder: dimensions - fieldEncoder: value - lookup failed: 'request.time'

**Comment by wu-sheng** [comment]
Which version of istio are you using? Look like it is an old version, which is not supporting timestamp. We have pushed this long time ago.

**Comment by nandhyala** [comment]
We are using Istio 1.2.3 version.

**Comment by wu-sheng** [comment]
Strange. This looks like something is not working on Istio mixer side. 

> 2019-09-06T18:11:35.896534Z	error	error creating instance: destination='metric.template.istio-system:sw.handler.istio-system(swadapter.adapter.istio-system)', error='fieldEncoder: dimensions - fieldEncoder: value - lookup failed: 'request.time''
2019-09-06T18:11:35.896622Z	error	api	Report failed: 1 error occurred:
* fieldEncoder: dimensions - fieldEncoder: value - lookup failed: 'request.time'

Could you file an issue on Istio? The mixer bypass adopter is what we are using, not built by SkyWalking.

@hanahmily Do you know anything about this?

**Comment by wu-sheng** [comment]
`request.time` should be always there, I am not following why istio says not there.

**Comment by wu-sheng** [comment]
@ZackButcher Do you have any clue?

**Comment by nandhyala** [comment]
@wu-sheng ,

I went back and checked on istio granfana dash board i see all new services data.
Due to some issue only on skywalking dashboard we are not seeing new services data.

**Comment by wu-sheng** [comment]
Because we are using different adopter. We are using Istio bypass adopter, your error log seems from there, right? Why it can't get `request.time` is the issue.

Read Istio doc, https://istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/. This key `request.time` is still there.

**Comment by wu-sheng** [comment]
Grafana thing is not referable, because they are not sharing same data source.

**Comment by nandhyala** [comment]
@wu-sheng  ok got it.

**Comment by nandhyala** [comment]
If we upgrade istio to latest version from 1.2.3 it will fix ?

**Comment by nandhyala** [comment]
@wu-sheng  If we upgrade istio to latest version from 1.2.3 it will fix ?

**Comment by wu-sheng** [comment]
@nandhyala I was using istio mixer solution only in 1.0.4 and 1.1, today, I am always using ALS, without mixer. So, sorry, haven't to tested these new versions, including 1.2.3. That is why I asked you to check to istio team, they know more than me.

**Comment by nandhyala** [comment]
Sure @wu-sheng ,I will check with istio team.
