### ISSUE TITLE
What does the refs array represent? Thank you!

### ISSUE THREAD

**Issue by x22x22** [apache/skywalking#3431]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

What does the refs array represent? Thank you!

![image](https://user-images.githubusercontent.com/3389949/64469056-87622d00-d15e-11e9-9191-399fa5e7a37d.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Because you could have multiple parents. Like consuming several messages of MQ in one request. Or batch jobs, which assigned by multiple sources.
