### ISSUE TITLE
After the vnode is created in the track UI, the normal child nodes will not be displayed and associated.

### ISSUE THREAD

**Issue by x22x22** [apache/skywalking#3432]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

After the vnode is created in the track UI, the normal child nodes will not be displayed and associated.

![image](https://user-images.githubusercontent.com/3389949/64470281-65bf7080-d173-11e9-967d-3d919cfc467f.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The vnode creation rule needs to be improved. @x22x22 Ping me if you have some uncertain things.

**Comment by x22x22** [comment]
Please wait for me to fix this bug before considering release 6.4

**Comment by wu-sheng** [comment]
When ref is missing, we need to create
1. Target spanId in the target segment id, with parentSegmentId = 0.
1. spanId = 0 in the target segment id, with parentSegmentId = -1. 

For parent span, we should follow same rule, if span is not exist, create parent span and root span(spanid = 0)

All these vnode should only be added when it is not existing(or created before)

**Comment by x22x22** [comment]
Have to repair, see https://github.com/apache/skywalking-rocketbot-ui/pull/154

**Comment by SevenBlue2018** [comment]
![image](https://user-images.githubusercontent.com/11767168/66918094-2f69f080-f051-11e9-89d4-a9f71b4e425c.png)
Now  I have the same problem in 6.4.0.
