### ISSUE TITLE
use my own elasticsearch instance? helm config

### ISSUE THREAD

**Issue by dbones** [apache/skywalking#3434]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I have my own existing elastic search server (i.e. either a single-node or one i will setup via aws) how can i configure this via the helm chart?

**Comment by wu-sheng** [comment]
Set the value of this https://github.com/apache/skywalking-kubernetes/blob/master/helm-chart/6.1.0/templates/oap-deployment.yaml#L94

`SW_STORAGE_ES_CLUSTER_NODES` is the system env name for this. Check the https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/assembly/application.yml#L73-L92 System env names are there.

Also, recommend do quick start at local first, only jdk 8 required to test.

**Comment by hanahmily** [comment]
Helm chart doesn't support external elasticsearch instance right now. If you want to use it anyway, oap-deployment should be updated and elasticsearch.enable set to false to remove internal es installed
