### ISSUE TITLE
Grpc server thread pool is full, rejecting the task

### ISSUE THREAD

**Issue by jadezhong** [apache/skywalking#3441]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
We have two oapServer, one of it report "Grpc server thread pool is full, rejecting the task" after running some days with fix GrpcServer's threadPoolSize and queueSize.

___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 6.3.0
CentOS 7.x, JDK 1.8, 8C CPU, 16G RAM

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Following solution of #3405, fixed 6.3.0 according to master branch(6.4.0 under testing) by setting GrpcServer's threadPoolSize and queueSize, oapServer seems ok within one day(no grpc-default-executor-* exponential growth and no heap OOM). but after running two ~ three days, one of our oapServer continue report "Grpc server thread pool is full, rejecting the task"(屏幕快照 2019-09-09 10 09 53) till now(屏幕快照 2019-09-09 10 10 36) in log.
in jConsole, difference between two oapServer is the one reported  "Grpc server thread pool is full, rejecting the task" has no grpc-default-executor-*(屏幕快照 2019-09-09 10 11 42).

<img width="1414" alt="屏幕快照 2019-09-09 10 09 53" src="https://user-images.githubusercontent.com/49858897/64500172-b4dde080-d2ee-11e9-9c96-b6eb7bf873d0.png">
<img width="1281" alt="屏幕快照 2019-09-09 10 10 36" src="https://user-images.githubusercontent.com/49858897/64500215-dfc83480-d2ee-11e9-8aeb-dbd7e824217c.png">
<img width="1640" alt="屏幕快照 2019-09-09 10 11 42" src="https://user-images.githubusercontent.com/49858897/64500248-fbcbd600-d2ee-11e9-929f-a2d59cd5694d.png">

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/64500352-6bda5c00-d2ef-11e9-9fdc-98f1e28f080d.png)
fixed these files.

**Comment by wu-sheng** [comment]
We added thread size control to make sure you wouldn't OOM. But two many connections are not acceptable. You should not have so many connections.

**Comment by jadezhong** [comment]
@wu-sheng fully upgraded to 6.4.0 and running almost three days, the problem reappeared: continue report "Grpc server thread pool is full, rejecting the task" error from grpc-default-worker-ELG-*.
in jvisualvm, no grpc-default-executor-*, looks like these threads are all destoried somehow.
pls look into this problem.

**Comment by wu-sheng** [comment]
They you have to look up your server env. Something blocks, I can't be sure why. Most likely, your storage crashed or facing performance issue, then, the grpc can't write data to memory cache, which could trigger this issue.

**Comment by wu-sheng** [comment]
What do you mean thread destoried?

**Comment by jadezhong** [comment]
from jvisualvm, can't find any thread named "grpc-default-executor-*", as if they have been destroied somehow. but another server still running ok has several "grpc-default-executor-*".

**Comment by wu-sheng** [comment]
That is new to me. Could you find why? How to make grpc thread exit

**Comment by jadezhong** [comment]
strange thing is "grpc-default-executor-" is from the default thread pool in grpc, which use name in format of "grpc-default-executor-%d", but in 6.4.0, a ThreadPoolExecutor is set in GRPCServer "nettyServerBuilder...executor(executor)" with given threadPoolSize and queueSize, so it make no sense still using the default thread pool.

**Comment by wu-sheng** [comment]
In 6.4.0, we use our own thread pool. Because in some cases, too many grpc thread created. That is expected.

**Comment by jadezhong** [comment]
@wu-sheng elasticsearch[scheduler][T#1], this thread blocking all grpc-default-executor-*, and that thread is continue in waiting status.

**Comment by wu-sheng** [comment]
If they are blocked, that is expected from design level, You need to find out why elasticsearch doesn't response. Check your ES server status and monitoring tool.

**Comment by jadezhong** [comment]
yes i will investigate our ES, but what i think is the data keeper should be the lowest priority task compare to others, especially those to save metrics/trace or register service/serviceInstance into ES, so can the data keeper modified to delete older datas only in "Idle" time?

**Comment by wu-sheng** [comment]
> yes i will investigate our ES, but what i think is the data keeper should be the lowest priority task compare to others, especially those to save metrics/trace or register service/serviceInstance into ES, so can the data keeper modified to delete older datas only in "Idle" time?

Delete? The 6.4.0(6.3.0+) delete only happens in middle night, and once per day. You may read the delete logs, but in ElasticSearch implementation, it would execute like that.

**Comment by jadezhong** [comment]
ps., after running oapServer on two servers, our ES become heavy loaded all the time, cpu/heap/load always off the chart.

**Comment by jadezhong** [comment]
that's strange, from the log, i can only surpose it is running the data keeper executor before thread pool is full.

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/65306905-1a688180-dbb9-11e9-9796-3f084b82636a.png)

**Comment by wu-sheng** [comment]
Read `ElasticsearchStorageTTL`, if you will find the delete wouldn't happen in every 5 mins. This is only the check running every 5 mins.

**Comment by jadezhong** [comment]
we plan to use skywalking on our production environment, but for the moment it can been done without solving this problem first, could you give use some advice on ES heavy load after running oapServer, for example, to disable some functionality that we may not use.
or where to find a stable version of skywalking?

**Comment by wu-sheng** [comment]
Really, there is nothing I can do. 
There are plenty of users using the project in production environments. Some of them are supporting several TB traces per day.
We can't provide the ElasticSearch service for you. ElasticSearch is a stable, powerful and widely used data platform, so you should be able to find the solution by yourself.

The only thing I could say is, either you don't set your ElasticSearch right(we highlighted some in our FAQ, https://github.com/apache/skywalking/blob/master/docs/en/FAQ/ES-Server-FAQ.md), or your ElasticSearch cluster is too small.

**Comment by DongWeiMa** [comment]
i have the same question,how do you resolve this probleam? @jadezhong

**Comment by wz2cool** [comment]
today, we also meet the same problem @wu-sheng

**Comment by jadezhong** [comment]
@DongWeiMa @wz2cool 

Sorry for the delayed reply.
never solved, i duplicated the "thread pool is full" scenario again, and using jvisualvm i saw the L*_AGGREGATION thread is dead due to each 00:00 we start to run a daily ElasticSearch index removal job, this will make the ElasticSearch reject tasks at that time, i suppose this will make those threads dead one after one.
Later we separate ElasticSearch used by Skywalking out, and never do index removal job, for almost a month, Skywalking seems works fine.
