### ISSUE TITLE
why skywalking can work without config/datasource-settings.properties   correct config?

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3442]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
 I   don't set the jdbcUrl in “config/datasource-settings.properties” right
value   , why does skywalking OAP start and UI display properly?

**Comment by kezhenxu94** [comment]
@webb2019 `config/datasource-settings.properties` only takes effect when the storage is set to H2 or MySQL, otherwise, SkyWalking works properly as if `config/datasource-settings.properties` doesn't exist
