### ISSUE TITLE
client may not successfully re-registed after oapServer restarted

### ISSUE THREAD

**Issue by jadezhong** [apache/skywalking#3443]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
client may not successfully re-registed after oapServer restarted.
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 6.3.0
CentOS 7.x, JDK 1.8, 8C CPU, 16G RAM

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
After oapServer restarted, some service with skywalking-agent may not successfully re-registed onto oapServer, no significant error in log that shows info of the "not successfully re-registed" services(name or something else to show which service it is). restart the service will solve the problem, but it is not a good choise if services and skywalking is in product environment. how to solve this problem.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
In some env, 6.3.0 may have this issue, due to some other fixed. Try master codes or next release. It may relate to grpc reconnection issue. But basically, we should have fixed it.
