### ISSUE TITLE
where file can set es quest timeout in oap?

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3444]
look for help
how skywalking oap  set elasticSearch requst like blow to anther timeout time 
[POST] service_inventory/type/hermes_0_0/_update?refresh=true&timeout=1m 
the default timeout value always be 1m
i want to set longer timeout

**Comment by wu-sheng** [comment]
We don't have it, I think. Contribution is welcome.

**Comment by wu-sheng** [comment]
But 1m is very long, I think.

**Comment by webb2019** [comment]
thanks . I've been learning the source code of skywalking and I'm looking forward to contributing

![image](https://user-images.githubusercontent.com/52440226/64581182-b4f7e200-d3bb-11e9-9168-d78d6d8a0b99.png)
As mentioned in the documentation, oap rebuilds the Es index regularly at every 1:00 am, Can you tell me which class implements this timed deletion?? thanks

**Comment by wu-sheng** [comment]
Create is based on elasticsearch template, data driven. No timer related.

**Comment by webb2019** [comment]
> Create is based on elasticsearch template, data driven. No timer related.
I understand that oap deleted endpoint_relation_cpm-20190909, and es create index endpoint_relation_cpm-20190910, data driven.
But the log shows that oap caused an error by dropping the index. I don't know why
![image](https://user-images.githubusercontent.com/52440226/64581927-829bb400-d3be-11e9-8b13-ca5a22b09abf.png)

![image](https://user-images.githubusercontent.com/52440226/64581888-5da74100-d3be-11e9-9f3d-5361ddc08344.png)

**Comment by wu-sheng** [comment]
Are you running 2 OAP clusters? Or 2 nodes without cluster management? I think this should not happen.

**Comment by webb2019** [comment]
> Are you running 2 OAP clusters? Or 2 nodes without cluster management? I think this should not happen.

no ,  OAP standlone and Es  all  locate at one host  .   we just are testing how to work .
 Can you give me some ideas to find out reseaon.

**Comment by wu-sheng** [comment]
> I understand that oap deleted endpoint_relation_cpm-20190909, and es create index endpoint_relation_cpm-20190910, data driven.

This should not happen at same time. Only 20190908 deleting and endpoint_relation_cpm creating. Min TTL is 2.

**Comment by wu-sheng** [comment]
We need to make sure, there is at least one index is there. Overwise, the no index found happens.

**Comment by webb2019** [comment]
> > I understand that oap deleted endpoint_relation_cpm-20190909, and es create index endpoint_relation_cpm-20190910, data driven.
> 
> This should not happen at same time. Only 20190908 deleting and endpoint_relation_cpm creating. Min TTL is 2.

simply say,   when I start oap  the first time  then creating index 20190909 ,  and come to nex day I checked there are only 20191010 there  in Es,   20190909 indices truly be deleted.

i have got  message from centos in the /var/mail/root  ,like below:
![image](https://user-images.githubusercontent.com/52440226/64586209-2e003500-d3ce-11e9-9e27-c25f4ac14d3c.png)

**Comment by wu-sheng** [comment]
In my test env, there is always keeping at least two indexes(default 2). And as I checked the source codes, it says so too. Unless you set the value to 1 explicitly.

**Comment by webb2019** [comment]
> > > I understand that oap deleted endpoint_relation_cpm-20190909, and es create index endpoint_relation_cpm-20190910, data driven.
> > 
> > 
> > This should not happen at same time. Only 20190908 deleting and endpoint_relation_cpm creating. Min TTL is 2.
> 
> simply say, when I start oap the first time then creating index 20190909 , and come to nex day I checked there are only 20191010 there in Es, 20190909 indices truly be deleted.
> 
> i have got message from centos in the /var/mail/root ,like below:
> ![image](https://user-images.githubusercontent.com/52440226/64586209-2e003500-d3ce-11e9-9e27-c25f4ac14d3c.png)



> In my test env, there is always keeping at least two indexes(default 2). And as I checked the source codes, it says so too. Unless you set the value to 1 explicitly.

Maybe I messed up the Settings,  Can you tell me which parameter to set in config file , or which code to specify in java file

**Comment by wu-sheng** [comment]
```yaml
    recordDataTTL: ${SW_CORE_RECORD_DATA_TTL:90} # Unit is minute
    minuteMetricsDataTTL: ${SW_CORE_MINUTE_METRIC_DATA_TTL:90} # Unit is minute
    hourMetricsDataTTL: ${SW_CORE_HOUR_METRIC_DATA_TTL:36} # Unit is hour
    dayMetricsDataTTL: ${SW_CORE_DAY_METRIC_DATA_TTL:45} # Unit is day
    monthMetricsDataTTL: ${SW_CORE_MONTH_METRIC_DATA_TTL:18} # Unit is month
```

Don't change any of this as `1`. Are you using master branch?

**Comment by webb2019** [comment]
> ```yaml
>     recordDataTTL: ${SW_CORE_RECORD_DATA_TTL:90} # Unit is minute
>     minuteMetricsDataTTL: ${SW_CORE_MINUTE_METRIC_DATA_TTL:90} # Unit is minute
>     hourMetricsDataTTL: ${SW_CORE_HOUR_METRIC_DATA_TTL:36} # Unit is hour
>     dayMetricsDataTTL: ${SW_CORE_DAY_METRIC_DATA_TTL:45} # Unit is day
>     monthMetricsDataTTL: ${SW_CORE_MONTH_METRIC_DATA_TTL:18} # Unit is month
> ```
> 
> Don't change any of this as `1`. Are you using master branch?

I downloaded skywalking 6.3.0  tar package. I have't changed this parameters.
How can I understand the parameter values you listed above?
As discussed earlier index endpoint_relation_cpm_20190908  will be deleted at 20190910, endpoint_relation_cpm_20190909 will retain ,what params effect this deleting action , hourMetricsDataTTL ? or recordDataTTL ?

**Comment by wu-sheng** [comment]
6.3.0 is running in 2 days ttl due to a bug. But still not one day. I think you could need to debug why your ttl seems to 1 day, which triggers your issue.

Record for trace, metrics for different time accuracy.

**Comment by webb2019** [comment]
> 6.3.0 is running in 2 days ttl due to a bug. But still not one day. I think you could need to debug why your ttl seems to 1 day, which triggers your issue.
> 
> Record for trace, metrics for different time accuracy.

hi, After analysis further, I found some new  details.  before run oap server, I run “oapServiceInit.sh”  create index templates  in Es ,Except below indexes:
- register_lock
- endpoint_inventory
- service_instance_inventory
- network_address_inventory
- service_inventory
these indexes will be created in oap start process ,I guess  
but come to next day like I said, these indexes will be deleted  and can't  be created again.
all problems of discussion maybe relate to this .

**Comment by wu-sheng** [comment]
All these indexes should not be delete even. These are metadata indexes.
