### ISSUE TITLE
Docker entry shell is not right in Jaeger and Zipkin receiver

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#3449]
According to this,
https://github.com/apache/skywalking-docker/blob/master/6/6.3/oap/docker-entrypoint.sh, it missed providing storage for zipkin and jaeger receiver.

@hanahmily Read these two
1. https://github.com/apache/skywalking-docker/blob/master/6/6.3/oap/docker-entrypoint.sh
1. https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#elasticsearch-6-with-jaeger-trace-extension

They are using different storage implementations of storage.

**Comment by hanahmily** [comment]
Our next plan is to push a new image with tag 6.3.1 to fix issues related to application.yaml generation

BTW, there’s a env variable[1] to override application.yaml generated by docker-entrypoint.sh, that provides
another approach for some guys can’t wait a new image.

1. https://github.com/apache/skywalking-docker/blob/b6989daf4f03dc1562fd76e1ac0ab929ac7962a8/6/6.3/oap/docker-entrypoint.sh#L376


Hongtao Gao

Apache SkyWalking && Apache ShardingSphere
Twitter, @hanahmily

**Comment by wu-sheng** [comment]
@hanahmily 6.3.1 is a new version, which has no Apache release, making this a bad idea. People may confuse, whether it is an Apache release image or not.

SkyWalking 6.4.0 will be shipped tomorrow, so let's move this to 6.4.0 only. Otherwise, you will need a release vote for your 6.3.1 image docker and script file.
