### ISSUE TITLE
SkywalkingAgent reconnect:false

### ISSUE THREAD

**Issue by weiqiang333** [apache/skywalking#3454]
- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
```
  skywalking agent Why not reconnect
```

___
### Bug
- Which version of SkyWalking, OS and JRE?
```
   version: 6.2.0
   OS: centos 4.14.123-111.109.amzn2.x86_64
  JDK version: 1.8.0_121
```

- Which company or project?
> GrowingIO

- What happen?
```
I restarted OAP and my agent has been failing to reconnect.
I confirm that the OAP is working properly and the test restarts the agent service and the connection is normal.
Why does the agent need to restart the connection?
```
- log
```
DEBUG 2019-09-11 08:24:47:972 DataCarrier.DEFAULT.Consumser.0.Thread TraceSegmentServiceClient :  6313 trace segments have been abandoned, cause by no available channel. 
DEBUG 2019-09-11 08:24:47:976 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-11 08:24:50:959 SkywalkingAgent-1-GRPCChannelManager-0 GRPCChannelManager :  Selected collector grpc service running, reconnect:false. 
DEBUG 2019-09-11 08:24:50:976 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-11 08:24:53:976 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-11 08:24:56:976 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-11 08:24:59:976 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-11 08:25:02:976 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-09-11 08:25:05:976 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:DISCONNECT.
```

**Comment by wu-sheng** [comment]
In some envs, we noticed that. 6.4.0 should be released today, we fixed it.

**Comment by weiqiang333** [comment]
Upgrade 6.4.0 Solution

**Comment by adventurer2008** [comment]
I use 6.5.0 version and ES database . And I also have the same problems.


DEBUG 2019-12-19 09:44:58:529 SkywalkingAgent-2-GRPCChannelManager-0 GRPCChannelManager : Selected collector grpc **service running, reconnect:true.** 
DEBUG 2019-12-19 09:44:58:538 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-12-19 09:45:01:538 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-12-19 09:45:02:859 DataCarrier.DEFAULT.Consumser.0.Thread TraceSegmentServiceClient **: 2 trace segments have been abandoned, cause by no available channel**. 
DEBUG 2019-12-19 09:45:04:538 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, **status:DISCONNECT**. 
DEBUG 2019-12-19 09:45:07:538 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2019-12-19 09:45:10:538 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:DISCONNECT.
