### ISSUE TITLE
fail to build skywalking on windows

### ISSUE THREAD

**Issue by chiqiu** [apache/skywalking#3456]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
question
___
### Question
- What do you want to know?
I cloned the code to my windows machine, tried to build it according to the build guide but failed.
Here are the logs I got:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
8.0:compile (default-compile) on project apm-network: Compilation failure: Compi
lation failure:
[ERROR] /C:/work/skywalking/apm-protocol/apm-network/src/main/java/org/apache/sk
ywalking/apm/network/trace/component/command/CommandDeserializer.java:[20,48] 程
序包org.apache.skywalking.apm.network.common不存在
[ERROR] /C:/work/skywalking/apm-protocol/apm-network/src/main/java/org/apache/sk
ywalking/apm/network/trace/component/command/CommandDeserializer.java:[27,49] 找
不到符号

Could you please tell me how can I build it ? 
My ENV:

Maven home: C:\work\apache-maven-3.6.0                                          
 Java version: 1.8.0_191-1-ojdkbuild, vendor: Oracle Corporation
Thanks.
--

**Comment by chiqiu** [comment]
Update: I don't have build issue on Linux

**Comment by wu-sheng** [comment]
Windows file system is different, you may be facing too long file path of git or file system. Check you log.

**Comment by chiqiu** [comment]
This is not a too long file path problem because I have fixed this problem before. anyway, I will use linux instead, thanks for the reply

**Comment by Yazhou-Lei** [comment]
> This is not a too long file path problem because I have fixed this problem before. anyway, I will use linux instead, thanks for the reply

Can you tell me how you fixed this problem? 
----------------------------------------------------------------------
[INFO] Compiling 1 proto file(s) to D:\Huaxia\oms\aries\aries-monitor-center\aries-monitor-apm\apache-skywalking-apm-7.0.0\oap-server
\server-configuration\grpc-configuration-sync\target\generated-sources\protobuf\java
[ERROR] PROTOC FAILED: D:\Huaxia\oms\aries\aries-monitor-center\aries-monitor-apm\apache-skywalking-apm-7.0.0\oap-server\server-confi
guration\grpc-configuration-sync\target\generated-sources\protobuf\java/org/apache/skywalking/oap/server/configuration/service/Config
urationRequest.java: No such file or directory

[ERROR] D:\Huaxia\oms\aries\aries-monitor-center\aries-monitor-apm\apache-skywalking-apm-7.0.0\oap-server\server-configuration\grpc-c
onfiguration-sync\src\main\proto\configuration-service.proto [0:0]: D:\Huaxia\oms\aries\aries-monitor-center\aries-monitor-apm\apache
-skywalking-apm-7.0.0\oap-server\server-configuration\grpc-configuration-sync\target\generated-sources\protobuf\java/org/apache/skywa
lking/oap/server/configuration/service/ConfigurationRequest.java: No such file or directory

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.815 s
[INFO] Finished at: 2020-05-28T16:53:08+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:compile (default) on project grpc-configuration
-sync: protoc did not exit cleanly. Review output for more information. -> [Help 1]

**Comment by Kenny-Tang** [comment]
I got the same problem, but i still can not search the way to solve it from the internet
