### ISSUE TITLE
On the topology, Is it possible to show the percent of errors and throughput between the application?

### ISSUE THREAD

**Issue by kevin3329** [apache/skywalking#3457]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Feature or performance improvement

___
### Requirement or improvement
- We want to see the throughput and errors between systems from a global perspective by topology. This can helps us find the problem quickly.
 On the old UI, the topology can show difference of throughput by the line's thickness，and also can show application's error percent. But these can't show in the new UI.

**Comment by wu-sheng** [comment]
![image](https://user-images.githubusercontent.com/5441976/64702503-87fd0b00-d45f-11e9-87f6-ff4fa05b666e.png)

It is already there, click the node inside red box.
