### ISSUE TITLE
Whether the dashboard can support to display service error endpoint

### ISSUE THREAD

**Issue by kevin3329** [apache/skywalking#3458]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Requirement

___
### Requirement 
-  We want to see the top error endpoind in dashboard. In some scenarios, there are system exceptions but the response time is very fast. Currently these cannot show in the dashboard.
All of these data have been collected, I think this function is not difficult to implement.

**Comment by wu-sheng** [comment]
That is SLA top N in desc order. The backend has supported, UI doesn't include it. If you want to add, contribution is welcome.
