### ISSUE TITLE
On the service dashboard, Is it possible to linked slow endpoint to the trace page.

### ISSUE THREAD

**Issue by kevin3329** [apache/skywalking#3459]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Requirement

___
### Requirement or improvement
- On the Service Dashboard,Is it possible to linked slow endpoint to the trace page.
By this we can positioning problem more convenient.

**Comment by wu-sheng** [comment]
Not today.

**Comment by adventurer2008** [comment]
I't's very necessary.
