### ISSUE TITLE
6.3 ui 配置用户名密码无效

### ISSUE THREAD

**Issue by yangyang198599** [apache/skywalking#3461]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [× ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dmsolr** [comment]
That is removed in 6.2.0. As far as i know.

**Comment by wu-sheng** [comment]
English only, and yes, removed.
