### ISSUE TITLE
Grpc server can not get traceId with apm-toolkit-logback-1.x when get remote call

### ISSUE THREAD

**Issue by bugmakesprogress** [apache/skywalking#3463]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- Which version of SkyWalking, OS and JRE?

SkyWalking 6.3.0 ubuntu java8

- What happen?

I m using skywalking in two project. I request A project method through http protocol. A project method then calll B project method through grpc protocol. The question is: traceId can be printed perfectly in project A log. However, project B which is Grpc server can not print the same traceId in project A. instead, traceId returns [TID:N/A] as a result.

**Comment by wu-sheng** [comment]
Trace id is only available when there is tracing context existing and agent has registered. If you are using a simple main, it doesn't work. SkyWalking is designed for server, meaning always standby.
