### ISSUE TITLE
Correction description about application config make NPE issue

### ISSUE THREAD

**Issue by itfinally** [apache/skywalking#3464]
I am highly doubting this is a docker issue. UUID is not existing somehow.

_Originally posted by @wu-sheng in https://github.com/apache/skywalking/issues/3460#issuecomment-530388540_

--- split line ---

Sorry , I realize that I gave a wrong description.

The config make NPE like this:

```yml
receiver-so11y:
  default:
```

Just correction my issue description.

**Comment by wu-sheng** [comment]
OK, that makes sense. @hanahmily

**Comment by wu-sheng** [comment]
You could send pull request directly.

**Comment by hanahmily** [comment]
Can you share you command line to start docker container? I didn't get any error when I run it. @itfinally

**Comment by itfinally** [comment]
Sure, the command:
```yml
docker run \
  --network=host \
  --restart=always \
  --env-file /data/server/skywalking/oap_config.list \
  --name skywalking-oap \
  -d docker.io/apache/skywalking-oap-server
```

And `oap_config.list`:

```text
SW_CLUSTER=nacos
SW_SERVICE_NAME=com.baibu.platform.skywalking
SW_CLUSTER_NACOS_HOST_PORT=192.168.16.132:8848


SW_STORAGE=elasticsearch
#SW_NAMESPACE=skywalking
SW_STORAGE_ES_CLUSTER_NODES=192.168.16.132:9200
SW_STORAGE_ES_HTTP_PROTOCOL=http


SW_CONFIGURATION=nacos
SW_CONFIGURATION_NACO_SERVER_ADDR=192.168.16.132
SW_CONFIGURATION_NACO_PORT=8848
SW_CONFIGURATION_NACO_GROUP=skywalking
SW_CONFIGURATION_NACO_CLUSTER_NAME=default


SW_CORE_REST_HOST=0.0.0.0
SW_CORE_REST_PORT=12800
SW_CORE_REST_CONTEXT_PATH=/
SW_CORE_GRPC_HOST=0.0.0.0
SW_CORE_GRPC_PORT=11800
```

**Comment by itfinally** [comment]
Emmm....   
Is the `latest` version is really is 6.3.0 version ?

**Comment by wu-sheng** [comment]
> Is the latest version is really is 6.3.0 version ?

I think the latest is 6.4.0, we just released it several days ago.
