### ISSUE TITLE
got traceId "N/A" in the class extends ZuulFilter under 6.4.0

### ISSUE THREAD

**Issue by jadezhong** [apache/skywalking#3469]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?
got traceId "N/A" in the class extends ZuulFilter under 6.4.0, how to solve this problem?

___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 6.4.0, CentOS 7.x, JDK 1.8, 8C CPU, 16G RAM

- Which company or project?

- What happen?
upgraded from 6.3.0 to 6.4.0, our gateway using Zuul, get traceId in the class extends ZuulFilter, it is ok under 6.3.0, but get traceId "N/A" under 6.4.0, debug step into found out the segment is null, how to solve this problem?

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by jadezhong** [comment]
@wu-sheng found out this problem caused by apm-sniffer/apm-sdk-plugin/undertow-plugins/undertow-2.x-plugin under 6.4.0, TraceContext.traceId() is ok when i use one under 6.3.0.

**Comment by jadezhong** [comment]
get undertow-2.x-plugin from 6.3.0, package it and upload it onto server's .../agent/plugins/, test and no conflict.

**Comment by jadezhong** [comment]
by the way, we use 1.4.* undertow.

**Comment by wu-sheng** [comment]
We can't verify in every case. If you think there is an issue, I think it is better to fix and send pull request. There are too many possibilities for plugin.
