### ISSUE TITLE
[Agent] How can i get  TraceId  in  c#. net core 2.2

### ISSUE THREAD

**Issue by chaoyueg** [apache/skywalking#3472]
[Agent] How can i get  TraceId  in  c#. net core 2.2
i  want to get the skywalking's traceId ,  then the trace in Skywalking can be linked with my data row.
unfortunately, i didn't find any doc or helps from internet, so i add issue here for help!
thanks.

**Comment by wu-sheng** [comment]
.net core agent is not skywalking's officially yet. So, submit this at agent core repo.
