### ISSUE TITLE
CANCELLED: cancelled before receiving half close

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3474]
___
### Question
 OAP Keep printing this error:

![image](https://user-images.githubusercontent.com/52440226/64949815-9eb2c000-d8ac-11e9-9f05-349e3540d7fd.png)
Is it because of communication timeout between agent and OAP??

**Comment by SummerOfServenteen** [comment]
I I also have this problem.In what scenario did it happen?Are your applications concurrently large?

**Comment by wu-sheng** [comment]
Half closing means, client disconnects from OAP, no matter what reason triggers this.

**Comment by SummerOfServenteen** [comment]
But it will cause data to no longer be written to es, and after a period of time, there will be no data on the page.

**Comment by wu-sheng** [comment]
I don't think that is the issue.

**Comment by wu-sheng** [comment]
I don't think that is the issue.

**Comment by wu-sheng** [comment]
I don't think that is the issue.

**Comment by WildWolfBang** [comment]
I I also have this problem. It works after  restarting skywalking-oap-server

**Comment by sfy1231** [comment]
> I don't think that is the issue.

But the log points to this is a communication issue, so could u give some adive or fix to avoide that? thx

**Comment by wu-sheng** [comment]
This is not a communication issue, every time you shutdown the agent, the TCP broken, and you got this at server side.
