### ISSUE TITLE
How to set UI login?

### ISSUE THREAD

**Issue by Zack-Ku** [apache/skywalking#3479]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Question
- What do you want to know?
Why remove login in the version 6.2 ? 
How can we set the protection for the ui after removing the login page?

**Comment by wu-sheng** [comment]
Because the login is not the real login, you could bypass it easily. It is being treated as a security vulnerability, so have to remove it.
