### ISSUE TITLE
TraceContext.traceId() always return [Ignored Trace]

### ISSUE THREAD

**Issue by qlql489** [apache/skywalking#3480]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
we hava 100+ services use skywalking,  and log TraceContext.traceId(), but in  some services 
always get [Ignored Trace], we not set sampling or IGNORE_SUFFIX, so what's the reason?
### Bug
- Which version of SkyWalking, OS and JRE?
6.2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You need to find out why `IgnoredTracerContext` created.  In my mind, either agent hasn't registered to backend successfully, or sampling/ignore mechanism is working. No other case.
