### ISSUE TITLE
An enhancement about A Table model Of Span View.

### ISSUE THREAD

**Issue by zhaoxunyong** [apache/skywalking#3481]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

  In the page of span view, I switched to the table model, but the title so narrow, I couldn't see the full information(including the contents). whether allow me adjusting the width? There is an alternative way to improve it:

1. When I press the left mouse button at the border of title, allowing me dragging the title until I can see the full information.
2. When I move the mouse there, giving a hint about the full title information.

I prefer the first way. and you guys?

Thanks~

![Snip20190918_3](https://user-images.githubusercontent.com/8733266/65112216-83ad9080-da11-11e9-8a64-0f815952adae.png)

**Comment by wu-sheng** [comment]
This UI enhancement is open to anyone who has interests to contribute. If you could send a pull request with a video to show how it will be. We are open to discuss there.

**Comment by x22x22** [comment]
It is recommended to use UI components, which can save contributors a lot of time.
https://element.eleme.cn/#/en-US/component/table#table-with-border

**Comment by wu-sheng** [comment]
Provided in 8.0.0.
