### ISSUE TITLE
intercept failure  java.lang.NullPointerException

### ISSUE THREAD

**Issue by pmq5205209** [apache/skywalking#3484]
![图片](https://user-images.githubusercontent.com/19252220/65146687-fc7f0d80-da4e-11e9-94a6-2f66ad34ab3a.png)
![图片](https://user-images.githubusercontent.com/19252220/65146706-0acd2980-da4f-11e9-9b2c-9744f15e5c7c.png)
![图片](https://user-images.githubusercontent.com/19252220/65146731-19b3dc00-da4f-11e9-9a85-73652b6daa09.png)

The Websphere can always work well. But after more 300 spans should be created in 30 seconds, it  cann't work.

**Comment by wu-sheng** [comment]
Shadow tracing context means you have plugin incompatible issue. But can't be sure which one. Recommend you to test plugin one by one, and only choose plugins you required.

**Comment by pmq5205209** [comment]
I found that an article had solved this problem. [](https://www.jianshu.com/p/52bbc503be19) .  I changed my codes like this:
![图片](https://user-images.githubusercontent.com/19252220/65207975-3808ee80-dac6-11e9-9661-a6b0a5946085.png)
And the agent would print warning logs, but it would print log like "intercept failure 
java.lang.NullPointerException".
