### ISSUE TITLE
dubbox微服务应用在UI拓扑图中的显示问题

### ISSUE THREAD

**Issue by itwenwu** [apache/skywalking#3489]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug

___
### Question
在agent设置name的情况下，UI拓扑图页面正常情况下node显示的name应该为agent的name，而且会以连线的方式表示各node之间的调用关系。
但在skywalking6.3.0和6.4.0这两个版本中拓扑图显示的调用关系出现了问题（6.2.0是没有问题的），下面以一个简单例子说明下问题：

有两个应用A和B，A是服务消费方，B是服务提供方，B的服务IP端口为：10.10.10.1:10001

1、正常情况应该是：
拓扑图中有2个node节点，分别为A和B，并且它们之间以连线的方式标注了调用关系。

2、而在6.3.0和6.4.0两个版本中却出现了以下的问题：
（1）、拓扑图中有3个node节点，分别是1个A，2个B，其中1个B的node名称为agent的名称，另1个B的node名称为10.10.10.1:10001；
（2）、以agent名称命名的B的node是孤立的，没有和A以连线的方式建立调用关系；
（3）、而是A和B的命名为10.10.10.1:10001的node以连线建立调用关系。

___
### Bug
- Which version of SkyWalking, OS and JRE?
相同应用运行环境，以上情况在skywalking6.2.0没有问题，在之后的版本6.3.0、6.4.0中都存在问题。

**Comment by wu-sheng** [comment]
English only.
