### ISSUE TITLE
Service not shown in Skywalking UI using SkyAPM.Agent.AspNetCore. please help.

### ISSUE THREAD

**Issue by 12371601** [apache/skywalking#3495]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
  Bug

___
### Question
- What do you want to know?
How to use SkyAPM.Agent.AspNetCore  on Docker File  for docker to run asp.net core app?
Could you help us check our docker file?
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
SkyWalking: 6.1
OS: Centos 7
.NET Runtime: .net core 2.2

- Which company or project?
Chy company

- What happen?
Service not shown in Skywalking UI using SkyAPM.Agent.AspNetCore. please help.
[http://letyouknow.net/img/skyissue.jpg](url)
please check issue screenshot: http://letyouknow.net/img/skyissue.jpg
below is docker file:

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
RUN dotnet tool install -g SkyWalking.DotNet.CLI
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet skywalking install

FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
COPY . .

FROM base AS final
ENV PATH="$PATH:/usr/local/share/dotnet/store"
ENV ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
ENV SKYWALKING__SERVICENAME=Lyn.Gateway
ENV DOTNET_ADDITIONAL_DEPS=/usr/local/share/dotnet/x64/additionalDeps/skywalking.agent.aspnetcore
COPY --from=build /usr/local/share/dotnet/store /usr/share/dotnet/store
COPY --from=build /usr/local/share/dotnet/store /usr/local/share/dotnet/store
COPY --from=build /usr/local/share/dotnet/x64 /usr/local/share/dotnet/x64
ENTRYPOINT ["dotnet", "Lyn.Gateway.dll"]

___
### Requirement or improvement
Help us check docker file.

**Comment by wu-sheng** [comment]
Please follow setup document. Your target application timezone doesn't match your browser. Change either side to make it matched
