### ISSUE TITLE
segment 索引 是不是只保存2两天的数据

### ISSUE THREAD

**Issue by lichengliang1** [apache/skywalking#3508]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
segment 索引 是不是只保存2两天的数据
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking6.3  jdk8  es6.5

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only. TTL document provides this detail.

**Comment by wu-sheng** [comment]
6.3 has a bug about TTL setting is not working in some cases, read issue and changelog. 6.4 release has fixed this.
