### ISSUE TITLE
Send UpstreamSegment to collector fail with a grpc internal exception

### ISSUE THREAD

**Issue by hepyu** [apache/skywalking#3511]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ Y] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I put skywalking-6.4.0 into kubernetes cluster，but agent log show I couldn't connect and send traces to sk-oap-server.
![image](https://user-images.githubusercontent.com/3917749/65422813-15fecb80-de3a-11e9-9b9c-560a9ec999c4.png)

**Comment by hepyu** [comment]
not all traces couldn't be sent to oap server, some traces could be sent sucessfully, and ui will show some information.
![image](https://user-images.githubusercontent.com/3917749/65422961-70982780-de3a-11e9-9e2f-3f50f48f35b4.png)

**Comment by hepyu** [comment]
The exception from sk-oap-server log：
![image](https://user-images.githubusercontent.com/3917749/65423253-28c5d000-de3b-11e9-9be9-f53fba1b06f8.png)

**Comment by wu-sheng** [comment]
If you are in k8s, you need to choose utc 0 in UI.

**Comment by hepyu** [comment]
> If you are in k8s, you need to choose utc 0 in UI.

Is there some doc to show hot wo set utc 0 in sk-ui ?

**Comment by wu-sheng** [comment]
Oh...man.. It is UI. Right bottom of the page.

**Comment by hepyu** [comment]
oh, this is my meaning, I think：
 the timezone of sk-image's dockerfile was specified by utc0, but timezone of apps in our k8s cluster was specifiied by utc8.

So, if I redefine the timezone of dockerfile in sk-image, is this question resovled?

**Comment by hepyu** [comment]
And another question is what about the exception mean in the images above? Are those exceptions was throw when utc error? 

Because I think those exceptions will still exist even if I changed utc of browser.

**Comment by hepyu** [comment]
I have changed timezone of sk-container in k8s, but time of sk-oap-server's log was still utc0 as below：
1：time of sk-oap-server's log, utc0
2：time of sk-oap-container, utc8

btw, after I changed timezone of ui, the problem is still exist, just doubt it need modify the timezone in sk-oap-server&ui's java code.

![image](https://user-images.githubusercontent.com/3917749/65428168-d325ff00-de0b-11e9-9cad-82c758b5514c.png)

**Comment by hepyu** [comment]
and the method I used to modify timezone in container: use host computer's timezone file to replace the original timezone file of image.

![image](https://user-images.githubusercontent.com/3917749/65428693-b76f2880-de0c-11e9-8ca6-71f3d37acc63.png)

**Comment by wu-sheng** [comment]
I recommend you to keep UTC 0 in docker and k8s env. I don't ever change it. So, don't know how to solve this.

> And another question is what about the exception mean in the images above?

The error is nothing special, it is just caused by connection broken.

**Comment by hepyu** [comment]
> I recommend you to keep UTC 0 in docker and k8s env. I don't ever change it. So, don't know how to solve this.
> 
> > And another question is what about the exception mean in the images above?
> 
> The error is nothing special, it is just caused by connection broken.

OK.

If I keep utc0 in sk-container, but keep utc8 in our business-apps-container, is this ok? 
As we know, we should keep utc8 in china's app server, otherwise it will cause lots of problems.

**Comment by hepyu** [comment]
I have sovled this problem, we must keep jvm the same timezone between agent jvm and oap-server/ui jvm.

We need config TZ in the env of container like this:

![image](https://user-images.githubusercontent.com/3917749/65565966-10ad9800-df84-11e9-8977-be46223d2673.png)
