### ISSUE TITLE
"id is not in cache and persistent storage" error

### ISSUE THREAD

**Issue by YoungHu** [apache/skywalking#3512]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.4.0 Linux with JRE 8

- Which company or project?

- What happen?
occur "id is not in cache and persistent storage" error when endpoint_inventory index have more than one record with same sequence.
after check the source code, find the problem at `if (response.getHits().totalHits == 1)`, if want to check whether the result just return one hit or not, we should use `if (response.getHits().getHits().length == 1)`
___
### Requirement or improvement
- check the real hits by use `if (response.getHits().getHits().length == 1)`

**Comment by wu-sheng** [comment]
Read the reply on pull request.
