### ISSUE TITLE
error about oap server configuration by consul

### ISSUE THREAD

**Issue by kongkong56** [apache/skywalking#3521]
![image](https://user-images.githubusercontent.com/3390474/65594370-30b17b80-dfc5-11e9-8059-65b289c44a0c.png)
i wanna know the oap server default service address.
i set the internalcomhost and intercomport.but the oap server cant start ,the error is:
![image](https://user-images.githubusercontent.com/3390474/65594087-a2d59080-dfc4-11e9-9115-7be91ff08c60.png)

**Comment by wu-sheng** [comment]
Have you set consul address? From the log, you didn't, or didn't set it right.

**Comment by kongkong56** [comment]
i config the SW_CLUSTER_CONSUL_HOST

**Comment by wu-sheng** [comment]
Do you check the original yml? Should be ip and port there.

**Comment by kongkong56** [comment]
cluster:
  consul:
    serviceName: ${SW_SERVICE_NAME:"SkyWalking_OAP_Cluster"}
    # Consul cluster nodes, example: 10.0.0.1:8500,10.0.0.2:8500,10.0.0.3:8500
    hostPort: ${SW_CLUSTER_CONSUL_HOST_PORT:consul:8500}


the application.yml like this

**Comment by wu-sheng** [comment]
Then why do you set an inexistence config? It says host_port

**Comment by kongkong56** [comment]
the error is 400,so it can connect to consul ,but the oap server's path has error. so i want to know the oap server default host address

**Comment by wu-sheng** [comment]
> the error is 400,so it can connect to consul ,but the oap server's path has error. so i want to know the oap server default host address

What do you mean oap default host address? We don't have that concept.

**Comment by kongkong56** [comment]
the consul agent address is the oap default host address

**Comment by wu-sheng** [comment]
> the consul agent address is the oap default host address

If you don't know what is InternalComHost/Port, why do you set it up?

**Comment by wu-sheng** [comment]
In default, it is automatically working without setting.

**Comment by tuhao1020** [comment]
I just use the orignal yml and start a consul instance on localhost:8500, but error occurs as @kongkong56  showed above.
