### ISSUE TITLE
can skywalking officially support Flink

### ISSUE THREAD

**Issue by Icefoxes** [apache/skywalking#3522]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
N/A
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Flink is regraded as next generation of streaming processing, however to track a message processed end to end in Flink is not that easy. So I'm wondering if skywalking has a plan to officially support Flink? If not, I will try to implement by myself

**Comment by wu-sheng** [comment]
There is no such thing called official support :) SkyWalking is built on the whole community. If you want more plugins, try to build one and welcome to contribute to the community.

The project relies on every contributor's commits.

**Comment by wu-sheng** [comment]
So, please try it, send the pull request and work with the committer review team to make it included in main repo

**Comment by kezhenxu94** [comment]
@Icefoxes Build one by yourself, and contribute it back to the community, then it becomes **official**
