### ISSUE TITLE
Error executing Ant tasks

### ISSUE THREAD

**Issue by HeMing16** [apache/skywalking#3523]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We don't have ant task. What do you mean?

**Comment by HeMing16** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project apm-agent-core: Error executing Ant tasks: org/apache/tools/ant/launch/Locator: org.apache.tools.ant.launch.Locator -> [Help 1]
当执行./mvnw clean package -DskipTests命令是出现上面的错误，构建方式GitHub

**Comment by wu-sheng** [comment]
This seems like a maven env error. We don't do anything about this.

**Comment by HeMing16** [comment]
git clone skywalking后 切换到v6.4.0，按照文档上的步骤运行至mvnw命令是出现构建错误。

**Comment by wu-sheng** [comment]
If you check our CI, you will notice, we check build and e2e feature tests for every pull request and commit. The master branch is guaranteed working.
