### ISSUE TITLE
Asynchronous use feign, lost link

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#3526]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.4.0
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Asynchronous use feign, lost link
```java
CompletableFuture.supplyAsync(() -> {....feign});
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Are you proposing the async API instrumentation?

**Comment by stalary** [comment]
> Are you proposing the async API instrumentation?

Yes, I have lost links to many asynchronous calls

**Comment by wu-sheng** [comment]
Could you give us a brief about what you are trying to do? This is an async API in JDK level, right?

**Comment by stalary** [comment]
yes, this is an async API in JDK level.
```java
long id;
CompletableFuture<Long> future = CompletableFuture.supplyAsync(() -> {
                return = feignClient.getGroupChatId(courseId, userId);
            });
....
....
if (future != null) {
            id = future.join();
}
```
One of my interfaces needs to invoke multiple services, so I need to make multiple asynchronous requests and finally retrieve the results uniformly

**Comment by wu-sheng** [comment]
Do you want instrument CompletableFuture? And join?

I just have concerns about whether instruments others in other libs. 
But, basically, I am good about this proposal.

**Comment by stalary** [comment]
Executor is used at the bottom. Can we implement it directly?

**Comment by wu-sheng** [comment]
In tech speaking, we could. But we should be carefully, because in my mind, to propagate context across threads, we may cause class type change.

You could try, and let's talk in the pull request.

**Comment by wu-sheng** [comment]
No update in 26 days.
