### ISSUE TITLE
skywalking cannot write ElasticSearch trace data that is not current time

### ISSUE THREAD

**Issue by xsisno1** [apache/skywalking#3529]
Question

When we use ElasticSearch as a store, we find that skywalking adds the current date to the index name when creating the index, but this will cause trace data that is not the current date to fail to write to the index. Here's an example: Set skywalking TTL time =2 days. When skywalking starts, create ElasticSearch index with the name of segment-20190924. Here, all data of 2019-09-24 will be written into this index, but when 2019-09-25, skywalking will fail to write. The reason is that the index name of skywalking when it writes trace data is segment-20190925, which actually does not exist in ElasticSearch. However, at 2019-09-26, after the previously created index named segment-20190924 was deleted by skywalking due to expiration, skywalking will create a new index named segment-20190926. Then 2019-09-26 trace data starts to be written into ElasticSearch. 

How can we solve this problem?

**Comment by wu-sheng** [comment]
It is caused by your Elasticsearch template not created correctly. Maybe upgrade from old version.

**Comment by xsisno1** [comment]
> It is caused by your Elasticsearch template not created correctly. Maybe upgrade from old version.

Elasticsearch template was created by skywalking. Is there an update to the skywalking version or Elasticsearch version?

**Comment by xsisno1** [comment]
@wu-sheng I am now using the skywalking version 6.3.0

**Comment by wu-sheng** [comment]
But old SkyWalking doesn't create the template.

**Comment by xsisno1** [comment]
> But old SkyWalking doesn't create the template.

Here is a piece of code I saw in 6.3.0 to create the index template:

`boolean isAcknowledged = esClient.createTemplate(model.getName(), settings, mapping);`

**Comment by wu-sheng** [comment]
6.3.0 yes, but for older version, it is not. But the template is using the same name as old index name. It could conflict.

**Comment by xsisno1** [comment]
> 6.3.0 yes, but for older version, it is not. But the template is using the same name as old index name. It could conflict.

Ok, I see. Thank you very much for your help
