### ISSUE TITLE
TracingContext : More than 300 spans required to create 

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3530]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

I would like to ask whether the agent lost the span of the entire request when it exceeded the limit 300, or just lost the extra span that  exceed 300 .
oap keeping output cancelled : cancelled before receiving half close

![image](https://user-images.githubusercontent.com/52440226/65668888-277fe780-e075-11e9-9054-e6c9989b6390.png)

**Comment by webb2019** [comment]
ps : I have thonght trace data  and metric data transport in diffrent way , not effect each other .   but  I found  span cant upstream , the metric also cannot display in web UI

**Comment by wu-sheng** [comment]
This shadow dump usually means some plugins having issues. Didn't close span as expected, unless you really have very long trace(unlikely.)

**Comment by webb2019** [comment]
> This shadow dump usually means some plugins having issues. Didn't close span as expected, unless you really have very long trace(unlikely.)

but  instance's CPU and memory metrics are also not displayed  in Web UI .

**Comment by wu-sheng** [comment]
If instance shows up on dashboard selector , then channel is established.

**Comment by jsonpang** [comment]
same happen in my condition  8.8.1 server and agent  springcloud gateway 2.3.12
