### ISSUE TITLE
slack invitation from the readme.md is not available.

### ISSUE THREAD

**Issue by yangyshdan** [apache/skywalking#3532]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
readme.md

- Which company or project?
School research project

- What happen?

The slack invitation link is broken from the readme.md
```
* Join `#skywalking` channel at [Apache Slack](https://join.slack.com/t/the-asf/shared_invite/enQtNDQ3OTEwNzE1MDg5LWY2NjkwMTEzMGI2ZTI1NzUzMDk0MzJmMWM1NWVmODg0MzBjNjAxYzUwMjIwNDI3MjlhZWRjNmNhOTM5NmIxNDk)
```

![image](https://user-images.githubusercontent.com/6780076/65706541-4609d100-e0bd-11e9-93d9-778991fe2ca9.png)

**Comment by wu-sheng** [comment]
Yes. Use this one, would you have interest to update document?

https://join.slack.com/t/the-asf/shared_invite/enQtNzc2ODE3MjI1MDk1LTAyZGJmNTg1NWZhNmVmOWZjMjA2MGUyOGY4MjE5ZGUwOTQxY2Q3MDBmNTM5YTllNGU4M2QyMzQ4M2U4ZjQ5YmY

**Comment by wu-sheng** [comment]
The link could be found here. https://cwiki.apache.org/confluence/display/INFRA/Slack+Guest+Invites
