### ISSUE TITLE
can apm-customize-enhance-plugin  support  class level intecepter rule ?

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3533]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Do This plug-in supports configuring all public methods of intercepting classes through xml configuration files instead of each method interceptor definition ?  I want to trace DAO layer class methods, how to do?

**Comment by wu-sheng** [comment]
The config is ant style, very similar to Spring. Please read the document.
