### ISSUE TITLE
How to configure weblogic's agent？

### ISSUE THREAD

**Issue by AirTrioa** [apache/skywalking#3535]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
Now we have developed a plugin for weblogic. Now we are going to add "- javaagent" to weblogic. Where should we add it?It's similar to what you did on "catalina. sh" when configuring tomcat.

CATALINA_OPTS="$CATALINA_OPTS -javaagent:/path/to/skywalking-agent/skywalking-agent.jar"; export CATALINA_OPTS

**Comment by AirTrioa** [comment]
I have solved this problem.

**Comment by howrain** [comment]
> I have solved this problem.

How to solve the problem

**Comment by lsy1990** [comment]
Thank a lot.
