### ISSUE TITLE
Agent services not detected

### ISSUE THREAD

**Issue by g29times** [apache/skywalking#3539]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
[CN]无法监控到后端服务 [EN] Agent services not detected
Env: ubuntu 18 , 2 Core, 8G Mem
Sky BackEnd ：http://47.244.220.225:8080/
Agent BackEnd(on same server) ：http://47.244.220.225:8013/welcome
(user:'user'/password:'password')
ES V7.2 (on same server) ：http://47.244.220.225:9200/
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.4.0, ubuntu 18.0.4, JRE 11
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Agent services not detected on Sky UI (8080)
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
1 What's the use of port 10800 11800 12800? I don't see any ports listening using 'netstat -anp | grep 12800' after SkyUI started.
2 What do i need to config for agent using spring boot with a "java -jar" fashion?  Do I need to specify like 'java -javaagent:/path-to/skywalking-agent.jar 
     -Dskywalking.agent.service_name=trace-api 
     -Dskywalking.collector.backend_service=localhost:**myAgentPort** 
     -jar xxx.jar'
3 I find 3 config files:  
  /config/application.yml(SW_CORE_REST_PORT:12800 | SW_CORE_GRPC_PORT:11800)   
  /webapp/webapp.yml(listOfServers: 127.0.0.1:12800)  
  /config/agent.config(SW_AGENT_COLLECTOR_BACKEND_SERVICES:127.0.0.1:11800), which I think related with my problem, but my agent's port is 8013.
 When I have several backend(agent) services, need to change all these config files ?

**Comment by kezhenxu94** [comment]
>   1 What's the use of port 10800 11800 12800? I don't see any ports listening using 'netstat -anp | grep 12800' after SkyUI started.

`11800` is for collecting trace data, `12800` is for UI to query, it can't be more obvious that your backend is not started successfully (I don't see any ports listening using 'netstat -anp | grep 12800')

>   2 What do i need to config for agent using spring boot with a "java -jar" fashion?  Do I need to specify like 'java -javaagent:/path-to/skywalking-agent.jar
>   -Dskywalking.agent.service_name=trace-api
>   -Dskywalking.collector.backend_service=localhost:**myAgentPort**
>   -jar xxx.jar'

it's not **myAgentPort**, it should be **yourBackendPort** as the name `skywalking.collector.backend_service` suggests

>   3 I find 3 config files:
>   /config/application.yml(SW_CORE_REST_PORT:12800 | SW_CORE_GRPC_PORT:11800)
>   /webapp/webapp.yml(listOfServers: 127.0.0.1:12800)
>   /config/agent.config(SW_AGENT_COLLECTOR_BACKEND_SERVICES:127.0.0.1:11800), which I think related with my problem, but my agent's port is 8013.

>   When I have several backend(agent) services, need to change all these config files ?

most (if not all) of the configurations can be configured by command line parameters, such as `-DSW_CORE_REST_PORT=xxx`, but according to your questions above, I don't think you have read the documentation first, so **please read the documentation first before asking, otherwise, it would be difficult to communicate**

**Comment by kezhenxu94** [comment]
And, SkyWalking doesn't support ES 7 or 7+ for now, which is documented too
