### ISSUE TITLE
Oap service start failed

### ISSUE THREAD

**Issue by g29times** [apache/skywalking#3540]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Running /bin/startup.sh in default config using H2, log shows started failed, console shows success.
![errorlog.png](http://ww1.sinaimg.cn/large/466e120egy1g7f8mkeh9ej20vw0brmyc.jpg)
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
"org.apache.skywalking.oap.server.library.module.ModuleStartException: ScopeDefine fieldName = All not found."
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dmsolr** [comment]
`startup.sh` prints `success` that means it has launched the processes. 

According to the message, I think you have to initialize.

**Comment by kezhenxu94** [comment]
@g29times if you're using JDK 8+, it's a known issue, because the recommended JDK version for OAP backend is JDK 8

**Comment by kezhenxu94** [comment]
@g29times if you're interested, please take a look at #3541 and see whether it resolves your problem
