### ISSUE TITLE
Is there any benchmark test for skywalking? Like many traces can be collected and how many nodes can be monitored concurrently

### ISSUE THREAD

**Issue by yangyshdan** [apache/skywalking#3542]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Question or discussion

___
### Question
Is there any benchmark test for skywalking? Like many traces can be collected and how many nodes can be monitored concurrently.  With how much Skywalking and ES reources?

**Comment by kezhenxu94** [comment]
@yangyshdan the fact that how many traces can be collected depends on the power of your OAP backend nodes and your ES cluster, refer to our [user cases](https://github.com/apache/skywalking/blob/master/docs/powered-by.md#user-cases) to see how many traces are collected and what's the scale of the backend and ES cluster, pay special attention to the case of Yonghui Supermarket.
