### ISSUE TITLE
Request ignore plugin document

### ISSUE THREAD

**Issue by ywf4026** [apache/skywalking#3543]
- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?

HI, I need a document address about how to use ignore plugin, thanks!

**Comment by kezhenxu94** [comment]
@ywf4026 learn how to search within this repo, you're requesting something that already exists.

https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/agent-optional-plugins/trace-ignore-plugin.md
