### ISSUE TITLE
why maxNonHeap result is negative?

### ISSUE THREAD

**Issue by x22x22** [apache/skywalking#3544]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

![20190928213921](https://user-images.githubusercontent.com/3389949/65817342-86418e80-e238-11e9-8df7-9c25e4ce9147.png)

maxNonHeap will affect the front-end display logic for 'free'. So the backend helps to confirm when maxNonHeap is minus. How should the frontend be displayed when maxNonHeap is minus.

![Snipaste_2019-09-28_21-47-57](https://user-images.githubusercontent.com/3389949/65817448-b2a9da80-e239-11e9-8c40-17276954370f.png)

For the front end pr, please see https://github.com/apache/skywalking-rocketbot-ui/pull/161
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by x22x22** [comment]
I see agent core souse(org.apache.skywalking.apm.agent.core.jvm.memory.MemoryProvider), use MemoryMXBean.getNonHeapMemoryUsage.getMax get maxNonHeap value. 

see jdk document: https://docs.oracle.com/javase/8/docs/api/java/lang/management/MemoryUsage.html

> getMax
> public long getMax()
> Returns the maximum amount of memory in bytes that can be used for memory management. This method returns -1 if the maximum memory size is undefined.
> This amount of memory is not guaranteed to be available for memory management if it is greater than the amount of committed memory. The Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.
> 
> Returns:
> the maximum amount of memory in bytes; -1 if undefined.

**Comment by wu-sheng** [comment]
Let's enhance UI to support this.
