### ISSUE TITLE
Add an introduction to the code style in the contribution guide

### ISSUE THREAD

**Issue by arugal** [apache/skywalking#3547]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
By adding an introduction to the code style in the contribution guide and reducing the amount of time new contributors spend on checkstyle, such as exporting an official idea code style profile, I was able to solve most of the problems with the shortcut keys
在贡献指南中添加对代码风格的介绍，减少新贡献者在checkstyle上所花费的时间，比如导出一个官方的idea code style配置文件，这样我通过快捷键就能解决大部分问题

**Comment by wu-sheng** [comment]
We have it. If you want to update document, I think it is good. But we don't need another duplicated file.

**Comment by liuzhiguo630** [comment]
> We have it. If you want to update document, I think it is good. But we don't need another duplicated file.

Where is it? I have searched all the code and docs.
