### ISSUE TITLE
Dashboard error,vue.runtime.esm.js : cannot read property 'type' of underfined

### ISSUE THREAD

**Issue by DiweiL** [apache/skywalking#3548]
![image](https://user-images.githubusercontent.com/54701106/65830596-62875280-e2e3-11e9-8922-6f43f26ce59c.png)

**Comment by wu-sheng** [comment]
You could try our online demo, if it is ok, then the issue is that, the SkyWalking isn't set up correctly.

**Comment by DiweiL** [comment]
I used docker-compose to build project,the first time OK.When I remove some block in the dashboard and refresh dashboard ,the dashboard was broken. After rebuild , the dashboard is still error.
