### ISSUE TITLE
logback输出不了traceId

### ISSUE THREAD

**Issue by 564907422** [apache/skywalking#3553]
<encoder charset="UTF-8" class="net.logstash.logback.encoder.LogstashEncoder">
    <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider">
    </provider>
</encoder>
json格式化输出日志，打印不了traceId

**Comment by wu-sheng** [comment]
English only. Read document before you submit any issue
