### ISSUE TITLE
about nacos's namespace settings

### ISSUE THREAD

**Issue by hello-zhengzq** [apache/skywalking#3568]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- about nacos config in version6.3, is it support namespace settings？current is 'public' as default.

**Comment by wu-sheng** [comment]
Nacos for what? Cluster management or Dyanmic configuration?

**Comment by wu-sheng** [comment]
I think both of them are not supporting namespace. If you want, the contribution is welcome.

**Comment by hello-zhengzq** [comment]
ok，i know，thx.
