### ISSUE TITLE
High cpu usage and High load  When the oap runs for a while

### ISSUE THREAD

**Issue by dingsongjie** [apache/skywalking#3569]
I run skywalking  with version  6.2.0  in kubernetes cluster

**cup usage from prometheus

![QQ图片20191008095532](https://user-images.githubusercontent.com/10933723/66361557-c8de3600-e9b1-11e9-90da-1056a3ca5fc7.png)

**Comment by wu-sheng** [comment]
Upgrade to latest, it is improved a lot. And check your ElasticSearch performance. It affects a lot.
