### ISSUE TITLE
doubt about trace list

### ISSUE THREAD

**Issue by niyanchun** [apache/skywalking#3572]
For now I see the trace list on UI is segment list, if one trace contains several segments, user will see same trace from different segment in the list. And I see one segment is one document in ES. I wonder is there any way to get a trace list instead of segment list without using ES aggregations. Or is segment list better than the unique trace list for the users(not developers) ?

**Comment by wu-sheng** [comment]
You only could use aggregation query to do that. That is why we don't do that. Coat too much.

**Comment by wu-sheng** [comment]
You only could use aggregation query to do that. That is why we don't do that. Coat too much.
