### ISSUE TITLE
rolling update of the micro service, skywalking has no data

### ISSUE THREAD

**Issue by duhongx** [apache/skywalking#3580]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Deploy skywalking to kubernetes and configure it in the micro service as follows: java -javaagent:/opt/skywalking-agent.jar -Dskywalking.agent.service_name=lc-menzhenjz -Dskywalking.collector.backend_service=oap.skywalking.svc:11800 -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -Xms2048m -Xmx2048m -Xmn256m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC -Dspring.profiles.active=dev -Dlogs.dir=/opt/logs -jar /opt/app.jar. After the rolling update of the micro service, skywalking has no data. How to locate and solve this problem?
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.1.0
Kubernetes 1.13.5
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We need your agent and OAP local (debug level). Otherwise, we can't tell from your single command.
