### ISSUE TITLE
Plugin using byHierarchyMatch

### ISSUE THREAD

**Issue by scolia** [apache/skywalking#3585]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I am try to write a plugin, but it it not recommend to use **byHierarchyMatch**, because it will causes performance issues and concerns. 

I want to using **byHierarchyMatch** to intercept a interface which only has **one** class implement it(the interface is stable, but implementation may change at any time).

In this type, it will also causes performance issues? or it's about the number of implementation classes? 
___

**Comment by wu-sheng** [comment]
If this is your own interface, not JDK's or public used, it is safe.

**Comment by scolia** [comment]
I am find many use cases of **objInst.setSkyWalkingDynamicField()**, What does it mean?

**Comment by wu-sheng** [comment]
> objInst.setSkyWalkingDynamicField(),

Propagate value across objects.

**Comment by scolia** [comment]
In same thread? or in same process?

**Comment by wu-sheng** [comment]
> In same thread? or in same process?

It is an object field, you choose.

**Comment by scolia** [comment]
I am trying to wirte a plugin or mongodb. **mongodb-3.x-plugin** only supported to 3.5.x. 
3.6.x change make some api changes, And 3.7.x or higher also different to 3.6.x.

My plan is supported 3.7.x or higher. but i hava some question:

- it is safely to cast EnhancedInstance to the interface which i intercepted.
- because of cast object, it it difficult to write unit test without create connect of external environment. (create actual object as parameter).

**Comment by scolia** [comment]
In this case, what module name should i use.

**Comment by wu-sheng** [comment]
> it is safely to cast EnhancedInstance to the interface which i intercepted.

We just add a new interface, so it is safe to cast back to original interface or class.

> because of cast object, it it difficult to write unit test without create connect of external environment. (create actual object as parameter).

It isn't hard. EnhancedInstance is just an interface, you could inherit the old class and implement this interface, then you have the parameter. 

Also, take a look at recent PR, https://github.com/apache/skywalking/pull/3575. The plugin test is embedded. But interceptor unit tests are still required.(Instrument don't).

**Comment by wu-sheng** [comment]
> In this case, what module name should i use.

You should be in same module, set `witness class` for existing instrumentation, and add a new one.

**Comment by scolia** [comment]
Can i make some log in plugin?

**Comment by wu-sheng** [comment]
> Can i make some log in plugin?

Depends. The log is not a low payload to agent, network and storage.
