### ISSUE TITLE
Endpoint Topology

### ISSUE THREAD

**Issue by adamswanglin** [apache/skywalking#3588]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Feature or performance improvement

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
![image](https://user-images.githubusercontent.com/26845930/66540208-ad179300-eb5d-11e9-91ce-c935196acb3b.png)
**### In endpoint topology view, it shows the endpoint name but not the service name. Is it possible to show the service name by the way?** 
In the demo,  endpoint names happens to contain service name, so one can tell the request is from Project C. But in my spring cloud projects,  endpoint names is hystrix name which don't contains service name, I cannot tell which service is using this endpoint.

**Comment by JaredTan95** [comment]
You can look into the `Topology` on the top-left is what you need.

**Comment by adamswanglin** [comment]
> You can look into the `Topology` on the top-left is what you need.

That is global service topology. What I want is endpoint topology that can show the endpoint's service name.

**Comment by JaredTan95** [comment]
> You can look into the `Topology` on the top-left is what you need.

Aha, I got your point. We can take it into plan, and looking forward to your contribution.

**Comment by wu-sheng** [comment]
We have endpoint metadata query service, this is just a UI enhancement requirement.

**Comment by JaredTan95** [comment]
> We have endpoint metadata query service, this is just a UI enhancement requirement.

Agree, Use `org.apache.skywalking.oap.query.graphql.resolver.MetadataQuery#getEndpointInfo` method would be more simpler.
