### ISSUE TITLE
Different websites, same paths

### ISSUE THREAD

**Issue by JoaoAlecrim** [apache/skywalking#3594]
___
### Question
Hi,
I don't have an environment to test yet, but it's mandatory for me to have the possibility to trace different websites with same paths. Is it possible to have a vision for each website easily? 

Also, can we group several paths into one "general" path?
Example: _mysite.pt/basket.aspx_ and _mysite.pt/add-to-basket.aspx_ into a single/global path or transaction like **basket_operations**

Thank you very much.

___
### Requirement
Trace same paths over different websites (ex.: mysite.pt, mysite.fr, mysite.com, etc)
Visualize each website individually

**Comment by wu-sheng** [comment]
> Is it possible to have a vision for each website easily?

I want to be clear. APM is monitoring backend system, so website is not our concern. If you set different backend services as different service names, then they are different. 

The path you mentioned is endpoint in skywalking concept, it is a subconcept under every specific service.

> Also, can we group several paths into one "general" path?

Grouping is agent's responsibility in agent case. In your case, should be .net agent's.
