### ISSUE TITLE
Run the SkyAPM-dotnet with docker, restart the container using the agents, oap warn

### ISSUE THREAD

**Issue by DiweiL** [apache/skywalking#3596]
skywalking-oap   | 2019-10-11 10:10:28,745 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister -995101 [grpcServerPool-1-thread-5] WARN  [] - Service instance 3 heartbeat, but not found in storage.
skywalking-oap   | 2019-10-11 10:10:28,751 - org.apache.skywalking.oap.server.receiver.clr.provider.handler.CLRSourceDispatcher -995107 [grpcServerPool-1-thread-3] WARN  [] - Can't find service by service instance id from cache, service instance id is: 3
skywalking-oap   | 2019-10-11 10:10:28,751 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler -995107 [grpcServerPool-1-thread-5] WARN  [] - Can't find service by service instance id from cache, service instance id is: 3, will send a reset command to agent side

**Comment by wu-sheng** [comment]
Means you erased the storage data, but agent didn't reboot.
