### ISSUE TITLE
Deploy backend in kubernetes failed

### ISSUE THREAD

**Issue by heyixiaoran** [apache/skywalking#3598]
___
### Question
OS: win 10
Docker : docker for windows 2.1.0.3
K8s:1.14.6

I‘m a new comer. I try to do as https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-k8s.md. 
I tried helm3/6.3.0 and helm3/6.4.0.  I can't install at  step 5 . 

**1. default** 

D:\GitHubDic\skywalking-kubernetes\helm-chart\helm3\6.3.0>**helm install skywalking skywalking-0.1.0.tgz**
Error: This command needs 1 argument: chart name

D:\GitHubDic\skywalking-kubernetes\helm-chart\helm3\6.4.0>**helm install skywalking skywalking-0.1.1.tgz**
Error: This command needs 1 argument: chart name

**2.add -n**

D:\GitHubDic\skywalking-kubernetes\helm-chart\helm3\6.3.0>**helm install -n skywalking skywalking-0.1.0.tgz**
Error: render error in "skywalking/templates/oap-deployment.yaml": template: skywalking/templates/oap-deployment.yaml:65:10: executing "skywalking/templates/oap-deployment.yaml" at <include "skywalking.containers.wait-for-es" .>: error calling include: template: skywalking/templates/_helpers.tpl:60:63: executing "skywalking.containers.wait-for-es" at <include "call-nested" (list . "elasticsearch" "elasticsearch.client.fullname")>: error calling include: template: skywalking/templates/_helpers.tpl:53:4: executing "call-nested" at <include $template (dict "Chart" (dict "Name" $subchart) "Values" (index $dot.Values $subchart) "Release" $dot.Release "Capabilities" $dot.Capabilities)>: error calling include: template: no template "elasticsearch.client.fullname" associated with template "gotpl"

D:\GitHubDic\skywalking-kubernetes\helm-chart\helm3\6.4.0>**helm install -n skywalking skywalking-0.1.1.tgz**
Error: render error in "skywalking/templates/oap-deployment.yaml": template: skywalking/templates/oap-deployment.yaml:65:10: executing "skywalking/templates/oap-deployment.yaml" at <include "skywalking.containers.wait-for-es" .>: error calling include: template: skywalking/templates/_helpers.tpl:60:63: executing "skywalking.containers.wait-for-es" at <include "call-nested" (list . "elasticsearch" "elasticsearch.client.fullname")>: error calling include: template: skywalking/templates/_helpers.tpl:53:4: executing "call-nested" at <include $template (dict "Chart" (dict "Name" $subchart) "Values" (index $dot.Values $subchart) "Release" $dot.Release "Capabilities" $dot.Capabilities)>: error calling include: template: no template "elasticsearch.client.fullname" associated with template "gotpl"

so what I miss ? not support docker for windows ?

**Comment by wu-sheng** [comment]
I wouldn't expect the windows, but @innerpeacez could you help here?

**Comment by heyixiaoran** [comment]
I saw the error is about es. Should I set es first?  Where is the es docs for install ? I didn't see it.

**Comment by wu-sheng** [comment]
We don't set es, you should.

**Comment by innerpeacez** [comment]
please refer to https://ipzgo.top/2019-07-26-Windows-%E4%BD%BF%E7%94%A8-helm3-%E5%92%8C-kubectl/ , help you to config the helm env. @heyixiaoran Make sure your helm environment is ok.

**Comment by innerpeacez** [comment]
![image](https://user-images.githubusercontent.com/37059529/66631024-f9370600-ec37-11e9-8cc1-870b93d774a1.png)
I tested it without problems.
