### ISSUE TITLE
e2e for JDK 9/11/12

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#3608]
@kezhenxu94 I think you said, JDK 9+(included) should be OK for OAP backend and UI. Let's add them into e2e and make it always available when you upgrade some libs.

**Comment by wu-sheng** [comment]
Add to Group2.

**Comment by kezhenxu94** [comment]
OAP and web app run in the same container now, but the web app doesn't work in JDK9, I'm not sure whether we should also make it work in JDK9 and above (maybe)

**Comment by wu-sheng** [comment]
I think we should, and that should be easy for Spring based, right?
