### ISSUE TITLE
Skywalking is used in conjunction with Fabio. Unable to be a real Topology in skywalking

### ISSUE THREAD

**Issue by SkyChenSky** [apache/skywalking#3609]
Question
Hi!

Skywalking is used in conjunction with fabio.  Unable to be a real Topology in skywalking.

My .Net Core application uses consul to do service discovery.Fabio doing load balancing.All traces of a request can be logged but cannot be connected on skywalking.

I guess whether it is related to fabio forwarding requests?  But I think and sdk again.

I can't find the essential reason when I read a lot of information.  Can you give me some advice?

**Comment by wu-sheng** [comment]
SkyWalking is just opening grpc endpoint to your agent. We don't require any special thing. No matter what you are using, make sure gRPC/HTTP2 is connectable.
