### ISSUE TITLE
 After integrating skywalking, arthas is not working properly.

### ISSUE THREAD

**Issue by nezha** [apache/skywalking#3610]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

After integrating skywalking, arthas is not working properly.

As I want use arthas trace to monitor my rest controller interface, but it prompts an execution error："Error during processing the command: null"

How can i monitor my interface correctly
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I don't know what is the error means. If you have issues about arthas, I think you should ask them.

From my understanding, arthas is designed for process monitoring or debug, it is not for tracing. SkyWalking is designed for the production env monitoring APM system. They are different.
