### ISSUE TITLE
How to manager the oap server?

### ISSUE THREAD

**Issue by liyanyan-dev** [apache/skywalking#3615]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How does skywalking monitor oap services or cluster status? Do you support the Restful API or other types of APIs?For example, monitor the status of the oap service through the Restful API on the web side of my project.

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Are you talking about monitoring oap cluster? We have document about self observability.
