### ISSUE TITLE
Skywalking Agent Logger

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3623]
![image](https://user-images.githubusercontent.com/11767168/66836304-ad67c200-ef93-11e9-91ce-45b361aa3ee5.png)
I think it's better to provide a split configuration by day.

**Comment by wu-sheng** [comment]
What is the point? The agent log is not business-related, and in most production env, it is off or error only(pretty small per day).

**Comment by SevenBlue2018** [comment]
Thank you.

**Comment by SevenBlue2018** [comment]
![image](https://user-images.githubusercontent.com/11767168/66899088-f881e380-f02c-11e9-9bd1-94506d220bf1.png)
This configuration does not work as described.

**Comment by SevenBlue2018** [comment]
logging.max_history_files

**Comment by SevenBlue2018** [comment]
OK, I know this is a feature of the next release.
