### ISSUE TITLE
 How to set the traceId to the current trace context

### ISSUE THREAD

**Issue by shook2012** [apache/skywalking#3625]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- How to set the traceId to the current trace context

I need to trace the whole invoke chain, but after MQ,  the traceId is lost。so i want get the traceId ,and put it into the MQ message body，when the message consume,   i can get the traceId from the message body and put it into the consume trace context.
the question is: I can use the method :TraceContext.traceId() get current traceId，but how can i set the traceId  into current trace context

**Comment by wu-sheng** [comment]
You need to develop a plugin to do that. Your guess is not totally rigtht. There are more inform than trace it. It is the propogatiom context.

Read plugin development document and protocol document.

**Comment by shook2012** [comment]
I got it,thanks~

**Comment by shook2012** [comment]
Maybe I can refer to the rocketmq plugin to implement it

**Comment by shook2012** [comment]
I refer to the rocketmq 3.x plugin and add a plugin for aliyun ons(now renames:rocketmq 消息队列 ). But in my project,Iuse the RocketMQ  ComponentsDefine instead ons。 Does the community need it?
