### ISSUE TITLE
Skywalking Plugins Lettuce

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3626]
![image](https://user-images.githubusercontent.com/11767168/66893240-29a7e700-f020-11e9-962b-add31456957d.png)
Why does "Lettuce/GET/accept" appear alone? I think it should be in the call chain like jedis.

**Comment by wu-sheng** [comment]
Left side is a segment list, not trace list. If it runs in another thread. Then it is right.

**Comment by SevenBlue2018** [comment]
Thank you, let me check it.

**Comment by SevenBlue2018** [comment]
![image](https://user-images.githubusercontent.com/11767168/66913662-b0bc8580-f047-11e9-86c0-902516a4a190.png)
![image](https://user-images.githubusercontent.com/11767168/66913708-c2059200-f047-11e9-9363-10e5abe3888b.png)
I specially printed the log to check this problem.It runs in the same thread.

**Comment by soye-yang** [comment]
> ![image](https://user-images.githubusercontent.com/11767168/66913662-b0bc8580-f047-11e9-86c0-902516a4a190.png) ![image](https://user-images.githubusercontent.com/11767168/66913708-c2059200-f047-11e9-9363-10e5abe3888b.png) I specially printed the log to check this problem.It runs in the same thread.

有找到解决方法吗
