### ISSUE TITLE
aliyun ons plugin

### ISSUE THREAD

**Issue by shook2012** [apache/skywalking#3630]
I refer to the rocketmq 3.x plugin and add a plugin for aliyun ons(now renames:rocketmq 消息队列 ). But in my project,Iuse the RocketMQ  ComponentsDefine instead ons。 Does the community need it? 

_Originally posted by @shook2012 in https://github.com/apache/skywalking/issues/3625#issuecomment-542665129_

**Comment by wu-sheng** [comment]
If you could download ons jar with acceptable license, such as from maven central directly, then we could accept that PR.

**Comment by wu-sheng** [comment]
Another big issue for this plugin is, how do you test it and prove it is working in OSS community. Clearly, we don't have ONS test env. One suggestion, consider to open source and host it in your own repo, we are glad to provide a link in our supported-list doc pointing to 3rd party repo.

**Comment by shook2012** [comment]
It's really a issue。

**Comment by wu-sheng** [comment]
Any update? Are you going to host the plugin repo by yourself?

**Comment by wu-sheng** [comment]
Closing with no response.
