### ISSUE TITLE
VNode again

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3632]
![image](https://user-images.githubusercontent.com/11767168/66925418-eb7de800-f05e-11e9-89be-397f8fd04894.png)
Now I have the same problem in 6.4.0.

**Comment by wu-sheng** [comment]
VNode in your case, most likely your context leaks. VNode is designed for parent segment is missing, but this a segment is reported to backend. I can't tell you why, you need to learn the source codes of lettuce, and locate why the context is not right. Then we could discuss. 

Please don't discuss one thing in different issues, it is meaningless.
