### ISSUE TITLE
Support undertow 1.x 

### ISSUE THREAD

**Issue by langyan1022** [apache/skywalking#3634]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
support undertow 1.x 
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Do you continue to work on this? Starting by moving undertow 2 plugin test?

**Comment by wu-sheng** [comment]
No update. Plugin test immigration has been tracked on #3583. Closing this.
