### ISSUE TITLE
the application blocked when it start

### ISSUE THREAD

**Issue by dasonXu** [apache/skywalking#3636]
we use the version 6.3.0 of skywalking
when our application start with java agent , it will blocked sometimes.
normal start log like this :
![image](https://user-images.githubusercontent.com/34209278/66976369-4e5d9680-f0d4-11e9-8b78-353ce55b2a93.png)

when it blocked:
![image](https://user-images.githubusercontent.com/34209278/66976189-90d2a380-f0d3-11e9-83eb-d885f319bb8c.png)

then we check skywalking log. we find it was loop loading plugin.
![image](https://user-images.githubusercontent.com/34209278/66976265-e909a580-f0d3-11e9-8975-73f3295664cf.png)
![image](https://user-images.githubusercontent.com/34209278/66976293-0179c000-f0d4-11e9-9d67-fc7526e3dd81.png)

can you answer me?

**Comment by wu-sheng** [comment]
I don't why. I think we need your help to locate the issue. You need to debug or add log to find out why.

**Comment by wu-sheng** [comment]
Grpc log is not related. If premain is executed twice or more, there is most likely your jvm facing issue and reboot. Try to find issue at the jvm perspective.

**Comment by wu-sheng** [comment]
No update.
