### ISSUE TITLE
The count of cpm is wrong when apm-spring-annotation-plugin-6.4.0 added

### ISSUE THREAD

**Issue by FredHuan** [apache/skywalking#3637]
Please answer these questions before submitting your issue.

- [ ] Question or discussion

___
### Question
I'm using skywalking 6.4.0, The number of cpm is likely to more then double when the apm-spring-annotation-plugin-6.4.0 is added.  

why?
<img width="214" src="https://user-images.githubusercontent.com/7801790/66977213-87e3d100-f0d7-11e9-884b-ad146a5af14a.png">

**Comment by wu-sheng** [comment]
I don't think that plugin affects this. The annotation plugin generates local spans only, which are not counted in the cpm.

**Comment by FredHuan** [comment]
> I don't think that plugin affects this. The annotation plugin generates local spans only, which are not counted in the cpm.

yes, i also think that plugin cannot affect the cpm. but that's true, i do change nothing except drag this plugin from option-plugins folder to plugins and then deploy my application, the cpm is doubled.
if i remove the plugin, the cpm go back.
it's weird. i can find a reasonable reason for this.
