### ISSUE TITLE
trace ui suggestion

### ISSUE THREAD

**Issue by yogaling** [apache/skywalking#3638]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [+] Requirement
- [+] Feature or performance improvement

### Requirement or improvement
Whether to filter and hide the nodes in the tracking tree according to the conditions in the TraceUI.

**Comment by wu-sheng** [comment]
What is tracking tree? Trace view? If so, are you meaning the node could hide or show including its subtree?
