### ISSUE TITLE
trace for agent.ignore_suffix

### ISSUE THREAD

**Issue by chtxia** [apache/skywalking#3641]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [1 ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
![image](https://user-images.githubusercontent.com/10877932/66993406-1d925700-f0fe-11e9-94b8-3d3300a7bce7.png)

too many trace what I do not care.
I want to ignore this,how could i do?
___
### Bug
- Which version of SkyWalking, OS and JRE?
apache-skywalking-apm-6.4.0

- Which company or project?
tencent

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Jedis is a span, not a trace. If you don't want this, remove jedis plugin. Ignore plugin including suffix ignore mechanism are for ignore the whole tracre segment.

**Comment by chtxia** [comment]
agent.ignore_suffix=${SW_AGENT_IGNORE_SUFFIX:.jpg,.jpeg,.js,.css,.png,.bmp,.gif,.ico,.mp3,.mp4,.html,.svg,Jedis,jedis}

![image](https://user-images.githubusercontent.com/10877932/66996660-b5467400-f103-11e9-981a-f8d95a6f2e87.png)

but it not work，help me pls

**Comment by chtxia** [comment]
agent.ignore_suffix=${SW_AGENT_IGNORE_SUFFIX:.jpg,.jpeg,.js,.css,.png,.bmp,.gif,.ico,.mp3,.mp4,.html,.svg,Jedis,jedis}

![image](https://user-images.githubusercontent.com/10877932/66996819-f3dc2e80-f103-11e9-902c-ffe2157dd903.png)

it not work, help me pls...

**Comment by wu-sheng** [comment]
Do you read my reply? And what is suffix? Have you read document?
