### ISSUE TITLE
Mr. Wu ,I want to know the Java classes and methods that handle SW6.

### ISSUE THREAD

**Issue by AirTrioa** [apache/skywalking#3664]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- What do you want to know?

Skywalking uses SW6 to concatenate each segment. I want to know where is the way skywalking deals with SW6?

I hope you can tell me in your busy schedule. Thank you very much.

**Comment by wu-sheng** [comment]
The project is maintained by many people, I am just having more time to respond.

Are you asking for these protocols?
https://github.com/apache/skywalking/blob/master/docs/en/protocols/README.md#language-based-native-agent-protocol

What do you mean class and method?
