### ISSUE TITLE
Add   register worker metrics

### ISSUE THREAD

**Issue by dominicqi** [apache/skywalking#3671]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [+] Question or discussion
- [ ] Bug
- [ ] Requirement
- [+] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
 Could i add a register worker latency metrics ?
  Here is the screenshot in Grafana.
![image](https://user-images.githubusercontent.com/12235378/67191670-98bc7b80-f424-11e9-962c-e45a19fa40c2.png)

**Comment by wu-sheng** [comment]
Make sense to me, if you want, please submit the pull request.

**Comment by JaredTan95** [comment]
added.
