### ISSUE TITLE
Alarm Message

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3672]
![image](https://user-images.githubusercontent.com/11767168/67193271-9e679080-f427-11e9-8e8b-d66d406ffa26.png)
Why is the scopeId value of type int, not string? If the value is "Service", I think it will be easier to understand.

**Comment by wu-sheng** [comment]
We are welcome your pull request, it could be added.

**Comment by arugal** [comment]
https://github.com/apache/skywalking/blob/6657e6ec1702cea093cc29f93b5fdda4efbd59a2/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/alarm/AlarmMessage.java#L28-L44 here?

**Comment by wu-sheng** [comment]
Added.
