### ISSUE TITLE
abount endpoint '{POST}/abc' and  '/abc'

### ISSUE THREAD

**Issue by yh1968684316** [apache/skywalking#3675]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- I find '{POST}/login' and  '/login' in my service's endpoint  list ; 
The interface of get mode is the same and this phenomenon exists at each endpoint . 
And I want to know why it happened . 
 The framework of my project is spring-boot2.0.9 . The service registry is Eureka.

**Comment by wu-sheng** [comment]
Which components do these two spans say?

**Comment by githuyong** [comment]
I get this case, I don't know why? @wu-sheng ,skywalking7.0 ,springboot1.5.8.

**Comment by BFergerson** [comment]
Duplicates #4907. Will close that ticket with fix
