### ISSUE TITLE
Some endpoint not belong to any service

### ISSUE THREAD

**Issue by jadezhong** [apache/skywalking#3687]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Search endpoints of service using searchEndpoint(), found out some endpoints that should belong to service not exists in search result, such as Hystrix/.../Execution or RabbitMQ/Topic/.../Producer, but in trace UI these endpoints which should belong to service is colored in its service's color.
Those "MISSING" endpoints can also been seen in result of getEndpointTopology();
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 6.4.0, CentOS 7.x, JDK 1.8, 8C CPU, 16G RAM

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Screenshot? All endpoints belong to service for sure.

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67363085-27ed9e80-f59f-11e9-9fe8-28e29f59d480.png)
"Hystrix/..." in red block is blong to rgb(65, 125, 224) color,
![image](https://user-images.githubusercontent.com/49858897/67363237-80bd3700-f59f-11e9-98f4-e14a5adc2555.png)
which is the color of service "...-api", so it should belong to this service,
![image](https://user-images.githubusercontent.com/49858897/67363558-35575880-f5a0-11e9-89ad-a9ce53274a38.png)
but it not in result of searchEndpoint().

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67363836-c6c6ca80-f5a0-11e9-886b-9f60f42666d5.png)

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67363945-17d6be80-f5a1-11e9-8d5e-541455a4365c.png)

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67364019-494f8a00-f5a1-11e9-9320-433804ca9ed0.png)

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67364112-756b0b00-f5a1-11e9-8047-b184e6f25bf1.png)

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67364188-a3504f80-f5a1-11e9-89e4-dccdd74ee607.png)

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67364269-cbd84980-f5a1-11e9-8fc5-ae846fe1defe.png)

**Comment by jadezhong** [comment]
"Hystrix/..." in red block is blong to rgb(65, 125, 224) color, which is the color of service "...-api", so it should belong to this service, but it not in result of searchEndpoint().
This will cause we can't BIND all endpoints with their services when we use getEndpointTopology() result, to make a map of service relationship and their endpoints relationship

**Comment by jadezhong** [comment]
Sorry to hide some information for security reasons.

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67372064-e6192400-f5af-11e9-9d92-b4e076bea4e7.png)

**Comment by jadezhong** [comment]
not a problem, those MISSING endpoints were registed long time age, thats why I can't get them within 1 day range using searchEndpoint();
pls close this issue, thx.

**Comment by jadezhong** [comment]
in index skywalking_endpoint_inventory, i can found one of the MISSING endpoint, it belongs to serviceid 55 which is the correct service shows in trace UI, but when it can't be found in the result when i using searchEndpoint(), i check the register_time is 2019/10/8 17:50:9, is it because it registered too long ago?

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67376798-4e1f3880-f5b7-11e9-81b7-ff47638de7c9.png)

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67379380-65602500-f5bb-11e9-96e0-47ad848b6f64.png)

**Comment by jadezhong** [comment]
![image](https://user-images.githubusercontent.com/49858897/67379412-74df6e00-f5bb-11e9-9ddc-9c9b1bd51c14.png)

**Comment by jadezhong** [comment]
why only search SERVER for detect_point?

**Comment by wu-sheng** [comment]
Because only that is for metrics. Local and Client spans are only for tracing. You could simulate what will happen if you calculate the metrics based on all these.

**Comment by jadezhong** [comment]
i want to draw a map, explaining relationship between service<->service relationship, and endpoint<->endpoint call relationship, and with endpoint<->service heiracry, so i need methods to search all services, then to search all endpoints by each service, then to search endpoint topology by each endpoint.
so i need a method such as searchEndpoint(serviceId, limit...) to search by serviceId and time period, which cannot only contains endpoint with SERVER dectec_point in the result.

**Comment by wu-sheng** [comment]
The service, endpoint, and instance dependency are already in the core. We have topology for service and endpoint in the UI already.

If you thought you need to show other relationships, then, it is not the same as project wanted. As that, it becomes your personal requirement, not projects.

**Comment by jadezhong** [comment]
yes i know, endpoint topology is what i started, it tell me endpoint<->endpoint relationship, and i try to bind each endpoint with their service, but found out most endpoints(registered long time ago) cannot find service it belongs to.
i know every endpoint should have their own service, now i know this issue is because searchEndpoint() make some filters(SERVER detect_point, limit from total result), from the method name searchEndpoint() i think it should give me everything i need, isn't it? or maybe add a method that can query all endpoints page by page with serviceId should do it?

**Comment by jadezhong** [comment]
`    public List<Endpoint> searchEndpointByTime(final Duration duration, final String keyword, final String serviceId,
        final int limit) throws IOException, ParseException {
        long startTimestamp = DurationUtils.INSTANCE.startTimeToTimestamp(duration.getStep(), duration.getStart());
        long endTimestamp = DurationUtils.INSTANCE.endTimeToTimestamp(duration.getStep(), duration.getEnd());
        return getMetadataQueryService().searchEndpoint(startTimestamp, endTimestamp, keyword, serviceId, limit);
    }`

**Comment by jadezhong** [comment]
for example, like above.

**Comment by jadezhong** [comment]
or merge above code into searchEndpoint(), and make SERVER detect_point as arguments, to meet both needs.

**Comment by wu-sheng** [comment]
There is no endpoint by time, it doesn't have the heartbeat. You need to learn deeper.

**Comment by jadezhong** [comment]
the code already support both register time and heartbeat time, i just add a new searchEndpoint and convet duration argument into start time and end time, of cause the underlying method should also be added to accept the time arguments, just like the way seachAllService did.

**Comment by jadezhong** [comment]
I just wander why not allow to expose data that already exists in storage by hard-code filters in the common method such as searchEndpoint(), shouldn’t it be much common to pass filter conditions into the method?

**Comment by jadezhong** [comment]
I set up a schedule and set a baseline of when the skywalking online in the our environment, and it will search endpoint within a scrolling time period to help building up a schematic of our system
