### ISSUE TITLE
spring cloud alibaba dubbo not recognized 

### ISSUE THREAD

**Issue by khiker007** [apache/skywalking#3694]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [x] Requirement
- [x] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?

SkyWalking-6.4.0

- What happen?

We use spring-cloud-alibaba，and service is dubbo，regist is nacos,The service can be traced, but the type of service is not recognized

![image](https://user-images.githubusercontent.com/10723358/67390077-75353480-f5ce-11e9-82ff-57f0d724b6e2.png)

**Comment by wu-sheng** [comment]
We are detecting execution libs. Spring alibaba is just a framework. We don't detect that.
