### ISSUE TITLE
java agent drop segment data

### ISSUE THREAD

**Issue by niyanchun** [apache/skywalking#3699]
Continue the #3692 issue, as @wu-sheng  reply,   the oap server and storage(we use es)  may be the bottleneck which case agent drop segment data. But in our test the oap server has a low cpu(below 30%), memory and disk are also sufficient. ES is also in low load. Is there any other approach to judge if oap server is the bottleneck? Thanks in advance.

**Comment by wu-sheng** [comment]
Why open a new one? If you are saying that, everything is sufficient, I can't tell more.

**Comment by niyanchun** [comment]
First, Sorry for  opening a new one. I ever created an issue,  I continued asking question after it was closed, but got no more reply any more. So I thought the closed issue would not be handled any more. As well as other github projects will only close the issue after the issue is resolved or get no more response from the author for a lone while.

Second, I am also feel strange that oap and es is not in high load( for the cpu, mem, disk are all in low usage) status but the agent drop data for buffer is full, and that's why I create an issue here. I wonder if the oap is the bottleneck, will it have a high cpu usage? Or other things that I can definitely know the oap is in high load status?

**Comment by niyanchun** [comment]
we change storage from es to h2( so the storage should not bottleneck) , agent still drop data, OAP load is as below:

![image](https://user-images.githubusercontent.com/5145759/67468555-4924bc80-f67d-11e9-92b3-653978432c1a.png)


![image](https://user-images.githubusercontent.com/5145759/67468525-3a3e0a00-f67d-11e9-8829-b0452b77fde1.png)

It seems consumer theads are idle in most time.

**Comment by wu-sheng** [comment]
H2 is only for demo only. There is the OAP backend observability by using Prometheus and Grafana. It is in the documentation, please read. 

For the CPU usage, I am not sure. I am not working on this part yet.
