### ISSUE TITLE
Skywalking UI Instance Duplicate

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#3703]
![image](https://user-images.githubusercontent.com/11767168/67470224-fdbfdd80-f67f-11e9-9bd7-fb4ddf5f3975.png)
I saw the instance name repeated here.

**Comment by SevenBlue2018** [comment]
![image](https://user-images.githubusercontent.com/11767168/67472572-e08d0e00-f683-11e9-8b0a-9b69274372de.png)
It's undefined when I copy it.

**Comment by wu-sheng** [comment]
I hope you could debug codes rather just copy screenshots here. Bug fix by yourselves and push upstream is recommended actually. This should be easy to find why

**Comment by wu-sheng** [comment]
And you are adding different things in one issue, hard to track.

@x22x22 could you take a look at the second one?

**Comment by wu-sheng** [comment]
@JaredTan95 do you have clue about one?

@SevenBlue2018 We need you take part in as a developer too.

**Comment by SevenBlue2018** [comment]
ok, thank you.I have a try

**Comment by wu-sheng** [comment]
Second bug fixed.

**Comment by it-ll** [comment]
How to deal with instance Duplicate
