### ISSUE TITLE
[istio-ci] Deploy istio and OAP

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#3712]
## Step 1 Deploy istio
Refer to https://istio.io/docs/setup/install/helm/ to install istio. There're some notices that should be followed.
1. Using the `helm template`, we should store it in CI for debugging.
1. After apply YAML, we should use `kubectl wait` to wait for all of the pods in istio-system up.

## Step2 Deploy OAP and UI
1. Add `https://github.com/apache/skywalking/blob/master/docs/en/setup/istio/yaml/skywalkingadapter.yml` in the helm template folder. And parameterize some items, for example, namespace, OAP endpoint, etc...
1. generate template file with `helm template`, then apply it to `istio-system`.
1. issue `kubectl apply -f https://raw.githubusercontent.com/istio/istio/1.3.3/mixer/template/metric/template.yaml` to apply mixer metric template, which is the bridge between mixer and OAP.
1. wait for all pods up.

## Step3 Deploy Booinfo sample application

Deploy bookinfo according to https://istio.io/docs/examples/bookinfo/. 

Then access productpage several times, and you will get metrics from UI.

@innerpeacez you should create some scripts to automate these steps.

**Comment by innerpeacez** [comment]
Ok, I know what you means, I will start to do it.

**Comment by wu-sheng** [comment]
Where should we deploy this?

**Comment by hanahmily** [comment]
In a short short term, it’s desiged to deploy to minikube in CI. In a long term, any user
 can deploy to any kubernetes cluster they want with those scripts.

Hongtao Gao

Apache SkyWalking && Apache ShardingSphere
Twitter, @hanahmily

**Comment by wu-sheng** [comment]
Make sense to me.  When you need a jenkins trigger, let me known.
