### ISSUE TITLE
cannot get the TID using the ConsoleAppender +LogstashEncoder+TradeIdJsonProvider

### ISSUE THREAD

**Issue by PhenJuly** [apache/skywalking#3713]
Cannot get the TID using the ConsoleAppender +LogstashEncoder+TradeIdJsonProvider in logback.xml, whether it only supports LogstashTcpStocketAppender, and does not support ConsoleAppender.

**Comment by wu-sheng** [comment]
You could contribute this to the project by yourself. It is not hard.

**Comment by wu-sheng** [comment]
Fixed in #5031
