### ISSUE TITLE
Feature request: telegraf output plugin for skywalking

### ISSUE THREAD

**Issue by rshriram** [apache/skywalking#3731]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

It would be good to have an output plugin in telegraf https://github.com/influxdata/telegraf for Skywalking. This will enable users to scrape data from wide variety of sources and push them into skywalking, and other output sinks simultaneously.

**Comment by wu-sheng** [comment]
SkyWalking's receiver is hard coded for format transfer today. Unless we have an explicit transfer description, it is hard to do this plugin, no matter at telegraf output or SkyWalking receiver.

**Comment by dagmom** [comment]
Such as  cpu , mem ,disk telegraf output plugin , metrics unique key  is host .
If developed telegraf format receiver, how to relate to sw serviceInstanceId ?

**Comment by wu-sheng** [comment]
@dagmom You could check how we make Prometheus fetcher works, and in the master(8.1), we also support OC(OpenCensus/OpenTelemetry) proxy forward format too.

If you want to do this, consider using a new receiver to do the data model convert.

**Comment by wu-sheng** [comment]
> Such as cpu , mem ,disk telegraf output plugin , metrics unique key is host .
If developed telegraf format receiver, how to relate to sw serviceInstanceId ?

@dagmom If you have interests to do, we have Prometheus fetcher and OpenCensus/OpenTelemetry receiver already. You could learn more from there, including the instance id issue.

**Comment by wu-sheng** [comment]
Prometheus protocol is supported. Telegraf isn't yet. If anyone wants to contribute this, please submit a new issue or pull request.
