### ISSUE TITLE
There is no Service in skywalking

### ISSUE THREAD

**Issue by stone-wlg** [apache/skywalking#3734]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
#### I setup app with skywalking agent using docker.
Scenario 1:
App on server A. Skywalking oap and ui on Server A. This is ok
Scenario 2:
App on server A, Skywalking oap and ui on Server B. This is failed
Scenario 3:
App on server A, Skywalking oap and ui using docker on Server A. This is failed
Scenario 4:
App on Server A, Skywalking oap and ui using docker on Server B. This is failed.
Scenario 2 ~ 4 failed result as below:
![image](https://user-images.githubusercontent.com/2622666/67741644-ce7ce800-fa54-11e9-9caf-d024fcb332f3.png)
### App skywalking agent config:
SW_AGENT_NAME=test
SW_AGENT_COLLECTOR_BACKEND_SERVICES=B:11800
export JAVA_OPTS="$JAVA_OPTS -javaagent:/skywalking-agent/skywalking-agent.jar"

### Skywalking docker compose file:
https://github.com/apache/skywalking-docker/blob/master/6/6.4/compose/docker-compose.yml

**Comment by meteorice** [comment]
the same to you。

i try h2 it's ok，but elasticsearch（6.8.1 and6.8.4 )。 

why?  trace is fine;
![image](https://user-images.githubusercontent.com/11306060/67746117-c32fb980-fa60-11e9-8abc-806c0ebf4435.png)
![image](https://user-images.githubusercontent.com/11306060/67746142-d0e53f00-fa60-11e9-8f01-52b27a3a4d23.png)

**Comment by stone-wlg** [comment]
> the same to you。
> 
> i try h2 it's ok，but elasticsearch（6.8.1 and6.8.4 )。
> 
> why? trace is fine;
> ![image](https://user-images.githubusercontent.com/11306060/67746117-c32fb980-fa60-11e9-8abc-806c0ebf4435.png)
> ![image](https://user-images.githubusercontent.com/11306060/67746142-d0e53f00-fa60-11e9-8f01-52b27a3a4d23.png)

not only elasticsearch, but also h2 to me.
you can try the scenarios as i comment before.

**Comment by meteorice** [comment]
i download Binary Distribution ,that h2 is ok.

**Comment by wu-sheng** [comment]
It is only simple time or time zone are not sync in different VMs. You don't set the time right.
