### ISSUE TITLE
jvm metrics display error

### ISSUE THREAD

**Issue by cyejing** [apache/skywalking#3735]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
instance jvm metrics have error。 have negative number

实例的jvm信息显示错误，有负数
![image](https://user-images.githubusercontent.com/6317049/67748281-82866f00-fa65-11e9-8b6f-530b3b292fa6.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.4.0 skywalking
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Fixed in the master.
