### ISSUE TITLE
How much jvm heap memory will be consumed by Agent

### ISSUE THREAD

**Issue by HackerRookie** [apache/skywalking#3737]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How much jvm heap memory will be consumed by Agent？

The class "org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus", loaded by "sun.misc.Launcher$AppClassLoader @ 0x7b0004ab0", occupies 128,490,120 (65.46%) bytes. The memory is accumulated in one instance of "java.util.concurrent.ConcurrentHashMap$Node[]" loaded by "<system class loader>".

Keywords
java.util.concurrent.ConcurrentHashMap$Node[]
org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus
sun.misc.Launcher$AppClassLoader @ 0x7b0004ab0
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you want to say? I am confusing.

**Comment by wu-sheng** [comment]
Agent is generating new class to do instrumentation, of course it costs heap size. So?

**Comment by mytimes** [comment]
@HackerRookie i meet the problem，do you solved?
