### ISSUE TITLE
is there any plan to upgrade es5 to es6 or es7 

### ISSUE THREAD

**Issue by xzwilliam** [apache/skywalking#3740]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [√] Feature or performance improvement

___
is there any plan to upgrade es5 to es6 or es7

**Comment by wu-sheng** [comment]
Do you even read doc? Es6 is supported long time ago.
