### ISSUE TITLE
how to get responsetime/throughput metrics of Redis/MQ  by /graphql ?

### ISSUE THREAD

**Issue by wurenny** [apache/skywalking#3746]
- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- i want to get some metrics for cache/mq component by access /graphql, like databaseResponseTime/databaseThroughput in database's dashboard.
how should i do ?
@zhaoyuguang @ascrutae thanks.

**Comment by wu-sheng** [comment]
You should read GraphQL, codes and query procotol. They are there already.

**Comment by wurenny** [comment]
> You should read GraphQL, codes and query procotol. They are there already.

@wu-sheng should i read https://github.com/apache/skywalking-query-protocol ?

**Comment by wu-sheng** [comment]
Including this, and codes. As you want to change, not just using.

**Comment by wurenny** [comment]
@wu-sheng emm, code is hard to me, i'm not developer 😃 . 
And i can't find any query type about cache or mq, are you sure it's been already implemented?

**Comment by wu-sheng** [comment]
For cache and MQ, NO. So I asked you to read codes, how database did. If you are not a developer, I assume it is impossible.

**Comment by wurenny** [comment]
ok, maybe i need to ask my colleague for some help , but anyway, thank you. 🍎
