### ISSUE TITLE
VM/Host metrics collector

### ISSUE THREAD

**Issue by viswaramamoorthy** [apache/skywalking#3749]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is there an agent available to gather VM/Host stats like top processes, host memory, paging stats etc ? I could not find this information in documentation
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No. That is out of APM scope.

**Comment by viswaramamoorthy** [comment]
Thanks for your response. It may not strictly fall into APM territory. But it is related when deploying in cloud.  There are APMs cover this feature as well.

**Comment by wu-sheng** [comment]
Yes, that is APM vendor product. It is provided by many projects. We don't need to build again.
