### ISSUE TITLE
RabbitMQ consumer duration is reported incorrectly

### ISSUE THREAD

**Issue by viswaramamoorthy** [apache/skywalking#3753]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking v6.4.0
OS: Ubuntu
JRE: OpenJDK 8.0

- Which company or project?
N/A

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

RabbitMQ consumer duration is reported incorrectly due to instrumenting com.rabbitmq.client.impl.ConsumerDispatcher.handleDelivery method in  class org.apache.skywalking.apm.plugin.rabbitmq.define.RabbitMQConsumerInstrumentation. Because ConsumerDispatcher.handleDelivery spins up a thread to deliver the message to registered consumer class. Instead all implementations of com.rabbitmq.client.Consumer could be instrumented to get accurate consumer duration times

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@ascrutae please confirm.

@viswaramamoorthy do you intend to submit a pull request to fix this?

**Comment by viswaramamoorthy** [comment]
will send a PR

**Comment by wu-sheng** [comment]
Read the things happen at #3583, I will recommend you to move the RabbitMQ test case into the main repo. The latest document for new test framework is not ready, but the new one is very similar the to  old one, check the old test repo and document
- repo, https://github.com/SkyAPMTest/agent-auto-integration-testcases/tree/master/rabbitmq-scenario
- document, https://github.com/SkyAPMTest/agent-auto-integration-testcases#document

**Comment by wu-sheng** [comment]
FYI @dmsolr

**Comment by viswaramamoorthy** [comment]
@wu-sheng 
I have raised PR https://github.com/apache/skywalking/pull/3761
Note that I have included migrating legacy RabbitMQ tests as well.

**Comment by wu-sheng** [comment]
@viswaramamoorthy The PR is under review, please follow the comments there.
