### ISSUE TITLE
oap.log output " Received DATA frame for an unknown stream 787491" warining

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3754]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 I found that the oap.log file frequently outputs logs. What causes this? 
![image](https://user-images.githubusercontent.com/52440226/67912864-31da5780-fbc6-11e9-8067-cdfcb4b2050e.png)

**Comment by wu-sheng** [comment]
Network issue? This seems a grpc internal issue.
