### ISSUE TITLE
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled

### ISSUE THREAD

**Issue by wangao029** [apache/skywalking#3755]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
    - version 6.4.0;
    - windows server 2012;
    - java 8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/3365461/67914263-94cded80-fbca-11e9-8292-8dd209fb73d3.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Meaning, the peer has disconnected. May be caused by timeout, client shutdown, etc.

**Comment by EtachGu** [comment]
after delete trace-buffer and mesh-buffer, it works.
