### ISSUE TITLE
Can support  the "JVM instance metrics"  to  alarm  now?

### ISSUE THREAD

**Issue by xianshun163** [apache/skywalking#3757]
right now metrics from Service, Service Instance, Endpoint scopes could be used in Alarm,

I  also  want to make alarm  with  the  "JVM instance metrics".  If that  any  plan  in further versions?

![image](https://user-images.githubusercontent.com/32457473/67916774-c5fdec00-fbd1-11e9-84b9-0addabd680b6.png)

**Comment by wu-sheng** [comment]
JVM is also an instance level metrics. Check the `catalog` definition.

```java
@ScopeDeclaration(id = SERVICE_INSTANCE_JVM_MEMORY, name = "ServiceInstanceJVMMemory", catalog = SERVICE_INSTANCE_CATALOG_NAME)
@ScopeDefaultColumn.VirtualColumnDefinition(fieldName = "entityId", columnName = "entity_id", isID = true, type = String.class)
public class ServiceInstanceJVMMemory extends Source {
```
