### ISSUE TITLE
[Design] SkyWalking CLI

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#3758]
SkyWalking CLI proposal has been posted in mail list
- https://lists.apache.org/thread.html/b33c73f430aff34e8f0303dcd854ef7586835f9c0c43cd0da64c212d@%3Cdev.skywalking.apache.org%3E

We have gotten supports from 3 committers and one contributor. So I assume this should be ready to go. The following steps are

1. Create `skywalking-cli` repo
1. Create an issue at GitHub main repo to track progress
1. I draft a design proposal
1. Review, change the design and finalize it
1. One takes the lead of development, and we separate the task to different people
1. Set up the project, CI, documentation, etc.
1. Because to go through license, dependency and run a release.

**Comment by zzrdark** [comment]
我想加入开发

**Comment by zzrdark** [comment]
May I take part in?

**Comment by wu-sheng** [comment]
Repo created, https://github.com/apache/skywalking-cli
All committers should have access rights soon automatically.

**Comment by wu-sheng** [comment]
Design doc is here, https://docs.google.com/document/d/1WBnRNF0ABxaSdBZo6Gv2hMzCQzj04YAePUdOyLWHWew/edit#

**Comment by wu-sheng** [comment]
@heyanlong @kezhenxu94 @dmsolr @arugal @hanahmily @innerpeacez Please review the design doc.

**Comment by innerpeacez** [comment]
It is recommended to replace `sw-cli` with `swctl` or `skywalkingctl`

**Comment by wu-sheng** [comment]
> It is recommended to replace sw-cli with swctl or skywalkingctl

Left the recommendation or comment to Google doc. It is a better place to share with other reviewers. I will copy the whole final version back to here and mail list.

**Comment by innerpeacez** [comment]
> Left the recommendation or comment to Google doc. It is a better place to share with other reviewers. I will copy the whole final version back to here and mail list.

Some comments has been added to the document

**Comment by wu-sheng** [comment]
I just updated the design based on @innerpeacez 's review. Subcommands added to make the parameters more clear and easier to extend. Further review is welcome to everyone.

**Comment by wu-sheng** [comment]
After metrics PR, what are left? Endpoint subcommand? Anyone could finish this in this week?

Then we may could prepare the 0.1.0 CLI release next week by a new release manager. In this process, we are not facing network issues, so don't count on me to do so.

**Comment by wu-sheng** [comment]
Metrics linear query PR is here. https://github.com/apache/skywalking-cli/pull/14

**Comment by kezhenxu94** [comment]
I’d like to take the role of CLI release manager, after a failed attempt of the main repo

**Comment by kezhenxu94** [comment]
The design has settled down now and this  can be closed
