### ISSUE TITLE
elasticsearch 7. X is not yet supported in the latest version

### ISSUE THREAD

**Issue by Maijh97** [apache/skywalking#3766]
elasticsearch 7. X is not yet supported in the latest version

**Comment by wu-sheng** [comment]
ES 6 is recommendation storage today.

**Comment by Maijh97** [comment]
Thank you for your reply. What is the current way to support elastic search 7. X，Production environment currently working es 7

**Comment by wu-sheng** [comment]
You need to implement storage by yourself.

**Comment by Maijh97** [comment]
at present, is there any other way to choose besides supporting es and H2 data storage?

**Comment by wu-sheng** [comment]
MySQL or TiDB.
