### ISSUE TITLE
org.apache.skywalking.oap.server.configuration.service.*

### ISSUE THREAD

**Issue by IndiraFinish** [apache/skywalking#3767]
i build with source code, but hint that there is no package `import org.apache.skywalking.oap.server.configuration.service.*;`

![image](https://user-images.githubusercontent.com/20626345/68018068-2a54a480-fcd3-11e9-9589-03f4ca70dc67.png)

**Comment by wu-sheng** [comment]
Read the compiling doc. It is there.
