### ISSUE TITLE
[ISTIO-CI] Add OAP+Istio(mixer) to CI pipeline

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#3771]
Now we build CI workflow for istio mixer and skywalking based on #3718 

## Requirement

Get all dependencies, including `kubectl`, `helm`, and `minikube` . (assigned to @hanahmily )

## Steps

the following steps are some of the critical points for the whole works. 

 1. build a OAP image locally, pick up commit id as the tag. 
 1. bootstrap minikube up, make it access local images. (assigned to @hanahmily )
 1. deploy istio, OAP, and ES. Enable skywalking adapter of the mixer. 
 1. deploy bookings demo. 
 1. access demo until we get some metrics from OAP. 
 1. if there are some errors.  print pods status, pods log and some necessary debug details to STD
 1. stop minikube and clear it. (assigned to @hanahmily )
 1. clear docker images.

@wu-sheng @innerpeacez @kezhenxu94 
Some issues should be confirmed before we start to do it. 
 1. ES will deploy several pods with the current Helm chart. That's not accepted in CI. So I suggest creating a new ES template which is only enabled in CI. 
 1. we don't deploy UI in CI. So we should write some scripts to fetch data through GraphQL.

**Comment by wu-sheng** [comment]
> build a OAP image locally, pick up commit id as the tag.

Pick up jenkins job id should make more sense.

> ES will deploy several pods with the current Helm chart. That's not accepted in CI. So I suggest creating a new ES template which is only enabled in CI.

Agree, we should reduce the unnecessary resource cost.

> we don't deploy UI in CI. So we should write some scripts to fetch data through GraphQL.

Recent e2e has coding to verify by GraphQL, please read codes there.

**Comment by innerpeacez** [comment]
Where is the minikube deployed?

**Comment by wu-sheng** [comment]
> Where is the minikube deployed?

Should be installed by scripts locally on VM.

**Comment by hanahmily** [comment]
Yes. I will fetch a appropriate minikube version, then set some system
settings to bootstrap it.

**Comment by wu-sheng** [comment]
Any update about this? @innerpeacez Any block?

**Comment by innerpeacez** [comment]
Thinking .  I have some issues.

1. How should the new ES templete  exist?
2.CI pipeline refering to Jenkins pipeline?

@hanahmily @wu-sheng

**Comment by wu-sheng** [comment]
@innerpeacez @hanahmily Do we have any update about this?

**Comment by wu-sheng** [comment]
Istio mixer is not recommended anymore.
