### ISSUE TITLE
Provide plugin for ShardingSphere 4.0.0-RC3

### ISSUE THREAD

**Issue by tuohai666** [apache/skywalking#3777]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

Provide plugin for ShardingSphere 4.0.0-RC3 of which the API is different from RC1 or RC2.

**Comment by wu-sheng** [comment]
You should have witness classes for different version libs.

Also, shardingsphere test case should be moved. @tristaZero are you going to do this?

**Comment by tuohai666** [comment]
I'll do this after 4.0.0-RC3 released.

**Comment by wu-sheng** [comment]
Thanks @tuohai666 to provide this. Is this plugin working for 4.0.0 stable release too?

**Comment by tuohai666** [comment]
Hi @wu-sheng, this plugin working only for 4.0.0-RC3. There're package name changes in 4.0.0 stable release.

**Comment by wu-sheng** [comment]
@tuohai666 :( Hope the ShardingSphere could be more stable. It keeps changing in every release.
