### ISSUE TITLE
Use the JavaAgent,Conflict with KafkaClient? (Magic v1 does not support record headers)

### ISSUE THREAD

**Issue by vipsql** [apache/skywalking#3778]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
java.lang.IllegalArgumentException: Magic v1 does not support record headers
        at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:403)
        at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:442)
        at org.apache.kafka.common.record.MemoryRecordsBuilder.append(MemoryRecordsBuilder.java:499)
        at org.apache.kafka.common.record.MemoryRecordsBuilder.append(MemoryRecordsBuilder.java:522)
        at org.apache.kafka.clients.producer.internals.ProducerBatch.tryAppend(ProducerBatch.java:107)
        at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:222)
at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
___
### Bug
- Which version of SkyWalking, OS and JRE?
JDK: 1.8.0_91
SkyWalking: 6.4.0

- What happen?
component version:
KafkaVersion:   KafkaClientVersion: 0.10.1.0

___
### Requirement or improvement
-  the can make the trun off or on control the kafka record

**Comment by wu-sheng** [comment]
That is your server error. The header begins being supported since 0.11 Kafka server.

**Comment by khiker007** [comment]
i have a kafka error in kafka 0.10 and spring stream with headerMode: embeddedheaders;

**Comment by khiker007** [comment]
@wu-sheng

**Comment by wu-sheng** [comment]
I have replied, now agian, kafka header supports since 0.11. This is an easy thing to google.

**Comment by khiker007** [comment]
I dont use header; in headerMode: embeddedheaders;spring kafka productor will put the type string in the message,and consumer will replace the type string from message;
when use kafka plugin, productor work well, but consumer dont replace the type string from msg,so we deserialize the msg to json will error;and remove the kafka plugin will work well

**Comment by wu-sheng** [comment]
I don't know the difference, sorry. We are just injecting the Kafka header. How it works inside, we don't change.

**Comment by yaojingguo** [comment]
A solution is to patch kafka-clients. Just commenting out the following code of [MemoryRecordsBuilder.java](https://github.com/apache/kafka/blob/2.3.1/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java). I use kafka-clients 2.3.1.

```
            if (magic < RecordBatch.MAGIC_VALUE_V2 && headers != null && headers.length > 0)
                throw new IllegalArgumentException("Magic v" + magic + " does not support record headers");
```


My first thought is to patch [KafkaProducerInterceptor](https://github.com/apache/skywalking/blob/v8.4.0/apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/KafkaProducerInterceptor.java). [KafkaProducer](https://github.com/apache/kafka/blob/2.3.1/clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java) has a private field  [apiVersions](https://kafka.apache.org/protocol#api_versions) which is updated to reflect Kafka server version before `KafkaProducer` sends its first message to Kafka server. However, `KafkaProducer` uses a separate thread to actually talk to a Kafka node. We don't know when `apiVersions` reflects the real version of a Kafka node. So this approach does not work out.
