### ISSUE TITLE
how can i send date to the skywalking

### ISSUE THREAD

**Issue by bnubobby** [apache/skywalking#3785]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Question or discussion
___
### Question
- What do you want to know?

 segment data format by skywalking v6
___
fist:   
send the following data to skywalking
`
{"traceSegmentId":{"idParts":["3","0","1572934140334734204"]},"spans":[{"spanId":500335830,"parentSpanId":-1,"startTime":"1572934140336","endTime":"1572934140404","operationName":"\/ping","spanLayer":"Http","logs":[{"time":"1572934140347","data":[{"key":"message","value":"[DEBUG][Redis]:Redis execute [ expire ] BSID_vovu19e182r9r4l393ripqihte [] []"}]}]}],"serviceId":3,"serviceInstanceId":3}
`

and then, query from es  by index  " skywalking_segment-* ",  get  data ：

`
{"_index":"skywalking_segment-0","_type":"type","_id":"vLQuOm4BSjVp4YK9aa7G","_version":1,"_score":1,"_source":{"trace_id":"3.0.1572934140334734204","endpoint_name":"/ping","latency":0,"end_time":0,"endpoint_id":2,"service_instance_id":0,"version":0,"start_time":0,"data_binary":"","service_id":0,"time_bucket":0,"is_error":0,"segment_id":null}}
`

Notice the  filled “  service_instance_id，  start_time ，  end_time  ”   Their value is 0

Second:  
send the following data to skywalking

`
{"traceSegmentId":{"idParts":["3","0","1572934595107781122"]},"spans":[{"parentSpanId":-1,"startTime":"1572934595109","endTime":"1572934595167","operationName":"\/ping","spanLayer":"Http","logs":[{"time":"1572934595112","data":[{"key":"message","value":"[DEBUG][Redis]:Redis execute [ expire ] BSID_vovu19e182r9r4l393ripqihte [] []"}]}]}],"serviceId":3,"serviceInstanceId":3}
`

and then, query from es  by index  " skywalking_segment-* ",  get  data ： 

`{"_index":"skywalking_segment-20191105","_type":"type","_id":"3.0.1572934595107781122","_version":1,"_score":1,"_source":{"trace_id":"3.0.1572934595107781122","endpoint_name":"/ping","latency":58,"end_time":1572934595167,"endpoint_id":2,"service_instance_id":3,"version":2,"start_time":1572934595109,"data_binary":"Cg0KCwMAgvTJouP1i+oVEoYBEP///////////wEYpeTU0eMtIN/k1NHjLToFL3BpbmdYA4IBYQio5NTR4y0SWAoHbWVzc2FnZRJNW0RFQlVHXVtSZWRpc106UmVkaXMgZXhlY3V0ZSBbIGV4cGlyZSBdIEJTSURfdm92dTE5ZTE4MnI5cjRsMzkzcmlwcWlodGUgW10gW10YAyAD","service_id":3,"time_bucket":20191105061635,"is_error":0,"segment_id":"3.0.1572934595107781122"}}`

What's wrong with my data?  
The data sent for the first time has a spanId,   but the server does not process it ?
Data sent for the second time has no spanId，but it can  found that  by ui ,

**Comment by wu-sheng** [comment]
Why are you sending data to SkyWalking directly, rather than using the agent?

**Comment by bnubobby** [comment]
no ,  I  try it by my php framework, because the php extension is not suitable

**Comment by wu-sheng** [comment]
If you are writing your own client, you need to understand the protocols and processes of all segment, register and ping services, even including the backend logic. This is a very long list. I highly recommend you to work with our php agent subproject team, enhance the feature there, rather than begin from day one.

**Comment by bnubobby** [comment]
@wu-sheng  How can I contact  the php agent subproject team ?

**Comment by wu-sheng** [comment]
Submit an issue at their project, https://github.com/SkyAPM/SkyAPM-php-sdk. I think they will be there.

**Comment by bnubobby** [comment]
@wu-sheng 
 I know it,But I don't think this project is suitable for my scenario， I have built a whole microservice system with my framework, and the tracking data has been sent to Jaeger,  but I regret that  jaeger is not good at performance analysis,   Now I just want to modify the framework and send the trace data to  skywalking

**Comment by wu-sheng** [comment]
Why? You wrote a framework, then, write a private plugin should be enough, why do the whole thing again?

**Comment by bnubobby** [comment]
Don't you think it has deviated from the point ? 
 A private plugin should be enough, so  I am codeing  it,  and the API document are not detailed enough

**Comment by wu-sheng** [comment]
Lack of the document(if it is), is still a thing about enhancing upstream.  In most cases, I would only recommend working with the upstream team. Don't create the same thing from line one.
