### ISSUE TITLE
ui: time range is incorrect when server zone is utc-0

### ISSUE THREAD

**Issue by lixiv** [apache/skywalking#3791]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Bug

### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking: v6.4.0
OS: CentOS 7.2 in Docker
JRE: Oracle JDK 1.8

- What happen?
Our Skywalking is running in docker, which timezone is utc-0. On the skywalking UI, we can get trace data when set server zone to UTC-0, but when select time range like "last 1 hour", cannot get any data.

**Comment by wu-sheng** [comment]
@TinyAllen Could you take a look? Seem like the last xxx is not working, because of some query logic change.

**Comment by wu-sheng** [comment]
@lixiv Have you tried the master? We have a related fix, https://github.com/apache/skywalking-rocketbot-ui/pull/173

**Comment by lixiv** [comment]
> @lixiv Have you tried the master? We have a related fix, [apache/skywalking-rocketbot-ui#173](https://github.com/apache/skywalking-rocketbot-ui/pull/173)

I just tried the master, the bug still exists.

**Comment by wu-sheng** [comment]
@lixiv We just fixed it in the UI.
