### ISSUE TITLE
The topology does not agree with the actual situation

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3792]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Our experimental deployment environment is as follows：
![image](https://user-images.githubusercontent.com/52440226/68276681-770bf700-00a8-11ea-85e9-31d4a487b48e.png)

After running for some time, we looked at the topology of skywalking and found that it was not consistent：
![image](https://user-images.githubusercontent.com/52440226/68276508-25fc0300-00a8-11ea-992e-735e9b12651d.png)
I checked the agent.config 's agent.service_name of each service without any problem.

The skywalking topoloy display  that "chegndu-t1-api"  call "foshan-s1-wms", "jiahu-s1-wms" ,  ... etc .  In fact, "chegndu-t1-api"  only calls  "chegndu-t1-wms" locally.  "chegndu-t1-api" can't call other services.

It's strange that  I  just only find skywalking traces of   "chegndu-t1-api" call  "chegndu-t1-wms" ,not others.

I think skywalking trace is right ,  topology maybe wrong in this situation. 
There are the same webapps in the each Host , but named different agent service name.
Who Can help to analyze the reason ?

**Comment by wu-sheng** [comment]
The topology is based on `IP: port`<->service mapping. Is there anything related to share the same address? Such as some virtual IP?

**Comment by webb2019** [comment]
> The topology is based on `IP: port`<->service mapping. Is there anything related to share the same address? Such as some virtual IP?
thanks！  
I  checked our hosts IP，Truly, every host has serveral IPs, One Public IP that Unique, others are private IPs ,such as 192.168.10.2, 192.168.10.7 etc .  And It exsits  that one host has a same private IP as other Host.

If ，like you said , "The topology is based on `IP: port`<->service mapping. " , but there might be a lot of the same private IP in microservices , are  all services associated？

As I mentioned  , our  service "xxx-xxx-api" calls  service "xxx-xxx-wms" use "http://localhost:80/api" , if  we use "http://ip:port/api" (ip is unique private )  to request , will the topology  be normal ?

**Comment by wu-sheng** [comment]
Yes. Don't use `localhost: port` ever. That will break the topology. The design is based on container-based or micro-service based architecture, so basically, no localhost is being called, all service should be discovered by register center or DNS.

**Comment by webb2019** [comment]
> Yes. Don't use `localhost: port` ever. That will break the topology. The design is based on container-based or micro-service based architecture, so basically, no localhost is being called, all service should be discovered by register center or DNS.

That is , if our  hosts has  only one different unique IP,  but  our service  "xxx-xxx-api" calls service "xxx-xxx-wms" use "http://localhost:80/api" , Is the topology still broken ?  because skywalking Unable to distinguish the api url ?

**Comment by wu-sheng** [comment]
Yes, that is the right expression.
