### ISSUE TITLE
Can 'MongoConstants.FILTER_LENGTH_LIMIT' in agent be configable?

### ISSUE THREAD

**Issue by thihy** [apache/skywalking#3796]
https://github.com/apache/skywalking/blob/80af1667528cfd8924cce5ca4bc62a31c116974f/apm-sniffer/apm-sdk-plugin/mongodb-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v3/support/MongoConstants.java#L34

**Comment by wu-sheng** [comment]
Not today, if you want that, you need to submit a PR to move it to Agent Config. Like this

https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Config.java#L222

**Comment by arugal** [comment]
I will finish this.

**Comment by wu-sheng** [comment]
Provided.
