### ISSUE TITLE
Why there are so many indexes

### ISSUE THREAD

**Issue by piaoluoxiaobai** [apache/skywalking#3801]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
use elasticSearch as storage，Why there are so many indexes，there are 621
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.4
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dmsolr** [comment]
It is easy to delete historical data of ES.
