### ISSUE TITLE
NodeJS auto-instrument agents cannot be used as expected

### ISSUE THREAD

**Issue by lixiv** [apache/skywalking#3806]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [  ] Question or discussion

___
### Question
- What do you want to know?
We shouldn't say we support NodeJS auto-instrument agents, because it cannot run as expected. One critical bug is that span references(childof) is incorrect. The agent lack of a "ThreadLocal" implementation, it cannot set/get per-request context.

**Comment by wu-sheng** [comment]
NodeJS is not an official Apache repo. The issue is not managed here.

**Comment by lixiv** [comment]
I mean we should modify our documents
SkyWalking supports to collect telemetry (traces and metrics) data from multiple sources and multiple formats, including
Java, .NET Core,  **NodeJS** and PHP auto-instrument agents in SkyWalking format

**Comment by wu-sheng** [comment]
There is no ThreadLocal in NodeJS. It works for some cases already, we don't need to remove it from my understanding. If it isn't suitable for you, you could contribute, that is how open source project works.
