### ISSUE TITLE
Service list in the web UI cannot be displayed

### ISSUE THREAD

**Issue by lmzhizhe** [apache/skywalking#3813]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ✔] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Service list in the web UI cannot be displayed，how to resloved it
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.1 ， centos 7 
- Which company or project?
vivo
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by lmzhizhe** [comment]
see the photoes

**Comment by wu-sheng** [comment]
Search the closed issue before you submit new. It is your OAP backend or app time and timezone issue. Notice the first line of the deployment doc.
