### ISSUE TITLE
[CLI] License checker for SkyWalking CLI

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#3818]
We don't have license checker for the [SkyWalking-CLI](https://github.com/apache/skywalking-cli) project now, and as an Apache TLP, this is a serious problem, so anyone have experience in this please help to add a checker for this project

**Comment by wu-sheng** [comment]
@kezhenxu94 This should be provided, right?

**Comment by kezhenxu94** [comment]
yes
