### ISSUE TITLE
[CLI] Add more commands to SkyWalking CLI

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#3819]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

we have the first workable command now, http://github.com/apache/skywalking-cli/pull/6, and we'd like to welcome more contributors to add more commands, if you're interested in contributing one, please create an issue titled `[CLI] Add command <COMMAND NAME> to SkyWalking CLI`, like `[CLI] Add command instance list to SkyWalking CLI`, and cross refer this issue, we'll assign it then

**Comment by arugal** [comment]
I'll try Instance --list

**Comment by kezhenxu94** [comment]
> I'll try Instance --list

Create another issue to track this command, and cross refer to this issue

**Comment by kezhenxu94** [comment]
We'll continuously add more commands in 0.2.0

**Comment by kezhenxu94** [comment]
This was to track the first set of commands and now that the basic commands are added, we can open new issues per command if specific commands are needed.
