### ISSUE TITLE
[CLI] Add command instance list to SkyWalking CLI

### ISSUE THREAD

**Issue by arugal** [apache/skywalking#3821]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

Command: ```./swctl --debug instance ls --service=1 --start=2019-11-09 --step=MONTH```

**Comment by arugal** [comment]
refer #3819

**Comment by arugal** [comment]
refer https://github.com/apache/skywalking-cli/pull/10

**Comment by wu-sheng** [comment]
Please use name string as service parameter, not id. You need to query service id by code first, then get instance list.
