### ISSUE TITLE
Add "Apdex" to OAL

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#3822]
Add "Apdex" to OAL, I will refer to "https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/apdex-measure-user-satisfaction"

**Comment by wu-sheng** [comment]
Notice, the appdex threshold should based on dynamic configuration and using JSON to provide default or service name based config.

**Comment by hanahmily** [comment]
> the appdex threshold should based on dynamic configuration.
Why not use `oal` file to accomplish this goal. just like:
```
// the threshold of service xxx is 500ms.
service_xxx_apdex = from(Service.latency).filter(name==xxx).apdex(500);
```
There's still some issues that should be addressed. The default "T", we can't set a default threshold for services, unless we calculate some apedx score more than once. For example:
```
// the default thredhold of service is 500ms.
service_apdex = from(Service.latency).apdex(500);
// the thredhold of service xxx is 200ms. but there's a default apdex score for this service.
service_xxx_apdex = from(Service.latency).filter(name==xxx).apdex(200);
```

Finally, Why I suggest on OAL? Because this requirement belongs to its scope, and I don't want to add config file for it.

**Comment by wu-sheng** [comment]
Don't set 500 in the OAL, read the value from `apdex` function. Then you could read from CoreModuleConfig and using `DynamicConfigurationService` in `ConfigurationModule` by providing dynamic configuration.

**Comment by hanahmily** [comment]
```
// read servicename -> "T" mapping from dynamic config service 
in apedx function, then pass service name to apdex function 
// as its parameter in order to filter mapping item from dynamic config.
service_apdex = from(Service.latency).apdex(name);
```
^^^ Is it correct?

**Comment by wu-sheng** [comment]
Correct.
