### ISSUE TITLE
Support apdex in UI service level

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#3827]
After #3822 provided, the UI should add Apdex value on the service level page. As default, apdex is only used a service level metrics.

**Comment by x22x22** [comment]
> After #3822 provided, the UI should add Apdex value on the service level page. As default, apdex is only used a service level metrics.

Just add it in the topology interface and dashboard?

**Comment by wu-sheng** [comment]
Yes. The default dashboard and service page of topology.

**Comment by x22x22** [comment]
Notify me when the backend provides an interface.

**Comment by wu-sheng** [comment]
Added by #3987
