### ISSUE TITLE
JDK 1.7和1.8 JVM Non-Heap (MB) 显示异常

### ISSUE THREAD

**Issue by chad0329** [apache/skywalking#3828]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ * ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- 使用jdk1.7 JVM Non-Heap (MB)显示为负数
![image](https://user-images.githubusercontent.com/56951099/68569160-625ca400-0498-11ea-8abd-53ba8aeba192.png)

使用1.8正常
![image](https://user-images.githubusercontent.com/56951099/68569212-80c29f80-0498-11ea-8d6a-170656b4d1bc.png)

___
### Bug
- jdk1.7

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only, and this has been fixed.
