### ISSUE TITLE
Service instance dependency and metrics of them

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#3829]
We are planning to provide service instance level dependency and metrics of them. 

Before that, the mapping of IP:port to service must be improved. We need to add IP:port to instance mapping.

Also after this, we could add OAL and manual relationship about service instance relationship and metrics of them.

The last step is providing GraphQL query for instance dependency. The idea right now is querying the instance relationship by given services of source and dest, we are not providing instance-level topology by default.

@kezhenxu94 Do you have interests to do this? Or any other @apache/skywalking-committers wants to do? Please let me know.

After the above is done, UI need to be upgraded too. When clicking the service relationship, the user should have a chance(button?) to dig deeper to instance relationships, and binding with metrics(similar to the service relationship and metrics in the topology). @Fine0830 @x22x22 @TinyAllen Which one of you could take this part in next release, please let me know.

**Comment by arugal** [comment]
So cool. I want to try it, but I'm not sure I can handle it.

**Comment by wu-sheng** [comment]
> So cool. I want to try it, but I'm not sure I can handle it.

You need to understand how current topology generated from trace raw data. This is not an easy task. This enhancement could be a separated release from my understanding. I would say 6.6.0 or 6.7.0 should for this, before the end of this year, as a closure and super powerful feature of SkyWalking 2019.

**Comment by arugal** [comment]
> > So cool. I want to try it, but I'm not sure I can handle it.
> 
> You need to understand how current topology generated from trace raw data. This is not an easy task. This enhancement could be a separated release from my understanding. I would say 6.6.0 or 6.7.0 should for this, before the end of this year, as a closure and super powerful feature of SkyWalking 2019.

I know about the collection of the raw data, but I don't understand topology generation. maybe I can do the odd jobs?

**Comment by wu-sheng** [comment]
You should read
1. MultiScopesSpanListener
1. Service Topology Query

Then, you may get the idea.

**Comment by dmsolr** [comment]
I would like to do it with you, @arugal . But I am not familiar at OAL.

**Comment by wu-sheng** [comment]
> I would like to do it with you, @arugal . But I am not familiar at OAL.

OAL is a super easy part :) The mapping and new query are really works.

**Comment by arugal** [comment]
Give us two weeks to learn. If no one else accepts the assignment, just assign the task to us. How about this idea?

**Comment by wu-sheng** [comment]
> Give us two weeks to learn. If no one else accepts the assignment, just assign the task to us. How about this idea?

Sure. Take your time. If you need help, ping me.

**Comment by aderm** [comment]
@wu-sheng I also hope to participate in this work. I don't know if it is ok?

**Comment by wu-sheng** [comment]
@aderm any one could be. The key is you could understand what should be done by yourself.😆

Who could provide a design and adjustment doc are the core requirement.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 Do you have interests to do this?

I'll have a detailed look and discuss here

**Comment by arugal** [comment]
Hi, this is my current train of thought:
+ add a ```SourceDispatcher``` implementation to store ```ServiceInstanceRelation```,refer to the implementation of ```ServiceInstance```
+ add ```getServiceInstanceTopology``` to ```TopologyQuery```  provide data query.

**Comment by wu-sheng** [comment]
These two are right, but you miss one part. See closer about how topology generated for service topology. There is a `IP:port` <-> `service name` mapping by analysis segment ref data, but today, we don't save the `IP:port` <-> `service instance` mapping even it is existing in the ref.

**Comment by wu-sheng** [comment]
@Fine0830 We have merged the backend PR. We will redeploy the latest codes to the demo env.

The UI changes should be like this,
![image](https://user-images.githubusercontent.com/5441976/70399968-0b2ffc00-1a63-11ea-8b62-9eef0200ec78.png)

After user clicks the new button, it should a box showing up, the [new topo query API](https://github.com/apache/skywalking-query-protocol/blob/master/topology.graphqls#L90) should be used for this. 

You should be able to get client id and server id from the original topology map. 

In the new box, in default, we should show all instances of client and server, like this
![image](https://user-images.githubusercontent.com/5441976/70400672-05d4b080-1a67-11ea-8e04-fd9870929e37.png)

Then we could click the any client instance and get the dependency server instance relationship. The line could be clicked like service topology line, and get following metrics of them
![image](https://user-images.githubusercontent.com/5441976/70400691-200e8e80-1a67-11ea-9aa0-f24edbe79fd8.png)

OAL of metrics, nearly as same as relationship metrics of service level. You should provide client/server side switch too.
```
service_instance_relation_client_cpm = from(ServiceInstanceRelation.*).filter(detectPoint == DetectPoint.CLIENT).cpm();
service_instance_relation_server_cpm = from(ServiceInstanceRelation.*).filter(detectPoint == DetectPoint.SERVER).cpm();
service_instance_relation_client_call_sla = from(ServiceInstanceRelation.*).filter(detectPoint == DetectPoint.CLIENT).percent(status == true);
service_instance_relation_server_call_sla = from(ServiceInstanceRelation.*).filter(detectPoint == DetectPoint.SERVER).percent(status == true);
service_instance_relation_client_resp_time = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.CLIENT).longAvg();
service_instance_relation_server_resp_time = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.SERVER).longAvg();
service_instance_relation_client_p99 = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.CLIENT).p99(10);
service_instance_relation_server_p99 = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.SERVER).p99(10);
service_instance_relation_client_p95 = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.CLIENT).p95(10);
service_instance_relation_server_p95 = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.SERVER).p95(10);
service_instance_relation_client_p90 = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.CLIENT).p90(10);
service_instance_relation_server_p90 = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.SERVER).p90(10);
service_instance_relation_client_p75 = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.CLIENT).p75(10);
service_instance_relation_server_p75 = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.SERVER).p75(10);
service_instance_relation_client_p50 = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.CLIENT).p50(10);
service_instance_relation_server_p50 = from(ServiceInstanceRelation.latency).filter(detectPoint == DetectPoint.SERVER).p50(10);
```

And also you could click server side instance.
![image](https://user-images.githubusercontent.com/5441976/70400772-83002580-1a67-11ea-8a05-fe8473f7c017.png)

**Comment by Fine0830** [comment]
Gotcha. I will do in the late few days.
