### ISSUE TITLE
When the plan to support the JavaRMI Client Plugins?

### ISSUE THREAD

**Issue by vipsql** [apache/skywalking#3830]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
when the pan to support javarmi client plugins

**Comment by wu-sheng** [comment]
There is no support plan in the SkyWalking community. Anyone wants to add new plugin, we are welcome the contribution and be happy to help with review. But no committer will be responsible to provide a new one, unless he needs it by himself.

**Comment by vipsql** [comment]
@wu-sheng  thanks

**Comment by alonelaval** [comment]
@vipsql I didn't ask to trace the original RMI API, and a lot of that information wasn't available, so I did the tracing directly based on Spring RMI.

**Comment by alonelaval** [comment]
@vipsql Because Java RMI does not support passing trace information through headers or attachments, I closed the issue
