### ISSUE TITLE
Question for tracing

### ISSUE THREAD

**Issue by bnubobby** [apache/skywalking#3831]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?

Looking at  the project demo, it looks like  that each database operation will create a span, 
I'm afraid it will produce too much span and hard to tracing.
Is that a problem?
What is usually done in  db layer ?

**Comment by wu-sheng** [comment]
The question should be, what do you want?

**Comment by bnubobby** [comment]
@wu-sheng 
I need database layer analysis, but I don't want too much  span ,
how can I do that?
or  can I hide the db layer span ?

**Comment by wu-sheng** [comment]
I don't know. At least, this is not skywalking's concern.
