### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by surechen** [apache/skywalking#3832]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
 COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /usr/local/src/java/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[21,1] package org.apache.skywalking.apm.network.common does not exist
[ERROR] /usr/local/src/java/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[30,26] package Command does not exist
[ERROR] /usr/local/src/java/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[45,12] package Command does not exist
[ERROR] /usr/local/src/java/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/CommandDeserializer.java:[20,48] package org.apache.skywalking.apm.network.common does not exist

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

![image](https://user-images.githubusercontent.com/7249331/68586996-eaef3a80-04c0-11ea-8ab5-a70d4fd9965c.png)
![image](https://user-images.githubusercontent.com/7249331/68587102-3275c680-04c1-11ea-877e-5f5848099dd1.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
I hope to be able to compile by sourecode in ubuntu. Could you help solve this problem?

**Comment by wu-sheng** [comment]
The compiling doc is required. Read it and follow it.

**Comment by JohnNiang** [comment]
You may have to Change JDK to `8 version` that mentioned [HERE](https://github.com/apache/skywalking/blob/master/docs/en/guides/How-to-build.md#build-from-github).

**Comment by jzdydd** [comment]
I also made this mistake
My environment: jdk 1.8.0_291, maven 3.8.3, os: windows
my step:
step1: git clone -b v7.0.0 --recurse-submodules https://github.com/apache/skywalking.git
step2: mvnw package -Pagent，dist
