### ISSUE TITLE
Does suport agent upload data cache to MQ  , oap pick data from MQ?

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3841]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does suport agent upload data cache to MQ first , later oap pick data from MQ?
I find OAP receiver parse Big trace segement（more then 1000+ spans） in heavy load status，CPU reach nearly 100%。（8C16G）。

**Comment by wu-sheng** [comment]
No, even it is, don't help the CPU payload. It will only make you cost more CPU.

**Comment by webb2019** [comment]
> No, even it is, don't help the CPU payload. It will only make you cost more CPU.
I think the benefit of MQ is that the disk exchange to the CPU，agent respone no timeout，and Reduce CPU pressure  ，Balance busy and idle time of the OAP  。

**Comment by wu-sheng** [comment]
But with that, the value of a monitoring system is keeping reduce. With several minutes latency to trigger alarm is meaningless. If you want, agent could override a trace sender by a plugin. I just said from my understanding, it is useless for a monitoring system.
