### ISSUE TITLE
which way deploy in clust mode best?

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3842]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I want to deploy  skywalking in cluster mode:
(1)  agent --> SLB( nginx) - > OAP clusters
(2)  agent --> OAP clusters 

which way does you  sugestion best?

**Comment by wu-sheng** [comment]
This depends on your network strategy. Different companies have different requirements.
