### ISSUE TITLE
Provide ES 7.x storage in a separated dist

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#3843]
With several times discussion between me and @kezhenxu94, we are going to provide a compatible way to support ES7 in OAP storage for making it easier for some users.

We are proposing to leverage a new OAP `starter` module, which could use maven exclude to get rid of existing ES6 storage plugin and ES6 client lib, then we could create new modules. The new structure will look like this

```
+ oap-server
   + server-starter-es7[new]
       pom.xml(depend on server starter, exclude storage-elasticsearch-plugin)
   + server-storage-plugin
       + storage-elasticsearch7-plugin[new]
```

Also, of course, we need some changes in the dist folder, to include the new package, but basically that is OK. And we should be able to use ES7 official client rather than #3613, which maintains the compatible by ourselves.

**Comment by kezhenxu94** [comment]
I should be available to work on this in the following weeks

**Comment by kezhenxu94** [comment]
Merged
