### ISSUE TITLE
What is the order defining for Segment  at  the same level ?

### ISSUE THREAD

**Issue by bnubobby** [apache/skywalking#3844]
### Question
What is the order defining for segment  at the same level ?

**My display:**
![image](https://user-images.githubusercontent.com/23736568/68736338-53eac580-061b-11ea-8731-edeeb98941ce.png)

**actually , my calling order is :** 

/home/par 
-> /home/test210 
-> /home/test310
-> /home/test410
-> /home/test1
-> /home/test501

**Isn't it order by start time ?**

**My data** 
`
{"data":{"trace":{"spans":[{"traceId":"6.6.1573622778174619","segmentId":"6.6.1573622778174626","spanId":0,"parentSpanId":-1,"refs":[],"serviceCode":"w.com","startTime":1573622778177,"endTime":1573622779586,"endpointName":"/home/par","type":"Entry","peer":"","component":"","isError":false,"layer":"Http","tags":[],"logs":[{"time":1573622779586,"data":[{"key":"message","value":"handleFoundRoute : App\\Controllers\\Home@par"}]},{"time":1573622779587,"data":[{"key":"message","value":"Redis execute [ expire ] BSID_3cj4rt0b51gu6fk35cbq0vhk9k"}]}]},{"traceId":"6.6.1573622778174619","segmentId":"6.6.1573622778452776","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"6.6.1573622778174619","parentSegmentId":"6.6.1573622778174626","parentSpanId":0,"type":"CROSS_PROCESS"}],"serviceCode":"w.com","startTime":1573622778453,"endTime":1573622778773,"endpointName":"/home/testcall/320","type":"Entry","peer":"","component":"","isError":false,"layer":"Http","tags":[],"logs":[{"time":1573622778774,"data":[{"key":"message","value":"test call by 320"}]},{"time":1573622778774,"data":[{"key":"message","value":"handleFoundRoute : App\\Controllers\\Home@testcall"}]},{"time":1573622778774,"data":[{"key":"message","value":"Redis execute [ expire ] BSID_3cj4rt0b51gu6fk35cbq0vhk9k"}]}]},{"traceId":"6.6.1573622778174619","segmentId":"6.6.1573622778205991","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"6.6.1573622778174619","parentSegmentId":"6.6.1573622778174626","parentSpanId":0,"type":"CROSS_PROCESS"}],"serviceCode":"w.com","startTime":1573622778206,"endTime":1573622778417,"endpointName":"/home/testcall/210","type":"Entry","peer":"","component":"","isError":false,"layer":"Http","tags":[],"logs":[{"time":1573622778431,"data":[{"key":"message","value":"test call by 210"}]},{"time":1573622778431,"data":[{"key":"message","value":"handleFoundRoute : App\\Controllers\\Home@testcall"}]},{"time":1573622778431,"data":[{"key":"message","value":"Redis execute [ expire ] BSID_3cj4rt0b51gu6fk35cbq0vhk9k"}]}]},{"traceId":"6.6.1573622778174619","segmentId":"6.6.1573622779019177","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"6.6.1573622778174619","parentSegmentId":"6.6.1573622778174626","parentSpanId":0,"type":"CROSS_PROCESS"}],"serviceCode":"w.com","startTime":1573622779019,"endTime":1573622779432,"endpointName":"/home/testcall/412","type":"Entry","peer":"","component":"","isError":false,"layer":"Http","tags":[],"logs":[{"time":1573622779432,"data":[{"key":"message","value":"test call by 412"}]},{"time":1573622779432,"data":[{"key":"message","value":"handleFoundRoute : App\\Controllers\\Home@testcall"}]},{"time":1573622779432,"data":[{"key":"message","value":"Redis execute [ expire ] BSID_3cj4rt0b51gu6fk35cbq0vhk9k"}]}]},{"traceId":"6.6.1573622778174619","segmentId":"6.6.1573622779458109","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"6.6.1573622778174619","parentSegmentId":"6.6.1573622778174626","parentSpanId":0,"type":"CROSS_PROCESS"}],"serviceCode":"w.com","startTime":1573622779458,"endTime":1573622779465,"endpointName":"/home/testcall/5","type":"Entry","peer":"","component":"","isError":false,"layer":"Http","tags":[],"logs":[{"time":1573622779466,"data":[{"key":"message","value":"test call by 5"}]},{"time":1573622779466,"data":[{"key":"message","value":"handleFoundRoute : App\\Controllers\\Home@testcall"}]},{"time":1573622779466,"data":[{"key":"message","value":"Redis execute [ expire ] BSID_3cj4rt0b51gu6fk35cbq0vhk9k"}]}]},{"traceId":"6.6.1573622778174619","segmentId":"6.6.1573622779491062","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"6.6.1573622778174619","parentSegmentId":"6.6.1573622778174626","parentSpanId":0,"type":"CROSS_PROCESS"}],"serviceCode":"w.com","startTime":1573622779491,"endTime":1573622779545,"endpointName":"/home/testcall/54","type":"Entry","peer":"","component":"","isError":false,"layer":"Http","tags":[],"logs":[{"time":1573622779546,"data":[{"key":"message","value":"test call by 54"}]},{"time":1573622779546,"data":[{"key":"message","value":"handleFoundRoute : App\\Controllers\\Home@testcall"}]},{"time":1573622779546,"data":[{"key":"message","value":"Redis execute [ expire ] BSID_3cj4rt0b51gu6fk35cbq0vhk9k"}]}]}]}}}
`

**Comment by wu-sheng** [comment]
This seems like multiple segments, rather than multiple spans. Right?

Right now it is not ordered from my understanding. We may need to add them by start time.

**Comment by wu-sheng** [comment]
`TraceQueryService#findRoots` should order the return list, by start time.

**Comment by wu-sheng** [comment]
Could you work on this? @bnubobby This should be an easy PR.

**Comment by bnubobby** [comment]
@wu-sheng  
This multiple segments.
But in terms of start  time,  api "/home/test210"  should be ahead of   "/home/test310" 
Maybe it's an interface error ?  I try it

**Comment by wu-sheng** [comment]
This could be resolved in the backend.  Try to find this `TraceQueryService#findRoots` and order the result list, and check whether UI is working.

**Comment by wu-sheng** [comment]
@bnubobby Any update? Have you tried the method I gave to you?

**Comment by bnubobby** [comment]
@wu-sheng 
yes , Try to find this TraceQueryService#findRoots and order the result list  is ok.
I tried to submit PR,  but something went wrong   at 
[PR](https://github.com/apache/skywalking/pull/3853)
Now I'm waiting for the new version

**Comment by wu-sheng** [comment]
@bnubobby I am a little confused, that PR is not same as the method I gave you. What is the matter you mean?

**Comment by bnubobby** [comment]
@wu-sheng  
maybe it's a mistake,   sort by database or sort by application  , I choose  database.
All in all, it's good to solve it, Thank you for your patience and  support.

**Comment by wu-sheng** [comment]
Good to know. My PR is merged, this should be good in next release.
