### ISSUE TITLE
how to enhance method with @RequestMapping annotation declared in interface?

### ISSUE THREAD

**Issue by pop0505** [apache/skywalking#3847]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question

___
### Question
- What do you want to know?
How to enhance method with @RequestMapping annotation declared in it's interface?

Here is the example code
```
interface RestApi {
    @RequestMapping("/test")
    String test();
}

@RestController
public class RestApiImpl implements RestApi {
    @Override
    public String test() {
        return "test";
    }
}
```
The problem is that skywalking can not enhance the `RestApiImpl.test()` method. I guess the reason is skywalking cannot find `@RequestMapping` annotation in overrided method.

And here is the related source code  in sw's spring-plugins:
```
# RequestMappingMethodInterceptor.java
public class RequestMappingMethodInterceptor extends AbstractMethodInterceptor {
    @Override
    public String getRequestURL(Method method) {
        String requestURL = "";
        RequestMapping methodRequestMapping = method.getAnnotation(RequestMapping.class);
        if (methodRequestMapping.value().length > 0) {
            requestURL = methodRequestMapping.value()[0];
        } else if (methodRequestMapping.path().length > 0) {
            requestURL = methodRequestMapping.path()[0];
        }
        return requestURL;
    }
  // ...
``` 
But the method `getAnnotation` can not get annotation from interface, so how can i solve this problem?

**Comment by wu-sheng** [comment]
If this is the case, we don't expect you to write in this way. You have to use more reflect API to get that.

**Comment by wu-sheng** [comment]
This should be not hard, could you try to submit a pull request to fix this?

**Comment by liudantop** [comment]
I don't think the issue is the reason and test not pass.
found the matcher is the isAnnotatedWith, explain in bytebuddy. the match does not match inherited annotations :
isAnnotatedWith(named("org.springframework.web.bind.annotation.RequestMapping"));

 * Matches an {@link AnnotationSource} for declared annotations.
     * **This matcher does not match inherited annotations which only exist for classes.** Use
     * {@link net.bytebuddy.matcher.ElementMatchers#inheritsAnnotation(net.bytebuddy.matcher.ElementMatcher)}
     * for matching inherited annotations.

**Comment by wu-sheng** [comment]
This issue is for fixing inheritance annotation meta inform. Yours may be different. You want to instrument the subclass without the annotation.

**Comment by liudantop** [comment]
case is similar.
If the annotation @RequestMapping("/test")  is define interface method. Subclass implement the method， and enhance is inoperative.

**Comment by wu-sheng** [comment]
I know it is similar, but at the codes level, it is different. You should be able to provide a pull request to fix this, as you have already been looking at the ByteBuddy APIs. There is only a chance to use suitable API to filter the classes.

**Comment by liudantop** [comment]
thanks, let me try.
