### ISSUE TITLE
Rocketmq async send message occurred exception

### ISSUE THREAD

**Issue by HackerRookie** [apache/skywalking#3848]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [*] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  skywalking version:6.4.0, 1.8+
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Because agent intercept is the sendMessage method in MQClientAPI Impl, if the exception occurs before this method, MessageSendInterceptor does not initialize setSkyWalkingDynamicField. Lead to OnIntercept Exceptionor will have NullPoint Exception
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Could you send a pull request to fix this? Seems you already know what happens, then how to fix should be easy.

**Comment by HackerRookie** [comment]
headache !!!! @wu-sheng  @ascrutae

**Comment by jackiepon31** [comment]
so , u haven fixed that problem???

**Comment by wu-sheng** [comment]
If you have issues, you should try to fix, amd consider to contribute to the open source. We only fix some issues when we have time. A plugin bug is not definitely high priority.

**Comment by HackerRookie** [comment]
Present,  Can't perfectly solve the problem

**Comment by dengliming** [comment]
Could you provide your related codes?I'd like to look at this scenario.

**Comment by jackiepon31** [comment]
> Present, Can't perfectly solve the problem
the inteceptions offered by Skywalking rocketmq-plugins  are via 2 phases ,firstly to update nameserver ,then to send message, so you should tell us whitch phase you get an exception.
By the way
dude, you‘d better offer more details of your problems instead of telling us some kind of conclusions ,other guys may face the same problem like you
