### ISSUE TITLE
Feign Client Operation Name with PathVariable

### ISSUE THREAD

**Issue by dominicqi** [apache/skywalking#3850]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [+] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Like #3293  ,i use a feign client  with PathVariable, there's going to be too much endpoint in memory。I think we can set the operationName  with the url before feign resolve it with args. Do you think we should add one  interceptor to do this, or do like restTemplate.opGroup ? 
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Could you do that in an interceptor to recognize the parameter?

**Comment by dominicqi** [comment]
> Could you do that in an interceptor to recognize the parameter?

Yes,because there is a method  one params is the origin url ,result is the resolved url,i think we could get the origin url  in an interceptor

**Comment by wu-sheng** [comment]
If you could get the URL without parameter in the interceptor, recommend to do it. Could you send to pull request to fix this?
