### ISSUE TITLE
http://122.112.182.72:8080/ does not have any data？

### ISSUE THREAD

**Issue by FrankWang307** [apache/skywalking#3851]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
the website displayed in the readme does have any data?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
I wanna to watch the displayed demo website
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Clieck reload. It is there. We are updating, it may just have data in UTC +13

**Comment by wu-sheng** [comment]
That is a demo env only. No gurarantee it is working.
