### ISSUE TITLE
How to add agent in other instance ?

### ISSUE THREAD

**Issue by aa6my** [apache/skywalking#3856]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to add the agent in the other instance

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking

- Which company or project?
Carsome

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Detail in documentation regarding installation and usage

**Comment by wu-sheng** [comment]
What is other instance? Unclear question.

**Comment by aa6my** [comment]
> What is other instance? Unclear question.

I want to add other endpoint for **example** i want to check `200` response at `http://10.10.10.10`

**Comment by wu-sheng** [comment]
Still, don't understand what is your meaning. Are you saying you want response code 200 metrics? If yes, do that in OAL, it is supported. But UI doesn't support that.
