### ISSUE TITLE
trace cannot be displayed

### ISSUE THREAD

**Issue by xun404** [apache/skywalking#3858]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug

Some trace cannot be displayed! new version fixed? version:6.3.0

![image](https://user-images.githubusercontent.com/10024821/68835018-1ad15480-06f2-11ea-95de-b56a93a5c362.png)

**Comment by wu-sheng** [comment]
Maybe some parts of trace missing. 6.4.0+ should support missing node visualization already. Please read changelog.
