### ISSUE TITLE
storage support clickhouse

### ISSUE THREAD

**Issue by bolyage** [apache/skywalking#3860]
- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?

Is the storage support clickhouse？Or is there a plan?

**Comment by nauu** [comment]
I am planning to implement a new storage with ClickHouse , using MergeTree engine.

**Comment by dmsolr** [comment]
I am thinking to implement the other NoSQL DB as storage. But not ClickHouse, something like InfluxDB or OpenTSDB. @nauu

**Comment by nauu** [comment]
ClickHouse record its own metrics into ClickHouse each second by default, and also some other query logs ,its performance should be suitable as a storage.

And if we have a ClickHouse storage in SkyWalking , it will be very convenient for those people who use ClickHouse as a warehouse. @dmsolr

**Comment by wu-sheng** [comment]
Clickhouse as a warehouse is not very suitable for SkyWalking process mode actually. 

Clickhouse is good at calculate things inside, but we don't need it.

We required high update performance, which is of an advantage of Clickhouse.

You could try. This is only my personal opinion.

**Comment by Slach** [comment]
@nauu did you get any results with support Clickhouse as storage engine inside SkyWalking?
