### ISSUE TITLE
UI not  display instance's  language?

### ISSUE THREAD

**Issue by bnubobby** [apache/skywalking#3862]
Why doesn't the UI  display instance  language?
my app  language is php 
**This is the data in my ES storage :** 

`
{
  "_index": "skywalking_service_instance_inventory",
  "_type": "type",
  "_id": "5_DESKTOP-VJDMAUP_0_0",
  "_version": 1,
  "_score": 1,
  "_source": {
    "sequence": 5,
    "last_update_time": 0,
    "heartbeat_time": 1573784378429,
    "service_id": 5,
    "address_id": 0,
    "name": "w2.com@DESKTOP-VJDMAUP",
    "is_address": 0,
    "instance_uuid": "DESKTOP-VJDMAUP",
    "register_time": 1573784378429,
    "properties": "{\"language\":\"PHP\",\"os_name\":\"WINNT\",\"host_name\":\"DESKTOP-VJDMAUP\",\"ipv4s\":\"[]\"}"
  }
}
`

**The UI  get  data from the api :**
`
{"data":{"getServiceInstances":[{"key":"3","label":"w.com@DESKTOP-VJDMAUP","attributes":[{"name":"os_name","value":"WINNT"},{"name":"host_name","value":"DESKTOP-VJDMAUP"}]}]}}
`

**and the ui  display**
![image](https://user-images.githubusercontent.com/23736568/68918700-50d20f80-07aa-11ea-83a0-41a44fd25220.png)

**Comment by wu-sheng** [comment]
It is already back in the latest release.

![image](https://user-images.githubusercontent.com/5441976/68921210-ea052400-07b2-11ea-9634-33addf2e7398.png)
