### ISSUE TITLE
Grpc server thread pool is full, rejecting the task

### ISSUE THREAD

**Issue by czd890** [apache/skywalking#3863]
Using https://github.com/apache/skywalking-docker/blob/master/6/6.4/compose/docker-compose.yml to run test server. Throw "Grpc server thread pool is full, rejecting the task" after running for a while. Agent has very small requets(1/m);

**Comment by wu-sheng** [comment]
This depends on your backend and storage. If storage is blocking somehow, the queue may be full too. You need to find out what is blocking.
