### ISSUE TITLE
How to compile using Eclips/spring boot.we are getting errors in pom.xml 

### ISSUE THREAD

**Issue by rakeshs335** [apache/skywalking#3864]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I don't know. AFAIK, all committer team is using IntelliJ if they are developing the Java part. Any help from the Eclipse user is welcome, but we don't have experience with this. Sorry.
