### ISSUE TITLE
[CLI] Add command instance search to SkyWalking CLI

### ISSUE THREAD

**Issue by arugal** [apache/skywalking#3867]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

Command: 
+  ```swctl instance search --regex=projectB(.*)skywalking-server-0002 --service-id=5 --start=2019-11-15 --step=MONTH```
+  ```swctl instance search --regex=projectB(.*)skywalking-server-0002 --service-name=projectA --start=2019-11-15 --step=MONTH```

**Comment by arugal** [comment]
refer #3819

**Comment by wu-sheng** [comment]
@arugal Any progress?

**Comment by arugal** [comment]
The code is finished and PR will be submitted soon.

**Comment by arugal** [comment]
Ref [#15](https://github.com/apache/skywalking-cli/pull/15)
