### ISSUE TITLE
[Feature] Add Warp 10 as a storage option

### ISSUE THREAD

**Issue by hbs** [apache/skywalking#3871]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement

Support Warp 10 as the storage backend for metrics

**Comment by wu-sheng** [comment]
Proposal, design, and pull request are welcome. New storage implementation is open to 3rd part.
