### ISSUE TITLE
6.5版本

### ISSUE THREAD

**Issue by huguangjun580** [apache/skywalking#3875]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
我想知道6.5版本是不是不需要登录了，打开就直接显示页面了？
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only, Login has been removed a long time ago, please read the changelog.

**Comment by huguangjun580** [comment]
> 仅英语，登录很久以前已被删除，请阅读变更日志。

6.5版本连接es可以查看是否是连接成功的吗？
