### ISSUE TITLE
6.5版本可以用哪个版本的es?

### ISSUE THREAD

**Issue by huguangjun580** [apache/skywalking#3877]
使用最新版的es报错，换了5.6.8的依旧。
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : {properties={start_time={type=long}, id0={type=integer}, scope={type=integer}, id1={type=integer}, name={type=keyword}, alarm_message={copy_to=alarm_message_match, type=keyword}, alarm_message_match={analyzer=oap_analyzer, type=text}, time_bucket={type=long}}}]"}},"status":400}

**Comment by kezhenxu94** [comment]
please ask question in English here

we only support ElasticSearch [6, 7), and the support to ES 7+ is under construction #3613

**Comment by huguangjun580** [comment]
> 请在这里用英语问问题
> 
> 我们仅支持ElasticSearch [6，7），而对ES 7+的支持正在建设中[＃3613](https://github.com/apache/skywalking/pull/3613)

Specific 6. X? Where can I refer to? Or where is the specific version number of ES supported in skywalking program.

**Comment by huguangjun580** [comment]
> please ask question in English here
> 
> we only support ElasticSearch [6, 7), and the support to ES 7+ is under construction #3613

Specific 6. X? Where can I refer to? Or where is the specific version number of ES supported in skywalking program

**Comment by wu-sheng** [comment]
You should read document first. Rather than keeping asking questions included already.

**Comment by wu-sheng** [comment]
You should read document first. Rather than keeping asking questions included already.

**Comment by wu-sheng** [comment]
You should read document first. Rather than keeping asking questions included already.

**Comment by huguangjun580** [comment]
> 您应该先阅读文档。与其继续问问题已经包括在内。

[https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md](url)

**Comment by wu-sheng** [comment]
The version has been documented there

**Comment by huguangjun580** [comment]
I see it.
The ES-6.5.0 perfect support.
