### ISSUE TITLE
[Agent] Integrate the spanId into log components

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#388]
We have already supported to integrate the traceId into log components, I think we should support spanId either.

**Comment by wu-sheng** [comment]
Low priority requirement, no community feedback.

**Comment by ygsama** [comment]
If collection log with ELK and SkyWalking-6.1, we mast to Integrate the spanID or others in log components ourselves ?

**Comment by wu-sheng** [comment]
@ygsama The traceid is available there, we are welcome contribution to provide span id API.

**Comment by wu-sheng** [comment]
@tristaZero If you like to try agent contribution, this is a good one.

**Comment by dagmom** [comment]
> @tristaZero If you like to try agent contribution, this is a good one.

log spanId after traceId?

can i try contribute this issue @wu-sheng

**Comment by wu-sheng** [comment]
@dagmom If you want, welcome to do, but personally, I think #4545 is more meaningful?

**Comment by tristaZero** [comment]
Welcome. :-)
