### ISSUE TITLE
Question for tracing using gRPC

### ISSUE THREAD

**Issue by finnlee87** [apache/skywalking#3880]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Requirement

___
### Question
-  I have three springboot Applications demo-a, demo-b and demo-c.
demo-a call demo-b, and demo-b call demo-c using gRPC.
When i use SkyWalking, the tracing is demo-a -> demo-b, demo-b -> demo-c, it isn't demo-a -> demo-b -> demo-c

**Comment by wu-sheng** [comment]
You need to find out, whether demo-b has across threads scenario, if yes, you need a customized plugin to link them together.
