### ISSUE TITLE
Skywalking Agent 导致 Metaspace OOM

### ISSUE THREAD

**Issue by cnfree** [apache/skywalking#3890]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.4
JDK 8, CMS GC
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

规则引擎项目使用了 nashron script，规则会动态生成大量Class，但之前一直稳定运行，引入Skywalking agent以后，每隔几个小时就会 Metaspace out of memory，将 metaspace 空间提升到1G依然会发生，设置任何和 class 相关的jvm参数均没有效果，移除Skywalking agent后，再无该异常发生，可以判定skywalking对 nashron script 产生的 class 持有了引用，导致 soft reference 无法被回收而产生的Metaspace OOM

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
对这类case进行处理，或者能够通过配置忽略某些package

**Comment by cnfree** [comment]
![image](https://user-images.githubusercontent.com/1320575/69123960-ae819700-0add-11ea-98c6-6ee8d25a207d.png)

![image](https://user-images.githubusercontent.com/1320575/69123990-c3f6c100-0add-11ea-81c8-190a63f9f9d5.png)

![image](https://user-images.githubusercontent.com/1320575/69124028-d670fa80-0add-11ea-9df1-c0074e3a92a2.png)

**Comment by wu-sheng** [comment]
English only.
