### ISSUE TITLE
Proxying Apache SkyWalking with Apache WebServer under a different endpoint URL

### ISSUE THREAD

**Issue by TigerIcecold** [apache/skywalking#3895]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I have a Liferay CE (Java CMS) on Apache Tomcat and Apache SkyWalking installed on the same machine. Liferay is configured to work with the ports 8009, 8080 and 8443 and Apache Skywalking is configured to use TCP_8081. Now I would like to manage the web acces over the Apache Webserver and enable authentication for SkyWalking. So I'd like to have the same hostname for both and Liferay should use the root URL location "/" and SkyWalking should use something like /skywalking - so:

Liferay:         mywebsite.com
SkyWalking: mywebsite.com/skywalking

Unfortunately SkyWalking doesn't work like this. It works only if it is proxied as root (/).
My experiments with the Apache Webserver mod_proxy_html weren't successful.

So, now there are two possibilities:

1) Does anybody know how to proxy Apache SkyWalking wit the Apache WebServer under a different endpoint URL?

2) Or is it possible to configure Apache SkyWalking to start under a different endpont URL, like localhost:8081/skywalking? Like this it would be very easy to proxy it.

I would like to not create a separate virtual host in Apache WebServer for this.

Thank you kindly in advance
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.5.0, Ubuntu 19.10, Azul OpenJDK 11.0.5
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
AFAIK, there is no config way to change root path of current UI. The only option may be changing the source codes.
