### ISSUE TITLE
[CLI] Heatmap graph for CLI

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#3897]
Adding this issue to track, is it possible to support the heatmap graph in CLI? CLI is not good at visualization heatmap, especially it is not colored. But we may could provide heatmap by a table or something similar, not perfect but usable.

**Comment by kezhenxu94** [comment]
> especially it is not colored

It's possible to color the terminal, with what I've found https://github.com/gizak/termui , and I'm re-implementing the [metrics command](https://github.com/apache/skywalking-cli/pull/14) with this library, because the original library doesn't support x-axis labels
