### ISSUE TITLE
Unable to launch skywalking in k8s

### ISSUE THREAD

**Issue by zhengcan** [apache/skywalking#3901]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.5.0

- Which company or project?
Demo

- What happen?
By using https://github.com/apache/skywalking-kubernetes, the k8s reports:
```
Wait helm template failed. Error: render error in "skywalking/templates/oap-deployment.yaml": template: skywalking/templates/oap-deployment.yaml:65:10: executing "skywalking/templates/oap-deployment.yaml" at <include "skywalking.containers.wait-for-es" .>: error calling include: template: skywalking/templates/_helpers.tpl:60:63: executing "skywalking.containers.wait-for-es" at <include "call-nested" (list . "elasticsearch" "elasticsearch.client.fullname")>: error calling include: template: skywalking/templates/_helpers.tpl:53:4: executing "call-nested" at <include $template (dict "Chart" (dict "Name" $subchart) "Values" (index $dot.Values $subchart) "Release" $dot.Release "Capabilities" $dot.Capabilities)>: error calling include: template: no template "elasticsearch.client.fullname" associated with template "gotpl" : exit status 1; waiting on helm-controller_c-swljp
```
I've checked the values.yml, and there is a `elasticsearch.client.name` instead of `elasticsearch.client.fullname`.

And, I've tried https://github.com/apache/skywalking-docker, the k8s reports:
```
org.apache.skywalking.oap.server.starter.OAPServerStartUp -10646 [main] ERROR [] - dataSource or dataSourceClassName or jdbcUrl is required.
```
I've checked the docker-entrypoint.sh, and it lost any important settings of mysql:
```
generateStorageMySQL() {
    cat <<EOT >> ${var_application_file}
storage:
  mysql:
    metadataQueryMaxSize: \${SW_STORAGE_H2_QUERY_MAX_SIZE:5000}
EOT
}
```

**Comment by wu-sheng** [comment]
Due to Apache license rules, the MySQL driver can't be included in the official image. You have to add the driver lib by yourself and repackage image by yourself.

**Comment by wu-sheng** [comment]
The scripts generate the YAML right as you set storage as MySQL.

**Comment by zhengcan** [comment]
1. Here are two issues, one for k8s, one for docker. Maybe I should split this ticket to two tickets.

2. I've added mysql driver, but the the script generate mysql configuration without url & driver.
It was totally different with what https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md mentioned.

**Comment by wu-sheng** [comment]
Yes, that is a bug of the docker image, it should be republished.

**Comment by wu-sheng** [comment]
@hanahmily Startup shell is not sync to the main branch, which has been changed. https://github.com/apache/skywalking-docker/blob/master/6/6.5/oap/docker-entrypoint.sh MySQL parameter has been added into the main YAML.

**Comment by wu-sheng** [comment]
> I've checked the values.yml, and there is a elasticsearch.client.name instead of elasticsearch.client.fullname.

@innerpeacez Could you identify this?

**Comment by innerpeacez** [comment]
> Wait helm template failed. Error: render error in "skywalking/templates/oap-deployment.yaml": template: skywalking/templates/oap-deployment.yaml:65:10: executing "skywalking/templates/oap-deployment.yaml" at <include "skywalking.containers.wait-for-es" .>: error calling include: template: skywalking/templates/_helpers.tpl:60:63: executing "skywalking.containers.wait-for-es" at <include "call-nested" (list . "elasticsearch" "elasticsearch.client.fullname")>: error calling include: template: skywalking/templates/_helpers.tpl:53:4: executing "call-nested" at <include $template (dict "Chart" (dict "Name" $subchart) "Values" (index $dot.Values $subchart) "Release" $dot.Release "Capabilities" $dot.Capabilities)>: error calling include: template: no template "elasticsearch.client.fullname" associated with template "gotpl" : exit status 1; waiting on helm-controller_c-swljp

Please execute `helm dep up ` at the root of the SW chart.

**Comment by innerpeacez** [comment]
SW chart depends on the es chart in the official chart repo , you need to pull first the es chart.

**Comment by hanahmily** [comment]
> @hanahmily Startup shell is not sync to the main branch, which has been changed. https://github.com/apache/skywalking-docker/blob/master/6/6.5/oap/docker-entrypoint.sh MySQL parameter has been added into the main YAML.

fixed it and re-push apache/skywalking-oap-server:6.5.0

**Comment by wu-sheng** [comment]
@zhengcan I think you should be good to go now. Follow the new entry file, and update the image locally with adding the MySQL driver in.

**Comment by zhengcan** [comment]
I've tested the new script, and it works well as expected.

But because I'm using k8s with rancher to deploy the skywalking, it's really hard to make it work without build my own image, which include mysql driver as default.
I've tried several solutions, includes:
- download the driver by sidecar, and use `lifecycle/postStart` to copy it to oap-libs
- download the driver by sidecar, and set JAVA_OPTS to `-cp folder/mysql.jar`
- and more
All of them are failed.

I wish the `docker-entrypoint.sh` not only load jars in oap-libs, but also an additional folder, for example:
```
CLASSPATH="config:$CLASSPATH"
for i in oap-libs/*.jar
do
    CLASSPATH="$i:$CLASSPATH"
done
for i in oap-libs-additional/*.jar
do
    CLASSPATH="$i:$CLASSPATH"
done
```

Thanks.

**Comment by zhengcan** [comment]
> SW chart depends on the es chart in the official chart repo , you need to pull first the es chart. @ zhengcan

I don't know how to do it in rancher :(
Let me do more researches...

**Comment by wu-sheng** [comment]
Thanks for the feedback. I agree, sidecar injection makes sense. @hanahmily @innerpeacez Do you think it makes sense? If yes, either of you, or @zhengcan could submit the pull request to change the main startup script.

**Comment by hanahmily** [comment]
@zhengcan 
you may try following steps to figure it out.

 * Build an image with mysql jar.
 * Set an `emptyDir` in volumn.
 * Add MySQL container to `initContianers`, then `cp` MySQL jars to `emptyDir`.
 * Load `emptyDir` to OAP container. 
 * Pick up `CLASSPATH` to load mysql driver jars. then `docker-entrypoint.sh` will load them automatically.

```
# The jars that user specific will follow "config".
CLASSPATH="config:$CLASSPATH"
for i in oap-libs/*.jar
do
    CLASSPATH="$i:$CLASSPATH"
done
```

If any luck, pls keep me posted.

**Comment by zhengcan** [comment]
Yes, I can use CLASSPATH to inject mysql driver. Thanks.
