### ISSUE TITLE
MariaDB doesn't appear in the topology view and is completely not recognized by SkyWalking

### ISSUE THREAD

**Issue by TigerIcecold** [apache/skywalking#3907]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
I'd like to monitor my Liferay Portal CE 7.2 GA1 instance with Apache SkyWalking 6.5.0. Liferay is a Java CMS. On that DEV environment following software is installed: Ubuntu 18.04.3 LTS, OpenJDK 11.0.4, Apache Tomcat 9.0.17 and MariaDB 10.1.41 as Liferay storage.

In than configuration the MariaDB database is not recognized by SkyWalking completely.

On a different VM with Ubuntu 19.10, Azul Zulu JDK 11.0.5 and MySQL 5.7.28 Skywalking recognizes the DB just fine. On that environment the DB is a different server, on the first one everything is on one machine.

Is that a bug or SkyWalking just doesn't work with MariaDB and it's a missing Feature? Or coud it be a configuration issue? (Config is on both environments is similar).

Thank you.

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.5.0, Ubuntu 18.04.3 LTS, OpenJDK 11.0.4, Apache Tomcat 9.0.17 and MariaDB 10.1.41
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
SkyWalking doesn't "see" the MariaDB database of the monitored application.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Do you read the supported-list doc? https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#supported-middleware-framework-and-library. SkyWalking's auto-detection is totally based on variable plugins. I am assuming the MariaDB has its own driver, right?

Could you try to follow MySQL driver plugin and contribute one to us?

**Comment by TigerIcecold** [comment]
I have migrated the my DB from MariaDB to MySQL. Now tracing works.

**Comment by wu-sheng** [comment]
I see. I still hope someone could contribute MariaDB driver plugin

**Comment by wu-sheng** [comment]
@TigerIcecold The plugin has been provided.
