### ISSUE TITLE
skywalking-ui reports error as the result of query endpoints

### ISSUE THREAD

**Issue by zhengcan** [apache/skywalking#3908]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.5.0

- Which company or project?
Demo

- What happen?
I've installed a new skywalking instance, includes oap-server and ui.

The ui throws error when I try to list all endpoints.
The browser send the following request:
```
{"query":"query queryEndpoints($serviceId: ID!, $keyword: String!) {
    getEndpoints: searchEndpoint(serviceId: $serviceId, keyword: $keyword, limit: 100) {
      key: id
      label: name
    }
}","variables":{"keyword":""}}
```
And server responses:
```
{"errors":[{"message":"Variable 'serviceId' has coerced Null value for NonNull type 'ID!'"}]}
```

The log of ui are:
```
...
2019-11-20 13:18:34.181 INFO 1 --- [nio-8080-exec-7] c.n.l.DynamicServerListLoadBalancer : DynamicServerListLoadBalancer for client collector initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=collector,current list of Servers=[localhost:12800],Load balancer stats=Zone stats: {unknown=[Zone:unknown; Instance count:1; Active connections count: 0; Circuit breaker tripped count: 0; Active connections per server: 0.0;]
},Server stats: [[Server:localhost:12800; Zone:UNKNOWN; Total Requests:0; Successive connection failure:0; Total blackout seconds:0; Last connection made:Thu Jan 01 00:00:00 GMT 1970; First connection made: Thu Jan 01 00:00:00 GMT 1970; Active Connections:0; total failure count in last (1000) msecs:0; average resp time:0.0; 90 percentile resp time:0.0; 95 percentile resp time:0.0; min resp time:0.0; max resp time:0.0; stddev resp time:0.0]
]}ServerList:com.netflix.loadbalancer.ConfigurationBasedServerList@36743aa4
...
```

I've check the data in database, which is mysql, and it has the following data:
```
select * from service_inventory;
+----------------+------------+------------+------------+-----------+--------------------+------------+----------+---------------+----------------+------------------+
| id             | name       | is_address | address_id | node_type | mapping_service_id | properties | sequence | register_time | heartbeat_time | last_update_time |
+----------------+------------+------------+------------+-----------+--------------------+------------+----------+---------------+----------------+------------------+
| SkyWalking_0_0 | SkyWalking |          0 |          0 |         0 |                  0 | {}         |        2 | 1574255785986 |  1574256185983 |    1574255785986 |
+----------------+------------+------------+------------+-----------+--------------------+------------+----------+---------------+----------------+------------------+

select * from service_instance_inventory;
+------------------+---------------+------------+------------+------------+------------+------------+----------+---------------+----------------+------------------+
| id               | instance_uuid | name       | service_id | is_address | address_id | properties | sequence | register_time | heartbeat_time | last_update_time |
+------------------+---------------+------------+------------+------------+------------+------------+----------+---------------+----------------+------------------+
| 2_standalone_0_0 | standalone    | standalone |          2 |          0 |          0 | NULL       |        2 | 1574255790988 |  1574257095983 |                0 |
+------------------+---------------+------------+------------+------------+------------+------------+----------+---------------+----------------+------------------+

select * from endpoint_inventory;
Empty set (0.00 sec)

select * from network_address_inventory;
Empty set (0.00 sec)
```

**Comment by wu-sheng** [comment]
You are not giving serviceId, it is defined as required in GraphQL already.

**Comment by zhengcan** [comment]
The ui shows "Current Endpoint" in dropdown list. And when I click the dropdown list, the ui send graphql automatically, and get error automatically later.Nothing I can do, and nothing I can see in the list.No way to input service id, what I don't know.发自我的华为手机-------- 原始邮件 --------主题：Re: [apache/skywalking] skywalking-ui reports error as the result of query endpoints (#3908)发件人：吴晟 Wu Sheng 收件人：apache/skywalking 抄送：Zheng Can ,Author You are not giving serviceId, it is defined as required in GraphQL already.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/skywalking/issues/3908?email_source=notifications\u0026email_token=AAF747MZIUGSOOCIWAUEXW3QUU5VZA5CNFSM4JPS2ZV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEESAVHA#issuecomment-556010140",
"url": "https://github.com/apache/skywalking/issues/3908?email_source=notifications\u0026email_token=AAF747MZIUGSOOCIWAUEXW3QUU5VZA5CNFSM4JPS2ZV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEESAVHA#issuecomment-556010140",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wu-sheng** [comment]
Maybe a just UI bug? I don't know.

**Comment by zhengcan** [comment]
I found a related issue.
apache/skywalking-rocketbot-ui#202

**Comment by wu-sheng** [comment]
This is not a big issue. Wouldn't cause real issue.

**Comment by zhengcan** [comment]
Sometimes after a new fresh install, I can see a "Skywalker" in service list. Sometimes not.
I'm not sure whether it make sense.

I'll do more research to reproduce it...
