### ISSUE TITLE
can oap auto get host ip to register center  in cluster mode

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#3910]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
if I dont set gRPCHost: ${SW_CORE_GRPC_HOST:0.0.0.0} , can oap auto get host Ip or docker container ?

**Comment by wu-sheng** [comment]
We don't provide this, as mostly, the IP or hostname could be multiple. If you want to add this kind of feature, you could send a pull request, and we discuss there. WIll you?

**Comment by webb2019** [comment]
I very like to ,but I have a little trouble to understand the  meanings of  source code . I need to learn soure code further

**Comment by pkxiuluo** [comment]
have same problem.
but i think when grpcHost set 0.0.0.0  , we could throw an warn or error  for in cluster mode at lest.
and mention it in our doc。
