### ISSUE TITLE
How to clean up historical data?

### ISSUE THREAD

**Issue by bnubobby** [apache/skywalking#3911]
- What do you want to know?
After the system runs for a long time, it will pile up a lot of data
Some of them can be discarded and  how to delete data safely?

**Comment by bnubobby** [comment]
by the way
Start an skywalking  without elk index, and the index will be automatically created.
However, deleting the index during running will cause program errors，and can't recover
It would be great if it could recover automatically

**Comment by wu-sheng** [comment]
Read the documentation, TTL is included there.

> However, deleting the index during running will cause program errors，and can't recover
It would be great if it could recover automatically

No one designs a system like this. This makes no sense. Are you application able to recreate the database after you delete all tables? I don't think so.
