### ISSUE TITLE
How can I run the test in idea

### ISSUE THREAD

**Issue by ZhuoSiChen** [apache/skywalking#3916]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to run the test in my IDEA.So, I can follow the code。
Please， help me run the test.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
When I run the test in my IDEA. 

If possible, provide a way for reproducing the error. e.g. demo application, component version.
Error:(92, 173) java: 不兼容的类型: <匿名io.grpc.stub.StreamObserver<org.apache.skywalking.apm.network.common.Commands>>无法转换为org.apache.skywalking.apm.dependencies.io.grpc.stub.StreamObserver<org.apache.skywalking.apm.network.common.Commands>
Error:(174, 65) java: 不兼容的类型: io.grpc.Channel无法转换为org.apache.skywalking.apm.dependencies.io.grpc.Channel
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ZhuoSiChen** [comment]
I had follow the markdown How to build project.

**Comment by wu-sheng** [comment]
I don't know what you are doing. If you want to debug agent, read official blogs.
