### ISSUE TITLE
How can I monitor Abnormal offline of service

### ISSUE THREAD

**Issue by pyxzzfly** [apache/skywalking#3918]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
we used skywalking-5.0.0 and configure a agent for each application, but when the application service is hung up, we can't monitor the abnormal logoff of the service. Is there any way to monitor the offline situation?

**Comment by wu-sheng** [comment]
That is not SkyWalking landscape, at least not yet. You could easily use other projects to check process existing or ip:port listening. It existed long time ago.
