### ISSUE TITLE
the demo webSit   in  skywalking git hub  is broken

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#3928]
### Bug
the demo webSit   in  skywalking git hub  is broken

http://122.112.182.72:8080/comparison

the website have not any data

**Comment by wu-sheng** [comment]
Click the reload, it is working at my side. But, notice, there is no SLA for demo, don't count on that. This is never being treated as an issue.

**Comment by seifeHu** [comment]
![image](https://user-images.githubusercontent.com/7017464/69610581-0af92f00-1067-11ea-844d-d7ccf640b171.png)
![image](https://user-images.githubusercontent.com/7017464/69610611-2106ef80-1067-11ea-9e4e-dea8e8c47df8.png)

I got this

**Comment by wu-sheng** [comment]
What  conditions do you query for trace?
