### ISSUE TITLE
There is normal data return, but it does not render properly

### ISSUE THREAD

**Issue by shefenfei** [apache/skywalking#3929]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

![image](https://user-images.githubusercontent.com/8509482/69523588-39133c00-0f9f-11ea-9d3a-fa4f4e6251cd.png)

![image](https://user-images.githubusercontent.com/8509482/69523687-7b3c7d80-0f9f-11ea-8a21-4e92be0ec619.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If you are trying to open a broken trace, some segments missing somehow, then 6.4.0+ is the better choice. You will see the virtual node the tree view.
