### ISSUE TITLE
Runner helper doesn't work when using dependencies.

### ISSUE THREAD

**Issue by wayilau** [apache/skywalking#3932]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

As titles said that runner-helper doesn't work when we using Tomcat-container， also we add dependencies in the configuration.yml. Source code using dependencies size to check which 'template' to use. but it didn't tell differences about the start_script. so start_script is NULL when using tomcat container. It will make an error like this:
 [ERROR] - org.apache.skywalking.plugin.test.helper.DockerComposeRunningGenerator.generateAdditionFiles(DockerComposeRunningGenerator.java:90) - freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> start_script  [in template "docker-compose.template" at line 41, column 39]

here is the docker-compose.template line 41:
![image](https://user-images.githubusercontent.com/3197838/69591882-20526700-102f-11ea-9be9-970ba7ecb125.png)

**Comment by wu-sheng** [comment]
Could you submit a pull request to fix it?

**Comment by wayilau** [comment]
ok. @wu-sheng
