### ISSUE TITLE
Service list is blank

### ISSUE THREAD

**Issue by hillbun** [apache/skywalking#3935]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

docker image of apache/skywalking-oap-server:6.4.0

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Service list is blank, but trace datas exist
![111](https://user-images.githubusercontent.com/2617575/69604752-42f97580-1059-11ea-9b81-fe26b37d9874.png)

/graphql api payload:
![222](https://user-images.githubusercontent.com/2617575/69604760-47be2980-1059-11ea-8820-fb39fb90356a.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Search issue and read document first. Time or time zone is incorrect.
