### ISSUE TITLE
kafka 版本冲突

### ISSUE THREAD

**Issue by lvshouyang** [apache/skywalking#3936]
昨天部署skywalking到腾讯云生产环境，报如下异常
Magic v1 does not support record headers

腾讯云kafka版本（0.9.0 - 010.0）
skywalking agent  支持的kafka版本 0.11.0

请问有好的解决办法吗，腾讯云因为使用开源的所以无法升级版本。

**Comment by wu-sheng** [comment]
English only. And this is Tencent's issue. Not ours.
