### ISSUE TITLE
Kill release6.5 backupServer and webUI. restart the two process.There are some bugs.

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#3937]
### Bug

in windows 10  jre 8

I start skywalking in bin/startup.sh。 all the config is default 。
I run agent in two app services
first time ,I can  got  some traceing in the web ui 。
but ,I close the skywalking webUi,and collector .

when I restart again.

I got nothing in the web ui. I request my two app .There are not got any tracing.

**Comment by wu-sheng** [comment]
Reconnect is working at my side and checked in every PR commit. You may need to invest more.

**Comment by seifeHu** [comment]
2019-11-26 15:38:28,380 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpcServerPool-1-thread-10] WARN  [] - Service instance 2 heartbeat, but not found in storage.
2019-11-26 15:38:28,380 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 68 [grpcServerPool-1-thread-10] WARN  [] - Can't find service by service instance id from cache, service instance id is: 2, will send a reset command to agent side
2019-11-26 15:38:28,384 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMSourceDispatcher - 51 [grpcServerPool-1-thread-9] WARN  [] - Can't find service by service instance id from cache, service instance id is: 2

the error info is above

**Comment by wu-sheng** [comment]
This is not reboot, this is you have deleted the storage data or using h2 for demo. Then you need 10 mins for agent hot rebooting. We have said very clear in the document, please read them.

**Comment by seifeHu** [comment]
DEBUG 2019-11-26 16:44:08:160 DataCarrier.DEFAULT.Consumser.0.Thread TraceSegmentServiceClient : 5 trace segments have been sent to collector. 
DEBUG 2019-11-26 16:44:09:488 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2019-11-26 16:44:12:487 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 


my agent log is above .  
It seems  trace have been sent to collector.
Bug In the Ui I got nothing.

and where is the doc about agent hot reboot ? I have read  https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md

Thanks.

**Comment by seifeHu** [comment]
> ou have deleted the storage data or using h2 for demo

my config is default .so  It is use h2

**Comment by wu-sheng** [comment]
The hot reboot is from the backend command system. The document is there. Agent can't do hot reboot by itself.

**Comment by seifeHu** [comment]
I have read https://skyapm.github.io/document-cn-translation-of-skywalking/zh/master/setup/backend/backend-init-mode.html

I got  the log :
use oapServiceInit.bat
OAP starts up in init mode successfully, exit now...
but restart  oapService.bat
I got no trace in ui . 

Now  I change the storage h2 to ES . I use oapServiceInit fist  and waiting for init end .
and use  oapService.bat   restart 
see the log the table have been creating . 
But It still have not any trace in ui.  I got GET /_cat/indices?v In es  I can see the index is exsit。
But still I got no trace...   
I got the agent log 

DEBUG 2019-11-26 18:01:38:013 DataCarrier.DEFAULT.Consumser.0.Thread TraceSegmentServiceClient : 2 trace segments have been sent to collector. 
DEBUG 2019-11-26 18:01:38:013 DataCarrier.DEFAULT.Consumser.0.Thread TraceSegmentServiceClient : 10 trace segments have been abandoned, cause by no available channel.

**Comment by wu-sheng** [comment]
Read English doc and 6.5 doc. You are reading the wrong one.

**Comment by seifeHu** [comment]
> Read English doc and 6.5 doc. You are reading the wrong one.

I fixed it ! 
Look this pages...I click 清空。。。 everyProblem disappear
![image](https://user-images.githubusercontent.com/7017464/69635223-e6b14880-108e-11ea-82e6-a5fa7754ea09.png)

**Comment by wu-sheng** [comment]
This feature exists several months ago.
