### ISSUE TITLE
I want to report the trace data centrally manually

### ISSUE THREAD

**Issue by Cczzzz** [apache/skywalking#3938]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

We intend to use the message trace of rocketmq, but rocket does not provide a presentation layer. I think it's done through skywalking.
Basically one of my components will accept the message trace of all the messages in rocketmq and then manually report it to skywalking.

I need to change Trace's IP, time and some attributes. I want to customize the Trace information and report it manually

I didn't find the right way or the right way. Is skywalking supporting this

**Comment by wu-sheng** [comment]
We don't support this officially. You could change the codes by yourself, but we don't have this.
