### ISSUE TITLE
alarm-settings.yml support exclude-names

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#3939]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
why alarm-settings.yml support only include-names, but not exclude-names? I have some upload interfaces that take a long time，it will trigger the alarm  a lot
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
supoort exclude-names

**Comment by wu-sheng** [comment]
No difference from my side. No special reason.

**Comment by stalary** [comment]
> No difference from my side. No special reason.

So how do I rule out long response time endpoints

**Comment by wu-sheng** [comment]
I think you misunderstand my point, only have either exclude or include is same. So we have only one. If you want to support exclude, contribution is welcome.

**Comment by stalary** [comment]
> I think you misunderstand my point, only have either exclude or include is same. So we have only one. If you want to support both, contribution is welcome.

I have thousands of endpoints here, I have to write thousands of includes, so include can be cumbersome for me.

**Comment by stalary** [comment]
If the project design allows, I will support both recently

**Comment by wu-sheng** [comment]
I know. So I said if you want to add exclude, it is fine and welcome. But don't remove the include, which will cause others' issue. Do you get my point?

**Comment by stalary** [comment]
I know, I meant to just add exclude, sorry, I didn't make myself clear at first

**Comment by wu-sheng** [comment]
New feature is welcome.
