### ISSUE TITLE
Documents  Error In v6.5 ?

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#3942]
In 
https://github.com/apache/skywalking/blob/v6.5.0/docs/en/setup/service-agent/java-agent/README.md

logging.dir | Log files directory. Default is blank string, means, use "system.out" to output logs. | ""
-- | -- | --

I fact ,the log file dir use    {jarfile.dir}/../logs to create a skywalking-api.log

**Comment by wu-sheng** [comment]
Yes, I think this an error of document, and `org.apache.skywalking.apm.agent.core.conf.Config#Logging#DIR`. Would you send a pull request to fix this?

**Comment by seifeHu** [comment]
> Yes, I think this an error of document, and `org.apache.skywalking.apm.agent.core.conf.Config#Logging#DIR`. Would you send a pull request to fix this?

ok.
