### ISSUE TITLE
Add apdex score for Service metrics page and in default layout

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#3946]
Continue from #3822. Apdex is valuable for the service level measure. 

@Fine0830 Please add a linear graph in the Service metrics page and in default layout after #3822 merged(will be short). We will do redeploy on the demo env for the backend. The value of the response, 10000 means 1.0 for Apdex score, the value should be 0 < score <= 1.0, so, you need to divide 10000 and show as float type. 

### For Apdex score,

Apdex score
The Apdex score is a ratio value of the number of satisfied and tolerating requests to the total requests made. Each satisfied request counts as one request, while each tolerating request counts as half a satisfied request.

An Apdex score varies from 0 to 1, with 0 as the worst possible score (100% of response times were Frustrated), and 1 as the best possible score (100% of response times were Satisfied).

**Comment by Fine0830** [comment]
Got it.

> Continue from #3822. Apdex is valuable for the service level measure.
> 
> @Fine0830 Please add a linear graph in the Service metrics page and in default layout after #3822 merged(will be short). We will do redeploy on the demo env for the backend. The value of the response, 10000 means 1.0 for Apdex score, the value should be 0 < score <= 1.0, so, you need to divide 10000 and show as float type.
> 
> ### For Apdex score,
> Apdex score
> The Apdex score is a ratio value of the number of satisfied and tolerating requests to the total requests made. Each satisfied request counts as one request, while each tolerating request counts as half a satisfied request.
> 
> An Apdex score varies from 0 to 1, with 0 as the worst possible score (100% of response times were Frustrated), and 1 as the best possible score (100% of response times were Satisfied).

Got it.

**Comment by wu-sheng** [comment]
And replace this one in the default layout, 

![image](https://user-images.githubusercontent.com/5441976/69702164-8cb19100-1129-11ea-9d8c-91fb61da187c.png)

Apdex default layout could ref the response time's. A avg value plus a linear graph.
![image](https://user-images.githubusercontent.com/5441976/69702216-ab178c80-1129-11ea-8656-5cad4eab3555.png)

**Comment by wu-sheng** [comment]
@Fine0830 Apdex PR merged, we will update the demo env soon. Then you could it to add apdex at service dashboard page.

**Comment by Fine0830** [comment]
> @Fine0830 Apdex PR merged, we will update the demo env soon. Then you could it to add apdex at service dashboard page.

noted, thanks.

**Comment by wu-sheng** [comment]
Added.
