### ISSUE TITLE
Add VictoriaMetrics storage backend

### ISSUE THREAD

**Issue by valyala** [apache/skywalking#3951]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
It would be great to add [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/) as storage backend for metrics collected by `SkyWalking`. VictoriaMetrics is optimized for speed and it provides the best on-disk compression ratio. It can accept metrics via any supported ingestion protocol:
- Prometheus remote_write protocol
- [Influx line protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf)
- [Graphite plaintext protocol with tags](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-send-data-from-graphite-compatible-agents-such-as-statsd)
- [OpenTSDB put protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-send-data-from-opentsdb-compatible-agents)

Stored metrics can be queried either via [PromQL](https://medium.com/@valyala/promql-tutorial-for-beginners-9ab455142085) or via [/api/v1/export](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-export-time-series) endpoint.

**Comment by wu-sheng** [comment]
Our storage APIs are open, if you have any proposal about how to implement those, we are glad to discuss the detail. @dmsolr is working on the prototype of using MySQL(or other traditional DB) + Influx DB to as a new storage option.

**Comment by valyala** [comment]
Thanks for the pointers! I and @dlazerka will look into how to add storage backend plugin for VictoriaMetrics.

**Comment by wu-sheng** [comment]
We have a document to show you the interfaces. After yoh read the design, consider to start from https://github.com/apache/skywalking/blob/master/docs/en/guides/storage-extention.md

We may have more interfaces listed there, but basic ideas are same.
