### ISSUE TITLE
Is possible can do search log with traceId  from elasticSearch In skywalking UI 

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#3957]
### Question
- What do you want to know?
Is possible can do search log with traceId  from elasticSearch In skywalking UI 
I  running skywalking In my microservices.
And I depoly Elk for collector apps logs 

If  I can do search log In skywalking . It will be a good features.

**Comment by wu-sheng** [comment]
I think ELK could provide a good UI for this, why do you want SkyWalking do this?
