### ISSUE TITLE
Skywalking追踪异步方法时，查到的调用链时间有点奇怪

### ISSUE THREAD

**Issue by tinet-shenjg** [apache/skywalking#3969]
![image](https://user-images.githubusercontent.com/25969983/69841593-d66db900-129a-11ea-8a92-e85568dc8c67.png)

**Comment by tinet-shenjg** [comment]
![image](https://user-images.githubusercontent.com/25969983/69849225-12167c00-12b7-11ea-85d8-32703e4a9b94.png)

**Comment by wu-sheng** [comment]
English only.
