### ISSUE TITLE
if only agent client in my server ,  no skywalking server or skywalking server has stoped, could my  server  be influenced ?

### ISSUE THREAD

**Issue by snowWave1995** [apache/skywalking#3970]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
if only agent client in my server ,  no skywalking server or skywalking server has stoped, could my  server  be influenced ? （如果我的服务中启动了skywalking的客户端，但是我没有部署对应的skywalking服务端 或者skywalking服务端挂了  这种情况对我的服务本身有影响吗 服务性能是否会被影响）

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dmsolr** [comment]
It is almost not affected.
