### ISSUE TITLE
How to integrate istio tracing with Skywalking 

### ISSUE THREAD

**Issue by JayWu890225** [apache/skywalking#3971]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ☑️] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.4
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

I followed below step to create the skywalking adapter for istio and related metrics transform to skywalking successful.
https://github.com/apache/skywalking/blob/master/docs/en/setup/istio/README.md
But Skywalking tracing is not available.
I found endpoint relation table don't have any data after check the skywalking data source.

So my question is  whether this adapter can collected tracing data ?

**Comment by wu-sheng** [comment]
If you want trace, you could use zipkin or jaeger receiver, plus zipkin-es or jaeger-es storage.
