### ISSUE TITLE
Can edit alarm configuration directly in skywalking's console?

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#3974]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
Can edit alarm configuration directly in skywalking's console. Like grafana.

At present, I need to modify the configuration file and restart the service, or I need to introduce other middleware, such as zk,nacos.

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Add edit interface，and store config to stores the configuration to the specified storage

**Comment by wu-sheng** [comment]
Alarm rule could be changed by Dynamic Configuration, including DCS(gRPC), ZK, or other config centers. You could read this, https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/dynamic-config.md
