### ISSUE TITLE
Why the skywalking UI does not show the Service，the oap and agent use default configuration

### ISSUE THREAD

**Issue by Passeng-LUCA** [apache/skywalking#3975]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
    Why my local skywalking UI show the data but does not show the service,the oapService and agent use the default  config, is h2 storage and agent.service_name is config by JVM options set -DSW_AGENT_NAME=demo;
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking:6.5.0
OS:Windows7
JRE:1.8.0_191
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

the datasource has init in the application start so there are data , but do not show the demo service name, my config is not right ,please let me know thanks!
___
![1575029516738_8672AF8A-3F43-47c2-BA39-645A680C1CC0](https://user-images.githubusercontent.com/13777117/69868438-a9de8f00-12e4-11ea-9f1d-6743f38d5561.png)
![1575029586429_D3517421-54A8-40da-B343-48E1A58F6BC1](https://user-images.githubusercontent.com/13777117/69868441-aa772580-12e4-11ea-9ead-1a1b8e918351.png)

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Follow the document please, make sure you set the time and TZ matched among the target application, OAP server and browser.
