### ISSUE TITLE
trace segment display position is incorrect in the UI

### ISSUE THREAD

**Issue by ghost** [apache/skywalking#3984]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
In the example in the figure below, the actual position of the second segment should start the hystrix call after the second redis span, but the position shown in the figure below is placed at the end.

![WechatIMG137](https://user-images.githubusercontent.com/2892433/70370803-cb540200-1906-11ea-959e-a9ef707e2239.jpeg)

**Comment by wu-sheng** [comment]
Basically, you are talking about ShardingSphere plugin issue. So I am forwarding this to @tuohai666 @tristaZero @terrymanu

**Comment by wu-sheng** [comment]
Ref to #3777 due to related maybe.

**Comment by wu-sheng** [comment]
@aderm Also, you should have been familiar with SkyWalking plugin system, you could try to debug and find out why first.

**Comment by aderm** [comment]
OK, let ’s take a closer look at this question

**Comment by aderm** [comment]
#4034

**Comment by tuohai666** [comment]
I guess what @aderm mentioned is about the trace order which is similar with what I had met before in https://github.com/apache/skywalking/issues/1657

I am not sure ShardingSphere plugin how to affect hystrix. Any suggestions?
