### ISSUE TITLE
Can't find the link to download the apache-skywalking-bin-es7.tar.gz or apache-skywalking-bin-es7.zip

### ISSUE THREAD

**Issue by ZhuoSiChen** [apache/skywalking#3991]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
according the doc [backend-storage.md](https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#elasticsearch)
I can't find the link to download the apache-skywalking-bin-es7.tar.gz or apache-skywalking-bin-es7.zip.
Can any one tell me? 
Thank~
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Because they are not released yet. They are new features in 6.6.0

**Comment by adventurer2008** [comment]
ES7.0+can't be supported by skywalking 6.5,  which has some errors when starting up. Hopefully skywalking 6.6 soon release.

**Comment by wu-sheng** [comment]
We have unfinished features in 6.6.0, we will try to release in the next month.
