### ISSUE TITLE
Is any sulotion send a traceId from web front page to   app server(which run with skywalking agent)?

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#3993]
### Question
If I want to know a trace chain from webUi ->app->mysql
How can I do ?

**Comment by wu-sheng** [comment]
What do you mean webUI? Are you talking about Browser?

**Comment by seifeHu** [comment]
> What do you mean webUI? Are you talking about Browser?

Yes .  I am talking ablout  trace from brower or trace from a c++ native client

**Comment by wu-sheng** [comment]
No, we don't have that. In theory, it is possible, but the cost will be high on network. You need to build your own client lib to follow the SkyWalking protocol.

**Comment by seifeHu** [comment]
> it is possible, but the cost will be high on network. You need to build your own client lib to follow the SkyWalking protocol.

Yes. I think you are right .Do this will cost hign.  But  some time.  Browser can do this  manually .

Can I send http  msg with http header 
```
key=sw3
value= 1.2343.234234234|1|1|1|#127.0.0.1:8080|#/portal/|#/testEntrySpan|1.2343.234234234
```
to app server ?

and do not send   this header to collector ?
So  skywalking can send tracing this msg ???

**Comment by wu-sheng** [comment]
Header is for propagation, it is just required in the HTTP header. But you need to register your agent and send the trace segments to the backend. There are two protocols, header and trace protocols.

**Comment by seifeHu** [comment]
> Header is for propagation, it is just required in the HTTP header. But you need to register your agent and send the trace segments to the backend. There are two protocols, header and trace protocols.

I got , I will try to propagation to see .tks

**Comment by seifeHu** [comment]
> Header is for propagation, it is just required in the HTTP header. But you need to register your agent and send the trace segments to the backend. There are two protocols, header and trace protocols.

I can open the zipkin-recevier .  ask webbrower  and  native client use zipkin sdk .

**Comment by wu-sheng** [comment]
> I can open the zipkin-recevier . ask webbrower and native client use zipkin sdk .

That would not work in that way.
