### ISSUE TITLE
Failed to startup when use cluster with consul

### ISSUE THREAD

**Issue by gonedays** [apache/skywalking#4000]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
 Question or discussion
 Seems looks like [https://github.com/apache/skywalking/issues/3069](url)

___
### Question
- What do you want to know?
Why failed to start up?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking: 6.5.0
OS: centos7
JER: openjdk version "1.8.0_232"

- Which company or project?
test 

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Settings in application.yml:
![1](https://user-images.githubusercontent.com/11483620/70119094-82047800-16a4-11ea-82d9-22cbd86fefb4.png)

 Error log:
![2](https://user-images.githubusercontent.com/11483620/70119110-892b8600-16a4-11ea-8be3-3cb2f7cd0c13.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
@gonedays From the source codes of Consul, none of your consul server nodes is healthy, after some time the all of them are put into blacklist(`com.orbitz.consul.util.failover.strategy.BlacklistingConsulFailoverStrategy#markRequestFailed`), and finally you got `no value present` exception, check your consul nodes please
