### ISSUE TITLE
Is the default configuration of dataKeeperExecutePeriod reasonable

### ISSUE THREAD

**Issue by bingwangzi1988** [apache/skywalking#4001]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ✔️] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The default configuration of 6.5.0's storage is elasticsearch. ES delete history by indexName, and these indexes are created by day or month, but the default value of dataKeeperExecutePeriod is 5 minutes, they don't match.

Should dataKeeperExecutePeriod be adjusted to one day？
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think that is because when we do TTL in MySQL, TiDB, ShardingSphere. They are minute level, that is why. If you want to make it reasonable, they you need to separated different storage, it is possible. Do you want to contribute this?

**Comment by bingwangzi1988** [comment]
Now I'm not very familiar with skywalking，maybe I can contribute later.
