### ISSUE TITLE
I want to know the creation strategy of skywalking's es index

### ISSUE THREAD

**Issue by AirTrioa** [apache/skywalking#4002]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion

___
### Question
- What do you want to know?

I checked all indexes of skywalking and found that there are two kinds of indexes: one is with time suffix, the other is without time suffix. 
Now I want to know how this index with time suffix is created? Is there a scheduled task running? Or is it directly generated before inserting data using the resthighlevelclient feature?
Also, I would like to know if skywalking has a scheduled task? Thank you for your answer.

**Comment by kezhenxu94** [comment]
@AirTrioa for an open-sourced project, all sorts of the questions can be answered by the source codes themselves.

> I checked all indexes of skywalking and found that there are two kinds of indexes: one is with time suffix, the other is without time suffix.

For those indices with suffix (ES), we use index template, and the indices will be automatically created by ES as long as they match the template name.

> Also, I would like to know if skywalking has a scheduled task? Thank you for your answer.

Yes, the class https://github.com/apache/skywalking/blob/master/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/storage/ttl/DataTTLKeeperTimer.java is what you're asking for
