### ISSUE TITLE
How to filter the enhance instance from difference package.

### ISSUE THREAD

**Issue by ZhuoSiChen** [apache/skywalking#4004]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to enhance the  instance  in my package and method was be annotation by @ Bean ，but not in the spring package.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I am not following your question. I don't think SkyWalking is blocking you from this. What do you mean how?

**Comment by ZhuoSiChen** [comment]
I suddenly understand how to do it. I just need to implement my customized indirectmatch and implement the methods in it. My idea is that skywalking only enhances the @ bean annotation in my package, but not the spring's own.

**Comment by wu-sheng** [comment]
> My idea is that skywalking only enhances the @ bean annotation in my package, but not the spring's own.

Yes, because we have concern too many spans created, which could cause performance issue. And in most cases, observing the beans inside Spring framework, it is not helpful.
