### ISSUE TITLE
Spring-annotation-plugin invoke app crash when intecept class with private constructor

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#4005]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I hava a class with @Service annoation  in my app ,  like below:

@Service
public class  UserService
{
     private UserService(){}
}

when release  app to tomcat ,and startup , then my app crashed . 
the log says:  occur something " cblig error ".
How to resolve this problem?

**Comment by wu-sheng** [comment]
I don't know actually, it depens why cglib error.

**Comment by webb2019** [comment]
> I don't know actually, it depens why cglib error.

I want to ignore the class matching @service has no public constructor  
how to modify spring-annotaion-plugin source to suport this?

**Comment by wu-sheng** [comment]
I haven't done this before. Change the method matcher method? I think.
