### ISSUE TITLE
Expect the function of clearing historical trace data with one click in UI

### ISSUE THREAD

**Issue by aderm** [apache/skywalking#4008]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
In the system test process, there are often many times of transaction pressure test. After each short test is completed, hope that the historical data can be quickly cleaned up and start the next round of testing. don't want to wait for the rolling time or manually clear it or select time range. One-click cleanup button is necessary. To prevent accidental deletion, you can add a confirmation.
even like grafana, UI provide choice last 3s/last 1min/last 5min etc.

**Comment by wu-sheng** [comment]
That is nearly impossible in production env. Once you provide this feature, the user may use this in the production env, then it will cause all ES and OAP cluster crash down.

**Comment by wu-sheng** [comment]
The risk is not about confirmation, it is the health of the whole cluster.

**Comment by aderm** [comment]
It is true that the immutability of the ES underlying index determines that it is relatively inefficient to delete data. In addition, is it possible to provide functions such as ES cluster reinitialization? At the same time, each agent service is required to register again.

**Comment by wu-sheng** [comment]
Re-Register is provided already. If you want to do this, you could do manually, I don't think this should be a UI feature too.
