### ISSUE TITLE
s there an official test report about OAP clusters?

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4009]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Official test report for what?

**Comment by EvanLjp** [comment]
Sorry ,please close the issue ,I find I cannot edit the content when I press the enter ,so I will submit a new standard issue ,thanks for your help

2019年12月6日 上午9:04，吴晟 Wu Sheng <notifications@github.com<mailto:notifications@github.com>> 写道：


Official test report for what?
