### ISSUE TITLE
How to integrate with logstash-logback-encoder in json format

### ISSUE THREAD

**Issue by gonedays** [apache/skywalking#4016]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
We use logstash-logback-encoder in custom json format, but failed to print TID in log file.

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking: 6.5.0
OS: linux or windows
JRE: JDK8
logback-core: 1.1.11

- Which company or project?
test

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
1. Add dependency in maven pom.xml
  ```
<dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>5.1</version>
        </dependency>
    <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
            <version>6.5.0</version>
        </dependency>
```

2. config logback xml
```
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <mdc/>
                <timestamp>
                    <timeZone>UTC</timeZone>
                </timestamp>
                <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider"/>
                <pattern>
                    <pattern>
                        {
                        "level": "%level",
                        "ip": "${IP}",
                        "service": "${APP_NAME:-}",
                        "trace": "%X{X-B3-TraceId:-}",
                        "TID": "%X{TID}",
                        "tid": "%X{tid}",
                        "span": "%X{X-B3-SpanId:-}",
                        "exportable": "%X{X-Span-Export:-}",
                        "pid": "${PID:-}",
                        "thread": "%thread",
                        "class": "%logger{1.}:%L",
                        "message": "%message",
                        "stackTrace": "%exception{10}"
                        }
                    </pattern>
                </pattern>
            </providers>
        </encoder>
```

3. No TID in log file.
log example:
```
{"@timestamp":"2019-12-06T07:52:10.162+00:00","level":"INFO","ip":"169.254.234.242","service":"dlsgateway","trace":"","TID":"","tid":"","span":"","exportable":"","pid":"17352","thread":"http-nio-8989-exec-1","class":"com.netflix.loadbalancer.DynamicServerListLoadBalancer:222","message":"Using serverListUpdater PollingServerListUpdater","stackTrace":""}
```

With above configuration, faield to print TID, but with below configuration, it works:
```
 <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
                <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level logger_name:%logger{36} - [%tid] - message:%msg%n</pattern>
            </layout>
        </encoder>
```

Please help how to handle it.  Appreciate your help.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by gonedays** [comment]
> Please answer these questions before submitting your issue.
> 
> * Why do you submit this issue?
> * [x]  Question or discussion
> * [ ]  Bug
> * [ ]  Requirement
> * [ ]  Feature or performance improvement
> 
> ### Question
> * What do you want to know?
>   We use logstash-logback-encoder in custom json format, but failed to print TID in log file.
> 
> ### Bug
> * Which version of SkyWalking, OS and JRE?
>   SkyWalking: 6.5.0
>   OS: linux or windows
>   JRE: JDK8
>   logback-core: 1.1.11
> * Which company or project?
>   test
> * What happen?
>   If possible, provide a way for reproducing the error. e.g. demo application, component version.
> 
> 1. Add dependency in maven pom.xml
> 
> ```
> <dependency>
>           <groupId>net.logstash.logback</groupId>
>           <artifactId>logstash-logback-encoder</artifactId>
>           <version>5.1</version>
>       </dependency>
>   <dependency>
>           <groupId>org.apache.skywalking</groupId>
>           <artifactId>apm-toolkit-logback-1.x</artifactId>
>           <version>6.5.0</version>
>       </dependency>
> ```
> 
> 1. config logback xml
> 
> ```
> <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
>             <providers>
>                 <mdc/>
>                 <timestamp>
>                     <timeZone>UTC</timeZone>
>                 </timestamp>
>                 <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider"/>
>                 <pattern>
>                     <pattern>
>                         {
>                         "level": "%level",
>                         "ip": "${IP}",
>                         "service": "${APP_NAME:-}",
>                         "trace": "%X{X-B3-TraceId:-}",
>                         "TID": "%X{TID}",
>                         "tid": "%X{tid}",
>                         "span": "%X{X-B3-SpanId:-}",
>                         "exportable": "%X{X-Span-Export:-}",
>                         "pid": "${PID:-}",
>                         "thread": "%thread",
>                         "class": "%logger{1.}:%L",
>                         "message": "%message",
>                         "stackTrace": "%exception{10}"
>                         }
>                     </pattern>
>                 </pattern>
>             </providers>
>         </encoder>
> ```
> 
> 1. No TID in log file.
>    log example:
> 
> ```
> {"@timestamp":"2019-12-06T07:52:10.162+00:00","level":"INFO","ip":"169.254.234.242","service":"dlsgateway","trace":"","TID":"","tid":"","span":"","exportable":"","pid":"17352","thread":"http-nio-8989-exec-1","class":"com.netflix.loadbalancer.DynamicServerListLoadBalancer:222","message":"Using serverListUpdater PollingServerListUpdater","stackTrace":""}
> ```
> 
> With above configuration, faield to print TID, but with below configuration, it works:
> 
> ```
>  <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
>             <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
>                 <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level logger_name:%logger{36} - [%tid] - message:%msg%n</pattern>
>             </layout>
>         </encoder>
> ```
> 
> Please help how to handle it. Appreciate your help.
> 
> ### Requirement or improvement
> * Please describe about your requirements or improvement suggestions.

Get solution for this, just add the Converter in logback.xml:
```
<configuration>
<conversionRule conversionWord="tid" converterClass="org.apache.skywalking.apm.toolkit.log.logback.v1.x.LogbackPatternConverter"/>

<!--appender-->
<appender name="logstash" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${LOG_PATH:-.}/${APP_NAME}/${APP_NAME}_json.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${LOG_PATH:-.}/${APP_NAME}/${APP_NAME}_json.log.%d{yyyy-MM-dd}.gz</fileNamePattern>
            <maxHistory>30</maxHistory>
        </rollingPolicy>
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <timestamp>
                    <timeZone>UTC</timeZone>
                </timestamp>
                <pattern>
                    <pattern>
                        {
                        "level": "%level",
                        "ip": "${IP}",
                        "service": "${APP_NAME:-}",
                        "tid": "%tid",
                        "pid": "${PID:-}",
                        "thread": "%thread",
                        "class": "%logger{1.}:%L",
                        "message": "%message",
                        "stackTrace": "%exception{10}"
                        }
                    </pattern>
                </pattern>
            </providers>
        </encoder>
    </appender>

</configuration>

```
 Thans anyway.

**Comment by wu-sheng** [comment]
If this missed in the document, could you send a pull request to add this in the document?

**Comment by gonedays** [comment]
> If this missed in the document, could you send a pull request to add this in the document?

Sure, my pleasure.

**Comment by gonedays** [comment]
> If this missed in the document, could you send a pull request to add this in the document?

@wu-sheng  wired problem, it doesn't work anymore, now the tid in log printed as "TID:[Ignored Trace]", what can  I do with that? Look into the source code of Agent, 
org.apache.skywalking.apm.agent.core.context.AbstractTracerContext, it chooseIgnoredTracerContext but not TracingContext, How to fixed it?

**Comment by wu-sheng** [comment]
Ignored should only show up when agent can't connect to backend. Is this your case?

**Comment by gonedays** [comment]
> Ignored should only show up when agent can't connect to backend. Is this your case?

Bingo, agent disconnet from the backend for some unknown reason, I restart the backend, and it works again, thank you very much. 

Where can I locate this info for document?  How about in FAQ？

**Comment by gonedays** [comment]
> Ignored should only show up when agent can't connect to backend. Is this your case?

@wu-sheng  Bingo, agent disconnet from the backend for some unknown reason, I restart the backend, and it works again, thank you very much.

Where can I locate this info for document? How about in FAQ

**Comment by wu-sheng** [comment]
Take an across check with this doc, https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-logback-1.x.md. If yours is still missing there, update this doc, please.

**Comment by gonedays** [comment]
> Take an across check with this doc, https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-logback-1.x.md. If yours is still missing there, update this doc, please.

Good, I'll update that tomorrow.

**Comment by gonedays** [comment]
> > Take an across check with this doc, https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-logback-1.x.md. If yours is still missing there, update this doc, please.
> 
> Good, I'll update that tomorrow.

[https://github.com/apache/skywalking/pull/4019](pull request for this)
