### ISSUE TITLE
skywalking docker swarm demo

### ISSUE THREAD

**Issue by leyou240** [apache/skywalking#4017]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion

___
### Question
- What do you want to know?

Our company use docker swarm to deploy.
But skywalking-docker repository has no docker swarm demo.
So I want to know how to deploy using docker swarm.
thx.

**Comment by wu-sheng** [comment]
Truly, we don't know. All PMC are either working on vm or k8s.
