### ISSUE TITLE
About Consul I think can describe  better 

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#4021]
In this doc
https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-cluster.md
suggest write consul cluster nodes .

But I think use consul agent can do the same things ? not need to writes cluster nodes.
Because Each agent can do same things for service  such as  register serverInstance or query service instance 

see this documents below
In consul 's description , no nodes . only agent(server or client )
https://learn.hashicorp.com/consul/getting-started/agent#server-and-client-agents
https://www.consul.io/docs/internals/architecture.html
![image](https://user-images.githubusercontent.com/7017464/70374767-8396a000-1931-11ea-996e-513ecabe4cd5.png)

**Comment by wu-sheng** [comment]
What are you proposing? I am not following.

**Comment by wu-sheng** [comment]
> suggest write consul cluster nodes .

We are not suggest to write consule node. We are giving configurations to the users about how to use SkyWalking consul cluster management plugin.

**Comment by wu-sheng** [comment]
If you want to propose another implementation of cluster management for Consul. You should propose the changes. I and SkyWalking team are very hard to evalue the meaning before this high level doc.

**Comment by seifeHu** [comment]
> What are you proposing? I am not following.

I suggest use " the consul agents " to instead

**Comment by wu-sheng** [comment]
> Can I write this one to push?

I am not following your change. How you deploy the Consul is your choice. The node we talked is the OAP node, it is not Consule node. That is why I mean, I am not following.

**Comment by seifeHu** [comment]
> > Can I write this one to push?
> 
> I am not following your change. How you deploy the Consul is your choice. The node we talked is the OAP node, it is not Consule node. That is why I mean, I am not following.

I means this text below:

` # Consul cluster nodes, example: 10.0.0.1:8500,10.0.0.2:8500,10.0.0.3:8500
    hostPort: ${SW_CLUSTER_CONSUL_HOST_PORT:localhost:8500}`

this ' consul cluster nodes.' can replace by 'the consul agents'  .  sorry for My description is not very clear ~~

**Comment by wu-sheng** [comment]
> this ' consul cluster nodes.' can replace by 'the consul agents' . sorry for My description is not very clear

Is there any difference for codes? Or just name change suggestion?

**Comment by seifeHu** [comment]
> > this ' consul cluster nodes.' can replace by 'the consul agents' . sorry for My description is not very clear
> 
> Is there any difference for codes? Or just name change suggestion?

just name change suggestion.

**Comment by wu-sheng** [comment]
Go for it.

**Comment by wu-sheng** [comment]
Fixed by #4030
