### ISSUE TITLE
what's the different betweens many standalone oap nodes and  many  oap cluster nodes 

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#4022]
### Question
- What do you want to know?
what's the different betweens many standalone oap nodes and  many  oap cluster nodes 。

I documents .I can not got any different. 
I can config 3 nodes in agent config.
If I deploy 3  standalone oap nodes or deploy  cluster nodes with consul ,what 's the different ?

**Comment by wu-sheng** [comment]
> If I deploy 3 standalone oap nodes or deploy cluster nodes with consul ,what 's the different ?

No, you can't. The analysis is a distributed aggregation. So, the OAP nodes should be aware of other nodes. We don't write these things in the documentations, I don't know any project to introduce this in the document. We said it is a cluster, which should indicate very clearly you should not do this.
