### ISSUE TITLE
ConfigurationServiceGrpc is not import

### ISSUE THREAD

**Issue by xiaotongtj** [apache/skywalking#4031]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
skywalking bratch docker/sync-6.2.0  is not import ConfigurationServiceGrpc
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean not import? do you read compiling doc?
