### ISSUE TITLE
How to get traceId when the agent is not registered to the collector?

### ISSUE THREAD

**Issue by JCchenxiang** [apache/skywalking#4033]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
There is such a requirement, only use skywalking agent , not register to collector , it will print traceId like "Ignored Trace", I just want to print correct traceId in the log. What should I do?Is it possible ?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You can't, because agent is in sleep mode.
