### ISSUE TITLE
The order of call chain displayed by UI is inconsistent with the actual order

### ISSUE THREAD

**Issue by boyill** [apache/skywalking#4034]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Which part inconsistent?

**Comment by boyill** [comment]
The order of display on UI，for example, before querying the database, call another link, but when it is displayed on the UI, call the link display, after querying the database

**Comment by wu-sheng** [comment]
> The order of display on UI，for example, before querying the database, call another link, but when it is displayed on the UI, call the link display, after querying the database

OK. I am not sure. If you have time, we are welcome you to contribute some fix. I think if there is a bug, it most likely a UI level bug.

**Comment by wu-sheng** [comment]
@boyill Could you provide the GraphQL query result here? It will help to locate the issue.

**Comment by boyill** [comment]
@wu-sheng The issue is because the UI is not sorted when it is displayed，I modified three files（trace-detail-chart-list.vue、trace-detail-chart-table.vue、trace-detail-chart-tree.vue） and added the order by span's startTime. But I'm not sure if sorting by time will cause new problems, such as time synchronization.

**Comment by wu-sheng** [comment]
Sort by time is not right, First, you should make sure the segment order is as same as the backend, by considering segment id + span id =0, then spanid and parent spanid relationship, finally if they have same parent span id, and belong to the same segment(same segment id), they should order by start time. Then you would not face time synchronization requirement. Could you follow this to submit a PR?

**Comment by boyill** [comment]
PR submitted
![image](https://user-images.githubusercontent.com/13619878/70430967-e36a8380-1ab6-11ea-8f70-c987638caa00.png)
![image](https://user-images.githubusercontent.com/13619878/70430991-f41af980-1ab6-11ea-97a0-ca5ad635e182.png)
![image](https://user-images.githubusercontent.com/13619878/70431004-fd0bcb00-1ab6-11ea-93c9-5ea43cb74fb5.png)

**Comment by wu-sheng** [comment]
@aderm could you verify this PR? I think you have the data to verfiy.

**Comment by aderm** [comment]
ok， I will first verify it in my own environment，And will observe if it will affect other traces

**Comment by aderm** [comment]
This has been online for almost a month, and no out-of-order issue has been found.

**Comment by wu-sheng** [comment]
Thanks for the update. Should we close this for now? If anything new found, we reopen this and dig deeper into a real case.

**Comment by aderm** [comment]
ok
