### ISSUE TITLE
AspNet configuration

### ISSUE THREAD

**Issue by simessk** [apache/skywalking#4041]
how to deal with the configuration of skywalking in  aspnet application project(Not aspnet core!!!)?

I had tried to configured using AspNET Core steps but failed.

Heere is the ex:

[FileLoadException: Could not load file or assembly 'Nito.AsyncEx.Context, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)]
   SkyApm.Agent.AspNet.InstrumentModule.Init(HttpApplication application) +0
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +552
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +181
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +228
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +314

**Comment by wu-sheng** [comment]
This is not the right place to submit this issue. .Net agent has its own repo, and it is not an Apache project yet. So please submit your question there.
