### ISSUE TITLE
End of supports of 1.6 JDK

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4049]
Original mail list, https://lists.apache.org/thread.html/7d8248870c99bcf59fe6bf288f02addcd9fa48ecefb5b4b5c7a04503%40%3Cdev.skywalking.apache.org%3E

This is a super important discussion and may require a vote later.
SkyWalking now supports JDK 6-13 in the agent side for a long time, and is
suffering the risk of RPC component bug too. gRPC has given up the supports
for JDK6 one year before.
Also ref to RedHat OpenJDK maintenance plan[1], OpenJDK6 has not been
supported in December 2016. Oracle JDK has similar storay.

I want to initial that, SkyWalking should decide to give up the support on
JDK 1.6, and move to higher JDK requirement. The question will be, does JDK
1.7 or 1.8 make more sense?

All people in the dev channel, your responses are super important.

The conclusion will be made soon in the next week.

[1] https://access.redhat.com/articles/1299013

**Comment by kezhenxu94** [comment]
closed by #4119
