### ISSUE TITLE
High cpu usage and maybe memory leak

### ISSUE THREAD

**Issue by kongminhao** [apache/skywalking#4051]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I run skywalking in our uat env, cpm about 1000, It's pretty small right?
I use a 4core/16G machine to deploy skywalking, when I use 2g memory, it will crash in 15min.
when I use 8G memory, It will crash after one night. 
I want to know it normal?

23200 root      20   0 12.2g 8.7g  22m S 374.2 56.1  32:53.31 java
22170 elastics  20   0 10.3g 2.6g 206m S  3.0 17.0  40:37.98 java
24113 root      20   0 15036 1300  944 R  0.3  0.0   0:00.27 top
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.5.0
os Red Hat Enterprise Linux Server release 6.5 (Santiago)
JRE 1.8_152
I have test it on the java11, but problem as before.

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Which storage are you using? If you are just using quick-start, which is a memory mode. We highlighted that in the document already.

**Comment by kongminhao** [comment]
> Which storage are you using? If you are just using quick-start, which is a memory mode. We highlighted that in the document already.

but I use elasticsearch.

**Comment by wu-sheng** [comment]
Then you should analysis the memory dump file. We may could have a clue there.

**Comment by kongminhao** [comment]
> Then you should analysis the memory dump file. We may could have a clue there.

thanks, I will try.
