### ISSUE TITLE
The Percent Response graph on UI shows unusual

### ISSUE THREAD

**Issue by Passeng-LUCA** [apache/skywalking#4055]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I'm not sure it's a bug or  data not right,what situation show the p95 and p99 smaller than the p90

___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking version :6.3
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improve
ment suggestions.

**Comment by Passeng-LUCA** [comment]
![Uploading 1576206676(1).jpg…]()

**Comment by wu-sheng** [comment]
Can’t see your image.
