### ISSUE TITLE
Remove local span and exit span OP name register permanently

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4056]
Today, there are endpoint register happens for entry, exit and local span, but we don’t need exit and local span OP names in 99% cases. We should remove it.

The only two scenarios is 
1. Segment query including endpoint id for endpoint dashboard page, but that page only shows entry span as endpoint, so it is safe to keep the column empty
2. Endpoint dependency in ref header dependency analysis in the backend. Let’s ignore the scenario of end parent endpoint is local or entry. Treat it as none, and don’t generate it as endpoint relation in the OAP side.

@kezhenxu94 Would you want to do this? Or I should run this removal.

**Comment by wu-sheng** [comment]
Local and exit register caused too much loads to the storage and waste a lot of endpoint ID for nothing. And entry span is the one could be used for metrics, endpoint dependency, and waste more time to finish register(because more ID required register).

So, from all perspectives, this mechanism should be removed. Actually, this should be removed earlier, but I forgot to propose this.

**Comment by jadezhong** [comment]
upgraded to 6.6.0, all exit/local span are ignored and no longer need to register, but some endpoints i needed is also among it, eg. RabbitMQ/Topic/xxxQueue/xxx.xxx/Producer which relates to RabbitMQ/Topic/xxxQueue/xxx.xxx/Comsumer, i will traversing those endpoints to retrieve their endpoint topologies, to draw a map of relationship between endpoints.
how to solve this?

**Comment by jadezhong** [comment]
most of the exit span indeed waste too much resources, eg. Mysql/JDBI/Statement/executeQuery, but some endpoints which acts as BRIDGE between two or more services should be registed whether it is exit/local span or not.
what do you think?

**Comment by wu-sheng** [comment]
We don't have any relationship analysis about the MQ producer/consumer ever.

**Comment by jadezhong** [comment]
yes, we have such demands, and i analysis endpoint topology to do that.

**Comment by wu-sheng** [comment]
I think upstream wouldn't include that, as our endpoint topology is not the one you mentioned.

**Comment by jadezhong** [comment]
yes, i forget to mention the skywalking_endpoint_inventory, conbines with endpoint topology, i can draw a map of endpoint relationship with their name.

**Comment by jadezhong** [comment]
i didn't make it clear, i mean i will retrieve endpoints of each service, then retrieve endpoint topology of each endpoint.

**Comment by jadezhong** [comment]
for this demand, i add a searchEndpointByTime() to search endpoints by time period and ignore DetectPoint condition.

**Comment by wu-sheng** [comment]
We have endpoint dependency map, also you could use that to draw topology. But not the one you mentioned. So, I am afraid your thing is a private version only.

**Comment by jadezhong** [comment]
yes, our demands are quite special.
