### ISSUE TITLE
skywalking-cli schema TraceBrief定义

### ISSUE THREAD

**Issue by clk1st** [apache/skywalking#4057]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

我试着在cli增加了trace列表信息的查询，遇到一个问题schema.go中TraceBrief中定义的结构如下：
type TraceBrief struct {
	Traces []*BasicTrace `json:"traces"`
	Total  int           `json:"total"`
}

查询queryTraces接口返回的json，需要把TraceBrief修改为：
type TraceBrief struct {
	Data  []*BasicTrace `json:"data"`
	Total int           `json:"total"`
}

不知道是不是我使用的有问题。

**Comment by kezhenxu94** [comment]
English please

**Comment by wu-sheng** [comment]
Enligsh only, please. Query interfaces are right, should not change in any way because of CLI.

**Comment by clk1st** [comment]
ok
