### ISSUE TITLE
There is no service on ui page.

### ISSUE THREAD

**Issue by adventurer2008** [apache/skywalking#4066]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
     I'm testing skywalking . I use h2 as database and added jar file to tomcat  server,which version is 8.0+. Tomcat server is working ok and log file is also ok. 
     The agent log is as below:

DEBUG 2019-12-15 11:31:12:707 SkywalkingAgent-2-GRPCChannelManager-0 GRPCChannelManager : Selected collector grpc service running, reconnect:false. 
DEBUG 2019-12-15 11:31:12:711 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2019-12-15 11:31:14:320 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2019-12-15 11:31:15:711 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 

But in ui page . there is no service . But endpoint is normal. When I click the URL of tomcat server. I may see the endpoint number is added, but service number is still zero.
![Snipaste_2019-12-15_11-38-42](https://user-images.githubusercontent.com/15321530/70857753-7e3be580-1f2f-11ea-8117-9a45b4729629.png)

**Comment by wu-sheng** [comment]
Please follow document and faq, yout timezone or time is not right.

**Comment by adventurer2008** [comment]
Thanks. I looked through the document.  I didn't set the default the time or timeframe section on the below part of the UI page. By modifing the default the time section. Now it's ok.

**Comment by wu-sheng** [comment]
First line of the setup document.
