### ISSUE TITLE
agent.config yaml format ?

### ISSUE THREAD

**Issue by wayilau** [apache/skywalking#4069]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
As the title said.

Although yml has strict syntax, it has a good format and eliminates duplicate code.

**Comment by wu-sheng** [comment]
What is different? Today's format has been set long time ago, 4 years at least. Why we want to change?

**Comment by wayilau** [comment]
Not change, just support another format. But also not important feature.

**Comment by wu-sheng** [comment]
But if want two formats, how do you deal with the conflicts? People provide both config files. The key point is what is the benefit for end-user?

**Comment by wayilau** [comment]
Yes, you're right.  we can put config.yml.example and agent.properties.example. when we start use SW, rename it to config.yml  or agent.properties. Only renamed files taken affect. If both renamed, chose yml file as the default one.

**Comment by kezhenxu94** [comment]
yaml supports more data structures (such as map and array) for sure, but introducing another configuration format requires another library(snakeyaml for example, and its transitive libraries if there is any) to parse it (in agent), just wondering whether it's worthwhile or not.

**Comment by wu-sheng** [comment]
I have the same concern as @kezhenxu94. The side effects are 
1. New library,
1.. No feature added, 
1. More maintenance work 
1. Users could think to have to change as document changed.

@wayilau If you have some good reasons, please share.

**Comment by wayilau** [comment]
Actually, From a technical perspective,I agree with you. Maybe my point just from a user's mind.
