### ISSUE TITLE
apollo configuration is not working?

### ISSUE THREAD

**Issue by sinoryan** [apache/skywalking#4073]
### Question
- apollo configuration is not working?

- Which version of SkyWalking, OS and JRE?
6.5.0/ jdk1.8 /  es7.5

- What happen?
First: my configuration segment
configuration:
  #none:
  apollo:
    apolloMeta: http://172.31.242.161:8080,http://172.31.242.162:8080
    apolloCluster: default
    # apolloEnv: # defaults to null
    appId: skywalking
    period: 10

And then, executing the startup.sh, following log::

2019-12-16 18:47:56,658 - com.ctrip.framework.apollo.internals.DefaultMetaServerProvider - 42 [main] INFO  [] - Located meta services from apollo.meta configuration: http://172.31.242.1:8080,http://172.31.242.2:8080!
2019-12-16 18:47:56,659 - com.ctrip.framework.apollo.core.MetaDomainConsts - 93 [main] INFO  [] - Located meta server address http://172.31.242.161:8080,http://172.31.242.162:8080 for env UAT from com.ctrip.framework.apollo.internals.DefaultMetaServerProvider
2019-12-16 18:47:56,736 - org.apache.skywalking.oap.server.configuration.apollo.ApolloConfigWatcherRegister - 54 [main] INFO  [] - Read dynamic configs from Apollo namespace: application

but not loading config item from my apollo center. please help me ,tx.

**Comment by kezhenxu94** [comment]
@sinoryan what are your configurations in Apollo, can you share some of them? Or you can test with the Apollo Demo environment (remember not to put sensitive configurations there) and I can see it there

**Comment by kezhenxu94** [comment]
Apollo Demo Environment: http://106.54.227.205/config.html?#/appid=skywalking

**Comment by sinoryan** [comment]
> @sinoryan what are your configurations in Apollo, can you share some of them? Or you can test with the Apollo Demo environment (remember not to put sensitive configurations there) and I can see it there

I want to override some configuration items from skywalking application.yml , sush as following fragment:
storage:
  elasticsearch:
    nameSpace: ${SW_NAMESPACE:""}
    clusterNodes: ${SW_STORAGE_ES_CLUSTER_NODES:localhost:9200}
    protocol: ${SW_STORAGE_ES_HTTP_PROTOCOL:"http"}

In my apollo center configuration ::
![image](https://user-images.githubusercontent.com/8133974/70964344-72cef280-20c6-11ea-8471-ace0f6985288.png)
all tried， include  comment out of configuration items .  
#storage.elasticsearch.clusterNodes = http://172.31.242.160:9200

**Comment by kezhenxu94** [comment]
@sinoryan not all config items in `application.yml` are dynamically configurable, check the documentation first, your efforts should not be wasted in such way

**Comment by sinoryan** [comment]
> @sinoryan not all config items in `application.yml` are dynamically configurable, check the documentation first, your efforts should not be wasted in such way

Ok,  got it. thank you!
 By the way, How to open the login validation with spring security?

**Comment by kezhenxu94** [comment]
> > @sinoryan not all config items in `application.yml` are dynamically configurable, check the documentation first, your efforts should not be wasted in such way
> 
> Ok, got it. thank you!
> By the way, How to open the login validation with spring security?

We don’t have that now
