### ISSUE TITLE
kafkaProcuctor使用了skywalking以后性能会严重下降

### ISSUE THREAD

**Issue by adamni135** [apache/skywalking#4085]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
当使用producer.send(new ProducerRecord<String, byte[]>(topic, msg), callback); 必须是使用了callback，callback不能为空

就会发现有大量线程在org.apache.kafka.clients.producer.internals.BufferPool#allocate方法line134
waitingTimeElapsed = !moreMemory.await(remainingTimeToBlockNs, TimeUnit.NANOSECONDS);
这里waiting

当我们修改org.apache.skywalking.apm.plugin.kafka.CallbackInterceptor#beforeMethod这个类里面
注释了line43-48就能fix问题

___
### Bug
- Which version of SkyWalking, OS and JRE?
kafka maven:
org.apache.kafka  kafka_2.12  2.2.0
skywalking plugin:
apm-kafka-plugin-6.5.0.jar

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
性能会严重下降
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please use English, and send pull request if you could fix a bug. Thanks.
