### ISSUE TITLE
when i use skywalking, i founded kafkaProcuctor will degrade performance very much

### ISSUE THREAD

**Issue by adamni135** [apache/skywalking#4087]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
when i use kafka producer.send(new ProducerRecord<String, byte[]>(topic, msg), callback);
callback must not be null

we found lots of threads waiting at org.apache.kafka.clients.producer.internals.BufferPool#allocate line134
codes: waitingTimeElapsed = !moreMemory.await(remainingTimeToBlockNs, TimeUnit.NANOSECONDS);

when we delete org.apache.skywalking.apm.plugin.kafka.CallbackInterceptor#beforeMethod
line43-48 then our springboot application performance will be as usual
___
### Bug
- Which version of SkyWalking, OS and JRE?
kafka maven:
org.apache.kafka kafka_2.12 2.2.0
skywalking plugin:
apm-kafka-plugin-6.5.0.jar

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
when using kafka sender with callback will degrade performance very much
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> when we delete org.apache.skywalking.apm.plugin.kafka.CallbackInterceptor#beforeMethod
line43-48 then our springboot application performance will be as usual

These lines are making sure your trace wouldn't break when callback executed in another thread. I t looks normal to me.

 I am not following, why is the following block related to those codes? Could you provide more detail?
>codes: waitingTimeElapsed = !moreMemory.await(remainingTimeToBlockNs, TimeUnit.NANOSECONDS);

ping @ascrutae @stalary

**Comment by adamni135** [comment]
our team is finding the reason too, we check the JVM safepoint log, we found that safe point reduce many, that means is not the safe point cause
if we start the application without that kafka plugin the qps is about 10000，when we add the plugin, the qps is 800
now I dump the theads info from vm when it work with kafka plugin
90% theads is waiting at that lines

"XNIO-1 task-214" #314 prio=5 os_prio=0 tid=0x00007f0e4402d050 nid=0x376b waiting on condition [0x00007f0c5c3c1000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000060ae48f28> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.apache.kafka.clients.producer.internals.BufferPool.allocate(BufferPool.java:134)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:210)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend$original$6nzgjrfj(KafkaProducer.java:901)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend$original$6nzgjrfj$accessor$RPNOCpVz(KafkaProducer.java)
	at org.apache.kafka.clients.producer.KafkaProducer$auxiliary$qXyiMoQM.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java)

**Comment by wu-sheng** [comment]
Thanks for sharing. All codes in the stack seem related to Kafka itself only, and this BufferPool is Kafka's. Strange, why plugin codes affect this. Please let us know if you have more clues.

**Comment by adamni135** [comment]
useing tools(greys) ,we found the without kafka plugin this methods
org.apache.kafka.clients.producer.internals.BufferPool.allocate(int, long)
all thread will enter line 110
 line 109: if (size == poolableSize && !this.free.isEmpty())
 line 110:    return this.free.pollFirst();

but with kafka plugin all thread will not enter this if block,  and they will go on to allocate the buffer
so 
i use my java tools to attach to the vm and using javassist to change the class print the args:
CtClass ct = pool.get("org.apache.kafka.clients.producer.internals.BufferPool");
CtMethod m = ct.getDeclaredMethod("allocate");
m.insertBefore("System.out.println(size + \":\" + poolableSize + \":\" + this.free.size());");

the result is

33554432:33554432:0
33554432:33554432:0
33554432:33554432:0
33554432:33554432:0
33554432:33554432:0
33554432:33554432:0
33554432:33554432:0
33554432:33554432:0
33554432:33554432:0
33554432:33554432:0
33554432:33554432:0
33554432:33554432:0
33554432:33554432:1
33554432:33554432:0
33554432:33554432:0
33554432:33554432:0

this means the "free" is almost empty

**Comment by adamni135** [comment]
if there some reason for that the 
"private final Deque<ByteBuffer> free;"
is not be deallocated?

**Comment by wu-sheng** [comment]
The codes in the plugin are as follows, right? These codes are not even change anything in the message, it just saves something inside your callback object. 

```
    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
                             MethodInterceptResult result) throws Throwable {
        CallbackCache cache = (CallbackCache) objInst.getSkyWalkingDynamicField();
        if (null != cache) {
            ContextSnapshot snapshot = getSnapshot(cache);
            RecordMetadata metadata = (RecordMetadata) allArguments[0];
            AbstractSpan activeSpan = ContextManager.createLocalSpan("Kafka/Producer/Callback");
            activeSpan.setComponent(ComponentsDefine.KAFKA_PRODUCER);
            Tags.MQ_TOPIC.set(activeSpan, metadata.topic());
            ContextManager.continued(snapshot);
        }
    }
```

**Comment by adamni135** [comment]
one more question: what is One trace segment has been abandoned, cause by buffer is full ?

DEBUG 2019-12-20 11:38:11:989 XNIO-1 task-133 TraceSegmentServiceClient : One trace segment has been abandoned, cause by buffer is full.
DEBUG 2019-12-20 11:38:11:989 kafka-producer-network-thread | producer-1 TraceSegmentServiceClient : One trace segment has been abandoned, cause by buffer is full.

**Comment by wu-sheng** [comment]
> one more question: what is One trace segment has been abandoned, cause by buffer is full ?

Meaning the speed of generating traces is faster than OAP consuming. So, the agent begins to abandon traces as a protection mechanism.

**Comment by adamni135** [comment]
maybe we found something new

this lock cause by the deallocate buffer delay too much
we found the code in kafka how to deallocate the buffer is:

org.apache.kafka.clients.producer.internals.Sender.completeBatch(ProducerBatch, PartitionResponse)

        if (batch.done(response.baseOffset, response.logAppendTime, null)) { // here kafka will call the callback
            maybeRemoveFromInflightBatches(batch);
            this.accumulator.deallocate(batch); // here kafka will release the buffer
        }

so if the callback rt is too large, it will cause the buffer can not release as soon as possible
and we trace in this method and print the stack:

 at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
        at com.bigo.eco.common.kafka.sender.KafkaEmptyCallback.onCompletion(KafkaEmptyCallback.java:-1)
        at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion$original$qobEMB62(KafkaProducer.java:1304)
        at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion$original$qobEMB62$accessor$KxcVlwF4(KafkaProducer.java:-1)
        at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback$auxiliary$SW3k8KDv.call(null:-1)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
        at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion(KafkaProducer.java:-1)
        at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:227)
        at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:196)
        at org.apache.kafka.clients.producer.internals.Sender.completeBatch(Sender.java:677)
        at org.apache.kafka.clients.producer.internals.Sender.completeBatch(Sender.java:649)
        at org.apache.kafka.clients.producer.internals.Sender.handleProduceResponse(Sender.java:557)
        at org.apache.kafka.clients.producer.internals.Sender.access$100(Sender.java:74)
        at org.apache.kafka.clients.producer.internals.Sender$1.onComplete(Sender.java:786)
        at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109)
        at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:557)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:549)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:311)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:235)
        at java.lang.Thread.run(Thread.java:748)

and the method 
org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(long, long, RuntimeException)  use 10ms to run

it is too long for the buffer to reuse

so we trace inside of the method

and found the each  "thunk.callback.onCompletion(metadata, null);" cause 2ms
and we need to find why it case 2ms
then we get this trace

`---+Tracing for : thread_name="kafka-producer-network-thread | producer-1" thread_id=0x39;is_daemon=true;priority=5;
    `---+[2,2ms]org.apache.skywalking.apm.agent.core.context.TracingContext:finish()
        +---[0,0ms]java.util.LinkedList:isEmpty(@452)
        +---[0,0ms]org.apache.skywalking.apm.agent.core.context.TracingContext:isLimitMechanismWorking(@453)
        +---[0,0ms]org.apache.skywalking.apm.agent.core.context.trace.TraceSegment:finish(@453)
        +---[0,0ms]org.apache.skywalking.apm.agent.core.context.trace.TraceSegment:hasRef(@460)
        +---[0,0ms]org.apache.skywalking.apm.agent.core.context.trace.TraceSegment:createTime(@471)
        `---[2,2ms]org.apache.skywalking.apm.agent.core.context.TracingContext$ListenerManager:notifyFinish(@475)


the code:
org.apache.skywalking.apm.agent.core.context.TracingContext$ListenerManager:notifyFinish(@475)
used 2ms

could you let me know what's this method for ? and do you have some suggest to fix it？

**Comment by adamni135** [comment]
we found the root cause ,my team mate use debug level log, we change it to error level then it fixed, sorry to trouble you

**Comment by adamni135** [comment]
some suggestion, the FileWriter write method:
    /**
     * Write log to the queue. W/ performance trade off, set 2ms timeout for the log OP.
     *
     * @param message to log
     */
    @Override public void write(String message) {
        try {
            logBuffer.offer(message, 2, TimeUnit.MILLISECONDS);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

the offer will return true or false,

maybe you can log when it return false;
that the developer can more easier to figger out the thread has been blocked

best wishes!!!

**Comment by wu-sheng** [comment]
We usually don't output the error unless it is necessary. Your suggestion is hard to implement. This is already logging API, how to log when it is already blocked :)

**Comment by adamni135** [comment]
I know it is a part of log, so may be it can log it self as next record, when we check the log we can know the queue is full, so that we can raise the log level or any other things, and this is only for suggestion,

**Comment by wu-sheng** [comment]
I know your meaning, but it is hard to implement. If you have any idea to do this in a good way, a pull request is welcome.

**Comment by adamni135** [comment]
ok，，let me think think how to fix it , do you have wechat ? can i join your chat group？

**Comment by wu-sheng** [comment]
You could find the QQ group here, https://github.com/apache/skywalking#contact-us. Basically, tech discussion should be on the mail list.
