### ISSUE TITLE
provider.parser.SegmentParseV2 -61464374 [grpc-default-executor-2589] ERROR [] - null

### ISSUE THREAD

**Issue by zsb7798169** [apache/skywalking#4088]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
Question 
- [ ] Bug
I think this is a bug
- [ ] Requirement
It is the same as issue #2224,but I don't want to  restart agent to slove the problem,online machines are not allowed to restart at will.
It is caused by the data deleted from storage.What can i do to prevent cache loss?

- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking-oap-server:6.2.0
jre 1.8

- Which company or project?

- What happen?
org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 -61464374 [grpc-default-executor-2589] ERROR [] - null

It is the same as issue #2224,but I don't want to  restart agent to slove the problem,online machines are not allowed to restart at will.

It is caused by the data deleted from storage.What can i do to prevent cache loss?

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is not cache loss, this is the metadata missing. They are very different. Only 6.4.0+ supports agent reboots, but I still don't recommend you count on that and removing data manually and randomly.

**Comment by zsb7798169** [comment]
oap server use dynamic ip,access through dynamic domain name,is this the cause?

**Comment by wu-sheng** [comment]
I don't know, sorry. It is hard to tell as this is your private network.
