### ISSUE TITLE
support track java private method

### ISSUE THREAD

**Issue by snowWave1995** [apache/skywalking#4091]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does skywalking support to track java private method ? Because some third part services we depend  are called in private methond , those can not be tracked.
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.4
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
It is supported, many methods we instrumented are private today.

**Comment by snowWave1995** [comment]
How to set it ? I don't find the way to set it in docs

**Comment by wu-sheng** [comment]
public or not. It depends on your plugin definition. We don't set anything, so there is no documentation about this.
