### ISSUE TITLE
spring mvc plugin can not enhance when RequestMapping annotation inherit from interface

### ISSUE THREAD

**Issue by liudantop** [apache/skywalking#4092]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

example code:
public interface TestController {
    @RequestMapping(value ="/test", method = RequestMethod.GET)
    String test();
}

@RestController
public class TestControllerImp implements TestController{
    public String test(){
         return "test";
    }
}

in spriing mvc plugin can not enhance

 new DeclaredInstanceMethodsInterceptPoint() {
                @Override
                public ElementMatcher<MethodDescription> getMethodsMatcher() {
                    return isAnnotatedWith(named("org.springframework.web.bind.annotation.RequestMapping"));
                }
}

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Fixed by #3847. Please search the issue before you submit a new but duplicated one.

**Comment by liudantop** [comment]
ok, thanks
