### ISSUE TITLE
Performance degradation for skywalking 

### ISSUE THREAD

**Issue by geektcp** [apache/skywalking#4101]
### Question
- Do u have benchmark test ?
I want know something about performance degradation for skywalking !

for example :
how much mem, cpu usage or thread increased when I use skywalking agent attach my micro service

**Comment by wu-sheng** [comment]
There are several documents on the agent setup doc. 

https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#test
