### ISSUE TITLE
how to use service mesh and native probe at the same time 

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4108]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [yes ] Question or discussion
___
### Question
- What do you want to know?
when I learning the feature supported by skywalking, I found the following terms:
1. You don't need to use Language based native agent and Service Mesh probe at the same time, because they both collect metrics data. As a result of that, your system suffers twice payloads, and the analytic numbers are doubled.
2. Use Service Mesh probe with Language based native agent or 3rd-party instrument library in tracing status. (Advanced usage)

I'm confused by the description above,How to properly use native probe in service mesh?
Thanks for your helping

**Comment by wu-sheng** [comment]
In my mind, today, they are alternative. Using them together is very complex, and I assume it is not suitable for an open source project. So, we only suggest you, don't use language agents in the service mesh. If you really want the agent for tracing only, consider adding a flag in the trace receiver, `isAnalysis`, and if it is set as `false`, then trace data only collected but not analysis.

**Comment by EvanLjp** [comment]
I'm just worried that the mixer won't have enough information to locate the problem
when some error occur in a method and with try catch process ,how to locte it from service mesh information 
Is there a best practice for service mesh tracing?

**Comment by wu-sheng** [comment]
> Is there a best practice for service mesh tracing?

I talked this multiple times in public conferences. There is no advantage of tracing in mesh. Mesh provides observability without agents in service level, not inside it. If you want the traditional method level or codes level diagnosis, agent is always the best choice.

**Comment by EvanLjp** [comment]
Thanks for your helping
