### ISSUE TITLE
支持 微服务注册发现中心是consul吗

### ISSUE THREAD

**Issue by sunxingxiang** [apache/skywalking#4122]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
支持 微服务注册发现中心是consul吗

**Comment by wu-sheng** [comment]
Read document and English only.

**Comment by sunxingxiang** [comment]
When to support Service Discovery  consul  ?

**Comment by wu-sheng** [comment]
If don't include in the doc, Then SkyWalking doesn't support today. If you want, you need to contribute by yourself.

**Comment by llliuwenjie** [comment]
how to join

**Comment by sunxingxiang** [comment]
add maven apm-agent-core pom  error

The beacon class location is jar:file:/Users/joey/.m2/repository/org/apache/skywalking/apm-agent-core/6.5.0/apm-agent-core-6.5.0.jar!/org/apache/skywalking/apm/agent/core/boot/AgentPackagePath.class.

**Comment by wu-sheng** [comment]
Why add this pom? I don't know. And Consul as cluster management is provided.
