### ISSUE TITLE
After my skywalking is replaced with MySQL storage, many of the displayed services are in red status.

### ISSUE THREAD

**Issue by zgui2000** [apache/skywalking#4123]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
Bug
___
### Question
- What do you want to know?
After my skywalking is replaced with MySQL storage, many of the displayed services are in red status.
___
### Bug
- Which version of SkyWalking, OS and JRE?
 SkyWalking: apache-skywalking-apm-6.4.0
 OS:  CentOS Linux release 7.6.1810 (Core)
 JRE: java version "1.8.0_102"
- Which company or project?
Shenzhen Baiqian Financial Information Technology Co., Ltd
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Log in skywalking's Web console to view the topology map，Originally, my skywalking storage uses elastic search. In the topology interface, each service has only two fields, name and type. However, after i migrated skywalking storage to MySQL, in the topology interface, each service display has name, type and SLA fields. And the value of SLA field is - 1%. Only when the value of SLA field is - 1%, its icon is red
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
How can I make the icons in the topology map not display red? That is, how can I just display the name and type of each service, not the SLA value, like the elastic search store

**Comment by wu-sheng** [comment]
There is nothing different about the feature between MySQL and ES storages. I think the differences you saw are caused by some error from you setup. ES is more widely used storage in production env, it has been tested by many users already.
