### ISSUE TITLE
When the front-end trace query granularity is seconds, the background granularity interval is minutes

### ISSUE THREAD

**Issue by ghost** [apache/skywalking#4124]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
<img width="1219" alt="WX20191225-151237@2x" src="https://user-images.githubusercontent.com/2892433/71436637-4a2fa400-2729-11ea-9121-6df6294e7f60.png">

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Maybe an optimization on the UI?

**Comment by aderm** [comment]
maybe

**Comment by wu-sheng** [comment]
@Fine0830 Please confirm the UI logic, if as described, please remove the SEC in the time-range selector.

**Comment by Fine0830** [comment]
Hmm, What is the SEC?

**Comment by Fine0830** [comment]
> @Fine0830 Please confirm the UI logic, if as described, please remove the SEC in the time-range selector.

Oh...Got it.
