### ISSUE TITLE
How to Defined [ Service Avg Throughput ]

### ISSUE THREAD

**Issue by shook2012** [apache/skywalking#4134]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion
-

___
### Question
-  Our bussiness system have one service named generalxxx-app, and this service contains six instance。i see every instance's  Avg Throughput is 3.4k cpm。but generalxxx-app service Avg Throughput  is 7.095k cpm 。In my understanding, shouldn't the Avg Throughput of service be the sum of the Avg Throughput of all instances？  What should it be？

**Comment by wu-sheng** [comment]
Logically, it should. But why it isn't, I am not sure. Check the storage persistence, maybe some OPs have error.
