### ISSUE TITLE
Multithreaded Link disconnected

### ISSUE THREAD

**Issue by llliuwenjie** [apache/skywalking#4135]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
Multithreaded link dow

___
### Question
- What do you want to know?
 what do i need to do?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please read the optional plugins, including @Trace or one more plugin in the optional plugin in 6.6
