### ISSUE TITLE
OAL doc question

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4141]
- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
1. when I saw the official doc about oap, I'm confused about the parameters of the  functions:

what is the meaning of ' 100 and 20 '?
All_heatmap = from(All.latency).thermodynamic(100, 20);

what is the meaning of ' 10 '?
All_p99 = from(All.latency).p99(10);

2. when I saw the official_analysis.oal, I found the following functions which don't exist in official doc:

service_cpm = from(Service.*).cpm();
service_apdex = from(Service.latency).apdex(name, status);

Where do I get the detailed functions?

thanks for your helping

**Comment by wu-sheng** [comment]
For the parameter, I think the current documents are missing.

**Comment by EvanLjp** [comment]
From what part of the code can I understand the meaning?

**Comment by wu-sheng** [comment]
Read #4142

**Comment by liuhaoXD** [comment]
The meaning of 'cpm' and 'maxDouble' is STILL missing. And, what does the

> 120ms and 124 are considered same

mean? I DID NOT see '120ms' or '124' anywhere.

Can I think `from(All.latency).p99(120ms)` is the same as`from(All.latency).p99(124)` ?

**Comment by wu-sheng** [comment]
The parameter is the precision. 120/10 == 124/10. So, in the stat level, they are the same response time.
