### ISSUE TITLE
Question about multiple version compatibility of skywalking components (agents/OAP/UI) 

### ISSUE THREAD

**Issue by makingtime** [apache/skywalking#4143]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion

___
### Question
- What do you want to know?
I didn't find compatibility information for each component version in the official documentation and release notes, below are some of my understandings, could you please help confirm if my understands are correct? Thanks. 

1， OAP Server version must be the same version as the agent version.
it means that if I upgrade OAP Server(6.4 to 6.6)，I must also upgrade all agents version as well.
is it correct?
2， UI version can be different with OAP Server. 
ex: UI 6.6 query against OAP Server 6.4

**Comment by wu-sheng** [comment]
There are different versions for protocols. You could check the difference between releases. 

Such as agents in the whole 6.x  are compatible, just have enhancement after 6.4. Go check skywalking-data-collect-protocol

UI and OAP have query protocol too. skywalking-query-protocol.
