### ISSUE TITLE
skywalking ui show no data when deploy separated

### ISSUE THREAD

**Issue by pugwoo** [apache/skywalking#4149]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

6.4.0 and 6.50

perhaps 6.6.0 has the same problem, I don't try it because there isn't ui docker image 6.6.0 yet.

- Which company or project?

demo

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

1. download skywalking 6.4.0.tar.gz and unzip it. start both oap and UI, port 8080,11800,12800 is listening well. Now, start a java project with skywalking agent, and it works. UI index looks like:

![image](https://user-images.githubusercontent.com/2637068/71570883-601adb80-2b12-11ea-93fd-98f846bcead9.png)

everything is ok now.

2. start an UI docker on the same machine as

```bash
docker run --name oap-ui --restart unless-stopped -d \
    -e SW_OAP_ADDRESS=10.100.99.41:12800 \
    -p 33800:8080 \
    apache/skywalking-ui:6.4.0
```

Notice that `10.100.99.41` is the IP of this machine. now visit UI provide by docker:

![image](https://user-images.githubusercontent.com/2637068/71570972-e46d5e80-2b12-11ea-90d9-377d0ffd26f6.png)

the services dropdown is gone, the server return no data.

While it shows a little which show that the docker UI really connected to skywalking:
![image](https://user-images.githubusercontent.com/2637068/71571079-9573f900-2b13-11ea-8680-82ff65a22fa6.png)

It's expected to show exactly same as the first step.

### Chinese version 中文描述

如上图所述，我下载了skywalking解压执行，然后起一个java，它能正常上报数据给skywalking并在页面中显示。但是如果我在一个docker中起一个ui，配置地址指向skywalking的12800，然后访问该UI。

问题：该UI很多地方显示不正常，例如service没有下拉列表、拓扑图也没显示。有2个地方则是正常的：一个是下面的概要（如上第3张图所示），一个是跟踪列表，这两个有数据显示且和步骤1一样。这说明dockerUI还是连到12800上的，不然它拿不到这两个数据。
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

It's expected to show exactly same as the first step.

**Comment by wu-sheng** [comment]
There are plenty of similar questions, you should search. And the documentation indicates you need to time and timezone right.

**Comment by pugwoo** [comment]
> There are plenty of similar questions, you should search. And the documentation indicates you need to time and timezone right.

建议将做法放到这里https://github.com/apache/skywalking-docker/ 的docker启动参数中，会减少很多这样的issue。

**Comment by wu-sheng** [comment]
This is the global used project. We can't set that.

**Comment by wu-sheng** [comment]
In 6.6.0 release, the UI will fetch the TZ automatically. As you are using 6.4, it is not there.

**Comment by pugwoo** [comment]
> In 6.6.0 release, the UI will fetch the TZ automatically. As you are using 6.4, it is not there.

it sounds great.
