### ISSUE TITLE
Support tracing starting at the browser

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4150]
As one of the key feature of client-js subproject, we should support the distributed tracing from the browser side. We should provide the following APIs(example only)
```javascript
new ClientMonitor()
.serviceName("svr-browser")
.instanceName("svr-browser-v1") // Optional, if empty, use the same name as service to register
.enableHTTPTracing() // Need start to trace the http request after this
.enableDefaultFilter() // Default filter will ignore the request for resources files, such as .jpg,.jpeg,.js,.css,.png,.bmp,.gif,.ico,.mp3,.mp4,.html,.svg
.useCustomFilter(".action,.do") // Optional, only trace the HTTP request having these suffix, separated by comma
.start();
```

### Register before tracing
The protocol doc this here, https://github.com/apache/skywalking/blob/master/docs/en/protocols/Trace-Data-Protocol-v2.md

You need to do register first after you have the IDs, you could try to intercept HTTP traffic. In the first version, we only need to create one exist span in the segment to represent the HTTP request. We could ignore other cases for now.
@ascrutae @hanahmily @JaredTan95 @dmsolr @kezhenxu94 @arugal @wayilau Any new case that browser tracing beside the only exit span?

### Header
In the tracing, besides to collect the segment, you should change the HTTP header. The document is here https://github.com/apache/skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Propagation-Headers-Protocol-v2.md. Notice, the `Entry endpoint` and `Parent endpoint ` in the header should be `-1` both as the browser is not a server-side application.

____
We need to add the following notice to the end-users in client-js document.

> Set only one service name for your whole browser application, and use service instance name to separate different versions or different platforms. Don't use different names in different pages.

**Comment by wu-sheng** [comment]
@Fine0830 Is there a tech to mock the browser, making the client-js working and tracing?

**Comment by wu-sheng** [comment]
Step 1, backend support service register as browser type, and query for browser type service. #4157

**Comment by wu-sheng** [comment]
I have request @ascrutae to update the demo env. After that, you could use this `type` field in service register, https://github.com/apache/skywalking-data-collect-protocol/blob/master/register/Register.proto#L56

And, at the same time, suggest API change from  
```
new ClientMonitor()
.serviceName("svr-browser")
.instanceName("svr-browser-v1") // Optional, if empty, use the same name as service to register
```
to
```
new ClientMonitor()
.browserSvrName("svr-browser") // Still as service name, but indicate it is a browser app.
.version("svr-browser-v1") // Optional, if empty, use `default` as version number. For backend interface, still use this as instance name, but this name should be consistent with the further rocketbot UI browser monitoring page.
```

**Comment by Fine0830** [comment]
Is the `version("svr-browser-v1")` app release version?

**Comment by wu-sheng** [comment]
> Is the version("svr-browser-v1") app release version?

Could be, or any version user like. My point is, SkyWalking will treat it as the instance at the backend.

**Comment by wu-sheng** [comment]
A reminder, the register would take time, maybe need several retries. If you intercept the trace before the register finished, please hold them in the memory and try to send them after the register successfully. The same mechanism for collecting error and perf detail data.

**Comment by Fine0830** [comment]
close this visa https://github.com/apache/skywalking-client-js/pull/23 and https://github.com/apache/skywalking-client-js/pull/28
