### ISSUE TITLE
What is the logic of sla?

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4154]
- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
when I use skywalking to monitor my service ,I found the meaning of sla is based on the request status.
How is status defined?
I have the fllowing guesses:
1. is based on the segment status on tracing (whether have Exception on the segment)

is it right?
thanks for your helping

**Comment by wu-sheng** [comment]
Exception or HTTP response code. Then calculate the success rate.

**Comment by imchao9** [comment]
Any document about the metrics mean (such as SLA) in skywalking 
for example what the meaning is SLA, it is Exception or HTTP response code. Then calculate the success rate.

**Comment by wu-sheng** [comment]
Yes, https://github.com/apache/skywalking/blob/v7.0.0/docs/en/ui/README.md
