### ISSUE TITLE
Decrease log level when byte buddy failed to match type

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#4155]
https://github.com/apache/skywalking/blob/8a97aad021b16eb72591323691e902b06bd54087/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/match/ProtectiveShieldMatcher.java#L45-L51

I'd like to raise a discussion on the log level in the above code snippet.

For some reasons, in some of our applications, we have many classes that are failed to be resolved by byte buddy, and cases are that the applications all work well including the SkyWalking agent, but the logs are somewhat overwhelming, I've found an old issue https://github.com/raphw/byte-buddy/issues/373 , and seems this exception is mostly harmless, so I'm wondering whether we could just log this kind of logs in `DEBUG` level, what's your opinion, @wu-sheng @ascrutae @JaredTan95 @dmsolr @arugal etc.

**Comment by wu-sheng** [comment]
It is harmless for the target application, yes. But this could make plugin failure if the target class is the instrumentation target. :) 

I am OK to change the log level to debug.
