### ISSUE TITLE
Support Browser protocol at OAP

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4166]
Follow protocol #4164 and design doc https://docs.google.com/document/d/1125WnFCsJnZ98m3H7hplgfkv5MXGJoYdPj-OSr64cDo/edit, implement the logic at the backend. 

if @apache/skywalking-committers wants to take over this, please let me know.

**Comment by arugal** [comment]
This is an interesting feature, I want to try.

**Comment by wu-sheng** [comment]
OK, I just assign this to you. Several keys. 
1. A new receiver module is required.
1. Register for the endpoint(pagePath) is the first priority work.
1. The browser-related sources should be new and separated too all related sources. OAL and antlr should be changed too.
1. All sources should be designed and discussed first.

### Metrics are following
1. PV for every page(endpoint), version(instance) and service
1. The error rate for every page.
1. TopN page is automatically available by topN query, don't need to implement
1. Error logs for every `BrowserErrorLog`, with rate sampling.

To @Fine0830, a question, what metrics are required for all fields in PerfDetail. Avg time? Maybe.

**Comment by Fine0830** [comment]
> OK, I just assign this to you. Several keys.
> 
> 1. A new receiver module is required.
> 2. Register for the endpoint(pagePath) is the first priority work.
> 3. The browser-related sources should be new and separated too all related sources. OAL and antlr should be changed too.
> 4. All sources should be designed and discussed first.
> 
> ### Metrics are following
> 1. PV for every page(endpoint), version(instance) and service
> 2. The error rate for every page.
> 3. TopN page is automatically available by topN query, don't need to implement
> 4. Error logs for every `BrowserErrorLog`, with rate sampling.
> 
> To @Fine0830, a question, what metrics are required for all fields in PerfDetail. Avg time? Maybe.

Yes. The data is displayed according to the average value of the indicator data in the specified time period. The average value can reflect the average performance over a period of time, but it is easily affected by the extreme value. For example, a user visiting the network is very poor, resulting in the overall page load is very slow, and the average value of the data will be directly pulled up. So I think we can do a filter and use the filter of de extremum to remove the extremum and avoid the influence of extremum on the overall trend of performance.

**Comment by wu-sheng** [comment]
@Fine0830 Your description is the difference between avg and p50 :) That is also why other metrics have p99->p50 to exclude the extreme values.

**Comment by Fine0830** [comment]
Ooh.... I don't quite understand p99->p50. I think `PerfDetail` also need avg value and p99->p50, like other metrics. WDYT @wu-sheng

**Comment by wu-sheng** [comment]
p50 means 50% of request duration is below the value, which wouldn't be affected by the long tail issue. Same for others. It is very easy to extend from avg to p99->50.

**Comment by arugal** [comment]
> The browser-related sources should be new and separated too all related sources.

A question about `inventory`.  I need to use the new `BrowserServiceInventory`,`BrowserServiceInstanceInventory`,`BrowserEndpointInventory`?

**Comment by wu-sheng** [comment]
@arugal  Any update about this?

**Comment by aderm** [comment]
> 3\. The browser-related sources should be new and separated too all related sources. OAL and antlr should be changed too.

@wu-sheng This sounds interesting, and I hope to participate in antlr related work

**Comment by wu-sheng** [comment]
@aderm , please talk with @arugal . Don't work on duplicated parts.

**Comment by aderm** [comment]
Ok i will communicate with him

**Comment by wu-sheng** [comment]
OAP Backend is ready. Waiting for the agent side release and new dashboard update.
