### ISSUE TITLE
skywalking-rocketbot-ui6.6 versioon  why An error was reported by the console when the project started in topology module eg:1. [vuex] unknown action type: rocketTopo/CLEAR_TOPO_INFO 2.Error in beforeDestroy hook: "TypeError: Cannot read property 'runtime' of undefined"

### ISSUE THREAD

**Issue by LSWleecc** [apache/skywalking#4179]
why An error was reported by the console when the project started in topology module
eg:1. [vuex] unknown action type: rocketTopo/CLEAR_TOPO_INFO
2.Error in beforeDestroy hook: "TypeError: Cannot read property 'runtime' of undefined"

**Comment by kezhenxu94** [comment]
Duplicate of https://github.com/apache/skywalking-rocketbot-ui/issues/240
