### ISSUE TITLE
webapp security

### ISSUE THREAD

**Issue by lurui04** [apache/skywalking#4181]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

Requirement or improvement
-The apache-skywalking-apm-6.5.0.  wenapp
-The webapp security do not support username and password config？

**Comment by wu-sheng** [comment]
Yes, it has been removed due to the prev implementation is not secure enough. So currently, no login or user management.

**Comment by lurui04** [comment]
OK.thanks for your helping
