### ISSUE TITLE
Agent Authentication

### ISSUE THREAD

**Issue by lurui04** [apache/skywalking#4182]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
the version of skywalking is 6.5.0.
skywalking agent has the config with 'agent.authentication';
but the application of backend setting, do not have the config of authentication

**Comment by wu-sheng** [comment]
Yes. Because the backend doesn't include these codes. It used to be included in 5.x, but in 6.x and 7.x, no one submits pull requests to move those codes. If you have interests, please raise a pull request to do so.

**Comment by lurui04** [comment]
OK.thanks for your helping

**Comment by wu-sheng** [comment]
Provided.
