### ISSUE TITLE
top_n_database_statement

### ISSUE THREAD

**Issue by renhaizhou** [apache/skywalking#4183]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.5.0  macos  jdk1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
top_n_database_statement  table  statement field   exist  null value
![Xnip2020-01-06_17-38-34](https://user-images.githubusercontent.com/41145169/71809618-6cbba880-30ab-11ea-8146-4f6654337748.jpg)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This could be commit/rollback or other no statement SQLs. We have ignored all these in 6.6.0
