### ISSUE TITLE
make a suggestion about DUBBO plugin

### ISSUE THREAD

**Issue by tzy1316106836** [apache/skywalking#4186]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] discussion

___
### Question
Dubbo plugin will have the following problems when retrying:
If the current link is triggered by other components that are not monitored, and it does not have EntrySpan, the stackDepth of the link is 0 when the dubbo is called internally. The traceId generated by the call is different. however, if the dubbo call timeout and retry, the traceId is the same, because the sw3 parameter of the last call is reused. In this scenario, The effect of multiple dubbo calls and dubbo retry  should be the same. I think the problem needs to be fixed, that is, update the value of sw3 when retrying.

**Comment by kezhenxu94** [comment]
@tzy1316106836 can you please send a pull request to fix this?

**Comment by tzy1316106836** [comment]
https://github.com/apache/skywalking/pull/4187/files

**Comment by tzy1316106836** [comment]
> @tzy1316106836 can you please send a pull request to fix this?

**Comment by kezhenxu94** [comment]
fixed by #4187
