### ISSUE TITLE
top_n_database_statement table  state field exist  [No statement]/null

### ISSUE THREAD

**Issue by renhaizhou** [apache/skywalking#4188]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.6.0 macos  jdk1.8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
top_n_database_statement table  state field exist  [No statement]/null
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Meaning, some executions of DB OP are slow, but not a statement, such as commit, rollback.
