### ISSUE TITLE
Poor readability(p99/p95/p90/p75/p50 response time graph)

### ISSUE THREAD

**Issue by geektcp** [apache/skywalking#4189]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What is the meaning of p99/p95/p90/p75/p50 in WEB-UI(Global Response Time Percentile)

### Requirement or improvement
- requirements or improvement suggestions.
There is no detail describe about this graph in WEB-UI.
Many user do not know what is it

**Comment by wu-sheng** [comment]
Percentile is introduced in the document, also referring to a WIKI page. Please read there.

**Comment by geektcp** [comment]
> Percentile is introduced in the document, also referring to a WIKI page. Please read there.

Can u show me  the WIKI  url?

**Comment by wu-sheng** [comment]
You could simply google it, https://en.wikipedia.org/wiki/Percentile

**Comment by geektcp** [comment]
> You could simply google it, https://en.wikipedia.org/wiki/Percentile

Thank, It is helpful for others too!

**Comment by geektcp** [comment]
> You could simply google it, https://en.wikipedia.org/wiki/Percentile

helpful
