### ISSUE TITLE
Recommendations for reducing the number of indexes

### ISSUE THREAD

**Issue by aderm** [apache/skywalking#4190]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
<img width="1171" alt="WX20200107-110218@2x" src="https://user-images.githubusercontent.com/2892433/71866345-bdc9ac00-3140-11ea-8791-6410d1b5b0f1.png">

Under the default parameters of SW, the number of ES indexes has reached more than 500, and the number of shards has exceeded the default maximum index number of ES shards of 1000. Under certain conditions, the larger the number of shards will affect query performance, It will also increase the burden of cluster management and increase the instability of the cluster.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Is it possible to combine hour, day, and month indexes and distinguish them by a type field inside the index, which is expected to reduce the number of indexes by 3/4. Query performance may be partially improved due to the use of fewer shards. But this has not been actually tested.

**Comment by wu-sheng** [comment]
Your idea is not possible, those four are using different TTL, which is hard to share the same index files. The idea could be sharing index for different metrics of different metrics. Adding a new column of metrics name in the index, and then, the query could use this. But across different time levels is not a good way.

**Comment by aderm** [comment]
Because I looked at the mapping of these four indexes, the structure is similar. Is it possible to add a type field to indicate the TTL type, that is, to store hour, day, and month in this field, so that all four queries query the same index name and use type = hour or day or month to filter

**Comment by wu-sheng** [comment]
But you can't delete data, which makes the TTL meaningless. You can't just make query works,

**Comment by aderm** [comment]
Deleting data is the same as before, but when deleting, add use type = hour or day or month to filter.This is the same as the previous logic. The only difference is the index name parameter, which is filtered by the type field.

**Comment by darcydai** [comment]
> But you can't delete data, which makes the TTL meaningless. You can't just make query works,

I am more concerned skywalking support set  different shards for indices,
Especially segment index ,size is very large than others.

**Comment by wu-sheng** [comment]
> Deleting data is the same as before, but when deleting, add use type = hour or day or month to filter.This is the same as the previous logic. The only difference is the index name parameter, which is filtered by the type field.

No, it doesn't. Currently, from 6.2.0, deleting mean remove the whole index, rather than data, which will cause elasticsearch GC or even FGC. So if you put different precision data in the same index, this is a problem.

**Comment by wu-sheng** [comment]
> I am more concerned skywalking support set different shards for indices,
Especially segment index ,size is very large than others.

I think this could be discussed and changed. After all, the segment is different from others. We could provide some config for segment only. Do you want to try to propose a pull request to do so?

**Comment by darcydai** [comment]
> > I am more concerned skywalking support set different shards for indices,
> > Especially segment index ,size is very large than others.
> 
> I think this could be discussed and changed. After all, the segment is different from others. We could provide some config for segment only. Do you want to try to propose a pull request to do so?

Yes !.  I glad to it,  I will open a pull request after completed.

**Comment by aderm** [comment]
> > Deleting data is the same as before, but when deleting, add use type = hour or day or month to filter.This is the same as the previous logic. The only difference is the index name parameter, which is filtered by the type field.
> 
> No, it doesn't. Currently, from 6.2.0, deleting mean remove the whole index, rather than data, which will cause elasticsearch GC or even FGC. So if you put different precision data in the same index, this is a problem.

<img width="368" alt="WX20200109-110838@2x" src="https://user-images.githubusercontent.com/2892433/72034538-4591f080-32d0-11ea-8aa5-3b1a32a260bc.png">

I'm also talking about deleting the index, not deleting the data inside. Deleting data does have performance problems, which is related to the principle of inverted index. For example, all_p75_day-20191225 and all_p75_hour-20191225 are deleted on a daily basis, But they can be merged into one, and the entire index is deleted by day after the merge..

**Comment by aderm** [comment]
If it is a merge index, these may need to be modified

**Comment by wu-sheng** [comment]
> If it is a merge index, these may need to be modified

Modification is not the key point. The point is how do you explain this to the user. Also, it is hard to name. Could you have an accurate and easily understandable name for this config?

**Comment by wu-sheng** [comment]
My only thought is only `metricsTTL`, and you have to explain, it will affect the different precision data, including month, day, hour and minute.

**Comment by aderm** [comment]
OK, I have n’t figured it out yet, let me think again

**Comment by wu-sheng** [comment]
Sure, have a new proposal, please let me know. This is not a small change, we should work on this ASAP.

**Comment by wu-sheng** [comment]
We should merge the following into one, **metricsTTL**
```
    @Setter private int minuteMetricsDataTTL = 2;
    @Setter private int hourMetricsDataTTL = 2;
    @Setter private int dayMetricsDataTTL = 2;
    private int otherMetricsDataTTL = 0;
    @Setter private int monthMetricsDataTTL = 18;
```

**Comment by wu-sheng** [comment]
In my mind, there should be two TTLs in ES storage after this adjustment
- metricsTTL, this will cover metrics in min, hour and day precision
- metricsTTLofMonth

So, basically, a reasonable solution is reducing 50% of indexes, as min/hour/day metrics index will merge into one per metrics type.

@kezhenxu94 @dmsolr @arugal @JaredTan95 @hanahmily What do you think?

**Comment by wu-sheng** [comment]
A follow-up, I invested the codes this morning, and noticed, `ModelName#build` is a global utility in the core, and effecting model in all storage implementation, rather than ES storage. So, basically, this change is not complex, but it definitely affects all storage, which have to face the model merging too.
I don't want to see this, as the merging should only seem to be an ES storage optimization, rather than global model change.

FYI @peng-yongsheng if you are available from personal affairs.

**Comment by wu-sheng** [comment]
After discussion with @hanahmily, I will move the change direction to provide new function(histogram) and new GraphQL query language to replace Pxx, also request changes to all UI related queries.

@Fine0830 I will inform you later that the new query protocol, and please adjust the UI after that.

**Comment by Fine0830** [comment]
OK
