### ISSUE TITLE
executed SQL statement

### ISSUE THREAD

**Issue by renhaizhou** [apache/skywalking#4192]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Now the link trace can see the executed SQL statement, but you cannot see the executed SQL statement that is the SQL with parameters. For example, you can see the following
```sql
select id, initiator_id, initiator_role_type, organization_id, type, session_type, created_at, updated_at, deleted_at, session_accid, owner_accid from s_message.t_session WHERE ( deleted_at is null and initiator_id = ? and initiator_role_type = ? ) 
```
I want to see the specific parameters when the question mark is executed. What configuration needs to be modified?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by JaredTan95** [comment]
Follow [docs](https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md) and you can find how to config.
