### ISSUE TITLE
Skywalking queries become slower as the amount of data becomes larger

### ISSUE THREAD

**Issue by Liu-XinYuan** [apache/skywalking#4194]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

The skywalking page query becomes slower as the total amount of data increases, but we generally only query the data of the day, and when using elasticsearch as the back-end storage, all indexes are traversed according to the alias query, in fact we only need to query The index of the day, which caused the total query time to slow

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
We only need to locate the index based on the time condition of the query and the timestamp information carried in the traceId. When the index is specified during the query, theoretically the number of indexes for the query will be reduced.

**Comment by wu-sheng** [comment]
Thanks for submitting this, Please provide the new codes and benchmark.

**Comment by Liu-XinYuan** [comment]
ok

**Comment by wu-sheng** [comment]
Have been fixed in 8.1.0
