### ISSUE TITLE
Clicking on the search will reset the selection criteria

### ISSUE THREAD

**Issue by renhaizhou** [apache/skywalking#4195]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.6.0  macos jdk1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/41145169/71942936-d649cd00-31f9-11ea-8fa8-e82d15058160.png)
Clicking on the search will reset the selection criteria
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Yes, seems a bug. Could you fix this?
