### ISSUE TITLE
The topology picture shows nothing

### ISSUE THREAD

**Issue by wutingjia** [apache/skywalking#4196]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I upgrade from 6.1.0 to 6.6.0,then it's show nothing in topology,but others work well。
The error log is like this:
```log
2020-01-08 13:18:33,316 - graphql.GraphQL - 515 [qtp2041611826-50] WARN  [] - Query failed to validate : 'query queryTraces($duration: Duration!) {
  topo: getGlobalTopology(duration: $duration) {
    nodes {
      id
      name
      type
      isReal
    }
    calls {
      id
      source
      target
      callType
      detectPoint
    }
  }}
```
Another questions: If I mixed use the different version of agent，what can be affected ?

___
### Bug
- Which version of SkyWalking, OS and JRE?
base on skywalking agent 6.6.0 and skywalking backend 6.6.0

- Which company or project?

- What happen?

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> Another questions: If I mixed use the different version of agent，what can be affected ?

If the agent is in 6.x release, it should be fine. It is impossible to guess from the information you posted.

**Comment by yangshixiong01** [comment]
What was the final solution?

**Comment by yangshixiong01** [comment]
I also encountered the same problem, very distressed
