### ISSUE TITLE
How skywalking can trace nginx ， h5 ,andorid

### ISSUE THREAD

**Issue by onebyte0755** [apache/skywalking#4200]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Simple answer, currently no. Similar discussions happen on mail list. https://lists.apache.org/list.html?dev@skywalking.apache.org
