### ISSUE TITLE
Agent Elasticsearch Highlevel Client  cannot use in trace query 

### ISSUE THREAD

**Issue by zhangyunpeng-ice** [apache/skywalking#4202]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x]  Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
  I use java agent 6.6 version,  In supported middlewire list, support rest-high-level-client,
  My  Rest-high-level-Client is 7.0.1,but  In SkyWalking UI Trace query,cant not query  es call 
  information,what reason? 
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Check the supported list document in 6.6.

**Comment by zhangyunpeng-ice** [comment]
> Check the supported list document in 6.6.

6.6 supported list have high level client, but can not record  trace infomation

**Comment by wu-sheng** [comment]
Check the test scenario in the test/plugin-test folder. You could find how it is tested.
