### ISSUE TITLE
.net core call java , the call chain break

### ISSUE THREAD

**Issue by solapvk** [apache/skywalking#4204]
java call .net core ,the http head is
 

> sw6 = 1-MjUuNzQuMTU3ODUzNTczNTUzNzAwMzU=-MjUuNzQuMTU3ODUzNTczNTUzNzAwMzQ=-2-25-25-I2xvY2FsaG9zdDo4MDg3-Iy9oZWxsbw==-Iy9oZWxsbw==

and the call chain is right.like  that

![p1](https://user-images.githubusercontent.com/5832358/72035745-b5ee4100-32d3-11ea-8520-95335645ff5f.jpg)

.net core call java ,the head is 

> sw6=1-MjMuNzYuMTU3ODUzNjc5ODM4MzAwMDk=-MjMuNzYuMTU3ODUzNjc5ODQ0NTAwMTE=-0-23-23-I2xvY2FsaG9zdDo4MDg5-I2h0dHA6Ly9sb2NhbGhvc3Q6ODA4OS9oZWxsbw==-Iy9hcGkvdmFsdWVzLzE=

and the call chain is not right.like  that
![image](https://user-images.githubusercontent.com/5832358/72035960-5ba1b000-32d4-11ea-8836-852e362d4afd.png)

**Comment by wu-sheng** [comment]
I think you should submit the issue to .net repo. SkyWalking header propagation codes are right, due to most users are using it. So, my guess is, in some .net plugin, it doesn't report the data in right format, and the javaagent ignores the header and start a new trace.
