### ISSUE TITLE
[UI Feature]I want to pass traceId as query parameter

### ISSUE THREAD

**Issue by LittleShrimp1987** [apache/skywalking#4205]
### Requirement or improvement
In my situation, I have my own log system and I apply skywalking's traceId in my log，so traceId is the connection between my log and skywalking trace. if i can pass traceId as query parameter to skywalking trace page, that would be helpful。eg. 
http://skywalking.com.cn/trace?traceId=xxxxxxxxx

**Comment by wu-sheng** [comment]
Search the pull request, it is already there in the 6.6.0

**Comment by LittleShrimp1987** [comment]
ok, thanks.
