### ISSUE TITLE
use es too many index

### ISSUE THREAD

**Issue by jinlong82921** [apache/skywalking#4216]
- [x] Requirement
   can it config  by month
   version 6.5.0,ten days 5000index ,it is expensive

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/pull/4214 will reduce some, but not too many. The number of indexes depends on metrics, TTL and precision. So as default, we keep that as much as possible.
You could simply remove `month` precision by reducing 25% indexes.
