### ISSUE TITLE
Support new Pxx metrics in UI

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4219]
Due to #4214, new protocol and implementation provided for Pxx. The UI should adopt this feature.

**Comment by wu-sheng** [comment]
Demo env updated, please fix the UI ASAP, due to the demo is not working well. Very appreciated. @Fine0830

**Comment by Fine0830** [comment]
OK.  I will do that.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
