### ISSUE TITLE
Unexpected endpoint register, endpoint isn't detected from server side. endpoints{xxx}

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#4222]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What does this log stand for? How do I resolve this warning? 
It did not appear in version 6.5.0, but did appear with the latest master(docker-oap-es7).

**Comment by stalary** [comment]
`
2020-01-13 10:11:38,866 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.RegisterServiceHandler -256210310 [grpcServerPool-1-thread-4] WARN  [] - Unexpected endpoint register, endpoint isn't detected from server side. endpoints {
  serviceId: 24
  endpointName: "Lettuce/SET"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/team/create.action"
}
endpoints {
  serviceId: 24
  endpointName: "/user/info"
}
endpoints {
  serviceId: 24
  endpointName: "Mysql/JDBI/Connection/close"
}
endpoints {
  serviceId: 24
  endpointName: "Zookeeper/getChildren2"
}
endpoints {
  serviceId: 24
  endpointName: "/getIMToken"
}
endpoints {
  serviceId: 24
  endpointName: "Mysql/JDBI/PreparedStatement/executeUpdate"
}
endpoints {
  serviceId: 24
  endpointName: "/classtalk/prod"
}
endpoints {
  serviceId: 24
  endpointName: "/nos/upload"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/COMMAND"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/msg/sendMsg.action"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/PEXPIRE"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/SUBSCRIBE"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/HDEL"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/GET"
}
endpoints {
  serviceId: 24
  endpointName: "/out/log/request"
}
endpoints {
  serviceId: 24
  endpointName: "Zookeeper/create"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/PSETEX"
}
endpoints {
  serviceId: 24
  endpointName: "/sms"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/EVALSHA"
}
endpoints {
  serviceId: 24
  endpointName: "Cassandra/executeAsync"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/history/queryTeamMsg.action"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/team/kick.action"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/CLIENT"
}
endpoints {
  serviceId: 24
  endpointName: "/la-doc-student_stat/_search"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/team/changeOwner.action"
}
endpoints {
  serviceId: 24
  endpointName: "Mysql/JDBI/PreparedStatement/executeQuery"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/MGET"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/team/addManager.action"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/INCR"
}
endpoints {
  serviceId: 24
  endpointName: "Zookeeper/getData"
}
endpoints {
  serviceId: 24
  endpointName: "Mysql/JDBI/Connection/commit"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/EXISTS"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/DEL"
}
endpoints {
  serviceId: 24
  endpointName: "Zookeeper/ping"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/SETEX"
}
endpoints {
  serviceId: 24
  endpointName: "Mysql/JDBI/Statement/execute"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/team/add.action"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/CLUSTER"
}
endpoints {
  serviceId: 24
  endpointName: "/exam/quiz/get"
}
endpoints {
  serviceId: 24
  endpointName: "/question/list"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/user/updateUinfo.action"
}
endpoints {
  serviceId: 24
  endpointName: "Zookeeper/delete"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/HGETALL"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/team/update.action"
}
endpoints {
  serviceId: 24
  endpointName: "Lettuce/PUBLISH"
}
endpoints {
  serviceId: 24
  endpointName: "//timer/job"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/team/updateTeamNick.action"
}
endpoints {
  serviceId: 24
  endpointName: "/pushMessage"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/msg/recall.action"
}
endpoints {
  serviceId: 24
  endpointName: "/nimserver/team/removeManager.action"
}
endpoints {
  serviceId: 24
  endpointName: "Cassandra/execute"
}
`

**Comment by stalary** [comment]
Too many warnings made it impossible for me to view the service log properly

**Comment by stalary** [comment]
https://github.com/apache/skywalking/blob/master/docs/en/FAQ/Unexpected-endpoint-register.md

**Comment by flydoos** [comment]
原因是：Since 6.6.0, SkyWalking cancelled the local span and exit span register. If old java agent(before 6.6.0) is still running, and do register to 6.6.0+ backend, you will face the following warning message.

所以就会出现这个告警：class=RegisterServiceHandler, message = Unexpected endpoint register, endpoint isn't detected from server side.

解决方法如下：/skywalking/config/log4j2.xml
新增一个规则：<logger name="org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.RegisterServiceHandler" level="ERROR"/>

![image](https://user-images.githubusercontent.com/3932827/85491474-31377b00-b606-11ea-8859-4ade13e23b7a.png)

完整配置如下：
`    <Loggers>
		<logger name="org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.RegisterServiceHandler" level="ERROR"/>
        <logger name="org.eclipse.jetty" level="INFO"/>
        <logger name="org.apache.zookeeper" level="INFO"/>
        <logger name="io.grpc.netty" level="INFO"/>
        <Root level="info">
            <AppenderRef ref="RollingFile"/>
        </Root>
    </Loggers>`
