### ISSUE TITLE
What's the usage of network_address_inventory and where its data come from?

### ISSUE THREAD

**Issue by f02061232-1** [apache/skywalking#4223]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I'm trying to create a sla report base on skywalking service_sla_day data. What confused me is that lots of services come from network address inventory. These services is not registered to skywalking by ourselves. I read md file, but got limited information.

For Network Address Inventory, it represents all network address, in IP:port, hostname, domain name formats, which are detected by language agents or other probes.

eg:
{
                "_index":"service_inventory",
                "_type":"type",
                "_id":"1_56",
                "_score":0,
                "_source":{
                    "sequence":68,
                    "heartbeat_time":1574781959840,
                    "node_type":3,
                    "mapping_last_update_time":1574782809172,
                    "name":"service-provider:80",
                    "address_id":56,
                    "is_address":1,
                    "mapping_service_id":64,
                    "register_time":1574781956854,
                    "properties":null
                }
            }

we are using javaagent -javaagent:apache-skywalking-apm-bin/agent/skywalking-agent.jar, how did this agent detect above Network Address (service-provider:80) or service and add to service_inventory index?

**Comment by wu-sheng** [comment]
If You want to understand this. You need to understand the topology detection. I am trying to write a paper about this, But it is not published yet. You need to read codes.
