### ISSUE TITLE
Requirement: Number of thread for service instance in skywalking-ui 

### ISSUE THREAD

**Issue by gonedays** [apache/skywalking#4224]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Would like to add num of thread for service instance in skywalking-ui, as this is a important metrics for performance, we can dig reason for bad performance, eg. Sudden increase in number of threads. Thanks

**Comment by wu-sheng** [comment]
SkyWalking community wouldn't do feature enhancement in this way. If you want this, we hope to accept your proposal and pull requests about this.
