### ISSUE TITLE
Provide plugin for ShardingSphere 4.0.0

### ISSUE THREAD

**Issue by tuohai666** [apache/skywalking#4229]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

Provide plugin for ShardingSphere 4.0.0 of which the package name is different from RC3.

**Comment by kezhenxu94** [comment]
@tuohai666 I hope you could refactor the existed codes of ShardingSphere plugins in this issue too, there're many duplicated codes, we could have much more clean codes :smile:

**Comment by tuohai666** [comment]
@kezhenxu94 You are right. ShardingSphere changed api or package name in every release, more plugins will be provided subsequently. It's time to extract common codes.

**Comment by wu-sheng** [comment]
@tuohai666 Any progress?

**Comment by menghaoranss** [comment]
I will follow up on this issue with @tuohai666

**Comment by wu-sheng** [comment]
Provided by #4873 4894
