### ISSUE TITLE
potential thread-unsafe problem in server-alarm-plugin of oap-server module

### ISSUE THREAD

**Issue by liuhaoXD** [apache/skywalking#4230]
https://github.com/apache/skywalking/blob/f9cf17be24304bdf4afef423cbb0d5e4925f668f/oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/RunningRule.java#L232

* `this.moveTo()`at line 234  is thread-unsafe.
* `minutesBetween` operation should be protected by lock()
* `if` statement at  line 233 is duplicate with line 240

**Comment by wu-sheng** [comment]
Could you submit the issue in English or send a pull request to fix the issue?
