### ISSUE TITLE
how long will  modify  the SW_STORAGE_ES_RECORD_DATA_TTL  do effect ?

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#4233]
### Question
- What do you want to know?
First My cluster 's SW_STORAGE_ES_RECORD_DATA_TTL is default value (7 days)
now I change the value to 3 days .

I restart all my skywalking cluster nodes .But the index segment-****  still have 7  indeies.

**Comment by wu-sheng** [comment]
It will active at middle night.

**Comment by seifeHu** [comment]
tks .got it !
