### ISSUE TITLE
alarm : if we have a service instance not work ,how to alarm

### ISSUE THREAD

**Issue by sunxingxiang** [apache/skywalking#4242]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
That is not supported today. To support this, the alarm should support the metrics of relationship, then you could set alarm at the client-side relationship metrics.

**Comment by sunxingxiang** [comment]
when this function can use?

**Comment by wu-sheng** [comment]
> when this function can use?

It depends on who and when will contribute this feature. AFAIK, no committer is working on this.

**Comment by sunxingxiang** [comment]
服务中要发送一个http 或者 resttemplate 请求如果 请求返回错误则除非报警，我们应该怎么做

**Comment by dagmom** [comment]
> 服务中要发送一个http 或者 resttemplate 请求如果 请求返回错误则触发报警，我们应该怎么做才能触发报警呢

https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-alarm.md

**Comment by wu-sheng** [comment]
We have the instance level metrics alarm now.
