### ISSUE TITLE
网差了去下载包下载不出来

### ISSUE THREAD

**Issue by fengwenchang** [apache/skywalking#4243]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
![image](https://user-images.githubusercontent.com/34081303/72491569-666cbf80-3855-11ea-872d-9eae9ffffd86.png)

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only.
