### ISSUE TITLE
Release 6.6 Not fixed the bug.  skywalking springcloud gateway plugin not suppot springcloud greenwish sr4

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#4252]
### Bug

- What happen?

same as 
https://github.com/apache/skywalking/issues/3985

I install release 6.6  . But this bug still happend 。   WebFlux and gateway are complex~。

**Comment by wu-sheng** [comment]
OK. Let's keep tracking this.

**Comment by wu-sheng** [comment]
@seifeHu Any update about this?

**Comment by CodeDestiny** [comment]
I have meet the same question

**Comment by seifeHu** [comment]
> @seifeHu Any update about this?

I change  my SpringCloud version to greenwish sr3 . It is work.
And   My rpc call traces In custom filter In spring apiGateway can not show.
 I develop a custom skywalking plugin . It is work too.  

tks.

**Comment by wu-sheng** [comment]
@seifeHu Then I will keep this open, as sr4 is not supported.

**Comment by baobeidaodao** [comment]
It seems that current version (6.6.0) also not support SpringCloud Hoxton.

**Comment by wu-sheng** [comment]
@baobeidaodao We never said `SpringCloud Hoxton` on the support list.

**Comment by wu-sheng** [comment]
The gateway plugin improved through #4878
