### ISSUE TITLE
Does the official plan to develop an alarm configuration page?

### ISSUE THREAD

**Issue by Lovnx** [apache/skywalking#4253]
Now we can only configure alarm by .yaml，When can the alarm configuration page be supported ?

**Comment by Lovnx** [comment]
Related feature: https://github.com/apache/skywalking/pull/3557

**Comment by wu-sheng** [comment]
SkyWalking doesn't work in this way. We are welcome the contributions, all features come from the contributor team by their own willings. So, if you want something, you should consider to propose a solution, work on that by your own team, we are super welcome you could talk with the committer team to push them upstream in the main repo.
