### ISSUE TITLE
[Plugin] Fastjson plugin

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#4254]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

We have plugin for [Gson](https://github.com/google/gson) now, [FastJson](https://github.com/alibaba/fastjson) should have its name on the supported list :)

**Comment by wu-sheng** [comment]
Moving this to help wanted as no progress and this is not critical.
