### ISSUE TITLE
Support evaluation using the returned object

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#4255]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

Now we can `tag` the span using the parameters of a method as stated [here](https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-trace.md), but the evaluation only supports parameters for now, it would be great to support tagging with the returned object like this:

```java
@Trace
@Tag(key = "username", value = "returnedObj.username")
@Tag(key = "age", value = "returnedObj.age")
public User methodYouWantToTrace(String param1, String param2) {
    // ...
}
```

**Comment by wu-sheng** [comment]
Haha, clearly, you are counting on Alibaba cloud tag based query very much :)

**Comment by kezhenxu94** [comment]
> Haha, clearly, you are counting on Alibaba cloud tag based query very much :)

Yes, it's a way to associate our business with the traces, in some degree 😄
