### ISSUE TITLE
Receiver implementation in Http protocol

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#4257]
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

We had an Http protocol implementation in version 1 before, but since v1 is going to be dropped, we may need to support it in v2 now, making [some other proposals](https://github.com/apache/skywalking/issues/4258) possible

**Comment by wu-sheng** [comment]
Two suggestion, 
1. Check whether grpc supports down grade to http1 or not.
2. If we need rest implementation hard coded, don't use short name like 5.x. Super unfriendly, and hard to understand.

**Comment by ElderJames** [comment]
I know that grpc must use http2 but grpc-web use http1.We maybe can support gpc-web.

**Comment by wu-sheng** [comment]
> I know that grpc must use http2 but grpc-web use http1.We maybe can support gpc-web.

We have jetty based container, so we could have native HTTP 1.1 query. Take a look at #4399
