### ISSUE TITLE
[NIGNX-LUA] Nginx plugin/module

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#4258]
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

As required [by the community](https://github.com/apache/skywalking/issues/4200) and the discussion between @wu-sheng and I, we're considering to provide a plugin/module in Nginx(maybe written in Lua), to make it possible to begin a trace in Nginx, or create spans in Nginx, the plugin/module should behave similar (in some degree) to that  in Java agent, more details and progress will be synchronized here, hopefully

**Comment by wu-sheng** [comment]
I would suggest this in a separate repo and do release independently. Of course, we need 7.0.0 release to work with it, unless we plan to use lua-grpc.
Due to new repo, please send a dev mail, and get permission from PMC.

**Comment by wu-sheng** [comment]
Also, after the setup is permitted, set up a new milestone for skywalking-nginx-lua subproject.

**Comment by wu-sheng** [comment]
A discussion landed here. https://lists.apache.org/thread.html/re075d6888bca580321c9d661596a819e2286798b6698695ad6d4abbc%40%3Cdev.apisix.apache.org%3E

**Comment by wu-sheng** [comment]
Another repo creation proposal has sent to the mail list.

**Comment by wu-sheng** [comment]
Finished by me. It belongs to another sub project , check the repo, https://github.com/apache/skywalking-nginx-lua.
