### ISSUE TITLE
i want to know the meaning of the filed "mapping_service_id" 

### ISSUE THREAD

**Issue by coki230** [apache/skywalking#4259]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
-  Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
i want to know the meaning of the filed "mapping_service_id" in "service_inventory". and why set the DestServiceId use this filed if the value is not null.

**Comment by wu-sheng** [comment]
We should read codes. That is not that simple. I am trying to publish a paper to introduce this, but haven't done yet.

**Comment by coki230** [comment]
thanks, if you publish a paper. please send the message to the home page. i will focus it.

**Comment by wu-sheng** [comment]
I will do that for sure, if I could make it passed.
