### ISSUE TITLE
Pick up system reserved threshold 500ms because of config missing

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#4260]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
oap server keeps showing up this log `Pick up system reserved threshold 500ms because of config missing`

I use docker-oap-es7
___

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by JaredTan95** [comment]
As you can see, it's just a `waring` log message. You can ignore or config `threshold ` through `dynamic config service` in `OAP`.

**Comment by stalary** [comment]
thanks

**Comment by zender-projects** [comment]
> As you can see, it's just a `waring` log message. You can ignore or config `threshold ` through `dynamic config service` in `OAP`.

but, server print it very fast, who to stop it?

**Comment by MWW0** [comment]
> 
How can I solve it?
