### ISSUE TITLE
Database ResponseTime not data

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#4261]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___

### Bug
- Which version of SkyWalking, OS and JRE?
docker-6.6-es7

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Database ResponseTime and not data in ui. but Database SLA and Database TopN Records have data

**Comment by bnubobby** [comment]
I'm in the same situation  

Which version of SkyWalking, OS and JRE?
docker-6.6-es7

What happen?
Database ResponseTime and not data in ui.
