### ISSUE TITLE
controller enhance 失败

### ISSUE THREAD

**Issue by dfsmallsky** [apache/skywalking#4262]
___
### Question
- What do you want to know?
为何无法 enhance controller,提示缺乏 witness class,使用的是传统 spring mvc 5.0.2版本,部署在 tomcat 中,已在 catalina.sh 中配置了 javaagent
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.6.0  linux openjdk1.8
- Which company or project?
crm
- What happen?
无法看到端点,无法 trace 到 端点,查看日志发下如下
WARN 2020-01-17 14:56:22:582 main AbstractClassEnhancePluginDefine : enhance class com.huatu.sku.web.controller.goods.SubGoodsController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v5.define.RestControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.resource.HttpResource is not existed.
另外还发现了kafka 的空指针报错,这不是重点,请重点看下 controller 无法 enhance 的问题,谢谢
ERROR 2020-01-17 17:05:33:430 kafka-consumer-issue.report.dev InstMethodsInter : class[class org.apache.kafka.clients.consumer.KafkaConsumer] after method[pollOnce] intercept failure
java.lang.NullPointerException
        at org.apache.skywalking.apm.plugin.kafka.KafkaConsumerInterceptor.afterMethod(KafkaConsumerInterceptor.java:61)

**Comment by dfsmallsky** [comment]
补充下,pom 里面是有 springmvc 的依赖的,并且HttpResource是存在于 spring-webmvc 包下的,应该能找到才对
	<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-webmvc</artifactId>
				<version>${spring.version}</version>
			</dependency>

**Comment by dfsmallsky** [comment]
在 catalina.sh 中添加了如下配置
CATALINA_OPTS="$CATALINA_OPTS -javaagent:/home/admin/agent/skywalking-agent.jar";export CATALINA_OPTS

**Comment by wu-sheng** [comment]
English only

**Comment by johnxue2013** [comment]
作者，你好，我奇怪的是既然你能看得懂中文，为什么不直接解答一下问题本身，为什么要英文才可以？

**Comment by heyanlong** [comment]
Because English is for everyone
