### ISSUE TITLE
Rocketbot 访问skywalking接口时间筛选相关问题

### ISSUE THREAD

**Issue by longdevops332** [apache/skywalking#4265]
各位大佬，请教一下，目前需要获取Skywalking中的统计信息制作报表。
Rocketbot追踪模块中
时间范围:2020-01-17 01:00:00 ~ 2020-01-17 02:00:00选择的是这样的，
怎么浏览器调试中接口访问，条件是"start":"2020-01-17 0600","end":"2020-01-17 0700","step":"MINUTE"   
各位大佬，有知道的吗？烦请指导指导

**Comment by wu-sheng** [comment]
English only.
