### ISSUE TITLE
Rocketbot time range and interface condition correspondence

### ISSUE THREAD

**Issue by longdevops332** [apache/skywalking#4266]
Everyone, please consult. At present, I need to get the statistics in skywalking to make a report.

In the rocketbot tracking module

Time range: 2020-01-17 01:00:00 ~ 2020-01-17 02:00:00,

How to access the interface in browser debugging under the conditions of "start": "2020-01-17 0600", "end": "2020-01-17 0700", "step": "MINUTE"

Everybody, do you know? Please guide me，Thank you!

**Comment by wu-sheng** [comment]
Read MetricQuery#getValues. There are time format converts about start and end time.  You will have the clue about this.
