### ISSUE TITLE
ServiceAndEndpointRegisterClient execute fail.  org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

### ISSUE THREAD

**Issue by xasnow** [apache/skywalking#4269]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1 ] Question or discussion
DEBUG 2020-01-19 13:59:08:395 main SkyWalkingAgent : On Transformation class com.snow.demo.web.Controllor. 
ERROR 2020-01-19 13:59:08:493 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:143)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:11800
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.net.ConnectException: Connection refused: no further information
	... 11 more

DEBUG 2020-01-19 13:59:08:776 main AbstractClassEnhancePluginDefine : prepare to enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation. 
WARN 2020-01-19 13:59:08:776 main AbstractClassEnhancePluginDefine : enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed. 
DEBUG 2020-01-19 13:59:08:776 main AbstractClassEnhancePluginDefine : prepare to enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by org.apache.skywalking.apm.plugin.spring.mvc.v4.define.ControllerInstrumentation. 
WARN 2020-01-19 13:59:08:777 main AbstractClassEnhancePluginDefine : enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.ControllerInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed. 
DEBUG 2020-01-19 13:59:08:777 main AbstractClassEnhancePluginDefine : prepare to enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by org.apache.skywalking.apm.plugin.spring.mvc.v4.define.ControllerForLowVersionInstrumentation. 
WARN 2020-01-19 13:59:08:777 main AbstractClassEnhancePluginDefine : enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.ControllerForLowVersionInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed. 
DEBUG 2020-01-19 13:59:08:777 main AbstractClassEnhancePluginDefine : prepare to enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by org.apache.skywalking.apm.plugin.spring.mvc.v5.define.ControllerInstrumentation. 
DEBUG 2020-01-19 13:59:08:777 main AbstractClassEnhancePluginDefine : enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by org.apache.skywalking.apm.plugin.spring.mvc.v5.define.ControllerInstrumentation completely. 
DEBUG 2020-01-19 13:59:08:777 main SkyWalkingAgent : Finish the prepare stage for org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController. 
DEBUG 2020-01-19 13:59:08:810 main SkyWalkingAgent : On Transformation class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController. 
DEBUG 2020-01-19 13:59:09:274 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2020-01-19 13:59:09:366 main AbstractClassEnhancePluginDefine : prepare to enhance class org.springframework.web.method.HandlerMethod by org.apache.skywalking.apm.plugin.spring.mvc.v3.define.HandlerMethodInstrumentation. 
WARN 2020-01-19 13:59:09:366 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed. 
DEBUG 2020-01-19 13:59:09:366 main AbstractClassEnhancePluginDefine : prepare to enhance class org.springframework.web.method.HandlerMethod by org.apache.skywalking.apm.plugin.spring.mvc.v4.define.HandlerMethodInstrumentation. 
WARN 2020-01-19 13:59:09:366 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed. 
DEBUG 2020-01-19 13:59:09:366 main AbstractClassEnhancePluginDefine : prepare to enhance class org.springframework.web.method.HandlerMethod by org.apache.skywalking.apm.plugin.spring.mvc.v5.define.HandlerMethodInstrumentation. 
DEBUG 2020-01-19 13:59:09:368 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.HandlerMethod by org.apache.skywalking.apm.plugin.spring.mvc.v5.define.HandlerMethodInstrumentation completely. 
DEBUG 2020-01-19 13:59:09:369 main SkyWalkingAgent : Finish the prepare stage for org.springframework.web.method.HandlerMethod. 
DEBUG 2020-01-19 13:59:09:385 main SkyWalkingAgent : On Transformation class org.springframework.web.method.HandlerMethod. 
DEBUG 2020-01-19 13:59:09:391 main AbstractClassEnhancePluginDefine : prepare to enhance class org.springframework.web.method.support.InvocableHandlerMethod by org.apache.skywalking.apm.plugin.spring.mvc.v3.define.InvocableHandlerInstrumentation. 
WARN 2020-01-19 13:59:09:391 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.support.InvocableHandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.InvocableHandlerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed. 
DEBUG 2020-01-19 13:59:09:391 main AbstractClassEnhancePluginDefine : prepare to enhance class org.springframework.web.method.support.InvocableHandlerMethod by org.apache.skywalking.apm.plugin.spring.mvc.v4.define.InvocableHandlerInstrumentation. 
WARN 2020-01-19 13:59:09:392 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.support.InvocableHandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.InvocableHandlerInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed. 
DEBUG 2020-01-19 13:59:09:401 main SkyWalkingAgent : On Transformation class org.springframework.web.method.support.InvocableHandlerMethod. 
DEBUG 2020-01-19 13:59:09:501 main AbstractClassEnhancePluginDefine : prepare to enhance class org.springframework.aop.framework.DefaultAopProxyFactory by org.apache.skywalking.apm.plugin.spring.patch.define.AopProxyFactoryInstrumentation. 
DEBUG 2020-01-19 13:59:09:503 main AbstractClassEnhancePluginDefine : enhance class org.springframework.aop.framework.DefaultAopProxyFactory by org.apache.skywalking.apm.plugin.spring.patch.define.AopProxyFactoryInstrumentation completely. 
DEBUG 2020-01-19 13:59:09:503 main SkyWalkingAgent : Finish the prepare stage for org.springframework.aop.framework.DefaultAopProxyFactory. 
DEBUG 2020-01-19 13:59:09:514 main SkyWalkingAgent : On Transformation class org.springframework.aop.framework.DefaultAopProxyFactory. 
DEBUG 2020-01-19 13:59:10:061 main AbstractClassEnhancePluginDefine : prepare to enhance class org.apache.catalina.core.StandardHostValve by org.apache.skywalking.apm.plugin.tomcat78x.define.TomcatInstrumentation. 
DEBUG 2020-01-19 13:59:10:065 main AbstractClassEnhancePluginDefine : enhance class org.apache.catalina.core.StandardHostValve by org.apache.skywalking.apm.plugin.tomcat78x.define.TomcatInstrumentation completely. 
DEBUG 2020-01-19 13:59:10:065 main SkyWalkingAgent : Finish the prepare stage for org.apache.catalina.core.StandardHostValve. 
DEBUG 2020-01-19 13:59:10:088 main SkyWalkingAgent : On Transformation class org.apache.catalina.core.StandardHostValve. 
DEBUG 2020-01-19 13:59:12:270 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
DEBUG 2020-01-19 13:59:15:269 SkywalkingAgent-5-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:DISCONNECT. 
___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by xasnow** [comment]
environment：
apache-skywalking-apm-bin-es7
elasticsearch-7.5.1
jdk 1.8

**Comment by wu-sheng** [comment]
Your backend is not available.
