### ISSUE TITLE
Topology ui Service SLA show error

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#4273]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
docker-6.6-ui

- What happen?
Topology ui Service SLA show error, Service SLA is 100%, but show 1.00%

**Comment by wu-sheng** [comment]
Which one? Could you provide a snapshot?

**Comment by wu-sheng** [comment]
![image](https://user-images.githubusercontent.com/5441976/72696601-cc1fbb00-3b77-11ea-8e11-c7a5663706ad.png)

This one?

**Comment by stalary** [comment]
> ![image](https://user-images.githubusercontent.com/5441976/72696601-cc1fbb00-3b77-11ea-8e11-c7a5663706ad.png)
> 
> This one?

yes

**Comment by wu-sheng** [comment]
Could you submit a pull request to fix this?

**Comment by stalary** [comment]
I'm not familiar with the front end, sorry

**Comment by wu-sheng** [comment]
@Fine0830 @x22x22 @TinyAllen Any of you could provide help? Or after the Chinese new year vacation? It is not urgent.

**Comment by x22x22** [comment]
give it to me.

**Comment by Fine0830** [comment]
Thanks @x22x22 working for this
