### ISSUE TITLE
is it able to change the UI binding port from 8080 to another?

### ISSUE THREAD

**Issue by godlockin** [apache/skywalking#4275]
env: Centos
version: 6.6.0-es7

This scenario blocked me a lot that, as a Java dev, we always open & monitor 8080 to offer our backend service, but, when I need to deploy skywalking the same node with my service, I have no idea but changing my port of service from 8080 to other one (e.g. 8081), so that I can access the skywalking UI then

And, I searched the config files & other online doc, but no one else can tell the stable way to change this config. 

So, my question is, is it able to change the default UI port of skywalking from 8080 to others instead of  modify the code and re-complie it?

**Comment by wu-sheng** [comment]
There is an application.yml in the UI project. You could change it by yourself.

**Comment by happytimor** [comment]
you can change port in apache-skywalking-apm-bin/webapp/webapp.yml
