### ISSUE TITLE
Can I disable jvm receiver?

### ISSUE THREAD

**Issue by f02061232-1** [apache/skywalking#4277]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is there any configuration that can disable JVM receiver? 
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read receiver doc. You could disable It by changing the YAML.
