### ISSUE TITLE
Micrometer Registry support for Skywalking Metrics

### ISSUE THREAD

**Issue by krmeda** [apache/skywalking#4279]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x]  Question or discussion
- [ ]  Bug
- [ ]  Requirement
- [x]  Feature or performance improvement

Question
What do you want to know?

I am interested in seeing micrometer support, because as an application developer I am interested in making custom metrics in one abstraction layer. For Spring Boot + Java language micrometer is giving me the flexibility to create metrics and then decide later at runtime where the metric needs to go or who it integrates to.

If Skywalking uses agents to gather information, then proposal would be to have an implementation of micrometer `MeterRegistry`[here](https://micrometer.io/docs/guide/customMeterRegistry) to plug into the existing skywalking metrics ingesting capabilities.  

That would allow for use cases where in development environment, i can bring up just my micro-service, and automated test my microservice is creating custom metric correctly using a prometheus exporter but in live environments, I turn on skywalking agent and have metrics stream.

_Originally posted by @wu-sheng in https://github.com/apache/skywalking/issues/3053#issuecomment-510691895_

**Comment by wu-sheng** [comment]
Sorry for the late, I am just back from the vacation. I am a part of Zipkin, but new to the micrometer.

What kinds of metrics do you propose to gather? And how gather it? In SkyWalking implementation, besides JVM metrics, others are being analyzed at the backend. Could you a little more detailed?

**Comment by wu-sheng** [comment]
Basically, the plugin system is open to others. You don't have to trace in there, I know many other users are doing this. If you want to propose a new or some plugins to make Micrometter working, please provide the details about which plugins you want to do.

**Comment by krmeda** [comment]
My proposal is to write an adapter for micrometer which plugs into micrometer end and publish metrics using skywalking support. It allows end users who create custom metrics in an application/library to express that metric in micrometer format and not care about which monitoring tool is loaded in order to surface those metrics.

**Comment by wu-sheng** [comment]
Today, SkyWalking doesn't have custom metrics, and here is the protocol, https://github.com/apache/skywalking-data-collect-protocol

How do you plan to send the metrics?

**Comment by krmeda** [comment]
Idea was when the skywalking java agent is enabled/loaded it registers the micrometer-skywalking adapter and then the skywalking agent already uses its implementation to send it to the skywalking server. My library/application has no knowledge where the metrics are going... it is only producing it... 

Similar to Slf4j...

**Comment by wu-sheng** [comment]
I think the metrics receiver is the gap. SkyWalking is keeping making sure to understand the data, including all metrics, so it does accept the agent, Istio and Envoy telemetry formats, rather than like Prometheus receiving the data and focusing on data type only.

**Comment by wu-sheng** [comment]
@krmeda The action is happening, as we are going to enhance the UI dashboard. 

https://lists.apache.org/thread.html/r79e6e0057bc16a3df77234286753404149652dcd35c3378312f23c11%40%3Cdev.skywalking.apache.org%3E

You could use this way to join our mail list for joining the discussion and action progress.
> Mail list: dev@skywalking.apache.org. Mail to dev-subscribe@skywalking.apache.org, follow the reply to subscribe the mail list.

**Comment by wu-sheng** [comment]
Or if you have time, we could set up an online meeting. You could help me on a quick and accurate understanding of the micrometer

**Comment by wu-sheng** [comment]
We supported this in the 8.1.0 release. @krmeda Could we work on a blog to post on the Spring website? Or how should we update the micrometer website?
