### ISSUE TITLE
Skywalking-No service or trace in UI - Windows machine

### ISSUE THREAD

**Issue by sujithkumar28** [apache/skywalking#4280]
I'm trying to setup skywalking in windows machine with a sample springboot application.

Skywalking version: 6.6.0
Java: 1.8

I've made the changes to agent.config with service name as BOOT_MVC and collector server as localhost. 

After all these configs I've run startup.bat from skywalking agent bin which is starting collector and webapp.

I'm starting my application with following command

java -javaagent:E:\Suju\apache-skywalking-apm-bin\agent\skywalking-agent.jar 
-DSW_AGENT_NAME=BOOT_MVC -jar MyApp.jar

I couldn't see any service or trace. What am i missing here? can anyone provide stepbystep guide to setup in windows?

**Comment by wu-sheng** [comment]
We can't tell the issue from your description. Please Check the logs.

**Comment by sujithkumar28** [comment]
Logs suggest that the services are running and reconnect: false. How to check if oap service is running properly at the background?

**Comment by wu-sheng** [comment]
There are also OAP logs in the log folder.

**Comment by R1310328554** [comment]
it seems the web cache cause this problem. clear the all cache solve the issue for me:

![图片](https://user-images.githubusercontent.com/9073658/73515639-ffdcc980-4430-11ea-88ef-89cf79156741.png)

**Comment by Starbucksstar** [comment]
> 似乎网络缓存导致了此问题。清除所有缓存为我解决问题：
> 
> ![图片](https://user-images.githubusercontent.com/9073658/73515639-ffdcc980-4430-11ea-88ef-89cf79156741.png)

清除浏览器缓存后service显示正常
