### ISSUE TITLE
service name is always unknown

### ISSUE THREAD

**Issue by yuquan-wang** [apache/skywalking#4281]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
I use openTelemetry-collector to export jaeger traces to skywalking-collectors, and i deployed skywalking-kubernetes in my k8s cluster, i can see traces in skywalking UI correctly, except for the service name, here's the screen for the trace:
![Screenshot from 2020-01-27 13-53-02](https://user-images.githubusercontent.com/43105533/73150974-7796b580-410c-11ea-9980-3926935ea02d.png)
![unknown](https://user-images.githubusercontent.com/43105533/73151075-f68bee00-410c-11ea-9bb6-2811419e706b.png)

note the exported traces can be correctly shown in jaeger UI, so i'm thinking if i missed anything?(I already enable jaeger receiver)
Thanks in advance!

**Comment by wu-sheng** [comment]
You need to check why Jeager missed the service name

**Comment by yuquan-wang** [comment]
> You need to check why Jeager missed the service name

@wu-sheng  thanks for quick reply! if Jaeger missed the service name, then how could it show that in its UI?

**Comment by wu-sheng** [comment]
Service name used to be an official field. I don't know whether it changes. Jaeger is not our high priority task. Especially, as we have SkyWalking go SDK.
