### ISSUE TITLE
Upgrade all java compiler versions to 1.8 

### ISSUE THREAD

**Issue by JohnNiang** [apache/skywalking#4285]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

---

### Feature or performance improvement

We should use the more powerful features about Java 8 or more. Related: <https://github.com/apache/skywalking/issues/4256>

**Comment by wu-sheng** [comment]
What is the issue? This should have been updated already.

**Comment by JohnNiang** [comment]
Maybe there's somewhere missing:

1. <https://github.com/apache/skywalking/blob/8e4c1e95d64f5fafda45629fa294270864f3ff1b/apm-commons/pom.xml#L40>

2. https://github.com/apache/skywalking/blob/8e4c1e95d64f5fafda45629fa294270864f3ff1b/apm-application-toolkit/pom.xml#L30

3. https://github.com/apache/skywalking/blob/8e4c1e95d64f5fafda45629fa294270864f3ff1b/test/plugin/scenarios/jdk-threading-scenario/pom.xml#L29

**Comment by kezhenxu94** [comment]
> Maybe there's somewhere missing:
> 
> 1. https://github.com/apache/skywalking/blob/8e4c1e95d64f5fafda45629fa294270864f3ff1b/apm-commons/pom.xml#L40
> 2. https://github.com/apache/skywalking/blob/8e4c1e95d64f5fafda45629fa294270864f3ff1b/apm-application-toolkit/pom.xml#L30
> 3. https://github.com/apache/skywalking/blob/8e4c1e95d64f5fafda45629fa294270864f3ff1b/test/plugin/scenarios/jdk-threading-scenario/pom.xml#L29

Go ahead and fix them please

**Comment by JohnNiang** [comment]
A little while.
