### ISSUE TITLE
Can I integrate Kafka with skywalking?

### ISSUE THREAD

**Issue by sujithkumar28** [apache/skywalking#4287]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question
- [ ] Requirement
- [ ] Feature

___
### Question
- What do you want to know?
 Can I have the skywalking data posted to Kafka instead of es or h2? Should I include the transport of data at Kafka plugin level ?
___
### Requirement or improvement
- To maintain the data of apm

**Comment by kezhenxu94** [comment]
Please refer to https://github.com/apache/skywalking/blob/master/docs/en/FAQ/why_mq_not_involved.md

may be duplicate of #4282
