### ISSUE TITLE
Skywalking Couldn't view H2 console

### ISSUE THREAD

**Issue by sujithkumar28** [apache/skywalking#4290]
Please answer these questions before submitting your issue.

I' new to skywalking. I've tried to implement skywalking agent. I'm trying to view h2 console where skywalking stores the data. How to view h2 console in skywalking. I've tried accessing with http://localhost:8080/login.do?jsessionid=someid but couldn't view it

**Comment by kezhenxu94** [comment]
No you can't access the H2 console by default, if you have to, please start H2 in server mode, for more information, please refer to http://h2database.com/html/features.html#auto_mixed_mode
