### ISSUE TITLE
Skywalking database connectivity understanding doc

### ISSUE THREAD

**Issue by sujithkumar28** [apache/skywalking#4293]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
This is to understand skywalking.

I'm new to skywalking. I want to understand how data as a whole sent to h2. Anyone naming the files to be looked after will be much helpful.

**Comment by wu-sheng** [comment]
`MetricsPersistentWorker` for metrics, topology, and topN. `RecordStreamProcessor` for traces.

**Comment by wu-sheng** [comment]
H2 is just an implementation of storage.

**Comment by sujithkumar28** [comment]
Thanks a lot for your reply. I'm trying to store the metrics into a file as json. Is there a guide to debug skywalking agent? Can the datacarrier object be made a json

**Comment by wu-sheng** [comment]
No. Basically, the thing doesn't work in this way. SkyWalking is an APM system, not as simply as you described.

**Comment by sujithkumar28** [comment]
Sorry!! If that was simply explained. I do understand that this is a very complex system that is developed, which made me curious to understand the underlying deatails. I've put my requirements in simple words. As far as my understand,the trace and method metrics are passed on to H2. Since we don't have a H2 console enabled and as I'm facing issues with configuring external h2. I just wanted to look at the raw data rather than UI. since I'm new to instrumentation I've put forth my requirements in simple words. I really appreciate your patience and quick replies. Thank you

**Comment by wu-sheng** [comment]
If you want to the outline, read the protocol documents, which could set the boundaries.
