### ISSUE TITLE
Agent issue with Java Spring framework

### ISSUE THREAD

**Issue by raybah** [apache/skywalking#4294]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Question or discussion
-  Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How we can resolve this issue?

For example, we can try to use older version of agent, or try to use newer version of Spring framework. Please help with this or or suggest other solutions. Also I hope this issue will be fixed in next versions of Skywalking. 

___
### Bug
- Which version of SkyWalking, OS and JRE?

Skywalking - 6.6.0 release (http://apache-mirror.rbc.ru/pub/apache/skywalking/6.6.0/apache-skywalking-apm-es7-6.6.0.tar.gz)
OS - CentOS release 6.5 (Final)
JRE - "1.8.0_92"
[java_info.txt](https://github.com/apache/skywalking/files/4127760/java_info.txt)
Spring version - "4.0.5"
Tomcat version - "7.0.35.0"

- Which company or project?

Company - Tango me
Project - APM research methods, trying to find solution for applications performance monitoring

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Skywalking server and agent have been deployed on server according documentation. Configuration parameters:
server - by default
agent - by default except:
agent.service_name=${SW_AGENT_NAME:controllerator}
collector.backend_service=${SW_AGENT_COLLECTOR_BACKEND_SERVICES:172.20.2.66:11800}

We want to monitor application which was deployed in Apache Tomcat server. All worked properly for a few hours, seems like after some request in app we received an error from skywalking agent, see logs attached.
 
[agent_bug.txt](https://github.com/apache/skywalking/files/4127882/agent_bug.txt)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You could check out supported test cases.
https://github.com/apache/skywalking/tree/master/test/plugin/scenarios

You could look through the test demo we wrote for testing.

**Comment by raybah** [comment]
@wu-sheng thanks for the answer. Please help with understanding what should we do with these scenarios? Should we deploy these as a plugins to Skywalking server? Or we should only make changes in configs?
Also if we deploy older versions of Skywalking agent/server, will it help?
thanks in advance

**Comment by wu-sheng** [comment]
Those are test codes. You could see they are common Spring app, it could be traced and monitored by SkyWalking agent. I don't know the real issue you asked.

I recommend you compare our tests with yours.

**Comment by wu-sheng** [comment]
The key is providing a demo code to replicate your error in a very simple demo.
