### ISSUE TITLE
Skywalking build failure

### ISSUE THREAD

**Issue by sujithkumar28** [apache/skywalking#4295]
I'm trying to build skywalking source in windows by executing the command

mvnw clean package -DskipTests but i'm receiving the following error

Dependencies for project org.apache.skywalking:apm-pulsar-plugin:jar:6.6.0: Faile
d to collect dependencies at org.apache.pulsar:pulsar-client:jar:2.4.0: Failed t
o read artifact descriptor for org.apache.pulsar:pulsar-client:jar:2.4.0: Could
not transfer artifact com.amazonaws:aws-java-sdk-bom:pom:1.11.297 from/to centra
l (https://repo1.maven.org/maven2): Connect to repo1.maven.org:443 [repo1.maven.
org/151.101.120.209] failed: Connection timed out: connect -> [Help 1]

**Comment by wu-sheng** [comment]
I think this is your local maven or network issue. Every release has been checked in the CI and release process.

Pulsar 2.4.0 is existing, https://mvnrepository.com/artifact/org.apache.pulsar/pulsar-client
