### ISSUE TITLE
Top 20 slow traces remove ?

### ISSUE THREAD

**Issue by 17173YeYu** [apache/skywalking#4296]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hello , did the Top 20 slow traces have removed in 6.0.0+?
where is the the time consumption of method ？I can find it.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by 17173YeYu** [comment]
Hello , did the Top 20 slow traces have removed in 6.0.0+?
where is the the time consumption of method ？I can find it.

**Comment by wu-sheng** [comment]
Top slow trace is based on trace query, nothing more.
