### ISSUE TITLE
6.0.0+版本最细的追踪粒度

### ISSUE THREAD

**Issue by 17173YeYu** [apache/skywalking#4297]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
6.0.0+版本最细的追踪粒度只能接口级别吗？ 原来的5.0.0+版本不是可以最终每个方法级别的时间消耗吗?  6.0.0+还能做到吗？ 如果6.0.0+没有了，那我该怎么追踪整个调用链上每个方法的耗时呢？
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by 17173YeYu** [comment]
6.0.0+版本最细的追踪粒度只能接口级别吗？ 原来的5.0.0+版本不是可以最终每个方法级别的时间消耗吗?  6.0.0+还能做到吗？ 如果6.0.0+没有了，那我该怎么追踪整个调用链上每个方法的耗时呢？

**Comment by wu-sheng** [comment]
English only.
