### ISSUE TITLE
How can I trace the time consum of every method now in 6.0.0+ ?

### ISSUE THREAD

**Issue by 17173YeYu** [apache/skywalking#4298]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How can I trace the time consum of every method now in 6.0.0+ ?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by 17173YeYu** [comment]
How can I trace the time consum of every method now in 6.0.0+ ?

**Comment by wu-sheng** [comment]
That is not possible if you do this in production env. This will make the latency of your app very bad. 
You could trace some of them by using the optional plugins. Read the agent optional plugin doc. there are spring bean plugin and customize plugin. https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#optional-plugins
