### ISSUE TITLE
How to use the plugin ---- Spring annotation plugin?

### ISSUE THREAD

**Issue by 17173YeYu** [apache/skywalking#4299]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to use the plugin ---- Spring annotation plugin?
Is there any doc about how to use it?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by 17173YeYu** [comment]
How to use the plugin ---- Spring annotation plugin?
Is there any doc about how to use it?

**Comment by wu-sheng** [comment]
Please read the document first. It is very clear there.
