### ISSUE TITLE
[CLI] Command to display thread profiling result

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#4312]
FYI @kezhenxu94 The whole profile should work for CLI too. We should add an issue to track.

_Originally posted by @wu-sheng in https://github.com/apache/skywalking/pull/4308#issuecomment-581792828_

**Comment by wu-sheng** [comment]
I prefer this to be 0.3.0, as it is sharing tech codes about trace tree and profile result tree. WDYT?

**Comment by kezhenxu94** [comment]
make sense to me

**Comment by kezhenxu94** [comment]
Closed by https://github.com/apache/skywalking-cli/pull/104
