### ISSUE TITLE
cannot compile with offical doc

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4316]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question1 
- What do you want to know?
when I compile the skywalking in the following steps:
1. git submodule init
2. git submodule update
3. Run ./mvnw clean package -DskipTests

the some error occurs:

![image](https://user-images.githubusercontent.com/31562192/73746109-73633b80-478f-11ea-8806-ad0f1e445157.png)
cannot find this proto file 

___
### Question12
- What do you want to know?
how to run springboot ui  module in idea ?

thanks for your helping

**Comment by wu-sheng** [comment]
I assume you download source codes from wrong place.

> how to run springboot ui module in idea ?

You can't.

**Comment by EvanLjp** [comment]
how to run ui module in local mode,the first question I will try agin

**Comment by wu-sheng** [comment]
Read UI document, https://github.com/apache/skywalking-rocketbot-ui#dev-build

**Comment by EvanLjp** [comment]
![image](https://user-images.githubusercontent.com/31562192/73748635-cee3f800-4794-11ea-8223-bce8f96e6ad0.png)
![image](https://user-images.githubusercontent.com/31562192/73748656-d99e8d00-4794-11ea-9223-1ae8d7d5175e.png)
still have this problem ,when git checkout v6.6.0

**Comment by wu-sheng** [comment]
Which JDK are you using? `javax.annotation` belongs to JDK's `rt.jar`. It is not SkyWalking's issue.

**Comment by EvanLjp** [comment]
when I checkout java verison from jdk 11 to jdk8,i successed

**Comment by wu-sheng** [comment]
Step 1, Prepare git, JDK8 and maven3

SkyWalking requires compiling in JDK8, but you could run in JDK8-12

**Comment by EvanLjp** [comment]
I found the oap module have some code about jdk9? what is the releationship between oap and jdk9

**Comment by EvanLjp** [comment]
thanks for your helping ,I will remember this one,thankyou
