### ISSUE TITLE
telemetry module

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4319]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
I am going to use skywalking in my company, but have doubts about the role of the telemetry module

thannks for your helping

The following graph is about skywalking6 in my mind:

![image](https://user-images.githubusercontent.com/31562192/73805557-f2915780-4801-11ea-8bcc-ee96944f093f.png)

**Comment by wu-sheng** [comment]
What is your question?

**Comment by EvanLjp** [comment]
When do I need to use it, Is there an official introduction document? I don't find it

**Comment by wu-sheng** [comment]
The document is in the backend setup already for a long time. https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-setup.md#telemetry-for-backend
