### ISSUE TITLE
There is no data shown in the dashboard

### ISSUE THREAD

**Issue by GitHub-Yann** [apache/skywalking#4324]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [Y ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why there is no data shown in the dashboard
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking : 6.5.0
OS : CentOS Linux release 7.7.1908 (Core)
JRE : 1.8.0_191

- Which company or project?
personal demo

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
(1)I download the skywalking from https://mirrors.tuna.tsinghua.edu.cn/apache/skywalking/6.5.0/apache-skywalking-apm-6.5.0.tar.gz
(2)unzip the package in my VMware
(3)change the server.port to 18080
(4)execute the command "./startup.sh"
![image](https://user-images.githubusercontent.com/9768021/74023891-ab5ebe80-49db-11ea-825d-cbae3af9353a.png)

(5)the home page is shown
![image](https://user-images.githubusercontent.com/9768021/74023784-68045000-49db-11ea-9ece-0abe42690ad2.png)

(6)then I use below command to start my project "java -javaagent:/opt/microservice/client/agent/skywalking-agent.jar -jar -Xmx128m consumer-0.0.1-SNAPSHOT.jar"
(7)visit the exposed interface of the project some times, expected result is shown
![image](https://user-images.githubusercontent.com/9768021/74023816-81a59780-49db-11ea-84c1-10338c07bf4d.png)

(8)then I checked the skywalking page , there is no data shown in the page

Is there any wrong ?
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by GitHub-Yann** [comment]
I change the data range under the browser , the data is shown

**Comment by longdevops332** [comment]
> I change the data range under the browser , the data is shown

* I'm the same
