### ISSUE TITLE
Reduce two steps while cloning project and subprojects

### ISSUE THREAD

**Issue by JohnNiang** [apache/skywalking#4331]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

We could reduce two steps inside [build-from-github](https://github.com/apache/skywalking/blob/master/docs/en/guides/How-to-build.md#build-from-github).

```diff
+ 2. git clone --recurse-submodules https://github.com/apache/skywalking.git
- 2. git clone https://github.com/apache/skywalking.git
- 5. git submodule init
- 6. git submodule update
```

So, what do you reckon?

**Comment by wu-sheng** [comment]
They are same thing to me.

**Comment by JohnNiang** [comment]
Same thing to me. But more convinient for fresh users.

**Comment by wu-sheng** [comment]
Maybe both ways in the doc as alternative?

**Comment by JohnNiang** [comment]
Not bad.

**Comment by wu-sheng** [comment]
Submit a pull request if you like.

**Comment by JohnNiang** [comment]
Okay.
