### ISSUE TITLE
topology: That 3 servers point to the same mysql at the same time

### ISSUE THREAD

**Issue by fadeli1** [apache/skywalking#4345]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I have 3 servers with the following structure:
10.1.0.19-> agent-> ofbiz1-> 127.0.0.1mysql
10.1.0.19-> agent-> ofbiz2-> 127.0.0.1mysql
10.1.0.11-> agent-> ofbiz-> 127.0.0.1mysql

Displayed in topology as:
10.1.0.19-> 127.0.0.1 mysql
10.1.0.19-> 127.0.0.1 mysql
10.1.0.11-> 127.0.0.1 mysql
That 3 servers point to the same mysql at the same time

How can I make it distinguish between mysql in 10.1.0.19 and mysql in 10.1.0.11?
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.6.0
centos7
jre 8

- Which company or project?
Customized ofbiz

- What happen?

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think currently you can't, unless you use the different hostnames to access the local database.
