### ISSUE TITLE
cross MQ trace 

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4358]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
*Today we conducted a review of using skywalking in online system.*
Someone asked a question:
```
a call is like following:
user====> ServiceA
                        ||
                       \ /
                        MQ
                        ||
                       \ /
                       ServiceB
```
could skywalking link the serviceA and ServiceB in the mode?

Thanks for your helping

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Simple answer, have you tried?

**Comment by wu-sheng** [comment]
In the open source community, we provide limited supports only.

**Comment by EvanLjp** [comment]
thanks for your helping, i Will try this feature with kafka
