### ISSUE TITLE
Deploy skywalking in a production environment.

### ISSUE THREAD

**Issue by fadeli1** [apache/skywalking#4365]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I want to deploy skywalking in a production environment.

1. I want to enable TLS, but I don't know how to configure it in application.yml. I have multiple agent clients.
2. I want to enable agent.authentication configuration, but I don't know how to configure it in application.yml

Can you give me some suggestions for deploying a production environment? please help me!
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.6.0
centos 7
java 8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> I want to enable TLS, but I don't know how to configure it in application.yml. I have multiple agent clients.

TLS is not being supported at the backend. If you have interests, please make a pull request to move the 5.x support codes to the master.

> I want to enable agent.authentication configuration, but I don't know how to configure it in application.yml

Only enable in next release. https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-token-auth.md

**Comment by wu-sheng** [comment]
@fadeli1 TLS is not so urgent. You could use a proxy to support that. It is easy.
