### ISSUE TITLE
apm-webapp  compile failed

### ISSUE THREAD

**Issue by nbacheng** [apache/skywalking#4369]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to solve this problem.
___
### Bug
- Which version of SkyWalking, OS and JRE?
   6.6es7,centos7.2,java1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Under skywalking6.6/apm-webapp directory, I want to compile apm-webapp project with mvn package - dmaven. Test. Skip = true, but the following error occurs. Please ask why?

Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project apm-webapp: Failed during checkstyle configuration: cannot initialize module TreeWalker - cannot initialize module ImportControl - illegal value 'apm-checkstyle/importControl.xml' for property 'file': com.puppycrawl.tools.checkstyle.api.Checks tyleException: Unable to find: apm-checkstyle/importControl.xml -> [Help 1]

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Where do you download the source code? I am feeling it is not from our GitHub or release.

**Comment by wu-sheng** [comment]
Every commit in this PR has been checked and passed the compiling and tests.

**Comment by nbacheng** [comment]
http://mirror.bit.edu.cn/apache/skywalking/6.6.0/apache-skywalking-apm-6.6.0-src.tgz

**Comment by wu-sheng** [comment]
That could be compiled, several PMC members have checked that in the release process.

**Comment by nbacheng** [comment]
Thank you. I'll check it myself again.

**Comment by tankilo** [comment]
I also came across this prolem., To be honest, it's very hard to compile this project on Windows.   
My code is  the latest master branch.   
If i compile module `apm-webap` alone , the following error will be raised.   
``` 
C:\Coding\Code\Github\skywalking\apm-webapp>mvn clean install -DskipTests -Drat.skip=true
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building apm-webapp 7.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ apm-webapp ---
[INFO] Deleting C:\Coding\Code\Github\skywalking\apm-webapp\target
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ apm-webapp ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java) @ apm-webapp ---
[INFO]
[INFO] --- os-maven-plugin:1.6.2:detect (default) @ apm-webapp ---
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
[INFO]
[INFO] --- maven-checkstyle-plugin:3.1.0:check (validate) @ apm-webapp ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.773 s
[INFO] Finished at: 2020-03-08T18:23:42+08:00
[INFO] Final Memory: 27M/279M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project apm-webapp: Failed during checkstyle configuration: cannot initialize module TreeWalker - cannot initialize module ImportControl - illegal value 'apm-checkstyle/importControl.xml' for property 'file': com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: apm-checkstyle/importControl.xml -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
