### ISSUE TITLE
Topology view page ES node type show Unknow.

### ISSUE THREAD

**Issue by aderm** [apache/skywalking#4370]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

<img width="743" alt="WX20200216-200511@2x" src="https://user-images.githubusercontent.com/2892433/74604365-49e3d180-50f8-11ea-9ddd-3b7193854bf0.png">
<img width="1081" alt="WX20200216-200600@2x" src="https://user-images.githubusercontent.com/2892433/74604371-510adf80-50f8-11ea-957d-b90466830dc5.png">

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Should be replaced by #4386
