### ISSUE TITLE
[SWCK] Initiate Backend Operator

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#4373]
The proposal of SkyWalking Cloud on Kubernetes is put in [mail list ](https://lists.apache.org/thread.html/d9a4c881ac3987af5d5aaf64ff8a3d97ba7155a98a47c736e7214268%40%3Cdev.skywalking.apache.org%3E) for a while, and it got several positive feedback from the whole community. 

Now I will push it to the next step:

* Create a new repo for SWCK, and compose issues to the main repo.
 * If anyone interest in this work, please reply to this thread. I have got some requests from offline, and also open to new members.
 * I drafted the design of the operator(https://docs.google.com/document/d/12s9d0XfL42F7qJeBXWbBvR2zc1tYEEDVOqJ4tM-8Ejc/edit?usp=sharing). needs reviewer on it.

Our short-term goal is:
 * Release the first version of the operator.
 * Document usage.
 * Free from critical bugs by integration test.

**Comment by hanahmily** [comment]
@innerpeacez @wayilau @dmsolr @wu-sheng Please help me review the design document. Thanks.

**Comment by wayilau** [comment]
This is a great job.  @Gao Hongtao<mailto:notifications@github.com>

**Comment by wu-sheng** [comment]
I replied on the design. And please add a milestone for SWCK, like other sub projects.

**Comment by clk1st** [comment]
I am interested in participating in SWCK development, thank you

**Comment by MAlj11** [comment]
I am interested in SWCK and want to be a developer of this project

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-swck repo created, please go ahead. The discussion should happens in PR review and our mail list. Glad to have you all to support this.

**Comment by hanahmily** [comment]
@clk1st @MAlj11 Glad to see you interested in this project. 

I have told with @clk1st about the details of the whole procedure. He is working on the OAP server. 

@MAlj11 Can you send a mail to hanahmily@apache.org, and we can dig into this topic, English/Chinses are all welcome.

**Comment by wu-sheng** [comment]
We had the 0.1.0 RC on the mail list.
