### ISSUE TITLE
Checkstyle plugin checks test codes too

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#4377]
Currently, the Checkstyle plugin in `pom.xml` of the root project only checks codes in the root project and its submodules, we also need to check those codes in `test/e2e` and `test/plugin`

- reusethe same checkstyle configurations

- add Checkstyle plugin in the `test/plugin/pom.xml` and `test/e2e/pom.xml`, and add the Checkstyle goal to `.github/workflow/plugins-test.yml` and `.github/workflow/e2e.yml`

**Comment by kezhenxu94** [comment]
@huangbowen521 are you going to do this :)

**Comment by huangbowen521** [comment]
I will work on it

**Comment by wu-sheng** [comment]
Move this to help wanted, as PR isn't updated for a long time.

**Comment by vcjmhg** [comment]
@wu-sheng , is there anyone else currently working on this issue? If not I can have a try.

**Comment by wu-sheng** [comment]
@vcjmhg I am not sure what is the status. You could try first.

**Comment by vcjmhg** [comment]
ok
