### ISSUE TITLE
when ues helm install, In addition to oap.envoy.als.enabled parameter, where are the other parameters?

### ISSUE THREAD

**Issue by justmine66** [apache/skywalking#4380]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how open SkyWalking envoy receiver in k8s, the following configuration needs to be added
application.yaml:
envoy-metric:
  default:
    alsHTTPAnalysis: ${SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS:k8s-mesh}
    restHost: ${SW_SHARING_SERVER_REST_HOST:0.0.0.0}
    restPort: ${SW_SHARING_SERVER_REST_PORT:12800}
    restContextPath: ${SW_SHARING_SERVER_REST_CONTEXT_PATH:/}
    gRPCHost: ${SW_SHARING_SERVER_GRPC_HOST:0.0.0.0}
    gRPCPort: ${SW_SHARING_SERVER_GRPC_PORT:11800}

when ues helm install, In addition to oap.envoy.als.enabled parameter, where are the other parameters?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
That is the only config you need to set. https://github.com/apache/skywalking-kubernetes/tree/master/chart/skywalking#envoy-als

I don't understand what do you mean about following things.
```
restHost: ${SW_SHARING_SERVER_REST_HOST:0.0.0.0}
restPort: ${SW_SHARING_SERVER_REST_PORT:12800}
restContextPath: ${SW_SHARING_SERVER_REST_CONTEXT_PATH:/}
gRPCHost: ${SW_SHARING_SERVER_GRPC_HOST:0.0.0.0}
gRPCPort: ${SW_SHARING_SERVER_GRPC_PORT:11800}
```

The question you are asking makes me feeling you are moving too fast. You know limited info about SkyWalking, but try to do the last step.

**Comment by justmine66** [comment]
> That is the only config you need to set. https://github.com/apache/skywalking-kubernetes/tree/master/chart/skywalking#envoy-als
> 
> I don't understand what do you mean about following things.
> 
> ```
> restHost: ${SW_SHARING_SERVER_REST_HOST:0.0.0.0}
> restPort: ${SW_SHARING_SERVER_REST_PORT:12800}
> restContextPath: ${SW_SHARING_SERVER_REST_CONTEXT_PATH:/}
> gRPCHost: ${SW_SHARING_SERVER_GRPC_HOST:0.0.0.0}
> gRPCPort: ${SW_SHARING_SERVER_GRPC_PORT:11800}
> ```
> 
> The question you are asking makes me feeling you are moving too fast. You know limited info about SkyWalking, but try to do the last step.

thanks, because there is no problem, we are ready to add the above configuration to try.
i install in the way below:
helm install skywalking skywalking --set oap.envoy.als.enabled=true
but application.yaml is:
envoy-metric:
  default:
    alsHTTPAnalysis: ${SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS:k8s-mesh}
oh, It was all right. 
but now i find no problems,can you help me?

**Comment by justmine66** [comment]
2020-02-18 13:05:42,837 - org.apache.skywalking.oap.server.receiver.envoy.als.K8sALSServiceMeshHTTPAnalysis -899941 [load-pod-0] INFO  [] - Load 40 pods in 107ms
2020-02-18 13:05:44,266 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient -901370 [pool-14-thread-1] INFO  [] - Synchronous bulk took time: 16266 millis, size: 2520
2020-02-18 13:05:45,419 - org.apache.skywalking.oap.server.core.remote.client.GRPCRemoteClient -902523 [grpc-default-executor-6] ERROR [] - UNAVAILABLE: upstream request timeout
io.grpc.StatusRuntimeException: UNAVAILABLE: upstream request timeout
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.15.1.jar:1.15.1]

**Comment by wu-sheng** [comment]
The error means, your OAP inside the cluster can't communicate with each other. Do you set something for you k8s?  Like I said, I still recommend you to understand SkyWalking more than just keeping trying the configurations. K8s is a very complex system, it is hard to tell what happens in your env.

**Comment by justmine66** [comment]
> The error means, your OAP inside the cluster can't communicate with each other. Do you set something for you k8s? Like I said, I still recommend you to understand SkyWalking more than just keeping trying the configurations. K8s is a very complex system, it is hard to tell what happens in your env.

Thank you for your advice. according to the official documents, there is no time to study systematically SkyWalking because of time. At present, we can only give SkyWalking up and choose Zipkin.

**Comment by wu-sheng** [comment]
Feel free to choose anything you like. If you are considering Zipkin, in the mesh solution, it is not SkyWalking's landscape from the beginning. SkyWalking is focusing observing topology and metrics more than tracing.
