### ISSUE TITLE
Add rest-high-level-client enhancements about class ClusterClient's method

### ISSUE THREAD

**Issue by aderm** [apache/skywalking#4381]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
enhancements method include `ClusterClient#putSettings` `ClusterClient#putSettingsAsync` `ClusterClient#getSettings` `ClusterClient#getSettingsAsync` `ClusterClient#health` `ClusterClient#healthAsync`
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by aderm** [comment]
merged, so close.

**Comment by wu-sheng** [comment]
@aderm Please set up the milestone/label/assignees for the issue closed/open

**Comment by aderm** [comment]
@wu-sheng get
