### ISSUE TITLE
about k8s as cluster coordinator question

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#4382]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
hello,  skywalking  oap deploy in k8s , i want to use k8s as the cluster coordinator. in config file, what param " cluster.kubernates.uidEnvName" indicate,  a k8s service name ?  or something else?
how to set this param?

![image](https://user-images.githubusercontent.com/52440226/74808201-46815d80-5325-11ea-92ab-2a94206c4e26.png)

**Comment by hanahmily** [comment]
k8s cluster manager uses this env to fetch a unique id,  for example `pod.metadata.uuid`. This `uid` intends to distinct a pod to others in a cluster.
