### ISSUE TITLE
Question about trace data ttl

### ISSUE THREAD

**Issue by dengliming** [apache/skywalking#4388]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I found that only the last two days of trace data can be searched at webapp(UI). How can I extend the time? Please help me to understand. Thanks.

Here is my es storage setting of ttl:
```
recordDataTTL: ${SW_STORAGE_ES_RECORD_DATA_TTL:15} # Unit is day
otherMetricsDataTTL: ${SW_STORAGE_ES_OTHER_METRIC_DATA_TTL:30} # Unit is day
monthMetricsDataTTL: ${SW_STORAGE_ES_MONTH_METRIC_DATA_TTL:6} # Unit is month
```

**Comment by wu-sheng** [comment]
`recordDataTTL` is the one. Which version are you using?

**Comment by dengliming** [comment]
version:6.6.0, Why close so fast (×_×)

**Comment by wu-sheng** [comment]
We keep issue opened for bug and new feature discussion.

From my understanding, there isn't a bug about it. Simply, check the demo env, there is still trace in several days ago. It uses this setting.
