### ISSUE TITLE
[NIGNX-LUA] e2e test for Nginx lua agent

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4401]
One hand, we will initial a new e2e in the main repo, to test the nginx with java agent.  I have added this suggestions in #4399 to @JaredTan95 

Also, in the nginx lua repo, we should consider how to test it, right now, the `example/nginx.config` could be a tracing tier1 + tier2 LBs, mock backend service and mock OAP backend. The trace will be reported and output in the nginx log. 

@kezhenxu94 @dmsolr @arugal @aderm Any suggestion about how to do this?
My idea is trying to output the trace into the file, and use some trace check tool to do this? Such as the main repo test tool? @dmsolr I think you are quite familiar with this. Could you consider to lead this part?

**Comment by dmsolr** [comment]
I am happy to do this.
We have 2 parts here, right? 
1. set up IT/UT nginx-agent on the skywalking-nginx-lua repo.
2. set up e2e (like java agent plugin) on the main repo.

**Comment by wu-sheng** [comment]
Most UT has been included and tested in the   nginx-lua repo. I have added.
This issue is only about e2e in the lua repo.

E2e in main repo should be a part of @JaredTan95 HTTP PR.

**Comment by wu-sheng** [comment]
@dmsolr about the e2e in the nginx lua repo, I hope we could do that in the lightweight way. Just use a container to run openresty, and output the existing trace into the file. Then we could use the existing tool to check.

But the tool codes have to been copied to there, right?

**Comment by dmsolr** [comment]
to validate the log file, the Nginx printed, is not difficult. We can re-use the validation-tools.
I ran the nginx-lua, but I cannot found the trace information in the log.

**Comment by wu-sheng** [comment]
Have provided by @dmsolr . Once the 7.0.0 HTTP APIs are ready, I am going to initial the release. FYI @JaredTan95 @arugal
