### ISSUE TITLE
Whether Java agent supports fetching exception stack trace?

### ISSUE THREAD

**Issue by long187** [apache/skywalking#4404]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Whether Java agent supports fetching exception stack trace?
___

**Comment by wu-sheng** [comment]
Yes. And why do you ask? Have you tried?

**Comment by long187** [comment]
No I haven't. 
Sometimes, developers catch exceptions, but they don't print them to the log. Can SkyWalking Java Agent catch these Exceptions?

**Comment by wu-sheng** [comment]
If they catched, there is nothing we could do. Instrumenting exception is not a good idea, if you were thinking about this. This should be inside the coding style scope, can't be taken care of by the APM system.

**Comment by long187** [comment]
Thanks a lot
