### ISSUE TITLE
Click on alarm message then jump to trace page

### ISSUE THREAD

**Issue by aderm** [apache/skywalking#4407]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
After SW triggers the alarm, need to manually jump to the trace page and enter related parameters to locate the trace. This is a common practice. But we can click directly to avoid the trouble of user input and optimize the user experience. This is just my personal thought, and everyone is welcome to give comments.

<img width="1326" alt="WX20200224-115758@2x" src="https://user-images.githubusercontent.com/2892433/75128234-1dcede80-56fe-11ea-8ff2-9eb646be3461.png">

**Comment by wu-sheng** [comment]
This seems mostly on UI, who will do this?

**Comment by wu-sheng** [comment]
What do you mean backend change? How do you know the alarm meaning? As user could customize the alarm rule.

**Comment by aderm** [comment]
> What do you mean backend change? How do you know the alarm meaning? As user could customize the alarm rule.

Just want to add a link to the message, you can jump to the trace page in question, avoid manual input params. Not involved customize the alarm rule.

**Comment by wu-sheng** [comment]
My point is, 
1. You tag this issue as `backend`, which means the OAP server. What kinds of changes are you proposing?
1. If this is a pure link, how the UI knows the query conditions in the trace query page? I have no clue about this.

**Comment by aderm** [comment]
> My point is,
> 
> 1. You tag this issue as `backend`, which means the OAP server. What kinds of changes are you proposing?
> 2. If this is a pure link, how the UI knows the query conditions in the trace query page? I have no clue about this.

IMO, Extend metric including calculated start time, end time, and traceId in OAP. thus, linked Trace query page will pinpoint the problem trace.

**Comment by wu-sheng** [comment]
> IMO, Extend metric including calculated start time, end time, and traceId in OAP. thus, linked Trace query page will pinpoint the problem trace.

Some alarm are about the latency and other about the status. Even same about latency, it has different threshold, such as percentile. How do you know and separate them? If you can't, what is the point to jump to the trace query?

**Comment by wu-sheng** [comment]
@aderm In SkyWalking, if you want to propose anything, please take the design with you, including the details. It is easy to ask even implement something, but we need to make sure it is meaningful, and will be widely used. Otherwise, as such a big open source community, it will be a disaster to maintain a project with so many but not important features.

The key principle of an open source project is resolving the harding and common problem, if there are some pre-conditions, let the users to add them in their fork even commercial versions. We are maintaining the most important core.

**Comment by aderm** [comment]
get it.
