### ISSUE TITLE
【spring-data-redis】默认使用io.lettuce，调用链未追踪到redis。改为jedis可以，请问是为啥

### ISSUE THREAD

**Issue by peterzhu8978** [apache/skywalking#4409]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- 【spring-data-redis】默认使用io.lettuce，调用链未追踪到redis。改为jedis后可以正常显示。

___
### Bug
- Skywalking version: 6.6.0

- What happen?
【spring-data-redis: 2.2.1】默认使用io.lettuce: lettuce-core: 5.2.1 ，调用链未追踪到redis的访问。
改为jedis后可以正常显示，请问问题出在哪？希望使用lettuce时能正常工作，谢谢！

【default lettuce】

       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

【jedis】

      <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.lettuce</groupId>
                    <artifactId>lettuce-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
        </dependency>

**Comment by wu-sheng** [comment]
English only.
