### ISSUE TITLE
[spring-data-redis:2.2.1]  redis tracking dosen't work

### ISSUE THREAD

**Issue by peterzhu8978** [apache/skywalking#4410]
sorry for last issue written by Chinese .

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- you know, spring-data-redis:2.2.1 default use lettuce(version:5.2.1). I found that redis tracking dosen't work in skywalking(version: 6.6.0), but when i manually exclude the lettuce and replace with jedis, it works normally.

[default]

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-redis</artifactId>
    </dependency>

[with jedis]

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-redis</artifactId>
        <exclusions>
            <exclusion>
                <groupId>io.lettuce</groupId>
                <artifactId>lettuce-core</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

    <dependency>
        <groupId>redis.clients</groupId>
        <artifactId>jedis</artifactId>
    </dependency>

![image](https://user-images.githubusercontent.com/61397066/75134832-7318e900-571a-11ea-8521-1ca261fc407b.png)

**Comment by wu-sheng** [comment]
Have you read the v6.6 agent doc? Because of JRE 1.8 requirements, it is an optional plugin only. https://github.com/apache/skywalking/blob/6.x/docs/en/setup/service-agent/java-agent/README.md#optional-plugins

The screenshot you provided is the master branch, it is a dev version for 7.0.0
