### ISSUE TITLE
optional-spring-plugins Support spring-cloud-gateway-2.2.x

### ISSUE THREAD

**Issue by cai-ti** [apache/skywalking#4412]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean? Why do you put that optional plugin into the gateway?

**Comment by cai-ti** [comment]
> What do you mean? Why do you put that optional plugin into the gateway?

skywalking-agentr:6.6.0
spring-cloud-gateway:2.2.1.RELEASE
在全局过滤器GlobalFilter打印出来的traceId和下游服务的traceId不一致，想问下是我这spring-cloud-gateway版本太高不支持吗？没有看到key为sw6的请求头向下游传递。

**Comment by wu-sheng** [comment]
English only. I am not sure the status of 2.2.1, these are versions we tested. https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/gateway-scenario/support-version.list

**Comment by cai-ti** [comment]
> English only. I am not sure the status of 2.2.1, these are versions we tested. https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/gateway-scenario/support-version.list

Debug HttpClientOperationsSendInterceptor find SWTransmitter is null，Can you give me a plan? I'll try

**Comment by wu-sheng** [comment]
I would suggest you to debug codes for older version to see where `SWTransmitter` created, then you may could find the new intercept point in the 2.2.x version, and create the `SWTransmitter` too.

**Comment by stalary** [comment]
> > English only. I am not sure the status of 2.2.1, these are versions we tested. https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/gateway-scenario/support-version.list
> 
> Debug HttpClientOperationsSendInterceptor find SWTransmitter is null，Can you give me a plan? I'll try

I'm having the same problem. Are you making any progress?
