### ISSUE TITLE
multiple endpoints will be created if has path variable in URL

### ISSUE THREAD

**Issue by f02061232-1** [apache/skywalking#4423]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hi, we have an api which url is /find/{userId}/{companyId}. When this api is called with different id, a new endpoint instance will be persisted in endpoint inventory. Is there any solution to avoid this problem? We just want to treat it as one endpoint.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Is this your private framework? SpringMVC has dealt with this case.

**Comment by f02061232-1** [comment]
It's a spring boot project.

**Comment by wu-sheng** [comment]
SpringMVC will fetch the path automatically, if you have set the parameter({param}) in the controller path.

**Comment by bjwanghua** [comment]
> SpringMVC will fetch the path automatically, if you have set the parameter({param}) in the controller path.

I also have the same problem. the url is /api/userCrowd/{adSystem}/{userId}, while the result has two kind of endpoints. /api/userCrowd/{adSystem}/{userId} and /api/userCrowd/YT/001, the throughput of the service is double of the requests. Is there any properties to set to fix this problem?

**Comment by wu-sheng** [comment]
>  Is there any properties to set to fix this problem?

Maybe you are using webflux as web container? If so, remove the plugin.

**Comment by bjwanghua** [comment]
> > Is there any properties to set to fix this problem?
> 
> Maybe you are using webflux as web container? If so, remove the plugin.

Thanks for reply. In my project I use undertow as the embed container in springboot. when I switch to tomcat, the problem is fixed.

**Comment by wu-sheng** [comment]
Then simply remove the undertow plugin, because of the async http framework, two entry span detected, that is why the CPM is not accurate.
