### ISSUE TITLE
suggest share trace by link

### ISSUE THREAD

**Issue by carlvine500** [apache/skywalking#4426]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Feature or performance improvement
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
when I find a trace error, I will send skywalking url and  traceId to colleagues,
and  colleagues open skywalking url then input traceId then search , this is a little complex,

suggest it can show trace by a url with traceId ,just like: 
  http://skywalking.company.com/trace?id=xxxx 
and add a copy button generate the url  .

**Comment by wu-sheng** [comment]
Read https://github.com/apache/skywalking/pull/4037. It is already there.

**Comment by carlvine500** [comment]
nice work !
