### ISSUE TITLE
We have consul doc for cluster manager. This log shows your YAML is not well formated.

### ISSUE THREAD

**Issue by Jason1220** [apache/skywalking#4429]
We have consul doc for cluster manager. This log shows your YAML is not well formated.

_Originally posted by @wu-sheng in https://github.com/apache/skywalking/issues/4427#issuecomment-592458554_

I also have the same exception and it is ok to verify the yaml format.
skywalking version:apache-skywalking-apm-es7-6.6.0

**Comment by wu-sheng** [comment]
Duplicated, there is nothing we could say.
