### ISSUE TITLE
Which companies are using SkyWalking

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#443]
# Welcome
# Users are encouraged to add their information to [powered-by](https://github.com/apache/skywalking/blob/master/docs/powered-by.md) page directly.

# Seed users
- 南京亚信软件有限公司， 移动社会化电子商务平台
- 亚信科技（中国）有限公司， ITSC报销系统
- GTrace
- 印记， http://www.yinjiyun.cn/

**Comment by wu-sheng** [comment]
* 随行付
* 北京中数智汇科技股份有限公司

**Comment by wu-sheng** [comment]
[Potential Company: 深圳卫盈智信科技有限公司]( https://github.com/OpenSkywalking/skywalking/issues/498#issuecomment-335990022) cc @neeuq

**Comment by klboke** [comment]
凯京集团
[http://www.keking.cn](http://www.keking.cn)

**Comment by carlvine500** [comment]
北京商云科技发展有限公司， 微商城， http://www.bizsaas.cn
苏州渠成易销网络科技有限公司，crm系统，  http://www.sucesschannel.com

**Comment by xyydcoo** [comment]
北京美德远健科技有限公司  医院应用云平台

**Comment by xyydcoo** [comment]
北京美德远健科技有限公司  医疗应用云平台

**Comment by fanshengado** [comment]
深圳融金宝互联网金融服务有限公司

**Comment by SaiDoFan** [comment]
深圳融金宝互联网金融服务有限公司 投资理财平台

**Comment by wendal** [comment]
广州文尔软件科技有限公司 https://www.site0.cn 当前使用的版本号 3.2.6

**Comment by chidaodezhongsheng** [comment]
当当网 [http://www.dangdang.com/](url) 已在生产环境使用，并自研PHP探针，当前使用的版本号为3.2.6

**Comment by KaiwenWang** [comment]
小米 基于部分SkyWalking中Agent部分逻辑移植公司原有Trace数据标准和打点规范，来应对使用非基础架构组提供的基础组件的内部客户需求。

**Comment by xiangyuSui** [comment]
北京中网易企秀科技有限公司  http://www.eqxiu.com/
目前测试环境正在测试 近期会上生产，当前使用版本 3.2.6

**Comment by simon2014** [comment]
深圳谷登科技有限公司  http://www.gdeng.cn/
正在测试使用 5.0，用熟悉之后准备全公司推广

**Comment by huangruisheng** [comment]
上海证大爱特金融信息服务有限公司 https://www.laocaibao.com/
正在使用5.0。部分生产已使用，观察一段时间后，全部系统使用。

**Comment by zuojunfang** [comment]
浙江钱宝网络科技有限公司 https://www.qsdjf.com/index.html

**Comment by Rainbowboys** [comment]
四三九九网络股份有限公司 http://www.4399.com/  
使用情况：目前使用的是5.0.0-beta 版本，即将在生产环境中使用。

**Comment by yrjjf** [comment]
杭州恒生云融网络科技有限公司  https://www.hsjry.com/
目前测试环境验证中，使用版本 skywalking-5.0.0-alpha ，

**Comment by iakei** [comment]
墨叽（深圳）科技有限公司 https://www.mojivip.com
线下环境验证中

**Comment by scguoi** [comment]
科大讯飞股份有限公司-消费者BG http://www.iflytek.com/
线上使用中， 3.2.6

**Comment by eaglewa** [comment]
百姓网 http://www.baixing.com/
线下环境预研中，5.0.0-beta，即将在生产试用

**Comment by wangjunniit** [comment]
河南有态度信息科技有限公司，微信小程序：得有生活
线下环境预研中，5.0.0-beta，即将在生产试用

**Comment by wu-sheng** [comment]
> 河南有态度信息科技有限公司，微信小程序：得有生活
线下环境预研中，5.0.0-beta，即将在生产试用

@wangjunniit Do you have any logo we could use? Our use case wall post logo only. :)

**Comment by liuhaoyang** [comment]
> Do you have any logo we could use? Our use case wall post logo only. :)

@wu-sheng 
![image](https://user-images.githubusercontent.com/10701915/41340797-c71cd1bc-6f2a-11e8-89ee-c5b5f08acd6c.png)

**Comment by wangjunniit** [comment]
@wu-sheng 
[logo](http://weixinimg.mtydx.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20180613165812.jpg)

**Comment by jameskypee** [comment]
@wu-sheng 
中企动力科技股份有限公司  http://www.300.cn/
线上3.6.0，即将切换5.0

**Comment by hellsoul86** [comment]
@wu-sheng 
上海好运虎供应链管理有限公司
[http://www.haoyunhu56.com/](url)

**Comment by daigong** [comment]
沈阳美行科技有限公司 http://www.mxnavi.com/
正在测试使用 5.0，线上小部分使用

**Comment by JaredTan95** [comment]
DaoCloud+www.daocloud.io

**Comment by wu-sheng** [comment]
> DaoCloud+www.daocloud.io

Thank to provide an important use case to the community.

**Comment by wu-sheng** [comment]
> DaoCloud+www.daocloud.io

@JaredTan95 Thank to provide an important use case to the community.

**Comment by zhangever** [comment]
dapeng-soa: https://github.com/dapeng-soa/dapeng-soa
![image](https://user-images.githubusercontent.com/2963615/43267676-3067a1ca-9121-11e8-9493-2e068302f182.png)
使用skywalking 5.0.0-beta

**Comment by wu-sheng** [comment]
> dapeng-soa: https://github.com/dapeng-soa/dapeng-soa

This is a project, right? Not a company. Use case needs a company or website name.

**Comment by chenpengfei** [comment]
公司全称：北京车和家信息技术有限责任公司
公司官网：www.chehejia.com
目前正在线下环境测试、验证，Agent采用5.0.0.0-RC，Collector和UI使用5.0.0.0-beta2

**Comment by mgsheng** [comment]
@wu-sheng  
 首约科技（北京）有限公司 https://www.01zhuanche.com/
目前使用版本5.0.0.0-beta2

**Comment by vflong** [comment]
乐心 http://www.lifesense.com/

**Comment by jinlongwang** [comment]
汽车之家-系统平台部
http://www.autohome.com.cn
使用情况：agent版本agent5.0.0.0-RC，测试环境验证中，验证过后推广使用
![image](https://user-images.githubusercontent.com/2275120/44246035-95b97000-a20e-11e8-884d-4b834dacc980.png)

**Comment by wu-sheng** [comment]
@jinlongwang Could you set a PR to change this too? https://github.com/apache/incubator-skywalking/blob/master/docs/users.md

**Comment by 511568420** [comment]
上海青客 .net core微服务框架

**Comment by wu-sheng** [comment]
@511568420  Could you set a PR to change this too? https://github.com/apache/incubator-skywalking/blob/master/docs/users.md

**Comment by zhanghao001** [comment]
杭州尚尚签网络科技有限公司  使用Skywalking5.0.0

**Comment by q1245242450** [comment]
招商局金融科技 https://www.cmft.com/
目前使用的版本:sky-wlaking5.0-RC 正在测试环境验证
![sw-2](https://user-images.githubusercontent.com/41274853/47128886-c036b080-d2c5-11e8-91d0-490028f75705.png)

**Comment by wu-sheng** [comment]
All above updated in user wall.
_____

**Comment by wu-sheng** [comment]
All above have been updated to powered-by page and user wall.

**Comment by Ahoo-Wang** [comment]
买道传感网 (https://www.51mydao.com/) - 生产环境 - V6.0  - SkyAPM-dotnet

**Comment by wu-sheng** [comment]
@Ahoo-Wang You could send pull request to update [powered-by page](https://github.com/apache/incubator-skywalking/blob/master/docs/powered-by.md) directly.

**Comment by Ahoo-Wang** [comment]
@wu-sheng ok,thx.

**Comment by wu-sheng** [comment]
User wall updated.
____

**Comment by Wooo0** [comment]
- 六合远教（成都）科技有限公司  http://www.cdlhyj.com/
- 应用于某党建项目中，线下预演中，已确定正式应用于线上。
- 使用skywalking 6.0GA+skyapm-netcore
![image](https://user-images.githubusercontent.com/31612998/55537705-68fb8f80-56ef-11e9-8255-e0045e867260.png)

**Comment by wu-sheng** [comment]
@Wooo0 Would you like to send a pull request to add your company into powered-by page directly?  https://github.com/apache/incubator-skywalking/blob/master/docs/powered-by.md

I really hope we could make that list longer :)

**Comment by singgel** [comment]
公司：雪球财经
网址：https://www.xueqiu.com/
地点：中国北京
联系方式：hekuangsheng@gmail.com
场景：多业务线追踪

**Comment by wu-sheng** [comment]
@singgel  Would you like to send a pull request to add your company into powered-by page directly? https://github.com/apache/incubator-skywalking/blob/master/docs/powered-by.md

**Comment by singgel** [comment]
That's it.

**Comment by wu-sheng** [comment]
User wall has been updated.

_____

**Comment by zygfengyuwuzu** [comment]
北京宅急送快运股份有限公司

**Comment by zygfengyuwuzu** [comment]
北京宅急送快运股份有限公司
http://www.zjs.com.cn/

**Comment by IanCao** [comment]
> 北京宅急送快运股份有限公司
> http://www.zjs.com.cn/

Would you like to send a pull request to add your company into powered-by page directly? https://github.com/apache/skywalking/blob/master/docs/powered-by.md

**Comment by tangyuxin2007** [comment]
江苏博瑞思科技有限公司 http://www.brains-info.com/zh/
正在测试使用 6.1，用熟悉之后准备项目使用，
谢谢大佬！！！

**Comment by peng-yongsheng** [comment]
北京天空漫步科技有限公司 http://www.apmstar.com
基于SkyWalking的APM系统服务商

**Comment by luzhen328** [comment]
深圳和而泰智能控制股份有限公司
http://www.szhittech.com/

**Comment by wu-sheng** [comment]
Add 同城金服(https://jr.ly.com/), based on https://github.com/apache/skywalking/issues/3224#issue-477689476.

**Comment by wu-sheng** [comment]
GOME. (gome.com.cn)

**Comment by kezhenxu94** [comment]
Thomas Cook (https://www.thomascook.com.cn) , based on https://github.com/apache/skywalking/issues/3315#issue-484876289

**Comment by wentjiang** [comment]
http://www.shuyun.com/
杭州数云信息技术有限公司

**Comment by kezhenxu94** [comment]
> http://www.shuyun.com/
> 杭州数云信息技术有限公司

@wentjiang could you send a pull request directly to add your company into the [power-by page](https://github.com/apache/skywalking/edit/master/docs/powered-by.md)

**Comment by wu-sheng** [comment]
# Users are encouraged to add their information to [powered-by](https://github.com/apache/skywalking/blob/master/docs/powered-by.md) page directly.
