### ISSUE TITLE
Strange endpoint

### ISSUE THREAD

**Issue by alishangtian** [apache/skywalking#4431]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- Why there are so many strange endpoints?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.5.0 with path ignore plugin
- Which company or project?
xiaomi
- What happen?
the picture i uplode for detail
![微信图片_20200302164856](https://user-images.githubusercontent.com/3463296/75661128-b558a200-5ca7-11ea-8596-afb3413f4006.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We can't tell where they are. Sorry. That is your app data.
