### ISSUE TITLE
SkyWalking Web Page shows no data

### ISSUE THREAD

**Issue by Heyman90** [apache/skywalking#4432]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [√] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.6.0, Linux, Binary Distribution for ElasticSearch 7
- What happen?
 After running SkyWalking for three days, SkyWalking Web Page shows no data. Response infos of the WebPage is 'We're sorry but SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue'. I ensure javascript of myweb view is enabled.

**Comment by wu-sheng** [comment]
Do you keep using h2 as storage?

**Comment by Heyman90** [comment]
> Do you keep using h2 as storage?
I config elasticsearch-7.6.0 as the storage.

**Comment by wu-sheng** [comment]
Your ES sever maybe crash. I can't tell why, you have to find out by yourself.

**Comment by Heyman90** [comment]
> Your ES sever maybe crash. I can't tell why, you have to find out by yourself.

I checked all my es nodes. However, all nodes are in health status and the cpu and memory of the machine are both in a good range.
Maybe should I check something other?

**Comment by wu-sheng** [comment]
No clue, are your ES supporting to create index through template?

**Comment by Heyman90** [comment]
> No clue, are your ES supporting to create index through template?

The es support create index through template. I can get the indexes by template:
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/15607384/75741133-a2e07600-5d44-11ea-8bb7-e39c94c39165.png">

**Comment by Heyman90** [comment]
> > Do you keep using h2 as storage?
> > I config elasticsearch-7.6.0 as the storage. The elasticsearch cluster include three nodes, every node has master and data roles.
> > At the same time, I note that the skywalking server print logs such as ’org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 388 [I/O dispatcher 1] WARN  [] - Bulk [3] executed with failures‘. Get more informations in the picture:
> 
> <img alt="image" width="1424" src="https://user-images.githubusercontent.com/15607384/75686472-45621000-5cd7-11ea-8f9d-a108e788bf55.png">


In addition, the logs of skywalking show the library use elasticsearch client while the storage use elasticsearch7 client. Will it influence the data interaction and lead to this result?

> > Do you keep using h2 as storage?
> > I config elasticsearch-7.6.0 as the storage. The elasticsearch cluster include three nodes, every node has master and data roles.
> > At the same time, I note that the skywalking server print logs such as ’org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 388 [I/O dispatcher 1] WARN  [] - Bulk [3] executed with failures‘. Get more informations in the picture:
> 
> <img alt="image" width="1424" src="https://user-images.githubusercontent.com/15607384/75686472-45621000-5cd7-11ea-8f9d-a108e788bf55.png">

In addition, the logs of skywalking show the library use elasticsearch client while the storage use elasticsearch7 client. Will it influence the data interaction and lead to this result?

**Comment by wu-sheng** [comment]
> In addition, the logs of skywalking show the library use elasticsearch client while the storage use elasticsearch7 client. Will it influence the data interaction and lead to this result?

Which es client you are using, base on your binary chosen and YAML config. I don't know what you choose.

**Comment by Heyman90** [comment]
> > In addition, the logs of skywalking show the library use elasticsearch client while the storage use elasticsearch7 client. Will it influence the data interaction and lead to this result?
> 
> Which es client you are using, base on your binary chosen and YAML config. I don't know what you choose.

SkyWalking Version: 6.6.0, Linux, Binary Distribution for ElasticSearch 7;
ElasticSearch Version: 7.6.0.
The picture shows my YAML config:
<img width="944" alt="image" src="https://user-images.githubusercontent.com/15607384/75748719-17beaa80-5d5b-11ea-8243-484e2f484e67.png">

**Comment by wu-sheng** [comment]
Look normal. Sorry, can't tell what happens.

**Comment by Heyman90** [comment]
> Look normal. Sorry, can't tell what happens.

Whatever, thanks for your reply very much.
I will add es nodes to try to reduce pressure of the cluster. Perhaps three nodes can't keep a long time to support skywalking.

**Comment by wu-sheng** [comment]
@Heyman90 Next time, please discuss this kind of thing in the mail list, rather than github issue. Today, too many discussions mixed in real issues.

**Comment by Heyman90** [comment]
> @Heyman90 Next time, please discuss this kind of thing in the mail list, rather than github issue. Today, too many discussions mixed in real issues.

OK，sorry about that.

**Comment by Heyman90** [comment]
It is solved by adding es nodes.

**Comment by Heyman90** [comment]
It is seemly solved by reinstall es and skywalking. However, one week later，the same error appears while es clean records at the TTL time(7days).

**Comment by CadenOf** [comment]
> It is seemly solved by reinstall es and skywalking. However, one week later，the same error appears while es clean records at the TTL time(7days).

Hi @Heyman90, did you make it working now ? I have the same issue like yours in my cluster

**Comment by wu-sheng** [comment]
TTL makes the indexes deleted at that moment, 7days in your case.
It requires more resources when doing this. So, likely, your eS cluster crashed.

**Comment by CadenOf** [comment]
@wu-sheng 
It seems that skywalking had created lots of  indexs after the TTL time(7 days), I found some logs in my elasticsearch cluster as follow 
![image](https://user-images.githubusercontent.com/32856921/76498668-4e41a700-6478-11ea-9e18-cec4fceba279.png)
after that, the es health status turn to green
![image](https://user-images.githubusercontent.com/32856921/76499048-fe171480-6478-11ea-8306-cead38e761a8.png)
but, the oap log still has warning: executed with failures
![image](https://user-images.githubusercontent.com/32856921/76500324-518a6200-647b-11ea-83cd-7b6fe99a871b.png)

**Comment by CadenOf** [comment]
It seems that skywalking created so much indices in elasticsearch7 at 00:00 everyday，I delete some older indices then restart skywalking oap resolved this problem. 
With defautl configuration in ES, the skwwalking TTL time seems cannot use the default config as 7 days, otherwise there will be more and more indexes in ES then cause this problem.

**Comment by wu-sheng** [comment]
No discussion will continue here. Discuss should happen on the official mail list.

**Comment by haanyip** [comment]
> Please answer these questions before submitting your issue.
> 
> * Why do you submit this issue?
> * [ ]  Question or discussion
> * [√] Bug
> * [ ]  Requirement
> * [ ]  Feature or performance improvement
> 
> ### Bug
> * Which version of SkyWalking, OS and JRE?
>   6.6.0, Linux, Binary Distribution for ElasticSearch 7
> * What happen?
>   After running SkyWalking for three days, SkyWalking Web Page shows no data. Response infos of the WebPage is 'We're sorry but SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue'. I ensure javascript of myweb view is enabled.

it is because of your wrong SW_OAP_ADDRESS when you setup the oap-ui, don't use 127.0.0.1 or localhost, pls fix it and try again~

**Comment by Superskyyy** [comment]
> > Please answer these questions before submitting your issue.
> 
> > 
> 
> > * Why do you submit this issue?
> 
> > * [ ]  Question or discussion
> 
> > * [√] Bug
> 
> > * [ ]  Requirement
> 
> > * [ ]  Feature or performance improvement
> 
> > 
> 
> > ### Bug
> 
> > * Which version of SkyWalking, OS and JRE?
> 
> >   6.6.0, Linux, Binary Distribution for ElasticSearch 7
> 
> > * What happen?
> 
> >   After running SkyWalking for three days, SkyWalking Web Page shows no data. Response infos of the WebPage is 'We're sorry but SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue'. I ensure javascript of myweb view is enabled.
> 
> 
> 
> it is because of your wrong SW_OAP_ADDRESS when you setup the oap-ui, don't use 127.0.0.1 or localhost, pls fix it and try again~

Please open a discussions thread and post a Q&A style post there. It will be easier for search for others with the same issue. I will mark your answer as accepted. :)
