### ISSUE TITLE
Add finagle plugin

### ISSUE THREAD

**Issue by huangyoje** [apache/skywalking#4433]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Add finagle plugin, version from 6.28.0 to 20.1.0

**Comment by wu-sheng** [comment]
Contribution is welcome

**Comment by huangyoje** [comment]
Hi, I have completed the main code and the automatic tests have passed.  I am very interested in contributing it to the community. how should i start?

**Comment by arugal** [comment]
Hi @huangyoje, welcome to contribute. Please refer to the [contribute plugins guide](https://github.com/apache/skywalking/blob/master/docs/en/guides/Java-Plugin-Development-Guide.md#contribute-plugins-into-apache-skywalking-repository ).
