### ISSUE TITLE
UI中当前端点不展示内容

### ISSUE THREAD

**Issue by joey-happy** [apache/skywalking#4444]
1.版本：apache-skywalking-apm-bin-es7 所有配置都是默认
2.java配置启动正常

结果：能采集到jvm的相关信息  但是请求的url的访问及追踪不展示

![image](https://user-images.githubusercontent.com/16012082/75955875-aa914d80-5ef1-11ea-9857-faaab72a6e05.png)

**Comment by joey-happy** [comment]
![image](https://user-images.githubusercontent.com/16012082/75956110-2a1f1c80-5ef2-11ea-89b1-6306bc3c571c.png)

**Comment by wu-sheng** [comment]
English only. Endpoint means you need to have traffic to access the system, such as spring controller.

**Comment by joey-happy** [comment]
I have visit the address: http://localhost:9080/test/type more than 100 times.

**Comment by wu-sheng** [comment]
Could you have the trace? If not, this service may haven't suitable plugin for your `/test/type` service somehow.

**Comment by joey-happy** [comment]
I use default config. How could I config the trace??

**Comment by joey-happy** [comment]
![image](https://user-images.githubusercontent.com/16012082/75957218-84b97800-5ef4-11ea-8a26-9a9bc8dfd5d8.png)
this is my started log

**Comment by joey-happy** [comment]
Is there some logs when the plugin not suitable for my service??

**Comment by wu-sheng** [comment]
Your config file is missing, SkyWalking agent wouldn't work. Please follow the set up document and don't move the agent.jar randomly

**Comment by joey-happy** [comment]
ERROR 2020-03-05 15:17:34:372 main SnifferConfigInitializer : Failed to read the config file, skywalking is going to run in default config.   
It use defalut config.

if the config error.  Why it collect my jvm info???

**Comment by wu-sheng** [comment]
I am not sure what kind of error of your config file. Once the agent get the service name and backend address it could run and collect JVM, which is easy. But the result can't be sure.

**Comment by joey-happy** [comment]
Thanks for your answer. I will give up.

**Comment by Ax1an** [comment]
@joey-happy You should put skywalking-agent.jar with the following directory.
![image](https://user-images.githubusercontent.com/28091237/78450506-90de5400-76b1-11ea-895c-ea737ac7e414.png)

**Comment by 1HEJIANFENG** [comment]
did it matters ?   how to slove it

**Comment by alloevil** [comment]
i got the same error, and this is my skwwalking-api.log
`DEBUG 2021-09-27 18:00:31:830 grpc-nio-worker-ELG-1-3 org.apache.skywalking.apm.dependencies.io.grpc.netty.NettyClientHandler : [id: 0x0d7e30ca, L:/10.119.108.11:42226 - R:/10.38.163.209:11800] INBOUND HEADERS: streamId=69 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] padding=0 endStream=false 
DEBUG 2021-09-27 18:00:31:830 grpc-nio-worker-ELG-1-3 org.apache.skywalking.apm.dependencies.io.grpc.netty.NettyClientHandler : [id: 0x0d7e30ca, L:/10.119.108.11:42226 - R:/10.38.163.209:11800] INBOUND DATA: streamId=69 padding=0 endStream=false length=5 bytes=0000000000 
DEBUG 2021-09-27 18:00:31:830 grpc-nio-worker-ELG-1-3 org.apache.skywalking.apm.dependencies.io.grpc.netty.NettyClientHandler : [id: 0x0d7e30ca, L:/10.119.108.11:42226 - R:/10.38.163.209:11800] OUTBOUND PING: ack=false bytes=1234 `

**Comment by alloevil** [comment]
> i got the same error, and this is my skwwalking-api.log
> `DEBUG 2021-09-27 18:00:31:830 grpc-nio-worker-ELG-1-3 org.apache.skywalking.apm.dependencies.io.grpc.netty.NettyClientHandler : [id: 0x0d7e30ca, L:/10.119.108.11:42226 - R:/10.38.163.209:11800] INBOUND HEADERS: streamId=69 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] padding=0 endStream=false DEBUG 2021-09-27 18:00:31:830 grpc-nio-worker-ELG-1-3 org.apache.skywalking.apm.dependencies.io.grpc.netty.NettyClientHandler : [id: 0x0d7e30ca, L:/10.119.108.11:42226 - R:/10.38.163.209:11800] INBOUND DATA: streamId=69 padding=0 endStream=false length=5 bytes=0000000000 DEBUG 2021-09-27 18:00:31:830 grpc-nio-worker-ELG-1-3 org.apache.skywalking.apm.dependencies.io.grpc.netty.NettyClientHandler : [id: 0x0d7e30ca, L:/10.119.108.11:42226 - R:/10.38.163.209:11800] OUTBOUND PING: ack=false bytes=1234 `

i asked my sre to see if there is something wrong with my network
