### ISSUE TITLE
deploy skywalking in kubernetes with helm2

### ISSUE THREAD

**Issue by runzexia** [apache/skywalking#4445]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
https://github.com/apache/skywalking-kubernetes
I saw the helm chart support in the repo above, but it does not seem to support helm2, our team has not upgraded to helm3. So what is the recommended way to deploy skywalking with helm2

**Comment by wu-sheng** [comment]
We don't have one maintaining that part. You could take helm3 as an example and write the helm2 by yourself.
