### ISSUE TITLE
Redis operation information cannot be displayed in tracking

### ISSUE THREAD

**Issue by shuaibo521** [apache/skywalking#4446]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- I want to see the specific operation of redis in the trace, but the component can't recognize it all the time. What it shows is: Spring MVC.Jedis2. X for redis link library
```
端点:com.zcsy.testapm.controller.APMTestController.testRedis()
跨度类型:Entry
组件:SpringMVC
Peer:No Peer
失败:false
url:http://172.16.1.21:28081/testapm/redis
http.method:GET
```

**Comment by wu-sheng** [comment]
This is the SpringMVC span, not redis' span
