### ISSUE TITLE
How to get traceId in skywalking-nginx-lua agent？

### ISSUE THREAD

**Issue by Lovnx** [apache/skywalking#4447]

**Comment by wu-sheng** [comment]
`TC.trace_id`. You should be able to use this in the tracer.

**Comment by wu-sheng** [comment]
Please use `[NGINX-LUA]` as title prefix.

**Comment by Hello-Linux** [comment]
@Lovnx Although I am not a developer, this function can be implemented. It is just the answer above that your developer does not understand the code functions maintained by himself
