### ISSUE TITLE
Add the possibilty to search for URL, not just Endpoint

### ISSUE THREAD

**Issue by mikkeschiren** [apache/skywalking#4453]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement

___
### Requirement or improvement
- Add the possibility to search for URL, not just endpoint.

When having an application with "messy URLs" it makes sense to have the possibility to search for URLs, not just endpoints.

![bild](https://user-images.githubusercontent.com/712838/76092698-23f77180-5fc0-11ea-8d67-74848f325099.png)

**Comment by wu-sheng** [comment]
Endpoint is including the URL. Read the core concept doc, https://github.com/apache/skywalking/blob/master/docs/en/concepts-and-designs/overview.md#why-use-skywalking

**Comment by mikkeschiren** [comment]
When I search for URL in Endpoint - I do not get any results though - is this in 7.0.0 ?

**Comment by mikkeschiren** [comment]
![bild](https://user-images.githubusercontent.com/712838/76093396-2d350e00-5fc1-11ea-82dd-d7a9b57f5803.png)


![bild](https://user-images.githubusercontent.com/712838/76093467-4c33a000-5fc1-11ea-9c8a-36ec565f1ff2.png)

**Comment by wu-sheng** [comment]
My guess, the parameter is not included. It is URI so get parameter should be excluded.

**Comment by wu-sheng** [comment]
Try `/play/api/media`, you could search the endpoint from dashboard page first, to check whether it is already there.

**Comment by mikkeschiren** [comment]
Yeah - that is there - but maybe I am phrasing myself wrong here - I would like a feature to be able to search for parameters in the url.

**Comment by wu-sheng** [comment]
Oh, do you mean all parameter or specific ones?

**Comment by mikkeschiren** [comment]
Yeah - all parameters - so if I have an endpoint, as my example /play/api/media I would like the possibility to search for the parameter `types`.

**Comment by wu-sheng** [comment]
First of all, you should not consider add all parameters, because that will make the endpoint number increasing out of control. We assume the endpoint number is limited and run the aggregation on it.
Second, even for explicit parameter names, such as `types` only, you should consider to discuss this on the agent repo. From my understanding, you are not using Java agent, maybe PHP?

**Comment by mikkeschiren** [comment]
Ok, I will do some own digging into this.
