### ISSUE TITLE
Failed to compile module apm-webapp on win10

### ISSUE THREAD

**Issue by tankilo** [apache/skywalking#4463]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I am not familiar with frontend , but when i compile the whole project, i always met the follwing error.

1. edit `skywalking\apm-webapp\pom.xml`
replace `<arguments>install --registry=https://registry.npmjs.org/</arguments> ` with  `<arguments>install --registry=https://registry.npm.taobao.org/</arguments>`
2. At the root dir of the project ,execute `mvn install -DskipTests -Drat.skip=true`

**maven log**  
```
[INFO] --- frontend-maven-plugin:1.6:npm (npm install) @ apm-webapp ---
[INFO] Running 'npm install --registry=https://registry.npm.taobao.org/' in C:\XXX\skywalking\skywalking-ui
[WARNING] npm WARN checkPermissions Missing write access to C:\XXX\skywalking\skywalking-ui\node_modules\del\node_modules\globby\node_modules\pify
[WARNING] npm WARN checkPermissions Missing write access to C:\XXX\skywalking\skywalking-ui\node_modules\braces\node_modules\extend-shallow
[ERROR] npm ERR! path C:\XXX\skywalking\skywalking-ui\node_modules\del\node_modules\globby\node_modules\pify
[ERROR] npm ERR! code ENOENT
[ERROR] npm ERR! errno -4058
[ERROR] npm ERR! syscall access
[ERROR] npm ERR! enoent ENOENT: no such file or directory, access 'C:\XXX\skywalking\skywalking-ui\node_modules\del\node_modules\globby\node_modules\pify'
[ERROR] npm ERR! enoent This is related to npm not being able to find a file.
[ERROR] npm ERR! enoent
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\XXX\npm-cache\_logs\2020-03-08T10_50_11_556Z-debug.log

[INFO] server-starter-es7 ................................. SUCCESS [ 11.657 s]
[INFO] apm-webapp ......................................... FAILURE [ 25.857 s]
[INFO] apache-skywalking-apm .............................. SKIPPED
[INFO] apache-skywalking-apm-es7 .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:33 min
[INFO] Finished at: 2020-03-08T18:50:11+08:00
[INFO] Final Memory: 200M/1707M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm install) on project apm-webapp: Failed to run task: 'npm install --registry=https://registry.npm.taobao.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: -4058 (Exit value: -4058) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apm-webapp
```

**2020-03-08T10_50_11_556Z-debug.log**   
```
20 verbose stack Error: ENOENT: no such file or directory, access 'C:\XXX\skywalking\skywalking-ui\node_modules\del\node_modules\globby\node_modules\pify'
21 verbose cwd C:\XXX\skywalking\skywalking-ui
22 verbose Windows_NT 10.0.17134
23 verbose argv "C:\\XXX\\skywalking\\skywalking-ui\\node\\node.exe" "C:\\XXX\\skywalking\\skywalking-ui\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "--registry=https://registry.npm.taobao.org/"
24 verbose node v8.9.4
25 verbose npm  v5.6.0
26 error path C:\XXX\skywalking\skywalking-ui\node_modules\del\node_modules\globby\node_modules\pify
27 error code ENOENT
28 error errno -4058
29 error syscall access
30 error enoent ENOENT: no such file or directory, access 'C:\XXX\skywalking\skywalking-ui\node_modules\del\node_modules\globby\node_modules\pify'
31 error enoent This is related to npm not being able to find a file.
32 verbose exit [ -4058, true ]
```

**Comment by wu-sheng** [comment]
Sorry. There is nothing we could do. You could read the ci logs, it must pass build in Windows, MacOS and Linux before any merge.

**Comment by tankilo** [comment]
> Sorry. There is nothing we could do. You could read the ci logs, it must pass build in Windows, MacOS and Linux before any merge.

I don't understand, Maven has restrict all the variables that you need to build this project. I follow the doc, then i should compile the project successfully. I think you miss something in the doc.

**Comment by wu-sheng** [comment]
No, there is nothing missing. NPM build depends on the network, that is not a part of maven issue.

**Comment by wu-sheng** [comment]
Take a look at our CI logs, https://github.com/apache/skywalking/actions?query=workflow%3A%22CI+AND+IT%22+branch%3Amaster.

Every thing must pass the build process and many tests. So, the project has to be able to build.

**Comment by tankilo** [comment]
There are really something missing!
The previous error can be ignored, because maven produces error, then i directly execute 'cnpm install' in directory `skywalking-ui` and i finally forget to clean node moudles before executing mvn again, so it's not an original error.

**This time, I clean everything and get the initial error.**
**If anyone got the following error.**
```
[INFO] > node-sass@4.11.0 postinstall C:\XXX\skywalking\skywalking-ui\node_modules\node-sass
[INFO] > node scripts/build.js

[ERROR] gyp verb check python checking for Python executable "python2" in the PATH
[ERROR] gyp verb `which` failed Error: not found: python2
[ERROR] gyp verb `which` failed     at getNotFoundError (C:\XXX\skywalking\skywalking-ui\node_modules\which\which.js:13:12)
[ERROR] gyp verb `which` failed     at F (C:\XXX\skywalking\skywalking-ui\node_modules\which\which.js:68:19)
[ERROR] gyp verb `which` failed     at E (C:\XXX\skywalking\skywalking-ui\node_modules\which\which.js:80:29)
[ERROR] gyp verb `which` failed     at C:\XXX\skywalking\skywalking-ui\node_modules\which\which.js:89:16
[ERROR] gyp verb `which` failed     at C:\XXX\skywalking\skywalking-ui\node_modules\isexe\index.js:42:5
[ERROR] gyp verb `which` failed     at C:\XXX\skywalking\skywalking-ui\node_modules\isexe\windows.js:36:5
[ERROR] gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)

[ERROR] gyp verb `which` failed   code: 'ENOENT' }
[ERROR] gyp verb check python checking for Python executable "python" in the PATH
[ERROR] gyp verb `which` succeeded python C:\Users\XXX\AppData\Local\Programs\Python\Python37\python.EXE
[ERROR] gyp ERR! configure error 
[ERROR] gyp ERR! stack Error: Command failed: C:\Users\XXX\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
[ERROR] gyp ERR! stack   File "<string>", line 1
[ERROR] gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
[ERROR] gyp ERR! stack                                ^
[ERROR] gyp ERR! stack SyntaxError: invalid syntax
[ERROR] gyp ERR! stack 
[ERROR] gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
[ERROR] gyp ERR! stack     at emitTwo (events.js:126:13)
[ERROR] gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
[ERROR] gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
[ERROR] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[ERROR] gyp ERR! System Windows_NT 10.0.17134
```

**You need to install python version 2.x and add 'python2' to PATH.**

[Python2，Python3环境及安装（windows、linux）](https://www.cnblogs.com/yunlong-hao/p/10939698.html)

```
[INFO] server-starter-es7 ................................. SUCCESS [ 11.352 s]
[INFO] apm-webapp ......................................... SUCCESS [14:27 min]
[INFO] apache-skywalking-apm .............................. SUCCESS [01:27 min]
[INFO] apache-skywalking-apm-es7 .......................... SUCCESS [01:25 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24:32 min
[INFO] Finished at: 2020-03-08T22:05:37+08:00
[INFO] Final Memory: 209M/1714M
[INFO] ------------------------------------------------------------------------
```

The only change i made to code is replacing `<arguments>install --registry=https://registry.npmjs.org/</arguments>` with `<arguments>install --registry=https://registry.npm.taobao.org/</arguments>`, i think this error will happen too if don't change the code.

**Comment by wu-sheng** [comment]
Got your point, if you want, feel free to send a pull request to the compiling https://github.com/apache/skywalking/blob/master/docs/en/FAQ/README.md#compiling.

But for python, it is really rare to see it is missing, especially only python2.

**Comment by tankilo** [comment]
Finally, as one who is not familiar with front end,  i understand what really happened.

According to https://github.com/sass/node-sass/issues/1176
> Native Node JS extensions like node-sass are compiled via npm which uses node-gyp. Python is required by node-gyp. We supply a bunch of precompiled binaries with out releases so you don't have to compile them yourself.
> 
> During the npm install process a binary is downloaded for your system. If you're on a system we haven't pre-compiled binaries for then npm will try to compile it for you, which is where python comes in.
> 
> Since you're one linux there should be a binary for you. This likely means you're running very old version of node-sass. You should always update to the latest version of a package. Please open a new issue if you continue to encounter errors with node-sass@4.5.0.

If you live in China and your vpn is not powerful enough, npm will fail to download some precompiled binaries for dependency `node-sass` , then it will compile them itself. That's why python2 is needed.

I will post an PR to guide people with network problems how to overcome this. Maybe skywalking really shouldn't care about it, but if this thing can be clarified, same kind of failure can be avoided.

**Comment by wu-sheng** [comment]
Please submit the PR for the FAQ.
