### ISSUE TITLE
how to open the dynaic configuration of alarm rule

### ISSUE THREAD

**Issue by wangyunchuan2012** [apache/skywalking#4469]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
___
### Question
- What do you want to know?
according to the doc, the dynamic configuration of alarm rule is off as default, but i want to know how to open it?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Change the YAML to the one implementation you want.
