### ISSUE TITLE
[Refactor] E2E test framework

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#4472]
According to the feedbacks from our developers, committers and PMCs, especially from @JaredTan95 , the E2E framework is rather unfriendly to our contributors, especially new contributors, therefore I'm refactoring the E2E test framework, the goals are:

- more debuggable, locally, in IDE

- more intuitive, adopt well known technologies to let people get started more quickly

- less verbose/duplicated codes

I've had a runnable version and may need some time to refactor the remains test cases, hope it would be ready soon, anyone who has more ideas about how the new E2E tests should work (friendly), please let me know

**Comment by wu-sheng** [comment]
I think debug in IDE is the key.
