### ISSUE TITLE
OAP : Unique index or primary key violation: "PRIMARY_KEY_A ON PUBLIC.SEGMENT(ID) VALUES ('5.24460.54184942355662976', 4013)"

### ISSUE THREAD

**Issue by Guozihong** [apache/skywalking#4478]
I deployed a nodejs program on a server, and this error will appear after a period of time，how to resolve this error. thanks!
![img](https://user-images.githubusercontent.com/21210394/76277575-1560d100-62c4-11ea-8f16-2aab53ddee03.png)

**Comment by wu-sheng** [comment]
I noticed this too, but don't get the answer yet. My last time research, the MySQL flush data not quickly enough, so can't be read next time in persistent process.

**Comment by Guozihong** [comment]
> I noticed this too, but don't get the answer yet. My last time research, the MySQL flush data not quickly enough, so can't be read next time in persistent process.

I tried in h2,mysql,elasticsearch mode, all will...

**Comment by wu-sheng** [comment]
I am quite sure, ES doesn't have this case

**Comment by Guozihong** [comment]
> I am quite sure, ES doesn't have this case

You are right. I've configured it wrong, so it doesn't work. I'll check it again.Thank's for your answer!
