### ISSUE TITLE
Using docker to start problems

### ISSUE THREAD

**Issue by Guozihong** [apache/skywalking#4481]
![image](https://user-images.githubusercontent.com/21210394/76290748-b06aa280-62e6-11ea-8682-758a09669741.png)
Has any problems in this Dockerfile? Why do I prompt Connection refused after startup.
![image](https://user-images.githubusercontent.com/21210394/76290985-34bd2580-62e7-11ea-9132-c7aafb394ca0.png)
Has anyone met?

**Comment by kezhenxu94** [comment]
You didn't control the start up order, please make sure that the Elasticsearch starts up **SUCCESSFULLY** and is **READY**, before starting OAP, you can leverage something like [wait-for-it](https://github.com/vishnubob/wait-for-it)
