### ISSUE TITLE
 In "Demo", if the time range in "Demo" is set to the span of one day, the data will not be queried.

### ISSUE THREAD

**Issue by Observe-secretly** [apache/skywalking#4482]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

In "Demo", if the time range in "Demo" is set to the span of one day, the data will not be queried. Data can be queried by setting a time span of more than one day.I think it should be a bug

**Comment by wu-sheng** [comment]
I just query several seconds ago, the data is there. I am not sure what do you mean.

![image](https://user-images.githubusercontent.com/5441976/76295367-75b93800-62ef-11ea-82d4-8ba05ece654c.png)

**Comment by Observe-secretly** [comment]
Please set the start time and end time to the same day. try again

**Comment by Observe-secretly** [comment]
![image](https://user-images.githubusercontent.com/34714262/76296232-dc8b2100-62f0-11ea-959d-648e41290011.png)
![image](https://user-images.githubusercontent.com/34714262/76296267-ea40a680-62f0-11ea-9329-c7b3561cefc3.png)
![image](https://user-images.githubusercontent.com/34714262/76296301-f3317800-62f0-11ea-9140-cea3e570e33f.png)

### Please take a closer look at the time frames of these three pictures

**Comment by wu-sheng** [comment]
There is no data for 3/9. They are deleted. This is only a demo, what do you expect?

For 3/10 noon(UTC +8), the demo env is internally set to UTC + 14 for global people having data for the `last one day`. Again, you seem misunderstand the purpose of the demo env, it is not for China only, and it is not for details.

**Comment by wu-sheng** [comment]
We don't guarantee anything for the demo. It could be erase from any committer or any reason, it could be the dev version only.

**Comment by Observe-secretly** [comment]
ok
