### ISSUE TITLE
Is 6.6 oap cluster can receive  trace from 6.5 Agent ？

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#4492]
### Question
- What do you want to know?
Is 6.6 oap cluster can receive  trace from 6.5 Agent .
I update my cluster from 6.5 to 6.6. But  some agent is 6.5 。
The oap clusters  can run . But some trace is bad. Service can not show right name ,It it show VNode....

**Comment by wu-sheng** [comment]
I don't think that is related to 6.5->6.6. It is compatible, and agent should be able hot reboot if you erase all data int the storage.

I am not sure what do you mean bad. VNode is a UI enhancement to tell you, some part of the traces has not been reported.

**Comment by seifeHu** [comment]
> compatible, and agent should be able hot reboot if you erase all data int the storage.

I delete all index just now . It is  works 
tks .
