### ISSUE TITLE
when use the gateway-agent and trace-ignore-agent. the "/actuator/health" can not be ignored!

### ISSUE THREAD

**Issue by Keanhua** [apache/skywalking#4494]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Bug
___
### Bug
6.6.0

- What happen?
when use the gateway-agent and trace-ignore-agent. the "/actuator/health" can not be ignored!

i configed the ignore_config   "/actuator/**",but it not worked,but in other application, it worked.
only in gateway, it not worked!

**Comment by wu-sheng** [comment]
This need your local test and debug. The plugin is coming from the 200+contributors, we can't tell all the details.
I just could share with you, the `ignore` plugin only works for the first span name of the tracing context, so make sure that is the right operation name.
