### ISSUE TITLE
CICD improvement

### ISSUE THREAD

**Issue by tristan-tsl** [apache/skywalking#4498]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
___
### Requirement or improvement

there is the description in english:

skywalking didn't feel the best solution in CICD, event feel confused, In fact, the support of skywalking in kubernetes has bean very good
skywalking's current practice:
	use submodules to include other modules in to top-level project
	CICD files with other subprojects declared in the docker directory, there is a problem, top-level projects cannot use source data provided by git itself to version multipart subprojects, it cause a lot of manual wor
let each subproject manage CICD, formation automation, provice a version correspondence table in the upper-level project, the records in the table are written in chronlogicial order, use for polymerization in the upper layer
the main contradiction is that the version of the subproject and the vesion of the upper layer  cannot be connected in series, unless the version has contains features, ant in the CICD process, it can directly connect the lower layer in the upper layer

这里是中文描述:

skywalking在CICD这块感觉没有做到最佳方案, 甚至感觉很混乱, 实际上skywalking在kubernetes的支持已经做到非常非常好了
目前做法:
	在顶层项目使用子模块将其他模块包含起来
	在docker目录中声明了其他子项目的CICD文件, 这样有一个问题, 顶层项目无法使用git本身提供的源数据对多个子项目的版本, 这就造成了大量的手工工作
让各个子项目各自管理CICD, 形成自动化, 在上层项目中提供版本对应表, 表中记录按照时间顺序编写记录, 在上层进行进行聚合使用

主要矛盾就是子项目的版本和上层的版本无法串联起来, 除非版本也有包含功能, 并且在CICD过程中能够在上层直接串联起下层

**Comment by kezhenxu94** [comment]
Totally confused what you’re talking about, even though you have a Chinese version, are you talking about codebase management or real CI/CD process? TBH you suggestion is too vague to catch up

**Comment by wu-sheng** [comment]
To be honest, I didn't follow your points. No matter in Chinese or English.
What is your proposal actually? What is the improvement?
@kezhenxu94 @dmsolr Any idea what this issue says?

**Comment by kezhenxu94** [comment]
@tristan-tsl  Totally confused what you're talking about, even though you have a Chinese version and I'm working in a CI/CD team, your opinion is too vague to catch up

**Comment by wu-sheng** [comment]
> CICD files with other subprojects declared in the docker directory

First thing confusing me is this, what are the CICD files? We never have such thing.

@tristan-tsl I used to work at Huawei HQ CI/CD department, @kezhenxu94 is working on Alibaba CI/CD team. And both of us are familiar with the SkyWalking. So, I think this is not our background issue.

The only guess I have, is you may have some misunderstanding about SkyWalking project structure. Especially when you said CI/CD, where is the CD? This is an open source environment, we have no where to deploy anything to anybody.

**Comment by wu-sheng** [comment]
The second one is what do you mean subproject? And which subproject do you refer? SkyWalking has a long repository list including sub projects and sub modules. We need you to clarify this too.

**Comment by wu-sheng** [comment]
After offline discussion, this topic doesn't make sense to the community. I am closing it.
