### ISSUE TITLE
zipkin_receiver  ERROR NOT in GZIP format

### ISSUE THREAD

**Issue by sharabao13** [apache/skywalking#4500]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- ERROR POST x.x.x.x:9411/api/v2/spans zipkin_API data use zipkin_receiver 
   org.apache.skywalking.oap.server.receiver.zipkin.handler.SpanV2JettyHandler - 7[qtp1227170244-64] ERROR [] - Not in GZIP format
java.util.zip.ZipException: Not in GZIP format

**Comment by wu-sheng** [comment]
That is the Zipkin client bug, I suppose. Please check with the Zipkin team.
