### ISSUE TITLE
Can skywalking exclude specified Exception？

### ISSUE THREAD

**Issue by CodeDestiny** [apache/skywalking#4505]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question

___
### Question
- What do you want to know?
In my project, develop defined BusinessException for some senerio such as parameter validate、bussiness logic validate，these exceptions are printed，but does not mean endpoint failure. 
In skywalking，these situation are calulated for service success rate metric.Is there anyway I can config, in order to exclude the BusinessException ?

**Comment by wu-sheng** [comment]
No, we can't. Using exception to propagate error is not a good idea, and have bad performance. 
Please consider to remove them.
The exception is dealt with in the plugin, If you insist, you have to change plugins one by one.

**Comment by CodeDestiny** [comment]
Because in last company，we used OneAPM which can config this，but also thanks a lot

**Comment by wu-sheng** [comment]
OneAPM product did very different way. They Even can't 100% sampling, Even far from it. We are different.
Again, this can be added If some one wants to contribute.
