### ISSUE TITLE
sharding-sphere-4.x-plugin dependencies error

### ISSUE THREAD

**Issue by muyun12** [apache/skywalking#4506]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug

Skywalking-6.4.0

The pom.xml of sharding-sphere-4.x-plugin dependency configration as bellow:
```xml
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-core-execute</artifactId>
            <version>[4.0.0-RC1,5.0.0)</version>
            <scope>provided</scope>
        </dependency>
```
`ShardingExecuteDataMap` class path is `org.apache.shardingsphere.core.execute.ShardingExecuteDataMap` at version 4.0.0-RC1 to 4.0.0-RC3, however, from version 4.0.0 the path was changed to `org.apache.shardingsphere.core.execute.engine.ShardingExecuteDataMap`.

**Comment by wu-sheng** [comment]
It is not supported, please submit issue to shardingsphere community.

**Comment by muyun12** [comment]
> It is not supported, please submit issue to shardingsphere community.

I think the version of adaptation shardingsphere4.0.0 is better，instead of RC versions.

**Comment by wu-sheng** [comment]
@muyun12 We don't work on that. ShardingSphere changed APIs in high frequency. There is nothing we can do except they contributed a new plugin. So ask this at their mail list :)

**Comment by muyun12** [comment]
> @muyun12 We don't work on that. ShardingSphere changed APIs in high frequency. There is nothing we can do except they contributed a new plugin. So ask this at their mail list :)

  @wu-sheng  All right, thank you!
