### ISSUE TITLE
can skywalking agent support in weblogic or websphere？ 

### ISSUE THREAD

**Issue by soulsoul** [apache/skywalking#4508]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- *  Question or discussion
- [ ] Bug
- *   Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
  we can use skywalking agent in tomcat easily.  but for some applications deployed with weblogic and websphere .  can it support ?  i can't get some info about this.
 
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
  If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
There is nothing different between weblogic and tomcat. Read weblogic and Websphere document about jvm arguments.

**Comment by soulsoul** [comment]
thx
