### ISSUE TITLE
How to connect elasticsearch with https?

### ISSUE THREAD

**Issue by vision-ken** [apache/skywalking#4512]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I had installed a external elasticsearch with [elastic-cloud-kubernetes](https://www.elastic.co/elastic-cloud-kubernetes), and install [skywalking-kubernetes](https://github.com/apache/skywalking-kubernetes) chart with helm 3:

```sh
$ helm install skywalking skywalking  \
        --set elasticsearch.enabled=false \
        --set elasticsearch.config.host=quickstart-es-http \
        --set elasticsearch.config.port.http=9200
```
Everything work fine but when OAP connect to es got a error:

```
org.apache.skywalking.oap.server.starter.OAPServerBootstrap -8869 [main] ERROR [] - Connection is closed
org.apache.skywalking.oap.server.library.module.ModuleStartException: Connection is closed
...
Caused by: org.apache.http.ConnectionClosedException: Connection is closed
```

the log in es has a WARN:
```
received plaintext http traffic on an https channel, closing connection
```

It looks like connecting to HTTPS through the HTTP port, how to solve this?

**Comment by vision-ken** [comment]
when I disable TLS of elasticsearch, OAP can connetct to ES now, but report the error:
```
org.elasticsearch.client.ResponseException: method [HEAD], host [http://quickstart-es-http:9200], URI [/], status line [HTTP/1.1 401 Unauthorized]
```
And then I add `oap.env` in charts/values.yaml as below and reinstall the chart, but it didn't work.
```
oap:
  env:
    SW_ES_USER: "elastic"
    SW_ES_PASSWORD: "xxx"
```

**Comment by wu-sheng** [comment]
@hanahmily 

> And then I add SW_ES_USER and SW_ES_PASSWORD in the oap.env section in charts/values.yaml as below, and reinstall the chart, but it didn't work.

These two env variables seem right. Any idea why?

**Comment by hanahmily** [comment]
@vision-ken it seems that  you should refer to https://github.com/apache/skywalking/blob/v6.6.0/docs/en/setup/backend/backend-storage.md#elasticsearch, then set up below parameters to enable TLS between OAP and ES.

```
 trustStorePath: ${SW_SW_STORAGE_ES_SSL_JKS_PATH:""}
 trustStorePass: ${SW_SW_STORAGE_ES_SSL_JKS_PASS:""}
```

Something you should take care of is
 1. OAP ports to `trustedStore` directly instead of X.502 CA files.
 1. The format of `trustedStore` is `JKS` instead of `PKCS12`.

**Comment by vision-ken** [comment]
@hanahmily 
How could I pass these env variable to the chart ?
- SW_ES_USER
- SW_ES_PASSWORD
- SW_SW_STORAGE_ES_SSL_JKS_PATH
- SW_SW_STORAGE_ES_SSL_JKS_PASS

**Comment by vision-ken** [comment]
Look like lost these lines in es-init.job.yaml :
```
        {{- range $key, $value :=  .Values.oap.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
```
After added these lines to  es-init.job.yaml, it work.

**Comment by wu-sheng** [comment]
@vision-ken Could you send a pull request to fix this?

**Comment by hanahmily** [comment]
`oap.env` list in https://github.com/apache/skywalking-kubernetes/tree/master/chart/skywalking#configuration is what you want

**Comment by yangvipguang** [comment]
@vision-ken  Could you show  how to configure  skywalking  connecting to  existing es  with https  passing  env in the values ?

**Comment by tirelibirefe** [comment]
Hello,
closed but still not clear how skywalking connects to https elasticsearch.
