### ISSUE TITLE
How to enable or disable skywalking  at the runtime

### ISSUE THREAD

**Issue by dragonlge** [apache/skywalking#4515]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
 
___
### Question
- What do you want to know?
Does skywalking can enable tracing or disable tracing  at the runtime?  beacuse of  sometime we don't  want to trace the application  it may cause lots of data and our  machine may can't handle it 

### Requirement or improvement
-  can u add a listener feature to skywalking

**Comment by wu-sheng** [comment]
We don't have that today, if you want to add a new feature, please write your proposal in English, and send in the SkyWalking mail list. That is the official way.

**Comment by dragonlge** [comment]
thank u for quick response :)

**Comment by wu-sheng** [comment]
This is not hard, just you need to propose a way to make agent know this notification.
