### ISSUE TITLE
 How to modify the segments 's TTL   and Do not delete all datas .

### ISSUE THREAD

**Issue by seifeHu** [apache/skywalking#4518]
- What do you want to know?
 How to modify the segments 's TTL   and Do not delete all datas .

**Comment by wu-sheng** [comment]
record TTL is for that.

**Comment by seifeHu** [comment]
> record TTL is for that.

some days ago I modify the ttl In yml file . But It is not work. 
So I think Must delete all data, and  run init scirpt  can work~.    But I don't want delete data

**Comment by wu-sheng** [comment]
It should work, and demo env is using it too. If you are running the cluster, you have to change all config files.
