### ISSUE TITLE
why  can't set agent.namespace  by Chinese language?

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#4522]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by lsy1990** [comment]
When I set this var agent.namespace  value to chinese language,all api will failed ,can't registry to eruka.

**Comment by lsy1990** [comment]
Is there some special setting ?

**Comment by wu-sheng** [comment]
Simple answer is, we are not expecting the namespace is Chinese. If you want, you basically need to fix the encoding issue.
