### ISSUE TITLE
Forgot archive source jar on Maven Repository? or other reasons?

### ISSUE THREAD

**Issue by mikepop7** [apache/skywalking#4523]
### Question
- Is there any source code JAR on Maven? I can't found at this URL:
https://repo.maven.apache.org/maven2/org/apache/skywalking/apm-agent-core/6.6.0/
source code is convenient for us to develop.

**Comment by wu-sheng** [comment]
It is never there. Please use GitHub repo tag or Apache download page to get full source codes.
The reason is we are using shade plugin of this, the source codes would be very confused after shade.
