### ISSUE TITLE
Elasticsearch JVM has too much memory and a long gc time

### ISSUE THREAD

**Issue by linliaoy** [apache/skywalking#4524]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
If anyone has ever encountered elasticsearch, heap memory takes up a lot, less memory is freed, frequent fullgc, and fullgc takes a long time.
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
I used version 6.6, es used 6.3.2, and found that it occupied a lot of heap memory, and the fullgc time was long.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
That is how ES works. I think we can't resolve this issue for ES. Maybe increasing `core/persistentPeriod` to longer refresh period could help you. But still your ES cluster is required to be powerful enough.

**Comment by linliaoy** [comment]
I compared it with skywalking6.1.

**Comment by wu-sheng** [comment]
They are both old, try latest release. The whole storage structure has been changed for better performance, even the next 7.0.0 is better.

**Comment by linliaoy** [comment]
The error log was 6.6 skywalking.
At present, the problem is still that the es heap memory is too large and a lot of memory cannot be released, which leads to the longer frequency and time of fullgc, which leads to the above error log. Compared with version 6.1, there is no such problem. The es configuration used by the two skywalking versions is the same.

**Comment by wu-sheng** [comment]
Sorry, can't get your point. We do nothing about ES heap memory. If you think 6.1 is better, you could continue to use on that. We rechecked with difference scenarios in the production, 6.3+ solution is always better than 6.1.

**Comment by linliaoy** [comment]
Okay, thanks. I'll look into it
