### ISSUE TITLE
The TOPN record in the database, what conditions will be recorded?

### ISSUE THREAD

**Issue by big-loser** [apache/skywalking#4527]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ * ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

The TOPN record in the database, what conditions will be recorded?

Through the tracking page, you can see that a certain URL has a database operation. However, there is no record in the  database TOPN record page.

Is it because sql executes too fast?

--------------------------------------------------------------------------

TopN数据库记录，什么条件会被记录？

通过追踪页面可以看到某个url 有数据库操作。但是，在database TOPN record 页面里并没有记录。

是因为sql执行的太快了吗？

**Comment by wu-sheng** [comment]
Yes. Read the top threshold setting document.

**Comment by big-loser** [comment]
> Yes. Read the top threshold setting document.

thank you for your reply.
