### ISSUE TITLE
Add alarm tests in the e2e

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4530]
As @dmsolr provide a hotfix for 7.0.0 release, we noticed, we miss one part of backend feature. Alarm test should be separated groups, we could use the mesh interface to report data which could guarantee the alarm occurs.

This could be tested in different storage too.

**Comment by mrproliu** [comment]
@kezhenxu94 Hi, have you started this e2e test? I'm interested in this.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 Hi, have you started this e2e test? I'm interested in this.

Not yet, go ahead
