### ISSUE TITLE
query one traceId ,but show more than one record

### ISSUE THREAD

**Issue by yaoyuandota** [apache/skywalking#4536]
### Question
- I use "ali transmittable-thread-local" for support share traceInfo between two threads or threadpool.I open log support ,the log is right.But i query traceId in "SkyWalking-UI" show more than one record. 
code like below:
![image](https://user-images.githubusercontent.com/48268070/76977186-eefbff00-696f-11ea-9f8c-7995ac8b22aa.png)
![image](https://user-images.githubusercontent.com/48268070/76977358-2a96c900-6970-11ea-9537-86a849da77f9.png)
ui like below:
![image](https://user-images.githubusercontent.com/48268070/76977681-96793180-6970-11ea-8a78-9be212d228c2.png)

please tell me why? thanks!
how can i fix it? Is skywalking  support  share traceInfo  between two threads future?

**Comment by wu-sheng** [comment]
Read UI usage doc in 7.0.0. They are trace segments.
