### ISSUE TITLE
Can't shutdown the Tomcat

### ISSUE THREAD

**Issue by makeths** [apache/skywalking#4538]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please run thread analysis, maybe some threads are not `demon` thread. I think similar to #4496

**Comment by makeths** [comment]
[a (2).txt](https://github.com/apache/skywalking/files/4352376/a.2.txt)
This is my analysis when Tomcat is running.

**Comment by wu-sheng** [comment]
@mrproliu Could you take a look? I do a quick research, seems `CommandService` is not running in the demon way.

**Comment by kezhenxu94** [comment]
> @mrproliu Could you take a look? I do a quick research, seems `CommandService` is not running in the demon way.

I wrote the `CommandService`, let me fix and check through the whole agent threads, as I mentioned in #4496

**Comment by makeths** [comment]
I wonder if this feature will be optimized in the next version？

**Comment by wu-sheng** [comment]
This has been fixed in the master branch, and tagged in 7.1.0
