### ISSUE TITLE
Active HTTP parameter collection automatically in the profiling context.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4542]
@kezhenxu94 used to add the HTTP parameter collection feature to those plugins, but due to the performance concern, it is default off. Now, as in 7.0.0, we have the profile feature, we know when to activate this.

@mrproliu Let's make the profile feature interactive with the plugins to provide more details of the profiled trace. :)

WDYT?

**Comment by mrproliu** [comment]
I think it's a good idea. 
But we have some static plugin configuration is processed based on the enhance mechanism, such as `plugin.mysql.trace_sql_parameter', which may require special processing.

**Comment by wu-sheng** [comment]
Two things, static config is just a condition. We could add a new condition. 
Two, sql parameter should be considered carefully, it may impact the performance. I thought just http request parameters, when http span at finish stage.

**Comment by mrproliu** [comment]
via #4546
