### ISSUE TITLE
New Feature Performance Analysis Contains bug in UI

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4550]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?

UI
- Which company or project?
local test
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

today i want to test the new feature that is performance analysis in 7.0.0,but  the user experience  of it is not good.
device: mac book pro 13  2017 
interface: /eureka/apps/  just a simple interface for service registry

![image](https://user-images.githubusercontent.com/31562192/77227248-e5fe6e00-6bb9-11ea-9c3e-40422c31d152.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
1. add option for  self duration ,for example : if have the opetion duration>1ms, the most of interfaces will be ignore and easier problem solving.
2. support window slide left to right

**Comment by wu-sheng** [comment]
@TinyAllen Let's add the horizontal scrolling feature to the table column.

**Comment by wu-sheng** [comment]
Especially for trace/span and profile/stack method tables.
