### ISSUE TITLE
Profile - Task in Skywalking

### ISSUE THREAD

**Issue by mailyathish** [apache/skywalking#4560]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- How to enable the profile-task ?
I have added below parameter in agent-config 
profile.duration=${SW_AGENT_PROFILE_DURATION:10}
profile.max_parallel=${SW_AGENT_PROFILE_MAX_PARALLEL:5}
profile.active=${SW_AGENT_PROFILE_ACTIVE:true}
profile.dump_max_stack_depth=${SW_AGENT_PROFILE_DUMP_MAX_STACK_DEPTH:500}
collector.get_profile_task_interval=100

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.6.0
OS - Linux
JRE - Java8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Requirement is enable the profiling details to get the Method level hotspots.

**Comment by wu-sheng** [comment]
Task started at UI and for 7.0.0 only.
