### ISSUE TITLE
have a skywarking docker image of arm 64？

### ISSUE THREAD

**Issue by landonzeng** [apache/skywalking#4562]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ *] Requirement
- [ ] Feature or performance improvement

### Requirement or improvement
- I run docker on the 4b of raspberry pie. I hope to find an arm 64 skyworking image in the docker hub

**Comment by hanahmily** [comment]
No, but you can get some inspiration from current Dockerfile to build a ARM dedicated one. and we even didn't verify whether OAP and UI can be running on ARM. If you have any luck, please let me know, thanks.
