### ISSUE TITLE
application with agent startup and report illegal field modifiers in class

### ISSUE THREAD

**Issue by YK-Leung** [apache/skywalking#4563]
jdk: 1.7
skywalking: 6.6
spring: 4.0.4
Other same versions projects with agent are startup normally except this，the error in agent log:
![image](https://user-images.githubusercontent.com/11452144/77383930-20852800-6dbf-11ea-96ec-0ceb342e665d.png)

my code :

`public interface TaskCallback<T> extends ListenableFutureCallback<T> {
public void onTimeout();
}`

`public interface ListenableTask<T> extends Callable<T>, TaskCallback<T> {
}`

**Comment by wu-sheng** [comment]
@ascrutae Please take a look.

**Comment by WickeyLiang** [comment]
> @ascrutae Please take a look.

i rewrite my interface to class and reboot success now, thank you

**Comment by leohuai** [comment]
> > @ascrutae Please take a look.
> 
> i rewrite my interface to class and reboot success now, thank you

how do you fix it？I met the same error
