### ISSUE TITLE
data loss

### ISSUE THREAD

**Issue by Heguoya** [apache/skywalking#4564]
jdk: 1.8
skywalking: 6.6
es7.6
When skywalking was just started, the service was normal, but after a while, the data became zero。
![image](https://user-images.githubusercontent.com/32662616/77393983-3a336900-6dd9-11ea-90d2-45b1d9e0fba6.png)

**Comment by wu-sheng** [comment]
From your information, there is nothing I can tell. You are just showing a blank page.
