### ISSUE TITLE
some query and monitoring features

### ISSUE THREAD

**Issue by yogaling** [apache/skywalking#4572]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
1、In our system, a request will have many redis queries; so in the tracking chain query interface, there will be many jedis records in the list. How to filter out these records and only display other related content。
2、Can the apm agent track a thread with a high CPU usage and push an alarm  event  containing the thread-related traceId , via mq or other methods. In this way, we can monitor the event and limit the request resource corresponding to the traceId, or even the user request.

**Comment by wu-sheng** [comment]
> 1、In our system, a request will have many redis queries; so in the tracking chain query interface, there will be many jedis records in the list. How to filter out these records and only display other related content。

You could remove redis plugin.

> 2、Can the apm agent track a thread with a high CPU usage and push an alarm event containing the thread-related traceId , via mq or other methods. In this way, we can monitor the event and limit the request resource corresponding to the traceId, or even the user request.

1. CPU alert, yes, you could set the rule to cpu related metrics. 
1. Trace id has nothing related to this. CPU is not thread-level metrics. I think you have wrong concept about the metrics and trace id relationship.

**Comment by yogaling** [comment]
Regarding the second question，Under Linux, we can get the top-related thread id through the ps command, which corresponds to the thread id of the JVM stack, and then find the corresponding traceId value through the thread variable.
[linux command : ps aux | sort -k3nr | head -n 10 ]

**Comment by yogaling** [comment]
Can we collude this process through apm agent？

**Comment by wu-sheng** [comment]
There is no thread-related CPU in the JVM MBean, as far as I known.

**Comment by yogaling** [comment]
Thanks for answering
