### ISSUE TITLE
仪表盘页脚本报错 v6.6

### ISSUE THREAD

**Issue by lengmianshi** [apache/skywalking#4573]
![image](https://user-images.githubusercontent.com/18379086/77617949-59b0ca00-6f70-11ea-9a9a-e8ccddb972eb.png)
![image](https://user-images.githubusercontent.com/18379086/77617977-67fee600-6f70-11ea-9ef2-829035e1f61f.png)

**Comment by wu-sheng** [comment]
English only, and from the logs, we can't know what is happenning.
