### ISSUE TITLE
How to set a password for WebUI with v7.0.0? 

### ISSUE THREAD

**Issue by xinyushiaolu** [apache/skywalking#4583]
in webapp.yml set 

security:
  user:
    admin:
      password: admin
is invalid；
 How to set a password for WebUI with v7.0.0?

**Comment by wu-sheng** [comment]
Don't have that. You could use Nginx to set up login by yourself.

**Comment by xinyushiaolu** [comment]
那么麻烦啊，6.几的版本不是有设置密码的地方吗，为什么7.0版本移出了

**Comment by wu-sheng** [comment]
Old one has security issue. Have to remove it. Unless someone contribute a good one, there isn't login.

English only.
