### ISSUE TITLE
Show instance name in the trace view.

### ISSUE THREAD

**Issue by zhangyucgme** [apache/skywalking#4586]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- How to display the instance name on the trace tree? A service may have multiple instances

**Comment by wu-sheng** [comment]
I think we don't have that in the GraphQL, If you want to add, we are welcome this contribution

**Comment by zhangyucgme** [comment]
thanks

**Comment by zhangyucgme** [comment]
Thank you. I'll try

**Comment by kezhenxu94** [comment]
> Thank you. I'll try

@zhangyucgme are you going to add this, the CLI could reuse this too :)

**Comment by xbkaishui** [comment]
Hi @wu-sheng  @kezhenxu94 ,  Please assign to me since no one has response.

**Comment by JaredTan95** [comment]
Service Instance Name provided already: https://github.com/apache/skywalking-query-protocol/blob/master/trace.graphqls#L82

**Comment by wu-sheng** [comment]
Yes, this is only an UI enhancement.
