### ISSUE TITLE
SpringCloudGateway Multiple filters are not connected

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#4588]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS and JRE?
version: 7.0.0
os: docker

- Which company or project?
netease-youdao

- What happen?
SpringCloudGateway Multiple filters are not connected
![屏幕快照 2020-03-30 08 24 50](https://user-images.githubusercontent.com/24592373/77865399-be19a500-7260-11ea-87a5-702856175946.png)

**Comment by wu-sheng** [comment]
I think SpringCloudGateway plugin requires some enhancements :) Welcome to do the contribution.

**Comment by stalary** [comment]
> I think SpringCloudGateway plugin requires some enhancements :) Welcome to do the contribution.

Ok, let me try. I'm not familiar with webflux

**Comment by ascrutae** [comment]
got it

**Comment by ascrutae** [comment]
Are those filter gateway filters?  As I know, gateway plugins doesn't instrument those filter.  Have you added new plugin which instrument those filter?

**Comment by stalary** [comment]
`public class IgnoreFilter implements GlobalFilter, Ordered {}`
@ascrutae

**Comment by stalary** [comment]
I don't use any other plugin

**Comment by wu-sheng** [comment]
The gateway plugin improved through #4878

**Comment by 1095071913** [comment]
@wu-sheng I would like to ask if the clone of this submission has been deleted. Has it been solved? But why does the problem still exist when I am using the 8.1.0 release

**Comment by wu-sheng** [comment]
@1095071913 Sorry, I don't know what is happening inside Gateway. There are several PRs following this, it is better to ping @ascrutae for more details.

**Comment by 1095071913** [comment]
@wu-sheng @ascrutae Ok, thank you. First of all, I described the problem clearly. I used https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/gateway-2.1.x-scenario/gateway-projectA-scenario for testing, and then the Agent used the 8.1.0 release.Finally, when running, Test1Filter and Test2Filter (GlobalFilter, Ordered) are not displayed in the link.
