### ISSUE TITLE
Some alarm rules cannot be triggered

### ISSUE THREAD

**Issue by heytong** [apache/skywalking#4590]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Which version of SkyWalking, OS and JRE?
skywalking 7.0

- What happen?
These alert rules(database_access_resp_time_rule,service_relation_server_resp_time_rule,service_relation_client_resp_time_rule)) cannot be executed. 
___
### Requirement or improvement
rules:
  service_resp_time_rule:
    metrics-name: service_resp_time
    op: ">"
    threshold: 500
    period: 5
    count: 2
    silence-period: 3
    message: Response time of service {name} is more than 500ms in 2 minutes of last 5 minutes.
  service_sla_rule:
    metrics-name: service_sla
    op: "<"
    threshold: 7000
    period: 10
    count: 3
    silence-period: 3
    message: Successful rate of service {name} is lower than 70% in 3 minutes of last 10 minutes
  service_p90_sla_rule:
    metrics-name: service_p90
    op: ">"
    threshold: 1000
    period: 10
    count: 3
    silence-period: 5
    message: 90% response time of service {name} is more than 1000ms in 3 minutes of last 10 minutes
  service_instance_resp_time_rule:
    metrics-name: service_instance_resp_time
    op: ">"
    threshold: 1500
    period: 10
    count: 2
    silence-period: 5
    message: Response time of service instance {name} is more than 1500ms in 2 minutes of last 10 minutes
  instance_jvm_cpu_rule:
    metrics-name: instance_jvm_cpu
    op: ">"
    threshold: 30
    period: 10
    count: 2
    silence-period: 5
    message: instance_jvm_cpu {name} is more than 30% in last 2 minutes
  instance_jvm_old_gc_count_rule:
    metrics-name: instance_jvm_old_gc_count
    op: ">="
    threshold: 1
    period: 5
    count: 1
    silence-period: 3
    message: instance_jvm_old_gc_count {name} trigger fullgc in last 5 minutes
  service_relation_client_resp_time_rule:
    metrics-name: service_relation_client_resp_time
    op: "<"
    threshold: 10000
    period: 10
    count: 2
    silence-period: 3                                                          
    message: relation {name} client response time lower than 10000ms in 2 minutes of last 10 minutes
  service_relation_server_resp_time_rule:
    metrics-name: service_relation_server_resp_time
    op: "<"
    threshold: 10000
    period: 10
    count: 2
    silence-period: 3                                                          
    message: relation {name} server response time lower than 10000ms in 2 minutes of last 10 minutes
  database_access_resp_time_rule:
    metrics-name: database_access_resp_time
    op: "<"
    threshold: 10
    period: 5
    count: 2
    silence-period: 2                                                       
    message: database_access_resp_time {name} lower than 10ms in 2 minutes of last 5 minutes

**Comment by wu-sheng** [comment]
Yes, they are not. Because we don't define their catalog. Only catalog SERVICE_CATALOG_NAME, SERVICE_INSTANCE_CATALOG_NAME and ENDPOINT_CATALOG_NAME will trigger the alarm today.

Read `DefaultScopeDefine` and `NotifyHandler`(related to `MetricFormatter`). You should have some clues, if you want to contribute this, please let us know.

**Comment by heytong** [comment]
> Yes, they are not. Because we don't define their catalog. Only catalog SERVICE_CATALOG_NAME, SERVICE_INSTANCE_CATALOG_NAME and ENDPOINT_CATALOG_NAME will trigger the alarm today.
> 
> Read `DefaultScopeDefine` and `NotifyHandler`(related to `MetricFormatter`). You should have some clues, if you want to contribute this, please let us know.

OK, thanks

**Comment by wu-sheng** [comment]
@heytong This could be provided in #4769

**Comment by heytong** [comment]
> @heytong This could be provided in #4769

thank you very much
