### ISSUE TITLE
Document file name and title are inconsistent

### ISSUE THREAD

**Issue by Yimismi** [apache/skywalking#4600]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
### Question

___
### Question
https://github.com/apache/skywalking/blob/master/docs/en/protocols/Trace-Data-Protocol-v3.md
the file name is Trace-Data-Protocol-v3 while its title is Trace Data Protocol v2. it's confusing.

**Comment by wu-sheng** [comment]
That is dev doc. :) We are upgrading many things in the master branch and incoming 8.x.

Read this, https://github.com/apache/skywalking/pull/4599 and the mail list link. You will have more informantion.
