### ISSUE TITLE
Support Kubernets Ingress

### ISSUE THREAD

**Issue by lipangeng** [apache/skywalking#4604]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___

### Requirement or improvement
- Support Kubernets Ingress, I think this is important feature, there are too many projects using Kubernets.

**Comment by wu-sheng** [comment]
Any contribution is welcome. If you plan to help, please bring your proposal in English to the mail list, including what you are going to do. We would discuss tech details there.
Basically, we expect people come and contribute.
