### ISSUE TITLE
OAL example in the document maybe wrong

### ISSUE THREAD

**Issue by MilkSDF** [apache/skywalking#4607]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
___
### Question
- What do you want to know?
I add the oal rules to my official_analysis.oal  which is copied from https://github.com/apache/skywalking/blob/v7.0.0/docs/en/concepts-and-designs/oal.md

Endpoint_500 = from(Endpoint.*).filter(responseCode like "5%").percent()

it didn’t work and I find error in the log.

___

If possible, provide a way for reproducing the error. e.g. demo application, component version.

![image](https://user-images.githubusercontent.com/7495090/78362349-88701580-75ec-11ea-93e9-c277162c25a6.png)

![image](https://user-images.githubusercontent.com/7495090/78362427-ac335b80-75ec-11ea-80aa-999ef5d188e5.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Response code is a number now. You should use >, < operator for it.
If You want 5xx, use>= 500
