### ISSUE TITLE
[Plugin] Elasticsearch rest-high-level-client 7.x

### ISSUE THREAD

**Issue by xhkyyy** [apache/skywalking#4608]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I see in the documentation that the Java Agent supports `ES rest-high-level-client 7.0.0-7.5.2`, but I don't find the file named `apm-elasticsearch-7.x-plugin.jar` in the plugins directory. 
I only found the 6.x version of APM jar (`apm-elasticsearch-6.x-plugin.jar`).

**Comment by wu-sheng** [comment]
There are 2 release packages. Read the documentation.
