### ISSUE TITLE
byte buddy is conflict with spring-aop 3  cgilb

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4611]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.6
linux
jdk 1.8
- Which company or project?
baidu

- What happen?

I am trying a test environment trial,but some old project build with spring3,I found the project cannot normal started,the happening is like following:
![image](https://user-images.githubusercontent.com/31562192/78548769-e17dba80-7833-11ea-9b47-b69df2a3a61d.png)
After some trials,I found the byte buddy is work well on spring4 or spring 5,but in spring3 the above situation will be occur,so I think the byte buddy is conflict with spring-aop 3  cgilb

In springMvc plugin ,it is only work on spring 4 or 5, but spring plugin don't have the flag

If you want, I will help add the pull request to add the version flag control in this week

Thanks for your helping

**Comment by wu-sheng** [comment]
Spring 3 looks like a long gone history. I am not familiar with that.
I can't be sure the conflicts.

**Comment by EvanLjp** [comment]
yes,it is occur on a old system  in my department, my advice is to add a flag to control version  probe,the 
Happening is like the above picture. when i remove the spring annotation plugin for agent plugin dirs,the system is normally started

**Comment by wu-sheng** [comment]
My idea is, there are countless old libraries, we can verify one by one. I still want to count on supported list doc.

**Comment by EvanLjp** [comment]
How will you verify the issue, can i take part in it?

**Comment by wu-sheng** [comment]
@EvanLjp I didn't verify it, I was saying, logically we can, but I doubt whether we have enough resources. Currently, agent tests are running for popular versions, but don't include those old ones.
