### ISSUE TITLE
About gateway

### ISSUE THREAD

**Issue by qpdyg** [apache/skywalking#4614]
Please answer these questions before submitting your issue.

- No solution found in use

___
### Question
- Is there an integrated gateway solution or plug-in

___
### Bug
- 6.5.0 version
Such as attachment effect. Thank you

![20190918205341422](https://user-images.githubusercontent.com/44364881/78639943-6a9efb00-78e1-11ea-8acf-0d793ca7f8f3.png)

**Comment by wu-sheng** [comment]
What Gateway?

**Comment by qpdyg** [comment]
https://spring.io/projects/spring-cloud-gateway

**Comment by qpdyg** [comment]
Well, I want to integrate with him
Plug in may be required

**Comment by wu-sheng** [comment]
We have an optional plugin, please read the documentation. And it only supports several version, not all.

**Comment by qpdyg** [comment]
请问你会中文吗？Can you speak Chinese?

**Comment by wu-sheng** [comment]
I can, but the issue discussion keeps in English only. We have users and developer globally, all official FAQ/Design/Doc are in English for more people. 

There are Chinese discussion channel unofficially in QQ. You could join.

**Comment by qpdyg** [comment]
QQ number, thank you

**Comment by wu-sheng** [comment]
It is on the readme page. Please read the doc rather than keeping asking.

**Comment by qpdyg** [comment]
OK, thank you for your help
