### ISSUE TITLE
Force flushing collected traces

### ISSUE THREAD

**Issue by BFergerson** [apache/skywalking#4619]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question

I'm creating a test that involves running code and verifying the traces which were sent to OAP are what's expected. I'm able to accomplish this if I run code more than necessary to make sure enough time has passed and enough traces have been sent to the OAP server.

For example, in my test I run:
```groovy
for (int i = 0; i < 40; i++) { //notice calling 40 times
    TraceTest.threeStaticMethodCallDepth() //<- this method is traced by agent
}
```

After this, I can query the OAP server with `queryBasicTraces` and a `pageSize` of `10`. This works great.

However, if I instead run:
```groovy
for (int i = 0; i < 10; i++) { //notice only calling 10 times
    TraceTest.threeStaticMethodCallDepth()
}
```

When I query the OAP server with `queryBasicTraces` and a `pageSize` of `10`, I can only find `2` results.

---

I've tried adding a listener like:
```groovy
def traceAsync = test.async(10)
def listener = new TracingContextListener() {
    void afterFinished(TraceSegment traceSegment) {
        traceAsync.countDown()
    }
}
TracingContext.ListenerManager.add(listener)

for (int i = 0; i < 10; i++) {
    TraceTest.threeStaticMethodCallDepth()
}
```

This only results in `afterFinished` being called three times though.

---

My question is, how can I set up my agent so that it will force flush traces to the OAP server or what can I run to wait until those traces have been sent out?

**Comment by wu-sheng** [comment]
Are you trying to interact with the segment sender of agent? Could you provide more context about in which case, which parts of codes are doing this?

**Comment by BFergerson** [comment]
Basically let's say I have:
```
class TraceTest {
   @Trace
   static void testMethodTrace() {
   }
```

And I have a test class:
```
TestTraceTest {
    @Test
    void verifyTraceExists() {
        TraceTest.testMethodTrace()
        List savedTraces = ...//here, call Apache SkyWalking OAP server via `queryBasicTraces`
        assert savedTraces.size() == 1
    }
}
```

This code won't work because by the time I call `queryBasicTraces` the trace that was created by calling `testMethodTrace()` hasn't been sent to the OAP server yet. What can I do to make the test wait till that's happened?

**Comment by wu-sheng** [comment]
Currently, there is no way to do this, that is why in our E2E, we only could set up the timeout for this.
