### ISSUE TITLE
Why not replace the GRPC

### ISSUE THREAD

**Issue by HackerRookie** [apache/skywalking#4620]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why can't  customize the message rules of skywalking like rocketmq
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read FAQ, queue based transport is only in mail list dicussion. It is not better than grpc.
