### ISSUE TITLE
Does skywalking provider us the real dependent metric between services

### ISSUE THREAD

**Issue by zjg88** [apache/skywalking#4621]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
does skywalking provider us the real dependent metric between services

for example : we have some service dependency like this :

![image](https://user-images.githubusercontent.com/18129981/78755038-12ccc680-79ab-11ea-9a0e-6eb15ceb5d96.png)

A_1 -> B -> D
A_1 -> B -> E
A_2 -> B -> E

the A_2 has nothing to do with E，the service A_1 and A_2 may call different service in different case .  
then one day we have a activity and be told that the qps of A_2 will increase twice ,and we need to calculate the real QPS of service E ,  the A_1 must have no effect on this capacity evaluation.what's more,in the production environment ,it come more complex case ,
A_2 -> B -> E -> A_2 , this may cause a cycle
does skywalking provide such metric for us , if yes , could u show me the .java file or the algorithm ; if not , does any idea about it 
thanks very much

**Comment by wu-sheng** [comment]
First f all, you are describing span? That is different things.

**Comment by wu-sheng** [comment]
Then the topology gives you the service relationship metrics already. Click the line, you will see them.
