### ISSUE TITLE
Long list of topology service group.

### ISSUE THREAD

**Issue by blank-1** [apache/skywalking#4625]
**skywaling version  7.x ,docker image tag:7.0.0** 
**1.all  topology cannot display**
![image](https://user-images.githubusercontent.com/30788027/78849068-0e092080-7a46-11ea-8fa4-af731970a82d.png)

**2.topology group can't show all, and no scroll bar**
![image](https://user-images.githubusercontent.com/30788027/78849326-c8992300-7a46-11ea-8120-e0a4cb6a83d2.png)

**Comment by wu-sheng** [comment]
All topology can't show up seems your ES performance issue.

@TinyAllen We could consider about the `scroll bar` supports.

**Comment by wu-sheng** [comment]
@blank-1 The `scroll bar` will be considered as an enhancement only.

The global topology query requires you to dig more, providing a blank page is not helpful.

**Comment by blank-1** [comment]
The global topology has complete data, which will be displayed once for the first time quickly, and then become blank. If you group or select an application, it will be displayed

**Comment by wu-sheng** [comment]
I haven't that before. Not sure.

**Comment by wu-sheng** [comment]
Fixed.

**Comment by blank-1** [comment]
apache/skywalking-ui
upload image or not？

**Comment by wu-sheng** [comment]
Fixed means it exists in the rocketbot-ui master branch, and will be included in the next release.

**Comment by wu-sheng** [comment]
Apache release is a very official process, we can't do that randomly.
