### ISSUE TITLE
需求：PHP如何采用swoole或Phar如何监控？

### ISSUE THREAD

**Issue by binghun0518** [apache/skywalking#4626]
- [ ] Requirement
我们PHP项目采用swoole或Phar在打包，请问大家对于这方面的使用经验或方案？

**Comment by wu-sheng** [comment]
I think the mail list comes from you too? Please don't submit the context duplicated.

**Comment by bnubobby** [comment]
@binghun0518  自研框架，自研组件，我们的项目已接入，效果不错，有兴趣可交流

**Comment by heyanlong** [comment]
@bnubobby +1
