### ISSUE TITLE
Protocol message tag had invalid wire type

### ISSUE THREAD

**Issue by huohuanhuan** [apache/skywalking#4629]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why report this mistake
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking6.5 es6.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
2020-04-10 10:58:57,824 - org.apache.skywalking.oap.server.library.buffer.DataStreamReader - 153 [pool-14-thread-1] ERROR [] - Protocol message end-group tag did not match expected tag.
com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
        at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:110) ~[protobuf-java-3.4.0.jar:?]
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This seems your local buffer file damaged somehow. You could simply remove them and reboot the backend.

**Comment by huohuanhuan** [comment]
Is this the folder ？
/apache-skywalking-apm-bin/trace-buffer

**Comment by wu-sheng** [comment]
Maybe, it is set by the application.yml
