### ISSUE TITLE
Question about the value of responseCode in the OAL

### ISSUE THREAD

**Issue by MilkSDF** [apache/skywalking#4631]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion

___
### Question
- What do you want to know?
I want to monitor the responseCode of the http call ,so I define a metric in the oal file

service_responseCode =  from(Service.responseCode).sum()

I invoke a http request, but in the table of service_responseCode, the value is always 0.
isn't it should be  multiple 200 or 500 ？

![image](https://user-images.githubusercontent.com/7495090/78962732-9dd2cb80-7b27-11ea-8aeb-1611dcf74913.png)

how to write the expression to calculate the percent of the 500 responseCode in the http call. 
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
First. I think the right function is count, not sum.

Your OAL is not right. Take this as an example.

service_5xx = from(Service.*).filter(responseCode >= 500).cpm();

We don't have that percent func you described, you may need to extend.

**Comment by wu-sheng** [comment]
Another thing, make sense the source.responseCode has value. We don't use this right now, especially in trace case.
