### ISSUE TITLE
The service throughput does not match the instance throughput

### ISSUE THREAD

**Issue by Yuanruitao** [apache/skywalking#4632]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?

  - Skywalking 6.5
  - Centos 6
  - JDK8

- What happen?

  Under the Tab of the service, we found the value of the service throughput did not match the value of the running serviceinstance.

  Sample Service have 7 instances and their CPM at 14:45 is as follows:
  - 21791
  - 10926
  - 10923
  - 10919
  - 10915
  - 10913
  - 10908

  The total is 87,295 cpm,but in service throughput is 66,714.

  And in the instance Tab, each instance throughput curve is flat, but under the service Tab, there are often have very low values.

**Comment by wu-sheng** [comment]
Do you set the enough bulk size? Otherwise, the data could be lost in some cases.

**Comment by wu-sheng** [comment]
This size could reach 2000 as the max, if you have many endpoints and services.

**Comment by Yuanruitao** [comment]
oap log: 
- Bulk execution id [41824] completed in 185 milliseconds, size: 2000
- Synchronous bulk took time: 2118 millis, size: 5788
- Bulk execution id [41825] completed in 50 milliseconds, size: 435
- Bulk execution id [41826] completed in 190 milliseconds, size: 2000
- Synchronous bulk took time: 2146 millis, size: 5519
- Bulk execution id [41827] completed in 170 milliseconds, size: 2000
- Bulk execution id [41828] completed in 78 milliseconds, size: 858
- Synchronous bulk took time: 2079 millis, size: 5468

Should I set bulk size to 8000?

**Comment by wu-sheng** [comment]
How this turns to 5000+? Is there a bug somehow? I don't have time to dig deeper yet.
Do you do some debugs?

**Comment by Yuanruitao** [comment]
I am work for it now , I will reply if there is any result.

**Comment by wu-sheng** [comment]
Oh, I realized I reading codes wrong, so basically, yes, you need 8000 as bulk size.

**Comment by Yuanruitao** [comment]
Ok, thanks. I'll test if it helpful.

**Comment by wu-sheng** [comment]
> Bulk execution id [41826] completed in 190 milliseconds, size: 2000

This is the real flush size. Set to 2000 or `storage/elasticsearch/bulkActions` value.

> Synchronous bulk took time: 2079 millis, size: 5468

This is the size in a timer persistent period only, it just shows you how many rows inserted/updated.

So I am sure for now, choose 2000.

**Comment by Yuanruitao** [comment]
Back to the questions, Dose it mean bulk size is enough?
> Do you set the enough bulk size? Otherwise, the data could be lost in some cases.
Other problems caused the loss of data.
Thank for your help,  I will keep looking for reason.

**Comment by wu-sheng** [comment]
2000 is the suitable value, if you set larger than this, should be fine.

**Comment by Yuanruitao** [comment]
Solved!
The problem is my grpc config no IP binding. 
If oap is in cluster mode, the "code.default.gRPCHost" config can not be "0.0.0.0".

**Comment by wu-sheng** [comment]
Thanks for the feedback.
