### ISSUE TITLE
后端那个模块可以去写具体的登陆逻辑代码呢？

### ISSUE THREAD

**Issue by puritykid** [apache/skywalking#4643]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

__Requirement_
### Question
- What do you want to know?

_I want to code login service__
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only, and we don't have login today.
