### ISSUE TITLE
the trace view is normal,but the dependency map not works

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4649]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
in my company ,I write a custom agent plugin for the internal rpc framwork,I found the trace view is normal ,but the dependency map is not work ,i try to compare the plugin with others,but i failed.
![image](https://user-images.githubusercontent.com/31562192/79202457-3d67c500-7e6c-11ea-8795-18a4e7d3378f.png)
![image](https://user-images.githubusercontent.com/31562192/79202619-76079e80-7e6c-11ea-90da-aac3fc5c5fee.png)

Thanks for your helping

**Comment by wu-sheng** [comment]
This seems related to the across thread case. Maybe in the first service, there is an async process?

**Comment by EvanLjp** [comment]
sorry,it is not a corss thread case,look file following graph,the call is normal in trace view
![image](https://user-images.githubusercontent.com/31562192/79203181-3beacc80-7e6d-11ea-8854-44257d105477.png)
but in Dependency map it is abnormal 
![image](https://user-images.githubusercontent.com/31562192/79203335-781e2d00-7e6d-11ea-800b-d75b51c9222c.png)

**Comment by wu-sheng** [comment]
No, those two are not endpoint dependency. Endpoint dependency is the relationship between the downstream entry endpoint and upstream entry endpoint. Not between any client/sider pair. I feel you are thinking the other thing.

**Comment by EvanLjp** [comment]
I found the resoult.it is because of the apm-undertow-2.x-plugin-7.0.0.jar,the follow is the past status,
![image](https://user-images.githubusercontent.com/31562192/79204876-cfbd9800-7e6f-11ea-8e89-2b1d03832ef1.png)
![image](https://user-images.githubusercontent.com/31562192/79205488-920d3f00-7e70-11ea-9d13-ca488b41beea.png)

the now status:
![image](https://user-images.githubusercontent.com/31562192/79205465-8b7ec780-7e70-11ea-9c75-841c412b9043.png)

so I think the problem of it  is one segment contains 2 entry

**Comment by wu-sheng** [comment]
I am not sure what you want to tell me. This is the design and idea, follow this.
> Endpoint dependency is the relationship between the downstream entry endpoint and upstream entry endpoint

**Comment by EvanLjp** [comment]
In my practice , the dependency map is normal work when i  delete the apm-undertow-2.x-plugin in agent plugins, I think there is a conflict between these two plugins (springmvc plugin and  undertow plugin)

**Comment by wu-sheng** [comment]
> In my practice , the dependency map is normal work when i delete the apm-undertow-2.x-plugin in agent plugins, I think there is a conflict between these two plugins (springmvc plugin and undertow plugin)

That is what I said about the async process. The async process will break this dependency, as it is not depending any more. Async could be bulk mode.
