### ISSUE TITLE
Question for sw-v7.0.0

### ISSUE THREAD

**Issue by wangdafang** [apache/skywalking#4653]
I have seed 'Support method performance profile.' in sw-v7.0.0 CHANGELOGS,and I can't understand what that means.
Does it related to the whole link method level monitoring? 
Or does sw-v7.0.0 support the whole link method level monitoring? 
And how to made it or config it? 
I need help

**Comment by wu-sheng** [comment]
We have documentation for it, https://github.com/apache/skywalking/blob/master/docs/en/ui/README.md#profile

If you want to understand more, read
- CN,  https://www.infoq.cn/article/CWUOl1JA0EyXw0CxQ4Zm
- EN,  https://thenewstack.io/apache-skywalking-use-profiling-to-fix-the-blind-spot-of-distributed-tracing/

I recommend you to read all these.

**Comment by wangdafang** [comment]
> We have documentation for it, https://github.com/apache/skywalking/blob/master/docs/en/ui/README.md#profile
> 
> If you want to understand more, read
> 
> * CN,  https://www.infoq.cn/article/CWUOl1JA0EyXw0CxQ4Zm
> * EN,  https://thenewstack.io/apache-skywalking-use-profiling-to-fix-the-blind-spot-of-distributed-tracing/
> 
> I recommend you to read all these.

I got it,and it's help me a lot,thank you very much~
