### ISSUE TITLE
How many shards will be created in es7 totally?

### ISSUE THREAD

**Issue by wutingjia** [apache/skywalking#4654]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How many shards will be created in es7 totally? In es7 the maximum of shard in single node is 1000 in default and it's not enough apparently。With the skywalking‘s default configuration two shards per index，just 2 days I reach the maximum of shard。If I want persist metric data for 2 weeks，with hundreds of service instances，how do I estimate the peek number of shards(I suppose skywalking will help me delete the expired index in es)?  
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.6.0
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> How many shards will be created in es7 totally? In es7 the maximum of shard in single node is 1000 in default and it's not enough apparently

This is increasing with days and TTL, consider to use skywalking 7/8(master), they reduce the number of index much. 7 is -50%, 8 is -75% comparing to 6.6

> If I want persist metric data for 2 weeks，with hundreds of service instances，how do I estimate the peek number of shards

That has nothing related to shards, default should be enough.

> I suppose skywalking will help me delete the expired index in es

Yes, when TTLs are reached.
