### ISSUE TITLE
Some question for upgrade from the version 6.6.0 to 7.0.0

### ISSUE THREAD

**Issue by darcydai** [apache/skywalking#4657]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Hi WuSheng, I saw skywalking release version 7.0.0 in recently, then we want to upgrade the APM that we use in the production environment(6.6.0). there are two things I want to confirm: 

*  is the probe that version 6.6.0 support APM 7.0.0 server ?
* I saw the elastic search index for metric merged into the minute index. if set the configuration 'storage/elasticsearch/enablePackedDownsampling‘  value false, the APM 7.0.0 can use indies that created in APM 6.6.0(query and store is ok);
thanks and good night!

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> is the probe that version 6.6.0 support APM 7.0.0 server ?

Yes.

> I saw the elastic search index for metric merged into the minute index. if set the configuration 'storage/elasticsearch/enablePackedDownsampling‘ value false, the APM 7.0.0 can use indies that created in APM 6.6.0(query and store is ok);

Yes, you could, but I encourage you don't do this. The `enablePackedDownsampling` is recommended, better for the performance.

@darcydai This kind of questions should happen on the mail list.
