### ISSUE TITLE
Skywalking about asynchronous monitoring

### ISSUE THREAD

**Issue by leo-sam** [apache/skywalking#4660]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Scenario: in an HTTP request, sometimes an asynchronous call is made (such as mq)
Question: can skywalking's traceid be passed to mq's processing log at this point?

**Comment by wu-sheng** [comment]
If you make the tracing works with your across thread case, then yes. Read plugin development documentation. They are there.
