### ISSUE TITLE
[Question] does skywalking support user to customize an endpoint?

### ISSUE THREAD

**Issue by MilkSDF** [apache/skywalking#4661]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- What do you want to know?
I want to know how to customize an endpoint. usually a method is an endpoint, can I add or extend endpoints according to the different parameters of the method when invoking it. so that i can count the response time of the method when different parameters. 

public void A(String B)
B=="a"--> endpoint a
B=="b"--> endpoint b

it's best that there is some annotation or api to define an endpoint. like the apm-toolkit-trace
@Trace
ActiveSpan.tag("tag","tagvalue");

or like spring-boot-starter-actuator to define an endpoint

**Comment by wu-sheng** [comment]
No, we are not today. If you want to do, welcome to contribute to add `org.apache.skywalking.apm.toolkit.trace.ActiveSpan#setOperationName`.

**Comment by JaredTan95** [comment]
I'm interested and assigned to me.
