### ISSUE TITLE
Socket plugin

### ISSUE THREAD

**Issue by smartisanyyh** [apache/skywalking#4662]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
Is there a Socket Plugin ? We have some  traditional Service  called by java.net.Socket ,But it is  not traced
___
### Bug
- Which version of SkyWalking, OS and JRE?
7.0.0
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Socket is not a safe protocol, it is at the kernel level. We can't and no one can provide a common plugin for that. You need to understand the real transport protocol, and inject the context into the header of your protocol.

**Comment by smartisanyyh** [comment]
i only want to know the  time cost  ,it does't need to parse response , Is it feasible

**Comment by smartisanyyh** [comment]
> Socket is not a safe protocol, it is at the kernel level. We can't and no one can provide a common plugin for that. You need to understand the real transport protocol, and inject the context into the header of your protocol.

i only want to know the time cost ,it does't need to parse response , Is it feasible

**Comment by wu-sheng** [comment]
Latency is a metrics, if you want to do this, join our bi-weekly meeting, 830 PM, April 28th, UTC+8. I will give an online introduction about SkyWalking 8.0 metrics system.
Subscribe our mail list, we will send the meeting link there.

**Comment by smartisanyyh** [comment]
i send mail to dev-subscribe@skywalking.apache.org but it's  look like not worl property 

> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.
> 
>                   The mail system

**Comment by wu-sheng** [comment]
Which mail box are you using? I haven't heard this issue before.

**Comment by smartisanyyh** [comment]
@yeah.net 
I will try other
