### ISSUE TITLE
grpc plugin not working

### ISSUE THREAD

**Issue by Allkoman** [apache/skywalking#4664]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
version 7.0 can not trace GRPC request
with Metadata(content-type=application/grpc,user-agent=grpc-node/1.24.2 grpc-c/8.0.0 (osx; chttp2; ganges),grpc-accept-encoding=identity,deflate,gzip,accept-encoding=identity,gzip) 

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I recommend you to debug and find out why. We have plugin test cases in the test folder, Check the versions and how we test them.

**Comment by Allkoman** [comment]
@wu-sheng ok ,thank you
