### ISSUE TITLE
Spring Cloud Gateway above 2.2.x isn't supported

### ISSUE THREAD

**Issue by stephen-liu1974** [apache/skywalking#4665]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [*] Feature or performance improvement

___
### Question
- What do you want to know?
Whether the version 2.2.x or above of spring cloud gateway is supported.
___
### Description
- Which version of SkyWalking, OS and JRE?
7.0.0

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
The the latest version (2.1.13) of spring cloud gateway 2.1.x works well. However for version 2.2.0 and above, it can be collected from agent, but no links between spring cloud gateway and other spring boot services.

**Comment by stephen-liu1974** [comment]
The the latest version (2.1.13) of spring cloud gateway 2.1.x works well. However for version 2.2.0 and above, it can be collected from agent, but no links between spring cloud gateway and other spring boot services.

**Comment by wu-sheng** [comment]
Duplicated, issue is there.
