### ISSUE TITLE
Doesn't skywalking support spring cloud gateway 2.2.x and above

### ISSUE THREAD

**Issue by stephen-liu1974** [apache/skywalking#4668]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Doesn't skywalking support spring cloud gateway 2.2.x and above
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 7.0.0, JRE 1.8.x and MacOS
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
For the version 2.1.13 of Spring Cloud Gateway, they all work well. However for 2.2.x, all the data from Spring Cloud Gateway can be collected, but no links between gateway and other microservices.

**Comment by wu-sheng** [comment]
Duplicated.
