### ISSUE TITLE
oap负载不均衡

### ISSUE THREAD

**Issue by huohuanhuan** [apache/skywalking#4675]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
使用zookeeper后可以使用负载均衡软件吗？使用负载均衡软件后会和zookeeper起冲突吗？

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only, you could set up gRPC-supported load balance/proxy by your own. We don't need to rewrite this, many great open source projects are there, including Nginx, Envoy.

**Comment by huohuanhuan** [comment]
After using nginx, still need to use zookeeper ？

**Comment by wu-sheng** [comment]
We never required zookeeper, it is just a backend coordinator option. If you want to set up OAP cluster,  choose at least one coordinator. As it is named as coordinator, it is for OAP cluster, it has nothing related to the agent.
