### ISSUE TITLE
What is the way to judge success or failure? Can I filter code 404

### ISSUE THREAD

**Issue by huohuanhuan** [apache/skywalking#4678]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What is the way to judge success or failure? Can I filter code 404

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> What is the way to judge success or failure? Can I filter code 404

According to HTTP definition, >= 400 is error. We follow that.
