### ISSUE TITLE
Adding java agent causes the process to fail to exit normally

### ISSUE THREAD

**Issue by Junqiann-Hao** [apache/skywalking#4680]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
After adding java agent, the process of spring boot failed to exit without starting fail.This will cause process monitoring to fail.How do I configure the agent.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean fail to exit?

**Comment by Junqiann-Hao** [comment]
exapmle : error loading configuration file or Port occupation

**Comment by wu-sheng** [comment]
You said `exit`, what configuration loaded in exiting?

**Comment by Junqiann-Hao** [comment]
no , i used systemctl to retry start spring boot application, but and agent  process will not exit. thanks for your help，but my english very poor .how about speak chinese

**Comment by wu-sheng** [comment]
We don't do Chinese discussion on the GitHub and mail list. You could join the QQ group, but there is only a community discussion channel, nothing official happens there.

Agent installed in the app, and start with the app. There is no start or exit about the agent.
