### ISSUE TITLE
WebUI problem

### ISSUE THREAD

**Issue by makeths** [apache/skywalking#4681]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
sw7,es7,tomcat8,jdk1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
The agent data has been stored in ES already, however, SW WebUI has nothing to show. 
![~{{YARS)04E{D}@0(2S9ZP9](https://user-images.githubusercontent.com/19485682/79769804-28ed6600-835f-11ea-822b-4fee44955ced.png)
![@5@3Q)@AK2 VK~ GLS E40D](https://user-images.githubusercontent.com/19485682/79769819-2be85680-835f-11ea-9431-aa92c97f2de2.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by makeths** [comment]
And the the agent timezone is consistent with server's.

**Comment by wu-sheng** [comment]
Your tz is not consistent with your browser. Choose the right one.
