### ISSUE TITLE
 several services that have no connection，but there's a connection in the topology diagram

### ISSUE THREAD

**Issue by longdevops332** [apache/skywalking#4684]
Hello, there's a problem. Skywalking7-es7 and sofa RPC are used for microservices. There are several services that have no connection, including in the tracking interface. There's no connection to view the service alone, but there's a connection in the topology diagram. What's the reason？Thank you

**Comment by wu-sheng** [comment]
Is there relationship between services or not? Please make yourself clear.

**Comment by longdevops332** [comment]
There are several services that do not have any connection at all, so there is something wrong with the topology map

**Comment by longdevops332** [comment]
In addition, I call all traceids of a service in skywalking's tracking module through Python program according to the link in question in the topology diagram. Query query trace ($traceid: ID!). In the result ["data"] ["trace"] ["spans"], all the statistics are made and no associated service is found in the topology diagram, so it's strange.

**Comment by wu-sheng** [comment]
Are they sharing the same network address, including port? If so, the alias could be set wrong. 

We don't have python sdk in the open source world, so, if you are doing something internally, it is very hard to find out what is the issue.

**Comment by longdevops332** [comment]
It's not a python SDK. I'm a python crawler mode. I grab the spans corresponding to all traceids related to the service. I find that there is no problem associated service in the topology map

**Comment by wu-sheng** [comment]
> It's not a python SDK. I'm a python crawler mode. I grab the spans corresponding to all traceids related to the service. I find that there is no problem associated service in the topology map

Then we are back to the IP issue. Do you have a chance A->B and C->D are using the same `ip:port`/`hostname`/`domain name`/anything at A and C sides?

**Comment by longdevops332** [comment]
I use services with different namespaces in k8s, and we have no connection at the code level. Env mode is used in pods to communicate with skywalking, [and each SW agent name is unique]

{"name": "SW_AGENT_NAMESPACE","value": "test" }, {"name": "SW_AGENT_NAME","value": "xx-user-biz-app"},{ "name": "SW_AGENT_COLLECTOR_BACKEND_SERVICES", "value": "xx.xx.xx.xx:11800"}

**Comment by wu-sheng** [comment]
Agent namespace doesn't affect the backend analysis, if you are sharing the OAP backend cluster, you need to make sure the IP is duplicated.

**Comment by longdevops332** [comment]
Excuse me, I found a strange phenomenon. Today at 10:00, skywalking is built in a completely new environment; ES7 is also new. It has no data at all. After that, it will collect more than one hour's data and view the service topology map. If the time node is selected as the latest day, the effect of the topology map is correct. However, if the latest week is selected, there are some services in the topology map that do not have a connection at all, which actually shows a connection. I'm surprised that since it's the new one installed today, shouldn't the topology map display the same in the last day and the last week

**Comment by wu-sheng** [comment]
Can't tell much from your description, I recommend you to read the topology build logic, then we could discuss online at our bi-weekly meeting, if you want.

Next Tuesday night is the next meeting. Subscribe to our mail list, you will receive the nofitication.
