### ISSUE TITLE
[Question] Configuration for skywalking to receive data using istio envoy

### ISSUE THREAD

**Issue by HashTableHu** [apache/skywalking#4688]
[Details]
My configuration is as follows:
1.enabling envoyAccessLogService in ProxyConfig(k8s istio)
2.skywalking in /config/application.yml
envoy-metric:
  selector: ${SW_ENVOY_METRIC:default}
  default:
    alsHTTPAnalysis: ${SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS:"k8s-mesh"}
[Question]
What other configurations are needed?
or
Can you provide a complete reference configuration?
thank you!

**Comment by wu-sheng** [comment]
Don't submit duplicated issue.
