### ISSUE TITLE
i can only get the  global data in the dashboard

### ISSUE THREAD

**Issue by smartisanyyh** [apache/skywalking#4692]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
do i config wrong with something  or  Skywalking always like this slow 
___
### Bug
- Which version of SkyWalking, OS and JRE?
7.0.0
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
i  can only get the glabal scope data ,the others scope   graphql all respones
```
timestamp: 1587605029082
status: 500
error: "Internal Server Error"
exception: "com.netflix.zuul.exception.ZuulException"
message: "GENERAL"
```
most of the webapp log  are 
`Caused by: java.net.SocketTimeoutException: Read timed out`

most of the  skywalking-oap-server.log  are 
`2020-04-23 09:29:30,644 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 383 [pool-16-thread-1] ERROR [] - listener timeout after waiting for [30000] ms
`

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The log only shows es read timeout, nothing more.

**Comment by smartisanyyh** [comment]
i know  but  that  is   too slow ,     es  data  just 20g + ,  I'm getting the Glabal data need 8-9s  ,the others socpe data timed out every time  ,  I can't found the problem  is the skywalking or network  or filesystem

**Comment by smartisanyyh** [comment]
How long does it usually take to get  graphql ?Is this normal

**Comment by wu-sheng** [comment]
In my es cluster, normally, 100ms.

**Comment by smartisanyyh** [comment]
ok  I will check my es cluster config

**Comment by smartisanyyh** [comment]
I found the problem,it's es cluster problem  , jvm heap size default value is 1g ,Insufficient  heap size cause full cg all the time , so that the es cluster always timeout ,turn up heap size in es/config/jvm.options  can fix the problem
