### ISSUE TITLE
contribute apm-sniffer resttemplate-4.x-plugin

### ISSUE THREAD

**Issue by thomasbryant1024** [apache/skywalking#4696]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
Hi，I enhance the resttemplate-4.x-plugin's function.That is to add the function of collecting the response of resttemplate which controlled by the system env variable named 'plugin.resttemplate.collect_http_response' .I tried to commit the code,but it shows me that  I 
 have  no permission to push the feautre. How I can contribute the code? 
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> Hi，I enhance the resttemplate-4.x-plugin's function.That is to add the function of collecting the response of resttemplate which controlled by the system env variable named 'plugin.resttemplate.collect_http_response' .I tried to commit the code,but it shows me that I
have no permission to push the feautre. How I can contribute the code?

No one has that permission. You need to follow the GitHub official pull request process. Fork the repo, change the codes there, and send the pull request to the main repo.

Also, we have plugin test documentation, please follow that to make sure your new feature has been covered in plugin test.
