### ISSUE TITLE
How to stop skywalking? why aren't there a stop script? 如何停止skywalking？

### ISSUE THREAD

**Issue by esolve** [apache/skywalking#4698]
skywalking好像有好几个进程
一个个找去kill比较麻烦
为何没有一个stop脚本？

**Comment by wu-sheng** [comment]
English only. We don't have stop script today. Contributions are welcome.

**Comment by bluesgone1** [comment]
Yes, I met the same thing today, help!

**Comment by Superskyyy** [comment]
> Yes, I met the same thing today, help!

If you need this please open a new Discussions thread, then we can see how it goes. It's hard to continue on a closed issue.

**Comment by 15732631053** [comment]
ps -ef |grep skywalk |awk '{print $2}'|xargs kill -9

**Comment by tencentemr** [comment]
ps -ef | grep skywalk |grep -v grep | awk '{print $2}'|xargs kill -9
