### ISSUE TITLE
Why the config  'flushInterval'  in ’application.yml‘ is bound to  "index.refresh_interval"？

### ISSUE THREAD

**Issue by coreyho** [apache/skywalking#4699]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Feature or performance improvement
___
### Question
Why the config  'flushInterval'  in ’application.yml‘ is bound to  "index.refresh_interval"？
```java
org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller#createSetting
setting.put("index.refresh_interval", record ? TimeValue.timeValueSeconds(10).toString() : TimeValue.timeValueSeconds(config.getFlushInterval()).toString());
```
The config also is bound to  bulk flush interval in 'org.apache.skywalking.oap.server.library.module.ServiceNotProvidedException'  ?
```java
 this.registerServiceImplementation(IBatchDAO.class, new BatchProcessEsDAO(elasticSearch7Client, config.getBulkActions(), config.getFlushInterval(), config.getConcurrentRequests()));
```
These are two different configuration items.
What does this config mean？
___

___
### Requirement or improvement
Adding more config about elasticsearch such as 'index.merge.scheduler.max_thread_count' which is important and necessary.

**Comment by wu-sheng** [comment]
What do you mean `why`? Very confused about your questions. Json formated `advanced` attribute is for any extension configs of es index.

**Comment by coreyho** [comment]
'bulk.flush.Interval' and 'refresh_interval' are two different attributes in es, but there is only one corresponding config in skywalking. I Cannot set them to different value。
```java
setting.put("index.refresh_interval", record ? TimeValue.timeValueSeconds(10).toString() : TimeValue.timeValueSeconds(config.getFlushInterval()).toString());
new BatchProcessEsDAO(elasticSearch7Client, config.getBulkActions(), config.getFlushInterval(), config.getConcurrentRequests())
```

**Comment by wu-sheng** [comment]
Because logically, they should be consistent from my understanding. Otherwise,  dirty read happens.
