### ISSUE TITLE
Oracle JDBC error when connecting Oracle with ServerName mode

### ISSUE THREAD

**Issue by silentmoooon** [apache/skywalking#4705]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
      6.6.0
      windows 10
       java8

 
- What happen?

 当jdbc url为全小写时会出现URLParse解析失败的情况。
 比如: jdbc:oracle:thin:@(description=(address=(host=x.x.x.x)(protocol=tcp)(port=1521))(load_balance=yes)(failover=on)(connect_data=(service_name=orcl)))

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Oracle plugin doesn't belong to the Apache, It is a 3rf party plugin only.

**Comment by silentmoooon** [comment]
但是问题是出现在jdbc-commons下

**Comment by wu-sheng** [comment]
Again English only, if you want to add some parser logic, feel free to submit the pull request.
