### ISSUE TITLE
Agent send a lot of IPV4s,so it causes the following error:org.h2.jdbc.JdbcSQLException: Value too long for column "PROPERTIES VARCHAR(2000)

### ISSUE THREAD

**Issue by welcome6688** [apache/skywalking#4707]
When agent is in VM,  it only sends **a IPV4 record**.  When agent is in docker, it sends many IPV4 records. so I want to modify  docker's agent

_Originally posted by @welcome6688 in https://github.com/apache/skywalking/issues/2511#issuecomment-618983747_

**Comment by wu-sheng** [comment]
Contributions are welcome, this is easy for the first time contributor.

**Comment by welcome6688** [comment]
I have a question about agent. Agent sends OSUtil information to server,result in table field error of server.Because there are too many IPv4 addresses obtained on the agent machine, the table fields of the server cannot be placed. Agent is in K8s. Server is oap-es-7.
![image](https://user-images.githubusercontent.com/8703738/80212414-05316500-866a-11ea-9eee-ea95bd1dbf75.png)
I want the agent not to send IPv4 information. I don't know how to change it?

**Comment by welcome6688** [comment]
So I don't understand why I only get one record in the virtual machine, and I get many records in the docker.
Can there be any place to modify the agent so that the agent does not send IPv4s.

**Comment by welcome6688** [comment]
![image](https://user-images.githubusercontent.com/8703738/80213409-b684ca80-866b-11ea-9fa0-ba7fc1f6e895.png)
The picture above shows a lot of IPV4s records

**Comment by wu-sheng** [comment]
That is based on your docker virtual network. It is designed by docker and k8s, etc. 

We should set the limitation of the list. OSUtil is already the place to change.

**Comment by welcome6688** [comment]
![image](https://user-images.githubusercontent.com/8703738/80215490-2052a380-866f-11ea-8c65-9d12d3612849.png)
I modified this method to return only empty arrays, but this is still the problem in the final run. Is there any other place to change

**Comment by wu-sheng** [comment]
No, there isn't, this is the only place.

**Comment by wu-sheng** [comment]
@welcome6688 I think @JaredTan95 provided this for you.
