### ISSUE TITLE
Snapshot continued  NullPointerException

### ISSUE THREAD

**Issue by dominicqi** [apache/skywalking#4709]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [-] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?

ContextManager#continued remove valid about IgnoredTraceContext.

https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/ContextManager.java#L143

Here will throw NullPointerException  if the pre-TraceContext is  IgnoredContext.Because traceSegmentId is null.

https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/ContextSnapshot.java#L53

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
  should allow IgnoredTraceContext continue

**Comment by wu-sheng** [comment]
@mrproliu please take a look.
