### ISSUE TITLE
Service id is empty

### ISSUE THREAD

**Issue by huohuanhuan** [apache/skywalking#4717]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
sw7,centos7,jdk1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
When you click track
2020-04-26 16:26:02,220 - graphql.execution.SimpleDataFetcherExceptionHandler - 23 [qtp1057263702-39] WARN  [] - Exception while fetching data (/topo) : Service id is empty
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Can't tell what happens. Recommend to debug, query is very easy to debug locally.

**Comment by liangguohun** [comment]
how to fix it,hi

**Comment by wu-sheng** [comment]
reboot agent. Don't delete data randomly.
