### ISSUE TITLE
Invalid input for Enum 'Language'. Unknown value 'PHP'

### ISSUE THREAD

**Issue by huohuanhuan** [apache/skywalking#4718]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
sw7 centos7 PHP1.7
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Click the refresh button of the dashboard to report the error below, and the PHP instance cannot be displayed

2020-04-26 16:41:49,827 - graphql.execution.ExecutionStrategy - 557 [qtp1057263702-41] WARN  [] - Can't serialize value (/getServiceInstances[0]/language) : Invalid input for Enum 'Language'. Unknown value 'PHP'
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Fixed in the master already. Will be released in 8.0
