### ISSUE TITLE
Why my springboot application can not  be shutdown gracefully with skywaking java agent?

### ISSUE THREAD

**Issue by wutingjia** [apache/skywalking#4720]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Firstly，I can confirm without agent my application can be shutdown gracefully.
But when I call a shutdown endpoint to my springboot application with java agent（no extra plugin），the jvm is not be destroyed. The thread status as follows:
![UcSTAR20200427085206](https://user-images.githubusercontent.com/33154970/80324786-f95dc280-8864-11ea-8fbb-5a4bf8f7f274.jpg)

  with arthas I can see some non-daemon thread is RUNNABLE.
  Another question is that if I use bootstrap-plugins，arthas can‘t attach the application

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.6.0
jdk1.8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking/pull/4541.
