### ISSUE TITLE
 is arths suitable for combination with skywalking?

### ISSUE THREAD

**Issue by HackerRookie** [apache/skywalking#4721]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [+] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
is the department or all function of arthas fit to combine with apm ?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> is the department or all function of arthas fit to combine with apm ?

What do you mean department? What department? What do you mean combine with APM?
Totally confused.

**Comment by wu-sheng** [comment]
After the DM discussion, this is not an issue, just an idea. Not suitable to be list here.
