### ISSUE TITLE
Is skywalking define trace-info protocol itself?

### ISSUE THREAD

**Issue by yaoyuandota** [apache/skywalking#4722]
(1)Agent send trace-info(TraceSegment) to OAPServer(by grpc or http).TraceSegment is a opentracing-skeleton only，but the info detail is define by skywalking itself,real?
eg: Trace-info of ZipKin is different between skywalking?  
(2) What the package "apm-toolkit-opentracing" doing for ? Can trace-info of skywalking transform to other  framework?

Thanks

**Comment by wu-sheng** [comment]
Your description is wrong. Trace segment is SkyWalking protocol and daya structure. We have nothing related to opentracing, except the toolkit to provide some compatible APIs only. We have clear protocol document to describe ours.

Our protocol is designed for APM, Zipkin is especially for tracing. We have much difference.

opentracing toolkit is providing limited APIs for users to interact with the agent.
