### ISSUE TITLE
A needed help about "Gloal Brief" part  in UI not showing numbers

### ISSUE THREAD

**Issue by sunrongxin7666** [apache/skywalking#4724]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
After building Sw Project in Idea By 8.0 master branch, I find that "Gloal Brief" part  in UI  does not show numbers and always "0". However, when I change sw version to 7.0 release, it works.  I am not sure that it is a bug in 8.0 version or my problem in local project build ?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  - SW 8.0 
  - centos8
  - Jdk 1.8.0_242
- Which company or project?
 - my local project
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
8.0 version
![image](https://user-images.githubusercontent.com/16604939/80350838-e3232700-88a3-11ea-9781-9af625d101de.png)
7.0 version
![image](https://user-images.githubusercontent.com/16604939/80351382-d226e580-88a4-11ea-83a1-5c169f14f7d7.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
First, there is no 8.0, then this is going to be removed in the official release.

**Comment by sunrongxin7666** [comment]
Very thanks for your response.  In other words，now master branch is just a dev branch and this ui problem will be corrected in release version. It’s right?

**Comment by wu-sheng** [comment]
No, this is not a bug. The brief visualization is abandoned. You will not see this on our UI anymore.

**Comment by sunrongxin7666** [comment]
OK, it make sense and hoping new version and new UI to release. Thanks again for your work
