### ISSUE TITLE
The same request url traceId sometimes shows "Ignored Trace" 

### ISSUE THREAD

**Issue by thomasbryant1024** [apache/skywalking#4734]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hi, Skywalking occurs a problem In the production environment.The traceId sometimes shows "Ignored Trace", sometimes is  normal. The request url is the same and one the same instance.The only difference is the request time is not the same.I checked the source code, but did not find the cause. Skywalking has mechanism like TTL for the agent registering? isn't a bug?  please show some tips. thx
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This thing should be in 2 cases
1. Agent sampling opened.
1. The codes processing Thread models are not same, even in the same endpoint.

Of course, a bug could cause this, But in most cases, the bug is actually caused by 2.

**Comment by thomasbryant1024** [comment]
> This thing should be in 2 cases
> 
> 1. Agent sampling opened.
> 2. The codes processing Thread models are not same, even in the same endpoint.
> 
> Of course, a bug could cause this, But in most cases, the bug is actually caused by 2.

Agent sampling closed，I have checked the agent config and OAP receiver config before

**Comment by wu-sheng** [comment]
Ignore is rarely to see in 100% sampling, in most cases, even there is bug, it doesn't show ignored trace.

**Comment by thomasbryant1024** [comment]
> Ignore is rarely to see in 100% sampling, in most cases, even there is bug, it doesn't show ignored trace.

so that is so odd, the interval of the two call with the same url is  almost two minutes, so the concurrency problem will be excluded ...I will try to debug locally and add more skywalking log in pro env tomorrow. If I still can not find the cause , then  ask for  help later

**Comment by wu-sheng** [comment]
I could share the understanding in the code level, cocurrency doesn't affect the sampling or ignorance.

**Comment by thomasbryant1024** [comment]
> I could share the understanding in the code level, cocurrency doesn't affect the sampling or ignorance.

OK.thx a lot

**Comment by whfjam** [comment]
in my case when the agent can not connect to oapServer it will creat the Ignored_Trace the code is in ContextManagerExtendService.createTraceContext " if (!Config.Agent.KEEP_TRACING && GRPCChannelStatus.DISCONNECT.equals(status)) {
            return new IgnoredTracerContext();
        }"

**Comment by SZMOFEI** [comment]
Yes , in my case too 。  if the agent config a uncorrect oap Server address , or unable to. connect to the correct oap Server  . 

the Trace_id will. return. **Ignored_Trace** ！！！

how to fix:
config the correct oap server  address 。  

`collector.backend_service=${SW_AGENT_COLLECTOR_BACKEND_SERVICES:127.0.0.1:11800}
`

**Comment by Bigbobc** [comment]
How did you finally solve this problem?

**Comment by Zhazhanan** [comment]
> How did you finally solve this problem?

1. Confirm that skywalking has started normally.
2. Confirm that the back-end address of agent configuration is correct。Parameter is "collector.backend_service="
