### ISSUE TITLE
[NIGNX-LUA]  Not all lua scripts are included after installation

### ISSUE THREAD

**Issue by harrybin815** [apache/skywalking#4742]
### Question
- What do you want to know?
[NIGNX-LUA]  Not all lua scripts are included after installation
___
### Requirement or improvement
       `luarocks install skywalking-nginx-lua` could install all lua script in dir `library/skywalking`

**Comment by wu-sheng** [comment]
@moonming I think we have lua rock release 0.1.0 already, right?

**Comment by harrybin815** [comment]
Hopefully compatible with v0.1.0 or v0.1.x

**Comment by wu-sheng** [comment]
@haotian2015 lua rocks is just a release way only. Nothing special.

**Comment by wu-sheng** [comment]
I just checked, lua rocks exists already. https://luarocks.org/modules/apache-skywalking/skywalking-nginx-lua

**Comment by harrybin815** [comment]
But rockspec file only specifies some lua files, which means that this is not a complete installation

**Comment by wu-sheng** [comment]
I think others have been included in the OpenResty already. Which Nginx are you using? We have the dependency list here, https://github.com/apache/skywalking-nginx-lua#local-development-and-unit-tests

**Comment by harrybin815** [comment]
This is the build information for rockspec
```
build = {
   type = "builtin",
   modules = {
    ["skywalking.register"] = "lib/skywalking/register.lua",
    ["skywalking.segment_ref"] = "lib/skywalking/segment_ref.lua",
    ["skywalking.segment"] = "lib/skywalking/segment.lua",
    ["skywalking.span_layer"] = "lib/skywalking/span_layer.lua",
    ["skywalking.span"] = "lib/skywalking/span.lua",
    ["skywalking.tracing_context"] = "lib/skywalking/tracing_context.lua",
    ["skywalking.util"] = "lib/skywalking/util.lua",
   }
}
```
But dir  `library/skywalking` contains the following script:
<img width="211" alt="Screen Shot 2020-05-07 at 10 24 50 AM" src="https://user-images.githubusercontent.com/41782151/81247640-1d7f8780-904d-11ea-9ecd-c74cb8f07dc8.png">

When `luarocks install` was run, I couldn't get all the scripts under the directory `library/skywalking`(*_test.lua can be ignore), Only the script specified in `rockspec.build` will be included

**Comment by wu-sheng** [comment]
@moonming Could you take a look? Typically, I don't use in this way.

**Comment by moonming** [comment]
@harrybin815 luarocks automatically installs the dependent files at the time of installation, so there is no need to install `dependencies` directory.
https://github.com/apache/skywalking-nginx-lua/blob/master/rockspec/skywalking-nginx-lua-0.1-0.rockspec#L14

`client.lua` and `tracer.lua` are showing how to use this library, and you may need to implement your own version.

**Comment by harrybin815** [comment]
but the `segment_ref.lua` depends on `dependencies/base64` which is not included in the installation directory. I should create a lua file named `dependencies/base64.lua` in my project? but all lua file in `build` is in 'skywalking' directory, maybe `skywalking/dependencies/base64.lua` would be better?

**Comment by wu-sheng** [comment]
@moonming Seems that file is missing in the rockspec, could you update the two spec files?

**Comment by moonming** [comment]
sure, I will fix

**Comment by harrybin815** [comment]
`https://luarocks.org/manifests/apache-skywalking/skywalking-nginx-lua-0.1-0.rockspec` has not been updated

**Comment by moonming** [comment]
upload the new version, please hae a look, thx

Thanks,
Ming Wen
Twitter: _WenMing


harrybin <notifications@github.com> 于2020年5月13日周三 上午10:53写道：
