### ISSUE TITLE
endpoint maximum number 

### ISSUE THREAD

**Issue by smilesheep** [apache/skywalking#4747]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- What do you want to know?
**Is the maximum number of endpoint is 10000? In Web UI 'Global Brief'**

**Comment by wu-sheng** [comment]
It has been removed in 8.0. And it could be more than 10k.

**Comment by smilesheep** [comment]
ok, thanks
