### ISSUE TITLE
URI endponit is random cause memory  increase

### ISSUE THREAD

**Issue by Chenguanqun00** [apache/skywalking#4755]
My issus is like [3293](https://github.com/apache/skywalking/issues/3293)
 
But the difference is  the url endpoint is  random .
Such as /a8fc1d-10674684-xxxxx/v/1588190430.jpg.
 I've seen the feature [3299](https://github.com/apache/skywalking/pull/3299).
But it can't solve my issus.
I would like to offer a humble suggestion just like "ignore the specific url" or "like [3299](https://github.com/apache/skywalking/pull/3299) merge the host"

Sorry,  it's my first issus by english.
 Please forgive me.

**Comment by wu-sheng** [comment]
I could understand your point. Basically, grouping the endpoints into one or excluding the `*.jpg`(which we should have provided already) are the options you have.

In the next 8.0.0, register and cache are both removed, the master branch includes the codes already. So we don't need to worry about this kind of issue. But in your case, excluding them is still the best choice from my understanding.
