### ISSUE TITLE
not support springmvc [server.servlet.context-path]

### ISSUE THREAD

**Issue by czeeland** [apache/skywalking#4759]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
   7.0.x
- What happen?

because skywalking override getRequestURL method by recursive annotaion, not support springmvc configration param [server.servlet.context-path], cause skywalking-oap search endpoint question；
if request return before controller method, like web filter,springboot interceptor，it will has the different endpoint。

```java
public class RequestMappingMethodInterceptor extends AbstractMethodInterceptor {
    @Override
    public String getRequestURL(Method method) {
        return ParsePathUtil.recursiveParseMethodAnnotaion(method, m -> {
            String requestURL = null;
            RequestMapping methodRequestMapping = AnnotationUtils.getAnnotation(m, RequestMapping.class);
            if (methodRequestMapping != null) {
                if (methodRequestMapping.value().length > 0) {
                    requestURL = methodRequestMapping.value()[0];
                } else if (methodRequestMapping.path().length > 0) {
                    requestURL = methodRequestMapping.path()[0];
                }
            }
            return requestURL;
        });
    }
}
```

```java
     if (Config.Plugin.SpringMVC.USE_QUALIFIED_NAME_AS_ENDPOINT_NAME) {
            operationName = MethodUtil.generateOperationName(method);
        } else {
            EnhanceRequireObjectCache pathMappingCache = (EnhanceRequireObjectCache) objInst.getSkyWalkingDynamicField();
            String requestURL = pathMappingCache.findPathMapping(method);
            if (requestURL == null) {
                requestURL = getRequestURL(method);
                pathMappingCache.addPathMapping(method, requestURL);
                requestURL = getAcceptedMethodTypes(method) + pathMappingCache.findPathMapping(method);
            }
            operationName = requestURL;
        }
```

**Comment by vgtom** [comment]
I would like to work on this issue!! Is there a chat forum where we can discuss??

**Comment by wu-sheng** [comment]
@vgtom Welcome. I also noticed you have found the slack room. So, the mail list is the most official discussion in the Apache, if you just need quick discussion, slack and github issue are both fine. :)

**Comment by vgtom** [comment]
is it possible to have a quick hangout/webex/zoom session to explain the code structure?

**Comment by wu-sheng** [comment]
@vgtom Usually we don't have such a session, because it could overload me easily. If you have any questions, feel free to ask me here or on the slack/mail list.

**Comment by wu-sheng** [comment]
@vgtom If you have subscribed to our dev mail list, I just send the invitation about that, we have a bi-weekly online meeting tomorrow night 0830 PM UTC+8 TZ. If you have any question, welcome to join. There are many discussion there in Mandarin, due to many of our users are, but feel free to use English, I will be there.

**Comment by vgtom** [comment]
@wu-sheng ...ok i will try to join the meeting tomorrow at  0830 PM UTC+8 TZ...but i just started here and would have been nice if someone cud have guided me on the code structure or some videos perhaps...

**Comment by jackiepon31** [comment]
i have read the source code of Skwalking  for a while and i have made some comments on that,may be i can help you ,

**Comment by timandy** [comment]
I have the same confuse. How to change the context path of skywalking-ui?

**Comment by wu-sheng** [comment]
> I have the same confuse. How to change the context path of skywalking-ui?

Off topic.
