### ISSUE TITLE
apache/skywalking-oap-server:7.0.0-es7------bug

### ISSUE THREAD

**Issue by soar1688** [apache/skywalking#4762]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug
___
### Bug
- Which version of SkyWalking, OS and JRE?
apache/skywalking-oap-server:7.0.0-es7
- What happen?
```
[Entrypoint] Apache SkyWalking Docker Image
Current image doesn't Elasticsearch 6
```
Elasticsearch vsersion is docker.elastic.co/elasticsearch/elasticsearch:7.6.2

**Comment by wu-sheng** [comment]
Read document and use correct parameter. Should be elasticsearch7.

**Comment by mchenx** [comment]
got same issue

have es 7.4.2 running 

started with apache/skywalking-oap-server:8.1.0-es7  image

and got below logs, the service not got really started

![image](https://user-images.githubusercontent.com/1550186/92430894-a576c900-f1c8-11ea-95ab-c3b92d7f2b4f.png)

**Comment by wu-sheng** [comment]
You are using wrong image. ES6 and ES7 are mapping 2 images.

**Comment by mchenx** [comment]
$ docker run --name oap --restart always -d -e SW_STORAGE=elasticsearc7 -e SW_STORAGE_ES_CLUSTER_NODES=es.my.local:9200 apache/skywalking-oap-server:8.1.0-es7

anything wrong?

**Comment by wu-sheng** [comment]
Could you be more careful? `elasticsearc7` really?

**Comment by mchenx** [comment]
that was typo
