### ISSUE TITLE
profile cannot be displayed more info

### ISSUE THREAD

**Issue by amwyyyy** [apache/skywalking#4764]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement
___
 - version: SkyWalking7.0.0
 - When the stack level is deep, some content cannot be displayed, and a horizontal scroll bar should be added.
![企业微信20200509171229](https://user-images.githubusercontent.com/8274512/81470014-f7a7dd80-921a-11ea-949d-056f6b1d9cbe.png)

**Comment by wu-sheng** [comment]
Duplicated, this has been reported by #4550. We are still trying to work it out. Currently, this component doesn't support this.
