### ISSUE TITLE
Oal sum function not work

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4771]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
the following expression is note on the official doc:
Service_Calls_Sum = from(Service.*).sum();
but,when I try it, there are some error
![image](https://user-images.githubusercontent.com/31562192/81526519-63f51f00-938a-11ea-9172-df67adbb35cd.png)

how can i use it to count all calls for a service?

**Comment by wu-sheng** [comment]
You are calling sum, should put a value in the from function. Otherwise, you should use count. Those are different functions.

**Comment by EvanLjp** [comment]
![image](https://user-images.githubusercontent.com/31562192/81527093-f9dd7980-938b-11ea-8b86-c29747913c8d.png)
Could you correct the documentation?

**Comment by wu-sheng** [comment]
You could send a pull request to do so directly. @EvanLjp

**Comment by EvanLjp** [comment]
ok .i would be correct

**Comment by EvanLjp** [comment]
And  I want to add a feature:
dynamic read config from kubernetes configMap, now skywalking configuration support apollo,consul,etcd,nacos,zookeeper , don't suuport watch kunbernetes configMap event,

could I pull request this feature?

**Comment by regardfs** [comment]
@EvanLjp I had met the same error, How did u fix it?

**Comment by regardfs** [comment]
hi, @EvanLjp, where did u get this error log, I found nothing in my oap server log, but no index generated in es...., I just did the samething like u by adding this kind of sum in oal prefix file, where did the file locate?
> Please answer these questions before submitting your issue.
> 
> * Why do you submit this issue?
> * [ ]  Question or discussion
> 
> ### Question
> * What do you want to know?
>   the following expression is note on the official doc:
>   Service_Calls_Sum = from(Service.*).sum();
>   but,when I try it, there are some error
>   ![image](https://user-images.githubusercontent.com/31562192/81526519-63f51f00-938a-11ea-9172-df67adbb35cd.png)
> 
> how can i use it to count all calls for a service?

**Comment by EvanLjp** [comment]
my oal  config is  wrong

**Comment by hyhy01** [comment]
same error
