### ISSUE TITLE
How to post spans to collector using http post?

### ISSUE THREAD

**Issue by Simbafa** [apache/skywalking#4774]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion

How to post spans to collector using http post?

___
### Question
- What do you want to know?

    - We want to use SkyWalking in a micro-services environment which Kong is used as gateway.
    - A plugin will be created in Kong to collection API calls info and then send the info to SkyWalking collector.
    - Is there a document which describes all services the collector exports? Or
    - Which services should the info be posted to?

**Comment by wu-sheng** [comment]
We have the LUA agent for OpenResty ecosystem. I think Kone should be compatible with it. Try this, https://github.com/apache/skywalking-nginx-lua

**Comment by wu-sheng** [comment]
And HTTP protocol has been provided in 7.0.0 release and have some upgrade in 8.0.0, you could find the document in the protocol section.
