### ISSUE TITLE
throw java.lang.NoClassDefFoundError: org/apache/shardingsphere/core/execute/ShardingExecuteDataMap

### ISSUE THREAD

**Issue by wz2cool** [apache/skywalking#4780]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to fix this exception or how to ignore this exception in log file
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 7.0,  jre

- What happen?
throw exception in log,  I have checked plugin, we have `apm-sharding-sphere-4.x-plugin-7.0.0.jar` in agent folder 
![image](https://user-images.githubusercontent.com/11556152/81769305-da6f5980-950f-11ea-9221-9f5d7c099c2b.png)

**Comment by wu-sheng** [comment]
Which shardingsphere version are you using? I think you should ping ShardingSphere community, they contribute this plugin with tests in the following versions.

![image](https://user-images.githubusercontent.com/5441976/81769598-992b7980-9510-11ea-8be2-6d8cb7e6fd8a.png)

Also, they open this #4229 but haven't processed this still.

**Comment by wu-sheng** [comment]
FYI @tristaZero @tuohai666 @terrymanu I think the ShardingSphere package rename continues happening. SkyWalking received 3+ issues reported because of the compatible issue. Please be advised.

**Comment by wz2cool** [comment]
> Which shardingsphere version are you using? I think you should ping ShardingSphere community, they contribute this plugin with tests in the following versions.
> 
> ![image](https://user-images.githubusercontent.com/5441976/81769598-992b7980-9510-11ea-8be2-6d8cb7e6fd8a.png)
> 
> Also, they open this #4229 but haven't processed this still.

thanks for your quick response ,  we use  org.apache.shardingsphere  v 4.0.0.0  not RC version

**Comment by wz2cool** [comment]
more info, the first time we found this error in skywalking.log, it shows "at org.apache.skywalking.apm.plugin.shardingsphere.v4rc3.ExecuteInterceptor.beforeMethod(ExecuteInterceptor.java:42)"
so we remove `apm-sharding-sphere-4.x-rc3-plugin-7.0.0.jar` from plugins folder, but it still don't work

![image](https://user-images.githubusercontent.com/11556152/81772854-81a4be80-9519-11ea-80ab-4084896203fe.png)

**Comment by wu-sheng** [comment]
Don't have plugin for that. That is why we asked you to submit request to ShardingSphere

**Comment by wz2cool** [comment]
> Don't have plugin for that. That is why we asked you to submit request to ShardingSphere

ok, thanks

**Comment by tuohai666** [comment]
@wu-sheng @wz2cool, this problem is due to package name changed. @menghaoranss from ShardingSphere community will add new plugin for that.

**Comment by wz2cool** [comment]
> @wu-sheng @wz2cool, this problem is due to package name changed. @menghaoranss from ShardingSphere community will add new plugin for that.

ok thanks, currently we will remove this plugin to avoid error log

**Comment by BruceZhangXL** [comment]
this proplem has not be fixed in version of 8.0.1
