### ISSUE TITLE
A bug when querying "instance_jvm_cpu" metric

### ISSUE THREAD

**Issue by sunrongxin7666** [apache/skywalking#4782]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

values of **instance_jvm_cpu** metric in ES  are doubles and less than 1.
![image](https://user-images.githubusercontent.com/16604939/81811908-f696e900-9557-11ea-8a92-39b6aa6b1833.png)

However,  in the query method `org.apache.skywalking.oap.server.storage.plugin.elasticsearch.query.MetricsQueryEsDAO`, **instance_jvm_cpu** values are converted as `Long`  without any treatment like `value * 100`.

![image](https://user-images.githubusercontent.com/16604939/81813091-9dc85000-9559-11ea-991d-035fd65e8ddd.png)

As a result,  **instance_jvm_cpu**  values in UI  are incorrect and too small.
![image](https://user-images.githubusercontent.com/16604939/81813222-c5b7b380-9559-11ea-8441-ef231243f4ba.png)

**Comment by wu-sheng** [comment]
I think this is not a bug. Please take a look at the agent side codes, it already multiplies 100. The most likely possibility of being `0`, is we assume the top of CPU usage is 100%, so it divides CPU core num.

Read the codes, please. If there is another case, please let me know.
