### ISSUE TITLE
skywalking7.0 

### ISSUE THREAD

**Issue by lijiahuioooo** [apache/skywalking#4785]
存储 ：elasticsearch 6.8.8 三台
skywalking版本 ：7.0
搭建好后，接入生产流量，日志一直有空指针异常，频率非常高
11:37:06,249 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 170 [grpcServerPool-1-thread-7] ERROR [] - null
多次重启 agent ,collector 问题依然存在

**Comment by wu-sheng** [comment]
English only. Clear your local buffer file and reboot agents

**Comment by WilliamShoww** [comment]
我也是7.0，strage我用的是es7， es版本7.3.2 然后双击oapService.bat一闪而过。没有日志，啥都没有。求教怎么启动？
