### ISSUE TITLE
why not distinguish trace segment index config and metrics index config

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4790]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
why not distinguish trace segment index config and metrics index config
One shards normally contains data is about 10G-30G

metrics data is usually smaller than above capacity ,trace segment data is is usually bigger than above capacity

Too many shards will affect es performance

why not distinguish the setting?Although I understand that manual templates can be controlled

**Comment by wu-sheng** [comment]
What do you want to propose? About how in the codes level? How to make people understand the config? There is not much special about the segment index from my understanding.

**Comment by EvanLjp** [comment]
1. The segment index is much larger than the other indexes
2. An index of 30-50g data can guarantee good query performance,and If a shards is too large, the es cluster will restart
So unless you manually control the number of shards, why not config it in code

And need to think again about how to implement code

**Comment by wu-sheng** [comment]
I know your case, I just consider the implementation. One, this is only an ES specific thing, the other is, this is only related to segment, but there are other record type entities.

**Comment by EvanLjp** [comment]
I think this function should be the same as the number of shards and should only work in es storage config

it only works here

![image](https://user-images.githubusercontent.com/31562192/82040153-b6ab3f80-96d8-11ea-9ab5-5e3a96a1a281.png)

**Comment by EvanLjp** [comment]
I think this function should be the same as the number of shards and should only work in es storage config
it only works here

![image](https://user-images.githubusercontent.com/31562192/82040287-f83bea80-96d8-11ea-8290-5b8ff55cce69.png)

**Comment by wu-sheng** [comment]
About config, yes. But you need to figure out how make it works for segment only? Have you considered this?

**Comment by EvanLjp** [comment]
I konw it,I will consider it

**Comment by wu-sheng** [comment]
I think you could do these
1. Add an annotation `@SuperDataSet`, this annotation indicates the `StorageData` implementation having super size data set.
1. Add `@SuperDataSet` to `SegmentRecord`.
1. Change the model definition with `superDataSet` flag.
1. Add `superDataSetShardsNumberFector` to give the `multiplier` of `indexShardsNumber` for the `@SuperDataSet` annotated type.

@kezhenxu94 @dmsolr @JaredTan95 @arugal  WDYT?

**Comment by EvanLjp** [comment]
It's a good idea for implement it

**Comment by kezhenxu94** [comment]
> I think you could do these
> 
> 1. Add an annotation `@SuperDataSet`, this annotation indicates the `StorageData` implementation having super size data set.
> 2. Add `@SuperDataSet` to `SegmentRecord`.
> 3. Change the model definition with `superDataSet` flag.
> 4. Add `superDataSetShardsNumberFector` to give the `multiplier` of `indexShardsNumber` for the `@SuperDataSet` annotated type.
> 
> @kezhenxu94 @dmsolr @JaredTan95 @arugal WDYT?

Sounds good enough to me,

**Comment by wu-sheng** [comment]
@EvanLjp Could you follow this to send a pull request?

**Comment by EvanLjp** [comment]
ok,I would like to do it
