### ISSUE TITLE
A needed help About Es expection "without one being designated as a write index" when creating a new profile task

### ISSUE THREAD

**Issue by sunrongxin7666** [apache/skywalking#4794]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion

___
### Question
- What do you want to know?
Similarly with #4729  ，I find an errors  "*The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index*" when creating a new profile task. However I am sure that I have pulled the lastest code in master branch.
![image](https://user-images.githubusercontent.com/16604939/82116428-5d0c4900-979c-11ea-8eb1-d34351f72038.png)

There are multiple indices with alias "profile_task" in my Es and the latest "Write Index" also exists
![image](https://user-images.githubusercontent.com/16604939/82116492-cc823880-979c-11ea-8dc3-20c1d264a671.png)

If "profile_task-20200516" is set as  "is_write_index" = true, it will work without this error.  But other metrics indexes with the same alias can work well without doing this. 

It is also a TTL Bug?  Would you mind to share some suggestions to deal with it?

**Comment by wu-sheng** [comment]
All indexes should be created based on the template. This seems very strange.

**Comment by wu-sheng** [comment]
Seems I could reproduce this issue locally, but don't know why for now.
