### ISSUE TITLE
improvement lettuce plugin

### ISSUE THREAD

**Issue by zuohl** [apache/skywalking#4797]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Feature or performance improvement
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Lettuce plugin can only display command type, not specific key,like jetty plugin

**Comment by wu-sheng** [comment]
Contribution is welcome. This should not be hard.

**Comment by zuohl** [comment]
> Contribution is welcome. This should not be hard.

ok,thank you,then i will don`t need submit a pull request
