### ISSUE TITLE
v6.5.0 gateway bug

### ISSUE THREAD

**Issue by wushihua** [apache/skywalking#4799]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [1 ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to fix，Upgrade version?
___
### Bug
- Which version of SkyWalking, OS and JRE?
v6.5.0，springateway 2.1.3
- What happen?
Do you encounter a 6.5.0 gateway that causes a memory overflow and a high CPU？

**Comment by wu-sheng** [comment]
Try the latest version, and we only support some versions of Gateway. Tracked in #4252, currently, no one focuses on that. I am feeling the gateway is not that popular due to no one wants to enhance and work on some PRs.

**Comment by wushihua** [comment]
ok，thanks
