### ISSUE TITLE
Is it a good idea to dynamic get config from configMap in kubernetes

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4800]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
Is it a good idea to dynamic config from configMap in kubernetes

nowadays,skywalking support the following config center:
![image](https://user-images.githubusercontent.com/31562192/82288822-ed819e00-99d5-11ea-9e01-2c20f8abd56e.png)
I want to add a plugin for support dynamic get config by configMap event when running in kubernetes.

**Comment by wu-sheng** [comment]
Could you provide detail about which API(s) you are planning to use for watching the config?

**Comment by EvanLjp** [comment]
Similar to cluster-kubernetes-plugi, it's depends on 
<dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
        </dependency>


the api is  use event to watch: watch = Watch.createWatch(client, api.listNamespacedPodCall(namespace, null, null, null, null, labelSelector, Integer.MAX_VALUE, null, null, Boolean.TRUE, null, null), new TypeToken<Watch.Response<V1Pod>>() {
            }.getType());

and spring cloud config is already implement it ,you can refer to this

https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-config

**Comment by hanahmily** [comment]
spring-cloud uses two modes to watch configmap changes: Polling, and Event. That's because it uses Watcher API which can disconnect (network problems, timeout, etc). So if users want to avoid them, Polling strategy is the option.

My suggestion is we should adopt to Informer which tries to re-list and re-watch to hide such failures from the caller. Below is the example
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/InformerExample.java

**Comment by EvanLjp** [comment]
In the afternoon,I learn some doc about the Informer.
1. In my mind , the Informer is a more effective
way to connect with api server compare with the watch event. so we can use it to watch configMap change event
2. the skywalking kubernetes version is 4.0.0, this version doesn't exist the Informer api,so we need to change the version of  kubernetes-client-java to 8.0.0.
3. Is need to change the cluster-kubernetes-plugin?

**Comment by wu-sheng** [comment]
> the skywalking kubernetes version is 4.0.0, this version doesn't exist the Informer api,so we need to change the version of kubernetes-client-java to 8.0.0.

Feel free to do, but you will need LICENSE update, and make CI passed(there are dependencies check)

> Does it need to change the cluster-kubernetes-plugin by using Informer at the same time?

@hanahmily WDYT?

**Comment by EvanLjp** [comment]
@wu-sheng  ok,i will do it on this week @hanahmily WDYT?

> @hanahmily WDYT? But basically, this is a separate issue. You could do in 2 pull requests.
no problem

**Comment by EvanLjp** [comment]
there is so many conflicts between client-java 4.0.0 with client-java 8.0.0 ,so maybe the receently commits choose 4.0.0 is a goog choose,in  the next commit , refactor this feature.

Known conflict:
![image](https://user-images.githubusercontent.com/31562192/83027373-a09b6880-a062-11ea-9e37-3d804b5fba1a.png)

**Comment by wu-sheng** [comment]
@hanahmily I think you asked for informer, which requires the 8.0.

@EvanLEva How about we update the lib first?

**Comment by EvanLjp** [comment]
ok, i try to modify it .but i don't hava test enviorment for envoy , I think the feature will be test  by regression testing

**Comment by wu-sheng** [comment]
We leak of als(envoy related) tests, yes. I think have to ask @hanahmily to do some manual test for now.

**Comment by wu-sheng** [comment]
@EvanLjp PR merged, I think you could continue on this.

**Comment by EvanLjp** [comment]
no problem
