### ISSUE TITLE
bug:tomcat-7.x-8.x-plugins

### ISSUE THREAD

**Issue by wangdafang** [apache/skywalking#4803]
skywalking-v7.0.0

desc
The question is ,there is lot's of url in our spring-controller,and some is dynamic parameter, such as "http://localhost:8080/hello/user/{userID} ". 
When the qps is growing with lot's of different userID,the sw-collector’s Memory will grow geometrically.Finally when the Old generation of JVM is Exhausted,the process will keep fgc forever. It's not  an accident.

I found it may because of an plugin:"tomcat-7.x-8.x-plugins", when the TomcatInvokeInteceptor.beforeMethod creates span, 
sw will set operationName by  request.getRequestURI() ,in general,that should transfer to a variable such as "{userID}",but it not work.

**Comment by wu-sheng** [comment]
Discussion happens on the mail list.

**Comment by wangdafang** [comment]
> Discussion happens on the mail list.

Thank you very much.And could you tell me  what's the reason,I wondering
