### ISSUE TITLE
spring

### ISSUE THREAD

**Issue by Z183123467** [apache/skywalking#4806]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ]Bug
- [ ]Requirement
- [x] Feature or performance improvement
___
### Question
- What do you want to know?
When Skywallking supports Spring Cloud Gateway 2.2.x?
___
### Bug
- Which version of SkyWalking, OS and JRE?
- version: 7.0.0
- OS:windows10

- What happen?
- incompatible！
- Link disconnected
![image](https://user-images.githubusercontent.com/41281902/82518238-7bce5f00-9b51-11ea-8a2b-fc2f6d1cc2d3.png)
![image](https://user-images.githubusercontent.com/41281902/82518346-c354eb00-9b51-11ea-9754-53f91af005e0.png)

- Which company or project?
- Personal Learning
___
### Requirement or improvement
- Hope to be compatible as soon as possible

**Comment by wu-sheng** [comment]
We have issue for Gateway already, don't submit the duplicate one.
