### ISSUE TITLE
Spring Cloud Gateway 2.2.x incompatible?

### ISSUE THREAD

**Issue by Z183123467** [apache/skywalking#4807]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ]Bug
- [ ]Requirement
- [x] Feature or performance improvement
___
### Question
- What do you want to know?
When Skywallking supports Spring Cloud Gateway 2.2.x?
___
### Bug
- Which version of SkyWalking, OS and JRE?
- version: 7.0.0
- OS:windows10

- What happen?
- incompatible！
- Link disconnected
![image](https://user-images.githubusercontent.com/41281902/82518238-7bce5f00-9b51-11ea-8a2b-fc2f6d1cc2d3.png)
![image](https://user-images.githubusercontent.com/41281902/82518346-c354eb00-9b51-11ea-9754-53f91af005e0.png)

- Which company or project?
- Personal Learning
___
### Requirement or improvement
- Hope to be compatible as soon as possible

**Comment by wu-sheng** [comment]
Why are you keeping submitting thing? We have one, https://github.com/apache/skywalking/issues/4252. Please be polite.

**Comment by Z183123467** [comment]
I'm sorry，my network is not good，is very bad.

> 你为什么一直在提交东西？我们有一个[＃4252](https://github.com/apache/skywalking/issues/4252)。请客气。



> Why are you keeping submitting thing? We have one, #4252. Please be polite.

I'm sorry，my network is not good，is very bad.

**Comment by Z183123467** [comment]
> Why are you keeping submitting thing? We have one, #4252. Please be polite.
I'm sorry,my network is not good,very bad! Sorry again
