### ISSUE TITLE
apm-trace-ignore-plugin failed to filter interface /actuator/health

### ISSUE THREAD

**Issue by suruns** [apache/skywalking#4809]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- apm-trace-ignore-plugin failed to filter interface /actuator/health

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking7.0  linux, jre 1.8.0.201
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

i use skywalking moniter my platform,which is based on spring cloud implementation. i want filter interface /actuator/health, i use apm-trace-ignore-plugin and copy it from optional-plugins to plugins, and set up filter config file, which write 'trace.ignore_path=/v1/catalog/services,/actuator/health,Lettuce/**'. but the web ui  tracking interface only still has ‘/actuator/health’ endpoints，other such as Lettuce/** is successful.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
i want to filter the endpoints i write in apm-trace-ignore-plugin.config

**Comment by wu-sheng** [comment]
This plugin is to filter the segment's first span. You need to make sure whether it is matched. Please try to debug locally. Once the `Lettuce/ is successful` works, I would not say this is a code level issue.

**Comment by suruns** [comment]
1.这个endpoint只有一个span，2我是全名称匹配，没有使用正则之类的

**Comment by wu-sheng** [comment]
English only. And still, local debug is much better than you ask here. At least you have more detail, we could do a more meaningful discussion.

Asking me to guess has not much meaning, and is not very helpful for you.

**Comment by suruns** [comment]
![image](https://user-images.githubusercontent.com/12554451/82531760-877e4d80-9b72-11ea-9f79-81499050daeb.png)
I modified the code to print all endpoints, but I didn't see ‘/actuator/health‘ in the log, but this endpoint was included on the page

**Comment by suruns** [comment]
org.apache.skywalking.apm.plugin.trace.ignore.TraceIgnoreExtendService
this is the class i modified

**Comment by wu-sheng** [comment]
That means,  ‘/actuator/health‘ isn't the one creating the segment. Suggest you consider other plugin works first, such as Tomcat container, jetty plugin, etc. 

The name showing in the segment doesn't mean it is the first span. EntrySpan has an operation name override mechanism.

Look closer and dig deeper.

**Comment by suruns** [comment]
thanks， I make an attempt

**Comment by DerekHQ** [comment]
I has this problem too！ I found out that  ignore '/actuator/health' base in Servlet project is ok, but in Webflux project is not work!

**Comment by suruns** [comment]
It's been renamed. Its real name is WEBFLUX.handle

**Comment by qixiang-liu** [comment]
> 请在提交问题之前回答这些问题。
> 
> * 为什么要提交这个问题？
> * [x] 问题或讨论
> * [x] 漏洞
> * [x] 要求
> * [ ] 功能或性能改进
> 
> ### 题
> * apm-trace-ignore-plugin 过滤接口/actuator/health 失败
> 
> ### 漏洞
> * SkyWalking、OS 和 JRE 的哪个版本？
>   skywalking7.0 linux, jre 1.8.0.201
> * 哪个公司或项目？
> * 发生什么事？
>   如果可能，请提供一种重现错误的方法。例如演示应用程序、组件版本。
> 
> 我使用 Skywalking 监控我的平台，它基于 Spring Cloud 实现。我想要过滤器接口/actuator/health，我使用apm-trace-ignore-plugin并将其从可选插件复制到插件，并设置过滤器配置文件，其中写入'trace.ignore_path=/v1/catalog/services，/执行器/健康，生菜/ **'。但是 web ui 跟踪界面仍然只有 '/actuator/health' 端点，其他如 Lettuce/**是成功的。
> 
> ### 要求或改进
> * 请描述您的要求或改进建议。
>   我想过滤我在 apm-trace-ignore-plugin.config 中编写的端点

解决了吗？我是最新版本的8.9.1也出现这个问题了。请问如何解决的那？
<img width="351" alt="image" src="https://user-images.githubusercontent.com/30148386/158094832-c6221046-109d-45d8-b830-7ac8d265d5f7.png">

**Comment by qixiang-liu** [comment]
已经解决。

**Comment by luckywur** [comment]
how to fix it?

**Comment by shelltea** [comment]
Try to use this config.

```
trace.ignore_path=GET:/actuator/*
```

**Comment by zhangam** [comment]
> 

nb!!!

**Comment by zhangam** [comment]
> Try to use this config.
> 
> ```
> trace.ignore_path=GET:/actuator/*
> ```

nb!!!
