### ISSUE TITLE
Any plan for Jaeger receiver to support Analysis mode?

### ISSUE THREAD

**Issue by ArronD** [apache/skywalking#4811]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [X ] Requirement
- [ ] Feature or performance improvement

___
### Question
- We are planning to add tracing for a C++ project.  Besides tracing, we want the additional APM functions which Skywalking provides. However,  skywalking doesn't have a C++ client library at this moment. Thus, we would like to use Jaegar C++ client library to collect the tracing data and send it to Skywalking. Howerver, Skywalking Jaeger receiver doesn't support  Analysis mode, which means we cannot use the additional APM functions which Skywalking provides. 
Now we are wondering is there any plan for Jaeger receiver to support Analysis mode?

Thanks!

**Comment by wu-sheng** [comment]
Analysis trace from zipkin or jaeger is not a high performance. We only have experimental Zipkin trace analysis. It is only working in no cluster mode. 

see #2653 for more details and context. Jaeger and Zipkin are sharing the same issue.

**Comment by ArronD** [comment]
Thanks for your reply！
