### ISSUE TITLE
Question about EndpointGroup Behavior

### ISSUE THREAD

**Issue by dominicqi** [apache/skywalking#4813]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [-] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
endpointGroup not group length less than endpointNameMaxLength ? expect behavior?
https://github.com/apache/skywalking/blob/a10e04493272a88931d6916662b30d0a320287bb/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/config/NamingControl.java#L98

**Comment by kezhenxu94** [comment]
I think this is a bug @wu-sheng

**Comment by wu-sheng** [comment]
I will fix this soon.
