### ISSUE TITLE
Skywalking only collect the wildcard endpoint "/**" rather than the real endpoints

### ISSUE THREAD

**Issue by yimzncy** [apache/skywalking#4823]
Skywalking 6.6, Spring MVC

When I only have one wildcard RequestMapping in my controller, Skywalking only collect the wildcard endpoint "/**" rather than the real endpoints.

```
@Controller
public class BaseController {
    @RequestMapping("/**")
    public @ResponseBody CommonResponse handle(@RequestBody CommonRequest) {
        // handle
        return commonResponse;
    }
}
```

Is there any solutions to show the real endpoints when I only use "/**" mapping?

**Comment by wu-sheng** [comment]
Nearly all people asking for the wildcard name, you are asking on the other side. If you want to do that, I recommend you remove SpringMVC plugin, which will make the Tomcat back at the first line, then the Container based URL is the real URL you expected.
