### ISSUE TITLE
Grpc server thread pool is full, rejecting the task

### ISSUE THREAD

**Issue by MilkSDF** [apache/skywalking#4824]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1] Question or discussion

### Question
- What do you want to know?

I use mysql as the datasource
![image](https://user-images.githubusercontent.com/7495090/82854175-3daeb200-9f3a-11ea-8d73-633681520991.png)

I want to know how to optimize the mysql, if i should adjust the transaction isolation level.

**Comment by wu-sheng** [comment]
I don't know how to optimize MySQL, sorry. I don't have specialized knowledge about that.
But actually, we don't need transactions in most cases(in 8.0, we don't need in any case), we already put the auto-commit about metrics and trace persistent in the codes already.

**Comment by MilkSDF** [comment]
If too much data leads mysql to lock wait,I use the skywalking 7

**Comment by wu-sheng** [comment]
Could you share which table?

**Comment by MilkSDF** [comment]
I use 'select * from innodb_locks', the lock table is segment.
![image](https://user-images.githubusercontent.com/7495090/82856478-a39e3800-9f40-11ea-9a95-a1186b7e99b3.png)

**Comment by wu-sheng** [comment]
Then it is too much payload to the segment, I think you could set up some sharding tool for segment table. Consider ShardingSphere? cc @tristaZero

**Comment by MilkSDF** [comment]
3Q
