### ISSUE TITLE
Can‘t find package

### ISSUE THREAD

**Issue by finefuture** [apache/skywalking#4828]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x ] Question or discussion

___
### Question
- What do you want to know?
Can‘t find package: **org.apache.skywalking.apm.network.language.agent**

**Comment by kezhenxu94** [comment]
Please read the documentations first before asking question, the package is generated by compiling from the submodule

**Comment by wu-sheng** [comment]
As you know Mandarin, you could learn lesson 2 from here. https://space.bilibili.com/390683219/channel/detail?cid=129405
