### ISSUE TITLE
MQ tracing spand time

### ISSUE THREAD

**Issue by yogaling** [apache/skywalking#4829]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

The MQ tracing spand time is not so easy to understand in the tracking UI , for it calc all the times from provider to consumer。But there is a unstable delay between the MQ Component and the consumer ,that  not belong to the program consumption time 。So Can add an other property record a single span time for only consumer spend？

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I am not following, the consumer span duration is the time about reading the message from MQ server. Wha are you asking?
