### ISSUE TITLE
high cpu consume when big sql execute

### ISSUE THREAD

**Issue by yogaling** [apache/skywalking#4830]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
in Production Environment， we set the agent config with the parameter 
 ：plugin.mysql.trace_sql_parameters= true ；
but when  insert batch records ，the skywalking take  high cpu consume，that make our application slower。Why to build the parameter take  high cpu consume？

**Comment by kezhenxu94** [comment]
@yogaling can you please describe how big the SQL is? Better to provide the complete SQL and parameters to help us diagnose the problem

**Comment by wu-sheng** [comment]
Two things, 
1. Long SQL statements mean more parameters, more parameters mean more interceptions happen, which cause CPU, and more memory means more CPU on GC.
1. Segment in the preparation stage before sending to the backend, it causes more resources(memory and CPU) and when sending happens, more network used.

People used to keep asking for tracing parameter, we always said, don't do that. But as people kept requesting, we added this as an option parameter. So people should consider why we don't put this as default.
