### ISSUE TITLE
When can skywalking support hbase?

### ISSUE THREAD

**Issue by andyhewenhui** [apache/skywalking#4831]
When can skywalking support hbase?

**Comment by wu-sheng** [comment]
HBase for storage? Or agent plugin of hbase-client?

**Comment by andyhewenhui** [comment]
yes , agent plugin of hbase-client

**Comment by wu-sheng** [comment]
The plugin is contributed by the whole community, I don't know who or when or whether there is one will/plan to do this.
In the SkyWalking project, if someone wants to contribute a plugin, we are glad to help with review. But we don't assign tasks.

**Comment by andyhewenhui** [comment]
ok,thanks
