### ISSUE TITLE
No sql statements are captured @ spring boot flowable service

### ISSUE THREAD

**Issue by HanishRamc** [apache/skywalking#4832]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
is there a support for Spring flow-able micro services  
___
### Bug
- Which version of SkyWalking, OS and JRE?
 Red Hat linux 7.4 ,skywalk latest , java 1.8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- have a service which is implemented in spring flowable ,
- when we setup apache skywalk we are able to trace only at entry point level it is not capturing sql statements and detailed trace from the flowable 

kindly advise me how to enable sql statements which are fired as part the request and how to enable further flowable trace 

Regards
Ram
![skywalk1](https://user-images.githubusercontent.com/65835018/82988025-1c79be80-a02b-11ea-97bf-bd14e5e30513.PNG)

**Comment by wu-sheng** [comment]
That is based on your JDBC driver and version. Check the supported list documents. There is no configuration about tracing database access.
