### ISSUE TITLE
tomcat 8.0.53 starts, see skywalking-api.log has 2 warnings

### ISSUE THREAD

**Issue by andyhewenhui** [apache/skywalking#4834]
WARN 2020-05-27 20:27:58:795 localhost-startStop-1 AbstractClassEnhancePluginDefine : enhance class com.mysql.jdbc.Driver by plugin org.apache.skywalking.apm.plugin.jdbc.mysql.v6.define.DriverInstrumentation is not working. Because witness class com.mysql.
cj.api.MysqlConnection is not existed.
WARN 2020-05-27 20:27:58:804 localhost-startStop-1 AbstractClassEnhancePluginDefine : enhance class com.mysql.jdbc.NonRegisteringDriver by plugin org.apache.skywalking.apm.plugin.jdbc.mysql.v6.define.DriverInstrumentation is not working. Because witness cl
ass com.mysql.cj.api.MysqlConnection is not existed.

**Comment by wu-sheng** [comment]
`witness` class exclusion mechanism is for the plugin version match. If the trace works well, you could ignore all these.

**Comment by iberZ** [comment]
11


| |
L13558845976
|
|
邮箱：l13558845976@163.com
|
On 05/27/2020 21:00, 吴晟 Wu Sheng wrote:

witness class exclusion mechanism is for the plugin version match. If the trace works well, you could ignore all these.
