### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [apache/skywalking#4835]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by wu-sheng** [comment]
Hi @thomasrockhu Thanks for reaching us. I just tried the link of Codecov app, but it requires the following permission

- Read access to code
- Read access to administration, issues, members, and metadata
- Read and write access to checks, commit statuses, and pull requests

But, normally, in the Apache, write access could only be granted to Apache committer(human) or PMC(project management committee) controlled bot. It is rare, even not allowed, to do this.

**Comment by wu-sheng** [comment]
The ASF INFRA granted. :) Could see it in the latest updated PR, https://github.com/apache/skywalking/pull/4826

**Comment by wu-sheng** [comment]
FYI @kezhenxu94

**Comment by thomasrockhu** [comment]
Oh amazing! Thanks for the quick turnaround here. Let me know if there's anything I can do to help.

**Comment by leezu** [comment]
@wu-sheng could you share a reference to the INFRA ticket?

**Comment by wu-sheng** [comment]
I didn't send the JIRA ticket, I just request through github. Then I got the approve.

**Comment by leezu** [comment]
Thanks for clarifying. I added a request via https://github.com/apps/codecov/installations/new too
