### ISSUE TITLE
How to set Skywalking SLA  Percent Calculate ignore Some http status Code

### ISSUE THREAD

**Issue by daigong** [apache/skywalking#4854]
- [ ] Question or discussion

___
### Question
- How to set Skywalking SLA  Percent Calculate ignore Some http status Code
I found sla config in /config/official_analysis.oal  ,

    service_sla = from(Service.*).percent(status == true);

how to set sla percent ignore http status code 404 、 422 、 595 and all

**Comment by wu-sheng** [comment]
You have to change code to do that. The status is reported from the plugin level.

**Comment by daigong** [comment]
Which module or class ?  could you help to give more information? 3q

**Comment by wu-sheng** [comment]
Plugin codes, I don't know which plugin you are using related to this.

**Comment by daigong** [comment]
I need ensure which Plugin in

https://github.com/apache/skywalking/tree/master/apm-sniffer/apm-sdk-plugin

right？ 3Q

**Comment by wu-sheng** [comment]
Or optional plugin, bootstrap plugin, application toolkit. I don't know. There are many plugins and interaction ways. So, only you could know which one.

**Comment by daigong** [comment]
Many Thanks for Your Attention and Patience
