### ISSUE TITLE
Incorrect state in link tracing: ERROR in one stage but whole stage link tracing shows SUCCESS

### ISSUE THREAD

**Issue by regardfs** [apache/skywalking#4861]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug
___
### Bug
- Which version of SkyWalking, OS and JRE?
> OS: CentOs 7.5
> JDK: jdk8u 241
> SkyWalking: 6.6.0-es7

- Which company or project?

- What happen?
![image](https://user-images.githubusercontent.com/8295227/83833438-8cb8cc00-a71e-11ea-9b73-bb6a7ad1c77d.png)
![image](https://user-images.githubusercontent.com/8295227/83833447-8fb3bc80-a71e-11ea-8e71-962364f5aae7.png)
when searching the trace link with the endpoint of the facade which state is `SUCCESS`,  I found that there is an error in this link, so the final state should be `ERROR`, I am a little confused about this.
___
### Requirement or improvement
- trace link should be set as state of `ERROR` within this condition;
- better if skywalking could print out the `ERROR` Jstack

**Comment by wu-sheng** [comment]
What is error jstack? What is related to SkyWalking?

**Comment by regardfs** [comment]
> What is error jstack? What is related to SkyWalking?

I mean, the threaddump of the error, nevermind, It is a good to have function, the main problem is the misstate in link tracing result

**Comment by wu-sheng** [comment]
@Fine08finCould you take a look how the UI visualize the error status?

**Comment by regardfs** [comment]
CC

**Comment by Fine0830** [comment]
@regardfs Now, UI according to `isError` from server data to visualize trace list. I didn't find this error case. Could you check if your data that `isError` is true but logs are errors is dirty? cc: @wu-sheng

**Comment by wu-sheng** [comment]
@regardfs If you could the trace query result(Graphql response), it would be helpful to identify the issue.

**Comment by Fine0830** [comment]
Probably there is another possibility that @regardfs  misunderstand the trace table. Now the trace table doesn't show error status,  like trace list. If it's necessary, I can add this. @wu-sheng

**Comment by wu-sheng** [comment]
Oh, I think that is the case, let's add it in 8.1.0
