### ISSUE TITLE
org.apache.skywalking.apm.network.common.v3

### ISSUE THREAD

**Issue by wangsai0806** [apache/skywalking#4864]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
程序包org.apache.skywalking.apm.network.common.v3不存在

真的没有办法了，按照文档编译一直失败。

确认找不到这个jar包，我看到相同的issues已经有好些了，请不要回复看文档了，好吗？
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wangsai0806** [comment]
环境：windows
apache-maven：3.6.0
npm：6.13.4
node：10.16.0

**Comment by HackerRookie** [comment]
![image](https://user-images.githubusercontent.com/1912153/83842905-7dde1380-a736-11ea-805d-77035dea6054.png)
## Setup your IntelliJ IDEA
**NOTICE**: If you clone the codes from GitHub, please make sure that you had finished step 1 to 3 in section **[Build from GitHub](#build-from-github)**, if you download the source codes from the official website of SkyWalking, please make sure that you had followed the steps in section **[Build from Apache source code release](#build-from-apache-source-code-release)**.

1. Import the project as a maven project
1. Run `./mvnw compile -Dmaven.test.skip=true` to compile project and generate source codes. Because we use gRPC and protobuf.
1. Set **Generated Source Codes** folders.
    * `grpc-java` and `java` folders in **apm-protocol/apm-network/target/generated-sources/protobuf**
    * `grpc-java` and `java` folders in **oap-server/server-core/target/generated-sources/protobuf**
    * `grpc-java` and `java` folders in **oap-server/server-receiver-plugin/receiver-proto/target/generated-sources/protobuf**
    * `grpc-java` and `java` folders in **oap-server/exporter/target/generated-sources/protobuf**
    * `grpc-java` and `java` folders in **oap-server/server-configuration/grpc-configuration-sync/target/generated-sources/protobuf**
    * `antlr4` folder in **oap-server/oal-grammar/target/generated-sources**

**Comment by wu-sheng** [comment]
English only. Make sure you download the source code though the right way. Git clone or website only.

**Comment by wangsai0806** [comment]
分享一下我可能出错的原因：
1.先克隆的项目，然后把项目导入到IDEA中，加载完成后我激活了“Maven自动导入功能”。
   IDEA开始处理mvn自动导入。
2.然后我执行的`git submodule init`  和 `git submodule update`
3.我运行着两个git命令，控制台无任何输出
4.最后执行 `mvn clean package -DskipTests`就报错了，提示找不到jar包

我现在重新clone项目，导入IDEA的时候，选择不启动IDEA的“Maven自动导入功能”后，就运行成功了。
希望可以帮助部分人。

**Comment by goodjuan-xj** [comment]
您说的选择不启动IDEA的“Maven自动导入功能”，是指取消如下设置吗？我按照您说的操作，还是报错，要崩溃了┭┮﹏┭┮
![image](https://user-images.githubusercontent.com/55343457/102571679-05183500-4125-11eb-804a-dc25178baa86.png)

**Comment by wangsai0806** [comment]
> 您说的选择不启动IDEA的“ Maven自动导入功能”，是指取消如下设置吗？我按照您说的操作，还是报错，要崩溃了┭┮﹏┭┮
> ![图片](https://user-images.githubusercontent.com/55343457/102571679-05183500-4125-11eb-804a-dc25178baa86.png)

你执行`git submodule init `和`git submodule update`的时候，控制台有输出内容吗？

**Comment by YczYanchengzhe** [comment]
I suspect you are caused by the fact that the proto package has not been downloaded, you can try to download again, with a git address: git@github.com:apache/skywalking-data-collect-protocol.git

**Comment by enderwsp** [comment]
> > 您说的选择不启动IDEA的“ Maven自动导入功能”，是指取消如下设置吗？我按照您说的操作，还是报错，要崩溃了┭┮﹏┭┮
> > ![图片](https://user-images.githubusercontent.com/55343457/102571679-05183500-4125-11eb-804a-dc25178baa86.png)
> 
> 你执行`git submodule init `和`git submodule update`的时候，控制台有输出内容吗？

和IDE的设置没有关联，要实地按照操作说明来

会有遇到问题，可参考 https://gitee.com/vic_1_499636487/zero2nine/tree/master/skywalking

**Comment by codexinfeng** [comment]
If you download in zip ,all  proto files do not exist ,you should download proto files again and put them into /apm-protocol/apm-network/src/main/proto/    and run ./mvnw compile -Dmaven.test.skip=true 
![111111111111](https://user-images.githubusercontent.com/22891341/119131246-cd167480-ba6b-11eb-8463-83103de77c44.png)

![2222222](https://user-images.githubusercontent.com/22891341/119131254-ce47a180-ba6b-11eb-8a4d-46bf486e1278.png)

![33333333333](https://user-images.githubusercontent.com/22891341/119131306-dc95bd80-ba6b-11eb-9aa7-c83fdd248b62.png)

**Comment by wu-sheng** [comment]
Don't download there. All ASF codes should be download through Git clone or our website. Don't download from any other places.

**Comment by davidricardo1026** [comment]
maven indeed will happen some strange quetions,suggest alt to gradle.it will more stable

**Comment by wu-sheng** [comment]
> maven indeed will happen some strange quetions,suggest alt to gradle.it will more stable

Please don't misguide people, there is nothing related to Maven V.S. gradle.

**Comment by andotorg** [comment]
This problem is because the files in proto in the network module of skywalking project are stored separately in another project. It is not allowed to clone or download the source code of skywalking alone. You need to clone the corresponding Apache/skywalking data collect protocol project or download it to skywalking/apm-protocol/apm-network/src/main/proto directory

**Comment by 393189720** [comment]
> This problem is because the files in proto in the network module of skywalking project are stored separately in another project. It is not allowed to clone or download the source code of skywalking alone. You need to clone the corresponding Apache/skywalking data collect protocol project or download it to skywalking/apm-protocol/apm-network/src/main/proto directory

then,how to?
