### ISSUE TITLE
How to install Apache skywalking in centos machine? 

### ISSUE THREAD

**Issue by subusharma2001** [apache/skywalking#4869]
Hi,

I want to install apache skywalking tool in my environment where my application is in nodejs(frontend),tomcat(backend) and databases as oracle.

I have tried with pinpoint tool but they are not supporting the Nodejs so i'm looking for this tool as potential of my application.
Currently i'm using kubernetes deployment for my application.
I want to install skywalking on one separate machine and installing/associating agent in my kubernetes deployed application for tracing.
Could you please help me to install skywalking? 
Any installation guide which i can follow to install skywalking?

Thank you.

**Comment by wu-sheng** [comment]
The nodejs agent has its own tepo, out of ASF. Lrase check there.
The backend doesn't require OS, as an Java application. We have links for doc for quick start in the github readme and website.
