### ISSUE TITLE
When the redis operation is abnormal, the span information is lost

### ISSUE THREAD

**Issue by hellojd2018** [apache/skywalking#4872]
### Bug
- env: SkyWalking：6.6.0； OS:linux 7。my project user jedis-2.9.0
 When the redis operation is abnormal, the span information is lost。 See the specific picture。
Missing error.kind，message,stack...
![redis_issue](https://user-images.githubusercontent.com/50145526/83991811-8cb80680-a980-11ea-8811-4fbadc5e65a5.png)

**Comment by wu-sheng** [comment]
This seems an enhancement. Welcome to learn and contribute.

**Comment by jackiepon31** [comment]
> ### Bug
> * env: SkyWalking：6.6.0； OS:linux 7。my project user jedis-2.9.0
>   When the redis operation is abnormal, the span information is lost。 See the specific picture。
>   Missing error.kind，message,stack...
>   ![redis_issue](https://user-images.githubusercontent.com/50145526/83991811-8cb80680-a980-11ea-8811-4fbadc5e65a5.png)

what do you mean by abnormal, did your redis transactions really throw out any Exception?
As we can check from InstMethodsInterWithOverrideArgs ，SKywalking can be sure of  catching any exceptions extends from throwable.
Can you describe it with more details ?

**Comment by wu-sheng** [comment]
No update in 15 days, closing.
