### ISSUE TITLE
Polish UI for 8.0.0 final release

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4877]
UI is closing to the final version, in the last local tests, I found the following points
1. The instance and endpoint pages in the topology, could not be edited like the dashboard. This makes the customization a little hard. Please provide it.
1. The instance and endpoint pages in the topology is in appending mode. This is wrong, it should be replacement mode.
1. The new dashboard adding is not working. 
![image](https://user-images.githubusercontent.com/5441976/84038950-214b5480-a9d3-11ea-8d12-303167d9bb23.png)
1. The topology page should select `all services` in default if no local group. 

Other polish and enhancement would move to 8.1.0 release, I will submit several new issues to track those.

**Comment by wu-sheng** [comment]
One topo, add button for topology dashboard.

**Comment by wu-sheng** [comment]
I think you left this.

![image](https://user-images.githubusercontent.com/5441976/84150019-e0ffdb00-aa93-11ea-9e46-51eb3320f420.png)

**Comment by wu-sheng** [comment]
And I think the other thing is, when I created a dashboard, seems you clone the template from the backend. For all creations, I think they should be empty only.

**Comment by wu-sheng** [comment]
What I heart from @hanahmily there are two bugs.

1. UI doesn't match the Labeled in the labeled value query, it is likely referring the order, which is not right. Please recheck. The order of response value may not be as same as the request. In response dataset, it includes the labels.
1. Heatmap doesn't use the bucket `min` and `max` to indicate its range, it is likely using the `index * 100`?(guessing). Please recheck and correct this.

Gao, if you have more details, please add here.

**Comment by hanahmily** [comment]
The Heatmap chart 

> What I heart from @hanahmily there are two bugs.
> 
> 1. UI doesn't match the Labeled in the labeled value query, it is likely referring the order, which is not right. Please recheck. The order of response value may not be as same as the request. In response dataset, it includes the labels.

It's a bug from OAP graphql service. 

> 2. Heatmap doesn't use the bucket `min` and `max` to indicate its range, it is likely using the `index * 100`?(guessing). Please recheck and correct this.
The data from OAP
```json
{"data":{"readHeatMap":{"values":[{"id":"202006091345_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,1,20,10,0]},{"id":"202006091346_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091347_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091348_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091349_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091350_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091351_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091352_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091353_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091354_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091355_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091356_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091357_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091358_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091359_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,10,0]},{"id":"202006091400_b2FwLXNlcnZlcg==.1_bG9jYWxob3N0OjEyMzQ=","values":[0,0,0,0,0,0,0,0,0,0,0,0,21,11,0]}],"buckets":[{"min":"0","max":"5"},{"min":"5","max":"10"},{"min":"10","max":"25"},{"min":"25","max":"50"},{"min":"50","max":"75"},{"min":"75","max":"100"},{"min":"100","max":"250"},{"min":"250","max":"500"},{"min":"500","max":"750"},{"min":"750","max":"1000"},{"min":"1000","max":"2500"},{"min":"2500","max":"5000"},{"min":"5000","max":"7500"},{"min":"7500","max":"10000"},{"min":"10000","max":"infinite+"}]}}}
```

![image](https://user-images.githubusercontent.com/1960537/84157393-45736800-aa9d-11ea-8265-9fae2a96b334.png)

**Comment by wu-sheng** [comment]
> It's a bug from OAP graphql service.

I am not sure how this issue comes from. The issue we fixed yesterday, is because of v1 metrics query. But the current UI is using the v2 implementation. @Fine0830 Could you recheck this? Whether UI is using the label name to match result dataset.

**Comment by hanahmily** [comment]
There's a mismatch between labels in pencentile chart. You can find `90` and `50` exchange their values as below. 
```json
{"data":{"readLabeledMetricsValues":[{"label":"99","values":{"values":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":7500},{"value":7500},{"value":7500},{"value":7500},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":7500},{"value":7500},{"value":5000},{"value":5000},{"value":5000}]}},{"label":"70","values":{"values":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":5000},{"value":7500},{"value":7500},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":7500},{"value":5000},{"value":5000},{"value":5000}]}},{"label":"50","values":{"values":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000}]}},{"label":"90","values":{"values":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":7500},{"value":7500},{"value":7500},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":5000},{"value":7500},{"value":5000},{"value":5000},{"value":5000}]}}]}}
```

![image](https://user-images.githubusercontent.com/1960537/84222853-34614000-ab0b-11ea-87d5-643580e9a1a8.png)

**Comment by wu-sheng** [comment]
After https://github.com/apache/skywalking-rocketbot-ui/pull/311, only find the instance selector and topology instance page are not working in some cases, @Fine0830 Please recheck. Look like there are some conflicts there.
