### ISSUE TITLE
[plugin/lettuce] sometimes trace doesn‘t show component type

### ISSUE THREAD

**Issue by dagmom** [apache/skywalking#4879]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
8, macos, jre8

___
![image](https://user-images.githubusercontent.com/43675197/84052238-df2a0f00-a9e2-11ea-9ad9-1ab2c66305e5.png)

**Comment by wu-sheng** [comment]
Check the interceptor codes. Maybe they miss some set(s). We don't have any special process about this in the agent core and backend.

**Comment by jackiepon31** [comment]
yep, i've checked the inteceptors under the luttuce plugin , they really did miss some sets on the local spans. Maybe we can add some on that and update the plugin。

**Comment by wu-sheng** [comment]
Please send a pull request to fix them.
