### ISSUE TITLE
Provide plugin for ShardingSphere 4.1.0

### ISSUE THREAD

**Issue by yu199195** [apache/skywalking#4885]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

Provide plugin for ShardingSphere 4.1.0 of which the package name is different from 4.0.0.

**Comment by wu-sheng** [comment]
Duplicated. Please request to ShardingSphere project.

**Comment by yu199195** [comment]
@wu-sheng hi，i work on shardingSphere, 4.1.0 Has been released, but the interface has changed,
so well should Provide plugin for ShardingSphere 4.1.0

**Comment by wu-sheng** [comment]
I think the plugin is missing supports from 4-RC1. Not only 4.1.0. @yu199195

**Comment by yu199195** [comment]
4.0.0-RC1 ~~4.0.0-RC3 have already provided。 @wu-sheng

**Comment by wu-sheng** [comment]
From SkyWalking doc, it doesn't say so.
