### ISSUE TITLE
I want to see metrics of springboot application on skywalking UI dashboard. I downloaded v7.0.0. of skywaking and i can see the dashboard.Can you please guide me how to integrate spring boot application?

### ISSUE THREAD

**Issue by cnu753718835-seelam** [apache/skywalking#4886]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The agent setup doc is provided.

**Comment by cnu753718835-seelam** [comment]
i followed the below link but i am not able to see my application on Ui dashboard-
https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md

First i changed application name and my spring boot application is also running on port 11800 .I started my application followng this command:  java -javaagent:/path/to/skywalking-agent/skywalking-agent.jar -jar yourApp.jar
