### ISSUE TITLE
Do you have plan to support hikari connection pool?

### ISSUE THREAD

**Issue by gogangipark** [apache/skywalking#4888]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [X ] Requirement
- [ ] Feature or performance improvement

___
I have used spring boot 2.1 at my service.
Recently, I have tried to apply at my service.

SkyWalking doesn't monitor hikari connection pool?

Is there any way to monitor hikari connection pool at skywalking

TIA.

**Comment by wu-sheng** [comment]
Our recommendation is, if you want to do this, we are welcome the contributions. The monitoring things are countless, the core team is only providing helping and reviewing when you try to contribute. You are a part of the community, please take actions.
