### ISSUE TITLE
Agent supports service invocation takes longer than threshold sampling

### ISSUE THREAD

**Issue by PrettyJerry** [apache/skywalking#4901]
- Why do you submit this issue?
**- [ ] Feature or performance improvement**

### Question

Whether the SkyWalking Agent sampling mechanism supports service invocation time  exceeding the specified threshold in order to reduce data transmission and storage.
This feature is of great value in a real production environment.

For example, the service invocation is not sampled until time cost more than 1 second

**Comment by wu-sheng** [comment]
No, because that trace will be broken. You could consider to add this sampling rule at the backend.
