### ISSUE TITLE
Strongly recommend Agent supports sampling whether the service invocation time exceeds the threshold

### ISSUE THREAD

**Issue by PrettyJerry** [apache/skywalking#4903]
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Whether the SkyWalking Agent sampling mechanism supports service invocation time exceeding the specified threshold in order to reduce data transmission and storage.
This feature is of great value in a real production environment.
For example,  Sampling is done only if the service invocation takes longer than 1 second.**

**Comment by wu-sheng** [comment]
Skywalking focuses as an APM, not tracing only. Your idea will make most metrics gone or pointless.
