### ISSUE TITLE
one url has two endpoint ?

### ISSUE THREAD

**Issue by githuyong** [apache/skywalking#4907]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- like #3675,  [https://github.com/apache/skywalking/issues/3675](url)
  skywalking7.0 , springboot1.5.8 ,  app.war is put in external tomcat deploy。

  My URL is http://127.0.0.1:8082/my/v2/ad  。application context is "**my**", and endpoint is "**/v2/ad**" and "**{POST}/v2/ad**"

 my java code like this
`@RequestMapping(path = "/v2/ad", method = {RequestMethod.POST})`

![捕获](https://user-images.githubusercontent.com/19883408/84372345-8e4a2e80-ac0d-11ea-9251-1e3d652e783b.PNG)
![捕获2](https://user-images.githubusercontent.com/19883408/84372352-9013f200-ac0d-11ea-821d-2903cf435e16.PNG)
![捕获3](https://user-images.githubusercontent.com/19883408/84372360-91451f00-ac0d-11ea-991a-21eea1b99a14.PNG)

**Comment by wu-sheng** [comment]
remove the http middleware plugin. Maybe webflux or some async middleware.

**Comment by githuyong** [comment]
I remove all http middleware  is not work。
I find a regular :fisrt request is {POST}/v2/*, and second request is /v2/* 
@wu-sheng

**Comment by githuyong** [comment]
this is my plugin 
![捕获4](https://user-images.githubusercontent.com/19883408/84375720-9193e900-ac12-11ea-857a-9550260e4e66.PNG)

**Comment by wu-sheng** [comment]
Don't know why. Not happening in my place. Sorry.

**Comment by BFergerson** [comment]
Found cause of issue. Will contribute fix.
