### ISSUE TITLE
关于skywalking 聚合metrics疑问

### ISSUE THREAD

**Issue by Joseph-xie** [apache/skywalking#4918]
请教开发同学一个问题：
由于英语不是很好，为了把问题描述清楚，所以使用中文描述。
想咨询你的问题是：
对于metrics的统计，比如 endpoint_cpm这个，
背景是 现在10个实例的agent都 在 同一分钟 搜集了同一个接口的 数据，其中5个实例把这个数据
发送到backend的实例a上，另外5个自己采集的数据发送到backend的实例b上，我现在知道在backend的
内部有进行数据的聚合，比如实例a里面会聚合a上的这5个请求，假设调用metrics的calucate方法值为5，
然后b上计算结果也是5，然后实例a和实例b同时写到es里面那这时候这个值是不准确的对吧，
正确的值应该是实例a和实例b相加的为10，由于实例a和实例b分别进行update，所以最终是其中的一个值即5。
关于这一点我现在是这样理解的，所以觉得会有问题。
所以现在请教您这一个问题。谢谢！

**Comment by wu-sheng** [comment]
English is only acceptable. If you want to know how metrics aggregated, read the codes.

**Comment by Joseph-xie** [comment]
> English is only acceptable. If you want to know how metrics aggregated, read the codes.

I have readed the codes,this question is produced by the code! but i thing there is a problem as descriped at last comment.

**Comment by wu-sheng** [comment]
My guessing, you didn't set up the cluster mode and coordinator. The documents indicate that already.

**Comment by Joseph-xie** [comment]
that's the key,thx!
