### ISSUE TITLE
can't see metrics of springboot application

### ISSUE THREAD

**Issue by cnu753718835-seelam** [apache/skywalking#4919]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Requirement
I want to see the metrics of my springboot java  application.I started apache skywalking  and running my application using below command-
java -javaagent:C:/Users/C-PWM3/Softwares/apache-skywalking-apm-bin/agent/skywalking-agent.jar -Dskywalking.agent.service_name=app1 -Dskywalking.collector.backend_service=localhost:11800 -jar mypp.jar
 
when i hit endpoint i can see endpoint count in skywalking UI dashboard but cant see any metrics or service name.Please guide.

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read doc carefully. We told at the first line, set up time and time zone right.
