### ISSUE TITLE
Unexpected behaviours of ShardingSphere plugin tests.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4920]
Hi @yu199195 
As you known, when I was upgrading the version from 8.0.0 to 8.1.0, the ShardingSphere test cases keep failing. I don't know why. Our PMC @dmsolr did local tests too, they passed.
But, according to they can't pass on the GitHub actions, I have to remove them in #4916. I hope you could optimize the cases, and add them back. As we really need all plugins are covered by these tests.

**Comment by yu199195** [comment]
ok，i will check it。

**Comment by wu-sheng** [comment]
With the latest feedback, the issue is caused by the `NO suitable witness class`. Because of this, plugins with different versions have conflicts. Need to fix.
