### ISSUE TITLE
[NIGNX-LUA] create a protocol v2 tag please

### ISSUE THREAD

**Issue by RelicOfTesla** [apache/skywalking#4922]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___

https://github.com/apache/skywalking-nginx-lua
this latest version is use v3 protocol+example...
and docker-hub use v2 protocol.....not support v3...
please tip it..and create git tag/branch

**Comment by wu-sheng** [comment]
The 0.1.0 is for v2 protocol. V3 agent has not been released.

**Comment by RelicOfTesla** [comment]
the code only used v3 protocol  in master branch 
https://github.com/apache/skywalking-nginx-lua/blob/master/lib/skywalking/client.lua#L83
you can see :
```
 local http = require('resty.http')
    local httpc = http.new()
    local res, err = httpc:request_uri(backend_http_uri .. '/v3/management/reportProperties', {
     
```

**Comment by wu-sheng** [comment]
Yes. So? I said only 0.1.0 tag for v2 protocol.

**Comment by RelicOfTesla** [comment]
ok.guy.
