### ISSUE TITLE
[CLI] Adopt new query protocl protocol

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#4923]
With new query protocol providing the name-based query, CLI could provide the direct queries for every kind of metrics easily. We should adopt the new in the CLI, which should not be a big change. Also, the old ones could be removed.

**Comment by kezhenxu94** [comment]
Fair enough.

FYI @fgksgf , as you're going to add a dashboard command in the CLI, please take a look at the latest query protocol and the [live demo](http://122.112.182.72:8080/), we'll adopt the new query protocol in the 0.3.0

**Comment by fgksgf** [comment]
> Fair enough.
> 
> FYI @fgksgf , as you're going to add a dashboard command in the CLI, please take a look at the latest query protocol and the [live demo](http://122.112.182.72:8080/), we'll adopt the new query protocol in the 0.3.0

OK
