### ISSUE TITLE
ifind a ui bug

### ISSUE THREAD

**Issue by seawavexhb** [apache/skywalking#4926]

**Comment by seawavexhb** [comment]
拓扑图页面，选择一个service后oap报{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: {\n  \"bool\" : {\n    \"must\" : [\n      {\n        \"range\" : {\n          \"time_bucket\" : {\n            \"from\" : 20200614,\n            \"to\" : 20200616,\n            \"include_lower\" : true,\n            \"include_upper\" : true,\n            \"boost\" : 1.0\n          }\n        }\n      },\n      {\n        \"bool\" : {\n          \"should\" : [\n            {\n              \"term\" : {\n                \"source_service_id\" : {\n                  \"value\" : \"dGVzdHN3.1\",\n                  \"boost\" : 1.0\n                }\n              }\n            },\n            {\n              \"term\" : {\n                \"dest_service_id\" : {\n                  \"value\" : \"dGVzdHN3.1\",\n                  \"boost\" : 1.0\n                }\n              }\n            }\n          ],\n          \"adjust_pure_negative\" : true,\n          \"boost\" : 1.0\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}","index_uuid":"o4A-friFS42djkkCN4m3uQ","index":"ccs_service_relation_client_side-20200615"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"ccs_service_relation_client_side-20200615","node":"m54H12ipSuWrX4uXWdoeeA","reason":{"type":"query_shard_exception","reason":"failed to create query: {\n  \"bool\" : {\n    \"must\" : [\n      {\n        \"range\" : {\n          \"time_bucket\" : {\n            \"from\" : 20200614,\n            \"to\" : 20200616,\n            \"include_lower\" : true,\n            \"include_upper\" : true,\n            \"boost\" : 1.0\n          }\n        }\n      },\n      {\n        \"bool\" : {\n          \"should\" : [\n            {\n              \"term\" : {\n                \"source_service_id\" : {\n                  \"value\" : \"dGVzdHN3.1\",\n                  \"boost\" : 1.0\n                }\n              }\n            },\n            {\n              \"term\" : {\n                \"dest_service_id\" : {\n                  \"value\" : \"dGVzdHN3.1\",\n                  \"boost\" : 1.0\n                }\n              }\n            }\n          ],\n          \"adjust_pure_negative\" : true,\n          \"boost\" : 1.0\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}","index_uuid":"o4A-friFS42djkkCN4m3uQ","index":"ccs_service_relation_client_side-20200615","caused_by":{"type":"number_format_exception","reason":"For input string: \"dGVzdHN3.1\""}}}]},"status":400}

我使用的是es6，看了一下es中 xxxxx_service_relation_client_side-yyyymmdd这个索引的_mapping中定义的字段dest_service_id和source_service_id都是integer类型

**Comment by wu-sheng** [comment]
The upgrade requires you to remove the ES data.

**Comment by wu-sheng** [comment]
English only.

**Comment by seawavexhb** [comment]
> The upgrade requires you to remove the ES data.

I delete all the indexes which created by skywalking then restart the es cluster. when I restart the oapServer,I find the log show creating indexes is right, in the _mapping, these columns was 'keyword' type. but I get the '_mapping' endpoint from es , it is still 'integer'. 
Hope you can help me , I guess it will be ok tomorrow, because the index name is endwith a date, but I really want to know , thank you . 
My poor English god ...

**Comment by wu-sheng** [comment]
ES data type is defined by data. Make sure you have the right OAP connected. Besides the index, there are es template.

**Comment by seawavexhb** [comment]
> ES data type is defined by data. Make sure you have the right OAP connected. Besides the index, there are es template.

Thank you very much.
It was problemed by index template，when I deleted all the index templates，It can be working.
I used elasticsearch for a shot time，sorry to disturbing you.
