### ISSUE TITLE
 Using Nacos as the dynamic configuration center，application.yml exists some problem

### ISSUE THREAD

**Issue by HelloHaiNG** [apache/skywalking#4928]
When using Nacos as the dynamic configuration center ，the application.yml configuration file, don't you need the dataId parameter?
if the dataId parameter do not need, then skywalking how to can know which configuration file in nacos config center is used to the alarm dynamic config?
![sw](https://user-images.githubusercontent.com/33769220/84643773-e005f800-af30-11ea-9239-05750baa75db.png)
![nacos](https://user-images.githubusercontent.com/33769220/84643883-fe6bf380-af30-11ea-8d0e-dda95a0dd8d1.png)

**Comment by wu-sheng** [comment]
Nacos has been removed since 8.0.0. If you are wondering some details, read the codes. You may know Nacos API more than us.

**Comment by HelloHaiNG** [comment]
> Nacos has been removed since 8.0.0. If you are wondering some details, read the codes. You may know Nacos API more than us.

the same question. if using apollo as  the dynamic configuration center ，the application.yml configuration file, don't we  need to specify namespace? if we need not, then skywalking how to can know which namespace in apollo config center is used to the alarm dynamic config?

**Comment by wu-sheng** [comment]
Read the codes. Most of us are noy using either Nacos or Appollo. Maybe you need to send a pull request to enhance.

**Comment by HelloHaiNG** [comment]
> Read the codes. Most of us are not using either Nacos or Appollo. Maybe you need to send a pull request to enhance.

Dynamic configuration is needed because we often change the alarm rule configuration, but don't want to restart SkyWalking

**Comment by wu-sheng** [comment]
I am not sure what you are saying.
