### ISSUE TITLE
skywalking6.6版本使用nacos配置中心做动态告警规则配置相关问题

### ISSUE THREAD

**Issue by HelloHaiNG** [apache/skywalking#4933]
application.yml如下配置：
![application](https://user-images.githubusercontent.com/33769220/84751287-f83c4c80-afee-11ea-8aea-5c305d17aecc.png)
nacos配置中心配置如下：
![nacos-config](https://user-images.githubusercontent.com/33769220/84751382-1609b180-afef-11ea-815a-2153d8957b0d.png)
nacos告警规则如下：
rules:
  service_resp_time_rule:
    metrics-name: service_resp_time
    op: ">"
    threshold: 1000
    period: 10
    count: 3
    silence-period: 5
    message: Response time of service {name} is more than 1000ms in 3 minutes of last 10 minutes.
webhooks:
  - http://10.xx.xx.xx:8030/alarm
经过如上配置之后，发现application.yml中nacos配置不生效（即触发了告警的情况之下，并没有走webhooks）

**Comment by wu-sheng** [comment]
English only, and make the format clear. BTW, the Nacos has been removed.

**Comment by HelloHaiNG** [comment]
> English only, and make the format clear. BTW, the Nacos has been removed.

i know nacos has been removed. but now i use skywalking on 6.6 release

**Comment by wu-sheng** [comment]
This is not a complex feature, you could easily debug. There are only < 10 classes.

**Comment by HelloHaiNG** [comment]
> This is not a complex feature, you could easily debug. There are only < 10 classes.

you mean that nacos yet works in 6.6 version?

**Comment by wu-sheng** [comment]
I don't know. There are 200+ contributors working on this project, some of them contributed this, and it passed the tests.

**Comment by HelloHaiNG** [comment]
> I don't know. There are 200+ contributors working on this project, some of them contributed this, and it passed the tests.

ok ,thanks
