### ISSUE TITLE
skywalking-python startup with django not working

### ISSUE THREAD

**Issue by chestarss** [apache/skywalking#4934]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 8.0
skywalking-python  make install by HEAD/4c2109fda41

- What happen?

hooks.py 
```python
from skywalking import agent, config

def one_time_startup():
    config.init(collector='trace.domain.name:11800', service='mydjangoprj')
    agent.start()
```

urls.py 
```python
from mydjangoprj.hooks import one_time_startup
...
urlpatterns.append(url(r'test/endpoint', views.TestView.as_view()))
one_time_startup()
```
views.py  call requests
```python
...
class TestView(View):
    def post(self, request):
          ...
          resp = requests.get(url)
          ....
```

```shell
curl http://127.0.0.1:8000/test/endpoint/
```
```python
    ...
    resp = requests.get(url)
  File "/home/admin/.virtualenvs/opssaas/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/admin/.virtualenvs/opssaas/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/admin/.virtualenvs/opssaas/lib/python3.6/site-packages/skywalking_python-0.1.1-py3.6.egg/skywalking/plugins/sw_requests/__init__.py", line 44, in _sw_request
    context = get_context()
  File "/home/admin/.virtualenvs/opssaas/lib/python3.6/site-packages/skywalking_python-0.1.1-py3.6.egg/skywalking/trace/context/__init__.py", line 123, in get_context
    _thread_local.context = _thread_local.context or (SpanContext() if agent.connected() else NoopContext())
AttributeError: '_thread._local' object has no attribute 'context'

```

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think there is no djanggo plugin?

**Comment by chestarss** [comment]
我临时用这个修复后可以用，不知道是什么原因文件上面的代码里的_thread_local.context赋值没有生效。
 skywalking/trace/context/__init__.py 
```python
def get_context() -> SpanContext:
    try:
        tmp_context = _thread_local.context
    except:
        tmp_context = None
    _thread_local.context = tmp_context or (SpanContext() if agent.connected() else NoopContext())
```

**Comment by kezhenxu94** [comment]
From your log `AttributeError: '_thread._local' object has no attribute 'context'`, I assume this issue is Django-specific because the name `_thread._local` is unexpected by the SkyWalking agent, and it behaves the same as when the assignment `_thread_local.context = None` is absent, anyway, I'd like to adjust the assignment into the `get_context` function, which should be more fault tolerant, BTW, if you're willing to open a PR, it's highly appreciated @chestarss
