### ISSUE TITLE
why 8.0 not support nacos?

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#4937]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
7.0 support nacos，but 8.0 not support nacos
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by killGC** [comment]
if i use nacos in 7.0，when i update to 8.0，how to use nacos

**Comment by wu-sheng** [comment]
I am afraid you can't. This is the community decision, read this, https://github.com/alibaba/nacos/issues/2842.

**Comment by killGC** [comment]
8.0 OAP cluster not support nacos，because i see document not about nacos，and i try nacos as OAP cluster register-center，but fail
