### ISSUE TITLE
use 'make -f Makefile install' install skywalking-python occurred error?

### ISSUE THREAD

**Issue by yue-chao** [apache/skywalking#4962]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ *] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
it's  Environmental error  ？
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking-python (#21) pyhton3.7 
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Error prompt：python3 -m grpc_tools.protoc --version || python3 -m pip install grpcio-tools
	                 python3 -m grpc_tools.protoc -I protocol --python_out=. --grpc_python_out=. protocol/**/*.proto
                         Could not make proto path relative: protocol/**/*.proto: No such file or directory
                        make: ***[gen] Error 1
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

Why did this error occur? The old version was installed successfully without any errors. Did me delete critical files when deleting older versions?

**Comment by kezhenxu94** [comment]
@yue-chao it's my fault to miss one step in the docs, but please clone the submodule first before running `make install`

**Comment by kezhenxu94** [comment]
To be clear, run `git submodule update --init` before `make install`

**Comment by yue-chao** [comment]
Thank you. It's done

**Comment by yue-chao** [comment]
thank you,this problem is solved



At 2020-06-23 14:53:48, "kezhenxu94" <notifications@github.com> wrote:

To be clear, run git submodule update --init before make install
