### ISSUE TITLE
可否计划开发以下需求，谢谢

### ISSUE THREAD

**Issue by suntianxian** [apache/skywalking#4963]
1.可否增加一个后台登录页面
2.可否实现一些可视化的 报警配置,例如报警组->报警人->报警策略 ,支持邮件发送与微信机器人，阿里钉钉的发送
3.java版本的监控，可否考虑使用maven进行集成

**Comment by wu-sheng** [comment]
If you want something, pleae contribute. We don't do like this in the open source.
