### ISSUE TITLE
Why index endpoint_cpm remove attribute instance_id?

### ISSUE THREAD

**Issue by Dongzai1005** [apache/skywalking#4966]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- skywalking version 8.0.1
- Why index endpoint_cpm remove attribute instance_id?
- Is it possible to add instance_id in index endpoint_cpm through configuration method/oal language?

**Comment by wu-sheng** [comment]
In the 8.x, there is no register, so no id. All information has been encoded in the role id already.
