### ISSUE TITLE
can sampleRate configuration of 'oap trace receiver ' be changed by dynamic configuration center?

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#4968]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
can sampleRate configuration of 'oap trace receiver ' be changed by dynamic configuration center?
___
### Bug
- Which version of SkyWalking, OS and JRE?
   skywalking7.0，linux，jdk8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is not hard to change, welcome to contribute.

**Comment by killGC** [comment]
ok,i will try to do it
