### ISSUE TITLE
how to collect http body params

### ISSUE THREAD

**Issue by cxbiao** [apache/skywalking#4969]
My Skywalking version is 7.0.0
I know plugin.springmvc.collect_http_params can only collect  http get params and post params (application/x-www-form-urlencoded)
but can't collect application/json params。

I want to know how to collect body params in content-type (application/json)。

if there are any optional plugin can implement my requirement,please tell me。
Thanks！

**Comment by wu-sheng** [comment]
No, we don't have that. Because the plugin would affect all HTTP request, collecting the body is super dangerous. I would recommend you to use our application toolkit API in your own filter, and tag the value into the span.

**Comment by wls1036** [comment]
"collecting the body is super dangerous." i don't understand why collecting the body will be super dangerous. Could you please expalian it more specific?Hope to get your reply. Thanks.

**Comment by wu-sheng** [comment]
This explanation should not by us. Read how servlet and http stream work.

**Comment by wls1036** [comment]
> This explanation should not by us. Read how servlet and http stream work.

Thanks.
