### ISSUE TITLE
can not trace when use spring cloud gateway 2.1.4 or 2.1.5 in skywalking 7.0.0 but can trace in 8.0.1

### ISSUE THREAD

**Issue by crazythinking** [apache/skywalking#4971]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
jdk8
skywalking 7.0.0

- What happen?
can not trace when use spring cloud gateway 2.1.4 or 2.1.5 in skywalking 7.0.0 but can trace in 8.0.1

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by crazythinking** [comment]
In my company still have some systems are running at jdk7, so I can not upgrade to skywalking8, so how could fix this bug in skywalking7? thans a lot.

**Comment by wu-sheng** [comment]
SkyWalking 7 is jdk8 based already. Please recheck your env.

**Comment by crazythinking** [comment]
I known sw7 is jdk8 based, the old systems are based jdk7 are using sw6.x agent to registering sw7, and the other new systems are all based jdk8; i need consider compatiblity in production environment, so i mean is i could only use sw7. so have any way to resolve this problem?

**Comment by wu-sheng** [comment]
You could try to copy the latest plugin codes into the skywalking 7- codebase, and try to recompile it. But no guarantee.
We did a whole community whole survey about JDK versions, 1.8 is the most reasonable choice.

**Comment by crazythinking** [comment]
thx for your reply, and i will try.

**Comment by crazythinking** [comment]
use web-flux and choud gateway plugin of version 8.0.1 can resolve this problem
