### ISSUE TITLE
How to ignore the root prefix

### ISSUE THREAD

**Issue by big-loser** [apache/skywalking#4973]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [I] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

Excuse me, I want to ignore the "/" path in the url request, how to write it in the agent configuration file?

agent.ignore_suffix=${SW_AGENT_IGNORE_SUFFIX:/,.jpg}

I wrote this in the configuration file, but it has no effect.

please help。

thanks

**Comment by wu-sheng** [comment]
If the endpoint is really `/`, I think this should work. Try debug your agent, and what is the real operation name when segment created.

**Comment by big-loser** [comment]
> If the endpoint is really `/`, I think this should work. Try debug your agent, and what is the real operation name when segment created.

Thank you for your quick reply。

Yes, I am sure the endpoint is /.

Because you can see it in ui.

![image](https://user-images.githubusercontent.com/10458694/85942972-85709100-b95f-11ea-8228-5d77f9a34852.png)

**Comment by wu-sheng** [comment]
No, the UI doesn't mean it is. There is an override mechanism in the span operation name. Read EntrySpan source codes.
