### ISSUE TITLE
There is no MySQL driver in the tar package downloaded in version 8.0.1

### ISSUE THREAD

**Issue by yazong** [apache/skywalking#4974]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

download address:
https://mirrors.tuna.tsinghua.edu.cn/apache/skywalking/8.0.1/apache-skywalking-apm-8.0.1.tar.gz

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yazong** [comment]
path:
apache-skywalking-apm-bin/oap-libs

**Comment by arugal** [comment]
Please read the documentation https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#mysql
