### ISSUE TITLE
skywalking-python

### ISSUE THREAD

**Issue by ZemarLi549** [apache/skywalking#4975]
Please answer these questions before submitting your issue.

Why do you submit this issue?
 Question 
### Question
class ArticleDetailView(DetailView):
    '''
    文章详情页面
    '''
    template_name = 'blog/article_detail.html'
    model = Article
    pk_url_kwarg = 'article_id'
    context_object_name = "article"
    @trace(op='get_object_detail')
    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
I tried the skywalking-python agent in my django project,using the buried points to tracing data,
There was a bug appears as follows  when calling this api,
and i want to know if it‘s true that the skywalking-python only surport buried points style to tracing data for django projects?
Will it  works when i only calling agent.start() in the manage.py file? Not using the context or trace decrator
### Bug

'_thread._local' object has no attribute 'context'

### Requirement or improvement
- Python django2.1

**Comment by wu-sheng** [comment]
Please make sure your issue title is reasonable, and description is well formated.

**Comment by wu-sheng** [comment]
The Django plugin progress should be tracked at #4744.

**Comment by wu-sheng** [comment]
> and i want to know if it‘s true that the skywalking-python only surport buried points style to tracing data for django projects?
Will it works when i only calling agent.start() in the manage.py file? Not using the context or trace decrator

I am not sure what you mean only. Language agent is tracing based analysis. What do you mean no context?

**Comment by kezhenxu94** [comment]
@ZemarLi549 even you're using decorators to trace methods, the initialization (`agent.start()`) is still required, that's a prerequisite of the decorators

**Comment by kezhenxu94** [comment]
and `'_thread._local' object has no attribute 'context'` is fixed by https://github.com/apache/skywalking-python/pull/19
