### ISSUE TITLE
every request have two same tracesegment record in skywalking ui

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#4977]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  skywalking 7.0， centOS 7.8.2003，HotSpot jdk1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
i found every request almost have two trace segment record in skywalking ui，and two trace segemnt‘s traceid is same
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by killGC** [comment]
file:///C:/Users/jichao.huang/AppData/Roaming/WeLink/UserData//jichaohuang@sendinfo_c03a50e5a95e281005c22ced0a441968/ReceiveFiles/ScreenShot/screenshot_20200629091830093.png

**Comment by killGC** [comment]
![截图1](https://user-images.githubusercontent.com/35632023/85964290-a5e62d00-b9eb-11ea-9877-4fd79bd58dfd.PNG)

**Comment by killGC** [comment]
![截图3](https://user-images.githubusercontent.com/35632023/85964297-b0082b80-b9eb-11ea-949f-2f59eb312319.PNG)

**Comment by killGC** [comment]
![截图](https://user-images.githubusercontent.com/35632023/85964331-daf27f80-b9eb-11ea-8e84-15194dfb964e.PNG)

**Comment by wu-sheng** [comment]
We don't have this issue, you could check the demo env. And base on your screenshot, it is not UI issue. there are duplicated data in your elasticsearch.

**Comment by wu-sheng** [comment]
Such as this trace id, the UI shows correctly.
![image](https://user-images.githubusercontent.com/5441976/85964762-50ab1b00-b9ed-11ea-8c22-a34aeddded5e.png)

**Comment by killGC** [comment]
![截图4](https://user-images.githubusercontent.com/35632023/85968288-4857dd80-b9f7-11ea-973d-269746e41c67.PNG)
two segment's databinary is different

databinary  of segmentid 19.130.15929839543651016：Cg0KCxOCAciV0Nqsg6YcEnoQ////////////ARi9x/ipri4gma75qa4uMCZYA2BUekUKA3VybBI+aHR0cDovL3Rlc3R3d3cubG90c21hbGwuY24vYXBpL3RoZWF0ZXIvbWVyY2hhbnRUaGVhdGVyU2hvd0dyaWR6EgoLaHR0cC5tZXRob2QSA0dFVBgCIBM=

databinary  of segmentid 19.198.15929839543650282：
Cg0KCxPGAeqP0Nqsg6YcEkoIARi9x/ipri4gvcf4qa4uOglKZWRpcy9nZXRAAlABWAVgHnoQCgdkYi50eXBlEgVSZWRpc3oTCgxkYi5zdGF0ZW1lbnQSA2dldBJKCAIYvsf4qa4uIL7H+KmuLjoJSmVkaXMvZ2V0QAJQAVgFYB56EAoHZGIudHlwZRIFUmVkaXN6EwoMZGIuc3RhdGVtZW50EgNnZXQSSggDGL7H+KmuLiC+x/ipri46CUplZGlzL2dldEACUAFYBWAeehAKB2RiLnR5cGUSBVJlZGlzehMKDGRiLnN0YXRlbWVudBIDZ2V0EkwIBRAEGL/H+KmuLiC/x/ipri46CUplZGlzL2dldEACUAFYBWAeehAKB2RiLnR5cGUSBVJlZGlzehMKDGRiLnN0YXRlbWVudBIDZ2V0Er0CCAYQBBjBx/ipri4gwcf4qa4uOiRNeXNxbC9KREJJL1ByZXBhcmVkU3RhdGVtZW50L2V4ZWN1dGVACVABWAFgIXoOCgdkYi50eXBlEgNzcWx6EwoLZGIuaW5zdGFuY2USBHh4c2N61QEKDGRiLnN0YXRlbWVudBLEAVNFTEVDVCAgaWQsZGVsZXRlZCxDUkVBVEVfQlksQ1JFQVRFX1RJTUUsTU9ESUZZX0JZLE1PRElGWV9USU1FLE1FUkNIQU5UX0lORk9fSUQsVVNFUl9JTkZPX0lEICBGUk9NIE1FUkNIQU5UX1VTRVIgIFdIRVJFICAgICAgICggIE1FUkNIQU5UX0lORk9fSUQgPSA/ICkKICAgIAogIAogICAgCiAgICAgIGFuZCAgICAgICggIGRlbGV0ZWQgPSA/ICkSuQIIBxAEGMTH+KmuLiDFx/ipri46JE15c3FsL0pEQkkvUHJlcGFyZWRTdGF0ZW1lbnQvZXhlY3V0ZUAJUAFYAWAheg4KB2RiLnR5cGUSA3NxbHoTCgtkYi5pbnN0YW5jZRIEeHhzY3rRAQoMZGIuc3RhdGVtZW50EsABU0VMRUNUIGNvdW50KDApIEZST00gbWVyY2hhbnRfdGhlYXRlcl9zaG93IGEsIHRoZWF0ZXJfc2hvdyBiIFdIRVJFIGEuZGVsZXRlZCA9ICdGJyBBTkQgYi5kZWxldGVkID0gJ0YnIEFORCBhLkNPREUgPSBiLkNPREUgQU5EIGIuRU5BQkxFRCA9ICdUJyBBTkQgYS5NRVJDSEFOVF9JTkZPX0lEID0gPyBBTkQgYi5NQUlOX1VTRVJfSUQgPSA/Et0FCAgQBBjHx/ipri4gx8f4qa4uOiRNeXNxbC9KREJJL1ByZXBhcmVkU3RhdGVtZW50L2V4ZWN1dGVACVABWAFgIXoOCgdkYi50eXBlEgNzcWx6EwoLZGIuaW5zdGFuY2USBHh4c2N69QQKDGRiLnN0YXRlbWVudBLkBHNlbGVjdCAJYS5JRCBpZCwKCQkJCWEuTUVSQ0hBTlRfSU5GT19JRCBtZXJjaGFudEluZm9JZCwKCQkJCWIuTkFNRSBuYW1lLAoJCQkJYS5TQUxFU19OVU0gc2FsZXNOdW0sCgkJCQliLkxPV19QUklDRSBsb3dQcmljZSwKCQkJCWIuSElHSF9QUklDRSBoaWdoUHJpY2UsCgkJCQliLkxJTktfTU9CSUxFX0lNRyBsaW5rTW9iaWxlSW1nLAoJCQkJYi5TVEFSVF9EQVRFIHN0YXJ0RGF0ZSwKCQkJCWIuRU5EX0RBVEUgZW5kRGF0ZSwKCQkJCWIuUFVSQ0hBU0VfREVTQyBwdXJjaGFzZURlc2MsCiAgICAgICAgICAgICAgICBiLmlkIHRoZWF0ZXJTaG93SWQsCiAgICAgICAgICAgICAgICBhLkNPREUgY29kZQoJCWZyb20gbWVyY2hhbnRfdGhlYXRlcl9zaG93IGEsIHRoZWF0ZXJfc2hvdyBiCgkJd2hlcmUgCWEuZGVsZXRlZCA9ICdGJyBhbmQgYi5kZWxldGVkID0gJ0YnCgkJCQlhbmQgYS5DT0RFID0gYi5DT0RFCgkJCQlhbmQgYi5FTkFCTEVEID0gJ1QnCgkJIAoJCQlhbmQgYS5NRVJDSEFOVF9JTkZPX0lEID0gPwoJCSAKCQkgCgkJCWFuZCBiLk1BSU5fVVNFUl9JRCA9ID8KCQkgCgkJIAoJCQoJCSAKCQkgCgkJIAoJCQlvcmRlciBieSBiLlNPUlRfTk8gZGVzYywgYi5JRCBMSU1JVCA/IBLcAggJEAQYycf4qa4uIMrH+KmuLjokTXlzcWwvSkRCSS9QcmVwYXJlZFN0YXRlbWVudC9leGVjdXRlQAlQAVgBYCF6DgoHZGIudHlwZRIDc3FsehMKC2RiLmluc3RhbmNlEgR4eHNjevQBCgxkYi5zdGF0ZW1lbnQS4wFTRUxFQ1QgaWQsZGVsZXRlZCxDUkVBVEVfQlksQ1JFQVRFX1RJTUUsTU9ESUZZX0JZLE1PRElGWV9USU1FLE1FUkNIQU5UX0lORk9fSUQsTUFSS0VUX0RJU19BQ0NPVU5ULFFZX0FDQ09VTlQsUVlfUEFTU1dPUkQsRElTX0FDQ05BTUUsUVlfRU5BQkxFLE9QRU5fU0lOR0xFICBGUk9NIE1FUkNIQU5UX1dIT0xFX01BUktFVCAgV0hFUkUgIGRlbGV0ZWQgPSA/IEFORCBNRVJDSEFOVF9JTkZPX0lEID0gPxLoAQgKEAQYysf4qa4uIODH+KmuLjonLy93aGFsZW1hcmtldGluZy9hcGkvYXV0aC9mZXRjaFVzZXJBdXRoQAtQAVgDYAt6EwoLaHR0cC5tZXRob2QSBFBPU1R6jQEKA3VybBKFAWh0dHA6Ly8xOTIuMTY4LjIwMC4xODk6ODA4MC8vd2hhbGVtYXJrZXRpbmcvYXBpL2F1dGgvZmV0Y2hVc2VyQXV0aD9jb3JwQ29kZT1xaHl4aWFvamluZyZvcGVuSWQ9MTYwOSZoZWFkSW1nVXJsPSZuaWNrTmFtZT0mcmVnQ2hhbm5lbD0SrAEICxAEGOHH+KmuLiC6gfmpri46LC9zeXNaWUJUaGVhdGVySW5mb1NlcnZpY2UvZmluZFRoZWF0ZXJTZXNzaW9uQA5QAVgDYAt6EwoLaHR0cC5tZXRob2QSBFBPU1R6TQoDdXJsEkZodHRwOi8vMTkyLjE2OC4yMDEuMTQ6ODAyMi9zeXNaWUJUaGVhdGVySW5mb1NlcnZpY2UvZmluZFRoZWF0ZXJTZXNzaW9uEqwBCAwQBBi7gfmpri4g3qz5qa4uOiwvc3lzWllCVGhlYXRlckluZm9TZXJ2aWNlL2ZpbmRUaGVhdGVyU2Vzc2lvbkAOUAFYA2ALehMKC2h0dHAubWV0aG9kEgRQT1NUek0KA3VybBJGaHR0cDovLzE5Mi4xNjguMjAxLjE0OjgwMjIvc3lzWllCVGhlYXRlckluZm9TZXJ2aWNlL2ZpbmRUaGVhdGVyU2Vzc2lvbhKsAQgNEAQY36z5qa4uIJGt+amuLjosL3N5c1pZQlRoZWF0ZXJJbmZvU2VydmljZS9maW5kVGhlYXRlclNlc3Npb25ADlABWANgC3oTCgtodHRwLm1ldGhvZBIEUE9TVHpNCgN1cmwSRmh0dHA6Ly8xOTIuMTY4LjIwMS4xNDo4MDIyL3N5c1pZQlRoZWF0ZXJJbmZvU2VydmljZS9maW5kVGhlYXRlclNlc3Npb24SrAEIDhAEGJKt+amuLiC/rfmpri46LC9zeXNaWUJUaGVhdGVySW5mb1NlcnZpY2UvZmluZFRoZWF0ZXJTZXNzaW9uQA5QAVgDYAt6EwoLaHR0cC5tZXRob2QSBFBPU1R6TQoDdXJsEkZodHRwOi8vMTkyLjE2OC4yMDEuMTQ6ODAyMi9zeXNaWUJUaGVhdGVySW5mb1NlcnZpY2UvZmluZFRoZWF0ZXJTZXNzaW9uEqwBCA8QBBjBrfmpri4g7a35qa4uOiwvc3lzWllCVGhlYXRlckluZm9TZXJ2aWNlL2ZpbmRUaGVhdGVyU2Vzc2lvbkAOUAFYA2ALehMKC2h0dHAubWV0aG9kEgRQT1NUek0KA3VybBJGaHR0cDovLzE5Mi4xNjguMjAxLjE0OjgwMjIvc3lzWllCVGhlYXRlckluZm9TZXJ2aWNlL2ZpbmRUaGVhdGVyU2Vzc2lvbhKsAQgQEAQY7q35qa4uIJeu+amuLjosL3N5c1pZQlRoZWF0ZXJJbmZvU2VydmljZS9maW5kVGhlYXRlclNlc3Npb25ADlABWANgC3oTCgtodHRwLm1ldGhvZBIEUE9TVHpNCgN1cmwSRmh0dHA6Ly8xOTIuMTY4LjIwMS4xNDo4MDIyL3N5c1pZQlRoZWF0ZXJJbmZvU2VydmljZS9maW5kVGhlYXRlclNlc3Npb24ScQgEGL/H+KmuLiCYrvmpri4wJlgDYA56RQoDdXJsEj5odHRwOi8vdGVzdHd3dy5sb3RzbWFsbC5jbi9hcGkvdGhlYXRlci9tZXJjaGFudFRoZWF0ZXJTaG93R3JpZHoSCgtodHRwLm1ldGhvZBIDR0VUEkoQ////////////ARi9x/ipri4gma75qa4uKhkIARINCgsTggHIldDarIOmHCATOBNIJlgmOhBVbmRlcnRvd0Rpc3BhdGNoUAJgVBgCIBM=

**Comment by killGC** [comment]
![截图4](https://user-images.githubusercontent.com/35632023/85968472-d2a04180-b9f7-11ea-80e2-92e0be9b20e0.PNG)

**Comment by killGC** [comment]
![截图4](https://user-images.githubusercontent.com/35632023/85968504-e77cd500-b9f7-11ea-8b0a-f400bf1479f3.PNG)

**Comment by killGC** [comment]
> We don't have this issue, you could check the demo env. And base on your screenshot, it is not UI issue. there are duplicated data in your elasticsearch.

if as you say，what reason possible be caused？

**Comment by wu-sheng** [comment]
If there are two segment, it is nornal. The list is segment not trace.
