### ISSUE TITLE
About the endpoint avg throughput metrics etc 

### ISSUE THREAD

**Issue by kongyu20** [apache/skywalking#4978]
In the service dashboard, Whether the indicator parameters of the endpoint are accurate，eg:Endpoint Avg ResponseTime,Endpoint Avg Throughput etc.The data that came out of my Jmeter pressure-testing interface is very different.

**Comment by wu-sheng** [comment]
If you are doing 100% sampling, default is, then the metrics are accurate.

**Comment by wu-sheng** [comment]
But you need to make sure your backend and storage are powerful enough. Otherwsie, safe mode activated, the trace will be abondoned.

**Comment by kongyu20** [comment]
OK, understand what your mean, the configuration item is not turned on, is it the default?As follows: #agent.sample_n_per_3_secs=${SW_AGENT_SAMPLE:-1}

Then,the storage is using ES cluster services.

**Comment by wu-sheng** [comment]
Yes, it is default.
