### ISSUE TITLE
The new plugin shows unknown and n/a in the topology diagram

### ISSUE THREAD

**Issue by a921897495** [apache/skywalking#4979]
Based on the plug-ins of oracle and tomcat, I wrote the plug-in support of China's domestic database Jincang database and Dameng data, as well as the application servers Dongfangtong and Kingdee Tianyan. Data can be collected, but displayed as unknown and n/a in the topology diagram. How do I need to modify it to display the picture I provided?
![捕获](https://user-images.githubusercontent.com/32760449/85968248-252d2e00-b9f7-11ea-8735-7234e0843886.PNG)

**Comment by wu-sheng** [comment]
Component id with namr and icon need to be added. Read plugin dev document.

**Comment by a921897495** [comment]
Where can I add it? I did not find the relevant description in the plugin development documentation。
https://github.com/apache/skywalking/blob/v7.0.0/docs/en/guides/Java-Plugin-Development-Guide.md

**Comment by wu-sheng** [comment]
Look like you missed the doc

Component IDs are defined and reserved by SkyWalking project. For component name/ID extension, please follow Component library definition and extension document.
