### ISSUE TITLE
Support segment status based on entry/first span only.

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4980]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
Is it possible to filter according to the final return status(entry point endpoint)? 

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

1. i want to find the errors in my serverice,so i choose the error status
2. i found the cloudlet-analysisBI-report_DataQuery_query interface have errors
3. i found the final status of the endpoint is success,the error reason is because the mysql have error in  the downstream.
![image](https://user-images.githubusercontent.com/31562192/85970070-e352b680-b9fb-11ea-9580-4f1127a18b83.png)
___
### Requirement or improvement
- Is it possible to filter according to the final return status(entry point endpoint)?

**Comment by wu-sheng** [comment]
I think it is the status of what `SegmentAnalysisListener` says, right now. If you want to add a configuration about this, we could accept, even could consider providing this as default.

Would you like to do a pull request?

**Comment by EvanLjp** [comment]
I found the codes in version 8, let me read the code first to understand your thinking

**Comment by wu-sheng** [comment]
Open this as PR submitted.
