### ISSUE TITLE
I want to modify skywalking agent to transfer globalTraceId into response header, Should I only need to update agent-plugin?

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#4982]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Yes, if you want that, you need to change the plugin source codes.
