### ISSUE TITLE
Spring cloud gateway project logback cannot print TraceID

### ISSUE THREAD

**Issue by cnhaicao** [apache/skywalking#4983]
spring cloud gateway 2.1.X
pom.xml:
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
        </dependency>

logback configuration:
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

	<property name="LOG_FILE" value="./logs/gateway-logs/gateway.log"/>
	<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
		<encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
			<layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
				<pattern>%d{HH:mm:ss.SSS} [%thread] %-5level logger_name:%logger{36} - [%tid] - message:%msg%n</pattern>
			</layout>
		</encoder>
	</appender>

	<appender name="FILE"
			  class="ch.qos.logback.core.rolling.RollingFileAppender">
		<file>${LOG_FILE}</file>
		<append>true</append>
		<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
			<fileNamePattern>${LOG_FILE}-%d{yyyy-MM-dd}.%i.log
			</fileNamePattern>
			<timeBasedFileNamingAndTriggeringPolicy
					class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
				<maxFileSize>104857600</maxFileSize>
			</timeBasedFileNamingAndTriggeringPolicy>
			<MaxHistory>10</MaxHistory>
		</rollingPolicy>
		<encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
			<layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
				<pattern>%d{HH:mm:ss.SSS} [%thread] %-5level logger_name:%logger{36} - [%tid] - message:%msg%n</pattern>
			</layout>
		</encoder>
	</appender>

	<root level="INFO">
		<appender-ref ref="CONSOLE" />
		<appender-ref ref="FILE" />
	</root>

</configuration>

LOG INFO IS :
The logback log TraceID has always been: [TID:N/A]

**Comment by wu-sheng** [comment]
We didn't test and guarantee that right now. This feature used to print the id in your app business code only.

Gateway has many async thread case, if you want to do this, you have to understand the tracing context and Gateway thread mode very clear.

**Comment by ldy** [comment]
below is my project lib version：
SpringBoot：2.1.4.RELEASE，Spring Cloud Gateway：2.1.2，apm-toolkit-logback-1.x：6.5.0，Skywalking：8.2.0

I met the same problem too！
In gateway service，i can print the tid in my code when i use ```String traceId = TraceContext.traceId();```,but logback cannot print tid,only show ```[TID:N/A]```.
In other service，logback can also print tid normal.
what can i do to let logback to print tid normal in gateway service?

![QQ图片20201126205646](https://user-images.githubusercontent.com/12880699/100353779-01aff300-302a-11eb-9878-3838fe6fd044.jpg)

**Comment by BothSavage** [comment]
https://bothsavage.github.io/article/240121-skywaking
