### ISSUE TITLE
编译咨询问题

### ISSUE THREAD

**Issue by wangsai0806** [apache/skywalking#4986]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
我如果用JDK1.7编译skywalking（我们的项目目前是JDK1.7的），需要在哪个分支中进行编译，谢谢
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only. The SkyWalking 6.6 is the last version could run in JDK 1.7
