### ISSUE TITLE
Open global traceId set

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#4991]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
In some business scenarios, custom traceid generation rules need to be customized
how about to open the set method?

Current plan: 
1. keep the three parts because  the structure is referenced  by so many other codes
2. open the setGlobalTraceId in ContextManager, add a setReadableGlobalTraceId in AbstractTracerContext interface

after done,there will be 2 ways to replace global traceid

1. ContextCarrier extract from upstream
2. set global traceId by in custom plugin

I think this has no meaning for skywalking itself, but it makes sense for some companies to have privatized plugins inside

**Comment by EvanLjp** [comment]
I also thought about making it plug-in
for example: 
1. the GlobalIdGenerator add a function Supplier method to To expose the algorithm implementation
2. a plugin service to implement boot service to invoke the GlobalIdGenerator Supplier method

but the thinking cannot use http header as the algorithm seed

**Comment by wu-sheng** [comment]
I don't think setting the global trace id is a good idea. Basically, and mostly in SkyWalking, we do auto-instrumentation, right?
The app developer is mostly impossible to set trace id before the first span created, also, it means, you can't guarantee, there is no `injection`  happened before your codes. In that case, the trace will break, the developer will be hard to understand what happened.

**Comment by wu-sheng** [comment]
`GlobalIdGenerator` should be refactored as a service, which could provide the override mechanism in the plugin system. But if this is an internal service, which generation algorithm would you like to provide? And what are the benefits?

**Comment by EvanLjp** [comment]
in our company , all pv coross bfe (cncf) ,and all the pv will be add  a unique bfeid as a  http header.
we want to use bfeid as a part of traceid.
I know this is a abnormal demand, I want to ensure that the company maintains the version  nearly equals the official version.
Do you have any other suggestions? thanks for your helping.

**Comment by EvanLjp** [comment]
I thought about it again, this thing is not suitable for appearing in the official version,If the set method is added, basically no one else will use it in official plugin

**Comment by wu-sheng** [comment]
I have a feeling, you treat trace context in an easier way, which is not correct.

No matter what in the header(in HTTP only), we should not use it as a trace, because this could be an abusion. If you want to add something into the trace, from BFE perspective or others', you could follow SkyWalking `Cross Process Propagation Headers Protocol v3`, in doc https://github.com/apache/skywalking/blob/master/docs/en/protocols/README.md

You could notice, the Nginx LUA agent has a different trace id format.

I think the correct solution is, making BFE follows SkyWalking protocol, including
1. Trace report
1. Cross Process Propagation Headers Protocol

WDYT?

**Comment by EvanLjp** [comment]
I know your feeling,thanks for your helping

**Comment by wu-sheng** [comment]
Look forward you could make BFE supported SkyWalking.
