### ISSUE TITLE
 Calling Python agent failed

### ISSUE THREAD

**Issue by yue-chao** [apache/skywalking#4992]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion

___
### Question
- What do you want to know?
Calling Python agent in Django service does not show anything in the alarm interface, is it because API calls errors? I added decorators to every interface in view. Please tell me how to call spans

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
python3.7  Django 2.1

**Comment by wu-sheng** [comment]
No Django plugin, read #4744. Please don't submit duplicated issue.
