### ISSUE TITLE
dose the OAL support the not op in filter?

### ISSUE THREAD

**Issue by bonnieguo** [apache/skywalking#4994]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
   Question or discussion

___
### Question
- What do you want to know?

i have a scenario like this:
in the OAL config,i want to filter out some service ,
my expression as below but not work, how can i make it work?
endpoint_success = from(Endpoint.*).filter(name not like ("%hairuo-gateway" or "%hairuo-gateway-file")).filter(status = "true").percent()
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
First of all, no matter there is or not. Your percent func usage is not correct. This is the right one.
> service_sla = from(Service.*).percent(status == true);

Then for filter, you need to extend the function, we don't have `not like` or `like` now

**Comment by bonnieguo** [comment]
so you mean the percent not support for the endpoint level ?

**Comment by wu-sheng** [comment]
No, percent parameter.

**Comment by bonnieguo** [comment]
i just get it from the example:
// Caculate the percent of response status is true, for each service.
Endpoint_success = from(Endpoint.*).filter(status = "true").percent()


// Caculate p99 of Endpoint name started with `serv`
serv_Endpoint_p99 = from(Endpoint.latency).filter(name like ("serv%")).summary(0.99)

**Comment by wu-sheng** [comment]
Real case is in core.oal
