### ISSUE TITLE
[nginx-lua] How do I deliver traceid and span?

### ISSUE THREAD

**Issue by snpcp** [apache/skywalking#4998]
Hi,

When I using skywalking for nginx, how does the upstream server get the traceid and span generated by skywalking of Nginx? This relates to how can Nginx and upstream server be concatenated. Please tell me what I should do?

Thanks.

**Comment by wu-sheng** [comment]
That is cross process propagation protocol. Read document in the main repo. It is defined there. Not just trace id. Your question is not right.

**Comment by snpcp** [comment]
Excuse me, Could you explain it in detail for me? 

About traceid and span, Don't I have to do anything? so, How do I associate Nginx and Upstream Server?

Thanks.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/blob/master/docs/en/protocols/README.md#language-based-native-agent-protocol

If you still don't understanf, you have missed the tracing acknowledge, not skywalking. Consider to read Google Dapper paper.

**Comment by wu-sheng** [comment]
If your app has installed the agent, then, yes. You don't need to do anything. That is auto instrumentation.

**Comment by snpcp** [comment]
Sorry, I don't understand skywalking.

So, Traceid is passed to the Server via an upstream request？Or Is nignx and upstream server associated by Skywalking server?

Thanks.

**Comment by snpcp** [comment]
I know opentracing and read your documentation, but I don't know the principle of nginx relevance to upstream server about traceid.

**Comment by wu-sheng** [comment]
Nginx lua agent is just an implementation of SkyWalking tracing model. Nothing more.

**Comment by snpcp** [comment]
Hi wu-sheng,

Does Skywalking use SW6 in the upstream request to associate a service? Is that so?

Thanks.

**Comment by snpcp** [comment]
If Skywalking is used dynamically in my customized Nginx, I need to manually add SW6 to the upstream request.

**Comment by wu-sheng** [comment]
Don't know what is your meaning.

**Comment by snpcp** [comment]
ok, thanks for your help me.
