### ISSUE TITLE
Failed to store data using elasticsearch6.7.1, Upgrade skywalking from 7.0.0 to 8.0.1

### ISSUE THREAD

**Issue by yh1968684316** [apache/skywalking#4999]
I deleted all related indexes before upgrading.

After the upgrade is complete, I see a lot of similar logs from  "skywalking-oap-server.log".
index [es_data_segment-20200701], type [type], id [b05353759ae4415ea1c389fc511618a6.41.15935745160680152], message [ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [endpoint_id] of type [integer] in document with id 'b05353759ae4415ea1c389fc511618a6.41.15935745160680152']]; nested: ElasticsearchException[Elasticsearch exception [type=number_format_exception, reason=For input string: "bWVtYmVyLXNlcnZlcg==.1_TGV0dHVjZS9IR0VUQUxM"]];]

Dashboard Only part of the data on the dashboard displays normally, and topology and trace have no data.
I hope to get some suggestions to solve the problem.

**Comment by wu-sheng** [comment]
You don't erase the es correctly.
