### ISSUE TITLE
skywalking报警规则使用

### ISSUE THREAD

**Issue by bonnieguo** [apache/skywalking#5000]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question

___
### Question
- What do you want to know?
关于skywalking报警规则（我目前用的是skywalking 7.0），想请教一个问题：
     endpoint的报警，我想要过滤到某一些service的内容，尝试方法如下：
     exclude-names：
       - hairuo-gateway
     exclude-names-regex:
      - .*\/\$\{server.error.path:\$\{error\.path\:\/error\}\}.*
      - .*hairuo-gateway.*
      - /${server.error.path:${error.path:/error}} in component-distribution
      - \/\$\{server.error.path:\$\{error\.path\:\/error\}\} in component-distribution
      - bizcrm_saasb_initAcsDataFromContract in biz-crm-bridge-crm

但是最终结果看，都没有起作用，请问使用方式有什么问题吗
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only.
