### ISSUE TITLE
skywalking alarm filter usage not work

### ISSUE THREAD

**Issue by bonnieguo** [apache/skywalking#5001]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
in skywalking alarm filter, in the file :alarm-settings.yml, i want to create a alarm rule and filter out some endpoint and service,
use the exclude-names and exclude-names-regex, but seems not work

the version of my skywalking is 7.0
use it as below: hairuo-gateway is a service
exclude-names：
- hairuo-gateway

exclude-names-regex:
 - .*\/\$\{server.error.path:\$\{error\.path\:\/error\}\}.*
 - .*hairuo-gateway.*
 - /${server.error.path:${error.path:/error}} in component-distribution
 - \/\$\{server.error.path:\$\{error\.path\:\/error\}\} in component-distribution
 - bizcrm_saasb_initAcsDataFromContract in biz-crm-bridge-crm

the alarm i recevie is like this
[
    {
        "scopeId":3,
        "scope":"ENDPOINT",
        "name":"/crm/web/generic/bizcrm/saasb/home/queryHomeMenu in hairuo-gateway",
        "id0":684,
        "id1":0,
        "ruleName":"endpoint_sla_49_rule",
        "alarmMessage":"endpoint /crm/web/generic/bizcrm/saasb/home/queryHomeMenu in hairuo-gateway",
        "startTime":1593581843991
    }
]

[
    {
        "scopeId":3,
        "scope":"ENDPOINT",
        "name":"/${server.error.path:${error.path:/error}} in cloudwareaiinvite-web",
        "id0":1279,
        "id1":0,
        "ruleName":"endpoint_sla_49_rule",
        "alarmMessage":"endpoint /${server.error.path:${error.path:/error}} in cloudwareaiinvite-web",
        "startTime":1593581845785
    }
]

is there any wrong with it?
__
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Endpoint is not service, it belongs to a service.

> /crm/web/generic/bizcrm/saasb/home/queryHomeMenu in hairuo-gateway

This is the endpoint name in the alarm. Make sure your name regex matching them. `RunningRule#in` is the core, debug it if necessary.

**Comment by bonnieguo** [comment]
for the endpoint mentioned above:
/crm/web/generic/bizcrm/saasb/home/queryHomeMenu in hairuo-gateway

i try to use 
.*hairuo-gateway.*

to regex match to it ,but it seems not work

**Comment by bonnieguo** [comment]
.\*hairuo-gateway.\*

**Comment by wu-sheng** [comment]
You should not ask for Regex. This is not the thing we created.

**Comment by wu-sheng** [comment]
I have told you the codes, do your local tests, and read codes.

**Comment by bonnieguo** [comment]
exclude-names-regex:
--
 - .\*\/\$\{server.error.path:\$\{error\.path\:\/error\}\}.\*
 - .\*hairuo-gateway.\*
 - /${server.error.path:${error.path:/error}} in component-distribution
 - \/\$\{server.error.path:\$\{error\.path\:\/error\}\} in component-distribution
 - bizcrm_saasb_initAcsDataFromContract in biz-crm-bridge-crm
