### ISSUE TITLE
[nginx-lua] Using skywalking-nginx-lua failed in openresty

### ISSUE THREAD

**Issue by snpcp** [apache/skywalking#5003]
I using span.lua throw 'not found lua' error.

The issue is caused by rockspec modules.

Please see '["skywalking.span_layer"] = "lib/skywalking/span_layer.lua"' (https://github.com/apache/skywalking-nginx-lua/blob/master/rockspec/skywalking-nginx-lua-0.1-0.rockspec)

In span.lua (https://github.com/apache/skywalking-nginx-lua/blob/master/lib/skywalking/span.lua) line 18. the span require 'span_layer' instead of 'skywalking.span_layer'. so not found span_layer.lua.

And I couldn't have set lua_package_path to the '/usr/local/openresty/luajit/share/lua/5.1/skywalking/' directory,  this is my lua_package_path: '/usr/local/openresty/luajit/share/lua/5.1/', I can using span.lua by require 'skywalking.span', but I have no control over the use of span_layer.lua.

Please tell me how to do it? thanks very much.

**Comment by wu-sheng** [comment]
I think you didn't install SkyWalking correctly.  We deploy in e2e like this, https://github.com/apache/skywalking/blob/master/test/e2e/e2e-test/docker/lua/Dockerfile.nginx

**Comment by wu-sheng** [comment]
This is a demo config file, https://github.com/apache/skywalking-nginx-lua/blob/master/examples/nginx.conf
The full document is here, https://github.com/apache/skywalking-nginx-lua

**Comment by snpcp** [comment]
It's not the same thing, I can successfully deploy as examples/nginx.conf, but I need rewrite client.lua and tracer.lua,  because my app is not nginx, it's a app based on Nginx. and I can't using lua_package_path is '/Users/wusheng/Documents/GitHub/skywalking-nginx-lua/lib/skywalking/?.lua;;'.

I don't know if I made myself clear.

**Comment by snpcp** [comment]
I using luarocks intsall skywalking-nginx-lua, This my code:

lua_package_path: /usr/local/openresty/luajit/share/lua/5.1/*.lua;

local Span = require('skywalking.span');
Span.start(entrySpan, ngx.now() * 1000);
...

**Comment by wu-sheng** [comment]
If you are not using in the case we provided, I am afraid that it is not our concern. You are on your own.

**Comment by snpcp** [comment]
May I add your Chinese contact information?Wechat?QQ?

**Comment by snpcp** [comment]
qq: 1109891383

**Comment by snpcp** [comment]
Here's my issue, 'skywalking. span_layer' is configured in Luarocks. Why is it still used 'span_layer' in code? 

This would result in me not being able to use span_layer.lua if I did not configure path to the /usr/local/openresty/luajit/share/lua/5.1/skywalking/ directory. This violates the Luarocks specification. 

what do you think?

**Comment by snpcp** [comment]
In https://github.com/apache/skywalking/issues/4742.

Please see :
-----------------------------
@harrybin815 luarocks automatically installs the dependent files at the time of installation, so there is no need to install dependencies directory.
https://github.com/apache/skywalking-nginx-lua/blob/master/rockspec/skywalking-nginx-lua-0.1-0.rockspec#L14

client.lua and tracer.lua are showing how to use this library, and you may need to implement your own version.
-----------------------------

**Comment by snpcp** [comment]
Whether you admit it or not, It is indeed bug, and with just Luarocks.
