### ISSUE TITLE
skywalking ui topology graph advice

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#5004]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
tracing must running a distributed system
so if our system invoke other system ,the skywalking would be add a unknown service.if the invoke target is a ip list ,the graph would be appear so many unknown service. And the behavior would be cost so many time when the front end rendering.
why not the default graphql query is to ignore unknown services?
and add a button to keep now status
![image](https://user-images.githubusercontent.com/31562192/86215245-f0fc6d80-bbae-11ea-986d-499a11b18e75.png)

**Comment by wu-sheng** [comment]
But that is the topology designed for, showing the real distributed relationships. Once we hide those conjecture nodes, people may even don't know they exist.

**Comment by EvanLjp** [comment]
so In the above description:
1. when we access the page ,i think the default page should inclue the following items
![image](https://user-images.githubusercontent.com/31562192/86227284-64a67680-bbbf-11ea-82f9-9c211c6a5a48.png)
2. if we want to know the mysql,es,unknown point ,we can open it
![image](https://user-images.githubusercontent.com/31562192/86227534-b818c480-bbbf-11ea-829b-42d6386c7feb.png)

now our staus is following:
![image](https://user-images.githubusercontent.com/31562192/86227581-cebf1b80-bbbf-11ea-8e53-aafc66b0b8c5.png)

so priority in my mind:
1. only show depenency between services
2. switch to open external components  dependency,for example : mysql ,es, or unknown services

**Comment by wu-sheng** [comment]
We gave the service group for the huge topology and make it more meaningful. For 100+ service nodes, I don't think there would be a real difference with or without conjecture nodes.

**Comment by EvanLjp** [comment]
1. i know the service group ,but the page rander is so slow because of the the front end render when has so many unknown services.
2. At 7.0.0 ,the service group has bug, cannot add some services which beyond the border
![image](https://user-images.githubusercontent.com/31562192/86229356-2b233a80-bbc2-11ea-8440-b6f456fd2dd5.png)
3. i think the services dependency for whole services has positive sense for deciders

**Comment by wu-sheng** [comment]
First, about (1) and (2), those are code level thing, they are not related to this topic. Should not change based on those.

For (3), I am not sure whether a 150 nodes topo and a 200 nodes topo have any different? Who can see what is happening there? 

All three should not be treated as a reasonable requirement for the feature you asked. At least for myself.

**Comment by EvanLjp** [comment]
I think your way of thinking is right,
1. about (1) and (2) i will open a new topic to discuss it
3. about 3, i agree with you if have more than 200 node in a dashboard

Could there be a more convenient way?
for example : 
1. user chose a central point
2. Increase the degree or decrease the degree to control the graph
Whether this approach is more efficient in analyzing service relationships

**Comment by wu-sheng** [comment]
Do you have a video to demo? I can't be sure of your points.

**Comment by EvanLjp** [comment]
reply the demo picture on qq
