### ISSUE TITLE
Endpoint throughput data in skywalking and data with Jmeter voltage measurement throughput

### ISSUE THREAD

**Issue by kongyu20** [apache/skywalking#5010]
Why is the endpoint throughput data in skywalking very different from the data measured with Jmeter press? Which data is more accurate and reasonable? Is the throughput of the endpoints in useful skywalking used as a stress indicator data and written on the performance test report?

**Comment by wu-sheng** [comment]
That could be many reasons, such as your ES cluster capability, whether in cluster mode, and whether cluster mode config correctly. It is hard to tell from your single one sentence question.

**Comment by kongyu20** [comment]
Endpoint throughput data in skywalking is about 10 times the Jmeter voltage dating data

**Comment by wu-sheng** [comment]
Are you reading what I replied? You are keeping saying the same thing. Without your local research, we can't help.

**Comment by kongyu20** [comment]
Sorry, I see what you mean. Explain the advance condition, skywalking is in ES cluster mode, and the agent data sampling rate is the default configuration.

**Comment by wu-sheng** [comment]
Is SkyWalking in cluster mode? Are you config correctly?

**Comment by kongyu20** [comment]
The skywalking service itself is not a cluster mode. As for most configurations are defaulted, there are several xxxMaxSize configuration items with values that are larger than the default adjustment.Reference to the official website and some technical blog configuration, to tell the truth whether this configuration is correct is really a question.

**Comment by wu-sheng** [comment]
I don't know what you changed. Please explain in detailly. Also, OAP server has fail-safe mechanism, once it can't process or ES can't process the throughput, even you set 100% sampling on the agent, some data will be ignored on the agent side directly.
