### ISSUE TITLE
Why All My Instances' PID Equal 1?

### ISSUE THREAD

**Issue by otailai** [apache/skywalking#5012]
- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

**the pids of all instances are all the same**
Please check the incident behavior via following screeshot: 
![2020-07-02_13-48-15](https://user-images.githubusercontent.com/10295363/86321076-d687ca00-bc6a-11ea-8b52-c1e347817b42.png)

These applications are running within Docker, and I build a basic image by `COPY agent/ /app/agent/` and run application by adding `-javaagent:/app/agent/skywalking-agent.jar` into program arguments.
Did I import any misconfiguration when deploying?

Hope for replying!

**Comment by otailai** [comment]
the version of SkyWalking is 7.0.0

**Comment by wu-sheng** [comment]
Easy answer, learn docker.
