### ISSUE TITLE
agent can support agent.sample_n_per_3_secs of agent property as Dynamic configuration 

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#5016]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think there is NOT an agent side dynamic configuration mechanism. What do you expect?

**Comment by killGC** [comment]
i expect when application request amount is big，i can reduce  agent.sample_n_per_3_secs to ruduce  agent using resource

**Comment by wu-sheng** [comment]
How do you know this is happening? I mean `too much traffic`, how do you know the baseline? and when to do this?
And when you want to change, which are the targets, for all instances of a service?
Then, how could you change and push the command to the agent? A possibility is `Dynamic Configuration Center` -> `OAP` -> `agent`.

**Comment by wu-sheng** [comment]
And, there is a challenge is, when the agent reboot, it would be back to local static config, until the backend pushed the new configs. 

But, you mean, there is agent fail-safe protection mechanism, why do we need this really? Is there CPU overload for real?

**Comment by killGC** [comment]
> How do you know this is happening? I mean `too much traffic`, how do you know the baseline? and when to do this?
> And when you want to change, which are the targets, for all instances of a service?
> Then, how could you change and push the command to the agent? A possibility is `Dynamic Configuration Center` -> `OAP` -> `agent`.

when having big activity, i estimate it may be come to too much traffic，and i adjust the property
i don't consider so much,it sound many thing need to consider
in the first place，my idea is directly from Dynamic Configuration Center>Agent
now get inspired from you ，whether or not it is able to sending command to reduce the property by skywalking ui ，UI->OAP->agent

**Comment by wu-sheng** [comment]
There are a lot of gaps
1. There is no UI related to the config center, even config center itself is not required, just optional.
1. There is no `config center -> OAP -> agent` yet.
1. Agent doesn't watch the changes of config.

If you want to do these, I am afraid you are required to provide a design doc, such as https://docs.google.com/document/d/1mlOmydJyICuqwGveem260dJEWxAE-ssMOy8gzXm33Yo/edit

**Notice, the reboot feature has been removed, this is only an example of design doc**.
