### ISSUE TITLE
question about alarming local span

### ISSUE THREAD

**Issue by firolololo** [apache/skywalking#5019]
If i write a plugin to establish a local span to intercept the constructor of my own java class, the span will fail in some situation. I try to alarm this situation and configure alarm-setting.xml as following:

rules:
  # alarm
  xxxxxxxx_rule:
    metrics-name: endpoint_sla
    op: ">"
    threshold: 60
    period: 10
    count: 1
    silence-period: 5
    message: "failed"
    include-names:
      - com.example.className in serviceName

but not work.

**Comment by wu-sheng** [comment]
Typically, this should not work, because there are no metrics generated through local spans.
But luckily, you have an option in the master and next 8.1 release. We call that logic endpoint from the span.

Read the latest doc for more details.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/blob/master/docs/en/guides/Java-Plugin-Development-Guide.md#extension-logic-endpoint-tag-key-x-le

**Comment by firolololo** [comment]
appreciate your reply!
