### ISSUE TITLE
can replace “？of sql” to “parameter value” in sql of trace 

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#5025]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We don't have the plan to do so, it will cause extra performance, and mislead people, they are not using the SQL prepared statement. Some companies have forbidden to use SQL in that way.

**Comment by killGC** [comment]
> We don't have the plan to do so, it will cause extra performance, and mislead people, they are not using the SQL prepared statement. Some companies have forbidden to use SQL in that way.

ok，thank you reply
