### ISSUE TITLE
reactor traceId does not relate to non-reactor traceId

### ISSUE THREAD

**Issue by zcz3313** [apache/skywalking#5026]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
I have a gateway service based on Spring-WebFlux and a demo service based on Spring-Web.
I found traceIds on skywalking-UI web, but these traces can't be correlated, they are indepent.

Here are my screen shots:

gateway
![1](https://user-images.githubusercontent.com/8746495/86454634-1aa1ca00-bd52-11ea-9d54-704852739175.png)
demo
![2](https://user-images.githubusercontent.com/8746495/86454660-28574f80-bd52-11ea-8bbd-c3baef98ce11.png)

You can see two traces on the screen shots above. Is there anything I missed?

**Comment by wu-sheng** [comment]
If there is across threads happens, you need to propagate the Context. Read the plugin dev doc. We can't guarantee your private gateway. The Spring Gateway(the official one) works well.

**Comment by zcz3313** [comment]
> If there is across threads happens, you need to propagate the Context. Read the plugin dev doc. We can't guarantee your private gateway. The Spring Gateway(the official one) works well.

My gateway is Spring Cloud Gateway (2.1.12). Anyway I will check the doc first and then reply, thanks.

**Comment by icyfox-bupt** [comment]
> > If there is across threads happens, you need to propagate the Context. Read the plugin dev doc. We can't guarantee your private gateway. The Spring Gateway(the official one) works well.
> 
> My gateway is Spring Cloud Gateway (2.1.12). Anyway I will check the doc first and then reply, thanks.

Hi, I'm facing the same problem, have you fixed it finally?

**Comment by zcz3313** [comment]
> > > If there is across threads happens, you need to propagate the Context. Read the plugin dev doc. We can't guarantee your private gateway. The Spring Gateway(the official one) works well.
> > 
> > 
> > My gateway is Spring Cloud Gateway (2.1.12). Anyway I will check the doc first and then reply, thanks.
> 
> Hi, I'm facing the same problem, have you fixed it finally?

yes，use the plugin。
