### ISSUE TITLE
Skywalk data population on Kibana.

### ISSUE THREAD

**Issue by mailyathish** [apache/skywalking#5033]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- Is there a way,  we can plot the Skywalk data in Kibana.    We have used the Elastic-search as data store.  is there pre-defined index for skywalk stats. 

___
### Bug
- Which version of SkyWalking, OS and JRE?
7.0.0

- Which company or project?
JCPenney

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Yes, the data is pre-defined by OAL scripts, and have been calculated. What else do you need? I think it is hard to use Kibana. Any block?

**Comment by mailyathish** [comment]
Thanks @wu-sheng,  I was looking at charting the metrics,  CPU, Memory and response time stats from Different JVM.

**Comment by wu-sheng** [comment]
>  metrics, CPU, Memory and response time stats from Different JVM.

Is this an issue? Some of them, such as response time, are aggregated across JVMs, into a logic service too.

**Comment by mailyathish** [comment]
Thanks for details.
