### ISSUE TITLE
Introduce "health checker" module to OAP

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#5034]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

## Why we need it?

OAP does not provide the health status to the external services, which causes it's too difficult to investigate the running issues of the OAP server, especially in could-native and CI scenarios. 

## How to figure it out?

I will introduce a new module called "health checker", which has capacities of:
 
 1. Collecting specific metrics from other modules through the telemetry module(Prometheus). 
 1.  Parsing and analyzing them by leveraging Prometheus text protocol parser.
 1. Providing a new GraphQL query to expose the health status.
 1. Providing GraphQL and gRPC health check tools,  one potential solution is to embed them to `swctl`. Then packaging them into the docker image.

@kezhenxu94 @wu-sheng any thoughts?

**Comment by wu-sheng** [comment]
Could you explain a little more about `through the telemetry module(Prometheus)`? Is that you are analysing Prome fetcher or oc-receiver data somehow? I want to know how you will do this.

**Comment by wu-sheng** [comment]
We did a direct discussion. This API could be provided by every module, but optional. The `health-manager` module could read health-related metrics, make the final decision, and open public through GraphQL.

**Comment by kezhenxu94** [comment]
Resolved
