### ISSUE TITLE
how know service intance of  joined up skywalking  hang up by skywalking？

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#5037]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean? It is mot clear.

**Comment by killGC** [comment]
skywalking have apm function ，can skywalking monitor service instance whether or not hang up？whether by alarm？

**Comment by wu-sheng** [comment]
Do you mean the port alive detection?

**Comment by killGC** [comment]
yes,i mean this

**Comment by wu-sheng** [comment]
Currently, we don't have that. But if you want, could consider contributing a new fetcher. We had one for prometheus, you could contribute one for port detection.

**Comment by killGC** [comment]
ok, I'll try later.
