### ISSUE TITLE
Duplicate service name

### ISSUE THREAD

**Issue by amwyyyy** [apache/skywalking#5039]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
Version: 8.0.0

I found a duplicate service name in the drop-down box
![image](https://user-images.githubusercontent.com/8274512/86578011-b7ac6f00-bfad-11ea-9f4b-48330d2fce52.png)

View elasticsearch, there are two data.
```json
{
  "_index": "sw8_service_traffic-20200704",
  "_type": "type",
  "_id": "bWJwLWJvbnVzLWNhbGN1bGF0ZQ==.1",
  "_version": 1,
  "_score": 2,
  "_source": {
    "node_type": 0,
    "name": "mbp-bonus-calculate"
  }
}
```
```json
{
  "_index": "sw8_service_traffic-20200706",
  "_type": "type",
  "_id": "bWJwLWJvbnVzLWNhbGN1bGF0ZQ==.1",
  "_version": 1,
  "_score": 2,
  "_source": {
    "node_type": 0,
    "name": "mbp-bonus-calculate"
  }
}
```

**Comment by wu-sheng** [comment]
From the data, we can see the service exists in 0704 and 0706 index both. So whether there is sometimes, the 0704 is not readable? Once it isn't, the data will be written into latest index again. This is how SkyWalking metadata works today.

**Comment by amwyyyy** [comment]
@wu-sheng 
I found the error log, which should be related to this. but this situation is sometimes unavoidable, I hope to be compatible with this problem.
![image](https://user-images.githubusercontent.com/8274512/86892261-99bc4700-c132-11ea-919b-cb8faa74e10e.png)

**Comment by wu-sheng** [comment]
We can't, because once it is available, we will write a new one. There is no point to deal with it in the query. Because
1. This will restore with time, TTL will delete them.
1. Any service you chose, will get the same result.

**Comment by wu-sheng** [comment]
ES is not available is not a small issu.e

**Comment by amwyyyy** [comment]
There will throw an exception,many features will not be available.
![image](https://user-images.githubusercontent.com/8274512/86912691-07c33700-c150-11ea-8c3c-0696b93faad1.png)

![image](https://user-images.githubusercontent.com/8274512/86913664-8cfb1b80-c151-11ea-9d42-d6005e368396.png)
Change line 48 can make the code robust
```
for (int i = 0; i < response.getHits().getHits().length; i++) {}
```

**Comment by wu-sheng** [comment]
If you want to change something, send a pull request with full description. We should discuss there. Open source project is collaborated.
