### ISSUE TITLE
how to deal with dynamic urls when registry lots of endpoints

### ISSUE THREAD

**Issue by xiaofeitu2** [apache/skywalking#5044]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
there is a scene,in springcloud, zuul gateway router dynamic urls to business springboot application, agent will  registry lots 
 of endpoints to oap server periodly,oap server will put the endpoint into localcache or es.but the endpoints are too much ,it will take quite a few time to deal with them .when the cahe size is not enough,a lot of requests will hit the es storage  and it will low down the performance of the oap server,in sometime maybe make the server oom. is there any way to solve the problem? 
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.6
- Which company or project?
autoai.com
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
 zuul gateway router dynamic urls to business springboot application
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
agent group rule for dynamic urls

**Comment by wu-sheng** [comment]
In 8+, there is no register, so, don't need to worry about this. And backend url grouping has been provided. Don't do this in the agent, it will be a high load for your app.

**Comment by xiaofeitu2** [comment]
1. dose that mean in 6.x version it is difficult to solve the problem?
2.in 8+,will all the operationame be recorded in es or other storage ? every time get the endpoint name or id will request the stroage and if there are lots of different endpoint name to request and quiet frequently,  if we add a choice that putting the endpoint name in distribute cache system ,will that be possible?

**Comment by wu-sheng** [comment]
> dose that mean in 6.x version it is difficult to solve the problem?

Yes, it is hard. That is why we changed the design.

> in 8+,will all the operationame be recorded in es or other storage ? 

Still in ES, but no register, so no block you are facing. And no endpoint cache anymore. If you want to know more details, read the latest codes.

> every time get the endpoint name or id will request the stroage and if there are lots of different endpoint name to request and quiet frequently, if we add a choice that putting the endpoint name in distribute cache system ,will that be possible?

It is possible, but not helpful. It still cost too much. We don't think that is a good idea. Anyway, the better way is provided, let's not stuck in the old design. High level design improvement is always better than purely tech level improvement.
