### ISSUE TITLE
InsMethodsInter: class[class org.redisson.client.RedisConnection] before/after method[send] intercept failure

### ISSUE THREAD

**Issue by tony1991** [apache/skywalking#5047]
#5045 # Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.0.0.GA
redisson 3.13.0

- Which company or project?
inner project

- What happen?

my skywalking work normal, but always print follow log:

"InsMethodsInter: class[class org.redisson.client.RedisConnection] before method[send] intercept failure, java.lang.NullPointException

InsMethodsInter: class[class org.redisson.client.RedisConnection] after method[send] intercept failure, java.lang.IllegalStateException: No active span
at org.apache.skywalking.apm.agent.core.context.TracingContext.activeSpan(TracingContext.java:383)
***
***
at org.redisson.client.RedisConnection.send(RedisConnection.java)
***
"

Looking forward to your reply

___

**Comment by wu-sheng** [comment]
6.0 is far from the latest. Please check the latest one. And plugin should be debugged locally first.
