### ISSUE TITLE
使用skywalking-webapp显示trace的调用时长不正确

### ISSUE THREAD

**Issue by snpcp** [apache/skywalking#5051]
调用时长的时长图像应该显示最大为10007ms，但是却显示成为了90s，导致看到的调用时长显示不正确。
通过network查看到获取到的trace的响应数据。
{
  "data": {
    "trace": {
      "spans": [
        {
          "traceId": "1594172755623.633498320.36694",
          "segmentId": "1594172755623.633498320.36694",
          "spanId": 0,
          "parentSpanId": -1,
          "refs": [],
          "serviceCode": "Test",
          "startTime": 1594172755623,
          "endTime": 1594172765630,
          "endpointName": "/a/b/c",
          "type": "Entry",
          "peer": "",
          "component": "Nginx",
          "isError": false,
          "layer": "Http",
          "tags": [
            {
              "key": "http.method",
              "value": "GET"
            },
            {
              "key": "http.params",
              "value": "http://xxx/a/b/c"
            }
          ],
          "logs": []
        },
        {
          "traceId": "1594172755623.633498320.36694",
          "segmentId": "1594172755623.633498320.36694",
          "spanId": 1,
          "parentSpanId": 0,
          "refs": [],
          "serviceCode": "Test",
          "startTime": 1594172765623,
          "endTime": 1594172765630,
          "endpointName": "/a/b/c",
          "type": "Exit",
          "peer": "server-1",
          "component": "Nginx",
          "isError": false,
          "layer": "Http",
          "tags": [],
          "logs": []
        },
        {
          "traceId": "1594172755623.633498320.36694",
          "segmentId": "1594172667479.374957098.22150",
          "spanId": 0,
          "parentSpanId": -1,
          "refs": [
            {
              "traceId": "1594172755623.633498320.36694",
              "parentSegmentId": "1594172755623.633498320.36694",
              "parentSpanId": 1,
              "type": "CROSS_PROCESS"
            }
          ],
          "serviceCode": "User Service Name 1",
          "startTime": 1594172667479,
          "endTime": 1594172667485,
          "endpointName": "/ingress01",
          "type": "Entry",
          "peer": "",
          "component": "Nginx",
          "isError": false,
          "layer": "Http",
          "tags": [
            {
              "key": "http.method",
              "value": "GET"
            },
            {
              "key": "http.params",
              "value": "http://xxx/ingress01"
            }
          ],
          "logs": []
        },
        {
          "traceId": "1594172755623.633498320.36694",
          "segmentId": "1594172667479.374957098.22150",
          "spanId": 1,
          "parentSpanId": 0,
          "refs": [],
          "serviceCode": "User Service Name 1",
          "startTime": 1594172667479,
          "endTime": 1594172667485,
          "endpointName": "/ingress01",
          "type": "Exit",
          "peer": "upstream service 1",
          "component": "Nginx",
          "isError": false,
          "layer": "Http",
          "tags": [],
          "logs": []
        }
      ]
    }
  }
}

**Comment by wu-sheng** [comment]
English only. And please provide well-formated information.
