### ISSUE TITLE
After 12:00 p.m., data writing to elasticsearch failed

### ISSUE THREAD

**Issue by kangswx** [apache/skywalking#5053]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
 skywalking 6.6  elastikcearch 7

- Which company or project?

- What happen?
After 12:00 p.m., data writing to elasticsearch failed
skywalking-oap-server.log   Bulk [566] executed with failures
locked org.eclipse.jetty.io.ManagedSelector$SelectorProduce

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Check your ES status, new index(s) for the next day created wwith data flowing in at that time.
