### ISSUE TITLE
SkyWalking CLI can't query a specific service by name

### ISSUE THREAD

**Issue by fgksgf** [apache/skywalking#5058]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
    - SkyWalking CLI 0.2.0
    - OS: MacOS 10.13.5

- What happen?
When I use the command `swctl service ls <service_name>`, it showed: 

`FATAL graphql: Exception while fetching data (/service) : Elasticsearch exception [type=illegal_argument_exception, reason=Alias [service_traffic] has more than one indices associated with it [[service_traffic-20200708, service_traffic-20200709]], can't execute a single index op]`

**Comment by wu-sheng** [comment]
I think you are not using the official release of SkyWalking somehow. It is a bug in the 8.0 dev stage only.

**Comment by kezhenxu94** [comment]
This should be in the scope of #4923 @fgksgf

**Comment by wu-sheng** [comment]
@kezhenxu94 I think this is not same thing. The error he posted is the illegal query. And the old query still could do based on the name. The document indicates the way.

**Comment by wu-sheng** [comment]
This seems a backend bug, locating why.
