### ISSUE TITLE
Convert instance as podName

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#5061]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
when running in k8s,podName is a common concept rather than ip;
So,How about changing the instance concept to POD when running on kubernetes?

**Comment by wu-sheng** [comment]
Instance name could be set through system env. You could set anything you want.

**Comment by kezhenxu94** [comment]
> Instance name could be set through system env. You could set anything you want.

I'm also in need of this minor change, the instance name can be set via ENV VAR, yes, but cannot be set dynamically the same as the pod name, (if I didn't miss anything), this proposed change is helpful when we want to map from the instance to the actually pod instance (for example, finding a specific pod from the trace, where there is an IP), I know from IP we can surely find the pod finally, but the conversion is an extra work, and if the instance IP is not a must to be retained, this change actually helps more than harms

**Comment by wu-sheng** [comment]
What do you mean dynamically? Could you provide more details about this?

**Comment by kezhenxu94** [comment]
For pod `abcd-efgh-1234`, set the instance name to `abcd-efgh-1234`, for pod `abcd-efgh-1235`, set the instance name to `abcd-efgh-1235`, and for whatever I don't know pod `whatever-random-pod-name`, can I set it to the `whatever-random-pod-name`

**Comment by kezhenxu94** [comment]
Just do a search on Google and there’s a workaround to expose the pod name to the end var https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/ @EvanLjp hope this helps, need extra config though

**Comment by wu-sheng** [comment]
That is what I mean, podname is controlled by k8s, so, there is no point, agent or SkyWalking gets the name. It should be injected by following k8s ways.

**Comment by EvanLjp** [comment]
![image](https://user-images.githubusercontent.com/31562192/88522131-852fe800-d028-11ea-9c4b-9b78df5a255e.png)
It's just what I need
@wu-sheng @kezhenxu94

**Comment by wu-sheng** [comment]
@EvanLjp Is there any issue? I think this is already there for a long time.
