### ISSUE TITLE
Add env config control when loading agent jar

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#5062]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
in our department , a unified agent  jar package will be used when Helm Chart  package in all the services.
maybe .some service don't need so many detail when tracing. for example spring plugin.
however,other service need it.
nowadays.we cannot now control the loading of the unified Jars  by reading environment variables.
so i want to add the feature. loading by env config.

for example:
/plugins has 5 jar
Optional way:
1. inclues: a.jar will only load a.jar
2.excludes: a.jar will load other 4 jars.

**Comment by wu-sheng** [comment]
How do you expert the option plugins?

**Comment by EvanLjp** [comment]
some plans:
(1) don't care option plugins.This will break now model.
the includes or excludes only work for plugins dir.

(2) work on option plugins.
1. all load plugins position and option plugins position.
2. includes work on option plugins dir , default is excludes all
3. excludes work on plugins dir , default is includes all

**Comment by wu-sheng** [comment]
I hope it could work in this way
1. `include-plugins`. When this is activated(not null), then only these plugins should be loaded. Path should be `/plugins/xxx.jar`, `optional-plugins/yyy.jar` or `activations/zzz.jar`
1. `exclude-plugins`. This should be based on the default only, `plugins/` and `activations`.

What do you think about these policies?

**Comment by EvanLjp** [comment]
question:
/plugins/ has 20 jars 
/optional-plugins/ has 10 jars

when need 8 jars in plugins and 2 jars in optional-plugins ,how it works?
1. include-plugins config 10 jars.

when need 10 jars in plugins and 2 jars in optional-plugins ,how it works?
1.  include-plugins config 12 jars.

Is only when you don't use the option-plugins,  the excludes works ?


maybe this is a good idea, user only care the plugins which is selected. So excludes status should be weakening

**Comment by wu-sheng** [comment]
> Is only when you don't use the option-plugins, the excludes works?

Yes and No. By reading your use case, you actually are looking for a solution for a unified base image. So, you could copy the all optional plugins into plugins, and use `excludes` to make things work.

Or, you should think again, whether `include` and `exclude` are both needed. I am feeling, `include` is required only. As that, I prefer this config called `activate-plugins`.
