### ISSUE TITLE
build connection between agent client and oap server with service discover

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#5063]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
In some cases,BACKEND_SERVICE is config as dns:port;
some dns production is not support Load balancing,for example core dns in cncf.

so i want to add a dns lookup to support the case

**Comment by wu-sheng** [comment]
Just confirm, you want to do `DNS lookup` manually by codes, then select the backend from candidates?

**Comment by EvanLjp** [comment]
yes，maybe can support more ways，for example 
1. dns
2. Kubernetes service
Maybe kubernetes service load balancer mode is a better way,but the way depends on cloud (aws,Ali),it would be not work in a privite kubernetes cluster 
So.i want to add the feature, like kubernetes dubbo 
1.Use kubernetes service self support 
1.if have time,also supports dns nslookup

**Comment by wu-sheng** [comment]
Do you have more material about DNS level load balancer can't work automatically? From your asking, it seems, we need codes to do a DNS lookup to get the candidate list. Am I right?

**Comment by wu-sheng** [comment]
If you want to add new dependency on the agent core, that wouldn't be recommended, especially for this case. The way would be adding a plugin for feature extension. If there is no extension point currently, we could create one.
Anymore, I need more details about what you are trying to do. Because I don't know what dubbo-k8s did, actually, that is not have to be our reference. Agent is very different from a dev framework.

**Comment by EvanLjp** [comment]
yes，i should change a new title
build the connection between  agent client and oap server with service discover
for example :
Kubernetes
dns
etcd
zk
.....

create a new extension point like oap

**Comment by wu-sheng** [comment]
OK, that will not be an easy job. NOTICE, receiver role OAP role is never registered through the coordinator, but your service discovery is for looking up receiver role nodes.

**Comment by wu-sheng** [comment]
And service discovery of OAP node is not recommended in many companies, because the OAP nodes are deployed in the system/operation platform zone, rather than the business zone. Service discovery wouldn't work in this case.

**Comment by EvanLjp** [comment]
OK，thx

**Comment by EvanLjp** [comment]
i found the purpose of boot service  int erface for single purpose.
if we want to support  the  polymorphism in service discovery.
2 ways: 
1. modify the boot service to support polymorphism
2. add a new interface.

Do you have any Suggestions
