### ISSUE TITLE
Are there some conflict between skywalking and dubbo？

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#5065]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

below is the agent logs ：

WARN 2020-07-09 10:08:24:235 main AbstractClassEnhancePluginDefine : enhance class com.hisense.inventory.rest.api.HealthCheckApi by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.RestControllerForLowVersionInstrumentation is not working. Because witness class org.springframework.web.context.support.ServletContextPropertyPlaceholderConfigurer is not existed. 
WARN 2020-07-09 10:08:24:235 main AbstractClassEnhancePluginDefine : enhance class com.hisense.inventory.rest.api.HealthCheckApi by plugin org.apache.skywalking.apm.plugin.spring.mvc.v5.define.RestControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.resource.HttpResource is not existed. 
WARN 2020-07-09 10:08:24:307 main AbstractClassEnhancePluginDefine : enhance class io.terminus.pampas.openplatform.core.Gateway by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed. 
WARN 2020-07-09 10:08:24:307 main AbstractClassEnhancePluginDefine : enhance class io.terminus.pampas.openplatform.core.Gateway by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.ControllerForLowVersionInstrumentation is not working. Because witness class org.springframework.web.context.support.ServletContextPropertyPlaceholderConfigurer is not existed. 
WARN 2020-07-09 10:08:24:307 main AbstractClassEnhancePluginDefine : enhance class io.terminus.pampas.openplatform.core.Gateway by plugin org.apache.skywalking.apm.plugin.spring.mvc.v5.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.resource.HttpResource is not existed. 
WARN 2020-07-09 10:08:27:179 main AbstractClassEnhancePluginDefine : enhance class org.springframework.boot.autoconfigure.web.BasicErrorController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed. 
WARN 2020-07-09 10:08:27:179 main AbstractClassEnhancePluginDefine : enhance class org.springframework.boot.autoconfigure.web.BasicErrorController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.ControllerForLowVersionInstrumentation is not working. Because witness class org.springframework.web.context.support.ServletContextPropertyPlaceholderConfigurer is not existed. 
WARN 2020-07-09 10:08:27:179 main AbstractClassEnhancePluginDefine : enhance class org.springframework.boot.autoconfigure.web.BasicErrorController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v5.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.resource.HttpResource is not existed. 
WARN 2020-07-09 10:08:39:422 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed. 
WARN 2020-07-09 10:08:39:424 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v5.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.resource.HttpResource is not existed. 
WARN 2020-07-09 10:08:39:907 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.support.InvocableHandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.InvocableHandlerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed. 
tail: unrecognized file system type 0x794c7630 for ‘skywalking-api.log’. please report this to bug-coreutils@gnu.org. reverting to polling

below is app log：
version=1.0.0, timeout=10000}]], channel: /10.160.22.41:49672 -> /10.161.21.132:26881
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:188)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96)
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke$original$2cnMHt0x(MonitorFilter.java:75)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke$original$2cnMHt0x$accessor$zt0AEObz(MonitorFilter.java)
	at com.alibaba.dubbo.monitor.support.MonitorFilter$auxiliary$u71zRpYK.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
	... 84 common frames omitted

**Comment by wu-sheng** [comment]
We only support
* RPC Frameworks
  * [Dubbo](https://github.com/alibaba/dubbo) 2.5.4 -> 2.6.0
  * [Dubbox](https://github.com/dangdangdotcom/dubbox) 2.8.4
  * [Apache Dubbo](https://github.com/apache/dubbo) 2.7.0

Only recommend Apache Dubbo rather than Alibaba Dubbo(they are expired)

**Comment by weimayougansha** [comment]
3q
