### ISSUE TITLE
config中的gateways.yml怎么配置的哇，能起到什么作用？（可以提供个模板最好）

### ISSUE THREAD

**Issue by haolanzhong** [apache/skywalking#5068]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only. Documents have been there.
