### ISSUE TITLE
support the  quartz-scheduler

### ISSUE THREAD

**Issue by IAMTJW** [apache/skywalking#5069]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
quartz-scheduler are used in many applications and it's not supported now
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Contribution is welcome.

**Comment by Patrick0308** [comment]
@wu-sheng Can I try it? It will be my first contribution in this repository.

**Comment by wu-sheng** [comment]
@Patrick0308 `help wanted` tag means you could have a try on this kind of issue.

**Comment by wu-sheng** [comment]
Feel free to go, if you have any issue, send a draft pull request, we could discuss on that.

**Comment by IAMTJW** [comment]
> Contribution is welcome.

I am doing this.

**Comment by wu-sheng** [comment]
@IAMTJW @Patrick0308 I suggest you two could connect directly in private, maybe have some collaborations. Glad to know you both are interested.
