### ISSUE TITLE
why you remove the “Dependency Map” in Endpoint with version 8.0.1 and simplify the ui so much

### ISSUE THREAD

**Issue by whfjam** [apache/skywalking#5073]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Because we will bring a much more powerful on in the 8.1, read this. https://twitter.com/ASFSkyWalking/status/1280479748427329544

We don't simply anything, I think you missed the point of 8.0. All metrics are there, we just organized them in a better way.
