### ISSUE TITLE
which apm-sdk-plugin is designed for SpringBoot Web 4.x?Thank you.

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#5074]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean to design for? The agent is not designed for the Spring only, it is for the Java ecosystem.
