### ISSUE TITLE
Missing traceId on static resource url

### ISSUE THREAD

**Issue by zcz3313** [apache/skywalking#5075]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
8.0.1-es6, Linux, JDK 11

- What happen?
postman -> gateway-service -> app-service
1.create a controller method in app-service as follow:
```java
@GetMapping("/test/**")
public void test() {

}
```
2.config a route in gateway service
3.call "http://${gatewayIp}:${gatewayPort}/api/app/test/test" and get result as follow:
![1](https://user-images.githubusercontent.com/8746495/87124853-10388080-c2bc-11ea-8eef-2ccb8ff81119.png)
4.call "http://${gatewayIp}:${gatewayPort}/api/app/test/test.jpg" and get result as follow:
![2](https://user-images.githubusercontent.com/8746495/87124857-13cc0780-c2bc-11ea-8125-166fd2a23df4.png)

**Comment by wu-sheng** [comment]
We don't trace static resources on the Tomcat or any other container. Check the `agent.config` -> `agent.ignore_suffix`. We indicate it very clearly in the doc and config file.
