### ISSUE TITLE
Chrome bowser "Cannot read property 'filter' of undefined"

### ISSUE THREAD

**Issue by changyuxin** [apache/skywalking#5078]
![image](https://user-images.githubusercontent.com/2537992/87147811-e1340600-c2df-11ea-9cb4-18aae0159ed6.png)

**Comment by wu-sheng** [comment]
Clean browser local cache. Likely you have dirty data in the cache.

**Comment by changyuxin** [comment]
I've cleared the chrome cache and it doesn't work. 
I've replaced my computer,  the same question

**Comment by wu-sheng** [comment]
Check our demo env, if it works, then it is your local env issue.
