### ISSUE TITLE
agent.config agent.instance_name configuration

### ISSUE THREAD

**Issue by imperatives** [apache/skywalking#5079]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What is the proper ${SW} syntax to set the Skywalking Agent instance name in the `agent.config` file?
___
### Bug
- Which version of SkyWalking, OS and JRE?
8.0.1
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
I am unable to set the instance name (`agent.instance_name`) from the `agent.config` file.  No matter what configuration values I set the Instance Name is set to `UUID@hostname`. 

I have attempted the following without success:
```
agent.instance_name=${SW_AGENT_INSTANCE_NAME:<value>}
agent.instance_name=${SW_AGENT_INSTANCE:<value>}
agent.instance_name=${SW_INSTANCE_NAME:<value>}
agent.instance_name=${SW_INSTANCE:<value>}
```

Am I entering the incorrect SW name or does the order of when agent.instance_name is listed?

Setting agent.instance_name value at the Agent Options level appears to work as expected (e.g. 
`-javaagent:/path/to/skywalking-agent.jar=agent.instance_name=<value>`).
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
I would prefer to be able to set the `agent.instance_name` value in the `agent.config` file.

**Comment by wu-sheng** [comment]
They are the same thing. Check you `agent.config` file, and do some simple local debug, please.
