### ISSUE TITLE
trace detail http params line break is not working

### ISSUE THREAD

**Issue by CrytisMT** [apache/skywalking#5083]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [√ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
trace detail http params using <span>,not support line break with "\n"
![image](https://user-images.githubusercontent.com/7419191/87224957-f3837200-c3bb-11ea-9818-2cb888c43cca.png)

**Comment by kezhenxu94** [comment]
I'm not sure whether the front-end buddies are going to support the line breaks or not, but I'm sure we won't add something like `<br>` at backend side, just assign to @Fine0830 if you don't think it's possible, feel free to close

**Comment by wu-sheng** [comment]
I don't think UI should take care of this care. It could be countless cases in randoms tag values. Trace should be the last step to locate issue, beside the profiling. Dev and SRE should not use it everyday, for every request.
