### ISSUE TITLE
question about TTL configuration

### ISSUE THREAD

**Issue by a198720** [apache/skywalking#5087]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When I read the document and configure the TTL of the data, I found that the environment variable configuration of recordDataTTL and metricsDataTTL is the same, I am not sure whether this is appropriate?
```yaml
    recordDataTTL: ${SW_CORE_RECORD_DATA_TTL:3} # Unit is day
    metricsDataTTL: ${SW_CORE_RECORD_DATA_TTL:7} # Unit is day
```
___
### Bug
- Which version of SkyWalking, OS and JRE?
 skywalking version: 8.0.1
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
It looks like a config file or document typo. Maybe both. Could you submit a pull request to fix?
