### ISSUE TITLE
dynamic configuration consul, does  "Config Key" can change to other

### ISSUE THREAD

**Issue by weihuaxiong** [apache/skywalking#5089]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ 1] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
dynamic configuration consul, does  "Config Key" can change to other;
 As I have multi sw instance, but with one consul.

Thanks
___

**Comment by wu-sheng** [comment]
Is that isolated by app or namespace? Key should not be changed in any case.
