### ISSUE TITLE
How to get the slowest span in each level of the tree?

### ISSUE THREAD

**Issue by Universe-Milky** [apache/skywalking#5090]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- How can i get the slowest span in each level of the tree, is there some simple ways?

**Comment by wu-sheng** [comment]
No, there isn't. What you asked is just scanning the whole trace.
