### ISSUE TITLE
How to start java agent with project in kubernetes?

### ISSUE THREAD

**Issue by liuzhiguo630** [apache/skywalking#5094]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

[x]I have read doc especially java-agent parts
[x]I have searched in google、baidu
___
### Question
- How to start java agent with project in kubernetes?

Can skywalking java agent could be a single jar file? We have a lot of host machine, use volumes will be hard.

Or some other way to use it with kubernetes? 

Thanks.

- Which version of SkyWalking, OS and JRE?
Skywalking: 8.0.1
OS/JRE: Doesn't matter.

**Comment by wu-sheng** [comment]
What do you mean? k8s is just a platform, we are not blocking you. You could build agent in the image, or sidecar to inject. There are many ways.
