### ISSUE TITLE
Can we support the presentation of ThreadMXBean related data in Instance？

### ISSUE THREAD

**Issue by stalary** [apache/skywalking#5098]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

Can we support the presentation of ThreadMXBean related data in Instance？

Currently, we only have CPU and JVM monitoring, but thread monitoring is just as important for Java applications.

**Comment by wu-sheng** [comment]
If you want to add, yes we can. You also need to add new sources in the backend, and update the templates in the UI. Contributions are welcome.

**Comment by stalary** [comment]
> If you want to add, yes we can. You also need to add new sources in the backend, and update the templates in the UI. Contributions are welcome.

Good, I'm going to start designing here this weekend

**Comment by wu-sheng** [comment]
Good to know. FYI @ascrutae I think you would be interested about this.

**Comment by ascrutae** [comment]
@wu-sheng  Thanks to ping me.  I'd like to join it. @stalary

**Comment by stalary** [comment]
@ascrutae Thanks, this week I will design a plan, now I am not familiar with the source code in some places

**Comment by HackerRookie** [comment]
expect！！！ @stalary
