### ISSUE TITLE
SelfDuration and TotalDuration meaning

### ISSUE THREAD

**Issue by pingliu** [apache/skywalking#5100]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What's the SelfDuration and TotalDuration meaning in the Trace with UI ??

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.4.0

- Which company or project?

**Comment by wu-sheng** [comment]
TotalDuration = SelfDuration + duration(s) of child spans.

**Comment by pingliu** [comment]
代表接口耗时的是哪个数据，谢谢！
