### ISSUE TITLE
What is the latest version of Skywalking that supports tomcat 6 JRE6

### ISSUE THREAD

**Issue by minlywang** [apache/skywalking#5104]
I have several old projects running on tomcat6 JRE6 to connect to Skywalking.

First question:
What is the **latest version of Skywalking that supports JRE6 tomcat 6**?

Second question:
Can I use the **old version of Skywalking agent that supports tomcat6 JRE6** to connect to **the lastest version of  Skywalking server**?

**Comment by wu-sheng** [comment]
We never had plugin in Tomcat 6 as far as I known. It is too old. About the JRE6, I think SkyWalking 7 and the previous version should work, but still, no Tomcat 6 plugin. You may could try SpringMVC plugin, to see whether you have luck.
