### ISSUE TITLE
dayStep doesn't working, index create by 1 day

### ISSUE THREAD

**Issue by weihuaxiong** [apache/skywalking#5106]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ 1] Question or discussion

___
### Question
- What do you want to know?
Skywalking version 8.0.1,    ES7
<img width="1321" alt="截屏2020-07-16 12 14 40" src="https://user-images.githubusercontent.com/29908290/87626580-4748df00-c75f-11ea-9d11-e9b32079857f.png">

I had set    dayStep 10, recordDataTTL 7, and  metricsDataTTL 30 
But the index create still by 1 day.
How can I find the problem , is there more info I should know?

Thank you

**Comment by wu-sheng** [comment]
From my last tests and code review, it is working. Read and debug `TimeSeriesUtils`, please. If any bug there, please submit the pull request to fix it.

**Comment by wu-sheng** [comment]
I noticed you set dayStep > TTL(some), which is wrong.
