### ISSUE TITLE
Cannot get the TID using the spring cloud gateway

### ISSUE THREAD

**Issue by chenshd** [apache/skywalking#5111]
Cannot get the TID using the spring-cloud (version:Hoxton.SR4)  apm-toolkit-logback-1.x  (version:8.0.1)  

logbac.xml

<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
                <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level logger_name:%logger{36} - [%tid] - message:%msg%n</pattern>
            </layout>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="CONSOLE" />
    </root>

log detail
22:46:35.594 [reactor-http-kqueue-2] ERROR logger_name:c.l.a.g.m.s.c.TestController - [TID:N/A] - message:gateway trace_id == N/A

**Comment by wu-sheng** [comment]
We are not supporting trace id in every line of log, that is not SkyWalking's way.

**Comment by BothSavage** [comment]
https://bothsavage.github.io/article/240121-skywaking
