### ISSUE TITLE
after oap-server restart, the agent have error log; oap don't receive  jvm and trace data

### ISSUE THREAD

**Issue by weihuaxiong** [apache/skywalking#5112]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ 1] Question or discussion

___
### Question
- What do you want to know?
---
oap-server 8.0.1 is run in k8s, with k8s svc nodeport proxy, then with nginx tcp proxy

nginx tcp proxy :11800 -> k8s svc nodeport:11800 -> oap-server:11800

---
after oap-server restart, the agent have error log; 
<img width="1350" alt="截屏2020-07-17 02 25 23" src="https://user-images.githubusercontent.com/29908290/87708278-0d1a2480-c7d5-11ea-89d0-407348fd7d07.png">

oap-server don't have error log, but in 15 min, oap-server don't recevie jvm and trace data.
after 15 min, restart the agent application, everything is ok.

---
How can i fix this problem?
Thank you

**Comment by weihuaxiong** [comment]
And the application nginx with skywalking-nginx-lua agent is ok, oap-server have trace data

**Comment by wu-sheng** [comment]
I think that most likely an Nginx issue, not SkyWalking. Some users told me so. Consider using Envoy or Traefik, which performs better in HTTP2/GRPC.
