### ISSUE TITLE
ModuleStartException: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by tianfuhou** [apache/skywalking#5113]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [+] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
怎么初始化mysql数据库？创建数据库的时候，应该指定哪种字符集？
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 8.0.1
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

./oapServiceInit.sh 初始化myql 报如下错误：
2020-07-17 10:07:31,855 - org.apache.skywalking.oap.server.core.storage.model.ModelInstaller - 54 [main] INFO  [] - table: alarm_record does not exist
2020-07-17 10:07:31,897 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - Specified key was too long; max key length is 767 bytes
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English onlyl

**Comment by Georege** [comment]
drop database if exists k8s_skywalking;
CREATE DATABASE IF NOT EXISTS k8s_skywalking DEFAULT CHARSET latin1 COLLATE latin1_general_ci;

**Comment by rainbowsky911** [comment]
> drop database if exists k8s_skywalking;
> CREATE DATABASE IF NOT EXISTS k8s_skywalking DEFAULT CHARSET latin1 COLLATE latin1_general_ci;

666
