### ISSUE TITLE
SelfDuration meaning

### ISSUE THREAD

**Issue by pingliu** [apache/skywalking#5114]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 我知道 TotalDuration = SelfDuration + duration(s) of child spans.
但是SelfDuration的时间代表什么？
接口的整个耗时是在trace的左边栏体现的吗？

___
### Bug
- Which version of SkyWalking, OS and JRE?
 6.4.0
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only.
