### ISSUE TITLE
SelfDuration meaning

### ISSUE THREAD

**Issue by pingliu** [apache/skywalking#5115]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I know ```TotalDuration = SelfDuration + duration(s) of child spans.```
but what's meaning of  the SelfDuration Time ?
where is the API latency ? 
what's relation with the API latency and the SelfDuration Time and the TotalDuration Time ?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.4.0
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I am afraid, you should learn about Google Dapper Paper and the basic knowledge of span. Once you have that the formula I gave you should be enough. The duration at the left side is the duration of the segment, the segment is the set of spans belonging to one process flow, mostly one HTTP request.

Basically, you need your side study, don't treat us as a service provider, which we are not. Open-source community is collaborating with developers, preaching is evangelists', consultant, or commercial services' responsibility.
