### ISSUE TITLE
Spring Cloud gateway : Why all endpoind is a fixed value “WEBFLUX.handle”

### ISSUE THREAD

**Issue by janecms** [apache/skywalking#5118]
Env list:  

- SkyWalking 6.6.0 
- JRE8
- Spring cloud gateway 2.1.14

I Found all endpoint is  the same value "WEBFLUX.handle"
`
 graphql queryEndpoints output:

[
    {
        "key": "3",
        "label": "WEBFLUX.handle"
    },
    {
        "key": "5",
        "label": "/gateway/routes"
    },
    {
        "key": "6",
        "label": "/**"
    }
]

`

## question:
Why all endpoind is a fixed value “WEBFLUX.handle”

**Comment by wu-sheng** [comment]
Use 8.0, how do this is open sourced. Read the codes if want to understand something.

**Comment by janecms** [comment]
After upgrading to version 8.0.1, I found that the problem has been resolved.
Can you tell me, if you upgrade from skywalking 6.6 to 8.0, is the underlying storage still compatible?

**Comment by wu-sheng** [comment]
All things have been changed in 8.0. Read v3 protocol. Same as storage level.
