### ISSUE TITLE
Inquiry: can we monitor db connection pool

### ISSUE THREAD

**Issue by suresh-pandi** [apache/skywalking#5119]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
can we monitor db connection pool ? i am using java application hosted on tomcat connecting to mysql. would like few metrics like total number of connections used, time taken to obtain connection from connection pool.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think @ascrutae is working on this part, but it will take time. This is not a small feature.

**Comment by wu-sheng** [comment]
DBCP, Alibaba Druid(https://github.com/apache/skywalking-java/pull/27), and HikariCP(https://github.com/apache/skywalking-java/pull/29) are supported now.

**Comment by wuguanyu** [comment]
> DBCP, Alibaba Druid([apache/skywalking-java#27](https://github.com/apache/skywalking-java/pull/27)), and HikariCP([apache/skywalking-java#29](https://github.com/apache/skywalking-java/pull/29)) are supported now.
Add this Druid plugins only have trace data.  Does this plugin have metrics like jdbc_connections_max?

**Comment by wu-sheng** [comment]
> > DBCP, Alibaba Druid([apache/skywalking-java#27](https://github.com/apache/skywalking-java/pull/27)), and HikariCP([apache/skywalking-java#29](https://github.com/apache/skywalking-java/pull/29)) are supported now.
> > Add this Druid plugins only have trace data.  Does this plugin have metrics like jdbc_connections_max?

They didn't provide meter reporting. We provided APIs for plugins.
https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/java-plugin-development-guide/#meter-plugin

**Comment by wuguanyu** [comment]
> > > DBCP, Alibaba Druid([apache/skywalking-java#27](https://github.com/apache/skywalking-java/pull/27)), and HikariCP([apache/skywalking-java#29](https://github.com/apache/skywalking-java/pull/29)) are supported now.
> > > Add this Druid plugins only have trace data.  Does this plugin have metrics like jdbc_connections_max?
> 
> They didn't provide meter reporting. We provided APIs for plugins. https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/java-plugin-development-guide/#meter-plugin

import skywalking-sdk dependency, and use skywalking api to report metric when we use java-agent right ?

**Comment by wuguanyu** [comment]
> > > > > DBCP, Alibaba Druid([apache/skywalking-java#27](https://github.com/apache/skywalking-java/pull/27)), and HikariCP([apache/skywalking-java#29](https://github.com/apache/skywalking-java/pull/29)) are supported now.
> > > > > Add this Druid plugins only have trace data.  Does this plugin have metrics like jdbc_connections_max?
> > > 
> > > 
> > > They didn't provide meter reporting. We provided APIs for plugins. https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/java-plugin-development-guide/#meter-plugin
> > 
> > 
> > import skywalking-sdk dependency, and use skywalking api to report metric when we use java-agent right ?
> 
> > > import skywalking-sdk dependency
> 
> No, this isn't this API for. These APIs are designed for plugins, which allow no-code changes from end users.

Does it has any demo in java plugins？

**Comment by wuguanyu** [comment]
> > > > > DBCP, Alibaba Druid([apache/skywalking-java#27](https://github.com/apache/skywalking-java/pull/27)), and HikariCP([apache/skywalking-java#29](https://github.com/apache/skywalking-java/pull/29)) are supported now.
> > > > > Add this Druid plugins only have trace data.  Does this plugin have metrics like jdbc_connections_max?
> > > 
> > > 
> > > They didn't provide meter reporting. We provided APIs for plugins. https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/java-plugin-development-guide/#meter-plugin
> > 
> > 
> > import skywalking-sdk dependency, and use skywalking api to report metric when we use java-agent right ?
> 
> > > import skywalking-sdk dependency
> 
> No, this isn't this API for. These APIs are designed for plugins, which allow no-code changes from end users.

Does it has any demo in java plugins？

**Comment by wu-sheng** [comment]
Isn't API doc clear enough? What is the demo?

**Comment by wu-sheng** [comment]
I just provided the link for the doc. The plugin APIs have nothing related to toolkit. 

`What is plugin API?`, the APIs you used in plugin(interceptors) to create spans(tags, context, etc.) are the tracing APIs. In the same time, we provided the meter API for metrics collecting.

**Comment by wuguanyu** [comment]
> I just provided the link for the doc. The plugin APIs have nothing related to toolkit.
> 
> `What is plugin API?`, the APIs you used in plugin(interceptors) to create spans(tags, context, etc.) are the tracing APIs. In the same time, we provided the meter API for metrics collecting.

I understood, Thanks I need modify plugin (interceptors) what i need

**Comment by wu-sheng** [comment]
Yes, also you need to setup meter analysis rule(MAL engine) to parse the meter data to queryable data.
