### ISSUE TITLE
How can I do to ensure that deleted microservice is not displayed on the Skywalking UI

### ISSUE THREAD

**Issue by YanwxTech** [apache/skywalking#5122]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- I have deleted a microservice, but the microservice is still displayed in the service list on the Skywalking UI. How can I do to ensure that the deleted microservice is not displayed on the page?

**Comment by wu-sheng** [comment]
With TTL, the data would be gone. Read the document.
