### ISSUE TITLE
What is the main point of performance loss?

### ISSUE THREAD

**Issue by thanq** [apache/skywalking#5123]
- Why do you submit this issue?
- [✔️ ] Question or discussion
___
### Question
I did a performance test. After adding skywalking agent, the throughput of Java application had a 7% loss, and the sampling rate setting had little impact on the throughput. I would like to ask this question, how do you view this problem: the performance loss has little to do with sampling rate, and what is the main point of performance loss do you think?

**Comment by wu-sheng** [comment]
7% throughput loss depends on what is your env. Such as it is costed by memory/GC. Sampling basically is about reducing network and serialization costs.
You could check our agent benchmark. The throughput loss is nearly nothing. You need to check this through a different perspective.
