### ISSUE TITLE
in docker image apache/skywalking-oap-server:8.0.1-es7, env dayStep maybe have a problem

### ISSUE THREAD

**Issue by weihuaxiong** [apache/skywalking#5125]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ 1] Bug
_
### Bug
- Which version of SkyWalking, OS and JRE?
   docker pull apache/skywalking-oap-server:8.0.1-es7

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

As describe in #https://github.com/apache/skywalking/issues/5106
the dayStep don't working

I try blow:
---
build a new storage-elasticsearch-plugin-8.0.1.jar replace the jar file in docker image
---
wget https://mirror.bit.edu.cn/apache/skywalking/8.0.1/apache-skywalking-apm-8.0.1-src.tgz
#line 42 : private static int DAY_STEP = 1; --> private static int DAY_STEP = 10;
sed -i -e "s/DAY_STEP = 1/DAY_STEP = 10/" oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/base/TimeSeriesUtils.java

docker run -ti --rm -v "$(pwd)":/usr/src/mymaven -v /home/weihua/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6-openjdk-8 ./mvnw clean package -Pbackend -DskipTests

Dockerfile:
---
FROM apache/skywalking-oap-server:8.0.1-es7
ADD application.yml /skywalking/config/
ADD docker-entrypoint.sh /skywalking
ADD storage-elasticsearch-plugin-8.0.1.jar /skywalking/oap-libs/

start skywalking with ENV  
---
 - 1.SW_STORAGE_DAY_STEP=10 
     bash-4.4# grep dayStep sw.log 
     2020-07-18 19:20:19,161 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -1293 [main] INFO  [] - Provider=elasticsearch7 config=dayStep has been set as 10
     bash-4.4# grep TTL sw.log 
     2020-07-18 19:20:19,159 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -1291 [main] INFO  [] - Provider=default config=recordDataTTL has been set as 20
     2020-07-18 19:20:19,159 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -1291 [main] INFO  [] - Provider=default config=metricsDataTTL has been set as 40 

 - 2.SW_STORAGE_DAY_STEP=9 
     bash-4.4# grep dayStep sw.log 
     2020-07-19 05:46:36,604 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -1114 [main] INFO  [] - Provider=elasticsearch7 config=dayStep has been set as 9
     bash-4.4# grep TTL sw.log 
     2020-07-19 05:46:36,602 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -1112 [main] INFO  [] - Provider=default config=recordDataTTL has been set as 20
     2020-07-19 05:46:36,602 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -1112 [main] INFO  [] - Provider=default config=metricsDataTTL has been set as 

 - 3.SW_STORAGE_DAY_STEP=8 
     bash-4.4# grep dayStep sw.log
     2020-07-19 05:42:47,514 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -1189 [main] INFO  [] - Provider=elasticsearch7 config=dayStep has been set as 8
     bash-4.4# grep TTL  sw.log
     2020-07-19 05:42:47,512 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -1187 [main] INFO  [] - Provider=default config=recordDataTTL has been set as 20
     2020-07-19 05:42:47,512 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader -1187 [main] INFO  [] - Provider=default config=metricsDataTTL has been set as 40

the index es is same (-20200714) as blow: GET _cat/indices/sq-qd-ny-t*    ###before env SW_STORAGE_DAY_STEP change, DELETE /sq-qd-ny-t*
green open sw-qd-ny-t_instance_jvm_memory_heap-20200714                                    wrQuh3llSeq7unYlswJslA 1 1   0    0    416b    208b
green open sw-qd-ny-t_instance_jvm_young_gc_count-20200714                                 dyHPdrB5Roy3o67zAF5wIg 1 1   0    0    416b    208b
green open sw-qd-ny-t_service_instance_relation_server_cpm-20200714                        o_9xbQAcRyycOhsdgGkxGA 1 1   0    0    416b    208b
green open sw-qd-ny-t_meter_instance_metrics_first_aggregation-20200714                    _0piYyCsRayYa66dNLSgmQ 1 1 622 6652 756.7kb 381.5kb
green open sw-qd-ny-t_meter_instance_mesh_analysis_error_count-20200714                    QxmisEWgSKixxf3djTASqg 1 1   0    0    416b    208b

---
I think ,maybe, there is a "dayStep" bug in the current image, and I cann't find it.
FYI

**Comment by wu-sheng** [comment]
I can't see the point of your logs. The data has been set back to 20200714. What is the error? What do you expect?

**Comment by weihuaxiong** [comment]
> I can't see the point of your logs. The data has been set back to 20200714. What is the error? What do you expect?

https://github.com/apache/skywalking/blob/8.0.1/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/base/TimeSeriesUtils.java
<img width="920" alt="截屏2020-07-19 15 18 05" src="https://user-images.githubusercontent.com/29908290/87869551-44eebb00-c9d3-11ea-9348-fb820119702b.png">

from 2000-01-01 to 2020-07-14 have 7500 days,
so when dayStep is 10, the index will create 20200704...20200714...20200724.

if dayStep is 9, from 2000-01-01 to 2020-07-11 have 7497 days, 7497%9 = 0
so the index shoud create 20200702...20200711...20200720.

and if dayStep is 8, from 2000-01-01 to 2020-07-18 have 7504 days, 7504%8 = 0
so the index shoud create 20200718...20200726...

**Comment by weihuaxiong** [comment]
> I can't see the point of your logs. The data has been set back to 20200714. What is the error? What do you expect?

https://github.com/apache/skywalking/blob/8.0.1/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/base/TimeSeriesUtils.java
<img width="920" alt="截屏2020-07-19 15 18 05" src="https://user-images.githubusercontent.com/29908290/87869771-c72baf00-c9d4-11ea-87f0-5af04ebf34a1.png">


from 2000-01-01 to 2020-07-14 have 7500 days,
so when dayStep is 10, the index will create 20200704...20200714...20200724.

if dayStep is 9, from 2000-01-01 to 2020-07-11 have 7497 days, 7497%9 = 0
so the index shoud create 20200702...20200711...20200720.

and if dayStep is 8, from 2000-01-01 to 2020-07-18 have 7504 days, 7504%8 = 0
so the index shoud create 20200718...20200726...

**Comment by wu-sheng** [comment]
I would not focus on that, if the algorithm has bug, ypu could test and debug easily. At least, feom your logs, the value should have been set, otherwise, the date should be today. I can't debug your local env or docker env. You need to find out which part has issue.
