### ISSUE TITLE
Plugin Config Loader

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#5130]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

A spi interface to load plugin config

### implementation
1. define a interface called Plugin Config
2. define a spi interface to load Plugin Config(all config schema is defined by submitter)
3. define a container to contain the plugin config,for example Map<class extends config loader spi,Plugin Config>
4. the container is shared with all agent plugins

**Comment by wu-sheng** [comment]
> define a interface called Plugin Config

Why do you need this? I think any class is suitable for Config initialization.

**Comment by wu-sheng** [comment]
> define a container to contain the plugin config,for example Map<class extends config loader spi,Plugin Config>

Read `SnifferConfigInitializer#initialize`. You just need a little refactor about this, and support to set a new Config Class. Such as providing a new method `public static void initialize(String agentOptions, Class<?> config)`.

**Comment by EvanLjp** [comment]
ok,i read this code first
