### ISSUE TITLE
spring gateway pathvariable URL having Parsing problem!!!

### ISSUE THREAD

**Issue by janecms** [apache/skywalking#5131]
### Bug
- Which version of SkyWalking, OS and JRE?
 
SkyWalking:8.0.1
JDK8

- Which company or project?
  Skywalking2.1.5.RELEASE

- What happen?
  When accessing /**/{pathvariable} type URL through the gateway。 the endointname style /**/1,/**/2 and many more.

![Screenshot_5](https://user-images.githubusercontent.com/3897037/87908412-ea1f9700-ca98-11ea-9cc7-82eaf46c9dd9.png)

___
### Requirement or improvement
My expected result is that the number variable fragment will be replaced with *。
For example, /user/1,/user/2 will eventually be converted to /user/*.
Can you tell me that it is okay to modify that module, or other solutions。

**Comment by wu-sheng** [comment]
Please don't use the `exclamation point` in your issue report. This is not a polite way in the writing. If you want to covert these, try backend endpoint grouping.

**Comment by janecms** [comment]
sorry.I will pay attention。

you say “try backend endpoint grouping”，Can you elaborate? or a blog  or  Provide a demo. or wiki?

Thanks

**Comment by janecms** [comment]
I found the solution from git. 
`through the static YAML file, named endpoint-name-grouping.yml`
