### ISSUE TITLE
SW_CORE_ROLE how to use in production 

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#5142]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
how to use SW_CORE_ROLE in production
___
### Question
- What do you want to know?
i find skywalking lost so many trace on production , and found the oap role.how to use it in production ,and Is there a best practice?

**Comment by EvanLjp** [comment]
l know how the way works.
i want to know the advantage when split 2 parts ,why have this mode.
Is it practical to propose such a solution in what scenarios

**Comment by wu-sheng** [comment]
When you want a super large OAP cluster, you may need to make network controllable or as planned. This role is helping you to make that. And it isolates the L1 and L2 aggregation, so your cluster performance should be more predictable, they would block each other or face race condition on CPU/thread scheduling.

**Comment by EvanLjp** [comment]
Is there some experience with the ratio of 2 parts,our applications will create over 900G data everyday. I am facing a very serious loss of behavior now
