### ISSUE TITLE
Is there some material to describe the agent's memory allocation and the difference between zipkin and skywalking?

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#5145]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by lsy1990** [comment]
The key point of this issue is how to manage memory when face to large depth tracing.

**Comment by wu-sheng** [comment]
SkyWalking provides the active span limitation, 300 in default. More than that, agent will not collect trace to avoid OOM. 
About Zipkin, you should ask at their channel.

**Comment by lsy1990** [comment]
Thanks a lot.
