### ISSUE TITLE
Question: No mapping found for HTTP request with URI [/registry/machine] in DispatcherServlet with name 'dispatcherServlet'

### ISSUE THREAD

**Issue by bjo2008cnx** [apache/skywalking#5146]
### Question
After I deploy skywalking,the console prints many statements as followings:
WARN 14218 --- [http-nio-8080-exec-2] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/registry/machine] in DispatcherServlet with name 'dispatcherServlet'

Could you please give some help? Many thanks.

**Comment by bjo2008cnx** [comment]
skywalking version:8.0.1

**Comment by wu-sheng** [comment]
Can't find out what is wrong. Can't link this to the agent. I think you should look deeper about logs.

**Comment by gaoweijie** [comment]
I have meet the same question, can you tell me how do you solve the issue?

**Comment by wz497345846** [comment]
同
