### ISSUE TITLE
ES index data suffix support config by date format 

### ISSUE THREAD

**Issue by dagmom** [apache/skywalking#5154]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
___
### Requirement or improvement

I want to make es index config by date format, eg. yyyyMMdd,yyyy-MM-dd or other pattern

There are other application's data besides skywalking's data in es, and move index of last week from ssd node to hdd node by job.

The job‘s migration index rule are based on index suffixes. So I hope  that index suffix can custom config.

**Comment by wu-sheng** [comment]
I think your private works, no matter what they are, are not the community concern. Anyone could submit this kind of request to many things. We can't and shouldn't make all things customizable.
