### ISSUE TITLE
Support Saturn

### ISSUE THREAD

**Issue by dagmom** [apache/skywalking#5155]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement

support [Saturn](https://github.com/vipshop/Saturn)

**Comment by wu-sheng** [comment]
> Saturn is originated from Dangdang's elastic job, we enhance it according to our requirement and understandings.

@terrymanu As you are the original author, I think I need your help to identify this lib. It says `originated from`, then how `from`? Is it a fork version?

**Comment by wu-sheng** [comment]
The key thing I want to be sure of is whether this lib has some IP issues. If it is a fork version, then all copy codes should keep the original license header, which means should have something about `dangdang.com`.

I was running the search, but only two source files have that header, https://github.com/vipshop/Saturn/search?q=dangdang.com&unscoped_q=dangdang.com

Is this accurate?

**Comment by terrymanu** [comment]
I am planning add ElasticJob agent, but no plan to Saturn for now.

**Comment by wu-sheng** [comment]
> I am planning add ElasticJob agent, but no plan to Saturn for now.

I was not asking about the plugin work, I am confirming the IP.

**Comment by terrymanu** [comment]
Saturn fork from ElasticJob and changed the copyright, I am not sure, but it seems like the IP is invalid.
Any idea?

**Comment by wu-sheng** [comment]
@dagmom I am afraid, based on @terranhu 's feedback. 

**Saturn fork from ElasticJob and changed the copyright**. This is a very serious license issue, based on elasticjob's original license, Apache 2.0, all headers should be kept, even they changed the codes. So, no matter you or anyone wants to do this plugin, we can't accept it as a part of Apache SkyWalking officially. If you know someone from them, please reach them. Only after they correct the license issue, and rollback all headers, we could support their new releases.

**Comment by dagmom** [comment]
@wu-sheng ok, I try to reach them, and rollback all headers

**Comment by wu-sheng** [comment]
Thanks for helping.

**Comment by dagmom** [comment]
@wu-sheng They have been rollback headers recently, please confirm. [https://github.com/vipshop/Saturn/commit/301f673857de8a62a1e069be6f84831318f8a132](https://github.com/vipshop/Saturn/commit/301f673857de8a62a1e069be6f84831318f8a132)

**Comment by wu-sheng** [comment]
@dagmom Do they have a release already? All ASF dependency requirements are based on release source codes.

**Comment by wu-sheng** [comment]
Closing as no update.
