### ISSUE TITLE
spring-annotation plugin component/layer show `Unknow` in backend

### ISSUE THREAD

**Issue by LiWenGu** [apache/skywalking#5157]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement

___
#### 1. spring-annotation plugin component

spring-annotation plugin component show `Unknow` in backend

SkyWalking version is: 8.0.1

![image](https://user-images.githubusercontent.com/15909210/88201436-06c6f500-cc7a-11ea-8ec6-96655219f7b6.png)

source code:       

https://github.com/apache/skywalking/blob/1877d0fcf41a320dc236c173c18b44f260e3c6f5/apm-sniffer/optional-plugins/optional-spring-plugins/spring-annotation-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/annotations/SpringAnnotationInterceptor.java#L27-L33

maybe we can add `SPRING_ANNOTATION` component, and then it will look like this:

![image](https://user-images.githubusercontent.com/15909210/88201383-f57de880-cc79-11ea-850c-4cd4afdbac6f.png)

#### 2. spring-annotation plugin layer

and we can add the `layer` for `SPRING_ANNOTATION`, Name it the `Local` layer?

https://github.com/apache/skywalking/blob/1877d0fcf41a320dc236c173c18b44f260e3c6f5/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/trace/SpanLayer.java#L21-L22

**Comment by wu-sheng** [comment]
You could add component, layer should be none, as it is related to rpc.
