### ISSUE TITLE
Skywalking 7.0.0-GA agent does not work properly with Spring Cloud Gateway

### ISSUE THREAD

**Issue by boystray** [apache/skywalking#5159]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [*] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
nothing
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 7.0.0
centos
JRE 1.8.0_11
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
when run java with agent , jvm abend with error 
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000040, pid=64560, tid=140172716922624

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

i have search some issues like 
#1865
#2556
#2686
#2872
but no answer. i have two server ,one is run OK,the other is run error.the difference is jdk version.
i feel the error is linked to jvm bug,so i upgrade the jdk from 1.8.0_11 to 1.8.0_161. 
it works
so please update jdk when meet the problem.

**Comment by wu-sheng** [comment]
So, this is a context for other user?
