### ISSUE TITLE
skywalking  in cluster mode ,   how does the alarm work？

### ISSUE THREAD

**Issue by githuyong** [apache/skywalking#5166]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question 

___
### Question
-  I have a skywalking cluster, but different alarm config, how does the alarm in each  skywalking server action？
   every skywalking backend have different alarm.yml , I wonder know the alarm behavior in cluster mode。
  thank you !

**Comment by wu-sheng** [comment]
This is not the design. If you want to know the result, read he source codes.
