### ISSUE TITLE
 When I set agent.sample_ N_ per_ 3_ When secs > 0, does it mean that the data I get is incomplete.

### ISSUE THREAD

**Issue by haolanzhong** [apache/skywalking#5167]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No, it wouldn't. Once it is sampled, it will be traced in the distributed env.

**Comment by haolanzhong** [comment]
By data, I mean all requests. I turn on sampling once every three seconds, which means that I will lose some requests。

**Comment by wu-sheng** [comment]
Sampling mean you will ignore some request. otherwise, why naming like this?
