### ISSUE TITLE
The Track displays incorrectly

### ISSUE THREAD

**Issue by a4215629** [apache/skywalking#5170]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ *] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
Windows , SkyWalking 7.0 ,  Elasticsearch 7.6.2,  java version "1.8.0_261"
- Which company or project?
skywalking
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

I did some test of track,   It displayed as not expected when I use Elasticsearch as storage
![image](https://user-images.githubusercontent.com/19680836/88394089-64318200-cdf1-11ea-8b39-f5b78a9a132a.png)

I think the right track should be this    /city ->  /WeatherForecast/4/3 .  
 And the Json data  proves it.  there are ony two segments  "/city"  and " /WeatherForecast/4/3 " , but there is a problem that the 
parentSegmentId  of endpoint "/WeatherForecast/4/3" is  3.18.15955943022620003  not the SegmentId of "/City" 3.18.15955943011290002.   I'm sure the "/city"  is the root endpoint.  why does this happen? 
![image](https://user-images.githubusercontent.com/19680836/88395347-83311380-cdf3-11ea-9e15-4f6ecfcb4eae.png)

And there is the json data as bellow.

{
    "data":{
        "trace":{
            "spans":[
                {
                    "traceId":"3.18.15955943011290001",
                    "segmentId":"3.18.15955943011290002",
                    "spanId":0,
                    "parentSpanId":-1,
                    "refs":[
                    ],
                    "serviceCode":"TestService1",
                    "startTime":1595594301129,
                    "endTime":1595594302374,
                    "endpointName":"/city",
                    "type":"Entry",
                    "peer":"::1",
                    "component":"AspNetCore",
                    "isError":false,
                    "layer":"Http",
                    "tags":[
                        {
                            "key":"url",
                            "value":"https://localhost:6001/city?city=ccccc"
                        },
                        {
                            "key":"path",
                            "value":"/city"
                        },
                        {
                            "key":"http.method",
                            "value":"GET"
                        },
                        {
                            "key":"status_code",
                            "value":"200"
                        }],
                    "logs":[
                        {
                            "time":1595594301129,
                            "data":[
                                {
                                    "key":"event",
                                    "value":"AspNetCore Hosting BeginRequest"
                                },
                                {
                                    "key":"message",
                                    "value":"Request starting HTTP/1.1 GET https://localhost:6001/city?city=ccccc"
                                }]
                        },
                        {
                            "time":1595594302374,
                            "data":[
                                {
                                    "key":"event",
                                    "value":"AspNetCore Hosting EndRequest"
                                },
                                {
                                    "key":"message",
                                    "value":"Request finished 200 application/json; charset=utf-8"
                                }]
                        }]
                },
                {
                    "traceId":"3.18.15955943011290001",
                    "segmentId":"2.4.15955943023310006",
                    "spanId":0,
                    "parentSpanId":-1,
                    "refs":[
                        {
                            "traceId":"3.18.15955943011290001",
                            "parentSegmentId":"3.18.15955943022620003",
                            "parentSpanId":0,
                            "type":"CROSS_PROCESS"
                        }],
                    "serviceCode":"TestService2",
                    "startTime":1595594302331,
                    "endTime":1595594302337,
                    "endpointName":"/WeatherForecast/4/3",
                    "type":"Entry",
                    "peer":"::1",
                    "component":"AspNetCore",
                    "isError":true,
                    "layer":"Http",
                    "tags":[
                        {
                            "key":"url",
                            "value":"https://localhost:5001/WeatherForecast/4/3"
                        },
                        {
                            "key":"path",
                            "value":"/WeatherForecast/4/3"
                        },
                        {
                            "key":"http.method",
                            "value":"GET"
                        },
                        {
                            "key":"status_code",
                            "value":"404"
                        }],
                    "logs":[
                        {
                            "time":1595594302331,
                            "data":[
                                {
                                    "key":"event",
                                    "value":"AspNetCore Hosting BeginRequest"
                                },
                                {
                                    "key":"message",
                                    "value":"Request starting HTTP/1.1 GET https://localhost:5001/WeatherForecast/4/3"
                                }]
                        },
                        {
                            "time":1595594302337,
                            "data":[
                                {
                                    "key":"event",
                                    "value":"AspNetCore Hosting EndRequest"
                                },
                                {
                                    "key":"message",
                                    "value":"Request finished 404 "
                                }]
                        }]
                }]
        }
    }
}

And  it display right when I use h2 as storage.
![image](https://user-images.githubusercontent.com/19680836/88393879-02711800-cdf1-11ea-81d2-e4644fe47272.png)

{
    "data":{
        "trace":{
            "spans":[
                {
                    "traceId":"3.10.15955949487730001",
                    "segmentId":"3.10.15955949487740002",
                    "spanId":0,
                    "parentSpanId":-1,
                    "refs":[
                    ],
                    "serviceCode":"TestService1",
                    "startTime":1595594948774,
                    "endTime":1595594950041,
                    "endpointName":"/city",
                    "type":"Entry",
                    "peer":"::1",
                    "component":"AspNetCore",
                    "isError":false,
                    "layer":"Http",
                    "tags":[
                        {
                            "key":"url",
                            "value":"https://localhost:6001/city?city=ccccc"
                        },
                        {
                            "key":"path",
                            "value":"/city"
                        },
                        {
                            "key":"http.method",
                            "value":"GET"
                        },
                        {
                            "key":"status_code",
                            "value":"200"
                        }],
                    "logs":[
                        {
                            "time":1595594948774,
                            "data":[
                                {
                                    "key":"event",
                                    "value":"AspNetCore Hosting BeginRequest"
                                },
                                {
                                    "key":"message",
                                    "value":"Request starting HTTP/1.1 GET https://localhost:6001/city?city=ccccc"
                                }]
                        },
                        {
                            "time":1595594950041,
                            "data":[
                                {
                                    "key":"event",
                                    "value":"AspNetCore Hosting EndRequest"
                                },
                                {
                                    "key":"message",
                                    "value":"Request finished 200 application/json; charset=utf-8"
                                }]
                        }]
                },
                {
                    "traceId":"3.10.15955949487730001",
                    "segmentId":"3.10.15955949499040003",
                    "spanId":0,
                    "parentSpanId":-1,
                    "refs":[
                        {
                            "traceId":"3.10.15955949487730001",
                            "parentSegmentId":"3.10.15955949487740002",
                            "parentSpanId":0,
                            "type":"CROSS_THREAD"
                        }],
                    "serviceCode":"TestService1",
                    "startTime":1595594949904,
                    "endTime":1595594950009,
                    "endpointName":"https://localhost:5001/WeatherForecast/4/3",
                    "type":"Exit",
                    "peer":"localhost:5001",
                    "component":"HttpClient",
                    "isError":true,
                    "layer":"Http",
                    "tags":[
                        {
                            "key":"url",
                            "value":"https://localhost:5001/WeatherForecast/4/3"
                        },
                        {
                            "key":"http.method",
                            "value":"GET"
                        },
                        {
                            "key":"status_code",
                            "value":"404"
                        }],
                    "logs":[
                    ]
                },
                {
                    "traceId":"3.10.15955949487730001",
                    "segmentId":"2.9.15955949499960001",
                    "spanId":0,
                    "parentSpanId":-1,
                    "refs":[
                        {
                            "traceId":"3.10.15955949487730001",
                            "parentSegmentId":"3.10.15955949499040003",
                            "parentSpanId":0,
                            "type":"CROSS_PROCESS"
                        }],
                    "serviceCode":"TestService2",
                    "startTime":1595594949996,
                    "endTime":1595594950003,
                    "endpointName":"/WeatherForecast/4/3",
                    "type":"Entry",
                    "peer":"::1",
                    "component":"AspNetCore",
                    "isError":true,
                    "layer":"Http",
                    "tags":[
                        {
                            "key":"url",
                            "value":"https://localhost:5001/WeatherForecast/4/3"
                        },
                        {
                            "key":"path",
                            "value":"/WeatherForecast/4/3"
                        },
                        {
                            "key":"http.method",
                            "value":"GET"
                        },
                        {
                            "key":"status_code",
                            "value":"404"
                        }],
                    "logs":[
                        {
                            "time":1595594949996,
                            "data":[
                                {
                                    "key":"event",
                                    "value":"AspNetCore Hosting BeginRequest"
                                },
                                {
                                    "key":"message",
                                    "value":"Request starting HTTP/1.1 GET https://localhost:5001/WeatherForecast/4/3"
                                }]
                        },
                        {
                            "time":1595594950003,
                            "data":[
                                {
                                    "key":"event",
                                    "value":"AspNetCore Hosting EndRequest"
                                },
                                {
                                    "key":"message",
                                    "value":"Request finished 404 "
                                }]
                        }]
                }]
        }
    }
}

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If segment data is not correct, then it is mot related to storage. Because if you have read the codes, we don't change anything about that, we just save the binary.
Maybe, it is caused by the your plugin doesn't work well in different cases, such as different concurrency payload.
