### ISSUE TITLE
Support storing the "latest" samples for meter system

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#5175]
The Meter system should support saving the lastest sample, the most common use case is to store the latest operation time. The format of the time is UNIX time(seconds/millisecond since Jan 01 1970.) 

FWIK, we should enhancement several parts:

OAP:
 - Add `LATEST` to `Function` enum
 - Add a `lastest` function to aggregate and save data points.
 - Update `readMetricsValue`(es, h2, influxdb....) in order to query lastest data.

UI:
 - Update option label "read avg value in duration" in the metric configuration field. Because we use `readMetricsValue` to load avg, sum and latest value, I suggest using "read the single value in duration"
 - Add a new function, timestamp, to convert raw UNIX/Java time to a human-readable format.

**Comment by wu-sheng** [comment]
> Update option label "read avg value in duration" in the metric configuration field. Because we use readMetricsValue to load avg, sum and latest value, I suggest using "read the single value in duration"

Is this just a text changing?

> Add a new function, timestamp, to convert raw UNIX/Java time to a human-readable format.

Why is this related to UI? I think we don't do this in all query definition.

**Comment by wu-sheng** [comment]
> Add a lastest function to aggregate and save data points.

Pay attention about this expression. In the downsampling case, this will be a very tricky situation.

**Comment by wu-sheng** [comment]
@Fine0830 I think, for now, we just need to change the text `read avg value in duration` to `read the single value in duration`

**Comment by hanahmily** [comment]
After a talk with @Sheng in person, UI should provide a new result function to format UNIX date to human-readable format. @Fine0830  The function should meet the following requirements:

 - Convert UNIX Time, which is seconds since Jan 01, 1970.
 - Convert Java Time, which is milliseconds since Jan 01, 1970.
 - Format date and time based on a template. 
 - Display date and time in any timezone.
