### ISSUE TITLE
Support dynamic labels in meter-system

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#5186]
Some labels in Prometheus practice can't be predicted by users previously, in another word, they are not in a limit range or their all candidates can't be recognized. 
For example, a label indicates the `kind` of Kubernetes resource, not only there are a number of official resources, for instance, deployment, statefulset, service and etc, but users can also define any custom resource they want. 

Based on the above requirement, we should support ingesting dynamic labels into the meter-system. 

A potential list of changes might be:

 - Add a new function to store multiple labels in one single line. 
 - Update labeled query to support fetching all of the values.
 - Update the alarm submodule to support configuring rules based on label values. 
 
@Fine0830 Would you please confirm if users don't set up any labels to label select template, UI also can display a chart based on the labels queried from graphql?

**Comment by Fine0830** [comment]
@hanahmily Now, UI is able to support the requirement without labels.

**Comment by wu-sheng** [comment]
I have merged the pull request, the UI submodule has not been updated, please recheck the status.

**Comment by Fine0830** [comment]
I have updated the UI submodule.

**Comment by hanahmily** [comment]
Thanks to @Fine0830 's contribution and @wu-sheng 's review, we have finished all of subtasks.
