### ISSUE TITLE
log4j1.x can't get trace ID used in spring cloud gateway

### ISSUE THREAD

**Issue by Glenrun** [apache/skywalking#5188]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I was using log4j1.2.17 in our spring cloud gateway, and I configured [%T] in TraceIdPatternLayout param, but it seems log4j can't get trace id at any time, it always shows [TID: N/A], does it have something to do with multiple thread?
___
### Bug
- Which version of SkyWalking, OS and JRE?
8.0.0
- Which company or project?
CCB

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We haven't done any test about `getting trace id` in this case. If you want trace id available, I think you have to make sure the thread your codes running has been instrumented, which mean having TracingContext.

**Comment by Glenrun** [comment]
so will the test be done on 8.1.0? @wu-sheng
