### ISSUE TITLE
为什么没有中文文档？为什么只允许英文？

### ISSUE THREAD

**Issue by EasyProgramming** [apache/skywalking#5191]
我寻思这项目不是国人开发的吗？有个双语文档很难吗？别人用中文提问问题，作者回复一个“english only”，好厉害哦，高人一等喔，都0202年了，不会还有人感觉文档用英语写就是国外开源项目吧？不会吧，不会吧

**Comment by boystray** [comment]
english pls。

**Comment by wu-sheng** [comment]
We are hosted in the Apache Software Foundation. We just ask for English on GitHub and Apache mail list, as the official channel, we need a global language. If you want to use Chinese, we support that in the QQ group.

**Comment by wu-sheng** [comment]
> 我寻思这项目不是国人开发的吗？

I am a Chinese and Mandarin is my native language, this is for sure. But SkyWalking today is not only written by me, also is not written by Chinese people only. We have users/contributors/committers all over the world, English is not the native language for many of them too. But we need to communicate, that is why we choose English, that is the reason.

**Comment by wu-sheng** [comment]
> 有个双语文档很难吗？

That is not about the hard and easy, that is workload. We have volunteers working on that, if you have simply searched the GitHub, you have already found that, rather than complaining here. https://github.com/SkyAPM/document-cn-translation-of-skywalking.
But we can't guarantee it is always updated, and it is always correct. as it is not official and out of date multiple times, it can't be listed in the Apache repo.

**Comment by EasyProgramming** [comment]
> > 有个双语文档很难吗？
> 
> That is not about the hard and easy, that is workload. We have volunteers working on that, if you have simply searched the GitHub, you have already found that, rather than complaining here. https://github.com/SkyAPM/document-cn-translation-of-skywalking.
> But we can't guarantee it is always updated, and it is always correct. as it is not official and out of date multiple times, it can't be listed in the Apache repo.

Thanks

**Comment by saxingz** [comment]
哪里来的小学生，没人求着你看。人家的项目，就算用日语写文档也是别人的自由。

**Comment by EasyProgramming** [comment]
> 哪里来的小学生，没人求着你看。人家的项目，就算用日语写文档也是别人的自由。

狗东西，说谁小学生呢？会不会说话，不会说话，滚尼玛娘胎里面回来重造，再跟爷说话

**Comment by EasyProgramming** [comment]
> 哪里来的小学生，没人求着你看。人家的项目，就算用日语写文档也是别人的自由。

cnm
