### ISSUE TITLE
 What role does zookeeper play in a cluster. I found that instead of setting up zookeeper, I only need to configure multiple addresses on UI and agent

### ISSUE THREAD

**Issue by haolanzhong** [apache/skywalking#5195]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
There is distributed aggregation. Zookeeper or other coordinators are required, this is not about load balance.
