### ISSUE TITLE
[QUESTION] The trace data didn't be collected by the commucation of the master and worker.

### ISSUE THREAD

**Issue by lgcareer** [apache/skywalking#5199]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I started the master service and worker service with the argument `-javaagent:/opt/app/apache-skywalking-apm-bin/agent/skywalking-agent.jar -Dskywalking.agent.service_name=master` and `-javaagent:/opt/app/apache-skywalking-apm-bin/agent/skywalking-agent.jar -Dskywalking.agent.service_name=worker`

###1Backgound
The master and worker service is the java process.
The master service communiation with the worker service through netty tcp protocol.

###2Question I FOUND
First,I saw the topology and it didn't show the relation of the master and worker.
![image](https://user-images.githubusercontent.com/15651066/88795105-0f678000-d1d2-11ea-8274-db7c28cef233.png)

Second,I saw the trace data didn't be collected by the commucation of the master and worker.

**Comment by wu-sheng** [comment]
Check the supported list document. And TCP is private network protocol, can't be auto instrumented.
