### ISSUE TITLE
test skywalking-nginx-lua-0.1.0 fail

### ISSUE THREAD

**Issue by ysj2018** [apache/skywalking#5201]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking6.4
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
I test  skywalking-nginx-lua-0.1.0 in linux,  but  occured a mistake： [error] 36891#0: *26 [lua] client.lua:239: reportTraces(): 5 segments reported., context: ngx.timer  。 
![image](https://user-images.githubusercontent.com/38675772/88804090-02ea2400-d1e0-11ea-9baf-88b27718acae.png)
queue’s segment put    res.body in client.lua  。 I console res.body,  but it is nothing . 
please tell me why？thanks very much！
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
1. nginx1.14.2
2.luajit2.0.5
3.luarocks3.3.1

**Comment by ysj2018** [comment]
![image](https://user-images.githubusercontent.com/38675772/88805386-adaf1200-d1e1-11ea-8862-73255158b10d.png)

**Comment by ysj2018** [comment]
![image](https://user-images.githubusercontent.com/38675772/88805482-c9b2b380-d1e1-11ea-9ea2-dfd30e4c7aef.png)
res.status is 200   but res.body  is nothing,

**Comment by wu-sheng** [comment]
- 0.1.0 release requires SkyWalking 7
- 0.2.0+ releases require SkyWalking 8

https://github.com/apache/skywalking-nginx-lua#download is clear about this.
