### ISSUE TITLE
 prometheus fetcher can‘t pull metrics

### ISSUE THREAD

**Issue by blank-1** [apache/skywalking#5204]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 how to pull prom  metrics
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 8.0.1  
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/30788027/88873374-197b9400-d24f-11ea-8ba9-eb9d3d372776.png)
![image](https://user-images.githubusercontent.com/30788027/88873395-28fadd00-d24f-11ea-829f-ecf18c185c16.png)
![image](https://user-images.githubusercontent.com/30788027/88873355-0f599580-d24f-11ea-8a76-8d27cc3151a2.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Without metrics rule, nothing will happen. SkyWalking is based on pre-calculation, even we accept Prometheus format, nothing changes there. The document requires you to config those rules clearly.

**Comment by blank-1** [comment]
how to do?prom-fetcher.yml is not metric setting?

**Comment by wu-sheng** [comment]
> how to do?prom-fetcher.yml is not metric setting?

You changed your issue description after submit, please don't do this again, other people can't follow the context.

Several things, 
1. Make sure source is correct, really exist in the Prometheus.
1. You are doing `rate in 5 mins`, so the metrics will be valid after 5 mins clearly.
1. Why a `service` level metric has instance `relabel`?

There is a lot of rules and codes in there, all things start at `PrometheusFetcherProvider#notifyAfterCompleted`. It should be easy to debug by yourself.

**Comment by blank-1** [comment]
![image](https://user-images.githubusercontent.com/30788027/88874450-b0e1e680-d251-11ea-8b35-a1d688af76ea.png)
prom metrics page can get graph!

**Comment by wu-sheng** [comment]
There is no point in proving Prometheus itself is working. You are just fetching data in Prometheus format. Nothing related to the Prometheus server.

**Comment by blank-1** [comment]
metrics  need add ’meter_‘ prefix

**Comment by wu-sheng** [comment]
@blank-1 Welcome to send a pull request to make the document more clear.

**Comment by wu-sheng** [comment]
@blank-1 I rechecked the document, the description is included already in the YAML file format definition.

https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-fetcher.md#metric_rules

**Comment by blank-1** [comment]
sw ui graph can't  get metric data . setting right, es index is exist,ui can get metric, and prom metric url can show real graph !

**Comment by wu-sheng** [comment]
Check the data in the index. Query is not related to Prometheus in anyway. It is as same as the native matrics.
