### ISSUE TITLE
have some config for redis to print redis trace param on skywalking ui?similar as plugin.mysql.trace_sql_parameters of agent

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#5207]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If there isn't this config in the document, then we haven't provided it yet. If you want, consider contributing to this.
