### ISSUE TITLE
useing the skywalking agent with jdk1.7

### ISSUE THREAD

**Issue by liheng0507** [apache/skywalking#5222]
Can I run the agent with java  project,which the jdk version is 1.7.0.15?

**Comment by liheng0507** [comment]
I use the 6.1.x skywalking agent and 8.0.0 skywalking server,would it work successfully?

**Comment by kezhenxu94** [comment]
> I use the 6.1.x skywalking agent and 8.0.0 skywalking server,would it work successfully?

No, when using SkyWalking agent 6.x, you can only use backend server under 8.0(6.x ~ 7.x)

**Comment by liheng0507** [comment]
my java project version are  all base on the jdk1.7，so won‘t I use the 8.0.0 skywalking and get new experience？

**Comment by wu-sheng** [comment]
No, you can't. This is based on 2019 community survey,  https://lists.apache.org/thread.html/40aaca56504e69040ea94d37aac5ab540cf60fb49444663621fa170b%40%3Cdev.skywalking.apache.org%3E

**Comment by liheng0507** [comment]
Ok,I will still use the 6.x skywalking,thanks~
