### ISSUE TITLE
gateway and microservice get trace inconsistent in one request

### ISSUE THREAD

**Issue by apple987** [apache/skywalking#5227]
Skywalking requests the gateway at one time and goes through microservice processing. The microservice uses thread pool inside and log4j2 for all. The execution results check the log. The traceid obtained in gateway and microservice is different. Moreover, the traceid obtained by opening sub thread in microservice is also different from that obtained by main thread. What's the matter? Skywalking version 6.6.0

**Comment by wu-sheng** [comment]
Choose 8.0+ for testing. @acurtain did some fixes in the 8.x

**Comment by apple987** [comment]
hi! i have test this with 8.1.0，but the gateway get traceId [TID:28e3fa62fda14ab0b7d668f3c155d987.535.15967849635830003]
and the service get traceId [TID: 28e3fa62fda14ab0b7d668f3c155d987.535.15967849635820001] in one request,the gateway plguin has added into agent\plugins,they are still different! 
why?need help!

**Comment by dodomao** [comment]
This problem has always been, so only oneself add a similar requestid parameter in the request, the gateway log and micro service log strung together, and then in turn fix gateway traceid
