### ISSUE TITLE
Implement browser metrics in a new page

### ISSUE THREAD

**Issue by Fine0830** [apache/skywalking#5228]
Visualize browser metrics in UI, as follow
![one](https://user-images.githubusercontent.com/20871783/89266357-66ed6c00-d668-11ea-9b85-2ad0c6388ed3.jpeg)
![two](https://user-images.githubusercontent.com/20871783/89266376-6b198980-d668-11ea-9266-d6be03fc1504.jpeg)

cc: @Jtrust

**Comment by Jtrust** [comment]
👌

**Comment by Jtrust** [comment]
Maybe could we try to replace the bar chart with a line chart？ Because the line chart can better show the trend of the data over time. @Fine0830

**Comment by wu-sheng** [comment]
@Jtrust I saw the prototype pages, only comparison charts are using the bar chart. Which one are you asking?

**Comment by Jtrust** [comment]
![image](https://user-images.githubusercontent.com/21056967/89796717-8dc20b80-db5c-11ea-97ef-a2ba426194dd.png)

@wu-sheng App PV and Error sum in the duration

**Comment by Fine0830** [comment]
> Maybe could we try to replace the bar chart with a line chart？ Because the line chart can better show the trend of the data over time. @Fine0830

Sure. Line and bar are linear charts,  so they can do both.

**Comment by wu-sheng** [comment]
Oh, if that is for one app, or one page, then yes, it should be a linear graph

**Comment by wu-sheng** [comment]
The first version will be provided through #5686

**Comment by wu-sheng** [comment]
One last thing is the log page seems to have some incorrect names.
