### ISSUE TITLE
feign-plugin support collecting feign params

### ISSUE THREAD

**Issue by zshit** [apache/skywalking#5233]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- feign-plugin support collecting feign request params.

**Comment by fly7632785** [comment]
你好  这个插件目前能使用吗？
这边在寻找 调用feignClient  收集其参数的方法
包括使用apm-toolkit-trace 这个库
但是它不支持 在feignclient的service方法上加@Trace注解等收集 其参数信息
