### ISSUE TITLE
why the oal filter op such as  "like,!=" is not working

### ISSUE THREAD

**Issue by gnr163** [apache/skywalking#5234]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
8.0.1
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
  - example1 
    - oal : endpoint_cpm = from(Endpoint.*).filter(name like ("serv%")).cpm();
    - error: ![image](https://user-images.githubusercontent.com/13776957/89369498-d6b73180-d710-11ea-8134-8f0fa38c55b3.png)
  - example2
    - oal:  endpoint_cpm = from(Endpoint.*).filter(name != "test").cpm();
    - error: 
![image](https://user-images.githubusercontent.com/13776957/89369547-02d2b280-d711-11ea-99e5-1366e4e9a5af.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
That is a grammar tree. No one implements this yet. Contributions are welcome.
