### ISSUE TITLE
how do I customize the instance name?

### ISSUE THREAD

**Issue by thanq** [apache/skywalking#5237]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- In skywalking8, the instance name is begin with meaningless character string,  how do I customize the instance name?

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
![image](https://user-images.githubusercontent.com/806891/89376427-484bab80-d722-11ea-8852-89cd83a04d9b.png)

**Comment by wu-sheng** [comment]
Read agent setup doc. It is there.
