### ISSUE TITLE
Topology display optimization（Three-color marker）

### ISSUE THREAD

**Issue by blank-1** [apache/skywalking#5239]
- [ v] Feature or performance improvement
The topology map function is optimized. According to the configuration of alarm rules and metric rules, the topology map displays different color states (such as red: for error or alarm, yellow: for high load, green: normal), making the display of the topology map more intuitive

**Comment by wu-sheng** [comment]
If we want to do, we will base on apdex score. Read the latest blog.

**Comment by wu-sheng** [comment]
This is the better way to measure health status

- EN, http://skywalking.apache.org/blog/2020-07-26-apdex-and-skywalking.html
- CN, http://skywalking.apache.org/zh/blog/2020-07-26-apdex-and-skywalking.html

**Comment by wu-sheng** [comment]
`legend` for red and common services are added in 8.4.0, but only according to Apdex.
