### ISSUE TITLE
question about no statement with slowStatement

### ISSUE THREAD

**Issue by gnr163** [apache/skywalking#5243]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 The code [MultiScopesAnalysisListener.java@213     statement.setStatement("[No statement]/" + sourceBuilder.getDestEndpointName());] 
sourceBuilder.getDestEndpointName() is null, why not use span.getOperationName() ? Is this a deliberate design ?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read how we set the dest endpoint name, which is exactly the operation name. Please recheck.

**Comment by wu-sheng** [comment]
OK, I think I get your point, that is a bug when updating 8.x

**Comment by wu-sheng** [comment]
Please submit a pull request to fix this. Should use `#getOperationName` of the span.
