### ISSUE TITLE
PreparedStatement is missing a constructor intercept？

### ISSUE THREAD

**Issue by HackerRookie** [apache/skywalking#5248]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
PreparedStatement is missing a constructor intercept and gets StatementEnhanceInfos with an NPE exception when executing the method.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please more details or demo, it is impossible to answer this kind of question.
