### ISSUE TITLE
how to mange es shards allocation

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#5251]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
nowadays, we meet We have a very serious imbalance problem with ES shards.
because the metrics shards has too much,and the data is quite small
so many segment index shards is allocated to one node. This leads to very serious performance problems.

![image](https://user-images.githubusercontent.com/31562192/89490048-6d9def80-d7de-11ea-9c99-90a574af9abc.png)

___
### Question
- What do you want to know?
is there some practice to solve it?
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
1. i found some settings But I'm not sure it will work
![image](https://user-images.githubusercontent.com/31562192/89490148-bbb2f300-d7de-11ea-858e-90dfc57f0b8b.png)
2. some suggestion:
record store in one es storage.
metrics store in another es storeage.

**Comment by wu-sheng** [comment]
So, are you trying to say, the shards of segment indexes are not balanced by the ElasticSearch cluster automatically?

**Comment by EvanLjp** [comment]
elasticsearch defalut balanced shards on cluster level.
so some case: one node have 20 metrics shards and 10 records shards. another has 20 record shards and 10 Metrics shards.

at cluster level. all nodes is balanced.
but in node level. not balance

**Comment by EvanLjp** [comment]
i think the effect on ES is too much metrics shards.The amount of data is not a problem for ES.the problem is create to many small shards in elasticsearch

**Comment by wu-sheng** [comment]
So basically, this is caused by the size of the metrics set is much smaller than the size of the trace dataset. Right? If so, I would like to ask you, consider to enhance `StorageModuleElasticsearchConfig#dayStep`.

```java
    /**
     * Since 6.4.0, the index of metrics and traces data in minute/hour/month precision are organized in days. ES
     * storage creates new indexes in every day.
     *
     * @since 7.0.0 dayStep represents how many days a single one index represents. Default is 1, meaning no difference
     * with previous versions. But if there isn't much traffic for single one day, user could set the step larger to
     * reduce the number of indexes, and keep the TTL longer.
     */
    @Getter
    private int dayStep = 1;
```

According to your case, we should add a new config for `dayStepForRecord`, which default is `-1`, meaning disabled. Then the codes still use `dayStep = 1`.
But to resolve your issue, you could set `dayStep = 7`(or more) and `dayStepForRecord = 1`, then the number of index(es) and shards decrease clearly. Then the ElasticSearch LB mechanism should be back to work again.

@EvanLjp If you like this, we should forward this change to the mail list before we change the codes(PR).

FYI @apache/skywalking-committers WDYT?

**Comment by EvanLjp** [comment]
@wu-sheng it's a good feature. This is the same idea as @SuperDataset

**Comment by wu-sheng** [comment]
Yes, it is quite similar. Actually, that is why we need `Record` and `Metrics` for the first time. We just aren't sure how difference they will be. More use cases drive us to provide more reasonable configurations, with good explanations about why we need them, and how we use them.

**Comment by wu-sheng** [comment]
Please send a mail to the mail list, with your issues and recommended solutions. Also, notice, the images are not working there. Try to use texts and static URLs provided by GitHub.

**Comment by EvanLjp** [comment]
ok

**Comment by wu-sheng** [comment]
@EvanLjp BTW, I think you should write an optimization blog about how to use these configurations in the production environment one day. This would be helpful for many people, who don't understand the source codes very well.

**Comment by EvanLjp** [comment]
no problem
