### ISSUE TITLE
is there any solution about io.netty.channel

### ISSUE THREAD

**Issue by whfjam** [apache/skywalking#5260]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
My service has the output use netty like "ChannelFuture  io.netty.channel.write(Object var1);"  but i have not fount any enhancements about that，so the trace-chain is broken，do you have any ideas about that ， thanks a lot！

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Because that is your private TCP level protocol, there is no header we could inject. So, wouldn't be any plugin for all TCP communication. But, at the same time, as you should know your protocol, you could build a plugin for your own.

**Comment by whfjam** [comment]
> 
> 
> Because that is your private TCP level protocol, there is no header we could inject. So, wouldn't be any plugin for all TCP communication. But, at the same time, as you should know your protocol, you could build a plugin for your own.

i got that ， thanks a lot！
