### ISSUE TITLE
Why does trace always return the last 400 spans？Is this a UI design issue?

### ISSUE THREAD

**Issue by heshang233** [apache/skywalking#5262]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [×] Bug
- [×] Requirement
- [×] Feature or performance improvement

___
### Question
- What do you want to know?
Why does trace always return the last 400 spans？Is this a UI design issue?
___
### Bug
- Which version of SkyWalking, OS and JRE?
8.0.1   linux   jre8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/13328402/89611914-fedd9680-d8b0-11ea-9614-7b69aec7c5af.png)
![image](https://user-images.githubusercontent.com/13328402/89611944-187ede00-d8b1-11ea-80a7-f02147678985.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by heshang233** [comment]
I checked the segment data and found that there are 1565 pieces of data, but there is no information I want. It should be lost data.

**Comment by wu-sheng** [comment]
I am not following your context. What do you mean lost? And which part do you mean?

**Comment by heshang233** [comment]
> I am not following your context. What do you mean lost? And which part do you mean?

If once trace calls too many other services, then leads to a lot of segment data, how to ensure that segment data is not lost？

**Comment by heshang233** [comment]
https://github.com/apache/skywalking/issues/2504
By modifying the oap configuration parameter SW_STORAGE_ES_QUERY_SEGMENT_SIZE=2000, all spans can be seen
