### ISSUE TITLE
buffer blocking strategy

### ISSUE THREAD

**Issue by LiWenGu** [apache/skywalking#5267]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

https://github.com/apache/skywalking/blob/9b6a4ed28ce957238851cb0a504ff8ad3c74e59b/apm-commons/apm-datacarrier/src/main/java/org/apache/skywalking/apm/commons/datacarrier/buffer/Channels.java#L33-L45

https://github.com/apache/skywalking/blob/9b6a4ed28ce957238851cb0a504ff8ad3c74e59b/apm-commons/apm-datacarrier/src/main/java/org/apache/skywalking/apm/commons/datacarrier/buffer/Buffer.java#L42-L61

From the initialization code of `Channels`, we can know that `Buffer` is never a `BLOCKING` strategy. What does this line of code mean(Buffer.java#L46-L53)?

**Comment by wu-sheng** [comment]
They were just legacy codes, right now the block mode is. using `ArrayBlockingQueueBuffer`. It used to be the internal block.
If you like, submit a pull request to remove them.
