### ISSUE TITLE
My log can't get traceId when I use Spring Cloud Gateway in my project ,all traceId in my log is "[traceId:TID:N/A]"

### ISSUE THREAD

**Issue by wwwlla** [apache/skywalking#5268]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Bug

___
### Question
- What do you want to know?
How can I get traceId in my log when I use Spring Cloud Gateway ,all traceId in my log is "[traceId:TID:N/A]".
The log get traceId can work well in other project
___
### Bug
- Which version of SkyWalking, OS and JRE?
       version of SkyWalking :  8.2.0  （use SpringCloudGateWay and apm-spring-cloud-gateway-2.1.x-plugin）
       OS:   windows and linux
       JRE:   java8
       

- What happened?
When this happen, I try move "ContextManager.stopSpan(span);" from  beforeMethod to afterMethod in DispatcherHandlerHandleMethodInterceptor. When I did this, log has traceId,but in SkyWalking server ,one traceId has a lot of API

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wwwlla** [comment]
version of SpringCloudGateway in my project is 2.2.3

**Comment by Lovnx** [comment]
You should set TraceId into ServerWebExchange in the agent, so that you will get TraceId from ServerWebExchange attribute.

**Comment by Lovnx** [comment]
Modify spring-webflux like this:
![image](https://user-images.githubusercontent.com/26428832/92846241-722b7880-f41a-11ea-8d2e-4763e400c526.png)

in your SCG project:
String TraceId = serverWebExchange.getAttribute("global.trace.id");

**Comment by wu-sheng** [comment]
We have no plan to set trace id in user codes to avoid conflict.

**Comment by Lovnx** [comment]
> We have no plan to set trace id in user codes to avoid conflict.

But, in async scenario, There is no way to get TraceId of per request, must relate to Context.

**Comment by wu-sheng** [comment]
It should relate to context, which relating to it is the question.

**Comment by wu-sheng** [comment]
The concern of this change is, if user use the same key, it breaks. And this provide the different API to end users, it is confused to users.

**Comment by Lovnx** [comment]
Why not give the authority to the user to decide the key name by config file instead of providing API?

**Comment by wu-sheng** [comment]
Bit still two API. We never did this before. Because  one day, you could ask for tag, log or new span in the context. 
We have to fix the thing in right theory, rather than keep breaking things.

**Comment by Lovnx** [comment]
So...Back to the beginning, How to get TraceId correcttly in SCG :)

**Comment by wu-sheng** [comment]
@ascrutae is doing some tests, that is why this PR is assigned to him.

**Comment by 9989836** [comment]
@ascrutae  We need to record traceid in SCG.  How to achieve it?

**Comment by pkbrown608** [comment]
any update regarding this issue? i am also frustrated about this

**Comment by xiaoyao2246** [comment]
any update regarding this issue? i am also frustrated about this

**Comment by 295black** [comment]
any update regarding this issue? i am also frustrated about this

**Comment by aliuql** [comment]
i am also frustrated about this
