### ISSUE TITLE
DNS-1035 label must consist of lower case alphanumeric characters - Kubernetes Helm Install

### ISSUE THREAD

**Issue by vishvarodrigo** [apache/skywalking#5278]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [✓]  Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 8.0.1, Google Kubernetes Engine, Java8

- Which company or project?
I'm looking for reliable opensource APM solution for all of my projects

- What happened?
I have created gke cluster with the kubernetes version 1.15.12-gke.2.  As per the readme.md, successfully completed the first 3 steps,

```
$ cd chart
$ helm repo add elastic https://helm.elastic.co
$ helm dep up skywalking
```
Final step was to run the below command

`helm install <release_name> skywalking -n <namespace>`

But, when i run the command it says,
<img width="1430" alt="Screenshot 2020-08-09 at 13 30 56" src="https://user-images.githubusercontent.com/20195427/89727691-a212e500-da44-11ea-831f-f93adf7bbc01.png">

**Comment by wu-sheng** [comment]
@innerpeacez Please take a look.

**Comment by innerpeacez** [comment]
`release_name` can only be lower case alphanumeric characters or '-', The error prompt has given the answer. You can try this. 
```
helm install skywalking skywalking -n skywalking
```
@vishvarodrigo
