### ISSUE TITLE
storage es often appear problem

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#5284]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
when data volume is big，query data of 80% by skywalking ui,often appear error，have good method to resolve the problem？

{"errors":[{"message":"Exception while fetching data (/services) : Elasticsearch exception [type=circuit_breaking_exception, reason=[parent] Data too large, data for [<http_request>] would be [1005165112/958.6mb], which is larger than the limit of [986061209/940.3mb], real usage: [1005163472/958.5mb], new bytes reserved: [1640/1.6kb], usages [request=0/0b, fielddata=193162/188.6kb, in_flight_requests=500152/488.4kb, accounting=58193669/55.4mb]]"}]}
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 7.0，os linux，jre jdk8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is ES or network issue. It says, you read too many data, I don't know why

> data for [<http_request>] would be [1005165112/958.6mb], which is larger than the limit of [986061209/940.3mb],

Do you really have so many data for service query?
