### ISSUE TITLE
skywalking-python not trace request

### ISSUE THREAD

**Issue by shuguang-dong** [apache/skywalking#5285]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- I learn skywalking-python by this page: https://github.com/apache/skywalking-python
after agent.start(),only create instance,but not track any request.  
when agent.start(), I also start my django server and request some api, then I view skywalking admin page,only see instance created but not trace any request info.  
### My fremework info:   
- Python-3.7  
- Djano-2.1.3  
- skywalking-python-0.2.0

**Comment by kezhenxu94** [comment]
@shuguang-dong please set the logging level(`config.logging_level`) to `DEBUG` and paste your logs here

**Comment by kezhenxu94** [comment]
Perhaps you just hit the incompatibility of Django plugin, which is [fixed in the master branch](https://github.com/apache/skywalking-python/pull/52) but not included in the 0.2.0, if possible, please try to [build from the master branch](https://github.com/apache/skywalking-python/blob/master/docs/FAQ.md#q-how-to-build-from-sources) codes and tell us whether it helps, or try a newer Django version (> 2.2), thanks

**Comment by shuguang-dong** [comment]
This is my code:  
```
from skywalking import agent, config

config.init(
    service='shenlong-kol',
    instance='dev-local',
    collector='my sky walking address',
)
agent.start()
```
and I debug it in pycharm ,here is log:  
```
sw_flask                         [MainThread     ] [WARNING ] failed to install plugin sw_flask
sw_kafka                         [MainThread     ] [WARNING ] failed to install plugin sw_kafka
sw_tornado                       [MainThread     ] [WARNING ] failed to install plugin sw_tornado
```

I will also try a newer Django version(>2.2) again

**Comment by alonelaval** [comment]
I tested Django==3.1, apache-skywalking==0.2.0.  it worked well
```
import sys
import time

from skywalking import agent, config

from django.conf import settings
from django.conf.urls import url
from django.http import JsonResponse


config.service_name = "provider"
config.logging_level = "DEBUG"
agent.start()


settings.configure(
    DEBUG=True,
    ROOT_URLCONF=__name__,
    ALLOWED_HOSTS=['*'],
)


def index(request):
    time.sleep(0.5)
    return JsonResponse({"song": "Despacito", "artist": "Luis Fonsi"})


urlpatterns = (
    url("users", index),
)


if __name__ == "__main__":
    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
```
cmd: python3 test_django.py runserver 0.0.0.0:9090

**Comment by wu-sheng** [comment]
I think the key may be this `I will also try a newer Django version(>2.2) again`

**Comment by kezhenxu94** [comment]
> I tested Django==3.1, apache-skywalking==0.2.0. it worked well @shuguang-dong
> 
> ```
> import sys
> import time
> 
> from skywalking import agent, config
> 
> from django.conf import settings
> from django.conf.urls import url
> from django.http import JsonResponse
> 
> 
> config.service_name = "provider"
> config.logging_level = "DEBUG"
> agent.start()
> 
> 
> settings.configure(
>     DEBUG=True,
>     ROOT_URLCONF=__name__,
>     ALLOWED_HOSTS=['*'],
> )
> 
> 
> def index(request):
>     time.sleep(0.5)
>     return JsonResponse({"song": "Despacito", "artist": "Luis Fonsi"})
> 
> 
> urlpatterns = (
>     url("users", index),
> )
> 
> 
> if __name__ == "__main__":
>     from django.core.management import execute_from_command_line
> 
>     execute_from_command_line(sys.argv)
> ```
> 
> cmd: python3 test_django.py runserver 0.0.0.0:9090

It's quite expected because we run the test cases over and over in the CI, and I'm pretty sure it's just a version incompatibility issue fixed by @Humbertzhang in https://github.com/apache/skywalking-python/pull/52 in the master branch now(not included in the 0.2.0), I'll close this for now and if you @shuguang-dong have any further question, please comment here

**Comment by wu-sheng** [comment]
@kezhenxu94 I think python agent should follow the java supported list doc style, add versions there.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 I think python agent should follow the java supported list doc style, add versions there.

Versioning the supported libraries as well as the tests is under construction by @Humbertzhang and I, will open another issue to track that
