### ISSUE TITLE
Get spanId by calling core API "ContextManager.activeSpan().getSpanId()" and print in log, however, seems always is '0', does'nt match actual returned spanIds in webapp  console.

### ISSUE THREAD

**Issue by wxk123** [apache/skywalking#5287]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We don't provide this feature. How do you do this?
