### ISSUE TITLE
[Proposal] [UI] Active Agent Check on UI

### ISSUE THREAD

**Issue by tarunwadhwa13** [apache/skywalking#5290]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [o] Feature or performance improvement

___
### Requirement or improvement
It is really difficult to know from UI which service is actively pushing data to Skywalking. It would be great if we can have a toggle for live data check (services or instances for which data was reported in say last 15 min). Or a tab where user can see registered agents pushing data and last push time. 
Currently data stop can be found using traces tab that too when all agents stop pushing data

**Comment by wu-sheng** [comment]
The instance list should be queried based on the time range you selected.

**Comment by wu-sheng** [comment]
Adding a separate page is fine if you want to contribute this feature. We are open to discuss the details.

**Comment by wu-sheng** [comment]
But since 8.0+, there is no heartbeat at the service level. But still, heartbeat is available at the service instance level.

**Comment by tarunwadhwa13** [comment]
Will try working on this and raise a PR once done. 

What method do you suggest for getting this info?

Should we query ES and find service/instance for which we have latest data? Or add some changes to agent so that agent can send some identifiers which can be stored in OAP . OAP can just maintain a map in-memory of the agents and their last push time

**Comment by wu-sheng** [comment]
You should add `lastPingTimestamp` in the [ServiceInstance entity](https://github.com/apache/skywalking-query-protocol/blob/master/metadata.graphqls#L31). This is the time bucket in the backend time format.

You could query the service list first, then get all instance lists with this time bucket(in minute level).

Then across check with [OAP time info](https://github.com/apache/skywalking-query-protocol/blob/master/metadata.graphqls#L89), you could have the status(alive or not).

WDYT?

**Comment by wu-sheng** [comment]
This requires very small change in the backend and a new page for this feature.
