### ISSUE TITLE
since the issue #4907 i think the class RestMappingMethodInterceptor should implements the method “getAcceptedMethodTypes”

### ISSUE THREAD

**Issue by whfjam** [apache/skywalking#5291]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Since the issue #4907 I think the class RestMappingMethodInterceptor should implements the method “getAcceptedMethodTypes” which returns “” by now

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think #5084 has fixed this.

**Comment by whfjam** [comment]
> 
> 
> I think #5084 has fixed this.

in #5084 it changed the code in the class AbstractMethodInterceptor use “getAcceptedMethodTypes(method)” but the method “getAcceptedMethodTypes” is a abstract one ，the implements are RequestMappingMethodInterceptor.getAcceptedMethodTypes and RestMappingMethodInterceptor.getAcceptedMethodTypes，then the RequestMappingMethodInterceptor.getAcceptedMethodTypes has handle the case but  the RestMappingMethodInterceptor.getAcceptedMethodTypes just return a empty string, did i miss something..

**Comment by wu-sheng** [comment]
Ping @BFergerson for a closer look. 

@whfjam If you have known what we're missing, could you send a pull request directly?

**Comment by whfjam** [comment]
> 
> 
> Ping @BFergerson for a closer look.
> 
> @whfjam If you have known what we're missing, could you send a pull request directly?

yes, i'd like to

**Comment by BFergerson** [comment]
https://github.com/apache/skywalking/pull/5085 is my attempt at fixing this. The only thing not working is the e2e tests.

**Comment by whfjam** [comment]
> 
> 
> #5085 is my attempt at fixing this. The only thing not working is the e2e tests.

i have saw your code， i noticed that in the last else situation u used the <return ""> i think this code
will cause the recursive to be ended because in the method ParsePathUtil.recursiveParseMethodAnnotaion it judges the result by 
Objects.isNull(result) , i doubt if you have notice that.

**Comment by whfjam** [comment]
> 
> 
> #5085 is my attempt at fixing this. The only thing not working is the e2e tests.

here is my code if any helps to you



@Override
    public String getAcceptedMethodTypes(Method method) {
        return ParsePathUtil.recursiveParseMethodAnnotaion(method, m -> {
            GetMapping getMapping = AnnotationUtils.getAnnotation(m, GetMapping.class);
            if (getMapping != null) {
                return RequestMethod.GET.toString();
            }
            PostMapping postMapping = AnnotationUtils.getAnnotation(m, PostMapping.class);
            if (postMapping != null) {
                return RequestMethod.POST.toString();
            }
            PutMapping putMapping = AnnotationUtils.getAnnotation(m, PutMapping.class);
            if (putMapping != null) {
                return RequestMethod.PUT.toString();
            }
            DeleteMapping deleteMapping = AnnotationUtils.getAnnotation(m, DeleteMapping.class);
            if (deleteMapping != null) {
                return RequestMethod.DELETE.toString();
            }
            PatchMapping patchMapping = AnnotationUtils.getAnnotation(m, PatchMapping.class);
            if (patchMapping != null) {
                return RequestMethod.PATCH.toString();
            }
            return null;
        });
    }

**Comment by whfjam** [comment]
> 
> 
> #5085 is my attempt at fixing this. The only thing not working is the e2e tests.

here is my codes if any helps to you


@Override
    public String getAcceptedMethodTypes(Method method) {
        return ParsePathUtil.recursiveParseMethodAnnotaion(method, m -> {
            if (AnnotationUtils.getAnnotation(m, GetMapping.class) != null) {
                return RequestMethod.GET.toString();
            }
            if (AnnotationUtils.getAnnotation(m, PostMapping.class) != null) {
                return RequestMethod.POST.toString();
            }
            if (AnnotationUtils.getAnnotation(m, PutMapping.class) != null) {
                return RequestMethod.PUT.toString();
            }
            if (AnnotationUtils.getAnnotation(m, DeleteMapping.class) != null) {
                return RequestMethod.DELETE.toString();
            }
            if (AnnotationUtils.getAnnotation(m, PatchMapping.class) != null) {
                return RequestMethod.PATCH.toString();
            }
            return null;
        });
    }

**Comment by wu-sheng** [comment]
@whfjam You could review that PR directly, comment on the specific line(s). And the codes should be well formated by using markdown(GitHub supports this).

**Comment by wu-sheng** [comment]
#5085 merged, if you still have some doubts, submit your proposal change through a pull request.
