### ISSUE TITLE
About  .NetCore RabbitMQ Question 

### ISSUE THREAD

**Issue by Ivin-yang** [apache/skywalking#5292]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is it possible to monitor RabbitMq when .netcore uses skywalking?

If yes?
How do it ?
Do I need to install any plugins?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
.net agent is not a part of Apache foundation yet. You need to reach the agent author.

**Comment by Ivin-yang** [comment]
thank you for your answer！
you mean .net core agent is not support RabbitMQ ?
