### ISSUE TITLE
Support elasticsearch in python agent

### ISSUE THREAD

**Issue by alonelaval** [apache/skywalking#5295]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please set the milstone and labels for your own.

**Comment by alonelaval** [comment]
> Please set the milstone and labels for your own.

ok
