### ISSUE TITLE
fail of span type ' [Broken] CROSS_PROCESS'

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#5297]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
i don't undewstand [Broken] CROSS_PROCESS 
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 7.0, os linux, jre jdk8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by killGC** [comment]
跨度信息
标记.
端点:VNode: 783.366.15971616001130002
跨度类型:[Broken] CROSS_PROCESS
组件:VirtualNode: #0
Peer:No Peer
失败:true

**Comment by wu-sheng** [comment]
Meaning, the reference segment didnt report to the backend.

**Comment by killGC** [comment]
sampleRate is not 100%，cause some segement not store to es，finally happen it？

**Comment by wu-sheng** [comment]
Maybe the plugin bug, backend process capability  not enough, elastic search cluster are not enough 
We have many fail safe mechanism, to protect the being monitored services.
