### ISSUE TITLE
disable kafka plugin in agent.config file

### ISSUE THREAD

**Issue by xbkaishui** [apache/skywalking#5300]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ x] Bug
- [ x] Requirement
- [ x] Feature or performance improvement

___
### Question
- What do you want to know?
I have downloaded the latest release v8.1.0, but found that  plugin.kafka.bootstrap_servers is enable by default. most of scenario are not use this. can we disable this property ?

**Comment by wu-sheng** [comment]
We never activate it default.

**Comment by xbkaishui** [comment]
Please check this url https://www.apache.org/dyn/closer.cgi/skywalking/8.1.0/apache-skywalking-apm-8.1.0.tar.gz

**Comment by wu-sheng** [comment]
That is not the way to activate. You need to copy the reporter plugin. Read the document.
