### ISSUE TITLE
in trace-detail-chart-list.vue when there exist some VNode then the svg's height is incorrect

### ISSUE THREAD

**Issue by whfjam** [apache/skywalking#5301]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
in trace-detail-chart-list.vue when there exist some VNodes then the svg's height is incorrect，i think it should be "fixSpans.length+row.length+1" and also there appears the  duplicate child nodes under the VNode

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Send a pull request directly? Your description is already including how to change codes.

**Comment by whfjam** [comment]
> 
> 
> Send a pull request directly? Your description is already including how to change codes.

i'd like to
