### ISSUE TITLE
Support @KafkaOnMessage annotation to replace @Trace when just using the Kafka scenario

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/skywalking#5302]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
For [FAQ:kafka-plugin](https://github.com/apache/skywalking/blob/master/docs/en/FAQ/kafka-plugin.md)
If we were just using the Kafka framework, then we would have to manually introduce the @trace annotation, while there are still have two problems, there would be a lot of localspan segments because poll() is empty and the link is not nice. I want to add the @KafkaOnMessage annotation to replace @Trace in this scenario to fix both of these problems

**Comment by wu-sheng** [comment]
Is this a document update plan?

**Comment by zhaoyuguang** [comment]
> Is this a document update plan?

Is not only document,  Also has toolkit
