### ISSUE TITLE
Prefix for ES Index

### ISSUE THREAD

**Issue by tarunwadhwa13** [apache/skywalking#5308]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [o] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
We are using a common Elasticsearch cluster for various applications including Skywalking OAP. Wanted to know if there is any way to add a common prefix for all indices like SW or OAP which helps us identify which indices OAP has created. 

Was checking the source code and found an implementation of [IndexNameConverter](https://github.com/apache/skywalking/blob/master/oap-server/server-library/library-client/src/main/java/org/apache/skywalking/oap/server/library/client/elasticsearch/IndexNameConverter.java#L24) and its use [here](https://github.com/apache/skywalking/blob/master/oap-server/server-library/library-client/src/main/java/org/apache/skywalking/oap/server/library/client/elasticsearch/ElasticSearchClient.java#L498) . But this interface is not being implemented for any index name conversion. Can I override this to create a converter which adds a prefix to index names?

**Comment by kezhenxu94** [comment]
`application.yml/storage/elasticsearch/namespace` is what you want, check https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#about-namespace
