### ISSUE TITLE
Nodejs agent segment not finish when high level QPS

### ISSUE THREAD

**Issue by TJ666** [apache/skywalking#5309]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
sw8 skyapm-nodejs 2.0.0
- Which company or project?
baidu
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
When high level QPS, segment is not finish. New segment still has a parent trace context ,and share traceId.So in skywalking dashboard. a trace chain keeps grow, the number of span :10,100,1000 .....
node versionn v10.9.0
eggjs worker = 8
![image](https://user-images.githubusercontent.com/17919231/90147086-606f9a80-ddb4-11ea-9fc7-9dfeac7a3dfc.png)

![image](https://user-images.githubusercontent.com/17919231/90146685-eb9c6080-ddb3-11ea-8339-f25618996ee4.png)
___

**Comment by TJ666** [comment]
@wu-sheng  thx for help

**Comment by wu-sheng** [comment]
Nodejs agent is not a part of Apache. Please contact the project directly.
