### ISSUE TITLE
delete service_name

### ISSUE THREAD

**Issue by gyjx** [apache/skywalking#5314]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [X] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

- [X]  I created one “Your_ApplicationName ”service_name at startup. How can I delete it?      

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You either understand the storage by yourself or wait for the TTL passed.
