### ISSUE TITLE
UI load balance doesn't work

### ISSUE THREAD

**Issue by Glenrun** [apache/skywalking#5316]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [Y] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
___
### Bug
- Which version of SkyWalking, OS and JRE?
  skywalking 8.0 Alpine linux 3.9.4 openJDK 1.8.0_212

- Which company or project?
  CCB
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
 UI ribbon load balancer doesn't work as expect. 
1.  I setup two backend servers, using zookeeper cluster as coordinator, and configure the two backend server in UI's collector's ribbon section: listOfServers
2. I shutdown one of the two backend server
3. Open UI to do apm trace query, sometimes it fails, even after a long time trying.
then, I added retry policy to ribbon, the request is still forwarded to the down server.
Configuration:
![APM-UI-RETRY](https://user-images.githubusercontent.com/10444152/90242942-8b172d00-de60-11ea-978e-ea63f2e1e1a1.png)

Error:
 
![APM-UI-ERROR](https://user-images.githubusercontent.com/10444152/90243061-c74a8d80-de60-11ea-98a1-06a98641cbed.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is a timeout, why you ask us?

**Comment by Glenrun** [comment]
> This is a timeout, why you ask us?
The backend server to be forward to is apm-backend-node1, it is down, so it is timeout.
Why I asked this is because UI frontend should request a healthy server, not a already down one, right?
@wu-sheng

**Comment by wu-sheng** [comment]
I think we don't set up any live-detection mechanism, it is a standard Spring Zuul, you could set by yourself. Or use a load balance like Envoy/Nginx to make that happens.
