### ISSUE TITLE
Get http headers

### ISSUE THREAD

**Issue by Silverbullet9** [apache/skywalking#5317]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?

Hi, does anyone know how to check http headers on skywalking?  I can see those data but no headers. 
![捕获](https://user-images.githubusercontent.com/69676171/90243227-1264a080-de61-11ea-8a85-2ac93f67ab45.PNG)

**Comment by wu-sheng** [comment]
Because the plugin doesn't collect them.
