### ISSUE TITLE
Some functions of performance analysis cannot be shown

### ISSUE THREAD

**Issue by lvjingang-git** [apache/skywalking#5324]
There is too much stack information. Some information can't see which class is affected by it, and the part must be circled in the picture  

![image](https://user-images.githubusercontent.com/34177769/90309062-6cc03880-df17-11ea-83ab-2d6b12578023.png)

**Comment by wu-sheng** [comment]
Check the changelog, have been fixed in the 8.1 release.

**Comment by lvjingang-git** [comment]
> 检查变更日志，已在8.1版本中修复。

我现在用的就是最新的8.1.0版本，ui上看不到具体的是哪个类的那个方法影响的，可能是页面递归显示的原因，这个在后面有版本解决么

**Comment by wu-sheng** [comment]
The first column could be resized at the top, this is only be blocked by the 2nd column, nothing more.
