### ISSUE TITLE
Display the dotnet components correctly

### ISSUE THREAD

**Issue by snakorse** [apache/skywalking#5325]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement
___
### Requirement or improvement
- I noticed that the skywalking v8.x data-transport-protocol only keeped the componentid which is number type field, and this cause dotnet components defined in the skyapm-dotnet can not be recognized by the oap server, I think this should be solved. Is there any solution to follow?

**Comment by wu-sheng** [comment]
It is always component id as an integer.
It is .net agent not suppoting 8.x, not just this field. And it is not the main repo issue.

**Comment by snakorse** [comment]
but is there ways to convert the .net defined component string to id?

**Comment by wu-sheng** [comment]
I think you are asking for this doc? https://github.com/apache/skywalking/blob/master/docs/en/guides/Component-library-settings.md

The ID/name could be found and added here, https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/component-libraries.yml#L321-L370

**Comment by snakorse** [comment]
Yes, that's it! Thanks!
