### ISSUE TITLE
The plugin of skywalking agent does not support collecting http header details, such as referer, user-agent, if-none-match, cookie, payload, etc.

### ISSUE THREAD

**Issue by CalbeeMing0530** [apache/skywalking#5329]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

**I want to ask the following questions first:**
     Does the skywalking java agent have a plugin that can collects the metadata of the http request header and can access it through the UI or elasticsearch? I have not found the relevant configuration  by checking the agent.config file.

**Some findings through operating the UI:**
     I can see the method and request url fields of the http header through the tracking function of the UI, and I can get the parameters carried in the http request url by modifying 
     `plugin.springmvc.collect_http_params=${SW_COLLECT_HTTP_PARAMS:true}` 
     as shown in the following figure:
    
![image](https://user-images.githubusercontent.com/40563405/90361317-7c16c180-e090-11ea-9ecc-9dd33ca3f5fd.png)
     So I think that skywalking should be able to get the detailed information of the http header. Is the skywalking UI unable to display this information now? Or need to be obtained through other methods?

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
If skywalking does not provide this function by default, do you consider adding it in later development? I think this function is still needed when doing microservice traffic data collection.

**Comment by wu-sheng** [comment]
It is not supported, but you could contribute this feature. And like parameter collection mechanism, this should be optional.

**Comment by xbkaishui** [comment]
I want to try, please assign to me

**Comment by wu-sheng** [comment]
Done

**Comment by xbkaishui** [comment]
For the headers part,  it maybe contains senstive data, such as token, or userInfo related. shoud we add option choose to filter by header names?

**Comment by wu-sheng** [comment]
Yes, we have to, in order to avoid security leak as you said, and overload the agent and storage.

**Comment by wu-sheng** [comment]
Such as cookie is a sensitive thing, which we should not collect in default, right?

**Comment by xbkaishui** [comment]
Yes, I agree
