### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/skywalking#5330]
https://github.com/apache/skywalking/blob/ed71efda52dd1cce31d53622ed5d3d8aa66e9c3d/test/plugin/scenarios/mariadb-scenario/src/main/java/org/apache/skywalking/apm/testcase/mariadb/MariadbConfig.java#L34

The program can potentially fail to release a system resource.

**Comment by wu-sheng** [comment]
Yes, you could submit a pull request to fix this.

**Comment by wu-sheng** [comment]
This is only a test case issue. Nothing about the released source code. Anyway wants to contribute and fix this, welcome.
