### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/skywalking#5331]
https://github.com/apache/skywalking/blob/ed71efda52dd1cce31d53622ed5d3d8aa66e9c3d/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/loader/AgentClassLoader.java#L75-L77

Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.

**Comment by wu-sheng** [comment]
What do your point of your question? I am confused. Java depends on the JVM and OS obviously, what tod you mean `not work reliably in a platform independent way`?
