### ISSUE TITLE
‘Service Avg Throughput’ cpm less than  all 'Running ServiceInstance' cpm of sum, why equals?

### ISSUE THREAD

**Issue by vcvinci** [apache/skywalking#5333]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
why ‘Service Avg Throughput’ cpm less than  all 'Running ServiceInstance' cpm of sum in version 7.0.0?
example:
a service cpm is 22525.13cpm , but this service has 8 machine isntances,and every instance cpm is about 16800，
so why 22525.12 != 16800 * 8?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is hard to tell. Do you run SkyWalking in the cluster mode?

**Comment by vcvinci** [comment]
> This is hard to tell. Do you run SkyWalking in the cluster mode? Are you using the cluster coordinator?

yes,cluster uses 3 zookeeper, oap has 3 instances.

**Comment by wu-sheng** [comment]
Do you use the real IP rather than `0.0.0.0` for OAP node?

**Comment by vcvinci** [comment]
> Do you use the real IP rather than `0.0.0.0` for OAP node?

no, i user 0.0.0.0

**Comment by wu-sheng** [comment]
Then, that is the issue. You must use the unique and real IP for that.

**Comment by vcvinci** [comment]
> Then, that is the issue. You must use the unique and real IP for that.

thank you very much.

**Comment by wu-sheng** [comment]
> thank you very much. if a machine launch 2 oap , one oap set grpc port 11800 other one set grpc port 11801, Will it happen the problem of title?

This is not about the one VM or more. The key is the IP you registered must accessible from other OAP nodes. That is the OAP cluster.
