### ISSUE TITLE
服务端的性能问题,导致客户端总是超时,麻烦您帮忙看一下问题描述

### ISSUE THREAD

**Issue by vcvinci** [apache/skywalking#5334]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
问题描述比较多，就用中文啦。版本是7.0.0
实际是我们的agent客户端有150多个机器，只有3个oap服务器。找一个cpm比较多的服务 高峰的时候cpm最少两万多，这个服务有8台机器，但是ui上展示的Running ServiceInstance 每个机器的cpm不均衡，cpm相对特别少的机器里都有grpc超时的日志打印。
我们做出了改变，新加了3台机器，每个机器都启动两个oap实例就是多了6个oap实例。只在这个cpm较多的服务，增加了agent对新oap地址的选取。看客户端源码是随机访问到其中一个oap服务。连接到新的6个中的oap实例，看Running ServiceInstance中的数据是均衡了，但是仍然有连接到之前老的三个oap，仍然是超时。
- 1  . 发送连接到老的那三个oap，那些客户端超时的数据基本是都丢弃了么？
- 2 . oap内存队列datacarries如果满了，看源码满了应该会阻塞，那阻塞后来得数据是丢弃了么？
- 3 . 可能是es的存储性能问题，但是之前超时的客户端连接到新的6个中oap，就没有超时错误了。但是连接到老的oap仍然报错。
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only.
