### ISSUE TITLE
java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL

### ISSUE THREAD

**Issue by ZhangDi-d** [apache/skywalking#5336]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
recently i use skywalking in my application ，which is based on  jdk 14（and i use it's new feature, "record"）.however ,when i try to use skywalking-agent with this application and my application was visited，the skywalking-agent logs will print “**java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL**”。

can somebody give me some advice which can slove this problem ?

**Comment by wu-sheng** [comment]
It seems requiring a byte buddy upgrade for jdk14.

**Comment by wu-sheng** [comment]
@raphw Is this a known issue?

**Comment by wu-sheng** [comment]
@ZhangDi-d  Do you want to instrument this class(`record`)? How do you trigger this? Or just have this kind of class, then this log output as an warning?

**Comment by dmsolr** [comment]
It has been fixed by #5338 
And, #5352 will add a test case in the plugin tests.

**Comment by ZhangDi-d** [comment]
Sorry to reply so late. yes i just want to instrument this class(record)，the error log will be printed （
The picture is shown below）. Since  you are repairing it, I will wait for the latest version. Thanks u very much
![skywalking error](https://user-images.githubusercontent.com/29948535/90994980-17f28100-e5ed-11ea-838e-95de6a5339d0.png)

**Comment by wu-sheng** [comment]
Try the master branch, it has been fixed
