### ISSUE TITLE
some questions about nacos

### ISSUE THREAD

**Issue by HowlsCastle** [apache/skywalking#5337]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
1. The reason of add port configuration to configuration of nacos.if we deploy the nacos in different port, how can I write it?
    serverAddr: ${SW_CONFIG_NACOS_SERVER_ADDR:127.0.0.1}
    port: ${SW_CONFIG_NACOS_SERVER_PORT:8848}
2. The configuration of nacos in the application.yml miss configuration about authorization of nacos（username and password）
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> The reason of add port configuration to configuration of nacos.if we deploy the nacos in different port, how can I write it?

You could change the `application.yml`, or use the System ENV, SW_CONFIG_NACOS_SERVER_PORT, to override it.

> The configuration of nacos in the application.yml miss configuration about authorization of nacos（username and password）

No code to support that today, a contribution is welcome.
