### ISSUE TITLE
SW_STORAGE_ES_INDEX_SHARDS_NUMBER ineffective 

### ISSUE THREAD

**Issue by pingliu** [apache/skywalking#5343]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking:6.4
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

first,I use the elasticsearch default config,the default index shard is 2. it's ok.
but when I change the index shard config, change to 3,then stop service and delete index, and start service,
the created index shard also is 2.  
why ??
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Do you delete the templates?

**Comment by wu-sheng** [comment]
6.4 is a very old version for the community.
