### ISSUE TITLE
How to access the same skywalking service in multiple environments?

### ISSUE THREAD

**Issue by gyjx** [apache/skywalking#5344]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [X] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
- [X] How to access the same skywalking service in multiple environments?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean by how to access? We don't set any limitation for this.

**Comment by gyjx** [comment]
I'm sorry, maybe I didn't make it clear. I mean, if I have three links: development, testing and pre release, but I just want to deploy a skywalking service, how will I divide it?

**Comment by wu-sheng** [comment]
No, we don't have that. Management is not our agenda today.

**Comment by gyjx** [comment]
Does SK not support service partitioning? Do I need to deploy three SK services? dev test pre ....

**Comment by wu-sheng** [comment]
You could do anything you want. I just say, we don't have that concept. Why need APM in the tesr and dev env? Strange thing.

**Comment by gyjx** [comment]
Because some of our interfaces have to go through pressure test before going online, we hope SK can help us do something.

**Comment by wu-sheng** [comment]
If you are going to do load test, then use a separate SW cluster. It is recommended.

**Comment by gyjx** [comment]
thank you
