### ISSUE TITLE
When sampling is turned on, the @TracecrossThread does not work

### ISSUE THREAD

**Issue by lichao0** [apache/skywalking#5354]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When sampling is turned on, the @TracecrossThread does not work.
Thread task cannot report, or report two unconnected traces?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking8.0.0

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Because it could be `not-sampled`, that is the side-effect of doing the sampling.

In across-process(RPC/MQ) case, once the plugin uses `public static AbstractSpan createEntrySpan(String operationName, ContextCarrier carrier)`, there is a force sampling mechanism. But for across-thread, there is no such thing.

**Comment by wu-sheng** [comment]
SkyWalking agent, especially Java agent, recommends you to do backend sampling. Because
1. The above side-effect
1. Metrics would not be accurate

**Comment by lichao0** [comment]
Will back-end sampling lead to higher  load collecter?  
Can across-thread do force sampling mechanism？

**Comment by wu-sheng** [comment]
> Will back-end sampling lead to higher load collecter?

Network load, yes. Analysis CPU cost, very limited.

> Can across-thread do force sampling mechanism？

I don't know, that depends on the plugin mechanism, some may be possible with agent kernel API adjustment.

**Comment by lichao0** [comment]
Thanks!
