### ISSUE TITLE
when i use @Aspect Annotation in a spring cloud app it has some infos 

### ISSUE THREAD

**Issue by whfjam** [apache/skywalking#5359]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
when i use @Aspect Annotation in a spring cloud app it has some infos , the bootstrap log has some info like 
2020-08-20 20:20:17.034 [main] INFO  org.springframework.aop.framework.CglibAopProxy - Unable to proxy method [final java.lang.String com.timevale.skwka.service.TestController.getMsg$original$aXsk4F1g$accessor$UIVnuXdt(java.lang.String)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Are you using agent to instrument that class and method as well? Please provide the full error stack.

**Comment by whfjam** [comment]
> 
> 
> Are you using agent to instrument that class and method as well? Please provide the full error stack.

yes i did， it seemed like just an info log not an error
i had a controller like below
---------------------------------
@Controller
public class TestController {


    @RequestMapping(path = "v2/test2/{fileId}",method = RequestMethod.GET)
    public String getMsg(@PathVariable String fileId){
        new RuntimeException().printStackTrace();
        return "1TT-"+fileId;
    }
}
--------------------------------
then i had a aop like below
--------------------------------
@Aspect
@Component
public class ParamValiAspect {

    @Pointcut("execution (* com.timevale.skwka.service.*.*(..))")
    public void doAspect() {

    }

    @Around("doAspect()")
    public Object around(ProceedingJoinPoint joinPoint) throws Throwable {
        Object[] args = joinPoint.getArgs();
        for(Object arg: args){
            if(arg == null) {
                continue;
            }
           System.out.println("arg:"+arg);
        }

        return joinPoint.proceed();
    }
}
--------------------------------------

in the startup logs i found this :

INFO  org.springframework.aop.framework.CglibAopProxy - Unable to proxy method [final java.lang.String com.timevale.skwka.service.TestController.getMsg$original$btT8GaHU$accessor$vhlk7XnS(java.lang.String)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.


if without skywalkingagent it would not happen

**Comment by wu-sheng** [comment]
Does this affect your application? This is because we(byte-buddy) added some internal method(final) in your Controller at the runtime. And Spring doesn't support to do `AOP` thing, so this error/warning shows up.

**Comment by whfjam** [comment]
> 
> 
> Does this affect your application? This is because we(byte-buddy) added some internal method(final) in your Controller at the runtime. And Spring doesn't support to do `AOP` thing, so this error/warning shows up.

I think i should learn more about this and test more , then i will tell you about if this could affect my application

**Comment by kezhenxu94** [comment]
I think you should rewrite your pointcut to only intercept methods that are `public` or annotated with `@RequestMapping`(or `@GetMapping` and other similar for POST, ect.), intercepting all methods in a controller is not realistic in a real scenario(it’s very likely that we have private methods in a controller) and I consider it as a bad practice(it costs too much extra and unnecessarily)
