### ISSUE TITLE
why agent setup so many threads？how to config netty thread pool size？

### ISSUE THREAD

**Issue by Geekplus-china** [apache/skywalking#5370]
I find agent setup 64 threads， CPU reach to 100%
how to config agent netty thread size？
![image](https://user-images.githubusercontent.com/46219602/90996913-a3badc00-e5f2-11ea-8109-118aa9b41099.png)

**Comment by wu-sheng** [comment]
Which version? We don't intend to set many threads. gRPC usually use one thread only as we don't call remote concurrency.

**Comment by Geekplus-china** [comment]
> Which version? We don't intend to set many threads. gRPC usually use one thread only as we don't call remote concurrency.

we use v6.5.0.

Will it default to 2 times CPU cores to set the number of netty threads ?

**Comment by wu-sheng** [comment]
Please try the latest.
