### ISSUE TITLE
The document is misspelled.

### ISSUE THREAD

**Issue by vincent2518** [apache/skywalking#5371]
skywalking/docs/en/guides/Java-Plugin-Development-Guide.md	
Develop a plugin-> Intercept-> in "Extend ClassStaticMethodsEnhancePluginDefine definec class method intercept points" ,"definec" may should be "defines"?

**Comment by kezhenxu94** [comment]
@vincent2518  thanks for pointing out, please send a pull request to fix it if you will

**Comment by xbkaishui** [comment]
please assign to me if it is ok

**Comment by vincent2518** [comment]
ok，i'll do it.



---Original---
