### ISSUE TITLE
Where are the three values of process.env.SW_PROXY_TARGET, process.env.NODE_ENV, and process.env.NODE_ENV set? I didn't find the setting, but it can be printed out through console.log, which is very strange

### ISSUE THREAD

**Issue by O-ll-O** [apache/skywalking#5373]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Where are the three values of process.env.SW_PROXY_TARGET, process.env.NODE_ENV, and process.env.NODE_ENV set? I didn't find the setting, but it can be printed out through console.log, which is very strange
![issue](https://user-images.githubusercontent.com/48112006/91030807-4e9eba80-e632-11ea-861e-0936dc087185.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- windows 10
- Skywalking v.8.1.0
- node  v.12.16.0
- npm v.6.13.4

**Comment by kezhenxu94** [comment]
@O-ll-O your question is too vague, please provide more context when asking, which agent are you using, how did you start the app? The 3 variables are usually set by environment variables or in the start up script, e.g. `NODE_ENV=development SW_PROXY_TARGET=xxxx node app.js`

**Comment by kezhenxu94** [comment]
Close it for now, if you have any further question, please reply here

**Comment by O-ll-O** [comment]
I actually want to know how its value is set when the project is running?
![issue2](https://user-images.githubusercontent.com/48112006/91113021-24dba700-e6b7-11ea-8471-d4e6436a3850.jpg)

**Comment by wu-sheng** [comment]
Understanding the codes basically are your own responsibility. We have opened the source.

**Comment by O-ll-O** [comment]
ok,thank u
