### ISSUE TITLE
Minimal Requirements

### ISSUE THREAD

**Issue by wandersonwhcr** [apache/skywalking#5375]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

What is the minimal requirements to run SkyWalking?

I am trying to run SW on a Kubernetes cluster using MySQL as database. I defined OAP server with memory limits equal to 1024Mi and it crashes after ~40min. If I use H2 as database, it crashes after ~5min.

___
### Bug
- Which version of SkyWalking, OS and JRE?

7.0.0-es7

- Which company or project?

Private project.

- What happened?

K8s kills pod with status OOMKilled.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Per document, we statemented the h2 is for demo only. Usually, Java app requires 4~8g as minimal recommended memory.

Also, we recommend you to use v8 for better performance.

**Comment by wandersonwhcr** [comment]
TY
