### ISSUE TITLE
10K+ thread in skywalking-oap process

### ISSUE THREAD

**Issue by worldwalk** [apache/skywalking#5378]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

deployed skywalking on AWS,  one skywalking-oap node cpu 100%. 
With jstack we found 10K+ thread there, and most of them is 

"DataCarrier.GRPCRemoteClient.Consumser.0.Thread" #29764 daemon prio=5 os_prio=0 tid=0x00007fce67fd1800 nid=0x7458 sleeping[0x00007fc7d0b02000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:72)

With jmap we got :
 num     #instances         #bytes  class name
----------------------------------------------
   1:      21632389     2500615320  [C
   2:      20464186     1145994416  org.apache.skywalking.apm.network.register.v2.Endpoint

Any clue please?  thanks!
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking-oap 6.3.0

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This has been fixed in many released versions. Check the changelog, and recommend to use the latest version.

**Comment by worldwalk** [comment]
this resolved in v6.4 by functionality called operation name group.
