### ISSUE TITLE
How to add user management to the UI interface

### ISSUE THREAD

**Issue by muoushi** [apache/skywalking#5381]
I installed the  ES7 +latest version of SkyWalking，when I launch the UI, I go directly to the page without logging in。
If I use it in the company's servers, this is generally not allowed.
So I need a solution that prevents arbitrary access from the outside world.

**Comment by wu-sheng** [comment]
Please don't submit a duplicated question. We have answered many times, there is no user management. Choose proxy, such as Nginx/APISIX to do that.
