### ISSUE TITLE
the optimization of "trace sql parameters"

### ISSUE THREAD

**Issue by novayoung** [apache/skywalking#5383]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [* ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
When "trace_ sql_parameters" is true, the agent will record the parameters, but if the parameters are too large, the performance will be affected and the memory will be occupied. 
I think it is better to get the truncated parameters string before build the full string of all the parameters.

**Comment by wu-sheng** [comment]
We have `SQL_PARAMETERS_MAX_LENGTH` from day one, please recheck the log.

**Comment by novayoung** [comment]
i know that, but truncation depends the full string. 
```
        String parameterString = getParameterString();  // Here is the string of parameters, maybe too large. 
        return truncate(parameterString);
```

**Comment by novayoung** [comment]
> We have `SQL_PARAMETERS_MAX_LENGTH` from day one, please recheck the doc.

i know that, but truncation depends the full string. 
```
        String parameterString = getParameterString();  // Here is the string of parameters, maybe too large. 
        return truncate(parameterString);
```

**Comment by wu-sheng** [comment]
OK, if you want to cut the string as soon as it reached the length limitation, you could optimize that.

**Comment by novayoung** [comment]
> OK, if you want to cut the string as soon as it reached the length limitation, you could optimize that.

Ok
