### ISSUE TITLE
use skywalking reciver zipkin span

### ISSUE THREAD

**Issue by huizluo** [apache/skywalking#5385]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
we deploy skywalking in k8s, I sent it to Skywalking by using the Zipkin trace of IStio, I configure storageType as  zipkin-elasticsearch.An error occurred in init job. this is error description.
org.apache.skywalking.oap.server.library.module.ProviderNotFoundException: no provider found for module storage, if you're sure it's not required module and want to remove it, set the selector to

when i configure storageType as  elasticsearch .it work well but tracing can not show.

### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
> we deploy skywalking in k8s, I sent it to Skywalking by using the Zipkin trace of IStio, I configure storageType as zipkin-elasticsearch.An error occurred in init job. this is error description.
org.apache.skywalking.oap.server.library.module.ProviderNotFoundException: no provider found for module storage, if you're sure it's not required module and want to remove it, set the selector to

For now, the Zipkin receiver only supports ElasticSearch 6, see #5384 to track the ElasticSearch 7 adoption.

> when i configure storageType as elasticsearch .it work well but tracing can not show.

Please provide more context, 1) is there trace data in the ElasticSearch storage 2) is there any error log from the backend/agent side
