### ISSUE TITLE
bug about prepareBath in MetricsPersistentWorker

### ISSUE THREAD

**Issue by gnr163** [apache/skywalking#5399]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

https://github.com/apache/skywalking/blob/c5df0760f257e523902b641755b1cf7e6cee4476/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/analysis/worker/MetricsPersistentWorker.java#L133

 Math.max make maxBatchGetSize meaningless. And from the context , should it be Math.min ?
___
### Bug
- Which version of SkyWalking, OS and JRE?
    8.1.X
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean meaningless? Could you explain?

**Comment by gnr163** [comment]
https://github.com/apache/skywalking/blob/c5df0760f257e523902b641755b1cf7e6cee4476/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/analysis/worker/MetricsPersistentWorker.java#L133-L147

If use Math.max, bathSize will always be astCollection.size() when astCollection.size() is grather than 2000. And then flushDataToStorage  all lastCollection。
If use Math.min, bathSize will  be 2000 when astCollection.size() is grather than 2000. And then flushDataToStorage  2000 size of 
lastCollection every time.

**Comment by wu-sheng** [comment]
Make sense, could you send the pull request to fix this?

**Comment by gnr163** [comment]
Of course.
