### ISSUE TITLE
skywalking-python  ModuleNotFoundError: No module named 'common.Common_pb2'

### ISSUE THREAD

**Issue by makerwei** [apache/skywalking#5402]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Bug
___
### Bug
- Which version of SkyWalking, OS and JRE?
- What happened?
在django项目中使用apache-skywalking模块时，如果项目本身有common目录，会报如下错误
![image](https://user-images.githubusercontent.com/43264876/91425999-78ecb400-e88e-11ea-93e3-10f9b8dc3a7a.png)

**Comment by wu-sheng** [comment]
English only.

**Comment by kezhenxu94** [comment]
FYI, should be fixed in the latest version
