### ISSUE TITLE
ui bug

### ISSUE THREAD

**Issue by alishangtian** [apache/skywalking#5405]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] 遇见了ui bug
- [ ] 页面展示不全
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
-如何修复ui 展示问题

___
### Bug
![image](https://user-images.githubusercontent.com/3463296/91513519-20adc480-e917-11ea-985b-72cc6aff4b32.png)
- What happened?
页面展示不全，版本8.1 Binary Distribution for ElasticSearch 7

**Comment by wu-sheng** [comment]
English only. This is not UI bug, either browser cache or backend is not working

**Comment by alishangtian** [comment]
what do you mean by English only？you are very close to the racial discrimination.



---Original---
