### ISSUE TITLE
The python-agent reports an error when starting the service

### ISSUE THREAD

**Issue by CalbeeMing0530** [apache/skywalking#5406]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, python, ?
   skywalking-kubernetes the latest version
   Ubuntu 18.04
   python version v3.6
   

- What happened?
   I deployed skywalking-kubernetes on my host, and then I installed the apache-skywalking python package through the official 
[https://github.com/apache/skywalking-python#from-source-code](url) method. After the installation was successful, I add the following code to the daemon.py of my program:
```
   from skywalking import agent, config
  if __name__ =='__main__':
       config.init(collector='10.102.249.111:11800', service='commodity')
       agent.start()
```

then I execute `python daemon.py`  and report the following error:

```
Traceback (most recent call last):
  File "daemon.py", line 6, in <module>
    agent.start()
  File "/usr/local/lib/python3.6/site-packages/apache_skywalking-0.3.0-py3.6.egg/skywalking/agent/__init__.py", line 76, in start
    __init()
  File "/usr/local/lib/python3.6/site-packages/apache_skywalking-0.3.0-py3.6.egg/skywalking/agent/__init__.py", line 60, in __init
    from skywalking.agent.protocol.grpc import GrpcProtocol
  File "/usr/local/lib/python3.6/site-packages/apache_skywalking-0.3.0-py3.6.egg/skywalking/agent/protocol/grpc.py", line 23, in <module>
    from common.Common_pb2 import KeyStringValuePair
ModuleNotFoundError: No module named'common.Common_pb2'
```

my python pacakge list:
```
Package           Version
----------------- ---------
apache-skywalking 0.3.0
certifi           2020.6.20
chardet           3.0.4
click             7.1.2
configparser      5.0.0
Flask             1.1.2
Flask-Cors        3.0.8
grpcio            1.31.0
grpcio-tools      1.31.0
idna              2.10
itsdangerous      1.1.0
Jinja2            2.11.2
MarkupSafe        1.1.1
packaging         20.4
pip               20.2.2
protobuf          3.13.0
psycopg2-binary   2.8.5
pyparsing         3.0.0a2
requests          2.24.0
setuptools        39.0.1
six               1.15.0
urllib3           1.25.10
Werkzeug          1.0.1
```

It seems that there is a problem with the grpc library. I searched google for related issues and there is no corresponding explanation. There is only one (https://github.com/apache/skywalking/issues/4917) but it seems to have nothing to do with the problem I encountered. Is this A bug? 

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

How can i solve this problem？

**Comment by kezhenxu94** [comment]
@CalbeeMing0530 can you paste all the logs when you execute `make install`? I suspect you didn't generate the source codes from Proto files correctly

**Comment by makerwei** [comment]
@kezhenxu94 I have same issue, pip install apache-skywalking python package,
When the project contains the Common directory, the application service fails and the error is reported as shown in the figure. When the Common directory is not included, it worked!
![image](https://user-images.githubusercontent.com/43264876/91549802-17921700-e95a-11ea-9ab2-34000ada006d.png)

**Comment by kezhenxu94** [comment]
> @kezhenxu94 I have same issue, pip install apache-skywalking python package,
> 
> When the project contains the Common directory, the application service fails and the error is reported as shown in the figure. When the Common directory is not included, it worked!
> 
> ![image](https://user-images.githubusercontent.com/43264876/91549802-17921700-e95a-11ea-9ab2-34000ada006d.png)
> 
> 
> 
> 
> 
> 

Root cause is found, I'm fixing

**Comment by kezhenxu94** [comment]
@CalbeeMing0530 to be clear, do you have a `common` package in your application too?

**Comment by kezhenxu94** [comment]
@CalbeeMing0530 @makerwei this pull request https://github.com/apache/skywalking-python/pull/72 tries to fix this bug, please help to verify that it solves your problem

**Comment by CalbeeMing0530** [comment]
@kezhenxu94 yes, my application include common package, I will try later, thanks for your reply : - )
