### ISSUE TITLE
one bug when query instance_jvm_cpu metric

### ISSUE THREAD

**Issue by liyanyan-dev** [apache/skywalking#5417]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ √] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
   skywalking 8.1.0  jdk1.8

- Which company or project?

- What happened?
When I query instance_jvm_cpu metric  ， the web side shows that the CPU utilization rate is 0, and the actual CPU  rate of the service process is 5-10%; I checked the code of the agent side and found that theCPU rate is * 100, but all the data stored in ES is less than 1; however, the query interface uses long type for this field, and all the data is converted to 0
 
![image](https://user-images.githubusercontent.com/54348450/91786093-6e893c00-ec39-11ea-95a7-1ad1f871f7a0.png)
![image](https://user-images.githubusercontent.com/54348450/91786136-8234a280-ec39-11ea-9954-3e2f14b924ce.png)
![image](https://user-images.githubusercontent.com/54348450/91786377-1272e780-ec3a-11ea-8cd4-1155584cab36.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by xbkaishui** [comment]
there should be some bug, let me check

**Comment by liyanyan-dev** [comment]
> there should be some bug, let me check

thanks!

**Comment by wu-sheng** [comment]
I am not sure whether this is a bug. In SkyWalking, we consider max CPU usage to 100%, so we divide CPU core number.

**Comment by wu-sheng** [comment]
The top command shows one core CPU usage. So it could be 800% even 1600%.
The reason we did this, is better for alarm threshold setting. Anyway, @xbkaishui this is the tips for you.

**Comment by xbkaishui** [comment]
Thanks， let me check the logic

**Comment by xbkaishui** [comment]
the bug is in the MetricsQuery*DAO , it read the value as long, but the actually value is double like 0.8842238771569793 for example, code as below

```

 // Label is null, because in readMetricsValues, no label parameter.
        IntValues intValues = metricsValues.getValues();
        for (String id : ids) {
            KVInt kvInt = new KVInt();
            kvInt.setId(id);
            kvInt.setValue(0);
            if (idMap.containsKey(id)) {
                Map<String, Object> source = idMap.get(id);
                kvInt.setValue(((Number) source.getOrDefault(valueColumnName, 0)).longValue());
            } else {
                kvInt.setValue(ValueColumnMetadata.INSTANCE.getDefaultValue(condition.getName()));
            }
            intValues.addKVInt(kvInt);
        }

```

@wu-sheng , Can I submit a pr and fix this ?

**Comment by wu-sheng** [comment]
This is the expected case. If you notice the query protocol, it is an int/long.

**Comment by wu-sheng** [comment]
Less than 1% usage would be expected as 0. If you want this away, we need to change JVM handler, make the <= 1 to 1 always.

**Comment by xbkaishui** [comment]
ok, that make sense. will change that
