### ISSUE TITLE
org.apache.skywalking.oap.server.cluster.plugin.kubernetes.NamespacedPodListInformer.listPods(NamespacedPodListInformer.java:96)

### ISSUE THREAD

**Issue by O-ll-O** [apache/skywalking#5418]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What is the reason for this error when deploying skywalking in k8s cluster? What is the general investigation direction
![skywalking-k8s-bug](https://user-images.githubusercontent.com/48112006/91788624-3edd3280-ec3f-11ea-8f81-81f006a4f06e.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
The reason I probably checked is that oap-server cannot access k8s service api.Please give some updated troubleshooting directions

**Comment by wu-sheng** [comment]
If you are using the k8s coordinator, try to use helm, it declare the required access rights for API server.
Unless you plan to learn source codes, don't use the master branch.
