### ISSUE TITLE
show the serviceCode in the span detail ui component

### ISSUE THREAD

**Issue by novayoung** [apache/skywalking#5420]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [*] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
when I  query the trace list by traceid, if the service too many, i don't know which span color is which serviceCode, only guess.

**Comment by wu-sheng** [comment]
UI is open for contributions, please try to submit the pull request.

**Comment by novayoung** [comment]
> UI is open for contributions, please try to submit the pull request.

OK
