### ISSUE TITLE
Oap8.1 An OAP node USES ES6.7 to limit the problem

### ISSUE THREAD

**Issue by linliaoy** [apache/skywalking#5421]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Because lock often occurs when the traffic of connecting an OAP node is high, and all grpcServerPool 1-Thread processes lock in the lock of this figure, concurrentRequests configuration is 10, as shown in the figure
![image](https://user-images.githubusercontent.com/16507478/91826275-ec683a00-ec6f-11ea-9d21-dc6c5f626104.png)
1. I checked es Github, but it was not really concurrent at this time, so the sending was restricted. The following is the connection
https://github.com/elastic/elasticsearch/pull/41451/commits
2. I want to know if there is a lock caused by my improper configuration
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I don't know any configuration could cost this lock. This seems more like a bug but only tagged in 7.3 and 8+. Are you using those versions?

**Comment by linliaoy** [comment]
Java High Level REST Client ：6.3.2    elasticsearch ：6.7

**Comment by wu-sheng** [comment]
I don't have feedback about this. But you could consider updating the ES client to 6.7

**Comment by linliaoy** [comment]
Ok, I'll try ES Client 6.7 first. Is there a recommended version of ES7?

**Comment by linliaoy** [comment]
![image](https://user-images.githubusercontent.com/16507478/91927500-3f8fca80-ed0c-11ea-871d-0ec12033965d.png)
Is it necessary to change ES Client from version 6.3.2 to 6.7

**Comment by wu-sheng** [comment]
I don't have much experience to be shared with you, I am afraid. We don't face this issue.

**Comment by linliaoy** [comment]
Again encounter the following things, can help to see the number of threads has no problem   "grpc-default-executor-1889" #1994 daemon prio=5 os_prio=0 tid=0x00007f8068037800 nid=0x846 waiting on condition [0x00007f80420e1000]
"Attach Listener" #1993 daemon prio=9 os_prio=0 tid=0x00007f8104001000 nid=0x824 waiting on condition [0x0000000000000000]
"grpc-default-executor-1888" #1992 daemon prio=5 os_prio=0 tid=0x00007f80680c0000 nid=0x809 waiting on condition [0x00007f8040adc000]
"grpc-default-executor-1887" #1991 daemon prio=5 os_prio=0 tid=0x00007f806810d000 nid=0x808 waiting on condition [0x00007f80402d8000]
"grpc-default-executor-1883" #1987 daemon prio=5 os_prio=0 tid=0x00007f80680c7000 nid=0x804 waiting on condition [0x00007f80f854d000]
"grpc-default-executor-1879" #1983 daemon prio=5 os_prio=0 tid=0x00007f80682be800 nid=0x800 waiting on condition [0x00007f80401d7000]
"qtp293870357-1967" #1967 prio=5 os_prio=0 tid=0x00007f8094003000 nid=0x7f0 runnable [0x00007f80a7dfe000]
"Connector-Scheduler-4cdd2c73-1" #136 prio=5 os_prio=0 tid=0x00007f7fa0005800 nid=0x9f waiting on condition [0x00007f80407d9000]
"DataCarrier.GRPCRemoteClient.Consumer.0.Thread" #103 daemon prio=5 os_prio=0 tid=0x00007f80e0072800 nid=0x7e waiting on condition [0x00007f80a43e8000]
"DataCarrier.GRPCRemoteClient.Consumer.0.Thread" #102 daemon prio=5 os_prio=0 tid=0x00007f80e0072000 nid=0x7d waiting on condition [0x00007f8041edf000]
"pool-2-thread-5" #86 prio=5 os_prio=0 tid=0x00007f80e800b800 nid=0x65 waiting on condition [0x00007f8041fe0000]
"pool-2-thread-4" #84 prio=5 os_prio=0 tid=0x00007f80e800a000 nid=0x63 waiting on condition [0x00007f80421e2000]
"pool-2-thread-3" #83 prio=5 os_prio=0 tid=0x00007f80e8008000 nid=0x62 waiting on condition [0x00007f80422e3000]
"grpcServerPool-1-thread-32" #82 prio=5 os_prio=0 tid=0x00007f8068145000 nid=0x61 waiting for monitor entry [0x00007f80425e4000]
"grpcServerPool-1-thread-31" #81 prio=5 os_prio=0 tid=0x00007f8068143000 nid=0x60 waiting for monitor entry [0x00007f80426e5000]
"grpcServerPool-1-thread-30" #80 prio=5 os_prio=0 tid=0x00007f8068141000 nid=0x5f waiting for monitor entry [0x00007f80427e6000]
"grpcServerPool-1-thread-29" #79 prio=5 os_prio=0 tid=0x00007f806813f800 nid=0x5e waiting for monitor entry [0x00007f80428e7000]
"grpcServerPool-1-thread-28" #78 prio=5 os_prio=0 tid=0x00007f806813d800 nid=0x5d waiting for monitor entry [0x00007f80429e8000]
"grpcServerPool-1-thread-27" #77 prio=5 os_prio=0 tid=0x00007f806813c000 nid=0x5c waiting for monitor entry [0x00007f8042ae9000]
"grpcServerPool-1-thread-26" #76 prio=5 os_prio=0 tid=0x00007f806813a000 nid=0x5b waiting for monitor entry [0x00007f8042bea000]
"grpcServerPool-1-thread-25" #75 prio=5 os_prio=0 tid=0x00007f8068138800 nid=0x5a waiting for monitor entry [0x00007f8042ceb000]
"grpcServerPool-1-thread-24" #74 prio=5 os_prio=0 tid=0x00007f8068136800 nid=0x59 waiting for monitor entry [0x00007f8042dec000]
"grpcServerPool-1-thread-23" #73 prio=5 os_prio=0 tid=0x00007f8068135000 nid=0x58 waiting for monitor entry [0x00007f8042eed000]
"grpcServerPool-1-thread-22" #72 prio=5 os_prio=0 tid=0x00007f8068133000 nid=0x57 waiting for monitor entry [0x00007f8042fee000]
"grpcServerPool-1-thread-21" #71 prio=5 os_prio=0 tid=0x00007f8068131800 nid=0x56 waiting for monitor entry [0x00007f80430ef000]
"grpcServerPool-1-thread-20" #70 prio=5 os_prio=0 tid=0x00007f806812f800 nid=0x55 waiting for monitor entry [0x00007f80431f0000]
"grpcServerPool-1-thread-19" #69 prio=5 os_prio=0 tid=0x00007f806812e000 nid=0x54 waiting on condition [0x00007f80432f1000]
"grpcServerPool-1-thread-18" #68 prio=5 os_prio=0 tid=0x00007f806812c000 nid=0x53 waiting for monitor entry [0x00007f80433f2000]
"grpcServerPool-1-thread-17" #67 prio=5 os_prio=0 tid=0x00007f806812a800 nid=0x52 waiting for monitor entry [0x00007f80434f3000]
"grpcServerPool-1-thread-16" #66 prio=5 os_prio=0 tid=0x00007f8068128800 nid=0x51 waiting for monitor entry [0x00007f80435f4000]
"grpcServerPool-1-thread-15" #65 prio=5 os_prio=0 tid=0x00007f8068126800 nid=0x50 waiting for monitor entry [0x00007f80436f5000]
"grpcServerPool-1-thread-14" #64 prio=5 os_prio=0 tid=0x00007f8068124800 nid=0x4f waiting for monitor entry [0x00007f80437f6000]
"grpcServerPool-1-thread-13" #63 prio=5 os_prio=0 tid=0x00007f8068123000 nid=0x4e waiting for monitor entry [0x00007f80438f7000]
"grpcServerPool-1-thread-12" #62 prio=5 os_prio=0 tid=0x00007f8068121000 nid=0x4d waiting for monitor entry [0x00007f80439f8000]
"grpcServerPool-1-thread-11" #61 prio=5 os_prio=0 tid=0x00007f806811f800 nid=0x4c waiting for monitor entry [0x00007f8043af9000]
"grpcServerPool-1-thread-10" #60 prio=5 os_prio=0 tid=0x00007f806811d800 nid=0x4b waiting for monitor entry [0x00007f8043bfa000]
"grpcServerPool-1-thread-9" #59 prio=5 os_prio=0 tid=0x00007f806811c000 nid=0x4a waiting for monitor entry [0x00007f8043cfb000]
"elasticsearch[scheduler][T#1]" #58 daemon prio=5 os_prio=0 tid=0x00007f8030047800 nid=0x49 waiting on condition [0x00007f8043dfc000]
"grpcServerPool-1-thread-8" #57 prio=5 os_prio=0 tid=0x00007f8068114800 nid=0x48 waiting for monitor entry [0x00007f8043efd000]
"grpcServerPool-1-thread-7" #56 prio=5 os_prio=0 tid=0x00007f8068112800 nid=0x47 waiting for monitor entry [0x00007f8043ffe000]
"grpcServerPool-1-thread-6" #52 prio=5 os_prio=0 tid=0x00007f8068111000 nid=0x43 waiting for monitor entry [0x00007f80a44e9000]
"grpcServerPool-1-thread-5" #51 prio=5 os_prio=0 tid=0x00007f806810f800 nid=0x42 waiting for monitor entry [0x00007f80a45ea000]
"grpcServerPool-1-thread-4" #50 prio=5 os_prio=0 tid=0x00007f8068102800 nid=0x41 waiting for monitor entry [0x00007f80a58ec000]
"grpcServerPool-1-thread-3" #49 prio=5 os_prio=0 tid=0x00007f8068100800 nid=0x40 waiting for monitor entry [0x00007f80a59ed000]
"grpcServerPool-1-thread-2" #48 prio=5 os_prio=0 tid=0x00007f80680fd800 nid=0x3f waiting for monitor entry [0x00007f80a5aee000]
"grpcServerPool-1-thread-1" #47 prio=5 os_prio=0 tid=0x00007f80680fa800 nid=0x3e waiting for monitor entry [0x00007f80a5bef000]
"grpc-nio-worker-ELG-3-1" #46 daemon prio=5 os_prio=0 tid=0x00007f809c006000 nid=0x3d runnable [0x00007f80a6ef1000]
"pool-2-thread-2" #45 prio=5 os_prio=0 tid=0x00007f80e8006800 nid=0x3c waiting on condition [0x00007f80a6ff2000]
"DataCarrier.GRPCRemoteClient.Consumer.0.Thread" #44 daemon prio=5 os_prio=0 tid=0x00007f80e006e000 nid=0x3b waiting on condition [0x00007f80a70f3000]
"DataCarrier.GRPCRemoteClient.Consumer.0.Thread" #43 daemon prio=5 os_prio=0 tid=0x00007f80e006c000 nid=0x3a waiting on condition [0x00007f80a71f4000]
"DataCarrier.GRPCRemoteClient.Consumer.0.Thread" #42 daemon prio=5 os_prio=0 tid=0x00007f80e006a800 nid=0x39 waiting on condition [0x00007f80a72f5000]
"DataCarrier.GRPCRemoteClient.Consumer.0.Thread" #41 daemon prio=5 os_prio=0 tid=0x00007f80e0068800 nid=0x38 waiting on condition [0x00007f80a73f6000]
"DataCarrier.GRPCRemoteClient.Consumer.0.Thread" #40 daemon prio=5 os_prio=0 tid=0x00007f80e0066800 nid=0x37 waiting on condition [0x00007f80a74f7000]
"DataCarrier.GRPCRemoteClient.Consumer.0.Thread" #39 daemon prio=5 os_prio=0 tid=0x00007f80e0063000 nid=0x36 waiting on condition [0x00007f80a75f8000]
"DataCarrier.GRPCRemoteClient.Consumer.0.Thread" #38 daemon prio=5 os_prio=0 tid=0x00007f80e0061000 nid=0x35 waiting on condition [0x00007f80a76f9000]
"DestroyJavaVM" #37 prio=5 os_prio=0 tid=0x00007f812800e800 nid=0x12 waiting on condition [0x0000000000000000]
"pool-11-thread-1" #36 prio=5 os_prio=0 tid=0x00007f8129f0c800 nid=0x34 waiting on condition [0x00007f80a79fa000]
"pool-10-thread-1" #35 prio=5 os_prio=0 tid=0x00007f8129f0a800 nid=0x33 waiting on condition [0x00007f80a7afb000]
"pool-9-thread-1" #34 prio=5 os_prio=0 tid=0x00007f8129f87000 nid=0x32 waiting on condition [0x00007f80a7bfc000]
"qtp293870357-33-acceptor-0@a94a6d-ServerConnector@4cdd2c73{HTTP/1.1, (http/1.1)}{0.0.0.0:12800}" #33 prio=5 os_prio=0 tid=0x00007f8129f82800 nid=0x31 runnable [0x00007f80a7cfd000]
"grpc-nio-boss-ELG-1-1" #31 daemon prio=5 os_prio=0 tid=0x00007f8129a48800 nid=0x2f runnable [0x00007f80f812b000]
"pool-2-thread-1" #30 prio=5 os_prio=0 tid=0x00007f80e8003800 nid=0x2e waiting on condition [0x00007f80f822c000]
"OkHttp ConnectionPool" #27 daemon prio=5 os_prio=0 tid=0x00007f80c4070800 nid=0x2b in Object.wait() [0x00007f80f874f000]
"OkHttp 192.168.0.1" #26 prio=5 os_prio=0 tid=0x00007f80c406e800 nid=0x2a runnable [0x00007f80f8850000]
"I/O dispatcher 1" #25 prio=5 os_prio=0 tid=0x00007f80b8001800 nid=0x29 runnable [0x00007f80f8b51000]
"pool-8-thread-1" #24 prio=5 os_prio=0 tid=0x00007f81299d1000 nid=0x28 runnable [0x00007f80f8c52000]
"controller-reflector-io.kubernetes.client.openapi.models.V1Pod-0" #23 prio=5 os_prio=0 tid=0x00007f80c000b800 nid=0x27 in Object.wait() [0x00007f80f8f59000]
"informer-controller-V1Pod" #21 prio=5 os_prio=0 tid=0x00007f80cc002800 nid=0x26 waiting on condition [0x00007f80f905a000]
"SKYWALKING_KUBERNETES_CLUSTER_INFORMER" #22 daemon prio=5 os_prio=0 tid=0x00007f81287ad000 nid=0x25 waiting on condition [0x00007f80f915b000]
"DataCarrier.METRICS_L1_AGGREGATION.BulkConsumePool.3.Thread" #19 daemon prio=5 os_prio=0 tid=0x00007f812a241800 nid=0x24 waiting on condition [0x00007f80f986f000]
"DataCarrier.METRICS_L1_AGGREGATION.BulkConsumePool.2.Thread" #18 daemon prio=5 os_prio=0 tid=0x00007f812a240000 nid=0x23 waiting on condition [0x00007f80f9970000]
"DataCarrier.METRICS_L1_AGGREGATION.BulkConsumePool.1.Thread" #17 daemon prio=5 os_prio=0 tid=0x00007f812a23d800 nid=0x22 waiting on condition [0x00007f80f9a71000]
"DataCarrier.METRICS_L1_AGGREGATION.BulkConsumePool.0.Thread" #16 daemon prio=5 os_prio=0 tid=0x00007f812a23c800 nid=0x21 waiting on condition [0x00007f80f9b72000]
"DataCarrier.METRICS_L2_AGGREGATION.BulkConsumePool.0.Thread" #15 daemon prio=5 os_prio=0 tid=0x00007f812a23a000 nid=0x20 waiting on condition [0x00007f80f9c73000]
"DataCarrier.TopNWorker.Consumer.0.Thread" #14 daemon prio=5 os_prio=0 tid=0x00007f812a238000 nid=0x1f waiting on condition [0x00007f80f9d74000]
"pool-4-thread-1" #13 prio=5 os_prio=0 tid=0x00007f812a234800 nid=0x1e waiting on condition [0x00007f80f9e75000]
"pool-3-thread-1" #12 prio=5 os_prio=0 tid=0x00007f812a1e2800 nid=0x1d waiting on condition [0x00007f80f9f76000]
"Thread-2" #11 prio=5 os_prio=0 tid=0x00007f81292c7000 nid=0x1c runnable [0x00007f80fb07b000]
"server-timer" #10 daemon prio=5 os_prio=0 tid=0x00007f81292c2000 nid=0x1b in Object.wait() [0x00007f80fb17c000]
"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x00007f81280bd800 nid=0x19 runnable [0x0000000000000000]
"C1 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f81280b8800 nid=0x18 waiting on condition [0x0000000000000000]
"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f81280b6000 nid=0x17 waiting on condition [0x0000000000000000]
"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f81280b4800 nid=0x16 runnable [0x0000000000000000]
"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f8128080800 nid=0x15 in Object.wait() [0x00007f8118dfc000]
"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f812807c000 nid=0x14 in Object.wait() [0x00007f8118efd000]
