### ISSUE TITLE
Ui bug of timezone selection

### ISSUE THREAD

**Issue by xbkaishui** [apache/skywalking#5423]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [√] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  SW 8.1.0 jdk 1.8 os mac
- Which company or project?
   Credigo

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
When I change the timezone of the right bottom button, the return data show in ui  is not format by select timezone, 
and also when click the select one day button, the time is not use choose timezone
please check below picture 
<img width="644" alt="屏幕快照 2020-09-01 下午4 59 16" src="https://user-images.githubusercontent.com/1477791/91830820-d9586880-ec75-11ea-8703-2a579f8d85de.png">

for UTC-3 , the correct time is 20200831:0559 to   20200901:0559

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Do you plan to fix this? Or need @TinyAllen to take a look?

**Comment by xbkaishui** [comment]
Aha, let me check first :joy:
