### ISSUE TITLE
Have to setup skywalking for each nginx location

### ISSUE THREAD

**Issue by ramonli** [apache/skywalking#5428]
I am trying to integrate skywalking with nginx, what bothering me is that it seem I have to setup skywlking for each location.
![image](https://user-images.githubusercontent.com/1152328/91928485-c776d400-ed0e-11ea-81e5-b91412669459.png)

can I just setup global skywalking for all nginx locations?

**Comment by wu-sheng** [comment]
That is how things work. You need to intercept all requests.
