### ISSUE TITLE
Agent support dynamic load config without restart instance

### ISSUE THREAD

**Issue by xbkaishui** [apache/skywalking#5430]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [√] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

For some scenario, we need change some configration of agent such as samplingRate, collect http params swith, this is more flexible to dynamic change the config without restart instance.  can we add it as feature ?

**Comment by kezhenxu94** [comment]
You'd better change the config through the `Command` responded from the backend when heart beating, instead of reloading the config file

**Comment by xbkaishui** [comment]
Ok, sound good to me，let me check logic and see how to implement it

**Comment by wu-sheng** [comment]
Loading dynamic config from file is fine. But like backend, it should through another file, not agent.config. 
Read backend es username password update.

Of course, through backend dynamic config is super.

**Comment by xbkaishui** [comment]
Yes, I agree it's better to config through backend command

**Comment by wu-sheng** [comment]
Personally, I prefer to provide a file watcher for agent, and the command system only provides a capability to update the dynamic config file.

This provides two capabilities at the same time, 
1. Could use backend configuration to update the configuration in batch(eg. all instance of a service)
1. Update one agent config manually.

Especially, terminal-based agent config update is safer in the product environment.

NOTE, not all configuration should support changing dynamically. They should be declared clearly, and if they are going to provide in the upstream release, they must be reviewed manually.

**Comment by wtsoftware** [comment]
use jvm attach agent，Is this method feasible？rebuild the agent

**Comment by wu-sheng** [comment]
> attach agent

It provides limited features, and it is not matching SkyWalking's requirement.

**Comment by wtsoftware** [comment]
> > attach agent
> 
> It provides limited features, and it is not matching SkyWalking's requirement.

Ok,your mean is monitor agent.conf file change? and call ServiceManager.shutdonw ->initializeCoreConfig->ServiceManager.boot ，Now follow this procedure to refresh the configuration successfully。 e ok?

**Comment by xbkaishui** [comment]
No, I think in agent side, we can just dynamic change Config  and Plugin related Config

**Comment by wu-sheng** [comment]
> Ok,your mean is monitor agent.conf file change?

No, we don't recommend doing this. 

>  I think in agent side, we can just dynamic change Config and Plugin related Config

Yes, I prefer this way.

**Comment by cheetah012** [comment]
Our approach here is to add a grpc interface. The agent side pulls the configuration information from the server every 60 seconds

**Comment by wu-sheng** [comment]
> Our approach here is to add a grpc interface. The agent side pulls the configuration information from the server every 60 seconds

The command system is there. It would be easy to use that.
