### ISSUE TITLE
view topological graph return exception

### ISSUE THREAD

**Issue by qlql489** [apache/skywalking#5434]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
8.1.0 ， deploy in k8s
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

view topological graph ,
the ui show: "No Endpoint Dependency"
query string: {"query":"query queryData($duration: Duration!) {cpm_0: readMetricsValue(condition: …
return code :500
responce:
error: "Internal Server Error"
exception: "com.netflix.zuul.exception.ZuulException"
message: "GENERAL"
status: 500
timestamp: 1599114115217

how to resolve the exception
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This means your backend is not ready. Please check your deployment.

**Comment by qlql489** [comment]
but other query is normal ，only few quey has exception

**Comment by wu-sheng** [comment]
Don't understand your meaning. You have the codes, try to provide some useful information if you want our help. Your descriptions mean nothing, we can't help.
