### ISSUE TITLE
How does SkywalkingMeterRegistry send mertrics to the OAP backend?

### ISSUE THREAD

**Issue by ramonli** [apache/skywalking#5436]
I just can't make my spring boot application work with skywalking(8.1.0) according to **https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/spring-sleuth-setup.md**

Setup agent
![image](https://user-images.githubusercontent.com/1152328/92112779-db125f80-ee20-11ea-8cfa-7dcb80348488.png)

Setup skywalking meter-registry:

    @Bean
    public SkywalkingMeterRegistry skywalkingMeterRegistry() {
        // Add rate configs If you need, otherwise using none args construct
        SkywalkingConfig config = new SkywalkingConfig(Arrays.asList(""));
        return new SkywalkingMeterRegistry(config);
    }

Create counter:

    @PostMapping("/search-group") 
    public ProductSearchGroupInfo searchGroupInfo(SearchInputParamInfo searchInputParam) { 
        ProductSearchGroupInfo groupInfo = this.productSearchFacadeProvider.searchGroupInfo(searchInputParam); 
        Counter saleCounter = Counter.builder("product.search-group").tag("category", "test-skywalking")
            .register(this.meterRegistry);
        saleCounter.increment();
        return groupInfo;
    }

And then the backend setting:
// spring-sleuth.yaml
![image](https://user-images.githubusercontent.com/1152328/92112887-0e54ee80-ee21-11ea-96a5-a9f21cda88f5.png)

// application.yaml
![image](https://user-images.githubusercontent.com/1152328/92113135-74417600-ee21-11ea-9c22-49342fe60a03.png)

Finally at the web UI, I have no idea how to configure this item to make it work. 
![image](https://user-images.githubusercontent.com/1152328/92113119-6d1a6800-ee21-11ea-881c-75ea84a39309.png)

Also I really wonder how does SkywalkingMeterRegistry send mertrics to the OAP backend? just no document found.

Thanks a lot.

**Comment by ramonli** [comment]
![image](https://user-images.githubusercontent.com/1152328/92113456-ec0fa080-ee21-11ea-91d8-0f7bb5ced060.png)
Seem the built-in sleuth pane works well.

**Comment by wu-sheng** [comment]
I don't follow what you mean. The document is here, https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-meter.md#meters-configure, which has been linked in the documents you posted.
