### ISSUE TITLE
Reading and Writing Separation in Storage .

### ISSUE THREAD

**Issue by xfzbw** [apache/skywalking#5437]
We need separate reading and writing in storage to improve skywalking oap receive performance
Scene sample : I use ES as storage, In oap server sider, I have 3 receiver and 2 aggregator, the total QPS is about 2k, many agent collect info is neglect. There’s many “No Peer” and “VirtualNode” info in the trace . Then I close all aggregator, the QPS can rise to 6k which is about three times than before. The main reason is aggregate needs many statistic count by ES. Reading influences the writing ability of ES. 
So if separate reading and writing , it will have great performance improvement. ES support reading and writing divid, but skywalking aggregator doesn’t support reading and writing divid( there’s only one storage url config)

**Comment by xfzbw** [comment]
The label is backend \ improment

**Comment by wu-sheng** [comment]
I totally lost about what you are saying. Very confused. There isn't a performance difference from the two ways of deployments, even the aggregation/receiver separated deployment has better performance from our tests.

**Comment by xfzbw** [comment]
> I totally lost about what you are saying. Very confused. There isn't a performance difference from the two ways of deployments, even the aggregation/receiver separated deployment has better performance from our tests.

The two ways of deployments have almost the same performance ,it's right. My question and  requirement is different. We need Skywalking have the ablility to  config different storage url  which one is read and one is write ,to impove the storage performance  .

**Comment by xfzbw** [comment]
Please do not simply regard read as read. Count  \sum  and  some other count functions cosumes many resource

**Comment by xfzbw** [comment]
Repeat again as  my first post content: 
Scene sample : I use ES as storage, In oap server sider, I have 3 receiver and 2 aggregator, the total QPS is about 2k, many agent collect info is neglect. There’s many “No Peer” and “VirtualNode” info in the trace . Then I close all aggregator, the QPS can rise to 6k which is about three times than before.

**Comment by xfzbw** [comment]
> Still don't understand, why SkyWalking needs to worry about your private usage. If you don't provide real cases related to SkyWalking itself. There is no point we continue here.

Repeat again as my first post content:
Scene sample : I use ES as storage, In oap server sider, I have 3 receiver and 2 aggregator, the total QPS is about 2k, many agent collect info is neglect. There’s many “No Peer” and “VirtualNode” info in the trace . Then I close all aggregator, the QPS can rise to 6k which is about three times than before. The agent side maintain the same before and after the server side adjustment.

**Comment by wu-sheng** [comment]
I know your description, but so what? If you think mixed role deployment fits you better. Just use it.

**Comment by xfzbw** [comment]
> I know your description, but so what? If you think mixed role deployment fits you better. Just use it.

No ,you misunderstanding my meaning,it'st not mix or seperate deployment problem. It's about skywalking should support reading writing storage divided by config. The aggregate role also have read and write action, aggregate role should have two storage config property row, one is for read (statistic),another for write( the statistic result).  In ES  reading writing seperation is implement by  primary node and copy node ,it cant't write data to copy node .

**Comment by xfzbw** [comment]
> I know your description, but so what? If you think mixed role deployment fits you better. Just use it.

In my cases, i shift the skywalking performance three times by  stoping the aggregate node ,only run the receive node . Why there has so large performance improvement,because the aggregate action influence  ES writeing ability.

**Comment by xfzbw** [comment]
I shift the skywalking performance three times by stoping the aggregate node ,But aggregate  ability is needed

**Comment by wu-sheng** [comment]
We don't take the responsibility of explaning the codes. You should read the codes by yourself.
