### ISSUE TITLE
The following bug occurred during my cluster deployment, and the program was forced to launch. Where is the configuration problem?

### ISSUE THREAD

**Issue by O-ll-O** [apache/skywalking#5438]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The following bug occurred during my cluster deployment, and the program was forced to launch. Where is the configuration problem?

![bug](https://user-images.githubusercontent.com/48112006/92192259-287de380-ee98-11ea-844e-2d2524e9a3b2.jpg)

_

### Bug
- Which version of SkyWalking, OS and JRE?
helm 3.+
ealstaticsearch 7
skwalking 8.+
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
OAP is reading API server for getting instance/pod list. Somehow, it is rejecting.
