### ISSUE TITLE
 init_worker_by_lua error: init_worker_by_lua:6: unexpected symbol near '#'

### ISSUE THREAD

**Issue by wangriyue001** [apache/skywalking#5439]
Please answer these questions before submitting your issue.

发生问题的版本
openresty-1.17.8.2
apache-skywalking-apm-es7-8.1.0.tar.gz
skywalking-nginx-lua-0.2.0.zip

**Comment by wu-sheng** [comment]
This kind of description isn't helpful. This is like an LUA grammar issue.
