### ISSUE TITLE
bug with ui

### ISSUE THREAD

**Issue by lzhaoyang** [apache/skywalking#5440]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [* ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
it seems there was a bug with ui refresh data.
___
### Bug
- Which version of SkyWalking, OS and JRE?

OS: windows 10
JRE: oracle jdk8
skywalking: 8.0.1

hello, I am deploy the skywalking on my local computer. and i can see the data on the ui pages.
but the default ui refresh setting does not work.  I think when i set the ui refresh time,it should 
fetch data and refresh the ui in time,but it happens nothing.

![image](https://user-images.githubusercontent.com/14249262/92211988-e36fa680-eec3-11ea-9b70-ac2b893d9f07.png)

I open this page for a long time and take a screenshot of this page. the picture shows ui dose not  launch  any requst for fetching data. 

Is this a bug or I have the wrong set? hope you can reply. Thanks very much.

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I just tried the demo page, refreshing works.

**Comment by wu-sheng** [comment]
http://122.112.182.72:8080/
