### ISSUE TITLE
start to error

### ISSUE THREAD

**Issue by dd01panqinglong** [apache/skywalking#5447]
### oal
endpoint_500 = from(Endpoint.*).percent(status == false);
### oap
endpoint_500_rule:
        # Metrics value need to be long, double or int
        metrics-name: endpoint_500
        op: ">"
        threshold: 1
        period: 10
        count: 1
        silence-period: 1
        message: Successful rate of endpoints_500 {name} is lower than 1% in 1 minutes of last 10 minutes
### oap-server
org.apache.skywalking.oap.server.core.storage.model.ModelInstaller -50520 [main] INFO  [] - table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later

**Comment by wu-sheng** [comment]
The document has told what is `no-init` mode.
