### ISSUE TITLE
not can custom oal scripts

### ISSUE THREAD

**Issue by dd01panqinglong** [apache/skywalking#5448]
### oal
Endpoint_200 = from(Endpoint.*).filter(responseCode like "2%").percent()
### oap
endpoint_200_rule:
        # Metrics value need to be long, double or int
        metrics-name: endpoint_200
        op: ">"
        threshold: 1
        period: 10
        count: 1
        silence-period: 1
        message: Successful rate of endpoints_500 {name} is lower than 1% in 1 minutes of last 10 minutes
### oap-server
line 41:53 no viable alternative at input 'responseCode like'
line 41:53 mismatched input 'like' expecting {SPACE, '='}
line 41:58 mismatched input '"2%"' expecting {SPACE, '='}

**Comment by wu-sheng** [comment]
response code is a number, note the document.
