### ISSUE TITLE
Question of getting HTTP POST parameter

### ISSUE THREAD

**Issue by Silverbullet9** [apache/skywalking#5449]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or  discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The parameters of HTTP POST request are needed in my data analysis project. 
I tried to add plugin.springmvc.collect_http_params of skywalking. 
After that, I could get the parameters of HTTP GET request. 
However, when I tried to send a POST request, there was no parameter. 
Did anyone meet this problem before?
Appreciate to your help!
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We only collected key~value pair before. In next release, we will have body collecting.

**Comment by 1393467261** [comment]
> We only collected key~value pair before. In next release, we will have body collecting.

Wondering if the body-collect feature is supported or not? There are some troubles getting http body.
