### ISSUE TITLE
I want to collect business statistics through Prometheus and micrometer, and then access skywalking to display data, how to configure？

### ISSUE THREAD

**Issue by pengyiwen139** [apache/skywalking#5452]
I want to collect business statistics through Prometheus and micrometer, and then access skywalking to display data, how to configure？god help me please~

**Comment by wu-sheng** [comment]
We have document and examples already

**Comment by pengyiwen139** [comment]
请问具体示例在哪呢，还是没找到，我是想用springboot的micrometer进行具体业务数据的收集，然后就是不知道如何把他们自定义推送展示到skywalking上
________________________________
发件人: 吴晟 Wu Sheng <notifications@github.com>
发送时间: 2020年9月7日 18:05
收件人: apache/skywalking <skywalking@noreply.github.com>
抄送: pengyiwen139 <pengyiwen139@outlook.com>; Author <author@noreply.github.com>
主题: Re: [apache/skywalking] I want to collect business statistics through Prometheus and micrometer, and then access skywalking to display data, how to configure？ (#5452)


We have document and examples already

―
