### ISSUE TITLE
Can skywalking capture SQL statements such as insert and update?

### ISSUE THREAD

**Issue by smilesheep** [apache/skywalking#5455]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Can skywalking capture SQL statements such as insert and update?
![sql20200908102901](https://user-images.githubusercontent.com/12063433/92427315-bfaba980-f1be-11ea-8bfc-9ee79b57a821.png)

**Comment by wu-sheng** [comment]
How you do run the insert statement? Check the postgre client source and plugin codes in `postgresql-8.x-plugin`. Is there any method that isn't being traced?

**Comment by wu-sheng** [comment]
Our test case could trace the insert SQL. This is our expected data file, https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/postgresql-scenario/config/expectedData.yaml#L47

**Comment by smilesheep** [comment]
thanks
