### ISSUE TITLE
Java Agent on Tomcat 9

### ISSUE THREAD

**Issue by karunanidiraja** [apache/skywalking#5458]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Dear All, I am new for skywalking and interested to try on my company. After following the steps for UI configuration, i able to see skywalking web page successfully. Then i have started to configure java agent on Tomcat (Tomcat 9 - installer version). I have added below line after @echo off on bin/catalina.bat file.
set "CATALINA_OPTS=-javaagent:E:\ProgramFiles\skywalking\agent\skywalking-agent.jar"

After this configuration ideally i should see this tomcat on Current service. But its no showing.

Can anybody help me to resolve this issue. Thanks in advance.

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking : 8.1.0
OS : Windows
JRE : 1.8.0_231
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What does agent log days?
