### ISSUE TITLE
Alarm support wechat webhook

### ISSUE THREAD

**Issue by xbkaishui** [apache/skywalking#5460]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [√ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Currently I saw slack and normal webhooks were added in SW, I want to add feature to support wechat webhook. 
Design: 
for the wechat webhook, it is similar to slack webhook, the difference is the request body , for example
```
curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=693axxx6-7aoc-4bc4-97a0-0ec2sifa5aaa' \
   -H 'Content-Type: application/json' \
   -d '
   {
        "msgtype": "text",
        "text": {
            "content": "hello world"
        }
   }'

```

For the Alarm webhook function, I think we can make some kind of abstraction， make the request body as a template
using template engine to render the template with the AlarmMessge

**Comment by wu-sheng** [comment]
We are open to his feature.

**Comment by xbkaishui** [comment]
@JaredTan95  I want to merge slack webhook function and normal webhook into Single webhook , which can support template(velocity engine) to dynamic generate the Post Resquest body, what do you think?

**Comment by wu-sheng** [comment]
Are those highly compatible? Usually, we expect API integration could be separated. Because it is easier to maintain, enhance, and bug fix.

One user may know nothing about others.

**Comment by wu-sheng** [comment]
BTW, all differences of any HTTP APIs are URI and HTTP body. 🤪 We can't say they are all similar and be replaced by the template.

**Comment by xbkaishui** [comment]
> Are those highly compatible? Usually, we expect API integration could be separated. Because it is easier to maintain, enhance, and bug fix.
> 
> One user may know nothing about others.
I think there are two solutions todo this.
1. break change.  merge slack and webhook to uniform one like belows: 

```
  webhooks:
       -
       url: http://xxx
       template: "sss"
       headers: ""
       -
       url: http://xxx
       template: "sss"
       headers: ""
        
```

2. Enhance slactHooks to support with template engine,  not change the webhooks config

what do you think?

**Comment by xbkaishui** [comment]
> BTW, all differences of any HTTP APIs are URI and HTTP body. 🤪 We can't say they are all similar and be replaced by the template.

For the webhook providers, I checked dingtalk, wechat they are both similar with slack

**Comment by xbkaishui** [comment]
I just want the webhook to be more general, refer to [zendesk webhook](https://support.zendesk.com/hc/en-us/articles/204890268-Creating-webhooks-with-the-HTTP-target#topic_yf1_fs5_tr)

**Comment by wu-sheng** [comment]
You add a thing called template, then what the difference of putting this alarm? I can't see much difference. 
This is my point.

**Comment by xbkaishui** [comment]
template can make request body dynamic, for example: 
`{
        "msgtype": "text",
        "text": {
            "content": ... $name, 报警内容 $alarmMessage
        }
   }`

the $name and $alarmMessage come from AlarmMessage body.  we can use velocity engine dynamic generate the request body based on AlarmMessage

**Comment by wu-sheng** [comment]
I know your meaning, we have freemarker in the oap lib. I am talking from design principle perspective.
