### ISSUE TITLE
start oap in idea failed

### ISSUE THREAD

**Issue by qlql489** [apache/skywalking#5463]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
download from github, use idea
i have finsh step 1 to 3  refer to https://github.com/apache/skywalking/blob/master/docs/en/guides/How-to-build.md
when i start OAPServerStartUp  show some error messages:

Error:(22, 1) java: 程序包lombok不存在
Error:(36, 81) java: 找不到符号
  符号:   方法 storage()
  位置: @interface org.apache.skywalking.oap.server.core.analysis.Stream
Error:(39, 6) java: 找不到符号
  符号:   类 Setter
  位置: 类 org.apache.skywalking.oap.server.core.analysis.generated.serviceinstanceclrthread.InstanceClrAvailableWorkerThreadsMetrics
Error:(39, 56) java: 找不到符号
  符号:   类 IDColumn
  位置: 类 org.apache.skywalking.oap.server.core.analysis.generated.serviceinstanceclrthread.InstanceClrAvailableWorkerThreadsMetrics

how to resolve it?
___
### Bug
- Which version of SkyWalking, OS and JRE?
tag 8.1.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
Please install Lombok plugin in your IDEA and enable annotation processor

**Comment by qlql489** [comment]
i have installed Lombok plugin  and enable annotation processor， but not usefull ，see ![](http://image.nianlun.tech/2020/09/10/9c195acf870d0d3e560b88fee52af499.jpg)

**Comment by kezhenxu94** [comment]
1. installing a plugin requires the IDEA to restart to take effect
2. make sure to import the project as maven project, and the maven dependencies are correctly refreshed
