### ISSUE TITLE
alarm logic is confused

### ISSUE THREAD

**Issue by ijiaojian** [apache/skywalking#5467]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [✔ ] Question or discussion

___
- Which version of SkyWalking, OS and JRE?
version: 8.1.0 
JRE: 1.8

**- What happened?**
alarm dynamic config.
when we config the alarm-settings.yml  in a zookeeper like this:
```java
rules:
  service_resp_time_rule:
    metrics-name: service_resp_time
    op: ">"
    threshold: 30
    period: 1
    silence-period: 1
    message: "aaaaaa"
    count: 1
  service_cpm_rule:
    metrics-name: service_cpm
    op: ">"
    threshold: 1
    period: 1
    silence-period: 1
    message: "bbbbbb"
    count: 1
webhooks:
  - http://127.0.0.1:8002/alarm-api/alarm
```

then , we initiate two requests which response time longer than 2 seconds.
this example, we should receive a alarm message list  which contains "aaaaaa" and ""bbbbbb"",  but we only receive "aaaaaa" or "bbbbbb" singly  sometimes,  we also can receive a message list contains both of the two,  so ,  I don`t understand the alarm logic.

**Comment by wu-sheng** [comment]
You set period to 1, which could make this happens. Period maps to the window for alarm rule check, at least set 2 or 3.

**Comment by wu-sheng** [comment]
Don't ask us to explain the logic. The codes are there. Please read them.
