### ISSUE TITLE
agent.instance_name is too long and can not to show full

### ISSUE THREAD

**Issue by super-ajun** [apache/skywalking#5471]
My java app is run in kubernetes, and configure the skywalking agent.instance_name=uuid@hostname,  the uuid is 32 bit ,  the hostname is longer than 20  or is longer than 50, but the agent.instace_name max length is 50, I can cancel the uuid in instance name , but the name still more than 50, so in skywalking ui can not show full.  I want to show full , What should i do ?

**Comment by wu-sheng** [comment]
The reason behind this limitation is, the instance id is part of storage id, such as ElasticSearch row id. Once you use the super long key, it will break the storage.

This is the backend default setting
```
    /**
     * The max length of the service name.
     */
    private int serviceNameMaxLength = 70;
    /**
     * The max length of the service instance name.
     */
    private int instanceNameMaxLength = 70;
    /**
     * The max length of the endpoint name.
     *
     * <p>NOTICE</p>
     * In the current practice, we don't recommend the length over 190.
     */
    private int endpointNameMaxLength = 150;
```
If 70 works for you, welcome to submit a pull request to change `org.apache.skywalking.apm.agent.core.conf.Config`.

**Comment by EvanLjp** [comment]
agent supports env as instance ，such as MY_POD_NAME
