### ISSUE TITLE
trace.ignore_path does not work in spring cloud gateway

### ISSUE THREAD

**Issue by kangswx** [apache/skywalking#5472]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [x] Bug

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.6.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please use the latest version.
