### ISSUE TITLE
Current branch 'master' => OALRuntime.java => line 167 => streamAnnotationListenerMetricsPersistentWorker.notify

### ISSUE THREAD

**Issue by joacatito** [apache/skywalking#5477]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
master branch, windows 10, JRE 1.8.0_211
- Which company or project?
OALRT
- What happened?
On line 167, probably a misspeling.

The current line have this instruction: 
```java
streamAnnotationListenerMetricsPersistentWorker.notify(metricsClass);
```

I guess the correct must be:  
```java
streamAnnotationListener.notify(metricsClass);
```

I've just followed the instructions at How-to-build.

Tks.

**Comment by wu-sheng** [comment]
The L167 is like this.
https://github.com/apache/skywalking/blob/master/oap-server/oal-rt/src/main/java/org/apache/skywalking/oal/rt/OALRuntime.java#L167

What is the issue?
