### ISSUE TITLE
After the Kafka consumer topic sends another topic, there will be a gap

### ISSUE THREAD

**Issue by wujieaiyan** [apache/skywalking#5480]
![image](https://user-images.githubusercontent.com/22367785/93066856-06ad0980-f6ad-11ea-9e65-dc02beef7542.png)

After data processing, the consumption of Kafka will be sent to another topic, and there will be problems that cannot be tracked. Consumer and producer are not linked. The traceid is different

**Comment by wu-sheng** [comment]
You need a context to include these two operations. Try to add `@Trace` or use `custom-enhance-plugin` to track the method including these two. 
We also have highlighted the solution for Kafka consumer case, https://github.com/apache/skywalking/blob/master/docs/en/FAQ/kafka-plugin.md.
