### ISSUE TITLE
About Map to the tags included in the traces

### ISSUE THREAD

**Issue by yixiuzhemu** [apache/skywalking#5483]
Question or discussion

### Question
Dear sheng wu,I want ask you a question.
Map to the tags included in the traces ,this function it's already in master branch .
Why I can't use it in 8.10?
When can I use this function?Hope you can answer me early.
[https://github.com/apache/skywalking-query-protocol/blob/master/trace.graphqls](url)
![image](https://user-images.githubusercontent.com/32632414/93155361-80d6a000-f738-11ea-9426-7099b7f0c408.png)

**Comment by wu-sheng** [comment]
Simple answer is, `master` != `8.1.0`.

**Comment by yixiuzhemu** [comment]
Ok，When release the next version?

**Comment by yixiuzhemu** [comment]
And,How can I use this function?

**Comment by wu-sheng** [comment]
Maybe next month. The release bases on community activity.

**Comment by yixiuzhemu** [comment]
Ok，Thank you very much
