### ISSUE TITLE
will the skywalking support the oracle db?

### ISSUE THREAD

**Issue by chensp0668** [apache/skywalking#5485]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
currently,most db is mysql or maridb in the internet project,but some projects use the oracle db as well,I check the agent plugins,it seems that not support oracle.
___
### Question
- What do you want to know?
I want to know it will support oracle db?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Take a look https://github.com/SkyAPM/java-plugin-extensions. It is out of Apache, because Oracle is a commercial software.
