### ISSUE TITLE
skywalking agent 7.1 match oapserver 8.1 

### ISSUE THREAD

**Issue by sky-dail** [apache/skywalking#5487]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Did skywalking agent 7.1 match oapserver 8.1 ?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by sky-dail** [comment]
Did skywalking agent 7.1 match oapserver 8.1 and ui 8.1.0?

**Comment by wu-sheng** [comment]
We never have that 7.1 release.

**Comment by sky-dail** [comment]
7.0

**Comment by wu-sheng** [comment]
We don't support that. v3 protocol is used since 8.0
