### ISSUE TITLE
Support build individual module 

### ISSUE THREAD

**Issue by xbkaishui** [apache/skywalking#5488]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
 current main branch  can't build individual module, 
exception is 
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.094 s
[INFO] Finished at: 2020-09-15T15:34:10+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project apm-agent: Failed during checkstyle configuration: cannot initialize module TreeWalker - cannot initialize module ImportControl - illegal value 'apm-checkstyle/importControl.xml' for property 'file': com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: apm-checkstyle/importControl.xml -> [Help 1]
[ERROR] 

```
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
 It is caused by checkstyle file is relative to project root, should be absolute  
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Which command do you run?

**Comment by xbkaishui** [comment]
cd apm-agent
mvn clean package -DskipTests

**Comment by xbkaishui** [comment]
I found the root cause, will submit a pr to fix this.

**Comment by wu-sheng** [comment]
Don't do cd. Use mvn -f pointing to the target pom.xml.

**Comment by xbkaishui** [comment]
but if the submodule is too deep, it's not convenient to do this

**Comment by wu-sheng** [comment]
You could try to resolve, you will notice it would not be an eaay thing.

**Comment by xbkaishui** [comment]
there is a inner property in maven `maven.multiModuleProjectDirectory` which will support this
