### ISSUE TITLE
how to fix the bug that there are duplicate trace in segment？ 

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#5492]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by lsy1990** [comment]
Some time,we can get twice trace in trace by traceid.

**Comment by wu-sheng** [comment]
I don't know what do you mean duplicate.

**Comment by lsy1990** [comment]
@wu-sheng dear,sir, what I mean is there are two same records in segment table ,all infos of this two records are same, include trace id.
If we search it in trace by trace id,we should get two records.Thank a lot.

**Comment by wu-sheng** [comment]
I am not aware of any issue should cause duplicate segments, like a copy. This is totally new to me.
