### ISSUE TITLE
Support metrics APIs for agent plugin

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5494]
In the 8.1.0, we have supported our own toolkit library and MicroMeter integration for metrics in the java application. Now, ShardingSphere community is requesting to collect metrics in the agent plugin system.

Right now, the `transform` and `adapter` systems are for toolkit with activation. In the agent core, we need this kind of simple APIs, such as `MeterFactory#createCounter`, for use inside the agent.

**Comment by lujiajing1126** [comment]
IMO, It's a very interesting feature. We are also working on the metrics for the agent side recently, for example the metrics of Kafka producer and consumer.

My question is whether it is possible to use micrometer in the plugin thru [`MeterBinder`](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/MeterBinder.java). Then everything would be extremely easy in the sense that there are a lot of micrometer implementations now.

I suppose so far the micrometer plugin is only available for the application.

**Comment by wu-sheng** [comment]
MicroMeter has been supported for a while. This is for auto instrumentation metrics collection.

**Comment by wu-sheng** [comment]
> I suppose so far the micrometer plugin is only available for the application.

Don't know what this means. @lujiajing1126

**Comment by lujiajing1126** [comment]
> > I suppose so far the micrometer plugin is only available for the application.
> 
> Don't know what this means. @lujiajing1126

I understand the micrometer support can be introduced by including `apm-toolkit-micrometer-registry` as a dependency in the service. And this requires manual work which is documented here https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-micrometer.md

But I am wondering if it is possible to support micrometer in the core part. So we can adapt a collection of `MeterBinder` provided by the community of micrometer. For instance [KafkaClientMetrics](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetrics.java), we can use it directly in the constructor interceptor of `KafkaProducer` and `KafkaConsumer` which thus does not need any manual code in the application.

**Comment by wu-sheng** [comment]
> But I am wondering if it is possible to support micrometer in the core part. So we can adapt a collection of MeterBinder provided by the community of micrometer. For instance KafkaClientMetrics, we can use it directly in the constructor interceptor of KafkaProducer and KafkaConsumer which thus does not need any manual code in the application.

This is very dangerous to do the integration. Use a 3rd party APIs and its implementation in the agent core would face the class loader issue. You should have noticed, we never introduce any other libs in the agent, unless the agent core uses itself, and it would be shaded in another package name to avoid conflict.

From my understanding of the micrometer system, KafkaClientMetrics is at the instrumentation side, once you activated that, and also activated the SkyWalking register, the metrics will flow into agent core directly. Have you tested?

**Comment by lujiajing1126** [comment]
> This is very dangerous to do the integration. Use a 3rd party APIs and its implementation in the agent core would face the class loader issue. You should have noticed, we never introduce any other libs in the agent, unless the agent core uses itself, and it would be shaded in another package name to avoid conflict.

Yes. I fully understood this concern. But also I believe as long as we shade the library and all its dependencies, that would not be a problem. We have developed some other agent which includes `micrometer` in the agent, of course with package shades. Everything works well except that we cannot talk to this kind of API from the application with any shaded class which is a known caveat.

> From my understanding of the micrometer system, KafkaClientMetrics is at the instrumentation side, once you activated that, and also activated the SkyWalking register, the metrics will flow into agent core directly. Have you tested?

Anyway, we will have an investigation first.

**Comment by wu-sheng** [comment]
As I mentioned, shade is not the problem, the problem is why you need this. API-based instrumentation(Prometheus SDK or MicroMeter) solution should not be mixed with the agent. That breaks the design at the both side. 
If you have some private agenda on this, it is fine. But base on your given information, it doesn't make sense to me.

**Comment by lujiajing1126** [comment]
> As I mentioned, shade is not the problem, the problem is why you need this. API-based instrumentation(Prometheus SDK or MicroMeter) solution should not be mixed with the agent. That breaks the design at the both side.
> If you have some private agenda on this, it is fine. But base on your given information, it doesn't make sense to me.

I see what you meant. So I guess the so-called native implementation without third-party dependency is still acceptable in the community, right?

**Comment by wu-sheng** [comment]
I don't know what do you mean acceptable. To accepy what? I think I am losing the context.

**Comment by lujiajing1126** [comment]
> I don't know what do you mean acceptable. To accepy what? I think I am losing the context.

I mean we can contribute some implementations of the metrics for the instrumented library, for example the metrics of Kafka producer and consumer with the help of metrics API provided by Skywalking agent (Probably after the current issue is resolved).

**Comment by wu-sheng** [comment]
Yes, that is what these APIs for. We also require backend analysis config file and UI config. Then users could have these out of box.

**Comment by wu-sheng** [comment]
Note, mostly, we expect these plugins are monotoring Kafka server. Consumer and producer have been traced already. Then we could have a real Kafa dashboard.
