### ISSUE TITLE
Is there a place to download the agent package separately?

### ISSUE THREAD

**Issue by harvies** [apache/skywalking#5497]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean?

**Comment by harvies** [comment]
The binary package of the agent needs to be downloaded separately, which is currently obtained from the complete package decompression.

**Comment by wu-sheng** [comment]
They are designed in this way. All releases should be downloaded as a tarball. Agent with all plugins is a real official release.
