### ISSUE TITLE
SkyWalking metrics are shown to single session at a time

### ISSUE THREAD

**Issue by rrajadevops** [apache/skywalking#5498]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Recently we have configured Apache Skywalking 8.1.0 version and Java agent send metrics to OAP service and I can see the metrics. If my team members are trying to see the dashboard in same time they dont get metrics.

Java version I am using: openjdk version "11.0.8" 2020-07-14
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I am confused, what is the different? Do you set the same time and timezone?

**Comment by rrajadevops** [comment]
@wu-sheng  if I open installed skywalking URL in two different system, i can see metrics in only one machine. Another system I can see only blank page without metrics.

**Comment by wu-sheng** [comment]
I don't know why. Maybe local browser cache?
