### ISSUE TITLE
How to upgrade from 7.x to 8.x

### ISSUE THREAD

**Issue by LuckyMango** [apache/skywalking#5500]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
We made a small modification on skywalking7.0, and now we want to upgrade to 8.x. How to upgrade. Is 8.x compatible with 7.x

**Comment by kezhenxu94** [comment]
> Is 8.x compatible with 7.x

No, 8.x uses a brand new protocol, so you have to update both backend and agents, and storage data are not compatible as well (you need to erase the storage data)
