### ISSUE TITLE
How can i alarm for service endpoint response 500?

### ISSUE THREAD

**Issue by keontang** [apache/skywalking#5502]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

How can i alarm for service endpoint response 500?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
First, you need to create new metrics through the OAL script, then you can set up the alarm for it. Default, there isn't this kind of metrics.
