### ISSUE TITLE
endpoint list  duplicate item

### ISSUE THREAD

**Issue by qlql489** [apache/skywalking#5503]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
8.1.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
we use the officai docker image deploy the UI
endpoint list has duplicate item 
![](http://image.nianlun.tech/2020/09/17/a7dfb0d0af32fad84bbec0285ef84f7c.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
which docker image is recommend

**Comment by wu-sheng** [comment]
This seems your ElastichSearch having some issue, the data is time-series based if some shards are not available occasionally, then this endpoint will be added again.
Our demo and users have deployed the 8.x multiple times, didn't report this issue. If you could provide more detailed information, would be more helpful.

**Comment by qlql489** [comment]
I search the es data , the endpoint_traffic index has 7 days data，and I look the code,  search endpoint_traffic index will  aggregate   all  day's data  like endpoint_traffic-20200921、endpoint_traffic-20200922 .. make the list has duplicate item
[](http://image.nianlun.tech/2020/09/25/7ccf25cfc3e8fae95984617093061a27.png)  
what should i do ?

**Comment by wu-sheng** [comment]
Do you set up the cluster coordinator? If not, and run in the cluster mode, this could happen.
