### ISSUE TITLE
8.1.0 Segment sampling bug

### ISSUE THREAD

**Issue by linliaoy** [apache/skywalking#5504]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 8.1.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
package org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener;
segmentId.hashCode() It's going to be negative。SW_TRACE_SAMPLE_RATE is configured to be positive

example：
segmentid ：40ae9aaa370449bd80b61452fcf04154.125.16003124206517460
hashCode：-103557884
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Thanks for your report, this is a bug for backend sampling.

**Comment by wu-sheng** [comment]
Could you try to send a pull request to fix this? Adding `Math#abs` should be an easy fix.

**Comment by linliaoy** [comment]
#5506

**Comment by N-Harsha** [comment]
i am a newbie and want work on this issue so please could you point me in the right direction
