### ISSUE TITLE
Question about data collecting

### ISSUE THREAD

**Issue by zhaodp** [apache/skywalking#5516]
Can the agent reports data to Kafka, and the collector collects data from Kafka? Like this: agent->kafka->collector->es .
I am worried that the agent directly reports data to the collector. In the case of high concurrency, there will be performance problems

**Comment by dmsolr** [comment]
Yes, it is supported.
Please read [kafka-fetcher](https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-fetcher.md#kafka-fetcher)

**Comment by wu-sheng** [comment]
Note, Kafka would not ease the performance issue. It is just a buffer mechanism.

**Comment by zhaodp** [comment]
> Yes, it is supported.
> Please read [kafka-fetcher](https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-fetcher.md#kafka-fetcher)

Thanks for your reply.
