### ISSUE TITLE
failure enabling TLS in Docker distro of OAP server 8.1.0-es7

### ISSUE THREAD

**Issue by pantovad** [apache/skywalking#5518]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
Docker OAP server 8.1.0-es7 (https://github.com/apache/skywalking-docker/tree/master/8/8.1.0/oap-es7)

- Which company or project?

- What happened?
When enabling TLS on gRPC listener in OAP server it fails with errors missing required libraries.

___
### Requirement or improvement
- I managed to resolve the issue by using adoptopenjdk/openjdk11:alpine (instead of openjdk:8-jre-alpine) as base Java image for both base and OAP image.

**Comment by hanahmily** [comment]
it's because netty tc-native needs some dynamic libraries which apline doesn't contain. we should release a new base image to adopt to "jdk" instead of "jre".

Since OAP can work fine with jdk11, I prefer to use it as the new base image. 
@wu-sheng @kezhenxu94 ^^

**Comment by wu-sheng** [comment]
Work for me. Please update the docker file in the main repo first.

**Comment by hanahmily** [comment]
> Work for me. Please update the docker file in the main repo first.

main repo doesn't have this issue and uses the jdk based image all the time due to our development and debugging requirement.

**Comment by wu-sheng** [comment]
@innerpeacez I added this to the k8s release milestone for next version, in case we miss this in next time.

@hanahmily Do you plan to push the 8.1.0 images again for jdk binded?

@pantovad I will recommend you to re package first locally.

**Comment by kezhenxu94** [comment]
And now, when testing https://github.com/apache/skywalking/pull/5722 , I've also found that it(Kubernetes Java client) doesn't work well on openjdk:8-jdk (see https://github.com/kubernetes-client/java/issues/1003), thus I used openjdk:11-jdk for the tests, I suggest to upgrade the JDK version in the base image ASAP

**Comment by wu-sheng** [comment]
JDK11 as next TLS, make sense to me. Just feel strange, why JDK version matters
