### ISSUE TITLE
How to find witnessClasses efficiently when adapting multi-version plug-ins?

### ISSUE THREAD

**Issue by harvies** [apache/skywalking#5521]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to find witnessClasses efficiently when adapting multi-version plug-ins? When multi-version plug-ins coexist, the version plug-in will affect the effect of the new version plug-in. Can you give me some suggestions? I am currently planning to write a tool to find witnessClasses that exist in the old version but do not exist in the new version.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> I am currently planning to write a tool to find witnessClasses that exist in the old version but do not exist in the new version.

This is an interesting idea :). 

> How to find witnessClasses efficiently when adapting multi-version plug-ins?

From my experiences, there seems no efficient way to do this in theory. But, logically and in the real world, but we are targeting stable and widely used libraries, they wouldn't randomly change source codes. Once one important core level class changed, the code structure changed with them, like SkyWalking v7 and v8, you are easy to identify the differences. Of course, this experience wouldn't affect your tool.

**Comment by harvies** [comment]
> > I am currently planning to write a tool to find witnessClasses that exist in the old version but do not exist in the new version.
> 
> This is an interesting idea :).
> 
> > How to find witnessClasses efficiently when adapting multi-version plug-ins?
> 
> From my experiences, there seems no efficient way to do this in theory. But, logically and in the real world, but we are targeting stable and widely used libraries, they wouldn't randomly change source codes. Once one important core level class changed, the code structure changed with them, like SkyWalking v7 and v8, you are easy to identify the differences. Of course, this experience wouldn't affect your tool.

I have another idea to resolve the conflict. After reviewing the source code and testing, I found that skywalking does not seem to enhance the target class from high to low according to the version of the agent package. Usually, a class will not appear again after the old version of the package is removed. , But classes that exist in an old package usually also exist in a new package. Do you think it is feasible?

**Comment by wu-sheng** [comment]
Basically, witness and deactivateIfPreaent are very similar logically. It is really hard to tell which is better. Witness is just an APM tradition from old experiences only. 
I am also aware in some cases, deactivateIfPreaent may be easier. Are you facing any issue? Why bring this discussion up?

**Comment by harvies** [comment]
In the adaptation of mongo4.x, I found that if apm-mongodb-3.x-plugin exists, the 4.x MongoDBOperationExecutorInterceptor will not be executed because the target class is intercepted by 3.x, and com.mongodb.client.ClientSession is in 4.x exists.

**Comment by wu-sheng** [comment]
But in your #5512, tests for both versions exist and passed. Why?

**Comment by harvies** [comment]
db.statement verification failed.When plug-in 3.x exists, db.statement verification fails. The reason is that com.mongodb.client.ClientSession exists in mongo-drive3.x, and com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor is 3 .x is enhanced, the class Operation does not exist when db.statement is obtained, and an exception is thrown.

![image](https://user-images.githubusercontent.com/16585330/93694143-fb3d6080-fb3a-11ea-94a5-553b4b085abb.png)

**Comment by harvies** [comment]
Db.statement is normal when 3.x does not exist.
![image](https://user-images.githubusercontent.com/16585330/93694223-c41b7f00-fb3b-11ea-9e14-d9d586f42cb7.png)
![image](https://user-images.githubusercontent.com/16585330/93694229-d4cbf500-fb3b-11ea-918b-6d8902377226.png)

**Comment by wu-sheng** [comment]
Then you should add witness class, existing in 3.x but not 4.x, amy class. Then this could be resolved.

**Comment by harvies** [comment]
> Then you should add witness class, existing in 3.x but not 4.x, amy class. Then this could be resolved.

Yes, that is, as I said before, use the tool to find the witness class.

**Comment by wu-sheng** [comment]
If you want, you could share them with the community through dev mail list. 
Once it is stable and formal, we could consider to recommend it from the official document.

**Comment by harvies** [comment]
![image](https://user-images.githubusercontent.com/16585330/93711396-7c6b1680-fb80-11ea-83a9-ae5b8a60ff3e.png)
I did it, and I will submit the pr verification program later.
