### ISSUE TITLE
login interface

### ISSUE THREAD

**Issue by sodared** [apache/skywalking#5525]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Question

___
### Question
- What do you want to know?
Hi Mr.Wu , I was wondering if skywalking8.1.0 has a login interface . If there is , then which config file is to set up the user and password ? Thanks.
___
### Requirement or improvement
- I just upgrade the skw 6.1.0 to 8.1.0 and I can not find my log in interface . Neither could I set up in webapp.yml

**Comment by wu-sheng** [comment]
No, there isn't. The old login is not real.

**Comment by wu-sheng** [comment]
Use APISIX, Nginx or other proxy tech to set up a login page.

**Comment by sodared** [comment]
roger that
