### ISSUE TITLE
async span can't clear traceContext

### ISSUE THREAD

**Issue by liyanyan-dev** [apache/skywalking#5526]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [√ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- jdk 8
- skywalking8.1.0

- Which company or project?

- What happened?
My plugin uses async span. It is found that after the service has been running for a period of time, the number of reported span created exceeds the upper limit. After positioning, it is found that non async span will clear tracecontext when the last span is closed, but async span does not clear tracecontext

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Is this an official plugin? Or your private one?

**Comment by liyanyan-dev** [comment]
It's not official. I wrote it myself

**Comment by wu-sheng** [comment]
Then. you seems missing to call `finishSpan` in the main context. Please follow the plugin dev document.

**Comment by liyanyan-dev** [comment]
I called the stopSpan in main context;I've solved this problem：
![image](https://user-images.githubusercontent.com/54348450/93739511-0798ea80-fc1b-11ea-8654-a826f5223ae6.png)
![image](https://user-images.githubusercontent.com/54348450/93739535-1aabba80-fc1b-11ea-8288-fb5203432731.png)

**Comment by wu-sheng** [comment]
No, this is absolutely the wrong way.

**Comment by liyanyan-dev** [comment]
OK, I'll check my plugin again
