### ISSUE TITLE
resource_already_exists_exception + no such index [register_lock]

### ISSUE THREAD

**Issue by romantictravel01** [apache/skywalking#5527]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug
___
### Bug

apache/skywalking-oap-server:6.6.0-es7

Restart after power failure

1.exception type=resource_already_exists_exception reason=index ***already exists

2.2020/9/21 下午5:31:27org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=index_not_found_exception, reason=no such index [register_lock]]

**Comment by wu-sheng** [comment]
Register lock index has been removed since 8.0. We are not recommending to use the v2(6.x and 7.x) protocol based releases.
