### ISSUE TITLE
Current image doesn't Elasticsearch 6

### ISSUE THREAD

**Issue by romantictravel01** [apache/skywalking#5528]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Bug
___
### Bug
use  https://hub.docker.com/r/apache/skywalking-oap-server/tags
apache/skywalking-oap-server:8.1.0-es7

2020/9/21 下午6:05:46[Entrypoint] Apache SkyWalking Docker Image
2020/9/21 下午6:05:46Current image doesn't Elasticsearch 6

**Comment by wu-sheng** [comment]
Do you read what you said and document? A es7 image for es6?

**Comment by romantictravel01** [comment]
I haven't done any other configuration

**Comment by wu-sheng** [comment]
We highlighted this is for es7. Why you use in this way? Please read document.

**Comment by romantictravel01** [comment]
I used ES7, not ES6, but the error message was ES6

**Comment by wu-sheng** [comment]
You need configuration to activate core to use es7 implementation. That is why I am asking you to read document.

**Comment by romantictravel01** [comment]
**Notice
From version 6.6.0, we split the oap image into two tags, x.y.z-es6, and x.y.z-es7. As their name indicates, es6 intends to connect to Elasticsearch 6, and es7 to Elasticsearch 7.

The latest tag points to es6**


but I use apache/skywalking-oap-server:8.1.0-es7,Where is the document you said

**Comment by fanyongju** [comment]
Hello, is the problem solved? Because I also encountered the same problem, I hope you share the solution, thank you

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#elasticsearch

```
In order to activate ElasticSearch 6 as storage, set storage provider to elasticsearch
In order to activate ElasticSearch 7 as storage, set storage provider to elasticsearch7
```

We highlight the words in the first lines. Choosing the right image is only a part.

**Comment by fanyongju** [comment]
> https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#elasticsearch
> 
> ```
> In order to activate ElasticSearch 6 as storage, set storage provider to elasticsearch
> In order to activate ElasticSearch 7 as storage, set storage provider to elasticsearch7
> ```
> 
> We highlight the words in the first lines. Choosing the right image is only a part.

thank you @wu-sheng，following your hint, I solved the problem
