### ISSUE TITLE
 how alarm for long duration segment of trace in skywalking ui ?

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#5532]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
to alarm long duration segment,how config in alarm-settings.yml or Dynamic Configuration?
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 7.0.0 ,os linux ,jre jdk8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Alarm can't and shouldn't targeting on the traces. That will crash the whole system.
