### ISSUE TITLE
if i deploy cluster nodes with explicit role，how to set SW_AGENT_COLLECTOR_BACKEND_SERVICES on agent side?

### ISSUE THREAD

**Issue by shuxiaxia** [apache/skywalking#5533]
OS：CentOS Linux release 7.7.1908 (Core)

Skywalking version：apache-skywalking-apm-es7-8.1.0

I have a three node cluster with the following roles:

node01：SW_ CORE_ ROLE:Receiver

node02：SW_ CORE_ ROLE:Receiver

node03：SW_ CORE_ ROLE:Aggregator

In addition to the role settings of the three nodes, do I need other settings?
How should I set SW_ AGENT_ COLLECTOR_ BACKEND_ SERVICES on agent side？
Please forgive my poor English.

**Comment by wu-sheng** [comment]
We would recommend you to set a proxy for node01 and node02 as LB. Or you could add both node01 and node02 at the agent config.
