### ISSUE TITLE
instance name repeat with es

### ISSUE THREAD

**Issue by a6205206z** [apache/skywalking#5535]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- If index ('instance_traffic') is sharded by date, like this (instance_traffic-20200916 or instance_traffic-20200917), the instance name will be repeat.

> the code in MetadataQueryEsDAO.java at line 192

```java
        SearchResponse response = getClient().search(InstanceTraffic.INDEX_NAME, sourceBuilder);

        List<ServiceInstance> serviceInstances = new ArrayList<>();
```

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
It should be not. Once the instance added, it wouldn't be added again. Untill TTL timer removed it. This duplicate name has been reported in the service level, for me, it looks like some shards are not available somehow, then the OAP core rewrited it again to another index(base on time).

**Comment by a6205206z** [comment]
If I deploy the OAP server more than 1，this question  will arise, that's the reason？
Looking forward to your answer, and thanks.

**Comment by a6205206z** [comment]
> If I deploy the OAP server more than 1，this question will arise, that's the reason？
> Looking forward to your answer, and thanks.

I deploy 3 OAP server in my cluster, and each service has 3 identical instances.

**Comment by wu-sheng** [comment]
I think you don't set up the cluster coordinator, but just deploying 3 nodes separately.

**Comment by a6205206z** [comment]
thanks, I use k8s coordinator,but I config the the same SKYWALKING_COLLECTOR_UID, I think this is the reason.

thanks again.

**Comment by HackerRookie** [comment]
@a6205206z Do you solved it?
