### ISSUE TITLE
skywalking ui elasticsearch7 query

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#5537]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why is the number of UI query results always 10,000 with elasticsearch 7.x? And why is there no such problem with elasticsearch 6.x?
![image](https://user-images.githubusercontent.com/11767168/93867637-e956eb80-fcfb-11ea-9b63-0da16800d492.png)
Note: I am currently using skywalking 8.0.0.

**Comment by harvies** [comment]
This is a limitation of es7, you can find information on the Internet.

**Comment by SevenBlue2018** [comment]
Thank you very much. I have been negligent.
