### ISSUE TITLE
How to extend other database plugin 

### ISSUE THREAD

**Issue by oliuhuano** [apache/skywalking#5538]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to extend other database plugin, so that skywalking can monitor it, I don't know how to start, thanks.
___
### Bug
- Which version of SkyWalking, OS and JRE?
8.1.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We could develop plugins for your database client driver. We have provided plugin development doc already.

**Comment by oliuhuano** [comment]
> We could develop plugins for your database client driver. We have provided plugin development doc already.

Can Kingbase be supported？

**Comment by wu-sheng** [comment]
What do you mean `can`? Please explain.

**Comment by oliuhuano** [comment]
> What do you mean `can`? Please explain.

My database is Kingbase, can you develop plugins for Kingbase ? thanks.

**Comment by wu-sheng** [comment]
As an open-source community, this is not how we work. From my check, Kingbase is a commercial database, and not open sourced. So, you need to contact your vendor and ask them to do this in an open source or private way.

**Comment by oliuhuano** [comment]
> As an open-source community, this is not how we work. From my check, Kingbase is a commercial database, and not open sourced. So, you need to contact your vendor and ask them to do this in an open source or private way.

I see,thanks a lot.
