### ISSUE TITLE
Table "PROFILE_TASK" not found

### ISSUE THREAD

**Issue by javaalpha** [apache/skywalking#5541]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by javaalpha** [comment]
Caused by: org.h2.jdbc.JdbcSQLException: Table "PROFILE_TASK" not found; SQL statement:
select * from profile_task where 1=1  and time_bucket >= ?  and time_bucket <= ?  ORDER BY start_time DESC  [42102-196]

**Comment by wu-sheng** [comment]
Are you running the OAP with H2 mode for a long time?

**Comment by javaalpha** [comment]
Version:apache-skywalking-apm-8.1.0
JDK: 1.8.0_251
OS: Red Hat 4.8.5-39

**Comment by coolbeevip** [comment]
By default, closing the last connection to a database closes the database. For an in-memory database, this means the content is lost.

**Comment by wu-sheng** [comment]
@coolbeevip If you like, feel free to add a thread to hold the jdbc unclosed for h2 storage. We don't know this feature.

**Comment by wu-sheng** [comment]
Or set the connection pool at least one.

**Comment by coolbeevip** [comment]
> @coolbeevip If you like, feel free to add a thread to hold the jdbc unclosed for h2 storage. We don't know this feature.

See http://h2database.com/html/features.html#in_memory_databases  quote:

```
By default, closing the last connection to a database closes the database. For an in-memory database, this means the content is lost. To keep the database open, add ;DB_CLOSE_DELAY=-1 to the database URL. To keep the content of an in-memory database as long as the virtual machine is alive, use jdbc:h2:mem:test;DB_CLOSE_DELAY=-1.
```

Just config JDBC connect URL with DB_CLOSE_DELAY=-1. If you agree with this plan I will submit a PR

**Comment by wu-sheng** [comment]
Make sense, but please only add this for h2 storage.
