### ISSUE TITLE
Do we have circle skywalking logo (vector)?

### ISSUE THREAD

**Issue by juzhiyuan** [apache/skywalking#5542]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Hi, do we have the circle skywalking logo vector(svg)? so it will show properly on the plugin market page :D

![image](https://user-images.githubusercontent.com/2106987/93959393-23bb9980-fd8b-11ea-8895-40ea5fb1f5d0.png)

**Comment by wu-sheng** [comment]
You could find from here, https://apache.org/logos/#skywalking.
