### ISSUE TITLE
alarm's count properties real meaning?

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#5545]
Please answer these questions before submitting your issue.

i see official document and official alarm-setting.yml, count is represent as Frequency of occurrence or time[minute]?
for example:

1、official document 
Count. In the period window, if the number of values over threshold(by OP), reaches count, alarm should send

2、official alarm-setting.yml
  service_sla_rule:
    # Metrics value need to be long, double or int
    metrics-name: service_sla
    op: "<"
    threshold: 8000
    # The length of time to evaluate the metrics
    period: 10
    # How many times after the metrics match the condition, will trigger alarm
    count: 2
    # How many times of checks, the alarm keeps silence after alarm triggered, default as same as period.
    silence-period: 3
    message: **Successful rate of service {name} is lower than 80% in 2 minutes of last 10 minutes**

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Consider the period is a moving window caching the metrics. Every minute is a slot in the window. 
Alarm core checks the window every minute. Count means the minimal count of value in the slot over threshold.

**Comment by killGC** [comment]
> Consider the period is a moving window caching the metrics. Every minute is a slot in the window.
> Alarm core checks the window every minute. Count means the minimal count of value in the slot over threshold.

i understand ,thank you
