### ISSUE TITLE
8.2.0 version release time

### ISSUE THREAD

**Issue by janecms** [apache/skywalking#5551]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can you tell in advance the specific release schedule for the next 8.2.0 version?

**Comment by wu-sheng** [comment]
We don't have a specific release date yet.
