### ISSUE TITLE
request help: any suggestions to migrate to v8.0

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/skywalking#5552]
- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Since protocol v3 is  incompatible with previous one, is there any document about how to migrate to v8.0, like the one of [etcd migration](https://etcd.io/docs/v3.4.0/op-guide/v2-migration/#migrate-client-library)

**Comment by wu-sheng** [comment]
We don't do migration. ETCD is a kind of storage, even a database, so, there are points of working on that. As a monitoring system, data are time sensitive, putting too much time on that is not a good use of time.

Take a reference from the FAQ, upgrade is not a hard process.

**Comment by Yiyiyimu** [comment]
thx!
