### ISSUE TITLE
How should I contribute a toolkit for finding witness classes?

### ISSUE THREAD

**Issue by harvies** [apache/skywalking#5553]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
@harvies is the tool already hosted on GitHub? @wu-sheng maybe we can create a repo in the SkyAPM org to host this tool?

**Comment by wu-sheng** [comment]
I am OK to open a repo in the SkyAPM and invite @harvies in. 

@kezhenxu94 I am removing this from the milestone, as it is not related to the release or main repo, right now.

**Comment by wu-sheng** [comment]
Could you give the name of the project?

**Comment by harvies** [comment]
> @harvies is the tool already hosted on GitHub?
Not hosted on Github.

**Comment by wu-sheng** [comment]
@harvies It is fine, I need the project name to create.

**Comment by harvies** [comment]
> @harvies It is fine, I need the project name to create.

uranus

**Comment by wu-sheng** [comment]
Project created, https://github.com/SkyAPM/uranus. And have sent the invitation to your GitHub account.
