### ISSUE TITLE
When does skywalking support browser？I see this by your book in p232：）

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#5559]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
It will be included in the 8.2.0 release.

**Comment by lsy1990** [comment]
Thanks a lot!
