### ISSUE TITLE
SW_STORAGE_ES_ADVANCED does not work for es7

### ISSUE THREAD

**Issue by mis98zb** [apache/skywalking#5567]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
I use docker image apache/skywalking-oap-server:8.1.0-es7 downloaded for docker hub.

- What happened?
I use docker swarm and yml file to deploy skywalking.
I add the environment as given in doc: 

> SW_STORAGE_ES_ADVANCED: "{\"index.translog.durability\":\"request\",\"index.translog.sync_interval\":\"5s\"}"

And when I deploy skywalking, the oap container start and then stop in a short time.
There is error in the log:

> 2020-09-27 06:23:45,286 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -1081 [main] ERROR [] - Can not set java.lang.String field org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchConfig.advanced to java.util.LinkedHashMap

When I comment out the SW_STORAGE_ES_ADVANCED environment variable, everything goes well.

**Comment by JaredTan95** [comment]
Followed By https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#advanced-configurations-for-elasticsearch-index, you need to  change `{"index.translog.durability":"request","index.translog.sync_interval":"5s"}` to `{\"index.translog.durability\":\"request\",\"index.translog.sync_interval\":\"5s\"}`

**Comment by mis98zb** [comment]
> Followed By https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#advanced-configurations-for-elasticsearch-index, you need to change `{"index.translog.durability":"request","index.translog.sync_interval":"5s"}` to `{\"index.translog.durability\":\"request\",\"index.translog.sync_interval\":\"5s\"}`

Yes, I do followed the doc.
I pasted the code directly into GitHub editor, and the dash character is not shown.

**Comment by kezhenxu94** [comment]
@mis98zb try

```yaml
SW_STORAGE_ES_ADVANCED: '"{\"index.translog.durability\":\"request\",\"index.translog.sync_interval\":\"5s\"}"'
```

add single quotes around the value `'`

**Comment by mis98zb** [comment]
@kezhenxu94 
got it, thank you so much~~~
