### ISSUE TITLE
How can I add a new span

### ISSUE THREAD

**Issue by ywcywc** [apache/skywalking#5576]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to know the method to make a new span.
___
### Bug
- Which version of SkyWalking, OS and JRE?
My SkyWalking version is 6.4.0 .
My OS is windows 10.
My JRE is 1.8.0.
- Which company or project?
I am a beginner , I want to build a text project.
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
<img width="960" alt="mycode" src="https://user-images.githubusercontent.com/71858084/94407435-02e9ae80-01a6-11eb-8e1e-029ce5b9186d.png">

This is my code and result.
<img width="576" alt="skywalking" src="https://user-images.githubusercontent.com/71858084/94406737-0c264b80-01a5-11eb-96ad-0340aa772f9b.png">

### Requirement or improvement
- Please describe your requirements or improvement suggestions.
<img width="576" alt="myresult" src="https://user-images.githubusercontent.com/71858084/94407002-6c1cf200-01a5-11eb-92f0-bbcfbdb9c851.png">
I want to add a new span such as "test:    This is a test." in the red square. I need a tutorial for this operation. I am very appreciated to the help. Thank you very much

**Comment by wu-sheng** [comment]
You are opening a span detail page. I don't know what do you mean add there. That is the wrong place.

About span, a new plugin, application toolkit are both available. Read the documents, we have included those.
