### ISSUE TITLE
cannot display thread stack well when thread stack is too deep

### ISSUE THREAD

**Issue by ssochi** [apache/skywalking#5577]
version : 8.0.0
bug : 
I create a profile task,and choose one sample to analyse.
SkyWalking display it's Thread Stack,but due to the deep of the stack,
 the 'Thread Stack' column  of the display table is too narrow to display the whole stack.
I find out no way to extend the 'Thread Stack' column  of the display table,
but i don't want miss the deep stack, what can i do?
![image](https://user-images.githubusercontent.com/15121953/94411558-4c88c800-01ab-11eb-8be8-7a28ff55db8a.png)

Look forward to your reply.

**Comment by ssochi** [comment]
version : 8.0.0
bug : 
I create a profile task,and choose one sample to analyse.
SkyWalking display it's Thread Stack,but due to the deep of the stack,
 the 'Thread Stack' column  of the display table is too narrow to display the whole stack.
I find out no way to extend the 'Thread Stack' column  of the display table,
but i don't want miss the deep stack, what can i do?
![image](https://user-images.githubusercontent.com/15121953/94411558-4c88c800-01ab-11eb-8be8-7a28ff55db8a.png)

Look forward to your reply.

**Comment by wu-sheng** [comment]
8.1.0 has fixed this, and this is a duplicated issue. Please don't submit without searching existing issues.
