### ISSUE TITLE
one springmvc path include lots of endpoint

### ISSUE THREAD

**Issue by qlql489** [apache/skywalking#5578]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
our service has a springmvc path  /as/**  include lots of path,like  /as/a/get、/as/a/put、/as/b/get ...  ，in ui the endpoit list just show one endpoit (/as/**) how to resovle
___
### Bug
- Which version of SkyWalking, OS and JRE?
v8.1.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is the way we designed. Not an issue.

**Comment by qlql489** [comment]
i want to know  if i modify the code，has the way  to solve the problem?

**Comment by wu-sheng** [comment]
That is on yourselves.
