### ISSUE TITLE
How to submit logs use HTTP 1.1 ?

### ISSUE THREAD

**Issue by bnubobby** [apache/skywalking#5581]
How to submit logs use HTTP 1.1 ?
There is no description in the document :
https://github.com/apache/skywalking/blob/master/docs/en/protocols/HTTP-API-Protocol.md

**Comment by wu-sheng** [comment]
Because we don't. Who said we supported collecting logs?

**Comment by bnubobby** [comment]
@wu-sheng 
actually,  This is just a missing document
```json
{
  "spans":[{
       "logs":[{
             "time" : 1601350705265,
              "data" : [{
                           "key":"message",
                           "value":"this is a log record"
                          }]
               }]
   }]
}
```
Please supplement the document，and  don't mislead orthers.

**Comment by wu-sheng** [comment]
You mislead me by mentioning log without context. In the observability field, log is another thing. You were asking logs of span

Also, you could submit pull request to adjust doc. This doesn't have to do by any specific person, that is how open source community works.
