### ISSUE TITLE
如何删除旧的服务

### ISSUE THREAD

**Issue by mlzxdzl** [apache/skywalking#5582]
之前创建的时候忘了给agent的 name改名了，我现在改了之后在UI里有两个一个是Your_ApplicationName,一个是Test-Environment。请问要如何把Your_ApplicationName 这个相关的全部删除？求大神帮助。英文苦手，文档里实在找不到
![微信截图_20200929101050](https://user-images.githubusercontent.com/10397077/94504772-1d6e6700-023c-11eb-8e63-49f4e6f75781.png)

**Comment by wu-sheng** [comment]
English please.
