### ISSUE TITLE
How to solve the async callback condition?

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#5586]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- What do you want to know?
How to solve the async callback condition?

some conditions:

An RPC trigger an external SMS supplier and the service would be received a callback after a few seconds or minutes from the SMS supplier. 
there are maybe 2 traces in the condition.

1. rpc service trigger SMS supplier
2. SMS supplier trigger rpc service.

We can deliver the trace id to the SMS supplier, which is got from the Skywalking toolkit and we can extract the before trace id from the callback.

But how to build the relationship between the 1st trace and the 2nd trace?  And how to monitor the condition?

For this situation in Skywalking support,  I have no idea for now. 
Thx for your help, whether SkyWalking supports this condition.

**Comment by wu-sheng** [comment]
Just trace id is not enough. Like we talked, I still prefer to use collaberate context to do by yourself.
