### ISSUE TITLE
skywalking agent bug

### ISSUE THREAD

**Issue by MikelPan** [apache/skywalking#5587]
skywalking agent log level set to INFO
but it display out to debug

**Comment by kezhenxu94** [comment]
@MikelPan tell us how you set the level please

**Comment by MikelPan** [comment]
i is configure agent cofnig logging.level=${SW_LOGGING_LEVEL:INFO},but i java pom file is configure log-back is debug

**Comment by wu-sheng** [comment]
What do you mean pom file? We don't provide pom file.

**Comment by MikelPan** [comment]
skywalking agent is to java Program. i java Program log level is config to debug，but skywalking agent is java agent，log level configure INFO，but in java Program log is diaplay skywalking log，and skywalking log level is debug

**Comment by wu-sheng** [comment]
It is very hard to understand your words. The way you expressing is quite tricky.
But no matter what your points are,
**We don't output anything to your app logs, besides the gRPC, which has been documented in the FAQ.**
