### ISSUE TITLE
Is there any way can get segmentId ? 

### ISSUE THREAD

**Issue by PertQin** [apache/skywalking#5588]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is there any way can get segmentId ?  

one trace contains many segments.  
that mean , trace = segment1 + ... + segmentN.

as I know,  Official provided the traceId that how to get. so is there any way can get segmentId ?  

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Duplicated, it is not supported yet.
