### ISSUE TITLE
Metrics about latency of consuming queue

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5591]
Hi @apache/skywalking-committers and @EvanLjp

I created this issue to track the discussion originally started here, https://github.com/apache/skywalking/issues/5584#issuecomment-700793580. The question of #5584  actually is asking for metrics of MQ consuming latency.

Here it is my proposal

The only high-performance way is to propagate the sending time(header injecting timestamp) in the extension header, https://github.com/apache/skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Propagation-Headers-Protocol-v3.md#extension-header-item.

If you are going to implement this, we should consider making it optional, such as
- `sw8-x` = `0-mq_send_timestamp` or `-mq_send_timestamp`
- `sw8-x` = `0`

Then, if when the upstream receiving this header, it could be readable by the entry span, the plugin could calculate the latency of this message, add as a new tag as `mq.consum_latency`. Then the OAP could do statistics with a new source.

NOTE, this new field of extension header should be readonly, but wouldn't propagate it because once it is read from the header, it means this message has been consumed.

**Comment by EvanLjp** [comment]
This is enough for me.

**Comment by wu-sheng** [comment]
@EvanLjp I think we still miss part of this feature. Could you complete this?

**Comment by EvanLjp** [comment]
Ok, I would finish it in May.

**Comment by wu-sheng** [comment]
@EvanLjp Do we have expect date to finish this?

**Comment by EvanLjp** [comment]
@wu-sheng I'm worried about whether I can finish this, so I'm going to close this first.
