### ISSUE TITLE
Is there common ways to stop the header propagator?

### ISSUE THREAD

**Issue by snakorse** [apache/skywalking#5593]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- My service call DingDing open apis via httpclient, the problem is the DingDing server do not allow additional custom http request header, thus I need a way to control do not inject the skywalking propagate-header to httpclient, so I want to known is there common ways to tell the skyapm-agent framwork that do not propagete the header further while doing some special request?

**Comment by wu-sheng** [comment]
Do you mean Java agent?

**Comment by snakorse** [comment]
Yes, does java agent have such function?

**Comment by snakorse** [comment]
But ideally, I want to known if we should provide a mechanism at the protocol layer to let the user disable the header propagation when call some special thirty party service.

**Comment by wu-sheng** [comment]
I think today, we don't have such things. As it is hard to tell which is an internal call, the other is for 3rd party, like Dingding. If this really is a block to you, I recommend you add a proxy before calling the dingding server. All HTTP1/2 proxy has the capability to filter or change headers.

Does this make sense to you?
