### ISSUE TITLE
Has skywalking-client-js been published to npm?

### ISSUE THREAD

**Issue by liangjun-jiang** [apache/skywalking#5621]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
has skywalking-client-js been published to npm? 
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
I run `https://github.com/apache/skywalking-client-js` as instructed [here](https://github.com/apache/skywalking-client-js)
Received error 
```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for skywalking-client-js

```

I also searched npm.org, couldn't find `skywalking-client-js`

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
It is still in the dev stage.
