### ISSUE TITLE
Add health check for Storage/Cluster management module

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5633]
In the previous releases, @hanahmily added the health check module and its implementation for the storage modules(H2, MySQL, and ES), we need to add a similar thing for InfluxDB.

Also, for cluster management, we need to add this too. If 
1. the registration fails 
1. can't get the instance list 
1. can't get itself, then
1. get multiple itself(such as multiple 127.0.0.1/0.0.0.0) in the instance list
The cluster management should be listed as an error 

The health check could be verified through CLI command, https://github.com/apache/skywalking-cli#checkhealth

@xbkaishui Are you going to do this?

**Comment by xbkaishui** [comment]
Yes, please assign to me.  Thanks

**Comment by hanahmily** [comment]
And you should check the runtime status of the Influxdb client, for instance, the new health checker would mark the storage module unhealthy once some writing, retrieving, and other critical operations failed.

**Comment by xbkaishui** [comment]
I will split two pr for this task: 

1. for influxdb
1. for cluster managment
