### ISSUE TITLE
skywalking-ui: jvm metrics only have one number per day?

### ISSUE THREAD

**Issue by worldwalk** [apache/skywalking#5636]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

version: V6.3

1. on UI page:
such as JVM GC counts, Heap, etc,  only has a number per day，  I guess the display is per day, where I can change to per hour for example?

2. is there any doc to show such configuration/introdction for JVM metrics?  (also the database metrics...)

3. what's the CLR means on page?  (CLR is beside JVM on UI), it's for .NET ?

thanks!
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> on UI page:
such as JVM GC counts, Heap, etc, only has a number per day， I guess the display is per day, where I can change to per hour for example?

Choose the right time duration.

> is there any doc to show such configuration/introdction for JVM metrics? (also the database metrics...)

It is auto.

> what's the CLR means on page? (CLR is beside JVM on UI), it's for .NET ?

CLR is .NET concept.

**Comment by worldwalk** [comment]
thanks a lot! it works, good day!
