### ISSUE TITLE
Can I use my own name of endpoint in alarm message？

### ISSUE THREAD

**Issue by fuhuo** [apache/skywalking#5638]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

I want to display my own name of  endpoint in alarm message, So, how can I configure endpoint name？And can I use endpoint name in alarm message? I try to config it in endpoint-name-grouping.yml, but it likely only work in Trace.Any document about it？Thank you

**Comment by wu-sheng** [comment]
I don't know what is your endpoint name. Alarm endpoint name is as same as the metrics entity name.
Endpoint grouping is not for trace, don't know what do you mean either.

**Comment by wu-sheng** [comment]
If you want, the grouping is the only choice. From my understanding, it should work, if the cost is acceptable.
