### ISSUE TITLE
pxx指标是否存在并发问题

### ISSUE THREAD

**Issue by ieven** [apache/skywalking#5642]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
pxx这类指标在计算时若之前已经计算过会先从存储（如：mysql）中获取历史，然后计算完以后进行覆盖更新。此处是否会出现并发问题，即A和B同时获取到了相同元数据，加上自身的元数据计算以后是不同的结果。
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please use English on the Github. We provided mandarin channel already.
