### ISSUE TITLE
Does the percentile metrics have concurrency problems

### ISSUE THREAD

**Issue by ieven** [apache/skywalking#5643]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
If percentile metrics (p50) have been calculated before, the history will be obtained from the storage, and then the update will be done after the calculation.I think there maybe a concurrency problem.
For example A and B get the same metadata at the same time. With their own metadata calculation, the results are different.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
There is no concurrency case unless the OAP cluster is not stable. We have guaranteed that in the OAP core. No metrics with the same id should be updated from two threads at the same time.
