### ISSUE TITLE
task list can not be removed

### ISSUE THREAD

**Issue by Diyuzhou** [apache/skywalking#5645]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [* ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to delete tasks in task list
___
### Bug
- Which version of SkyWalking, OS and JRE?
8.1.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What is the task list? Do you mean profiling task?
If so, it will be removed according to record TTL

**Comment by Diyuzhou** [comment]
![Screen Shot 2020-10-10 at 7 51 31 PM](https://user-images.githubusercontent.com/21288434/95654349-04b25b00-0b32-11eb-8cf9-6637faf2d413.png)
here is the picture

**Comment by Diyuzhou** [comment]
can not remove tasks in task list

**Comment by Diyuzhou** [comment]
> What is the task list? Do you mean profiling task?
> If so, it will be removed according to record TTL

I have no idea about how to config record TTL, can I configure it in some config file or some env variable?
