### ISSUE TITLE
Performance Profiling task can not be removed from task list

### ISSUE THREAD

**Issue by Diyuzhou** [apache/skywalking#5646]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ *] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Performance Profiling task can not be removed from task list
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 8.1.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
add new task in Performance Profiling task list ,then find no way to delete it like below picture
![Screen Shot 2020-10-10 at 7 51 31 PM](https://user-images.githubusercontent.com/21288434/95654455-a5a11600-0b32-11eb-9e3d-1d2f8b5562f5.png)

___

**Comment by Diyuzhou** [comment]
how can I remove useless tasks in task list.

**Comment by wu-sheng** [comment]
Why keep submitting things? I have replied in the previous one.
