### ISSUE TITLE
Nginx Subrequest return `[Broken] CROSS_PROCESS`

### ISSUE THREAD

**Issue by Ediliu13** [apache/skywalking#5649]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hi, I'm trying to integrate Nginx with Skywalking APM, but I figure out an issue for the request that using [subrequest](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/), when I check the trace for the request with subrequest it show something like: 
```
Endpoint: VNode - randomUUID
Span Type: [Broken] CROSS_PROCESS
Component: VirtualNode: #0
```

Question: What does that mean? and any Idea how to solve that?

For the request without subrequest it's work as expected.
To make it easier to check here is my nginx configuration: https://github.com/Ediliu13/nginx-sw8

##### Without Subrequest
<img width="1440" alt="000" src="https://user-images.githubusercontent.com/6216477/95684527-88487680-0c1c-11eb-9c08-11123bcf57b3.png">
<img width="1440" alt="001" src="https://user-images.githubusercontent.com/6216477/95684497-59320500-0c1c-11eb-93e1-542dd797fab0.png">

##### With Subrequest
<img width="1440" alt="002" src="https://user-images.githubusercontent.com/6216477/95684499-5b945f00-0c1c-11eb-9fed-ee329f48c0ca.png">
<img width="1440" alt="003" src="https://user-images.githubusercontent.com/6216477/95684521-7f57a500-0c1c-11eb-9408-da7d877c2353.png">

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking-8.1.0
skywalking-nginx-lua-0.2.0

Thanks in advance.

**Comment by wu-sheng** [comment]
@moonming What is subrequest? Could you take a look?

**Comment by moonming** [comment]
@membphis is working on the Apache APISIX's plugin around skywalking 8.0 and nginx-lua 0.2, do you have time to check this issue? thx

**Comment by membphis** [comment]
I will take a look at this bug when I have time ^_^

**Comment by membphis** [comment]
@wu-sheng @moonming  you can assign this bug to me

**Comment by spacewander** [comment]
@Ediliu13 
I think the broken message is because subrequest doesn't run the log phase by default.
You can enable it via log_subrequest directive: http://nginx.org/en/docs/http/ngx_http_core_module.html#log_subrequest

**Comment by Ediliu13** [comment]
> @Ediliu13
> I think the broken message is because subrequest doesn't run the log phase by default.
> You can enable it via log_subrequest directive: http://nginx.org/en/docs/http/ngx_http_core_module.html#log_subrequest

Thank you @spacewander I just try to put that `log_subrequest` directive as your suggestion, in http, server, and location block but it still remains the same, so I don't think that is the proper solution for this issue.

<img width="1081" alt="Screen Shot 2020-12-14 at 23 48 42" src="https://user-images.githubusercontent.com/6216477/102110340-9bb7ce00-3e67-11eb-9d1c-5b510968b449.png">

**Comment by spacewander** [comment]
`auth_request` doesn't run the body filter phase. Maybe you need to reimplement it with Lua code or add extra workaround for it.

**Comment by WilliamShoww** [comment]
> @wu-sheng @moonming you can assign this bug to me

I'm havel same question with you too. Finally, how do you handler this question?
