### ISSUE TITLE
dynamic configuration with apollo dose not work

### ISSUE THREAD

**Issue by zender-projects** [apache/skywalking#5655]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I am greenhand for skywalking, when i use it, apollo dynamic configuration dose not work, the detail is :
1. skywalking deployed in my personal computer(mac) and apollo is my company's dev environment
2.i change application.yml, configuration is 
`configuration:
  selector: apollo
 apollo:
    apolloMeta: http://ip:port
    apolloCluster: default
    apolloEnv: DEV
    appId: skywalking
    period: 20
`
3.configuration in apollo is type of properties(key-value)
4.now , the apollo's configuration is loaded into skywalking's config-cache path and the file name is skywalking+default+application.properties

5.but, the configuration is not effective, oap server print the following log:
`
2020-10-13 15:20:12,935 - org.apache.skywalking.oap.server.core.alarm.provider.AlarmRulesWatcher - 93 [pool-5-thread-1] INFO  [] - Update alarm rules to Rules(rules=[], webhooks=[], grpchookSetting=null)
`

by test with skywalking agent, the configuration is really not effective, now, I don't know why and what can I do for this?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean test with `skywalking agent`? This is for backend, no agent. Do you misunderstand something?

**Comment by zender-projects** [comment]
> What do you mean test with `skywalking agent`? This is for backend, no agent. Do you misunderstand something?

just request a http interface, and generate some monitor log to backend with agent, so that i can see it on alarm part of web ui.
because i only config alarm , so i want to know the configuration work or not

**Comment by zender-projects** [comment]
> What do you mean test with `skywalking agent`? This is for backend, no agent. Do you misunderstand something?

the version is apache-skywalking-apm-es7-8.1.0.tar.gz

**Comment by wu-sheng** [comment]
I am still not following your things. The dynamic configuration just syncs the alarm rule data with 3rd party, depending on different implementations. From the logs, there is nothing to be read, that is all.
I am not sure whether apollo is working personally, but the test seems passed. Do you real set anything on the Apollo with correct keys?

**Comment by kezhenxu94** [comment]
@zender-projects please check the OAP logs to see whether there is anything wrong (for example, parsing the config), and try this http://106.54.227.205/config.html?#/appid=skywalking from the demo env that Apollo provides, I tested with this when developing the plugin

**Comment by zender-projects** [comment]
> I am still not following your things. The dynamic configuration just syncs the alarm rule data with 3rd party, depending on different implementations. From the logs, there is nothing to be read, that is all.
> I am not sure whether apollo is working personally, but the test seems passed. Do you real set anything on the Apollo with correct keys?

ok, thank you very much for replying soon.  i describe it more detail
first, the configuration's key on apollo contains the following
`
alarm.default.alarm-settings.webhooks
alarm.default.alarm-settings.rules.service_resp_time_rule.metrics-name
alarm.default.alarm-settings.rules.service_resp_time_rule.op
alarm.default.alarm-settings.rules.service_resp_time_rule.threshold
alarm.default.alarm-settings.rules.service_resp_time_rule.period
alarm.default.alarm-settings.rules.service_resp_time_rule.count
alarm.default.alarm-settings.rules.service_resp_time_rule.silence-period
alarm.default.alarm-settings.rules.service_resp_time_rule.message
`
the above key's value is correct , i verify it with configuration.selector=none (in alarm-setting.yml)

when i modify values and deploy on apollo , the data was loaded by skywalking backend into a file named skywalking+default+application.properties in the directory 'config/config-cache',  the properties's content is same with apollo, but it dose not effective for backend service

i am not sure if i have something wrong or others. 

thank you.

**Comment by zender-projects** [comment]
> @zender-projects please check the OAP logs to see whether there is anything wrong (for example, parsing the config), and try this http://106.54.227.205/config.html?#/appid=skywalking (apollo:admin) from the demo env that Apollo provides, I tested with this when developing the plugin
> 
> UPDATED: Seems your configuration format is not correct

ok, the key 'alarm.default.alarm-settings' 's value is the whole content of alarm-settings.yml , really? 

i am not do like this, instead of one special key - value

**Comment by wu-sheng** [comment]
> i am not do like this, instead of one special key - value

This is not about like or not like. This is about how this thing is designed for.

**Comment by wu-sheng** [comment]
And we described this very clear on the dynamic configuration document page.

**Comment by zender-projects** [comment]
> And we described this very clear on the dynamic configuration document page.

ok, i understand , thank you!
