### ISSUE TITLE
SkyWalking Nacos implementation of Coordinator/Dynamic Configuration authentication

### ISSUE THREAD

**Issue by ITGcx** [apache/skywalking#5665]
Support authentication in Nacos implementation of coordinator and dynamic configuration,

https://nacos.io/en-us/blog/nacos%201.2.0%20guide.html

**Comment by kezhenxu94** [comment]
@ITGcx please use English when communicating on GitHub or mailing list.

Now we don't support the authentication, if you want, consider contributing the feature, it's rather easy actually, if you have any trouble, ping us anytime

**Comment by xbkaishui** [comment]
@kezhenxu94  please assign to me

**Comment by unc1** [comment]
Is there any sort of user roles used in Skywalking? It would be nice to have normal users and then the admins. Or is there going to be authentication support in future releases that would allow the use of LDAP, SSO or something else? Thanks.

T

**Comment by wu-sheng** [comment]
@unc1 Your question is unrelated to this issue.
