### ISSUE TITLE
SpringCloud gateway integration SkyWalking.Link monitoring collection request address problem.

### ISSUE THREAD

**Issue by uzdz** [apache/skywalking#5668]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ✅  ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

I hope that after skywalking collects the gateway endpoint, the UI will display the specific request address. However, it seems that the current display will always be 'spring cloudgateway / routingfilter'. Is this my configuration problem? Or design?

![image](https://user-images.githubusercontent.com/28328355/95987234-b797f700-0e59-11eb-86e7-e3f67311e916.png)

**Comment by uzdz** [comment]
At present, the `apm-spring-cloud-gateway-2.1.x-plugin-8.1.0-SNAPSHOT.jar` under the optional plugins package is moved to the plugins package.

**Comment by wu-sheng** [comment]
8.1.0-SNAPSHOT plugin has been changed. How it works base on its contributor :)
