### ISSUE TITLE
What should I pay attention to if the backend cluster node are distributed in different area?

### ISSUE THREAD

**Issue by wutingjia** [apache/skywalking#5670]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What should I pay attention to if the backend cluster node are distributed in different area or city?  
Is there any potential risk or unstabitily?
___
### Bug
- Which version of SkyWalking, OS and JRE?
8.1.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We don't recommend that I think, unless. you have a great network across the cities. For me, multiple zones support usually is a part of a commercial product, but AFAIK, there is no one or company did that.
