### ISSUE TITLE
Everything is all right just selfObservability-oap-server can not collect any data

### ISSUE THREAD

**Issue by Diyuzhou** [apache/skywalking#5671]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to make selfObservability-oap-server collect data

- Which version of SkyWalking, OS and JRE?
skywalking 8.1.0

![Screen Shot 2020-10-15 at 3 31 26 PM](https://user-images.githubusercontent.com/21288434/96091381-1a41cf00-0efc-11eb-80df-cf6c2958826b.png)

**Comment by wu-sheng** [comment]
You need to open it manually. Please read the documents.
