### ISSUE TITLE
Seeing that your current master version is supports thrift, but tag 8.0.1 don't  supports, I would like to ask whether the latest version supports thrift?

### ISSUE THREAD

**Issue by 2719969254** [apache/skywalking#5682]
Seeing that your current master version is supports thrift, but tag 8.0.1 don't  supports, I would like to ask whether the latest version supports thrift?

**Comment by kezhenxu94** [comment]
The thrift plugin is not yet released, if you want, please build from the source codes, and you can simply move the thrift plugin jar to 8.0.1 plugins folder, it should also work
