### ISSUE TITLE
How to support traditional projects（Spring MVC ,not springboot springcloud）?

### ISSUE THREAD

**Issue by saasjwl** [apache/skywalking#5689]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ 1] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to support traditional projects
___
### Bug
- Which version of SkyWalking, OS and JRE?
 8.1.0，linux， jdk1.8
- Which company or project?
my project
- What happened?
I have two projectes（ UserCenter and UserSystem） ，two tomcat  ， UserCenter calls UserSystem（http request）
tomcat add agent in catalina.sh(eg:CATALINA_OPTS="$CATALINA_OPTS -javaagent:/data/xxx/agent/skywalking-agent.jar=agent.active_v2_header=true"; export CATALINA_OPTS)
 

but  result:    
User-->UserCenter
User-->UserSystem

expect：User-->UserCenter-->UserSystem

![result](https://user-images.githubusercontent.com/34735127/96440403-8002c380-123a-11eb-8adf-a9164a8e8172.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
That depends on your RPC framework. We have nothing related to Spring boot.

**Comment by saasjwl** [comment]
traditional projects ，All communications are used http ，Configuration required nginx?

**Comment by saasjwl** [comment]
I want traceid on the whole chain, but the result is a single system link,  Please tell me what I need to do

**Comment by wu-sheng** [comment]
We have the supported list for rpc frameworks. I don't know what you did in your project. You should learn the project first.

**Comment by saasjwl** [comment]
I can understand that a full link must be supported by an RPC framework？

**Comment by wu-sheng** [comment]
SkyWalking must have suitable plugin for that framework with supported versions.

**Comment by saasjwl** [comment]
ok, thank you

**Comment by geniusjoe** [comment]
I'm new to skywalking. But I think Java frameworks mentioned in below link are supported.
https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/supported-list/
