### ISSUE TITLE
how to config database instance name mapping to logic name instead of ip:port? 

### ISSUE THREAD

**Issue by zender-projects** [apache/skywalking#5693]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
usually, one service maybe access  two or more database instance, now i have learned that db instance name is ip:port in the database monitor of web ui, now i want to know if the name can mapping to a logic name
eg : 127.0.0.1 -> local, the readability is better, but i can't find config properties in agent.config
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
![20201020102015](https://user-images.githubusercontent.com/16514360/96532163-e2e96e80-12bd-11eb-94ee-5b2e6d5d09f0.jpg)

**Comment by wu-sheng** [comment]
We don't have for now.
