### ISSUE TITLE
About apm-sdk-plugin

### ISSUE THREAD

**Issue by MxAc** [apache/skywalking#5696]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
   Our project  was Golang stack and now  we want to use skywalking as our open tracing platform，while there seems to be not so much support for Golang. I wonder if there‘s any schedule  for you excellent committers to overwrite the apm-sdk-plugin in Golang? If not maybe we can contribute some code to skywalking.

**Comment by wu-sheng** [comment]
You are asking in the wrong place, check https://github.com/SkyAPM/go2sky

More importantly, read the documents. We gave all the links to all language agents.
