### ISSUE TITLE
How to trace a message in the bigdata architecture by skywalking

### ISSUE THREAD

**Issue by pierre94** [apache/skywalking#5698]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?

In the bigdata architecture，a message will flow through many components like producer-server、mq-server(kafka)、etl-process(strom/flink)、db(redis/mysql).So how to trace this message?

**Comment by kezhenxu94** [comment]
Is there anything special in the BigData architecture? We support many MQ frameworks, as long as the framework (e.g. Kafka, RabbitMQ, etc.) is in our supported list, their messages should be traced correctly usually. If you meet any problems in real scenario, please provide more context, thanks
