### ISSUE TITLE
Feature Request: agent supports payara41

### ISSUE THREAD

**Issue by jamesgdb** [apache/skywalking#5701]
We use [payara41](https://github.com/payara/Payara), but skywalking doesn't support it. Can you also get a plugin to support it

**Comment by kezhenxu94** [comment]
Almost all the plugins we have now are contributed by the community, so if you want, please try to build one and contribute back to the community, that's how open source projects works.

Basically, the one who needs a feature will contribute it, we (maintainers) will help on reviewing
