### ISSUE TITLE
Skywalking UI blank

### ISSUE THREAD

**Issue by SevenBlue2018** [apache/skywalking#5702]
Now, Skywalking UI always stays blank. I checked the data of ES and found that it has not been updated. I have adjusted the bulk write size and period of the PersistenceTimer.java.What should I do to solve this problem?
![image](https://user-images.githubusercontent.com/11767168/96586377-7ef19500-1313-11eb-861c-bdbafc7cec46.png)

**Comment by kezhenxu94** [comment]
Please check the OAP logs to see whether there is any error log

**Comment by SevenBlue2018** [comment]
Now, I do not find any erro log.

**Comment by xbkaishui** [comment]
Maybe it is the timezone issue(current screenshot show utc_8), you can change it in the right bottom corner.

**Comment by SevenBlue2018** [comment]
> Maybe it is the timezone issue(current screenshot show utc_8), you can change it in the right bottom corner.

Thanks. That's what I'm using. Not all data on my page is empty.

**Comment by wu-sheng** [comment]
Do you have the traffic for this instance? From the only screenshot you gave, there is no unusual thing.

**Comment by SevenBlue2018** [comment]
Yes, I have the traffic for this instance.

**Comment by SevenBlue2018** [comment]
Yes, I have the traffic for this instance.

**Comment by SevenBlue2018** [comment]
Yes, I have the traffic for this instance, but the last_ping is not updated.
![image](https://user-images.githubusercontent.com/11767168/96599036-11993080-1322-11eb-974e-0dbb45e578ea.png)

**Comment by SevenBlue2018** [comment]
Now, I found the trace data is normal, but just the metric data is so slow.

**Comment by SevenBlue2018** [comment]
I modified the code for the PersistenceTimer.java，as follows

**Comment by SevenBlue2018** [comment]
I modified the code for the PersistenceTimer.java，as follows
![image](https://user-images.githubusercontent.com/11767168/96600744-d8fa5680-1323-11eb-93a1-1ef45626215d.png)
Because the bulk too large will cause the exception : 413 Request Entity Too Large. Then to prevent update delays, I adjusted the PersistenceTimer frequency to once per second.

**Comment by wu-sheng** [comment]
I think this is a bug that has been fixed in the master branch. In the 8.2.0, the max bulk size is not working. Check the change log. We are going to release recently.
