### ISSUE TITLE
The links  of overview of SkyWalking module [call flow] and [hierarchy]  cannot be openned

### ISSUE THREAD

**Issue by humyna** [apache/skywalking#5710]
The links referenced in the document cannot be opened.

pls click the [document url](https://github.com/apache/skywalking/tree/master/docs
) and search keyword: [call flow](https://sourcespy.com/github/skywalking/xx-omcalls-.html) or [hierarchy](https://sourcespy.com/github/skywalking/xx-omhierarchy-.html
),  then click it

it will show the below error info.

> HTTP Status 500 – Internal Server Error
> Type Exception Report
> 
> Message Servlet execution threw an exception
> 
> Description The server encountered an unexpected condition that prevented it from fulfilling the request.
> 
> Exception
> 
> javax.servlet.ServletException: Servlet execution threw an exception
> 	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	com.gotapi.ca.plain.server.MyFilter.doFilter(MyFilter.java:79)
> Root Cause
> 
> java.lang.Error: Project 'github:skywalking' has not been compiled yet
> 	com.gotapi.ca.plain.server.ProjectCache.getProject(ProjectCache.java:40)
> 	com.gotapi.ca.plain.server.GithubServlet.doGet(GithubServlet.java:189)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
> 	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	com.gotapi.ca.plain.server.MyFilter.doFilter(MyFilter.java:79)
> Note The full stack trace of the root cause is available in the server logs.

**Comment by kezhenxu94** [comment]
Thanks for reporting this, will take a look

**Comment by kezhenxu94** [comment]
@alexkarezin can you please take a look since you added these?

**Comment by alexkarezin** [comment]
@kezhenxu94 looking at it, will reply in a bit
