### ISSUE TITLE
How to add login module for skywalking,why remove login function in 6.2 version.

### ISSUE THREAD

**Issue by primefour** [apache/skywalking#5712]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ #] Feature or performance improvement

___
### Question
- What do you want to know?
 how to add login module for skywalking ?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by R1hug0** [comment]
Add Nginx proxy in front of skywalking-UI and open the basic authentication  of Nginx.

**Comment by kezhenxu94** [comment]
@R1hug0 gave the right answer, please use Nginx or APISIX to control access, SkyWalking doesn't provide login feature now
