### ISSUE TITLE
Custom query logic extension

### ISSUE THREAD

**Issue by zhyhzhylove** [apache/skywalking#5715]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

A lot of data query logic is encapsulated in module service-core, it is very inconvenient to expand.Can the query logic be extracted and designed as a plug-in mode？

for example：
     I want to query some data for our custom function，i need to change module server-core，because query service is inside.

**Comment by wu-sheng** [comment]
Our query is already abstract base designed. If you want to query in the private implementation, the OAP module based design already provides that. You could have a new module to do amything you want. But from my experience, it is not necessary.

**Comment by zhyhzhylove** [comment]
skywalking query: query-graphql-plugin -> service-core -> storage-elasticsearch7-plugin

If i want to custom query, i need to build three module: my-graphql-plugin -> my-service-core -> my-elasticsearch7-plugin？

**Comment by zhyhzhylove** [comment]
ok，thanks
