### ISSUE TITLE
Trace pageing reaturn "Exception while fetching Data (/traces) : Elasticsearch Exception [Type = search_phase_execution_Exception, reason=all shards Failed]"

### ISSUE THREAD

**Issue by tvrc1990** [apache/skywalking#5716]
### Question

Trace - list 

The list contains 15 records per page,a total of 1000 pages. But the maximum query index is 666 pages, page index over 666 return exception " {"data":{},"errors":[{"message":"Exception while fetching data (/traces) : Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]"}]} "

Error:
![image](https://user-images.githubusercontent.com/7088242/96949781-4b815700-151b-11eb-906c-fd08cac3fe98.png)

OK:
![OT{%2 3X7N65MOIFR%U@0S2](https://user-images.githubusercontent.com/7088242/96949912-9d29e180-151b-11eb-9091-adbde8a976b1.png)

### Environment
apache-skywalking-apm-8.1.0 (stand-alone)
elasticsearch 6.8.0 (stand-alone)
windows server 2012 R2 32G

How to fix this error ?  tks !!!

**Comment by wu-sheng** [comment]
Learn Elasticsearch, that is not SkyWalking feature.
