### ISSUE TITLE
Too long Http GET url or parameter will cause span lost

### ISSUE THREAD

**Issue by HaojunRen** [apache/skywalking#5721]
Too long Http GET url or parameter will cause span lost in 8.1

**Comment by wu-sheng** [comment]
What do you mean span lost? How?

**Comment by HaojunRen** [comment]
Just lik Http GET htttp://ip:port/doxx/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, let the URL long enough. SkyWalking span limits the length to store. I use memory Mode to test the feature, but it works fine in 
Http POST whatever Body length long or short

**Comment by wu-sheng** [comment]
We limit the length for statistic, not for span itself. I am not sure what fo you mean memory mode, we don't have that thing.

**Comment by HaojunRen** [comment]
很多业务系统(例如银行)里跟第三方系统做接口，url一般都很长，很长的url会导致埋点无法入库，在Skywalking界面上无法显示。你可以亲自测试一下，而Jaeger处理长url完全没问题

**Comment by HaojunRen** [comment]
有些长url是因为parameter很多引起的，例如，doxx?a=123&b=23456&c=111111&d=8888888888，为了能输出埋点，需要削减掉参数？

**Comment by HaojunRen** [comment]
可能还有个问题需要补充一下，这个issue似乎在Spring Boot 2.3.x才会出现

**Comment by wu-sheng** [comment]
Please update all discussion in English.

**Comment by HaojunRen** [comment]
It is not a good manner to close the issue before that issue is resolved

**Comment by wu-sheng** [comment]
We only keep the issue open if it is real an issue. Discussion could continue, but it would not be listed as open. Every community has its own style, that is all.

**Comment by HaojunRen** [comment]
Dis you do some tests to confirm that is not a real issue?

**Comment by wu-sheng** [comment]
We never use the parameter as span name, so, there is nothing to test.

**Comment by HaojunRen** [comment]
![图片](https://user-images.githubusercontent.com/42354711/97099901-10248b00-16c9-11eb-9ac1-d07de2547b49.png)
![图片](https://user-images.githubusercontent.com/42354711/97099924-495cfb00-16c9-11eb-9b13-236e71422345.png)

There different is the url length
![图片](https://user-images.githubusercontent.com/42354711/97099945-81643e00-16c9-11eb-83eb-bfda31d6c151.png)

**Comment by wu-sheng** [comment]
No, those 3 are services. There is nothing related to span, uri, or the length.

**Comment by HaojunRen** [comment]
If I reduce the url, 3 service node can display well
![图片](https://user-images.githubusercontent.com/42354711/97100007-3eef3100-16ca-11eb-9957-7c7a5b90cabc.png)

![图片](https://user-images.githubusercontent.com/42354711/97100014-529a9780-16ca-11eb-9e02-aad106a36f51.png)

**Comment by wu-sheng** [comment]
Please don't make me repeat myself. There is no such mechanism as you are just guessing.

**Comment by HaojunRen** [comment]
这是测试结果，请尊重事实，如何？你可以不需要再恢复我，我不寄希望你能解决这个问题，谢谢

**Comment by HaojunRen** [comment]
Based on Spring Cloud Hoxton.SR8 & Spring Boot 2.3.4.RELEASE
