### ISSUE TITLE
Agent plugin for Kafka 2.1.0+

### ISSUE THREAD

**Issue by hsoftxl** [apache/skywalking#5730]
kafka client 2.3.1

![image](https://user-images.githubusercontent.com/6965803/97155073-c2368280-17af-11eb-8f35-0c7e55d23c65.png)

**Comment by kezhenxu94** [comment]
https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md

we don't support Kafka 2.x.x for now

**Comment by kezhenxu94** [comment]
Confirmed, 2.3.1 is also supported, need to update the plugin list

**Comment by wu-sheng** [comment]
@hsoftxl Could you submit a pull request to update the doc?
