### ISSUE TITLE
Will there be a page to configure alarm rules and hot deploy them?

### ISSUE THREAD

**Issue by nimeijian** [apache/skywalking#5731]
Alarm webhooks sometimes very useful, we can get the running status of our systems in time, will there be a page to configure alarm rules and hot deploy them or take effect in a minute?Thank you!

**Comment by wu-sheng** [comment]
We have dynamic configurations for them already. But whether will be a page is a question we can't answer. If there are contributors to do this, then yes. 
This is how the community works. We don't decide, we collaborate with people.

**Comment by kezhenxu94** [comment]
> Alarm webhooks sometimes very useful, we can get the running status of our systems in time, will there be a page to configure alarm rules and hot deploy them or take effect in a minute?Thank you!

If you're using dynamic configuration, most of the implementations(Apollo, Nacos, etc.) already provide a UI to edit the configurations, we don't bother to reimplement this kind of feature
