### ISSUE TITLE
 SkyWalking Python Agent - One minute after adding a Python application with any web-based framework, skywalking stops monitoring endpoints

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking#5732]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
python version 3.8
skywalking 8.1
Flask 1.1.2

When adding a skywalking agent to the application, endpoints are monitored only for about a minute, after which an exception is reflected in the logs:
![image](https://user-images.githubusercontent.com/48470313/97166911-48d66a00-1786-11eb-9952-0ced1b1c2171.png)
From that moment skywalking stops monitoring the applications

**Comment by kezhenxu94** [comment]
The agent cannot reconnect to the OAP after disconnection is a known issue, and should be fixed by https://github.com/apache/skywalking-python/pull/73
