### ISSUE TITLE
The httpclient plugin cannot collect http parameters

### ISSUE THREAD

**Issue by zhaodp** [apache/skywalking#5736]
The httpclient plugin can not collect http parameters, but spring mvc plugin can. 
My config:
plugin.springmvc.collect_http_params=true
plugin.tomcat.collect_http_params=true

and my skywalking version is 8.1.0

**Comment by kezhenxu94** [comment]
`httpclient` plugin doesn't collect the parameters now, if you want, please enhance that plugin and add a config item like `plugin.springmvc.collect_http_params` and `plugin.tomcat.collect_http_params` to make it work

**Comment by xbkaishui** [comment]
please assign to me

**Comment by wu-sheng** [comment]
Question, do we really need to support parameter collection from client side? As we are providing e2e tracing, server side is not enough?

**Comment by kezhenxu94** [comment]
> Question, do we really need to support parameter collection from client side? As we are providing e2e tracing, server side is not enough?

Maybe when accessing external services?

**Comment by xbkaishui** [comment]
if not server is not supported by skywalking, such as s3?

**Comment by wu-sheng** [comment]
OK, maybe.

**Comment by zhaodp** [comment]
> `httpclient` plugin doesn't collect the parameters now, if you want, please enhance that plugin and add a config item like `plugin.springmvc.collect_http_params` and `plugin.tomcat.collect_http_params` to make it work
  I enhanced the httpClient-4.x-plugin, it worked  :
   `    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
        MethodInterceptResult result) throws Throwable {
        if (allArguments[0] == null || allArguments[1] == null) {
            // illegal args, can't trace. ignore.
            return;
        }
        final HttpHost httpHost = (HttpHost) allArguments[0];
        HttpRequest httpRequest = (HttpRequest) allArguments[1];
        final ContextCarrier contextCarrier = new ContextCarrier();

        String remotePeer = httpHost.getHostName() + ":" + port(httpHost);

        String uri = httpRequest.getRequestLine().getUri();
        String requestURI = getRequestURI(uri);
        String operationName = requestURI;
        AbstractSpan span = ContextManager.createExitSpan(operationName, contextCarrier, remotePeer);

        span.setComponent(ComponentsDefine.HTTPCLIENT);
        Tags.URL.set(span, buildSpanValue(httpHost, uri));
        Tags.HTTP.METHOD.set(span, httpRequest.getRequestLine().getMethod());
        SpanLayer.asHttp(span);

        **if (httpRequest  instanceof HttpEntityEnclosingRequest) {
            HttpEntityEnclosingRequest httpEntityEnclosingRequest = (HttpEntityEnclosingRequest) httpRequest;
            HttpEntity entity = httpEntityEnclosingRequest.getEntity();
            if (entity instanceof StringEntity) {
                String tagValue = EntityUtils.toString(entity);
                tagValue = StringUtil.cut(tagValue, 1024);
                Tags.HTTP.PARAMS.set(span, tagValue);
            }
        }**

        CarrierItem next = contextCarrier.items();
        while (next.hasNext()) {
            next = next.next();
            httpRequest.setHeader(next.getHeadKey(), next.getHeadValue());
        }
    }`

**Comment by zhaodp** [comment]
> `httpclient` plugin doesn't collect the parameters now, if you want, please enhance that plugin and add a config item like `plugin.springmvc.collect_http_params` and `plugin.tomcat.collect_http_params` to make it work
  I enhanced the httpClient-4.x-plugin, it worked  ：


 `    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
        MethodInterceptResult result) throws Throwable {
        ......
        if (httpRequest  instanceof HttpEntityEnclosingRequest) {
            HttpEntityEnclosingRequest httpEntityEnclosingRequest = (HttpEntityEnclosingRequest) httpRequest;
            HttpEntity entity = httpEntityEnclosingRequest.getEntity();
            if (entity instanceof StringEntity) {
                String tagValue = EntityUtils.toString(entity);
                tagValue = StringUtil.cut(tagValue, 1024);
                Tags.HTTP.PARAMS.set(span, tagValue);
            }
        }

        CarrierItem next = contextCarrier.items();
        while (next.hasNext()) {
            next = next.next();
            httpRequest.setHeader(next.getHeadKey(), next.getHeadValue());
        }
    }`

**Comment by zhaodp** [comment]
> `httpclient` plugin doesn't collect the parameters now, if you want, please enhance that plugin and add a config item like `plugin.springmvc.collect_http_params` and `plugin.tomcat.collect_http_params` to make it work
  I enhanced the httpClient-4.x-plugin, it worked  ：


 `    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
        MethodInterceptResult result) throws Throwable {
        ......
        if (httpRequest  instanceof HttpEntityEnclosingRequest) {
            HttpEntityEnclosingRequest httpEntityEnclosingRequest = (HttpEntityEnclosingRequest) httpRequest;
            HttpEntity entity = httpEntityEnclosingRequest.getEntity();
            if (entity instanceof StringEntity) {
                String tagValue = EntityUtils.toString(entity);
                tagValue = StringUtil.cut(tagValue, 1024);
                Tags.HTTP.PARAMS.set(span, tagValue);
            }
        }

        CarrierItem next = contextCarrier.items();
        while (next.hasNext()) {
            next = next.next();
            httpRequest.setHeader(next.getHeadKey(), next.getHeadValue());
        }
    }`

> `httpclient` plugin doesn't collect the parameters now, if you want, please enhance that plugin and add a config item like `plugin.springmvc.collect_http_params` and `plugin.tomcat.collect_http_params` to make it work

  I enhanced the httpClient-4.x-plugin, it worked  ：
        if (httpRequest  instanceof HttpEntityEnclosingRequest) {
            HttpEntityEnclosingRequest httpEntityEnclosingRequest = (HttpEntityEnclosingRequest) httpRequest;
            HttpEntity entity = httpEntityEnclosingRequest.getEntity();
            if (entity instanceof StringEntity) {
                String tagValue = EntityUtils.toString(entity);
                tagValue = StringUtil.cut(tagValue, 1024);
                Tags.HTTP.PARAMS.set(span, tagValue);
            }
        }

**Comment by zhaodp** [comment]
I enhanced the httpClient-4.x-plugin, it worked  ：

        if (httpRequest  instanceof HttpEntityEnclosingRequest) {
            HttpEntityEnclosingRequest httpEntityEnclosingRequest = (HttpEntityEnclosingRequest) httpRequest;
            HttpEntity entity = httpEntityEnclosingRequest.getEntity();
            if (entity instanceof StringEntity) {
                String tagValue = EntityUtils.toString(entity);
                tagValue = StringUtil.cut(tagValue, 1024);
                Tags.HTTP.PARAMS.set(span, tagValue);
            }
        }

**Comment by xbkaishui** [comment]
> I enhanced the httpClient-4.x-plugin, it worked ：
> 
> ```
>     if (httpRequest  instanceof HttpEntityEnclosingRequest) {
>         HttpEntityEnclosingRequest httpEntityEnclosingRequest = (HttpEntityEnclosingRequest) httpRequest;
>         HttpEntity entity = httpEntityEnclosingRequest.getEntity();
>         if (entity instanceof StringEntity) {
>             String tagValue = EntityUtils.toString(entity);
>             tagValue = StringUtil.cut(tagValue, 1024);
>             Tags.HTTP.PARAMS.set(span, tagValue);
>         }
>     }
> ```

You are collect the http request body,  not the params ?

**Comment by xbkaishui** [comment]
We don't recommend to collect body, it may case performance issue.

**Comment by zhaodp** [comment]
> We don't recommend to collect body, it may cause performance issue.

We only use it in  test environment
