### ISSUE TITLE
define alarm rule but service_instance name isn't unchanged

### ISSUE THREAD

**Issue by Jiangting1** [apache/skywalking#5738]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
define alarm rule but service_instance name isn't unchanged
- [ ] Bug
- [ ] Requirement
if I want define a  instance rule ,how can i know the include_names,and the alarm like this
Response time of service instance a-b-loans-pid:7223@localhost is more than 1500ms in 2 minutes of last 10 minutes
service_instance_resp_time_5000_rule:
    metrics-name: service_instance_resp_time
    include-names:
      - a-b-loans
    op: ">"
    threshold: 5000
    period: 10
    count: 2
    silence-period: 5
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how can i know the include_names
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.6.0 
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
@Jiangting1 if you really want to do that, specify your own instance name instead of letting agent to generate it, see `agent.instance_name` in [the doc](https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#table-of-agent-configuration-properties)

**Comment by Jiangting1** [comment]
ok,thanks very much
