### ISSUE TITLE
how to modify traceId

### ISSUE THREAD

**Issue by wuxingye** [apache/skywalking#5740]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

1. how can i trace my project myself

the client is just

    <dependency>
      <groupId>org.apache.skywalking</groupId>
      <artifactId>apm-toolkit-trace</artifactId>
      <version>${skywalking.version}</version>
      <scope>provided</scope>
    </dependency>

or more

2. can i modify traceId, so it can associate another
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
You cannot do that via the toolkit. We don't support that now. If the trace breaks, you should find out why, simply modifying the trace id may make things worse.

**Comment by kezhenxu94** [comment]
As for how to trace by yourself, please read the doc, it's clearly documented.

**Comment by wuxingye** [comment]
As i publish a topic to redis, when i subscribe it, the traceId lose

I wanna add the traceId to data, and modify subscribe traceId, so the to trace linked

**Comment by kezhenxu94** [comment]
> As i publish a topic to redis, when i subscribe it, the traceId lose
> 
> I wanna add the traceId to data, and modify subscribe traceId, so the to trace linked

I personally don't suggest to do that (and the toolkit doesn't have such APIs, as I said above), in my opinion, you should consider enhancing the Redis plugin(or create one) to propagate the tracing context in the PubSub mode, maybe the Redis plugin currently doesn't support that mode
