### ISSUE TITLE
grpc-default-worker thread is too much int k8s

### ISSUE THREAD

**Issue by qlql489** [apache/skywalking#5751]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
agent client start too much thread for grpc，our server is in k8s pod，32 cpu process count，so every server has 64 grpc-default-worker thread , does is configurable in next version 
___
### Bug
- Which version of SkyWalking, OS and JRE?
8.2
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Check the backend configuration vocabulary. We have that already.
