### ISSUE TITLE
docker image tag 'apache/skywalking-oap-server:8.1.0-es7' not support elasticsearch-7.9.3

### ISSUE THREAD

**Issue by rysinal** [apache/skywalking#5753]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Which image tag should I use to ensure the log output is normal

command：

`$ docker run --name oap --restart always -d -e SW_STORAGE=elasticsearch -e SW_STORAGE_ES_CLUSTER_NODES=10.10.5.26:19200 apache/skywalking-oap-server:8.1.0-es7
`
this output log:

```
[Entrypoint] Apache SkyWalking Docker Image

Current image doesn't Elasticsearch 6
```

#elasticsearch  version:
```
{
    "name": "node-1",
    "cluster_name": "li_test",
    "cluster_uuid": "hhHlP90-QlumiqcjvXVm3w",
    "version": {
        "number": "7.9.3",
        "build_flavor": "default",
        "build_type": "rpm",
        "build_hash": "c4138e51121ef06a6404866cddc601906fe5c868",
        "build_date": "2020-10-16T10:36:16.141335Z",
        "build_snapshot": false,
        "lucene_version": "8.6.2",
        "minimum_wire_compatibility_version": "6.8.0",
        "minimum_index_compatibility_version": "6.0.0-beta1"
    },
    "tagline": "You Know, for Search"
}
```

**Comment by wu-sheng** [comment]
You set wrong. You need to set storage to elasticsearch7. Please read document first.
