### ISSUE TITLE
In cluster mode ʻinternalComHost` and ʻinternalComPort` bring complexity

### ISSUE THREAD

**Issue by GerryYuan** [apache/skywalking#5763]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When sw is in cluster mode, our configuration items need to use the two configurations of "internalComHost" and "internalComPort", which increases the complexity of users and is easy to make mistakes. I think the program should automatically help us complete the registration address.
___
### Bug
- Which version of SkyWalking, OS and JRE?
jdk8
sw8.1.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
How to complete that? SkyWalking don't ask for `internalCom*` always, I think the reason you need is you always set the listening IP to 0.0.0.0.
