### ISSUE TITLE
trace list show incomplete

### ISSUE THREAD

**Issue by HuangDayu** [apache/skywalking#5769]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug

___
### Question
- What do you want to know?

**trace list show incomplete**

___
### Bug
- Which version of SkyWalking, OS and JRE?

`SkyWalking 8.1.0`

- What happened?

**If trace list span greater than 8 ，then show incomplete .**

___
### Requirement or improvement

- Please describe your requirements or improvement suggestions.

You can add a drop-down scroll bar to solve this problem.

### evidence

![image](https://user-images.githubusercontent.com/23421574/97840891-cd456180-1d1f-11eb-9c70-6ed1ad3c35aa.png)

**Comment by wu-sheng** [comment]
![image](https://user-images.githubusercontent.com/5441976/97841104-1dbcbf00-1d20-11eb-93a7-50e30cded6ad.png)

It is working as expected on the demo and my browser. http://122.112.182.72:8080/trace

**Comment by wu-sheng** [comment]
Also, there is a scrolling bar there.

**Comment by HuangDayu** [comment]
![image](https://user-images.githubusercontent.com/23421574/97843482-565e9780-1d24-11eb-9da0-6b3126469c8d.png)

I compared the source code, aren’t we using the same version?

**Comment by wu-sheng** [comment]
This is the 8.2.0 release, I think.

**Comment by HuangDayu** [comment]
`8.0.2`  No problem. Thanks
