### ISSUE TITLE
Support HPA in the SWCK

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5772]
I and @hanahmily had a discussion days ago, as SkyWalking has full capability of metrics, and we have the operator, HPA seems a reasonable next step.

K8s HPA, https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

We should set up an adaptor to bridge the OAP cluster and k8s API Server.

**Comment by wu-sheng** [comment]
@hanahmily Should we close this? I think you are running the 0.2.0 release already.

**Comment by hanahmily** [comment]
All right, this had been closed by https://github.com/apache/skywalking-swck/pull/12
