### ISSUE TITLE
kubernetes-java-client watch time unit error

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#5778]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Bug
https://github.com/kubernetes-client/java/pull/1344
in Kubernetes-java-client, the millisecond is used to deliver to the API server.
but the unit in the API server is Second.

PR: https://github.com/apache/skywalking/pull/5777

**Comment by wu-sheng** [comment]
We should fix this after new k8s-java-client released.

**Comment by wu-sheng** [comment]
@EvanLjp I can see the 8.0.2 k8s-client-java released in May only. https://search.maven.org/artifact/io.kubernetes/client-java

It seems like 8.x is not updated, could you take a look, and evaluate, whether do we need to upgrade? @hanahmily Please take a look too.

**Comment by EvanLjp** [comment]
![image](https://user-images.githubusercontent.com/31562192/105953441-236f3a00-60ae-11eb-8d1c-dccbaf3c1b05.png)
I have checked the released package recently and found only fixed in the `10.01` and `11`  version.

**Comment by wu-sheng** [comment]
Yes, clearly, 8.x is not maintained. When you have time, please consider to upgrade this client lib to resolve this issue.

**Comment by EvanLjp** [comment]
ok

**Comment by wu-sheng** [comment]
It is not that urgent, but we should fix this :)
