### ISSUE TITLE
storage-jdbc isExists not set dbname

### ISSUE THREAD

**Issue by FoolRabbit** [apache/skywalking#5785]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS and JRE?
8.2.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
when i has two or more schemas, can't auto create tables

```
    @Override
    protected boolean isExists(Model model) throws StorageException {
        TableMetaInfo.addModel(model);
        JDBCHikariCPClient h2Client = (JDBCHikariCPClient) client;
        try (Connection conn = h2Client.getConnection()) {
            // getTables need set catalog = conn.getCatalog()
            try (ResultSet rset = conn.getMetaData().getTables(null, null, model.getName(), null)) {
                if (rset.next()) {
                    return true;
                }
            }
        } catch (SQLException | JDBCClientException e) {
            throw new StorageException(e.getMessage(), e);
        }
        return false;
    }
```

**Comment by wu-sheng** [comment]
@JaredTan95 Could you take a look?

**Comment by JaredTan95** [comment]
I will check it soon.
