### ISSUE TITLE
lastest version - compile error (File not found)

### ISSUE THREAD

**Issue by Lynda-Li** [apache/skywalking#5787]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When Collector module is deleted from skywalking?
___
### Bug
- Which version of SkyWalking, OS and JRE?
latest
- Which company or project?
BOCOMM
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
Maven compile error :/skywalking/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[34,19] 程
序包Command不存在
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please read the compiling doc.
