### ISSUE TITLE
UI timezone default value problem

### ISSUE THREAD

**Issue by zhyhzhylove** [apache/skywalking#5789]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Could the time setting of the page be changed to the default last 15 minutes？
Every time I enter the page, I need to change to the time setting.
![image](https://user-images.githubusercontent.com/3204108/98079395-a701fc00-1eae-11eb-92ad-d48bcc70d0bb.png)

**Comment by wu-sheng** [comment]
The setting is based on your browser's local cache. The default is 15 mins.

**Comment by zhyhzhylove** [comment]
The browser's local cache stores the last time value.
I mean whether it could be reset to the last 15 minutes after entering the page again

**Comment by zhyhzhylove** [comment]
> The setting is based on your browser's local cache. The default is 15 mins.

The browser's local cache stores the last time value.
I mean whether it could be reset to the last 15 minutes after entering the page again.

**Comment by wu-sheng** [comment]
Then this is not a problem, someone may like the latest always. New feature depends on the contributors. If someone contributes this, I think should be acceptable.

**Comment by zhyhzhylove** [comment]
> Then this is not a problem, someone may like the latest always. New feature depends on the contributors. If someone contributes this, I think should be acceptable.


I am looking forward to it. In fact, from a performance perspective, displaying the latest data may be a better user experience.

Thanks.

**Comment by wu-sheng** [comment]
Maybe true. But SkyWalking is driven by the community, a.k.a. contributors. So, this feature would show up once we have one does that. Unless there is a blocking bug, we usually don't assign tasks to the core committer team. They are diverse in the different companies, I can't assign jobs :)
