### ISSUE TITLE
ServletContextPropertyPlaceholderConfigurer is not found in some new version for springframework 4

### ISSUE THREAD

**Issue by lagudomeze** [apache/skywalking#5790]
#### skywalking-api.log 
```
org.apache.skywalking.apm.plugin.spring.mvc.v4.define.RestControllerForLowVersionInstrumentation is not working. 
Because witness class org.springframework.web.context.support.ServletContextPropertyPlaceholderConfigurer is not existed. 
```

#### ServletContextPropertyPlaceholderConfigurer removed in some new version for springframework 4

1. [cannot-find-class-org-springframework-web-context-support-servletcontextproperty](https://stackoverflow.com/questions/60722169/cannot-find-class-org-springframework-web-context-support-servletcontextproperty)

1. [cannot find in github too](https://github.com/spring-projects/spring-framework/find/v4.3.24.RELEASE)

#### in code check ServletContextPropertyPlaceholderConfigurer  for springmvc 4
https://github.com/apache/skywalking/blob/9042ce6fe225a5c68fd00185e7dec9dff14b9eee/apm-sniffer/apm-sdk-plugin/spring-plugins/mvc-annotation-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/mvc/v4/define/RestControllerForLowVersionInstrumentation.java#L28

any way to solve this problem?

thx

**Comment by wu-sheng** [comment]
Should consider using this tool https://github.com/SkyAPM/uranus to find a new suitable witness class. @lagudomeze I could assign this issue to you if you want to resolve and submit a pull request to the repo.

**Comment by lagudomeze** [comment]
ok.
```
./bin/old-class -c org.springframework:spring-web:4.3.24.RELEASE  -n org.springframework:spring-web:5.0.0.RELEASE -s
org.springframework.http.client.OkHttpClientHttpResponse
...

org.springframework.web.method.annotation.ExceptionHandlerMethodResolver$1

org.springframework.web.method.HandlerMethodSelector
...

size:46
```

`org.springframework.web.method.HandlerMethodSelector`

i test spring-web 4.3.0/4.3.24/4.2.0/4.1.0/4.0.0, HandlerMethodSelector is old class.

so i try submit a pull request?

**Comment by wu-sheng** [comment]
It looks reasonable, please submit the pull request, and I will ask the reviewer to recheck.

**Comment by LiWenGu** [comment]
We also encountered the same problem, the version of spring-web we used was 4.3.16. We change the witness class of the following two files to org.springframework.web.method.HandlerMethodSelector:
https://github.com/apache/skywalking/blob/f94bf971fdf8beb4905ac140fcde93dcf2e1af62/apm-sniffer/apm-sdk-plugin/spring-plugins/mvc-annotation-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/mvc/v4/define/ControllerForLowVersionInstrumentation.java#L28
https://github.com/apache/skywalking/blob/f94bf971fdf8beb4905ac140fcde93dcf2e1af62/apm-sniffer/apm-sdk-plugin/spring-plugins/mvc-annotation-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/mvc/v4/define/RestControllerForLowVersionInstrumentation.java#L28
@lagudomeze

**Comment by wu-sheng** [comment]
@LiWenGu Welcome to submit a pull request about this.
