### ISSUE TITLE
About search Trace with tag this function?

### ISSUE THREAD

**Issue by yixiuzhemu** [apache/skywalking#5793]
Dear wu-sheng:

This is my search with queryTrace function:
![image](https://user-images.githubusercontent.com/32632414/98093986-a031b400-1ec3-11eb-9a7e-08804a96e34b.png)

We can find out this result include <url,"http://t-xg.boleme.net/pl/pack/login/usernameLogin"> this tag.

But when I using queryBasicTraces this function:
![image](https://user-images.githubusercontent.com/32632414/98094333-1afacf00-1ec4-11eb-9702-6d623d3b0569.png)
The result is NULL,In other words,I didn't get result with tag.

Maybe I got it wrong,this function can't index trace result for I want?
Or did  I use the wrong way?

Hope you can answer for me as soon as possible.

**Comment by wu-sheng** [comment]
Find `searchableTracesTags` in doc https://github.com/apache/skywalking/blob/ac36a3ff49bb174dc5d7982098fab5dc4cd583c4/docs/en/setup/backend/configuration-vocabulary.md, also exist in the `application.yml` of the OAP.

You should find your own answer.

**Comment by yixiuzhemu** [comment]
OK . thank you very much!

**Comment by yixiuzhemu** [comment]
This mean is I can't use myself tag In my code?

**Comment by wu-sheng** [comment]
Do you really read? They are configurations.

**Comment by yixiuzhemu** [comment]
I'm sorry, maybe I was wrong about what i meant.
There include some default configuration.But my mean is use  ActiveSpan.tag this function in my code to  add myself tag.Use this function I can add one segement.
 like this:
![image](https://user-images.githubusercontent.com/32632414/98097195-a45fd080-1ec7-11eb-8c79-2a7524d58308.png)
I want use some tag to find this segement.
Uh...... 
Maybe I shouldn't use this function?
I am a novice for skywalking.

**Comment by wu-sheng** [comment]
Again, this is a configuration. If you want more tags, add them.

**Comment by yixiuzhemu** [comment]
Ah .I see. thank you very much
