### ISSUE TITLE
[Lua]SkyWalking-nginx-lua0.3.0 traceid repeat all the time

### ISSUE THREAD

**Issue by gudandezhu** [apache/skywalking#5805]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
skywalking-nginx-lua0.3.0 , macOS , JRE8.0

when I used skywalking-nginx-lua0.3.0 , I got the same traceid(all api) ，I just changed the Nginx.conf
next is my nginx.conf :
![image](https://user-images.githubusercontent.com/43182553/98346318-bde05400-2050-11eb-9d3a-3d955cf4fee9.png)

this is log:
![image](https://user-images.githubusercontent.com/43182553/98346511-05ff7680-2051-11eb-8cda-160f9b42081d.png)

**Comment by wu-sheng** [comment]
@moonming @dmsolr We need to recheck this, once this is true, we need a 0.3.1 directly.

**Comment by wu-sheng** [comment]
Seem @membphis 's local test doesn't show the same issue.

![image](https://user-images.githubusercontent.com/5441976/98353253-06e8d600-205a-11eb-978c-d565aefea763.png)

**Comment by membphis** [comment]
we need to set the random seed in `init_worker_by_lua_block` phase:

```diff
--- a/README.md
+++ b/README.md
@@ -32,6 +32,7 @@ http {
         -- Instance means the number of Nginx deployment, does not mean the worker instances
         metadata_buffer:set('serviceInstanceName', 'User Service Instance Name')

+        require("skywalking.util").set_randomseed()
         require("skywalking.client"):startBackendTimer("http://127.0.0.1:8080")
     }
```

I will submit a new PR about this.

**Comment by Miss-you** [comment]
I think it's better to use ngx.var.request_id rather than generate uuid by itself.

**Comment by wu-sheng** [comment]
I like @Miss-you 's idea.

**Comment by Miss-you** [comment]
The distributed unique id generation algorithm is a classic problem, so we'll just use `ngx.var.request_id` here.

**Comment by wu-sheng** [comment]
I have removed `high-priority` as this UUID should be safe(maybe?). @Miss-you feel free to submit a PR to implement in your way, and we could include it in the 0.4.0.

**Comment by membphis** [comment]
@gudandezhu please confirm if you enabled the directive `lua_code_cache` in your Nginx config.

I can get the same output when using `lua_code_cache off` in Nginx config.

1. please remove `lua_code_cache` or set `lua_code_cache on`.
2. add `require("skywalking.util").set_randomseed()` in `init_worker_by_lua_block`, here is example: https://github.com/apache/skywalking-nginx-lua/pull/52/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R36

**Comment by gudandezhu** [comment]
yes , remove lua_code_cache is right

**Comment by snpcp** [comment]
Hello,

I not use lua_code_cache, and using 'require("skywalking.util").set_randomseed()'. However, I look out the traceid is repeat.
In particular, I have 16 processors of Nginx, and repeat count is 16.

So, What am I doing wrong?

**Comment by snpcp** [comment]
The random_seed is /dev/urandom, the uuid is resty.jit-uuid.
