### ISSUE TITLE
service_cpm

### ISSUE THREAD

**Issue by githubphy** [apache/skywalking#5819]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
In the process of testing, we found that service_cpm counts the average TPS per instance, not the TPS of the entire application?

**Comment by wu-sheng** [comment]
> service_cpm counts the average TPS per instance

No, it should not be. Are you using the cluster mode? Do you set the mode correctly? Such as checking the logs, and health check CLI(https://github.com/apache/skywalking-cli#checkhealth) with 8.2.0?

**Comment by githubphy** [comment]
> > service_cpm counts the average TPS per instance
> 
> No, it should not be. Are you using the cluster mode? Do you set the mode correctly? Such as checking the logs, and health check CLI(https://github.com/apache/skywalking-cli#checkhealth) with 8.2.0?

We used 8.1.0, used two oapservices, The cluster mode uses zookeeper, and did the following tests:
1. For a node, the total number of JMeter requests is 100, and the requests are 100 / s. The total number of requests displayed by skyui is 100, service_cpm is 100;
![100](https://user-images.githubusercontent.com/9158859/98911082-012e3d00-24ff-11eb-8752-460fdb68ff70.jpg)

2. When there are two nodes, the total number of JMeter requests is 100, and the requests are 100 / s. The total number of requests displayed by skyui is 50, service_cpm is 50;
![50](https://user-images.githubusercontent.com/9158859/98911198-2cb12780-24ff-11eb-8aad-12c8fc226941.jpg)

Therefore, our test conclusion is service_cpm counts the average TPS per instance

**Comment by wu-sheng** [comment]
Again, check the health status. I still think your cluster mode of SkyWalking OAP is not set correctly.

**Comment by githubphy** [comment]
> Again, check the health status. I still think your cluster mode of SkyWalking OAP is not set correctly.

Thank you. It's settled
