### ISSUE TITLE
org.apache.skywalking.apm.toolkit.trace.TraceContext.traceId()  is   Ignored_Trace

### ISSUE THREAD

**Issue by fxw727143568** [apache/skywalking#5825]
when I get traceId by 
org.apache.skywalking.apm.toolkit.trace.TraceContext.traceId()

return Ignored_Trace

could you help me？

**Comment by wu-sheng** [comment]
Ignored means, you may have opened the sampling mechanism. Also could because of the suffix or ignore plugin.

**Comment by fxw727143568** [comment]
where can i find these，could you tell me how to fix it

**Comment by wu-sheng** [comment]
I don't know why in your case, the thing I provided is just guessing. All of them are available and configurable features.

**Comment by fxw727143568** [comment]
It was normal yesterday. but It can't be used today. Nothing has been modified
