### ISSUE TITLE
The distributed trace chain is broken when Redis is treated as a message queue

### ISSUE THREAD

**Issue by ascrutae** [apache/skywalking#583]
The trace context isn't propagate when Redis is treated as a message queue.

**Comment by KaiwenWang** [comment]
This needs users to define a rule to mix traceId and queue message element, then write a plugin to parse the rule . but it is possible to prodcuce other problems.

**Comment by wu-sheng** [comment]
@KaiwenWang Yes, that is why @ascrutae keeps it in TBD. Can't find a safe way to solve this.

**Comment by wu-sheng** [comment]
Close for now.

**Comment by zhangnew** [comment]
Is there a solution yet ?

**Comment by wu-sheng** [comment]
> Is there a solution yet ?

There is no good solution for this. We just opened this for backlog.
