### ISSUE TITLE
It is recommended to separate OAP Server's Collector and query functions

### ISSUE THREAD

**Issue by koalas1105** [apache/skywalking#5830]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ x] Requirement
- [ ] Feature or performance improvement
It is recommended to separate OAP Server's Collector and query functions
___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Is this a question or something? I am confused.

**Comment by koalas1105** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    it not a question， it is suggest.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                32508133
                            
                    
                        
                            
                                    32508133@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 11/11/2020 16:08，吴晟 Wu Sheng<notifications@github.com> wrote： 



Is this a question or something? I am confused.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wu-sheng** [comment]
It is supported already. Set the oap as receiver role.

**Comment by koalas1105** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    ths。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                32508133
                            
                    
                        
                            
                                    32508133@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 11/11/2020 17:02，吴晟 Wu Sheng<notifications@github.com> wrote： 



It is supported already. Set the oap as receiver role.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by koalas1105** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    How to Set the oap as receiver role? 
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                32508133
                            
                    
                        
                            
                                    32508133@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 11/11/2020 17:02，吴晟 Wu Sheng<notifications@github.com> wrote： 



It is supported already. Set the oap as receiver role.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by koalas1105** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    I know how to config.
            role: ${SW_CORE_ROLE:Mixed} # Mixed/Receiver/Aggregator
            
        
    but That‘s not what I want。I expect query and collect functions to be separate。 
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                32508133
                            
                    
                        
                            
                                    32508133@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 11/11/2020 17:02，吴晟 Wu Sheng<notifications@github.com> wrote： 



Closed #5830.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wu-sheng** [comment]
It is included in the document, please read.
