### ISSUE TITLE
Dynamic configuration key bug of `endpoint-name-grouping`

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5831]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

EndpointNameGroupingRuleWatcher class provides an incorrect module name, which makes the configuration key wrong. The wrong name includes the unexpected package name. Referring to the following codes, 

https://github.com/apache/skywalking/blob/master/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/config/group/EndpointNameGroupingRuleWatcher.java#L38

**Comment by tangshan-brs** [comment]
The problem has been modified and submitted to PR;

https://github.com/apache/skywalking/pull/5833
