### ISSUE TITLE
when I use 'sum' in oal script,it can't generate dynamic class

### ISSUE THREAD

**Issue by HowlsCastle** [apache/skywalking#5837]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking8.2
- Which company or project?

- What happened?
I add sum operation into oal script,but the oap server can't start correctly.There is something error when the backend generate dynamic class.I saw the code and I think the reason is that the annotation in SumMetrics used error (org.apache.skywalking.oap.server.core.analysis.metrics.SumMetrics).
![image](https://user-images.githubusercontent.com/5523569/99021676-2624bd80-259c-11eb-97d4-89c63fe26e84.png)
Is that right？
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think the current is correct. Why do you expect the `ConstOne`? Are you actually looking for `count`?(`CountMetrics`)

**Comment by HowlsCastle** [comment]
> I think the current is correct. Why do you expect the `ConstOne`? Are you actually looking for `count`?(`CountMetrics`)

So there is some error in doc?I add sum option which descript in doc,the backed is wrong.
![image](https://user-images.githubusercontent.com/5523569/99030294-a0127200-25af-11eb-9aba-1c4ed8144f23.png)
![image](https://user-images.githubusercontent.com/5523569/99030336-b3bdd880-25af-11eb-8054-fd860531d457.png)
I should add field name to replace the '*'?

**Comment by wu-sheng** [comment]
Those are different. Sum base on numberic field. Count is for counting the number of input data set.
