### ISSUE TITLE
Leverage ShardingSphere's SQL parser to get table's read/write level metrics

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5838]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

We were waiting for ShardingSphere's 5.0 release for a long time. Powered by that, we have the SQL parser compatibility across different SQL databases. So, we could run SQL parser at the backend in doing trace/span and ALS+SQL-log(in the future) analysis.

We should be able to get the metrics like 
1. read/write latency/traffic for table and table set.
1. select/update metrics per database.
1. DDL detection. As normally, there should be no DDL in the product environment.

@tristaZero When your documentation is ready, please ping us. If you want to lead this, please let us know. 
@ascrutae @kezhenxu94 @hanahmily We need to keep our eyes on this and add this into the OAP in the next several weeks, especially for trace analysis first.

**Comment by ascrutae** [comment]
got it!

**Comment by tristaZero** [comment]
Hi everyone. I am glad to see this SQL-parsing feature of ShardingSphere can come into play in Skywalking community. :-）
We spent a lot of effort and time on this important feature, though it is the first time to present it an independent feature from ShardingSphere. Some interesting ideas are still in the incubator. Stayed tuned!

The additional doc is under review. I suppose [it](https://github.com/apache/shardingsphere/pull/8138) will be merged soon. Please give it a watch.

Best,
Trista

**Comment by wu-sheng** [comment]
I set up the benchmarks to test the performance, https://github.com/apache/shardingsphere/issues/8208. We need a deeper discussion and maybe optimization as right now, it seems would cause a big impact to the OAP.
