### ISSUE TITLE
Add Service Group concept for service filter

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5841]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement

SkyWalking has the capability to observe thousands of services, which have different types, such as agent-observed, service-mesh, Istio control panel, Envoy data panel, ShardingSphere proxy(etc.). All of them should have different dashboards due to we enhanced in the past 2 versions.
Now, I intend to add this. 
1. Service Group is a string name-based concept, added to the service list. 
1. Provide a new optional condition(group) in the GraphQL. If provided, use it to filter the service list, otherwise, like we did today.
1. The group name would not be updated due to the ServiceTraffic is `supportUpdate = false`. So, it is only updated(actually added) once the TTL reached and data has been removed.
1. UI should be updated to add the current filter condition in the GraphQL. cc @Jtrust 

If #5835 merged fast, this would be added in the 8.4.0.

This concept is helpful for supported group based topology in the future, but note, this is not the goal of this PR.

**Comment by hanahmily** [comment]
> Provide a new optional condition(group) in the GraphQL. If provid to filter  ser
