### ISSUE TITLE
Metrics data  persistence question

### ISSUE THREAD

**Issue by haoyann** [apache/skywalking#5843]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bux
- [ ] Requirement
- [ ] Feature or performance improvement

___

### Question

- What do you want to know?

  We use skywalking version 8.2.0, and use ES cluster to store data, five data nodes (cpu: 16 memery: 32G). But his QPS is only 2W at most, and ES throws EsRejectedExcutionException, so kafka has a lot of news accumulation. The highest accumulation reaches 200 million. After we made various optimizations to ES, we found that the effect was very small.
  We will look at the code later and find that the segment data is written asynchronously and the metrics is written synchronously.

   metrics persistence code in `org.apache.skywalking.oap.server.core.storage.PersistenceTimer.

   It needs to use the previous storage for calculations, and it needs to query the previous data and can only be written synchronously.There are two problems:

  1. Synchronous writing is very slow, and some data needs to be updated, which will block ES from processing other requests.
  2. Synchronous writing does not limit the size of the requested data.

  Later, we observed a phenomenon, a synchronous request has 2w data, which takes 10000ms, so ES will block the processing of this request, and if the time is too long, it will discard other asynchronous requests and throw EsRejectedExcutionException.

- How we solved it

  We removed the writing of metrics data, so we also lost the metrics data in skywalking。

  Because this kind of persistence will greatly affect the write performance, you can do calculations when querying and not doing calculations when writing. In this way, when we write data, we can write asynchronously, so QPS will be improved a lot, but this will change a lot. . .

  The above are the problems I encountered in using skywalking and some suggestions of my own. : )

**Comment by wu-sheng** [comment]
I don't know the performance of your Elasticsearch, but there are many cases supporting TB even PB level analysis nd persistent. There is no performance issue.

We limited the size per batch of metrics persistent. I don't know what is your meaning.

You remove the metrics persistent, which is your choice, not the optimization.
