### ISSUE TITLE
trace-ignore-plugin dose not work

### ISSUE THREAD

**Issue by zender-projects** [apache/skywalking#5847]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to ignore path of eureka, eg /eureka/**，so i config it follow:
1.copy apm-trace-ignore-plugin-8.1.0.jar from optional-plugins to plugins
2.add apm-trace-ignore-plugin.config in config path
3.restart agent

but, i also find eureka uri in UI 

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
There is a `TraceIgnoreTest#TraceIgnoreTest` for **"/eureka/**"**. Please check the source codes.

**Comment by zender-projects** [comment]
> There is a `TraceIgnoreTest#TraceIgnoreTest` for **"/eureka/**"**. Please check the source codes.

i am a new user of skywalking, i just want to know why it dose not work with right configuration

**Comment by caopengan** [comment]
I also met this problem. Have you solved it?

**Comment by zender-projects** [comment]
> I also met this problem. Have you solved it?

just like this:
1. provide apm-trace-ignore-plugin.config in ${agent_home}/config
2. touch trace.ignore_path=/eureka/**,Mysql/JDBI/Connection/close,/actuator/** 

the difference is that i remove ${} that document provide
