### ISSUE TITLE
Does skywalking 8.x support spring cloud gateway version 2.2.x ?

### ISSUE THREAD

**Issue by huangcanhui2018** [apache/skywalking#5850]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [Y ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

Hi,wusheng!

Does skywalking 8.x support spring cloud gateway version 2.2.x ? At present, it is found that the tracking information cannot be obtained normally. However, skywalking 8.1.0 can obtain the tracking information of spring cloud gateway version 2.0.0.
At present, the only plug-ins available for spring cloud gateway are apm-spring-cloud-gateway-2.0.x-plugin-8.1.0.jar and apm-spring-cloud-gateway-2.1.x-plugin-8.1.0.jar.

SkyWalking：8.1.0 or 8.2.0
OS：win7
JRE：1.8.x

**Comment by wu-sheng** [comment]
We have 2.2.3 tested. https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/gateway-2.1.x-scenario/support-version.list

**Comment by huangcanhui2018** [comment]
@wusheng
But the version we are using is spring cloud gateway 2.2.2.RELEASE. When skywalking 8.1.0 / 8.2.0 is used, the tracking information cannot be obtained normally, and the span cannot be connected in series according to traceId.

**Comment by wu-sheng** [comment]
I just gave you the fact of testing. Our test codes are verifying the plugin, and also for you to compare what is the difference. Because, in the reality, we can't test every version and every usage you could do.

**Comment by wu-sheng** [comment]
In the plugin case, we always prefer you could find the issue first, even send a pull request to fix. The libraries with versions are countless. This is not a job for one man or a limited group of people. We are looking forward to the whole community including the end-users to maintain the plugin system.

**Comment by huangcanhui2018** [comment]
Referring to the test example given above, I also tested it with the following version:
1) spring boot 2.2.10.RELEASE
2) spring cloud Hoxton.SR5
3) spring cloud gateway 2.2.3.RELEASE

The results as follows:
The traceId obtained by spring cloud gateway, sc-consumer and sc-provider is still independent.
The traceId obtained by spring cloud gateway is "A", and traceId obtained by sc-consumer and sc-provider is "B". 
So the whole request trace cannot be connected in series by traceId .

**Comment by wu-sheng** [comment]
I don't know how you test. We don't test manually, SkyWalking check this case with the expected trace data automatically, https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/gateway-2.1.x-scenario/config/expectedData.yaml.

Read the test scenario deeper.
