### ISSUE TITLE
Slow statements dashboard slow SQL statistics is not complete, SQL only shows half why

### ISSUE THREAD

**Issue by qiang33161312** [apache/skywalking#5854]
Skywalking version：8.1.0
Problem description：Slow statements dashboard slow SQL statistics is not complete, SQL only shows half why
Problem phenomenon：Open the browser console (F12), select the corresponding slow SQL in the tab, and the content in the label is also half displayed

**Comment by wu-sheng** [comment]
We truncate the SQL to protect the memory at the agent side.

**Comment by qiang33161312** [comment]
thank you very much.
