### ISSUE TITLE
The memory of the JVM continues to rise to the maximum

### ISSUE THREAD

**Issue by Qx-Meng** [apache/skywalking#5857]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- skywalking-agent8.2.0

- Which company or project?

- What happened?
JVM memory to continuously increase to the maximum value.
___
### Requirement or improvement
- Deploying agent 8.2.0 in a websocket service causes the JVM memory to continuously increase to the maximum value. However, the skywalking UI shows that the application service itself occupies a small amount of JVM memory (1.7g). The maximum memory of the JVM is (- xmx6144m). The websocket service is deployed in docker. The problem is that it happens in the morning. Normally, it will maintain a 5K long link service

**Comment by zifeihan** [comment]
Where did you know that the maximum was reached? Your question is whether the jvm memory reaches the maximum after using the agent? Or is the UI display inconsistent with the maximum value you got?
If it is determined that the memory keeps increasing after using the agent, please dump the memory when the memory is relatively high to facilitate analysis of the problem. Note that dumping memory will cause the application to stop the world.

**Comment by Qx-Meng** [comment]
> Where did you know that the maximum was reached? Your question is whether the jvm memory reaches the maximum after using the agent? Or is the UI display inconsistent with the maximum value you got?
> If it is determined that the memory keeps increasing after using the agent, please dump the memory when the memory is relatively high to facilitate analysis of the problem. Note that dumping memory will cause the application to stop the world.

Yes, we used to use agent version 6.0. This week we switched to version 8.2.0. We used Prometheus to monitor and find that the memory of the JVM continues to rise to the maximum, and several of our services are connected to skywalking. Other services are OK, but the websocket service has a memory problem

**Comment by zifeihan** [comment]
> > Where did you know that the maximum was reached? Your question is whether the jvm memory reaches the maximum after using the agent? Or is the UI display inconsistent with the maximum value you got?
> > If it is determined that the memory keeps increasing after using the agent, please dump the memory when the memory is relatively high to facilitate analysis of the problem. Note that dumping memory will cause the application to stop the world.
> 
> Yes, we used to use agent version 6.0. This week we switched to version 8.2.0. We used Prometheus to monitor and find that the memory of the JVM continues to rise to the maximum, and several of our services are connected to skywalking. Other services are OK, but the websocket service has a memory problem

Is there a big difference between the memory index without agent and with agent? Or is there a big difference between the memory index of using 6.x and 8.x? If there is a big difference, I suggest you dump the jvm memory, I can help you analyze it.

**Comment by Qx-Meng** [comment]
> > > Where did you know that the maximum was reached? Your question is whether the jvm memory reaches the maximum after using the agent? Or is the UI display inconsistent with the maximum value you got?
> > > If it is determined that the memory keeps increasing after using the agent, please dump the memory when the memory is relatively high to facilitate analysis of the problem. Note that dumping memory will cause the application to stop the world.
> > 
> > 
> > Yes, we used to use agent version 6.0. This week we switched to version 8.2.0. We used Prometheus to monitor and find that the memory of the JVM continues to rise to the maximum, and several of our services are connected to skywalking. Other services are OK, but the websocket service has a memory problem
> 
> Is there a big difference between the memory index without agent and with agent? Or is there a big difference between the memory index of using 6.x and 8.x? If there is a big difference, I suggest you dump the jvm memory, I can help you analyze it.

Of course, we dump the JVM memory and find that it is basically the same as the application service memory monitored on skywalking UI. There is no memory overflow on skywalking UI

**Comment by Qx-Meng** [comment]
> > Where did you know that the maximum was reached? Your question is whether the jvm memory reaches the maximum after using the agent? Or is the UI display inconsistent with the maximum value you got?
> > If it is determined that the memory keeps increasing after using the agent, please dump the memory when the memory is relatively high to facilitate analysis of the problem. Note that dumping memory will cause the application to stop the world.
> 
> Yes, we used to use agent version 6.0. This week we switched to version 8.2.0. We used Prometheus to monitor and find that the memory of the JVM continues to rise to the maximum, and several of our services are connected to skywalking. Other services are OK, but the websocket service has a memory problem

What we dump from docker should be the memory of websocket service, which is basically the same as that of skywalking UI monitoring. However, the terminal "top" command shows that the memory occupied by java process has reached the maximum memory

**Comment by wu-sheng** [comment]
> Of course, we dump the JVM memory and find that it is basically the same as the application service memory monitored on skywalking UI. There is no memory overflow on skywalking UI
However, the terminal "top" command shows that the memory occupied by java process has reached the maximum memory

This is a strange thing. Do the service crash after it reached the max memory?

**Comment by Qx-Meng** [comment]
> > Of course, we dump the JVM memory and find that it is basically the same as the application service memory monitored on skywalking UI. There is no memory overflow on skywalking UI
> > However, the terminal "top" command shows that the memory occupied by java process has reached the maximum memory
> 
> This is a strange thing. Do the service crash after it reached the max memory? What does the JVM tool say?

We looked at dump and there was nothing unusual. When the JVM memory is close to the maximum value, the connection creation of websocket is normal, and messages can also be pushed. When our websocket service has a feature, the connection will be frequently disconnected and reconnected
<img width="448" alt="mem-time" src="https://user-images.githubusercontent.com/19489652/99373969-04f60100-28fd-11eb-9b59-525373924d44.png">
<img width="666" alt="connect" src="https://user-images.githubusercontent.com/19489652/99374011-14754a00-28fd-11eb-9df3-b626c7e1d309.png">
<img width="1058" alt="skywalking" src="https://user-images.githubusercontent.com/19489652/99374062-222acf80-28fd-11eb-9675-023a7656dac3.png">

**Comment by wu-sheng** [comment]
Could you keep receiving the trace from that app? Could you run a dump analysis to find out which object(s) cost the memory?
