### ISSUE TITLE
how to use the log, why the log is empty?

### ISSUE THREAD

**Issue by auqf** [apache/skywalking#5858]
![image](https://user-images.githubusercontent.com/8895540/99406200-962e9d00-2928-11eb-8212-e80931b44e04.png)

**Comment by wu-sheng** [comment]
It is the browser log only, the data is from https://github.com/apache/skywalking-client-js.

**Comment by auqf** [comment]
and the service log how to use, it's empty too
![image](https://user-images.githubusercontent.com/8895540/99634023-cd14c800-2a7a-11eb-938a-472b68e046e5.png)

**Comment by wu-sheng** [comment]
Not provided, it may come in 2021.

**Comment by auqf** [comment]
the dashboard how to custom by myself?

**Comment by wu-sheng** [comment]
I don't know what do you mean by custom. As an open source project, you could try by yourself. If you want a specific question, we could help. Don't count on us to help you step by step.
