### ISSUE TITLE
use threadpool,‘trace cross thread’ can print tid，but tid not change all the time

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#5859]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
https://github.com/apache/skywalking/blob/v8.0.1/docs/en/setup/service-agent/java-agent/Application-toolkit-trace-cross-thread.md

use trace cross thread，can print threadpool‘s thread tid，but if main thread change， threadpool‘s thread tid not change all the time

having some good way to resolve this？for example alibaba TransmittableThreadLocal(TTL) 

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking7.0.0, os linux, jre jdk8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I can't understand your meaning. I don't know what change and unchanged mean.

**Comment by wu-sheng** [comment]
Tracing context is working with thread/stack. So, basically, we don't care about the thread id, only thread stack matters. Across threads propagation belongs to the plugins or manually operation. We don't do anything.
