### ISSUE TITLE
Cross-room monitoring service

### ISSUE THREAD

**Issue by 1314cc** [apache/skywalking#5862]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
   Question or discussion

___
### Question
- What do you want to know?
   There are multiple customer room deployment applications, and how is the performance of the service monitored across the room? Is it possible to monitor the service through the public network?

**Comment by wu-sheng** [comment]
What do you mean room? AZ, IDC or something?

**Comment by 1314cc** [comment]
Some services at IDC, some services in the customer motor room.

**Comment by wu-sheng** [comment]
If the internet is good enough for you, it is fine. Basically, the question is, whether do you want to collect all data to one SkyWalking cluster.

**Comment by 1314cc** [comment]
There are not enough machines in the client room, and there is not enough budget. Therefore, it is put in a unified center to collect and monitor service

**Comment by wu-sheng** [comment]
Then you have to provide enough network. I don't know your system load/traffic.
