### ISSUE TITLE
What format should we have in mind for logging to spans?

### ISSUE THREAD

**Issue by vcjmhg** [apache/skywalking#5863]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
when we implication logger plugin whose detailed description can ben found in #4545 , what format should we have in mind for logging to spans?

___
### Current proposal
We all know  AbstractSpan only has log(Throwable) and log(long, Map<String, ?>). It seems that only `log(long, Map<String, ?>)`  can meet the requirements. 
The current preliminary proposal is that the key is the name of log systems such as `logback` ,`log4j`, or `log4j2`. And its value is the content of the log message. 
Just like this:
```java
 ContextManager.activeSpan().log(System.currentTimeMillis(), (Map<String, ?>) new HashMap<>().put("logback","formate log"));
```
**But I am not sure if the above usage is correct.**
Or through `AbstractSpan tag(AbstractTag<?> tag, String value)` instead of log(long, Map<String, ?>) ?
If there is a better method, please come up and discuss it together.

**Comment by wu-sheng** [comment]
First logs should be cataloged as a `log`, rather than a `tag`.

And about the format, how about taking a reference from here? https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/trace/AbstractTracingSpan.java#L171-L173

- `event`=log level(debug/info/...)
- `log.kind`=class of the logger
- `message`=formated text

What do you think? @BFergerson @vcjmhg @kezhenxu94 @codelipenghui 
Another question is, why the log framework matters?

**Comment by BFergerson** [comment]
I can't think of a good reason why the logging framework should matter and I was unaware of the format `AbstractSpan.error()` was already using. I believe that format is just as applicable for the logging desired in #4545.

The only question I have is whether or not #4545 will include the stack trace for each logging level. It should obviously include it for **error** but #4545 includes configuration for the logging level to be configurable to lower levels. If someone is capturing **info** logs will the stack trace also be captured?

**Comment by vcjmhg** [comment]
It's good for me to implication it.:smile:

> Another question is, why the log framework matters?

Because some information that cannot be directly obtained by intercepting the `logger `trace()` ,  such as the stack trace of the exception associated with the logging event. To obtain this information, it must be processed separately through different log frameworks. In other words, it is for better log formatting function.

**Comment by BFergerson** [comment]
@vcjmhg, I think @wu-sheng means why should the logging framework matter to `AbstractSpan.log(long, Map<String, ?>)`. Once you've obtained all the information you need to call that method, why should you also be storing the logging framework which triggered it? For example, why should RocketBot care which logging framework the logs are coming from?

**Comment by vcjmhg** [comment]
> Once you've obtained all the information you need to call that method, why should you also be storing the logging framework which triggered it? For example, why should RocketBot care which logging framework the logs are coming from?

Thank you very much for your explanation. If so, It seems that it not necessary to record the kind name of the logging framework.

**Comment by vcjmhg** [comment]
> I was unaware of the format `AbstractSpan.error()` was already using

@BFergerson,The result of the previous discussion is that we don’t care about the format `AbstractSpan.error()` was already using, we will provide configuration issues to control the format of the log.
```yaml
  - name: "log4j2"
    packages:
      - package1
      - package2
    level: "trace"
    pattern: "%date %level [%thread] %logger{10} [%file:%line] %msg%n"
    filter: "Regular expression"
```
In the above config file, `pattern` will control the format of logging information that we need.

**Comment by wu-sheng** [comment]
What is the filter for?

**Comment by vcjmhg** [comment]
> What is the filter for?


Sorry, I made a mistake. It should be `expression` not `filter`  which can filter logging information with regular expression

**Comment by BFergerson** [comment]
@vcjmhg, 

> > I was unaware of the format `AbstractSpan.error()` was already using
> 
> @BFergerson, The result of the previous discussion is that we don’t care about the format `AbstractSpan.error()` was already using, we will provide a configuration file to control the format of the log.
> 
> ```yaml
>   - name: "log4j2"
>     packages:
>       - package1
>       - package2
>     level: "trace"
>     pattern: "%date %level [%thread] %logger{10} [%file:%line] %msg%n"
>     expression: "Regular expression"
> ```
> 
> In the above config file, `pattern` will control the format of logging information that we need.

I don't think the `pattern` from your configuration and the format which `AbstractSpan.error(Throwable)` is using are mutually exclusive. `pattern` would simply take the place of `message`. I'm probably just increasing confusion by using the word format so liberally. Basically, I'm thinking this:
```java
val pattern = null //todo: parse and format log message based on the configured pattern from logfilter.yaml
val level = null //todo: determine log level being logged

if (ContextManager.isActive()) {
    Map<String, String> logMap = new HashMap<>();
    logMap.put("event", level);
    logMap.put("message", pattern);
    if (level == "error") {
        logMap.put("error.kind", null); //todo: determine error kind
        logMap.put("stack", null); //todo: determine stack trace
    }

    ContextManager.activeSpan().log(logMap);
}
```

Though again, my only question would be whether or not the stack trace was always included regardless of log level.

**Comment by wu-sheng** [comment]
Yes, my understanding is `pattern` is the `message` in the log. The `expression` still doesn't make sense to me. How do we plan to do that?

**Comment by vcjmhg** [comment]
> Yes, my understanding is `pattern` is the `message` in the log. The `expression` still doesn't make sense to me. How do we plan to do that?

The `expression` is mainly to increase the flexibility of the function. In a certain situation, we may need to only record log information containing certain keywords.For example, we need to record the logging message contains  "thread name".
But I don’t know if these scenarios really exist in a production environment.

**Comment by vcjmhg** [comment]
> Though again, my only question would be whether or not the stack trace was always included regardless of log level.

@BFergerson , I am not sure if there will be the following usage in a real environment:
```java
logger.debug("has exception",new Exception());
```
And the information just above needs to be recorded in the span log.

**Comment by BFergerson** [comment]
@vcjmhg, fair enough. My reason for asking was mainly due to my interest in being able to correlate which line the log came from. It would be helpful for a project I'm working on for SkyWalking. I think I could always add an additional configuration setting to `logfilter.yaml` further down the line which would add the class/line number to none error logs.

**Comment by wu-sheng** [comment]
> the expression is mainly to increase the flexibility of the function. In a certain situation, we may need to only record log information containing certain keywords.For example, we need to record the logging message contains "thread name".

OK, I got your time. But, regex match would be a big performance impact on the target system. The log should follow the same logic as the log filter system originally, such as, log level, package name filter, etc. which have been included in the log framework.

**Comment by vcjmhg** [comment]
@BFergerson , ok,`logback` supports the function that collects the line number from where the logging request was issued (the conversion word is [`%line`](http://logback.qos.ch/manual/layouts.html)), so I will use `PatternLayoutEncoder` which from logback to format logs to test its support for this feature .

**Comment by vcjmhg** [comment]
> OK, I got your time. But, regex match would be a big performance impact on the target system. The log should follow the same logic as the log filter system originally, such as, log level, package name filter, etc. which have been included in the log framework.

Ok, if `expression` is not necessary, I will remove it later.

**Comment by vcjmhg** [comment]
@wu-sheng @BFergerson , about the plugin, can we make the following conclusions:
1. The format of logging to spans will contain three fields:
    * event=log level(debug/info/...)
    * log.kind=class of the logger
    * message=formated text
2. `Pattern` will support `%line`  which represents line number from where the logging request was issued.
3. `expression` will be removed. The content of the configuration file is as follows:
```yaml
- name: "log4j2"
    packages:
      - package1
      - package2
    level: "trace"
    pattern: "%date %level [%thread] %logger{10} [%file:%line] %msg%n"
```

**Comment by wu-sheng** [comment]
Make sense to me. @BFergerson Please confirm.

**Comment by BFergerson** [comment]
The format above appears to be more logback than log4j2. Also, I don't think there would be a need for a new line in the pattern as these logs are not going directly to the console.

I'm also having second thoughts about adding the file and line number to the pattern. I forgot these incur a [performance cost](https://logging.apache.org/log4j/2.x/manual/layouts.html#LocationInformation). I still would like to be able to correlate this information but again I'm not completely sure my needs represent what most people's needs are. Either way, I'm starting to think that an apprioate solution for me would be to simply store the log pattern and the parameters separately. Given that the logger plugin hooks into `trace/debug/info/error` method calls, it actually has access to both the pattern and the parameters. If I knew what the unformatted pattern was I can essentially do a grep to find the location (even using the logger name to limit the search even further).

There are some advantages to structured logs over unstructured logs. For example, given this log:
```java
log.warn("span {} has illegal status code {}", span, tag.getValue());
```

Storing this as unstructured would be saving the following map to a span:
```json
"logs": [
  {
    "time": 1605225365711,
    "data": [
      {
        "key": "event",
        "value": "warn"
      },
      {
        "key": "log.kind",
        "value": "org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.MultiScopesAnalysisListener"
      },
      {
        "key": "message",
        "value": "span *span* has illegal status code *tag.getValue()*"
      }
    ]
  }
]
```

Now I'm unsure if SkyWalking plans on making the logs queryable but if I wanted to find all the logs where the `tag.getValue()` had a certain value that would mean doing regex over the `message` variable. Alternatively, you could store both the pattern and the params, like so:
```json
"logs": [
  {
    "time": 1605225365711,
    "data": [
      {
        "key": "event",
        "value": "warn"
      },
      {
        "key": "log.kind",
        "value": "org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.MultiScopesAnalysisListener"
      },
      {
        "key": "message",
        "value": "span {} has illegal status code {}"
      },
      {
        "key": "param.1",
        "value": "*span*"
      },
      {
        "key": "param.2",
        "value": "*tag.getValue()*"
      }
    ]
  }
]
```

I think storing logs this way could provide some benefits when it comes to making them queryable. It would also solve my desire to be able to correlate the source code location of the data being logged as now I can simply grep by the message. There could also be benefits to RocketBot/CLI visualization as the user could then reformat logs on the client side as they see fit and the structure of the logs wouldn't need to be processed on-the-fly by the SkyWalking agent (so maybe that'll help with processing time).

Let me know what you guys think. As always, I'm fine simply creating a PR later on to add extra configuration to suite my needs.

**Comment by wu-sheng** [comment]
> Now I'm unsure if SkyWalking plans on making the logs queryable

Right now, tag-based query is providing limited and pre-defined scopes, as the performance impact.

> I don't think there would be a need for a new line in the pattern as these logs are not going directly to the console.

I have a similar feeling, but the most interesting thing is `threadId`, which is not required by the SkyWalking currently but may be needed by the users. What do you think?

- For `structure` vs `no-structure`.

It looks like the `structure` proposal is better, less performance impact, still readable, and has more possibilities in the future. Personally like this. @vcjmhg thoughts?

**Comment by vcjmhg** [comment]
> It looks like the `structure` proposal is better, less performance impact, still readable, and has more possibilities in the future. Personally like this. @vcjmhg thoughts?

Yes, I also agree that `structured` proposla seems better
