### ISSUE TITLE
Is there a plan to support DM7 or DM8

### ISSUE THREAD

**Issue by MrSiLu** [apache/skywalking#5864]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___

### Requirement or improvement
- Excuse me, do we have plans to support DM DBA, thanks.

**Comment by wu-sheng** [comment]
What is the DM?

**Comment by MrSiLu** [comment]
A database

**Comment by wu-sheng** [comment]
Could you provide more information? You are giving very few word about your context.

**Comment by MrSiLu** [comment]
Sorry , I didn't make it clear .
DM is a database , like oracle . But DM was designed by the Chinese . 
so some projects need use DM.
I want one Java agent plugin extensions for  DM , like oracle-10.x-plugin . 
thanks again

**Comment by wu-sheng** [comment]
As an open source project, we don't have any interest or plan to work on the commercial database. Also, you should understand, all plugins of SkyWalking come from contributors all over the world. We don't assign any task to anyone, they are volunteers to do what they want to do.

As far as I know, no one works on a DB called DM. We have provided the full plugin development documentation, you could follow that to build the plugin on your own.

**Comment by MrSiLu** [comment]
OK , I will try to build the plugin by myself . Thanks again .

**Comment by 958123835** [comment]
> Sorry , I didn't make it clear .
> DM is a database , like oracle . But DM was designed by the Chinese .
> so some projects need use DM.
> I want one Java agent plugin extensions for DM , like oracle-10.x-plugin .
> thanks again

这块的封装,参照了mysql和oracle和sqlserver都行不通呢，这块达梦数据库是否有什么限制呢
