### ISSUE TITLE
[Python]  Not getting db data while using pymysql or pymongo inside flask server

### ISSUE THREAD

**Issue by rohan2546** [apache/skywalking#5865]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Using flask v 1.1.2
in the same project, using pymysql to fetch data
SW8.2.0
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

Code 👍 
```
import datetime
import pymysql.cursors
import json
from flask import Flask, render_template, request, url_for, redirect, abort, jsonify, make_response
from flask_cors import CORS, cross_origin
from bson import json_util
from bson.json_util import dumps,ObjectId
import random
from skywalking import agent, config
from skywalking.decorators import trace
from skywalking import Component,Layer,config,plugins
from skywalking.trace.context import SpanContext, get_context
from skywalking.trace.tags import Tag



config.service_name = 'service5'
#config.init(collector='127.0.0.1:11800', service='service4')
config.logging_level = 'DEBUG'
config.mysql_trace_sql_parameters = True
agent.start()
app=Flask(__name__)




@app.route('/getDoctor',methods=['GET','OPTIONS'])
@cross_origin(origin='*',headers=['Content-Type','Authorization'])
def addProblem():
  if request.method == 'GET':
    context: SpanContext = get_context() 
    connection = pymysql.connect(
    host="localhost",
    user="root",
    password="mypwd",
    database="hospital_db")
    with connection.cursor() as cursor:
      sql = "SELECT `*` FROM `doctors`"
      cursor.execute(sql)
      result = cursor.fetchone()
    connection.close()
    a= ''
    for x in result:
      a=a+str(x)
    return a,201
    # return myresult,201

if __name__ == '__main__':
  app.run(debug=True)
```

Db is not getting registered and trace doesn't contain db calls as in Java
<img width="1061" alt="ab" src="https://user-images.githubusercontent.com/31701608/99659347-c1c79980-2a86-11eb-90b3-a3fa07dc4bc6.png">

**Comment by wu-sheng** [comment]
Please update the title

**Comment by alonelaval** [comment]
You need to know the order in which python modules are loaded. @rohan2546 

![image](https://user-images.githubusercontent.com/1763449/99675957-d588f500-2ab2-11eb-8563-0bfd2a841db1.png)

`import pymysql.cursors
from flask import Flask, request

from skywalking import agent, config
from skywalking.trace.context import SpanContext, get_context
app=Flask(__name__)

@app.route('/getDoctor',methods=['GET','OPTIONS'])
def addProblem():
    if request.method == 'GET':
        context: SpanContext = get_context()
        connection = pymysql.connect(
            host="localhost",
            user="root",
            password="root123",
            database="test")
        with connection.cursor() as cursor:
            sql = "SELECT `*` FROM `doctors`"
            cursor.execute(sql)
            result = cursor.fetchone()
        connection.close()
        a= ''
        for x in result:
            a=a+str(x)
        return a,201
        # return myresult,201

if __name__ == '__main__':
    config.service_name = 'service5'
    config.logging_level = 'DEBUG'
    config.mysql_trace_sql_parameters = True
    agent.start()
    app.run(debug=True,port=8999)`

**Comment by rohan2546** [comment]
The same code is not showing database in my local

**Comment by kezhenxu94** [comment]
> The same code is not showing database in my local

The codes @alonelaval pasted work for me, please provide more context/information if it doesn't work at your side, e.g. how you tested it, what's the actual results, etc. Simply saying "it doesn't work" is not helpful

![image](https://user-images.githubusercontent.com/15965696/99751211-b3c45800-2b1c-11eb-9e88-8966db7c00ab.png)

**Comment by kezhenxu94** [comment]
Also, I noticed that your SQL is 

```sql
SELECT `*` FROM `doctors`
```

FWIK, `*` doesn't need the backticks if you want to query all fields

```diff
- SELECT `*` FROM `doctors`
+ SELECT * FROM `doctors`
```

**Comment by rohan2546** [comment]
skywalking.agent.protocol.grpc   [Thread-2       ] [DEBUG   ] grpc channel connectivity changed, [None -> ChannelConnectivity.IDLE]
skywalking.agent.protocol.grpc   [Thread-3       ] [DEBUG   ] grpc channel connectivity changed, [ChannelConnectivity.IDLE -> ChannelConnectivity.CONNECTING]
skywalking.plugins               [MainThread     ] [DEBUG   ] installing plugin sw_http_server
skywalking.agent.protocol.grpc   [Thread-4       ] [DEBUG   ] grpc channel connectivity changed, [ChannelConnectivity.CONNECTING -> ChannelConnectivity.READY]
skywalking.plugins               [MainThread     ] [DEBUG   ] installing plugin sw_requests
skywalking.plugins               [MainThread     ] [DEBUG   ] installing plugin sw_urllib_request
skywalking.client.grpc           [HeartbeatThread] [DEBUG   ] service heart beats, [service1], [923abb5e2ade11eba0bcdca904830e44]
 * Serving Flask app "example2" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
werkzeug                         [MainThread     ] [INFO    ]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
werkzeug                         [MainThread     ] [INFO    ]  * Restarting with stat
skywalking.agent.protocol.grpc   [Thread-2       ] [DEBUG   ] grpc channel connectivity changed, [None -> ChannelConnectivity.IDLE]
skywalking.plugins               [MainThread     ] [DEBUG   ] installing plugin sw_http_server
skywalking.agent.protocol.grpc   [Thread-2       ] [DEBUG   ] grpc channel connectivity changed, [ChannelConnectivity.IDLE -> ChannelConnectivity.CONNECTING]
skywalking.plugins               [MainThread     ] [DEBUG   ] installing plugin sw_requests
skywalking.agent.protocol.grpc   [Thread-3       ] [DEBUG   ] grpc channel connectivity changed, [ChannelConnectivity.CONNECTING -> ChannelConnectivity.READY]
skywalking.plugins               [MainThread     ] [DEBUG   ] installing plugin sw_urllib_request
skywalking.client.grpc           [HeartbeatThread] [DEBUG   ] service heart beats, [service1], [9366e9bc2ade11ebaa9edca904830e44]
werkzeug                         [MainThread     ] [WARNING ]  * Debugger is active!
werkzeug                         [MainThread     ] [INFO    ]  * Debugger PIN: 235-266-699
skywalking.client.grpc           [HeartbeatThread] [DEBUG   ] service heart beats, [service1], [923abb5e2ade11eba0bcdca904830e44]
skywalking.client.grpc           [HeartbeatThread] [DEBUG   ] service heart beats, [service1], [9366e9bc2ade11ebaa9edca904830e44]
werkzeug                         [Thread-6       ] [INFO    ] 127.0.0.1 - - [20/Nov/2020 08:45:45] "GET /getDoctor HTTP/1.1" 201 -
skywalking.agent.protocol.grpc   [Thread-4       ] [DEBUG   ] reporting segment Segment@4490400960[segment_id=adcc81ea2ade11ebaa9edca904830e44, spans=[<skywalking.trace.span.EntrySpan object at 0x10ba616a0>], timestamp=1605842145190, related_traces=[<skywalking.trace.ID object at 0x10ba616d0>]]
werkzeug                         [Thread-7       ] [INFO    ] 127.0.0.1 - - [20/Nov/2020 08:45:46] "GET /getDoctor HTTP/1.1" 201 -
skywalking.agent.protocol.grpc   [Thread-4       ] [DEBUG   ] reporting segment Segment@4490401728[segment_id=ae7cc85c2ade11ebaa9edca904830e44, spans=[<skywalking.trace.span.EntrySpan object at 0x10ba61970>], timestamp=1605842146345, related_traces=[<skywalking.trace.ID object at 0x10ba61940>]]
skywalking.client.grpc           [HeartbeatThread] [DEBUG   ] service heart beats, [service1], [923abb5e2ade11eba0bcdca904830e44]
skywalking.client.grpc           [HeartbeatThread] [DEBUG   ] service heart beats, [service1], [9366e9bc2ade11ebaa9edca904830e44]

Logs for my code

**Comment by kezhenxu94** [comment]
> I don't know why plugin sw_pymysql not getting installed

From the logs, seems you only have very limited plugins installed. Which version are you using? How did you install skywalking-python agent. Please make sure you're using the latest available version, some plugins are not added until a specific version
