### ISSUE TITLE
If bean with a complex structure  Spring-annotation-plugin will produces an exception

### ISSUE THREAD

**Issue by janecms** [apache/skywalking#5869]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug

___
___
### Bug
- Which version of SkyWalking, OS and JRE?
   JDK8
  sky 8.1.0
- Which company or project?

- What happened?
I introduced Spring-annotation-plugin in the project， which caused the project that started normally to fail to start。
Reason for error code
`
public abstract class BaseConsumer<T extends TagAction> implements TagConsumer<T> {

    protected Class<T> clazz;

    @Autowired
    TagGenerateService tagGenerateService;

    public TagBaseConsumer() {
        Class clazz = this.getClass();
        Type[] genericInterfaces = clazz.getGenericInterfaces();
        Type genericType;
        if (genericInterfaces.length == 1) {
            //分析接口 泛型定义
            genericType = genericInterfaces[0];
        } else {
            //分析父类 泛型定义
            genericType = clazz.getGenericSuperclass();
        }
        try {
            if (genericType instanceof ParameterizedType) {
                Type actualTypeArguments = ((ParameterizedType) genericType)
                    .getActualTypeArguments()[0];
                Class actualTypeClass = Class.forName(actualTypeArguments.getTypeName());
                this.clazz = actualTypeClass;
            }
        } catch (ClassNotFoundException e) {
            log.error("初始化环境失败", e);
            throw new RuntimeException("初始化环境失败");
        }

    }

     ...
`
our clazz attribute can not be initialized.

The Second Issue
In spring cloud  gateway，The plugin did not embed the method。

Thanks 
___

**Comment by wu-sheng** [comment]
Have you checked the plugin codes and found out why? The private codes have countless ways, which we may not aware and cover right now. I prefer you could locate the cause first. We can't debug your private codes.
