### ISSUE TITLE
The Design of Skywalking Satellite

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#5871]
The issue is to discuss the design of the Skywalking Satellite.
doc: https://docs.google.com/document/d/1RB5EXyX9k63QabSpaWLZvN5JQ4NoNgGIH1t8LMt6Bys/edit#heading=h.o1c72xcxm0n7

**Comment by EvanLjp** [comment]
https://meeting.tencent.com/s/UVDuHxyYUmrc

**Comment by EvanLjp** [comment]
**2020-11-23 Review**
**Questions & Discussion:**

1. How to support the http receiver?
2. What are the strategies for file creation and deletion?
3. What is the detail of the committed offset?
4. Put the offsets of the batch data into FlyingChannel rather than a copy.
5. SLO of the resources.
6. How about reusing files in Queue?
7. Daemonset Or Sidecar ?
8. Whether indexing files will cost more resources?

**Comment by EvanLjp** [comment]
The new doc: https://docs.google.com/document/d/14iy7x_vh5OTkpwCBgqaBXMz6LWDCksJO38KJ-KF4KxY/edit#

**Comment by EvanLjp** [comment]
Satellite LightWeight Design Meeting: https://meeting.tencent.com/s/SGe0rVkqvOR0 we would have an online discussion on 2020-11-25 15:00(+8:00). Thx for joining it.

**Comment by wu-sheng** [comment]
Design doc has been published publicly, http://skywalking.apache.org/blog/2020-11-25-skywalking-satellite-0.1.0-design/
