### ISSUE TITLE
Can't get NodeJS agent test to run

### ISSUE THREAD

**Issue by tom-pytel** [apache/skywalking#5875]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

After doing everything I think I need to do I try to run the NodeJS agent test and I get the following:
```
> skywalking@0.0.1 test /home/tom/src/skywalking-nodejs
> mocha -r ts-node/register 'tests/**/test.ts'



  
Creating network "http_traveling-light" with the default driver
Building server
Step 1/5 : FROM nodejs-dependencies
    ✓ test /home/tom/src/skywalking-nodejs/tests/plugins/http
Service 'server' failed to build: pull access denied for nodejs-dependencies, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Removing network http_traveling-light


  1 passing (4s)
```
Where is nodejs-dependencies supposed to come from and what am I missing?

[edit]
P.S. What is the current state of the NodeJS agent, is it considered working? I find it only kind-of sometimes works for me.

**Comment by kezhenxu94** [comment]
Thanks for reporting this. The test codes were tested locally only, I’ve fixed them now and will set up GHA workflows to verify soon

**Comment by wu-sheng** [comment]
Hi, remind you, if you two plan to finish the nodejs repo and run the release, don't forget to add the repo at the website, http://skywalking.apache.org/docs/.

**Comment by kezhenxu94** [comment]
The tests should be fixed after https://github.com/apache/skywalking-nodejs/pull/1

> P.S. What is the current state of the NodeJS agent, is it considered working? I find it only kind-of sometimes works for me.

It only worked for some scenarios, after https://github.com/apache/skywalking-nodejs/pull/1, it's expected to cover more scenarios, yet I don't suggest to write your own plugin for now, since the docs are not provided and the core codes are not settled down and may change in the following days, I'd like to feed myself the dog food by writing several plugins and make the core codes and docs ready, feel free to provide more negative scenarios that it didn't covered, thanks very much.

**Comment by tom-pytel** [comment]
Actually the problem in the agent seems to be that it is not dealing properly with the asynchronous nature of Javascript. I am pretty sure I can fix this, just tell me if you want me to push to master or a separate branch?

**Comment by kezhenxu94** [comment]
> Actually the problem in the agent seems to be that it is not dealing properly with the asynchronous nature of Javascript. I am pretty sure I can fix this, just tell me if you want me to push to master or a separate branch?

can you pull the latest codes and work based on that, then open a pull request?

**Comment by kezhenxu94** [comment]
I have set up the tests there, so that you can verify your works easily

**Comment by tom-pytel** [comment]
You mean the stabilize branch or master?

**Comment by tom-pytel** [comment]
Looking at the stabilize branch it seems to attempt to deal with asynchronous stuff but it does not seem to be doing it in a way that will work, I replace that with a completely general mechanism anyway so if you want me to use stabilize for the async stuff there then it is better I go from master.

**Comment by tom-pytel** [comment]
Or I can do the async mechanism in master which I already started and you could merge it into stabilize since you are more familiar with the code?

**Comment by kezhenxu94** [comment]
@tom-pytel it is ok to go from the master

**Comment by kezhenxu94** [comment]
@tom-pytel this specific issue is fixed by https://github.com/apache/skywalking-nodejs/pull/1 feel free to open another issue/PR for other discussions
