### ISSUE TITLE
Broken DOAP link

### ISSUE THREAD

**Issue by sebbASF** [apache/skywalking#5876]
The DOAP has gone missing:

URL: http://skywalking.apache.org/assets/doap_SkyWalking.rdf
HTTP Error 404: Not Found
Source: https://svn.apache.org/repos/asf/comdev/projects.apache.org/trunk/data/projects.xml

Please either restore the DOAP or update the projects.xml file

**Comment by wu-sheng** [comment]
I will restore it tomorrow.
