### ISSUE TITLE
Multiple duplicate services are found on the Rockbot.

### ISSUE THREAD

**Issue by JHub-Wei** [apache/skywalking#5877]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [y ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why duplicate service names are found on the Rockbot andthey don't have endpoints？
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking8.1.0，JRE1.8
- Which company or project?

**Comment by wu-sheng** [comment]
I think there are issues we discussed this. Please search before submitting a new one.
