### ISSUE TITLE
Does the sw8-corrlation header vlaues should be add to tracing span and uploaded to oap backend

### ISSUE THREAD

**Issue by snakorse** [apache/skywalking#5878]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- One question about the [Skywalking-Cross-Process-Correlation-Headers-Protocol](https://github.com/apache/skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Correlation-Headers-Protocol-v1.md)：does the key-value pairs included in the sw8-corrlation header should be add to tracing span and uploaded to oap backend automatically by the agent?

**Comment by wu-sheng** [comment]
It depends. The java agent provides the optional feature. Read `correlation.auto_tag_keys` here, should be clear for you, https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#table-of-agent-configuration-properties
