### ISSUE TITLE
please share detail step about integration with jaeger

### ISSUE THREAD

**Issue by haboy52581** [apache/skywalking#5882]
please share detail step about integration with jaeger, skywalk agent plus what version of jaeger

**Comment by wu-sheng** [comment]
It is just an experimental feature. Don't recommend end user to try.

**Comment by haboy52581** [comment]
but can we try the experimental feature

**Comment by wu-sheng** [comment]
If you want that, check and try that as a developer. We don't touch those codes for a long time.

**Comment by haboy52581** [comment]
thanks, but how to enable opentracing feature in skywalking and combined with popular opentracing tools in skywalking?

**Comment by wu-sheng** [comment]
I think I have explained this very clearly in the other issue you submitted. **We(SkyWalking community) is never `built on` or `for` OT in any case. We provided a bridge, no one wants to follow up, that is all.**
