### ISSUE TITLE
what's the largest scale and latency for micro services now skywalking used?

### ISSUE THREAD

**Issue by haboy52581** [apache/skywalking#5883]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by haboy52581** [comment]
what's the largest scale and latency for micro services now skywalking used?

**Comment by wu-sheng** [comment]
This is unreasonable question. How could we know that. As an open source community, we can't and shouldn't touch users env, and product data, which are user privacy.

**Comment by haboy52581** [comment]
sorry, i mean is there any successful example about large scale skywalking

**Comment by wu-sheng** [comment]
We have this, https://skywalking.apache.org/blog/2020-08-11-observability-at-scale/

**Comment by haboy52581** [comment]
thanks, this is what I need! do we have benchmark saying for what kind of computing resource to support the amount of tracing or number of java micro services so that we could extend it horizontally

**Comment by wu-sheng** [comment]
Do your own research rather than just asking. Your research and your conclusion should not depend on us.
