### ISSUE TITLE
how to enable opentracing feature and combined with popular opentracing tools in skywalking

### ISSUE THREAD

**Issue by haboy52581** [apache/skywalking#5884]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean popular opentracing tool in SkyWalking? We don't have concepts like that.

**Comment by haboy52581** [comment]
sorry my bad, i mean since skywalking claims support for open tracing , is there any integration example for skywalking agent plus opentracing server except skywalking collector like jaeger or other stuff?

**Comment by wu-sheng** [comment]
Simple answer, we don't. We don't say we support ot without condition. If you want Jaeger ecosystem, go to their repo please. It doesn't make sense to keep asking here about another project. It is their responsibility, not ours.

**Comment by haboy52581** [comment]
sorry and thanks for your quick feedback!
personally I like skywalking very much but needs some comparison about other system, for now I am using 6.6 since 8.x not working on my env complaining collector not up and try figuring out can skywalking support over hundred microservices with heavy payload. 
The reason I am asking jaeger is what they claimed good support about k8s in the doc but I never succeeded following it.
Btw is the java agent universal for all ( zipkin etc, collector)

**Comment by wu-sheng** [comment]
2 things, one, 6 is not recommended. And most users have upgraded to 8 as it has much better performance and more maintainability. Then, Jeager and Zipkim have their communities and ecosystems, both of them are not SkyWalking responsibility anyway, no matter tech itself. The open source projects are driven by their contributors, currently, we don't have people working on that.Also, we can't tell others performance, as they are not experts about them.

**Comment by haboy52581** [comment]
thanks and I found this https://github.com/SkyAPMTest/Agent-Benchmarks, hope it helps!
also I am thinking about since open tracing is just a spec that means technically everybody following same format should be able to communicate with each other

**Comment by wu-sheng** [comment]
No, it isn't a spec. It never is. I am a member of open tracing, trust me, it is far from a spec. OpenTracing actually is being merged into OpenTelemetry, very little people use it than you thought. Please don't read a doc and believe it. Do some research before have conclusion. 
More importantly, OpenTracing doesn't have format, never, it is just an API layer. Read the thing and understand the thing you bring up.

**Comment by wu-sheng** [comment]
We wouldn't and shouldn't continue on talking a thing doesn't relate and matter to SkyWalking much.
