### ISSUE TITLE
[CLI] Incorrect instance and enpoint level query implementation

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5890]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
![image](https://user-images.githubusercontent.com/5441976/100191819-c29b7800-2f2b-11eb-8109-ce3f3c58ac40.png)

This bug is detected, which starts with the discussion here, https://github.com/apache/skywalking-swck/pull/12#discussion_r530091651. The current implementation of linear(maybe more) query, doesn't adopt/use the correct parameters.

We should provide separate parameters for instance and endpoint names, with `isNormal` flag, which could be used in conjecture services.

@fgksgf Let's fix this and call for 0.5.0 release. Note, #4466 should follow this when you implement those queries.

**Comment by fgksgf** [comment]
@wu-sheng 
I added a bool flag named `unnormal`, it's not required. Because the default value of `normal` is `true`.
If we create a `isNormal` flag, we probably have to add this flag most of the time.
What do you think ？

**Comment by wu-sheng** [comment]
> I added a bool flag named unnormal, it's not required. Because the default value of bool is true.
If we create a isNormal flag, we probably have to add this flag most of the time.
What do you think ？

I think this is only coding style. You could give the parameter `true` if no input parameter. Right? `unnormal` is anti-protocol, which should not be recommended.

**Comment by kezhenxu94** [comment]
> > I added a bool flag named unnormal, it's not required. Because the default value of bool is true.
> > If we create a isNormal flag, we probably have to add this flag most of the time.
> > What do you think ？
> 
> I think this is only coding style. You could give the parameter `true` if no input parameter. Right? `unnormal` is anti-protocol, which should not be recommended.

+1, @fgksgf make `isNormal` type of string, and give it default value `true`, and validate that it should be either `true` or `false`

**Comment by fgksgf** [comment]
Make sense to me
