### ISSUE TITLE
skywalking-agent 8.2 NullPointException when mysql update

### ISSUE THREAD

**Issue by chenting123** [apache/skywalking#5892]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [Question ] Question or discussion
- [ Bug ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking-agent 8.2 NullPointException
![image](https://user-images.githubusercontent.com/18435220/100203095-20848b80-2f3d-11eb-8ad2-7dcde89fc73f.png)

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Check your codes with our tested demo, including versions, https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/mysql-scenario.
