### ISSUE TITLE
Class JDK9ModuleExporter has incomplete comment

### ISSUE THREAD

**Issue by Shuang-Han** [apache/skywalking#5893]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
Comments in class org.apache.skywalking.apm.agent.core.plugin.jdk9module.JDK9ModuleExporter as below

```
   /**
      * Since JDK 9, module concept has been introduced. By supporting that, agent core needs to open the
      */
```

open what ?

**Comment by wu-sheng** [comment]
Are you reading the right codes? https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/jdk9module/JDK9ModuleExporter.java#L30

**Comment by Shuang-Han** [comment]
in v8.2.0 release, it is missing

**Comment by wu-sheng** [comment]
Yes, it was and fixed.
