### ISSUE TITLE
How  to use version_8.2.0   Web Browser Collects Data

### ISSUE THREAD

**Issue by huazhanghui007** [apache/skywalking#5902]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [Question ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Why are you keeping submitting duplicate issue? Search first.
