### ISSUE TITLE
Spring cloud gateway project logback cannot print TraceID

### ISSUE THREAD

**Issue by ldy** [apache/skywalking#5906]
### Question
below is my project lib version：
SpringBoot：2.1.4.RELEASE，Spring Cloud Gateway：2.1.2，apm-toolkit-logback-1.x：6.5.0，Skywalking：8.2.0

In gateway service，i can print the tid in my code when i use ```String traceId = TraceContext.traceId();```,but logback cannot print tid,only show ```[TID:N/A]```.
In other service，logback can also print tid normal.
what can i do to let logback to print tid normal in gateway service?

![QQ图片20201126205646](https://user-images.githubusercontent.com/12880699/100354846-beef1a80-302b-11eb-9e42-7fba24e2bf55.jpg)

**Comment by wu-sheng** [comment]
Could you share your gateway codes, including settings with a package? We need to reproduce what is going on.

**Comment by ldy** [comment]
Sorry take too long to give a reply.Please see the demo in [Spring Cloud Gateway Demo](https://github.com/ldy/demo).

Below is new project lib version：
`SpringBoot：2.3.1.RELEASE，Spring Cloud:Hoxton.SR8，Spring Cloud Gateway：2.2.5，apm-toolkit-logback-1.x：6.6.0，Skywalking：8.2.0`

There are three situation：

First，when use default netty container，in gateway service，i can't print tid on console，only show [TID:N/A].In other service，logback can print tid normal.
![tomcat](https://user-images.githubusercontent.com/12880699/101053563-e3ff0280-35c2-11eb-9f5e-14762b329c18.png)

Second，when use tomcat container，in gateway service，i can print the tid in my code when i use `String traceId = TraceContext.traceId();`，but in response filter logback partly cannot print tid，only show [TID:N/A].In other service，logback can print tid normal.
![Uploading tomcat-pom.png…]()
![tomcat2](https://user-images.githubusercontent.com/12880699/101054943-6805ba00-35c4-11eb-9e4b-27bf09642001.png)


Thirdly，when use  jetty container，in gateway service，i can print the tid in my code when i use `String traceId = TraceContext.traceId();`，but in response filter logback partly cannot print tid，only show [TID:N/A].In other service，logback can print tid normal.
![Uploading jetty-pom.png…]()
![jetty2](https://user-images.githubusercontent.com/12880699/101054947-689e5080-35c4-11eb-82e7-34c2896f5526.png)

**Comment by wu-sheng** [comment]
First but not maybe not the cause, don't use 6.x toolkit. Use 8.x.

**Comment by wu-sheng** [comment]
And, I think for the traceid injection, it depends on whether the current thread has been tracing. This is not 100% guarantee

**Comment by ldy** [comment]
apm-toolkit-logback-1.x use 8.x get the same conclusion
https://github.com/apache/skywalking/issues/5906#issuecomment-738481281

**Comment by starboyate** [comment]
@ldy If you use the default plugin or have imported gateway related plugins ，spring-cloud-gateway（reactor-netty） cannot print traceId，this is because these plugins are all in beforeMethod and delete trace. If you want to print that traceId，you can import spring-annotation-plugin，but this cannot solve the problem that your logback traceId in ResponseBobyGatewayFilter cannot be printed，because you are an asynchronous callback method.
![image](https://user-images.githubusercontent.com/40192576/101980550-2a2e2300-3ca1-11eb-8faf-a6f35bb3a58f.png)

**Comment by wu-sheng** [comment]
Yes, if you have new plugin installed, we don't support for now. I removed the bug tag. Encourage the community to contribute the enhancement.

**Comment by billytomato** [comment]
how to fix this.or any idea to fix.

**Comment by libing08** [comment]
> @ldy If you use the default plugin or have imported gateway related plugins ，spring-cloud-gateway（reactor-netty） cannot print traceId，this is because these plugins are all in beforeMethod and delete trace. If you want to print that traceId，you can import spring-annotation-plugin，but this cannot solve the problem that your logback traceId in ResponseBobyGatewayFilter cannot be printed，because you are an asynchronous callback method.
> ![image](https://user-images.githubusercontent.com/40192576/101980550-2a2e2300-3ca1-11eb-8faf-a6f35bb3a58f.png)

if in aop don't print traceid，import spring-annotation-plugin can fix it. 
thanks offer ideas like this!

**Comment by DiscoverCZY** [comment]
> @ldy If you use the default plugin or have imported gateway related plugins ，spring-cloud-gateway（reactor-netty） cannot print traceId，this is because these plugins are all in beforeMethod and delete trace. If you want to print that traceId，you can import spring-annotation-plugin，but this cannot solve the problem that your logback traceId in ResponseBobyGatewayFilter cannot be printed，because you are an asynchronous callback method. ![image](https://user-images.githubusercontent.com/40192576/101980550-2a2e2300-3ca1-11eb-8faf-a6f35bb3a58f.png)

use the FunctionWrapper which under the apm-toolkit-trace lib, it looks like can fix the asynchronous callback missing the trace id problem.

**Comment by babyshy** [comment]
so, how to resolve this problem?

**Comment by DanielJefferson1990** [comment]
how about this issue? @ascrutae @wu-sheng

**Comment by zjls007** [comment]
搞定了吗，怎么就是打印不了traceID啊

**Comment by hnsongbiao** [comment]
how to resolve this problem?

**Comment by BothSavage** [comment]
> so, how to resolve this problem?

https://bothsavage.github.io/article/240121-skywaking

**Comment by BothSavage** [comment]
> how to resolve this problem?

https://bothsavage.github.io/article/240121-skywaking
