### ISSUE TITLE
I have a question about kafka

### ISSUE THREAD

**Issue by YczYanchengzhe** [apache/skywalking#5909]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hello, we are currently using skywalking for system monitoring, but because the amount of data reported by the agent is relatively large, we plan to connect to Kafka for data collection, but skywalking supports the agent to write directly to Kafka's topic by default. There are a lot of connect . Kafka limits the maximum number of connections to 100, and too many connections will also affect the performance of Kafka. So we thought of two design solutions, I hope you can help evaluate which solution is more suitable for future expansion and our applications Scenes .
Figure 1 below is the current skywalking architecture. In the first solution, we plan to add a layer of kafka between oap and es. When writing, instead of writing to es, write to kafka, and then build a consumer to consume kafka to write Enter es, as shown in Figure 2. In the second scheme, we plan to add a layer of kafka producer between agent and oap, and the work is mainly to collect agent data and forward it to kafka.
Hope to get your suggestions, thank you very much!

> ___
![wtrace-kafka](https://user-images.githubusercontent.com/45945752/100404332-1a58f100-309c-11eb-9c0b-c61cad35050d.png)

### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> we plan to add a layer of kafka between oap and es. When writing, instead of writing to es,

This would cause the risk you have inaccurate data.

> In the second scheme, we plan to add a layer of kafka producer between agent and oap, and the work is mainly to collect agent data and forward it to kafka.

Are you saying adding a layer between agent and Kafka? What you described is today's status, so I am guessing. If I guess correctly, read https://github.com/apache/skywalking-satellite

**Comment by YczYanchengzhe** [comment]
I'm sorry to bother you again. What do you mean by the data inaccuracy that you said may cause? Because I understand that the data written into es after the calculation of oap should be the real data queried by the web side during query Now, is there some problem with my understanding of the data? Is the data aggregated again when it is queried? The reason why it may be inaccurate is because some of the data that needs to be aggregated may not be consumed in Kafka? Hope Get your answer, thank you very much!

**Comment by wu-sheng** [comment]
> Because I understand that the data written into es after the calculation of oap should be the real data queried by the web side during query. Now, is there some problem with my understanding of the data? 

That is not all. You could read codes to learn more, the basic module is `read->aggregation->write`.

**Comment by YczYanchengzhe** [comment]
Thank you very much for your answers, I will look at the code to learn more about it
