### ISSUE TITLE
How can Redis be recoginzed as a Database?

### ISSUE THREAD

**Issue by Lynda-Li** [apache/skywalking#5910]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] 

- [ ] Question or discussion

- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How can Redis be recoginzed as a Database?  So we can see it in the Database Dashboard.
___
### Bug
- Which version of SkyWalking, OS and JRE?
8.1.0, Linux, JDK1.8

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The simple answer is, it isn't a database. It is only a cache.

**Comment by holtenko** [comment]
I think what you want to know is how can Redis be shown in the Dashboard.
