### ISSUE TITLE
Nothing can be queried by the tag in version 8.2.0

### ISSUE THREAD

**Issue by GuiSong01** [apache/skywalking#5912]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug

- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
8.2.0-es7
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
Nothing can be queried by the tag when I use UI.
![image](https://user-images.githubusercontent.com/18419834/100427535-90298080-30cd-11eb-969e-b6af257e1daf.png)
I'm sure there is a trace with tag "http.method=GET"
![image](https://user-images.githubusercontent.com/18419834/100427756-e696bf00-30cd-11eb-8778-1e8bfc6e378c.png)
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Just rechecked on the demo env.

![image](https://user-images.githubusercontent.com/5441976/100427977-442b0b80-30ce-11eb-8ff2-db3eb03db1c9.png)

**Comment by GuiSong01** [comment]
Default value of searchableTracesTags contains key "http.method", I add ENV SW_SEARCHABLE_TAG_KEYS on the skywalking-oap-server and skywalking-ui, SW_SEARCHABLE_TAG_KEYS  contains default keys and my custom keys. But I still could  not query anything by tags.

request payload:
![image](https://user-images.githubusercontent.com/18419834/100491725-00351680-3161-11eb-8fa9-a2bc0ca4454e.png)

data in es:
![image](https://user-images.githubusercontent.com/18419834/100491833-bf89cd00-3161-11eb-8a33-3ce4919f8825.png)

env in container:
![image](https://user-images.githubusercontent.com/18419834/100492071-ef39d480-3163-11eb-8a02-00143954953f.png)

**Comment by wu-sheng** [comment]
I am not sure what is your status. Recommend to debug locally or try latest codes.
