### ISSUE TITLE
【qustion】 es storage with https

### ISSUE THREAD

**Issue by yangvipguang** [apache/skywalking#5913]
Version：
ES: 7.10
Skywalking： 8.2
Deployment： skywalking-helm 4.0

How could i configure es as storage with https access ？
![image](https://user-images.githubusercontent.com/11416887/100428210-99671d00-30ce-11eb-8803-8c6c0e26421e.png)

![image](https://user-images.githubusercontent.com/11416887/100428341-c3b8da80-30ce-11eb-9671-979d4daf1cb1.png)

Tips： Jaeger has options to configure this 。

**Comment by wu-sheng** [comment]
Read this, https://github.com/apache/skywalking/blob/v8.2.0/docs/en/setup/backend/backend-setup.md#configuration-vocabulary

![image](https://user-images.githubusercontent.com/5441976/100428819-683b1c80-30cf-11eb-8b4a-9e235eb8fbaa.png)

**Comment by yangvipguang** [comment]
@wu-sheng   how about the configuration in the values  of helm 
![image](https://user-images.githubusercontent.com/11416887/100429272-0d55f500-30d0-11eb-9350-639c37823f4a.png)

**Comment by wu-sheng** [comment]
The doc gives you the system env variable names. The helm opened those to you.

**Comment by yangvipguang** [comment]
@wu-sheng  But If I use env to pass SSL cert ?
 trustStorePath: ${SW_SW_STORAGE_ES_SSL_JKS_PATH:""}
 trustStorePass: ${SW_SW_STORAGE_ES_SSL_JKS_PASS:""}

1、the format of trustedStore is  jks instead of  cert  format 。
2、should I put ssl cert to  oap files with volumemount  to use it？
![image](https://user-images.githubusercontent.com/11416887/100495066-b9581880-3182-11eb-9548-cb23ba50042f.png)

**Comment by wu-sheng** [comment]
Yes, you need a file system to host files.

**Comment by yangvipguang** [comment]
@wu-sheng   I have tried But i have a suggestion:
jks is a binary file ，so，putting the file  into  oap files，helm install will produce error because of no UTF-8 file。
![image](https://user-images.githubusercontent.com/11416887/100496397-c844c800-318e-11eb-9a22-bce300051699.png)
I suggest add a configmap with binarydata type  for storing jks file， or just through ca format ssl file.

**Comment by kezhenxu94** [comment]
@yangvipguang can you try this? https://github.com/apache/skywalking-kubernetes/pull/63

**Comment by wu-sheng** [comment]
FYI @kezhenxu94 I just fixed the wrong milestone of this.
