### ISSUE TITLE
print warn log very fast

### ISSUE THREAD

**Issue by zender-projects** [apache/skywalking#5924]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
configuration with apollo and skywalking-oap-server.log contains the logs :
'Pick up system reserved threshold 500ms because of config missing'

as the important , it print very fast , i find one answer of skywalking member, he say it can be ignore but the disk will full very fast.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
There should be a `service-apdex-threshold.yml` file in your `/config`, which would make the `warning` goes away. Which version are you using?

**Comment by zender-projects** [comment]
> There should be a `service-apdex-threshold.yml` file in your `/config`, which would make the `warning` goes away. Which version are you using?

i use 8.1.

the problem solved,  the reason is configuration's value of apollo wrong, the right way is :
key = core.default.apdexThreshold
value = default: 500

**Comment by ranxuxin001** [comment]
> There should be a `service-apdex-threshold.yml` file in your `/config`, which would make the `warning` goes away. Which version are you using?

hi @wu-sheng , I would like to use DCS dynamic configure to set apdex. Is my configuration in call function correct, please?

```
func (s *configServer) Call(ctx context.Context, req *pb.ConfigurationRequest) (*pb.ConfigurationResponse, error) {
	cfgTb := []*pb.Config{
		{
			Name:  "core.default.apdexThreshold",
			Value: "default: 3000 \nqewqw-test::myapmmysqlservice: 10000",
		},
		/*
			{
				Name:  "configuration-discovery.default.agentConfigurations",
				Value: "configurations:\n  qewqw-test::myapmmysqlservice:\n    agent.span_limit_per_segment: 300\n",
			},
		*/
	}
```

ps: qewqw-test::myapmmysqlservice is my service name.
