### ISSUE TITLE
Optimize the addition of TraceSegmentRef

### ISSUE THREAD

**Issue by starboyate** [apache/skywalking#5925]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Feature or performance improvement
___
### Question
when the extract() and continued() methods of TraceContext are called, TraceSegmentRef is created in the outer layer and then ref() is called to bind. If the corresponding TraceSegmentRef already exists, then no operation is done in the ref() method, here Will cause useless TraceSegmentRef object creation
___
### Requirement or improvement
I think some common fields of ContextCarrier and ContextSnapshot can be extracted and defined as the parent class, and then provide a method to create TraceSegmentRef based on the parent class. In the ref() method of TraceSegment, the parameter is defined as the parent class, and then the ref() method returns TraceSegmentRef for external use

**Comment by wu-sheng** [comment]
What do you mean `in the outer layer`? Could you make yourself clear? Do you mean without active running context?

**Comment by starboyate** [comment]
I mean that the corresponding tracesementref will be created in the extract() and continued() methods of tracingcontext, and then bound through the ref() method. However, if the tracesemmentref exists, then it will create a useless tracesemmentref object?

**Comment by wu-sheng** [comment]
What do you mean useless? Ref is designed to be created. I can't see your point.

**Comment by starboyate** [comment]
Maybe there is something wrong with what I described. I mean useless. That is, if there is a corresponding TraceSegmentRef in the LinkedList, the newly created TraceSegmentRef will not be added. This will create an object in the heap, but it will not be used
![image](https://user-images.githubusercontent.com/40192576/100586732-8c466a00-332a-11eb-933b-74a2b3704ab1.png)

**Comment by wu-sheng** [comment]
I am still not following. This method belongs to TraceSegment, which is owned by TracingContext. What is the issue?

**Comment by starboyate** [comment]
![image](https://user-images.githubusercontent.com/40192576/100587337-6372a480-332b-11eb-95b1-4a4558c27ed3.png)
![image](https://user-images.githubusercontent.com/40192576/100587353-67062b80-332b-11eb-96fb-8562f72c1504.png)
I just think it can save the extra creation of TraceSegmentRef object, because the created TraceSegmentRef object may already exist. If the corresponding TraceSegmentRef object already exists, there is no need to create it and then judge whether it exists, which will result in the creation of TraceSegmentRef It doesn't work because it already exists in the LinkedList

**Comment by wu-sheng** [comment]
Could you share the real use case? If you want to change source codes in your private usage, it is open to you. Feel free to do anything you like. In the upstream, I can't see the issue now.
