### ISSUE TITLE
How to skip kafka tracing?

### ISSUE THREAD

**Issue by 3838438abcd** [apache/skywalking#5927]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I'm coding a plugin which use kafka to produce metric，but it will be traced by apm-kafka-plugin.I want to know whether is there a way to avoid it?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Ignore yours or ignore all tracing of the Kafka plugin?

**Comment by 3838438abcd** [comment]
> Ignore yours or ignore all tracing of the Kafka plugin?

Just for the plugin of  mine,not for all tracing

**Comment by wu-sheng** [comment]
No, there is no such mechanism. Tracing means tracing all related. You can't partial OFF, because they are the same at the instrumentation level. The plugin can't tell who is using it.

**Comment by 3838438abcd** [comment]
> No, there is no such mechanism. Tracing means tracing all related. You can't partial OFF, because they are the same at the instrumentation level. The plugin can't tell who is using it.

Understand,thanks
