### ISSUE TITLE
I use the skywalking chart to deploy the skywalking on the k8s,but i get the system error.

### ISSUE THREAD

**Issue by xgy560501** [apache/skywalking#5928]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- I use the skywalking chart to deploy the skywalking on the k8s,but i get the system error.

___
### Bug
- Which version of SkyWalking, OS and JRE?
7.0.0
- Which company or project?
Shinho

- What happened?
  I use the skywalking chart and set the dynamicConfigEnabled to true, but the oap server doesn't work. Look at the error "no provider found for module configuration, if you're sure it's not required"

___
### Requirement or improvement
- I want to know how to use where and how to config the dynmiconfig to make the oap server reachable。

**Comment by wu-sheng** [comment]
Please learn how to use the system env to control `application.yml` first. This log usually means you don't set the correct provider. Dynamic configurations have multiple options, read the doc.

**Comment by xgy560501** [comment]
I need to config the alarm and it could not use the env to control.

**Comment by xgy560501** [comment]
serviceAccounts:
  oap:

oap:
  name: oap
  # When 'dynamicConfigEnabled' set to true, enable oap dynamic configuration through k8s configmap，
  # Note: The default configmap data is empty, please refer to the detailed documentation (https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/dynamic-config.md)
  # Sync period in seconds. Defaults to 60 seconds. env: SW_CONFIG_CONFIGMAP_PERIOD
  dynamicConfigEnabled: true
  image:
    repository: apache/skywalking-oap-server
    tag: 7.0.0-es7
    pullPolicy: IfNotPresent
  storageType: elasticsearch7
  ports:
    grpc: 11800
    rest: 12800
  replicas: 2
  service:
    type: ClusterIP

**Comment by xgy560501** [comment]
dynamicConfigEnabled: true
  image:
    repository: apache/skywalking-oap-server
    tag: 7.0.0-es7
    pullPolicy: IfNotPresent
  storageType: elasticsearch7
  ports:
    grpc: 11800
    rest: 12800
  replicas: 2
  service:
    type: ClusterIP

**Comment by wu-sheng** [comment]
> I need to config the alarm and it could not use the env to control.

Again, please read the documents about dynamic configuration and what `application.yml` means, including which system env variables controlling all there. Please don't guess.
