### ISSUE TITLE
bug with spring gateway 

### ISSUE THREAD

**Issue by huanglong2016** [apache/skywalking#5929]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [√ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SW :8.2.0
OS: window 10
JRE: 1.8.0_261
spring boot 2.3.4
spring gateway 2.2.0.RELEASE

- Which company or project?
(bsp) spring cloud project

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

![image](https://user-images.githubusercontent.com/17040991/100711878-dc860080-33ec-11eb-8866-611a955f86b1.png)
from the image ,the node "abnomal node" should not have appeared here。it was "interconnect" node.
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
All data will be removed after the TTL reached.
