### ISSUE TITLE
Contribute `baseline` computing module from jd.com

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#593]
We are glad to accept your contributions. As we told, this baseline computing module is from you private/internal APM system, this will help skywalking to provide more features. Thanks.

Here is my guideline:
1. The whole collector is based on modulization core. So I define a module for your team, named `baseline-computing`, and path is `/apm-collector/apm-collector-baseline/collector-baseline-computing-define`. You should define the baseline services, which represent as Java interfaces, like many rpc frameworks did. You should register them in module define through the return list of `ComputingModule#services`.
```java
    @Override public Class[] services() {
        return new Class[0];
    }
```
2. You need to provide a `provider` for this module, that is why I set up a provider, named `default`, and path is `/apm-collector/apm-collector-baseline/collector-baseline-computing-provider`.
3. Bind the services and implementations in `#prepare`, by using `#registerServiceImplementation`. The `serviceType` parameter should be the service, you defined in module, and the `service` parameter should be your implementation of the first parameter service.
4. Set the test cases about how to use the your services, and make sure the test coverage is over 80% in `provider` module.

And there are some attentions:
1. `check-sytle` works, so make sure you imported the style file, and ci passed.
1. License head is in `java.header` file, please make sure your IntelliJ preference setting is right. It should add the heads automatically.
1. Make sure @ustbsjl and @beforeeight set the github right.
1. Link your pull request to this issue.

Looking forward your pull request.

If you need any help, you know how to find me.

Thanks.
Skywalking PMC team.

**Comment by wu-sheng** [comment]
FYI @OpenSkywalking/pmc @OpenSkywalking/committer-team @OpenSkywalking/huawei-devcloud-contributor-team

**Comment by peng-yongsheng** [comment]
I care about the data structure of the services.

**Comment by peng-yongsheng** [comment]
@beforeeight 
Can you share some experience about the baseline?
1. Which metrics need to do baseline calculate.(application/instance/service 's error/response time/rate.... anything else?)
2. Which time duration? (every ? minute/hour/day)
3. How often need to do baseline recalculate.(The number of services are so huge. )
