### ISSUE TITLE
Log collecting, analysis, and query

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5930]
Hi, as we are establishing the [Satellite](https://github.com/apache/skywalking-satellite), log collecting and analysis should be built on the OAP server too.

I have submitted the [data collecting service](https://github.com/apache/skywalking-data-collect-protocol/pull/35), once it is approved, we could begin to build a new receiver(`log-receiver`) to provide backend features.
In the log analysis, I propose to add the following features
1. gRPC and HTTP format should be provided by following the proto definition.
1. `service` in the reported data should support auto-filling if it is null. If the no previous service name, the log should be ignored.
1. `timestamp` could be reported by the client-side or use the analysis component to read from the text.
1.  Provide different analyzers for different format logs. Every analyzer implementation could have its own expression definition to read the data from the logs, such as for instance name, tags, traceid

Query GraphQL definition will be submitted later, and ask UI side to confirm.

**Comment by EvanLjp** [comment]
Do we need to plan for split storage? Logs have to be large.

**Comment by wu-sheng** [comment]
That is another topic, I have no plan to add it for now.

**Comment by wu-sheng** [comment]
Query protocol has been polished through https://github.com/apache/skywalking-query-protocol/pull/44.

Take a look at this, https://github.com/apache/skywalking-query-protocol/blob/master/log.graphqls

@arugal will lead this feature at the backend, @Fine0830 will follow up at the UI side after the backend is ready. This would be the core feature of 8.4.0. 

FYI @dmsolr, if you have time, we could consider looking deeper into the OpenTelemetry collector log report format(gRPC), this would be a very useful integration and as an alternative with our Satellite.
