### ISSUE TITLE
influxdb response format error

### ISSUE THREAD

**Issue by zhangjianweibj** [apache/skywalking#5931]
###Requirement

we use influxdb srelay(https://github.com/toni-moreno/influxdb-srelay) for influxdb ha.but influxdb-sreay not support msgpack protocol only support JSON format.

![image](https://user-images.githubusercontent.com/18585129/100745931-f63e3c80-341a-11eb-81fc-325dc07dcca5.png)

**Comment by wu-sheng** [comment]
Read https://github.com/apache/skywalking/pull/5932#issuecomment-737648703 for the update.
