### ISSUE TITLE
org.apache.skywalking.apm.plugin.spring.mvc.commons.exception.ServletResponseNotFoundException

### ISSUE THREAD

**Issue by xuguoqi302** [apache/skywalking#5933]
- [ √] Bug

___
### Question
- What do you want to know?
We are using version 8.2 of skywalking, and there is an error in the figure below, can we fix this problem?
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 8.2 ,spring 4.x, tomcat7,jdk1.8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/55222048/100747037-79ac5d80-341c-11eb-9f10-95f71abe46fe.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Could you provide a demo to reproduce the error?
