### ISSUE TITLE
Met the bug "frozen class" when configured the telemetry for backend

### ISSUE THREAD

**Issue by zhaizhai96** [apache/skywalking#5937]
I met the bug "frozen class" when configured the telemetry for backend. The version of SkyWalking is 8.1.0, CentOS7 and jdk 1.8.

![image](https://user-images.githubusercontent.com/57163421/100839383-17e90380-34af-11eb-89c1-89e0097dba18.png)

My configuration was according to the docs (https://github.com/apache/skywalking/blob/35264e6171b7a5c675d4fdf42645dae4caa5a31c/docs/en/setup/backend/backend-telemetry.md), I don't know where is the problem?

**Comment by wu-sheng** [comment]
Try the latest.
