### ISSUE TITLE
When using the Kafka plug-in, skywalking can't always detect the usage of the JVM.

### ISSUE THREAD

**Issue by zhaozhengbin** [apache/skywalking#5938]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
___
### Question
- What do you want to know?
when using the Kafka plug-in,sometimes you can't add data to the service_traffic index.so you can't get your project jvm instance message.I found that in skywalking-management-receiver-plugin module, 94-98 lines of  ManagementServiceHandler method have the operation of adding service to the queue, but there is no corresponding operation in the handle corresponding to Kafka.
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking version:8.1
- Which company or project?
myself test demo
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
fisrt empty data in ES index,second put APM\skywalking-agent\optional-reporter-plugins\kafka-reporter-plugin-8.1.0.jar in APM\skywalking-agent\plugins folder，end run your project with javaagent command.
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> ManagementServiceHandler method have the operation of adding service to the queue, but there is no corresponding operation in the handle corresponding to Kafka.

I can't understand your meaning. There is no Kafka in the backend.

**Comment by zhaozhengbin** [comment]
Sorry, I didn't make it clear.I want to express is kafka-fetcher-plugin module there is no operation to insert data into e's service_traffic index.

**Comment by wu-sheng** [comment]
These are not related things, OAP will read data from Kafka and do all necessary process.
