### ISSUE TITLE
If set influxdb connection response format as InfluxDB.ResponseFormat.JSON，there will be some error

### ISSUE THREAD

**Issue by cuiweiwei** [apache/skywalking#5945]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
If set influxdb connection response format as InfluxDB.ResponseFormat.JSON，the start time of trace will always be 1970-01-01 08:00:00，also cannot see details of profiled trace segments.

___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking version：8.2.0.RELEASE
OS：linux or windows

- What happened?
When use influxdb as storage of Skywalking, due to certain limitations, only can use json as influxdb connection response format .Some errors will occur, as follows.
![image](https://user-images.githubusercontent.com/15830188/101014244-8659be80-35a0-11eb-8fac-fe774d52cb8b.png)

**Comment by wu-sheng** [comment]
Read #5932. That PR we asked for proving is knowing this could happen.

**Comment by wu-sheng** [comment]
Quick answer is, don't use JSON mode.
