### ISSUE TITLE
more info of alarm content 

### ISSUE THREAD

**Issue by Jiangting1** [apache/skywalking#5948]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
Response time of endpoint /XXX in XXX is mXXXore than 1500ms in 2 minutes of last 10 minutes
The message like this is very simple，through the message ,we don't know the alarm value or the error code.
- [ ] BugXXX
- [ ] Requirement
I want to know the alarm value or other concrete alarm info.
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can any method  improve this requirement？
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.6
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> Response time of endpoint /XXX in XXX is mXXXore than 1500ms in 2 minutes of last 10 minutes
The message like this is very simple，through the message ,we don't know the alarm value or the error code.

Alarm based on a set of values, not a single value.
