### ISSUE TITLE
http://localhost:8080/graphql response error

### ISSUE THREAD

**Issue by xflag** [apache/skywalking#5950]
Platform:windows 10
SkyWalking version:7.0/6.6
Storage:mysql 5.7
JDK:8
After I run startup.bat,then visit localhost:8080,there are not any dashboard charts.
![image](https://user-images.githubusercontent.com/3249626/101146518-0beb7600-3656-11eb-966a-7ae078387a3a.png)
Then through F12,the request localhost:8080/graphql return error:
{"errors":[{"message":"Validation error of type FieldUndefined: Field 'getAllTemplates' in type 'Query' is undefined @ 'getAllTemplates'"}]}

The skywalking-oap-server.log:
2020-12-04 17:13:54,691 - graphql.GraphQL - 515 [qtp1920098017-51] WARN  [] - Query failed to validate : 'query queryGetAllTemplates {
    getAllTemplates(includingDisabled: false) {
      name,
      type
      configuration,
      activated,
      disabled,
    }
  }'

But,I start skywalking 8.0 for mysql successfully.
I can't find the reason of above error.

**Comment by wu-sheng** [comment]
Match the version of your UI and backend.

**Comment by xflag** [comment]
> Match the version of your UI and backend.

How math?Could you describe detail?

**Comment by wu-sheng** [comment]
Match, not math. Use the same version.
