### ISSUE TITLE
What is the "Log" menu,and how to cook it?

### ISSUE THREAD

**Issue by ryangsun** [apache/skywalking#5956]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What is the "Log" function,and how to cook it?

in the top of  8.3 ui,there is "Dashboard Topology Trace Profile Log Alarm" in main menu.
I want to know the function of the "Log" menu ,and how can i setup it?

**Comment by wu-sheng** [comment]
Browser log. See https://github.com/apache/skywalking-client-js for more details.
