### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound] - and missing image

### ISSUE THREAD

**Issue by MrCull** [apache/skywalking#5959]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
N/A
- Which company or project?
N/A
- What happened?
In the main page for this repo (i.e the readme):

Status code [404:NotFound] - Link: https://camo.githubusercontent.com/20262efc5acf41a0c3e95d73835f73b40009696e81c274a3f6d81a928642c467/687474703a2f2f736b7977616c6b696e672e6170616368652e6f72672f6173736574732f75736572732d32303230303732362e706e67

![image](https://user-images.githubusercontent.com/16634034/101282104-f481c980-37ca-11eb-9577-38050a3c7b9e.png)

___
### Requirement or improvement
Both the image and link which it points too both needs fixing.

--

This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fapache%2fskywalking
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=apache

--

I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or long an “Issue”.

**Comment by wu-sheng** [comment]
I could access the link. I am not sure what is your issue.

**Comment by MrCull** [comment]
Hmm weird.
Maybe you are logged into https://camo.githubusercontent.com/ or are IP whitelisted (??)
I think this will affect most other people on the web too.

We'll see
![image](https://user-images.githubusercontent.com/16634034/101285617-1e90b700-37de-11eb-8efe-27d23eb8f93e.png)

Then the link will give this:
![image](https://user-images.githubusercontent.com/16634034/101285590-f608bd00-37dd-11eb-89e3-9e26c7b380ea.png)

**Comment by wu-sheng** [comment]
![image](https://user-images.githubusercontent.com/5441976/101313876-3f1a4900-3892-11eb-860c-2e6427fda0aa.png)
