### ISSUE TITLE
UI enhancement for quick search by trace ID

### ISSUE THREAD

**Issue by superbible** [apache/skywalking#5963]
Requirement:
Exisiting UI behavior is kind of slow for UI operation, consider this case:
User get a trace Id, need to check the tracing log in Skywalking, user copy and paste trace ID into inputbox for trace ID, then press search button.
1. I'd like to copy and paste trace ID then press Enter key to trigger search action.
2. If we can do above by copy and paste an URL like http://demo.skywalking.apache.org/trace?id=xxxx, that will be very helpful, because we put the Skywalking trace ID and Skywalking server URL in HTTP response header for our business system, for convinience of debugging.

**Comment by wu-sheng** [comment]
Try this, /trace?traceid=3d0003cb-e6b8-4fa4-abfa-3e61acc8d511

**Comment by superbible** [comment]
> traceid=3d0003cb-e6b8-4fa4-abfa-3e61acc8d511

Thanks.
Does this feature be mentioned in Skywalking document? If doesn't, we need add this.
And, it's better we can press Enter key to do search function in tracing page, because this is frequent action, saving time you know.

**Comment by wu-sheng** [comment]
Welcome to submit pull request to update this, https://github.com/apache/skywalking/blob/master/docs/en/ui/README.md#trace-query

**Comment by superbible** [comment]
> Welcome to submit pull request to update this, https://github.com/apache/skywalking/blob/master/docs/en/ui/README.md#trace-query

Sure, I'd like to patch your document for this, but I failed to git clone skywalking for many ways...you know, it's hard from China.
I'm wondering how you do this project form China, you do this from China, right?

**Comment by wu-sheng** [comment]
Yes, everything works for me. I am using GitHub. Consider using VPN if needed.
