### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by githubphy** [apache/skywalking#5967]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
The dashboard often has no data intermittently. We find that the data is often lost and not stored in es. OAP error: org.apache.skywalking . oap.server.receiver . trace.provider.handler .v8. grpc.TraceSegmentReportServiceHandler - 83 [grpcServerPool-1-thread-24] ERROR [] - CANCELLED: cancelled before receiving half close

We used 8.1.0
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This error only means the network disconnected, due to network or client side
