### ISSUE TITLE
how to save customize dashboard and share anyone

### ISSUE THREAD

**Issue by wuwenrufeng** [apache/skywalking#5968]
Please answer these questions before submitting your issue.

Question or discussion
  - how to save customize dashboard and share anyone?
  like this:
  
![Snipaste_2020-12-08_11-21-22](https://user-images.githubusercontent.com/45844514/101435683-bbbb2f00-3947-11eb-8cbd-f4e5a1595fea.png)

**Comment by wu-sheng** [comment]
All template files are located here, https://github.com/apache/skywalking/tree/master/oap-server/server-bootstrap/src/main/resources/ui-initialized-templates.
You could add your own.

**Comment by wuwenrufeng** [comment]
thans a lot :)
