### ISSUE TITLE
How to enable Alarm funtion in debug mode？

### ISSUE THREAD

**Issue by Lynda-Li** [apache/skywalking#5969]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
1. Besides _alarm-settings.xml_ to uncomment the webhooks setting, what else should we do to enable Alarm function？
Since, I start a Spring MVC app in debug mode, a local OAP, and the settings meet, but it doesn't go to my breakpoint. Could you help?
2. From source code, it looks like the webhook response is formatted in _AlarmMessageFormatter_?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I can't see the point. We don't play any dark magic about the source codes and debugging, especially at the backend/OAP.

What do you mean `how`?

**Comment by Lynda-Li** [comment]
I just want to ask a question, maybe the title sounds vague.

**Comment by wu-sheng** [comment]
I have read your question, but can't understand your question. OAP backend could debug directly in the IntelliJ. We are doing this every day.

**Comment by Lynda-Li** [comment]
My mistake, wrong _alarm-settings.xml_ is used. Used the dist one, that's why it seems not working.

**Comment by wu-sheng** [comment]
Thanks for the clarification
