### ISSUE TITLE
A large amount of data causes the browser to crash

### ISSUE THREAD

**Issue by LuckyMango** [apache/skywalking#5970]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 在某个接口中有大量链路，点击该接口会导致浏览器卡死。请问一下，怎么限制链路的深度呢？

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 7.0.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
如图所示，现在该接口链路跨度2万多，导致点击该接口时页面卡死，浏览器崩溃。请问一下，该问题怎么有什么好的解决办法呢？

![image](https://user-images.githubusercontent.com/43702671/101447479-490a7d80-3960-11eb-9442-22f7cbbefee5.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please keep using English on the GitHub. Could you explain first why do you have so many spans in one traceid? Is it a scheduled task or something?

**Comment by LuckyMango** [comment]
> 请继续在GitHub上使用英语。您能先解释一下为什么一个traceid中有这么多跨度吗？是预定任务还是其他？

**Comment by LuckyMango** [comment]
> Please keep using English on the GitHub. Could you explain first why do you have so many spans in one traceid? Is it a scheduled task or something?
I am not sure why there are so many traceids in other departments，Is there any good solution?

**Comment by wu-sheng** [comment]
First, please make sure this is really a reasonable trace, because in some cases, bugs of plugins could cause this. Link several requests with one dirty trace id.

**Comment by LuckyMango** [comment]
> First, please make sure this is really a reasonable trace, because in some cases, bugs of plugins could cause this. Link several requests with one dirty trace id.

Some connection timeouts will cause these errors，There is no way to restrict him，Don't show so much traceid

**Comment by wu-sheng** [comment]
I still can't follow. `timeout` has no relationship with the traceid.

**Comment by LuckyMango** [comment]
> I still can't follow. `timeout` has no relationship with the traceid.
Sorry, I just reply to you now，There is a lot of this kind of data causes the browser to crash。

![image](https://user-images.githubusercontent.com/43702671/101556804-99ccb580-39f6-11eb-9cdb-6684c34ae4f9.png)

**Comment by wu-sheng** [comment]
These things seem not collected by SkyWalking in default, do you change or set up something?

**Comment by LuckyMango** [comment]
> These things seem not collected by SkyWalking in default, do you change or set up something?

We modified agent.config `logging.max_history_files=${SW_LOGGING_MAX_HISTORY_FILES:1}` and  `plugin.mysql.trace_sql_parameters=${SW_MYSQL_TRACE_SQL_PARAMETERS:true}` 。 oap application.yml only add es  configuration and ui changed

**Comment by wu-sheng** [comment]
I have a feeling you are adding Spring annotation or custom tracing plugins.

**Comment by LuckyMango** [comment]
> I have a feeling you are adding Spring annotation or custom tracing plugins.

yes ，we also modified a little code。can you give us some suggestions  solved by other means?

**Comment by wu-sheng** [comment]
Other 10k's span, I think either you don't trace so much, so we have to try browser-side optimization.

**Comment by LuckyMango** [comment]
> 尝试

thanks

**Comment by LuckyMango** [comment]
> Other 10k's span, I think either you don't trace so much, so we have to try browser-side optimization.

thankes ~
