### ISSUE TITLE
elasticsearch7 Indexreplicasnumber does not work

### ISSUE THREAD

**Issue by vienous** [apache/skywalking#5974]
Provider=elasticsearch7 config=indexReplicasNumber has been set as 0

but still show one rep in elasticsearch

**Comment by wu-sheng** [comment]
Which index?

**Comment by vienous** [comment]
![image](https://user-images.githubusercontent.com/16508257/101467119-e1aef680-397c-11eb-934e-9e00971512c8.png)

**Comment by vienous** [comment]
配置了elasticsearch7， shard我设置的2，注释了elasticsearch，都没起作用

`Provider=elasticsearch7 config=indexShardsNumber has been set as 2`
`Provider=elasticsearch7 config=indexReplicasNumber has been set as 0`

**Comment by wu-sheng** [comment]
Please keep using English on GitHub. @EvanLjp I think you tested this a lot of times locally, right? Could you take a look? AFAIK, there is no issue with this.

**Comment by EvanLjp** [comment]
@vienous try to remove all templates and restart again. DELETE _template/{templates}  .you can use this command to find all templates: GET _cat/templates
