### ISSUE TITLE
Can you pass tracID from the front end to the back end to form a complete chain of calls?

### ISSUE THREAD

**Issue by xiaoliu10** [apache/skywalking#5976]
RT

**Comment by wu-sheng** [comment]
I think you don't mean front end. Front end is still a server. 
We don't support tracing from browser. Read the document, https://github.com/apache/skywalking-client-js
It is very clear.

**Comment by xiaoliu10** [comment]
![image](https://user-images.githubusercontent.com/28430309/101482283-74599080-3991-11eb-97ab-48a30a070924.png)

How can I understand this sentence

**Comment by wu-sheng** [comment]
Search **WIP**? 
https://www.google.com/search?q=WIP&oq=WIP&aqs=chrome..69i57j0j46i131i199i291i433j0l2j0i131i433j69i61l2.602j0j7&sourceid=chrome&ie=UTF-8

**Comment by xiaoliu10** [comment]
ok. thank you

**Comment by xiaoliu10** [comment]
may i know when a version well be released ? i'll try it

**Comment by wu-sheng** [comment]
It depends on contributors. We don't set the deadline. If you are urgent, try to contribute, this is how open source works.
