### ISSUE TITLE
[UI] Support group concept in the topology

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5978]
At the current topology page, the page is driven by the service selector
![image](https://user-images.githubusercontent.com/5441976/101561054-938f0700-39ff-11eb-895e-8058d1459776.png)

There are some side effects
1. Once the number of services is large, hundreds and even 1k+ in some cases, it would be hard to find
1. Rending speed is limited, due to browser performance and the backend.
1. We recently add group concept in the naming system, #5977

As a result, we have a group name in the service metadata now
https://github.com/apache/skywalking-query-protocol/blob/4be8e459b0ff56ed5d41a3b5c2173ba83668831e/metadata.graphqls#L29

@Fine0830 We should refactor this selector to 2 hierarchy levels
```
- group name 1(selectable)
+--- service 1(selectable)
     service 2
- group name 2
+--- service 3
     service 4
- default
+--- service 5 (all services without group name)
     service 6
     service 7
```

Topology renders based on selected service group or service, when re-entering the topology page, it renders based on last time chosen.
When entering this page, it renders the topology based on the last time selected.

At the bottom of the page, there is a client-side temp group,
![image](https://user-images.githubusercontent.com/5441976/101561686-b8d04500-3a00-11eb-981c-4b89a43ae7ed.png)
Let's keep it for now, and reword it as `Add local view`.

**Comment by Fine0830** [comment]
close this via https://github.com/apache/skywalking-rocketbot-ui/pull/399
