### ISSUE TITLE
Why sw don't parse and save  the prometheus federate endpoint return  metrics as untyped?

### ISSUE THREAD

**Issue by wuwenrufeng** [apache/skywalking#5979]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- What do you want to know?
  I've taken some metrics by using the prometheus federate, it return metrics like this:
```text
  # TYPE container_cpu_cfs_periods_total untyped
   container_cpu_cfs_periods_total{replica="center"} 1000 1607425368513
```
  I add yaml file in $CLASSPATH/fetcher-prom-rules, but These metrics are not stored，if I alter  metrcis is below, it ok
```text
  # TYPE container_cpu_cfs_periods_total gauge
   container_cpu_cfs_periods_total{replica="center"} 1000 1607425368513
```
Why does the federate endpoint return all metrics as untyped? I find this: https://github.com/prometheus/prometheus/issues/5589
if i want stored this metrics by sw, what should i do?

**Comment by hanahmily** [comment]
Prometheus federation loses metadata due to a "complicated" reason. And from https://www.robustperception.io/federation-what-is-it-good-for, the federation is **NOT** good for exporting all metrics to the third platform, like SW. 

I suggest using SW Prometheus fetcher directly or leverage OpenTelemetry collector to collect metrics from Prometheus then export to SW.

**Comment by wu-sheng** [comment]
Agree, SkyWalking backend is more powerful and supporting cluster mode. We don't need the federation mode.

**Comment by wuwenrufeng** [comment]
Yes, but some metric can't pull by fetcher directly, such as container cpu usage, It's included in the cluster。so，I set fetcher metrics URL is prometheus fedarate address(egg: http://prometheus:37772/federate?match[]={pod_name="test"}).

**Comment by wu-sheng** [comment]
@wuwenrufeng Take a look at OpenTelemetry collector for now.

**Comment by wuwenrufeng** [comment]
ok
