### ISSUE TITLE
SelfObservability does not display any data in version 8.3.0

### ISSUE THREAD

**Issue by xinfeingxia85** [apache/skywalking#5983]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
   SelfObservability does not display any data under the panel, but data does exist in the database.
   The data store is mysql
   Want to know why
   But  there is no problme with version 8.2.0

- Which version of SkyWalking, OS and JRE?
   skywalking:  version 8.3.0
   os: ubtuntu

 UI screenshot:
![image](https://user-images.githubusercontent.com/20057242/101604326-b93a0180-3a3b-11eb-951f-ff3a6065c3cc.png)

Database screenshot:
![image](https://user-images.githubusercontent.com/20057242/101604462-ec7c9080-3a3b-11eb-9de1-07741c979031.png)

 The file "self.yaml" is default and the  configuration through environment variables is as follows:

  SW_PROMETHEUS_FETCHER: "default"
  SW_TELEMETRY: "prometheus"

**Comment by wu-sheng** [comment]
You have the service and endpoint, then the data has been fetched. I am not sure what is your issue.

**Comment by xinfeingxia85** [comment]
> You have the service and endpoint, then the data has been fetched. I am not sure what is your issue.

Select the corresponding service in the UI interface and get no data。
However, if I set metricPrefix to value "meter", it would be normal for the UI interface to select the corresponding service.
Set metricPrefix to any other value, it has problem.

**Comment by wu-sheng** [comment]
Oh, you changed that, then yes. You can't change them randomly. Change the UI to edit mode, you will see there are configuration related to the metrics name.

**Comment by xinfeingxia85** [comment]
> Oh, you changed that, then yes. You can't change them randomly. Change the UI to edit mode, you will see there are configuration related to the metrics name.

OK, thank you!

**Comment by JayeshMuley** [comment]
I am new to Skywalking and want to setup APM for my services. I am facing issue with SelfObservability UI not showing anything neither meter tables got created in mysql database. 

Skywalking version 8.3

Can you please suggest the configuration 

1) In self.yml   ( where this url should point to )

  # targets will be labeled as "instance"
  targets:
    - url: http://localhost:1234
      sslCaFilePath:
  labels:
    service: oap-server

2) There is no data on Profile and Log tab on UI , What configuration i need to set.

Please suggest.

**Comment by kezhenxu94** [comment]
> I am new to Skywalking and want to setup APM for my services.

Did you read [this](https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-telemetry.md#self-observability)?

> I am facing issue with SelfObservability UI not showing anything neither meter tables got created in mysql database.
> 
> Skywalking version 8.3
> 
> Can you please suggest the configuration
> 
> 1. In self.yml   ( where this url should point to )

The url should point to `http://localhost:1234`, this is an endpoint exposed by OAP itself, and is consumed by itself, make sure to enable `telemetry` that exposes the endpoint.

> 
> ```yaml
>   # targets will be labeled as "instance"
>   targets:
>     - url: http://localhost:1234
>       sslCaFilePath:
>   labels:
>     service: oap-server
> ```
> 
> 1. There is no data on Profile and Log tab on UI , What configuration i need to set.

Profile task is created by you, if you didn't create any, there is no data without doubt.

The Log tab is for frontend at the moment, check [the SDK](https://github.com/apache/skywalking-client-js)

**Comment by pantovad** [comment]
Hello,

With the setup as explained in the instructions I still get no oap-server metrics ...

**Comment by pantovad** [comment]
So the issue is mismatching setup between UI and backend:
Backend sets 'metricPrefix: meter_oap' in config/fetcher-prom-rules/self.yaml
UI expects 'meter' prefix as specified in charts 'Metrics' charts configuration.

Fix is either changing manually UI charts or in the backend setting 'metricPrefix: meter'

**Comment by wu-sheng** [comment]
I think this is your local browser cache. The templates cached. I checked the settings, it is there

**Comment by pantovad** [comment]
Thx vm ! Used another browser and looks good. Any hint how to remove cache for skywalking only in Chrome ?

**Comment by wu-sheng** [comment]
Open F12, the you have these. Clear them.

![image](https://user-images.githubusercontent.com/5441976/105705813-aa57d180-5f4b-11eb-9045-a6d8d683f17e.png)

**Comment by pantovad** [comment]
Great thx vm !
