### ISSUE TITLE
[CLI] set up a simple test with GitHub Actions to verify the minimal functionalities

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#5985]
We'll use the latest released docker image as the server side

**Comment by wu-sheng** [comment]
Please choose the official release of SkyWalking as the server side.

**Comment by fgksgf** [comment]
> Please choose the official release of SkyWalking as the server side.

How about using the latest docker image of SkyWalking ?

**Comment by wu-sheng** [comment]
Yes, that works too.
