### ISSUE TITLE
skywalking dashboard and tracing page is blank when startup by docker-compose

### ISSUE THREAD

**Issue by v-zhidu** [apache/skywalking#5990]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I want setup a playgroud environment by docker.

1. using [docker-compose.yml](https://github.com/apache/skywalking-docker/blob/master/8/8.3.0/compose-es7/docker-compose.yml)
2. emit a request to my demo application that start with Java agent

The question is both dashboard and tracing page is blank in UI. And instance_name is empty.

![image](https://user-images.githubusercontent.com/8225531/101767853-c4fef400-3b1f-11eb-9e0b-93f24a747f75.png)

But it can return data by a specific trace id that i take from log

![image](https://user-images.githubusercontent.com/8225531/101768620-c846af80-3b20-11eb-975b-2d71ad8b8127.png)

I also query the instance from skywalking-cli. It's correct

```
/bin/swctl-0.5.0-darwin-amd64 service ls test-application
[{"id":"dGVzdC1hcHBsaWNhdGlvbg==.1","name":"test-application","group":""}

./bin/swctl-0.5.0-darwin-amd64 instance ls --service-name=test-application
[{"id":"dGVzdC1hcHBsaWNhdGlvbg==.1_OWQ0YTNmMzk2NzFkNGMxMWJjYTEzYWQ4NzY3ZmM4MmNAMTkyLjE2OC44LjY3","name":"9d4a3f39671d4c11bca13ad8767fc82c@192.168.8.67","attributes":[{"name":"OS Name","value":"Mac OS X"},{"name":"hostname","value":"v-zhidus-MacBook-Pro.local"},{"name":"Process No.","value":"32235"},{"name":"ipv4s","value":"192.168.8.67"}],"language":"JAVA","instanceUUID":"dGVzdC1hcHBsaWNhdGlvbg==.1_OWQ0YTNmMzk2NzFkNGMxMWJjYTEzYWQ4NzY3ZmM4MmNAMTkyLjE2OC44LjY3"}]
```

There is no problem without docker. Can you help me with this question? Am i miss something important ?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Because docker is using UTC-0 as TZ. Please select correct timezone at the UI.
