### ISSUE TITLE
how to find oap_analyzer plugin

### ISSUE THREAD

**Issue by goodjuan-xj** [apache/skywalking#5996]
Exception in thread "main" ElasticsearchStatusException[Elasticsearch exception [type=mapper_parsing_exception, reason=analyzer [oap_analyzer] not found for field [alarm_message_match]]]

**Comment by wu-sheng** [comment]
Do you upgrade from some old versions? This analyzer added by codes when OAP boots at the 1st time.

**Comment by goodjuan-xj** [comment]
the skywalking version is 8.1.0

**Comment by wu-sheng** [comment]
I mean did you install some old version? This is there for a long time.

**Comment by goodjuan-xj** [comment]
> Do you upgrade from some old versions? This analyzer added by codes when OAP boots at the 1st time.

where can i download opa_analyzer ?Can you give me a link?

**Comment by wu-sheng** [comment]
How about simply searching the source codes before asking? 

https://github.com/apache/skywalking/blob/f513726fead7543e2b90acea079e6c7b50523c01/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/base/StorageEsInstaller.java#L116
