### ISSUE TITLE
spring cloud gateway2.2.1 Unable to monitor

### ISSUE THREAD

**Issue by hsw409328** [apache/skywalking#6004]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
gateway 2.2.1 monitor
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking: 8.3.0
Gateway: 2.2.1
plugin: apm-spring-webflux-5.x-plugin-8.3.0   apm-spring-cloud-gateway-2.1.x-plugin-8.3.0

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
Agent Log:
WARN 2020-12-14 16:03:57:507 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.reactive.DispatcherHandler by plugin org.apache.skywalking.apm.plugin.spring.cloud.gateway.v20x.define.DispatcherHandlerInstrumentation is not working. Because witness class org.springframework.cloud.gateway.config.GatewayAutoConfiguration$1 is not existed.
WARN 2020-12-14 16:04:00:199 main AbstractClassEnhancePluginDefine : enhance class com.mx.gateway.handler.SwaggerHandler by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.RestControllerInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed.
WARN 2020-12-14 16:04:00:199 main AbstractClassEnhancePluginDefine : enhance class com.mx.gateway.handler.SwaggerHandler by plugin 
org.apache.skywalking.apm.plugin.spring.mvc.v4.define.RestControllerForLowVersionInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed.
WARN 2020-12-14 16:04:00:487 main AbstractClassEnhancePluginDefine : enhance class org.springframework.cloud.gateway.filter.NettyRoutingFilter by plugin org.apache.skywalking.apm.plugin.spring.cloud.gateway.v20x.define.NettyRoutingFilterInstrumentation is not working. Because witness class org.springframework.cloud.gateway.config.GatewayAutoConfiguration$1 is not existed.
WARN 2020-12-14 16:04:05:461 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed.
WARN 2020-12-14 16:04:05:463 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
witness class log only means there are plugins inactivated, which is normal. Because you use all default plugins, the SkyWalking disable unsuitable plugins automatically, but outputa the logs to warning you.

**Comment by hsw409328** [comment]
The current version 2.2.1 has loaded all the plug-ins and the URL request monitoring cannot be reached. Will the next version solve the monitoring problem for the Gateway 2.2.x version?

**Comment by wu-sheng** [comment]
We have 2.2.3 tested here. https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/gateway-2.1.x-scenario

Rhe community can't have everything, we relies on every one to test and send pull request to fix unsupported things. The plugins you are using are from other 300+ contributors, this is how open source works. New features of next release could be from you.
