### ISSUE TITLE
The data of the previous days was lost when the panel was displayed

### ISSUE THREAD

**Issue by CodingOX** [apache/skywalking#6005]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug

### Bug
- Which version of SkyWalking, OS and JRE?
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

- Which company or project?
UeWell

- What happened?
On the dashboard, if I choose a day data, most of the data will be empty,like this:
![image](https://user-images.githubusercontent.com/9800933/102062207-62636c00-3e2f-11eb-9726-a2fde46844d3.png)
![image](https://user-images.githubusercontent.com/9800933/102062335-8de65680-3e2f-11eb-8f5c-04eb8293f330.png)

But i have some data at 3 days ago
![image](https://user-images.githubusercontent.com/9800933/102062491-c9812080-3e2f-11eb-972f-8a22bf93f307.png)

And http post data is 
```json
{"query":"query queryData($condition: MetricsCondition!, $duration: Duration!) {\n  readMetricsValues: readMetricsValues(condition: $condition, duration: $duration) {\n    label\n    values {\n      values {value}\n    }\n  }}","variables":{"duration":{"start":"2020-12-13 17","end":"2020-12-14 17","step":"HOUR"},"condition":{"name":"instance_jvm_memory_heap","entity":{"scope":"ServiceInstance","serviceName":"ubirth","serviceInstanceName":"ecs2","normal":true}}}}
```

___
### Requirement or improvement
Is it bug?
How to solve this problem？

**Comment by wu-sheng** [comment]
The query time is based on TimeZone. The data in the storage is based on OAP timezone. I guess you miss some of them.
