### ISSUE TITLE
How to review the gRPC request/response data in trace view?

### ISSUE THREAD

**Issue by Sky-Walkrr** [apache/skywalking#6010]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Can we review the request & response data in trace view of Skywalking Rocketbot?
___
### Bug
- Which version of SkyWalking, OS and JRE?

SkyWalking 8.2

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

We have several services using gRPC to communicate with each other, and try using SkyWalking to deal with the trace stuff.
We can find out the complete call chain and each span info in trace view of Rocketbot, that's really nice. But sometimes we hope to review the request or response data of the gRPC call in one span, can we do that with SkyWalking?

**Comment by wu-sheng** [comment]
Read the agent setup doc. Some plugins support collecting parameters, some are not. I remember grpc didn't. If you want, contributions are welcome.
