### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by OPSTime** [apache/skywalking#6011]
**Info:**
`
pkg: https://github.com/apache/skywalking/archive/v8.3.0.tar.gz

$ uname -a
Linux iZuf69qeee7fl6gj4ktpfiZ 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release 
CentOS Linux release 8.2.2004 (Core) 
$ java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
$ javac -version
javac 1.8.0_261
$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/apache-maven
Java version: 1.8.0_261, vendor: Oracle Corporation, runtime: /usr/java/jdk1.8.0_261-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-193.14.2.el8_2.x86_64", arch: "amd64", family: "unix"
`

**Error:**
> [INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ apm-network ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 11 source files to /data/src/skywalking-8.3.0/apm-protocol/apm-network/target/classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Serializable.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Serializable.java:[24,12] package Command does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[22,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[28,26] package Command does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[43,12] package Command does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Deserializable.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Deserializable.java:[24,19] cannot find symbol
>   symbol:   class Command
>   location: interface org.apache.skywalking.apm.network.trace.component.command.Deserializable<T>
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/ProfileTaskCommand.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/ProfileTaskCommand.java:[22,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/ProfileTaskCommand.java:[54,43] cannot find symbol
>   symbol:   class Command
>   location: class org.apache.skywalking.apm.network.trace.component.command.ProfileTaskCommand
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/ProfileTaskCommand.java:[92,19] package Command does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/UnsupportedCommandException.java:[20,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/UnsupportedCommandException.java:[23,19] cannot find symbol
>   symbol:   class Command
>   location: class org.apache.skywalking.apm.network.trace.component.command.UnsupportedCommandException
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/UnsupportedCommandException.java:[25,46] cannot find symbol
>   symbol:   class Command
>   location: class org.apache.skywalking.apm.network.trace.component.command.UnsupportedCommandException
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/UnsupportedCommandException.java:[29,12] cannot find symbol
>   symbol:   class Command
>   location: class org.apache.skywalking.apm.network.trace.component.command.UnsupportedCommandException
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[22,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[34,19] package Command does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/CommandDeserializer.java:[20,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/CommandDeserializer.java:[24,49] cannot find symbol
>   symbol:   class Command
>   location: class org.apache.skywalking.apm.network.trace.component.command.CommandDeserializer
> [INFO] 21 errors 
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for apm 8.3.0:
> [INFO] 
> [INFO] apm ................................................ SUCCESS [  3.209 s]
> [INFO] apm-commons ........................................ SUCCESS [  0.211 s]
> [INFO] apm-util ........................................... SUCCESS [01:59 min]
> [INFO] apm-datacarrier .................................... SUCCESS [  6.299 s]
> [INFO] apm-protocol ....................................... SUCCESS [  0.213 s]
> [INFO] apm-network ........................................ FAILURE [  3.218 s]
> [INFO] apm-sniffer ........................................ SKIPPED
> [INFO] apm-agent-core ..................................... SKIPPED
> [INFO] apm-agent .......................................... SKIPPED
> [INFO] apm-test-tools ..................................... SKIPPED
> [INFO] apm-sdk-plugin ..................................... SKIPPED
> [INFO] dubbo-plugin ....................................... SKIPPED
> [INFO] jdbc-commons ....................................... SKIPPED
> [INFO] apm-httpclient-commons ............................. SKIPPED
> [INFO] httpclient-4.x-plugin .............................. SKIPPED
> [INFO] jedis-2.x-plugin ................................... SKIPPED
> [INFO] redisson-3.x-plugin ................................ SKIPPED
> [INFO] tomcat-7.x-8.x-plugin .............................. SKIPPED
> [INFO] motan-plugin ....................................... SKIPPED
> [INFO] mongodb-plugin ..................................... SKIPPED
> [INFO] mongodb-plugin ..................................... SKIPPED
> [INFO] apm-feign-default-http-9.x-plugin .................. SKIPPED
> [INFO] okhttp-3.x-plugin .................................. SKIPPED
> [INFO] apm-sdk-plugin ..................................... SKIPPED
> [INFO] async-annotation-plugin ............................ SKIPPED
> [INFO] spring-commons ..................................... SKIPPED
> [INFO] concurrent-util-4.x-plugin ......................... SKIPPED
> [INFO] resttemplate-4.3.x-plugin .......................... SKIPPED
> [INFO] mvc-annotation-commons ............................. SKIPPED
> [INFO] mvc-annotation-4.x-plugin .......................... SKIPPED
> [INFO] spring-cloud ....................................... SKIPPED
> [INFO] netflix-plugins .................................... SKIPPED
> [INFO] spring-cloud-feign-1.x-plugin ...................... SKIPPED
> [INFO] apm-spring-cloud-feign-2.x-plugin .................. SKIPPED
> [INFO] mvc-annotation-3.x-plugin .......................... SKIPPED
> [INFO] core-patch ......................................... SKIPPED
> [INFO] mvc-annotation-5.x-plugin .......................... SKIPPED
> [INFO] kafka-commons ...................................... SKIPPED
> [INFO] apm-spring-kafka-1.x-plugin ........................ SKIPPED
> [INFO] apm-spring-kafka-2.x-plugin ........................ SKIPPED
> [INFO] scheduled-annotation-plugin ........................ SKIPPED
> [INFO] spring-webflux-5.x-webclient-plugin ................ SKIPPED
> [INFO] struts2-2.x-plugin ................................. SKIPPED
> [INFO] apm-sdk-plugin ..................................... SKIPPED
> [INFO] http-1.x-plugin .................................... SKIPPED
> [INFO] mvc-annotation-1.x-plugin .......................... SKIPPED
> [INFO] jetty-plugin ....................................... SKIPPED
> [INFO] jetty-client-9.x-plugin ............................ SKIPPED
> [INFO] jetty-server-9.x-plugin ............................ SKIPPED
> [INFO] jetty-client-9.0-plugin ............................ SKIPPED
> [INFO] spymemcached-2.x-plugin ............................ SKIPPED
> [INFO] sharding-jdbc-1.5.x-plugin ......................... SKIPPED
> [INFO] sharding-sphere-3.x-plugin ......................... SKIPPED
> [INFO] sharding-sphere-4.x-plugin ......................... SKIPPED
> [INFO] sharding-sphere-4.x-rc3-plugin ..................... SKIPPED
> [INFO] sharding-sphere-4.0.x-plugin ....................... SKIPPED
> [INFO] sharding-sphere-4.1.0-plugin ....................... SKIPPED
> [INFO] xmemcached-2.x-plugin .............................. SKIPPED
> [INFO] grpc-1.x-plugin .................................... SKIPPED
> [INFO] apm-mysql-commons .................................. SKIPPED
> [INFO] mysql-5.x-plugin ................................... SKIPPED
> [INFO] mysql-6.x-plugin ................................... SKIPPED
> [INFO] mysql-8.x-plugin ................................... SKIPPED
> [INFO] h2-1.x-plugin ...................................... SKIPPED
> [INFO] postgresql-8.x-plugin .............................. SKIPPED
> [INFO] rocketMQ-3.x-plugin ................................ SKIPPED
> [INFO] rocketMQ-4.x-plugin ................................ SKIPPED
> [INFO] elastic-job-2.x-plugin ............................. SKIPPED
> [INFO] elastic-job-3.x-plugin ............................. SKIPPED
> [INFO] apm-mongodb-2.x-plugin ............................. SKIPPED
> [INFO] httpasyncclient-4.x-plugin ......................... SKIPPED
> [INFO] apm-kafka-plugin ................................... SKIPPED
> [INFO] apm-sdk-plugin ..................................... SKIPPED
> [INFO] servicecomb-java-chassis-0.x-plugin ................ SKIPPED
> [INFO] servicecomb-java-chassis-1.x-plugin ................ SKIPPED
> [INFO] apm-hystrix-1.x-plugin ............................. SKIPPED
> [INFO] sofarpc-plugin ..................................... SKIPPED
> [INFO] activemq-5.x-plugin ................................ SKIPPED
> [INFO] elasticsearch-5.x-plugin ........................... SKIPPED
> [INFO] elasticsearch-6.x-plugin ........................... SKIPPED
> [INFO] undertow-plugins ................................... SKIPPED
> [INFO] undertow-2.x-plugin ................................ SKIPPED
> [INFO] rabbitmq-5.x-plugin ................................ SKIPPED
> [INFO] apm-dubbo-conflict-path ............................ SKIPPED
> [INFO] canal-1.x-plugin ................................... SKIPPED
> [INFO] dubbo-2.7.x-plugin ................................. SKIPPED
> [INFO] apm-dubbo-2.7.x-conflict-path ...................... SKIPPED
> [INFO] vertx-plugins ...................................... SKIPPED
> [INFO] vertx-core-3.x-plugin .............................. SKIPPED
> [INFO] resteasy-plugin .................................... SKIPPED
> [INFO] apm-resteasy-server-3.x-plugin ..................... SKIPPED
> [INFO] solrj-7.x-plugin ................................... SKIPPED
> [INFO] apm-cassandra-java-driver-3.x-plugin ............... SKIPPED
> [INFO] light4j-plugins .................................... SKIPPED
> [INFO] light4j-plugin ..................................... SKIPPED
> [INFO] ehcache-2.x-plugin ................................. SKIPPED
> [INFO] apm-pulsar-plugin .................................. SKIPPED
> [INFO] netty-socketio-plugin .............................. SKIPPED
> [INFO] armeria-0.84.x-plugin .............................. SKIPPED
> [INFO] armeria-0.85.x-plugin .............................. SKIPPED
> [INFO] httpclient-3.x-plugin .............................. SKIPPED
> [INFO] play-2.x-plugin .................................... SKIPPED
> [INFO] lettuce-5.x-plugin ................................. SKIPPED
> [INFO] apm-avro-plugin .................................... SKIPPED
> [INFO] apm-finagle-6.25.x-plugin .......................... SKIPPED
> [INFO] quasar-plugin ...................................... SKIPPED
> [INFO] mariadb-2.x-plugin ................................. SKIPPED
> [INFO] apm-influxdb-2.x-plugin ............................ SKIPPED
> [INFO] baidu-brpc-plugin .................................. SKIPPED
> [INFO] hbase-1.x-plugin ................................... SKIPPED
> [INFO] graphql-plugin ..................................... SKIPPED
> [INFO] graphql-8.x-plugin ................................. SKIPPED
> [INFO] graphql-9.x-plugin ................................. SKIPPED
> [INFO] graphql-12.x-plugin ................................ SKIPPED
> [INFO] xxl-job-2.x-plugin ................................. SKIPPED
> [INFO] apm-thrift-plugin .................................. SKIPPED
> [INFO] apm-asynchttpclient-2.x-plugin ..................... SKIPPED
> [INFO] dbcp-2.x-plugin .................................... SKIPPED
> [INFO] mssql-jtds-1.x-plugin .............................. SKIPPED
> [INFO] mssql-jdbc-plugin .................................. SKIPPED
> [INFO] cxf-3.x-plugin ..................................... SKIPPED
> [INFO] apm-application-toolkit ............................ SKIPPED
> [INFO] apm-toolkit-trace .................................. SKIPPED
> [INFO] apm-toolkit-activation ............................. SKIPPED
> [INFO] apm-toolkit-kafka-activation ....................... SKIPPED
> [INFO] apm-toolkit-log4j-1.x .............................. SKIPPED
> [INFO] apm-toolkit-log4j-1.x-activation ................... SKIPPED
> [INFO] apm-toolkit-log4j-2.x-activation ................... SKIPPED
> [INFO] apm-toolkit-logback-1.x-activation ................. SKIPPED
> [INFO] apm-toolkit-opentracing ............................ SKIPPED
> [INFO] apm-toolkit-opentracing-activation ................. SKIPPED
> [INFO] apm-toolkit-trace-activation ....................... SKIPPED
> [INFO] apm-toolkit-meter .................................. SKIPPED
> [INFO] apm-toolkit-meter-activation ....................... SKIPPED
> [INFO] bootstrap-plugins .................................. SKIPPED
> [INFO] apm-jdk-http-plugin ................................ SKIPPED
> [INFO] apm-jdk-threading-plugin ........................... SKIPPED
> [INFO] optional-plugins ................................... SKIPPED
> [INFO] optional-spring-plugins ............................ SKIPPED
> [INFO] apm-spring-annotation-plugin ....................... SKIPPED
> [INFO] apm-spring-tx-plugin ............................... SKIPPED
> [INFO] apm-spring-webflux-5.x-plugin ...................... SKIPPED
> [INFO] optional-spring-cloud .............................. SKIPPED
> [INFO] gateway-2.0.x-plugin ............................... SKIPPED
> [INFO] gateway-2.1.x-plugin ............................... SKIPPED
> [INFO] apm-trace-ignore-plugin ............................ SKIPPED
> [INFO] gson-2.8.x-plugin .................................. SKIPPED
> [INFO] zookeeper-3.4.x-plugin ............................. SKIPPED
> [INFO] customize-enhance-plugin ........................... SKIPPED
> [INFO] kotlin-coroutine-plugin ............................ SKIPPED
> [INFO] quartz-scheduler-2.x-plugin ........................ SKIPPED
> [INFO] optional-reporter-plugins .......................... SKIPPED
> [INFO] kafka-reporter-plugin .............................. SKIPPED
> [INFO] apm-toolkit-log4j-2.x .............................. SKIPPED
> [INFO] apm-toolkit-logback-1.x ............................ SKIPPED
> [INFO] apm-toolkit-micrometer-registry .................... SKIPPED
> [INFO] apm-toolkit-kafka .................................. SKIPPED
> [INFO] oap-server ......................................... SKIPPED
> [INFO] server-library ..................................... SKIPPED
> [INFO] library-util ....................................... SKIPPED
> [INFO] library-module ..................................... SKIPPED
> [INFO] server-telemetry ................................... SKIPPED
> [INFO] telemetry-api ...................................... SKIPPED
> [INFO] server-configuration ............................... SKIPPED
> [INFO] configuration-api .................................. SKIPPED
> [INFO] library-client ..................................... SKIPPED
> [INFO] library-server ..................................... SKIPPED
> [INFO] server-testing ..................................... SKIPPED
> [INFO] server-core ........................................ SKIPPED
> [INFO] analyzer ........................................... SKIPPED
> [INFO] agent-analyzer ..................................... SKIPPED
> [INFO] meter-analyzer ..................................... SKIPPED
> [INFO] server-receiver-plugin ............................. SKIPPED
> [INFO] skywalking-sharing-server-plugin ................... SKIPPED
> [INFO] skywalking-trace-receiver-plugin ................... SKIPPED
> [INFO] server-storage-plugin .............................. SKIPPED
> [INFO] storage-elasticsearch-plugin ....................... SKIPPED
> [INFO] storage-zipkin-plugin .............................. SKIPPED
> [INFO] skywalking-management-receiver-plugin .............. SKIPPED
> [INFO] zipkin-receiver-plugin ............................. SKIPPED
> [INFO] skywalking-mesh-receiver-plugin .................... SKIPPED
> [INFO] skywalking-jvm-receiver-plugin ..................... SKIPPED
> [INFO] receiver-proto ..................................... SKIPPED
> [INFO] envoy-metrics-receiver-plugin ...................... SKIPPED
> [INFO] skywalking-clr-receiver-plugin ..................... SKIPPED
> [INFO] storage-jaeger-plugin .............................. SKIPPED
> [INFO] jaeger-receiver-plugin ............................. SKIPPED
> [INFO] skywalking-profile-receiver-plugin ................. SKIPPED
> [INFO] otel-receiver-plugin ............................... SKIPPED
> [INFO] skywalking-meter-receiver-plugin ................... SKIPPED
> [INFO] skywalking-browser-receiver-plugin ................. SKIPPED
> [INFO] server-cluster-plugin .............................. SKIPPED
> [INFO] cluster-zookeeper-plugin ........................... SKIPPED
> [INFO] cluster-standalone-plugin .......................... SKIPPED
> [INFO] cluster-kubernetes-plugin .......................... SKIPPED
> [INFO] cluster-consul-plugin .............................. SKIPPED
> [INFO] cluster-etcd-plugin ................................ SKIPPED
> [INFO] cluster-nacos-plugin ............................... SKIPPED
> [INFO] storage-jdbc-hikaricp-plugin ....................... SKIPPED
> [INFO] storage-elasticsearch7-plugin ...................... SKIPPED
> [INFO] storage-influxdb-plugin ............................ SKIPPED
> [INFO] storage-tidb-plugin ................................ SKIPPED
> [INFO] oal-grammar ........................................ SKIPPED
> [INFO] oal-rt ............................................. SKIPPED
> [INFO] server-fetcher-plugin .............................. SKIPPED
> [INFO] prometheus-fetcher-plugin .......................... SKIPPED
> [INFO] kafka-fetcher-plugin ............................... SKIPPED
> [INFO] server-health-checker .............................. SKIPPED
> [INFO] server-query-plugin ................................ SKIPPED
> [INFO] query-graphql-plugin ............................... SKIPPED
> [INFO] server-alarm-plugin ................................ SKIPPED
> [INFO] telemetry-prometheus ............................... SKIPPED
> [INFO] exporter ........................................... SKIPPED
> [INFO] grpc-configuration-sync ............................ SKIPPED
> [INFO] configuration-apollo ............................... SKIPPED
> [INFO] configuration-zookeeper ............................ SKIPPED
> [INFO] configuration-etcd ................................. SKIPPED
> [INFO] configuration-consul ............................... SKIPPED
> [INFO] configuration-k8s-configmap ........................ SKIPPED
> [INFO] configuration-nacos ................................ SKIPPED
> [INFO] server-bootstrap ................................... SKIPPED
> [INFO] server-tools ....................................... SKIPPED
> [INFO] profile-exporter ................................... SKIPPED
> [INFO] tool-profile-snapshot-server-mock .................. SKIPPED
> [INFO] tool-profile-snapshot-bootstrap .................... SKIPPED
> [INFO] tool-profile-snapshot-exporter ..................... SKIPPED
> [INFO] server-starter ..................................... SKIPPED
> [INFO] tool-profile-snapshot-exporter-es7 ................. SKIPPED
> [INFO] server-starter-es7 ................................. SKIPPED
> [INFO] apm-webapp ......................................... SKIPPED
> [INFO] apache-skywalking-apm .............................. SKIPPED
> [INFO] apache-skywalking-apm-es7 .......................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  02:15 min
> [INFO] Finished at: 2020-12-15T20:54:45+08:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project apm-network: Compilation failure: Compilation failure: 
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Serializable.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Serializable.java:[24,12] package Command does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[22,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[28,26] package Command does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[43,12] package Command does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Deserializable.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/Deserializable.java:[24,19] cannot find symbol
> [ERROR]   symbol:   class Command
> [ERROR]   location: interface org.apache.skywalking.apm.network.trace.component.command.Deserializable<T>
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/ProfileTaskCommand.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/ProfileTaskCommand.java:[22,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/ProfileTaskCommand.java:[54,43] cannot find symbol
> [ERROR]   symbol:   class Command
> [ERROR]   location: class org.apache.skywalking.apm.network.trace.component.command.ProfileTaskCommand
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/ProfileTaskCommand.java:[92,19] package Command does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/UnsupportedCommandException.java:[20,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/UnsupportedCommandException.java:[23,19] cannot find symbol
> [ERROR]   symbol:   class Command
> [ERROR]   location: class org.apache.skywalking.apm.network.trace.component.command.UnsupportedCommandException
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/UnsupportedCommandException.java:[25,46] cannot find symbol
> [ERROR]   symbol:   class Command
> [ERROR]   location: class org.apache.skywalking.apm.network.trace.component.command.UnsupportedCommandException
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/UnsupportedCommandException.java:[29,12] cannot find symbol
> [ERROR]   symbol:   class Command
> [ERROR]   location: class org.apache.skywalking.apm.network.trace.component.command.UnsupportedCommandException
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[22,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/TraceIgnoreCommand.java:[34,19] package Command does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/CommandDeserializer.java:[20,51] package org.apache.skywalking.apm.network.common.v3 does not exist
> [ERROR] /data/src/skywalking-8.3.0/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/CommandDeserializer.java:[24,49] cannot find symbol
> [ERROR]   symbol:   class Command
> [ERROR]   location: class org.apache.skywalking.apm.network.trace.component.command.CommandDeserializer
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :apm-network

**Comment by wu-sheng** [comment]
That is not our download. Read the compiling doc and official website to get the real source codes.
