### ISSUE TITLE
can't find skywalking-oap-server.log files of skywalking-oap in k8s pod

### ISSUE THREAD

**Issue by ZhangDi-d** [apache/skywalking#6013]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I deploy skywalking-oap in k8s by executing values.yaml file in project skywalking-kubernetes(https://github.com/apache/skywalking-kubernetes, release 4.0.0)  without changing any settings about log output.
The question is i can't find skywalking-oap-server.log files of skywalking-oap in k8s pod.  checking the log4j2.xml of the pod，i didn‘t see RollingFile Appenders 。The picture is below. I wonder if you designed it like this on purpose，if not ，Could you please tell me how to modify it to have log file output . THANKS .
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

JDK14，skywalking 8.2.0，application and skywalking are both deployed on k8s.
![a0507a8e0a20c936835e6debfc33257b4a4f18b9](https://user-images.githubusercontent.com/29948535/102291546-50dcaa00-3f7e-11eb-9868-fd2382b02263.png)

**Comment by kezhenxu94** [comment]
@ZhangDi-d I think that’s by design, Kubernetes services usually log to stdout and you can check them all (there may be many pods per service) with `kubectl log` conveniently, in your case it’s `kubectl -n istio-system logs -f $(kubectl get pod -A -l "app=skywalking,release=skywalking,component=oap" -o name)`, is it what you want?

**Comment by ZhangDi-d** [comment]
I think your suggestion may solve my doubt, thank you very much
