### ISSUE TITLE
Multiple applications sharing agent.jar package cause agent.jar to be modified

### ISSUE THREAD

**Issue by zhoujia916** [apache/skywalking#6015]
When i copy apache-skywalking-apm-bin/agent/* in version 8.1.0 to directory /apply/agent/skywalking-8.1.0/, and run multiple applications sharing agents by jdk8, as shown below: 
java -DSW_AGENT_NAME=AAA -javaagent:/apply/agent/skywalking-8.1.0/skywalking-agent.jar -jar xxx.jar

After running for a while, the property Last Modified Time of directory /apply/agent/skywalking-8.1.0/ is modifed, and skywalking-agent.jar is changed to 0 bytes

I wonder if multiple applications are allowed to share agents, and whether the agent will modify the skywalking-agent directory.

If sharing is allowed, how should it be configured.

thanks

**Comment by wu-sheng** [comment]
We have nothing related to this. Many users share the agent jar files. Check your own env.
