### ISSUE TITLE
Monitoring browser data not available.

### ISSUE THREAD

**Issue by glmemail** [apache/skywalking#6017]
- Why do you submit this issue?
When monitoring the browser, no relevant data was obtained.

___
### Question
**To monitor my browser, do the following steps.
1. Install "skywalking - client - JS" on the monitored machine.
2. Add register method in your own code.
But now the data is not available. What is the reason?**

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking8.3.0，centos7.4，jre1.8.2

- Which company or project?
bis

- What happened?
nothing

___
### Requirement or improvement
nothing

**Comment by wu-sheng** [comment]
Do you see the data report in your browser? Do you forward the data to OAP?
