### ISSUE TITLE
[Python] Revise plugins involved with http client, avoid recording password in url

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#6018]
Now some of the http client plugins record the `username:password` into the tag `peer` and `url`, this should be removed explicitly.

Example request url might be http://username:password@example.com

**Comment by taskmgr** [comment]
I'd like to do this.

**Comment by wu-sheng** [comment]
Ha, I think this kind of issue will be widely existing in all agent. Haven't know any agent or plugin to avoid this.

**Comment by Superskyyy** [comment]
Hello, I would like to take over this issue if @taskmgr is not available.

**Comment by kezhenxu94** [comment]
> Hello, I would like to take over this issue if @taskmgr is not available.

I think he hasn't started to work on this, @Superskyyy please go ahead.

**Comment by Superskyyy** [comment]
> Now some of the http client plugins record the `username:password` into the tag `peer` and `url`, this should be removed explicitly.
> 
> Example request url might be http://username:password@example.com

Should I remove the auth part entirely from url/peer or replace any `userabc:pwcde` with literal `username:password`? I feel like replacing may be a good choice too (I hope no one uses `password` as their actual password).  @kezhenxu94  @wu-sheng

**Comment by Superskyyy** [comment]
> @Superskyyy I don't see any point to replace them with placeholders, if we don't want to record them why bother to bring extra bytes to store and network load?

I see. 

I realize the passwords also appear in logs upon failure, I will also remove them there.
