### ISSUE TITLE
Agent segment have only one span ,Should we abandon this segment without parent or non-entrySpan.

### ISSUE THREAD

**Issue by scorus916** [apache/skywalking#6020]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
   
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
   when i use 8.3 skywalking . i get too many Segment only one span and this span is exit .because this segment from back process.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If you don't want, set up rules to ignore them
