### ISSUE TITLE
将skywalking的数据存储引擎换成mysql后 日志一致报错

### ISSUE THREAD

**Issue by io-better** [apache/skywalking#6021]
将skywalking从elasticsearch切换到mysql时，查看日志一致报 com.mysql.cj.jdbc.exceptions.MysqlDataTruncation 错误

我使用的是8.3.0版本

数据库配置：
storage:
  selector: ${SW_STORAGE:mysql}
  mysql:
      properties:
        jdbcUrl: ${SW_JDBC_URL:"jdbc:mysql://localhost:3306/skywalking"}
        dataSource.user: ${SW_DATA_SOURCE_USER:root}
        dataSource.password: ${SW_DATA_SOURCE_PASSWORD:root}
        dataSource.cachePrepStmts: ${SW_DATA_SOURCE_CACHE_PREP_STMTS:true}
        dataSource.prepStmtCacheSize: ${SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_SIZE:250}
        dataSource.prepStmtCacheSqlLimit: ${SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_LIMIT:2048}
        dataSource.useServerPrepStmts: ${SW_DATA_SOURCE_USE_SERVER_PREP_STMTS:true}
      metadataQueryMaxSize: ${SW_STORAGE_MYSQL_QUERY_MAX_SIZE:5000}
      maxSizeOfArrayColumn: ${SW_STORAGE_MAX_SIZE_OF_ARRAY_COLUMN:20}
      numOfSearchableValuesPerTag: ${SW_STORAGE_NUM_OF_SEARCHABLE_VALUES_PER_TAG:2}

日志报错信息：
2020-12-17 03:32:24,002 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 75 [pool-4-thread-1] ERROR [] - Data truncation: Data too long for column 'source_endpoint' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'source_endpoint' at row 1

2020-12-17 03:32:24,203 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 75 [DataCarrier.H2_ASYNCHRONOUS_BATCH_PERSISTENT.BulkConsumePool.0.Thread] ERROR [] - Data truncation: Data too long for column 'endpoint_id' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'endpoint_id' at row 1

**Comment by wu-sheng** [comment]
Please use English on the github.

**Comment by io-better** [comment]
I am using version 8.3.0 
oap server database config :
storage:
selector: ${SW_STORAGE:mysql}
mysql:
properties:
jdbcUrl: ${SW_JDBC_URL:"jdbc:mysql://localhost:3306/skywalking"}
dataSource.user: ${SW_DATA_SOURCE_USER:root}
dataSource.password: ${SW_DATA_SOURCE_PASSWORD:root}
dataSource.cachePrepStmts: ${SW_DATA_SOURCE_CACHE_PREP_STMTS:true}
dataSource.prepStmtCacheSize: ${SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_SIZE:250}
dataSource.prepStmtCacheSqlLimit: ${SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_LIMIT:2048}
dataSource.useServerPrepStmts: ${SW_DATA_SOURCE_USE_SERVER_PREP_STMTS:true}
metadataQueryMaxSize: ${SW_STORAGE_MYSQL_QUERY_MAX_SIZE:5000}
maxSizeOfArrayColumn: ${SW_STORAGE_MAX_SIZE_OF_ARRAY_COLUMN:20}
numOfSearchableValuesPerTag: ${SW_STORAGE_NUM_OF_SEARCHABLE_VALUES_PER_TAG:2}

log error info:
2020-12-17 03:32:24,002 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 75 [pool-4-thread-1] ERROR [] - Data truncation: Data too long for column 'source_endpoint' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'source_endpoint' at row 1


Should I pull the code and compile it myself to solve this problem?

**Comment by wu-sheng** [comment]
We have set the length limitation for the endpoint. I am not sure what is your case.

**Comment by io-better** [comment]
where is the init sql script

**Comment by wu-sheng** [comment]
Generated in codes.

**Comment by zxz-hash** [comment]
我也遇到这个问题  请问解决了吗
