### ISSUE TITLE
UI 中的得分计算方法是否精确

### ISSUE THREAD

**Issue by bufx** [apache/skywalking#6023]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
UI 中的得分计算方法是否精确，是不是先计算总和除以10000\*个数，而不是每个先除以10000\*1然后在取平均数。
![](https://gitee.com/bufx/oss/raw/master/uPic/DnSqMt1608195260159.png)
___
### Bug
- Which version of SkyWalking, OS, and JRE?
   - Skywalking:7.0.0
   - OS：Centos7
   - JRE：jdk8
- Which company or project?
个人
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please use English on GitHub.

**Comment by bufx** [comment]
Okay thank you

**Comment by bufx** [comment]
> Please use English on GitHub.

Okay thank you
