### ISSUE TITLE
Why only grpc to send trace data, not http? 

### ISSUE THREAD

**Issue by lijial** [apache/skywalking#6027]
Hi SkyWalking team

As I choose SkyWalking to trace, Some question confuse me
___
### Question

In   v5.0.0-beta2  , there is  embed jetty, javaagent could send tracedata to collector use http
In   v6.0.0-GA and later versions, there is only grpc . 
Why remove jetty/http? 
Is the reason only grpc performance better? 
Now can I use http to send tracedata? is there any worse situation from http?

**Comment by wu-sheng** [comment]
> Why remove jetty/http?

You are not following the latest, it is back, but we only recommend for the languages don't support grpc.

> Is the reason only grpc performance better?

Yes, much much better than JSON based HTTP.

> Now can I use http to send tracedata? is there any worse situation from HTTP?

Send, I don't know, that depends on the agent or SDK. As OAP server, we support that.

**Comment by lijial** [comment]
>Now can I use http to send tracedata? is there any worse situation from HTTP?
Deal wu-sheng, Thanks for reply , as this question I should not understand your answer, 
As I use 8.4.0  ,  I can use http?  And you support to use http? 
Are there still several kind of agent ? 
As I only know only one agent and OAP server...

**Comment by kezhenxu94** [comment]
@lijial if you mean to send the data in Java agent with HTTP, it's not supported, for Java agent, we only support gRPC.

The OAP backend can receive HTTP data because some languages are hard to use gRPC, Nginx Lua for example

**Comment by lijial** [comment]
@wu-sheng 
> @lijial if you mean to send the data in Java agent with HTTP, it's not supported, for Java agent, we only support gRPC.
> 
> The OAP backend can receive HTTP data because some languages are hard to use gRPC, Nginx Lua for example

OK，this is what I wanna know. And 8.4.0 version not support javaagent using HTTP either?

**Comment by wu-sheng** [comment]
I think that would be never due to no reason to do this.

**Comment by lijial** [comment]
> I think that would be never due to no reason to do this.

As our company use skywalking but grpc not stable in some situation. So I wanna change the grpc to http.
If it's just performance, and our flow is  low as 10k/s. 
Should I change the agent to use http? 
Is it necessary for safety and stability for me to do so？

**Comment by wu-sheng** [comment]
I don't know what do you mean grpc is not stable. But from my understanding, it is really widely adopted. You could change the codes by yourself, for stability, that depends on your codes only.

**Comment by lijial** [comment]
> I don't know what do you mean grpc is not stable. But from my understanding, it is really widely adopted. You could change the codes by yourself, for stability, that depends on your codes only.

OK，I know, thankyou
And is there SPI interface  in javaagent, Easy for me to extend data transmission using http?

**Comment by wu-sheng** [comment]
See how Kafak reporter works. It is the same way for other reporters.
