### ISSUE TITLE
Hello, I am developing skywalking on the company's intranet, and an error occurs when compiling the source code: UnknownHostException: repo.maven.apache.org, how can I solve this?

### ISSUE THREAD

**Issue by goodjuan-xj** [apache/skywalking#6028]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Sorry, this is out of the community's scope. The internal environment is complex.
