### ISSUE TITLE
[OPERATOR]Agent injection webhook

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#6029]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
___
### Requirement or improvement
SWCK operator supports provisioning skywalking backends to a kubernetes cluster. However, the agent that generally refer to java, C#, python, and nodejs automatic instruments is the last piece of the puzzle. 

After a long period of discussion and investigation, we have a plan to introduce a new webhook to inject agent images to workload pods **automatically**(by the **`operator`**) or **manually**(by **`swctl`**). 

A canonical path to trigger auto-injection is to insert dedicated **annotations** to workloads and namespaces, then **`operator`** intercepts the provision of their pods, injecting agent relevant pieces into pod template. The result of injection might like below:

<img width="653" alt="WechatIMG62" src="https://user-images.githubusercontent.com/1960537/102572664-a7d1b300-4127-11eb-8b11-bbf852cb39cb.png">

**Comment by wu-sheng** [comment]
Does this mean, we are going to release agent images separately? If so, seems there are several things to adjust the release processes and docker files.

**Comment by hanahmily** [comment]
> Does this mean, we are going to release agent images separately? If so, seems there are several things to adjust the release processes and docker files.

Exactly. The basic idea of images is to follow the backend convention. That means putting agent manifests into the `skywalking-docker` repo, releasing agent images as one step of the entire image release process, documenting the new images on the `README.md` of `skywalking-docker`, the official docker hub repo and skywalking website.

**Comment by wu-sheng** [comment]
The key is you need to adjust main repo docker file, to make sure they are voted in the release. Your mentioned things are after release.

**Comment by hanahmily** [comment]
> The key is you need to adjust main repo docker file...

I didn't find any reason to introduce the agent docker file into the main repo. The E2E of webhook will be added into `swck` repo with the agent docker image built from a released agent version. 

Even though we submit it into the main repo, it seems nothing special should be taken care of in the release vote process? If I missed something, feel free to correct me.

**Comment by wu-sheng** [comment]
If the docker file is never voted, then images can't be pushed as it is not an official release source codes.

**Comment by wu-sheng** [comment]
> I didn't find any reason to introduce the agent docker file into the main repo. 

Only reason is, this image will need to push with every release. This is a requirement from a release vote perspective.

**Comment by kagaya85** [comment]
Hi there, I am interested in this issue and would like to participate in contributing code to SkyWalking through the opensource summer 2021 project. I prepared a technical proposal and wanted to further discuss the specific implementation with mentor of this issue. I tried to send an email but didn't get a reply, thanks very much if someone could tell me how to get involved in the work😀.

**Comment by wu-sheng** [comment]
@hanahmily I think it is on your hands, right?

**Comment by hanahmily** [comment]
@kagaya85 I have not received messages from you. Since several students who want to join iscas have contacted with me, you seem to send the wrong address. My mail address is `hanahmily@apache.org` or `hanahmily@gmail.com`. 

We could discuss the details through the mail.

**Comment by kagaya85** [comment]
@hanahmily Thank you very much, I will try again to submit my application.

**Comment by kezhenxu94** [comment]
Resolved by https://github.com/apache/skywalking-swck/pull/30
