### ISSUE TITLE
[NodeJS] Add a git hook to lint the codes

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#6034]
Add a git hook to lint the codes in https://github.com/apache/skywalking-nodejs, using [husky](https://typicode.github.io/husky/#/)

**Comment by goat023** [comment]
I would like to contribute to this issue since I'm new here, could someone guide me?

**Comment by kezhenxu94** [comment]
> I would like to contribute to this issue since I'm new here, could someone guide me?

Sure. If you have any question, feel free to ask and ping me, I'm glad to help

**Comment by WHYSOS** [comment]
Node.js how to use import agent from 'skywalking-backend-js'.We usually use require().Thank

**Comment by kezhenxu94** [comment]
> Node.js how to use import agent from 'skywalking-backend-js'.We usually use require().Thank

`const Agent = require('skywalking-backend-js').default;`

Next time, please create your own issue instead of commenting on an irrelevant issue

**Comment by kezhenxu94** [comment]
@goat023 are you still working on this ?

**Comment by ruleeeer** [comment]
Is this issue still valid?

**Comment by kezhenxu94** [comment]
> Is this issue still valid?

Yes. If you'd like to contribute. Feel free to open a PR

**Comment by ruleeeer** [comment]
> > Is this issue still valid?
> 
> Yes. If you'd like to contribute. Feel free to open a PR

yeah,let me try

**Comment by wu-sheng** [comment]
Is this done?

**Comment by wu-sheng** [comment]
This one, https://github.com/apache/skywalking-nodejs/pull/66?
