### ISSUE TITLE
how to  link the profile result with the business log  and async task using java

### ISSUE THREAD

**Issue by beijingzhangwei** [apache/skywalking#6043]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- What do you want to know?
-First Question: Is skywalking support log(business log) collect. Like alibaba's arms link the profile result with the business log.
-Second Question:  In java project, business logic process use thread pool,  how to bind traceContext to the task? and how to  analysis the async thread pool task consuming.  like cost ?

**Comment by wu-sheng** [comment]
> -First Question: Is skywalking support log(business log) collect. Like alibaba's arms link the profile result with the business log.

Please don't involve a commercial product in, that is not a reference for an open-source project. 
1. Collecting logs in traces has been supported, and will be released in 8.4.0, you could read docs/en/setup/service-agent/java-agent/agent-optional-plugins/Logger-plugin.md
2. If you want a better way, lower load to your application(agent), consider waiting for the satellite release in 2021, https://github.com/apache/skywalking-satellite

> -Second Question: In java project, business logic process use thread pool, how to bind traceContext to the task? and how to analysis the async thread pool task consuming. like cost ?

Across thread solution has been provided for a long time, https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-trace-cross-thread.md

Your questions are mostly included in the documentation. Please read them before submitting an issue.

**Comment by beijingzhangwei** [comment]
thx，we just want to reduce dependence on commercial product, so we coming.

**Comment by wu-sheng** [comment]
I know, but please let's keep discussion on tech perspective only.
