### ISSUE TITLE
The image in docs/en/setup/backend/backend-ui-setup.md 404 not found

### ISSUE THREAD

**Issue by infraio** [apache/skywalking#6044]
The url is http://skywalking.apache.org/doc-graph/communication-net.png. If I am not wrong, there should be a architecture image, such as http://skywalking.apache.org/assets/frame-v8.jpg?u=20200423 ?

**Comment by wu-sheng** [comment]
Thanks for reporting. I have added it back. We recently changed a lot on the website.
