### ISSUE TITLE
spring cloud gateway 2.2.1 for TraceContext.traceId() == "N/A"

### ISSUE THREAD

**Issue by stelin** [apache/skywalking#6050]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Normal request TraceContext.traceId() == "N/A" at spring cloud gateway 2.2.1，But spring boot project is ok!
___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking: 8.3.0
apm-toolkit-trace: 8.3.0

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please search the issue before submit new one.

**Comment by stelin** [comment]
I has searched!

**Comment by stelin** [comment]
How to solve this problem,Thanks

**Comment by wu-sheng** [comment]
Simple answer is, there is nothing to resolve. We never said, all threads will have trace id. 

The gateway is using the async-thread model, there could be many threads not in tracing status. So, N/A shows up.

**Comment by stelin** [comment]
Got it. Thought it was a bug for first use skywalking

Thanks!

**Comment by xiaoshi1994** [comment]
怎么解决呢？
