### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'services' of undefined

### ISSUE THREAD

**Issue by qianglu1989** [apache/skywalking#6051]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
 

___
### Question
Why did it report an error？

Uncaught (in promise) TypeError: Cannot read property 'services' of undefined

![image](https://user-images.githubusercontent.com/8486184/102838981-706e4980-443a-11eb-9952-42235145ae84.png)

___
### Requirement or improvement
version ：skywalking 8.3
jdk: 1.8

**Comment by wu-sheng** [comment]
Could you recheck this on the demo env?

**Comment by qianglu1989** [comment]
> Could you recheck this on the demo env?

Such as?

**Comment by wu-sheng** [comment]
It is on the website, https://skywalking.apache.org/#demo.

**Comment by qianglu1989** [comment]
> It is on the website, https://skywalking.apache.org/#demo.

I'm not sure what I need to configure for this UI. Could you please make it clear? Thank you

**Comment by wu-sheng** [comment]
What do you mean configure? I mean, if this is a code level issue, you should be able to see the error when you visit the demo SkyWalking, which is the same codes you are using.

**Comment by qianglu1989** [comment]
> What do you mean configure? I mean, if this is a code level issue, you should be able to see the error when you visit the demo SkyWalking, which is the same codes you are using.

我其实就想知道这个错误是什么问题导致的，我好去查查，你叫我看demo 有啥用，我当然知道你demo好使了

**Comment by wu-sheng** [comment]
I can't see what is error. How could I guess this?

**Comment by qianglu1989** [comment]
> I can't see what is error. How could I guess this?

Thanks a lot. I'll check again

**Comment by Lovnx** [comment]
@qianglu1989 
its a bug when u use elasticsearch as storage.

how to solve:
1、step to org.apache.skywalking.oap.server.storage.plugin.elasticsearch.query.MetadataQueryEsDAO
2、code line 239 replaces to:
  `service.setGroup(serviceTraffic.getGroup() == null ? "-" : serviceTraffic.getGroup());`
3、repackage storage-elasticsearch-plugin-8.3.0.jar and restart OAPserver
