### ISSUE TITLE
use influxdb identifier cause error

### ISSUE THREAD

**Issue by zhe1926** [apache/skywalking#6056]
### improvement
searchService method use influxdb identifier in sql when we use storage-influxdb-plugin.Put influxdb identifier in the middle of double quotation marks can solve this question.

![image](https://user-images.githubusercontent.com/13587931/102866269-f1950300-4471-11eb-85b5-b31d67364824.png)

**Comment by wu-sheng** [comment]
Could you submit a pull request directly?
