### ISSUE TITLE
[javaagent] agent.sample_n_per_3_secs config stands for TraceSegment?

### ISSUE THREAD

**Issue by lijial** [apache/skywalking#6061]
Dear skywalking team.
As I read skywalking agent code, **agent.sample_n_per_3_secs** this config stands for upper limit of TraceSegment, is it right?
As one TraceSegment can hold many spans, just suppose 1 TraceSegment has 3 spans, 
if **agent.sample_n_per_3_secs** set to 150, then the upper limit of spans has been 450.
Is it right?

**Comment by wu-sheng** [comment]
Yes, but span doesn't matter for SkyWalking, especially at the storage level.

**Comment by lijial** [comment]
@wu-sheng 
> Yes, but span doesn't matter for SkyWalking, especially at the storage level.
**agent.sample_n_per_3_secs** config cannot measure network flow accuracy
Even **agent.sample_n_per_3_secs** is numeric small , but the whole network flow has been numeric big. 
The more spans, the high network flow.
So I think agent.config need a new config **agent.spans_n_per_3_secs**

**Comment by wu-sheng** [comment]
Read the document, there is a config called `SPAN_LIMIT_PER_SEGMENT` to do this. But less spans could break your traces, do the client side tracing is not working because of this.

**Comment by lijial** [comment]
> Read the document, there is a config called `SPAN_LIMIT_PER_SEGMENT` to do this. But less spans could break your traces, do the client side tracing is not working because of this.

OK,I see, thank you
