### ISSUE TITLE
When the thread pool multiplies the same thread, the traceid obtained by the multiplexed thread is N/A

### ISSUE THREAD

**Issue by 18600454482** [apache/skywalking#6065]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
___
### Question
- What do you want to know?
When the thread pool multiplexes the same thread, the traceid obtained by the multiplexed thread is N/A, the non-multiplexed thread Traceid can output normally and be the same, the submitted task uses SupplierWrapper. Of () method wrapper. What might be the problem?
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
jdk-8、skywalking-8.3.0

**Comment by wu-sheng** [comment]
Read FAQ.
