### ISSUE TITLE
Whether the global data is affected by the sampling rate？

### ISSUE THREAD

**Issue by qianglu1989** [apache/skywalking#6067]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Whether the global data is affected by the sampling rate？
For example, the sample rate configuration is 30，Is the global statistics 100？ or 30？
![image](https://user-images.githubusercontent.com/8486184/103048830-d8539a00-45ca-11eb-922b-f4623f2782a1.png)

**Comment by wu-sheng** [comment]
If you are asking about backend sampling, no, it isn't. The metrics are accurate even in sampling mode

**Comment by qianglu1989** [comment]
> If you are asking about backend sampling, no, it isn't. The metrics are accurate even in sampling mode

666
