### ISSUE TITLE
skywalking client sample rate setting 

### ISSUE THREAD

**Issue by vperson** [apache/skywalking#6068]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- The skywalking agent is configured with agent.sample_n_per_3_secs=200, and there is still a lot of data seen on the server, and it is in the test environment, there should not be so much data.

**Comment by wu-sheng** [comment]
Sampling depends on downstream sampling mechanism. Read the codes, would be helpful.
