### ISSUE TITLE
I can't find class OALParserBaseListener

### ISSUE THREAD

**Issue by goodjuan-xj** [apache/skywalking#6069]
Please answer these questions before submitting your issue.

Question
What do you want to know?
how to build project from GitHub
Which version of SkyWalking, OS, and JRE?
SkyWalking v6.5.0 、 Windows7、 jdk8
What happened?
I can't find class OALParserBaseListener
![image](https://user-images.githubusercontent.com/55343457/103054277-e5758680-45d4-11eb-8797-f81852d42c32.png)
Requirement or improvement
Please describe your requirements or improvement suggestions.

**Comment by goodjuan-xj** [comment]
I can't find class OALParserBaseListener

**Comment by kezhenxu94** [comment]
That's generated, please run maven command to compile first
