### ISSUE TITLE
monitor the browser in IE 11,But monitor.js report an error 

### ISSUE THREAD

**Issue by zxz9325** [apache/skywalking#6070]
Please answer these questions before submitting your issue.

### Question
- What do you want to know?
I want to try to monitor the browser in IE 11.
- Which version of SkyWalking, OS, and JRE?
SkyWalking 8.3 、 Windows10、 jdk8、npm i skywalking-client-js 0.2.0
- What happened?
I want to try to monitor the browser in IE 11,But Internet Explorer does monitor.js report an error ：SCRIPT1003: lack':',the Google browser doesn't.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Could you provide demo to reproduce thjs error?

**Comment by Fine0830** [comment]
Ahah....Don't support IE, please use chrome.
