### ISSUE TITLE
why use 【collector.backend_service 】when skywalking have 【plugin.kafka.bootstrap_servers】

### ISSUE THREAD

**Issue by a1242902560** [apache/skywalking#6071]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Question or discussion
___
### Question
- What do you want to know?
   i have use kafka to fetch message,why  need use backend_service?
i have a problem with this url
https://github.com/apache/skywalking/blob/8.3.0/docs-hotfix/docs/en/setup/service-agent/java-agent/How-to-enable-kafka-reporter.md

**Comment by kezhenxu94** [comment]
@a1242902560 the link you posted have clearly stated the reason 

> Notice, currently, the agent still needs to configure GRPC receiver for delivering the task of profiling.
