### ISSUE TITLE
About TraceCrossThread ,think how to transport my threadLocal variables

### ISSUE THREAD

**Issue by beijingzhangwei** [apache/skywalking#6072]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- In SW i use TraceCrossThread make trace across thread. But I also want transport my threadLocal variables through threads, here  i make a nest wrapper callable ,like this : 
        Future<List<Users>> operationFuture = pool.submit(CallableWrapper.of(new ThreadLocalCallable(userWrapper::doRecall)));  

when  ThreadLocalCallable construct method was called, i record the  threadLocal variables  ,then   when userWrapper::doRecall was called i set the  threadLocal variables to the work thread context, so in doRecall method it can access the  threadLocal variables.

I want to known ,is there a better way to transport the threadLocal variables in SW? or should another annotation to permit transport  threadLocal variables ?

![image](https://user-images.githubusercontent.com/11971162/103061387-2d50d980-45e6-11eb-81de-d46c64d0f1e2.png)
[](url)

**Comment by wu-sheng** [comment]
I can't see there is the difference between the thing you described and native `TraceCrossThread`. If you are going to change source codes, what makes it better?
