### ISSUE TITLE
is:issue is:open 安装 skywalking 6.5在linux上 本身服务起来是必须需要jdk1.8是吗？1.6的不可以是吗？然后如果我们安装好后，可以在jdk1.6的服务里进行使用吗？ 

### ISSUE THREAD

**Issue by zhangchengchun** [apache/skywalking#6074]
一、我想在JDK1.6的环境里使用skywalking 6.5
1、安装skywalking时候必须使用jdk1.8吗？
2、若我用jdk1.8安装skywalking后可以在jdk1.6的服务里使用吗

**Comment by wu-sheng** [comment]
Please use English on the GitHub.
