### ISSUE TITLE
How to monitor apache web service from skywalking and its steps to follow if any?

### ISSUE THREAD

**Issue by Nirajkumar2626** [apache/skywalking#6076]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think you submit issue to a wrong place. Apache server is another project.

**Comment by wu-sheng** [comment]
We don't have anything related to that, AFAIK.
