### ISSUE TITLE
Skywalking Oap server Storage to elasticSearch-6.* failed

### ISSUE THREAD

**Issue by ZhouZiHe** [apache/skywalking#6078]
Recently We upgrade skywalking from 8.1.0 to 8.3.0 . Then we found problems , when we used 8.3.0 storage to elasticSearch .it current exception like this :
![image](https://user-images.githubusercontent.com/20511319/103081164-5b4c1300-4612-11eb-8ac3-8d419a8b47a6.png)
this is stack info :
![image](https://user-images.githubusercontent.com/20511319/103081247-8a628480-4612-11eb-879b-e4bb13aec830.png)
During this time, we began to deal with this problem .
finally , We used arthas to find the problem !!!
When storing to es , we print the logs as you see in the image below , it really is too length 
![image](https://user-images.githubusercontent.com/20511319/103083196-c7c91100-4616-11eb-846b-acd1090a4910.png)
Then we started to analyze the id , we find the really long part like this
![image](https://user-images.githubusercontent.com/20511319/103083735-1d51ed80-4618-11eb-9ab1-65ecee2d1f68.png)
It repeat once more ,but that is not an important problem !!!
The real problem is that when we decode this string , it is all of us oap server nodes' ip .
We deploy on k8s , so we have many pods to run the oap server node , and then current this problem .
thanks

**Comment by wu-sheng** [comment]
Why this ID is so long? There is a length control mechanism, do your team change some of them?
![image](https://user-images.githubusercontent.com/5441976/103088415-b4717200-4625-11eb-9754-96a362e3a45f.png)
