### ISSUE TITLE
mssql error

### ISSUE THREAD

**Issue by arronbin** [apache/skywalking#6080]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Caused by: org.apache.ibatis.executor.ExecutorException: Error preparing statement. Cause: java.lang.ClassCastException: org.apache.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement
at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:97)
at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
at sun.reflect.GeneratedMethodAccessor405.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
at com.sun.proxy.$Proxy320.update(Unknown Source)
at sun.reflect.GeneratedMethodAccessor405.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
at com.sun.proxy.$Proxy320.update(Unknown Source)
... 290 more

**Comment by wu-sheng** [comment]
I am not familiar with the ibatis codes, why it is trying to casting?

**Comment by wu-sheng** [comment]
Could you provide a demo app to reproduce the error?

**Comment by zifeihan** [comment]
Received, I will test and fix the bug as soon as possible.

**Comment by zifeihan** [comment]
> Please answer these questions before submitting your issue.
> 
> * Why do you submit this issue?
> * [ ]  Question or discussion
> * [ ]  Bug
> * [ ]  Requirement
> * [ ]  Feature or performance improvement
> 
> ### Question
> * What do you want to know?
> 
> ### Bug
> * Which version of SkyWalking, OS, and JRE?
> * Which company or project?
> * What happened?
>   If possible, provide a way to reproduce the error. e.g. demo application, component version.
> 
> ### Requirement or improvement
> * Please describe your requirements or improvement suggestions.
>   Caused by: org.apache.ibatis.executor.ExecutorException: Error preparing statement. Cause: java.lang.ClassCastException: org.apache.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement
>   at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:97)
>   at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
>   at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
>   at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
>   at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
>   at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
>   at sun.reflect.GeneratedMethodAccessor405.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
>   at com.sun.proxy.$Proxy320.update(Unknown Source)
>   at sun.reflect.GeneratedMethodAccessor405.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
>   at com.sun.proxy.$Proxy320.update(Unknown Source)
>   ... 290 more

@arronbin Sorry, I did not reproduce this problem, Could you provide a demo app to reproduce the problem?

**Comment by arronbin** [comment]
@zifeihan Debug finds that it is affected by the dynamic data source, but SkyWalking happend an error that affects the rollback of the main process transaction

**Comment by zifeihan** [comment]
> @zifeihan Debug finds that it is affected by the dynamic data source, but SkyWalking happend an error that affects the rollback of the main process transaction

Can you help us provide a simple demo to reproduce this bug? So that I can fix this problem as soon as possible.

**Comment by arronbin** [comment]
CREATE TABLE [dbo].[DEMO] (
[Id] bigint NOT NULL IDENTITY(1,1) ,
[CODE] varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
CONSTRAINT [PK__DEMO__3214EC27BF799427] PRIMARY KEY ([Id])
)
ON [PRIMARY]
GO

DBCC CHECKIDENT(N'[dbo].[DEMO]', RESEED, 8)
GO


package com.homedo.microservice.test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;

/**
 * @Auther: arronbin
 * @Date: 2021/1/5
 * @Description:
 */
public class MssqlTest {


    public static void main(String [] args)
    {
        Connection conn = null;
        PreparedStatement p = null;
       try {
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           conn = DriverManager.getConnection(
                   "jdbc:sqlserver://172.16.220.115:1433;databasename=TestDB", "Test",
                   "HMDTest321");
            p = conn.prepareStatement("insert into demo(code)values(?)",
                           Statement.RETURN_GENERATED_KEYS);
           p.setString(1, "test");
           p.executeUpdate();
       }catch (Exception e){
           System.out.println(e.getMessage());
       }finally {
          try {
              p.close();
              conn.close();
          }catch (Exception e){

          }
       }
    }


}


Similar to https://github.com/apache/skywalking/issues/554
@zifeihan @wu-sheng

**Comment by zifeihan** [comment]
> CREATE TABLE [dbo].[DEMO] (
> [Id] bigint NOT NULL IDENTITY(1,1) ,
> [CODE] varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
> CONSTRAINT [PK__DEMO__3214EC27BF799427] PRIMARY KEY ([Id])
> )
> ON [PRIMARY]
> GO
> 
> DBCC CHECKIDENT(N'[dbo].[DEMO]', RESEED, 8)
> GO
> 
> package com.demo.microservice.test;
> 
> import java.sql.Connection;
> import java.sql.DriverManager;
> import java.sql.PreparedStatement;
> import java.sql.Statement;
> 
> /**
> 
> * @auther: arronbin
> * @Date: 2021/1/5
> * @description:
>   */
>   public class MssqlTest {
>   public static void main(String [] args)
>   {
>   Connection conn = null;
>   PreparedStatement p = null;
>   try {
>   Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
>   conn = DriverManager.getConnection(
>   "jdbc:sqlserver://ip:1433;databasename=TestDB", "XX",
>   "XX");
>   p = conn.prepareStatement("insert into demo(code)values(?)",
>   Statement.RETURN_GENERATED_KEYS);
>   p.setString(1, "test");
>   p.executeUpdate();
>   }catch (Exception e){
>   System.out.println(e.getMessage());
>   }finally {
>   try {
>   p.close();
>   conn.close();
>   }catch (Exception e){
>   ```
>      }
>   }
>   ```
>   
>   
>   }
> 
> }
> 
> Similar to #554
> @zifeihan @wu-sheng

@arronbin Thank you very much, I will fix it as soon as possible.
