### ISSUE TITLE
web ui configuration

### ISSUE THREAD

**Issue by zender-projects** [apache/skywalking#6092]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I update the chart configuration of Service tag,(use the lock on the he top left-hand corner)
it was effective in my local browser, but not in my colleague‘s computer, i don't know why ..... 
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> I update the chart configuration of Service tag,(use the lock on the he top left-hand corner)
it was effective in my local browser, but not in my colleague‘s computer, i don't know why .....

Because it is locally only. If you want to update the default configuration, use the files in the ui-initialized-templates
