### ISSUE TITLE
ThreadPoolTaskExecutor.executor(new Runnable()) done not show in skywalking UI

### ISSUE THREAD

**Issue by lijial** [apache/skywalking#6095]
Dear skywalking team
My code is springboot http GET method, in http method, I call ThreadPoolTaskExecutor.execute(new Runnable()).
code as the pic below
![image](https://user-images.githubusercontent.com/4213303/103255662-20a4fa80-49c5-11eb-95e3-67bb1025d396.png)

When I use skywalking, I notice there is no Runnable trace in UI result , there's only http method as pic show.
![image](https://user-images.githubusercontent.com/4213303/103255507-85138a00-49c4-11eb-91f8-c77d5f616581.png)

My question is, is this the correct result in skywalking ? in http request, the Runnable method in ThreadPoolTaskExecutor.executor() dose not show?

**Comment by wu-sheng** [comment]
Read `If you want to continue traces across thread manually, use across thread solution APIs.` doc in the agent setup doc, https://github.com/apache/skywalking/blob/v8.3.0/docs/en/setup/service-agent/java-agent/README.md#advanced-features-1

**Comment by lijial** [comment]
@wu-sheng I see, this method could solve threadpool monitor. But this could make so very invasive to business code compare with only  -javaagent  jvm parameters. 
For if I new Runnable() with Anonymous object, I could not use @TraceCrossThread annotation. Only I should do is to try implemetation of Runnable and put it to threadpool. A little complex to use I think.
Am I think is correct and comprehensive？And is there any solution for easy monitor threadpool?

**Comment by wu-sheng** [comment]
They provided `RunnableWrapper.of` for you. Thread is widely used, agent can't do the dark magic.
