### ISSUE TITLE
delete outdated data manually

### ISSUE THREAD

**Issue by ZhangDi-d** [apache/skywalking#6096]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Hi, I have encountered a dilemma. My storage elasticsearch may not support the data input of skywalking very well.
I cannot scale out es at present, and I have no opportunity to upgrade skywalking . So,I wanna delete some outdated data ,
My Question is , If the data of the first few days is deleted (such as *20201226,*20201225... in the picture below), will skywaking  still work normally? 
AND , do you honor ever think add a BUTTON in the UI that users can clean up outdated data by the button?

Thanks to the outstanding skywalking.

___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking 8.0.1 ,JDK 14, elasticsearch7.6 as storage
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by ZhangDi-d** [comment]
![96d3f17b9a177fe4c5501aca03ab8d338d27a4d7](https://user-images.githubusercontent.com/29948535/103257418-19cdb600-49cc-11eb-8923-aaed0d115be8.png)

**Comment by wu-sheng** [comment]
There are setting(s) called **TTL** for these from beginning. Read the doc of your version.
