### ISSUE TITLE
UI enhancement for quick search by service name

### ISSUE THREAD

**Issue by muqp** [apache/skywalking#6097]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to access the page of trace.But the url is always http://ip:port/trace.I want to access the trace of specified service.Is there a way access trace such as http://ip:port/trace?servicename.
![image](https://user-images.githubusercontent.com/52477868/103260947-96679100-49da-11eb-8597-4a9a618d7911.png)

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We don't support that. Contributions are welcome.

**Comment by muqp** [comment]
> We don't support that. Contributions are welcome.

Thank you.
