### ISSUE TITLE
Don't understand the code in HTableInterceptor.

### ISSUE THREAD

**Issue by xiangwangcheng** [apache/skywalking#6099]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ✔️] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I wonder what these codes for？
Just set tracing context infos to operation. I don't see the operation is used anywhere.
![image](https://user-images.githubusercontent.com/8049014/103295519-1cadc280-4a2f-11eb-8a52-7f644da2ccbd.png)

**Comment by wu-sheng** [comment]
ContextCarrier is for cross-process propagation. If one day, we provide HBase server plugin, the trace could continue at the server side.
