### ISSUE TITLE
[NodeJS] Agent getting error in 0.1.0 release that wasn't there before release

### ISSUE THREAD

**Issue by tom-pytel** [apache/skywalking#6100]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug

I am now getting the following in release version 0.1.0 in a test which was working fine just before release:
```js
{
  file: '/home/tom/src/revdebugjs/skywalking-nodejs/lib/agent/protocol/grpc/clients/TraceReportClient.js',
  code: 12,
  metadata: Metadata {
    _internal_repr: {
      server: [ 'nginx/1.16.1' ],
      date: [ 'Tue, 29 Dec 2020 21:23:12 GMT' ],
      'content-length': [ '0' ]
    },
    flags: 0
  },
  details: 'Method not found: skywalking.v3.TraceSegmentReportService/collect',
  level: 'error',
  message: 'Failed to report trace data12 UNIMPLEMENTED: Method not found: skywalking.v3.TraceSegmentReportService/collect',
  stack: 'Error: 12 UNIMPLEMENTED: Method not found: skywalking.v3.TraceSegmentReportService/collect\n' +
    '    at Object.exports.createStatusError (/home/tom/src/revdebugjs/skywalking-nodejs/node_modules/grpc/src/common.js:91:15)\n' +
    '    at Object.onReceiveStatus (/home/tom/src/revdebugjs/skywalking-nodejs/node_modules/grpc/src/client_interceptors.js:1238:28)\n' +
    '    at InterceptingListener._callNext (/home/tom/src/revdebugjs/skywalking-nodejs/node_modules/grpc/src/client_interceptors.js:568:42)\n' +
    '    at InterceptingListener.onReceiveStatus (/home/tom/src/revdebugjs/skywalking-nodejs/node_modules/grpc/src/client_interceptors.js:618:8)\n' +
    '    at /home/tom/src/revdebugjs/skywalking-nodejs/node_modules/grpc/src/client_interceptors.js:925:18\n' +
    '    at callbackTrampoline (internal/async_hooks.js:126:14)'
}
```

Any changes made which might explain this?

**Comment by wu-sheng** [comment]
@tom-pytel Do you update the submodule locally? This error is caused by a backend protocol upgrade. Once the SkyWalking 8.4.0 released, the new protocol will be supported(namespace `skywalking.v3` added). At the same time, the existing no-namespace protocol is supported. 
I checked the submodule of repo https://github.com/apache/skywalking-nodejs, it is targeting only protocol, which should only include the namespace.

Check your local `tracing.proto` in the protocol folder folder. I checked the file of the release, https://dist.apache.org/repos/dist/dev/skywalking/node-js/0.1.0/. It seems correct.

**Comment by wu-sheng** [comment]
Also, I checked e2e test in the main repo, https://github.com/apache/skywalking/blob/f4b739c26b6cbf8272abee8cadef13230de45358/test/e2e/e2e-test/docker/nodejs/Dockerfile.nodejs#L18, which targeting the last code commit, and test passed with the dev version of OAP backend.

**Comment by kezhenxu94** [comment]
The protocol sub module is pinned to an old version (https://github.com/apache/skywalking-data-collect-protocol/tree/24788cf41807048dcbe8dba0958688aaaf630d73), while the error is only possible in recent version, make sure you didn't update it locally

**Comment by tom-pytel** [comment]
> The protocol sub module is pinned to an old version (https://github.com/apache/skywalking-data-collect-protocol/tree/24788cf41807048dcbe8dba0958688aaaf630d73), while the error is only possible in recent version, make sure you didn't update it locally

Yes I did update the protocol submodule so that is obviously the cause, my bad, went back to the pinned commit and all works fine. Though I updated because I was getting another error which was not present pre-release:
```js
{
  file: '/home/tom/src/revdebugjs/skywalking-nodejs/lib/agent/protocol/grpc/clients/TraceReportClient.js',
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'DNS resolution failed',
  level: 'error',
  message: 'Failed to report trace data14 UNAVAILABLE: DNS resolution failed',
  stack: 'Error: 14 UNAVAILABLE: DNS resolution failed\n' +
    '    at Object.exports.createStatusError (/home/tom/src/revdebugjs/skywalking-nodejs/node_modules/grpc/src/common.js:91:15)\n' +
    '    at Object.onReceiveStatus (/home/tom/src/revdebugjs/skywalking-nodejs/node_modules/grpc/src/client_interceptors.js:1238:28)\n' +
    '    at InterceptingListener._callNext (/home/tom/src/revdebugjs/skywalking-nodejs/node_modules/grpc/src/client_interceptors.js:568:42)\n' +
    '    at InterceptingListener.onReceiveStatus (/home/tom/src/revdebugjs/skywalking-nodejs/node_modules/grpc/src/client_interceptors.js:618:8)\n' +
    '    at /home/tom/src/revdebugjs/skywalking-nodejs/node_modules/grpc/src/client_interceptors.js:925:18\n' +
    '    at callbackTrampoline (internal/async_hooks.js:126:14)'
}
```
This was odd and I traced it down to the agent init code:
```js
agent.start({
  serviceName: '',
  serviceInstance: '',
  collectorAddress: '',
  authorization: '',
  maxBufferSize: 1000,
});
```
Having the `collectorAddress` as an empty string causes this. This worked fine before release but does not now, which is odd and I am not quite sure how it worked before. But it does not now the current README specifies this as the proper way to initialize.

**Comment by kezhenxu94** [comment]
> This worked fine before release but does not now, which is odd and I am not quite sure how it worked before

That was a bug actually, it should not have worked before. This is because the `GrpcProtocol` was initialized too early, even before `agent.start`, so that when the `collectorAddress` was overrode to be empty string, the connection had been established. The fact that `GrpcProtocol` being initialized too early will make the options here (in `agent.start`) not work, that was fixed just before 0.1.0

> But it does not now and the current README specifies this as the proper way to initialize.

That's what I didn't expect that users will just copy and paste without modification of these values :(

**Comment by tom-pytel** [comment]
> > But it does not now and the current README specifies this as the proper way to initialize.
> 
> That's what I didn't expect that users will just copy and paste without modification of these values :(

I assumed an empty string indicates a null value meaning default should be used. Other people may assume the same so maybe the README should be clarified?

**Comment by kezhenxu94** [comment]
> > > But it does not now and the current README specifies this as the proper way to initialize.
> > 
> > 
> > That's what I didn't expect that users will just copy and paste without modification of these values :(
> 
> I assumed an empty string indicates a null value meaning default should be used. Other people may assume the same so maybe the README should be clarified?

Make sense to me. https://github.com/apache/skywalking-nodejs/pull/17 @tom-pytel can you review this
