### ISSUE TITLE
[NIGNX-LUA] Add a method "destroyBackendTimer" to stop reporting metrics?

### ISSUE THREAD

**Issue by spacewander** [apache/skywalking#6101]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

Currently we can start a backend timer to report metrics, but there is no way to stop the timer. It would be great if we can solve via adding a new method to stop timer and clean up unreported data, so that we can solve problem like https://github.com/apache/apisix/issues/2895

**Comment by wu-sheng** [comment]
Make sense to add this method. I think the idea is due to the plugin could be disabled dynamically in the APISIX, right?
