### ISSUE TITLE
javaagent property key has not traced parameters info

### ISSUE THREAD

**Issue by ZovenCraig** [apache/skywalking#6106]
I have set property keys like : 
-javaagent:/opt/apm/skywalking-agent/skywalking-agent.jar -Dplugin.feign.collect_request_body=true -Dplugin.jdbc.trace_sql_parameters=true -Dplugin.mysql.trace_sql_parameters=true -Dplugin.tomcat.collect_http_params=true -Dplugin.springmvc.collect_http_params=true -Dplugin.httpclient.collect_http_params=true
but in fact, these info have not be traced 

version 8.3.0
centos 7.0
jdk 1.8
spring cloud 2

**Comment by wu-sheng** [comment]
Read the documentation, you are using the wrong name. System property name is not as same as the System ent.

**Comment by ZovenCraig** [comment]
> Read the documentation, you are using the wrong name. System property name is not as same as the System env.

set in os env variable?

**Comment by wu-sheng** [comment]
Again, read the document. https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Setting-override.md

**Comment by ZovenCraig** [comment]
> Again, read the document. https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Setting-override.md

orz.I used the wrong prefix, thanks.
