### ISSUE TITLE
Failed to submit a listener notification task. Event loop shut down?

### ISSUE THREAD

**Issue by qianglu1989** [apache/skywalking#6107]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

 `
-|2020-12-30 16:35:36.456|ERROR|TID:N/A|oap-netty-server-worker|o.a.s.a.d.i.n.u.c.D.rejectedExecution.log:606-Failed to submit a listener notification task. Event loop shut down? java.lang.OutOfMemoryError: unable to create new native thread at java.lang.Thread.start0(Native Method) at java.lang.Thread.start(Thread.java:717) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.ThreadPerTaskExecutor.execute(ThreadPerTaskExecutor.java:32) at org.apache.skywalking.apm.dependencies.io.netty.util.internal.ThreadExecutorMap$1.execute(ThreadExecutorMap.java:57) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor.doStartThread(SingleThreadEventExecutor.java:978) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:947) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:830) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183) at org.apache.skywalking.apm.dependencies.io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) at org.apache.skywalking.apm.dependencies.io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) at org.apache.skywalking.apm.agent.core.client.AgentNettyClient.start(AgentNettyClient.java:112) at org.apache.skywalking.apm.agent.core.client.AgentNettyClient$2$1.run(AgentNettyClient.java:131) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) at org.apache.skywalking.apm.dependencies.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at java.lang.Thread.run(Thread.java:748)
`

why???????
_

**Comment by wu-sheng** [comment]
Doesn't it say `java.lang.OutOfMemoryError`?
