### ISSUE TITLE
Adopt the INFRA VM/Machine monitoring

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6108]
Since @hanahmily brings the OpenTelemetry receiver in the SkyWalking's landscape, now we could move on to the new territory, this time, VM/Machine Infrastructure.

@wankai123 pinged me about he wants to take part in this. FYI @hanahmily @kezhenxu94 cc @apache/skywalking-committers 

In the implementation, I prefer, Prometheus eco-system agents -> OpenTelemetry collector --(OC format)--> OAP server. 
Such as Prometheus node exporter, https://prometheus.io/docs/guides/node-exporter/
@hanahmily agree?

---
~~At the backend side, we need to add a new `vm_traffic` to represent VMs and Machines, which should include~~
~~1. name, entity id. IDManager should implement this.~~
~~2. tags (JsonObject properties), like InstanceTraffic implemented.~~

~~The key point of this is adding aggregation capability for MAL core. From my understanding the key point is adding `SampleFamily#vm` for new entity context, also `Analyzer#generateTraffic` should be enhanced to support the new aggregation type.~~

~~After above finish, the UI(cc @Fine0830) will add a new kind of dashboard called `Infrastructure `, which just query `VM` list. NOTE, this is a query-protocol level change.~~

---
Based on https://github.com/apache/skywalking/issues/6108#issuecomment-758311084, the change proposal in the above block is not necessary. Updated at Jan. 12th 2021.

@wankai123 If you have any question, please discuss at here.

**Comment by wankai123** [comment]
I'm ready to start

**Comment by wu-sheng** [comment]
@mrproliu @wankai123 I was thinking about the VM entity for a while, when you were adopting the protocol/format.
I think as far as we have adopt the group concept in the naming format, we could simply use `vm::`/`network::`/etc. as the standard prefix when we need to monitor infra entities. All VM or network entity could be treated as service. By that, we don't need to add the VM concept in the core, which impacts the query, which is very complex. 
Also, we could support VM level topology once we have the data.

WDYT?
