### ISSUE TITLE
Deploy Istio Observability on the demo.skywalking.apache.org

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6119]
I and @kezhenxu94 had a discussion, because SkyWalking is more and more natively closing to Istio ecosystem, we plan to deploy Istio + ALS/MetricsService activated + OAP in the `demo.skywalking.apache.org`.

We have the agent + VM deployment already, which could keep unchanged. At the same time, we will deploy another cluster of OAP for Istio observability. Both SkyWalking clusters plan to share the same ES cluster and UI, which would make the metrics from both typical scenarios available for users.

One key thing is, all monitored service on the Istio deployment should use `istio` as group name. Then, with the latest UI, we could have topology for VM and Istio, which is cooler. :)

**Comment by kezhenxu94** [comment]
Done, related UI enhancement / bug fixes will be updated routinely
