### ISSUE TITLE
which branch for version 8.1?

### ISSUE THREAD

**Issue by zender-projects** [apache/skywalking#6122]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ -] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I will compile the source code for 8.1, but i dose not know which batch is matching with version 8.1
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
All releases are tagged.

**Comment by zender-projects** [comment]
> All releases are tagged.

git  it, thanks .
