### ISSUE TITLE
Collect Log with java agent

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#6127]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### discussion
Collect the java logs with the java agent.

There is a point in the feature, which it should have 2 gRPC channels to send data. one is the original gRPC channel to directly send trace data to the OAP server, another channel is the optional gRPC client to send the log to the Satellite.  
@elk-g

**Comment by zifeihan** [comment]
There is a question, will it cause relatively large performance overhead or network bandwidth problems for business applications? Or we need to define the level of collecting logs on the agent?

**Comment by wu-sheng** [comment]
@zifeihan @EvanLjp Could you take a look at existing log collection plugin, recently added.
We should enhance it rather than building a new one. Speaking about the channel, I prefer separate channel is an optional feature for the plugin. Because not all people are going to use satellite.

**Comment by EvanLjp** [comment]
> There is a question, will it cause relatively large performance overhead or network bandwidth problems for business applications? Or we need to define the level of collecting logs on the agent?

1. The extension plugins is an appender plugin for log framework, such as Logback. The collected logs could be controlled by logback.xml by loggers or level. So the agent should not care about which logs should be collected. 
2. For the performance, In the future Satellite will support file reading, but for cloud disk mount, there will still be network consumption, so the first version prefers to use localhost network transfer to deliver the log data. I have no relevant experience in network performance testing, which I will learn about in the near future.

**Comment by zifeihan** [comment]
> @zifeihan @EvanLjp Could you take a look at existing log collection plugin, recently added.
> We should enhance it rather than building a new one. Speaking about the channel, I prefer separate channel is an optional feature for the plugin. Because not all people are going to use satellite.

Okay, let me take a look first.

**Comment by zifeihan** [comment]
> > There is a question, will it cause relatively large performance overhead or network bandwidth problems for business applications? Or we need to define the level of collecting logs on the agent?
> 
> 1. The extension plugins is an appender plugin for log framework, such as Logback. The collected logs could be controlled by logback.xml by loggers or level. So the agent should not care about which logs should be collected.
> 2. For the performance, In the future Satellite will support file reading, but for cloud disk mount, there will still be network consumption, so the first version prefers to use localhost network transfer to deliver the log data. I have no relevant experience in network performance testing, which I will learn about in the near future.

I am worried that the log is too large and frequent. We can configure another level in the agent. For example, if it is not configured, it will be consistent with logback.xml. If it is configured, we can filter it once. Perhaps this level can be dynamically adjusted.

**Comment by wu-sheng** [comment]
> I am worried that the log is too large and frequent. We can configure another level in the agent. For example, if it is not configured, it will be consistent with logback.xml. If it is configured, we can filter it once. Perhaps this level can be dynamically adjusted.

Take a look, it is already there. That is why I am asking for enhancing the existing plugin rather than writing a new one.

**Comment by zifeihan** [comment]
> > I am worried that the log is too large and frequent. We can configure another level in the agent. For example, if it is not configured, it will be consistent with logback.xml. If it is configured, we can filter it once. Perhaps this level can be dynamically adjusted.
> 
> Take a look, it is already there. That is why I am asking for enhancing the existing plugin rather than writing a new one.

Get it, Log-plugin has made certain filtering rules, we can enhance it.
