### ISSUE TITLE
my question about agent

### ISSUE THREAD

**Issue by zxz9325** [apache/skywalking#6130]
I want to analyze the value carried in a header in a request from SpringMVC. Does SkyWalking support that?Or do you need to develop your own plugins?Can you give me some ideas? thanks

**Comment by wu-sheng** [comment]
What do you analyze? Do you want to save the headers in the trace or something?

**Comment by zxz9325** [comment]
For example, with some user information in the header, Skywalking intercepts requests and custom extensions to save user information, which can then be analyzed to specify the user's call chain.Something like that. Thanks

**Comment by wu-sheng** [comment]
Take a look at `plugin.http.include_http_headers` in https://github.com/apache/skywalking/blob/v8.3.0/docs/en/setup/service-agent/java-agent/README.md#table-of-agent-configuration-properties
