### ISSUE TITLE
oap-server support opentelemetry-go data?

### ISSUE THREAD

**Issue by ylywyn** [apache/skywalking#6135]
- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
oap-server support opentelemetry-go data?

**Comment by wu-sheng** [comment]
We don't accept the data. We did several times of try about Jaeger and Zipkin format traces, it isn't native enough to provide the analysis features. We adopt opentelemetry metrics, but trace, from my understanding, there are gaps in design perspective.

**Comment by ylywyn** [comment]
thanks!
