### ISSUE TITLE
ReadWriteSafeCache simultaneous read-write support

### ISSUE THREAD

**Issue by andyzzl** [apache/skywalking#6136]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___

### Requirement or improvement
- Please describe your requirements or improvement suggestions.

Currently, `ReadWriteSafeCache` holds two buffer pointers to read-buffer and write-buffer respectively. Writer thread write data to write-buffer, while reader thread read data from read-buffer. Pointers will be swapped after reading finished. All operations are controlled by one single `ReentrantLock`. As follows:

```java
public void write(List<T> data) {
    lock.lock();
    try {
        data.forEach(writeBufferPointer::accept);
    } finally {
        lock.unlock();
    }
}

public List<T> read() {
    lock.lock();
    try {
        // Switch the read and write pointers, when there is no writing.
        BufferedData<T> tempPointer = writeBufferPointer;
        writeBufferPointer = readBufferPointer;
        readBufferPointer = tempPointer;

        return readBufferPointer.read();
    } finally {
        lock.unlock();
    }
}
```

I'm confused that why two buffers are used here. It seems like one single buffer can do the same job. Maybe the switchable buffers here are used for simultaneous read-write. But it's not possible with only one lock, cause all operations to `ReadWriteSafeCache` are blocked.

To support simultaneous read-write, I synchronize the operations with two locks, and move the swapping operations to writing method, just after writing operation is finished, only if read-buffer is empty. As follows:

```
public void write(List<T> data) {
    writeBufferLock.lock();
    try {
        data.forEach(writeBufferPointer::accept);
        try {
            readBufferLock.lock();
            if (readBufferPointer.isEmpty()) {
                switchPointers();
            }
        } finally {
            readBufferLock.unlock();
        }
    } finally {
        writeBufferLock.unlock();
    }
}

public List<T> read() {
    readBufferLock.lock();
    try {
        return readBufferPointer.read();
    } finally {
        readBufferLock.unlock();
    }
}

private void switchPointers() {
    BufferedData<T> tempPointer = writeBufferPointer;
    writeBufferPointer = readBufferPointer;
    readBufferPointer = tempPointer;
}
```

Only swapping operation need to acquire two lock. Reading and writing operation just need to acquire their own lock. Empty check avoids unnecessary swapping and disorder problem of data.

It has some performance improvement if read-write conflict happens frequently. But in Skywalking, reading operation happens every 3 seconds. Read-write conflict happens rarely in this time period. So I'm not sure if it's necessary to change code.

**Comment by wu-sheng** [comment]
Thanks for bringing this up to our attention with details.

> It has some performance improvement if read-write conflict happens frequently. But in Skywalking, reading operation happens every 3 seconds. Read-write conflict happens rarely in this time period. So I'm not sure if it's necessary to change code.

First about this, I understand. From my understanding, lock is definitely a thing which should be improved, no matter how little impact it is. Because in the large scale deployment, we never know how much impact it really is.

___
Back to the issue you found, I think first, yes, there are some issues about the implementation as you provided. Your double locks mechanism seems better, but in detail, I have a little doubt, when is `if (readBufferPointer.isEmpty())` is not going to be empty?
```java
         data.forEach(writeBufferPointer::accept);
        try {
            readBufferLock.lock();
            if (readBufferPointer.isEmpty()) {
                switchPointers();
            }
```

**Comment by andyzzl** [comment]
In previous implemention, I swap the buffer every time write operation has finished. If two write operations happen continuously, read-buffer will be not empty at second write operation.
1. At beginning:
read-buf[], write-buf[]
2. first write method finished, swap:
read-buf[data1], write-buf[]
3. second write method finished, swap:
read-buf[data2], write-buf[data1]
4. read:
read data2. out of order.

**Comment by wu-sheng** [comment]
AFAIK, `PersistenceWorker#buildBatchRequests` is only driven by a single thread timer, right? So, how could the read-buf is not fully read and switch(next round) happens? What do I miss?

**Comment by andyzzl** [comment]
Yes, reading operation always obtain all data in read-buf. But the frequency of reading is slower than writing. When writing operation happen continuously,  in the first round, read-buf is empty,  swapped. But in the second round, the read-buf has not been read yet, now the read-buf is not empty. The writer thread shouldn't swap the buffer.

**Comment by wu-sheng** [comment]
By following this path, it looks like we could make switch happens driven by `read` rather than `write`? It could reduce the complexity of the logic.

**Comment by andyzzl** [comment]
Thanks a lot! I complicated the logic. Swapping the buffer after reading finished is much better, which no need to check whether read-buffer is empty.

**Comment by wu-sheng** [comment]
Would you submit the pull request to improve the master branch?

**Comment by andyzzl** [comment]
Thanks. And there is another problem I didn't notice before. The reader can only obtain the data in read-buf currently, not all of data, which may produce delay.  In the worst situation, if writer thread write `data1` right after the first round reading finished, then `data1`  can only be read until the third round reading, which delays for 2*(reading period). Is this acceptable?

**Comment by wu-sheng** [comment]
> if writer thread write data1 right after the first round reading finished

First, every write should be in the `write buffer`, correct? Then once the switch happens, it will be read. You set the lock for the switch before the read and write. There should be no chance the data could write into the `read buffer` in any case.

**Comment by andyzzl** [comment]
Oh, I complicated it again. Is that swapping happens before the `readBufferPointer.read()` call? Then there is no delay like that. I made a mistake that I thought swapping is called right after `readBufferPointer.read()`.

**Comment by wu-sheng** [comment]
No matter how you put the codes, the key is, reduce the duration of locking, and only lock when you need to switch.

Base on the discussion, you will find, the key to improve the codes(from my understanding), is to move `readBufferPointer.read()` out of lock. Others don't impact the performance much, what do you think?

**Comment by andyzzl** [comment]
Do we assume that there is always only one thread read from the read-buffer? If so, `readBufferPointer.read()` is no need to be locked.  And the `readBufferLock` is no need to exsit at all, because writer thread never access read-buffer. AFAIK, only `PersistenceTimer` Thread read data from cache. Is it neccesary to assume that there is annother situation to use `ReadWriteSafeCache` in diffrent way in the future?

**Comment by wu-sheng** [comment]
I am not whether read writer lock could help. Yes, there is always timer fresh causing the read and switch.

**Comment by andyzzl** [comment]
I haven't figured out how to use read-write lock in our condition yet. I'll think about it. Thanks.

Back to `readBufferLock`, considring timer thread only, I think we can use only one lock, which is more effective. As follows:

```java
public void write(List<T> data) {
    writeBufferLock.lock();
    try {
        data.forEach(writeBufferPointer::accept);
    } finally {
        writeBufferLock.unlock();
    }
}

public List<T> read() {
    writeBufferLock.lock();
    try {
        BufferedData<T> tempPointer = writeBufferPointer;
        writeBufferPointer = readBufferPointer;
        readBufferPointer = tempPointer;
    } finally {
        writeBufferLock.unlock();
    }
    readBufferPointer.read();
}
```

Considering annother situation with multiple reader thread, read-buffer lock is necessary. As follows.

```java
public void write(List<T> data) {
    writeBufferLock.lock();
    try {
        data.forEach(writeBufferPointer::accept);
    } finally {
        writeBufferLock.unlock();
    }
}

public List<T> read() {
    readBufferLock.lock();
    try {
        writeBufferLock.lock();
        try {
            BufferedData<T> tempPointer = writeBufferPointer;
            writeBufferPointer = readBufferPointer;
            readBufferPointer = tempPointer;
        } finally {
            writeBufferLock.unlock();
        }

        readBufferPointer.read();
    } finally {
        readBufferLock.unlock();
    }
}
```

Maybe the second way is better? Maybe there are some features need to use `ReadWriteSafeCache` in multiple reader way in the future.

**Comment by wu-sheng** [comment]
> Considering annother situation with multiple reader thread, read-buffer lock is necessary. As follows.

I don't think there will be concurrency read. Why do you expect this? My understanding is, maybe we could do parallel streaming reading in the persistent timer, considering about this is not a quick job(do you have self-observability metrics to approve my guess?). Even in this case, we should do parallel for different `PersistenceWorker` instances, what do you think?

**Comment by wu-sheng** [comment]
And I prefer your 1st solution.

**Comment by andyzzl** [comment]
Thank you very much! I got this. There is no need of concurrency reading. Even there is, we should use different worker instances to handle it. I'll keep the first solution. Thanks again.

**Comment by wu-sheng** [comment]
> There is no need of concurrency reading. Even there is, we should use different worker instances to handle it. I

Oh, I don't mean this. I was talking about the Timer reads the list of PersistenceWorker. This could be parallel.

**Comment by andyzzl** [comment]
The timer reads worker in parallel, but for the cache in a single worker, there is always one thread to read it. Is this right? I don't know if I think it right.

**Comment by wu-sheng** [comment]
Yes, you are right. I just give you another idea if you want to optimize this part a little more, of source, we need the product metrics to support this decision(my parallel idea)

**Comment by andyzzl** [comment]
Sorry, I'm not familiar with self-observability metrics. I saw it in back-end-telemetry docs, defined in fetcher-prom-rules/self.yaml. Is this self-observability metrics? I haven't reach that far.

**Comment by wu-sheng** [comment]
> I saw it in back-end-telemetry docs, defined in fetcher-prom-rules/self.yaml. Is this self-observability metrics?

Yes, it is. From there, you will know the time cost for `buildBatchRequests`(persistence_timer_bulk_prepare_latency) and  `save into es`(persistence_timer_bulk_execute_latency). Then if the prepare stage costs too much time, we need to consider  parallel.

**Comment by andyzzl** [comment]
Thanks! I'll learn about it. Could I make a PR for code of solution 1?

**Comment by wu-sheng** [comment]
Please, just note, we are facing a GitHub action CI block, so, the CI tasks of your PR may take a long time to finish.

**Comment by andyzzl** [comment]
OK, thanks again for your help!
