### ISSUE TITLE
java.lang.InterruptedException: null

### ISSUE THREAD

**Issue by yangvipguang** [apache/skywalking#6138]
When I change a diffrent environment . some issues occured.
java.lang.InterruptedException: null
![image](https://user-images.githubusercontent.com/11416887/103723307-bddae100-500c-11eb-80ed-d198b32fd774.png)

**Comment by wu-sheng** [comment]
@hanahmily @EvanLjp Any of you know this error stack?

@yangvipguang This seems more related to Kubernetes client rather than SkyWalking's scope.

**Comment by yangvipguang** [comment]
@wu-sheng  But  I have other two K8S cluster with seem aks version. Both of them have the seem issue.
