### ISSUE TITLE
skywalking 8.3.0version Unsupported spring-cloud-gateway 2.2.4.RELEASE???

### ISSUE THREAD

**Issue by lvjingang-git** [apache/skywalking#6141]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We supported these versions, https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/gateway-2.1.x-scenario/support-version.list
