### ISSUE TITLE
Remove log tid prefix [TID:]

### ISSUE THREAD

**Issue by ecyuan** [apache/skywalking#6142]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [Remove log tid prefix [TID:] ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Remove log tid prefix [TID:],  it can be easy copy & paste to anywhere.
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Invalid issue.

**Comment by yaojingguo** [comment]
Here is a workaround. @ecyuan
