### ISSUE TITLE
oap-server

### ISSUE THREAD

**Issue by githubphy** [apache/skywalking#6143]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.2,centos7,jdk8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/9158859/103774513-abda5c00-5067-11eb-8e50-6a0756f8016e.png)
Why is there an index of future time？
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is based on your time zone.
