### ISSUE TITLE
optimize metric aggregate

### ISSUE THREAD

**Issue by coki230** [apache/skywalking#6148]
Please answer these questions before submitting your issue.
- Feature or performance improvement

___
### Requirement or improvement
- the metric aggregate take a lot of time and the es server have a high load for it. because every metric need to query the minute, hour, month data, and update the query data.
- so i think we can chage the mode to improve performance
- first we can load the minute data to memory or file (if we loss of some real time for it)
- second we can use a hour timer and day timer to calculat the hour data and day data then save it.

**Comment by wu-sheng** [comment]
There is a mechanism called session to do things like this.

> second we can use a hour timer and day timer to calculat the hour data and day data then save it.

This will cause OOM, so we can't do this.
