### ISSUE TITLE
Agent supports Kafka SASL authentication.

### ISSUE THREAD

**Issue by JHub-Wei** [apache/skywalking#6150]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How Do I Configure Authentication Parameters on the Agent When SASL Authentication Is Enabled for Kafka?
___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.3.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If this could be set by Kafka properties(`AdminClient.create(properties);`), then we have provided documentation to do it. If this can't be, then we don't provide this. Contribution is welcome.
