### ISSUE TITLE
es plugin thread leak problem

### ISSUE THREAD

**Issue by YczYanchengzhe** [apache/skywalking#6151]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to fix it？ I need some suggestions and solutions.
___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywaling : 8.1
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
Plugin name: apm-elasticsearch-6.x-plugin
ES version used: elasticsearch-rest-high-level-client-6.8.4.jar
apache.pool version: commons-pool2-2.4.3

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
Problem description: We built an es connection pool based on apache.pool, and thread leaks occurred when using the skywalking plugin
Cause investigation:
In the es plug-in, a connection will be built here, causing the es client to fail to release the connection, and the thread cannot be released and continues to rise.

![image](https://user-images.githubusercontent.com/45945752/103883876-c02a6180-5118-11eb-9e49-4aabf9d10754.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think we should close this client after get nodeList. Could you try to submit a pull request to fix this?

**Comment by YczYanchengzhe** [comment]
I did try to do this, but I found that if you call the close method directly, the connection cannot be closed. The phenomenon is that the number of threads will be reduced by 10 after the connection is closed, but it will be created back, which does not solve the problem. The specific reason I suspect is to use HttpAsyncCloseableHttpAsyncClientBase will judge the link status when closing the link, causing the closing to fail. I haven't found any further reasons~
![image](https://user-images.githubusercontent.com/45945752/103966832-9fefb680-519b-11eb-9e82-4f5101bbee4f.png)

**Comment by wu-sheng** [comment]
Then, the other direction is, do you have any other way to get the node list? It is important for the topology.

**Comment by YczYanchengzhe** [comment]
I tested it again, it is effective to close the connection manually, and I will submit the change to fix this problem

**Comment by wu-sheng** [comment]
Please go ahead.
