### ISSUE TITLE
config instance_uuid manually

### ISSUE THREAD

**Issue by xiaoxinxin85** [apache/skywalking#6152]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to config instance_uuid manually. How can I do ?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

sky walking version：8.3.0-es7
OS：Amazon Linux 2 AMI
JRE:1.8.0_181

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read agent setup doc.
