### ISSUE TITLE
apisix作为多个系统的入口，不同系统不同域名，不同域名/系统下有相同path。skywalking做追踪的时候，如何区分端点

### ISSUE THREAD

**Issue by Dragon-dufei** [apache/skywalking#6154]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please use English to discuss on the GitHub.

**Comment by Dragon-dufei** [comment]
Hi,  the situation as follow:
Apisix serves as a portal to multiple systems, with different domain names for different systems and the same path for different domain names/systems.now,we use skywalking to be a APM system,how to distinguish endpoints.
for example,I have two url like http://www.bbb.com/add  and http://www.aaa.com/add, they both are in Apisix.But in Skywalking,they both shows /add.

**Comment by wu-sheng** [comment]
Could you open a new issue to discuss this? And I will include the team of APISIX to help on that discussion too.

**Comment by Dragon-dufei** [comment]
ok,thk!
