### ISSUE TITLE
Apisix serves as a portal to multiple systems, with different domain names for different systems and the same path for different domain names/systems.now,we use skywalking to be a APM system,how to distinguish endpoints. 

### ISSUE THREAD

**Issue by Du-fei** [apache/skywalking#6155]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by Dragon-dufei** [comment]
Hi, the situation as follow:
Apisix serves as a portal to multiple systems, with different domain names for different systems and the same path for different domain names/systems.now,we use skywalking to be a APM system,how to distinguish endpoints.
for example,I have two url like http://www.bbb.com/add and http://www.aaa.com/add, they both are in Apisix.But in Skywalking,they both shows /add.

**Comment by wu-sheng** [comment]
First, I am not an expertise of APISIX, is this a common usage? @moonming @Miss-you ?

Currently, we only use `uri` as the span's operation name, which is the source of your endpoint.

https://github.com/apache/skywalking-nginx-lua/blob/0795297970f1cab01558ec1787499b6a5eef5233/lib/skywalking/tracer.lua#L46

**Comment by membphis** [comment]
After discussing with @wu-sheng , we can add a global field to decide whether to use `uri` or `domain` + `uri`. 

> use `uri`

`local entrySpan = TC.createEntrySpan(tracingContext, ngx.var.uri, nil, contextCarrier)`

> use `domain` + `uri`

`local entrySpan = TC.createEntrySpan(tracingContext, ngx.var.host .. "/" .. ngx.var.uri, nil, contextCarrier)`

@Du-fei what do you think?

**Comment by Du-fei** [comment]
It's one way!!!
I'll have a try  :)
thx!!!

**Comment by wu-sheng** [comment]
@membphis Do you think we are worth to add this into the LUA agent as official option and then forward to APISIX?

**Comment by wu-sheng** [comment]
Such as we could change 
```
require("skywalking.tracer"):start("upstream service")
```
to
```
opt.includeHostInEntrySpan = true; # default is false
require("skywalking.tracer"):start("upstream service", opt)
```

**Comment by membphis** [comment]
@wu-sheng 

I suggest to make `includeHostInEntrySpan` as a global field instead of per trace.

For most users, either all are enabled or all disabled, it should not be per request.

we can set this field in this way: https://github.com/apache/skywalking-nginx-lua/blob/master/examples/nginx.conf#L39

**Comment by Du-fei** [comment]
I think it should be.
This is the kind of problem that other people are bound to encounter if they choose APISIX as a portal to multiple systems.

**Comment by wu-sheng** [comment]
@Du-fei If this works at your side, would you like to send a pull request to the upstream?

**Comment by Du-fei** [comment]
Yes,it works.
You mean send a pull request to skywalking-nginx-lua?

**Comment by wu-sheng** [comment]
Yes.

**Comment by Du-fei** [comment]
All right. Let me test it out again, and then I'll send a pull request to the upstream.
