### ISSUE TITLE
I am facing issue with timezone is UTC + 5 i.e (IST timezone) . On UI logs are showing 30 min delayed logs.

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6156]
I am facing issue with timezone is UTC + 5  . Need to set it to UTC+530 (IST) timezone. In which configuration file I can set this.

Kindly suggest,

Thanks and Regards,
Jayesh Muley
![timezone](https://user-images.githubusercontent.com/75727262/103917453-a34f5780-5133-11eb-8d13-87f1ba375bf8.png)

_Originally posted by @JayeshMuley in https://github.com/apache/skywalking/issues/2594#issuecomment-756224982_

**Comment by wu-sheng** [comment]
Could you check the graphql to see whether the data is correct from the backend?

**Comment by JayeshMuley** [comment]
Backend is storing the data UC + 5 (OAP Server Time Zone UC+5) where I need to store it on UC+5:50 (IST) time. Where I can change this. 
Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
That is JVM Time Zone setting. We don't control that. But currently UI doesn't support UTC +5.5 I am afraid.

**Comment by wu-sheng** [comment]
No Update.
