### ISSUE TITLE
Dubbo link tracing- show "group" attribute value in OperationName 

### ISSUE THREAD

**Issue by bootsrc** [apache/skywalking#6158]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x] Feature or performance improvement

___
In my company, we need to show "group" attribute value in OperationName in Dubbo trace.
For example. I have set group value  in my Dubbo project application.properties 
`
dubbo.consumer.group=g2
`
Now in trace page, it shows "com.example.dubbodemo.api.DemoService.hello(String)"
But we want to show group value,
 like this "g2 com.example.dubbodemo.api.DemoService.hello(String)"

I have done Pull Request
#6159
, could you check it?

**Comment by wu-sheng** [comment]
Could you provide a link about Dubbo document of group?

**Comment by bootsrc** [comment]
#6159 
this is my PR.

**Comment by wu-sheng** [comment]
We need to take a look what is Dubbo group first. The implementation could wait for a while.

**Comment by bootsrc** [comment]
Thanks .
Introduce In Chinese :
服务分组，当一个接口有多个实现，可以用分组区分


 Dubbo group introduce doc is

[http://dubbo.apache.org/zh/docs/v2.7/user/references/xml/dubbo-provider/](http://dubbo.apache.org/zh/docs/v2.7/user/references/xml/dubbo-provider/)

please search keywords "dubbo" in this link page
