### ISSUE TITLE
query traces by tag

### ISSUE THREAD

**Issue by zxz9325** [apache/skywalking#6160]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
-  Bug

___
### Bug
- Which version of SkyWalking, OS, and JRE?
   SkyWalking 8.3

- What happened?
   For example
    1. plugin.http.include_http_headers=${SW_INCLUDE_HTTP_HEADERS:userId}
    2. add 'http.headers' in 'core/default/searchableTracesTags'
    3. Add a header value (userId=zhangsan) to a request
    4. Follow the tag value (http.headers=userId=[zhangsan]) on Skywalking's tracking query page
    5. Cannot query anything
   

___
### Requirement or improvement
  query body :  {"query":"query queryTraces($condition: TraceQueryCondition) {\n  data: queryBasicTraces(condition: $condition) ...
   but Parsing tags parameters is "tags":[{"key":"http.headers","value":"userId"}], rather than "tags":[{"key":"http.headers","value":"userId=[zhangsan]"}]
![Snipaste_2021-01-08_22-16-43](https://user-images.githubusercontent.com/21777063/104025324-681a5a80-51ff-11eb-849e-d74ec10fa2f0.png)

**Comment by wu-sheng** [comment]
Do you really have this tag in the span? Could you take a look at your trace?

**Comment by wu-sheng** [comment]
Your query condition seems strange, shouldn't it be `http.headers`=`userId=[zhangsan]`? Why could you ignore part of the value?

**Comment by zxz9325** [comment]
Sorry, it's a little messy...
Here is the data stored in ES7,the key tags are stored 'http.headers' key-val...

{
    "_index": "my-application_segment-20210108", 
    "_type": "_doc", 
    "_id": "94d250ef7e5944a898d1491963421abc.39.16101060532900008", 
    "_version": 1, 
    "_score": 1, 
    "_source": {
        "trace_id": "94d250ef7e5944a898d1491963421abc.39.16101060532900009", 
        "endpoint_name": "{GET}/show", 
        "latency": 1, 
        "end_time": 1610106053291, 
        "endpoint_id": "QU06OmFsYXJtMDE=.1_e0dFVH0vc2hvdw==", 
        "service_instance_id": "QU06OmFsYXJtMDE=.1_OGYwODdlZWNmNWIyNGYwNjk0NjJkZmI1YzBmMTk3YzZAMTkyLjE2OC40Ni4x", 
        "version": 3, 
        **"tags": [
            "_http.headers=userId=[zhangsan]_", 
            "http.method=GET"
        ],** 
        "start_time": 1610106053290, 
        "data_binary": "CjU5NGQyNTBlZjdlNTk0NGE4OThkMTQ5MTk2MzQyMWFiYy4zOS4xNjEwMTA2MDUzMjkwMDAwORI1OTRkMjUwZWY3ZTU5NDRhODk4ZDE0OTE5NjM0MjFhYmMuMzkuMTYxMDEwNjA1MzI5MDAwMDgagAEQ////////////ARiqxbKO7i4gq8Wyju4uMgp7R0VUfS9zaG93SANQDmIhCgN1cmwSGmh0dHA6Ly9sb2NhbGhvc3Q6ODA4OS9zaG93YhIKC2h0dHAubWV0aG9kEgNHRVRiHgoMaHR0cC5oZWFkZXJzEg51c2VySWQ9W21hbGl1XSILQU06OmFsYXJtMDEqLThmMDg3ZWVjZjViMjRmMDY5NDYyZGZiNWMwZjE5N2M2QDE5Mi4xNjguNDYuMQ==", 
        "service_id": "QU06OmFsYXJtMDE=.1", 
        "statement": "{GET}/show - 94d250ef7e5944a898d1491963421abc.39.16101060532900009", 
        "time_bucket": 20210108194053, 
        "is_error": 0, 
        "segment_id": "94d250ef7e5944a898d1491963421abc.39.16101060532900008"
    }
}



Here is the graphql query body:

{
    "query": "query queryTraces($condition: TraceQueryCondition) {
  data: queryBasicTraces(condition: $condition) {
    traces {
      key: segmentId
      endpointNames
      duration
      start
      isError
      traceIds
    }
    total
  }}", 
    "variables": {
        "condition": {
            "queryDuration": {
                "start": "2021-01-01", 
                "end": "2021-01-08", 
                "step": "DAY"
            }, 
            "traceState": "ALL", 
            "paging": {
                "pageNum": 1, 
                "pageSize": 15, 
                "needTotal": true
            }, 
            "queryOrder": "BY_START_TIME", 
            "tags": [
                **{
                    "key": "http.headers", 
                    "value": "userId"
                }**
            ]
        }
    }
}

**Comment by wu-sheng** [comment]
Isn't the tag clear enough? `"http.headers=userId=[zhangsan]"` has in. your data. Why do you use different value to query?

**Comment by zxz9325** [comment]
the tags data stored in ES7 is "http.headers=userId=[zhangsan]",so I follow the tag value (http.headers=userId=[zhangsan]) on Skywalking's tracking query page,but when I click on the query,but the parsed graphql query body is 
"tags": [
   {
     **"key": "http.headers",
         "value": "userId"**
  }
], 
have I made myself clear? follow the tag value (http.method=GET) on Skywalking's tracking query page is ok.

**Comment by wu-sheng** [comment]
@Fine0830 Could you take a look at this? It seems if there is `=` in the value, the UI doesn't put the right GraphQL parameter.

**Comment by Fine0830** [comment]
> @Fine0830 Could you take a look at this? It seems if there is `=` in the value, the UI doesn't put the right GraphQL parameter.

Sure. Let me find out it.

**Comment by Fine0830** [comment]
As there are two `=`, they are conflict. Please use other symbols to replace one of them.

**Comment by wu-sheng** [comment]
> As there are two =, they are conflict. Please use other symbols to replace one of them.

Could we use `firstIndexOf` to separate key and value?

**Comment by wu-sheng** [comment]
`key=value` as the value of tag is caused by some plugins' implementation. @Fine0830

**Comment by Fine0830** [comment]
Alright.....
