### ISSUE TITLE
How to tracing GraphQL query with skywalking ?

### ISSUE THREAD

**Issue by kdlan** [apache/skywalking#6162]
### Question

Does skywalking support to trace a GraphQL query and requests to other services?

**Comment by wu-sheng** [comment]
We have provided the GraphQL service side plugin for several months. Tests are here, https://github.com/apache/skywalking/tree/master/test/plugin/scenarios

![image](https://user-images.githubusercontent.com/5441976/104088230-32797e00-52a0-11eb-9d32-15c7c04d9ac3.png)

**Comment by wu-sheng** [comment]
Please read the documentation before submit the issue.  https://github.com/apache/skywalking/blob/v8.3.0/docs/en/setup/service-agent/java-agent/Supported-list.md
