### ISSUE TITLE
在UI管理页面的日志页面，无法查看client js上报的error page字段和调用栈

### ISSUE THREAD

**Issue by withyanni** [apache/skywalking#6166]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking client js  
SkyWalking  v8.3.0 for H2/MySQL/TiDB/InfluxDB/ElasticSearch 7 
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

vue开发的前端控制台报了错误，但在UI管理页面貌似没有正确展示字段和调用栈
能否展示更多字段，以及展示调用栈。
![image](https://user-images.githubusercontent.com/28222123/104145376-bc8d2800-5401-11eb-876e-18595813e2ef.png)
![image](https://user-images.githubusercontent.com/28222123/104145425-e3e3f500-5401-11eb-8413-b9406c88e8a3.png)
![image](https://user-images.githubusercontent.com/28222123/104145564-6f5d8600-5402-11eb-849e-4c91660a4431.png)

### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please use English on Github.
