### ISSUE TITLE
Can't show pagePath field and call stack on UI web log page

### ISSUE THREAD

**Issue by withyanni** [apache/skywalking#6167]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
- 
SkyWalking v8.3.0 for H2/MySQL/TiDB/InfluxDB/ElasticSearch 7
skywalking-client-js": "^0.2.0"

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

there happen an error on the console, but on the UI page can't show user custom field pagePath and can't show call stack rightly.
the call stack is not report to collector
![image](https://user-images.githubusercontent.com/28222123/104146237-00356100-5405-11eb-8821-47faf5b14b7d.png)
![image](https://user-images.githubusercontent.com/28222123/104146337-50142800-5405-11eb-800b-ed1e8b0fc022.png)
![image](https://user-images.githubusercontent.com/28222123/104146349-586c6300-5405-11eb-9b26-b8b37522a7f8.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
show more fields and show call stack rightly.
also wanna add sort.
Thanks.

**Comment by wu-sheng** [comment]
Could you share a static page to reproduce this bug?

**Comment by withyanni** [comment]
@Fine0830 
please, I can't  see the field pagePath on the web, and the stack is not show rightly.

![image](https://user-images.githubusercontent.com/28222123/104282339-db66e980-54e9-11eb-9aa0-6465c87b1eeb.png)
![image](https://user-images.githubusercontent.com/28222123/104282366-e7eb4200-54e9-11eb-9f1f-cddf542a2784.png)

**Comment by Fine0830** [comment]
Noticed

**Comment by wu-sheng** [comment]
@withyanni I have asked, please submit some demo codes to help on reproducing the bug. You should not ask us to guess what is going on.

**Comment by withyanni** [comment]
@Fine0830 @wu-sheng 
I constructed a demo on Jsrun, please see http://jsrun.net/34IKp/edit
 when click the button , the console will see below pic

![image](https://user-images.githubusercontent.com/28222123/104297614-09eebf80-54fe-11eb-9ac1-782c6412b498.png)

and the same code in IDE develop, will see below pic 
![image](https://user-images.githubusercontent.com/28222123/104296981-453cbe80-54fd-11eb-80f2-223c06bd742b.png)

and on the web will see 
![image](https://user-images.githubusercontent.com/28222123/104297070-5ede0600-54fd-11eb-9f45-4b8d132e9e59.png)
![image](https://user-images.githubusercontent.com/28222123/104297732-2b4fab80-54fe-11eb-90a3-1b063a70686e.png)
