### ISSUE TITLE
chore(lua-agent): remove the wrong directive in Nginx example

### ISSUE THREAD

**Issue by membphis** [apache/skywalking#6168]
need to remove https://github.com/apache/skywalking-nginx-lua/blob/master/examples/nginx.conf#L52

It may cause us to obtain duplicate UUIDs and cause abnormal issues.

we can just remove https://github.com/apache/skywalking-nginx-lua/blob/master/examples/nginx.conf#L50-L52

**Comment by Frapschen** [comment]
how can i help this issue,just remove the server {} block?
