### ISSUE TITLE
Why no cpm data display on Topo ?

### ISSUE THREAD

**Issue by L-Y-L** [apache/skywalking#6169]
- Why do you submit this issue?
- [✓] Question
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to know why the tomcat node does not have cpm data, because the service is requested from the topological diagram.
___
### Bug
- Which version of SkyWalking, OS, and JRE?
v8.x
- Which company or project?
http://skywalking-ui.derunht.cn/topology

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/23448471/104162191-1b1ccb00-542f-11eb-9cfc-7af8b321edf0.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
-

**Comment by wu-sheng** [comment]
Duplicated.
