### ISSUE TITLE
Why no cpm data on topo

### ISSUE THREAD

**Issue by L-Y-L** [apache/skywalking#6170]
- Why do you submit this issue?
- [✓] Question
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to know why the tomcat node does not have cpm data, because the service is requested from the topological diagram.
___
### Bug
- Which version of SkyWalking, OS, and JRE?
v8.x
- Which company or project?
http://skywalking-ui.derunht.cn/topology

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/23448471/104162191-1b1ccb00-542f-11eb-9cfc-7af8b321edf0.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
-

**Comment by wu-sheng** [comment]
You have selected hour-level metrics, which means you need at least having 1 * 60 calls in this hour, you could have 1 cpm.

**Comment by L-Y-L** [comment]
In this way, 59 calls occurred in one hour, and the cpm data will be displayed as 0. I think it is unreasonable, because it is the fact that calls occurred in this hour.

**Comment by wu-sheng** [comment]
If you take a look at minutes level, it is there. We never said it is traffic, if you wants purely calls, you should learn OAL and UI custom setting.

**Comment by L-Y-L** [comment]
Thank you for your prompt reply, I see where you're going.
