### ISSUE TITLE
I want to use skywalking agent for traffic dyeing, want to add custom <k,v> identification in the tracing link, and can pass through the Skywalking transmission system in the whole link, how should I deal with it?

### ISSUE THREAD

**Issue by chenhuandong8010** [apache/skywalking#6171]
I want to use skywalking agent for traffic dyeing, want to add custom <k,v> identification in the tracing link, and can pass through the Skywalking transmission system in the whole link, how should I deal with it?

我想利用skywalking agent进行流量染色，想在tracing链路中增加自定义的<k,v>标识，并且能通过Skywalking透传体系在整个链路中透传，请问我该如何处理？

**Comment by wu-sheng** [comment]
We have this defined as collaborate context in API and protocol. Read the documents.

**Comment by chenhuandong8010** [comment]
Where is the address of the document? I can't find any information for a long time, please

**Comment by wu-sheng** [comment]
- `Cross Process Correlation Headers Protocol v1` of the protocol doc, https://github.com/apache/skywalking/blob/master/docs/en/protocols/README.md.
- `propagating custom data` in the agent doc, https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#advanced-features-1

**Comment by chenhuandong8010** [comment]
Well, thanks, I just need to configure the agent start parameter correlation.auto_tag_keys, put the dye mark key on the whole start parameter, and then put the <k,v> of the dye mark in the header ："sw8-correlation" at the kong gateway layer
嗯，谢谢，我只需要配置agent启动参数correlation.auto_tag_keys，将染色标记key放在整个启动参数，然后在kong网关层将染色标记的<k,v>放在header :"sw8-correlation"中就可以了吧

**Comment by wu-sheng** [comment]
You didn't read the documentations correctly. Please be more patient .

**Comment by chenhuandong8010** [comment]
![image](https://user-images.githubusercontent.com/35483146/104181464-cf2b4f80-5449-11eb-977c-3719d2046b0a.png)
Have read API document for a long time, isn't it?

**Comment by wu-sheng** [comment]
Your work, your responsibility. You don't need to check with me. Try the codes.
