### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6175]
Hi,
I have two  services are running on same host and setup using two separate folders. I can see both the services are present in topology but not on the Service Filter list. 

I have setup separate agent folder for each service. How to fix this problem or if there is another way to avoid using two separate folders.

folders - 
drwxr-xr-x. 9 Jayesh Jayesh   176 Jan  5 13:11 agent_solution
drwxr-xr-x. 9 Jayesh Jayesh   176 Jan  5 13:11 agent_edge
  
![Service_No_Available_in List](https://user-images.githubusercontent.com/75727262/104182302-4525bb80-5436-11eb-91ce-4fc838067a35.png)

Thanks and Regards,
Jayesh Muley

_Originally posted by @JayeshMuley in https://github.com/apache/skywalking/issues/698#issuecomment-757919393_

**Comment by wu-sheng** [comment]
Are you scrolling that selector?

**Comment by wu-sheng** [comment]
>  if there is another way to avoid using two separate folders.

Read the `setting override` doc, https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#table-of-agent-configuration-properties

**Comment by JayeshMuley** [comment]
Sorry but there is no scrolling bar in selector as there are no specified services available.

**Comment by wu-sheng** [comment]
Then the other node not showing up, may be not a real service. It could show up in the topology if one service is calling it through the name.
