### ISSUE TITLE
Istio control panel setting

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6177]
@kezhenxu94 has set up the control panel observability on the live demo, I found there are following issues to be rechecked and fixed.

1. The metrics seems having incorrect metrics.
![image](https://user-images.githubusercontent.com/5441976/104252421-fcf5b000-54ac-11eb-9acd-defdf0adfecc.png)

2. `Configuration Validation` is using `self selectors` as entity condition, which should be a bug.
3. There is a blank zone when use the current layout
![image](https://user-images.githubusercontent.com/5441976/104252483-26164080-54ad-11eb-8dae-dd3b3ae16f7c.png)

We should try to fix there and update the demo env again.

**Comment by kezhenxu94** [comment]
Updated
