### ISSUE TITLE
How can I  export alerm metrics

### ISSUE THREAD

**Issue by ylywyn** [apache/skywalking#6180]
- Why do you submit this issue?
- [ ] Question or discussion

### Question
- What do you want to know?
   I need alerm metrics( export to our monitor system), But I can't find it  in prometheus-fetcher. How can I  export alerm metrics(*.oal  metrics)?

**Comment by wu-sheng** [comment]
You can't do `prometheus-fetcher.` to OAP, it will kill the memory, which is the limitation of how Prometheus works. We provided metrics exporter for you to forward any metrics you like.

Read **Metrics exporter. Use metrics data exporter to forward metrics data to 3rd party system.** of the backend setup doc, https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-setup.md
