### ISSUE TITLE
Storing Actual Service Name in skywalking mysql storage

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6181]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ Y] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Need to store actual service name in storage database. Where I can set this property. Currently all the entities are storing in form of some Id's.

202101121013_ZWRnZTEuc2VydmljZQ==.1             | ZWRnZTEuc2VydmljZQ==.1             |    81 |    81 | 202101121013 |
| 202101121013_ZWRnZV9wZXJmLnNlcnZpY2U=.1         | ZWRnZV9wZXJmLnNlcnZpY2U=.1         |    39 |    39 | 202101121013 |
| 202101121014_U29sdXRpb24xLnNlcnZpY2U=.1         | U29sdXRpb24xLnNlcnZpY2U=.1         |     5 |     5 | 202101121014 |

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Could you share why do you ask for this?

**Comment by JayeshMuley** [comment]
I need to check, I have seen few Services are not coming on the UI (ex. Instance Tab ).So need to check if the data is available for those services in backend.  also by seeing the db I can't figure out what is value belong  which service. 

However in ELK they have the facility to store actual values of entities by changing the configuration.

Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
Search `activeExtraModelColumns` at the Configuration Vocabulary doc, https://github.com/apache/skywalking/blob/v8.3.0/docs/en/setup/backend/configuration-vocabulary.md
