### ISSUE TITLE
Is there a plan of supporting opentracing v0.33.0?

### ISSUE THREAD

**Issue by xiangwangcheng** [apache/skywalking#6184]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [√] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Now skywalking supports opentracing v0.30.0, and v0.33.0 has a lot of changes. 
Is there a plan of support opentracing v0.33.0?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
OpenTracing is not maintained actively basically. 

![image](https://user-images.githubusercontent.com/5441976/104288984-85973f00-54f3-11eb-8a07-921f72104ff1.png)

From the day one we supported(2~3 years), we can't see the real value of a set of APIs. Our native toolkits have wider users and 100% matching the agent core.
