### ISSUE TITLE
Endpoint name group doesn't work due to service name not set in SourceBuilder

### ISSUE THREAD

**Issue by buxingzhe** [apache/skywalking#6185]
### Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
       When segment span reference list is not empty, for MultiScopesAnalysisListener.parseEntry method, the SourceBuilder sets endpoint name before service name is set which makes the endpoint name grouping doesn't work due to miss service name.
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
   SkyWalking 8.3.0, Linux, JDK 11
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
   Just set the service name before setting endpoint in source builder.

**Comment by buxingzhe** [comment]
![Uploading endpoint-name-group-failed.png…]()

**Comment by buxingzhe** [comment]
<img width="960" alt="endpoint-name-group-failed" src="https://user-images.githubusercontent.com/5172430/104289210-d4dd6f80-54f3-11eb-9efa-8da635502682.png">

**Comment by wu-sheng** [comment]
Take a look at `SourceBuilder#setSourceEndpointName`? I can see the `NamingControl` mechanism working in there. Anything I missed?

**Comment by buxingzhe** [comment]
<img width="960" alt="endpoint-name-group-failed" src="https://user-images.githubusercontent.com/5172430/104289768-8086bf80-54f4-11eb-9b69-09f89b57c3fd.png">

**Comment by buxingzhe** [comment]
![image](https://user-images.githubusercontent.com/5172430/104290044-ccd1ff80-54f4-11eb-8c0c-893c0354b136.png)

**Comment by buxingzhe** [comment]
Just refer to my screenshot, as the service name is null, we can't get the right group rule.

**Comment by wu-sheng** [comment]
OK, I can get your point now. Yes, the naming mechanism fails because of the order of setting.
This is very tricky and hard to find.

My suggestion is adding a `prepare` method for `SourceBuilder` class, which should be called before `toXXX` in the `MultiScopesAnalysisListener#build`. And follow your path, I can see `slowDatabaseAccesses` and `logicEndpointBuilders` have bugs for the whole `NamingControl`. Could you fix this in the same way?

**Comment by buxingzhe** [comment]
OK, I'll commit a fix.
