### ISSUE TITLE
the first segment of a trace should be tageed ?

### ISSUE THREAD

**Issue by bestpayAmes** [apache/skywalking#6186]
### Question
- the first segment of a trace is should tageed? because when querying trace ,we transfer a traceId ,but return is all segment list, this is not reasonable?

**Comment by wu-sheng** [comment]
That query is query segments, which composing the trace. We explained it in the UI doc already.

**Comment by bestpayAmes** [comment]
`private List<Span> findRoot(List<Span> spans) {
        List<Span> rootSpans = new ArrayList<>();
        spans.forEach(span -> {
            String segmentParentSpanId = span.getSegmentParentSpanId();

            boolean hasParent = false;
            for (Span subSpan : spans) {
                if (segmentParentSpanId.equals(subSpan.getSegmentSpanId())) {
                    hasParent = true;
                    // if find parent, quick exit
                    break;
                }
            }

            if (!hasParent) {
                span.setRoot(true);
                rootSpans.add(span);
            }
        });`
because of it,This code is inefficient,O(N^2)
