### ISSUE TITLE
Throw exception that index is already existed when starting the oap cluster with three nodes for the first time

### ISSUE THREAD

**Issue by 3838438abcd** [apache/skywalking#6189]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How the oap to control the behavior to create es index where in cluster mode? 
___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalkinf 8.1.0, win10, jdk1.8,Storage es7
- Which company or project?

- What happened?
When I start three nodes at the same time with helm，there is a chance that index will be created repeatedly in different nodes
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
There is an `initial`-container for creating the index.

**Comment by kezhenxu94** [comment]
@3838438abcd can you share the `helm` command that you used to deploy SkyWalking, I didn't encounter this before

**Comment by wu-sheng** [comment]
No update.

**Comment by 3838438abcd** [comment]
> @3838438abcd can you share the `helm` command that you used to deploy SkyWalking, I didn't encounter this before

I just deploy it with the command that `helm install oap oap-charts`,

**Comment by kezhenxu94** [comment]
> > @3838438abcd can you share the `helm` command that you used to deploy SkyWalking, I didn't encounter this before
> 
> I just deployed it with the command that `helm install oap oap-charts`

That does not make sense, the default replica number of OAP is 2 if you didn't modify them, also, from your previous comment "When I start three nodes at the same time with helm", I don't know how you start "three nodes at the same time", but it sounds that you run `helm install` multiple times?

I'd suggest you firstly deploy with the default configurations and tune the replicas according to the doc after the default configurations work
