### ISSUE TITLE
Why profile has no manual deletion function?

### ISSUE THREAD

**Issue by cuiweiwei** [apache/skywalking#6197]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement
___
### Requirement or improvement
- I find that profile has the deletion function controlled by TTL, but can't be deleted Manually. Is it some kind of consideration or is it simply that no one is providing the code?   
-  The user may have miswritten the endpoint name of profileTask, it is also possible that no data was collected within a given duration, In these cases, I think the manual  deletion function is necessary.

**Comment by wu-sheng** [comment]
We don't provide such kind of management feature, as the community has no interest to do this.

**Comment by cuiweiwei** [comment]
I have interest to do this.

**Comment by wu-sheng** [comment]
`No interest` is from tech perspective, deleting a row in some storage, such as ElasticSearch will be a performance impact, which could cause issues, in some cases.

**Comment by cuiweiwei** [comment]
All right, I see.
