### ISSUE TITLE
Failed to develop a plugin to enhance Storm's class

### ISSUE THREAD

**Issue by pierre94** [apache/skywalking#6198]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?
I want to develop a plugin to count the cost of `org.apache.storm.spout.ISpout#nextTuple`. 
My `instrumentation` define：
```java
    private static final String ENHANCE_CLASS = "org.apache.storm.spout.ISpout";
    private static final String ENHANCE_METHOD = "nextTuple";
    private static final String STORM_METHOD_INTERCEPT_CLASS = "org.apache.skywalking.apm.plugin.storm.ISpoutInterceptor";

    @Override
    public ClassMatch enhanceClass() {
        return byHierarchyMatch(new String[]{ENHANCE_CLASS});
    }

    // ……
    }
```

My Plugin works well in Storm's `LocalCluster` model, but failed in Storm's cluster model.

This is the cluster model's log:
![image](https://user-images.githubusercontent.com/12579749/104420255-8f34ab80-55b4-11eb-942b-d81f341b30e0.png)

Can you give me some advice to fix it?

**Comment by wu-sheng** [comment]
I am not sure, do you enhance something related to the message of RPC?

**Comment by pierre94** [comment]
> I am not sure, do you enhance something related to the message of RPC?

Hello sheng. 
`org.apache.storm.spout.ISpout#nextTuple` will emit data from spout to bolt. It relate to data's serialization like RPC.
![image](https://user-images.githubusercontent.com/12579749/104558489-d6d33a00-567d-11eb-836d-a339098a63c8.png)

Does it relate to this byte-buddy‘s issue ？ [`Cannot deserialize class after Advice instrumentatio`](https://github.com/raphw/byte-buddy/issues/167)

**Comment by wu-sheng** [comment]
It is related to the issue you are pointing, but to be accurate, it is not an issue. You should not change classes going to serialization or deserialization, because SkyWalking will change the class structure for sure.
