### ISSUE TITLE
a SBT project，can't see the data information on the Skywalking interface!

### ISSUE THREAD

**Issue by OnedayGh** [apache/skywalking#6199]
Hello, I can't see the data information on the Skywalking interface!

I am a SBT project. My REST framework is Spray and the programming language is Scala. I use the command: java -javaagent:/home/sunsheng/skyWalkingDemo/apache-skywalking-apm-bin/agent_b/skywalking-agent.jar -Dserver.port=8072 -jar configadapter-1.0-SNAPSHOT2.jar &,  

please support my project, if can undertake what operations the, thank you!

**Comment by wu-sheng** [comment]
Can't see any information feom your description. You should provide, agent log, backend log, storage data(such as service_traffic). Otherwise, don't know what we can do.
