### ISSUE TITLE
Database Dashboard is blank

### ISSUE THREAD

**Issue by LaimGit** [apache/skywalking#6201]
- [ ] Bug
___
### Bug
- Which version of SkyWalking, OS, and JRE?
- oap version:8.1.0, OS:centos, JRE:1.8

- What happened?
I used the default config when i installed the WkyWalking, 
the Database Dashboard is blank, granQL response is "{"data":{"services":[]}}",
mysql-5.x, 
but the HTTP,Dubbo service APM dashboard is normal.

if it need additional configuration, to display the Database Dashboard?

**Comment by wu-sheng** [comment]
Do you have mysql span in your trace?
