### ISSUE TITLE
Add log analyzer in es storage

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#6205]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
add log anlyzer for log query

**Comment by wu-sheng** [comment]
@EvanLjp Are you adding this in 8.4.0? I may plan to finalize the 8.4.0 in next weekend, or 2 weeks later.

**Comment by EvanLjp** [comment]
i am already write some codes， i would try to push it on this weekend
