### ISSUE TITLE
elasticsearch

### ISSUE THREAD

**Issue by githubphy** [apache/skywalking#6206]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
We use Alibaba cloud elasticsearch to store data. Is there any case that supports the separation of hot and cold data?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We are not having such kind of thing. Observability data usually is kept in 7 days. There is no cold data. We are not a BI system.
