### ISSUE TITLE
How to remove C# related   segment that cantain _clr_?

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#6207]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Dot net agent has its own repo, and discussion channel. Please go to there.
