### ISSUE TITLE
 stores data in ES7 cluster,query traces by tag is empty?

### ISSUE THREAD

**Issue by zxz9325** [apache/skywalking#6208]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question

___
### Question
- What do you want to know?
 I use skywalking oapServer cluster and use ES cluster to store data, how to query by tag?There seems to be a problem,did I set the problem?
___
### Bug
- Which version of SkyWalking, OS, and JRE?
   SkyWalking8.3
- What happened?
1. Set three ES7 cluster and  skywalking oapServer cluster
 2. Follow the tag value (http.method=GET) on Skywalking's tracking query page...query is empty
 3. But if it's a standalone, it's good to query like this...

___

**Comment by wu-sheng** [comment]
Does that ElasticSearch have supported older release? Maybe some indexes templates are still there.
