### ISSUE TITLE
[Discuss] Response to Elastic 2021 License Change

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6219]
Hi Community,

Elastic announced they are changing the license of ElasticSearch server recently, from Apache 2.0 to SSPL. Official announcement is here, https://www.elastic.co/pricing/faq/licensing
SSPL has been confirmed as a Catalog X LICENSE. So we can't only focus on it anymore. We need to consider other storage options. Right now, we still have InfluxDB, TiDB, H2 server still in Apache 2.0 licensed.

As one optional plugin, we need to focus on the client driver license. Right now, we are only using ElasticSearch 7.5.0 and 6.3.2 drivers, which are both Apache 2.0 licensed. So, we are safe.
For further upgrade, here is their announcement. 
```
Many of our products and projects continue to be under Apache 2.0, including our client libraries
```
```
> I'm using Elasticsearch via APIs, how does this change affect me?
This change does not affect how you use client libraries to access Elasticsearch. Our client libraries remain licensed under 
Apache 2.0, with the exception of our Java High Level Rest Client (Java HLRC).

The Java HLRC has dependencies on the core of Elasticsearch, and as a result this client library will be licensed under the 
Elastic License. Over time, we will eliminate this dependency and move the Java HLRC to be licensed under Apache 2.0. Until 
that time, for the avoidance of doubt, we do not consider using the Java HLRC as a client library in development of an 
application or library used to access Elasticsearch to constitute a derivative work under the Elastic License, and this will not 
have any impact on how you license the source code of your application using this client library or how you distribute it.
```

**The only impact to us is**, if we move on to support the 8.x or upgrade the driver to 7.11+(include 7.11), we have to wait for their latest Apache 2.0 licensed driver.

___

Besides the potential risk of ElasticSearch's company behaviors, we need to consider other more general available database solution. There are several in my mind.
1. Apache Cassandra, https://cassandra.apache.org/. cc @michaelsembwever 
2. Apache Solr, https://lucene.apache.org/solr/. Sub-project of Lucene, which is the core of ElasticSearch too. cc @dmsolr 
3. Apache IoTDB, https://iotdb.apache.org/. cc @jixuan1989
4. Hybrid, M3 https://m3db.io/, focuses on metrics, Cassandra or something focuses on the trace/log.

Besides above, I was having long discussion with @hanahmily, we should have plan to build SkyWalking own storage solution, focusing on metrics/log/trace observability area data, without bothering about the transaction and consistency of most database provided. We should be able to delivery a higher performance, lower resource cost hybrid database solution as a new sub project under SkyWalking's umbrella.

To all @apache/skywalking-committers, what do you prefer? And what do you want to add about this event? It is welcome to join this thread.

**Comment by JaredTan95** [comment]
> Apache Cassandra, https://cassandra.apache.org/. cc @michaelsembwever
Apache Solr, https://lucene.apache.org/solr/. Sub-project of Lucene, which is the core of ElasticSearch too. cc @dmsolr
Apache IoTDB, https://iotdb.apache.org/. cc @jixuan1989
Hybrid, M3 https://m3db.io/, focuses on metrics, Cassandra or something focuses on the trace/log.

ClickHouse could be another solution option?

**Comment by wu-sheng** [comment]
> ClickHouse could be another solution option?

If you have time, could do a research, from my understanding, it doesn't support update, which could be a critical block for use to adopt it.

**Comment by JaredTan95** [comment]
> > ClickHouse could be another solution option?
> 
> If you have time, could do a research, from my understanding, it doesn't support update, which could be a critical block for use to adopt it.

Live updates are supported in later versions of April 2020. And I found it in the official [docs](https://clickhouse.tech/docs/en/sql-reference/statements/alter/update/).
However, the official documentation mentions that update operations are not designed to be frequently updated.
In summary, we can be a pick it up as a discussion.

**Comment by zifeihan** [comment]
> > ClickHouse could be another solution option?
> 
> If you have time, could do a research, from my understanding, it doesn't support update, which could be a critical block for use to adopt it.

Can we insert, reduce or not update by time period？

**Comment by wu-sheng** [comment]
> > > ClickHouse could be another solution option?
> > 
> > 
> > If you have time, could do a research, from my understanding, it doesn't support update, which could be a critical block for use to adopt it.
> 
> Can we insert, reduce or not update by time period？

This is not about can or can't. This is about why we choose that. ClickHouse is super powerful in BI area, as its analysis capability. But if we don't leverage that, all capabilities don't matter.

**Comment by wu-sheng** [comment]
I updated a blog about this, https://skywalking.apache.org/blog/2021-01-17-elastic-change-license/
