### ISSUE TITLE
can't find C++ SDK

### ISSUE THREAD

**Issue by coki230** [apache/skywalking#6223]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question

___
### Question
- the doc said. it had supported Go and C++ SDKs. but i can't find it. can i have a C ++ sdk link? thanks

**Comment by kezhenxu94** [comment]
https://github.com/SkyAPM/cpp2sky/

the link is there https://skywalking.apache.org/docs/

**Comment by coki230** [comment]
@kezhenxu94 3Q, you are a big handsome guy。
