### ISSUE TITLE
Are there any new features for Skywalking Client JS 0.3.0? Live Demo

### ISSUE THREAD

**Issue by zxz9325** [apache/skywalking#6224]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We provided changelog. Please read.

**Comment by wu-sheng** [comment]
Also, we posted it on the website's event page.

**Comment by zxz9325** [comment]
I saw the introduction of new features,But and then tried not found with the difference between version 0.2, may be my configuration has a problem, can show new features on the website's Live Demo? "Make browser as a start of whole distributed tracing",Does this mean that I can use the trace page as a conditional query?

**Comment by wu-sheng** [comment]
> Does this mean that I can use the trace page as a conditional query?

Do you mean this? https://twitter.com/ASFSkyWalking/status/1346356363279011840

About the demo env, it is a demo. SkyWalking is too powerful, we can't show all the things on there. We have only limited resource to support the deployment.

**Comment by zxz9325** [comment]
I saw the new feature of ClientJS-0.3.0 according to the test example provided by the running official [(skywalking-client-test),](https://github.com/SkyAPMTest/skywalking-client-test) but after we introduced ClientJS-0.3.0 to our company's front-end project, we kept reporting errors, and would not automatically send HTTP requests (**v3/segments**). Before, ClientJS-0.2.0 did not report errors, our project was the framework of React, and the error message was :**Uncaught TypeError:First argument must be a string, Buffer, Array, or array-like object.**
Here's the code we added:
`import ClientMonitor from "skywalking-client-js";`
  `ClientMonitor.register({`
    `The collector: "/cfv2",`
    `Service: "cfv2-UI",`
    `ServiceVersion: "1.0.0".`
    `PagePath: "test.html",`
    `UseFmp: true,`
    `DetailMode: true`
  `});`

**Comment by wu-sheng** [comment]
Could you provide a demo to reproduce the error? It is hard to locate it from the stack. And you could ask your frontend team to take a look. Agent is not that complex.

**Comment by kezhenxu94** [comment]
Just took a quick look and seems this is a bug,

https://github.com/apache/skywalking-client-js/blob/239f4b2020aaa8c0f582ea486c74e25dff4b66d9/src/trace/segment.ts#L46

in the `else` block, the url is a string, while in 

https://github.com/apache/skywalking-client-js/blob/239f4b2020aaa8c0f582ea486c74e25dff4b66d9/src/trace/segment.ts#L72

`url.host` is `undefined` and `encode(undefined)` throws the exact error `TypeError:First argument must be a string, Buffer, Array, or array-like object.`, @Fine0830 is that right?

**Comment by Fine0830** [comment]
Hmm... There is no error when I run String(encode(undefined)) in my code. Probably the pr is useful. Let me find it out.

**Comment by kezhenxu94** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/15965696/105357627-0bbc2f80-5c30-11eb-91ee-ec01a7e0c86f.png">

I used this to reproduce https://npm.runkit.com/js-base64

**Comment by Fine0830** [comment]
Ah... It is an amazing library. I run` window.encode = jsBase64.encode`, then I run console.log(String(encode(undefined))) in browser Console, the result is undefined.
![123](https://user-images.githubusercontent.com/20871783/105360697-d6b1dc00-5c33-11eb-89d9-d0d106cacd88.png)

Anyhow, here need to fix this problem. Thank you for fixing this. @kezhenxu94

**Comment by zxz9325** [comment]
> Just took a quick look and seems this is a bug,
> 
> https://github.com/apache/skywalking-client-js/blob/239f4b2020aaa8c0f582ea486c74e25dff4b66d9/src/trace/segment.ts#L46
> 
> in the `else` block, the url is a string, while in
> 
> https://github.com/apache/skywalking-client-js/blob/239f4b2020aaa8c0f582ea486c74e25dff4b66d9/src/trace/segment.ts#L72
> 
> `url.host` is `undefined` and `encode(undefined)` throws the exact error `TypeError:First argument must be a string, Buffer, Array, or array-like object.`, @Fine0830 is that right?



Does this issue affect browser monitoring?When can I try again after fixing this problem? Our project was the framework of React.

**Comment by wu-sheng** [comment]
The codes have been merged, you could try the latest codes.

**Comment by zxz9325** [comment]
> The codes have been merged, you could try the latest codes.

Do: npm install skywalking-client-js --save,   did I download the latest codes?

**Comment by Fine0830** [comment]
> > The codes have been merged, you could try the latest codes.
> 
> Do: npm install skywalking-client-js --save, did I download the latest codes?

No, the code hasn't been released yet.

**Comment by zxz9325** [comment]
> > > The codes have been merged, you could try the latest codes.
> > 
> > 
> > Do: npm install skywalking-client-js --save, did I download the latest codes?
> 
> No, the code hasn't been released yet.

OK, excuse me, when do you have time to release it?

**Comment by wu-sheng** [comment]
You could clone from the GitHub repo, then you have the latest codes. You don't need to wait for our release process.

**Comment by zxz9325** [comment]
Skywalking client js 0.3.0 monitoring has two modes, automatic (ClientMonitor.register())  and manual (ClientMonitor.setPerformance()) ,  What's the difference between the two?

**Comment by Fine0830** [comment]
`setPerformance` can collect metrics manually. like this https://github.com/apache/skywalking-client-js#spa-page

**Comment by codering** [comment]
when to release ...?

**Comment by wu-sheng** [comment]
> when to release ...?

0.3.0 has been released one month ago.

**Comment by codering** [comment]
This bug is fixed ?

> I saw the new feature of ClientJS-0.3.0 according to the test example provided by the running official [(skywalking-client-test),](https://github.com/SkyAPMTest/skywalking-client-test) but after we introduced ClientJS-0.3.0 to our company's front-end project, we kept reporting errors, and would not automatically send HTTP requests (**v3/segments**). Before, ClientJS-0.2.0 did not report errors, our project was the framework of React, and the error message was :**Uncaught TypeError:First argument must be a string, Buffer, Array, or array-like object.**
> ![image](https://user-images.githubusercontent.com/21777063/105136094-0ecdf780-5b2c-11eb-9538-2dea16c31d31.png)
> 
> Here's the code we added:
> `import ClientMonitor from "skywalking-client-js";`
> `ClientMonitor.register({`
> `The collector: "/cfv2",`
> `Service: "cfv2-UI",`
> `ServiceVersion: "1.0.0".`
> `PagePath: "test.html",`
> `UseFmp: true,`
> `DetailMode: true`
> `});`

**Comment by wu-sheng** [comment]
Please don't mix the thread. Is you having any issue, please submit a new issue with codes and steps to reproduce the issue.

**Comment by zxz9325** [comment]
I am now introducing Skywalking 0.3.0 and it is a single page application.
Excuse me, SkywalkingClient JS 0.3.0 when monitoring the browser side, when will the monitoring data be sent, and what we found was that it wasn't real time, there will be a delay of more than 20 seconds.  (like /brower/perfData), and another request (/v3/segments), What is the timing of this request?
what is the sample rate for the Skywalking Client JS 0.3.0 browser monitoring?

**Comment by wu-sheng** [comment]
Your browser may can't afford we report that data immediately, so we choose periodically.
No sampling for performance data, trace sampling rate is as same as server side tracing.
