### ISSUE TITLE
文档为何如此匮乏了。

### ISSUE THREAD

**Issue by huguangjun580** [apache/skywalking#6225]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by huguangjun580** [comment]
question

**Comment by wu-sheng** [comment]
Please use English on GitHub. We have provided all necessary documents.
