### ISSUE TITLE
Agent & collector details

### ISSUE THREAD

**Issue by mdnowshath** [apache/skywalking#6227]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- 
We installed Docker setup H2 for skywalking. We installed OAP server and UI. We need to setup collector. Kindly provide the collector software and network port details from agent to collector or How the communication established from agent to skywalking
___
Regards
Nowshaht

**Comment by kezhenxu94** [comment]
All your questions are already documented, please read before asking: https://github.com/apache/skywalking/tree/master/docs/en/setup 


P.S. H2 is for developing / testing purpose , we don't recommend to use it in production environment
