### ISSUE TITLE
Where is the new operator's manual?

### ISSUE THREAD

**Issue by huguangjun580** [apache/skywalking#6228]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please read the website page before you submit this kind of issue.

https://github.com/apache/skywalking-swck
https://skywalking.apache.org/docs/

**Comment by huguangjun580** [comment]
> 提交此类问题之前，请阅读网站页面。
> 
> [https://github.com/apache/skywalking-swck ](https://github.com/apache/skywalking-swck)
> https://skywalking.apache.org/docs/

There used to be principle pictures, but now it's just a brief introduction. Are there no configuration items in the project?
Is this the so-called new operator's manual? It is recommended to refer to Seata's rookie Handbook.

**Comment by wu-sheng** [comment]
You are asking questions from wrong perspective. We trust our PMC and committer team. They think it is enough, then, it is.
If you want to contribute more details, we are welcome.

**Comment by huguangjun580** [comment]
I am a new user. If I want to use a service, I will first describe how to operate in the specific configuration items of the server and project side, rather than the general description. Therefore, there is no wrong point of view in my question.

If the founder of the service thinks that it is enough, then as a user, I have nothing to say.
