### ISSUE TITLE
8.3.0 SelfObservability change the config as the doc say , still does not work

### ISSUE THREAD

**Issue by ZhouZiHe** [apache/skywalking#6236]
**We have already change the config as doc say** 
https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-telemetry.md#self-observability
![image](https://user-images.githubusercontent.com/20511319/105116730-445fea00-5b06-11eb-91bc-87fe2038be12.png)
**This is our new config below :** 
![image](https://user-images.githubusercontent.com/20511319/105116798-65283f80-5b06-11eb-945e-5861e47a48eb.png)
![image](https://user-images.githubusercontent.com/20511319/105116873-80934a80-5b06-11eb-959d-4df430d34d7f.png)
![image](https://user-images.githubusercontent.com/20511319/105116944-9c96ec00-5b06-11eb-8882-3cfd0cc4716f.png)
**But it didn't seem to work  and the instance disappear too !!!** 
![image](https://user-images.githubusercontent.com/20511319/105117233-1fb84200-5b07-11eb-8bf0-7087c4adc19d.png)
**At the same time , we could get data by using metrics interface :** 
![image](https://user-images.githubusercontent.com/20511319/105139833-c9acc400-5b31-11eb-9e9b-d2a98f955e05.png)
**And I also want to konw is there anything wrong with docs about this when configure OAP backend Self Observability  :**
![image](https://user-images.githubusercontent.com/20511319/105122470-395e8700-5b11-11eb-8d47-c533a1cb8c35.png)
**We used elasticSearch verison : 6.8.2**
_Originally posted by @ZhouZiHe in https://github.com/apache/skywalking/issues/6230#issuecomment-763276177_

**Comment by wu-sheng** [comment]
Don't submit duplicate issue.
