### ISSUE TITLE
Spring Cloud Gateway support not working on 8.2/8.3/6.6/6.5

### ISSUE THREAD

**Issue by haboy52581** [apache/skywalking#6237]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Spring Cloud Gateway support not working on 8.2/8.3/6.6/6.5
I could not get tracing data from oap server or web, using spring cloud Greenwich.SR2 version and spring-cloud-starter-gateway 2.1.5.release version, have already put the plugin jar apm-spring-cloud-gateway-2.1.x-version.jar to plugins dir under agent of skywalking

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Check the cases we provided in the test folder https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/gateway-2.0.x-scenario

**Comment by wu-sheng** [comment]
And https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/gateway-2.1.x-scenario

**Comment by wu-sheng** [comment]
We don't have resources to test all. Check the difference.

**Comment by haboy52581** [comment]
thanks, but in the test case there is no way to use url rewrite with spring cloud gateway

**Comment by wu-sheng** [comment]
Could you be more clear sbout the difference?

**Comment by haboy52581** [comment]
the test case here is not including anything like rewrite url in which case our scenario is not working

**Comment by wu-sheng** [comment]
> the test case here is not including anything like rewrite url in which case our scenario is not working

@ascrutae If you have time, you could give a try.

**Comment by ascrutae** [comment]
Cloud you give the configure of gateway?

**Comment by haboy52581** [comment]
in our code we do not have any controller in api-gateway since we are using spring cloud gateway + webflux:
here is the example:
```  return builder.routes()
                .route(r -> r
                        .path("/*/path1", "/*/path2", "/project/*/path2")
                        .and().method(HttpMethod.GET)
                        .filters(f -> f.modifyResponseBody(path2WebJson.class, path1WebJson.class,
                                (exchange, path2WebJson) -> {
                                    path1WebJson path1WebJson = new path1WebJson(path2WebJson.getpath2());
                                    return Mono.just(path1WebJson);
                                }))
                        .uri(Url))
                .route(r -> r
                        .path("/*/path1", "/*/path1/*",
                                "/project/*/path2",  "/project/*/path2/*")
                        .uri(Url))
                .build();
```
this is when we start the service to register route mapping, but this is never picked up by skywalking
