### ISSUE TITLE
logging.max_history_files does not work

### ISSUE THREAD

**Issue by lzeqian** [apache/skywalking#6238]
This configuration does not work as described.  
    -DSW_LOGGING_LEVEL=DEBUG -Dskywalking.logging.max_history_files=5 -Dskywalking.logging.max_file_size=100
5 additional documents actually generated why???

**Comment by wu-sheng** [comment]
I think `-Dskywalking.logging.max_history_files` is the right one. I am not sure what is the issue. Could you debug `FileWriter`?

**Comment by wu-sheng** [comment]
We tested the config initialization through UT, `SnifferConfigInitializerTest`
