### ISSUE TITLE
How to set up client sampling

### ISSUE THREAD

**Issue by xuguoqi302** [apache/skywalking#6242]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
We have such a scene
It is expected that when the java client sampling is set, the traceId can be guaranteed to be 100% generated, and the traceId can be transferred across services, and reported to the oap service according to the sampling set by the client. If you can, how to set it up, thanks.
___

**Comment by wu-sheng** [comment]
No trace, no trace id. We don't provide such strange mechanism.
