### ISSUE TITLE
Does SkyWalking support thrift-0.9.2?

### ISSUE THREAD

**Issue by FudanYuan2019** [apache/skywalking#6245]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [* ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does SkyWalking support thrift-0.9.2?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
From the supported list(versions we tested), it isn't. https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md
