### ISSUE TITLE
Does toolkit can support wrapper an executor?

### ISSUE THREAD

**Issue by wallezhang** [apache/skywalking#6251]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

I am writing a second-party lib that provide a manager of the thread executors. I want wrapper the executors so that the user can easily execute a task or submit a callable without wrap it manually.

**Comment by wu-sheng** [comment]
I can see `org.apache.skywalking.apm.toolkit.trace.CallableWrapper` exists already, what else are you asking?

**Comment by wallezhang** [comment]
I don't want user wrap `Callable` or `Runnable` manually when invoke `submit()` function. 
e.g. I have an executor 
```
private final ExecutorService executor = ExecutorServiceWrapper
            .of(new ThreadPoolExecutor(5, 10, 1L, TimeUnit.MINUTES,
                    new ArrayBlockingQueue<>(100),
                    new ThreadFactoryBuilder().setNameFormat("refresh-all-value-thread-%d").setDaemon(true).build());
```

And user can invoke `execute()` or `submit()` without wrap the runnable.

**Comment by wu-sheng** [comment]
What is the difference? If you control the `ExecutorServiceWrapper`, you could wrap the `Runnable` to SkyWalking's wrapper internally.

**Comment by wallezhang** [comment]
In fact, there is no difference. However, this can reduce the amount of code when user invoke `execute()` and also reduce the probability of forgetting wrap the task. 😄

**Comment by wu-sheng** [comment]
I mean you could. Rather than user's work. `ExecutorServiceWrapper` could wrap the input parameter.

**Comment by wallezhang** [comment]
Yes, I have done.
