### ISSUE TITLE
mvn package error with "dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin"

### ISSUE THREAD

**Issue by bjo2008cnx** [apache/skywalking#6253]
mvn package error on Mac OS X 10.15 with following details:

`[INFO] --- exec-maven-plugin:1.6.0:exec (default) @ receiver-proto ---
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/michael/codes-wwdz-arch/service-goven/skywalking830/oap-server/server-receiver-plugin/receiver-proto/target/bin/flatc (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib`

Could you give some help?Thank you very much.
Version: 8.3.0

**Comment by wu-sheng** [comment]
Read FAQ, https://github.com/apache/skywalking/blob/master/docs/en/FAQ/How-to-build-with-mac-m1.md.
I guess you are using the latest MacBook(Pro)

**Comment by bjo2008cnx** [comment]
Thank you wu-sheng very much.  I'm trying this solution.

**Comment by ywf4026** [comment]
@wu-sheng I also got this problem. addding -Dos.detected.classifier=osx-x86_64 does't work fine.

tag:v8.4.0

[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.13
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 13
[INFO] os.detected.classifier: osx-x86_64


![image](https://user-images.githubusercontent.com/3722641/108595786-a12c1a00-73bc-11eb-8e77-597ab33c3b24.png)

**Comment by wu-sheng** [comment]
If you are using M1 chip too, sorry, this is out of our control.

**Comment by kezhenxu94** [comment]
> @wu-sheng I also got this problem. addding -Dos.detected.classifier=osx-x86_64 does't work fine.
> 
> tag:v8.4.0
> 
> [INFO] os.detected.name: osx
> [INFO] os.detected.arch: x86_64
> [INFO] os.detected.version: 10.13
> [INFO] os.detected.version.major: 10
> [INFO] os.detected.version.minor: 13
> [INFO] os.detected.classifier: osx-x86_64
> 
> ![image](https://user-images.githubusercontent.com/3722641/108595786-a12c1a00-73bc-11eb-8e77-597ab33c3b24.png)

You're using MacOS version under 10.15, you have to compile flatc by yourself and use `./mvnw -Dfbs.compiler=` to specify your local flatc compiler

**Comment by ywf4026** [comment]
> > @wu-sheng I also got this problem. addding -Dos.detected.classifier=osx-x86_64 does't work fine.
> > tag:v8.4.0
> > [INFO] os.detected.name: osx
> > [INFO] os.detected.arch: x86_64
> > [INFO] os.detected.version: 10.13
> > [INFO] os.detected.version.major: 10
> > [INFO] os.detected.version.minor: 13
> > [INFO] os.detected.classifier: osx-x86_64
> > ![image](https://user-images.githubusercontent.com/3722641/108595786-a12c1a00-73bc-11eb-8e77-597ab33c3b24.png)
> 
> You're using MacOS version under 10.15, you have to compile flatc by yourself and use `./mvnw -Dfbs.compiler=` to specify your local flatc compiler

thanks, it is useful
