### ISSUE TITLE
java.lang.NullPointerException at org.apache.skywalking.apm.plugin.spring.mvc.commons.JavaxServletResponseHolder.statusCode(JavaxServletResponseHolder.java:32 )

### ISSUE THREAD

**Issue by wangriyue001** [apache/skywalking#6257]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
spring-web version 5.2.7
skywalking version 8.3.0
spring mvc apm NullPointerException

**Comment by wangriyue001** [comment]
java.lang.NullPointerException
        at org.apache.skywalking.apm.plugin.spring.mvc.commons.JavaxServletResponseHolder.statusCode(JavaxServletResponseHolder.java:32
)
        at org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.AbstractMethodInterceptor.afterMethod(AbstractMethodIntercep
tor.java:184)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:97)

**Comment by wu-sheng** [comment]
From the codes, seem it can't get the `response`. Spring 5.2.0 has been tested by this case, you could run some cross check.

https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/spring-4.3.x-scenario

**Comment by wangriyue001** [comment]
now spring version 5.2.7 ，Which version will work
