### ISSUE TITLE
How to pressure test es and oap

### ISSUE THREAD

**Issue by YczYanchengzhe** [apache/skywalking#6258]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hello, I would like to ask about the use of oap and es. We currently deploy 10 oap nodes and 7 es nodes. We want to stress test the current bottleneck of es and oap. Is there a recommended solution? , I tried to start multiple agents to perform stress testing, but it did not reach the bottleneck. I wonder if there are some problems with my method.
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think this is out of the community's responsibility. You are setting the performance test, you set the benchmark and cases.
