### ISSUE TITLE
Endpoint ID too long

### ISSUE THREAD

**Issue by pantovad** [apache/skywalking#6262]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
docker 8.3.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
Getting in OAP server:
2021-01-26 16:15:33,380 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO -410069 [DataCarrier.H2_ASYNCHRONOUS_BATCH_PERSISTENT.BulkConsumePool.0.Thread] ERROR [] - Data truncation: Data too long for column 'endpoint_id' at row 1
Using MySQL 5.7 and the column is set in segment table as: 
`endpoint_id` varchar(200) DEFAULT NULL
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This should have been fixed in https://github.com/apache/skywalking/pull/6188
