### ISSUE TITLE
Introduce LAL(Log Analysis Language) 

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6264]
Hi @arugal @EvanLjp @hanahmily @kezhenxu94 and other contributors.

I want to bring the highest priority feature of the 8.5.0. Here is the proposal.
SkyWalking has 2 languages targeting the analysis related features.
1. OAL introduced in 6.x and is enhanced w/ time to support language-agent tracer and service mesh telemetry analysis to get metrics.
2. MAL introduced in 8.2 and 8.3 to adopt the native and 3rd party meter system, including Prometheus, MicroMeter, Zabbix(WIP)

With the incoming 8.4.0 release, we have logging collection, persistent, and query capability. Now, we should focus on enhancing the analysis feature. That is where LAL stands on.
The LAL should be able to provide the following features.
1. It should be defined in the config file, like OAL script, and MAL YAML. It is usable by the end users.
2. Support structure unify log data content. Especially for TEXT format log. Should be able to convert it to the JSON, or something for further process.
3. Support TEXT, YAML, JSON formats
4. Filter logs based on conditions
5. Build new meter(metrics) based on the match conditions of structured log. Such as, you could set a business error metrics if there is a specific text(`xyz fails`) detected in the logs.
6. Build collaboration with trace context. Such as isolate text(trace_id) from the text by using some split/regex mechanism.
7. Entity assignment mechanism. Build the connection between entity(service/instance/endpoint) with the log contents.

From the tech perspective, this could reference from the MAL tech stack. If anyone of @apache/skywalking-committers will lead this, please reply here.

**Comment by kezhenxu94** [comment]
Since my #6322 will leverage some features described in this issue, I’ll take this issue if there is no one already works on it.

**Comment by wangruice** [comment]
please send me a document link ,I don't know how to config ,it do not work and have no error log
need  to install filebeat,logstash?

**Comment by wu-sheng** [comment]
> please send me a document link ,I don't know how to config ,it do not work and have no error log
> need to install filebeat,logstash?

You are asking at wrong place. We don't support those yet. You need to read doc of agent application toolkit.

**Comment by kezhenxu94** [comment]
@wangruice you opened this issue https://github.com/apache/skywalking/issues/6405 and I answered there, you have obvious error in configuration, please check there, don't ask here and there

**Comment by wangruice** [comment]
> @wangruice you opened this issue #6405 and I answered there, you have obvious error in configuration, please check there, don't ask here and there

thanks
