### ISSUE TITLE
OAP complains errors once disabling "browser_error_log" in oal file

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#6265]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug

- What happened?
When disabling `browser_error_log` in `oal/browser.oal`, OAP would raise an error as below:

```
 mismatched input 'browser_error_log' expecting {'segment', 'top_n_database_statement', 'endpoint_relation_server_side', 'service_relation_server_side', 'service_relation_client_side', 'alarm_record', 'http_access_log', 'zipkin_span', 'jaeger_span', 'profile_task', 'profile_task_log', 'profile_task_segment_snapshot'}

```

That's due to https://github.com/apache/skywalking/blob/7b1c63de11b78b98b40e019a5b31ccbac54da9c2/oap-server/oal-grammar/src/main/antlr4/org/apache/skywalking/oal/rt/grammar/OALParser.g4#L62-L65, which block the input.

**Comment by wu-sheng** [comment]
Let me take care of this.
