### ISSUE TITLE
Some Problem in New Log UI

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#6288]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [- ] Bug

1. could not read the log details after press the follow buttons.
![image](https://user-images.githubusercontent.com/31562192/106375768-2168ec00-63ca-11eb-993e-67b530970b7a.png)
![image](https://user-images.githubusercontent.com/31562192/106375770-24fc7300-63ca-11eb-8a0d-33172591e646.png)
![image](https://user-images.githubusercontent.com/31562192/106375773-275ecd00-63ca-11eb-893a-82ea8a9c9926.png)

https://user-images.githubusercontent.com/31562192/106375997-00a19600-63cc-11eb-999e-a7c4717e4b2a.mov

2. chould not read log from the trace ui.

https://user-images.githubusercontent.com/31562192/106375990-f089b680-63cb-11eb-9854-6402f1d068d4.mov

3. UI doesn't support multi conditions query in include keywords and exclude keywords. The Backend service and protocol have already supported it.

![image](https://user-images.githubusercontent.com/31562192/106375813-81f82900-63ca-11eb-822d-922cbfb3a934.png)

![image](https://user-images.githubusercontent.com/31562192/106375815-845a8300-63ca-11eb-86ec-eb2d4ae5edb1.png)

**Comment by wu-sheng** [comment]
> UI doesn't support multi conditions query in include keywords and exclude keywords. The Backend service and protocol have already supported it.

@Fine0830 Please take a reference from the tag, except this time, we don't need `key=value`. Once user clicks the `enter`, then a new condition

**Comment by wu-sheng** [comment]
And please add a tip about how to enter multiple conditions.

**Comment by wu-sheng** [comment]
> chould not read log from the trace ui.

@Fine0830 From my reading of Browser logs, these should relate to the fields we recently deleted. The UI codes seem haven't remove all of them on this page, but the log query page is OK.
