### ISSUE TITLE
oap or storage performance

### ISSUE THREAD

**Issue by HarryFQ** [apache/skywalking#6296]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When we used pinpoint before, we encountered some performance problems on pinpoint data storage. Therefore, we plan to find better alternatives and want to compare it. Do you have more detailed design documents and performance tests for data storage on skywalking? 
___
### Bug
- Which version of SkyWalking, OS, and JRE?
 JDK1.8.0_65,ES7.6.2, sky8.3.0
- Which company or project?

- What happened?

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
If possible, provide a way to reproduce the error. e.g. demo application, component version.
By configuring some parameters such as agent.sample_n_per_3_secs, we can see that some ingored_trace will be ignored in the log. If the configuration does not have these, are all uploaded to OAP? OAP For the upload of thousands of nodes, we can configure some parameters such as agent .sample_n_per_3_secs, I can see that some ingored_trace will be ignored in the log, so if the configuration does not have these, are all uploaded to OAP? Does OAP have problems with the upload performance of our thousands of nodes?

**Comment by wu-sheng** [comment]
We don't have that for public. But you could easily find 100+ TB and 10+ PB level use cases without performance issue.

**Comment by wu-sheng** [comment]
SkyWalking doesn't rely on calculate performance of db like pinpoint did. So there is nothing to compare. Basically, we are different, and read the STAM paper to understand what we do.
