### ISSUE TITLE
The use of about the Spring annotation plugin

### ISSUE THREAD

**Issue by zxz9325** [apache/skywalking#6300]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- What do you want to know?
1. I read the documentation [https://github.com/apache/skywalking/blob/8.3.0/docs-hotfix/docs/en/setup/service-agent/java-agent/agent-optional-plugins/Spring-annotation-plugin.md](url) about   trace all methods of beans in Spring context: apm-spring-annotation-plugin-8.4.0-SNAPSHOT.jar, try it but doesn't seem to work
  My steps:
     1). Move the apm-spring-annotation-plugin-8.4.0-SNAPSHOT.jar to agent\plugins\;
     2). Add config 'plugin.springannotation.classname_match_regex=${SW_SPRINGANNOTATION_CLASSNAME_MATCH_REGEX: com.musi.service.PersonService}' to agent.config;

----------------------------------------------------------------------------------------------------
2. In addition, I pulled the master's code, but compile the code returns an error :  'Cannot resolve symbol 'LogTags''..

**Comment by wu-sheng** [comment]
I think we have tested that, https://github.com/apache/skywalking/blob/1f391b85b91b6b73758c0698b8c8e43fbb2194f9/test/plugin/scenarios/exception-checker-spring-scenario/configuration.yml#L22. I don't think you are using the correct regex.

**Comment by zxz9325** [comment]
I would like to try skywalking the new features of 8.4，But I pulled the master's code, but compile the code returns an error :
![image](https://user-images.githubusercontent.com/21777063/106547840-eb9e4180-6548-11eb-9f9c-a6b5d6c8daf2.png)
Some classes seem to be missing, For example, org.apache.skywalking.apm.network.logging.v3.LogTags;

**Comment by wu-sheng** [comment]
8.4 is still on voting, and you didn't follow the compiling documentation. `Download` button on the GitHub is not suitable option for SkyWalking.

**Comment by wu-sheng** [comment]
And this part you mentioned, AFAIK, nothing changed there.
