### ISSUE TITLE
The compatibility between tomcat plugin & SpringMVC plugin

### ISSUE THREAD

**Issue by furaul** [apache/skywalking#6306]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?

When I use tomcat plugin & SpringMVC plugin，My java codes are like this
当我同时使用tomcat插件和springMVC插件时，我的代码如下所示。

`
@RequestMapping(value = "/**")

public Object doService() {

}

`

Skywalking only collect ’/\*\*‘ as the endpoint, without the real endpoint, when I send the request like '/api-gateway/query'.
当我使用”/api-gateway/query“发送请求时，Skywalking只会统计”/\*\*“作为endpoint，不会统计实际的endpoint。

When I removed springMVC plugin, Skywalking collect the real endpoint like '/api-gateway/query'.
当我移除了springMVC插件之后，Skywalking统计的endpoint就是真实的endpoint，”/api-gateway/query“。

In my opinion, Skywalking should collect both '/\*\*' and '/api-gateway/query'. 
个人拙见，Skywalking应该将两者都展示出来。

When I use undertow plugin & SpringMVC plugin, Skywalking collect both.
当我使用undertow插件和SpringMVC插件时，Skywalking会同时统计undertow的endpoint和SpringMVC的endpoint。

![skywalking](https://user-images.githubusercontent.com/4946739/106586470-74d26a00-6583-11eb-8694-7cb354fc1b1a.png)

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.2.0
- Which company or project?
Didi
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
Use tomcat plugin & SpringMVC plugin
Use undertow plugin & SpringMVC plugin
根据问题描述即可重现。

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
To verify if the result is as exceped, and the purpose of the design.
确认结果是否符合预期，以及这样设计的原因是什么？

**Comment by wu-sheng** [comment]
> Skywalking only collect ’/**‘ as the endpoint, without the real endpoint, when I send the request like '/api-gateway/query'.

That is expected, because you code says so. You could find the real URL in the span's tag(value = 'http://ip:port/api-gateway/query'). But not as an endpoint.
If you activate both, then the statistic will be wrong, you access the system once, the traffic will count 2, as you have both spans as entry span.

**Comment by furaul** [comment]
What about the situation that Skywalking collect them both when I activate undertow plugin & SpringMVC plugin, the undertow endpoint and SpringMVC endpoint are both in the trace, as the screenshot is shown.

**Comment by wu-sheng** [comment]
> What about the situation that Skywalking collect them both when I activate undertow plugin & SpringMVC plugin, the undertow endpoint and SpringMVC endpoint are both in the trace, as the screenshot is shown.

Metrics of the dashboard will be wrong.

**Comment by wu-sheng** [comment]
> What about the situation that Skywalking collect them both when I activate undertow plugin & SpringMVC plugin, the undertow endpoint and SpringMVC endpoint are both in the trace, as the screenshot is shown.

Metrics of the dashboard will be wrong.
