### ISSUE TITLE
Database Metrics not showing on Skywalking UI , Data is present in mysql Database

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6308]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Database metrics not showing on UI. Although data is present database. Please help if not setting parameter correctly.
I can see data in mysql database but not on UI.

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
That depends on the plugins. They need to report database related spans. 
You could see our demo, there are database metrics there.

**Comment by JayeshMuley** [comment]
Is it because of some threshold values 
![SkyUI](https://user-images.githubusercontent.com/75727262/106595209-389a0c00-6579-11eb-956e-97e175c6c1a5.png)
![skydatabase](https://user-images.githubusercontent.com/75727262/106595238-42237400-6579-11eb-98bf-b5ba4a23ceaf.png)

**Comment by wu-sheng** [comment]
There is threshold, but from your screenshot, the data exists already. 
Top N statement collected, consider time rangr issue.
Then, latency is based on your span duration, whether it is over 1ms?
And you select hour level metrics, you need at least 60 calls in one hour to make CPM as 1.
