### ISSUE TITLE
The time table about skywalking 8.4.0 release

### ISSUE THREAD

**Issue by itfinally** [apache/skywalking#6313]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I noticed that 8.4.0 milestone has been closed. 

Do you have a time table about skywalking 8.4.0 release ?  

We look forward to release of this version. 

Thank.

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?

___

**Comment by wu-sheng** [comment]
All official things happen in the mail list, Mail list: dev@skywalking.apache.org. 
Mail to dev-subscribe@skywalking.apache.org, follow the reply to subscribe the mail list.
