### ISSUE TITLE
where set “allArguments[0]”  to EnhancedInstance class at logback async ？

### ISSUE THREAD

**Issue by killGC** [apache/skywalking#6314]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

package org.apache.skywalking.apm.toolkit.activation.log.logback.v1.x.async;

import org.apache.skywalking.apm.agent.core.context.ContextManager;
import org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance;
import org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstanceMethodsAroundInterceptor;
import org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.MethodInterceptResult;

import java.lang.reflect.Method;

public class AsyncAppenderBaseMethodInterceptor implements InstanceMethodsAroundInterceptor {

    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
        MethodInterceptResult result) throws Throwable {
        if (allArguments[0] instanceof EnhancedInstance) {
            EnhancedInstance instances = (EnhancedInstance) allArguments[0];
            instances.setSkyWalkingDynamicField(ContextManager.getGlobalTraceId());
        }
    }

    @Override
    public Object afterMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
        Object ret) throws Throwable {
        return ret;
    }

    @Override
    public void handleMethodException(EnhancedInstance objInst, Method method, Object[] allArguments,
        Class<?>[] argumentsTypes, Throwable t) {
    }
}

which class set allArguments[0] to EnhancedInstance ？
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Sorry, please don't expect the community to explain the codes in the issue. It is unaffordable. Simple answer is, any class enhanced by SkyWalking's plugin, then its objects are implementing EnhancedInstance automatically.
