### ISSUE TITLE
SkyWalking native APM Database - BanyanDB

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6315]
This discussion originally happened in the mail list, https://lists.apache.org/thread.html/rb6d663a5187eb0b5d2af6c254c1dfb779124c15f1044a31fed24f361%40%3Cdev.skywalking.apache.org%3E, started by @hanahmily 

___
Hi, community:

As the previous thread mentioned[1], Sheng and I had a long time discussing
a dedicated database for storing skywalking hyper-modal data. The first
idea could be traced back to the time I joined SkyWalking, which still was
Sheng's personal project. The main architecture is discussed in my graduate
thesis in 2017, with the title of "The design and implement of tracing
database system". In that paper, I discussed a potential database
implementation to handling tracing data and design an abstract model to
save the data.

After that, several issues blocked me from pushing this work till I figured
them out about one month ago. Simultaneously, the debate of the ES's
license transferring caused Sheng and me to decide to kick the project off.

In recent weeks, I composed a list[2] to trace the main ideas and tech
stacks that could affect the final architecture. If you have any ideas,
feel free to comment on them.

From my perspective, we would verify some potential data modals before
starting the design. Based on that, I begin a study[2] to choose an idea
data modal from several candidates. In this study, I should set up some
stimulation workloads to test data models. These workload designs need your
help to make them as close to the real scenarios. If anyone has any ideas,
pls let me know.

In the next few weeks, I will be on the study. Once some results merge, the
community will get the updates.

1. https://github.com/apache/skywalking/issues/6219#issue-787602819
2. https://docs.google.com/document/d/1qzzJ3caBtAFmFBBoB0VoETqWAUMP2jSR4UR3C3Jykos/edit?usp=sharing
3. https://docs.google.com/document/d/1bvvycAe1MlXKIJPdGUFBS8XDI7nPpIpI44RKwH_UkJc/edit?usp=sharing

**Comment by wu-sheng** [comment]
FYI @tristaZero , as you asked.

**Comment by tristaZero** [comment]
Thanks @wu-sheng , I will give them a look later.

**Comment by wu-sheng** [comment]
Data Model, https://docs.google.com/document/d/1XFzHWXSWyIC7AVNIx0ifQ0eJAJYfoPO-2j_lgbl9zu8/edit#

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-banyandb MVP is nearly done.
