### ISSUE TITLE
Show selectors scrollbar in all pages

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6317]
The current selector(service group/service/instance/endpoint) in all pages supports scrolling, but it is not clear.

![image](https://user-images.githubusercontent.com/5441976/106832980-ace5c400-66cd-11eb-8882-e35b4e71e1cf.png)

@Fine0830 Please help on polishing this a little.

**Comment by Fine0830** [comment]
We should set scroller in computer system settings.
![10](https://user-images.githubusercontent.com/20871783/106838090-942ddc00-66d6-11eb-96f4-fbe0b9c66b26.jpeg)

**Comment by wu-sheng** [comment]
I have set that too on the MacOS, but nothing shows on the Chrome.

**Comment by Fine0830** [comment]
Close this via https://github.com/apache/skywalking-rocketbot-ui/pull/426

**Comment by wu-sheng** [comment]
Please sync the submodule when you have time.
