### ISSUE TITLE
Skywalking supports Postgreql as storage option

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6321]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Is there any way to use Postgresql as a storage option for Skywalking.

Thanks and Regards,
Jayesh
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We support H2 and MySQL today, PostgreSQL could be supported as a storage plugin.
The contribution is welcome.

**Comment by haoyann** [comment]
I would like to contribute to this issue.

**Comment by wu-sheng** [comment]
> I would like to contribute to this issue.

Welcome, if you need any help, ping me

**Comment by wu-sheng** [comment]
> I would like to contribute to this issue.

Please evaluate how many libs and sizes of them before you write codes.

**Comment by haoyann** [comment]
Familiar with the code, I think this part of the function should be written in the `storage-jdbc-hikaricp-plugin` module, like h2、 mysql, there may be some differences, is right?

**Comment by wu-sheng** [comment]
> Familiar with the code, I think this part of the function should be written in the `storage-jdbc-hikaricp-plugin` module, like h2、 mysql, there may be some differences, is right?

Yes, it is. But we need to depend on the driver libs.

**Comment by haoyann** [comment]
#1964
```
MySQL driver is NOT allowed in Apache official distribution and source codes.
Please download MySQL driver by yourself. Copy the connection driver jar to oap-libs
```
Postgreql have the same problem?

**Comment by wu-sheng** [comment]
Postgreql driver should be licensed as Apache 2.0, if so, it doesn't have this issue. The MySQL driver is GPL license.

**Comment by haoyann** [comment]
The PostgreSQL JDBC Driver is distributed under the BSD-2-Clause License. Should be no problem
https://jdbc.postgresql.org/about/license.html

**Comment by wu-sheng** [comment]
Yes, according to ASF doc, https://www.apache.org/legal/resolved.html#category-a, it should be fine.

**Comment by haoyann** [comment]
@wu-sheng .Hi, I have completed this part of the function, but how do I test.

**Comment by wu-sheng** [comment]
The upstream has the e2e to cover all tests.
- GitHub action control file, https://github.com/apache/skywalking/tree/master/.github/workflows
- e2e test codes, https://github.com/apache/skywalking/tree/master/test/e2e
- doc, https://github.com/apache/skywalking/blob/master/docs/en/guides/README.md#end-to-end-tests-e2e-for-short

Please run the new tasks on local and make them passed. The upstream tests will cause more time.

**Comment by haoyann** [comment]
> The upstream has the e2e to cover all tests.
> 
> * GitHub action control file, https://github.com/apache/skywalking/tree/master/.github/workflows
> * e2e test codes, https://github.com/apache/skywalking/tree/master/test/e2e
> * doc, https://github.com/apache/skywalking/blob/master/docs/en/guides/README.md#end-to-end-tests-e2e-for-short
> 
> Please run the new tasks on local and make them passed. The upstream tests will cause more time.

Thanks.
