### ISSUE TITLE
When to fix the bug of  Skywalking Client JS 0.3.0 ? 

### ISSUE THREAD

**Issue by codering** [apache/skywalking#6323]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
   - Bug

___
### Question
- When to fix this bug?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
   Skywalking Client JS 0.3.0
- Which company or project?
   
- What happened?
 Browser error log: Uncaught TypeError:First argument must be a string, Buffer, Array, or array-like object.
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by codering** [comment]
ref https://github.com/apache/skywalking/issues/6224#issuecomment-763369708

**Comment by wu-sheng** [comment]
This is a wrong example of submitting issue. Please provide full information and how to reproduce the error.

**Comment by codering** [comment]
你们明明知道这是个bug，而且pr已经合并了！。。。这都过了半个月了，是准备过完年再说？

**Comment by wu-sheng** [comment]
If you are so unpolite, the community would not answer your question again. Issue locked.
