### ISSUE TITLE
about skywalking8.4.0's new feature for collecting logs

### ISSUE THREAD

**Issue by zxz9325** [apache/skywalking#6325]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- What do you want to know?
 I'd like to try out Skywalking8.4.0's new feature for collecting logs, according to the document [https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-log4j-2.x.md#grpc-reporter](url)
 1. `<GRPCLogClientAppender name="grpc-log"/>`
 2. `plugin.toolkit.log.grpc.reporter.server_host=${SW_GRPC_LOG_SERVER_HOST:127.0.0.1}
plugin.toolkit.log.grpc.reporter.server_port=${SW_GRPC_LOG_SERVER_PORT:11800}
plugin.toolkit.log.grpc.reporter.max_message_size=${SW_GRPC_LOG_MAX_MESSAGE_SIZE:10485760}
plugin.toolkit.log.grpc.reporter.upstream_timeout=${SW_GRPC_LOG_GRPC_UPSTREAM_TIMEOUT:30}`

I don't see the effect, Is there anything else that needs to be configured?

**Comment by wu-sheng** [comment]
Have you used the latest(8.4.0) toolkit in your codes? Our demo env is using this right now.

**Comment by zxz9325** [comment]
I can already see demo env  the results.

1. maven config

   `  <dependency> `
             `<groupId>org.apache.skywalking</groupId> `
             `<artifactId>apm-toolkit-log4j-2.x</artifactId> `
             `<version>8.4.0</version> `
        ` </dependency>`

2. log4j2.xml config
    `    <appenders> `
          `   <Console name="Console" target="SYSTEM_OUT"> `
               `<PatternLayout pattern="%d [%traceId] %-5p %c{1}:%L - %m%n"/> `
        ` </Console> `

        ` <GRPCLogClientAppender name="grpc-log"/> `
   `  </appenders>`

3. agent.conf  add config
  `plugin.toolkit.log.grpc.reporter.server_host=${SW_GRPC_LOG_SERVER_HOST:127.0.0.1}`
  `plugin.toolkit.log.grpc.reporter.server_port=${SW_GRPC_LOG_SERVER_PORT:11800}`
 `plugin.toolkit.log.grpc.reporter.max_message_size=${SW_GRPC_LOG_MAX_MESSAGE_SIZE:10485760}`
 `plugin.toolkit.log.grpc.reporter.upstream_timeout=${SW_GRPC_LOG_GRPC_UPSTREAM_TIMEOUT:30}`

4. skywalking 8.4 the storage mode of choice is H2

Such configuration, I can print tracID in the log, but I don't have the log report effect, is there anything else that needs to be configured?

**Comment by wu-sheng** [comment]
`<Console name="Console" target="SYSTEM_OUT">`, you are outputting to console? We need you to target this appender for your logs.

**Comment by wu-sheng** [comment]
Take a look at our demo source codes, https://github.com/SkyAPMTest/skywalking-live-demo/blob/master/projectB/src/main/resources/log4j2.xml

**Comment by zxz9325** [comment]
I experienced it. Thanks
