### ISSUE TITLE
Can I delete oap-role.yaml oap-rolebinding.yaml in skywalking-kubernetes

### ISSUE THREAD

**Issue by xiangwangcheng** [apache/skywalking#6326]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [✔️] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What's role/rolebinding/serviceaccount for in skywalking-kubernetes, can I delete them?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean? If you want to change anything, all source codes are open for you.

**Comment by kezhenxu94** [comment]
@xiangwangcheng for `role` and `RoleBinding`, if you don't enable Envoy ALS (or you don't know what Envoy ALS is), you can safely delete it, at this time, it takes no effect at all so leaving them there does no harm.

But SkyWalking OAP needs a service account, hence you cannot delete `oap-serviceaccount.yaml`

**Comment by xiangwangcheng** [comment]
> @xiangwangcheng for `role` and `RoleBinding`, if you don't enable Envoy ALS (or you don't know what Envoy ALS is), you can safely delete it, at this time, it takes no effect at all so leaving them there does no harm.
> 
> But SkyWalking OAP needs a service account, hence you cannot delete `oap-serviceaccount.yaml`

Thank you for the quick reply!
