### ISSUE TITLE
'spanLayer' is null in optional plugin(gateway-2.0.x-plugin gateway-2.1.x-plugin) for springcloud gateway?

### ISSUE THREAD

**Issue by navychi** [apache/skywalking#6331]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion

___
### Question
- What do you want to know?
'spanLayer' is null in optional plugin(gateway-2.0.x-plugin gateway-2.1.x-plugin) for springcloud gateway.
![Dingtalk_20210206090616](https://user-images.githubusercontent.com/43361137/107103990-cec08180-685a-11eb-8073-0b7ad373b4b6.jpg)

___

**Comment by wu-sheng** [comment]
You are welcome to fix this through pull request.

**Comment by navychi** [comment]
Also, Why NettyRoutingFilterInterceptor In Spring Cloud Gateway Plugin using LocalSpan, and setting  "SpringCloudGateway/RoutingFilter" as default operation name?
Would it be better to use EntrySpan and set different request path as operation name?

**Comment by wu-sheng** [comment]
Because the webflux plugin takes the responsibility of creating entry span. Routing is only for propagating the context.

**Comment by wu-sheng** [comment]
Read this expected data file in the test, https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/gateway-2.0.x-scenario/config/expectedData.yaml#L46
