### ISSUE TITLE
The dashboard often does not display data

### ISSUE THREAD

**Issue by githubphy** [apache/skywalking#6333]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.20，centos7，jdk8
- What happened?
The entire dashboard often does not display data, but the link tracking data is normal, and OAP has no abnormal error information. In the 14 node es cluster I used, the CPU of most nodes is about 70%. The average QPS of the ES cluster is 30000-40000, and occasionally the peak value reaches 100000. Trace index has a large amount of data. I set 28 Shards. The amount of data in other metric indexes is very small, so 2shard is set. Is this reasonable? What's the reason why we can't collect metric data?

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> the CPU of most nodes is about 70%.

This clearly shows you are over loaded. 70% CPU used is not reasonable for any case, And why your QPS is so high?

**Comment by githubphy** [comment]
> > the CPU of most nodes is about 70%.
> 
> This clearly shows you are over loaded. 70% CPU used is not reasonable for any case, And why your QPS is so high?
We have access to about 1000 applications, and have been reporting data constantly, resulting in frequent es writing

Attached is a monitoring chart of ES cluster
<img width="1660" alt="es" src="https://user-images.githubusercontent.com/9158859/107108300-e22b1700-6871-11eb-850d-935aac454aa7.png">

**Comment by wu-sheng** [comment]
Do you have self-observability of SkyWalking? It provides the details of data insert/update performance.

To be honest, your CPU usage has shown clearly, your ElasticSearch is over loaded.
