### ISSUE TITLE
Skywalking multi-database support

### ISSUE THREAD

**Issue by webb2019** [apache/skywalking#6337]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
Does Skywalking have any plans to support multiple databases, such as MySQL, SQL Server, Oracle？

**Comment by wu-sheng** [comment]
MySQL is already available, with H2 and TiDB. PostgreSQL is tracked at #6321. But Oracle? No plan on the Apache repo. But the extension mechanism supports you or someone to provide implementations on other 3rd party repo.
