### ISSUE TITLE
skywalking support http-client apm plugin?

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#6346]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

org.asynchttpclient.async-http-client,  skywalking can support this client apm-plugin?

**Comment by wu-sheng** [comment]
Check the supported list before you submitted issue, it is on the list.

**Comment by xu1009** [comment]
skywalking apm-httpsayncclient use apache http client, not support org.asynchttpclient.async-http-client

**Comment by wu-sheng** [comment]
What are talking about? https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-sdk-plugin/asynchttpclient-2.x-plugin/pom.xml#L38-L40

**Comment by xu1009** [comment]
https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-sdk-plugin/httpasyncclient-4.x-plugin/pom.xml 

ok,my porject use this version, it is diff with 2.x version

**Comment by xu1009** [comment]
> What are you talking about? https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-sdk-plugin/asynchttpclient-2.x-plugin/pom.xml#L38-L40

can this plugin use in skywalking 7.0?

**Comment by wu-sheng** [comment]
I don't know, this is not upstream's responsibility.
