### ISSUE TITLE
Skywalking NodeJS MongoDB Integration

### ISSUE THREAD

**Issue by joshkurz** [apache/skywalking#6352]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ *] Feature or performance improvement

___
### Question
- What do you want to know?
Is there any plan to integrate mongodb into the nodejs apm? Curious if there is a way to get mongodb integrated if running nodejs.

___

**Comment by wu-sheng** [comment]
We are welcome the contribution.

**Comment by joshkurz** [comment]
@wu-sheng ok. Just for clarification. I have not worked on this library before. 

This would go into this library correct? https://github.com/apache/skywalking-nodejs I see another nodejs apm, but it seems to not be recently active.

**Comment by wu-sheng** [comment]
Both of them are working with SkyWalking 8.x. Your link is the official Apache repo. The other is 3rd party maintained by individual. They use different cores.

**Comment by iIdiomatic** [comment]
@wu-sheng Didn't get you, the links given says, mongodb already supported - 

`There are some built-in plugins that support automatic instrumentation of NodeJS libraries`

What exactly needs to be done here?

**Comment by wu-sheng** [comment]
Simple answer is, waiting for 0.2.0 release. It is in the process.
