### ISSUE TITLE
Need to post  Alarm to https , How to provide header , also need hostname with alarm

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6353]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Need to post  Alarm to https , How to provide header. Also how to get the Hostname along with Alarm.
For example need to post the alarms through

curl -X POST \
  https://*********************/event \
  -H 'applicationauthorization: dhlhsadkjfhkjsdhkhdf' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{"Entity": "","severity": "CRITICAL","description":"High CPU Utilization","createdTime": "1573304437","source": "Postman", "priority": "MEDIUM"}'

   
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think you should take a look at this, https://github.com/apache/skywalking/blob/master/oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/WebhookCallback.java.

I don't find the authentication configuration right now. Do you want to send a pull request to add?

**Comment by Prasanna0806** [comment]
@wu-sheng how to provide headers details in alarm-settings.yml file.

**Comment by wu-sheng** [comment]
@Prasanna0806 Why do you ask again?

**Comment by JayeshMuley** [comment]
Our Endpoint required SSL Authentication and getting this error - How to resolve this - 

2021-02-08 18:00:25,477 - org.apache.skywalking.oap.server.core.alarm.provider.WebhookCallback - 88 [pool-2-thread-1] ERROR [] - send alarm to https://10.136.105.9/integration/work failure.
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_181]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964) ~[?:1.8.0_181]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328) ~[?:1.8.0_181]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322) ~[?:1.8.0_181]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614) ~[?:1.8.0_181]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_181]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:1.8.0_181]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[?:1.8.0_181]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[?:1.8.0_181]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_181]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_181]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_181]
        at

**Comment by wu-sheng** [comment]
I am not following. We don't support that, at least, no tested. I have given you the codes, which only have 20+ lines. Read and debug them.

**Comment by JayeshMuley** [comment]
ya got it thanks.

**Comment by iIdiomatic** [comment]
@wu-sheng So the way to go here is add configuration in file for https, and then accept cert. path , for this webhook-https, config has to be created as there can be multiple webhook, http and https combination. 

Let me know for what I think is correct, or suggest better approach if any, will work on it to submit MR.

**Comment by wu-sheng** [comment]
Basically, yes. It is better we discuss the format of yaml you propose first.

**Comment by iIdiomatic** [comment]
```
webhooks:
   http:
     - http://localhost:8081/message/
     #- http://127.0.0.1/go-wechat/
   https:
     -url:https://ssldomain1.com/message
      key_store_path:<path to keystore>
      key_store_pass:<key_store_pass>
      key_pass:<key_pass>
     -url:https://ssldomain2.com/message
      key_store_path:<path to keystore>
      key_store_pass:<key_store_pass>
      key_pass:<key_pass>
```

@wu-sheng above is proposal for same.

**Comment by wu-sheng** [comment]
> ```
> webhooks:
>   http:
>     - http://127.0.0.1/notify/
>     - http://127.0.0.1/go-wechat/
>   https:
>     - key_pass: testkeypass
>       key_store_pass: testpass
>       key_store_path: "test path"
>       url: "https://ssldomain1.com/message"
>     - key_pass: testkeypass
>       key_store_pass: testpass
>       key_store_path: "test path"
>       url: "https://ssldomain1.com/message"
> ```
> 
> @wu-sheng above is proposal for same.

make sense to me.

**Comment by wu-sheng** [comment]
But you should know that the alarm configuration file can't be overridden through system env, once this config in the image, it is hard to change things like this.

**Comment by iIdiomatic** [comment]
> 
> 
> But you should know that the alarm configuration file can't be overridden through system env, once this config in the image, it is hard to change things like this.

I think, that is separate problem to solve - `making this config changeable from GUI.` For now I am working on above suggested proposal to push change.

**Comment by wu-sheng** [comment]
> > But you should know that the alarm configuration file can't be overridden through system env, once this config in the image, it is hard to change things like this.
> 
> I think, that is separate problem to solve - `making this config changeable from GUI.` For now I am working on above suggested proposal to push change.

Agree.

**Comment by iIdiomatic** [comment]
Questions:
1. Do we need to add test cases for running a SSL webhook? Any suggestion on approach , if yes?
2. Any code format guideline? or some xml file I can import.?

**Comment by wu-sheng** [comment]
1. Yes, a test case is required. Setting up a mock server like WebhookCallbackTest did.
2. Code style, https://github.com/apache/skywalking/blob/master/codeStyle.xml.

**Comment by wu-sheng** [comment]
@iIdiomatic Any update?

**Comment by iIdiomatic** [comment]
@wu-sheng Thank you so much for asking, certificates are problem, code is standard have written, but haven't been to certificates before. Not able to get right ones I believe. Would you mind if send a pull request at-least you can see code, by the time I will try generating more openssl certificates. Any tutorial or certificates for same are welcome.

**Comment by iIdiomatic** [comment]
will positively try closing this week, apologies for delay.

**Comment by wu-sheng** [comment]
> @wu-sheng Thank you so much for asking, certificates are problem, code is standard have written, but haven't been to certificates before. Not able to get right ones I believe. Would you mind if send a pull request at-least you can see code, by the time I will try generating more openssl certificates. Any tutorial or certificates for same are welcome.

I am not sure about your question. We are using Apache HTTP component as the client lib, which has already included the SSL/HTTPS logic. Check their document, it should not be hard.

**Comment by iIdiomatic** [comment]
SSL Certificate generation is problem , I don't think am generating correct. 

Yes code is pretty straight forward.

**Comment by wu-sheng** [comment]
I have this, https://github.com/apache/skywalking/blob/master/tools/TLS/tls_key_generate.sh. But it was 3 years ago.
This thing should be very common and widely documented.

**Comment by iIdiomatic** [comment]
Thanks a lot, will recheck.

**Comment by wu-sheng** [comment]
No update for months.
