### ISSUE TITLE
[NIGNX-LUA] About SkyWalking Nginx Agent of runtime environment

### ISSUE THREAD

**Issue by zxz9325** [apache/skywalking#6354]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Bug
- Which version of SkyWalking, OS, and JRE?
- SkyWalking 8.4、Linux、nginx1.18.0、LUA5.1、skywalking-nginx-lua0.3.0

- What happened?
  myConfig:
 ` lua_shared_dict tracing_buffer 100m;`
    `init_worker_by_lua_block {`
       `local metadata_buffer = ngx.shared.tracing_buffer`
        `metadata_buffer:set('serviceName', 'nginx::loadbalancer')`
        `metadata_buffer:set('serviceInstanceName', 'loadbalancer@76')`
        `require("skywalking.client"):startBackendTimer("http://127.0.0.1:8080")`
    `}`

When I add the above configuration, the nginx error.log keeps showing the error log, error info is `worker process 969965 exited on signal 11 (core dumped)`..

But My other running environment Only nginx version (1.10.0) is different, no such problems after integration...
Is the above error message a problem with my environment or my configuration? Have you come across it?

**Comment by wu-sheng** [comment]
Typically, we use OpenResty or APISIX and test. I think you are facing some incompatible issues at Nginx and/or LUA sides.
