### ISSUE TITLE
Skywalking agent installation for IHS servers

### ISSUE THREAD

**Issue by mdnowshath** [apache/skywalking#6355]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

- [x] Requirement

___
### Question
- What do you want to know?

_Kindly provide skywalking agent for IHS servers and installation steps.  we are getting below error while installing the agent.

httpd: Syntax error on line 1893 of /app/IBM/IHS/conf/httpd.conf: Cannot load /app/apache-skywalking-apm-bin/agent/skywalking-agent.jar into server: /app/apache-skywalking-apm-bin/agent/skywalking-agent.jar: invalid ELF header

Regards
Nowshath

**Comment by wu-sheng** [comment]
I think you have some misunderstanding. AFAIK, httpd is not a Java application.

**Comment by mdnowshath** [comment]
we want to monitor httpd. is it possible to monitor from skywalking ?

**Comment by mdnowshath** [comment]
can you provide the skywalking agent for IHS

**Comment by wu-sheng** [comment]
We don't have that. SkyWalking open the protocol suitable for all language servers, but who will implement the agents, this depends on the community, you or anyone else.

**Comment by mdnowshath** [comment]
Thanks !!
