### ISSUE TITLE
The segment index's alias can't create automatically

### ISSUE THREAD

**Issue by splf32** [apache/skywalking#6357]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When I use SkyWalking 8.4.0 and ES 6.8.0, the segment index create by date such as ‘segment-20210209’ just can not add alias automatically. This makes SkyWalking Web 'trace root' always failed.

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking: 8.4.0
OS: centos 6.8
JRE: 1.8.0_152

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
I can add alias use such as :
PUT %3Csegment-%7Bnow%2Fd%7BYYYYMMdd%7D%7D%3E
{
  "aliases": {
      "logstash": { 
      "is_write_index":true
    }
  }
}
However,this will affect segment index created by SkyWalking. Do I lost some config or other matters need attention, please tell me. Thx

**Comment by wu-sheng** [comment]
I think this is not the project issue. We are using index auto creation by alias, rather than the way you did.
