### ISSUE TITLE
Log date-time format

### ISSUE THREAD

**Issue by margauxcabrera** [apache/skywalking#6379]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.4, macOSBigSur, JRE 8
- Which company or project?
Skuvantage
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
when I debug the transform method, I still have the correct date:
timestamp: 1613453027245
service: "local"
serviceInstance: "9a7c900b03764cc28099f6be3015d784@10.8.0.14"
body {
  type: "TEXT"
  text {
    text: "CPU UTILIZATION : CPU states: 3.7% user, 3.8% system, 0.0% nice, 0.0% wait, 92.3% idle % \n"
  }
}
traceContext {
  traceId: "4b3a6e6dcea642dabcf4f51d624d8f48.151.16134530272370001"
  traceSegmentId: "4b3a6e6dcea642dabcf4f51d624d8f48.151.16134530272370000"
}
tags {
  data {
    key: "level"
    value: "INFO"
  }
  data {
    key: "logger"
    value: "au.com.skuvantage.storefront.controllers.pages.DashboardPageController"
  }
  data {
    key: "thread"
    value: "hybrisHTTP38"
  }
![image](https://user-images.githubusercontent.com/41929409/108023287-52a61500-7076-11eb-868a-5f54a5cb1735.png)

Timestamp is incorrect in UI though:
![image](https://user-images.githubusercontent.com/41929409/108023322-6487b800-7076-11eb-8489-1efd5ef67048.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Duplicated #6343
