### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object

### ISSUE THREAD

**Issue by codering** [apache/skywalking#6384]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS, and JRE?
   SkyWalking: 8.3.0
   skywalking-client-js: 0.3.0

- What happened?
When installed skywalking-client-js by npm in my project, the collector run failed. I meet this error :
![image](https://user-images.githubusercontent.com/2271825/108149557-17efbb80-710e-11eb-976a-a9578cba4c0c.png)
  and my config 
  ![image](https://user-images.githubusercontent.com/2271825/108149846-95b3c700-710e-11eb-9fe4-171e417530c9.png)

___
### Requirement or improvement
I think this is a big problem, and you have already fixed with https://github.com/apache/skywalking-client-js/pull/41. Why not release a new version？

**Comment by wu-sheng** [comment]
Release is determined by the project lead. And they are ob vacation.

**Comment by Huang8013** [comment]
How to solve it. I meet the same problem.
