### ISSUE TITLE
Alarm composite rule not working

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6390]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Sorry for repeated question , was trying so many combinations to get it working. But there is some problem and not getting the composite alarms. ( Tried with only-as-condition: true)

Configuration File skywalking 8.3

rules:
  # Rule unique name, must be ended with `_rule`.
  service_instance_resp_time_rule:
    metrics-name: service_instance_resp_time
    op: ">"
    threshold: 10
    period: 3
    count: 1
    only-as-condition: false
    message: service_instance_resp_time time is more than 10ms in 1  minutes of last   3 minutes Message1
  service_instance_jvm_cpu_alert_rule:
    metrics-name: instance_jvm_cpu
    op: ">"
    threshold: 10
    period: 3
    count: 1
    only-as-condition: false
    message: service_instance_jvm_cpu is more than 20% in 1 time  in last 3  minutes Message2
composite-rules:
  comp_rule:
    expression: service_instance_resp_time && service_instance_jvm_cpu_alert_rule
    message: Both Service Response and Cpu are high Message4

Individual Alert - 
 
On service_instance_resp_time  for Period: 3 count: 1

| name                                | start_time    | alarm_message                                                                                | time_bucket    |
+-------------------------------------+---------------+----------------------------------------------------------------------------------------------+----------------+
| "CORE SERVICE" of core_perf.service | 1613565757431 | service_instance_resp_time time is more than 10ms in 1  minutes of last   3 minutes Message1 | 20210217181237 |
| "CORE SERVICE" of core_perf.service | 1613565977428 | service_instance_resp_time time is more than 10ms in 1  minutes of last   3 minutes Message1 | 20210217181617 |
| "CORE SERVICE" of core_perf.service | 1613566217428 | service_instance_resp_time time is more than 10ms in 1  minutes of last   3 minutes Message1 | 20210217182017 |
| "CORE SERVICE" of core_perf.service | 1613566457428 | service_instance_resp_time time is more than 10ms in 1  minutes of last   3 minutes Message1 | 20210217182417 |
| "CORE SERVICE" of core_perf.service | 1613566697428 | service_instance_resp_time time is more than 10ms in 1  minutes of last   3 minutes Message1 | 20210217182817 |
 

On JVM CPU 

mysql> select name , start_time , alarm_message , time_bucket from alarm_record where name like '%core_perf.service%' and alarm_message like '%Message2%';
+-------------------------------------+---------------+----------------------------------------------------------------------------------+----------------+
| name                                | start_time    | alarm_message                                                                    | time_bucket    |
+-------------------------------------+---------------+----------------------------------------------------------------------------------+----------------+
| "CORE SERVICE" of core_perf.service | 1613565857428 | service_instance_jvm_cpu is more than 20% in 1 time  in last 3  minutes Message2 | 20210217181417 |
| "CORE SERVICE" of core_perf.service | 1613566097428 | service_instance_jvm_cpu is more than 20% in 1 time  in last 3  minutes Message2 | 20210217181817 |
| "CORE SERVICE" of core_perf.service | 1613566337428 | service_instance_jvm_cpu is more than 20% in 1 time  in last 3  minutes Message2 | 20210217182217 |
| "CORE SERVICE" of core_perf.service | 1613566577428 | service_instance_jvm_cpu is more than 20% in 1 time  in last 3  minutes Message2 | 20210217182617 |
+-------------------------------------+---------------+----------------------------------------------------------------------------------+----------------+

But I am not getting the composite alarm 
Both Service Response and CPU are high Message4.  if you need more information I will provide other combinations also.

Kindly help. 

Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
Please don't report the duplicated issue,  you could continue your question on https://github.com/apache/skywalking/issues/6370
