### ISSUE TITLE
"topology map" module can not show the third-party API components

### ISSUE THREAD

**Issue by gaoweijie** [apache/skywalking#6393]
- Why do you submit this issue?
- [x] Question or discussion
___
### Question
The "topology map" module in the ui page , Skywalking can show amost all kinds of mainstream middleware called by the application, but it can't show the third-party API components called. Is there any plugin support to show the third-party API components in the "topology map" module?

**Comment by wu-sheng** [comment]
What do you mean third-party API components called?
Is that a service or endpoint? Please use SkyWalking term rather than your private thing.

**Comment by gaoweijie** [comment]
The third-party API components means endpoint.
For example: 
    ProjectA calls the api interface (endpoint) of another projectB. The calling relationship can not be displayed on the "topology" page. 
Is there any way to resolve this question?

**Comment by wu-sheng** [comment]
> The third-party API components means endpoint.
> For example:
> ProjectA calls the api interface (endpoint) of another projectB. The calling relationship can not be displayed on the "topology" page. This rpc calling is based on the api method of sdk encapsulated by httpclient. So skywalking can not identify it.

We have plugins for that, and we supported this case for several years. You even could see https://skywalking.apache.org#demo, we have `baidu.com` on the topology.
