### ISSUE TITLE
SW_SERVICE_NAME_MAX_LENGTH 

### ISSUE THREAD

**Issue by wlyu** [apache/skywalking#6399]
/skywalking # env|grep 100
SW_SERVICE_NAME_MAX_LENGTH=100
/skywalking # 
version=8.3.0
set  serviceName lenth is 60,but store  just 50 char in elasticsearch .

**Comment by wu-sheng** [comment]
We measurelength by using Java string, not database.

**Comment by wlyu** [comment]
@wu-sheng thanks,
but the real reason is agent limit.
  /**
         * Service name is showed in skywalking-ui. Suggestion: set a unique name for each service, service instance
         * nodes share the same code
         */
        @Length(50)
        public static String SERVICE_NAME = "";
