### ISSUE TITLE
how to ues the log

### ISSUE THREAD

**Issue by ktoking** [apache/skywalking#6401]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [v ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
how to use the log ,i use mysql storage but UI service has none log info ,i cant see any info about use log
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
> i cant see any info about use log

Please read trough the docs first, docs are definitely there for open source projects

https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-log4j-1.x.md#grpc-reporter
https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-log4j-2.x.md
https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-logback-1.x.md
