### ISSUE TITLE
How deploy skywalking service based on the Elasticsearch7.X and jdk6

### ISSUE THREAD

**Issue by coverYouth** [apache/skywalking#6402]
___
### Question
- What do you want to know?
I want to use skywakling stored in Elasticsearch7.X, so launch skywaking-collector8.2 service based on jdk8 alone. But current online program use jdk6(cannot update to jdk8), the agent8.2 cannot compatible(skywalking7.0 only consider jdk8). How deploy skywalking service based on the Elasticsearch7.X and jdk6?

**Comment by wu-sheng** [comment]
ElasticSearch 7 is supported, but JDK 6 is not. We are clear in the document.
