### ISSUE TITLE
log have no data ,how to config the log collect server

### ISSUE THREAD

**Issue by wangruice** [apache/skywalking#6405]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
logback_spring.xml 
`<conversionRule conversionWord="tid" converterClass="org.apache.skywalking.apm.toolkit.log.logback.v1.x.LogbackPatternConverter"/>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">

        <encoder charset="UTF-8" class="net.logstash.logback.encoder.LogstashEncoder">
            <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider">
            </provider>
        </encoder>
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <pattern>
                    <pattern>
                        {
                        "timestamp":"%d{yyyy-MM-dd HH:mm:ss}",
                        "level": "%level",
                        "tid": "%tid",
                        "thread": "%thread",
                        "class": "%logger{1.}:%L",
                        "message": "%message",
                        "stackTrace": "%exception{10}"
                        }
                    </pattern>
                </pattern>
            </providers>
        </encoder>
    </appender>
    <appender name="grpc-log" class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender"/>
    <root level="INFO">
        <appender-ref ref="STDOUT"/>
    </root>`

print log

`{"timestamp":"2021-02-20 14:10:09","level":"INFO","tid":"TID:Ignored_Trace","thread":"qtp658673405-54","class":"com.test.common.logging.LogFilter:100","message":"Request uri:/favicon.ico, params: ","stackTrace":""}
{"timestamp":"2021-02-20 14:10:09","level":"INFO","tid":"TID:Ignored_Trace","thread":"qtp658673405-54","class":"com.test.common.logging.LogFilter:72","message":"Request uri:/favicon.ico, cost:6ms","stackTrace":""}`

why skyworking ui  log module show  no data? 
trace is working

**Comment by kezhenxu94** [comment]
> ```xml
> <root level="INFO">
>    <appender-ref ref="STDOUT"/>
> </root>
> ```

This is a simple cause, you configure an appender but didn't use it, try 

```xml
<root level="INFO">
    <appender-ref ref="STDOUT"/>
    <appender-ref ref="grpc-log"/>
</root>
```
