### ISSUE TITLE
enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.

### ISSUE THREAD

**Issue by rola0411** [apache/skywalking#6407]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
what is it！how to fixed
___
### Bug
- Which version of SkyWalking, OS, and JRE?
agent 8.4 ， centos7，openjdk8
- What happened?
WARN 2021-02-20 15:27:04:379 main AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.

**Comment by kezhenxu94** [comment]
It's just a warning log saying that some plugin instrumentations not work because of version mismatch, it's not a problem
