### ISSUE TITLE
kubernetes.client.opeanapi.ApiException

### ISSUE THREAD

**Issue by buzuotaxuan** [apache/skywalking#6408]
When i use kubernetes as SW_CLUSTER value , i catch this exception  

![image](https://user-images.githubusercontent.com/11420694/108590622-7a131f80-739f-11eb-974a-70679075e93e.png)

following the exception ,  i found the issues.

In class NamespacedPodListInformer,add the code   
![image](https://user-images.githubusercontent.com/11420694/108590907-ecd0ca80-73a0-11eb-982b-de722f496100.png)

In class ConfigurationConfigmapInformer, add the code 
![image](https://user-images.githubusercontent.com/11420694/108590938-125dd400-73a1-11eb-844a-979e5204a555.png)

So i fix the exception

**Comment by kezhenxu94** [comment]
Can you please send a PR?

**Comment by buzuotaxuan** [comment]
ok
