### ISSUE TITLE
demo env not support query trace by tags?

### ISSUE THREAD

**Issue by daiqianshi** [apache/skywalking#6414]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Queried by the tag doesn't seem to work when I use demo env UI. No tag information was entered in the request. The same is true for our own projects. Now the trace query does not support tag?
![Snipaste_2021-02-21_09-57-54](https://user-images.githubusercontent.com/20640926/108613282-572e4d00-742b-11eb-81ac-f5f435a35ed6.png)

**Comment by wu-sheng** [comment]
You need `enter` to confirm the query condition. This has no difference with your local deployment. I am confused why are you saying demo doesn't support. Whenever we do support like you did?
