### ISSUE TITLE
Can apollo's configuration center use the server push method instead of the thread pool pull method?

### ISSUE THREAD

**Issue by LiWenGu** [apache/skywalking#6419]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?

Skywakling's configuration center module uniformly uses timed tasks to obtain remote configuration, but many configuration centers (ps:apollo) can use the server to notify the client to make configuration updates more efficient.

https://github.com/apache/skywalking/blob/85fc4f827c7b8ef32f17aefbecd202c01d9048e1/oap-server/server-configuration/configuration-api/src/main/java/org/apache/skywalking/oap/server/configuration/api/ConfigWatcherRegister.java#L70-L75

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

Can we try to use server notify (if supported by the configuration center) to dynamically update the configuration?

**Comment by kezhenxu94** [comment]
> Can we try to use server notify (if supported by the configuration center) to dynamically update the configuration?

Yes, we use this method in other config centers implementations such as etcd, nacos, but it still needs schedule task in API level, if you want to remove the scheduled task in API level,


https://github.com/apache/skywalking/blob/85fc4f827c7b8ef32f17aefbecd202c01d9048e1/oap-server/server-configuration/configuration-api/src/main/java/org/apache/skywalking/oap/server/configuration/api/ConfigWatcherRegister.java#L70-L75

that may need more evaluation from the PMC

**Comment by kezhenxu94** [comment]
If you take reference from etcd, nacos implementation and want to do the similar enhancement, welcome

**Comment by wu-sheng** [comment]
> Can we try to use server notify (if supported by the configuration center) to dynamically update the configuration?

My question would be, how do those client libs make push mode? In many known implementation, they are still using an internal ping to fake the push.
Could you share with us, why do you need this? @LiWenGu Why do you think this is important?

**Comment by kezhenxu94** [comment]
> > Can we try to use server notify (if supported by the configuration center) to dynamically update the configuration?
> 
> 
> 
> My question would be, how do those client libs make push mode? In many known implementation, they are still using an internal ping to fake the push.
> 
> Could you share with us, why do you need this? @LiWenGu Why do you think this is important?

For Apollo, it's using long-polling mechanism.

**Comment by LiWenGu** [comment]
> > > Can we try to use server notify (if supported by the configuration center) to dynamically update the configuration?
> > 
> > 
> > My question would be, how do those client libs make push mode? In many known implementation, they are still using an internal ping to fake the push.
> > Could you share with us, why do you need this? @LiWenGu Why do you think this is important?
> 
> For Apollo, it's using long-polling mechanism.


If the configuration center naturally supports long connections, we can use this feature directly, the code will be simple. In addition, take apollo as an example. Its long polling is not an ordinary long polling, but a long connection. The client will be hanged after requesting the server. It can perform real-time synchronization configuration within a certain period of time, which is more efficient than timing tasks, and real-time synchronization configuration is also faster.

**Comment by wu-sheng** [comment]
It has a chance to sync the data quicker, then read in a loop. Yes. 
But from the connection perspective, today's implementation also doesn't re-create connection every time.

Back to your question, if you want, this is possible. You could override `ConfigWatcherRegister#start` to make the timer disable easily. If you want to do this in Apollo, I would like to recommend you supporting both way(current and your proposal), because users are mostly using this way, and no one was asking for this.

**Comment by LiWenGu** [comment]
No one else has asked about this, indicating that the current code is sufficient for the community. I try to be compatible in two ways, the code implementation is more complicated. My proposal may require more consideration

**Comment by wu-sheng** [comment]
Personally, once your codes are compatible with the current implementation, I will not block it. 
All my comments are for you to consider whether we need this in the real world.
