### ISSUE TITLE
Web UI service search failed

### ISSUE THREAD

**Issue by JHub-Wei** [apache/skywalking#6420]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is the search suspension bug caused by duplicate service names found on the UI fixed in 8.4.0?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Duplicated, we explained several. Search first please.

**Comment by JHub-Wei** [comment]
I searched.I want to know whether some protection measures can be taken on the frontend so that duplicate service names will not be displayed and the search will not be suspended.

**Comment by wu-sheng** [comment]
No, you need to fix your storage, rather than frontend.
