### ISSUE TITLE
plugin.toolkit.log.grpc.reporter.server_host=${SW_GRPC_LOG_SERVER_HOST:127.0.0.1} doesnot effect

### ISSUE THREAD

**Issue by whaon** [apache/skywalking#6422]
refrence this page:  [https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-log4j-2.x.md](https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-log4j-2.x.md)
I place the follow in agent.conf
`plugin.toolkit.log.grpc.reporter.server_host=${SW_GRPC_LOG_SERVER_HOST:192.168.1.84}`

but it does not effect
I debug it and seee the pic below
![image](https://user-images.githubusercontent.com/2542483/108798883-d194d380-75c9-11eb-85f8-d92276e9c6b3.png)

@augustowebd @adriancole @dio @Videl @TomMD

**Comment by wu-sheng** [comment]
Do you know the people you mentioned above?

**Comment by EvanLjp** [comment]
![image](https://user-images.githubusercontent.com/31562192/108801196-07d55180-75d0-11eb-98f8-af1cba123a8f.png)
Let me make sure again

**Comment by EvanLjp** [comment]
![image](https://user-images.githubusercontent.com/31562192/108804118-5e925980-75d7-11eb-90f6-98e20d304f0e.png)
@whaon could u check again?

**Comment by whaon** [comment]
I checked but it failed again
but the other variable is ok,such as **agent.service_name**
![image](https://user-images.githubusercontent.com/2542483/108806496-cac38c00-75dc-11eb-8df6-ba6f9118271b.png)

the version is **v8.4.0 for H2/MySQL/TiDB/InfluxDB/ElasticSearch 7** and I download it from http://skywalking.apache.org/downloads/
![image](https://user-images.githubusercontent.com/2542483/108806369-78826b00-75dc-11eb-8d9e-cb48f527f712.png)

can you tell me where the place is solving the parameter **plugin.toolkit.log.grpc.reporter.server_host**

**Comment by whaon** [comment]
> Do you know the people you mentioned above?

idk,just use the tips where i type @,  :)

**Comment by whaon** [comment]
I get the reason @EvanLjp @wu-sheng 
because I placed the below in the pom
`        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-log4j-2.x-activation</artifactId>
            <version>8.4.0</version>
            <scope>provided</scope>
        </dependency>`

when i remove it and  it's ok now

but another issue is the time is wrong ,see the pic :
![image](https://user-images.githubusercontent.com/2542483/108809592-2a716580-75e4-11eb-8016-76e2f252eff6.png)

**Comment by whaon** [comment]
> I get the reason @EvanLjp @wu-sheng
> because I placed the below in the pom
> 
> ```
> <dependency>
>             <groupId>org.apache.skywalking</groupId>
>             <artifactId>apm-toolkit-log4j-2.x-activation</artifactId>
>             <version>8.4.0</version>
>             <scope>provided</scope>
> </dependency>
> ```
> 
> when i remove it and it's ok now
> 
> but another issue is the time is wrong ,see the pic :
> ![image](https://user-images.githubusercontent.com/2542483/108809592-2a716580-75e4-11eb-8016-76e2f252eff6.png)

see #6343
