### ISSUE TITLE
alarm  dynamic configuration with apollo dose not work

### ISSUE THREAD

**Issue by jianghebo** [apache/skywalking#6423]
I changed it application.yml Then Apollo was configured, but it didn't work, as shown in my 

![1](https://user-images.githubusercontent.com/17865919/108806816-b92eb400-75dd-11eb-89f8-8af864f2d531.png)
![2](https://user-images.githubusercontent.com/17865919/108806822-bdf36800-75dd-11eb-86e4-9f53a7be1e35.png)

**Comment by wu-sheng** [comment]
How do you know it is not working? I can't see any debug information.

**Comment by kezhenxu94** [comment]
![image](https://user-images.githubusercontent.com/15965696/108807161-9fda3780-75de-11eb-9841-b72d12929e36.png)

If your SkyWalking failed to start, check your screenshot, there is obvious mistake

```diff
- ${SW_CONFIGURATION:apollo:}
+ ${SW_CONFIGURATION:apollo}
```

P.S. Learn how to ask question, don't just paste screenshots without any further context

**Comment by jianghebo** [comment]
> ![image](https://user-images.githubusercontent.com/15965696/108807161-9fda3780-75de-11eb-9841-b72d12929e36.png)
> 
> If your SkyWalking failed to start, check your screenshot, there is obvious mistake
> 
> ```diff
> - ${SW_CONFIGURATION:apollo:}
> + ${SW_CONFIGURATION:apollo}
> ```
> 
> P.S. Learn how to ask question, don't just paste screenshots without any further context
Sorry, it's my screenshot error. There's no problem to enable Apollo in this line, as you wrote. But I found that the Apollo I configured didn't trigger, and I still used the alarm configuration rules to alarm

**Comment by kezhenxu94** [comment]
> But I found that the Apollo I configured didn't trigger, and I still used the alarm configuration rules to alarm

You need to check whether or not you configure the right url for `apolloMeta`, be careful there are several services in Apollo (config service, meta service, admin service and portal), and then check the OAP logs. We can't (and won't) help without any useful information because we have tests there to verify it works.

**Comment by jianghebo** [comment]
> > But I found that the Apollo I configured didn't trigger, and I still used the alarm configuration rules to alarm
> 
> You need to check whether or not you configure the right url for `apolloMeta`, be careful there are several services in Apollo (config service, meta service, admin service and portal), and then check the OAP logs. We can't (and won't) help without any useful information because we have tests there to verify it works.

Thank you very much. I found the problem in the log
