### ISSUE TITLE
the webhook has error:Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by whaon** [apache/skywalking#6424]
see pic:
![image](https://user-images.githubusercontent.com/2542483/108810330-e0897f00-75e5-11eb-8fb1-b703903e9e98.png)

@EvanLjp

**Comment by wu-sheng** [comment]
Why are you keeping pinging the member of the project? I have asked about that. This is not polite unless you have off-list discussion.

**Comment by EvanLjp** [comment]
Related functions are contributed by different members. Sorry, I am not familiar with this problem.

**Comment by wu-sheng** [comment]
This error seems some kinds of connection link? I never used this part too. Recommend to read and debug `DingtalkHookCallback`.

**Comment by whaon** [comment]
> Why are you keeping pinging the member of the project? I have asked about that. This is not polite unless you have off-list discussion.

sorry about that, i I don't mean to
i use 8.2.0 before,but i found 8.4.0 these days and it's really good, so i just want to use it as soon as possible,but found some issues now and want to solve it
thanks for your job and replay.
i will pay more attention to my words and behaviours

**Comment by whaon** [comment]
the reason may be high concurrence
guess there are some issues in httpclient config

**Comment by wu-sheng** [comment]
> the reason may be high concurrence
> guess there are some issues in httpclient config

There is no concurrency in the design level of alarm core. That is why I feel there is connection leak somehow.

**Comment by haoyann** [comment]
`httpResponse` should be closed.
```
    private void sendAlarmMessage(CloseableHttpClient httpClient, String url, String requestBody) {
        try {
            HttpPost post = new HttpPost(url);
            post.setConfig(requestConfig);
            post.setHeader(HttpHeaders.ACCEPT, HttpHeaderValues.APPLICATION_JSON.toString());
            post.setHeader(HttpHeaders.CONTENT_TYPE, HttpHeaderValues.APPLICATION_JSON.toString());
            StringEntity entity = new StringEntity(requestBody, ContentType.APPLICATION_JSON);
            post.setEntity(entity);
            CloseableHttpResponse httpResponse = httpClient.execute(post);
            StatusLine statusLine = httpResponse.getStatusLine();
            if (statusLine != null && statusLine.getStatusCode() != HttpStatus.SC_OK) {
                log.error("send dingtalk alarm to {} failure. Response code: {}, Response content: {}", url, statusLine.getStatusCode(),
                        EntityUtils.toString(httpResponse.getEntity()));
            }
        } catch (Throwable e) {
            log.error("send dingtalk alarm to {} failure.", url, e);
        }
    }
```
https://hc.apache.org/httpcomponents-client-4.5.x/quickstart.html

**Comment by wu-sheng** [comment]
Any of you are willing to send a pull request?

**Comment by haoyann** [comment]
I would like to contribute to this issue.

**Comment by whaon** [comment]
I checked the hooks and find all web hooks have the same problem
such as: feishu, slack, wechat, dingtalk

**Comment by wu-sheng** [comment]
Yes, they seem so.
