### ISSUE TITLE
the log ui has some problems

### ISSUE THREAD

**Issue by whaon** [apache/skywalking#6429]
skywalking version is **v8.4.0 for H2/MySQL/TiDB/InfluxDB/ElasticSearch 7**

1. search probplem
first i put some traceid in the form and then press seach, it's ok
then i press reset button ,the data is reresh, but the traceid input does not clear,and i press search again ,the trace id input does not efffect
then i put some word in the other input,such "as content keyword",press search button,it does not effect
then i try to reset but nothing appear

2. combo box problem
when i type some words in the service combo box and want to search some service
but it does not effect and i can't choose one item,and the select box does not disappear unless i refresh the page
![image](https://user-images.githubusercontent.com/2542483/108938403-fc932c00-768a-11eb-8c94-fb6024325704.png)

3. log time is error
![image](https://user-images.githubusercontent.com/2542483/108938441-087eee00-768b-11eb-8d68-124a5e916f5f.png)

thanks

**Comment by wu-sheng** [comment]
3 fixed for a long time.
@Fine0830 Could you recheck 1 and 2? I am not sure.

**Comment by whaon** [comment]
3 see #6343

**Comment by wu-sheng** [comment]
(1), query is working, and `More Conditions` are not, I think it is a `clear` button related bug.
(2), I can't reproduce it, the search works in my browser.

**Comment by Fine0830** [comment]
Apologies for the delay in replying. I checked and the result is same to @wu-sheng result. Please feel free to ping me if you still have any question.

**Comment by whaon** [comment]
i test it in my local pc and it's ok
but in other machine it is not
and not only in /log page , the /trace page still has the same problem beause the comobox use the same component
when i type numbers it's ok ,but letters not
the erros in the browser is:
![image](https://user-images.githubusercontent.com/2542483/109116437-7dc9ec00-777b-11eb-8c25-41f895217a00.png)

the other point maybe import is 
the queryServices api in my environment returns 62 because we have many projects
the json return is below(the lable is desensitized):
·
{
	"data": {
		"services": [{
			"key": "bGVlbGVuLWNybS1jdXN0b21lcnNlcnZpY2Utc2VydmVy.1",
			"label": "server",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1jdXN0b20tc2VydmVy.1",
			"label": "server",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1nYXRld2F5.1",
			"label": "gateway",
			"group": ""
		}, {
			"key": "c21z.1",
			"label": "a",
			"group": ""
		}, {
			"key": "Y2FwaQ==.1",
			"label": "a",
			"group": ""
		}, {
			"key": "bWdhdGV3YXk=.1",
			"label": "a",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1zeXN0ZW0tc2VydmVy.1",
			"label": "b",
			"group": ""
		}, {
			"key": "b3JkZXI=.1",
			"label": "c",
			"group": ""
		}, {
			"key": "aW52ZW50b3J5.1",
			"label": "c",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1zeXN0ZW0tc2VydmVy.1",
			"label": "d",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1nYXRld2F5.1",
			"label": "e",
			"group": ""
		}, {
			"key": "c21z.1",
			"label": "f",
			"group": ""
		}, {
			"key": "bWVtYmVy.1",
			"label": "g",
			"group": ""
		}, {
			"key": "b3JkZXI=.1",
			"label": "h",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1jdXN0b21lcnNlcnZpY2Utc2VydmVy.1",
			"label": "a",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS13b3Jrb3JkZXItc2VydmVy.1",
			"label": "b",
			"group": ""
		}, {
			"key": "YmFwaQ==.1",
			"label": "c",
			"group": ""
		}, {
			"key": "bWdhdGV3YXk=.1",
			"label": "d",
			"group": ""
		}, {
			"key": "b3JkZXI=.1",
			"label": "e",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1jdXN0b21lcnNlcnZpY2Utc2VydmVy.1",
			"label": "f",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1zeXN0ZW0tc2VydmVy.1",
			"label": "g",
			"group": ""
		}, {
			"key": "aW52ZW50b3J5.1",
			"label": "a",
			"group": ""
		}, {
			"key": "bWdhdGV3YXk=.1",
			"label": "b",
			"group": ""
		}, {
			"key": "YmFwaQ==.1",
			"label": "c",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS13b3Jrb3JkZXItc2VydmVy.1",
			"label": "d",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1vcmRlcg==.1",
			"label": "e",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1jdXN0b21lcnNlcnZpY2Utc2VydmVy.1",
			"label": "f",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1jdXN0b20tc2VydmVy.1",
			"label": "g",
			"group": ""
		}, {
			"key": "aW52ZW50b3J5.1",
			"label": "h",
			"group": ""
		}, {
			"key": "bWdhdGV3YXk=.1",
			"label": "a",
			"group": ""
		}, {
			"key": "b3JkZXI=.1",
			"label": "b",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS13b3Jrb3JkZXItc2VydmVy.1",
			"label": "c",
			"group": ""
		}, {
			"key": "bG9naXN0aWNz.1",
			"label": "d",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1zeXN0ZW0tc2VydmVy.1",
			"label": "e",
			"group": ""
		}, {
			"key": "YmFwaQ==.1",
			"label": "f",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1jdXN0b20tc2VydmVy.1",
			"label": "a",
			"group": ""
		}, {
			"key": "YmFwaQ==.1",
			"label": "b",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1vcmRlcg==.1",
			"label": "l",
			"group": ""
		}, {
			"key": "dGg=.1",
			"label": "th",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1jdXN0b21lcnNlcnZpY2Utc2VydmVy.1",
			"label": "server",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS13b3Jrb3JkZXItc2VydmVy.1",
			"label": "server",
			"group": ""
		}, {
			"key": "aW52ZW50b3J5.1",
			"label": "i",
			"group": ""
		}, {
			"key": "MTkyLjE2OC4xLjg0.1",
			"label": "192.168.1.84",
			"group": ""
		}, {
			"key": "WW91cl9BcHBsaWNhdGlvbk5hbWU=.1",
			"label": "Your_ApplicationName",
			"group": ""
		}, {
			"key": "bG9naXN0aWNz.1",
			"label": "a",
			"group": ""
		}, {
			"key": "bWdhdGV3YXk=.1",
			"label": "b",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1zZWN1cml0eQ==.1",
			"label": "a",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1zZWN1cml0eQ==.1",
			"label": "b",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1vcmRlcg==.1",
			"label": "a",
			"group": ""
		}, {
			"key": "bWdhdGV3YXk=.1",
			"label": "c",
			"group": ""
		}, {
			"key": "dGg=.1",
			"label": "th",
			"group": ""
		}, {
			"key": "bG9naXN0aWNz.1",
			"label": "a",
			"group": ""
		}, {
			"key": "YWZ0ZXJzYWxlcw==.1",
			"label": "b",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1vcGVyYXRpb24tc2VydmVy.1",
			"label": "a",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS13b3Jrb3JkZXItc2VydmVy.1",
			"label": "b",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1zZWN1cml0eQ==.1",
			"label": "a",
			"group": ""
		}, {
			"key": "YWZ0ZXJzYWxlcw==.1",
			"label": "c",
			"group": ""
		}, {
			"key": "YmFwaQ==.1",
			"label": "d",
			"group": ""
		}, {
			"key": "bWVtYmVy.1",
			"label": "b",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1vcmRlcg==.1",
			"label": "a",
			"group": ""
		}, {
			"key": "bGVlbGVuLWNybS1vcGVyYXRpb24tc2VydmVy.1",
			"label": "a",
			"group": ""
		}, {
			"key": "bG9naXN0aWNz.1",
			"label": "b",
			"group": ""
		}]
	}
}
·

**Comment by wu-sheng** [comment]
62 services is not an issue, we have 200+ services case in many companies.  But I can see duplicate service names, so your storage may not work as expected. As make sure your browser cache has been cleared.

**Comment by whaon** [comment]
chrome browser cache is cleared
and edge has the same problem
and my workmate has the same problem
the lables is duplicated indeed maybe that's the point

**Comment by wu-sheng** [comment]
You need to resolve your storage issue first.
