### ISSUE TITLE
The UI dashboard only displays microservices in the same cluster.

### ISSUE THREAD

**Issue by JHub-Wei** [apache/skywalking#6430]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ * ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to distinguish and display microservices of different clusters on the UI dashboard instead of all microservices integrated with the agent? Many cloud services are connected to the same Skywalking backend. On the UI dashboard, you can view the comparison data of microservices of different cloud services. However, it is preferable to check which microservice has high load and slow response within a cloud service.
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We recommend to use group concept since 8.4.0

**Comment by JHub-Wei** [comment]
group concept was proposed in 8.3.0.I used group in version 8.3.0,but it still displayed all microservices on the global panel of the dashboard.

**Comment by wu-sheng** [comment]
We could you the dashboard locking to your service group, you could custom by yourself.

**Comment by JHub-Wei** [comment]
How to let the global panel of the dashboard lock to my service group?I can not find it.

**Comment by wu-sheng** [comment]
Like we did for Istio Control Panel dashboard
![image](https://user-images.githubusercontent.com/5441976/108963048-928f7c80-76b4-11eb-95f5-9555bb1326a8.png)

**Comment by JHub-Wei** [comment]
For some reason, I can't upload pictures right now.

For example, there are two service groups ops and rtc. There are two microservices ops::test1 and rtc::test2.When I filter ops in Service Group, only ops::test1 is displayed in the drop-down list of the Current Service. However, the global panel still displays the data of the rtc::test2 service on the Service Load panel,Slow Services panel,etc. I only want to view the microservice data of the ops service group.

**Comment by wu-sheng** [comment]
Global of course, otherwise, why it is called global? Group is not tenancy.

**Comment by JHub-Wei** [comment]
So there's no way to do that, is there?

**Comment by wu-sheng** [comment]
No, this is out the project's landscape.

**Comment by JHub-Wei** [comment]
OK，thx.
