### ISSUE TITLE
apm-toolkit-opentracing support seting Component and SpanLayer.

### ISSUE THREAD

**Issue by liqiangz** [apache/skywalking#6433]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

### Requirement or improvement
- Please describe your requirements or improvement suggestions.

apm-toolkit-opentracing does not support seting Component and SpanLayer.  It will shown "Unknown" in skywalking ui.

**Comment by wu-sheng** [comment]
There is no such thing in the OpenTracing. What can we do?

**Comment by liqiangz** [comment]
@wu-sheng   When we set Tag like `Tags.COMPONENT.set(span, "jersey")`,   maybe we can get the tag value and setComponent in apm-toolkit-trace-activation?

**Comment by wu-sheng** [comment]
`COMPONENT` in SkyWalking native concept, you are being required a ID, how do that in the OpenTracing API? 
And I can't see `Layer` in the OT too.

Also, do you know, OT is being abandoned by their maintainers? Check opentracing.io for more details.

**Comment by liqiangz** [comment]
@wu-sheng apm-toolkit-trace can only create localSpan. Besides using apm-toolkit-opentracing and sdk plugins, is there any other way to create entrySpan and exitSpan?

**Comment by wu-sheng** [comment]
Yes, you can, take a look at `SkywalkingSpanBuilder`.

**Comment by liqiangz** [comment]
@wu-sheng  SkywalkingSpanBuilder can't set Component and SpanLayer.  Is it only possible to set Component and SpanLayer through the SDK plugin?

**Comment by wu-sheng** [comment]
> @wu-sheng SkywalkingSpanBuilder can't set Component and SpanLayer. Is it only possible to set Component and SpanLayer through the SDK plugin?

I think I replied. You don't explain how. Why you are asking again?

**Comment by liqiangz** [comment]
thank you for your reply

**Comment by qinshaokang** [comment]
I also don't understand how to create entrySpan if i use SkywalkingSpanBuilder，could you plese describ how again?

**Comment by qinshaokang** [comment]
I think i got it. Take a look at this method.
`public SpanBuilder withTag(String key, String value) {
        if (Tags.SPAN_KIND.getKey().equals(key)) {
            if (!"client".equals(value) && !"producer".equals(value)) {
                if (!"server".equals(value) && !"consumer".equals(value)) {
                    this.isEntry = false;
                    this.isExit = false;
                } else {
                    this.isEntry = true;
                    this.isExit = false;
                }
            } else {
                this.isEntry = false;
                this.isExit = true;
            }
        } else if (!Tags.PEER_HOST_IPV4.getKey().equals(key) && !Tags.PEER_HOST_IPV6.getKey().equals(key) && !Tags.PEER_HOSTNAME.getKey().equals(key)) {
            if (Tags.PEER_SERVICE.getKey().equals(key)) {
                this.operationName = value;
            } else {
                this.tags.add(new Tag(key, value));
            }
        } else {
            this.peer = value;
        }

        return this;
    }`
