### ISSUE TITLE
jedis not support pipeline

### ISSUE THREAD

**Issue by xuanyu66** [apache/skywalking#6434]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Feature or performance improvement

___
### Question
- What do you want to know?
I look into jedis-2.x plugin, find that enhanceClass is redis.clients.jedis.Jedis.
But pipeline will directly invoke jedis client.
Jedis --invoke---> client
pipeline ---invoke-->client

There are two solution to solve this  problem
1. just enhance client
2. enhance both Jedis and Pipeline

**Comment by wu-sheng** [comment]
I think both of them are open choice. We don't determine how the plugin do instrumentation.

**Comment by xuanyu66** [comment]
I will dig into it sooner or later
