### ISSUE TITLE
can't choose service in log page 

### ISSUE THREAD

**Issue by john1337** [apache/skywalking#6436]
Version :8.3.0
in skywalking log page,service option is disabled,only browser option can be choosen.

**Comment by wu-sheng** [comment]
Read changelog, it was not available

**Comment by john1337** [comment]
> Read changelog, it was not available

i am using 8.3.0 version,but the sample page from you can choose service option!!!

**Comment by wu-sheng** [comment]
We never said, 8.3.0 has this feature.
