### ISSUE TITLE
service option is disabled in log page

### ISSUE THREAD

**Issue by john1337** [apache/skywalking#6437]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

can't choose service option in log page,this option is disabled,i want to know how to solve this.

![3B1D9C97-6914-4e0c-B3AC-48B9C313CDD7](https://user-images.githubusercontent.com/11956341/108979223-66c8c280-76c5-11eb-992c-fc6d66e801dc.png)

**Comment by wu-sheng** [comment]
I relied, why keep asking same thing?
