### ISSUE TITLE
lettucev5 plugin bug when redis sentinel mode  can't get hosts value

### ISSUE THREAD

**Issue by DeadLion** [apache/skywalking#6443]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [√] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___

SkyWalking :8.4.0   
Centos7.0+
java version "1.8.0_191"

lettucev5 plugin bug when redis sentinel mode  can't get hosts value,so ui tolopogy will display null:0 , like below pic
![image](https://user-images.githubusercontent.com/2594907/109130182-65160200-778c-11eb-990e-480fa06882d1.png)

because sentinel mode the server nodes info will save in sentinels field, below is debug info, it's clear to understand why this bug happen.
![image](https://user-images.githubusercontent.com/2594907/109130915-3b110f80-778d-11eb-92cd-65936b8fb3ca.png)

i already fixed this , i will make a pr.

**Comment by wu-sheng** [comment]
Yes, please.
