### ISSUE TITLE
Search Endpoint  use keyword params

### ISSUE THREAD

**Issue by liqiangz** [apache/skywalking#6444]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Now the Endpoint list gets one hundred items when it is initialized. Now the search is only the hundred items.

![image](https://user-images.githubusercontent.com/16935891/109132609-fd14eb00-778e-11eb-9fe1-b0c76085ad23.png)

If the number of Endpoints exceeds one hundred, maybe we can search it use keyword params
``` json
{"query":"query queryEndpoints($serviceId: ID!, $keyword: String!) {\n    getEndpoints: searchEndpoint(serviceId: $serviceId, keyword: $keyword, limit: 1000) {\n      key: id\n      label: name\n    }\n}","variables":{"serviceId":"dGhzamotZG9ja2VyLWZ1bmRzYWxlLXdzank4NDQz.1","keyword":"trend"}}
```
![image](https://user-images.githubusercontent.com/16935891/109132968-685ebd00-778f-11eb-911c-e249889b4ed1.png)

**Comment by wu-sheng** [comment]
Why do you need such a long list?

**Comment by wu-sheng** [comment]
Do you mean this UI doesn't use search service? If so, this seems a bug. @Fine0830 Could you check this?

![image](https://user-images.githubusercontent.com/5441976/109135589-326f0800-7792-11eb-85e6-6de89e61fc38.png)
When I type things here and click `enter`, it should be `run` for this
https://github.com/apache/skywalking-query-protocol/blob/42d6783d8c1a0d0d4c2b28e58dc1f47dd554964e/metadata.graphqls#L85

**Comment by liqiangz** [comment]
@wu-sheng yes,   clicking enter  does't  search service by calling graphql request.

**Comment by wu-sheng** [comment]
> @wu-sheng yes, clicking enter does't search service by calling graphql request.

I have tagged this as a bug.

**Comment by andotorg** [comment]
export const Endpoints = {
  variable: '$serviceId: ID!, $keyword: String!',
  query: `
    getEndpoints: searchEndpoint(serviceId: $serviceId, keyword: $keyword, limit: 100) {
      key: id
      label: name
    }
`,
};

Because skywalking has access to many systems and there are many endpoints, it is obviously inappropriate to add the data of the drop-down box to the limit
