### ISSUE TITLE
Provide trace id even if we should not upload the trace info.

### ISSUE THREAD

**Issue by libinglong** [apache/skywalking#6451]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

Provide trace id even if we should not upload the trace info.

There are many case such as oap error or sampling in which we also want to get a uniqe trace id.
Generating trace id is the mechanism of agent. It should not be affect by the health of oap.
In the last few days, our oap reject all request by some unexpected reason, which causes we lost all skywalking trace info in a long time. It's important if our log has the trace id.

**Comment by wu-sheng** [comment]
We explained this in many many issues. No, we are not going to do this.
If you want to buffer traces, try Kafka reporter or new Satellite.

**Comment by sruby** [comment]
With apm-toolkit-trace, trace ids can be generated normally even without oap.
