### ISSUE TITLE
the log time is error

### ISSUE THREAD

**Issue by haoyanbing** [apache/skywalking#6452]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- The log time is error, i use the skywalking version is 8.4.0.
![image](https://user-images.githubusercontent.com/20509387/109261516-ddd39780-783a-11eb-82a4-9c8b6507aa43.png)

**Comment by kezhenxu94** [comment]
This was reported and fixed in master branch
