### ISSUE TITLE
Database Slow Statements return error:Cannot return null for non-nullable type: 'String' within parent 'SelectedRecord' (/readSampledRecords[0]/name)

### ISSUE THREAD

**Issue by daiqianshi** [apache/skywalking#6455]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___

___
### Bug
- Which version of SkyWalking, OS, and JRE?
   SkyWalking:8.3.0, OS:Centos, java:1.8.0_221
- What happened?
  The error only returned by ES database,Mysql is ok. Is there any additional configuration I need to add? 
```json
{
	"errors": [{
		"message": "Cannot return null for non-nullable type: 'String' within parent 'SelectedRecord' (/readSampledRecords[0]/name)"
	}, {
		"message": "Cannot return null for non-nullable type: 'String' within parent 'SelectedRecord' (/readSampledRecords[1]/name)"
	}]
}
```

**Comment by wu-sheng** [comment]
I think you need to open `TRACE_DSL` for your elasticsearch plugin.

**Comment by wu-sheng** [comment]
`MultiScopesAnalysisListener` should add `slowStatementBuilder#statement != null` check.

**Comment by daiqianshi** [comment]
Thank you for your answer, Where can I configure or add *slowStatementBuilder#statement != null* @wu-sheng

**Comment by wu-sheng** [comment]
This is a code change, you can't config it.

**Comment by wu-sheng** [comment]
@daiqianshi If you are willing to read codes, and submit pull request, read `MultiScopesAnalysisListener.java`

**Comment by haoyann** [comment]
https://github.com/apache/skywalking/blob/19d4a77235de37f47c3b97cff0118fddbdb565e3/oap-server/analyzer/agent-analyzer/src/main/java/org/apache/skywalking/oap/server/analyzer/provider/trace/parser/listener/MultiScopesAnalysisListener.java#L206-L210

@wu-sheng  `StringUtil.isEmpty(sqlStatement)` check  move out of the loop , can it be changed like this? 
```
            if (StringUtil.isEmpty(slowStatementBuilder.getStatement())) {
                slowStatementBuilder.setStatement("[No statement]/" + span.getOperationName());
            }
```

**Comment by wu-sheng** [comment]
Make sense, I think we should also check check operation name is null. Because I remember there is a case, people said they have `[No statement]/null` on the UI.

**Comment by haoyann** [comment]
> Make sense, I think we should also check check operation name is null. Because I remember there is a case, people said they have `[No statement]/null` on the UI.

Replace null with  "" ?

**Comment by wu-sheng** [comment]
Yes, and no /
