### ISSUE TITLE
Why are there two copies of CallbackAdapter.java?

### ISSUE THREAD

**Issue by yaojingguo** [apache/skywalking#6457]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
The following two files are exactly the same:
1. ./apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/CallbackAdapter.java
2. ./apm-sniffer/apm-sdk-plugin/kafka-commons/src/main/java/org/apache/skywalking/apm/plugin/kafka/CallbackAdapter.java

___
### Requirement or improvement
Since apm-kafka-plugin artifact depends on apm-kafka-commons artifact, I think that apm-kafka-plugin's copy shoud be removed.

**Comment by wu-sheng** [comment]
Yes, they should share common lib.

**Comment by zifeihan** [comment]
@yaojingguo @wu-sheng i notice too, and org.apache.skywalking.apm.plugin.kafka.CallbackAdapter is not used. @yaojingguo welcome to send pr for fix https://github.com/apache/skywalking/issues/6456 and this issue.
