### ISSUE TITLE
plugin.mysql.trace_sql_parameters not working in skywalking v8.4.0

### ISSUE THREAD

**Issue by wls1036** [apache/skywalking#6465]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking:v8.4.0
OS:Mac Mojave 10.14.5
JRE:jdk1.8.0_161
Mysql Version:8.0.21
Mysql JDBC Driver Version:8.0.20
Mysql JDBC Driver class: com.mysql.cj.jdbc.Driver,com.mysql.jdbc.Driver

- Which company or project?
Person

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

set agent config plugin.mysql.trace_sql_parameters=true not working in skywalking v8.4.0，but working in version 8.0.1，the same code.

sample code:

@RestController
public class JDBCController {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @GetMapping("/jdbc")
    public Map testJDBC() {
        return jdbcTemplate.queryForMap("select * from apm_project where short_code=?", "hr");
    }
}

application.properties

spring.datasource.url=jdbc:mysql://localhost:3308/apiman?useUnicode=true&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=xxxx
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please read the correct documentation. Configuration key could be changed in the new version.
`plugin.jdbc.trace_sql_parameters` ref to https://skywalking.apache.org/docs/main/v8.4.0/en/setup/service-agent/java-agent/readme/#table-of-agent-configuration-properties

**Comment by wls1036** [comment]
Thanks. new version `agent.config` is the old name configuration`plugin.mysql.trace_sql_parameters` not update.Maybe you can add a tip comment in the next version.

**Comment by wu-sheng** [comment]
Take a look at https://github.com/apache/skywalking/pull/6303.
