### ISSUE TITLE
customize property for table service_traffic

### ISSUE THREAD

**Issue by lixue123221** [apache/skywalking#6475]
we want to customize other property for table service_traffic to query service with our customize property, 

but now I don't know how to fix it

**Comment by wu-sheng** [comment]
No, there isn't query for those conditions.

**Comment by lixue123221** [comment]
for saas, we should control their query permission, they should query their own services, not other users, now how to fix it in this scenario

**Comment by wu-sheng** [comment]
Your saas, you are making money by this, this is your responsibility
