### ISSUE TITLE
端点数过多问题

### ISSUE THREAD

**Issue by huangxinjun** [apache/skywalking#6483]
hello，各位skywalking负责人，帮忙解答下以下几个问题：
1、为什么endpoint统计的数量远超接口数？
2、当前端点下拉列表展示的数量是不是做了裁剪，发现只能查询查到，但是下拉找不到？
3、skywalking是否有计划展示单个service下所有endpoint的列表数据，而不是靠人工手动一个个点去看响应时间和吞吐量

**Comment by wu-sheng** [comment]
Please use English on GitHub. If you want to use Chinese, qq group for you to other community members.
