### ISSUE TITLE
duplicated services  in combobox

### ISSUE THREAD

**Issue by whaon** [apache/skywalking#6484]
reference #6429 

skywalking version is  **v8.4.0 for H2/MySQL/TiDB/InfluxDB/ElasticSearch 7**

when use **mysql** as storage,the table store all services is table **service_traffic** and the id is primary key,so when a new service restart today,it insert a record and when it restart tomorrow it will not insert again,it's ok when when search service in the webUI.

but when use **es** as storage,it split tables by day,such as es_service_traffic-20210303,es_service_traffic-20210304 etc.
when a service restart today,it insert a record in es_service_traffic-20210304,and we restart tomorrow it will insert a record into es_service_traffic-20210305 again,but the http interface /graphql of queryServices collect all the services in the tables by day ,so the services in UI will be duplicated and cause the search problem in #6429 

the database has the same data problem but the search is ok:
```
{
	"data": {
		"services": [{
			"key": "MTkyLjE2OC4xLjk4OjMzMDY=.0",
			"label": "192.168.1.198:3306"
		}, {
			"key": "MTkyLjE2OC4xLjk5OjMzMDY=.0",
			"label": "192.168.11.99:3306"
		}, {
			"key": "MTkyLjE2OC4xLjgyOjMzMDY=.0",
			"label": "192.168.11.82:3306"
		}, {
			"key": "MTkyLjE2OC4xLjk5OjMzMDY=.0",
			"label": "192.168.11.99:3306"
		}, {
			"key": "MTkyLjE2OC4xLjgyOjMzMDY=.0",
			"label": "192.168.11.82:3306"
		}, {
			"key": "MTkyLjE2OC4xLjk5OjMzMDY=.0",
			"label": "192.168.1.99:3306"
		}, {
			"key": "MTkyLjE2OC4xLjk4OjMzMDY=.0",
			"label": "192.168.11.98:3306"
		}, {
			"key": "MTkyLjE2OC4xLjk5OjMzMDY=.0",
			"label": "192.168.11.99:3306"
		}, {
			"key": "MTkyLjE2OC4xLjk5OjMzMDY=.0",
			"label": "192.168.11.99:3306"
		}, {
			"key": "MTkyLjE2OC4xLjk4OjMzMDY=.0",
			"label": "192.168.11.98:3306"
		}, {
			"key": "MTkyLjE2OC4xLjgyOjMzMDY=.0",
			"label": "192.168.11.82:3306"
		}]
	}
}
```

**Comment by wu-sheng** [comment]
We explain repeatedly at this, this is not exactly like you described. Please read old issues and the official demo is on es, no duplicated.

**Comment by xuanyu66** [comment]
@whaon hello, have you solve the problem
