### ISSUE TITLE
[question] local test for plugin, could not pull docker image skywalking/agent-test-jvm

### ISSUE THREAD

**Issue by xingren23** [apache/skywalking#6485]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

when run local test for plugin, could not pull docker image skywalking/agent-test-jvm , how to get or build this image ?

sh test/plugin/run.sh -f dubbo-2.7.x-scenario
+ mv ./target/dubbo-2.7.x-scenario.jar ./target/dubbo-2.7.x-scenario.jar.original ./target/dubbo-2.7.x-scenario.zip /Users/wangzhiguo/workspace/skywalking/skywalking/test/plugin/workspace/dubbo-2.7.x-scenario/2.7.3
+ java -jar -Xmx256m -Xms256m -Dconfigure.file=/Users/wangzhiguo/workspace/skywalking/skywalking/test/plugin/scenarios/dubbo-2.7.x-scenario/configuration.yml -Dscenario.home=/Users/wangzhiguo/workspace/skywalking/skywalking/test/plugin/workspace/dubbo-2.7.x-scenario/2.7.3 -Dscenario.name=dubbo-2.7.x-scenario -Dscenario.version=2.7.3 -Doutput.dir=/Users/wangzhiguo/workspace/skywalking/skywalking/test/plugin/workspace/dubbo-2.7.x-scenario/2.7.3 -Dagent.dir=/Users/wangzhiguo/workspace/skywalking/skywalking/test/plugin/../../skywalking-agent -Djacoco.home=/Users/wangzhiguo/workspace/skywalking/skywalking/test/plugin/../jacoco -Ddebug.mode= -Ddocker.image.version=1.0.0 /Users/wangzhiguo/workspace/skywalking/skywalking/test/plugin/dist/plugin-runner-helper.jar
+ [[ 0 -ne 0 ]]
+ echo 'start container of testcase.name=dubbo-2.7.x-scenario-2.7.3'
start container of testcase.name=dubbo-2.7.x-scenario-2.7.3
+ bash /Users/wangzhiguo/workspace/skywalking/skywalking/test/plugin/workspace/dubbo-2.7.x-scenario/2.7.3/scenario.sh
Unable to find image 'skywalking/agent-test-jvm:1.0.0' locally
docker: Error response from daemon: pull access denied for skywalking/agent-test-jvm, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
"docker wait" requires at least 1 argument.
See 'docker wait --help'.

Usage:  docker wait CONTAINER [CONTAINER...]

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
@xingren23 please refer to https://github.com/apache/skywalking/blob/d113f58645f7f02508da75f648e829dbd83e7d82/docs/en/guides/Plugin-test.md and https://github.com/apache/skywalking/blob/9de93119e2e616e419c540a17de00e6f1719c2b2/.github/actions/plugins-test/action.yml#L73
