### ISSUE TITLE
Why doesn’t JVMMetricsSender notify the status as DISCONNECT when sending a network error?

### ISSUE THREAD

**Issue by LiWenGu** [apache/skywalking#6491]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?

Why doesn’t JVMMetricsSender notify the status as DISCONNECT when sending a network error?
Is it by design or is it missed? I noticed that if there is a network error, TraceSegmentServiceClient/MeterSender/ServiceManagementClient will notify DISCONNECT.

https://github.com/apache/skywalking/blob/871fdf2fa251e3e2c3082a2373e4ead6c4aec8fd/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/jvm/JVMMetricsSender.java#L70-L89

**Comment by wu-sheng** [comment]
What do you mean? I can see `JVMMetricsSender#statusChanged` exists. What do I miss?

**Comment by LiWenGu** [comment]
I mean, why not add reportError in line 86, like this:
```java
 catch (Throwable t) {
    LOGGER.error(t, "send JVM metrics to Collector fail.");
    ServiceManager.INSTANCE.findService(GRPCChannelManager.class).reportError(t);
}
```

**Comment by kezhenxu94** [comment]
> I mean, why not add reportError in line 86, like this:
> 
> ```java
> 
>  catch (Throwable t) {
> 
>     LOGGER.error(t, "send JVM metrics to Collector fail.");
> 
>     ServiceManager.INSTANCE.findService(GRPCChannelManager.class).reportError(t);
> 
> }
> 
> ```
> 
> 

I think it's missed, will you open a pull request to add it?
