### ISSUE TITLE
zuul with skywalking8.4.0 config grpc but the skywalking log does not work

### ISSUE THREAD

**Issue by apple987** [apache/skywalking#6494]
zuul config with skywalking grpc,but the skywalking console can not show the traceId,the current version 8.4.0

![image](https://user-images.githubusercontent.com/21330215/110075149-51d2ea00-7dbd-11eb-88ad-00cb875d4d3c.png)
![image](https://user-images.githubusercontent.com/21330215/110075187-61eac980-7dbd-11eb-9a22-9ec702d9bff0.png)

**Comment by wu-sheng** [comment]
You are using log4j toolkit, read https://github.com/apache/skywalking/issues/6377 and check your logs.

**Comment by apple987** [comment]
zuul config with logback,not the log4j

**Comment by wu-sheng** [comment]
Then we don't have Zuul plugin, I am not sure because no one in the community says it works. Even the whole agent or tracing. Read the supported list documentation first.

**Comment by apple987** [comment]
ok!thanks
