### ISSUE TITLE
build skywalking on mac has error

### ISSUE THREAD

**Issue by zhyhzhylove** [apache/skywalking#6497]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
build skywalking has error,
![image](https://user-images.githubusercontent.com/3204108/110107489-e7826f80-7de5-11eb-8761-a2e7d76b24aa.png)

![image](https://user-images.githubusercontent.com/3204108/110107442-d46f9f80-7de5-11eb-9449-66a6353a8f57.png)
How should I solve this problem?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
Seems your mirror is not working, please try again or use another maven mirror

**Comment by zhyhzhylove** [comment]
thx
