### ISSUE TITLE
Propose to optimize the self monitoring grafana dashboard.

### ISSUE THREAD

**Issue by Ax1an** [apache/skywalking#6498]
- Why do you submit this issue?
- [x] Feature or performance improvement

### Requirement or improvement
  I propose to optimize the self monitoring grafana dashboard.

  Now, the dashboard is not only troublesome to import, but also lacks some important metrics. So I made two new dashboards that I wanted to contribute to the SkyWalking Community.

  The new dashboard is not only easy to import, but also has more practical metrics. Our company engineer uses it every day.

  I believe it can help more people who use SkyWalking. Whether it's self-monitoring or optimizing performance.

  Here is a comparison between the old and new dashboards.

  SkyWalking offical dashboard:
  
  ![image](https://user-images.githubusercontent.com/28091237/110111565-82317d00-7deb-11eb-855c-4797365411df.png)

  My optimized dashboard:

  1. SkyWalking Cluster Monitor Dashboard
  
  ![image](https://user-images.githubusercontent.com/28091237/110111644-a2f9d280-7deb-11eb-994b-674ac9e93351.png)

  2. SkyWalking Standalone Monitor Dashboard

  ![image](https://user-images.githubusercontent.com/28091237/110111705-b5740c00-7deb-11eb-9b3d-889a6ef55259.png)

**Comment by wu-sheng** [comment]
> SkyWalking Standalone Monitor Dashboard

Should this be called, OAP metrics per instance? Standalone means there is only one node of OAP, please confirm.

**Comment by Ax1an** [comment]
Yes，you are right. If the community accepts my propose, I will adjust the name later.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/skywalking"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 晚上7:52
收件人:&nbsp;"apache/skywalking"<skywalking@noreply.github.com&gt;;
抄送:&nbsp;"Ax1an"<ax1an@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/skywalking] Propose to optimize the self monitoring grafana dashboard. (#6498)





  
SkyWalking Standalone Monitor Dashboard
  
Should this be called, OAP metrics per instance? Standalone means there is only one node of OAP, please confirm.

**Comment by wu-sheng** [comment]
@apache/skywalking-committers I will treat this as lazy consensus, if no objection, then good to go.

**Comment by hanahmily** [comment]
It also looks great to me. Furthermore, our UI could get some insights from these panels.  @Ax1an Greate job!

**Comment by wu-sheng** [comment]
@Ax1an Could you give the full list of the metrics here with a table?

**Comment by Ax1an** [comment]
@hanahmily Thank you!

**Comment by Ax1an** [comment]
@wu-sheng wu Yes, I'll sort out the data.

**Comment by Ax1an** [comment]
I used almost all the metrics of SkyWalking exposure. And the mesh_analysis_error_count metrics needs to be increased.

| Metric Name                                  |
| -------------------------------------------- |
| jvm_info                                     |
| uptime                                       |
| process_start_time_seconds                   |
| process_cpu_seconds_total                    |
| process_resident_memory_bytes                |
| process_virtual_memory_bytes                 |
| process_open_fds                             |
| process_max_fds                              |
| jvm_memory_bytes_used                        |
| jvm_memory_bytes_committed                   |
| jvm_memory_bytes_max                         |
| jvm_memory_bytes_init                        |
| jvm_memory_pool_bytes_used                   |
| jvm_memory_pool_bytes_committed              |
| jvm_memory_pool_bytes_max                    |
| jvm_memory_pool_bytes_init                   |
| jvm_memory_pool_allocated_bytes_total        |
| jvm_gc_collection_seconds_count              |
| jvm_gc_collection_seconds_sum                |
| jvm_threads_started_total                    |
| jvm_threads_current                          |
| jvm_threads_daemon                           |
| jvm_threads_peak                             |
| jvm_threads_state                            |
| jvm_classes_loaded                           |
| jvm_classes_unloaded_total                   |
| jvm_buffer_pool_used_bytes                   |
| jvm_buffer_pool_capacity_bytes               |
| jvm_buffer_pool_used_buffers                 |
| trace_in_latency_count                       |
| trace_in_latency_sum                         |
| trace_analysis_error_count                   |
| mesh_analysis_latency_count                  |
| mesh_analysis_latency_sum                    |
| mesh_analysis_error_count (Need add)         |
| metrics_aggregation                          |
| remote_out_count                             |
| remote_in_latency_count                      |
| persistence_timer_bulk_prepare_latency_count |
| persistence_timer_bulk_prepare_latency_sum   |
| persistence_timer_bulk_execute_latency_count |
| persistence_timer_bulk_execute_latency_sum   |
| persistence_timer_bulk_error_count           |
| nacos_client_request_count                   |
| nacos_client_request_sum                     |

**Comment by wu-sheng** [comment]
3 suggestions
1. Where are the nacos metrics from? We need to remove that, as we don't recommend specific configuration center.
2. We should add trace in metrics to zipkin receiver with label.
3. Add telemetey data about metrics in, metrcis scratching, and log in metrics. And adjust dashboard.

Please consider these in the enhancement by using 2 - 3 PRs, one to add new telemetey, the other for dashboard, grafana and self observability

**Comment by Ax1an** [comment]
@wu-sheng I think your suggestion is very good. I will perfect it according to your suggestion.

**Comment by wu-sheng** [comment]
@Ax1an Consider #6516 has merged, could you make this feature ready?

**Comment by Ax1an** [comment]
@wu-sheng Sorry, I have other things to deal with this weekend. The grafana dashboard has some small details to adjust and I will submit them tomorrow.
