### ISSUE TITLE
Deployed skywalking-oap-es7, also connected to apm-agent, no data and no errors

### ISSUE THREAD

**Issue by eltonbfw** [apache/skywalking#6507]
Use the official helm package for installation, with the following configuration parameters

https://github.com/apache/skywalking-kubernetes

oap: 8.4.0-es7
elasticsearch: 7.11.1

As the title says, everything is fine, no error logs for oap, no error logs for agent, just can't query any data.

There is a list of services, there is a list of endpoints, but other than that, there is nothing

**Comment by wu-sheng** [comment]
Check the timezone on the right corner, should be utc0. Read the document and search the issue before you submit a new one.

**Comment by eltonbfw** [comment]
> Check the timezone on the right corner, should be utc0. Read the document and search the issue before you submit a new one.
You are right, it is indeed utc0.
I really didn't read the official documentation too carefully, and one of the main reasons is that I don't know how to find it.
Also, can I fix this problem by adding environment variables?
```yaml
- name: TZ
  value: Asia/Shanghai
```

**Comment by eltonbfw** [comment]
https://github.com/apache/skywalking/issues/6507#issuecomment-792369597

> Check the timezone on the right corner, should be utc0. Read the document and search the issue before you submit a new one.

Can you tell me where the documentation related to the time zone you mentioned is?

**Comment by wu-sheng** [comment]
How about first line of the documentation? https://skywalking.apache.org/docs/main/v8.4.0/en/setup/readme/
