### ISSUE TITLE
Support for Weblogic

### ISSUE THREAD

**Issue by ommikadam** [apache/skywalking#6510]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Discussion
- Requirement
- Feature

___
### Question
- Apache skywalk does not support weblogic it only displays JVM data no other data is logged is the support for weblogic is there or the feature may be available in future.?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
- Skywalking -8.4.0
- OS - RHEL 7
- JRE 1.8

**Comment by wu-sheng** [comment]
If you are using SpringMVC or Struts2, it is automatically set.

**Comment by wu-sheng** [comment]
You don't need specific plugin for it.

**Comment by wu-sheng** [comment]
If you are willing to decompile and write plugins, you could do like the existing Oracle plugin by 3rd party. But as Apache, we don't hack a commercial product.
