### ISSUE TITLE
about server side load balance questions

### ISSUE THREAD

**Issue by DeadLion** [apache/skywalking#6511]
- [x] Question or discussion

___
### Question
agent could set the collector server list , but application access increases, the server needs to expand. 

And we don't want to edit agent config(too many applications),

- so we consider  server side LB like F5 or LVS,is that a good idea?

- Another questions is  that backend supports  cluster management , agent why not get collector server list from consul 、zk or somethings else  ?

**Comment by wu-sheng** [comment]
1. We recommend Envoy proxy, Nginx, or similar HTTP2 supported L7 proxy.
2. We answered this many times. Please search issue before submit. Short version, typically, agents and OAP servers are in different VPCs. The things you mentioned wouldn't work.

**Comment by DeadLion** [comment]
thanks for anwser

we use consul for our micro services ,It's natural to use for skywalking server cluster management.
now skywalking agent trace these micro services ,so they are in same VPC.  maybe  our network is too simple.

maybe we could put those questions often be asked on FAQs

**Comment by wu-sheng** [comment]
> we use consul for our micro services ,It's natural to use for skywalking server cluster management.
now skywalking agent trace these micro services ,so they are in same VPC. maybe our network is too simple.

Your case may be not typically for larger scale deployment. In many cases, one company(big enterprise) has over 200 services, which are deployed even in different VPCs, K8s, data center. It is pointless to set a service discovery to resolve this, especially in today's cloud native tech stack, proxy is widely used, and good at it.
