### ISSUE TITLE
Can we install java agent into node of k8s?

### ISSUE THREAD

**Issue by childewuque** [apache/skywalking#6514]
Now ，We must add params in java start command ，sidecar or   the same container.
and if  skywalking supporting  installation on the k8s node, as if the agent installation is very simple. 
Some commercial softwares do like this.

**Comment by wu-sheng** [comment]
What agent installation? We don't have steps like that. Please be clear what you are asking.

> Some commercial softwares do like this.

This means nothing. Please focus on tech case and solution.

**Comment by childewuque** [comment]
This means to install the java agent on the k8s host node，we don’t have to add command line parameters.
It's easier.

Now there is no such installation way, so what is the official recommended installation method  of java agent in k8s?

**Comment by wu-sheng** [comment]
No, that is not correct. Java agent must change the command. This is how JVM works.
Your idea is wrong.
