### ISSUE TITLE
receiver don't need to get itself when healthCheck

### ISSUE THREAD

**Issue by xuanyu66** [apache/skywalking#6515]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion

___
### Question
- What do you want to know?
If OapNode‘s role is receiver, the OAPNodeChecker'method isHealth() will return unHealth.
```
 public static ClusterHealthStatus isHealth(List<RemoteInstance> remoteInstances) {
        if (CollectionUtils.isEmpty(remoteInstances)) {
            return ClusterHealthStatus.unHealth("can't get the instance list");
        }
        List<RemoteInstance> selfInstances = remoteInstances.stream().
                filter(remoteInstance -> remoteInstance.getAddress().isSelf()).collect(Collectors.toList());
        if (CollectionUtils.isEmpty(selfInstances)) {
            return ClusterHealthStatus.unHealth("can't get itself");
        }
        if (remoteInstances.size() > 1 && hasIllegalNodeAddress(remoteInstances)) {
            return ClusterHealthStatus.unHealth("find illegal node in cluster mode such as 127.0.0.1, localhost");
        }
        return ClusterHealthStatus.HEALTH;
    }
```

I think OAPNodeChecker should check its role and then decide whether to get itself.
But how can I get role?

**Comment by wu-sheng** [comment]
Yes, this is a bug, you could use `RemoteInstance#Address#isSelf` to get the status you want.
Are you going to submit a pull request to fix this?

**Comment by xuanyu66** [comment]
yes, maybe this week

**Comment by xuanyu66** [comment]
But how can I get OAP's role @wu-sheng

**Comment by wu-sheng** [comment]
I think currently, this is only available `CoreModuleProvider#start` stage, SkyWalking hasn't saved it in any place.

**Comment by xuanyu66** [comment]
But how can receiver realize that he doesn't need to check itself If he don't know his role is receiver

**Comment by s00373198** [comment]
1、Add variable `private static string role` in `OAPNodeChecker`, and set it in `CoreModuleProvider#start` stage
2、check `private static string role` before `CoreModuleProvider#isHealth` check itself
@wu-sheng ,is that ok?

**Comment by wu-sheng** [comment]
> 1、Add variable `private static string role` in `OAPNodeChecker`, and set it in `CoreModuleProvider#start` stage
> 2、check `private static string role` before `CoreModuleProvider#isHealth` check itself
> @wu-sheng ,is that ok?

Basically, I think it is reasonable. You could try a pull request about this.
