### ISSUE TITLE
skywalking and pinpoint compatibility test

### ISSUE THREAD

**Issue by HarryFQ** [apache/skywalking#6521]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### 1. Question
Does your online system use pinpoint? Are you still worried about the compatibility of skywalking and pinpoint?

#### 2.1 The test steps are as follows
1. Configuration
2. Call statistics on skywalking and pinpoint interfaces respectively
    1. Run pinpoint alone
    2. Run pinpoint and skywalking at the same time 
3. Result analysis
#### 2.2 Details of running pinpoint alone
1. Version Information
   2. pinpoint1.8.4， hbase
2. Configuration
   1. Pinpoint is deployed using the default configuration.
3. Application agent Configuration
```
-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/spring-boot/gc_logs/delay-queue/java_dump1.hprof -Xloggc:/app/spring-boot/gc_logs/delay-queue/gc1.log -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCDateStamps -XX:+DisableExplicitGC -XX:+ExplicitGCInvokesConcurrent -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=3 -XX:GCLogFileSize=5M -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1026 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -javaagent:/app/jvmagent/jmx_prometheus_javaagent-0.12.0.jar=12345:/app/jvmagent/config.yaml  -server -Xms4096m -Xmx4096m -Xmn2g -Xss256K -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseCMSInitiatingOccupancyOnly  -Xbootclasspath/a:/app/pinpoint-agent-boot/fcbox-trace-util.jar -javaagent:/app/pinpoint-agent-boot/pinpoint-bootstrap-1.8.4.jar -Dpinpoint.agentId=$APP_NAME`echo $MY_POD_IP|awk -F '.' '{print $3}'` -Dpinpoint.applicationName=$APP_NAME  -jar /app/war/delay-queue/pkg/delay-queue.jar
```
##### 2. Application startup information
The following pictures are screenshots of pinpoint and skywalking startup, as well as screenshots of abnormal source code.
![image](https://user-images.githubusercontent.com/34418180/110429396-da1afd00-80e5-11eb-8dc3-c8e7b02c0428.png)

##### 3. Application request statistics
1. The test case calls the test service interface 5000 times per minute, and then counts the individual running status of pinpoint.
    1. Initial state
![image](https://user-images.githubusercontent.com/34418180/110430341-303c7000-80e7-11eb-801d-db81bf067b85.png)
2. Statistics start
     the first time
![image](https://user-images.githubusercontent.com/34418180/110430486-6ed22a80-80e7-11eb-9b1a-a63c20ba7e85.png)
     the second time
![image](https://user-images.githubusercontent.com/34418180/110430619-99bc7e80-80e7-11eb-8489-18b52b4c1060.png)
     the third time
![image](https://user-images.githubusercontent.com/34418180/110430684-b48ef300-80e7-11eb-8c42-d1cecaadcd17.png)

#### 2.3Details of running pinpoint and skywalking at the same time
1. Version Information
   1. skywalking8.3，kafka2.1.4，es7.6.2
   2. pinpoint1.8.4， hbase
2. Configuration
   1. skywalking deploys using kubernetes default configuration.
   2. Pinpoint is deployed using the default configuration.
3. Application agent Configuration
```
-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/spring-boot/gc_logs/delay-queue/java_dump1.hprof -Xloggc:/app/spring-boot/gc_logs/delay-queue/gc1.log -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCDateStamps -XX:+DisableExplicitGC -XX:+ExplicitGCInvokesConcurrent -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=3 -XX:GCLogFileSize=5M -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1026 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -javaagent:/app/jvmagent/jmx_prometheus_javaagent-0.12.0.jar=12345:/app/jvmagent/config.yaml  -server -Xms4096m -Xmx4096m -Xmn2g -Xss256K -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseCMSInitiatingOccupancyOnly  -Xbootclasspath/a:/app/pinpoint-agent-boot/fcbox-trace-util.jar -javaagent:/app/pinpoint-agent-boot/pinpoint-bootstrap-1.8.4.jar -Dpinpoint.agentId=$APP_NAME`echo $MY_POD_IP|awk -F '.' '{print $3}'` -Dpinpoint.applicationName=$APP_NAME -javaagent:/app/skywalking/agent/skywalking-agent.jar   -Dskywalking.collector.backend_service=skywalking-oap.skywalking.svc.cluster.local:11800 -Dskywalking.agent.service_name=$APP_NAME -Dskywalking.agent.instance_name=$APP_NAME`echo $MY_POD_IP|awk -F '.' '{print $3}'` -Dskywalking.plugin.kafka.bootstrap_servers=10.216.58.167:9092,10.216.58.168:9092,10.216.58.169:9092 -jar /app/war/delay-queue/pkg/delay-queue.jar
```
##### 2. Application startup information
The following pictures are screenshots of pinpoint and skywalking startup, as well as screenshots of abnormal source code.
![image](https://user-images.githubusercontent.com/34418180/110426392-fbc5b580-80e0-11eb-8000-bc7d6035a15a.png)
![image](https://user-images.githubusercontent.com/34418180/110426334-df297d80-80e0-11eb-81d4-b9df163dbc55.png)
![image](https://user-images.githubusercontent.com/34418180/110426581-55c67b00-80e1-11eb-861f-ca9d2257206e.png)
##### 3. Application request statistics
1. The test case calls 5000 test service interfaces every minute, and then counts whether the two tests are the same.
    1. Initial state
![image](https://user-images.githubusercontent.com/34418180/110427384-a2f71c80-80e2-11eb-8b13-5d5237cd0528.png)
![image](https://user-images.githubusercontent.com/34418180/110427426-b0aca200-80e2-11eb-9a56-8de9838da1e1.png)
     2. Statistics start
     the first time
![image](https://user-images.githubusercontent.com/34418180/110427685-1305a280-80e3-11eb-8bf0-9b47df4e9080.png)
![image](https://user-images.githubusercontent.com/34418180/110427798-3c263300-80e3-11eb-91b7-c05eb8a05663.png)     the second time
![image](https://user-images.githubusercontent.com/34418180/110427894-62e46980-80e3-11eb-9286-172718a113e6.png)
![image](https://user-images.githubusercontent.com/34418180/110428035-a8089b80-80e3-11eb-87e6-692124961e72.png)
![image](https://user-images.githubusercontent.com/34418180/110428352-13eb0400-80e4-11eb-8d70-e28eee886250.png)
#### 3. conclusion
Only from the final statistical results, the two are compatible with each other. Although there is a type mismatch in the second startup log, you will find that it is because the pinpoint type does not match. This is because both of them use bytecode enhancement technology, and from the source code document. It can be understood that there are problems with using the same technology. The processing above the source code is only to capture the exception and print it out in debug form. Generally, bytecode enhancement technology does not appear in our business logic.

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
skywalking8.3,pinpoint1.8.4

**Comment by wu-sheng** [comment]
> Does your online system use pinpoint? Are you still worried about the compatibility of skywalking and pinpoint?

No, this is not our responsibility.
