### ISSUE TITLE
storage module no provider found - Postgresql

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6522]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Using postgresql as storage option getting following error  (v.8.4.0)

2021-03-09 11:43:25,492 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - storage module no provider found.
org.apache.skywalking.oap.server.library.module.ProviderNotFoundException: storage module no provider found.
 

Configuration  - 

oap- lib - 

-rwxrwxrwx. 1 root root 1004719 Mar  9 09:16 postgresql-42.2.18.jar

postgresql:
    properties:
      jdbcUrl: ${SW_JDBC_URL:"jdbc:postgresql://x.x.x.x:5432/skywalking"}
      dataSource.user: ${SW_DATA_SOURCE_USER:postgres}
      dataSource.password: ${SW_DATA_SOURCE_PASSWORD:postgres}
      dataSource.cachePrepStmts: ${SW_DATA_SOURCE_CACHE_PREP_STMTS:true}

Kindly advice. 

Thanks and Regards,
Jayesh Muley

**Comment by kezhenxu94** [comment]
PostgreSQL storage plugin is not included in 8.4.0, it is expected to be available in (next release 8.5.0)
