### ISSUE TITLE
a quick and effective upgrade way ?

### ISSUE THREAD

**Issue by lzjlzj43** [apache/skywalking#6523]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to quickly upgrade new skywalking version (oap,ui,agent) in production environment when hundreds of applicatons has integrated its older version?
___
### Bug
- Which version of SkyWalking, OS, and JRE?
v8.3.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
 Hundreds of applications  in production environment has integated skywalking v8,3,0 , and now I want to upgrade skywaking v8.3.0 to v8.4.0 , is there a quick and effective way?

**Comment by woshishitou** [comment]
> Set up a new backend, and everything should be back to normal in several minute. You could upgrade agents on any moment you can.

Hello. Is the upgrade from 8.1 to 8.4 similar to the upgrade from 8.3 to 8.4?
