### ISSUE TITLE
Is there a way to add a new SpanLayer definetion?

### ISSUE THREAD

**Issue by snakorse** [apache/skywalking#6524]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- Is there a way to add a new SpanLayer definetion?

**Comment by wu-sheng** [comment]
That do you mean a way? It is an enum, so definitely could add. The issue is what case.

**Comment by snakorse** [comment]
I want to add spans produced by a job-scheduler framework, and I can't find the proper value in the  predefined SpanLayer enums, so I need defined a new enum something like SpanLayer.Scheduler-Framework, and my question is: 
How to give this new user-defined SpanLayer value a friendly name shown on the RocketUI Tracing page?

**Comment by wu-sheng** [comment]
`job-scheduler` is not a layer. The layer only relates to RPC.
