### ISSUE TITLE
kafka 批量消费的场景，Skywalking8+版本 链路和traceId如何支持的？kafka batch consumption scenarios, how Skywalking8+ supporting tracing and  traceId in this case?

### ISSUE THREAD

**Issue by chenhuandong8010** [apache/skywalking#6528]
当kafka生产者多次请求消费产生多条链路，多个traceId，然后kafka消费者批量消费，通过kafka header透传过来的trace链路信息的处理逻辑是什么样的？是随机选择继承一个trace链路吗？求指导！
when kafka producers repeatedly request consumption to produce multiple tracing, multiple traceIds, and then kafka consumers to consume in batches, what is the processing logic of tracing information transmitted through the kafka header? Are randomly selected to inherit a tracing info?

**Comment by wu-sheng** [comment]
We don't explain the logic of the codes, that is not the open source community's responsibility.
