### ISSUE TITLE
How is the trace ID propagated when REST services invoke each other?

### ISSUE THREAD

**Issue by JHub-Wei** [apache/skywalking#6529]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is the trace ID in the request header when REST services invoke each other?If so, in which header is it?How do I collect trace IDs from Istio access logs? I tried to add trace-id: request.headers["sw8"] | "unknown" to the rule, but it didn't take effect.
___
### Bug
- Which version of SkyWalking, OS, and JRE?
- 8.3.0

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read the documentation before you submit a question.

**Comment by wu-sheng** [comment]
http://skywalking.apache.org/docs/main/latest/en/protocols/skywalking-cross-process-propagation-headers-protocol-v3/
