### ISSUE TITLE
How do I  remove the index for C# related _clr_ index?

### ISSUE THREAD

**Issue by lsy1990** [apache/skywalking#6531]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by lsy1990** [comment]
We don't need the index related _clr? this will occupy some lucense instance.

**Comment by kezhenxu94** [comment]
Use `disable` directive to disable the metrics in https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/oal/dotnet-agent.oal

**Comment by wu-sheng** [comment]
You could set `SW_RECEIVER_CLR=-` in the system env. Then the whole OAL script is going to be disabled.

**Comment by lsy1990** [comment]
@wu-sheng，I still use 7.0.0， update the oal file maybe is right.

**Comment by kezhenxu94** [comment]
> @wu-sheng，I still use 7.0.0， update the oal file maybe is right.

@lsy1990 `SW_RECEIVER_CLR` is feasible in 7.0.0

**Comment by lsy1990** [comment]
@kezhenxu94 Thanks.

**Comment by lsy1990** [comment]
@kezhenxu94   Set   SW_RECEIVER_CLR to -， the log show 'Remove module receiver-clr without any provider'   ,but the index related _clr_ ,such as instance_clr_gen0_collect_count_month, will still be created.

**Comment by lsy1990** [comment]
org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.createTable(StorageEsInstaller.java:87) - create instance_clr_cpu_hour-20210311 index finished

**Comment by kezhenxu94** [comment]
OK I see, for 7.0.0, the CLR related oal are all in the `https://github.com/apache/skywalking/blob/v7.0.0/oap-server/server-bootstrap/src/main/resources/official_analysis.oal`, please use `disable` or delete the related lines in that file

**Comment by lsy1990** [comment]
@kezhenxu94 Agree, I will use disable to test ,thanks.
