### ISSUE TITLE
Agent performance overhead

### ISSUE THREAD

**Issue by JHub-Wei** [apache/skywalking#6535]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is there any optimization method for the performance overhead caused by the access agent?For example, we have a service that is not connected to Skywalking. The JVM runs for 31 seconds and the service starts for 24 seconds. After Skywalking is interconnected, the JVM runs for 99 seconds, but the service starts for only 52 seconds.
In addition, can I set a sampling policy on the agent side? For example, successful partial sampling and failed full sampling.
___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.3.0
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We don't have bootstrap performance. Runtime overhead, we have.
Read the document.

**Comment by JHub-Wei** [comment]
In addition, can I set a sampling policy on the agent side? For example, successful partial sampling and failed full sampling.

**Comment by wu-sheng** [comment]
Read the documentation and follow the guide there.

**Comment by JHub-Wei** [comment]
But the document doesn't say that...

**Comment by wu-sheng** [comment]
Which document says something not provided? If it doesn't exist on the document, but it is not a feature.
