### ISSUE TITLE
hourMetricsDataTTL is deleted in skywalking7,8? 

### ISSUE THREAD

**Issue by lanxiudh** [apache/skywalking#6540]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- hourMetricsDataTTL is deleted in skywalking7 or 8?  The min ttl is Day, right?  

___
### Bug

___

**Comment by wu-sheng** [comment]
Please read the document before submitting an issue, http://skywalking.apache.org/docs/main/v8.4.0/en/faq/hour-day-metrics-stopping/
