### ISSUE TITLE
A little confused about the alarm rules

### ISSUE THREAD

**Issue by ppliuppliu** [apache/skywalking#6541]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Requirement
- [ ] Bug
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I am a little confused about the conception of the alarm rule, even after I read the document  many times.

- How often will the data be evaluated? If I set the _Period_ to be 10, will it evaluate the data of the past 10 minutes every 1 minute? Or I can set the interval in somewhere?
- What _Count_ exactly means? If I set the _Count_ to be 2, and the _Period_ to be 10,  does it means the metric reach the alarm condition for 20 minutes? Or twice of the evaluated interval?

**Comment by wu-sheng** [comment]
Think in this way, period is windows of metric slot. Count means how many slots over the threshold in the given window.

**Comment by ppliuppliu** [comment]
查了下代码，每10s检测一下告警，但我更没有办法理解这里count的含义了。
以默认告警配置为例：
`  service_resp_time_rule:
    metrics-name: service_resp_time
    op: ">"
    threshold: 1000
    period: 10
    count: 3
    silence-period: 5
    message: Response time of service {name} is more than 1000ms in 3 minutes of last 10 minutes.`

这里的count:3 为什么是指 响应时间在最近10分钟内有3分钟超过了1000ms，服务的吞吐比较高的话，每秒都有几十次请求，每个请求都有响应时间，这个3是如何对应到3分钟的呢？如果是指检测间隔的话，应该是30s才对吧

**Comment by ppliuppliu** [comment]
How to understand _how many slots_? Take response time as an example. When the application throughput is relatively high, there are hundreds of requests per second, and each request has a response time. Does each request count as a count?

**Comment by wu-sheng** [comment]
In the storage, all metrics have been downsampling into minutes. Such as CPM in 21:54 is one slot, the next is 21:55. What is your traffic load, doesn't matter.
