### ISSUE TITLE
 Can't generate method doEndpointAbnormal for EndpointDispatcher.

### ISSUE THREAD

**Issue by keylihai** [apache/skywalking#6545]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
the question is that i add two oal  metrics that are given by official document to core.oal .
![image](https://user-images.githubusercontent.com/11571589/110911861-31bba180-834e-11eb-87ff-69cc7abf1763.png)
but it get error:
![image](https://user-images.githubusercontent.com/11571589/110911922-47c96200-834e-11eb-844f-fa847d354187.png)

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Sum requires a value as parameter. I remember there is a wrong in the doc, and has been fixed in the latest.

**Comment by keylihai** [comment]
@wu-sheng So,how cat i define a metric to do the same thing like this:
endpoint_abnormal = from(Endpoint.*).filter(responseCode in [404, 500, 503]).sum()

**Comment by wu-sheng** [comment]
Are you meaning count?

**Comment by keylihai** [comment]
@wu-sheng yes

**Comment by wu-sheng** [comment]
Use count function. Sum means add the value of a field.

**Comment by 1534834526** [comment]
new version 9.4.0,skywalking/docs/en/concepts-and-designs/oal.md，use endpoint_abnormal = from(Endpoint.*).filter(httpResponseStatusCode in [404, 500, 503]).count() can pass
