### ISSUE TITLE
Skywalking-client-js cannot fetch a stream from the fetch API

### ISSUE THREAD

**Issue by tianyk** [apache/skywalking#6546]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- [skywalking-client-js](https://github.com/apache/skywalking-client-js)

- Which company or project?
[pdf.js](https://github.com/mozilla/pdf.js/)

- What happened?
[whatwg-fetch](https://github.com/github/fetch) doesn't implement stream api <https://github.com/github/fetch/issues/746> An error occurs when you try to get a ReadableStream. pdf.js use `res.body` get a stream.

```js
// Fetch the original image
fetch('./tortoise.png')
// Retrieve its body as ReadableStream
.then(response => response.body)
.then(body => {
  const reader = body.getReader();
});
```
![image](https://user-images.githubusercontent.com/3387702/110934783-756fd480-8369-11eb-9c1f-7bb693d8570a.png)

[jsfiddle example](https://jsfiddle.net/pdfjs/wagvs9Lf/) (First of all, the cross-domain problem should be solved before it can be reproduced)

@Fine0830

**Comment by Fine0830** [comment]
Close this via https://github.com/apache/skywalking-client-js/pull/48
