### ISSUE TITLE
Will the memory leak when the oap server cooperates with the kafka plug-in?

### ISSUE THREAD

**Issue by goudai** [apache/skywalking#6548]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
## oap-server version 8.4 monitoring(-Xmx4300M -Xms4300M)
![image](https://user-images.githubusercontent.com/16605628/111071214-0bddfa80-8510-11eb-85d6-6e09e0ddff5c.png)
![image](https://user-images.githubusercontent.com/16605628/111071334-a0e0f380-8510-11eb-9ffe-3f729777a05e.png)
![image](https://user-images.githubusercontent.com/16605628/111071355-b6eeb400-8510-11eb-867d-72e44dbcf494.png)

**Comment by wu-sheng** [comment]
4G is not a big memory set. and your stack shows, there are a lot of ES Request instances, which means your ElasticSearch can't support the traffic, so many things are hold in the memory.  
We have a size threshold for the queues, but still, you could leak considering you only have 4G memory.

**Comment by goudai** [comment]
How to set the size of the queue to avoid OOM。

**Comment by wu-sheng** [comment]
First of all, 4G is really not suitable for product env. The current queue size is 20k elements(max) per metric. It is a static setting, rather than a configuration.

**Comment by goudai** [comment]
What is the recommended setting。

**Comment by wu-sheng** [comment]
Base on your throughput, at least 8G or 16G, even above. OAP server could process 100k+ traces/s easily, but you need to make sure, your ES server and memory are enough

**Comment by goudai** [comment]
My ES can support 100W/s writes, and my oap runs in kubernetes. I want to run multi-pod, small (2G, 4G) OAPserver, because this way I can make better use of fragmented resources. At present, I It's useless to encounter the performance problem of writing ES, but the problem of OAPserver GC AND OOM。

**Comment by wu-sheng** [comment]
You have a huge number of ES update objects, read the memory table you posted yourself. It shows very clear. I am doubting the performance of your ES. 
Anyway, that is your env, I(we) can't and shouldn't touch. I just provide information to help. You need to do deep analysis.

**Comment by goudai** [comment]
The memory has been increased according to your suggestion, and oap-server seems to be working great at the moment.
![image](https://user-images.githubusercontent.com/16605628/111072545-fec40a00-8515-11eb-9f6b-5569ee7b5d3b.png)

**Comment by goudai** [comment]
Can I reduce the accumulation of memory queues by increasing SW_STORAGE_ES_CONCURRENT_REQUESTS and SW_KAFKA_HANDLER_THREAD_POOL_SIZE? , I found that my maximum batch submission is set to 4000, the actual maximum submission is about 2300, this configuration does not seem to take effect. My ES is very idle.

**Comment by wu-sheng** [comment]
Check the metrics about persistent latency. What does it say?

**Comment by goudai** [comment]
![image](https://user-images.githubusercontent.com/16605628/111073227-e99caa80-8518-11eb-906b-98a5ce1d687f.png)

**Comment by wu-sheng** [comment]
OK, this could confirm, your ES status is good. Then just simply making the OAP having enough memory. It should be good enough.

**Comment by goudai** [comment]
I need to support OAP to write ES 100W/s. May I have any good suggestions, such as machine specifications, memory size, number of CPU cores, OAP parameter configuration, and the number of OAP PODs.

**Comment by wu-sheng** [comment]
Sorry, I don't have that. This could be changed by many different factors. And this is far from the community support responsibility.

**Comment by goudai** [comment]
`SW_STORAGE_ES_CONCURRENT_REQUESTS`  `SW_KAFKA_HANDLER_THREAD_POOL_SIZE` configured to the same size？

**Comment by wu-sheng** [comment]
Those have nothing related.

**Comment by goudai** [comment]
would like to ask what might be causing this.
![image](https://user-images.githubusercontent.com/16605628/111074096-7c8b1400-851c-11eb-9361-3fa72b8e4874.png)

**Comment by wu-sheng** [comment]
I am not sure, should not.

**Comment by goudai** [comment]
### he's here again 
![image](https://user-images.githubusercontent.com/16605628/111074775-9e39ca80-851f-11eb-8cf1-b05dadc28872.png)

**Comment by wu-sheng** [comment]
Sorry, GC really needs your own work to locate the scenario. We are impossible to guess.
