### ISSUE TITLE
How to use tags for trace search in Web UI?

### ISSUE THREAD

**Issue by yaojingguo** [apache/skywalking#6551]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I got traces after I submitted a search with no tags specified.

<img width="926" alt="截屏2021-03-15 下午7 55 23" src="https://user-images.githubusercontent.com/516386/111149877-63d83800-85c8-11eb-82c8-8205611b521d.png">

And there were traces with `http.method:GET` tag:

<img width="1680" alt="截屏2021-03-15 下午8 04 57" src="https://user-images.githubusercontent.com/516386/111150970-c251e600-85c9-11eb-9250-bdf15951f012.png">

Then I added `http.method:GET` tag and searched again, I got nothing.

<img width="1064" alt="截屏2021-03-15 下午7 55 56" src="https://user-images.githubusercontent.com/516386/111150015-8bc79b80-85c8-11eb-8a9b-ba8184d02e8f.png">

Why did I get no traces with `http.method:GET` tag? Is there something wrong with my usage of tag search?

I was using v8.4.0 with JDK 1.8.0_162 on macOS 10.15.5. I used the default storage backend. And I did not update `./config/application.yml`.

**Comment by wu-sheng** [comment]
I am looking at the demo env, it is working.

![image](https://user-images.githubusercontent.com/5441976/111159377-01853480-85d4-11eb-960e-554b43220cf2.png)

Check `searchableTracesTags` in your `application.yml`, it should be like this in the core module
![image](https://user-images.githubusercontent.com/5441976/111159541-2b3e5b80-85d4-11eb-8dbb-6dc806c62161.png)

**Comment by yaojingguo** [comment]
Trace search with tags works with es7. But it does not work with MySQL and h2.

**Comment by yaojingguo** [comment]
https://github.com/apache/skywalking/commit/03824477496910c39ded204f03697126ab990838#diff-43fb50c00bdccd70957a71c68472111bd74eea94546269f340e9651b62bb8292 fixes this problem.
