### ISSUE TITLE
“Global Response Latency” has no data to display.

### ISSUE THREAD

**Issue by CodingOX** [apache/skywalking#6555]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug

___
### Bug
- Which version of SkyWalking, OS, and JRE?
Skyalking:8.4.0
OS:CentOS 7
JRE:JDK 11

- What happened?
I deploy skywalking through docker and use elasticsearch 7 as storage. But found “Global Response Latency” has no data to display.
![image](https://user-images.githubusercontent.com/9800933/111264891-45734a80-8663-11eb-904d-98463ec4bb24.png)

And I didn't find any error logs on the oap-server. es7 work fine。How should I deal with this problem？

**Comment by wu-sheng** [comment]
0 doesn't always mean error. This is a percentile, if your service is quicker enough, less than 10ms globally, it shows as 0.

**Comment by CodingOX** [comment]
> 0 doesn't always mean error. This is a percentile, if your service is quicker enough, less than 10ms globally, it shows as 0.


The above figure shows that the HTTP request during this period took 23679 milliseconds，This number should be much more than 10ms。

![image](https://user-images.githubusercontent.com/9800933/111274474-fed81d00-866f-11eb-9555-a087149f1d12.png)

**Comment by wu-sheng** [comment]
Read why percentile means. Slow endpoints existing are fine. This may not affect the statistic.
