### ISSUE TITLE
Whether the sampling rate causes a VNode to appear？

### ISSUE THREAD

**Issue by woshishitou** [apache/skywalking#6556]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Whether the sampling rate causes a VNode to appear？

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by woshishitou** [comment]
There are many vnodes in my Skywalking. I understand that the direct reason for vnodes' appearance is the loss of segment. I refer to this article:
https://github.com/apache/skywalking/blob/9268b987afd35ed6b0b963758bfd7d55c0916b23/docs/en/FAQ/vnode.md
I also checked the Response information with the browser, and it is true that some segment is missing

**Comment by woshishitou** [comment]
Then, I found the following issue:
https://github.com/apache/skywalking/issues/5297
According to the last two dialogues of this issue, I know that we can start with "Samprate, Plugin Bug, Backend Process Capability not enough, Elastic Search Cluster are not enough" to find the reason for segment loss

**Comment by woshishitou** [comment]
Then I found the following article describing the sampling rate:
https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/trace-sampling.md
I found that the sampRate for the current Skywalking service was set to 1%. I adjusted it to 100%, and there were no vnodes appeared (this proves that it's the sampling rate that caused the vnodes to happen, it's not something else).
However, this phenomenon does not match the following description in the documentation:
"Of course, even you open sampling, the traces will be kept as consistent as possible. Consistent means, once the trace segments have been collected and reported by agents, the backend would do their best to don't break the trace. See Recommendation to understand why we called it as consistent as possible and do their best to don't break the trace."
That is, I don't think Skywalking guarantees the consistency of the trace.

**Comment by woshishitou** [comment]
As currently understood, in order not to have a VNode, I have to adjust the sampling rate to 100%

**Comment by woshishitou** [comment]
Am I not doing something wrong?

**Comment by woshishitou** [comment]
Did I do something wrong?

**Comment by wu-sheng** [comment]
> As currently understood, in order not to have a VNode, I have to adjust the sampling rate to 100%

This is a wrong statement. Sampling would affect the trace integrity unless you set different rates in different OAP nodes. The sampler at the backend is simply `trace_id mod N`.

**Comment by woshishitou** [comment]
> > As currently understood, in order not to have a VNode, I have to adjust the sampling rate to 100%
> 
> This is a wrong statement. Sampling would not affect the trace integrity unless you set different rates in different OAP nodes. The sampler at the backend is simply `trace_id mod N`.

There is only one node in My Skywalking cluster

**Comment by wu-sheng** [comment]
You could read the codes, there is nothing complex.

**Comment by woshishitou** [comment]
> You could read the codes, there is nothing complex.

Okay, thank you

**Comment by woshishitou** [comment]
I think I know why. My skywalking version is 8.1, I Read the code in this version, the sampler at the backend is simply trace_id mod N.

**Comment by woshishitou** [comment]
I think I know why.
My skywalking version is 8.1, and I Read the code in this version, the sampler at the backend is segmentid mod N.
And in version 8.4(current), the sampler at the backend  is indeed traceid mod n.

**Comment by wu-sheng** [comment]
> I think I know why.
> My skywalking version is 8.1, and I Read the code in this version, the sampler at the backend is segmentid mod N.
> And in version 8.4(current), the sampler at the backend is indeed traceid mod n.

Oh, yes. There was a bug about this.
