### ISSUE TITLE
A requirement of "slow statements"

### ISSUE THREAD

**Issue by OPSTime** [apache/skywalking#6557]
### Requirement or improvement
1、Whether we can add a display of SQL execution times in "slow statements" or sort according to the execution times, in practical work, we pay more attention to those slow queries that are executed the most times. Some slow queries may be executed once a day or at a longer interval, and the relative priority may not be the highest.
2、Whether "slow statements" can be associated with specific services (for example, add a "current service" to the right of "current database" as an optional condition), so that when troubleshooting problems, we can quickly locate which service slow SQL comes from.

**Comment by wu-sheng** [comment]
1. This is not easy to do. Because the slow statement is based on a sampling mechanism. It is hard to get the execution time.
2. You have to change codes to do that. You could set up the top N metrics to get the SQL list on the service level dashboard. The reason we don't do this, because accessing the same database from different services is not recommended in the distributed architecture. I am not sure why you are doing this.

**Comment by OPSTime** [comment]
1、获取采样数据中该慢SQL出现的次数就能反应出其调用频次高低了，也是有很强参考价值的
2、和具体服务关联起来，方便快速定位，不能说看到慢SQL再在大脑里回忆或者去查代码去看是和哪个有关系吧，还有一个库里有多种多张表，不同表对应不同服务在使用，不可能完全做到一个服务对应一个数据库实例吧。

**Comment by wu-sheng** [comment]
Please keep the discussion in English. We need things open for the global.

**Comment by OPSTime** [comment]
1. The frequency of slow SQL call can be reflected by the frequency of slow SQL in sampling data, which is also of great reference value

2. After being associated with specific services, it is convenient to quickly locate problems. Do we have to recall in our brain or look up the code to find out which service is related to? There are also multiple tables in a database. Different tables correspond to different services in use, or in different databases of the same instance. It is impossible to completely realize that one service corresponds to one database instance. Cost should be considered in the production environment.
