### ISSUE TITLE
MultiScopesAnalysisListener#setPublicAttrs log warn   frequently

### ISSUE THREAD

**Issue by pkxiuluo** [apache/skywalking#6562]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking: 8.3.0
OS: centos 6.7
JRE : 1.8

- What happened?
MultiScopesAnalysisListener#setPublicAttrs log warn   frequently

```
private void setPublicAttrs(SourceBuilder sourceBuilder, SpanObject span) {
       xxxxxxx
        span.getTagsList().forEach(tag -> {
            if (SpanTags.STATUS_CODE.equals(tag.getKey())) {
                try {
                    sourceBuilder.setResponseCode(Integer.parseInt(tag.getValue()));
                } catch (NumberFormatException e) {
                    log.warn("span {} has illegal status code {}", span, tag.getValue());
                }
            }
            sourceBuilder.setTag(tag);
        });
        xxxxxxx
}
```

As above code ,backend only accept status_code as Integer type, but some agent plugins  sent a String .
Because of STATUS_CODE defined  by  Tags#STATUS_CODE in apm agent-core is a StringTag, Most of agent plugin will use Integer.toString to guarantee it correct. but some plugin dosenot obey this rules，such as grpc_v1 、rocketmq_3.x、rocketmq_4.x 。

Suggestion:
create the IntTag class as subclass AbstractTag of  for STATUS_CODE , fix all agent plugins.

**Comment by wu-sheng** [comment]
> create the IntTag class as subclass AbstractTag of for STATUS_CODE , fix all agent plugins.

Make sense. Are you going to work on this?

> but some plugin dosenot obey this rules，such as grpc_v1 、rocketmq_3.x、rocketmq_4.x

They should use a new RESPONSE_CODE(StringTag), and also add responseCodeStr in the `SourceBuilder` and other `Sources`. Then the OAL script could use this kind of tag.

**Comment by wu-sheng** [comment]
@pkxiuluo Are you going to fix this?

**Comment by wallezhang** [comment]
I think I can fix this if no one else is working on it.

**Comment by wu-sheng** [comment]
> I think I can fix this if no one else is working on it.

@wallezhang assigned, no one is working on this.
