### ISSUE TITLE
UI Custom Dashboard panel : Could we provide some panels(chars) to show single value metrics which include labels

### ISSUE THREAD

**Issue by wankai123** [apache/skywalking#6569]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [X] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
Sometimes, the metrics provides info in labels, the value is a flag like:
```
kube_node_status_condition{node="gke-monitoring-default-pool-afc3b58c-9m3f",condition="DiskPressure",status="true"} 0
kube_node_status_condition{node="gke-monitoring-default-pool-afc3b58c-9m3f",condition="DiskPressure",status="false"} 1
kube_node_status_condition{node="gke-monitoring-default-pool-afc3b58c-9m3f",condition="DiskPressure",status="unknown"} 0
kube_node_status_condition{node="gke-monitoring-default-pool-afc3b58c-9m3f",condition="PIDPressure",status="true"} 0
kube_node_status_condition{node="gke-monitoring-default-pool-afc3b58c-9m3f",condition="PIDPressure",status="false"} 1
kube_node_status_condition{node="gke-monitoring-default-pool-afc3b58c-9m3f",condition="PIDPressure",status="unknown"} 0
kube_node_status_condition{node="gke-monitoring-default-pool-afc3b58c-9m3f",condition="Ready",status="true"} 1
kube_node_status_condition{node="gke-monitoring-default-pool-afc3b58c-9m3f",condition="Ready",status="false"} 0
kube_node_status_condition{node="gke-monitoring-default-pool-afc3b58c-9m3f",condition="Ready",status="unknown"} 0
```
After aggregation, in the meter system the metric value would like:
`DiskPressure, 0|PIDPressure,0|Ready,1`
For now, we could only select `read all values with label in the duration` and chose `Bar/Area/Line Chart`.
If we want to get useful info we have to put the mouse on the chart:
![image](https://user-images.githubusercontent.com/16773043/111457334-03c1cd00-8753-11eb-91bb-5f803c225328.png)

Could we provide some panels(charts) which can show the label info more directly when we don't need the duration values.Like just put label and value on the panel:
![image](https://user-images.githubusercontent.com/16773043/111458103-0244d480-8754-11eb-843b-1ed2a64eb892.png)

**Comment by wu-sheng** [comment]
Is this about the single value or the labeled value? If it is a single value, then no label involved. Please be clear about your requirements.

**Comment by wankai123** [comment]
I think it's a `single labeled value` that is a labeled value but don't need read duration values. @wu-sheng

**Comment by wu-sheng** [comment]
This is the official thing called single value, https://github.com/apache/skywalking-query-protocol/blob/42d6783d8c1a0d0d4c2b28e58dc1f47dd554964e/metrics-v2.graphqls#L143-L144. 

Also as the option on the UI setting page.
![image](https://user-images.githubusercontent.com/5441976/111464608-f0672f80-875b-11eb-9681-6bbfbdb81ff6.png)

If you are asking about the label, then, it is totally different thing. https://github.com/apache/skywalking-query-protocol/blob/42d6783d8c1a0d0d4c2b28e58dc1f47dd554964e/metrics-v2.graphqls#L149-L151

Both of them could visualize the way you mentioned, please confirm the case.

**Comment by wankai123** [comment]
OK, I got it. I mean labeled value, and need a more directly Chart to show the info like `read the single value in the duration `, not just `Line/Area/Bar`

**Comment by wu-sheng** [comment]
Actually, let me be clear about what you want to the UI side. @Fine0830 ignore above discussion to avoid confusing.

![image](https://user-images.githubusercontent.com/5441976/111466279-0c6bd080-875e-11eb-8a38-0a36dc721190.png)

We need to add another new option, called `Table of latest values`, which means, you still use the same query, but show the result as a table with 2 columns. Col-1 is the label name, col-2 is the latest value of the label. The latest value is the value in the last time slot.

**Comment by Fine0830** [comment]
Got it
