### ISSUE TITLE
Implement Neo4j client lib plugin

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6570]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

Q1. In our echosystem we have services which are keep on talking with Neo4j on some specified IP Port . The question is, In the Instance Client or Server tables why its IP and Port not been detected. Is there any specific reason. 

select  distinct  source_service_name,  dest_service_name  from  service_instance_relation_server_cpm;
+---------------------+----------------------------------------------------------+
| source_service_name | dest_service_name                                        |
+---------------------+----------------------------------------------------------+
| solutions.service   | x.x.x.x:5432                                             |
| core.service        | x.x.x.x:5671                                             |
+---------------------+----------------------------------------------------------+
No Neo4j port information

Q2. How we can know that particular server is of which technology like Postgres , RabbitMQ  ect. are we storing this information anywhere in database. 

Kindly suggest. 
Thanks and Regards,
Jayesh

![image](https://user-images.githubusercontent.com/75727262/111467068-0966e500-874a-11eb-9ac2-6b41b89619dc.png)

**Comment by wu-sheng** [comment]
Q1, it depends
1. Whether the node showing on the topology?
2. Whether the server has installed an agent?
If both are YES, then the IP:port most likely is in the `network_address_alias`. The topology includes the logic name once the mapping/alias detected by OAP.

Q2, you need to apply for an ID for the new component, https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/component-libraries.yml. Then use this component id in the new plugin. Then you could add the icon by using the name, like this, https://github.com/apache/skywalking-rocketbot-ui/pull/419/files

**Comment by JayeshMuley** [comment]
For Q1 : 
Neo4j node is not showing up in topology. There is no agent installed on neo4j server as well. 

But Postgres and RabbitMQ nodes are present in topology which are auto detected (no agent installed there as well).  So if Service is communicating with Neo4j IP than the Neo4j node should also be displayed and stored in instance client/server tables?

Kindly advice. 

Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
> For Q1 :
> Neo4j node is not showing up in topology. There is no agent installed on neo4j server as well.
> 
> But Postgres and RabbitMQ nodes are present in topology which are auto detected (no agent installed there as well). So if Service is communicating with Neo4j IP than the Neo4j node should also be displayed and stored in instance client/server tables?
> 
> Kindly advice.
> 
> Thanks and Regards,
> Jayesh Muley

Then, it is most likely, you need a plugin for Neo4j client library. That is how the other servers work.

**Comment by JayeshMuley** [comment]
Is it possible Skywalking detect all the IP and Ports a service communicated with and get stored in Instance Client/Server Relation tables. Irrespective of  available technology plugin. 

Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
They always will be detected by one plugin or another. Such as a plugin for the specific framework, or a plugin for the network level API.

**Comment by wallezhang** [comment]
@JayeshMuley Could you provide some information about server and client? E.g. server version, which client, and client version.

**Comment by wallezhang** [comment]
@wu-sheng Please assign to me, I will try to implement it.

**Comment by wu-sheng** [comment]
Done.

**Comment by wallezhang** [comment]
@wu-sheng I have a problem when writing scenario test. The client of Neo4j uses asynchronous implementation, so if the asynchronous process is executed quickly, then `createExitSpan` will be executed in the main thread, and a new trace segment will not be created. If the execution is slow, the `createExitSpan` method will be executed in the callback thread and a new trace segment will be created. So in the `expectedData.yaml` file, the expected trace segment and the span in the segment cannot be determined. Is there any good solution to this?

**Comment by wu-sheng** [comment]
OK, this would be very tricky. We usually expect you have certain segments. Because otherwise, the testing is meaningless.

**Comment by wallezhang** [comment]
OK, I tried another solution, which can create exit span in IO thread, but when actually setting tag, because the current span is in asynchronous mode, it cannot be set, however setting operation name is fine. I think the reason is because the `isInAsyncMode` condition is not judged in `org.apache.skywalking.apm.agent.core.context.trace.ExitSpan#tag()` method.

```java
    @Override
    public AbstractTracingSpan tag(AbstractTag<?> tag, String value) {
        if (stackDepth == 1 || tag.isCanOverwrite()) {
            super.tag(tag, value);
        }
        return this;
    }

    @Override
    public AbstractTracingSpan setOperationName(String operationName) {
        if (stackDepth == 1 || isInAsyncMode) {
            return super.setOperationName(operationName);
        } else {
            return this;
        }
    }
```

**Comment by wu-sheng** [comment]
Are you facing `stackDepth > 1`? Which means nested logic exit span?

**Comment by wallezhang** [comment]
No. The Neo4j client call processor are like these:

**Comment by wu-sheng** [comment]
Oh, you mean it has finished in the sync mode. Yes, you need to add `isInAsyncMode` check. Please submit a separate PR for this.

**Comment by wallezhang** [comment]
> Oh, you mean it has finished in the sync mode. Yes, you need to add `isInAsyncMode` check. Please submit a separate PR for this.

Yes, do I still need to create a new issue to associate this pr?

**Comment by wu-sheng** [comment]
> > Oh, you mean it has finished in the sync mode. Yes, you need to add `isInAsyncMode` check. Please submit a separate PR for this.
> 
> Yes, do I still need to create a new issue to associate this pr?

You don't have to. Writing the details in the pull request is fine.
