### ISSUE TITLE
alarm rule config

### ISSUE THREAD

**Issue by keylihai** [apache/skywalking#6578]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
we hava many services in our backend , and i can not use the default alarm rules config to all of our services,but the alarm config is in a yml file ，if i write all unique alarm rules into it,it will be very hard to manage.So i want to know if there are some ways to make is easy or skywalking can provide a web util to manage it.Thank you!

**Comment by kezhenxu94** [comment]
You can configure the alarm rules with dynamic configuration, for many popular configuration centers, there are web UI to configure the yaml, but if you're asking for non-yaml edit of the configuration, we don't have that
