### ISSUE TITLE
Play framework 2.8 support 

### ISSUE THREAD

**Issue by aamrute-idnow** [apache/skywalking#6581]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ :heavy_check_mark: ] Feature or performance improvement

___
### Question
- What do you want to know?
Plugin for play framework do not report data for play version 2.8 
___
### Bug
- Which version of SkyWalking, OS, and JRE?
 skywalking 8.4.0 (Pre built docker image apache/skywalking-oap-server:8.4.0-es7), play 2.8 + jdk 11 
 
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Our existing plugin tests are here, https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/play-scenario, including the 2.8. Maybe you used the framework in another way. Please recheck the test codes and compare them to yours.
