### ISSUE TITLE
Why the server-configuration module can only read one configMap resource in k8s?

### ISSUE THREAD

**Issue by panniyuyu** [apache/skywalking#6584]
### Question
 I found that only one configmap resource can be read, When i use configuration-k8s-configmap in server-configuration module.

In this reference:
org.apache.skywalking.oap.server.configuration.configmap.ConfigurationConfigmapInformer#doStartConfigMapInformer

and this part:
SharedIndexInformer<V1ConfigMap> configMapSharedIndexInformer = factory.sharedIndexInformerFor(
            params -> coreV1Api.listNamespacedConfigMapCall(
                settings.getNamespace(), null, null, null, null, settings.getLabelSelector()
                , 1, params.resourceVersion, 300, params.watch, null
            ),
            V1ConfigMap.class, V1ConfigMapList.class
        );

The parameter limit is fixed at 1. When I modify the parameter limit to null or 2, and i get a empty configmap.
I think that different types of configurations are often divided into multiple configmaps to save. 
What should i do?Looking forward your answer.

**Comment by wu-sheng** [comment]
No matter what style of k8s API says, we require all configurations in one setting with YAML format. As all other config centers did in the same way.

> The parameter limit is fixed at 1. When I modify the parameter limit to null or 2, and i get a empty configmap.

Back to this, I think this is not SkyWalking's responsibility. You are using k8s-client API directly. If you have any question, ask their community.

**Comment by panniyuyu** [comment]
In my scene, I want to save the alarm rules of different businesses in different configmaps. I can isolate the alarm rules of different businesses and facilitate management.In this way, we can isolate the alert rules of different businesses and facilitate management.In my opinion, this should be a more general requirement.

> No matter what style of k8s API says, we require all configurations in one setting with YAML format. As all other config centers did in the same way.
> 
> > The parameter limit is fixed at 1. When I modify the parameter limit to null or 2, and i get a empty configmap.
> 
> Back to this, I think this is not SkyWalking's responsibility. You are using k8s-client API directly. If you have any question, ask their community.

In my scene, I want to save the alarm rules of different businesses in different configmaps. In this way, we can isolate the alert rules of different businesses and facilitate management.In my opinion, this should be a more general requirement.

**Comment by wu-sheng** [comment]
> In my scene, I want to save the alarm rules of different businesses in different configmaps. I can isolate the alarm rules of different businesses and facilitate management.In this way, we can isolate the alert rules of different businesses and facilitate management.In my opinion, this should be a more general requirement.
> 
> > No matter what style of k8s API says, we require all configurations in one setting with YAML format. As all other config centers did in the same way.
> > > The parameter limit is fixed at 1. When I modify the parameter limit to null or 2, and i get a empty configmap.
> > 
> > 
> > Back to this, I think this is not SkyWalking's responsibility. You are using k8s-client API directly. If you have any question, ask their community.
> 
> In my scene, I want to save the alarm rules of different businesses in different configmaps. In this way, we can isolate the alert rules of different businesses and facilitate management.In my opinion, this should be a more general requirement.

Management is your concern, not community's.

**Comment by panniyuyu** [comment]
> > In my scene, I want to save the alarm rules of different businesses in different configmaps. I can isolate the alarm rules of different businesses and facilitate management.In this way, we can isolate the alert rules of different businesses and facilitate management.In my opinion, this should be a more general requirement.
> > > No matter what style of k8s API says, we require all configurations in one setting with YAML format. As all other config centers did in the same way.
> > > > The parameter limit is fixed at 1. When I modify the parameter limit to null or 2, and i get a empty configmap.
> > > 
> > > 
> > > Back to this, I think this is not SkyWalking's responsibility. You are using k8s-client API directly. If you have any question, ask their community.
> > 
> > 
> > In my scene, I want to save the alarm rules of different businesses in different configmaps. In this way, we can isolate the alert rules of different businesses and facilitate management.In my opinion, this should be a more general requirement.
> 
> Management is your concern, not community's.

I will think of another way, thank you for your answer.Thanks♪(･ω･)ﾉ
