### ISSUE TITLE
The startup duration increases.

### ISSUE THREAD

**Issue by JHub-Wei** [apache/skywalking#6585]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ * ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
After the service in k8s is integrated with the agent, the service startup time increases. For example, the service takes about 40 seconds to start before. After integration, the service takes about 80 seconds, which is twice as slow.
What's the reason for this? Is there any solution? Thank you.
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We can't see your codes, so, it is impossible to locate this kind of issue. You need to measure which parts of the process take those time.

**Comment by JHub-Wei** [comment]
But almost all integrated services have this phenomenon...

**Comment by wu-sheng** [comment]
All or one, this is not the thing we could know or fix. Please understand how the open-source works. You are a part of the community, we need you to do the research. You just shared with us a scenario/case, we can't randomly guess why, this is pointless.
We don't say this is or isn't an issue, the key is, we can't tell the details.

**Comment by JHub-Wei** [comment]
OK, thx.
