### ISSUE TITLE
view logs bug

### ISSUE THREAD

**Issue by haoyanbing** [apache/skywalking#6586]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.4.0
- Which company or project?

- What happened?
在 trace 界面，点击 相关的日志，显示出的日志是不全的，但是用traceid 作为条件查询，能查询到完整的日志。

**Comment by wu-sheng** [comment]
Please use English on GitHub. And your description shows little useful information. Check the database, check GraphQL requests.

**Comment by haoyanbing** [comment]
![image](https://user-images.githubusercontent.com/20509387/111757772-a6568900-88d6-11eb-85fc-374cbbf70e30.png)
 
this is the request param，only show 10 logs，but the log is not only 10，
![image](https://user-images.githubusercontent.com/20509387/111758035-f46b8c80-88d6-11eb-996d-54ebe1b829cc.png)
But can not change the page no

**Comment by haoyanbing** [comment]
@wu-sheng

**Comment by wu-sheng** [comment]
Read the pull requests and changes.md in the master branch. It has been fixed.

**Comment by haoyanbing** [comment]
ok，thank you
