### ISSUE TITLE
skywalking agent grpc report issues

### ISSUE THREAD

**Issue by YczYanchengzhe** [apache/skywalking#6589]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When I use the agent, I found that the yoyu class cannot find all the agent-side grpc always fails to start. What is the possible reason?
___
### Bug
- Which version of SkyWalking, OS, and JRE?
OS ： mac m1
skywalking 8.4
jre jdk1.8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/45945752/111861203-6dc2b800-8987-11eb-9958-442438dc5581.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is not our official package. We test agenta of every commit and tag.
