### ISSUE TITLE
count in alarm rules

### ISSUE THREAD

**Issue by keylihai** [apache/skywalking#6594]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
i want to know what dose count means in alarm rules config? The offical doc explain it to time period, but i find it seems to be the count number  of reaching the threshhold
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by keylihai** [comment]
![image](https://user-images.githubusercontent.com/11571589/111953030-00e32580-8b21-11eb-8268-69f23b165206.png)

**Comment by keylihai** [comment]
default example:
![image](https://user-images.githubusercontent.com/11571589/111953165-37b93b80-8b21-11eb-915e-ee70095610de.png)

**Comment by wu-sheng** [comment]
Check the period of the timer running.
