### ISSUE TITLE
protocol issue

### ISSUE THREAD

**Issue by haisheng666** [apache/skywalking#6595]
ModuleNotFoundError: No module named 'skywalking.protocol'
Run your simplest demo report this error, please help solve it

**Comment by wu-sheng** [comment]
What agent do you mean?

**Comment by haisheng666** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        If you want to try out the latest features that are not released yet, please refer to the guide to build from sources.from skywalking import agent, config

config.init(collector='127.0.0.1:11800', service='your awesome service')
agent.start()
            
        
    
    
        
            I directly run your test scripts have problems, after checking, the installed package does not contain common protocol, please have a look
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                QQ邮箱1
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 3/22/2021 16:54，吴晟 Wu ***@***.***> wrote： 



What agent do you mean?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wu-sheng** [comment]
No detail provided. If you want to submit issue, please pay more attention on how the community works.

**Comment by haisheng666** [comment]
skywalking import agent, config

config.init(collector='127.0.0.1:11800', service='your awesome service')
agent.start()
![issue1](https://user-images.githubusercontent.com/42937758/111984637-9644e080-8b46-11eb-839d-fa705c429931.png)

I directly run your test scripts have problems, after checking, the installed package does not contain common protocol, please have a look

**Comment by kezhenxu94** [comment]
@haisheng666 if you want to build from the source codes, MAKE SURE to follow every single step of the doc, from the error codes, I suspect that you didn't run `git submodule update --init`

**Comment by haisheng666** [comment]
I installed it by PIP. What should I do?

**Comment by kezhenxu94** [comment]
@haisheng666 please, learn how to ask question and communicate efficiently, how exactly did you install the agent, one of your comment said you installed from source codes, northern other one said you install from pip, please describe you question completely at one time, and provide the full steps to reproduce your issue

**Comment by haisheng666** [comment]
When did I say I installed the source code? I just asked you whether the PIP installation module can be used, and whether the basic demo can be used, right?

**Comment by kezhenxu94** [comment]
The PIP module can be used, the basic demo can be used

**Comment by haisheng666** [comment]
I've tried, PIP install "Apache skywalking" is not very easy to use, and I can't find the corresponding module after installation, but PIP install Apache skywalking = = 0.5.0 can be used, and the module can be used normally. Finally, thank you for your open source module!

**Comment by haisheng666** [comment]
I want to know in "alarm"- settings.yml ”In this file, except for the {name} variable, where can I query other variables? For example, the endpoint name，thank you！
![sky报警变量](https://user-images.githubusercontent.com/42937758/112242240-6866b580-8c86-11eb-99ce-fc395916adfe.png)

**Comment by kezhenxu94** [comment]
> I want to know in "alarm"- settings.yml ”In this file, except for the {name} variable, where can I query other variables? For example, the endpoint name，thank you！
> ![sky报警变量](https://user-images.githubusercontent.com/42937758/112242240-6866b580-8c86-11eb-99ce-fc395916adfe.png)

Only name and id are supported for now, but it should be easy to extend, https://github.com/apache/skywalking/blob/2c729b5d69b095962e7be5b8570eedc374659ec5/oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/AlarmMessageFormatter.java please try to contribute if you need a new feature.

**Comment by kezhenxu94** [comment]
Also, let’s focus on one case per issue and open another issue for a different case next time, so that we don’t mix the context here :)

**Comment by haisheng666** [comment]
![image](https://user-images.githubusercontent.com/42937758/115354186-ecf81580-a1eb-11eb-9492-b096243dfb5d.png)
Do you have any other parameters besides these alarm parameters? For example, the endpoint name
![image](https://user-images.githubusercontent.com/42937758/115354334-19ac2d00-a1ec-11eb-91a6-6fd274027c6e.png)

**Comment by haisheng666** [comment]
![image](https://user-images.githubusercontent.com/42937758/115810942-69276e80-a421-11eb-8f1a-80a9a717f263.png)
![image](https://user-images.githubusercontent.com/42937758/115810964-72b0d680-a421-11eb-9a20-f4bec11acb76.png)
Please have time to answer me!

**Comment by wu-sheng** [comment]
Why a service level alarm including an endpoint name? What do you mean?

**Comment by haisheng666** [comment]
I mean, can the alarm parameters received by webhook include the endpoint name? Now there is no such parameter
![image](https://user-images.githubusercontent.com/42937758/115829994-40fc3780-a442-11eb-8f41-de9bcb237902.png)

**Comment by wu-sheng** [comment]
Again, there is no such thing. Why are you keeping asking?

**Comment by haisheng666** [comment]
Don't you know what that means? So I answer you?

I asked if I could add this parameter? Just answer yes or no

**Comment by haisheng666** [comment]
Aren't you community defenders? Who do you ask?

**Comment by wu-sheng** [comment]
I have given you the answer. I don't know how to give an answer.

> Why a service level alarm including an endpoint name?

If you set an endpoint level alarm, then it has an endpoint name, otherwise, how could it be included?
That is why I am asking you, your question doesn't make sense at all.
