### ISSUE TITLE
Cant find graph on skywalking UI for play framework

### ISSUE THREAD

**Issue by aamrute-idnow** [apache/skywalking#6599]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I am try to skywalking with my application in play 2.8 framework with jdk 11. But I could get matrix data in  UI, where I could service name and intense field populated correctly. I also tried test example "play-scenario"  (started test application with SBT command passing javaagent detail at command line", it has the same behavior, in UI instance and service name shown correctly but matrix data and endpoint details are missing. 
___
### Bug
- Which version of SkyWalking, OS, and JRE?
Current Master on linux version (skaywalking locally build and created docker images)

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
Start play-scenario application from test section using SBT command 
`sbt -J-javaagent:/skywalking/skywalking-agent/skywalking-agent.jar testProd`

for agent config setup I follow below two instruction

- Set agent.service_name in config/agent.config. Could be any String in English.
- Set collector.backend_service in config/agent.config. Default point to 127.0.0.1:11800, only works for local backend

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Play component has been defined, https://github.com/apache/skywalking/blob/fdab7f06a11b9ce45ac0d9ba31061fc16bda2921/oap-server/server-bootstrap/src/main/resources/component-libraries.yml#L236.

`PLAY` icon should be added here, https://github.com/apache/skywalking-rocketbot-ui/tree/master/src/views/components/topology/assets

Take this PR as a reference.

**Comment by aamrute-idnow** [comment]
Issue with application starting with SBT, if play application start with `sbt run` or `sbt testProd`, agent could not send data to backend because of below exception, which is caused by extension class loader.

`Caused by: java.lang.ClassNotFoundException: Can't find org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstanceConstructorInterceptor`

As explained in https://github.com/apache/skywalking/issues/5242#issuecomment-671032068 extension class loader not support yet,

In order to fix the issue, run play application in production mode (https://www.playframework.com/documentation/2.8.x/Deploying).

Step 1 : Run on play project  `sbt dist`. It will create zip file in `target/universal/my-first-app-1.0.zip` folder.
Step 2 : `unzip my-first-app-1.0.zip`
Step 3: run `bin/my-first-app` from terminal with `-javaagent` arg.
`bin/my-first-app -J-javaagent:/home/aamrute/work/tool/skywalking/8.5.0-es7/apache-skywalking-apm-bin-es7/agent/skywalking-agent.jar=agent.service_name=your_application_name`
