### ISSUE TITLE
Feature Log combined with alarm for webhook？

### ISSUE THREAD

**Issue by colincatsu** [apache/skywalking#6600]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

- Please describe your requirements or improvement suggestions.
Feature Log combined with alarm for webhook ，i want one feature,webhook alarm log details

**Comment by wu-sheng** [comment]
I am not following what do you mean. What is `Feature Log combined`?
