### ISSUE TITLE
Does skywalking provide an open API？

### ISSUE THREAD

**Issue by FangPengbo** [apache/skywalking#6601]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Feature or performance improvement

___
### Question

Does skywalking provide an open API？

___

 Which version of SkyWalking, OS, and JRE?
8.1
___
### Requirement or improvement
I want to get skywalking data through code,
We use es storage. Is there any way to get it?

Please help me
thank you

**Comment by wu-sheng** [comment]
You could start from here, https://skywalking.apache.org/docs/main/v8.4.0/en/protocols/query-protocol/.

**Comment by FangPengbo** [comment]
> You could start from here, https://skywalking.apache.org/docs/main/v8.4.0/en/protocols/query-protocol/.

We use HTTP to request,
But there seems to be a problem.
`
{"data":{},"errors":[{"message":"Exception while fetching data (/data) : entity content is too long [105138986] for the configured buffer limit [104857600]"}]}
`

**Comment by wu-sheng** [comment]
Learn graphql, which is a widely used protocol.

**Comment by FangPengbo** [comment]
> Learn graphql, which is a widely used protocol.

It uses grapql to query,
However, the amount of data seems to be very large. Es threw an error when querying
Can this buffer area be configured?
Can I use resthighlevelclient to query by myself?

`
{"data":{},"errors":[{"message":"Exception while fetching data (/data) : entity content is too long [105138986] for the configured buffer limit [104857600]"}]}
`

**Comment by wu-sheng** [comment]
I am not sure what you are doing. If you want to query ES directly, you could do anything you want.

**Comment by FangPengbo** [comment]
> I am not sure what you are doing. If you want to query ES directly, you could do anything you want.

thank you

**Comment by FangPengbo** [comment]
> I am not sure what you are doing. If you want to query ES directly, you could do anything you want.

"data_binary" : "CjYzZWRmOTM0NDUyZmQ0ZjdjOTY1NDExYmJjZjMyYWRlMS4zMTAuMTYxNjYwNTkxODc0OTQwNTESNjNlZGY5MzQ0NTJmZDRmN2M5NjU0MTFiYmNmMzJhZGUxLjMxMC4xNjE2NjA1OTE4NzQ5NDA1MBpREP///////////wEYneziqYYvIJ3s4qmGLzIbRWhjYWNoZS9nZXQvcGxhbkRlZmluZUNhY2hlQAJIBVBLYhMKDGRiLnN0YXRlbWVudBIDSDA5Ig9ub25tb3RvcmpvYi11YXQqIW5vbm1vdG9yam9iLTIwMjEwMzI1LTAxMDcwNC1uaDRtag=="

Hi,

I got this data from ES,
How to get the specific content?
