### ISSUE TITLE
Loop alarm into event system.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6604]
Considering today's event system, we could make triggered alarm back into SkyWalking OAP as a one-time event, which makes us finally could visualize the alarm back into the dashboard.

@kezhenxu94 Does this make sense to you?

**Comment by kezhenxu94** [comment]
@chenmudu will work on this, if you have any question, feel free to ask here.

**Comment by wu-sheng** [comment]
OK, as this has been changed to a new contributor assignment, I am removing this from 8.5.0 milestone.

**Comment by chenmudu** [comment]
Yeah, I think I can try. 😀
