### ISSUE TITLE
Browser error logs not captured by skywalking-client-js agent for Angular apps

### ISSUE THREAD

**Issue by Debanjan05** [apache/skywalking#6607]
- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS, and JRE?

Skywalking 8.2
skywalking-client-js - v0.4.0
OS - Mac
Angular app version - 11

- What happened?
I'm trying to test an angular app with the agent - I'm able to register the app and get performance data and app load. But browser error logs which I'm generating in the app are not captured by the agent and hence not pushed to the collector.
I'm able to connect and send browser error logs for Vue and React apps with the same agent. 

This is what I'm doing to register and send the data in main.ts file of the angular app - 

_ClientMonitor.register({
  collector:
    'http://localhost:12800',
  service: 'angular-test',
  pagePath: location.href,
  serviceVersion: 'v1.0.0',
  jsErrors: true,
  apiErrors: true,
  resourceErrors: true,
  enableSPA: true,
  useFmp: true,
  autoTracePerf: true,
  detailMode: true,
});_ 

I don't see any network calls happening to collector endpoint when any error is triggered from the angular application.
Presently for testing purpose I'm just throwing an error on some button click - _throw new EvalError("EvalError");_

Please let me know if this is a bug or I'm missing something on the configuration part.

**Comment by Fine0830** [comment]
@Debanjan05 Here is a Angular demo with skywalking-client-js. https://github.com/Fine0830/angular-demo/blob/master/src/app/home/home.component.ts

**Comment by Fine0830** [comment]
For https://the-asf.slack.com/archives/CHQ1L4T54/p1616746142035800?thread_ts=1614298078.005500&cid=CHQ1L4T54,  I plan to implement a manual report function to handle frames `errorHandler`. Meanwhile the issue will be solved.

**Comment by wu-sheng** [comment]
> For https://the-asf.slack.com/archives/CHQ1L4T54/p1616746142035800?thread_ts=1614298078.005500&cid=CHQ1L4T54, I plan to implement a manual report function to handle frames `errorHandler`. Meanwhile the issue will be solved.

Doesn't `error` handler of Angular have a unified place to intercept?

**Comment by Fine0830** [comment]
Yes, it does. I sorted out the interceptors of the framework, including React, Angular, Vue. 
Here's how to use error handler in projects,
<img width="578" alt="1" src="https://user-images.githubusercontent.com/20871783/113690070-9bd12780-96fd-11eb-9250-09a32a6505b7.png">

From my point, No matter which framework, we just implement `logErrorToSWClientJs` in skywalking-client-js.

**Comment by Debanjan05** [comment]
Hi @Fine0830 What is the logErrorToSWClientJS(error) implementation? Where have you implememented this?

**Comment by wu-sheng** [comment]
> Hi @Fine0830 What is the logErrorToSWClientJS(error) implementation? Where have you implememented this?

We haven't released that version yet. It is on the main branch or next 0.5.0 release.

**Comment by Debanjan05** [comment]
Thanks @wu-sheng. Any tentative time or date for the release of 0.5.0 release?

**Comment by bee-cult** [comment]
Any update on 0.5.0 release?

**Comment by wu-sheng** [comment]
We need a 0.5.1, `0.5.0` faces an issue in the release process. 0.5.1 is on the way.

**Comment by bee-cult** [comment]
Any timeline of 0.5.1 ?

**Comment by wu-sheng** [comment]
Learn to subscribe to the mail list. Official release happens there.
