### ISSUE TITLE
skywalking thread context transfer？

### ISSUE THREAD

**Issue by lorgine** [apache/skywalking#6610]
when i deep into skywalking code？ i hava a issue? why just capture context,and not capture `runtimecontext?`

```
public class ThreadingConstructorInterceptor implements InstanceConstructorInterceptor {

    @Override
    public void onConstruct(final EnhancedInstance objInst, final Object[] allArguments) {
        if (ContextManager.isActive()) {      
            objInst.setSkyWalkingDynamicField(ContextManager.capture());     
        }
    }
}
```

and in the method 
ContextManager.getRuntimeContext().capture()
this method just capture the default key context?

```
public class RuntimeContextConfiguration {
    public static String[] NEED_PROPAGATE_CONTEXT_KEY = new String[] {
        "SW_REQUEST",
        "SW_RESPONSE",
        "SW_WEBFLUX_REQUEST_KEY"
    };
}
```
```
public RuntimeContextSnapshot capture() {
        Map<Object, Object> runtimeContextMap = new HashMap<>();
        for (String key : RuntimeContextConfiguration.NEED_PROPAGATE_CONTEXT_KEY) {
            Object value = this.get(key);
            if (value != null) {
                runtimeContextMap.put(key, value);
            }
        }
        return new RuntimeContextSnapshot(runtimeContextMap);
    }
```

can you give some sugustion?

**Comment by wu-sheng** [comment]
I think you are not asking questions from the right point. The community is impossible to explain all codes of all cases, those are your responsibility. If you want some questions and new cases, we could focus on that.
Otherwise, the people of the community are going to face endless source code questions.

**Comment by lorgine** [comment]
my scenario is i just want to transfer some data into thread,but i don't want to transfef these data cross transfer like http? and i can do what?

**Comment by lorgine** [comment]
my scenario is i just want to transfer some context data into thread,but i don't want to transfef these data cross transfer like http? and i can do what?

**Comment by wu-sheng** [comment]
Are you talking about an upstream plugin or some private codes?

**Comment by lorgine** [comment]
i need to devlop second times. and i want to transfer context into thread。i found it is wrong. and specialy sometimes i want to transfer object into thread. depend on source code,i found i need to change source code,and the orgin code has no this fuction, so i want to ask this scenario is right?

**Comment by lorgine** [comment]
i need to devlop sky second times. and i want to transfer some object context into thread。by default, i cant't do this. depend on source code,if i want to realize this function, i need to change source code, so i want to ask this scenario is right?

**Comment by wu-sheng** [comment]
From the current codebase, yes, this is not allowed to extend without changing codes. And to be honest, a private version is hard to judge, so, it is hard to discuss features of a private version.

**Comment by lorgine** [comment]
in next version, it will add this function?

**Comment by wu-sheng** [comment]
I have said very clearly, unless you open source your case/code, this discussion is hard to keep.

**Comment by lorgine** [comment]
ok, I will open my code later.
