### ISSUE TITLE
[BUG] helm installation fails when using H2 database

### ISSUE THREAD

**Issue by mritd** [apache/skywalking#6611]
> Please answer these questions before submitting your issue.

### Why do you submit this issue?

- [x] Bug

___
#### Which version of SkyWalking, OS, and JRE?

Skywalking Version: `v8.4.0`
Kubernetes Version: `v1.20.4`
Helm Version: `v3.5.2`

#### Which company or project?

For testing project

#### What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

helm installation fails when using H2 database.

#### Steps to reproduce:

- Clone `skywalking-kubernetes` repo
- Follow the official documentation to update the helm repo
- Set storageType to H2 database installation

**Please see the screenshot for the complete operation command:**
![image](https://user-images.githubusercontent.com/13043245/112255289-d8803600-8c9c-11eb-852b-c5a1e8e64482.png)

**Comment by kezhenxu94** [comment]
@mritd if you want to deploy skywalking-kubernetes with h2 storage, please refer to [this](https://skywalking.apache.org/blog/2020-12-03-obs-service-mesh-with-sw-and-als/#deploying-apache-skywalking), there are other extra option to specify (such as disable es, starting OAP in init  mode, etc.)

**Comment by mritd** [comment]
@wu-sheng @kezhenxu94 Please reopen this issue.

After reviewing the code, a bug was introduced in recent https://github.com/apache/skywalking-kubernetes/commit/31898203dceba00550cf78eb5ce979efea562587 commit:

"volumeMounts" and other options were not included in the `{{- if hasPrefix "elasticsearch" .Values.oap.storageType }}` check, which would lead to use Installation of other storage backends failed.

```diff
{{- if hasPrefix "elasticsearch" .Values.oap.storageType }}
apiVersion: batch/v1
kind: Job
metadata:
.......
        {{- range $key, $value :=  .Values.oap.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
{{- end}}
+        volumeMounts:
+          {{- if (.Files.Glob "files/conf.d/oap/**") }}
+            {{ range $path, $bytes := .Files.Glob "files/conf.d/oap/**" }}
+            - name: skywalking-oap-override
+              mountPath: {{ print "/skywalking/config/" ($path | replace "files/conf.d/oap/" "") }}
+              subPath: {{ $path | replace "files/conf.d/oap/" "" | b64enc | replace "=" "-" }}
+            {{- end }}
+            {{- end }}
+      volumes:
+        {{- if (.Files.Glob "files/conf.d/oap/**") }}
+        - name: skywalking-oap-override
+          configMap:
+            name: {{ template "skywalking.fullname" . }}-oap-cm-override
+        {{- end }}
```
