### ISSUE TITLE
Service log time is not formatted correctly

### ISSUE THREAD

**Issue by liqiangz** [apache/skywalking#6612]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
  v8.4.0
- Which company or project?
  
- What happened?
Service log is not formatted correctly. The returned timestamp is a string type, it should need `parseInt(currentLog[item.label])`

![image](https://user-images.githubusercontent.com/16935891/112264540-015bf780-8cac-11eb-82ae-df19200bdd09.png)

![image](https://user-images.githubusercontent.com/16935891/112264205-7c70de00-8cab-11eb-860c-e69e8cefc53d.png)

![image](https://user-images.githubusercontent.com/16935891/112263928-040a1d00-8cab-11eb-8ad0-5da846ae0cd7.png)

**Comment by kezhenxu94** [comment]
Please search before opening a new issue, this problem has been addressed and fixed in the master branch.
