### ISSUE TITLE
Skywalking-agent is plan to support collect trace for weblogic

### ISSUE THREAD

**Issue by scorus916** [apache/skywalking#6616]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

### Question
Skywalking-agent now is support collect trace for weblogic，if not , have plan to support ?

**Comment by wu-sheng** [comment]
First of all, weblogic is a commercial product, decompiling source codes is not recommended(or allowed) in the ASF. But from tech perspective, if you are using Spring/Structs, you don't need a plugin for that.
