### ISSUE TITLE
why createIndex in HistoryDeleteEsDAO#deleteHistory?

### ISSUE THREAD

**Issue by system-designer** [apache/skywalking#6618]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- why createIndex in HistoryDeleteEsDAO#deleteHistory?
When chosing elasticsearch as oap-server's storage, DataTTLKeeperTimer executes HistoryDeleteEsDAO#deleteHistory every 5(default) minutes to delete expired timeseries index, this may cause heavy perfomance loss. Thus I try to set enableDataKeeperExecutor=false to disable DataTTLKeeperTimer and set index ttl on es cluster, but new index will not be created. This is because new index is only created in HistoryDeleteEsDAO#deleteHistory and in oap-server bootstrap.
I wonder why not seperate deleteHistory and createIndex into two timers, DataTTLKeeperTimer takes responsibility for delete expired index, and a new Timer takes in charge of creating new index in elasticsearch.

**Comment by wu-sheng** [comment]
If you have the data on a new day, a new index will be created. I am not sure how you tested this, but the index creation is not only TTL timer's responsibility
