### ISSUE TITLE
Skywalking UI failed through NGINX reverse proxy

### ISSUE THREAD

**Issue by Maijh97** [apache/skywalking#6621]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can the Skywalking UI make reverse proxy requests through NGINX? So far, it seems not.

nginx config:
`        
         location /skywalking/ {
            proxy_pass http://xx.xx.xx.xx:8080/;
        }
`
curl http://xx.xx.xx.xx/skywalking/,
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Your proxy, your responsibility. We don't provide that.

**Comment by Maijh97** [comment]
@wu-sheng  I found out that this wasn't a proxy issue because I did curl http://localhost:8080/ on the server where the Skywalking UI was running and I got something like:   
`<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><link rel=icon href=/favicon.ico><title>SkyWalking</title><link href=/css/app.bba62f2d.css rel=preload as=style><link href=/js/app.4761da87.js rel=preload as=script><link href=/js/chunk-vendors.8c1cbdce.js rel=preload as=script><link href=/css/app.bba62f2d.css rel=stylesheet></head><body><noscript><strong>We're sorry but SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script src=/js/chunk-vendors.8c1cbdce.js></script><script src=/js/app.4761da87.js></script></body></html>`
However, a review of the logs shows that the Skywalking service is working.
