### ISSUE TITLE
A few questions about the use of skywalking and data storage

### ISSUE THREAD

**Issue by eltonbfw** [apache/skywalking#6633]
### Why do you submit this issue?
- [x] Question or discussion

___
### Question
- Can a single OAP be shared by multiple microservice clusters of different businesses? If yes, what do I need to do?
- Can one OAP be shared by different microservice clusters of the same business, e.g. dev, test, beta? If so, what do I need to do?
- What is the concept of service group and how to use it?
- If OAP cannot be shared across multiple business microservice clusters, can it share an elasticsearch cluster? Can multiple OAPs all write data to this es cluster and be able to properly distinguish between queries and writes?

**Comment by wu-sheng** [comment]
1. dev, test, prod shouldn't share APM. We don't recommend to do that.
2. Group is a logic concept for different levels services. Such as VM service and agent-based business service.
3. You could use namespace to share the ES cluster.

**Comment by eltonbfw** [comment]
> 2. Group is a logic concept for different levels services. Such as VM service and agent-based business service.
How do I use service groups or can you tell me where the documentation is located?

> 3. You could use namespace to share the ES cluster.
I am using helm installation, how to specify namespace
