### ISSUE TITLE
Can the `_Id` of ES be used for storage, but not `traceId`?

### ISSUE THREAD

**Issue by HarryFQ** [apache/skywalking#6636]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
In storage-elasticesearch7-plugin, the stored ‘_id’ is the same as ‘trace_id’, but this will affect the ES storage performance. Can I not specify the ‘_id’ when storing and use the ID generated by ES?

- What happened?
Es uses traceId every time it is stored, then Es internally checks whether this Id is duplicated, which has a certain impact on performance.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
id is not traceid.

**Comment by HarryFQ** [comment]
> id is not traceid.
Yes, but ‘_id’ and ‘trace_id’ are not the same value, it’s like this
"'_id': 'a8962ebdac6a4a37b962b14f88520a5c.217.16169798504166384','trace_id': 'a8962ebdac6a4a37b962b14f88520a5c.217.16169798504166385'". But'_id' is also generated when skywalking is inserted? Is it possible not to generate it and let ES generate it by itself?
