### ISSUE TITLE
PersistenceTimer Performance cause full GC frequent

### ISSUE THREAD

**Issue by xuanyu66** [apache/skywalking#6639]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement

___
### Requirement or improvement
- We face full gc issue lately，I dump the heap and found that PersistenceTimer occupied most of heap memory
![image](https://user-images.githubusercontent.com/17768378/112794457-7a3ac500-9099-11eb-8414-24ade8a38c22.png)
- I looked into code, found that PersistenceTimer use one thread persistence Metrics synchronously and periodically（5s）
- When peak traffic arrives, persistence time explode sharply and next persistence will delay (scheduleWithFixedDelay), which cause Metrics increase next time. It is vicious circle.
![image](https://user-images.githubusercontent.com/17768378/112795248-d6eaaf80-909a-11eb-94bf-91bca1fc07ad.png)
- I want to konw, why metrics need to persist synchronously, can we just persist like record

**Comment by wu-sheng** [comment]
Read #6472
