### ISSUE TITLE
apm-toolkit-trace: @Trace, @Tag and @Tags do not work for static methods

### ISSUE THREAD

**Issue by yaojingguo** [apache/skywalking#6640]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
I added `Trace` annotation to a static method. The result shows that `Trace` annotation does not work for static methods. A browse of `apm-toolkit-trace-activiation` module shows that `TagAnnotationActivation` and `TraceAnnotationActivation` only do method interception for static methods.

Does this work as designed? If not, I am willing to add support for static methods.

**Comment by wu-sheng** [comment]
They are a little different. As static methods, you can access this reference.

**Comment by yaojingguo** [comment]
I don't quite get your point. Could you give some explanation of `this referenece`?

**Comment by wu-sheng** [comment]
You could tag a value of the instance field, but can't do in static method.If we want to support static methods, we need things like traceStatic

**Comment by liqiangz** [comment]
Let me hava a try.
