### ISSUE TITLE
How can i config collector.backend_service to use HTTP protocol?

### ISSUE THREAD

**Issue by goooogs** [apache/skywalking#6643]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want to use HTTP protocol (12800) to communicate with OAP Service in AGENT, but it seems only support GRPC protocol? like this:
```
SW_AGENT_COLLECTOR_BACKEND_SERVICES=my-oap-service:12800
```

**Comment by wu-sheng** [comment]
Java agent doesn't support HTTP protocol, and it is not recommended.
