### ISSUE TITLE
which is the alarm rule config file in the new version?

### ISSUE THREAD

**Issue by ProLayman09** [apache/skywalking#6644]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
I clone the project of latest version（2021.03.25）and plan to set alarm rule for my services. But when I look for guide about alarm rule in *docs/en/setup/backend/backend-alarm.md* or other tutorials（official or not，e.g. [Alarm](https://skyapm.github.io/document-cn-translation-of-skywalking/zh/8.0.0/setup/backend/backend-alarm.html)） ，*config/ Alarm -settings.yml*  is always mentioned. But Obviously, there isn't *config/ Alarm -settings.yml* within the project. *dist-material/alarm-settings.yml* and *oap-server/server-bootstrap/src/main/resources/alarm-settings.yml* are found instead(except *oap-server/server-alarm-plugin/src/test/resources/alarm-settings.yml*)  
So it's due to the version? In the old version the config file is in the dir *config* but changed now, while the docs haven't been updated yet.
If so, which config file should I take to bring in Alarm rule?
Much confused!

**Comment by wu-sheng** [comment]
The document is about the dist, rather than source codes. 
You should package the source to get the tar, then, the doc mentioned things are there.

**Comment by ProLayman09** [comment]
Thx a lot!
By the way，I notice that skywalking calls webhooks .i.e. another application, to process alarm message. But sometimes I want do some pre-work first, such as data filtering, adding params .etc. before calling the webhooks. Are there any solutions for the scenario?

**Comment by ProLayman09** [comment]
okay...I see，by customing WebhookCallback$doAlarm.
Thanks anyway!
