### ISSUE TITLE
Why VNode's traceId is the same?

### ISSUE THREAD

**Issue by fomeiherz** [apache/skywalking#6645]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
Today, I found traceId: 7b9b5c6f5fc14027a5d5022c2b1ce760.42.16110695962920005  has too many. And It appears in VNode Endpoint. Why?
![image](https://user-images.githubusercontent.com/8408589/112830162-bf282100-90c4-11eb-85e0-699394310320.png)

**Comment by wu-sheng** [comment]
Read FAQ. VNode is not real data.
