### ISSUE TITLE
Envoy ALS mx-mesh should resolve service name from another position

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#6647]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
___
### Requirement or improvement
Since Istio injects ` service.istio.io/canonical-name` to the pod as the service name, OAP Envoy receiver should update `https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/metadata-service-mapping.yaml` to replace `LABELS.app` with this canonical label.

**Comment by wu-sheng** [comment]
Is this another key in the identify?
