### ISSUE TITLE
Exception was happened  when upgrade the jdbc.Drvier to 8.0.23 

### ISSUE THREAD

**Issue by githubcheng2978** [apache/skywalking#6652]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
StringIndexOutOfBoundsException  was happened  when upgrade the jdbc.Drvier to 8.0.23 
___
### Bug
- Which version of SkyWalking, OS, and JRE?
![image](https://user-images.githubusercontent.com/22095448/112850307-754b3500-90dc-11eb-83c5-ce227fefe7df.png)

version: 8.3.0
os:linux
jre:1.8

- Which company or project?

springboot

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
StringIndexOutOfBoundsException  was happened  when upgrade the jdbc.Drvier to 8.0.23 
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Seems your way of JDBC config is not supported. Read the codes, should be easy to find out why.

**Comment by githubcheng2978** [comment]
when i rollback the version 5.1.41.  there was no exceptions
