### ISSUE TITLE
How trace query paging implemented?

### ISSUE THREAD

**Issue by elvislou** [apache/skywalking#6653]
Hi guys,

I have a question with Skywalking trace query paging implementation.

as we know, the trace was stored as segment in elasticsearch,

and as I saw in the code, the trace query paging was with the segment index,

but I can see the trace was grouped by trace id in the fronted, 

how was this implemented? or am i missing something? please help, thanks.

**Comment by wu-sheng** [comment]
We don't explain codes. This is not community responsibility.
