### ISSUE TITLE
 web ui SelfObservability page display problem

### ISSUE THREAD

**Issue by DeadLion** [apache/skywalking#6656]
- [x] Bug

### Bug
SkyWalking 8.4.0

- What happened?
 web ui SelfObservability page  met problem

![image](https://user-images.githubusercontent.com/2594907/112951319-cd7e4780-916d-11eb-9aa2-71cdb3353db8.png)

two same group

![image](https://user-images.githubusercontent.com/2594907/112951463-f6064180-916d-11eb-9e6c-fcae2698068b.png)

two vm ,  two instances  each vm , so total 4 instances, before everything is ok, until yesterday  i got 8 instance (oap_server 
 no restart), i try to clean the chrome local cache , it doesn't work.

**Comment by wu-sheng** [comment]
Read old issues about why duplicated service or instance existing.
