### ISSUE TITLE
how to create a service group?

### ISSUE THREAD

**Issue by ligerman33** [apache/skywalking#6659]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
how to create a service group in the dashboard page, please have a look at the pic below:

<img width="374" alt="微信截图_20210331111620" src="https://user-images.githubusercontent.com/30819702/113085618-c2c9be00-9212-11eb-9457-ad4d6aace458.png">

oap and ui : 8.4.0
i am using java client, and i did not find config items in agent.config, plz...

**Comment by wu-sheng** [comment]
Read the agent set up doc. This is only a naming rule. Nothing to create.
