### ISSUE TITLE
Startup performance after the agent is integrated

### ISSUE THREAD

**Issue by JHub-Wei** [apache/skywalking#6661]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ * ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
If the service is not integrated with the agent, it takes 30 seconds to start the service. After the integration, it takes 50 seconds to start the service.In the same case, when the pinpoint agent is used, the startup time is increased by only 3s.
Why does the startup time increase so much after the Skywalking agent is integrated? Is there any optimization in the future?thx.
___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.4.0，k8s，1.8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We can't answer this question, if you like pinpoint, go ahead. We have friends there.
This is not a competition.
