### ISSUE TITLE
OAL disable statement doesn't work

### ISSUE THREAD

**Issue by nisiyong** [apache/skywalking#6662]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.4.0

#### What happened?

As the [document](https://skywalking.apache.org/docs/main/v8.4.0/en/concepts-and-designs/oal/#disable) said, 
> disable statement is designed for make them de-active, such as segment, top_n_database_statement.

I disabled some metrics in the oal files, but the ES indies are still created when I boot OAP with init-mode. There are the disable statements in oal files.
```bash
disable(browser_error_log);
disable(zipkin_span);
disable(jaeger_span);
disable(profile_task);
disable(profile_task_log);
disable(profile_task_segment_snapshot);
```

And I remove all es indices and template first, then start the OAP to create Indies. I curl the ES indies after the OAP finished initialize.
```
green open profile_task_segment_snapshot-20210331               LY2xjsBkTzGNQZjlc-51fw 1 1 0 0   522b   261b
green open browser_error_log-20210331                           K7ArON33RI26gPezW7-KuA 5 0 0 0  1.2kb  1.2kb
green open profile_task-20210331                                fuxKtckzQAy_lTMjKybiiw 1 1 0 0   522b   261b
green open profile_task_log-20210331                            G5ZNtKMVT_SRF_g7_NXRqA 1 1 0 0   522b   261b
green open jaeger_span-20210331                                 fDe8MlD_QwKCVeIU8ciY3Q 5 0 0 0  1.2kb  1.2kb
green open zipkin_span-20210331                                 OTNLbC_WS-WeUFxaGMl4ww 5 0 0 0  1.2kb  1.2kb
```

I already read the #6265 #6267 , but I cannot get some useful information.

**Comment by wu-sheng** [comment]
This is not a hard thing to debug, you could simply do by yourself.

**Comment by nisiyong** [comment]
Okay, we confirm whether this issue needs to be polished first.
If `disable` means DO NOT CREATE indices, maybe I could fix it.

**Comment by wu-sheng** [comment]
Disable doesn't only mean no index, it disable the whole streaming process.

**Comment by wu-sheng** [comment]
> Most users disable the metrics because they don't need the indices.
> But the useless indices created and deleted day by day. I think the disabled statements that don't create the index will be better.

Read my reply again. I didn't say index should be created.

**Comment by wu-sheng** [comment]
I found out what happens now, we changed the OAL loading sequence which makes the disable not working.
