### ISSUE TITLE
Installing skywalking via helm and using external elasticsearch how to specify storage.elasticsearch.namespace for skywalking

### ISSUE THREAD

**Issue by eltonbfw** [apache/skywalking#6667]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
-  Installing skywalking via helm and using external elasticsearch how to specify `storage.elasticsearch.namespace` for skywalking?  （通过helm安装skywalking，并且使用外部的elasticsearch服务，如何为skywalking指定）`storage.elasticsearch.namespace`
- How to filter endpoints for business-specific exceptions or error tracing? （如何为端点过滤特定的业务异常或错误的追踪）

- These questions above can be summarized as, what is the best practice of using skywalking in K8S platform and can you provide a sample for us to learn from.（上面这些问题可以汇总为，在K8S平台使用skywalking的最佳实践是什么样的，能否提供一个样本供我们借鉴。）

**Comment by wu-sheng** [comment]
1. You could use the system env to override all configurations. Document has included this.
2. I don't think we provide this kind of feature.
3. Best practice is from end users, rather than the dev team. This is not a proper question.

**Comment by eltonbfw** [comment]
> 1. You could use the system env to override all configurations. Document has included this.
> 2. I don't think we provide this kind of feature.
> 3. Best practice is from end users, rather than the dev team. This is not a proper question.

thank you
