### ISSUE TITLE
Why do you need to store binary data when storing in es

### ISSUE THREAD

**Issue by YczYanchengzhe** [apache/skywalking#6668]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
In the code, I see that when the data is stored using es, the reported segment data will be stored in binary format using grpc's tobyte, and the query field will be stored as a single row, so when it is stored, it may be queried Will the data be stored in two copies so that it will not lead to waste of resources? What is the reason for the design? Or is there a deviation between my understanding and the real situation? Hope to get your answer, thank you very much!
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Again, explaining code detail is not community responsibility.
