### ISSUE TITLE
Please remove old releases from the mirroring system

### ISSUE THREAD

**Issue by sebbASF** [apache/skywalking#6669]
To reduce the load on the ASF mirrors, projects are required to delete old releases [1]

Please can you remove all non-current releases?

i.e. please remove:

https://dist.apache.org/repos/dist/release/skywalking/8.1.0/
https://dist.apache.org/repos/dist/release/skywalking/8.2.0/
https://dist.apache.org/repos/dist/release/skywalking/8.3.0/

Remove or adjust any links on the download page first.

It's unfair to expect the 3rd party mirrors to carry old releases.

However you can still link to the archives for historic releases.

Please also update your release procedures to ensure old releases are archived in a timely manner.
A good time to do this is just after a new release has been announced.

Thanks!

[1] http://www.apache.org/dev/release.html#when-to-archive

**Comment by wu-sheng** [comment]
Hi, usually, we removed the releases too old, released 8-10 months

**Comment by sebbASF** [comment]
The policy is that non-current releases should be dropped from the mirrors.

They can still be linked from the download page.

**Comment by wu-sheng** [comment]
Website updated, download removed.
