### ISSUE TITLE
Service Log setup - not dispalyed on UI

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6672]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Service Logs not appearing on UI.
I have setup Skywalking 8.4 version. Kindly let me know if anything need to be set in configuration.

Thanks and Regards,
Jayesh Muley
![Service log Tab UI](https://user-images.githubusercontent.com/75727262/113304968-2db4eb00-9320-11eb-9310-78f01f6ac199.png)

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read the doc, https://skywalking.apache.org/docs/main/v8.4.0/en/setup/service-agent/java-agent/readme/#advanced-features-1

Part
> If you want to print trace context(e.g. traceId) in your logs, or collect logs, choose the log frameworks

**Comment by JayeshMuley** [comment]
Hello Sir, 

We are using Log4j and Logback in one of the client application. We are not having control to append the skywalking dependency in the config file of Log4j. 

-- As there suggested, to add the log4j config and change the following properties. 

   <dependency>
      <groupId>org.apache.skywalking</groupId>
      <artifactId>apm-toolkit-log4j-1.x</artifactId>
      <version>{project.release.version}</version>
   </dependency>

log4j.appender.CONSOLE.layout=TraceIdPatternLayout
log4j.rootLogger=INFO,CustomAppender
log4j.appender.CustomAppender=org.apache.skywalking.apm.toolkit.log.log4j.v1.x.log.GRPCLogClientAppender

ect. 


My Question is  - 

1.Is there any way we can avoid appending these property in Log4j, and without changing  anything in log4j properties and we start getting the logs. 

2. We have filebeat installed on one for the machine. Can we take the output for filebeat directly to OAP. 

Kindly suggest.

Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
You could avoid `log4j.appender.CustomAppender`, but you still need the SkyWalking layout(inject trace context metadata), take a look at the latest doc, and incoming 8.6.0.
