### ISSUE TITLE
Elasticsearch configuration does not take effect

### ISSUE THREAD

**Issue by ChuckyThh** [apache/skywalking#6675]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Elasticsearch configuration does not take effect
___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking830，docker，1.8

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
Use skywalking-docker-8.3.0 to make image ,docker 18.06.3-ce,kubernetes1.18.8
This is my configuration
![iShot2021-04-02 13 40 42](https://user-images.githubusercontent.com/17842316/113384695-31e11700-93b9-11eb-9689-efc567ea4137.png)
This is the running log

![iShot2021-04-02 13 37 33](https://user-images.githubusercontent.com/17842316/113385004-d1060e80-93b9-11eb-8a75-557ba5aea68a.png)
But the settings file I saw from kibana is wrong

![iShot2021-04-02 13 39 00](https://user-images.githubusercontent.com/17842316/113385667-2989db80-93bb-11eb-9569-5c2b70000556.png)

I want to know why ？

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by ChuckyThh** [comment]
No matter how I change the value of flushInterval, refresh_interval is always 10s or 30s

**Comment by wu-sheng** [comment]
Have you deleted the template? It can't change once it is initilaized

**Comment by ChuckyThh** [comment]
Do you mean that application.yml cannot be modified through environment variables?

**Comment by ChuckyThh** [comment]
Sorry i don't know what template refers to

**Comment by wu-sheng** [comment]
> Do you mean that application.yml cannot be modified through environment variables?

I mean the template of ElasticSearch. Removing the indices is not enough, you need to remove the template.

**Comment by ChuckyThh** [comment]
Where is the template for ElasticSearch？ @wu-sheng

**Comment by wu-sheng** [comment]
This is not our responsibility. Learn ES by yourself.
