### ISSUE TITLE
Demo skywalking website is down 

### ISSUE THREAD

**Issue by XI1998-swapnilmarathe** [apache/skywalking#6680]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Bug

___
### Bug
- What happened?
I was going through main page and saw live demo option, but seems that on clicking that (https://demo.skywalking.apache.org/) is opened but, its down.

![image](https://user-images.githubusercontent.com/74582859/113485375-c8e9c400-94ca-11eb-8740-e69c3fd0279f.png)
![image](https://user-images.githubusercontent.com/74582859/113485386-d43cef80-94ca-11eb-904c-c1ea739ab79e.png)

___
### Requirement or improvement
- Expected: The live demo website should be available for demonstration purposes.

**Comment by wu-sheng** [comment]
@ascrutae PTAL

**Comment by wu-sheng** [comment]
It is back online.

**Comment by XI1998-swapnilmarathe** [comment]
its down again

![image](https://user-images.githubusercontent.com/74582859/147383003-6728a849-b607-4c03-80a2-972072046e0e.png)

**Comment by wu-sheng** [comment]
> its down again
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/74582859/147383003-6728a849-b607-4c03-80a2-972072046e0e.png)
> 
> 

Still work on my side.
