### ISSUE TITLE
Support TCP topology and metrics in Istio/Envoy mesh case

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6682]
@kezhenxu94 I think right now is a good time to expand our ALS solution(IP mapping) to support TCP. As we know, we have HTTP 1/2 supported through the ALS, TCP in theory should be very similar, but the metrics could be very different, such as package/s, reconnecting rate.

@kezhenxu94 Base on current features, we could provide topology with TCP in analysis and query. But we should add new dashboard for TCP metrics of service in the `apm` panel.

@Fine0830 The biggest change this time is the metrics of nodes and line in the topology, it should be determined by 
1. Node types, https://github.com/apache/skywalking-query-protocol/blob/42d6783d8c1a0d0d4c2b28e58dc1f47dd554964e/topology.graphqls#L46
2. Call types(sourceComponents and targetComponents) https://github.com/apache/skywalking-query-protocol/blob/master/topology.graphqls#L92-L95

All services(default) keep as same as today.
For specific type, at this time, is TCP(we could have more in the future). UI should support load metrics for nodes and lines from different metrics(different names, protocol, and parameters are nearly the same) and different buttons(when clicking node, less than the default, so only a subset). But the same button(such as instance) should load different UI template, such as `TOPOLOGY_INSTANCE_TCP`

Note, this is a feature for **8.6.0** release, if @kezhenxu94 @hanahmily @Fine0830 @wankai123 have any concern about this, please let me know. We could set a meeting to discuss this.

**Comment by kezhenxu94** [comment]
For this issue, I'd split it into 2 parts (PRs), one is for the access log analysis (#6727), the other is for tcp metrics analysis.

We can analyze the topology between http 1/2 and tcp services from the Envoy access logs, but it's impossible to get metrics like package per minute / second, connection reset rate, Network Round Trip Time, etc. from the access logs, so I'll finish #6727 first and do some research on how to get important tcp metrics.

**Comment by wu-sheng** [comment]
> but it's impossible to get metrics like package per minute / second, connection reset rate, Network Round Trip Time, etc.

I am a little confused about this statement. If the metric isn't package/min, then what is the ALS TCP represents? Clearly, there is call/min at TCP level at all.

**Comment by kezhenxu94** [comment]
> > but it's impossible to get metrics like package per minute / second, connection reset rate, Network Round Trip Time, etc.
> 
> I am a little confused about this statement. If the metric isn't package/min, then what is the ALS TCP represents? Clearly, there is call/min at TCP level at all.

OK I should not say metrics “packet per minute (PPM) is impossible to get from the logs”, PPM can be derived from the traditional CPM because we can generate the traffic from the access log. 

What about the other metrics I listed above? I have no idea to retrieve them from the access log and I’m investigating on how to retrieve them from the metrics service or Istio metrics service (not ALS)

**Comment by wu-sheng** [comment]
1. `connection reset rate` is not from ALS, it is from the Envoy metrics service. Sorry, my mistake.
2. `Network Round Trip Time`, this should be the latency of TCP package, why we have issue about this?

**Comment by Fine0830** [comment]
Please feel free ping me,  if UI development can be started.

**Comment by wu-sheng** [comment]
@kezhenxu94 has finished the backend development.

@Fine0830 Now, all metrics on the topology should be configurable and should base on component type. 
About configurable, service's metrics,  relationship(service/instance/endpoint) metrics should have a new layout to make sure we have templates defined from the backend. We should discuss how to do this.
About base on `component type`, UI should be able to support read different templates according to node and line component type.
