### ISSUE TITLE
The relationship between the transmission of traceId and the sampling rate is too tight

### ISSUE THREAD

**Issue by zhousiliang163** [apache/skywalking#6694]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [] Requirement
- [ ] Feature or performance improvement

___

- 
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Through the Skywalking Agent TraceID passthrough, do link log query system, need to collect all the data, but do not want to let the sampling rate failure, this is a solution?
Now if the sampling rate is set, it will result in a portion of the log without traceId.
The relationship between the transmission of traceId and the sampling rate is too tight.
This should be the Skywalking optimization point

**Comment by wu-sheng** [comment]
Please don't submit duplicated questions on different channels. You are wasting the community's resouces.
