### ISSUE TITLE
java.lang.AbstractMethodError error

### ISSUE THREAD

**Issue by lorgine** [apache/skywalking#6695]
when i want to enhance spring filter,and it happens an error like under below?

`
public class FilterInstrumentation extends ClassInstanceMethodsEnhancePluginDefine {
    private static final String ENHANCE_CLASS = "javax.servlet.Filter";
    private static final String INTERCEPT_CLASS = "org.apache.skywalking.apm.plugin.spring.FilterInterceptor1";
    private static final String CONSTRUCTOR_CLASS = "org.apache.skywalking.apm.plugin.spring.FilterConstructorInterceptor";
    @Override
    protected ClassMatch enhanceClass() {
        return PrefixMatch.nameStartsWith("com.ppdai.infrastructure.demo.CatServletFilter");
    }

    @Override
    public ConstructorInterceptPoint[] getConstructorsInterceptPoints() {
        /*return new ConstructorInterceptPoint[]{
                new ConstructorInterceptPoint() {
                    @Override
                    public ElementMatcher<MethodDescription> getConstructorMatcher() {
                        return any();
                    }

                    @Override
                    public String getConstructorInterceptor() {
                        return CONSTRUCTOR_CLASS;
                    }
                }
        };*/
        return new ConstructorInterceptPoint[0];

    }

    @Override
    public InstanceMethodsInterceptPoint[] getInstanceMethodsInterceptPoints() {
        return new InstanceMethodsInterceptPoint[]{
                new InstanceMethodsInterceptPoint() {
                    @Override
                    public ElementMatcher<MethodDescription> getMethodsMatcher() {
                        return named("doFilter").and(takesArguments(3));
                    }

                    @Override
                    public String getMethodsInterceptor() {
                        return INTERCEPT_CLASS;
                    }

                    @Override
                    public boolean isOverrideArgs() {
                        return false;
                    }
                }
        };
    }
}

public class FilterInterceptor1 implements InstanceMethodsAroundInterceptor {

    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, MethodInterceptResult result) throws Throwable {

    }

    @Override
    public Object afterMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, Object ret) throws Throwable {
        return ret;
    }

    @Override
    public void handleMethodException(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, Throwable t) {

    }
}

@WebFilter
public class CatServletFilter  implements Filter {
    @Override
    public void init(FilterConfig filterConfig) throws ServletException {

    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
        chain.doFilter(request,response);
    }

    @Override
    public void destroy() {

    }
}
`

**Comment by wu-sheng** [comment]
Your description is chaotic, please make it well-formatted.
