### ISSUE TITLE
 spring cloud gateway Generated traceid and microservice are different

### ISSUE THREAD

**Issue by LingLingFeng** [apache/skywalking#6708]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- spring cloud gateway Generated traceid and microservice are different

- What happened?
forwarding requests from gateway to service a and from service a to service B，gateway Generated traceid and microservice are different
![sky请求1](https://user-images.githubusercontent.com/32393778/113958590-efee2000-9853-11eb-9451-1ce9d5687b02.png)
![sky网关](https://user-images.githubusercontent.com/32393778/113958606-f54b6a80-9853-11eb-9e36-f554513907ab.png)
![sky服务a](https://user-images.githubusercontent.com/32393778/113958617-f8def180-9853-11eb-9903-042862372b80.png)
![sky服务b](https://user-images.githubusercontent.com/32393778/113958621-fb414b80-9853-11eb-9284-caa02b527801.png)

spring boot 2.3.9.RELEASE、spring cloud Hoxton.SR10、skywalking 8.3.0

**Comment by wu-sheng** [comment]
Different trace IDs mean trace context doesn't propagate correctly. Use the latest version, and cross-check with our test cases, https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/gateway-2.1.x-scenario/support-version.list

**Comment by LingLingFeng** [comment]
Does the gateway use version 2.1.2.RELEASE or 2.2.3.RELEASE and the skywalking uses version 8.4.0  Or just need to use the 8.4.0 version of the skywalking？

**Comment by wu-sheng** [comment]
> Does the gateway use version 2.1.2.RELEASE or 2.2.3.RELEASE and the skywalking uses version 8.4.0 Or just need to use the 8.4.0 version of the skywalking？

They are tested. The plugins are contributed by countless contributors, we have nearly 340 for this repo. We can't test every version, we don't have enough resources.

**Comment by hefangqiang** [comment]
I had the same problem

**Comment by LingLingFeng** [comment]
Is there a corresponding version or sample of gateway and skywalking integration test successful

**Comment by LingLingFeng** [comment]
> I had the same problem

Have you solved your problem
