### ISSUE TITLE
The request was rejected because the upstream retry limit (HTTP) or maximum connect attempts (TCP) was reached

### ISSUE THREAD

**Issue by goooogs** [apache/skywalking#6709]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

As the image shows below, when I access the **`APM`** or **`SelfObservability`** page,  it always got some faild request (1, 2, or 3) with **`503`** status code, and the sequence of failed request is unpredictable.

I looked at the istio-ingressgateway log, it says that: `POST /graphql HTTP/2" 503 URX`, and the `URX` means that the request was rejected because the upstream retry limit (HTTP) or maximum connect attempts (TCP) was reached (see [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#format-rules))

I tried to call the request manualy by `curl`, it's fine.

I have no limitation on my k8s cluster and istio.
Is it the limit by graphql?

<img width="1049" alt="img1" src="https://user-images.githubusercontent.com/8554557/113961978-778a5d80-9859-11eb-8de1-c12099a3bb31.png">

___
### Bug
- Which version of SkyWalking, OS, and JRE?

* `docker image`: apache/skywalking-oap-server:8.4.0-es6
* `OS`: CentOS Linux release 7.7.1908 (Core)
* `k8s`:
        - Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1"
        - Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1"
* `istio`: 1.8.0
-----

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
eliminate the failed request with status code of 503.

**Comment by wu-sheng** [comment]
We don't set anything related to 503. I think it is your env issue.
