### ISSUE TITLE
Add Dynamic Configuration in Satellite

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#6720]
For some scenarios, we need a central way to control all the Satellite containers. 
1. dynamic rule to convert log to Metrics .
2. dynamic change the fetching intervals of Prometheus fetcher. 

How about using the configuration discovery receiver to implement it?

**Comment by wu-sheng** [comment]
> How about using the configuration discovery receiver to implement it?

Once you have the configuration format for Satellite, this is acceptable for OAP.

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-satellite/pull/54
