### ISSUE TITLE
Add alarm rule management page.

### ISSUE THREAD

**Issue by liqiangz** [apache/skywalking#6723]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
I feel that the current alarm rules  are very complex and difficult to manage. Maybe we can add an alarm rule management page in the alarm page to visualize it. When we modify the alarm rules
  1. When the dynamic data source is configured, the added rule will be synchronized to the dynamic data source
  2. When the dynamic data source is not configured, the added rules will only exist in the memory
 
In the future, we may be able to visualize other configurations as well, so that users can use skywalking more conveniently.

**Comment by wu-sheng** [comment]
We don't get us involved in the management UI. You could setup a new project for it, as it has to adopt different configuration center servers, even k8s.
