### ISSUE TITLE
Include events of the entity(s) in the alarm

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6725]
I talked with @llinder yesterday, to introduce the current SkyWalking and what we are going to do about the EVENT concept.
Lance proposed a very interesting thing when SkyWalking sends an alarm, we could include the events of entity(one or two if it is a relationship level alarm) in the alarm message according to the period.

@kezhenxu94 You asked a very similar thing back in the opposite direction(https://github.com/apache/skywalking/pull/6702#discussion_r611034197).

I think we should do both ways. @kezhenxu94 @chenmudu What do you think? Of course, in a separated PR later.

**Comment by kezhenxu94** [comment]
That sounds indeed interesting to me 😉 and it collaborates the alarms and the events. @chenmudu are you interested in this?

**Comment by chenmudu** [comment]
@wu-sheng @kezhenxu94 
Yeah, It looks pretty good, it makes the event and the alert more closely related in Oap.
