### ISSUE TITLE
Why is it different from production? What's the matter with this Redis/SUBSCRIBE? Why?

### ISSUE THREAD

**Issue by ziyouwuai** [apache/skywalking#6726]
### prod

![image](https://user-images.githubusercontent.com/61656126/114272519-19bc6800-9a49-11eb-88de-314eb95c81dd.png)

### test
![image](https://user-images.githubusercontent.com/61656126/114272557-3ce71780-9a49-11eb-8f4b-358b22c8d75a.png)

Why is it different from production? What's the matter with this Redis/SUBSCRIBE? Why?The code is the same

**Comment by wu-sheng** [comment]
Read the plugin source codes. The SkyWalking core and concept have nothing related to this.
