### ISSUE TITLE
pulsar plugin breaks trace on the consumer size

### ISSUE THREAD

**Issue by wallezhang** [apache/skywalking#6730]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking：8.4.0
OS：MacOS
JRE：11
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

Pulsar plugin is only enhance `org.apache.pulsar.client.impl.ConsumerImpl` class, however pulsar will use `org.apache.pulsar.client.impl.MultiTopicsConsumerImpl` class to consume when topic's partition size greater than 0. So the trace will be breaked on consumer side. 

In `org.apache.pulsar.client.impl.MultiTopicsConsumerImpl` class, pulsar will new some  `org.apache.pulsar.client.impl.ConsumerImpl` class instances to receive messages, but consumption process is in the internal executor while callback to listener in the external executor.

The entry method is `org.apache.pulsar.client.impl.PulsarClientImpl#doSingleTopicSubscribeAsync`.
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@codelipenghui Could you take a look? I don't know what it is.

**Comment by codelipenghui** [comment]
@wu-sheng sure. will take a look ASAP.

**Comment by codelipenghui** [comment]
@wallezhang I want to double confirm this issue. If I understand correctly, you are using the message listener on a MultipleTopicConsumerImpl and the message trace does not work? Or use receive() method also does not work?

**Comment by wallezhang** [comment]
@codelipenghui Hi, I found a solution that just modify the enhanced classes and methods.
Enhance class: `org.apache.pulsar.client.impl.ConsumerBase` and method: `callMessageListener`
However, this modification can only be applied to pulsar version 2.7+. There are no `callMessageListener` method in pulsar client versions earlier than 2.7, so I think we can enhance `internalReceive` method instead.

**Comment by wallezhang** [comment]
> @wallezhang I want to double confirm this issue. If I understand correctly, you are using the message listener on a MultipleTopicConsumerImpl and the message trace does not work? Or use receive() method also does not work?

yes, I can't get message trace in listener

**Comment by codelipenghui** [comment]
@wallezhang Could you please share the way that you get the message trace?

**Comment by wallezhang** [comment]
> @wallezhang Could you please share the way that you get the message trace?

```
ConsumerBuilder<?> builder = pulsarClient.newConsumer(getSchema(holder));
            builder.consumerName("consumer-" + name)
                    .subscriptionName(subscriptionName)
                    .subscriptionType(holder.getAnnotation().subscriptionType())
                    .messageListener((consumer, msg) -> {
                        try {
                            final Method method = holder.getHandler();
                            log.info("on message. data:{}", msg.getValue());
                            method.setAccessible(true);
                            method.invoke(holder.getBean(), msg.getValue());

                            consumer.acknowledge(msg);
                        } catch (Exception e) {
                            e.printStackTrace();
                            consumer.negativeAcknowledge(msg);
                            exceptionEmitter.onNext(new FailedMessage(e, consumer, msg));
                        }
                    });
            return builder.subscribe();
```

Log In message listener can not get message trace, log output: *****TID: N/A*****

**Comment by codelipenghui** [comment]
@wallezhang Seems the problem is related to passing the span across threads. Have you tried to get the `ContextCarrier` from the properties of the message?

```
ContextCarrier carrier = new ContextCarrier();
            CarrierItem next = carrier.items();
            while (next.hasNext()) {
                next = next.next();
                next.setHeadValue(msg.getProperty(next.getHeadKey()));
            }
```

Then you can use the carrier to create a span or other operations

```
ContextManager.createEntrySpan(<operationName>, carrier);
```

**Comment by wallezhang** [comment]
> @wallezhang Seems the problem is related to passing the span across threads. Have you tried to get the `ContextCarrier` from the properties of the message?
> 
> ```
> ContextCarrier carrier = new ContextCarrier();
>             CarrierItem next = carrier.items();
>             while (next.hasNext()) {
>                 next = next.next();
>                 next.setHeadValue(msg.getProperty(next.getHeadKey()));
>             }
> ```
> 
> Then you can use the carrier to create a span or other operations
> 
> ```
> ContextManager.createEntrySpan(<operationName>, carrier);
> ```

Why not pass the span in the message across the thread?

**Comment by wallezhang** [comment]
I wonder if we can do a `MessageListener` enhancement, so that the business code can pay more attention to the business logic instead of the logic related to trace

**Comment by codelipenghui** [comment]
@wallezhang Yes, agree. we can do a MessageListener enhancement for passing the span.

**Comment by wallezhang** [comment]
> @wallezhang Yes, agree. we can do a MessageListener enhancement for passing the span. Are you interested in pushing a PR for it? If you don't have a chance to deal with it, I can push a fix later.

Yes, I'm working on it.

**Comment by wallezhang** [comment]
@codelipenghui Could you review the PR please?

**Comment by wallezhang** [comment]
@wu-sheng @codelipenghui I found a bad case when the number of subject partitions is greater than 1, it will lead to errors on the consumer side. I need to fix it on a new branch and submit another PR tomorrow. Of course I will write more test scenarios to cover the bad case. Sorry for this.

**Comment by wallezhang** [comment]
@wu-sheng @codelipenghui Please help to review the code. Thx
