### ISSUE TITLE
Alarm rules for endpoint and instance of  specified services

### ISSUE THREAD

**Issue by ProLayman09** [apache/skywalking#6731]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I use alarm recently and I notice there are rules for Instance and Endpoint:
```
Instance: {Instance name} of {Service name}
Endpoint: {Endpoint name} in {Service name}
```
As the docs say, I can fill the *include-names* to specify the Instance and Endpoint so that the rule would be applied to specified instance and endpoint.  
But do I need to specify the Service? If dont, the rule would be applied to all the instance and endpoint despite service, right? For example, I have service A and service B and they both have endpoint *sayHello*.When I set up an endpoint rule whose *include-names* is *sayHello*, then the rule will be applied to service A and service B both? Even if I just want to set up rule for service A.  
So any wrong with my understanding?  Are there any solutions for setting up rules for endpoint and instance of  specified services?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> When I set up an endpoint rule whose include-names is sayHello, then the rule will be applied to service A and service B both?

No, we don't support this.
