### ISSUE TITLE
Page style problem

### ISSUE THREAD

**Issue by linhantao** [apache/skywalking#6732]
![image](https://user-images.githubusercontent.com/56330004/114356187-e68dec00-9ba2-11eb-8812-28d6c80ca613.png)
![image](https://user-images.githubusercontent.com/56330004/114356209-edb4fa00-9ba2-11eb-8738-5e8868c727ed.png)
The scroll bar is not hidden

**Comment by Fine0830** [comment]
I don't reproduce this.

**Comment by linhantao** [comment]
I use the 360 Speed Browser

**Comment by wu-sheng** [comment]
> I use the 360 Speed Browser

This is not on our check list.
