### ISSUE TITLE
[Python] Is there no support for python websocket

### ISSUE THREAD

**Issue by coveyliu** [apache/skywalking#6733]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is there no support for python websocket
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
thank you! when i want to trace websocket in my python project, but i can not find, so i write this issue to you

**Comment by kezhenxu94** [comment]
If it’s not in the supported list, it’s not supported. And yes it’s not supported yet. Welcome to contribute.

**Comment by PhilippHelfenritter** [comment]
I would like to give this issue a shot, if possible.

**Comment by wu-sheng** [comment]
@PhilippHelfenritter I could assign this to you if you like.

**Comment by PhilippHelfenritter** [comment]
@wu-sheng Sure, thanks!

**Comment by PhilippHelfenritter** [comment]
I am sorry, currently I do not have any time to work it, maybe I will in the future.

**Comment by wu-sheng** [comment]
> I am sorry, currently I do not have any time to work it, maybe I will in the future.

Got it. It is fine. Let's keep this open.

**Comment by kezhenxu94** [comment]
> Is there support for java websocket like netty?

Read the doc... and don't mix unrelated questions in a single issue, this issue is about Python agent

**Comment by mihir1739** [comment]
I would like to work on this if its available...

**Comment by kezhenxu94** [comment]
> I would like to work on this if its available...

Yes, assign to you, please go ahead

**Comment by Superskyyy** [comment]
I was just fixing up the FastAPI plugin and therefore added support for websocket server there (only from within the fastAPI plugin for now). So I suppose I will add websocket client/server plugin too (they may not land before 1.0.0 release). 

Since last assignee didn't proceed I will take over.
