### ISSUE TITLE
the UI dashboard is blank

### ISSUE THREAD

**Issue by goooogs** [apache/skywalking#6735]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

After the installiton, the UI dashboard is fine.
Today, I found that the UI dashboard became blank, without error log in the web page, UI and OAP service (may be because ES cluster become RED, but I fixed it).

I don't know how to troubleshooting about it.

<img width="1435" alt="ui-dashboard-blank" src="https://user-images.githubusercontent.com/8554557/114376518-46db5880-9bb8-11eb-85ec-8e80bfb78493.png">

`/graphql` Response
[graphql-01.json.txt](https://github.com/apache/skywalking/files/6295658/graphql-01.json.txt)
[graphql-02.json.txt](https://github.com/apache/skywalking/files/6295659/graphql-02.json.txt)
[graphql-03.json.txt](https://github.com/apache/skywalking/files/6295660/graphql-03.json.txt)
[graphql-04.json.txt](https://github.com/apache/skywalking/files/6295661/graphql-04.json.txt)

___
### Bug
- Which version of SkyWalking, OS, and JRE?
docker image: apache/skywalking-oap-server:8.4.0-es6
OS: CentOS Linux release 7.7.1908 (Core)
k8s:
  Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1"
  Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1"
istio: 1.8.0
---

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by Fine0830** [comment]
Please clear browser cache

**Comment by goooogs** [comment]
> Please clear browser cache

It works for me, thanks a lot!

**Comment by goooogs** [comment]
This problem comes up again.
Is there a better way instead of clear browser cache?

**Comment by Fine0830** [comment]
Datum are cache in browser, so you have to clear browser cache to get latest data.

**Comment by goooogs** [comment]
It's useless for checked the`DISABLE CACHE` option in my chrome browser's develop tool.
All response data is new, why browser cache can cause this problem? Is there a refresh mechanism?

It's so inconvenient, I don't want to clear cache other than skywalking.

**Comment by wu-sheng** [comment]
> It's useless for checked the`DISABLE CACHE` option in my chrome browser's develop tool.
> All response data is new, why browser cache can cause this problem? Is there a refresh mechanism?
> 
> It's so inconvenient, I don't want to clear cache other than skywalking.

We don't explain the history and codes, if you want to understand or enhance the features, you need to follow the context by yourself. We are just saying it is what it is right now.

**Comment by wu-sheng** [comment]
And I am hard to understand what do you mean again. What do you have done on your side, is a black box to us. 
Please understand how an open source community works, it is about collaboration, we are not responding like a commercial service vendor.

**Comment by goooogs** [comment]
I didn't do anything.  The UI dashboard may becomes blank again after a few days. 

I found another way to clear browser cache only for skywalking (MaxOS):
press `Option` + `Command` + `I`
then press `Command` + `Shift` + `P`
then type `Clear site data`
press `Enter`

**Comment by goooogs** [comment]
I just don't want to clear all browser cache.
The above method is useful for me.
Thanks for your answer ^_^

**Comment by wu-sheng** [comment]
You need to refresh, the UI is querying the last time range. That is all.
