### ISSUE TITLE
How to set alarm rule for instance and endpoint of specified service

### ISSUE THREAD

**Issue by R0-D0** [apache/skywalking#6740]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
I use skywalking to monitor my services. To be simple, suppose there be serviceA..In skywalking dashboard, I can see serviceA has two instances:instanceA1, instanceA2,  each has two endpoints: endpointA1, endpointA2.
Now I want to set *instance* level alarm rule, such as sla rule for instanceA1:
```
my_instance_sla_rule:
    metrics-name: service_instance_sla
    include-names:
      - instanceA1
   # other configuration
```
or a endpoint alarm rule similar to above.
My question is ,: have skywalking make promise that instance or endpoint (shown in the dashboard) is global unique? 
Do we need to provide any other infomation exception for value *instanceA1*?

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
> My question is ,: have skywalking make promise that instance or endpoint (shown in the dashboard) is global unique?

That's weird question. All the instances and endpoints are from your applications, instances and endpoints with same names are considered as a single instance / endpoint in SkyWalking, thus unique of course. But under edge cases like https://github.com/apache/skywalking/issues/5535 you may see duplicated instances / endpoints in the UI, which you should fix first.

**Comment by R0-D0** [comment]
![image](https://user-images.githubusercontent.com/82426355/114494126-5dcc8a00-9c4e-11eb-8722-8d7136bb38a6.png)

It's what my skywalking dashboard shows when I search for metrics of endpoint in services.Obviously the endpoints such as /admin/, /token......are so common that it's likely two services have same endpoints.In that case, when I set up endpoint rule : 
```
my_endpoint_percent_rule:
    metrics-name: endpoint_percent
    include-names:
      - /token
   # other configuration
```
That would be applied to all the services which have endpoint: /token, right？  
When we use skywalking dashboard to search some metrics such as endpoint, we select service at first, then one endpoint at the endpoints list, which stands for all the endpoints WITHIN the service.In other words, the endpoints listed are been searched within service，not globally. So when set endpoint alarm rule, is it enough that just specify *endpoint*?

**Comment by wu-sheng** [comment]
No, your description doesn't make sense. Alarm rules should not do that.

**Comment by R0-D0** [comment]
You mean Skywalking alarm can't set up rule for a specified service's endpoint?

**Comment by wu-sheng** [comment]
> You mean Skywalking alarm can't set up rule for a specified service's endpoint?

No, you are not asking this. We only support that.
