### ISSUE TITLE
feat: add json rpc plugin 

### ISSUE THREAD

**Issue by gy09535** [apache/skywalking#6742]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
___

### Description
jsonrpc is a lightweight rpc framework that currently has used in some small and medium-sized companies, project address: https://github.com/briandilley/jsonrpc4j . This plug-in mainly adds tracing in the jsonsonrpc client and the service side to help users  better track their tracing.

**Comment by kezhenxu94** [comment]
@gy09535 are you going to do this?

**Comment by gy09535** [comment]
> @gy09535 are you going to do this?

yeah, I am doing it.
