### ISSUE TITLE
Add AWS OpenSearch as storage option

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6745]
@kezhenxu94 As AWS has finally announced the APLv2 distribution of ElasticSearch, we should evaluate the possibility and impact if SkyWalking use it as the storage to replace the ElasticSearch as the recommended one, especially for open-source users. We should also evaluate the possibility and practicability of removing the ElasticSearch's client if they don't release APLv2-licensed client anymore.

**Comment by kezhenxu94** [comment]
Early OpenSearch should be compatible with existing ES client (APLv2 licensed), I'll test it and if that's the case, I'll add OS to the test matrix and gradually replace the client libs when OS release their client jars (not yet now)

**Comment by kezhenxu94** [comment]
OK, it seems to be the case, https://github.com/apache/skywalking/runs/2534688698?check_suite_focus=true , but because OS also haven't release their docker image, do you @wu-sheng we should wait for that, or use the image built by ourself?

**Comment by wu-sheng** [comment]
> Early OpenSearch should be compatible with existing ES client (APLv2 licensed), I'll test it and if that's the case,

Yes, it is better they are compatible. Be aware, I noticed, OpenSearch image seems, has opened the authentication and TLS in default.

**Comment by kezhenxu94** [comment]
Built from https://github.com/opensearch-project/OpenSearch/releases/tag/1.0.0-beta1

**Comment by wu-sheng** [comment]
Oh, `Open Distro` has been totally replaced, even including the version number. I think we could only keep it built by ourselves for now. I am going to ask about the image status.

**Comment by kezhenxu94** [comment]
> > Built from https://github.com/opensearch-project/OpenSearch/releases/tag/1.0.0-beta1
> 
> Do you build the image by yourself?

Yes

**Comment by wu-sheng** [comment]
I am good to have self build image for now. Is that easy to build in the CI process? I mean, at least don't have to depend on a personal image.

**Comment by kezhenxu94** [comment]
> I am good to have self build image for now. Is that easy to build in the CI process? I mean, at least don't have to depend on a personal image.

Yes. Do you mean to build the image on the fly in our testing CI? If so, I can have it set up too

**Comment by wu-sheng** [comment]
Yes, build it in every e2e test, and we could be easy to upgrade the version once they have new release to test, such as 1.0 GA.

**Comment by caoheyang** [comment]
> > Early OpenSearch should be compatible with existing ES client (APLv2 licensed), I'll test it and if that's the case,
> 
> Yes, it is better they are compatible. Be aware, I noticed, OpenSearch image seems, has opened the authentication and TLS in default.

您好，吴老师，

请问那对于skywalking，是否支持https opensearch？

Thanks,
Heyang
