### ISSUE TITLE
how can trace action in parallelStream or parallel

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#6746]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1 ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

when use parallelStream or paralle  cross thread in project, how should do to tarce  action

like this，

      IntStream.range(1, 10).parallel().forEach(it -> {
               httpclient.post(xxx);
        });

when i use custom thread pool, skywalking can use  @TraceCrossThread to trace,  but use parallelStream or paralle，can trace?

**Comment by wu-sheng** [comment]
> when i use custom thread pool, skywalking can use @TraceCrossThread to trace, but use parallelStream or paralle，can trace?

We are clear in the plugin development document about how we do for async mode. Read it, we don't explain the duplicated things.
