### ISSUE TITLE
About the value of service_instance_id in receiver_zipkin

### ISSUE THREAD

**Issue by klboke** [apache/skywalking#6749]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ 1] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS, and JRE?

1. OS : mac os 10.15.7
2. JRE : jdk1.8
3. skywalking version ：8.5.0
4. elasticsearch version ：7.10.2

- Which company or project?
TapTap
- What happened?
I tried to use receiver_zipkin in spring cloud and istio environment. But there are bugs. When ui query trace, this exception will appear: `Cannot return null for non-nullable type:'ID' within parent'Span' (/trace/spans[0]/serviceInstanceName`. For example:
![image](https://user-images.githubusercontent.com/18591662/114656226-42ca4a80-9d20-11eb-839b-ea898efd1f0f.png)

I have located the reason, which is caused by the lack of ServiceInstanceId in the span entity that was queried. I went to look at the processing logic of zipkin when receiving data, and found that there is no processing logic for ServiceInstanceId
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
I learned that there is no definition of ServiceInstanceId in the zipkin data model, and then found that there is spring.InstanceId in the zipkin tags in the spring-cloud environment. There is node.id in the tags of istio's zipkin. These are very suitable to be used as ServiceInstanceId.

istio zipkin data
![image](https://user-images.githubusercontent.com/18591662/114656875-70fc5a00-9d21-11eb-81b6-91be420693ed.png)

spring-cloud  zipkin data
![image](https://user-images.githubusercontent.com/18591662/114657028-ba4ca980-9d21-11eb-8342-57610c4586f3.png)

**Comment by wu-sheng** [comment]
We could adpot Spring if you like, and set an empty as name in default. Welcome to send a pull request to fix

**Comment by klboke** [comment]
No problem, I plan to first be compatible with the naming of zipkin tags in the istio and spring environments. Then if there is not, set a default empty, you see if this is ok. If there is no problem, I will start to develop

**Comment by wu-sheng** [comment]
Generally, you could set a list of tag keys and try to set an instance name. If nothing found, set a default value.

**Comment by klboke** [comment]
Okay, design to get the naming corresponding to service_instance_id in tags from receiver_zipkin. I will follow up on this issue and submit pr
