### ISSUE TITLE
Why remove the query `getGlobalBrief` logic?

### ISSUE THREAD

**Issue by nisiyong** [apache/skywalking#6750]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
  - [X] Question or discussion

___
### Question

Hi, @wu-sheng. I noticed you remove the query `getGlobalBrief` logic, and keep it return mock data.
I have tried to find why from issue or PR, but there was nothing about that. I wanna know why? Because I think the query `getGlobalBrief` is useful, has there some problems?

`org.apache.skywalking.oap.query.graphql.resolver.MetadataQuery#getGlobalBrief`
```java
/**
 * @return all 0 of metadata.
 */
@Deprecated
public ClusterBrief getGlobalBrief(final Duration duration) throws IOException, ParseException {
    return new ClusterBrief();
}
```

**Comment by wu-sheng** [comment]
Because there is no metadata query available on the UI.

**Comment by nisiyong** [comment]
> Because there is no metadata query available on the UI.

You mean the backend has metadata, but the current UI doesn't want to show that?

**Comment by wu-sheng** [comment]
> You mean the backend has metadata, but the current UI doesn't want to show that?

Yes. We can't find the points of showing how many services/instances/endpoints. SkyWalking is not a BI system, APM doesn't care the number of them, it cares the performance.

**Comment by nisiyong** [comment]
Agree, thanks. By the way, I just want to add `ServiceBrief` like `GlobalBrief` in our internal system, we can do it by ourselves base on the SkyWalking core.

**Comment by wu-sheng** [comment]
>  By the way, I just want to add ServiceBrief like GlobalBrief in our internal system, we can do it by ourselves base on the SkyWalking core.

It is totally fine to do anything you believe useful in the private version. :) This is common in the open source.
