### ISSUE TITLE
Support collecting threadpool metrics by agent-core

### ISSUE THREAD

**Issue by 807801002** [apache/skywalking#6755]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can Skywalking support extension development in agent.core by intercepting the ThreadPoolExecutor class constructor?Way through the onConstruct InstanceConstructorInterceptor class objInst parameters corresponding to the instance,Then periodically collect ThreadPoolExecutor instance's thread pool metrics and construct new metric to implement thread pool monitoring

skywalking能否支持在agent.core扩展开发通过拦截ThreadPoolExecutor类构造器的方式，通过InstanceConstructorInterceptor类的onConstruct方法的objInst参数获取对应instance，然后定时采集ThreadPoolExecutor实例的线程池指标构造成新的metric来实现针对线程池的监控
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean `Can`?

**Comment by 807801002** [comment]
就是想在agent-core中新建一个包，然后通过InstanceConstructorInterceptor类来拦截ThreadPoolExecutor这个类，通过onConstruct方法的objInst参数获取对应instance，开启定时器去定时采集实例对应的线程池指标（PoolSize、ActiveCount、CorePoolSize、MaximumPoolSize、TaskCount等），上报到oap-server。这个方式可行不？或者说有什么其他方式可以采集线程池指标来实现对线程池的监控？

**Comment by wu-sheng** [comment]
Please keep all things in English. We need this readable for global. And the meter APIs exist for a while. Read plugin development doc, https://skywalking.apache.org/docs/main/v8.5.0/en/guides/java-plugin-development-guide/#meter-plugin
