### ISSUE TITLE
When using the AOP aspect in the project, the result obtained by using TraceContext.traceId() is Ignored_Trace

### ISSUE THREAD

**Issue by cjxiong** [apache/skywalking#6758]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ v] Question or discussion
 
___
### Question
- What do you want to know?
I quoted in the Spring project

`	<dependency>
			<groupId>org.apache.skywalking</groupId>
			<artifactId>apm-toolkit-trace</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.skywalking</groupId>
			<artifactId>apm-toolkit-logback-1.x</artifactId>
		</dependency>`
I need to print the parameters in AOP when the method is called

`    @Before("execution(public * com.apis..*.*(..))" + "||execution(public * com.provider..*.*(..))")
    public void before(JoinPoint point) {
        this.printMethodParams(point);
    }`

`public void printMethodParams(JoinPoint point) {
 String traceId = TraceContext.traceId();
}`
At this time, the value of traceId is Ignored_Trace

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking 8.5
 ___
### Requirement or improvement
I want to know how to output traceId correctly.
Thank you

**Comment by wu-sheng** [comment]
Don't submit duplicated issue. We don't generate trace id in this case

**Comment by cjxiong** [comment]
Is that 8.6.0 version supports such an operation?

**Comment by wu-sheng** [comment]
We don't think this should be supported.

**Comment by cjxiong** [comment]
There are detailed class calls in the skywalking trace, but the call parameters are not displayed
