### ISSUE TITLE
JavaxServletRequestHolder cannot be cast to

### ISSUE THREAD

**Issue by pc-jack** [apache/skywalking#6760]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug

___
### Question
- What do you want to know?

Does  skywalking 8.5.0   conflict with  druid-spring-boot-starter or spring-boot-starter-jdbc ?

If you remove the druid-spring-boot-starter and spring-boot-starter-jdbc, the problem does not exist.

This problem does not exist in version skywalking 6.3
___
### Bug
- Which version of SkyWalking, OS, and JRE?
- skywalking:8.5.0
- spring boot 2.1.5.RELEASE
- druid-spring-boot-starter-1.2.5.jar
- spring-boot-starter-jdbc-2.1.5.RELEASE.jar

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

ERROR 2021-04-15 17:50:15:538 http-nio-8000-exec-1 InstMethodsInter : class[class cn.watsons.monitoringalarm.controller.AlertController] before method[pstn] intercept failure 
java.lang.ClassCastException: org.apache.skywalking.apm.plugin.spring.mvc.commons.JavaxServletRequestHolder cannot be cast to org.apache.skywalking.apm.plugin.spring.mvc.commons.RequestHolder
	at org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.AbstractMethodInterceptor.beforeMethod(AbstractMethodInterceptor.java:99)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)
	at cn.watsons.monitoringalarm.controller.AlertController.pstn(AlertController.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

pom.xml

 <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.2.5</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
- This conflict has always existed
- Does  skywalking 8.5.0   conflict with  druid-spring-boot-starter or spring-boot-starter-jdbc ?
- This problem does not exist in version skywalking 6.3

**Comment by wu-sheng** [comment]
We don't know this conflict, and this is the first time reporting this. I would recommend you to debug the codes to see whether this casting error. My guess is, there is something not to be instrumented.
