### ISSUE TITLE
what about service cpm and service cpm

### ISSUE THREAD

**Issue by YczYanchengzhe** [apache/skywalking#6765]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What is the difference between the service's cpm and the service instance's spm? According to my understanding, the service's cpm is the total number of requests received by the service in a unit time, and the service instance's cpm is the total number of requests received by the service node in a unit time. But according to our online statistics, the total number of cpm nodes will be greater than the number of cpm services. I am very confused about this.
I read the source code and saw that cpm actually does a sum operation in a unit of time, then the two data should not be so different in theory.
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> ccording to my understanding, the service's cpm is the total number of requests received by the service in a unit time

This is correct. But you should check whether OAP fresh all the data into the ES or other storage.
