### ISSUE TITLE
[Bug]EndpointNameGrouping in SourceBuilder may not work

### ISSUE THREAD

**Issue by honganan** [apache/skywalking#6766]
I glad to found the `EndpointNameGrouping` feature, and it can really solve problems that many enterprises will face.
### Bug
`SourceBuilder` using `NamingControl` to do endpoint name length format and `end-name-grouping` when `setSourceEndpointName` or `setDestEndpointName` invoked. But `NameControl` dependence on `serviceName` to finish the group matching according to the code:
```java
    @Getter
    private String destServiceName;

    public void setDestServiceName(final String destServiceName) {
        this.destServiceName = namingControl.formatServiceName(destServiceName);
    }

    @Getter
    @Setter
    private NodeType destNodeType;
    @Getter
    private String destServiceInstanceName;

    public void setDestServiceInstanceName(final String destServiceInstanceName) {
        this.destServiceInstanceName = namingControl.formatServiceName(destServiceInstanceName);
    }
```
But at this time the `serviceName` may not have been set. When using `SourceBuilder` in `MultiScopesAnalysisListener`, there are many place that set endpoint name first and service name later, like L118~L120

```java
sourceBuilder.setDestEndpointName(span.getOperationName());
sourceBuilder.setDestServiceInstanceName(segmentObject.getServiceInstance());
sourceBuilder.setDestServiceName(segmentObject.getService());
```

### Requirement or improvement
The fastest way to solve is change the set methods invoking order. But it's too easy to make a mistake as it depends on set method calling order.
I suggest adding a `namingFormat()` method in `SourceBuilder` and call it manually after all properties are set. How do you think?

**Comment by kezhenxu94** [comment]
I don't see the codes in the latest branch, maybe you're looking at an old commit

**Comment by honganan** [comment]
Oh yes, I have an old version code.
