### ISSUE TITLE
gRPC reporter not take effect

### ISSUE THREAD

**Issue by dylanxu90** [apache/skywalking#6769]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?

Hello, when I configured gRPC reporter according to the document, it was configured in log4j2.xml, but it did not take effect.
<GRPCLogClientAppender name="grpc-log">
         <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}-%msg%n"/>
</GRPCLogClientAppender>

By opening debug, it is found that the corresponding class (org.apache.skywalking.apm.toolkit.log.log4j.v2.x.log.GRPCLogClientAppender) has been enhanced, but the interceptor (org.apache.skywalking.apm. toolkit.activation.log.log4j.v2.x.log.GRPCLogAppenderInterceptor)

**Comment by kezhenxu94** [comment]
There is nothing useful in the question. Please learn how to ask question.
