### ISSUE TITLE
how to add login page to skywalking UI

### ISSUE THREAD

**Issue by manmohanmirkar123** [apache/skywalking#6776]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by manmohanmirkar123** [comment]
could you please guide me on how to add login authetication in skywalking UI page

**Comment by wu-sheng** [comment]
Please don't submitb duplicated issue. SkyWalking doesn't have login.
