### ISSUE TITLE
skywalking 8.5.0 Unable to collect logs normally

### ISSUE THREAD

**Issue by Gitwangpin** [apache/skywalking#6778]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
skywalking 8.5.0 Unable to collect logs normally

___
### Bug
- Which version of SkyWalking, OS, and JRE?
apache-skywalking-apm-es7-8.5.0
windwos and linux
jdk1.8

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
skywalking 8.5.0 Unable to collect logs normally
When I tested skywalking log function, I found that the latest version can't collect logs normally. I can collect logs normally when I switch to 8.4.0，Default configuration, local machine

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
Possibly duplicated with https://github.com/apache/skywalking/issues/6767

**Comment by wu-sheng** [comment]
http://demo.skywalking.apache.org is using 8.5.0. So we don't know what is wrong.

**Comment by Gitwangpin** [comment]
In my test, I use a simple spring boot program. When OAP server is 8.5.0 and agent is 8.5.0, it doesn't work. When OAP server is 8.5.0 and agent is 8.4.0, it works

**Comment by wu-sheng** [comment]
Read the latest doc, they are different in different versions.
