### ISSUE TITLE
Monitoring Application Servers such as Tomcat

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6779]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Can we monitor Application server like Tomcat ect using Skywalking plugins. 
Kindly suggest.

Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
Tomcat is on the supported list. Read documentation, it is very clear, http://skywalking.apache.org/docs/main/v8.5.0/en/setup/service-agent/java-agent/readme/#install-javaagent-faqs.

**Comment by JayeshMuley** [comment]
Dear sir, 
I have installed skywalking agent on Tomcat server for an application, as per the specified instructions on the link. 
I am getting application related matrices but the problem is I am not getting the Tomcat(as Application Server) related metrics ( like Request throughput ,latency metrics, Thread pool metrics etc). 

Also Topology not showing The Tomcat Server where  My Application is deployed. 

Do we have any settings which I am not doing to get these matrices, so that we can make use of it.

![TomcatServerApp](https://user-images.githubusercontent.com/75727262/115187879-ae862c00-a101-11eb-9b5c-03930d9aa41b.png)


Thanks and Regards,
Jayesh Muley

Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
It seems no suitable Tomcat plugin. Do you check the doc of the supported list?

**Comment by JayeshMuley** [comment]
Tomcat Version where Application is running  - 

Server version: Apache Tomcat/9.0.31
Server built:   Feb 5 2020 19:32:12 UTC
Server number:  9.0.31.0
OS Name:        Linux

Skywalking Version - 

8.4 

Agent Called Through Skywalking 

export CATALINA_OPTS="-Xmx1400m -Xms400m -server -Dsolr.solr.home=${CATALINA_HOME}/solr -Djava.awt.headless=true -Dactivemq.store.dir=${CATALINA_HOME}/mq 
-Dkk.log4j.debug=true -XX:-OmitStackTraceInFastThrow -DjvmRoute=`hostname` -javaagent:/home/sky3.4/apache-skywalking-apm-bin-es7/agent/skywalking-agent.jar"


Plugin under directory (/home/sky3.4/apache-skywalking-apm-bin-es7/agent/plugins) 

-rw-r--r--. 1 root root 23385 Apr 17 09:47 tomcat-7.x-8.x-plugin-8.4.0.jar


Kindly suggest if this plugin version a problem  tomcat-7.x-8.x-plugin-8.4.0.jar ? If yes from where we can get the plugin for tomcat-9.x

Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
Sorry, I don't have details about this. Maybe need another new plugin.

**Comment by JayeshMuley** [comment]
To monitor tomcat server metrics and to populate the data in following table do I need to Integrate Prometheus? or using probe inside catalina.sh can do.

 meter_tomcat_sessions_active_current
 meter_tomcat_sessions_active_max
 meter_tomcat_sessions_rejected

Kindly suggest.

**Comment by wu-sheng** [comment]
The agent has no relationship with Prometheus. Set `-javaagent` should be enough.
