### ISSUE TITLE
如何获取链路告警中的详细异常信息

### ISSUE THREAD

**Issue by z8772083** [apache/skywalking#6782]
请教：

  我想获取更加详细的链路告警跨度信息然后输出告警，通过api查询？或者在ES中根据日志过滤关键字告警？获取的信息如下图：

版本: 8.4

![image](https://user-images.githubusercontent.com/18564603/115211404-1d7b7900-a132-11eb-9e91-543cba6c06b9.png)

**Comment by wu-sheng** [comment]
Use English on GitHub please. And read protocol doc, the query protocol is about this

**Comment by z8772083** [comment]
好的，麻烦通过下QQ群 Apache Skywaling，申请加入QQ群了。 @wu-sheng
