### ISSUE TITLE
jdk-threading-plugin not work

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#6785]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ 1] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

v8.3

jdk-threading-plugin not work

1. i put this plugin from bootstarp to plugins dic
2. i config plugin.jdkthreading.threading_class_prefixes in agent.config 

use arthas get static field org.apache.skywalking.apm.plugin.jdk.threading.JDKThreadingPluginConfig.Plugin.JdkThreading#THREADING_CLASS_PREFIXES

it is the value i config in agent.config

but the class which impl runnable interface is not enhanced,  where is the problem

**Comment by wu-sheng** [comment]
I think you are not new to the SkyWalking. Please always check the plugin tests, https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/jdk-threading-scenario. It is there, and it is real.
