### ISSUE TITLE
Service Topology

### ISSUE THREAD

**Issue by githubphy** [apache/skywalking#6786]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to find the interface call between services from a large amount of data to prove the call relationship between services shown in the topology diagram
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> How to find the interface call between services from a large amount of data to prove the call relationship between services shown in the topology diagram

I am not sure about your question. We don't have endpoint->service topology. Why need that? 
We provide endpoint->endpoint dependency map.

**Comment by githubphy** [comment]
> > How to find the interface call between services from a large amount of data to prove the call relationship between services shown in the topology diagram
> 
> I am not sure about your question. We don't have endpoint->service topology. Why need that?
> We provide endpoint->endpoint dependency map.

I mean, for the service topology diagram, how to prove that there are call relationships between these services, because we found some uncertain call relationships

**Comment by wu-sheng** [comment]
> I mean, for the service topology diagram, how to prove that there are call relationships between these services, because we found some uncertain call relationships

Prove? We don't have that. APM seems not designing for proving something.
