### ISSUE TITLE
Service is started and the UI is not visible

### ISSUE THREAD

**Issue by aokinba** [apache/skywalking#6788]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.4.0-es7  + clustering
os = centos

- What happened?

The Gateway Service is started and the UI is not visible
![image](https://user-images.githubusercontent.com/6531769/115331720-050a6d80-a1c9-11eb-9e5d-f0a20a27ad96.png)

**Comment by wu-sheng** [comment]
Sorry, debugging your local env is not community's responsibility. We can't afford all of them.
