### ISSUE TITLE
MongoDB can only view parameters, not view SQL？

### ISSUE THREAD

**Issue by aokinba** [apache/skywalking#6789]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

MongoDB can only view parameters, not view SQL？
![image](https://user-images.githubusercontent.com/6531769/115334181-7b10d380-a1cd-11eb-8f9c-d58b0111f061.png)

**Comment by wu-sheng** [comment]
Operation name is including the MongoDB execution method. What SQL do you mean? I don't remember MongoDB has SQL in native mode.
