### ISSUE TITLE
oap meter_instance_metrics_first_aggregation Question

### ISSUE THREAD

**Issue by YczYanchengzhe** [apache/skywalking#6790]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hello, how does the monitoring of the oap node determine the first-level aggregated traffic when it is used as the receive role? When we deployed online, we found that the first-level aggregated statistics for the nodes that did not have access to traffic were not 0, the value It is 165, which is very stable. It is found through tcpdump to interact with other nodes. Can you answer what this part of the traffic refers to?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I am not 100% sure. Are you asking about this?

https://github.com/apache/skywalking/blob/527d772575ebb8b4bd86ab4add8651aefeede8d4/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/analysis/worker/MetricsAggregateWorker.java#L92

L1 aggregation is relating to the received data.

**Comment by YczYanchengzhe** [comment]
Thank you very much for your answers, your suggestions have helped us a lot
