### ISSUE TITLE
Deployment Analysis with APM agents

### ISSUE THREAD

**Issue by gokcesurenkok** [apache/skywalking#6798]
- Why do you submit this issue?
 Feature or performance improvement

___
### Question
- I would like to know if it is possible to track a service deployment historically with deployment version tags 

Thanks

**Comment by wu-sheng** [comment]
That is what we called EVENT. Read this, https://skywalking.apache.org/docs/main/v8.5.0/en/concepts-and-designs/event/.
Use the SkyWalking CLI in your CD system or any system controlling your version in deployment, we will have the event about that.
