### ISSUE TITLE
[NGINX-LUA] Support Kafka producer to report tracing

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#6801]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

I am planning to implement Kafka Reporter for Nginx Lua Agent. Now, as I know, it can be achievable. I am still a freshman in LUA, so if something I missed, please point it out. Simultaneously, any suggestion is welcome.

There are two choices to do for Kafka Fetcher in OAP. 
1. Lets Kafka Fetcher support JSON format record. 
2. Nginx Lua Agent is going to support `Protocol Buffer`.

**Comment by wu-sheng** [comment]
> Nginx Lua Agent is going to support Protocol Buffer.

This would be better.
