### ISSUE TITLE
DataTTLKeeperTimer not deleting the record as expected

### ISSUE THREAD

**Issue by whohasthis** [apache/skywalking#6804]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.4.0, running in Kubernetes pod on CentOS, JRE1.8, storage is elasticsearch 6.7
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
we use default configuration for TTL part, 
the DataTTLKeeperTimer keeps returning this message : The selected first getAddress is _IP_hidden__11800. Skip.  
Could you please point a way to check what could be the cause for this ? the data keeps in ES for more than 2 weeks, we have to manully clear the data. 
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This should be simple to debug, check why this skip happens.
