### ISSUE TITLE
springboot 1.5 not work when use skywalking

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#6808]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ 1] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

project use springboot 1.5，when add skywalking to it，it can not start competely，skywalkig log no error，project start log stuck，and no error log，remove skywalking， it can work

when i use arthas look classloader info,  org.springframework.boot.loader.LaunchedURLClassLoader just load one class，where is the problem

![image](https://user-images.githubusercontent.com/22722907/115708613-cfb97780-a3a2-11eb-8e3a-aaed4ebe24ac.png)

**Comment by wu-sheng** [comment]
This description is not enough, I am not sure what `when i use arthas look classloader info, org.springframework.boot.loader.LaunchedURLClassLoader just load one class` means.

**Comment by xu1009** [comment]
> This description is not enough, I am not sure what `when i use arthas look classloader info, org.springframework.boot.loader.LaunchedURLClassLoader just load one class` means.

org.springframework.boot.loader.LaunchedURLClassLoader should load class in springboot project, when add skywalking, it looks like something stuck the load

**Comment by wu-sheng** [comment]
Spring boot codes are used in many test cases. I don't know this is the typical key.

**Comment by wu-sheng** [comment]
Such as this one, https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/spring-tx-scenario/pom.xml#L40

**Comment by xu1009** [comment]
> Such as this one, https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/spring-tx-scenario/pom.xml#L40

project use ext classloader load all dependency, it not work
