### ISSUE TITLE
Does SkyWalkinig support manual instrumentation of Android and iOS?

### ISSUE THREAD

**Issue by yaojingguo** [apache/skywalking#6810]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I want to add actions taken by iOS and Android to the distributed trace. If I make an HTTP request in an APP, I want the following trace:

````
     Span [in an APP]
                 |
                 |
                 +
    Span [at the server side]
````

I know there is [cpp2sky](https://github.com/SkyAPM/cpp2sky) which supports C++. Are there similar SDKs for Android and iOS?

**Comment by wu-sheng** [comment]
I think you have to set up new sub-projects to do so. Anything to propose?

**Comment by wu-sheng** [comment]
No update.
