### ISSUE TITLE
 the total  calls in an hour or one day

### ISSUE THREAD

**Issue by mlzxdzl** [apache/skywalking#6813]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Where can I find the total  calls in an hour or one day? In the Topology,I can only see the Cpm.
In the pinpoint, I can the total  calls in the ServerMap ，Just like the data in the red box of the picture below。
![A036AC41-16B4-410b-8025-F9070474DECD](https://user-images.githubusercontent.com/10397077/115814088-ff11c800-a426-11eb-84f4-7e01c1709857.png)

**Comment by wu-sheng** [comment]
We don't response to pinpoint question. Your question is not on the right way.
Learn SkyWalking, learn OAL.

**Comment by mlzxdzl** [comment]
Sorry, Maybe I didn't make it clear。 I only want to know,if skywalking have the same function like Pinpoint that I can know the total calls in an hour or one day. Now In the Topology,I can only see the Cpm.

**Comment by wu-sheng** [comment]
> Sorry, Maybe I didn't make it clear。 I only want to know,if skywalking have the same function like Pinpoint that I can know the total calls in an hour or one day. Now In the Topology,I can only see the Cpm.

You can, but we don't provide as default, as it doesn't make sense. You could customize by yourself very easily. That is why I mentioned OAL. But again, don't include Pinpoint in, what they did has nothing related to the answer.

**Comment by mlzxdzl** [comment]
@wu-sheng Thank you very much,that is my wrong. And Can you tell me how to customize it ?

**Comment by wu-sheng** [comment]
I have told you twice. Read OAL doc.

**Comment by mlzxdzl** [comment]
@wu-sheng Very sorry to make you angry. I have read the doc. I have solve the problem. Many people recommend this software to me.

**Comment by wu-sheng** [comment]
> @wu-sheng Very sorry to make you angry. I have read the doc. I have solve the problem. Many people recommend this software to me.

I am not angry, I just can't paste all documents here.
