### ISSUE TITLE
skywalking log UI has now traceId

### ISSUE THREAD

**Issue by netfreeperson** [apache/skywalking#6815]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
skywalking log UI has now traceId
___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking version: 1.8.5
- Which company or project?
sunyard
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
skywalking log UI has now traceId
![skywalking](https://user-images.githubusercontent.com/10592599/115836235-d18a4600-a449-11eb-8c29-fd4a5c282e59.png)

**Comment by netfreeperson** [comment]
skywalking version is : 8.5.0

**Comment by netfreeperson** [comment]
when i remove -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector configuration , the skywalking log ui became normal （has traceId data）.

**Comment by netfreeperson** [comment]
@wu-sheng is this normal? tanks

**Comment by netfreeperson** [comment]
@wu-sheng log4j2 use AsyncRoot config has the same problem,  is this nromal?

**Comment by wu-sheng** [comment]
Read document about which log appenders supported. I don't have answer for all these plugins

**Comment by netfreeperson** [comment]
> Read document about which log appenders supported. I don't have answer for all these plugins

thanks, i use log4j2 in Mixed Sync & Async pattern, it is normal.
