### ISSUE TITLE
span breaked on the invoke node of hystrix

### ISSUE THREAD

**Issue by zender-projects** [apache/skywalking#6819]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
1. dose skywalking support hystrix with 2.1.5 ?
2. span breaked on the invoke node of hystrix but not all, i can't find the reason, dose it associate with the hystrix pulgin version?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> dose skywalking support hystrix with 2.1.5 ?

Read the document, too many plugins. impossible to remember all.

> span breaked on the invoke node of hystrix but not all, i can't find the reason, dose it associate with the hystrix pulgin version?

You have to debug the plugin by yourself. And find out why.
