### ISSUE TITLE
Support search and visualize alarms with tags

### ISSUE THREAD

**Issue by liqiangz** [apache/skywalking#6821]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

### Requirement or improvement
- Please describe your requirements or improvement suggestions.

The previous issue #5124 is only related to notification. I think we should also support searching based on tag  on the alarm page.

**Comment by wu-sheng** [comment]
Does this make sense to you? @Fine0830 @kezhenxu94 If so, I am going to merge the protocol update.

**Comment by kezhenxu94** [comment]
It sounds good to me.

**Comment by Fine0830** [comment]
It looks good to me.

**Comment by wu-sheng** [comment]
On the alarm page, we expect to see tags on query conditions and in the details.
