### ISSUE TITLE
node.js grpc client 

### ISSUE THREAD

**Issue by sunze4** [apache/skywalking#6822]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
我使用node.js grpc服务，想要接入skywalking。参考http协议。
span =  ContextManager.current.newExitSpan(serviceName, "professor_server", Component.UNKNOWN);
使用这个方法获取span。
span.inject()数据如下
ContextCarrier {
  key: 'sw8',
  traceId: undefined,
  segmentId: undefined,
  spanId: undefined,
  service: undefined,
  serviceInstance: undefined,
  endpoint: undefined,
  clientAddress: undefined,
  items: [ [Circular *1] ],
  encode: [Function (anonymous)],
  decode: [Function (anonymous)]
}
由于数据是undefined，grpc序列化时报错。

我想知道，node.js，怎么手动获取span。

**Comment by wu-sheng** [comment]
Use English on Github. And writing plugin is contributor responsibility. We are not guiding people step by step. Read the many existing plugins, and learn concepts of SkyWalking.
