### ISSUE TITLE
skywalking node.js grpc support

### ISSUE THREAD

**Issue by sunze4** [apache/skywalking#6825]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- I use node service to access skywalking. but skywalking-nodejs is not supported grpc. I want do it myself。

**Comment by sunze4** [comment]
const span = ContextManager.current.newExitSpan(operation, host, Component.HTTP);

**Comment by sunze4** [comment]
when I get a span .I get a span without data.like this:
ContextCarrier {
  key: 'sw8',
  traceId: undefined,
  segmentId: undefined,
  spanId: undefined,
  service: undefined,
  serviceInstance: undefined,
  endpoint: undefined,
  clientAddress: undefined,
  items: [ [Circular *1] ],
  encode: [Function (anonymous)],
  decode: [Function (anonymous)]
}

**Comment by sunze4** [comment]
ContextManager.current can not get the context used in node agent.
how can I get the context which used in node agent ,in node.js service.

**Comment by wu-sheng** [comment]
@kezhenxu94 Do we have a development doc for the nodejs agent? I am feeling this question basically is caused by both lacking basic SkyWalking/Tracing design concept and how to use APIs

**Comment by riskgod** [comment]
Very happy to see this issue, hopes node.js agent will support GRPC.
