### ISSUE TITLE
deploy failed on module receiver-proto in the version of 8.5.0

### ISSUE THREAD

**Issue by coki230** [apache/skywalking#6827]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- I deploy the 8.5.0 skywalking in my windows system it perfact well. bug when i deploy it in our centos system it block on receiver-proto modul, I check it pom file, and modify "<family>window</family>" to "<family>linux</family>". 
- now it said "Could not find artifact com.github.davidmoten:flatbuffers-compiler:zip:distribution-linux:1.12.0.1 ". but i can't find the artifact in the ali maven. where am wrong.

**Comment by coki230** [comment]
modify “<family>window</family>” to “<family>linux</family>”

**Comment by coki230** [comment]
<os>
                    <family>window</family>
                </os>

**Comment by wu-sheng** [comment]
I am not sure what you are doing. Deploying has nothing relating to find artifacts. It happens in compiling stage. 
Please be clear about what you are doing.

**Comment by kezhenxu94** [comment]
@coki230 you should not modify the `.pom` file, if you failed to compile on some linux platforms, please download the `flatc` compiler from https://github.com/davidmoten/flatbuffers/tree/master/flatbuffers-compiler/bin and use `-Dfbs.compiler=/path/to/your/local/flatc` in the `./mvnw` command

**Comment by coki230** [comment]
> @coki230 you should not modify the `.pom` file, if you failed to compile on some linux platforms, please download the `flatc` compiler from https://github.com/davidmoten/flatbuffers/tree/master/flatbuffers-compiler/bin and use `-Dfbs.compiler=/path/to/your/local/flatc` in the `./mvnw` comma
3Q for your advice. good luck for good people all life.

**Comment by coki230** [comment]
@kezhenxu94 3Q for your advice. good luck for good people all life.
