### ISSUE TITLE
Does skywalking want to query the total number of calls of a certain interface in a day?

### ISSUE THREAD

**Issue by kongdeling** [apache/skywalking#6833]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean SkyWalking wants? I am confused.

**Comment by kongdeling** [comment]
怎么用查询某个接口的一天的调用次数

**Comment by wu-sheng** [comment]
We don't provide that as default metrics. Search existing questions, this has been asked again and again.
