### ISSUE TITLE
Questions about Agent Sampling logic

### ISSUE THREAD

**Issue by honganan** [apache/skywalking#6836]
I have some questions about the agent sampling logic when I'm reading the code of `SamplingService.java` today:

1. I don't see the effect of `forceSampled()` method. It just increase the `samplingFactorHolder`, but the vacancy space it left can not be used by current request. The only effect it seems just making the sampling result count decrease 1 in current period, And the current request still need to compete for sampling in high concurrency scenario, it seems not so helpful for current request's sampling.
2. The `trySampling` method use CAS, In extreme situation, It may result in some requests be ignored but sum of  the sampled requests even less than the threshold set by `SAMPLE_N_PER_3_SECS` in this period. Will it?

### Background
I know the agent sampling exist to avoid extreme huge request make cpu and network overload. And the backend sampling to store a part of traces to reduce storage cost.
What I want to do is saving the error traces 100% while opening the backend sampling to save the storage cost. This is a common demand in distributed tracing system. 
As different service report data respectively in one request, they don't know if each other contains exception. 
The common practice is using downstream feedback mechanism. For example, if there is an invocation chain like: A -> B -> C, if C caught an exception and make it's segment be force sampled. Then it can set a flag in the response, B found the flag from the response and also set force sampling and then propagation the flag to A. This mechanism can promise the exception trace(except the branch of the invocation tree) be sampled 100% and it may be very helpful for problem troubleshooting.

Hope SkyWalking have this feature.

**Comment by wu-sheng** [comment]
Let me give you the conclusion first, the feedback chain would work. Think about how MQ and many async mechanisms work today in the distributed system. This is a bad mislead to the users saying, we could only sample the wrong request.

**Comment by wu-sheng** [comment]
And you are still seeing SkyWalking like it was 4 years ago, now, traces are affecting the topology and metrics analysis. All client sampling is recommended only when it has to be, due to performance impact. Otherwise, don't do client sampling.
Right now, in 2020 and 2021, k8s/micro-service/distributed-service is the trend and reality. Purely using tracing like enhanced logs would not be recommended.

**Comment by wu-sheng** [comment]
Back to the codes, `#forceSampled` is for making sure the trace continues when context exists and propagated from downstream. And you should know, we never declared `SAMPLE_N_PER_3_SECS` that N is an accurate number and must be kept.

**Comment by wu-sheng** [comment]
In the end, I think you are walking on the wrong road. If you want to reduce the storage load, try to activate sampling at the backend, but metrics should be accurate and consistent.
If no topology and metrics, actually, you don't need the APM. Trace records are not SkyWalking design goal, APM is.

**Comment by LiWenGu** [comment]
We also want to have this feature, but we are not to reduce storage load, but for two purposes:
1. Set a lower sampling rate to reduce the impact on client machine performance
2. When troubleshooting online problems, no abnormal trace will be missed

I see that this issue has joined the 8.6.0 milestone, but has been closed again.

**Comment by wu-sheng** [comment]
> We also want to have this feature, but we are not to reduce storage load, but for two purposes:
> 
> 1. Set a lower sampling rate to reduce the impact on client machine performance
> 2. When troubleshooting online problems, no abnormal trace will be missed
> 
> I see that this issue has joined the 8.6.0 milestone, but has been closed again.

We have explained the reasons. Unless you have something to fix our concerns, there is no further action to be taken.

**Comment by LiWenGu** [comment]
> Let me give you the conclusion first, the feedback chain would work. Think about how MQ and many async mechanisms work today in the distributed system. This is a bad mislead to the users saying, we could only sample the wrong request.

I don't quite understand the feedback chain implementation mechanism here.
But when I tried to implement 100% error trace collection in SkyWalking, there was a problem:
For example, A-> B-> C, when C does not return, because A and B do not know whether the trace is wrong, A and B need to keep the TracingContext information in memory all the time, which affects the machine memory.

**Comment by wu-sheng** [comment]
> But when I tried to implement 100% error trace collection in SkyWalking, there was a problem:
For example, A-> B-> C, when C does not return, because A and B do not know whether the trace is wrong, A and B need to keep the TracingContext information in memory all the time, which affects the machine memory.

We never said this should be done. Do you misunderstand something?

**Comment by LiWenGu** [comment]
I'm just discussing how to implement this feature in skywalking if possible

**Comment by wu-sheng** [comment]
> I'm just discussing how to implement this feature in skywalking if possible

From my understanding, if you consider MQ and async processes, this never works. So, this is a limited feature.

**Comment by wu-sheng** [comment]
> But when the all trace is called synchronously, there will also be the memory problems I mentioned.

You definitely have to cost as much as 100% sampling, as you never know what is the case. That is also we don't believe this could work efficiently. So, in the design level, **SkyWalking trust we make sure 100% sampling working on the agent side**.

**Comment by LiWenGu** [comment]
I have learned that if this feature is to be supported, these losses are inevitable in this case. Thanks.
