### ISSUE TITLE
[KONG] Skywalking agent plugin for Kong throw an exception

### ISSUE THREAD

**Issue by kasimLZ** [apache/skywalking#6839]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

I installed a skywalking plugin on my service in kong. I would like to use it to monitor my ES cluster. 

The skywalking configuraion like this.
```json
 "config": {
    "service_name": "Kong Service",
    "sample_ratio": 1,
    "namespace": null,
    "max_callback_time_spent": 5000,
    "service_instance_name": "Kong Service Instance",
    "backend_http_uri": "http://192.168.1.101:12800"
  }
```

I sure about that back end URL is accessible.

But when I switch on this plugin, the kong gateway will throw a error message like this:
```json
{
    "message": "An unexpected error occurred"
}
```

I checked  the proxy error log. follow this

```
2021/04/26 08:15:13 [error] 24#0: *254687 [kong] init.lua:271 [skywalking] ...uarocks/share/lua/5.1/kong/plugins/skywalking/tracer.lua:72: attempt to concatenate local 'namespace' (a nil value), client: 192.168.1.250, server: kong, request: "POST /myindex/_search HTTP/1.1", host: "192.168.1.1:9200"
```

**Comment by wu-sheng** [comment]
Which codes are you using? I don't think SkyWalking has a Kong plugin release.

**Comment by dmsolr** [comment]
I am sure Skywalking-Kong agent does not have these two configurations, `namespace` or `max_callback_time_spent`.

**Comment by kasimLZ** [comment]
I follow this document [README.md](https://github.com/apache/skywalking-kong/blob/master/README.md) to install the plugin.

I repackaged the image based on kong:2.4.0. This is my dockerfile:
```Dockerfile
FROM kong:2.4.0

RUN luarocks install kong-plugin-skywalking --local

ENV KONG_NGINX_HTTP_LUA_SHARED_DICT="tracing_buffer 128m"

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8001 8443

STOPSIGNAL SIGQUIT

CMD ["kong", "docker-start"]
```

Then I can see the Skywalking-Kong plugins in konga.  Did I install a wrong plugin?

**Comment by dmsolr** [comment]
Hi @kasimLZ 
I found two unnecessary items in the configurations you provided. You need to remove `namespace` and `max_callback_time_spent`. 
```
 "config": {
    "service_name": "Kong Service",
    "sample_ratio": 1,
    "service_instance_name": "Kong Service Instance",
    "backend_http_uri": "http://192.168.1.101:12800"
  }
```
