### ISSUE TITLE
skywalking 8.5.0 plugin.toolkit.log.grpc.reporter.server_host support cluster config?

### ISSUE THREAD

**Issue by netfreeperson** [apache/skywalking#6844]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Dose skywalking 8.5.0 plugin.toolkit.log.grpc.reporter.server_host support cluster config?

**Comment by wu-sheng** [comment]
No, it doesn't. There are many proxies available, you don't need the agent did this.
