### ISSUE TITLE
Issue running Plugin test on macos

### ISSUE THREAD

**Issue by divyakumarjain** [apache/skywalking#6846]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
- Which version of SkyWalking, OS, and JRE?
Skywalking 8.6 code on master branch, macos (Big Sur), JDK 1.8

- Which company or project?
Plugin test framework fails with run.sh failing to run sed command on macos

- What happened?
Run Plugin test on macos as per [link](https://github.com/apache/skywalking/blob/master/docs/en/guides/Plugin-test.md#local-test-and-pull-request-to-the-upstream) on macos. it fails with error such as "invalid command .". After debugging for some time found that sed command used on between 145-156 in run.sh is not compatible on macos.

Either the document needs to be updates to support linux only and remove macos or fix the run.sh script.

**Comment by kezhenxu94** [comment]
This is a known issue of the script.

**Comment by wu-sheng** [comment]
@divyakumarjain Welcome to submit a patch to fix this script issue.

**Comment by wallezhang** [comment]
@wu-sheng I submit a PR related to this issue, please help review the code at your convenience.
