### ISSUE TITLE
Can filter self-defined tags of local span in oal scripts?

### ISSUE THREAD

**Issue by coveyliu** [apache/skywalking#6853]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can filter self-defined tags of local span in oal scripts?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
I tagged a local span and then defined a metric using filter function filter the tag, but nothing happened
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
OAL is targeting metrics and the internal source concept. It has nothing directly relating to the trace or span. What do you want to do?
