### ISSUE TITLE
how can i understand cpu useage? it looks like incorrect

### ISSUE THREAD

**Issue by pope12389** [apache/skywalking#6857]
Please answer these questions before submitting your issue.

___
### Question

in infrastructure monitoring 
how can i understand cpu useage?
it always 0.0 
___
![image](https://user-images.githubusercontent.com/9252880/116229805-82198200-a789-11eb-9edb-c4954d9cd192.png)
here is the config:
![image](https://user-images.githubusercontent.com/9252880/116229938-9fe6e700-a789-11eb-958b-ba7fd5579195.png)

otel-collector-config:
![image](https://user-images.githubusercontent.com/9252880/116229997-b55c1100-a789-11eb-901a-f1ce834d58b5.png)

**Comment by wu-sheng** [comment]
@wankai123  Do you want to give an explanation?

**Comment by wankai123** [comment]
How many cores the VM has？It seems always idle. The CPU max usage is 100% * cores.
`rate('PT1M')`  is the per-second average rate of increase **in a minute**, and if the value is less than 1 there will show 0.
Could you make the CPU busier and use the command `top` in the OS to compare the CPU usage ？
And you can try replace `rate('PT1M')` to `irate()`.
Then I can found out whether this is a bug. @pope12389

**Comment by pope12389** [comment]
i've change the config to irate. 


![image](https://user-images.githubusercontent.com/9252880/116329805-aebbb100-a7fe-11eb-8299-139fe9d9bbd9.png)


![image](https://user-images.githubusercontent.com/9252880/116329581-41a81b80-a7fe-11eb-88b9-d4308c8afa60.png)

![image](https://user-images.githubusercontent.com/9252880/116329575-3ce36780-a7fe-11eb-96ce-3968bb6dc0ac.png)

here is the promethues collector info:
![image](https://user-images.githubusercontent.com/9252880/116329897-e0347c80-a7fe-11eb-9617-ff40c0d40800.png)

node exporter info:
node_cpu_seconds_total{cpu="0",mode="idle"} 815137.84
node_cpu_seconds_total{cpu="0",mode="iowait"} 10458.64
node_cpu_seconds_total{cpu="0",mode="irq"} 0
node_cpu_seconds_total{cpu="0",mode="nice"} 2.41
node_cpu_seconds_total{cpu="0",mode="softirq"} 6421.4
node_cpu_seconds_total{cpu="0",mode="steal"} 0
node_cpu_seconds_total{cpu="0",mode="system"} 26899.33
node_cpu_seconds_total{cpu="0",mode="user"} 82443.91
node_cpu_seconds_total{cpu="1",mode="idle"} 817822.83
node_cpu_seconds_total{cpu="1",mode="iowait"} 9163.18
node_cpu_seconds_total{cpu="1",mode="irq"} 0
node_cpu_seconds_total{cpu="1",mode="nice"} 2.27
node_cpu_seconds_total{cpu="1",mode="softirq"} 3993.8
node_cpu_seconds_total{cpu="1",mode="steal"} 0
node_cpu_seconds_total{cpu="1",mode="system"} 26800.13
node_cpu_seconds_total{cpu="1",mode="user"} 83231.37
node_cpu_seconds_total{cpu="2",mode="idle"} 817083.51
node_cpu_seconds_total{cpu="2",mode="iowait"} 8699.93
node_cpu_seconds_total{cpu="2",mode="irq"} 0
node_cpu_seconds_total{cpu="2",mode="nice"} 3.06
node_cpu_seconds_total{cpu="2",mode="softirq"} 3325.54
node_cpu_seconds_total{cpu="2",mode="steal"} 0
node_cpu_seconds_total{cpu="2",mode="system"} 26521.71
node_cpu_seconds_total{cpu="2",mode="user"} 84404.14
node_cpu_seconds_total{cpu="3",mode="idle"} 818108.08
node_cpu_seconds_total{cpu="3",mode="iowait"} 8813.03
node_cpu_seconds_total{cpu="3",mode="irq"} 0
node_cpu_seconds_total{cpu="3",mode="nice"} 2.38
node_cpu_seconds_total{cpu="3",mode="softirq"} 3131.57
node_cpu_seconds_total{cpu="3",mode="steal"} 0
node_cpu_seconds_total{cpu="3",mode="system"} 26872.19
node_cpu_seconds_total{cpu="3",mode="user"} 83934.8
node_cpu_seconds_total{cpu="4",mode="idle"} 819348.98
node_cpu_seconds_total{cpu="4",mode="iowait"} 8770.52
node_cpu_seconds_total{cpu="4",mode="irq"} 0
node_cpu_seconds_total{cpu="4",mode="nice"} 2.52
node_cpu_seconds_total{cpu="4",mode="softirq"} 3038.3
node_cpu_seconds_total{cpu="4",mode="steal"} 0
node_cpu_seconds_total{cpu="4",mode="system"} 26647.34
node_cpu_seconds_total{cpu="4",mode="user"} 83536.82
node_cpu_seconds_total{cpu="5",mode="idle"} 818377.95
node_cpu_seconds_total{cpu="5",mode="iowait"} 8682.65
node_cpu_seconds_total{cpu="5",mode="irq"} 0
node_cpu_seconds_total{cpu="5",mode="nice"} 2.83
node_cpu_seconds_total{cpu="5",mode="softirq"} 2979.97
node_cpu_seconds_total{cpu="5",mode="steal"} 0
node_cpu_seconds_total{cpu="5",mode="system"} 26828
node_cpu_seconds_total{cpu="5",mode="user"} 84234.19
node_cpu_seconds_total{cpu="6",mode="idle"} 818812.64
node_cpu_seconds_total{cpu="6",mode="iowait"} 8591.55
node_cpu_seconds_total{cpu="6",mode="irq"} 0
node_cpu_seconds_total{cpu="6",mode="nice"} 2.61
node_cpu_seconds_total{cpu="6",mode="softirq"} 2907.02
node_cpu_seconds_total{cpu="6",mode="steal"} 0
node_cpu_seconds_total{cpu="6",mode="system"} 26629.19
node_cpu_seconds_total{cpu="6",mode="user"} 84268.84
node_cpu_seconds_total{cpu="7",mode="idle"} 849867.47
node_cpu_seconds_total{cpu="7",mode="iowait"} 9926.45
node_cpu_seconds_total{cpu="7",mode="irq"} 0
node_cpu_seconds_total{cpu="7",mode="nice"} 2.36
node_cpu_seconds_total{cpu="7",mode="softirq"} 14627.28
node_cpu_seconds_total{cpu="7",mode="steal"} 0
node_cpu_seconds_total{cpu="7",mode="system"} 19884.98
node_cpu_seconds_total{cpu="7",mode="user"} 42339.94

**Comment by pope12389** [comment]
> How many cores the VM has？It seems always idle.
> The CPU max usage is 100% * cores.
> `rate('PT1M')` is the per-second average rate of increase **in a minute**, and if the value is less than 1 there will show 0.
> Could you make the CPU busier and use the command `top` in the OS to compare the CPU usage ？
> And you can try replace `rate('PT1M')` to `irate()`.
> Then I can found out whether this is a bug. @pope12389
https://github.com/apache/skywalking/issues/6857#issuecomment-828058898

**Comment by wankai123** [comment]
Thanks for the info, it seems a bug, I will find it out.

**Comment by fengrui1990** [comment]
I have the same problem,according to promethues rules:

 - name: cpu_total_percentage
    exp: (node_cpu_seconds_total * 100).tagNotEqual('mode' , 'idle').sum(['node_identifier_host_name']).rate('PT1M')
to:
  - name: cpu_total_percentage
    exp: 100 - (node_cpu_seconds_total * 100).tagEqual('mode' , 'idle').avg(['node_identifier_host_name']).rate('PT1M')
It works well,for reference.
