### ISSUE TITLE
Does the Meter data structure support users to dynamically create multiple thread pools to automatically collectt metric datas

### ISSUE THREAD

**Issue by 807801002** [apache/skywalking#6858]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does the Meter data structure support users to dynamically create multiple thread pools to automatically collectt metric datas?

The meter table structure only has entity_id, service_id, and no extended field to save the thread pool name dynamically to save user created thread pool.

 MAL also supports only fixed index names to YAML files and cannot dynamically generate index names based on multiple thread pools created by the user.
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
There is an open PR about thread monitoring, but he didn't finish it.
Multiple pools should be treated as labeled values, with using label key as pool name.
Make sense?
No monitoring system build dynamic indices, even we had, you can't set the UI.
