### ISSUE TITLE
The service ComboBox component of the UI does not show my service, but it does show my service in skywalking-tracing

### ISSUE THREAD

**Issue by aokinba** [apache/skywalking#6862]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
version:skywalking8.4.0-es7

- Which company or project?

- What happened?

The service ComboBox component of the UI does not show my service
![image](https://user-images.githubusercontent.com/6531769/116341308-3b706a00-a813-11eb-8ee7-7f421c51172f.png)

My ELF-SJL microsuit is displayed in tracking
![image](https://user-images.githubusercontent.com/6531769/116341368-622ea080-a813-11eb-9bde-2d8bc98c15b3.png)

Didn't I index of ELF - SJL elasticsearch
![image](https://user-images.githubusercontent.com/6531769/116341669-e84ae700-a813-11eb-8b86-421a6fcbef7f.png)

- **this issue didn't appear 2 days ago, it appeared yesterday, will it be an elasticsearch issue?Or where?**

thank you

**Comment by wu-sheng** [comment]
It is most likely your trace ttl is longer than metrics ttl. Then the metadata is removed due to metric ttl.
