### ISSUE TITLE
can i monitor windows metrics by using prometheus windows_exportor

### ISSUE THREAD

**Issue by pope12389** [apache/skywalking#6866]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question

___
### Question
- What do you want to know?
can i monitor windows metrics by using prometheus windows_exportor. 
i tried to make it work but nothing happened !
i found the metrics is different from linux:

windows_cpu_cstate_seconds_total{core="0,0",state="c1"} 698215.9164874
windows_cpu_cstate_seconds_total{core="0,0",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,0",state="c3"} 0
windows_cpu_cstate_seconds_total{core="0,1",state="c1"} 699348.0720012999
windows_cpu_cstate_seconds_total{core="0,1",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,1",state="c3"} 0
\# HELP windows_cpu_dpcs_total Total number of received and serviced deferred procedure calls (DPCs)
\# TYPE windows_cpu_dpcs_total counter
windows_cpu_dpcs_total{core="0,0"} 6.043656e+06
windows_cpu_dpcs_total{core="0,1"} 1.6283996e+07
\# HELP windows_cpu_idle_break_events_total Total number of time processor was woken from idle
\# TYPE windows_cpu_idle_break_events_total counter
windows_cpu_idle_break_events_total{core="0,0"} 1.32701757e+08
windows_cpu_idle_break_events_total{core="0,1"} 1.24128133e+08
\# HELP windows_cpu_interrupts_total Total number of received and serviced hardware interrupts
\# TYPE windows_cpu_interrupts_total counter
windows_cpu_interrupts_total{core="0,0"} 1.8000451e+08
windows_cpu_interrupts_total{core="0,1"} 2.15803753e+08
\# HELP windows_cpu_parking_status Parking Status represents whether a processor is parked or not
\# TYPE windows_cpu_parking_status gauge
windows_cpu_parking_status{core="0,0"} 0
windows_cpu_parking_status{core="0,1"} 0
\# HELP windows_cpu_processor_performance Processor Performance is the average performance of the processor while it is executing instructions, as a percentage of the nominal performance of the processor. On some processors, Processor Performance may exceed 100%
\# TYPE windows_cpu_processor_performance gauge
windows_cpu_processor_performance{core="0,0"} 1.6463450154e+12
windows_cpu_processor_performance{core="0,1"} 1.53011138335e+12
\# HELP windows_cpu_time_total Time that processor spent in different modes (idle, user, system, ...)
\# TYPE windows_cpu_time_total counter
windows_cpu_time_total{core="0,0",mode="dpc"} 41.3125
windows_cpu_time_total{core="0,0",mode="idle"} 708528.796875
windows_cpu_time_total{core="0,0",mode="interrupt"} 229.984375
windows_cpu_time_total{core="0,0",mode="privileged"} 2752.765625
windows_cpu_time_total{core="0,0",mode="user"} 3000.703125
windows_cpu_time_total{core="0,1",mode="dpc"} 457.328125
windows_cpu_time_total{core="0,1",mode="idle"} 708977.90625
windows_cpu_time_total{core="0,1",mode="interrupt"} 507.71875
windows_cpu_time_total{core="0,1",mode="privileged"} 2859.140625

**Comment by wu-sheng** [comment]
You need another new OC receiver rule for it.
