### ISSUE TITLE
[Chore] upgrade dependencies to get rid of jcenter

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#6867]
jcenter is going to shut down according to https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ , but we still have some (transitive) dependencies that downloaded from jcenter, we should find them out and point the download address to maven central.

This should be done before 1st, May, 2021

**Comment by wu-sheng** [comment]
Do you know which dependencies? I think we should download from maven central in default.

**Comment by kezhenxu94** [comment]
I know one of the transitive dependencies of gRPC (netty) is downloaded from jcenter, jctools-core

**Comment by wu-sheng** [comment]
> I know one of the transitive dependencies of gRPC (netty) is downloaded from jcenter, jctools-core

OK, does this mean we need to upgrade some versions? It seems we don't depend on jcenter directly.

**Comment by kezhenxu94** [comment]
> > I know one of the transitive dependencies of gRPC (netty) is downloaded from jcenter, jctools-core
> 
> OK, does this mean we need to upgrade some versions?

It may need a version upgrade, but it's also possible to replace the download URL with maven, I I didn't dive into this though.

>  It seems we don't depend on jcenter directly.

Yes for sure, but as I said, the transitive dependencies do, and they have to be downloaded from where they're declared.

**Comment by wu-sheng** [comment]
> This should be done before 1st, May, 2021

This passed, it seems nothing broken. Should we still track this?
