### ISSUE TITLE
UI problem: Database and Infrastructure monitoring

### ISSUE THREAD

**Issue by bpadulareply** [apache/skywalking#6869]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

- Which version of SkyWalking, OS, and JRE?
Apache SkyWalking 8.4.0
![versions](https://user-images.githubusercontent.com/83359567/116433894-37137380-a84a-11eb-8953-a0bb6e971319.PNG)

- What happened?

log error
![Error](https://user-images.githubusercontent.com/83359567/116436025-472c5280-a84c-11eb-81f4-8bfc15549189.PNG)

I am trying to setup a working enviroment for Apache skywalking. I successfully instrumented a Java agent running in a tomcat10 application.
Next I've tried to implement an infrastucture monitoring following this guide: [https://skywalking.apache.org/blog/2021-02-07-infrastructure-monitoring/](url)
I successfully installed the Prometheus exporter and a local instance of OpenTelemetry (at first I used docker but had some problem with networking). As you can see from the logs the enviroment seems to be working.
Unfortunately I can't see the vm on my UI, i've tried different configuration or test but I had no success.

_The problem that I want to solve:_
![noVmUI](https://user-images.githubusercontent.com/83359567/116435592-d08f5500-a84b-11eb-904a-2e3793386b14.PNG)

_Prometheus on remote WindowsMachine_ 
![prometheusMetrics](https://user-images.githubusercontent.com/83359567/116435091-4c3cd200-a84b-11eb-8490-0e4faadf8483.PNG)

_Metrics acquired from otel_
![OtelMetrics](https://user-images.githubusercontent.com/83359567/116435221-6aa2cd80-a84b-11eb-9684-8645583b526e.PNG)

_Active connection (otel->skywalkingOAP, otel->Prometheus)_
![activeConnections](https://user-images.githubusercontent.com/83359567/116435363-8dcd7d00-a84b-11eb-91f7-ba538e25c422.PNG)

_Otel configuration_
![OtelConf](https://user-images.githubusercontent.com/83359567/116435741-fddc0300-a84b-11eb-8b2a-52a0ca3825de.PNG)

_application.yaml file_
![SKWcoreConf](https://user-images.githubusercontent.com/83359567/116435848-1815e100-a84c-11eb-85e0-0b354a9e6952.PNG)
![SKWotelConf](https://user-images.githubusercontent.com/83359567/116435861-1b10d180-a84c-11eb-8cc7-e4044585a187.PNG)

_webapp.yaml file_
![SKWwebappConf](https://user-images.githubusercontent.com/83359567/116435896-249a3980-a84c-11eb-8017-40ff22caad5a.PNG)

Lastly I moved to a mysql db agent: I used this configuration: [https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md](url)
I activate the mysql module in the selector, downloaded the driver (mysql-connector-java-5.1.46.jar) as required and I have tested all the db connection that are working properly right now.

_application.yaml file_
![SKWmysqlConf](https://user-images.githubusercontent.com/83359567/116436630-e05b6900-a84c-11eb-9d5d-7776a82db861.PNG)

Unfortunately I have the same exact problem as for the previous agent, do you get any suggestion on what to do in order to see the vm or the database in the SkyWalking UI? Is the webapp error related to it? I couldn't find anything useful about this error.

**Comment by wu-sheng** [comment]
First about database metrics, currently, database-related metrics are from your language agent detection. If you can see spans of trace include DB access and SQL in it. You will see the metrics.
`application.yaml`'s MySQL is indicating SkyWalking requires MySQL as storage, nothing about monitoring.

**Comment by wu-sheng** [comment]
I don't think our OS monitoring has Windows related setup, it should be a Linux kernel. If you want to monitor Windows, you have to learn and write MAL as we provided in default, https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/otel-oc-rules/vm.yaml

Read the documentation about MAL and take reference to what we gave.

At last, how to use docker and how to make the network connectable for docker env is the capability and skill you should learn. Or if you don't like docker, you could use OpenTelemetry's binary to do so.
