### ISSUE TITLE
instance_jvm_memory_noheap_max  is showing a negative value on UI Instance dashboard

### ISSUE THREAD

**Issue by whohasthis** [apache/skywalking#6870]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking 8.4.0 running on kubernetes , JRE 1.8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
I did not find a way to insert pictures here, anyway, the instance_jvm_memory_noheap_max is showing a negative value 
-9.5367431640625e-7

Is there a way to correct this on configuration level or is this a code bug ?
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think you should debug the agent in your specific JDK and find out why. You could see on our demo env, the value is positive and normal.
There is always a bug existing, but the environment is yours. So working on that and contribute to the community.
