### ISSUE TITLE
Class Information with trace 

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6871]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

Dear Sir,

Is there any way if we can get Class, detailed API calls and Call trace information on this UI. 

![Traces](https://user-images.githubusercontent.com/75727262/116518038-616a3d00-a8ed-11eb-9357-e713e0599723.png)

Also can we get Profile enabled for all the endpoint to get the maximum information for debugging purpose.  Kindly suggest.

Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
> Is there any way if we can get Class, detailed API calls and Call trace information on this UI.

What do you mean on the UI? Do you mean in the span tags or something?

**Comment by wu-sheng** [comment]
> Also can we get Profile enabled for all the endpoint to get the maximum information for debugging purpose

That would crash and slow down your application in a disastrous way. A lot of profiling tools out there could do this. APM is designed for product env, so performance impact should be minimal and acceptable.
Only profiling codes when you can't have the idea from traces, logs and metrics.

**Comment by JayeshMuley** [comment]
Sorry replying late as testing the version 8.5. 

Just talking about the exception and call tree information if we can get on Trace UI for each Endpoint. For example see the attachment. Kindly advice.

![CallTraceInfo](https://user-images.githubusercontent.com/75727262/116556763-71991100-a91b-11eb-946c-f761557a85df.png)

![CallTree](https://user-images.githubusercontent.com/75727262/116556655-5201e880-a91b-11eb-9a53-899bc99beccf.png)

**Comment by wu-sheng** [comment]
> Just talking about the exception and call tree information if we can get on Trace UI for each Endpoint. For example, see the attachment. Kindly advice.

If you activate some optional plugins, such as Spring annotations, even custom enhancement plugin.
Like I described, I don't think what classes are not the correct usage. You should not try to locate method-level performance. Your application in the real will overload easily.
