### ISSUE TITLE
How to store trace analysis metrics data into promethues

### ISSUE THREAD

**Issue by ayumiono** [apache/skywalking#6872]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Backendground:
My company use prometheus to monitor k8s node and other devices, and use prometheus alertmanager to do alert jobs, so i want to store skywalking metrics data into promethues to keep prometheus alertmanager still working for skywalking metrics.

However, it turns out to be pretty harder than imagination to do this, because skywalking metrics data may change anytime the new trace event come and on the other hand, prometheus does not support update data by timestamp not like elasticsearch or influxdb. it seems to be impossible to implement such a prometheus storage module

it is really appreciated if anyone can provide me with any idea, thx!!!

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think your idea is correct. It is impossible. If they are so closed, we should not build SkyWalking after all. But clearly, APM is a much larger thing than Prometheus told people.

Read this if you want to learn more. Even about metrics, Prometheus can't support many cases when you treat it like an APM rather as a tool.
https://skywalking.apache.org/blog/2020-08-11-observability-at-scale/
