### ISSUE TITLE
Add fluctuation function in the alarm core

### ISSUE THREAD

**Issue by gtahubb** [apache/skywalking#6875]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- How can the alarm function know that the traffic of an endpoint or all endpoints drops instantaneously within a period of time

**Comment by wu-sheng** [comment]
I think you need a fluctuation function to check the trend, we don't have that for now. But endpoint level metrics check is a very expensive in-memory cost. But this will still be useful at the service or instance level.

**Comment by gtahubb** [comment]
> I think you need a fluctuation function to check the trend, we don't have that for now. But endpoint level metrics check is a very expensive in-memory cost. But this will still be useful at the service or instance level.

Can only adding this feature to the service Load (CPM-calls per minute) indicator in the service can reduce memory overhead?

**Comment by wu-sheng** [comment]
> > I think you need a fluctuation function to check the trend, we don't have that for now. But endpoint level metrics check is a very expensive in-memory cost. But this will still be useful at the service or instance level.
> 
> Can only adding this feature to the service Load (CPM-calls per minute) indicator in the service can reduce memory overhead?

Once you are using service-level metrics, you are safe. I don't say endpoint 100% means OOM, but you should understand there is a risk.

**Comment by gtahubb** [comment]
> > > I think you need a fluctuation function to check the trend, we don't have that for now. But endpoint level metrics check is a very expensive in-memory cost. But this will still be useful at the service or instance level.
> > 
> > 
> > Can only adding this feature to the service Load (CPM-calls per minute) indicator in the service can reduce memory overhead?
> 
> Once you are using service-level metrics, you are safe. I don't say endpoint 100% means OOM, but you should understand there is a risk.

That's right. Thanks
