### ISSUE TITLE
UI dashboard config: `independentSelector` not available.

### ISSUE THREAD

**Issue by wankai123** [apache/skywalking#6878]
- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking 8.5.0 & master

- What happened?
When I config the dashboard panel and select `comment selectors` the selection seems not to work, the panel does not show any metrics. I reopen the panel to edit, it's still `self selectors`.

![image](https://user-images.githubusercontent.com/16773043/116661951-c003e980-a9c7-11eb-8a93-2c658de407b7.png)

I export the template and found:

![image](https://user-images.githubusercontent.com/16773043/116662993-14f42f80-a9c9-11eb-8333-68708d32a1d5.png)
It's should be `"independentSelector": false`, not a String.

Impact:
It's will impact the new dashboard configuration or edit an old one.
And users could export the wrong UI template.

**Comment by wu-sheng** [comment]
@wankai123 Any existing template has this issue? AFAIK, all of them are exported from UI rather than writing manually.

**Comment by wankai123** [comment]
No. I check some UI templates from the source code, the issue seems from version 8.5.0. And if they don't re-edit the configuration, it's could work well.

**Comment by wu-sheng** [comment]
> No. I checked some UI templates from the source code, the issue seems from version 8.5.0. And if they don't re-edit the configuration, it's could work well.

Cool. Good to know. @hailin0 @zhaoyuguang As you are adding a dashboard to 3rd ecosystem, please be aware of this.

**Comment by wu-sheng** [comment]
@Fine0830 Please sync the submodule. @wankai123 I think you could verify now.

**Comment by wankai123** [comment]
Rechecked after updated UI.
Panel edit works well, export template correct. 

![image](https://user-images.githubusercontent.com/16773043/116768073-a1086480-aa66-11eb-9b54-341d7b35cf6f.png)
![image](https://user-images.githubusercontent.com/16773043/116768142-107e5400-aa67-11eb-8e6a-c9b276e2e2a2.png)
@Fine0830 @wu-sheng
