### ISSUE TITLE
[Client-JS] Skywalking-Client-JS supports mini program applications

### ISSUE THREAD

**Issue by 807801002** [apache/skywalking#6886]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does Skywalking - Client-JS support WeChat applets?I imported skywalking-client-js in main.js,it prompts 'Cannot read property 'webpackHotUpdate' of undefined',Is it incompatible?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
`WeChat applets`? I think this is new to us. That plugin is designed for browser, rather than applet.
@Fine0830 Any experience with that?

**Comment by 807801002** [comment]
I created the WeChat Applet by uni-app framework, which is built by VueJs, also like a Chromium App, but it is a mobile embedded chromium, Something is different with PC Chrome I think.

**Comment by wu-sheng** [comment]
Are the framework open sourced? We need something to evaluate. And even that, @Fine0830 will make the call whether this is an expected use case.

**Comment by 807801002** [comment]
Yes, see the official website https://uniapp.dcloud.io/, By the way, my project can send data to the oap-server when I visited it by PC Chrome browser,but it reported error when I visited it by WeChat dev simulator, the error is 'Cannot read property 'webpackHotUpdate', which is mentioned above

**Comment by wu-sheng** [comment]
There is no guarantee, let's see whether we have time to take care, or should take care.
Like all of our agents, we recommend users debug and try to fix it by themselves. This is how open source works.

**Comment by Fine0830** [comment]
Now, `Client-js` doesn't support any mini programs, including WeChat, DingTalk, Alipay. It supports only Web Applications.  From my perspectives, monitor mini programs need a new module rather than being compatible with Web applications in a common module. If we have source and time to take care, we can do this. Welcome to contribute.

**Comment by Fine0830** [comment]
> `WeChat applets`? I think this is new to us. That plugin is designed for browser, rather than applet.
> @Fine0830 Any experience with that?

Uhh! I have less experience.

**Comment by wu-sheng** [comment]
@Fine0830 If you have other agenda or interest, we definitely could skip this. We don't have to support anything.

**Comment by Fine0830** [comment]
Got it.

**Comment by wu-sheng** [comment]
Ping @Jtrust

**Comment by Fine0830** [comment]
@Jtrust I remember you have developed mini program applications before, you should be more suitable for developing this than me. Please feel free to ping me, if I could help you.

**Comment by wu-sheng** [comment]
@Jtrust plans to work about this direction at this repo, https://github.com/SkyAPM/applet-monitor.

Notice, this would be out of ASF, so, no discussion here.

**Comment by Jorkins** [comment]
支持小程序接入吗？
