### ISSUE TITLE
 call statistics of interface

### ISSUE THREAD

**Issue by githubcheng2978** [apache/skywalking#6887]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
display the call statistics of interface

- Which company or project?
  spring-mvc

- What happened?
 in sykwalking-ui cannot display the call statistics of interface , just only display interface trace.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Again, this kind of description means nothing.
This is open source community, not commercial customer service.
You said nothing showed, so?
