### ISSUE TITLE
Visualize events on the alarm page.

### ISSUE THREAD

**Issue by chenmudu** [apache/skywalking#6889]
- [x] Requirement
- [x] Feature or performance improvement

___

I changed the query alarm logic in OAP Server and now need to add the newly added field `events` to the return value.

For all of this, here:  

- issue: #6888

- [the pr web link](https://github.com/apache/skywalking/pull/6888/files)

Thanks a lot.

**Comment by wu-sheng** [comment]
@Fine0830 We enhanced the content of the alarm a little due to #6888. So, we should add events to the alarm pop-up box.
It is better you could visualize them with a graph.
