### ISSUE TITLE
Support Windows monitoring

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6891]
We have Linux monitoring, metrics collected by Prometheus and Zabbix agents. Some people in the community are asking about monitoring Windows OS, which is not very popular in service backend deployment, but still have some.
If someone new to SkyWalking or anything, want to take a reference from existing Linux monitoring and add this feature. We are welcome to accept.

**Comment by dmsolr** [comment]
So crazy but I like it. :)
