### ISSUE TITLE
skywalking-client-js for SPA

### ISSUE THREAD

**Issue by impavido-7** [apache/skywalking#6892]
I am working on a Single Page Application developed on polymer and I am using skywalking-client-js. But I am getting the same values for the redirectTime, dnsTime and so on for each and every URL,

**Comment by wu-sheng** [comment]
If you want helps, you need to provide more information or debug locally.
Please learn how to ask questions at open source project.

**Comment by impavido-7** [comment]
I am really sorry Sir,....To be more precise with the question, I am using skywalking like this

ClientMonitor.register({
    collector: 'http://127.0.0.1:8080',
    service: 'browser-app',
    serviceVersion: '1.0.0',
    pagePath: location.href,
    enableSPA: true,
    useFmp: true
  });

And in the index.js file in skywalking-client-js/lib, I console logged the data like this 

Report.prototype.sendByXhr = function (data) {
  delete data.collector;
  if (!this.url) {
    return;
  }
  console.log(data);
}

This data, I am getting the same .....

Hope I provided some information. If still the question looks stupid, I am sorry

**Comment by wu-sheng** [comment]
The key of a question is providing a way to reproduce steps and codes. What you do or not do, we can't tell as we know nothing about your private codes. Don't ask like we know all possibilities, clearly, we are not.
Our support is limited, not customer service.
