### ISSUE TITLE
Can Spring RestTemplate work?

### ISSUE THREAD

**Issue by makefriend8** [apache/skywalking#6893]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ *] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking master     windows   openjdk version "1.8.0_242"
- What happened?
code is very simple
```
@SpringBootApplication
public class MessagingStompWebsocketApplication {
	public static void main(String[] args) {
		RestTemplate restTemplate=new RestTemplate();
		String result = restTemplate.getForObject("http://192.168.2.333:8080/", String.class);
		System.out.println(result);
	}
}
```
and I run 
```
java -jar build/libs/myjar.jar -javaagent:skywalking-agent.jar
```
I user wireshark to catch the packet.The result is right, But no http head sw8 is added.

**Comment by wu-sheng** [comment]
Read at least the first line of the introduction.
>SkyWalking: an APM(application performance monitor) system, especially designed for microservices, cloud native and container-based architectures.

You are not running a service at all.

**Comment by makefriend8** [comment]
I use  https://github.com/spring-guides/gs-spring-boot.git
and 
```
@RestController
public class HelloController {

	@RequestMapping("/")
	public String index() {
		RestTemplate restTemplate=new RestTemplate();
		String result = restTemplate.getForObject("http://192.168.2.333:8080/", String.class);
		System.out.println(result);
		return "Greetings from Spring Boot!";
	}

}
``` 
and everthing is the same.

**Comment by wu-sheng** [comment]
We wouldn't debug your codes for you if you want to find our test codes, they ar here, https://github.com/apache/skywalking/tree/master/test/plugin/scenarios

**Comment by makefriend8** [comment]
Thank you.

**Comment by mikhaeljonathan** [comment]
i know it's too late, i had the same problem (I'm using resttemplate 6.x) but already found the solution, you can use optional plugin

just copy optional-plugins/apm-resttemplate-6.x-plugin-9.3.0.jar to plugins and restart your service

https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/supported-list/
