### ISSUE TITLE
Dynamically changing the Alarm Threshold not picked up. 

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6896]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

I am using Skywalking 8.5 and need to change the alarm setting dynamically, And for this i changed the Service Instance Response Time Rule Threshold value. But it didn't picked up . 

As per the document alarm.default.alarm-settings this needs to be set. But not sure how this parameter to be set in Application.yml, so that dynamic changes can be reflected. 

Please guide.

Thanks and Regards,
Jayesh Muley

**Comment by wu-sheng** [comment]
I am not sure about your question. `Application.yml` has nothing related to the alarm. And the dynamic alarm setting is actually overriding the whole alarm context. 

> As per the document alarm.default.alarm-settings this needs to be set

The value is the latest content of all alarm rules. Same format as `alarm-settings.yml`.

**Comment by JayeshMuley** [comment]
This means the Alarm should picked up the latest value setup in alarm-setting.yml.  But in my case I need to restart OAP server in order to reflect the latest value.

**Comment by wu-sheng** [comment]
> This means the Alarm should picked up the latest value setup in alarm-setting.yml. But in my case I need to restart OAP server in order to reflect the latest value.

No, it doesn't mean that. The dynamic content should be updated through the dynamic config center. Not through the original file. https://skywalking.apache.org/docs/main/v8.5.0/en/setup/backend/dynamic-config/
