### ISSUE TITLE
Purpose of server logs pointing to china servers part of config

### ISSUE THREAD

**Issue by arimon-arvind-das** [apache/skywalking#6898]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [discussion ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The APM jar that comes with skywalking, while starting it prints server locations from china.

 Merging document (no matchers set): {azure={service={endpoints={cn={aadSigninUri=https://login.partner.microsoftonline.cn/, aadGraphApiUri=https://graph.chinacloudapi.cn/, aadKeyDiscoveryUri=https://login.partner.microsoftonline.cn/common/discovery/keys, aadMembershipRestUri=https://graph.chinacloudapi.cn/me/memberOf?api-version=1.6}, global={aadSigninUri=https://login.microsoftonline.com/, aadGraphApiUri=https://graph.windows.net/, aadKeyDiscoveryUri=https://login.microsoftonline.com/common/discovery/keys, aadMembershipRestUri=https://graph.windows.net/me/memberOf?api-version=1.6}}}}}

What is the purpose of them being there ?
___
### Bug
- Which version of SkyWalking, OS, and JRE? Skywalking 8.5.0 ,JDK 8

- Which company or project?
NA
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
Start the jar with the apm agent and it prints the above information, doubtful of what is being shared on those endpoints.
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Could you provide more details? I am not aware of this kind of thing on purpose. I can't find the logs coded like this.

**Comment by arimon-arvind-das** [comment]
Hi @wu-sheng I validated this again with my teammate, we looked more closely in the logs, looks like this information is coming up from the azure configurations. We are still not sure how these urls are framed but we will look into this issue. 
Meanwhile this can be closed, does not seem to be with apache skywalking.
