### ISSUE TITLE
SpringcloudGateway can't get traceId

### ISSUE THREAD

**Issue by woshishitou** [apache/skywalking#6900]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why I can't get traceId? And how can I get it in gateway?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
My code is below

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Skywalking: 8.4
SpringcloudGateway: 2.1.1
Springcloud: Greenwich.SR1 
Springboot: 2.1.6

**Comment by woshishitou** [comment]
`package com.example.gatewaydemo.filter;

import org.apache.skywalking.apm.toolkit.trace.TraceContext;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.GlobalFilter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.Ordered;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

@Configuration
public class FilterConfig {

    @Bean
    public GlobalFilter b() {
        return new BFilter();
    }

    public class BFilter implements GlobalFilter, Ordered {

        @Override
        public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
			// 这里获取到的traceId是N/A
            exchange.getResponse().getHeaders().set("tid", TraceContext.traceId());
            return chain.filter(exchange).then(Mono.fromRunnable(() ->
            {
				// 这里获取到的也是N/A
                String traceId2 = TraceContext.traceId();
                System.out.println("traceId:" + traceId2);
            }));
        }

        @Override
        public int getOrder() {
            return 1;
        }
    }

}
`

**Comment by woshishitou** [comment]
`
package com.example.gatewaydemo.filter;

import org.apache.skywalking.apm.toolkit.trace.TraceContext;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.GlobalFilter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.Ordered;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

@Configuration
public class FilterConfig {

    @Bean
    public GlobalFilter b() {
        return new BFilter();
    }

    public class BFilter implements GlobalFilter, Ordered {

        @Override
        public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
			// 这里获取到的traceId是N/A
            exchange.getResponse().getHeaders().set("tid", TraceContext.traceId());
            return chain.filter(exchange).then(Mono.fromRunnable(() ->
            {
				// 这里获取到的也是N/A
                String traceId2 = TraceContext.traceId();
                System.out.println("traceId:" + traceId2);
            }));
        }

        @Override
        public int getOrder() {
            return 1;
        }
    }

}

`

**Comment by woshishitou** [comment]
`
package com.example.gatewaydemo.filter;

import org.apache.skywalking.apm.toolkit.trace.TraceContext;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.GlobalFilter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.Ordered;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

@Configuration
public class FilterConfig {

    @Bean
    public GlobalFilter b() {
        return new BFilter();
    }

    public class BFilter implements GlobalFilter, Ordered {

        @Override
        public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
			// The value here is N/A
            exchange.getResponse().getHeaders().set("tid", TraceContext.traceId());
            return chain.filter(exchange).then(Mono.fromRunnable(() ->
            {
				// The value here is also N/A
                String traceId2 = TraceContext.traceId();
                System.out.println("traceId:" + traceId2);
            }));
        }

        @Override
        public int getOrder() {
            return 1;
        }
    }

}

`

**Comment by wu-sheng** [comment]
We never said you could always have trace id. You misunderstand the feature I think.

**Comment by woshishitou** [comment]
https://github.com/apache/skywalking/issues/3891
But he got the value here，we use the same method.

**Comment by woshishitou** [comment]
Is that what I'm getting wrong？

**Comment by wu-sheng** [comment]
Gateway has a complex thread model, you only could get value when your codes and skywalking instrument codes sharing thread.

**Comment by woshishitou** [comment]
Although I don't quite understand, but thank you for your explanation

**Comment by 504099993** [comment]
> `
> 包com.example.gatewaydemo.filter;
> 
> 导入org.apache.skywalking.apm.toolkit.trace.TraceContext;
> 导入org.springframework.cloud.gateway.filter.GatewayFilterChain;
> 导入org.springframework.cloud.gateway.filter.GlobalFilter;
> 导入org.springframework.context.annotation.Bean;
> 导入org.springframework.context.annotation.Configuration;
> 导入org.springframework.core.Ordered;
> 导入org.springframework.web.server.ServerWebExchange;
> 导入reactor.core.publisher.Mono;
> 
> @configuration
> 公共类FilterConfig {
> 
> ```
> @Bean
> public GlobalFilter b() {
>     return new BFilter();
> }
> 
> public class BFilter implements GlobalFilter, Ordered {
> 
>     @Override
>     public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
> 		// The value here is N/A
>         exchange.getResponse().getHeaders().set("tid", TraceContext.traceId());
>         return chain.filter(exchange).then(Mono.fromRunnable(() ->
>         {
> 			// The value here is also N/A
>             String traceId2 = TraceContext.traceId();
>             System.out.println("traceId:" + traceId2);
>         }));
>     }
> 
>     @Override
>     public int getOrder() {
>         return 1;
>     }
> }
> ```
> 
> }
> 
> `

Hello, I also encountered this problem. Using TraceContext.traceId() in the gateway, the traceId cannot be obtained. How did you solve it?

**Comment by ralphgj** [comment]
Try to get traceid by implementing method of `HttpHeadersFilter#filter`

> > `
> > 包com.example.gatewaydemo.filter;
> > 导入org.apache.skywalking.apm.toolkit.trace.TraceContext;
> > 导入org.springframework.cloud.gateway.filter.GatewayFilterChain;
> > 导入org.springframework.cloud.gateway.filter.GlobalFilter;
> > 导入org.springframework.context.annotation.Bean;
> > 导入org.springframework.context.annotation.Configuration;
> > 导入org.springframework.core.Ordered;
> > 导入org.springframework.web.server.ServerWebExchange;
> > 导入reactor.core.publisher.Mono;
> > @configuration
> > 公共类FilterConfig {
> > ```
> > @Bean
> > public GlobalFilter b() {
> >     return new BFilter();
> > }
> > 
> > public class BFilter implements GlobalFilter, Ordered {
> > 
> >     @Override
> >     public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
> > 		// The value here is N/A
> >         exchange.getResponse().getHeaders().set("tid", TraceContext.traceId());
> >         return chain.filter(exchange).then(Mono.fromRunnable(() ->
> >         {
> > 			// The value here is also N/A
> >             String traceId2 = TraceContext.traceId();
> >             System.out.println("traceId:" + traceId2);
> >         }));
> >     }
> > 
> >     @Override
> >     public int getOrder() {
> >         return 1;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > `
> 
> Hello, I also encountered this problem. Using TraceContext.traceId() in the gateway, the traceId cannot be obtained. How did you solve it?

**Comment by woshishitou** [comment]
> > `
> > 包com.example.gatewaydemo.filter;
> > 导入org.apache.skywalking.apm.toolkit.trace.TraceContext;
> > 导入org.springframework.cloud.gateway.filter.GatewayFilterChain;
> > 导入org.springframework.cloud.gateway.filter.GlobalFilter;
> > 导入org.springframework.context.annotation.Bean;
> > 导入org.springframework.context.annotation.Configuration;
> > 导入org.springframework.core.Ordered;
> > 导入org.springframework.web.server.ServerWebExchange;
> > 导入reactor.core.publisher.Mono;
> > @configuration
> > 公共类FilterConfig {
> > ```
> > @Bean
> > public GlobalFilter b() {
> >     return new BFilter();
> > }
> > 
> > public class BFilter implements GlobalFilter, Ordered {
> > 
> >     @Override
> >     public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
> > 		// The value here is N/A
> >         exchange.getResponse().getHeaders().set("tid", TraceContext.traceId());
> >         return chain.filter(exchange).then(Mono.fromRunnable(() ->
> >         {
> > 			// The value here is also N/A
> >             String traceId2 = TraceContext.traceId();
> >             System.out.println("traceId:" + traceId2);
> >         }));
> >     }
> > 
> >     @Override
> >     public int getOrder() {
> >         return 1;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > `
> 
> Hello, I also encountered this problem. Using TraceContext.traceId() in the gateway, the traceId cannot be obtained. How did you solve it?

Hello，I got the traceid through reflection. Through debug, we can see that there is the traceId we need in the exchange object
![image](https://user-images.githubusercontent.com/22254487/132274359-3db30544-88d3-4d6a-8fcb-8dbd1c2812ff.png)

**Comment by woshishitou** [comment]
There are related classes in the skywalking source code in this picture. 
Finally, you can get the traceid through the method getReadablePrimaryTraceId() in interface AbstractTracerContext.

**Comment by woshishitou** [comment]
There are related classes in the skywalking source code in this picture.
Finally, you can get the traceid through the method getReadablePrimaryTraceId() in interface AbstractTracerContext.
![image](https://user-images.githubusercontent.com/22254487/132275108-11cbe067-5e72-4570-8630-672d9134aa20.png)

**Comment by xiaozuo2020** [comment]
> There are related classes in the skywalking source code in this picture. Finally, you can get the traceid through the method getReadablePrimaryTraceId() in interface AbstractTracerContext. ![image](https://user-images.githubusercontent.com/22254487/132275108-11cbe067-5e72-4570-8630-672d9134aa20.png)

hello could you show me the code? I try to get the traceID by reflection,but i am failed

**Comment by woshishitou** [comment]
> 

`            // 获取skywalking设置到exchange中的span实例，并使用反射获取其owner字段（该字段从父类的父类继承而来，类型为TracingContext）
            Object entrySpanInstance = exchange.getAttributes().get("SKYWALING_SPAN");
            Class<?> entrySpanClazz = entrySpanInstance.getClass().getSuperclass().getSuperclass();
            Field field = entrySpanClazz.getDeclaredField("owner");
            // 利用反射调用owner的getReadablePrimaryTraceId()方法，以获取traceId
            field.setAccessible(true);
            Object ownerInstance = field.get(entrySpanInstance);
            Class<?> ownerClazz = ownerInstance.getClass();
            Method getTraceId = ownerClazz.getMethod("getReadablePrimaryTraceId");
            String traceId = (String) getTraceId.invoke(ownerInstance);
`

**Comment by woshishitou** [comment]
> 

Object entrySpanInstance = exchange.getAttributes().get("SKYWALING_SPAN");
Class<?> entrySpanClazz = entrySpanInstance.getClass().getSuperclass().getSuperclass();
Field field = entrySpanClazz.getDeclaredField("owner");
field.setAccessible(true);
Object ownerInstance = field.get(entrySpanInstance);
Class<?> ownerClazz = ownerInstance.getClass();
Method getTraceId = ownerClazz.getMethod("getReadablePrimaryTraceId");
String traceId = (String) getTraceId.invoke(ownerInstance);


You need to write this code in the filter method.

Hope it helps you.

**Comment by xiaozuo2020** [comment]
> 



> > 
> 
> Object entrySpanInstance = exchange.getAttributes().get("SKYWALING_SPAN");
> 
> Class<?> entrySpanClazz = entrySpanInstance.getClass().getSuperclass().getSuperclass();
> 
> Field field = entrySpanClazz.getDeclaredField("owner");
> 
> field.setAccessible(true);
> 
> Object ownerInstance = field.get(entrySpanInstance);
> 
> Class<?> ownerClazz = ownerInstance.getClass();
> 
> Method getTraceId = ownerClazz.getMethod("getReadablePrimaryTraceId");
> 
> String traceId = (String) getTraceId.invoke(ownerInstance);
> 
> 您需要在过滤器方法中编写此代码。
> 
> 希望对你有帮助。

3q,so much!!!
that day, I found another way 
modify the 2.1x gateway plugin，this plugin  includ webflux plugin code
![1122](https://user-images.githubusercontent.com/52436771/147524244-afcf41d6-fe9e-4002-8454-0780e0944256.png)

then  i can get traceID in attributes

![445](https://user-images.githubusercontent.com/52436771/147524441-aa79abad-ca7c-4038-a553-6fe2327fdae2.png)

**Comment by vtroisWhite** [comment]
> > > `
> > > 包com.example.gatewaydemo.filter;
> > > 导入org.apache.skywalking.apm.toolkit.trace.TraceContext;
> > > 导入org.springframework.cloud.gateway.filter.GatewayFilterChain;
> > > 导入org.springframework.cloud.gateway.filter.GlobalFilter;
> > > 导入org.springframework.context.annotation.Bean;
> > > 导入org.springframework.context.annotation.Configuration;
> > > 导入org.springframework.core.Ordered;
> > > 导入org.springframework.web.server.ServerWebExchange;
> > > 导入reactor.core.publisher.Mono;
> > > @configuration
> > > 公共类FilterConfig {
> > > ```
> > > @Bean
> > > public GlobalFilter b() {
> > >     return new BFilter();
> > > }
> > > 
> > > public class BFilter implements GlobalFilter, Ordered {
> > > 
> > >     @Override
> > >     public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
> > > 		// The value here is N/A
> > >         exchange.getResponse().getHeaders().set("tid", TraceContext.traceId());
> > >         return chain.filter(exchange).then(Mono.fromRunnable(() ->
> > >         {
> > > 			// The value here is also N/A
> > >             String traceId2 = TraceContext.traceId();
> > >             System.out.println("traceId:" + traceId2);
> > >         }));
> > >     }
> > > 
> > >     @Override
> > >     public int getOrder() {
> > >         return 1;
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > > `
> > 
> > 
> > Hello, I also encountered this problem. Using TraceContext.traceId() in the gateway, the traceId cannot be obtained. How did you solve it?
> 
> Hello，I got the traceid through reflection. Through debug, we can see that there is the traceId we need in the exchange object ![image](https://user-images.githubusercontent.com/22254487/132274359-3db30544-88d3-4d6a-8fcb-8dbd1c2812ff.png)

@wu-sheng hello, Based on the debug information in this image, I was able to retrieve the correct TID (Trace ID) using reflection. This indicates that the TID does exist. However, when using TraceContext.traceId(), it still returns N/A. Can this be fixed so that I don't have to rely on complex reflection to retrieve it?

**Comment by wu-sheng** [comment]
Why ping me? I don't know anything about this. What the others implemented, they are documented.

I can't and wouldn't answer about why, because I can answer things I don't know.
