### ISSUE TITLE
HTTP endpoints' module sometimes show as 'SpringMVC' but sometimes show as 'Tomcat Http'

### ISSUE THREAD

**Issue by 807801002** [apache/skywalking#6905]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
HTTP endpoints' module sometimes show as 'SpringMVC' but sometimes show as 'Tomcat Http',and when it was shown as SpringMVC,it could aggregate as one endpoint name when I used PathVariable,and not aggregate when it shown as Tomcat Http
![image](https://user-images.githubusercontent.com/8719537/117300542-3b740800-aeac-11eb-8184-010aa2e8893d.png)
___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking-8.5.0,Linux,java8
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You could simply remove the Tomcat plugin. If you want to understand details, you should read how your SpringMVC filter works.
