### ISSUE TITLE
Support  ignore some server-side failed HTTP status code.

### ISSUE THREAD

**Issue by liqiangz** [apache/skywalking#6906]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Now the http request regards all requests with http status code >= 400 as failed. But as a http server, we often use 403 as the status code of not logged in, and we don’t want to treat not being logged in as an error.  In some other scenarios , we do not want the 404 or 405 status code to interfere with the statistics of the successful rate. 
![image](https://user-images.githubusercontent.com/16935891/117303701-952a0180-aeaf-11eb-9627-fcfd51bd3688.png)

Maybe We can support  `statuscheck.ignored_server-side_http_status_code` in agent configuration.

**Comment by wu-sheng** [comment]
> Now the http request regards all requests with http status code >= 400 as failed. But as a http server, we often use 403 as the status code of not logged in, and we don’t want to treat not being logged in as an error. In some other scenarios , we do not want the 404 or 405 status code to interfere with the statistics of the successful rate.

Why isn't `not-authentication` coded as 503?

**Comment by wu-sheng** [comment]
If you insist on your response code, use `responseCode` in the OAL to calculate the successful rate.

**Comment by liqiangz** [comment]
> > Now the http request regards all requests with http status code >= 400 as failed. But as a http server, we often use 403 as the status code of not logged in, and we don’t want to treat not being logged in as an error. In some other scenarios , we do not want the 404 or 405 status code to interfere with the statistics of the successful rate.
> 
> Why isn't `not-authentication` coded as 503?

There is a lot of old code here. We cannot modify these logics. We can only be compatible with these codes.

**Comment by wu-sheng** [comment]
> > > Now the http request regards all requests with http status code >= 400 as failed. But as a http server, we often use 403 as the status code of not logged in, and we don’t want to treat not being logged in as an error. In some other scenarios , we do not want the 404 or 405 status code to interfere with the statistics of the successful rate.
> > 
> > 
> > Why isn't `not-authentication` coded as 503?
> 
> There is a lot of old code here. We cannot modify these logics. We can only be compatible with these codes.

Read https://github.com/apache/skywalking/issues/6906#issuecomment-833526364. But also, you should know, we never should add features base on others' mistakes. This is not a good way.

**Comment by liqiangz** [comment]
> If you insist on your response code, use `responseCode` in the OAL to calculate the successful rate.

But now in the agent, the httpcode above 400 is regarded as a failure. There are some scenarios, such as 404 and other codes, which are not regarded as failures.

**Comment by wu-sheng** [comment]
> > If you insist on your response code, use `responseCode` in the OAL to calculate the successful rate.
> 
> But now in the agent, the httpcode above 400 is regarded as a failure. There are some scenarios, such as 404 and other codes, which are not regarded as failures.

So what? OAL is the one determining the metrics, which is your question.

**Comment by wu-sheng** [comment]
> > > > If you insist on your response code, use `responseCode` in the OAL to calculate the successful rate.
> > > 
> > > 
> > > But now in the agent, the httpcode above 400 is regarded as a failure. There are some scenarios, such as 404 and other codes, which are not regarded as failures.
> > 
> > 
> > So what? OAL is the one determining the metrics, which is your question.
> 
> Thanks for your reply. Using oal is a good idea, the disadvantage is that it will affect all agents. But it is enough for me now.

You could target specific services if you want. But after all, it is low-performance impact, and keep in your private version only.
