### ISSUE TITLE
[Core Feature] Replace OAL with MAL

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6907]
Hi @apache/skywalking-committers 

This is one of the features, I plan to release in SkyWalking 2021. The OAL was introduced from 6.0 to make SkyWalking more flexible in agent and mesh scenarios. With all 3 years, we moved the SkyWalking from agent tracing analysis to service mesh covered. Now, SkyWalking support metrics, traces, logs, and event all in one.
But also, with time, I noticed, the OAL is not a little too heavier, as many binary codes(classes) generated in the runtime. Currently 8.2 to 8.5 releases, we added MAL and LAL, which is groovy based, lighter, and more powerful, also if #6897 works, it has a super important advantage, which OAL is much harder to achieve.

So, I and @kezhenxu94 discussed the possibility to replace OAL with MAL today. It seems practical. 

I open this issue to track when would we and how will lead on this. Please reply if you want to lead on this path. This is a high complex task, you are required to know OAP very well.

**Comment by wu-sheng** [comment]
Please notice, the biggest gap is OAL targeting detail, but MAL targeting statistic data.
The function in OAL is actually `downsampling` in MAL. So, even we unify the expression format, the functions we used would be a little different.

If anyone wants to discuss details, I will dive deeper.

**Comment by hanahmily** [comment]
This's a brilliant idea to unify our metric analysis engine, which is good news to OAP maintainers. Let's make it happened ASAP.

My only concern is about the performance side effect. 

It's conceivable to increase CPU and memory usage due to groovy-based DSL scripts. From my perspective, A new round performance test is necessary before the OAL system is merged. The test will give us a baseline to estimate the risk of CPU exhaustion and OOM.

**Comment by wu-sheng** [comment]
> My only concern is about the performance side effect.
It's conceivable to increase CPU and memory usage due to groovy-based DSL scripts. From my perspective, A new round performance test is necessary before the OAL system is merged. The test will give us a baseline to estimate the risk of CPU exhaustion and OOM.

Yes, I think so. Groovy is just taking care of the filter part, others are still on the hardcoded aggregation, which is driven by function implementation. So, I am assuming we should be fine. Of course, the test should be done.

**Comment by kezhenxu94** [comment]
I’m going to investigate more and undertake this task.

**Comment by wu-sheng** [comment]
JVM analysis OAL has been replaced by MAL through #7091.

**Comment by kezhenxu94** [comment]
From our users' report and my investigation, MAL (Groovy DSL) is in poor performance when the traffic is large, and replacing OAL with MAL gains very little so we won't consider this issue for now.
