### ISSUE TITLE
[Trace] Storage-Query 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#6924]
The query sub-system of the storage module ingests query request from the liaison, and then attempts to 

  - find the most efficient way to execute it based on internal statistics and data placement. 
  - generate a series of tiny operations and compose them to a hierarchical execution topology.
  - send operations to storage and index modules to retrieve desired results.
  - aggregate sub results to a final one, then transfer to liaison module.
 
Before diving into the codes, we need to output a more fined design of this module.

**Comment by lujiajing1126** [comment]
Pls assign to me

**Comment by lujiajing1126** [comment]
@hanahmily a preliminary draft can be found here 
https://docs.google.com/document/d/1BHIcHby_aEplVbsDv2mUFnu_nSpx_upAGHL96sTY_U8/edit?usp=sharing

**Comment by hanahmily** [comment]
This module is done
