### ISSUE TITLE
How set  alarm rule for  an endpoint of a service/instance

### ISSUE THREAD

**Issue by Dosteyevsky** [apache/skywalking#6926]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I want  to set  an  alarm rule for  an endpoint of a service/instance, how  to do it?
I read backend-alarm.md and alarm-settings.xml, but dont  find  it.
Examples about  endpoint alarm  rule dont specify   the  property *include-names*.
Can you  guys give  me some examples?   Thanks!

**Comment by wu-sheng** [comment]
I think the entity name part gives a clear explanation. http://skywalking.apache.org/docs/main/v8.5.0/en/setup/backend/backend-alarm/#entity-name

**Comment by Dosteyevsky** [comment]
got it,Thanks！
