### ISSUE TITLE
About NPM vulnerabilities

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6927]
When I run `npm install` for Client JS source codes, I got this

```
added 808 packages, and audited 875 packages in 14s

18 vulnerabilities (7 low, 2 moderate, 9 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

Most of them could be fixed through `npm audit fix`, 3 of them(low level) can't. Should we fix this? And which vulnerabilities these are? As far as I know, client-js has very few dependency libraries, where do warnings come from?

**Comment by Fine0830** [comment]
Yes, we should. Those packages are dev dependency libraries, so we don't have to think about licenses.

**Comment by wu-sheng** [comment]
> es, we should. Those packages are dev dependency libraries, so we don't think about licenses.

Yes, dev has nothing related to release or apache release policy. But still, let's fix it in the next iteration.
