### ISSUE TITLE
Spring RestTemplate plugin IllegalArgumentException

### ISSUE THREAD

**Issue by zhangsaizz** [apache/skywalking#6928]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
   8.5.0
- Which company or project?
   apm-resttemplate-4.3.x-plugin
- What happened?
   exception :
![image](https://user-images.githubusercontent.com/9312086/117909903-9e7ef800-b30d-11eb-9aec-7e5b78b14592.png)

When class extends  `AbstractClientHttpResponse` , funciton `getStatusCode()` will check whether the status code exists in the http status code table, if not, an exception will be thrown

**Comment by wu-sheng** [comment]
One question, why your REST response code isn't  an integer?

**Comment by zhangsaizz** [comment]
It should be that our gateway has customized an http code to return -1, but why is it not an integer, we are still checking it internally. Back to the question, do we need to consider the scenario of custom status codes?

**Comment by zhangsaizz** [comment]
> One question, why your REST response code isn't an integer?

It should be that our gateway has customized an http code to return -1, but why is it not an integer, we are still checking it internally. Back to the question, do we need to consider the scenario of custom status codes?

**Comment by wu-sheng** [comment]
Status code has very specific definition in HTTP spec. This is why I am confused. Custom response code is not negative value.

**Comment by zhangsaizz** [comment]
> Status code has very specific definition in HTTP spec. This is why I am confused. Custom response code is not negative value.

Okay, I also think that the custom status code should not have negative numbers. But now whether the scene is negative or positive, it will report an error if it is not the originally designed status code range, and the user will not be able to use the custom status code.

**Comment by wu-sheng** [comment]
I haven't read source codes, but if it is, it looks like rest template design, we are just using it. Otherwise, what we can do? Catching the exception and say unknown response code will cause more confused, and our users will ask again about why again.
What do you propose?

**Comment by wu-sheng** [comment]
Look at the exception stack, it is caused by spring framework API.

**Comment by zhangsaizz** [comment]
> I haven't read source codes, but if it is, it looks like rest template design, we are just using it. Otherwise, what we can do? Catching the exception and say unknown response code will cause more confused, and our users will ask again about why again.
> What do you propose?

Can I directly use method `getRawStatusCode()` to get the status? This way there will be no verification exceptions .

**Comment by wu-sheng** [comment]
But code is the only way to determine right or wrong status efficiently. Without that, successful rate is not accurate, or costs too many backend resources.

**Comment by zhangsaizz** [comment]
> But code is the only way to determine right or wrong status efficiently. Without that, successful rate is not accurate, or costs too many backend resources.

Can the status of right and wrong be left to the user to define? The default logic is the current one. Adding a custom status code judgment table can give users right and wrong configuration options, whether it can be more flexible

**Comment by wu-sheng** [comment]
What do you mean by user definition? This code is in the agent. 100% transparent to the end user.

**Comment by wu-sheng** [comment]
No update
