### ISSUE TITLE
[UI] "Web Browser" don't  have metric data in 8.5.0, but  it is normal in 8.4.0

### ISSUE THREAD

**Issue by HendSame** [apache/skywalking#6930]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.5.0 

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

#### In 8.5.0
![image](https://user-images.githubusercontent.com/9264192/117922764-887d3180-b325-11eb-8d86-fdee3cd6e01f.png)

#### In 8.4.0
![image](https://user-images.githubusercontent.com/9264192/117922811-9c289800-b325-11eb-9c8f-71e8b9a16513.png)

It's pretty obvious that there are 12 requests normally, but there are 3 requests in 8.5.0.
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Our demo is running based on 8.5. Make sure your UI match oap version.

**Comment by HendSame** [comment]
@wu-sheng UI and oap  version both is 8.5.0.

**Comment by wu-sheng** [comment]
The demo you are looking at should run this. Please check your side, please. I can't see what is happening.
