### ISSUE TITLE
noTraceOrigins is not in skywalking-client-js version 0.4.0

### ISSUE THREAD

**Issue by dgy5554** [apache/skywalking#6940]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- skywalking-client-js latest version is 0.4.0, and is publish at 26, Feb. But the feature of noTraceOrigins was added on 16 Mar, when we can use the 0.4.1 or 0.5.0
https://github.com/apache/skywalking-client-js/pull/45

**Comment by Fine0830** [comment]
Please read docs. https://github.com/apache/skywalking-client-js/blob/master/CHANGES.md

**Comment by dgy5554** [comment]
i cannot find 0.5.0 in npm repository
https://www.npmjs.com/package/skywalking-client-js

**Comment by wu-sheng** [comment]
It isn't out yet. Subscribe to our twitter or mail list for latest news.
