### ISSUE TITLE
Can the APM global view support only displaying and counting selected service groups

### ISSUE THREAD

**Issue by 807801002** [apache/skywalking#6942]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can the APM global view support only displaying and counting selected service groups?We need to display and calculate only the groups that the user cares about
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No. it can't.
