### ISSUE TITLE
bug report:NPE

### ISSUE THREAD

**Issue by JoeKerouac** [apache/skywalking#6945]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___

In method `org.apache.skywalking.oap.server.configuration.configmap.ConfigmapConfigurationWatcherRegister#readConfig`:

NullPointException occurs when method `io.kubernetes.client.openapi.models.V1ConfigMap#getData` returns null,The method `io.kubernetes.client.openapi.models.V1ConfigMap#getData` returns empty, which is normal for k8s;

**Comment by wu-sheng** [comment]
Why do you activate the k8s configuration but don't provide anything?

**Comment by JoeKerouac** [comment]
> Why do you activate the k8s configuration but don't provide anything?

yes, and I am preparing to submit a PR fix

**Comment by wu-sheng** [comment]
I am not talking about a PR, it could be fixed, but just strange you are using a system like this.

**Comment by JoeKerouac** [comment]
> I am not talking about a PR, it could be fixed, but just strange you are using a system like this.

In fact, I just don’t know what to configure for the time being, I will configure it later, but this problem prevents me from starting oap;

**Comment by wu-sheng** [comment]
OK, get it. You could submit a pull request if you like.
