### ISSUE TITLE
Does Skywalking support print spanid and parent Id in log4j2

### ISSUE THREAD

**Issue by sweat123** [apache/skywalking#6954]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Does skywalking which version is 8.4 support getting spanid and parentid in log?
Thanks a lot.

___
### Bug
- Which version of SkyWalking, OS, and JRE?

skywalking version `8.4`

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
No, it's tagged in milestone 8.6.0 #6795
