### ISSUE TITLE
The newest apm-toolkit-log4j-2.x.jar

### ISSUE THREAD

**Issue by bitbybit-edu** [apache/skywalking#6959]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
    I use  '%sw_ctx' in the log4j2.xml, but not work.
    I see the apm-toolkit-log4j-2.x.jar, version 8.50, has not the SkyWalkingContextConverter.java.
    How can i find the newest jar.

**Comment by kezhenxu94** [comment]
It’s tagged in 8.6.0, which is not released yet.

**Comment by bitbybit-edu** [comment]
Thank you , so much!
