### ISSUE TITLE
Service Traffic Bug

### ISSUE THREAD

**Issue by JelfPann** [apache/skywalking#6961]
Skywalking version is 8.2.0.  The ElasticSeach7 is used for backend data storage. The index xxx_service_traffic-YYMMDD was only created once when the oap server started. It was not automatically created in another day. When the skywalking ui executes 'queryServices', "Cannot read property 'services' of undefined at dashboard-option.ts:126" occurs. The skywalking ui cannot work well, and only part of it can be shown. After index xxx_service_traffic-YYMMDD was created manually, the skywalking ui works well.
I want a suggestion of How to Make index xxx_service_traffic-YYMMDD created automatically day by day.

**Comment by wu-sheng** [comment]
I can't follow your context. We don't need to do that. They are all auto-generated. Choose the latest version.
