### ISSUE TITLE
when i use custom config and field type is float, i can't get right value.

### ISSUE THREAD

**Issue by myfairys** [apache/skywalking#6963]
Bug
___
### Question
when i use custom config and field type is float, i can't get right value. 
___
### Bug
I use skywalking 8.1.0，but the same code util 8.5.0，and use jdk8、windows 10.

It's occur to Agent.
I look up source code,i get it. to Class `ConfigInitializer`
`} else if (boolean.class.equals(type) || Boolean.class.equals(type)) {
            result = Boolean.valueOf(value);
        } else if (float.class.equals(type) || Float.class.equals(type)) {
            result = Boolean.valueOf(value);`

So is it a bug?

**Comment by wu-sheng** [comment]
Yes, this is a bug.

**Comment by wu-sheng** [comment]
@myfairys Are you going to send a pull request to fix this?

**Comment by myfairys** [comment]
> @myfairys Are you going to send a pull request to fix this?

@wu-sheng I'm sorry,i'm not

**Comment by wu-sheng** [comment]
Thanks for updating. Remove the milestone, this is a low priority issue.

**Comment by zifeihan** [comment]
@wu-sheng 
i will try to fix it.
