### ISSUE TITLE
Search Endpoint use keyword params in trace view.

### ISSUE THREAD

**Issue by liqiangz** [apache/skywalking#6969]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/16935891/118658021-9566bd00-b81e-11eb-8583-3244a1ab0999.png)

### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Yes, there is a bug. Are you going to fix this?

**Comment by liqiangz** [comment]
@wu-sheng I will fix it later.
