### ISSUE TITLE
Make %traceId configurable for application toolkit for logging

### ISSUE THREAD

**Issue by yaojingguo** [apache/skywalking#6970]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [X] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
For [Application-toolkit-log4j-2.x][1], [Application-toolkit-log4j-1.x][2] and [Application-toolkit-logback-1.x][3], `%traceId` means  `TID: real_trace_id`. For example, a `%traceId` placeholdder is replaced with `TID: df16a9001ca34cafbe23cbc5751c0d66.96.16206346254060001` in [log4j-2.x][1]. It is hard to extract `df16a9001ca34cafbe23cbc5751c0d66.96.16206346254060001` from `TID: df16a9001ca34cafbe23cbc5751c0d66.96.16206346254060001` when such log  messages are injected into ELK or Aliyun SLS.  But if `%traceId` means `real_trace_id`, the extraction is trival. And if we want something like `TID: real_trace_id`, we can write `TID: %traceId` in log4j-2.x's PatternLayout.

Is it possible to make `%traceId` pattern configurable?

[1]: https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-log4j-2.x.md
[2]: https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-log4j-1.x.md
[3]: https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-logback-1.x.md

**Comment by wu-sheng** [comment]
What do you mean hard to extract? We could easily do by using LAL by SkyWalking OAP.

**Comment by wu-sheng** [comment]
And we recommend injecting trace context rather than trace id already in the 8.6.0-dev.

**Comment by wu-sheng** [comment]
Read this if you want to know how SkyWalking does log collection. https://github.com/apache/skywalking/pull/6952

**Comment by yaojingguo** [comment]
> What do you mean hard to extract? We could easily do by using LAL by SkyWalking OAP.

For example, we use `%d{ISO8601}|%-5p|[%t]|%traceId|%c{2}|%m%n` log4j2 pattern. When log messages are loaded into Aliyun SLS,  `|` is used to split the log message. After the split, we get `TID: real_trace_id`.  We don't want the prefix `TID: `. We just want `real_trace_id`.

> And we recommend injecting trace context rather than trace id already in the 8.6.0-dev.

Where can I find the related information? I have just skimmed the source code. But I don't find it.

**Comment by wu-sheng** [comment]
Sorry, SLS should not be used as a primary consideration in this case. To match `TID:` is a very easy regex capability, I can't see why you want to use `|`, which doesn't make sense to a community-level feature.

This doc should help, https://skywalking.apache.org/docs/main/latest/en/setup/service-agent/java-agent/application-toolkit-log4j-2.x/#print-skywalking-context-in-your-logs. But still, don't try to use `|` to do log analysis.

**Comment by wu-sheng** [comment]
Notice, once you have entered the commercial product/service field, you are on your own, or we should say, it is AliCloud's responsibility, rather than the community's.

**Comment by yaojingguo** [comment]
I have another use case with Skywalking trace ID which has nothing to do with AliCloud's products. I want to format Log4j2 logs as JSON with the pattern layout. In order to make the log message a valid JSON, I need to double-quote `%traceId` in the following way:

```
{
  "TID" : "%traceId"
}
```

An example log message is:
```
{
  "TID" : "TID: df16a9001ca34cafbe23cbc5751c0d66.96.16206346254060001"
}
```

But what I really want is:
```
{
  "TID" : "df16a9001ca34cafbe23cbc5751c0d66.96.16206346254060001"
}
```

For now, I need to use the following `TraceIdConverter` wrapper to remove the prefix:
```java
@Plugin(name = "TraceIdConverter", category = "Converter")
@ConverterKeys({"sw_tid"})
public class SwTraceIdConverter extends LogEventPatternConverter {

  private TraceIdConverter converter;

  protected SwTraceIdConverter(String name, String style) {
    super(name, style);
    converter = TraceIdConverter.newInstance(null);
  }

  public static SwTraceIdConverter newInstance(String[] options) {
    return new SwTraceIdConverter("sw_tid", "sw_tid");
  }

  @Override
  public void format(final LogEvent event, final StringBuilder toAppendTo) {
    StringBuilder sb = new StringBuilder();
    converter.format(event, sb);
    String traceId = sb.toString().substring(5);
    toAppendTo.append(traceId);
  }
}
```

If the `TID: ` prefix can be removed, I don't need to do any coding to have the above valid JSON. And if the user really wants something like `TID: df16a9001ca34cafbe23cbc5751c0d66.96.16206346254060001`, he can use `TID: %traceId`. Here is another issue requesting the removal of the prefix: #6142. @ecyuan

https://github.com/apache/skywalking-java/blob/main/docs/en/setup/service-agent/java-agent/Application-toolkit-log4j-2.x.md now supports both `%traceId` and `%sw_ctx`. `%sw_ctx` has all the context information beside Skywalking trace ID. If the prefix can't be removed, `%traceId` can be more easily used in Log4j2 pattern layout. And if the user wants to more tracing context information, he can use `%sw_ctx`.
