### ISSUE TITLE
Bug: The prometheus metrics type is wrong in TextParse.java

### ISSUE THREAD

**Issue by gxthrj** [apache/skywalking#6971]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
IMHO , The Prometheus metrics type is wrong in TextParse.java
`ctx.type` should be set in with the second word in `# TYPE`.
[Should not set `ctx.type`](https://github.com/apache/skywalking/blob/master/oap-server/server-library/library-util/src/main/java/org/apache/skywalking/oap/server/library/util/prometheus/parser/TextParser.java#L96)
[Should set `ctx.type`](https://github.com/apache/skywalking/blob/master/oap-server/server-library/library-util/src/main/java/org/apache/skywalking/oap/server/library/util/prometheus/parser/TextParser.java#L109)

___
### Bug
- Which version of SkyWalking, OS, and JRE?
master

**Comment by gxthrj** [comment]
@hanahmily PTAL, if you have time.

**Comment by wu-sheng** [comment]
Please update the link to perm link.

**Comment by gxthrj** [comment]
> Please update the link to perm link.

Updated

**Comment by hanahmily** [comment]
It's a bit tricky here, but defaulting to  "Gauge" in the "HELP" line is intentional. 

Referring to Prometheus metric specification, if there's no  "TYPE" line, the metric will be parsed as "untyped". But MAL CAN'T handle such metrics, will complain about missing type. 

Based on that, I default it to "Gauge".

**Comment by gxthrj** [comment]
> It's a bit tricky here, but defaulting to "Gauge" in the "HELP" line is intentional.
> 
> Referring to Prometheus metric specification, if there's no "TYPE" line, the metric will be parsed as "untyped". But MAL CAN'T handle such metrics, will complain about missing type.
> 
> Based on that, I default it to "Gauge".

Got it , but the second question is [here](https://github.com/apache/skywalking/blob/master/oap-server/server-library/library-util/src/main/java/org/apache/skywalking/oap/server/library/util/prometheus/parser/TextParser.java#L109), I think should set `ctx.type` instead of `ctx.name`.

**Comment by wu-sheng** [comment]
Type is set here, 

https://github.com/apache/skywalking/blob/e7d6b5457bcbdac370a4a7912766510253ec7f4b/oap-server/server-library/library-util/src/main/java/org/apache/skywalking/oap/server/library/util/prometheus/parser/Context.java#L55

**Comment by hanahmily** [comment]
> Got it , but the second question is [here](https://github.com/apache/skywalking/blob/master/oap-server/server-library/library-util/src/main/java/org/apache/skywalking/oap/server/library/util/prometheus/parser/TextParser.java#L109), I think should set `ctx.type` instead of `ctx.name`.

The `addAllowNames` set the type in the next line

**Comment by gxthrj** [comment]
Thanks, understand.
