### ISSUE TITLE
default alarm config may produce a lot of objects(RunningRule$Window)

### ISSUE THREAD

**Issue by nl594** [apache/skywalking#6977]
Please answer these questions before submitting your issue.
- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

is this a problem ? or my config have a problem ?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking : 8.2.0
OS : Linux
JRE : jdk8

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

in the product environment, we use skywalking-nginx-lua let nginx access to skywalking , after running for 2 days, we find 1 million objects(org.apache.skywalking.oap.server.core.alarm.provider.RunningRule$Window).

   1:       5278672      873303032  [B (java.base@11.0.9)
   2:      16697019      400728456  java.util.LinkedList$Node (java.base@11.0.9)
   3:       5045442      121090608  java.lang.String (java.base@11.0.9)
   4:       1669626       66785040  org.apache.skywalking.oap.server.core.alarm.provider.RunningRule$Window
   5:       1696742       54295744  java.util.concurrent.ConcurrentHashMap$Node (java.base@11.0.9)
   6:       1670763       53464416  java.util.concurrent.locks.ReentrantLock$NonfairSync (java.base@11.0.9)
   7:       1670030       53440960  java.util.LinkedList (java.base@11.0.9)
   8:       1669531       40068744  org.apache.skywalking.oap.server.core.alarm.EndpointRelationMetaInAlarm
   9:       1670751       26732016  java.util.concurrent.locks.ReentrantLock (java.base@11.0.9)

Then i build a environment at my own computer, find the follow thing. a interface has variable parameter in the uri, after I call the api with different parameter, every different uri  will be add the RunningRule.windows. Is this a problem ? or just my configration is not right ?
<img width="1389" alt="skywalking issue1" src="https://user-images.githubusercontent.com/23700054/118831885-b567b080-b8f2-11eb-8ef7-ac481142db2f.png">

<img width="1456" alt="skywalking-issue2" src="https://user-images.githubusercontent.com/23700054/118832349-214a1900-b8f3-11eb-955a-8295ef5f499a.png">

### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I don't think we have a default alarm rule about the endpoint. Please make the status clear when you ask questions.

**Comment by nl594** [comment]
> I don't think we have a default alarm rule about the endpoint. Please make the status clear when you ask questions.

but I download the package by url:https://archive.apache.org/dist/skywalking/8.2.0/apache-skywalking-apm-es7-8.2.0.tar.gz, which find in official address:http://skywalking.apache.org/downloads . in the file /apache-skywalking-apm-bin-es7/config/alarm-settings.yml has endpoint config as follow:
  endpoint_relation_resp_time_rule:
    metrics-name: endpoint_relation_resp_time
    threshold: 1000
    op: ">"
    period: 10
    count: 2
    message: Response time of endpoint relation {name} is more than 1000ms in 2 minutes of last 10 minutes

**Comment by wu-sheng** [comment]
Remove them if you want. My point is, this is not default anymore. 8.2.0 is an official release, but it is old
