### ISSUE TITLE
业务系统服务下线后，如何在skywalking服务中下线该服务的实例

### ISSUE THREAD

**Issue by cuixu3659271** [apache/skywalking#6978]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
业务系统服务下线后，如何在skywalking服务中下线该服务的实例
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We only accept English on GitHub.
