### ISSUE TITLE
每次重启项目服务后，都会在skywalking服务中新增一个新的服务实例？如何能保证同一个服务只有一个服务实例？

### ISSUE THREAD

**Issue by cuixu3659271** [apache/skywalking#6979]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

每次重启项目服务后（项目的ip地址会变更），都会在skywalking服务中新增一个新的服务实例？如何能保证同一个服务只有一个服务实例？
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We only accept English on GitHub.
