### ISSUE TITLE
How to delete the service instance of skywalking when the service is offline

### ISSUE THREAD

**Issue by cuixu3659271** [apache/skywalking#6980]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to delete the service instance of skywalking when the service is offline
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?
- project

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment]
Just wait (TTL) for the cleaner to delete them. We don't support manual removal of service instance.
