### ISSUE TITLE
detailed implementation of performance analysis

### ISSUE THREAD

**Issue by kuailelijuan** [apache/skywalking#6982]
### Question
- What do you want to know?

I am investigating skywalking and trying to understand its implementation principles. I read an article [https://skywalking.apache.org/zh/2020-03-23-using-profiling-to-fix-the-blind-spot-of-distributed-tracing/#%E6%96%B9%E6%B3%95%E4%BB%8B%E7%BB%8D ] that hope you can provide some implementation details and code location of this article. Thank you.

**Comment by kezhenxu94** [comment]
Source codes are all open sourced, we don't answer code level details questions, please read by yourself.
