### ISSUE TITLE
apm-cassandra-java-driver-3.x-plugin  stament can't get host bug

### ISSUE THREAD

**Issue by DeadLion** [apache/skywalking#6983]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
SkyWalking 8.5.0

now the cassandra version is  3.7.2 ，we use 3.4.0

```
        String remotePeer = statement.getHost() == null ? connectionInfo.getContactPoints() : (statement.getHost()
                                                                                                        .getSocketAddress()
                                                                                                        .getHostName() + ":" + statement
            .getHost()
            .getSocketAddress()
            .getPort());

```

 statement.getHost() will throw NPE on 3.4.0 ，maybe we should check null before geting host to adapter low version's driver.

**Comment by kezhenxu94** [comment]
The supported versions is 3.7.0-3.7.2, you're using 3.4.0, that's not adapted by our contributors, if you want, you need to enhance that.
