### ISSUE TITLE
How to implement a metric which is computed by previous collected data?

### ISSUE THREAD

**Issue by JelfPann** [apache/skywalking#6985]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- How to implement a metric which is computed by previous collected data?
- For example, at time T, the JVM thread count is 10, and at time T-1, the JVM thread count is 5, 
 what I want to compute is the increment of the JVM thread count, which is 5 computed by 10 subtracts 5.
 We want to use the metric of the increment of the JVM thread count to do alarm behaviors.

**Comment by wu-sheng** [comment]
MAL has a rate function for it.

**Comment by JelfPann** [comment]
I have learned about 
```
browser_app_error_rate = from(BrowserAppTraffic.*).rate(trafficCategory == BrowserAppTrafficCategory.FIRST_ERROR, trafficCategory == BrowserAppTrafficCategory.NORMAL); 
``` 
but my case is different.
In my case, only `ServiceInstanceJVMThread.liveCount` is used as the condition. I do not know how to compare with the past value.
Could you show me a example?

**Comment by wu-sheng** [comment]
I think this is not available through OAL. All metrics should transfer into MeterSystem, and use MAL to run analysis. There is a `rate` function there.

**Comment by JelfPann** [comment]
I do have learned ablout MAL as possible as I can. But I could just get a few of docs about it.
Firstly, I am very confused of the Meter and Metric.
In my debug practice, when JVM info of the agent received, only OAL works to process it. I can't find where the stream data go to the meter system.
The config file `meter-analyzer-config/spring-sleuth.yaml` seems not working. 
I do not know how the following scrpit works or whether it worked.
```
expSuffix: instance(['service'], ['instance'])
metricPrefix: meter
metricsRules:
  - name: jvm_threads_live
    exp: jvm_threads_live
```

**Comment by wu-sheng** [comment]
JVM metrics right now are only for OAL I am afraid. Unless you or someone contribute this and change it to MAL core, I don't think your requirement is possible.
