### ISSUE TITLE
Consider to integrate fluentd file scanner into the Satellite

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6986]
We have Fluentd integration merged, see #6260. But when we need Satellite MMAP or don't want Kafka as a transport layer, Satellite should be able to read logs(file) directly.
We could consider something similar with Fluentd in OTEL collector, and integrate it into the Satellite at the API level. FYI @hailin0

**Comment by dmsolr** [comment]
Do you mean to let Satallite own the ability to read log files directly?

**Comment by wu-sheng** [comment]
> Do you mean to let Satallite own the ability to read log files directly?

Yes, I am.

**Comment by wu-sheng** [comment]
Then, we could remove the fluent agent and Kafka from the deployment.

**Comment by wu-sheng** [comment]
All logs could be transported in native gRPC log format, which is better.

**Comment by dmsolr** [comment]
Got it

**Comment by kagaya85** [comment]
Are we going to use some third-party lib like https://github.com/observIQ/stanza as an intergated log agent?

**Comment by wu-sheng** [comment]
> Are we going to use some third-party lib like https://github.com/observIQ/stanza as an intergated log agent?

Please don't mix different topics.

**Comment by kagaya85** [comment]
> > Are we going to use some third-party lib like [observIQ/stanza](https://github.com/observIQ/stanza) as an intergated log agent?
> 
> Please don't mix different topics.

Sorry I may not understand the context, has this issue already been resolved? I am looking for contributing to skywalking-satellite but confused about this

**Comment by wu-sheng** [comment]
Fluentd is c based, this issue is not suitable. You could submit a new issue or discuss about your proposal.
