### ISSUE TITLE
The error rate is calculated with more types of errors

### ISSUE THREAD

**Issue by Fine0830** [apache/skywalking#6990]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

Should we calculate the error rate with more types of errors? The current error rate is only calculated with JS errors. There are gaps between errors logs with error rate.

**Comment by wu-sheng** [comment]
> Should we calculate the error rate with more types of errors? The current error rate is only calculated with JS errors. There are gaps between errors logs with error rate.

I think we should keep them consistent. Once some logs show up, the rate should match them. And error rate should be named as `error per page view`? The rate usually only counts one per page if there are multiple errors.
