### ISSUE TITLE
Add SpanLayer DistributedTransaction to description distributed-transaction plugin such as Seata

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/skywalking#6993]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement

I want add SpanLayer DistributedTransaction(7) to description distributed-transaction plugin such as Seata
![image](https://user-images.githubusercontent.com/10150229/119112413-a437b480-ba56-11eb-82d6-d3ef4dfd2733.png)

![image](https://user-images.githubusercontent.com/10150229/119112512-ba457500-ba56-11eb-9b28-1ea24d4e80e8.png)

**Comment by wu-sheng** [comment]
The layer is not for extension. Unless there are typical reasons related to analyzing, SkyWalking wouldn't add any new. The current layers are network related, rather than framework related, to build different dashboards.
