### ISSUE TITLE
ResponseCallBackInterceptor in restemplate-4.x-plugin has a wrong intecept which lead an error

### ISSUE THREAD

**Issue by whl12345** [apache/skywalking#6994]
### Bug
![bug](https://user-images.githubusercontent.com/36367435/119125190-14990280-ba64-11eb-8a3f-53c9d193ef79.png)

line 32 in the first image lead a specific error below
![bug2](https://user-images.githubusercontent.com/36367435/119126047-1d3e0880-ba65-11eb-8d0a-50c149f43b9c.png)

- Which version of SkyWalking, OS, and JRE?
6.1.0

- What happened?
I found a bug when I user skywalking-auth\test\plugin\scenarios\resttemplate-4.x-scenario to test resttemplate for asyn. ResponseCallBackInterceptor has an error after I user remote debug for skywalking agent. In beforeMethod allArguments[] is not compatible with allArgumentTypes[]，allArguments[] is not value of SuccessCallback/FailureCallback but FrontController(Controller Class in Test Server) !The bug lead an error in line 32 as the second image.The third image is the test case controller. 
![test_case](https://user-images.githubusercontent.com/36367435/119125870-e2d46b80-ba64-11eb-9ec9-4e173b57cdcc.png)

___
### Requirement or improvement
How can I fix the bug? Please give me some advice.

**Comment by wu-sheng** [comment]
Check the latest release.

**Comment by whl12345** [comment]
> Check the latest release.
Can you locate the code which fix the question?For some reason ,we cannot change the version of skywalking.

**Comment by whl12345** [comment]
> Check the latest release.
LatestRelease do not fix the bug.

**Comment by wu-sheng** [comment]
Once you have all things, try to submit a pull request to fix it. The community doesn't have a chance to check every use case. We need you to enhance the plugins.
