### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'services' of undefined

### ISSUE THREAD

**Issue by siliang42** [apache/skywalking#6995]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
when i want get trace detail , console print error like the tilte
java -agent 
version 6.5.0
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Can't see the relationship. WIthout more details, this seems impossible to know.
