### ISSUE TITLE
Use MAL to calculate JVM metrics, remove OAL dependency

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6996]
More metrics analysis should be moved into MAL's responsibility.

**Comment by liqiangz** [comment]
I am interested in it.

**Comment by wu-sheng** [comment]
Assigned, this should not be hard. Ping me if you face any issue.

**Comment by wu-sheng** [comment]
And a reminder, JVM metrics seem don't have e2e cover. Please add them in the PR.
