### ISSUE TITLE
kafka-fetcher topic prefix is not generated 

### ISSUE THREAD

**Issue by queenns** [apache/skywalking#6998]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-fetcher.md#kafka-fetcher
___
### Bug
- Which version of SkyWalking, OS, and JRE?
oap.images.tag: 8.5.0-es7
oap.images.storageType: elasticsearch7

helm install "${SKYWALKING_RELEASE_NAME}" skywalking -n "${SKYWALKING_RELEASE_NAMESPACE}" \
-f ./skywalking/values-my-es.yaml \
--set oap.env.SW_CLUSTER=kubernetes \
--set oap.env.SW_CLUSTER_K8S_NAMESPACE=sky \
--set oap.env.SW_KAFKA_FETCHER=default \
--set oap.env.SW_KAFKA_FETCHER_SERVERS=xxx:9092 \
--set oap.env.SW_KAFKA_FETCHER_PARTITIONS=4 \
--set oap.env.SW_KAFKA_FETCHER_IS_SHARDING=true \
--set oap.env.**SW_NAMESPACE**=**pre** \
--set oap.env.SW_CONFIGURATION=k8s-configmap

- What happened?

After deployment according to the document description,
SW_NAMESPACE is set, topic is not prefixed, 
but elasitcsearch index is prefixed by default

Example after **topic** generation:**skywalking-segments**
Example after **index** generation:**pre_segment-20210524**

**Comment by wu-sheng** [comment]
Should have been fixed by https://github.com/apache/skywalking/pull/6952.

**Comment by queenns** [comment]
> Should have been fixed by #6952.
**agent:**
https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md
I can modify the configuration specified topic in agent.conf.
plugin.kafka.topic_meter
plugin.kafka.topic_metrics
plugin.kafka.topic_segment
plugin.kafka.topic_profilings
plugin.kafka.topic_management
**oap:**
https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/configuration-vocabulary.md
**Without the system variable name**, **I cannot specify it,** so how can I solve the problem of multiple skywalking clusters using one Kafka before 8.6?
kafka-fetcher.default.topicNameOfMeters etc.

**Comment by queenns** [comment]
> Please be clear.

Simply speaking, I don't want to use the default topic name. How can I specify the name of topic in OAP before 8.6.0

**Comment by queenns** [comment]
I use this method to install, but if --set is specified, there is no system environment name and cannot be specified.

helm install "${SKYWALKING_RELEASE_NAME}" skywalking -n "${SKYWALKING_RELEASE_NAMESPACE}" \
-f ./skywalking/values-my-es.yaml \
--set oap.env.SW_CLUSTER=kubernetes \
--set oap.env.SW_CLUSTER_K8S_NAMESPACE=skywalking \
--set oap.env.SW_KAFKA_FETCHER=default \
--set oap.env.SW_KAFKA_FETCHER_SERVERS=172.18.96.29:9092 \
--set oap.env.SW_KAFKA_FETCHER_PARTITIONS=4 \
--set oap.env.SW_KAFKA_FETCHER_IS_SHARDING=true
