### ISSUE TITLE
Not Support HttpClient3.X

### ISSUE THREAD

**Issue by gangchaopan** [apache/skywalking#700]
The Old project always use HttpClient3.x，Please consider if this is feasible

**Comment by wu-sheng** [comment]
HTTPClient is a little old. The last version of 3.x released more than ten years ago. http://archive.apache.org/dist/httpcomponents/commons-httpclient/3.0/

I will not suggest the core team to support them. If you or anyone else is interested in supporting this version, we are welcome to guide you and accept your pull request. Thanks.

**Comment by wu-sheng** [comment]
No old lib, no update.
