### ISSUE TITLE
The meaning of 'Counter' variable in RunningRule

### ISSUE THREAD

**Issue by zhyyu** [apache/skywalking#7000]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
  - org.apache.skywalking.oap.server.core.alarm.provider.RunningRule
		- what do variable 'Counter' mean?
		- why need a Counter variable?
		- the method 'isMatch' use the 'countThreshold' variable, but method 'checkAlarm' also use the 'countThreshold' varaible to compare, I cannot understant why compare it twice.

```java
public Optional<AlarmMessage> checkAlarm() {
            if (isMatch()) {
                /*
                 * When
                 * 1. Metrics value threshold triggers alarm by rule
                 * 2. Counter reaches the count threshold;
                 * 3. Isn't in silence stage, judged by SilenceCountdown(!=0).
                 */
                counter++;
                if (counter >= countThreshold && silenceCountdown < 1) {
                    silenceCountdown = silencePeriod;
                    return Optional.of(new AlarmMessage());
                } else {
                    silenceCountdown--;
                }
            } else {
                silenceCountdown--;
                if (counter > 0) {
                    counter--;
                }
            }
            return Optional.empty();
        }

private boolean isMatch() {
            int matchCount = 0;
            for (Metrics metrics : values) {
                if (metrics == null) {
                    continue;
                }

            // xxx
            // xxx
            
            // Reach the threshold in current bucket.
            return matchCount >= countThreshold;
        }
```

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
	- There is a example:
		- window size: 5
		- window threshold: 3
		- initial window data: 0 1 1 0 1 (0 means not matched, 1 means matched), and later data is all 0 when window move
	- this example rule will not be triggered by followed rule
	  - window size: 5
	  - window threshold: 3
	- I think it should be triggered, but it's not. So it confuse me a lot.

**Comment by wu-sheng** [comment]
I think you should not ask a community to explain the source codes to you. If you find a bug, we could dive in.

**Comment by zhyyu** [comment]
Ok, I think it's a bug; The default alarm-settings.yml

```
service_resp_time_rule:
    metrics-name: service_resp_time
    op: ">"
    threshold: 1000
    period: 10
    count: 3
    silence-period: 5
    message: Response time of service {name} is more than 1000ms in 3 minutes of last 10 minutes.
```

if 1, 2, 3 minutes metrics match the threshold, it will not triggered. It hava to wait 3 more minutes to wait for triggering because of 'Counter' compare 'countThreshold' twice in the source code. So the default rule message is not accurate.

**Comment by wu-sheng** [comment]
OK, this makes sense now. We don't need `counter`, this is actually a duplicate logic bug.
Are you going to send a pull request to fix this?
