### ISSUE TITLE
[NIGNX-LUA] skywalking_tracer:finish() should execute in log_by_lua_block

### ISSUE THREAD

**Issue by yxudong** [apache/skywalking#7004]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
https://github.com/apache/skywalking-nginx-lua

- What happened?

Hi,

In the skywalking-nginx-lua Doc, skywalking_tracer:finish() function will be called in body_filter_by_lua_block.
But in some case, the http request will not execute body_filter_by_lua phase. so this function will not be called.

example:

>     location = xxxxx/xxxxxx {
>         rewrite_by_lua_block {
>             skywalking_tracer:start("upstream service")
>         }
> 
>         proxy_pass http://xxxxxxxxxx;
>         proxy_connect_timeout 1;
>         proxy_send_timeout 1;
>         proxy_read_timeout 1;
> 
>         body_filter_by_lua_block {
>             if ngx.arg[2] then
>                 skywalking_tracer:finish()
>             end
>         }
> 
>         log_by_lua_block {
>             skywalking_tracer:prepareForReport()
>         }
>     }

   the proxy_read_timeout config is 1s, but if upstream reponse time more than that, nginx will has error log

>  upstream timed out (110: Connection timed out) while reading response header from upstream, xxxxxxxxxx

  In this case, the http request will not execute body_filter_by_lua phase, skywalking_tracer:finish() function is not be called also.

  So skywalking_tracer:finish() should execute in log_by_lua_block, in order to record upsteam status correctly.
  I tried to call skywalking_tracer:finish() in log_by_lua_block, it's work in this case.

**Comment by wu-sheng** [comment]
I think I have replied you, you should ask for help to Apache APISIX community. We are willing to accept the change if they confirm this is an incorrect use.

**Comment by wu-sheng** [comment]
SkyWalking community is not a place for Nginx/OpenResty experts. We are cooperating with Apache APISIX to build all these ecosystem, including Nginx-LUA, APISIX, KONG plugins.

**Comment by yxudong** [comment]
Sorry,

But I'm not found where can I report this issue.
the [skywalking-nginx-lua](https://github.com/apache/skywalking-nginx-lua#contact-us) write 

> submit an issue with [NIGNX-LUA] as the issue title prefix

 here. 
 Can you forward this issue to them or show where can I report issue about [skywalking-nginx-lua](https://github.com/apache/skywalking-nginx-lua) ?

**Comment by wu-sheng** [comment]
No, about Nginx/OpenResty tech stack, ask here, https://github.com/apache/apisix.

> submit an issue with [NIGNX-LUA] as the issue title prefix

All these are only related to the source code details. Your question is about how to use OpenResty/LUA API.
