### ISSUE TITLE
apm-trace-ignore-plugin-8.5.0.jar not working in Win10

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [apache/skywalking#7012]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
- What do you want to know?
apm-trace-ignore-plugin won't work in Win10 environment

___
### Bug
- Which version of SkyWalking, OS, and JRE?
- SkyWalking 8.5.0
- Win10
- jre1.8.0_271

- What happened?
Here is my configuration steps:
1. copy apm-trace-ignore-plugin-8.5.0.jar from \agent\optional-plugins to \agent\plugins
2. created a file named apm-trace-ignore-plugin.config in \agent\config
3. edit the file with param 
`trace.ignore_path=/eureka/**`
4. restart all applications
5. change the file with
 `trace.ignore_path=${SW_AGENT_TRACE_IGNORE_PATH:/eureka/**}` 
6. restart all applications

From agent log, I can see that apm-trace-ignore-plugin was loaded successfully and the config was also found.
But In both configuration ways apm-trace-ignore-plugin will fail to work, skywalking UI still shows the unexpected urls.

I have no idea what is going on, I have done all the steps properly which doc told me to do so.
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by WilliamChen-luckbob** [comment]
In additional, the skywalking service I used was downloaded from 
[official](https://apache.claz.org/skywalking/8.5.0/apache-skywalking-apm-es7-8.5.0.tar.gz)

setup by following steps:
1. unzip the tar.gz file
2. config the agent before staring up my springboot applications
3. use \bin\startip.bat to start up service and UI
4. wait and see, skywalking runs well.

**Comment by wu-sheng** [comment]
I think you need to read source codes and verify why. There are test cases running in Linux and Windows.

**Comment by WilliamChen-luckbob** [comment]
> I think you need to read source codes and verify why. There are test cases running in Linux and Windows.

Well, according to my observation, in centOS, after starting up the applications, configured path /eureka/** won't work for a quite long time ( for more than 15 minutes after all applications were started successfully, new trace with with current timestamp and pattern /eureka/** still pop out in UI while eureka is doing heart beat) 

but that seems to become normal after lunchtime (about 2 hours later without any movement) ...

And still, in Win10, trace-ignore-plugin won't work at all with the same configuration. I've observed for over 20 minutes, new trace with unexpected pattern still pop out.

I 'll checkout the source code later and see why, thanks a lot!

**Comment by WilliamChen-luckbob** [comment]
> I think you need to read source codes and verify why. There are test cases running in Linux and Windows.
Problem Solved.

I think there maybe some problem about refreshing dashboard.

After set the config from 
`trace.ignore_path=/eureka/**` 
back to `trace.ignore_path=${SW_AGENT_TRACE_IGNORE_PATH:/eureka/**}`

I've set my eureka heartbeat interval to 1 second for observation.

I've started applications at about 2021-05-26 13:45:00.

while observing the UI for about 30 minutes, trace with pattern /eureka/** continues to show at 2021-05-26 14:10:00.
but at 2021-05-26 14:11:00 , all the traces with /eureka/** from 13:55:00 to current time suddenly disappeared, while old ones still show in UI dashboard.

After that , all this come to normal, the filter works in Win10 too.

**Comment by WilliamChen-luckbob** [comment]
At 14:24 , in Win10, the trace with pattern /eureka/** shows again after refreshing UI dashboard.

**Comment by wu-sheng** [comment]
At the community, we should take out codes. No matter how it performs at your side, that is on your own. If you want to discuss codes, we are glad to join.

**Comment by wu-sheng** [comment]
No update.
