### ISSUE TITLE
Use Skywalking with Sping Native

### ISSUE THREAD

**Issue by mattwmj** [apache/skywalking#7014]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1 ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

We are using Skywalking java agent with Spring Boot and they work together very well.

Recently, I am looking into Spring Native to speed up Spring Boot in Docker container.

https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/

However, It seems that Spring Native and GraalVM do not support java agent currently.

https://github.com/oracle/graal/issues/1065

I understand this defect is not about Skywalking, but is there a solution to use Skywalking when java agent is not an option?

Is there a feature that I can instrument java class with Skywalking during compile time?

Thanks!

**Comment by wu-sheng** [comment]
In theory, of course, you could. We keep our eyes on all static compiling solution for a while. But the community don't have anyone saying he/she wants to lead on that part.

**Comment by mattwmj** [comment]
> In theory, of course, you could. We keep our eyes on all static compiling solution for a while. But the community don't have anyone saying he/she wants to lead on that part.

Is there any document about Skywalking static compiling that I can start with?

**Comment by wu-sheng** [comment]
There isn't. No PMC member is on this. I think you could learn how Java compiling plugin works, such as maven system.
BTW, this solution also could work for Android. So, it is valuable, but complex.

**Comment by ricardo0624** [comment]
> There isn't. No PMC member is on this. I think you could learn how Java compiling plugin works, such as maven system.
> BTW, this solution also could work for Android. So, it is valuable, but complex.

打扰一下,原来提的issue言辞有很大的不妥,可不可以让我改改,我还怕影响不好
