### ISSUE TITLE
Hope support diff alarm rules to be sent to diff alarm callback

### ISSUE THREAD

**Issue by Tecyang** [apache/skywalking#7015]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [V] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement

Hope to provide support for configuring different alarm rules to be sent to different DingTalk groups

**Comment by wu-sheng** [comment]
Currently, no configuration related to this. And don't know anyone would like to contribute this.

**Comment by Tecyang** [comment]
If I do this enhancement (for webhooks), what do I need to do！
thanks for the  reply！

**Comment by wu-sheng** [comment]
This will make the configuration complex, which is why we didn't ask about this. 
We have a grpc alarm hook, how about you write a service to redirect alarms to different channels? Once you have your internal rules, shouldn't be hard.
