### ISSUE TITLE
Provide REST API for log collection endpoint

### ISSUE THREAD

**Issue by Shikugawa** [apache/skywalking#7025]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

In current implementation, we don't have REST endpoint for log collection endpoint. https://github.com/apache/skywalking/tree/master/oap-server/server-receiver-plugin/skywalking-log-recevier-plugin/src/main/java/org/apache/skywalking/oap/server/recevier/log/provider/handler

In some situations, we need to provide them.

**Comment by wu-sheng** [comment]
@hailin0 @kezhenxu94 I think we could add this for fluent-bit ecosystem.

**Comment by kezhenxu94** [comment]
Can’t we use gRPC protocol for fluentbit plugin?

**Comment by Shikugawa** [comment]
> Can’t we use gRPC protocol for fluentbit plugin?

gRPC is very large library and may cause improvement of the binary size of fluent-bit. It is used for embedding system so that not match for the usage to introduce it. This is why we should rely on simple REST API.

**Comment by kezhenxu94** [comment]
> > Can’t we use gRPC protocol for fluentbit plugin?
> 
> gRPC is very large library and may cause improvement of the binary size of fluent-bit. It is used for embedding system so that not match for the usage to introduce it. This is why we should rely on simple REST API.

Ok, make sense to me.

**Comment by wu-sheng** [comment]
@dmsolr @gxthrj We should add an issue to track HTTP log receicer on Satellite, and add gprc sender to transport for better performance, if logs are going to out of VPC or region.

**Comment by hailin0** [comment]
> @hailin0 @kezhenxu94 I think we could add this for fluent-bit ecosystem.

Need to recevie `native-json` format log in skywalking-log-recevier-plugi, support multiple collectors to report text logs?

**Comment by wu-sheng** [comment]
> > @hailin0 @kezhenxu94 I think we could add this for fluent-bit ecosystem.
> 
> Need to recevie [native-json](https://github.com/apache/skywalking/blob/master/docs/en/protocols/Log-Data-Protocol.md#Native-Json-Protocol) format log in skywalking-log-recevier-plugin, support multiple collectors to report text logs?

Yes, use HTTP + JSON, like the Kafka + JSON we have.
