### ISSUE TITLE
how to show service count and endpoint count in ui 

### ISSUE THREAD

**Issue by qlql489** [apache/skywalking#7030]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to show service count and endpoint count in ui like this，can't find setting in doc
![](http://image.nianlun.tech/2021/05/27/f7ff049ed13e30cc4ba04ae4b7b2687e.png)
___
### Bug
- Which version of SkyWalking, OS, and JRE?
 8.1
- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We removed that. Not available anymroe.

**Comment by wu-sheng** [comment]
v7, all things changed since v8.
