### ISSUE TITLE
Does skywalking support HSF framework

### ISSUE THREAD

**Issue by renhaizhou** [apache/skywalking#7035]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does skywalking support HSF framework? If not, can we modify the source code to support it
___

**Comment by wu-sheng** [comment]
Ask AliCloud, not our responsibility.
