### ISSUE TITLE
Can gRpc receiver and Kafka fetcher work together?

### ISSUE THREAD

**Issue by yaojingguo** [apache/skywalking#7042]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
In my use case, some trace segments would be reported to the OAP gRPC receiver. And some trace segments would be fetched to OAP from Kafka. And segments for the same trace might go to OAP server with different ways. 

Is my use case supported by SkyWalking?

**Comment by wu-sheng** [comment]
Yes, you can.
