### ISSUE TITLE
I am new to Skywalking . Want to install Skywalking and other agents 

### ISSUE THREAD

**Issue by Sajal8600** [apache/skywalking#7047]
Hi Folks , 

I am new to skywalking and i want to install Skywalking and other agents like which can send logs, metrices and traces . Please help me to install all components and test it end to end . From official documentation i am unable to understand.

Thanks
Sajal

**Comment by wu-sheng** [comment]
I am not sure what do you know unable to understand.

**Comment by Sajal8600** [comment]
What would be installation steps to see metrices , logs and traces and Skywalking UI ?
Like what should i install first in AKS cluster apart from UI ?

Eg : Prometheus , Zipkin , Side car etc

**Comment by wu-sheng** [comment]
You are using a complex system. Take one at a step. All these you mentioned are not in one documentation.

**Comment by Sajal8600** [comment]
Can you please just guide the steps as i am really very confused that what should be the steps ?
I am very new to this field. Please help me with the steps

**Comment by wu-sheng** [comment]
What do you want to do with step one? You are listing many things at one time.

**Comment by Sajal8600** [comment]
My bad . If i say that i want to start using Skywalking then what should be my first step for it's installation.

**Comment by Sajal8600** [comment]
Eg : If i want to test traces in SW UI then what all should i install step by step ?

**Comment by wu-sheng** [comment]
Set up OAP and UI, and install our javaagent by using `-javaagent:`. 
1. Agent, https://skywalking.apache.org/docs/main/latest/en/setup/service-agent/java-agent/readme/
2. OAP + UI, https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-setup/

**Comment by Sajal8600** [comment]
Thanks a lot wu-sheng . So step 1 and 2 will help me to collect only traces right ?

**Comment by wu-sheng** [comment]
SkyWalking agent will help you on trace, metric, topology and even alarm. Some plugins could do log collecting.
Read the whole doc, it helps.

**Comment by Sajal8600** [comment]
Thanks a lot Sir. I was able to get metrices and topology of bookinfo application. I followed steps from the documentation and was able to do. It's amazing.

**Comment by Sajal8600** [comment]
Hi Sir , 

How to get K8s monitoring in Skywalking . I want cluster info like nodes , namespaces . How should i proceed ?

![image](https://user-images.githubusercontent.com/84438488/120481592-e1446500-c3cd-11eb-8a0f-7c83d551144d.png)

**Comment by wu-sheng** [comment]
We have provided `node` tab, what is your question?

**Comment by Sajal8600** [comment]
I want to see my Kubernetes cluster information like Cluster , node and service . But i am not getting that in SW UI. For that can you help me how can i get that ?

My SW UI that i had installed .
![image](https://user-images.githubusercontent.com/84438488/120483013-55333d00-c3cf-11eb-9022-52132ec13786.png)

**Comment by Sajal8600** [comment]
![image](https://user-images.githubusercontent.com/84438488/120483424-b65b1080-c3cf-11eb-978b-6693119aaff9.png)

**Comment by wu-sheng** [comment]
Maybe you are 
1. Using an old version, upgrade the version. 8.5.0 began to provide k8s monitoring.
2. You used to set up an old version. Clean your browser local storage and cache.

**Comment by Sajal8600** [comment]
where can i provide K8s monitoring , i mean in which config file ?

**Comment by wu-sheng** [comment]
How about doc? Please don't rely on me for every answer. Read all documents.

https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-infrastructure-monitoring/#k8s-monitoring

**Comment by Sajal8600** [comment]
Hi Sir, 

I was able to get K8S monitoring UI .

Thanks

**Comment by Sajal8600** [comment]
Hi Sir, 

Can you please help me know how can i see trace and log in my Skywalking UI ? It is coming blank. I tried installing guestbook application to see it's traces and log in UI but nothing is coming. Do i need to install any other application like some Java application ?

![image](https://user-images.githubusercontent.com/84438488/121168562-b98f4a00-c870-11eb-8106-2ce11ab1f5f1.png)


Thanks
Sajal

**Comment by wu-sheng** [comment]
You need agents, don't have to be a Java agent. Read the projects page, we have many.
