### ISSUE TITLE
why was the witness class in springcloud gateway 2.1.x and 3.x both the same?

### ISSUE THREAD

**Issue by navychi** [apache/skywalking#7051]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
why was the witness class in springcloud gateway 2.1.x and 3.x both the same?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
- Windows 10 , JDK8

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
2.1.x plugin will not work properly when springcloud gateway 2.1.x and 3.x plugin exist in plugin folder.
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Why 2 optional plugins exist at the same time? 
Plugins contributed by many people, we can't explain all.
