### ISSUE TITLE
How to trace the sub-thread and display in web UI correctly 

### ISSUE THREAD

**Issue by Miemiemiemieqiang** [apache/skywalking#7053]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?
I want to monitor the sub-thread runtime states.
But i found it is replicated in Web-UI.

- Which version of SkyWalking, OS, and JRE?
SkyWalking: 8.5.0 with h2 and use default agent plugins
OS: MacOS
JRE: JDK-1.8.0_211

- What happened?
I created a new spring-boot project that only have the multi-thread task.

Import the dependency that
```xml
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-trace</artifactId>
            <version>8.5.0</version>
        </dependency>
```

and added the annotation `@TraceCrossThread` above my Task that implement `Runnable` interface.

I sent the request to the application, and received the response successfully.
Then l opened the ui,
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/39361661/120279196-be8c5080-c2e8-11eb-9665-da3c5eb48fae.png">
I found that there are 10 thread records + 1 http trace record and those detail info is the same include trace-id.

I want to know is it normal or not 
and what should l do to get the only one trace that exclude thread records in trace list.

**Comment by wu-sheng** [comment]
Read UI introduction doc, the left side list is not trace list, it is segment list.
