### ISSUE TITLE
How to configure an endpoint to push an alarm when it reports an error once

### ISSUE THREAD

**Issue by jianghebo** [apache/skywalking#7054]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What is the case? Why doing this?
We don't provide error count metric in default. You need to add oal script to do so.

**Comment by jianghebo** [comment]
> What is the case? Why doing this?
> We don't provide error count metric in default. You need to add oal script to do so.

I think that if there is an exception in the call between my endpoints, I want to push this exception as an alarm, but the only alarm I see now is endpoint_ relation_ resp_ time_ The number of timeouts configured by rule. Is there a way to do this in alarm?

**Comment by jianghebo** [comment]
> What is the case? Why doing this?
> We don't provide error count metric in default. You need to add oal script to do so.

![企业微信截图_16225383918073](https://user-images.githubusercontent.com/17865919/120297652-e46f2080-c2fb-11eb-8cb5-28b28183ac81.png)
Is it possible to push an alarm when an endpoint request returns an exception instead of a 200 status code

**Comment by wu-sheng** [comment]
If you don't have a current response code, I don't think OAL could take care of it.
