### ISSUE TITLE
No response to query

### ISSUE THREAD

**Issue by queenns** [apache/skywalking#7055]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
-  Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

How to troubleshoot and locate if the query result is not available, or have any suggestions
___
### Bug
- Which version of SkyWalking, OS, and JRE?
1.skywalking: v8.5.0
2.elasticsearch: 7.5.1
3.kafak-reporter-plugin and kafka-fetcher are turned on
4.Deployed in kubernetes,3 oap, 1 ui
5.Customized tomcat plugin implementation
[TomcatInvokeInterceptor](url)
```java
    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
                             MethodInterceptResult result) throws Throwable {
        Request request = (Request) allArguments[0];
        ContextCarrier contextCarrier = new ContextCarrier();

        CarrierItem next = contextCarrier.items();
        while (next.hasNext()) {
            next = next.next();
            next.setHeadValue(request.getHeader(next.getHeadKey()));
        }

        AbstractSpan span = ContextManager.createEntrySpan(request.getRequestURI(), contextCarrier);

        // ------------------------------Custom start-------------------------------------------
        String traceIdKey = "traceid";
        if (StringUtil.isNotEmpty(System.getenv("traceIdKey"))) {
            traceIdKey = System.getenv("traceIdKey");
        }

        String oldTraceId = null;
        if (StringUtil.isNotEmpty(request.getHeader(traceIdKey))) {
            oldTraceId = request.getHeader(traceIdKey);
        } else if (StringUtil.isNotEmpty(request.getHeader("x-request-id"))) {
            oldTraceId = request.getHeader("x-request-id");
        }

        if (StringUtil.isNotEmpty(oldTraceId)) {
            DistributedTraceId newDistributedTraceId = new NewDistributedTraceId(oldTraceId);
            ContextSnapshot contextSnapshot = ContextManager.capture();
            this.setFieldValue(contextSnapshot, "traceId", newDistributedTraceId);
            this.setFieldValue(contextSnapshot, "traceSegmentId", "X" + contextSnapshot.getTraceSegmentId());
            ContextManager.continued(contextSnapshot);
        }
        // ------------------------------Custom end-------------------------------------------

        Tags.URL.set(span, request.getRequestURL().toString());
        Tags.HTTP.METHOD.set(span, request.getMethod());
        span.setComponent(ComponentsDefine.TOMCAT);
        SpanLayer.asHttp(span);

        if (TomcatPluginConfig.Plugin.Tomcat.COLLECT_HTTP_PARAMS) {
            collectHttpParam(request, span);
        }
    }
```
```java
public class NewDistributedTraceId extends DistributedTraceId {
    public NewDistributedTraceId(String traceId) {
        super(traceId);
    }
}
```
- Which company or project?

- What happened?

After the cluster is installed successfully, there is no problem with a small amount of access data. After increasing the amount of access data, it is found that there is no response to the query today.

![微信图片_20210602105604](https://user-images.githubusercontent.com/20701102/120417389-56457980-c391-11eb-8b2a-75c9760da6db.png)
![微信图片_20210602105614](https://user-images.githubusercontent.com/20701102/120417394-58a7d380-c391-11eb-9e9f-5eb714d7f3b6.png)
![微信图片_20210602105622](https://user-images.githubusercontent.com/20701102/120417397-59406a00-c391-11eb-9ccd-af4634a01d7c.png)
![微信图片_20210602105627](https://user-images.githubusercontent.com/20701102/120417404-5b0a2d80-c391-11eb-9f68-78ba0582ddd7.png)

**Comment by wu-sheng** [comment]
Once you changed codes, they are your reponsibility. Don't ask to a community about your fork.

**Comment by queenns** [comment]
@wu-sheng 
When using 8.1(**But did not modify the custom code**), the cluster is unavailable after running for a period of time, and then I made a part of the transformation
1. There is a problem with the kubernetes cluster deployment mode,
Solution: --set oap.env.SW_CLUSTER=kubernetes
2. There are some error messages such as queue accumulation in the backend, which may be caused by a relatively large amount of data
Solution: kafak-reporter-plugin and kafka-fetcher are turned on
3. Large amount of data, elasticsearch upgrade configuration

Now use 8.5, and solve the above problems, but skywalking is not available today, ui and oap have no obvious abnormalities

**Comment by wu-sheng** [comment]
All you mentioned, we have documents to mention that. I can't see what is the point. You should understand, the community is a place to discuss tech and find a solution, rather than a place to provide diagnose service. 
Unless you have some specific questions, I don't think this is a valid question.

**Comment by queenns** [comment]
> All you mentioned, we have documents to mention that. I can't see what is the point. You should understand, the community is a place to discuss tech and find a solution, rather than a place to provide diagnose service.
> Unless you have some specific questions, I don't think this is a valid question.

Okay, just now, the cluster can query the results again. For the time being, this problem has not happened, although I don't know the reason.:flushed:
