### ISSUE TITLE
Span is missing from the trace list UI

### ISSUE THREAD

**Issue by wallezhang** [apache/skywalking#7063]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking: 8.5.0
OS: MacOS 11.4
JRE: 11

- What happened?
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/33749/120598353-c0851980-c478-11eb-9e03-d7c12e524839.png">

The list on the left side is missing a span named `Neo4j/Transaction/runAsync`.

**Comment by wu-sheng** [comment]
Read doc, left is trace segment, not span.

**Comment by wallezhang** [comment]
OK, I read the UI doc and TraceSegment class comment in the source, so if span crosses threads or processes there will be multiple trace segments, otherwise there will only be one. Thanks 😄
