### ISSUE TITLE
请问skywalking ui中的related  logs 如何上报

### ISSUE THREAD

**Issue by soooldier** [apache/skywalking#7064]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- 请问skywalking ui中的related  logs是什么概念呢？ 如何上报数据？golang sdk 

![image](https://user-images.githubusercontent.com/1681065/120632773-e7087c00-c49b-11eb-91fb-2883371f58f5.png)

**Comment by wu-sheng** [comment]
Why report duplicated issue? You are wasting other's time.

**Comment by andotorg** [comment]
log4j2 grepc appender report
