### ISSUE TITLE
kong agent with grpc protocol

### ISSUE THREAD

**Issue by conghuo** [apache/skywalking#7067]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
Why is the link span monitored by kong agent only 2.Cannot completely connect the entire call chain. Is there something wrong with my configuration?

kong-plugin-skywalking configuration：

![image](https://user-images.githubusercontent.com/22426964/120734426-6e490480-c51b-11eb-93f6-c7c60139e324.png)

Link tracking results：
![image](https://user-images.githubusercontent.com/22426964/120736588-17452e80-c51f-11eb-9589-9cde41111f74.png)

![image](https://user-images.githubusercontent.com/22426964/120736634-2fb54900-c51f-11eb-9389-d6298c52815e.png)

**Comment by wu-sheng** [comment]
@dmsolr Could you share some ideas?

**Comment by wu-sheng** [comment]
@dmsolr Also, why here, there is no peer detected as exit span?

**Comment by conghuo** [comment]
> @conghuo Do you have SkyWalking other language agents deployed? Are they using v3 protocol?

YES,We have deployed the java skywalking agent,using the  GRPC protocol

Link tracking results：
![image](https://user-images.githubusercontent.com/22426964/120741313-7149f200-c527-11eb-9f40-a18c6988de9c.png)

Could it be caused by the different traceid? If so, how can we solve it?

**Comment by wu-sheng** [comment]
That is the key, I think. I am not sure whether this works for grpc. We do http testing only.

**Comment by wu-sheng** [comment]
@conghuo Are you using our official plugin? https://luarocks.org/modules/apache-skywalking/kong-skywalking

**Comment by wu-sheng** [comment]
If not, try that. This is the only version we are going to respond.

**Comment by conghuo** [comment]
> If not, try that. This is the only version we are going to respond.

https://github.com/apache/skywalking-kong.git

**Comment by dmsolr** [comment]
> > @conghuo Do you have SkyWalking other language agents deployed? Are they using v3 protocol?
> 
> YES,We have deployed the java skywalking agent,using the GRPC protocol
> 
> Link tracking results：
> ![image](https://user-images.githubusercontent.com/22426964/120741313-7149f200-c527-11eb-9f40-a18c6988de9c.png)
> 
> Could it be caused by the different traceid? If so, how can we solve it?

The call stack is Client -- http --> Kong -- RPC --> service ?
First, we need to ensure you use the official plugin.

**Comment by conghuo** [comment]
> If not, try that. This is the only version we are going to respond.
We are using the official：
https://github.com/apache/skywalking-kong.git   branches: v0.1.1

**Comment by conghuo** [comment]
> > > @conghuo Do you have SkyWalking other language agents deployed? Are they using v3 protocol?
> > 
> > 
> > YES,We have deployed the java skywalking agent,using the GRPC protocol
> > Link tracking results：
> > ![image](https://user-images.githubusercontent.com/22426964/120741313-7149f200-c527-11eb-9f40-a18c6988de9c.png)
> > Could it be caused by the different traceid? If so, how can we solve it?
> 
> The call stack is Client -- http --> Kong -- RPC --> service ?
> First, we need to ensure you use the official plugin.

Client --> Kong -- http server -- RPC server

**Comment by dmsolr** [comment]
It is very strange that the component name should be `Kong` and the peer was `upstream service`.
Did you install other versions of skywalking-kong plugin before?

**Comment by conghuo** [comment]
> It is very strange that the component name should be `Kong` and the peer was `upstream service`.
> Did you install other versions of skywalking-kong plugin before?

Not，I build it using docker

Dockerfile
FROM kong:2.2.2
USER root
RUN luarocks install kong-plugin-skywalking
ENV KONG_NGINX_HTTP_LUA_SHARED_DICT="tracing_buffer 128m" 
USER kong

**Comment by dmsolr** [comment]
RUN luarocks install kong-plugin-skywalking -> RUN luarocks install kong-skywalking

**Comment by conghuo** [comment]
According to the installation instructions of the master, there is a problem, so I dit not use this instruction to install
luarocks install kong-skywalking 

![image](https://user-images.githubusercontent.com/22426964/120775221-95242c80-c555-11eb-90c8-332b8032b45d.png)

**Comment by dmsolr** [comment]
> According to the installation instructions of the master, there is a problem, so I dit not use this instruction to install
> luarocks install kong-skywalking
> 
> ![image](https://user-images.githubusercontent.com/22426964/120775221-95242c80-c555-11eb-90c8-332b8032b45d.png)

Fixed

**Comment by conghuo** [comment]
> > According to the installation instructions of the master, there is a problem, so I dit not use this instruction to install
> > luarocks install kong-skywalking
> > ![image](https://user-images.githubusercontent.com/22426964/120775221-95242c80-c555-11eb-90c8-332b8032b45d.png)
> 
> Fixed


The upgrade has been completed, but the same problem
![image](https://user-images.githubusercontent.com/22426964/120791977-73cc3c00-c567-11eb-86d4-6b68bf3d6581.png)

Link tracking results：
![image](https://user-images.githubusercontent.com/22426964/120792266-d1608880-c567-11eb-8f52-c75942838960.png)

The complete call chain of this interface should be as follows：
![image](https://user-images.githubusercontent.com/22426964/120792547-4633c280-c568-11eb-98ea-f90a5325b64b.png)

**Comment by dmsolr** [comment]
Looks look it is not working with the skywalking official plugin.
kong-plugin's component name should `kong` or `Unknown`(component id = 6001). and the peer MUST NOT be `upstream service`.

![image](https://user-images.githubusercontent.com/29735230/120880198-5779df00-c5fb-11eb-95c3-2cc95a22540c.png)

![image](https://user-images.githubusercontent.com/29735230/120880211-6cef0900-c5fb-11eb-82d5-4bd1e6c3710e.png)

**Comment by conghuo** [comment]
> Looks look it is not working with the skywalking official plugin.
> kong-plugin's component name should `kong` or `Unknown`(component id = 6001). and the peer MUST NOT be `upstream service`.
> 
> ![image](https://user-images.githubusercontent.com/29735230/120880198-5779df00-c5fb-11eb-95c3-2cc95a22540c.png)
> 
> ![image](https://user-images.githubusercontent.com/29735230/120880211-6cef0900-c5fb-11eb-82d5-4bd1e6c3710e.png)

Strange, is there a requirement for the kong version? Can you share your installation and configuration methods? Dockerfile is best

**Comment by conghuo** [comment]
?

**Comment by dmsolr** [comment]
Sorry for missing the message.
I have tested on kong 2.2.0 and 2.3.0.
In your case, there is only one possibility that another version had been installed in your env before.

**Comment by dmsolr** [comment]
You cloud have a try this [docker-compose.yaml](https://github.com/dmsolr/docker-library/blob/main/kong/docker-compose.yaml)

**Comment by wu-sheng** [comment]
No update in 10 days.
