### ISSUE TITLE
Kettle run abnormally with MongoDB after deployed agent

### ISSUE THREAD

**Issue by pmq5205209** [apache/skywalking#7072]
Runtime Environment: Kettle 7.1.0.0-12, Java 1.8, Windows 10, Skywalking-agent 6.5, Mongo-java-driver 3.2.2.

After kettle started，I started a task which needed to query data from Mongodb.
**When run the task for the first time, Kettle would report these errors.**
2021/06/04 16:47:27 - mongodb输入.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unexpected error
2021/06/04 16:47:27 - mongodb输入.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : java.lang.NoClassDefFoundError: org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/EnhancedInstance
2021/06/04 16:47:27 - mongodb输入.0 - 	at java.lang.ClassLoader.defineClass1(Native Method)
2021/06/04 16:47:27 - mongodb输入.0 - 	at java.lang.ClassLoader.defineClass(Unknown Source)
2021/06/04 16:47:27 - mongodb输入.0 - 	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2318)
2021/06/04 16:47:27 - mongodb输入.0 - 	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1524)
2021/06/04 16:47:27 - mongodb输入.0 - 	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
2021/06/04 16:47:27 - mongodb输入.0 - 	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
2021/06/04 16:47:27 - mongodb输入.0 - 	at java.lang.ClassLoader.loadClass(Unknown Source)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.connection.DefaultConnectionFactory.create(DefaultConnectionFactory.java:23)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.connection.DefaultServer.getConnection(DefaultServer.java:72)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:86)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:237)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.operation.FindOperation.execute(FindOperation.java:482)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.operation.FindOperation.execute(FindOperation.java:79)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.Mongo.execute(Mongo.java:772)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.Mongo$2.execute(Mongo.java:759)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:851)
2021/06/04 16:47:27 - mongodb输入.0 - 	at com.mongodb.DBCursor.hasNext(DBCursor.java:152)
2021/06/04 16:47:27 - mongodb输入.0 - 	at org.pentaho.mongo.wrapper.cursor.DefaultCursorWrapper.hasNext(DefaultCursorWrapper.java:34)
2021/06/04 16:47:27 - mongodb输入.0 - 	at org.pentaho.di.trans.steps.mongodbinput.MongoDbInput.processRow(MongoDbInput.java:87)
2021/06/04 16:47:27 - mongodb输入.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/06/04 16:47:27 - mongodb输入.0 - 	at java.lang.Thread.run(Unknown Source)
2021/06/04 16:47:27 - mongodb输入.0 - Caused by: java.lang.ClassNotFoundException: org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance not found by org.mongodb.mongo-java-driver [65]
2021/06/04 16:47:27 - mongodb输入.0 - 	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1556)
2021/06/04 16:47:27 - mongodb输入.0 - 	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
2021/06/04 16:47:27 - mongodb输入.0 - 	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
2021/06/04 16:47:27 - mongodb输入.0 - 	at java.lang.ClassLoader.loadClass(Unknown Source)
2021/06/04 16:47:27 - mongodb输入.0 - 	... 22 more**

**When run the task after the first time and , Kettle would report these errors.**
2021/06/04 17:00:12 - mongodb输入.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unexpected error
2021/06/04 17:00:12 - mongodb输入.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : java.lang.NoClassDefFoundError: com/mongodb/connection/DefaultServerConnection
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.connection.DefaultConnectionFactory.create(DefaultConnectionFactory.java:23)
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.connection.DefaultServer.getConnection(DefaultServer.java:72)
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:86)
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:237)
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.operation.FindOperation.execute(FindOperation.java:482)
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.operation.FindOperation.execute(FindOperation.java:79)
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.Mongo.execute(Mongo.java:772)
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.Mongo$2.execute(Mongo.java:759)
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:851)
2021/06/04 17:00:12 - mongodb输入.0 - 	at com.mongodb.DBCursor.hasNext(DBCursor.java:152)
2021/06/04 17:00:12 - mongodb输入.0 - 	at org.pentaho.mongo.wrapper.cursor.DefaultCursorWrapper.hasNext(DefaultCursorWrapper.java:34)
2021/06/04 17:00:12 - mongodb输入.0 - 	at org.pentaho.di.trans.steps.mongodbinput.MongoDbInput.processRow(MongoDbInput.java:87)
2021/06/04 17:00:12 - mongodb输入.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/06/04 17:00:12 - mongodb输入.0 - 	at java.lang.Thread.run(Unknown Source)

**Comment by wu-sheng** [comment]
I think we don't declare Kettle is on the support list.
