### ISSUE TITLE
skywaling 8.5 Storage issues

### ISSUE THREAD

**Issue by conghuo** [apache/skywalking#7074]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
It was found that after skywaling was upgraded from 7.0 to 8.5, the data volume of es index sw_segment-xx increased by almost half under the same service volume and visit volume.
For advice, which parameter is related to the size of segment-index data in version 8.5?

**Comment by wu-sheng** [comment]
Check changelog. I think we don't change segment entity for a long time.
