### ISSUE TITLE
oap alarm config can support i18n？

### ISSUE THREAD

**Issue by lmx1989219** [apache/skywalking#7076]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ✓ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Right now, it can't. You could consider to contribute it. But the question would be, how to determine the language?

**Comment by lmx1989219** [comment]
@wu-sheng its a good idea.

**Comment by wu-sheng** [comment]
We could continue once you have real solution.
