### ISSUE TITLE
Dynamic configuration for a set of configurations.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7081]
Currently, `ConfigChangeWatcher` only allows implementors to register a key for a dynamic configuration update. With more configurations being dynamic, we may not provide all keys, such as all MAL scripts.

@wankai123 @mrproliu @kezhenxu94 @dmsolr or other @apache/skywalking-committers do we have any ideas about how to add another dynamic configuration API for a set of data?

I don't think we have to keep compatible with the existing one, the keys about this feature are 
1. Watcher could indicate a name/key for multiple items.
2. Every item of the name/key could be changed/updated separately, which means it could be maintained separately.

**Comment by dmsolr** [comment]
Not watcher entirely configuration file anymore? And replacing it with all keys of configuration items.
If so, the result was `alarm-settings.yaml` + `alarm.default.alarm-settings.xxxx` (e.g. rules), righ?

**Comment by wu-sheng** [comment]
Not replace, another new option. I think not all configuration requiring a list.

**Comment by kezhenxu94** [comment]
> With more configurations being dynamic, we may not provide all keys, such as all MAL scripts.

Using MAL as an example, do you mean every single rule 👇 (like `heap_memory_used`) can be updated separately?

https://github.com/apache/skywalking/blob/f54f639c4d9207c20490519121eeabe6acf37374/oap-server/server-bootstrap/src/main/resources/envoy-metrics-rules/envoy.yaml#L34-L59

If this is what you proposed, the config keys would be too many to manage

**Comment by wu-sheng** [comment]
> > With more configurations being dynamic, we may not provide all keys, such as all MAL scripts.
> 
> 
> 
> Using MAL as an example, do you mean every single rule 👇 (like `heap_memory_used`) can be updated separately?
> 
> 
> 
> https://github.com/apache/skywalking/blob/f54f639c4d9207c20490519121eeabe6acf37374/oap-server/server-bootstrap/src/main/resources/envoy-metrics-rules/envoy.yaml#L34-L59
> 
> 
> 
> If this is what you proposed, the config keys would be too many to manage

I don't mean expression. The case is like, MAL script files could be modified and added in the runtime. But we don't know the file name, a.k.a. key name, unless it is added.
So, we have to use a key called OC-MAL-SCRIPTS as a key of the whole collection.

**Comment by kezhenxu94** [comment]
> I don't mean expression. The case is like, MAL script files could be modified and added in the runtime. But we don't know the file name, a.k.a. key name, unless it is added.
> So, we have to use a key called OC-MAL-SCRIPTS as a key of the whole collection.

I still don't see how would that affect dynamic configuration and why we need this kind of modifications in dynamic configuration level.

If the MAL files are still on filesystem, we only need a single config item for example `receiver-zabbix.default.activeFiles=agent,newly-added-file-name` to trigger rescanning the config files.

If the MAL files contents are in config center totally, in this case, we don't have to seperate the rules into several "files", no? Then we only need a new config item, say `receiver-zabbix.default.dynamicMetricsRules`, whose content can be anything that `receiver-zabbix` can parse

**Comment by wu-sheng** [comment]
> If the MAL files are still on filesystem

No, it doesn't exist in local OS system. Think in this way, OAP is running in the dev/local env, even maybe in prod, users want to accept metrics from a new system, and build MAL scripts accordingly. How is this possible?

>  the MAL files contents are in config center totally, in this case, we don't have to seperate the rules into several "files", no?

We don't separate or manage file content. Instead, the key is managing the files themselves. #7039 's key point is not just updating the content, which should be done, but not all. We expect to add a new config file.

> Then we only need a new config item, say receiver-zabbix.default.dynamicMetricsRules

Yes, if we only consider from tech perspective. But if a management backend or a team manages these settings, it would be chaos if we only accept one MAL file for the whole receivers.
Also, if you still think MAL is not a strong argue(which I think it should, but just in case), take a look at #7113 context. We are going to support OpenAPI spec importing to enhance endpoint grouping rules. It is unrealistic to ask users to merge all OpenAPI spec files for the whole distributed system(200-400 services usually) into one file to be managed and watched. 
Even they accepted this, the one line changed could cause content update event of a huge file, which is not friendly from any point, including performance impact or debug.

**Comment by wu-sheng** [comment]
> No, it doesn't exist in local OS system. Think in this way, OAP is running in the dev/local env, even maybe in prod, users want to accept metrics from a new system, and build MAL scripts accordingly. How is this possible?

@kezhenxu94  We are moving the OAP to fully configurable in the runtime, including the UI templates. One day in this or next year, UI template should be considered that, could be imported from UI directly. 
I plan to sync with the whole community about this agenda, but at least, we could sync here. Many contributors from different vendors/groups are showing more interest to build commercial services on top of us, let's make the core level ready.
Of course, tenancy and data authority/permission are not being considered. Every vendor/product(s) have their own agenda.

**Comment by kezhenxu94** [comment]
> > If the MAL files are still on filesystem
> 
> No, it doesn't exist in local OS system. Think in this way, OAP is running in the dev/local env, even maybe in prod, users want to accept metrics from a new system, and build MAL scripts accordingly. How is this possible?

This doesn't explain why we need the changes, let's ignore this situation if it is not a reason to bring the proposed changes, (I gave some possibilities that might need the proposed changes).

> But if a management backend or a team manages these settings, it would be chaos if we only accept one MAL file for the whole receivers.

This is a perfect reason why we need the changes.

> The case is like, MAL script files could be modified and added in the runtime. But we don't know the file name, a.k.a. key name, unless it is added.

I'm interested in how the proposed changes solve this if the key is even unknown yet? How to register a listener for an unknown config item?

**Comment by wu-sheng** [comment]
> This doesn't explain why we need the changes, let's ignore this situation if it is not a reason to bring the proposed changes, (I only gave some possibilities that might be a reason).

This actually is. Because this is a cause.

> I'm interested in how the proposed changes solve this if the key is even unknown yet? How to register a listener for an unknown config item?

That is a thing we need to research. But at least for something, I know from a configuration server
1. CDS is easy to support, as it is a coded system.
2. Zookeeper could watch a whole path's children.
3. Others with no children mechanism, could support an encoded structure, the value of a known key is a list `key:encode(value)` pair.

The key of this feature is not about making a configuration server to do something special but inside the SkyWalking OAP server. 

> I'm interested in how the proposed changes solve this if the key is even unknown yet? How to register a listener for an unknown config item?

I think this is the biggest gap for you. Because you are thinking this listening mechanism is for configuration server, like etcd, Nacos, etc. But it isn't.

**Comment by wu-sheng** [comment]
From reading #7130, I am feeling we should add dynamic configuration APIs as following
1. `ConfigChangeWatcher` add a new constructor parameter `WatchType`(enum), to set whether dynamic configuration implementor should support a set(map) of config.  The config should be a `key:value` list, which dynamic configuration implementor could determine how to represent the key and value.
2. The element of the set, should be presented as a new `subkey` in the `ConfigChangeEvent` when do event notification.
