### ISSUE TITLE
TracesTags doesn't support className and method by default

### ISSUE THREAD

**Issue by legendwu9527** [apache/skywalking#7087]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
   - Feature or performance improvement

___
### Question
- What do you want to know?
- In an APM system, classname and method are common  trace information, for example,classname and method were used in the 
 customize-enhance-plugin.  Because of system resources or other reasons skywalking doesn't support these two parameters currently?

___
### Requirement or improvement
- if we support  the tags of  classname and method by default, we could get the  span info more precisely.

**Comment by wu-sheng** [comment]
I think it is included in the operation name already.
