### ISSUE TITLE
How to support high QPS with skywalking?

### ISSUE THREAD

**Issue by aaronray** [apache/skywalking#7088]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Question or discussion

___
### Question
- What do you want to know?

I need to monitor a system which have a 50000 QPS at most. Dose one skywalking cluster(with zookeeper) support my needs. What do I have to do to optimize skywalking cluster in order to handle high QPS?

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
50k is not a challenge at all. I don't know why this is a question the community should answer.
