### ISSUE TITLE
Does skywalking support unique traceid across two or more skywalking cluster?

### ISSUE THREAD

**Issue by aaronray** [apache/skywalking#7089]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
In my accasion, one skywalking cluster was deployed in an IDC, but the other skywalking cluster was deployed in another IDC. For example, a request crossed the two IDC ,handled by several micro services. How to get the unique traceid in different skywalking cluster? Thanks a lot!

**Comment by wu-sheng** [comment]
Don't think this is SkyWalking issue. We don't set any limitation.
