### ISSUE TITLE
https_proxy doesn't work for skywalking-oap-server:8.5.0-es7

### ISSUE THREAD

**Issue by john1337** [apache/skywalking#7097]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
i set https_proxy  in docker-compose for skywalking-oap-server,but it can't send message using dingtalk 
by the way, i am running skywalking-oap-server in a net which   can't rich internet,so i have to use proxy to rich outside,but sadly it didn't work for me.

**Comment by wu-sheng** [comment]
This is not the community's responsibility. Your env replies on yourself.
