### ISSUE TITLE
Traceid cannot find the log

### ISSUE THREAD

**Issue by renhaizhou** [apache/skywalking#7105]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Traceid cannot find the log，Background database table log does not generate data，Do you need to configure any parameters？
![image](https://user-images.githubusercontent.com/41145169/121493045-02c6d180-ca0a-11eb-81f5-ee0937c9f742.png)

![image](https://user-images.githubusercontent.com/41145169/121493313-4a4d5d80-ca0a-11eb-8852-829140bbf83f.png)

**Comment by wu-sheng** [comment]
Trace id injection based on your log framework settings.
Database dashboard requires database related spans collected.

**Comment by renhaizhou** [comment]
![image](https://user-images.githubusercontent.com/41145169/121496047-ae712100-ca0c-11eb-93b7-d98bb6b6bb1a.png)
Tracking ID set based on log framework has been injected
Why is there no data yet?

**Comment by wu-sheng** [comment]
If you are using Java, you have 2 choices.
1. Use log reporter. 8.5.0+ required.
2. Use filebeat or fluentd to collect, LAL scripts to build trace and log relationship. 8.6.0+ required.
