### ISSUE TITLE
can i set webhooks notify timeout time

### ISSUE THREAD

**Issue by john1337** [apache/skywalking#7107]
Please answer these questions before submitting your issue.

___
### Question
how can i set webhooks call timeout time when skywalking-oap send alert message,i use nginx to forward reponse outside,here's the message from nginx:
proxy_connect: client read timed out while connecting to upstream, client: xx.xxx.xx.xx, server: , request: "CONNECT oapi.dingtalk.com:443 HTTP/1.1

i seems like the skywalking-oap timeout before nginx receive the reponse from dingtalk

i'am wondering how can i set webhooks  notify timeout time

**Comment by wu-sheng** [comment]
We send HTTP request to 3rd party, whether it is a really dingtalk endpoint, or your proxy, it depends on you. 
Alarm or not, it is on your side.

**Comment by john1337** [comment]
> We send HTTP request to 3rd party, whether it is a really dingtalk endpoint, or your proxy, it depends on you.
> Alarm or not, it is on your side.

yes,but skywalking use httpclient to send message,apprently there should be one setting to config http timeout parameter

**Comment by wu-sheng** [comment]
> > We send HTTP request to 3rd party, whether it is a really dingtalk endpoint, or your proxy, it depends on you.
> > Alarm or not, it is on your side.
> 
> yes,but skywalking use httpclient to send message,apprently there should be one setting to config http timeout parameter

The codes are there, take a look by yourself.
