### ISSUE TITLE
Can not get value from TraceContext.getCorrelation()

### ISSUE THREAD

**Issue by ZHANG-GXJ** [apache/skywalking#7110]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to use TraceContext.putCorrelation() properly?
 

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking: 8.2.0
OS: MAC 11.4
JRE: 1.8
- Which company or project?
Micro service

- What happened?
I am using skywalking to track kafka message.I put the traceId into kafka header, then I get the traceId from kafka header at consumer side. Then, cause I can not get traceId by TraceContext.traceId() from consumer side. I want to put the value like this: TraceContext.putCorrelation("traceId", traceId). So that I can get traceId by TraceContext.getCorrelation("traceId"). However, the value is empty. 
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Maybe I'm missing something. Anyone can tell me a right way to achieve this? Any help will be appreciated.

**Comment by ZHANG-GXJ** [comment]
Here are some code and logs:
Code:
`log.info( "===Headers-traceId==={}", traceId );
        TraceContext.putCorrelation( "traceId", traceId );
        log.info( "Step0: Start. traceId:{}", TraceContext.getCorrelation( "traceId" ) );`
Logs:
`===Headers-traceId===b871f6620a76412ab23794b9c11801f2.118.16234074007380001
2021-06-11 18:30:03.862  INFO 17034 --- [ntainer#1-0-C-1] c.s.m.message.TopicConsumer              : Step0: Start. traceId:Optional.empty`

**Comment by ZHANG-GXJ** [comment]
Besides, I had tried to put the info from kafka producer side, but it still can not get value from consumer side.

**Comment by wu-sheng** [comment]
Do you read after consumering? If not, it is not realistic to get.
Two, the trace id is not read by this way. Don't know why you are using this.
Your way of using is not following official document.

**Comment by jj2784992** [comment]
I have encountered the same problem. May I know how it was resolved in the end

**Comment by jj2784992** [comment]
app-gateWay:
TraceContext.putCorrelation("demo_userId", s);

app-A1:
TraceContext.getCorrelation("demo_userId") return is empty

agent config:
correlation.auto_tag_keys=${SW_CORRELATION_AUTO_TAG_KEYS:demo_userId}

May I know how it was resolved in the end? thanks
