### ISSUE TITLE
Add logging level switching API in OAP backend for debugging purpose

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7114]
For now, we have some logs that are very helpful in debugging and troubleshooting but too verbose to be printed in production environment, hence we print them in `DEBUG` level.

However, switching the log level requires OAP to restart and that may make the errors recover from a restart, so in this issue, we're going to discuss and implement a new API that allows users to switch a particular logger's level. This is kind of similar to [Spring Boot Actuator loggers endpoint](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.loggers).

Another doc provided by @hanahmily is [log4j auto-config](https://logging.apache.org/log4j/2.x/manual/customconfig.html)

**Comment by wu-sheng** [comment]
This should be a core level enhancement. As it is important for prod env.
