### ISSUE TITLE
Questions about writing service-traffic

### ISSUE THREAD

**Issue by LiWenGu** [apache/skywalking#7115]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

At present, I found that the writing of service_traffic (ServiceTrafficDispatcher) is only triggered when analyzing the segment reported by the client. However, although some applications do not report segment, the instance information has been reported, such as jvm data. On the oap page, you must first check the service_traffic information before you can check the specific instance information (even if the client has uploaded the instance information, it cannot be queried on the oap page, but it can be obtained in the jvm related table of the ES). Is this reasonable? Would it be better if the writing of service_traffic is triggered in the register of the client?

![image](https://user-images.githubusercontent.com/15909210/121771482-32104680-cba2-11eb-8909-300bb43a5390.png)

**Comment by wu-sheng** [comment]
Which agent are you talking about? Are you really facing a case or just guessing when read source codes?

**Comment by LiWenGu** [comment]
Really facing a case about this. Our agent only uses the dubbo plugin, and we have a service A which has no dubbo-related logic, but we want to monitor its machine and jvm information. However, because service_traffic does not have the service information, we cannot search on the oap background service page, but the jvm information of the service is actually stored in es.

**Comment by wu-sheng** [comment]
It is most likely you changed the source codes, rather than the official agent. Where is your codebase from?

**Comment by LiWenGu** [comment]
I will check it carefully, we did change the source code, but did not change this place. In addition, we use the kafka-reporter-plugin

**Comment by wu-sheng** [comment]
Do you cut the grpc channel when you use kafka reporter? You should know, once you change source codes, you are on your own.
There is nothing the community could do, or should do.

**Comment by adamscotthi** [comment]
Thanks a lot for information, was searching for it
