### ISSUE TITLE
[CLI] `swctl` GitHub Action for integration of CI/CD workflows to report events

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7116]
Nowadays, we have event reporter for Java agent, Kubernetes, etc., there are cases where users don't use Java and still need to integrate `swctl` into their CD workflow to report deployments events, having a GitHub Action for this purpose makes our users easily integrate into their workflows, if they are using GHA for deployments.

This gives an example of the best practice to report events in CD workflows, future contributors may also want to provide Jenkins plugin, GitLab plugin, etc.

**Comment by wu-sheng** [comment]
It seems good to go.
