### ISSUE TITLE
the minimum configuration of the machine to deploy OAP service

### ISSUE THREAD

**Issue by renhaizhou** [apache/skywalking#7117]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What is the minimum configuration of the machine to deploy OAP service

**Comment by wu-sheng** [comment]
We don't have such thing. Quick start is no config required at local env.
