### ISSUE TITLE
[Python] Collect log with Python agent

### ISSUE THREAD

**Issue by Humbertzhang** [apache/skywalking#7118]
As kezhenxu94 said in #7084, the Python agent now focus on trace, but log is also an important pillars of Observability.
This time we want to add log collect support in Python agent, it will use existing protocol as defined in [this pr](https://github.com/apache/skywalking-data-collect-protocol/pull/35), and @Superskyyy will be working on this.

We will track this task in this issue.

**Comment by Superskyyy** [comment]
Thank you! I'll do my best to implement this feature.

**Comment by wu-sheng** [comment]
Is this summer 2021 task?

**Comment by Humbertzhang** [comment]
> Is this summer 2021 task?

Yes, it's a summer 2021 task.

**Comment by wu-sheng** [comment]
But we don't have official announcement from program committee. We should not statement, we have selected candidate.

**Comment by Humbertzhang** [comment]
> But we don't have official announcement from program committee. We should not statement, we have selected candidate.

I see. Should I edit this issue?

**Comment by wu-sheng** [comment]
Let's keep this, but don't do this again. FYI to all @apache/skywalking-committers

**Comment by kezhenxu94** [comment]
Closed by https://github.com/apache/skywalking-python/pull/147#event-5126394531
