### ISSUE TITLE
Concurrent create PrepareRequest when persist Metrics

### ISSUE THREAD

**Issue by a1vin-tian** [apache/skywalking#7120]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ * ] Feature or performance improvement

Skywalking v8.4.0
Elasticsearch 7.8.1

___
### Requirement or improvement

I watched the Grafana and found persist to ES is too slow that costs 600s. 

![51567F30EFE0EBE075423524701AE310](https://user-images.githubusercontent.com/4693441/122004726-5c9f1100-cde7-11eb-9d8e-12ed8a5bb659.jpg)
![image](https://user-images.githubusercontent.com/4693441/122009934-2d8b9e00-cded-11eb-8a88-ecc378f8bc19.png)

I found that there are 2 steps in the PersistenceTimer.extractDataAndSave 

Step 1: Prepare requests which searching ES for merge Metrics. (Need Concurrent)
Step 2: Persist prepare request that we made in `Step 1` to ES. (Already fixed in https://github.com/apache/skywalking/issues/6472)

I fix in my code.  This is the result. 

![image](https://user-images.githubusercontent.com/4693441/122007444-8443a880-cdea-11eb-99e7-0dd4dd5261ee.png)

```
List<Future<List<PrepareRequest>>> futures = new ArrayList<>(persistenceWorkers.size());
persistenceWorkers.forEach(worker -> {
    futures.add(prepareExecutorService.submit(() -> {
        if (log.isDebugEnabled()) {
            log.debug("extract {} worker data and save", worker.getClass().getName());
        }
        List<PrepareRequest> innerPrepareRequests = new ArrayList<>(5000);

        worker.buildBatchRequests(innerPrepareRequests);

        worker.endOfRound(System.currentTimeMillis() - lastTime);
        return innerPrepareRequests;
    }));

});
for (Future<List<PrepareRequest>> future : futures) {
    List<PrepareRequest> requests = future.get();
    if(CollectionUtils.isNotEmpty(requests)){
        prepareRequests.addAll(requests);
    }
}
```

Can we change it to concurrent when we prepare the request?

**Comment by wu-sheng** [comment]
@a1vin-tian Thanks for reporting this case clearly. We used to optimize execution in concurrency as we only have a report about we facing that issue.

Because you have proved the case existing, which should be optimized. One question for your codes, do you run preparing in batch mode(your Step 1) and wait until all subtasks finished, then run into the persistent stage(your Step 2)?

**Comment by a1vin-tian** [comment]
@wu-sheng  Yes,  Step 2 waits until step 1 all subtasks finished at present. But we can do step 1 and step 2 concurrently, which will shorten the entire persistence time.

**Comment by wu-sheng** [comment]
>  Yes, Step 2 waits until step 1 all subtasks finished at present. But we can do step 1 and step 2 concurrently, which will shorten the entire persistence time.

I am thinking about this, as this could use the storage performance more efficiently due to part in the preparation stage and the other part in flushing. Do you have data to compare these 2 ways to verify the feeling?

**Comment by wu-sheng** [comment]
Another way to fix is also merging the channels, which is going to be done once @mrproliu makes the Satellite ready for java agent.

**Comment by a1vin-tian** [comment]
I am going to verifying it this week. It needs more time. 

> Another way to fix is also merging the channels, which is going to be done once @mrproliu makes the Satellite ready for java agent.

At present,  I think our bottleneck is that there are too many series needs to storage as well as search at the batch stage. Use Using Satellites seems to be unable to solve the storage problem, because the  series  cardinality have not changed in the end

**Comment by wu-sheng** [comment]
> I am going to verifying it this week. It needs more time. 
> 
> 
> 
> > Another way to fix is also merging the channels, which is going to be done once @mrproliu makes the Satellite ready for java agent.
> 
> 
> 
> At present,  I think our bottleneck is that there are too many series needs to storage as well as search at the batch stage. Use Using Satellites seems to be unable to solve the storage problem, because the  series  cardinality have not changed in the end

Satellite reply is wrong context. Please ignore.

**Comment by a1vin-tian** [comment]
Metrics "all" means  entire  `PersistenceTimer.extractDataAndSave` cost.

Stage 1 and Stage 2 are executed sequentially.
![image](https://user-images.githubusercontent.com/4693441/122351707-fc43d700-cf80-11eb-949d-f7568995276f.png)
State 1 and Stage 2 are executed parallelly.
![image](https://user-images.githubusercontent.com/4693441/122351718-ff3ec780-cf80-11eb-9278-35fb81c4aab2.png)

Time shortened by 1-2 times.

**Comment by wu-sheng** [comment]
OK, it seems as expected. I think you should have enough background to submit a pull request, right?

**Comment by a1vin-tian** [comment]
Ok. I  will do it recently.
