### ISSUE TITLE
Evaluate Webapp container(Spring boot 1.x + Zuul) replacement options

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7122]
We were using Spring boot 1.x and Zuul gateway as the webapp container to host UI, and bypass GraphQL query to OAP. According to @hanahmily https://github.com/apache/skywalking/pull/7119#discussion_r652272379, we are facing continuous CVEs, which should drive us to look for a replacement solution.
 
To all @apache/skywalking-committers , we have the following options.
1. Keep in Java, upgrade to Spring boot 2.x, use Spring Gateway or something in Spring ecosystem to host UI. This solution would be coherent.
2. Use NodeJS server to provide service, which basically we to just simply distribute rocketbot-ui in a server mode, and 100% adopt NodeJS ecosystem. @Jtrust @Fine0830 What do you think about this?

**Comment by wu-sheng** [comment]
Any other suggestion is also welcome.

**Comment by hanahmily** [comment]
If we adopted to 2, the dev UI docker image building artifacts should be transferred to the UI repo, the release UI docker process should be updated correspondingly.

**Comment by kezhenxu94** [comment]
Both works for me.

But I just want to remind that the number of dependencies in NodeJS is sometimes unpredictably LARGE even if you only import a simple package, and CVEs in NodeJS is not necessarily less than Java. It would be helpful if UI team could evaluate before we make a final decision.

**Comment by wu-sheng** [comment]
Notice, in this issue, we don't discuss `UI release separately`. The query protocol keeps upgrading and enhancing, this is not a good time to do so. We don't recommend mismatched UI and OAP versions.

**Comment by Fine0830** [comment]
Can we use `Nginx` to provide web server? CVEs seems to be avoided.

**Comment by wu-sheng** [comment]
> Can we use `Nginx` to provide web server? CVEs seems to be avoided.

We could use Nginx or APISIX/OpenResty, if we want. @Fine0830 So, you don't like NodeJS to host service directly, right?

**Comment by Fine0830** [comment]
> > Can we use `Nginx` to provide web server? CVEs seems to be avoided.
> 
> We could use Nginx or APISIX/OpenResty, if we want. @Fine0830 So, you don't like NodeJS to host service directly, right?

Yes. For fixing CVEs, If we adopted to 2, there will be other uncontrollable problems. like this, 

![1](https://user-images.githubusercontent.com/20871783/122148571-477cbd80-ce8d-11eb-8517-7516d30f97d7.png)

**Comment by wu-sheng** [comment]
OK than. @hanahmily it seems moving to Spring Gateway + Spring boot 2 would be better.

**Comment by heyanlong** [comment]
I think it would be good to use nginx to host the UI, and i often do this in my work. only need to put the compiled UI in the www directory to provide high-quality services.

**Comment by wu-sheng** [comment]
> I think it would be good to use nginx to host the UI, and i often do this in my work. only need to put the compiled UI in the www directory to provide high-quality services.

The challenge about Nignx/OpenResty/APISIX is all about how to distribute so many distributions for different OS.

**Comment by heyanlong** [comment]
as far as i know, nginx can run on unix, linux and windows

**Comment by wu-sheng** [comment]
> as far as i know, nginx can run on unix, linux and windows

It can, but with different binary tars. So we have to release -linux, -win, etc. Then plus we have -es6 and -es7, it would be a huge release set.

**Comment by wu-sheng** [comment]
@JaredTan95 Let's try Spring boot 2 and Spring Gateway.
