### ISSUE TITLE
[DiSCUSSION] OAL supports generating metrics from events

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7126]
It's kind of doubtful at the first thought of letting OAL support events, but I lately believe it's helpful for some events to be supported by OAL, especially in Kubernetes events, such that we can have metrics to answer the questions like

- How often pods cannot be scheduled? Are they related to capacity errors?
- What is the distribution of Pods, Deployments Created / Updated through out the day?
- Are there significant amount of "Error" events right now?

@wu-sheng what do you think of this

**Comment by wu-sheng** [comment]
It makes sense, but within these cases, should we conside whether MAL is a good option? Or is it still reasonable using MAL replace OAL?

**Comment by kezhenxu94** [comment]
I'd rather finish this feature first as it takes very little efforts but brings important features to Event concept in our landscape. Replacing OAL with MAL is architecture optimization after all. I haven't dived too much into replacing OAL with MAL up to now.

**Comment by wu-sheng** [comment]
I am fine with enhancing the OAL as we have no decision about whether OAL is replaceable or not.
