### ISSUE TITLE
agent sampling config option `sample_n_per_3_secs `

### ISSUE THREAD

**Issue by luckymrwang** [apache/skywalking#7128]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
SAMPLE_N_PER_3_SECS is -1 by default which means sampling N TraceSegment in 3 seconds tops in the document.

I have two questions:
- What's the max value? `N` means unlimited？
- What is the reasonable range?  Many documents suggest it is in 500~1500, and is it right?
___
### Bug
- Which version of SkyWalking, OS, and JRE?
v8.3.0
- Which company or project?
Inspur
- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> What's the max value? N means unlimited？
What is the reasonable range? Many documents suggest it is in 500~1500, and is it right?

No recommendation. SkyWalking Java agent could work in 100% sampling in 5000 tps only with 10% extra CPU. We designed this years ago to support large scale distributed system.
