### ISSUE TITLE
Format all HTTP related operation name in METHOD:URI

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7135]
@wankai123 Due to #7130, we should adjust all Java related plugin, and make sure the format is correct. And we should update plugin dev doc about this.

All @apache/skywalking-committers, other language agents should take care of this too.

**Comment by kezhenxu94** [comment]
Should also only count response code 5xx as errors?

https://github.com/apache/skywalking/pull/7111

**Comment by wu-sheng** [comment]
> Should also only count response code 5xx as errors?
> 
> #7111

We should count that as an error at the client side, but that is a different context. This issue is relating to operation name because OpenAPI spec support.

**Comment by wu-sheng** [comment]
@wankai123 After you finish the group dynamic configuration, you could take care of this. We should have several weeks before cut 8.8.0 release, because there will a long testing about our new Elastic client implementation.

**Comment by wu-sheng** [comment]
@wankai123 I just moved the milestone, due to Java agent moved out of main repo.
