### ISSUE TITLE
请问skywalking过滤不需要监控的路径，接口路径为{GET,POST}/apis/m1_contact_photo_isUpload/v1.0，配置到apm-trace-ignore-plugin.config中怎么写都不生效，请问有什么办法过滤掉这个路径？万分感谢！

### ISSUE THREAD

**Issue by cy145** [apache/skywalking#7142]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please use English on GitHub. We need things readable globally.

**Comment by wu-sheng** [comment]
There are a lot of blogs out there to tell you how to do this.
