### ISSUE TITLE
question about apm-trace-ignore-plugin

### ISSUE THREAD

**Issue by cy145** [apache/skywalking#7143]
The skywalking filter interface {GET,POST}/apis/m1_contact_photo_isUpload/v1.0 that does not need to be monitored, configured to apm-trace-ignore-plugin.config, trace.ignore_path=*/apis/m1_contact_photo_isUpload/* is invalid, because {And, is it unrecognizable?Can you tell me how to write trace.ignore_path to take effect?

**Comment by cy145** [comment]
Missing punctuation

**Comment by katelei6** [comment]
apm-trace-ignore-plugin.config  I config the path like this: /actuator/**,/actuator,Redisson/**   Redisson can work，but  /actuator/**, do not work!@wu-sheng
