### ISSUE TITLE
question about  apm-trace-ignore-plugin

### ISSUE THREAD

**Issue by cy145** [apache/skywalking#7144]
The skywalking filter interface {GET,POST}/apis/m1_contact_photo_isUpload/v1.0 that does not need to be monitored, configured to apm-trace-ignore-plugin.config, trace.ignore_path=*/apis/m1_contact_photo_isUpload/*   is invalid, because {And, is it unrecognizable?Can you tell me how to write trace.ignore_path to take effect?__

**Comment by wu-sheng** [comment]
Read the documentation, we never said you should config like this. `{GET,POST}/apis/m1_contact_photo_isUpload/v1.0` is the operation name, your config should match this.
