### ISSUE TITLE
Why skywalking need add a new  ‘_$EnhancedClassField_ws’ filed and Is there any potential such risk?

### ISSUE THREAD

**Issue by gaoweijie** [apache/skywalking#7146]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- Why skywalking need add a new  ‘_$EnhancedClassField_ws’ filed into origin source class when skywalking do enhance logic.
Is there any potential such risk about this logic? For example as below:
      When the business code takes out all the fields of a class (which has been enhanced by bytecode) through reflection for processing, it will also take out '_$EnhancedClassField_ws'  field for logical processing, which will cause problems.

**Comment by wu-sheng** [comment]
Your question is very hard to answer. In any case, with any form, you could say adding codes always have a bug. So, from a tech perspective, the answer would only have to be YES. There is a risk.

**Comment by wu-sheng** [comment]
If you look at the source codes of plugin, such as popular SpringMVC, you will see why we need that.

**Comment by gaoweijie** [comment]
> If you look at the source codes of plugin, such as popular SpringMVC, you will see why we need that.

OK, thanks.

**Comment by gaoweijie** [comment]
I carefully read the source code of springmvc, still have a little incomprehensible.
Can you give me some explanation or inspiration.
Thank you very much.

**Comment by wu-sheng** [comment]
You need a class level cache to hold the context for instrumentation. Otherwise, you have to resolve the context every time, which is a big performance issue.

**Comment by gaoweijie** [comment]
> You need a class level cache to hold the context for instrumentation. Otherwise, you have to resolve the context every time, which is a big performance issue.

Thanks.
