### ISSUE TITLE
dashboard serivce can't choose

### ISSUE THREAD

**Issue by start1943** [apache/skywalking#7147]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- dashboard serivce can't choose

___
### Bug
- version:8.6

- What happened?
dashboard  after select server ,get a error: 
TypeError: Cannot read property 'key' of undefined
Search history issues，this problem possible is service_traffic index have duplicate data.  try to delete all xx_service_traffic_yymmdd, and restart oapserver....but new index service_traffic not have all service-name, Must  restarts N++ oap-server, every restart , index service_traffic，there's more service，we used java-agent ,The metric is always reported ,  i want to ask, when can the problem of duplicate data be fixed.  or Restart one only and get all the service data

**Comment by wu-sheng** [comment]
`this problem possible is service_traffic index have duplicate data.` This is an issue with your storage. We have explained this many many times, this means your metrics is not accurate. We keep this duplicate issue for you as a warning.

**Comment by wu-sheng** [comment]
Your ElasticSearch is not available in a part of the time, that is why duplicate data generated. You should take care of it first rather than asking us to swallow an exception of your env.

**Comment by start1943** [comment]
I confirm that there is no problem with  ES. Before we use is version 8.2, is not met this problem , recently upgraded to 8.6, because the cause of the business version deployment agent is not all the upgrade is complete. I don't know if this will cause problem.. ES and oap have not any error log。

**Comment by wu-sheng** [comment]
> I confirm that there is no problem with ES. Before we use is version 8.2, is not met this problem , recently upgraded to 8.6, because the cause of the business version deployment agent is not all the upgrade is complete. I don't know if this will cause problem.. ES and oap have not any error log。

The codes only insert duplicate when query is not available. That is why we said so. This is not a thing you could confirm. It is a runtime issue.

**Comment by start1943** [comment]
Well, how do I solve this problem? Have any plan to  fix this kind of data duplication。If can't resolve it, Looks like only roll back OAP version。。。Or do you have any better suggestions

**Comment by wu-sheng** [comment]
Again, this is your ElasticSearch error. Why you keep repeating?

**Comment by wu-sheng** [comment]
We only will resolve UI to work in this case, but keep duplicated services. Again and again, your ElasticSearch has performance issue, or yellow status occasionally.
It is not a thing SkyWalking could do.

**Comment by start1943** [comment]
Well, thanks for your reply

**Comment by SZMOFEI** [comment]
> Your ElasticSearch is not available in a part of the time, that is why duplicate data generated. You should take care of it first rather than asking us to swallow an exception of your env.

We met the same problem, which is effective
