### ISSUE TITLE
Webui query time intervals not latest while refresh ?

### ISSUE THREAD

**Issue by Chasun-fhd** [apache/skywalking#7148]
![image](https://user-images.githubusercontent.com/8635910/122742046-29152880-d2b8-11eb-9fdd-08389fc24d44.png)

why the webui query time intervals  are not latest, event if i refresh the page manually ? Is  there any specific consideration ? 
seems like it recorded last chosen time intervals.

**Comment by wu-sheng** [comment]
There is refresh button in the right top bottom.
