### ISSUE TITLE
Update Maven Repository

### ISSUE THREAD

**Issue by Kyle-Dwyer** [apache/skywalking#7150]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Hello, I notice that version 8.6.0 has been released, but the related toolkit has not been updated in Maven(https://mvnrepository.com/artifact/org.apache.skywalking/apm-toolkit-logback-1.x), so that the function of printing skywalking context to logs cannot be used. Could you please release it?
![image](https://user-images.githubusercontent.com/34733051/122753270-97f87e80-d2c4-11eb-8fd6-ba84c5557901.png)

**Comment by kezhenxu94** [comment]
@wu-sheng I also noticed this just now

**Comment by wu-sheng** [comment]
I forgot to release for maven central. Thanks for reporting.
I just did. Let's wait for several hours to see.

**Comment by wu-sheng** [comment]
ASF maven repo confirmed release done. We need to wait for Maven central update.

**Comment by wu-sheng** [comment]
I can see the 8.6.0 available here, https://search.maven.org/artifact/org.apache.skywalking/apm-toolkit-logback-1.x/8.6.0/jar.

I am not sure when https://mvnrepository.com/artifact/org.apache.skywalking/apm-toolkit-logback-1.x gets sync, but should not be long.

Closing this, as this thing has been fixed on our side.
