### ISSUE TITLE
skywalking stored on elasticsearch and create too many index ，and index doc  count is zero

### ISSUE THREAD

**Issue by xuanyuan1hao** [apache/skywalking#7152]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [*] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- skywalking会创建太多的索引库，我这里进行了代码修改，删除一天以前历史记录中文档数量为0的索引库。

### Requirement or improvement
- 修改代码：HistoryDeleteEsDAO .java 
- long  deadline2 = Long.parseLong(new DateTime().plusDays(-1).toString("yyyyMMdd"));
-  for (String index : indexes) {
            long timeSeries = TimeSeriesUtils.isolateTimeFromIndexName(index);
            if (deadline >= timeSeries||(client.indexDocIsZero(tableName) && deadline2>= timeSeries)) {
                prepareDeleteIndexes.add(index);
            } else {
                leftIndices.add(index);
            }
        }
- 
修改代码：ElasticSearchClient.java

public boolean indexDocIsZero(String tableName) throws IOException {
        SearchSourceBuilder sourceBuilder = new SearchSourceBuilder();
        SearchRequest rq = new SearchRequest();
        //索引
        rq.indices(tableName);
        //各种组合条件
        rq.source(sourceBuilder);
        //其实位置
        sourceBuilder.from(0);
        //每页数量
        sourceBuilder.size(1);
        SearchResponse search = client.search(rq);
        return search.getHits().totalHits==0;
    }

**Comment by wu-sheng** [comment]
I don't know which version are you talking about. Could you be more clear when you ask a question. Putting some codes here is not making sense.

**Comment by xuanyuan1hao** [comment]
sorry, 我这里的代码有点问题，主要意思就是看1天以前建立的索引库是否为空的索引库，如果是的话就删除了，留着没什么用。

**Comment by wu-sheng** [comment]
If you want to talk with the Community on the GitHub. We have to ask you to use English, to make the global people readable.
Anyway, can't see your point, seems not a community level question.

**Comment by xuanyuan1hao** [comment]
正确代码应该如下：
public boolean indexDocIsZero(String tableName,RestHighLevelClient client) throws IOException {
        SearchSourceBuilder sourceBuilder = new SearchSourceBuilder();
        sourceBuilder.from(0);
        sourceBuilder.size(1);
        SearchRequest rq = new SearchRequest();
        rq.indices(tableName);
        rq.source(sourceBuilder);
        SearchResponse search = client.search(rq);
        return search.getHits().getHits().length==0;
    }

**Comment by xuanyuan1hao** [comment]
ok, thanks ,i will  talk use english

**Comment by wu-sheng** [comment]
There would no index should be empty, unless you are facing a very low load system.  I can't see why you are asking about deleting indices. But once you are doing it in your private fork, you could do anything you want. Again, this seems not a community concern.

SkyWalking doesn't create index if there is no data, except the day one when the system installed.
