### ISSUE TITLE
delete empty index for history on skywalking8.5

### ISSUE THREAD

**Issue by xuanyuan1hao** [apache/skywalking#7154]
i change code on file HistoryDeleteEsDAO .java  in about 59 lines 

long deadline2 = Long.parseLong(new DateTime().plusDays(-1).toString("yyyyMMdd"));
for (String index : indexes) {
long timeSeries = TimeSeriesUtils.isolateTimeFromIndexName(index);
if (deadline >= timeSeries||(client.indexDocIsZero(tableName) && deadline2>= timeSeries)) {
prepareDeleteIndexes.add(index);
} else {
leftIndices.add(index);
}
}

add method on file  ElasticSearchClient.java 

/**
     * adjust index is empty
     * @param tableName
     * @return
     * @throws IOException
     */
    public boolean indexDocIsZero(String tableName) throws IOException {
        SearchSourceBuilder sourceBuilder = new SearchSourceBuilder();
        SearchRequest rq = new SearchRequest();
        rq.indices(tableName);
        rq.source(sourceBuilder);
        sourceBuilder.from(0);
        sourceBuilder.size(1);
        SearchResponse search = client.search(rq);
        return search.getHits().getHits().length==0;
    }

**Comment by wu-sheng** [comment]
Why do you open a new one?
