### ISSUE TITLE
How to classify endpoints

### ISSUE THREAD

**Issue by Little-kangaroo** [apache/skywalking#7156]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
**I want to aggregate all endpoints in an application according to different types, but I can't find out how to distinguish the types of these endpoints**

It's like this：
![image](https://user-images.githubusercontent.com/17957051/122905336-b7a2ac00-d383-11eb-9e52-ec67b29c43ab.png)

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No, there is no such thing existing.
