### ISSUE TITLE
Query trace should sort by startTime to reduce VNode

### ISSUE THREAD

**Issue by liuzhiguo630** [apache/skywalking#7157]
I found lot of VNode in trace, but they are exists in storage, just limit by query size:
https://github.com/apache/skywalking/blob/1bc69370bfcd3891b0726c219e1ae39b92d8f894/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/query/TraceQueryEsDAO.java#L166

So I add `sourceBuilder.sort(SegmentRecord.START_TIME, SortOrder.ASC);` in `queryByTraceId`, VNode are all disappeared. if trace's size over limit, tail of the trace will not shown, not head or middle.

**Comment by wu-sheng** [comment]
I am not sure what do you mean adding a start_time sort could help.

**Comment by liuzhiguo630** [comment]
> I am not sure what do you mean adding a start_time sort could help.

Sure, because you haven't really use Skywalking in real world. I do.

**Comment by wu-sheng** [comment]
> > I am not sure what do you mean adding a start_time sort could help.
> 
> Sure, because you haven't really use Skywalking in real world. I do.

If this is your attitude to respond to a question, I can't see why you bother to talk with a community.  This issue will be locked forever. Once you do this again, we will check across for your behavior.
