### ISSUE TITLE
Query trace should support "show current segment only"

### ISSUE THREAD

**Issue by liuzhiguo630** [apache/skywalking#7158]
When trace too long -- it's common to happen, such as application produce lots of message to MQ  -- , it'll over limit of segmentQueryMaxSize(default to 200), user maybe can't find his application's segment forever.

show current segment only will help people find his segment in trace, just see what he cared part in trace.

**Comment by wu-sheng** [comment]
This is not about trace view. I am afraid this can't be accepted by the community.

**Comment by liuzhiguo630** [comment]
Wrong, it is about trace view. In a long trace, people cannot view their part in trace. This makes traceview useless.

I realized these scenes you can't understand. You haven't really worked in a big company, or monitor a big system right?
