### ISSUE TITLE
[Client JS] headers could be null

### ISSUE THREAD

**Issue by aoxls** [apache/skywalking#7161]
[https://github.com/apache/skywalking-client-js/blob/master/src/trace/interceptors/fetch.ts#L82](https://github.com/apache/skywalking-client-js/blob/master/src/trace/interceptors/fetch.ts#L82)

if `args[1]` is an object without property `headers`, it will throw an exception here.

suggestion：
```js
if (!args[1]) {
    args[1] = {};
}
if (!args[1].headers) {
    args[1].headers = {};
}
args[1].headers['sw8'] = values;
```

**Comment by wu-sheng** [comment]
@aoxls If you want a bug to fix, you could submit a pull request directly.

**Comment by aoxls** [comment]
OK, I have submitted a pull request already, please review it.

https://github.com/apache/skywalking-client-js/pull/61
