### ISSUE TITLE
 Profile.duration  in agent.config , but it's Profile.MAX_DURATION in Config.java

### ISSUE THREAD

**Issue by tangxqa** [apache/skywalking#7162]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
-  Profile.duration  in agent.config , but it's Profile.MAX_DURATION in Config.java

___
### Bug
- Which version of SkyWalking, OS, and JRE?
v8+

- What happened?
 Profile.duration  in agent.config , but it's Profile.MAX_DURATION in Config.java

**Comment by wu-sheng** [comment]
Could you send a pull request to fix config file? And check what document says.
