### ISSUE TITLE
When configuring a gateway without the agent installed in gateways.yml, can the topology be improved?

### ISSUE THREAD

**Issue by heihaozi** [apache/skywalking#7165]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement

If the gateway does not have a agent installed, after configuring it in `gateways.yml`, the upstream and downstream of the gateway cannot be displayed in the topology. The topology display is incomplete.

For example: 

Service A calls service B through the gateway. Select service A in the topology, it shows this:

```
A --> Gateway
```

Select service B in the topology, it shows this:

```
Gateway --> B
```

But I think the desired topology should be like this:

```
A --> B
```

Here is another complicated example:
Service A calls service B through the gateway. Service C calls service D through the gateway. 
If services A, B, and D are in a group, and this group is selected in the topology, it shows this:

```
                        
A --> Gateway --> B
         |
         ↓
         D
```

It is easy to be misunderstood that service A calls service D through the gateway.

**Comment by wu-sheng** [comment]
> But I think the desired topology should be like this:

I don't think this is expected. Could you explain your point?

> Service A calls service B through the gateway. Service C calls service D through the gateway.
If services A, B, and D are in a group, and this group is selected in the topology, it shows this:

This is always what we expect to see, `one-level-jump` group topology never would be complete topology. 

___
Besides all above, why you don't have an agent on Gateway? This uninstrumented setting is for a gateway not supported, but SkyWalking covers most popular gateway, even the ones we don't, I think you should add for them.

**Comment by heihaozi** [comment]
Thank you for such a quick response.

For example, when `service A` is called, it is called through `gateway G`.

In the topology, only the calls of `service A` and `gateway G` are shown.

However, which real services call `service A` through `gateway G` is very necessary from a business perspective.

**Comment by wu-sheng** [comment]
Yes, I know. Your description is correct. My point is, topology is not about data flowing. From topology, you always could find this edge case, no matter how many jumps you are going to show.
You could try yo think in this way.

**Comment by heihaozi** [comment]
I got it, thank you for your answers.
