### ISSUE TITLE
[Client JS] ajaxErrors doesn't support fetch

### ISSUE THREAD

**Issue by aoxls** [apache/skywalking#7166]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
Hi ~ I found that `ajaxErrors` doesn't contains the errors of `fetch`, should it be supported ? 
By the way, would you please conside to add a params in `register`method, to customize ajaxError, just like some business exception?

**Comment by Fine0830** [comment]
`PromiseErrors` is able to catch fetch errors

**Comment by aoxls** [comment]
> `PromiseErrors` is able to catch `fetch` errors

`PromiseErrors` just catches the unhandled rejections,  it won't work if I catched in my code, maybe it's better to create an interceptor?

**Comment by Fine0830** [comment]
Let's fix this.
