### ISSUE TITLE
please provide the Log Analysis Language  text  regexp debugger 

### ISSUE THREAD

**Issue by zhouhuicong** [apache/skywalking#7168]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Feature or performance improvement
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
when i use the Log Analysis Language to parser the  unstructured logs. i  have to configure the text regexp .  but I need to change the regular expression many times and then restart the oapsever. It is inefficient to load tests for many times .   the Skywalking can it be provided the regular expression parser debugger  like the kibana grok debugger

**Comment by wu-sheng** [comment]
I am not sure what Kibana does, but it makes sense to have a tool to debug, and make the behavior predictable.
But we need to see who wants to do this.

**Comment by kezhenxu94** [comment]
This is Java regex and there are a bunch of tester out there for test and debugging, https://www.google.com.hk/search?q=java+regex+tester&safe=strict&client=safari&hl=en-cn&sxsrf=ALeKk01O7h-PjV9rN3nj76LKhdvSIauC6A%3A1624617447086&ei=57HVYOnCBIKMr7wP77uTyA4&oq=java+regex+tester&gs_lcp=ChNtb2JpbGUtZ3dzLXdpei1zZXJwEAMyBQgAEMQCMgIIADICCAAyAggAMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BAgAEEdQ8RVYrRdgyRhoAHACeACAAZwBiAGcAZIBAzAuMZgBAKABAcgBCMABAQ&sclient=mobile-gws-wiz-serp

**Comment by wu-sheng** [comment]
> This is Java / Groovy regex and there are a bunch of tester out there for test and debugging, https://www.google.com.hk/search?q=java+regex+tester&safe=strict&client=safari&hl=en-cn&sxsrf=ALeKk01O7h-PjV9rN3nj76LKhdvSIauC6A%3A1624617447086&ei=57HVYOnCBIKMr7wP77uTyA4&oq=java+regex+tester&gs_lcp=ChNtb2JpbGUtZ3dzLXdpei1zZXJwEAMyBQgAEMQCMgIIADICCAAyAggAMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BAgAEEdQ8RVYrRdgyRhoAHACeACAAZwBiAGcAZIBAzAuMZgBAKABAcgBCMABAQ&sclient=mobile-gws-wiz-serp

@kezhenxu94 I haven't checked, I think he means a simulator, could get input and output, without running the OAP.

**Comment by wu-sheng** [comment]
@kezhenxu94 @Fine0830 Once #7180 has a solid result, we should have a discussion about how to do this. We may need a debug UI to interact with the backend. I don't have a design yet, let's discuss when the LAL engine is improved.

**Comment by wu-sheng** [comment]
@Fine0830 Is RocketBot UI suitable to pop up(or open a new window) for debugger tools? It should have 2 inputs and 1 output, which are listed like project kanban. And we need to add one more for MAL, @wankai123 I think you will like this idea.

Inputs have
1. Orginal text of log, @kezhenxu94 Should we support multiple logs?
2. LAL configuration

Output should be
1. The results of every execution stage
2. Final log in the database if it will be persistent.
3. Metrics output
4. @kezhenxu94 You could add one.

This should not be hard to implement in SkyWalking backend, we just need a debuger-tool GraphQL.

**Comment by kezhenxu94** [comment]
> 1. Orginal text of log, @kezhenxu94 Should we support multiple logs?

Supporting 1 or 1+ logs seems no difference from frontend or backend side, let's support this.

**Comment by wu-sheng** [comment]
> > 1. Orginal text of log, @kezhenxu94 Should we support multiple logs?
> 
> Supporting 1 or 1+ logs seems no difference from frontend or backend side, let's support this.

The key is how to separate records because one log record could include multiple lines.

**Comment by kezhenxu94** [comment]
Well, I finally realize that this should be done only after we address the security of LAL or https://github.com/apache/skywalking/issues/6897, otherwise this would be a security problem

**Comment by wu-sheng** [comment]
#6897 would be withdraw, because I have done the research, it is too complex, and too dangerous to cause OOM and GC storm in the load traffic load.

**Comment by wu-sheng** [comment]
@dmsolr Please take a reference from here, and we should have MAL debug tool too.

**Comment by kezhenxu94** [comment]
Then we need to harden the LAL engine to make it more secure

**Comment by wu-sheng** [comment]
> Then we need to harden the LAL engine to make it more secure

Yes, we need to control its runtime scope. In and in debug sandbox only. Also this mechanism could benefit the MAL debug tool.

**Comment by kezhenxu94** [comment]
> > Then we need to harden the LAL engine to make it more secure
> 
> Yes, we need to control its runtime scope. In and in debug sandbox only. Also this mechanism could benefit the MAL debug tool.

Sandboxing the Groovy runtime is also very complex and may bring CVEs, I once did some research on this too and found https://github.com/jenkinsci/groovy-sandbox, which is not a general-purpose tool but can be reference, it also has some limitations.

**Comment by wu-sheng** [comment]
> > > Then we need to harden the LAL engine to make it more secure
> > 
> > 
> > Yes, we need to control its runtime scope. In and in debug sandbox only. Also this mechanism could benefit the MAL debug tool.
> 
> Sandboxing the Groovy runtime is also very complex and may bring CVEs, I once did some research on this too and found https://github.com/jenkinsci/groovy-sandbox, which is not a general-purpose tool but can be reference, it also has some limitations.

Sorry for misleading. I am not taking about real sandbox. What I want to say is, we need to determine which variables and methods are allowed in the groovy runtime we build, because in MAL or LAL case, we don't allow to use Java class or any 3rd party class.

**Comment by kezhenxu94** [comment]
> > > > Then we need to harden the LAL engine to make it more secure
> > > 
> > > 
> > > Yes, we need to control its runtime scope. In and in debug sandbox only. Also this mechanism could benefit the MAL debug tool.
> > 
> > 
> > Sandboxing the Groovy runtime is also very complex and may bring CVEs, I once did some research on this too and found https://github.com/jenkinsci/groovy-sandbox, which is not a general-purpose tool but can be reference, it also has some limitations.
> 
> Sorry for misleading. I am not taking about real sandbox. What I want to say is, we need to determine which variables and methods are allowed in the groovy runtime we build, because in MAL or LAL case, we don't allow to use Java class or any 3rd party class.

They are basically the same complexity, to build a boundary that what codes can be run and what codes cannot, https://github.com/jenkinsci/groovy-sandbox is for the same purpose as our use case.

**Comment by wu-sheng** [comment]
Yes, it wouldn't be easy. We have to try to find a `Constructor` to limit the scope. Also, providing a disable option and add a comment at the doc saying this is for dev stage only, would help to hold the CVE process.

**Comment by wu-sheng** [comment]
Open this. The next step is on the UI side.

**Comment by wu-sheng** [comment]
@Fine0830 Any update about debugger UI?

**Comment by Fine0830** [comment]
With the new environment @kezhenxu94 gave me last night, I'm in the process of realizing and self-test the function.

**Comment by wu-sheng** [comment]
@kezhenxu94 I think we need a tool on the UI introduction page to talk about this? And we need to be clear `SW_QUERY_GRAPHQL_ENABLE_LOG_TEST_TOOL` should be activated.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 I think we need a tool on the UI introduction page to talk about this? And we need to be clear `SW_QUERY_GRAPHQL_ENABLE_LOG_TEST_TOOL` should be activated.

What kind of tool do you mean?


> BTW, what does our UI say if `SW_QUERY_GRAPHQL_ENABLE_LOG_TEST_TOOL=false`?

It should be something like this

<img width="1792" alt="Screen Shot 2021-09-06 at 21 56 28" src="https://user-images.githubusercontent.com/15965696/132228449-e94fc066-d641-4327-abbc-9e1bf9223abf.png">

**Comment by wu-sheng** [comment]
> What kind of tool do you mean?

I mean we should add document about this tool.  

> It should be something like this

Could you make the backend response more clear? Such as directly saying `xxx is not activated, and follow yyy to open it`.

___

@Fine0830 I just noticed, the tool name is LAL. Could you rename it to `Log Analysis Language Debugger`?

**Comment by Fine0830** [comment]
> @Fine0830 I just noticed, the tool name is LAL. Could you rename it to `Log Analysis Language Debugger`?

Sure.
