### ISSUE TITLE
missing db.statement tag for jedis blocking api

### ISSUE THREAD

**Issue by Yolo-Hao** [apache/skywalking#7170]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
SkyWalking latest

- What happened?
when using jedis blocking api like `blpop`，it won't have a `db.statement` tag, because it only check type `String` and `byte[]` for first argument as below:
```java
if (allArguments.length > 0 && allArguments[0] instanceof String) {
    Tags.DB_STATEMENT.set(span, method.getName() + " " + allArguments[0]);
} else if (allArguments.length > 0 && allArguments[0] instanceof byte[]) {
    Tags.DB_STATEMENT.set(span, method.getName());
}
```
maybe we need to add a check for `Integer`

**Comment by wu-sheng** [comment]
Feel free to enhance plugin, you could send a pull request. Also, you need to enhancr plugin integration test case.

**Comment by wu-sheng** [comment]
Closing due to author's comments, https://github.com/apache/skywalking/pull/7185#issuecomment-870201002
