### ISSUE TITLE
8.5无法查看不到三天前的数据真的需要改代码嘛，，，昨天确认了，昨天晚上看的还有，今天就没了，但是查看es 23号的索引还是在的

### ISSUE THREAD

**Issue by tscuite** [apache/skywalking#7178]
8.5无法查看不到三天前的数据真的需要改代码嘛，，，昨天确认了，昨天晚上看的还有，今天就没了，但是查看es 23号的索引还是在的

**Comment by tscuite** [comment]
需要进行代码修改吗，在官方文档也没有查询到相关配置

**Comment by wu-sheng** [comment]
We only accept English discussion on GitHub for global people. TTL doc is there.
