### ISSUE TITLE
Revert 7091:Use MAL to calculate JVM metrics, remove OAL dependency.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7181]
@liqiangz We have received confirmation, MAL is not suitable in high load. This change should be reverted. #7091 can't be reverted automatically through GitHub, could you send a pull request to finish this revert?

This performance issue is not caused by MAL, actually, we found it through LAL, which is most likely caused by the groovy engine. Check #7180 for more details.

**Comment by liqiangz** [comment]
@wu-sheng  ok.
