### ISSUE TITLE
How to get traceid while using Spring Cloud Gateway

### ISSUE THREAD

**Issue by Owenxh** [apache/skywalking#7188]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Bug

___
### Bug
- Which version of SkyWalking, OS, and JRE?
Skywalking 8.6.0

- What happened?
I am using Spring Cloud Gateway 3.x in our project. I also add  apm-spring-cloud-gateway-3.x-plugin-8.6.0.jar and apm-spring-webflux-5.x-plugin-8.6.0.jar to the agent plugins directory. I want to print skywalking traceId in the log (logback).
The pom of apm-toolkit-logback-1.x has been added to the project. But I can't get the traceid. Is there any way to get traceid?
Thank you so muck!

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We never says, we provide this in Gateway always. If you want to learn why, you need to know how trace context propagates.

**Comment by BothSavage** [comment]
https://bothsavage.github.io/article/240121-skywaking
