### ISSUE TITLE
[PYTHON] plugin thrift support

### ISSUE THREAD

**Issue by xuanyu66** [apache/skywalking#7196]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
We want to know, Do we have a plan to support thrift plugin on python?
Have someone tried to do it?

**Comment by kezhenxu94** [comment]
> Please answer these questions before submitting your issue.
> 
> * Why do you submit this issue?
> * [ ]  Question or discussion
> * [ ]  Bug
> * [ ]  Requirement
> * [x]  Feature or performance improvement
> 
> ### Requirement or improvement
> * Please describe your requirements or improvement suggestions.
>   We want to know, Do we have a plan to support thrift plugin on python?
>   Have someone tried to do it?

AFAIK, no one is working on this, welcome to contribute
