### ISSUE TITLE
Web UI（OAP Server） queries are slow in the case of large amounts of data

### ISSUE THREAD

**Issue by xjt2016** [apache/skywalking#7197]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
1. When do you support storage above influxdb2.0？
2. Why does elasticsearch7 storage indexes in days instead of hours (`dayStep`)? At present, we are slow in the web query interface, is it possible to optimize?
```yaml
dayStep: ${SW_STORAGE_DAY_STEP:1} # Represent the number of days in the one minute/hour/day index.
```

**Comment by wu-sheng** [comment]
1. No one is working on that. Community dependa on the contributers.
2. ElasticSearch could work perfectly for PB level data. Set your ES shards to increase performance.
