### ISSUE TITLE
[Java] dubbo 3.0 plugin support

### ISSUE THREAD

**Issue by naah69** [apache/skywalking#7203]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x ] Requirement

___
### Question
- java agent support dubbo 3.0

**Comment by wu-sheng** [comment]
Are you going to contribute this plugin?

**Comment by naah69** [comment]
sry,may not

**Comment by wu-sheng** [comment]
OK, then I am going to keep this issue open. Anyone wants to do, welcome to self-assign this.

**Comment by hermeshephaestus** [comment]
@wu-sheng i want to to contribute this plugin!

**Comment by kezhenxu94** [comment]
@hermeshephaestus assigned, thanks and good luck!

**Comment by hermeshephaestus** [comment]
@kezhenxu94  @wu-sheng Does skywalking have a WeChat group？ I want to join in!

**Comment by wu-sheng** [comment]
> @kezhenxu94  @wu-sheng Does skywalking have a WeChat group？ I want to join in!

No, we don't have that.

**Comment by wu-sheng** [comment]
@hermeshephaestus Do you have anything to update? I see this has passed 10 days.

**Comment by hermeshephaestus** [comment]
I'm still working on this task. I still need some time. @wu-sheng

**Comment by pangshuqiang** [comment]
期待Dubbo3.0插件，
或许下面这个地址的问题有点帮助
https://github.com/apache/dubbo/issues/8365

**Comment by wu-sheng** [comment]
@pangshuqiang Please keep all comments in English on SkyWalking GitHub.

**Comment by hailin0** [comment]
I am interested in it

**Comment by wu-sheng** [comment]
@hailin0 Please go ahead. There is no progress yet.

**Comment by hailin0** [comment]
> @hailin0 Please go ahead. There is no progress yet.
👌

**Comment by ronanzhan** [comment]
> > @hailin0 Please go ahead. There is no progress yet.
> > 👌
Hi hailin0, any progress?

**Comment by tedli** [comment]
Hi all,
Please have a look.
https://github.com/apache/skywalking-java/pull/73
