### ISSUE TITLE
VNode error

### ISSUE THREAD

**Issue by 844067874** [apache/skywalking#7207]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
![image](https://user-images.githubusercontent.com/11434590/123908492-2c8c6c00-d9aa-11eb-9764-e8332058530b.png)
what does it means?sometimes it happend. 
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Read FAQ.
