### ISSUE TITLE
Error topic in kafka fetcher

### ISSUE THREAD

**Issue by Linda-pan** [apache/skywalking#7208]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
  Bug
___
### Bug
- Which version of SkyWalking, OS, and JRE?
Skywalking‘s version is 8.4.0, And and I've seen this issue in the Master branch as well

- What happened?
The official document says this: 
skywalking-segments, skywalking-metrics, skywalking-profile, skywalking-managements, skywalking-meters, Skywalking logs and skywalking logs-json topics are required by Kafka-fetcher.
I found this passage in the https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-fetcher/#kafka-fetcher, **but in fact the topic is not "skywalking-profile", it is "skywalking-profilings".**

By the way, we use Kafka fetcher because GRPC has the problem of dropping header sleuth trace nodes in the scenario of large quantities of long trace chain,

**Comment by wu-sheng** [comment]
> The official document says this:
skywalking-segments, skywalking-metrics, skywalking-profile, skywalking-managements, skywalking-meters, Skywalking logs and skywalking logs-json topics are required by Kafka-fetcher.
I found this passage in the https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-fetcher/#kafka-fetcher, but in fact the topic is not "skywalking-profile", it is "skywalking-profiling".

You could submit a pull request to fix this document issue directly. Master branch hosts dev doc and next release doc. We have web-docs/xxx for specific versions. Welcome to submit multiple pull requests for different docs.

> By the way, we use Kafka fetcher because GRPC has the problem of dropping header sleuth trace nodes in the scenario of large quantities of long trace chain,

I can't understand what your meaning. Sorry.
