### ISSUE TITLE
Does skywalking have plans to support quarkus

### ISSUE THREAD

**Issue by hqq718685** [apache/skywalking#7213]
Does skywalking have plans to support quarkus？

We urgently hope skywalking support quarkus

Thanks

**Comment by wu-sheng** [comment]
That is not our call, sorry. quarkus is static compiling. They don't provide -javaagent, then what we can do?
This is the consistent bad side when you use static compiling language. Check c++ and golang agents, they all need manual instrumentation.

**Comment by wu-sheng** [comment]
That is not our call, sorry. quarkus is static compiling. They don't provide -javaagent, then what we can do?
This is the consistent bad side when you use static compiling language. Check c++ and golang agents, they all need manual instrumentation.
