### ISSUE TITLE
 Wrong gpr lib version or lib not found

### ISSUE THREAD

**Issue by Alrodemoa** [apache/skywalking#7216]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [+ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I trying to build Skywalking agent for PHP, but i have instantly this error:
 Wrong gpr lib version or lib not found 
I rebuilt cmake and grpc for 3 time but it make no difference.

___
### Bug
- Which version of SkyWalking, OS, and JRE?
Skywalking 4.1.2 agent for PHP
My OSs Centos 7.9 and Oracle Linux 7.9
gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11) from devtoolset-10
cmake 3.20.0-rc1 built from sources i try with 3.6 but same error
grpc for c++ 1.37.0 stable built from sources, i try with 1.38 - but same error

- Which company or project?
 PHP project

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
i try to install Skywalking via pear:
pecl install skywalking
![изображение](https://user-images.githubusercontent.com/40126319/124004026-4779d300-d9e0-11eb-90e7-d51e0d454648.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The question about php agent should not be submitted here. Their repo has its own issue tracker.
