### ISSUE TITLE
Upgrade from 8.2.0 to 8.6.0 cause to TID:Ignored_Trace

### ISSUE THREAD

**Issue by ecyuan** [apache/skywalking#7218]
When upgrade skywalking-server from 8.2.0 to 8.6.0, and skywalking-agent still running in 8.2.0;
This cause traceId all become to  "TID:Ignored_Trace";
So upgrade can't gracefully to higher version?
Server and agent must upgrade simultaneously?

**Comment by wu-sheng** [comment]
We don't change this part logic, I think. 8.6.0 server is compatible with 8.2.0 agent. But the storage is not compatible, you have to erase the ES, especially templates.
