### ISSUE TITLE
service_sla total value is small then segments count

### ISSUE THREAD

**Issue by nileblack** [apache/skywalking#7219]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- skywalking 8.1.0

- What happened?
all service_sla `total` value, `daily`, `hourly`, `minute` `service_sal.total` is not match segments count. all the value is smaller then segments count value.

**Comment by wu-sheng** [comment]
sla is a successful rate, it doesn't relate to count directly. I am not following your question.

**Comment by nileblack** [comment]
A simple question, is the expression Right?
`service_sla.percentage = service_sla.match / service_sla.total `
`service_sla.total`  is count from segments records?

What i confused is  segments count is larger then service_sla.total.

**Comment by wu-sheng** [comment]
> service_sla.percentage = service_sla.match / service_sla.total
service_sla.total is count from segments records?

It could be from there, but in the runtime, rather than reading the segment index.

**Comment by nileblack** [comment]
> It could be from there, but in the runtime, rather than reading the segment index.
OK. It is no need to read segments index, but I think the result should equals, or maybe something is wrong during REALTIME statistics.

**Comment by wu-sheng** [comment]
> > It could be from there, but in the runtime, rather than reading the segment index.
> 
> OK. It is no need to read segments index, but I think the result should equals, or maybe something is wrong during REALTIME statistics.

It could be caused by ES performance issue, cluster coordinator doesn't work as expected, anyway, could be many reasons.
