### ISSUE TITLE
skywalking alarm How to push Chinese message

### ISSUE THREAD

**Issue by cuixu3659271** [apache/skywalking#7225]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When we configure alarm rules and use push messages of enterprise Wx, how to push Chinese messages to enterprise wechat robot
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Sorry, we didn't check this. Maybe some encode issue? We don't have specific logic, just focus on utf-8.
