### ISSUE TITLE
Locate e2e failing, InfluxDB e2e tests.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7228]
@dmsolr I can see the pattern of Influxdb e2e tests keep failing. Let's do some research about what is happening.

**Comment by kezhenxu94** [comment]
The services list has many duplicated items, that's why it failed 

![61625228055_ pic_hd](https://user-images.githubusercontent.com/15965696/124273244-58f2e480-db72-11eb-8b94-19cf8a353263.jpg)
