### ISSUE TITLE
Add some new thread metric and class metric to JVMMetric

### ISSUE THREAD

**Issue by Switch-vov** [apache/skywalking#7230]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Feature or performance improvement

___
## Requirement or improvement

Add some new thread metric and class metric to JVMMetric.

### Protocal

```protobuf
message JVMMetric {
    int64 time = 1;
    CPU cpu = 2;
    repeated Memory memory = 3;
    repeated MemoryPool memoryPool = 4;
    repeated GC gc = 5;
    Thread thread = 6;
    Class clazz = 7;
}

message Thread {
    int64 liveCount = 1;
    int64 daemonCount = 2;
    int64 peakCount = 3;
    // new metric
    int64 newStateThreadCount = 4;
    int64 runnableStateThreadCount = 5;
    int64 blockedStateThreadCount = 6;
    int64 waitingStateThreadCount = 7;
    int64 timedWaitingStateThreadCount = 8;
    int64 terminatedStateThreadCount = 9;
}

// new metric
message Class {
    int64 loadedClassCount = 1;
    int64 totalUnloadedClassCount = 2;
    int64 totalLoadedClassCount = 3;
}
```

### The result in skywalking ui
![image](https://user-images.githubusercontent.com/11993575/124437068-3e568080-dda9-11eb-808d-5e2715bdf033.png)
![image](https://user-images.githubusercontent.com/11993575/124437088-46162500-dda9-11eb-88da-43104cd1c18c.png)

**Comment by wu-sheng** [comment]
You could send pull request to data-collect-protocol repo, we could check details there.

**Comment by Switch-vov** [comment]
> You could send pull request to data-collect-protocol repo, we could check details there.

ok. I'm trying to send PR.
