### ISSUE TITLE
how  to trace the batch task

### ISSUE THREAD

**Issue by code4bread163com** [apache/skywalking#7231]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Question 

___
### Question
i have a batch task. the tasks in the batch will be executed in each new thread one by one. but now the tasks have the same tid printed in log. so how can i do to trace the each task.

**Comment by wu-sheng** [comment]
There are many ways, how to measure a trace completed, and propagate context. 
DolphinScheduler, Spring Async, Elastic Job are all batch task frameworks, and we have plugins for them.

**Comment by code4bread163com** [comment]
thx
