### ISSUE TITLE
Can't match the implementation class of the interface?

### ISSUE THREAD

**Issue by vcjmhg** [apache/skywalking#7232]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 I am implementing a zeebe plugin, but encountered the following problem：
I want to match the implementation class of the `io.zeebe.client.api.worker.JobHandler` interface, when I write the `JobHandlerInstrumentation` just like this:
```java
public class JobHandlerInstrumentation extends ClassInstanceMethodsEnhancePluginDefine {

    private static final String ENHANCE_CLASS = "io.zeebe.client.api.worker.JobHandler";
    private static final String ENHANCE_METHOD = "handle";
    private static final String INTERCEPTOR_CLASS = "org.apache.skywalking.apm.plugin.zeebe.client.JobHandlerInterceptor";

    @Override
    protected ClassMatch enhanceClass() {
        return HierarchyMatch.byHierarchyMatch(ENHANCE_CLASS);
    }

    @Override
    public ConstructorInterceptPoint[] getConstructorsInterceptPoints() {
        return new ConstructorInterceptPoint[0];
    }

    @Override
    public InstanceMethodsInterceptPoint[] getInstanceMethodsInterceptPoints() {
        return new InstanceMethodsInterceptPoint[] {
            new InstanceMethodsInterceptPoint() {
                @Override
                public ElementMatcher<MethodDescription> getMethodsMatcher() {
                    return ElementMatchers.named(ENHANCE_METHOD);
                }

                @Override
                public String getMethodsInterceptor() {
                    return INTERCEPTOR_CLASS;
                }

                @Override
                public boolean isOverrideArgs() {
                    return false;
                }
            }
        };
    }
}
```
but it can't match the class `ExampleJobHandler` and the method `handle` which has implement `io.zeebe.client.api.worker.JobHandler`.
```java
public class ExampleJobHandler implements JobHandler {
    @Override
    public void handle(final JobClient client, final ActivatedJob job) {
        // here: business logic that is executed with every job
        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<String> result = restTemplate.getForEntity("http://localhost:8080/zeebe-client-1.x-scenario/hello", String.class);
        System.out.println(result.getBody());
        System.out.println(job);
        client.newCompleteCommand(job.getKey()).send().join();
        JobWorkerCreator.setStop(true);
    }
}
```
When the agent start, I debug it and find that the matcher seems to be normal.

![image](https://user-images.githubusercontent.com/55177318/124242603-7cf0fe80-db4f-11eb-9177-2ce42fd3c2b2.png)

but the INTERCEPTOR_CLASS doesn't work.
**I want to know if there is a problem with the `JobHandlerInstrumentation ` class?**
AND
Is there any way I can distinguish the situation below:
1. The class `ExampleJobHandler` matched successfully, but the method `handle()` did not succeed.
2. The class did not match successfully

Thank you!

**Comment by wu-sheng** [comment]
If you can have the target class in `SkyWalkingAgent#Transformer#transform`, then the class matched successfully.

**Comment by vcjmhg** [comment]
ok, thank u! 😄

**Comment by vcjmhg** [comment]
@wu-sheng ,What is the reason the match has not been successful? Is it because `ExampleJobHandler ` is a local class which in `zeebe-client-scenario`?
In the process of matching between the class and its interceptor, there hasn't even been a situation where 
`typeDescription`  = "org.apache.skywalking.apm.testcase.zeebe.client.job.FirstJobHandler"?
![image](https://user-images.githubusercontent.com/55177318/124431142-963db900-dda2-11eb-9f50-e9063f14c23e.png)

**Comment by wu-sheng** [comment]
I think you missed the key notice in the plugin dev doc, `org.apache.skywalking.apm` should not be used, if you want to instrument it. This package is reserved and used by SkyWalking official classes/APIs only. We don't instrument ourselves.

**Comment by wu-sheng** [comment]
`test.apache.skywalking` is recommended instead, if I remember correctly. Please check the doc.

**Comment by vcjmhg** [comment]
ok， thank you!
