### ISSUE TITLE
is implementing custom agents  enough for supporting APM on iOS/Android?

### ISSUE THREAD

**Issue by xpacificsoda** [apache/skywalking#7233]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
 Just wondering to support APM on iOS/Android with SkyWalking, what things should be done? If I implement custom agents in iOS/Android, would it be sufficient?

**Comment by wu-sheng** [comment]
Your question is very abstract. I can't give much more. Once you follow SkyWalking in-wire and out-wire protocols, you could work. Every existing agents are written by different people due to languages and platform.
