### ISSUE TITLE
TID repetition

### ISSUE THREAD

**Issue by yangh0597** [apache/skywalking#7240]
When using Skywalking to find TID duplicates, isn't the TID unique for every request?

![image](https://user-images.githubusercontent.com/86940083/124412456-25d27000-dd81-11eb-8be4-7ec333bb21a4.png)

**Comment by wu-sheng** [comment]
If there is a plugin bug, which could cache the TID in a reusable thread forever, then you could face this. You need to check which plugin could cause this, and why the last request's context doesn't get cleared properly.

**Comment by yangh0597** [comment]
这个TID重复的问题可能是因为这里没有考虑到多线程的问题，没有清空CONTEXT，导致TID重复了
![image](https://user-images.githubusercontent.com/86940083/124902972-0ef87b80-e016-11eb-86c4-d13a0221146e.png)

**Comment by yangh0597** [comment]
The problem with TID duplication may be that there is no consideration for multi-threading, and the CONTEXT is not cleared, so the TID is repeated

![image](https://user-images.githubusercontent.com/86940083/124903085-2e8fa400-e016-11eb-87c6-ebd3989b9d65.png)

**Comment by wu-sheng** [comment]
> The problem with TID duplication may be that there is no consideration for multi-threading, and the CONTEXT is not cleared, so the TID is repeated
> 
> ![image](https://user-images.githubusercontent.com/86940083/124903085-2e8fa400-e016-11eb-87c6-ebd3989b9d65.png)

We have many plugins running in multiple threads. I think you missed the root cause about , why not `remove`, it should.

**Comment by yangh0597** [comment]
We didn't develop any plugins ourselves, we just copied all the plugins in "optional-plugins" to plugins, and we did so to use it to monitor the spring-boot-gateway. I wonder if it's a bug in Skywalking itself

**Comment by wu-sheng** [comment]
> We didn't develop any plugins ourselves, we just copied all the plugins in "optional-plugins" to plugins, and we did so to use it to monitor the spring-boot-gateway. I wonder if it's a bug in Skywalking itself

There is nothing about any plugin. Thread model could be complex, or plugin could have bug. 
Also, importantly, don't copy all optional plugins, they are optional for reasons. Use necessary ones.

**Comment by yangh0597** [comment]
thanks,I try

**Comment by yangh0597** [comment]
I found that the "context" was not emptied because the list was not empty. After a look at the contents of the list, it might be as follows: since the local environment cannot be reproduced, it can only appear in the development environment on Linux, so we are running out of ideas to deal with it. Could you give me some advice?
![image](https://user-images.githubusercontent.com/86940083/125062733-4d0ea180-e0e1-11eb-93c3-1fc5db5d2693.png)

**Comment by wu-sheng** [comment]
> I found that the "context" was not emptied because the list was not empty. After a look at the contents of the list, it might be as follows: since the local environment cannot be reproduced, it can only appear in the development environment on Linux, so we are running out of ideas to deal with it. Could you give me some advice?
> 
> ![image](https://user-images.githubusercontent.com/86940083/125062733-4d0ea180-e0e1-11eb-93c3-1fc5db5d2693.png)
> 
> 

This is out the scope of community. We can't do private and debug for you. That is open source.
If you have uncertain question, we could help.
