### ISSUE TITLE
endpoint_percentile Display data are all 0

### ISSUE THREAD

**Issue by Little-kangaroo** [apache/skywalking#7242]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When I was debugging, I found that the parameters when calling the method were like this
`query queryData($endpointId: ID!,$duration: Duration!) {
  endpointP99: getLinearIntValues(metric: {
    name: "endpoint_p99"
    id: $endpointId
  }, duration: $duration) { values { value } }
  endpointP95: getLinearIntValues(metric: {
    name: "endpoint_p95"
    id: $endpointId
  }, duration: $duration) { values { value } }
  endpointP90: getLinearIntValues(metric: {
    name: "endpoint_p90"
    id: $endpointId
  }, duration: $duration) { values { value } }
  endpointP75: getLinearIntValues(metric: {
    name: "endpoint_p75"
    id: $endpointId
  }, duration: $duration) { values { value } }
  endpointP50: getLinearIntValues(metric: {
    name: "endpoint_p50"
    id: $endpointId
  }, duration: $duration) { values { value } }}`

but when the method was executed here
![image](https://user-images.githubusercontent.com/17957051/124431790-6cd15d00-dda3-11eb-9d39-4ce3b081509c.png)
**_endpointP99_** is an UNKNOWN, so the returned data defaults to 0
Only found in the **mapping**
![image](https://user-images.githubusercontent.com/17957051/124432584-5d9edf00-dda4-11eb-8f0a-142f11dd4c15.png)

So how should I get data like endpoint_p99?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Where do you find to say we have this metric name? I am feeling strange why you query like this.

**Comment by Little-kangaroo** [comment]
From the page, it is the request sent by this panel data
<img width="1436" alt="企业微信20210705-154423@2x" src="https://user-images.githubusercontent.com/17957051/124436105-3c3ff200-dda8-11eb-9198-6c963b831082.png">

> Where do you find to say we have this metric name? I am feeling strange why you query like this.

**Comment by wu-sheng** [comment]
Go to edit mode, you could on your own. And GraphQL shows how we query, we never use the metric, which is totally by your guess.
