### ISSUE TITLE
 Is it possible to specify a network card?

### ISSUE THREAD

**Issue by conghuo** [apache/skywalking#7245]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
The java agent collects all the network card information of the instance. It seems particularly inconvenient for instances with multiple network cards. Is it possible to specify a network card?
![image](https://user-images.githubusercontent.com/22426964/124456146-f3deff00-ddbc-11eb-8e9b-bc1a3ed7a2dd.png)

![image](https://user-images.githubusercontent.com/22426964/124456250-0fe2a080-ddbd-11eb-907a-984498ce532b.png)

**Comment by wu-sheng** [comment]
I think we can't. You could set an instance name manually.
