### ISSUE TITLE
持久化到es后，造成es占用内存持续增加

### ISSUE THREAD

**Issue by ZaneGeng** [apache/skywalking#7246]
jdk11环境，docker部署es7，使用SkyWalking8.6持久化到es后，会让es的内存逐渐增大，直到100%造成OOM，请问如何解决？
![1](https://user-images.githubusercontent.com/13901003/124463598-b337b380-ddc5-11eb-84ba-7fecccc6b0cc.png)

**Comment by ZaneGeng** [comment]
持久化到mysql8，也会使mysql8占用内存持续增长到100%造成oom

**Comment by wu-sheng** [comment]
Github discussion is required to be English for global users.

**Comment by wu-sheng** [comment]
Your description is totally wrong. We push data into a storage, then database fails, try to make the database more powerful.
