### ISSUE TITLE
How to push log to SkyWalking with fluent-bit?

### ISSUE THREAD

**Issue by StayTherapy** [apache/skywalking#7250]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

For simple, I  want collect JSON log with `fluent-bit` and direct push to SkyWalking .

Follow [Log Collecting And Analysis](https://skywalking.apache.org/docs/main/latest/en/setup/backend/log-analyzer/), I setup a `fluent-bit` in docker like this:

**fluent-bit.conf**
```bash
[SERVICE]
    Flush          5
    Daemon         Off
    Log_Level      warn
    Parsers_File   fluent-bit-parser.conf
[INPUT]
    Name           tail
    Path           /logs/*.log
    Parser         my-log-format
[OUTPUT]
    Name            stdout
    Match           *
    Format          json
[OUTPUT]
    Name            http
    Match           *
    Host            oap
    Port            12800
    URI             /v3/logs
    Format          json
```

**fluent-bit-parser.conf**
```bash
[PARSER]
    Name   my-log-format
    Format json
```

The log of `fluent-bit` is fine, JSON log printed. **But** there is nothing in `log` page in SkyWalking UI ,it's always `No Data`.

Is there any configuration of `skywalking-oap-server` should be update?

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/tree/5dd56a5ca45c1bc423af71dc0829aed1221621ac/test/e2e/e2e-test/docker/log/fluent-bit Are you using this setup? We have tested in the e2e for every commit.
Your description is hard to reply.

**Comment by StayTherapy** [comment]
@wu-sheng Thanks, problem resolved.

I think the key point is : [log-data-protocol](https://skywalking.apache.org/docs/main/latest/en/protocols/log-data-protocol/#http-api)

Before push log , we can POST to http://OAP:12800/v3/logs , and check the JSON body.

**Comment by zhujinhu21** [comment]
@StayTherapy  I use https://github.com/apache/skywalking/tree/5dd56a5ca45c1bc423af71dc0829aed1221621ac/test/e2e/e2e-test/docker/log/fluent-bit confi file. but fluent-bit tell me " [ warn] [router] NO match for stdout.0 output instance"
![企业微信截图_16275468733071](https://user-images.githubusercontent.com/4327149/127457715-1ed9a275-40f9-4ff5-b6f0-108d9b7edde3.png)

**Comment by zhujinhu21** [comment]
@wu-sheng , hi can i use skywalking 8.6.0 version with fluent-bit
