### ISSUE TITLE
Skywalking8.5.0 was unable to collect log4j2 logs

### ISSUE THREAD

**Issue by wwh313** [apache/skywalking#7251]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 ERROR 2021-07-06 09:59:36:306 DataCarrier.gRPC-log.Consumer.0.Thread GRPCLogReportServiceClient : Report log failure with the gRPC client.
java.lang.NullPointerException
        at org.apache.skywalking.apm.toolkit.logging.common.log.GRPCLogReportServiceClient.consume(GRPCLogReportServiceClient.java:107)
        at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:75)
        at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:53)
___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.5.0  linux  1.8
- Which company or project?
- 普通maven

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You need to debug why NPE happens at least, there is no enough context to know what is going on.

**Comment by q82184828** [comment]
i meet the same problem, could you have solve it ?
