### ISSUE TITLE
add dameng8 JDBC plugin support (java-agent)

### ISSUE THREAD

**Issue by zhyyu** [apache/skywalking#7252]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
There are some companies use dameng8 database, but it's not in the java agent support list. So I want to contribute a java-agent plugin to support it.

**Comment by wu-sheng** [comment]
@leizhiyuan As far as I know, dameng8 is a commercial and close-source database, correct?

**Comment by zhyyu** [comment]
> @leizhiyuan As far as I know, dameng8 is a commercial and close-source database, correct?



> @leizhiyuan As far as I know, dameng8 is a commercial and close-source database, correct?

It's correct, dameng8 is a commercial and close-source. But dameng8's jdbc driver can be downloaded from it's official website [https://eco.dameng.com/docs/zh-cn/start/java-development.html](url). So we can enhance the driver including specific class.

**Comment by wu-sheng** [comment]
> > @leizhiyuan As far as I know, dameng8 is a commercial and close-source database, correct?
> 
> It's correct, dameng8 is a commercial and close-source. But dameng8's jdbc driver can be downloaded from it's official website [https://eco.dameng.com/docs/zh-cn/start/java-development.html](url). So we can enhance the driver including specific class.

Then it can't be hosted in the Apache, it is commercial, so no maven central address. They don't set up the license for their driver, so we can't determine our instrumentation codes are valid or not. Decompiling is a tricky way, you could do it, but SkyWalking and Apache Software Foundation don't want to take any risk about violating their IP, commercial license, or branding.

If you want to open the implementation of a plugin for their driver, you could open it on your own repo. We are welcome you to post a blog on https://skywalking.apache.org/zh/ to talk about how to use it.

The contribution has to be rejected. sorry. Hope you could understand the reasons we mentioned.
