### ISSUE TITLE
Apache Skywalking for serverless architecture

### ISSUE THREAD

**Issue by farhanahraf03** [apache/skywalking#7253]
Please answer these questions before submitting your issue.

___
### Questions
- 1) Can Apache Skywalking monitor serverless entities like AWS lambda and Azure Functions?
- 2) Can it be integrated with services like ECS/EKS?
___

**Comment by wu-sheng** [comment]
> 1. Can Apache Skywalking monitor serverless entities like AWS lambda and Azure Functions?

You could read this, https://github.com/apache/skywalking-nodejs#experimental-azure-functions-support

> * 1. Can it be integrated with services like ECS/EKS?

ECS and EKS have nothing special, SkyWalking doesn't care how your applications are running. The container is not sensitive for language agents.

**Comment by ssvssv** [comment]
Shall I configure  Apache Skywalking for  monitoring AWS ECS fargate?
