### ISSUE TITLE
elasticsearch-6.x-plugin will enhance elasticsearch-5.x, resulting java.lang.ClassCastException

### ISSUE THREAD

**Issue by LiWenGu** [apache/skywalking#7256]
- Why do you submit this issue?
- [x] Feature or performance improvement
___

### Requirement or improvement
- Please describe your requirements or improvement suggestions.

Skywalking: 8.2.x
OS: linux/mac
JRE: 8.x
plugin: elasticsearch-6.x-plugin

some client use elasticsearch-rest-high-level-client is 5.6.4, will cause an exception.
error log:
```log
java.lang.ClassCastException: org.elasticsearch.client.RestClient cannot be cast to org.elasticsearch.client.RestClientBuilder
at org.apache.skywalking.apm.plugin.elasticsearch.v6.interceptor.RestHighLevelClientConInterceptor.onConstruct(RestHighLevelClientConInterceptor.java:32)
```

i use uranus and add witnessClass org.elasticsearch.client.common.XContentSource in `org.apache.skywalking.apm.plugin.elasticsearch.v6.define.RestHighLevelClientInstrumentation`

**Comment by wu-sheng** [comment]
I can see the 5.4.2 is running in the tests, https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/elasticsearch-5.x-scenario/support-version.list. Nothing wrong happens. I think you should upgrade SkyWalking. This is a resolved issue.

**Comment by LiWenGu** [comment]
i use uranus:
```
./new-class -c org.elasticsearch.client:elasticsearch-rest-high-level-client:5.4.2  -n org.elasticsearch.client:elasticsearch-rest-high-level-client:5.6.4 -s
```

output:
```
org.elasticsearch.client.Request

org.elasticsearch.client.Request$Params

org.elasticsearch.client.RestHighLevelClient

org.elasticsearch.client.RestHighLevelClient$1

size:4
```

version 5.6.4 have new class: org.elasticsearch.client.RestHighLevelClient, but elasticsearch-6.x-plugin enhance this class.

**Comment by wu-sheng** [comment]
OK, we don't have a chance to verify this kind of tiny version change, if you have some witness class change proposal, send a pull request and add your 5.6.4 in the test to verify your pull request.
