### ISSUE TITLE
Mock collector startup script fails in CentOS 6.9

### ISSUE THREAD

**Issue by whl12345** [apache/skywalking#7258]
I need local  integration test by skywalking-agent-test-tool, but I can not start  skywalking-mock-collector by collector-startup.sh like the doc says.

**Comment by whl12345** [comment]
some docs in
[https://github.com/apache/skywalking-agent-test-tool](url)

**Comment by kezhenxu94** [comment]
I think the doc needs update, @whl12345 are you able to run locally? I think it's not hard to make it run

**Comment by whl12345** [comment]
> I think the doc needs update, @whl12345 are you able to run locally? I think it's not hard to make it run

The collector-startup.sh can not be executed.I run it locally after changing the collector-startup.sh.

**Comment by wu-sheng** [comment]
> > I think the doc needs update, @whl12345 are you able to run locally? I think it's not hard to make it run
> 
> The collector-startup.sh can not be executed.I run it locally after changing the collector-startup.sh.

What do you mean can't be executed? Don't `chmod`? Or something?

**Comment by whl12345** [comment]
**local shell** 
cd /data/skywalking/mock-collector/skywalking-mock-collector
bash ./bin/collector-startup.sh

**when i execute: bash ./bin/collector-startup.sh** 
  : command not foundrtup.sh: line 2: 
  : command not foundrtup.sh: line 18: 
  /..: No such file or directoryne 21: cd: ./bin
  : command not foundrtup.sh: line 22: 
  : command not foundrtup.sh: line 25: 
  '/bin/collector-startup.sh: line 28: syntax error near unexpected token `do
  '/bin/collector-startup.sh: line 28: `do

**after i execute jar manully,it works**
java -cp /data/skywalking/mock-collector/skywalking-mock-collector/libs/animal-sniffer-annotations-1.17.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/error_prone_annotations-2.3.4.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/grpc-api-1.26.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/grpc-context-1.26.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/grpc-core-1.26.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/grpc-netty-1.26.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/grpc-protobuf-1.26.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/grpc-protobuf-lite-1.26.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/grpc-stub-1.26.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/gson-2.8.6.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/guava-20.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/javax.servlet-api-3.1.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/jetty-http-9.4.2.v20170220.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/jetty-io-9.4.2.v20170220.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/jetty-security-9.4.2.v20170220.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/jetty-server-9.4.2.v20170220.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/jetty-servlet-9.4.2.v20170220.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/jetty-util-9.4.2.v20170220.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/jsr305-3.0.2.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/log4j-api-2.9.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/log4j-core-2.9.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/log4j-over-slf4j-1.7.25.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/log4j-slf4j-impl-2.9.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/mock-collector-1.0.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-buffer-4.1.42.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-codec-4.1.42.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-codec-http2-4.1.42.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-codec-http-4.1.42.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-codec-socks-4.1.42.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-common-4.1.42.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-handler-4.1.42.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-handler-proxy-4.1.42.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-resolver-4.1.42.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-tcnative-boringssl-static-2.0.26.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/netty-transport-4.1.42.Final.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/opencensus-api-0.24.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/opencensus-contrib-grpc-metrics-0.24.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/perfmark-api-0.19.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/protobuf-java-3.11.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/protobuf-java-util-3.11.4.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/proto-google-common-protos-1.12.0.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/skywalking-mock-collector.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/slf4j-api-1.7.25.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/snakeyaml-1.24.jar:/data/skywalking/mock-collector/skywalking-mock-collector/libs/validator-1.0.0.jar org.apache.skywalking.plugin.test.mockcollector.Main

**Comment by wu-sheng** [comment]
@dmsolr I think you know the details.

**Comment by dmsolr** [comment]
Hi @whl12345 
Could you share some information about your environment?
I test success on ubuntu 20-08 just now.

**Comment by whl12345** [comment]
> Hi @whl12345
> Could you share some information about your environment?
> I test success on ubuntu 20-08 just now.

CentOS release 6.9

**Comment by dmsolr** [comment]
```bash
mvn clean package -DskipTests
cd dist/
tar -zxvf skywalking-mock-collector.tar.gz
cd skywalking-mock-collector/
bash bin/collector-startup.sh
```

**Comment by whl12345** [comment]
> ```shell
> bash bin/collector-startup.sh
> ```
It seems no difference like my shell.

**Comment by wu-sheng** [comment]
It looks like a shell incompatible?

**Comment by whl12345** [comment]
It seems like that, will it just a little question.

**Comment by wu-sheng** [comment]
> It seems like that, will it just a little question.

Could you try to improve and submit a pull request?

**Comment by dmsolr** [comment]
So strange. When I am working on agent test tool, I am using centos 6.x.

**Comment by whl12345** [comment]
After I focus on this problem, It may be my fault.
Because I compile it in windows and upload it to linux, it causes the problem. When I complie it in linux ,it works well.

**Comment by whl12345** [comment]
Please close the issue.
