### ISSUE TITLE
When i start server, i received  " message: 'Error installing plugin mysql2 *',", i used skywalking-nodejs 3.0 version.

### ISSUE THREAD

**Issue by zyfyuanyuan6** [apache/skywalking#7260]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### ### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
3.0? We don't have that release.

**Comment by wu-sheng** [comment]
And you should provide demo codes to reproduce the error, otherwise, how should we or original contributor @tianyk guess?

**Comment by zyfyuanyuan6** [comment]
> 3.0? We don't have that release.

skywalking-nodejs "^0.3.0",

**Comment by zyfyuanyuan6** [comment]
const { default: agent } = require('skywalking-backend-js');

agent.start({
  serviceName: 'test-api',
  serviceInstance: 'test-instance',
  collectorAddress: '127.0.0.1:11800',
});

**Comment by wu-sheng** [comment]
> const { default: agent } = require('skywalking-backend-js');
> 
> 
> 
> agent.start({
> 
>   serviceName: 'test-api',
> 
>   serviceInstance: 'test-instance',
> 
>   collectorAddress: '127.0.0.1:11800',
> 
> });
> 
> 

I don't think these several lines help. Not every nodejs app faces this potential issue, I think. So I ask for your codebase which coule make us to see this error.

**Comment by kezhenxu94** [comment]
> const { default: agent } = require('skywalking-backend-js');
> 
> agent.start({
> serviceName: 'test-api',
> serviceInstance: 'test-instance',
> collectorAddress: '127.0.0.1:11800',
> });

Please provide valuable code snippet to help reproduce the problem, these lines of codes are running in our tests in every commit and we're not able to see the error you reported.
