### ISSUE TITLE
When i start server, i received " message: 'Error installing plugin mysql2 *',", i used skywalking-nodejs "^0.3.0",

### ISSUE THREAD

**Issue by zyfyuanyuan6** [apache/skywalking#7262]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
const { default: agent } = require('skywalking-backend-js');
agent.start({
  serviceName: 'test-api',
  serviceInstance: 'test-instance',
  collectorAddress: '127.0.0.1:11800',
});

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If you kee open new issue, I have to block you. Why are you doing this.
