### ISSUE TITLE
Can alarm message show the actual value

### ISSUE THREAD

**Issue by 807801002** [apache/skywalking#7264]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can alarm message show the actual value when alarm occured?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No, it doesn't make sense. Alarm use operation(<, >) and count to measure values with threshold, there is no place to say what is the value. They are values in the time window.
