### ISSUE TITLE
agent has NoClassDefFoundError error

### ISSUE THREAD

**Issue by CrytisMT** [apache/skywalking#7267]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I want collect logs without importing apm-application-toolkit to business project,so I imported apm-application-toolkit in   apm-toolkit-logback-1.x-activation and agent-core, I used GRPCLogClientAppender in apm-application-toolkit to active log collecting, and the GRPCLogClientAppender class exists in skywaling-agent.jar and apm-toolkit-logback-1.x-activation.jar, but the agent always has error(stack in apm-application-toolkit):
`java.lang.NoClassDefFoundError: org/apache/skywalking/apm/toolkit/log/logback/v1/x/log/GRPCLogClientAppender` 
why the agent can't load  GRPCLogClientAppender ?

Thanks!
___
### Env
- Which version of SkyWalking, OS, and JRE?
Skywalking：8.6.0
JRE：1.8
OS：centos 7.2

**Comment by wu-sheng** [comment]
Why you import activation and agent core? Please follow document, your steps are illegal.

**Comment by CrytisMT** [comment]
@wu-sheng No,i import toolkit  to agent core and activation, to  collect logs without modify business code(no intrusion).
I add GRPCLogClientAppender to logback to collect logs in activation.

**Comment by wu-sheng** [comment]
> i import toolkit to agent core and activation

Still wrong. Activation is not the lib that should be imported.

**Comment by CrytisMT** [comment]
@wu-sheng there is a misunderstanding,I import the tookit to  Activation,not import Activation 😂

**Comment by CrytisMT** [comment]
`
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>apm-toolkit-activation</artifactId>
        <groupId>org.apache.skywalking</groupId>
        <version>8.6.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>apm-toolkit-logback-1.x-activation</artifactId>

    <properties>
        <logback-classic.version>1.2.3</logback-classic.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback-classic.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logging-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
`

**Comment by wu-sheng** [comment]
```
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logging-common</artifactId>
            <version>${project.version}</version>
        </dependency>
```

Why add this?

**Comment by wu-sheng** [comment]
` <artifactId>apm-toolkit-logback-1.x-activation</artifactId>` Why refer this pom? I am totally confused.

**Comment by CrytisMT** [comment]
because i add GRPCLogClientAppender  to business code  logback to collect logs when the agent enhance logback.

**Comment by CrytisMT** [comment]
i add some Interceptors in Activation to use GRPCLogClientAppender

**Comment by wu-sheng** [comment]
How agent works is a core level thing in SkyWalking. Have nothing related to you. You need to 100% follow document and install agent. 
Don't guess, and don't change before you read codes.

**Comment by CrytisMT** [comment]
yes, i didn't chage the core code,just add Interceptors in activation plugin...

**Comment by wu-sheng** [comment]
Again, you import is not following document.
