### ISSUE TITLE
How does istio integrate skywalking

### ISSUE THREAD

**Issue by githublaohu** [apache/skywalking#7272]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [yes ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How does istio integrate skywalking, Where are the documents and source code

istio 如何集成 skywaling，请问文档与源码在哪里。istio官网上有说支持，没有找到文档与源码

istio已经不打算支持helm，是否有istioclt 部署方案，谢谢大佬了。

**Comment by wu-sheng** [comment]
We require English on Github. Read https://skywalking.apache.org/docs/main/latest/en/setup/envoy/als_setting/

The whole section is about service mesh observability. I don't know your meaning.

**Comment by githublaohu** [comment]
谢谢。

请问下， skywalking如何支持istio的。
在代码里面没有找到istio 的依赖
找到一个org.apache.skywalking.aop.server.receiver.mesh 项目。有mesh的支持
只有一个service-mesh.proto，文件作为传输。
这个service-mesh.proto是mash标准还是istio标准吗？

**Comment by wu-sheng** [comment]
You ignore all we request. Would not follow this.
