### ISSUE TITLE
[NodeJS] undefined error when Redis plugin is used in nodejs agent

### ISSUE THREAD

**Issue by DanielYWoo** [apache/skywalking#7275]
___
### Bug
- Which version of SkyWalking, OS, and JRE?
NodeJS module skywalking-backend-js 0.3.0

- What happened?
throws an error
```
TypeError: Cannot read property 'select' of undefined
  at Redis.Cls.<computed> [as sendCommand] (/home/jack/app/node_modules/skywalking-backend-js/lib/plugins/IORedisPlugin.js:53:67)

```

**Comment by kezhenxu94** [comment]
Hi @DanielYWoo , thanks for reporting this, can you check what's the difference between our tests https://github.com/apache/skywalking-nodejs/blob/163a70d4b8b863d063b7d96cacb5641730eb48b7/tests/plugins/ioredis/server.ts and your use case? Our test case passed and we need some input to see what's wrong

**Comment by wu-sheng** [comment]
No update in months.

**Comment by zhgtot** [comment]
I met this error too. It happens when you conect a redis cluster not single redis node.
In my code, I init the redis client like this
![image](https://user-images.githubusercontent.com/19788099/146736779-058e3f64-8fd0-407e-9111-169d6018272d.png)

**Comment by DanielYWoo** [comment]
I encounter this problem with Redis cluster too.
