### ISSUE TITLE
what is wrong with it?@wu-sheng

### ISSUE THREAD

**Issue by lmx1989219** [apache/skywalking#7278]
@wu-sheng   
@TinyAllen i get the same questions.
![image](https://user-images.githubusercontent.com/9464485/125154059-9cf57300-e18a-11eb-8a78-d3467799c3b1.png)

skywalking v8.3.0
es 6.8.3

[trace.txt](https://github.com/apache/skywalking/files/6794774/trace.txt)

_Originally posted by @lmx1989219 in https://github.com/apache/skywalking/issues/3276#issuecomment-877578524_

**Comment by lmx1989219** [comment]
with the same docker image,i found this problem more times in difference env.
and i also cannot see any exception in  es/oap log file.

**Comment by wu-sheng** [comment]
Don't know. And we don't have 8.0.3.

**Comment by wu-sheng** [comment]
I can't know what happens in your env. We are not facing or faced this.

**Comment by wu-sheng** [comment]
This is an incorrect way to talk with the community. I am not a custome service. Why put my name in an issue title?
In the open source community, we discuss and help each other.

**Comment by lmx1989219** [comment]
> I can't know what happens in your env. We are not facing or faced this.



> This is an incorrect way to talk with the community. I am not a custome service. Why put my name in an issue title?
> In the open source community, we discuss and help each other.

oh,i'm so sorry.
