### ISSUE TITLE
Why the same Zipkin traceId corresponds to different aerial walking traceId

### ISSUE THREAD

**Issue by Linda-pan** [apache/skywalking#7283]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Question or discussion
___
### Question
- What do you want to know?
I found that the same Zipkin traceId corresponds to different skywalking traceId, which causes my call chain to have multiple branches instead of the complete call chain in Zipkin, and I want to know the possible cause of this situation

![image](https://user-images.githubusercontent.com/18511489/125225795-6d697680-e302-11eb-90af-f5e4fdc3af23.png)

**Comment by wu-sheng** [comment]
We don't support Zipkin community. This is not our responsibility. Sorry.

If a trace breaks somehow, you should check from which points. They may be caused by unsupported cases, and no plugin is for that.
