### ISSUE TITLE
[Client JS] provide time interval configuration for segments report.

### ISSUE THREAD

**Issue by JaredTan95** [apache/skywalking#7284]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
for segments report, we may need a report time interval configuration to avoid data loss.

**Comment by wu-sheng** [comment]
The client js has already added the browser hook to avoid segment lost. What is this period for?

**Comment by JaredTan95** [comment]
> The client js has already added the browser hook to avoid segment lost. What is this period for?

As @Fine0830 said, client js will report every 5 minutes or browser closed. but, in this scenario, UI often occurs tracing broken due to the front-end not reporting in time.

**Comment by JaredTan95** [comment]
> The client js has already added the browser hook to avoid segment lost. What is this period for?

As @Fine0830 said, client js will report every 5 minutes or browser closed. but, in this scenario, UI often occurs tracing broken due to the front-end not reporting in time.

**Comment by JaredTan95** [comment]
So, we hope we can config time interval to make client report as soon as possible.

**Comment by wu-sheng** [comment]
> > The client js has already added the browser hook to avoid segment lost. What is this period for?
> 
> As @Fine0830 said, client js will report every 5 minutes or browser closed. but, in this scenario, UI often occurs tracing broken due to the front-end not reporting in time.

OK, it is fine to set. I just want us to have a reasonable default report period.

**Comment by Fine0830** [comment]
> > > The client js has already added the browser hook to avoid segment lost. What is this period for?
> > 
> > 
> > As @Fine0830 said, client js will report every 5 minutes or browser closed. but, in this scenario, UI often occurs tracing broken due to the front-end not reporting in time.
> 
> OK, it is fine to set. I just want us to have a reasonable default report period.

I don't understand what is a reasonable default report period for different scenarios?

**Comment by wu-sheng** [comment]
> I don't understand what is a reasonable default report period for different scenarios?

I don't know what is the better value, just asking.

**Comment by Fine0830** [comment]
Close this via https://github.com/apache/skywalking-client-js/pull/65
