### ISSUE TITLE
Skywalking oap cluster

### ISSUE THREAD

**Issue by wwh-coder** [apache/skywalking#7285]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When building a skywalking OAP cluster, how to configure the routing when using the gateway, how to sense OAP expansion between UI and agent, and whether to directly configure the gateway address? Can you provide a configuration example？
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We expect you could find the target pods by service name in k8s directly. We don't expose anything.
