### ISSUE TITLE
Production parameter configuration

### ISSUE THREAD

**Issue by renhaizhou** [apache/skywalking#7288]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

In the case of extremely high concurrency in the production environment, if es is used for storage, how to configure the sampling rate in the production environment? Does OAP need cluster deployment？

**Comment by wu-sheng** [comment]
OAP should run in cluster mode for sure. We provide document for that already.

**Comment by wu-sheng** [comment]
Sampling provided, whether needed is your call.
