### ISSUE TITLE
how many machines does OAP need at least  If Nacos is selected for cluster mode

### ISSUE THREAD

**Issue by renhaizhou** [apache/skywalking#7289]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

If Nacos is selected for cluster mode, how many machines does OAP need at least

**Comment by wu-sheng** [comment]
I don't know your point. These 2 things seem unrelated.
