### ISSUE TITLE
[ issues ] Can multiple addresses be configured

### ISSUE THREAD

**Issue by githublaohu** [apache/skywalking#7292]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can multiple addresses be configured。
可以在 meshConfig.defaultConfig.envoyMetricsService.address 配置多个地址吗？ 
请问如何配置。
如果配置多个，是每个服务发一条。还是一保证一次了？

抱歉，在istio里面没有找到源码。
有点忙，麻烦。大佬了。

`
istioctl install -y \
  --set profile=demo `# replace the profile as per your need` \
  --set meshConfig.defaultConfig.envoyMetricsService.address=<skywalking.address.port.11800> 

`

**Comment by wu-sheng** [comment]
Envoy's configuration is not SkyWalking's responsibility. Please submit to the right community.
