### ISSUE TITLE
[Client JS] segments is only send once

### ISSUE THREAD

**Issue by Lighfer** [apache/skywalking#7303]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?

skywalking-client-js 0.6.0

- What happened?

`SEGMENTS report` only send once, because `segment.ts` reassign an empty array to `segments`, which cause `xhrInterceptor` and `windowFetch`  always adds segment to old array.

```javascript
export default function traceSegment(options: CustomOptionsType) {
  let segments = [] as SegmentFields[];
  // inject interceptor
  xhrInterceptor(options, segments);
  windowFetch(options, segments);

  // ...

  setInterval(() => {
    if (!segments.length) {
      return;
    }
    new Report('SEGMENTS', options.collector).sendByXhr(segments);
    segments = []; // should clear the segments, not assign [] to it
  }, options.traceTimeInterval);
}

```

**Comment by wu-sheng** [comment]
Do you mean a bug? Would you send a pull request?
