### ISSUE TITLE
Does SkyWalking have a tool/library which converts SkyWalking tracing data into OpenTelemetry format?

### ISSUE THREAD

**Issue by yaojingguo** [apache/skywalking#7305]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Does SkyWalking have a tool/library which can converts data in [Tracing.proto](https://github.com/apache/skywalking-data-collect-protocol/blob/master/language-agent/Tracing.proto) format to OpenTelemetry trace format?

**Comment by wu-sheng** [comment]
No, we are not. This is not on the plan of any maintainer.
