### ISSUE TITLE
通过Java agent启动项目后，Http请求得到response的Body为null

### ISSUE THREAD

**Issue by d3ngs1q1** [apache/skywalking#7306]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ √ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
  apache-skywalking-apm-es7-8.6.0

- What happened?

SprintBoot项目，使用restTemplate调用https，get请求后，
responseEntity结果是200成功的，但是body为null

___

**Comment by wu-sheng** [comment]
We only accept English on GitHub.
