### ISSUE TITLE
[KONG] skywalking plugin metadata_buffer and get_hostname nil value

### ISSUE THREAD

**Issue by cooocy** [apache/skywalking#7308]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I installed it after reading this documents. [apache/skywalking-kong](https://github.com/apache/skywalking-kong)
I want to know how to resolve this error.
Thanks.

#### My Environments
`kong` 
![image](https://user-images.githubusercontent.com/26477692/125755303-b756942a-72cb-4206-9c5d-01d152305954.png)

`skywalking`
![image](https://user-images.githubusercontent.com/26477692/125755384-7230a5f3-9511-4998-8a16-eb96cd03ee79.png)

`sw-config`
```json
{
  "created_at": 1626337670,
  "config": {
    "service_name": "kong",
    "service_instance_name": "kong-with-skywalking",
    "sample_ratio": 100,
    "backend_http_uri": "http://xxxxxx:11800",
    "include_host_in_entry_span": false
  },
  "id": "6c3e91c4-f1ab-49db-bfa8-48d10e86685c",
  "service": null,
  "enabled": true,
  "protocols": [
    "grpc",
    "grpcs",
    "http",
    "https"
  ],
  "name": "skywalking",
  "consumer": null,
  "route": null,
  "tags": null
}
```

#### Erorr log
```
targets HTTP/1.1" 200 211 "-" "lua-resty-http/0.16.1 (Lua) ngx_lua/10015"
2021/07/15 08:06:04 [error] 23#0: *14746 lua coroutine: runtime error: ...custom/share/lua/5.1/kong/plugins/skywalking/handler.lua:46: attempt to index local 'metadata_buffer'(a nil value)
stack traceback:
coroutine 0:
        ...custom/share/lua/5.1/kong/plugins/skywalking/handler.lua: in function <...custom/share/lua/5.1/kong/plugins/skywalking/handler.lua:35>
coroutine 1:
        [C]: in function 'resume'
        coroutine.wrap:21: in function <coroutine.wrap:21>
        /usr/local/share/lua/5.1/kong/init.lua:687: in function 'access'
        access_by_lua(nginx-kong.conf:87):2: in main chunk, client: 100.109.135.216, server: kong, request: "GET /gatewayv2/tensorbay-open-api/v1/datasets?offset=0&limit=128&name=test_draft HTTP/1.1", host: "gas.dev.graviti.cn"
2021/07/15 08:06:04 [error] 23#0: *14746 [kong] init.lua:689 [skywalking] ...custom/share/lua/5.1/kong/plugins/skywalking/handler.lua:46: attempt to index local 'metadata_buffer' (a nil value), client: 100.109.135.216, server: kong, request: "GET /gatewayv2/tensorbay-open-api/v1/datasets?offset=0&limit=128&name=test_draft HTTP/1.1", host: "gas.dev.graviti.cn"
2021/07/15 08:06:04 [error] 23#0: *14746 failed to run body_filter_by_lua*: ...custom/share/lua/5.1/kong/plugins/skywalking/handler.lua:75: attempt to call field 'get_hostname' (a nil value)
stack traceback:
        ...custom/share/lua/5.1/kong/plugins/skywalking/handler.lua:75: in function <...custom/share/lua/5.1/kong/plugins/skywalking/handler.lua:72>
        /usr/local/share/lua/5.1/kong/init.lua:195: in function 'execute_plugins_iterator'
        /usr/local/share/lua/5.1/kong/init.lua:957: in function 'body_filter'
        body_filter_by_lua:2: in main chunk, client: 100.109.135.216, server: kong, request: "GET /gatewayv2/tensorbay-open-api/v1/datasets?offset=0&limit=128&name=test_draft HTTP/1.1", host: "gas.dev.graviti.cn"
100.109.135.216 - - [15/Jul/2021:08:06:04 +0000] "GET /gatewayv2/tensorbay-open-api/v1/datasets?offset=0&limit=128&name=test_draft HTTP/1.1" 500 0 "-" "python-requests/2.25.1"
```

___
### Bug
- Which version of SkyWalking, OS, and JRE?
kong-skywalking 0.1.1-0

- Which company or project?

- What happened?
Call kong admin api to save plugin configurations and then restart kong. 
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by dmsolr** [comment]
@cooocy @wu-sheng 
there is a compatible issue.

**Comment by wu-sheng** [comment]
> @cooocy @wu-sheng
> there is a compatible issue.

Is this a Kong plugin level issue only?

**Comment by dmsolr** [comment]
> Is this a Kong plugin level issue only?

Yes

**Comment by wu-sheng** [comment]
@dmsolr Please fix this when you have time, then we could consider a patch(0.2.0) release.

**Comment by xzclinux** [comment]
I installed kong with helm, version 2.8.1, and still have this problem
error-log:
2022/05/15 14:03:15 [error] 1110#0: *16858 [kong] init.lua:297 [skywalking] /opt/kong/plugins/skywalking/handler.lua:46: attempt to index local 'metadata_buffer' (a nil value), client: 172.20.0.1, server: kong, request: "POST /async/task HTTP/1.1", host: "xxx"
2022/05/15 14:03:15 [error] 1110#0: *16858 failed to run body_filter_by_lua*: /home/kong/.luarocks/share/lua/5.1/skywalking/span.lua:223: attempt to index local 'span' (a nil value)
stack traceback:
	/home/kong/.luarocks/share/lua/5.1/skywalking/span.lua:223: in function 'tag'
	/opt/kong/plugins/skywalking/handler.lua:75: in function </opt/kong/plugins/skywalking/handler.lua:72>
	/usr/local/share/lua/5.1/kong/init.lua:326: in function 'execute_collected_plugins_iterator'
	/usr/local/share/lua/5.1/kong/init.lua:1270: in function 'body_filter'
	body_filter_by_lua:2: in main chunk, client: 172.20.0.1, server: kong, request: "POST /async/task HTTP/1.1", host: xxx"
kong-version:
![image](https://user-images.githubusercontent.com/75306994/168477491-6b37566c-11ae-4976-9f27-47e5204b1434.png)
