### ISSUE TITLE
[License-Eye] resolve maven dependencies' licenses

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7311]
License eye now can resolve dependencies licenses in `go.mod`, we want to resolve dependencies from `pom.xml` too.

Let's discuss and track the progress in this issue.

**Comment by MoGuGuai-hzr** [comment]
I am glad to do this. Actually, research of maven has been going on for some time and one simple example would be submitted soon.

**Comment by kezhenxu94** [comment]
> I am glad to do this. Actually, research of maven has been going on for some time and one simple example would be submitted soon.

Thanks for the update. Assigned.

**Comment by wu-sheng** [comment]
Notice maven bom and deployment management.

**Comment by kezhenxu94** [comment]
Fixed by a couple of PRs, although need some enhancements on the license identifications, which is a continuous work

https://github.com/apache/skywalking-eyes/pull/50
https://github.com/apache/skywalking-eyes/pull/53
