### ISSUE TITLE
[License-Eye] resolve npm dependencies' licenses

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7312]
License eye now can resolve dependencies licenses in `go.mod`, we want to resolve dependencies from npm `package.json` too.

Let's discuss and track the progress in this issue.

**Comment by zooltd** [comment]
I'm glad to work on this.

**Comment by kezhenxu94** [comment]
> I will be glad to work on this.

Thanks. Assigned.

**Comment by kezhenxu94** [comment]
Resolved by https://github.com/apache/skywalking-eyes/pull/48 and https://github.com/apache/skywalking-eyes/pull/51
