### ISSUE TITLE
[INFRA] Does skywalking-eyes support resolve license dependencies from pom.xml

### ISSUE THREAD

**Issue by ruanwenjun** [apache/skywalking#7314]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When I browsed the [skywalking-eyes](https://github.com/apache/skywalking-eyes) code, I found that the interface `Resolve` only have `GoModResolver` one kind of implementation. 
Does this mean that skywalking-eyes can currently only resolve dependencies from the .mod file and not support resolve from pom.xml.
___

**Comment by wu-sheng** [comment]
Duplicate with #7311
