### ISSUE TITLE
Is it a bug in spring-kafka-1.x-plugin's ProcessSeeksMethodInterceptor?

### ISSUE THREAD

**Issue by honganan** [apache/skywalking#7317]
@lujiajing1126 
In `ProcessSeeksMethodInterceptor` of spring-kafka-1.x-plugin, I see it calls `InterceptorMethod.afterMethod()` in `beforeMethod()` and `InterceptorMethod.beforeMethod()` in `afterMethod()`. I haven't run the test but it seems obviously not correct.
```java
public class ProcessSeeksMethodInterceptor implements InstanceMethodsAroundInterceptor {

    private static final String OPERATION_NAME = "/spring-kafka" + Constants.KAFKA_POLL_AND_INVOKE_OPERATION_NAME;

    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
                             MethodInterceptResult result) throws Throwable {
        InterceptorMethod.afterMethod(null);
    }

    @Override
    public Object afterMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
                              Object ret) throws Throwable {
        InterceptorMethod.beforeMethod(OPERATION_NAME);
        return ret;
    }

    @Override
    public void handleMethodException(EnhancedInstance objInst, Method method, Object[] allArguments,
                                      Class<?>[] argumentsTypes, Throwable t) {
        InterceptorMethod.handleMethodException(t);
    }
}
```

**Comment by wu-sheng** [comment]
I think we can't know. Maybe it is better to read the codes whether it is a naming issue or bug.

**Comment by lujiajing1126** [comment]
Pls check very carefully the enhanced method on which this interceptor is imposed and the logic of the spring-kafka 1.x.

We also have an e2e test targeting at this plugin, as you can find here  https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/spring-kafka-1.3.x-scenario

**Comment by wu-sheng** [comment]
> Pls check very carefully the enhanced method on which this interceptor is imposed and the logic of the spring-kafka 1.x.
> 
> 
> 
> We also have an e2e test targeting at this plugin, as you can find here  https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/spring-kafka-1.3.x-scenario
> 
> 

It is more about naming confusion. I think. I know we have plugin test.

**Comment by lujiajing1126** [comment]
> > Pls check very carefully the enhanced method on which this interceptor is imposed and the logic of the spring-kafka 1.x.
> > We also have an e2e test targeting at this plugin, as you can find here  https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/spring-kafka-1.3.x-scenario
> 
> It is more about naming confusion. I think. I know we have plugin test.

Yes. I guess so.

Probably we can change the `beforeMethod`, `afterMethod` to `start(end)PollIteration` or something similar?

**Comment by wu-sheng** [comment]
> Probably we can change the `beforeMethod`, `afterMethod` to `start(end)PollIteration` or something similar?

It seems so.
