### ISSUE TITLE
What kind of trace can be counted to cpm

### ISSUE THREAD

**Issue by 807801002** [apache/skywalking#7321]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I have some traces from webflux or springmvc,but the cpm shows 0 when there are springmvc and webflux traces.
![image](https://user-images.githubusercontent.com/8719537/126040979-eb04fec1-cffb-48ad-bb92-ebbb901ca0e7.png)
![image](https://user-images.githubusercontent.com/8719537/126040994-15f9cab6-f294-4ea6-bfc9-321ce8cd1ca9.png)

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Entry span means traffic incoming. You should know CPM is calls per minute. You at least need a call in one minute, 60 calls in one hour, and 24 * 60 calls one day. Notice the
