### ISSUE TITLE
Evaluate `new object` V.S. object pool for metric objects.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7322]
The metric objects, such as PercentileMetrics and PercentileFunction are heavy for creating and GC. Because of the DataTable fields, and the number of creations and destruction.

I have seen @kezhenxu94 reported GC cost is high. Notice, this doesn't mean GC stop time is long(the stop time should be less than 1s per minute), but from the profiling results, the GC process costs too much.

![image](https://user-images.githubusercontent.com/5441976/126058487-0d03546a-45f0-4137-a855-5ab1a7ce2a46.png)

**39% of 8U has been detected in GC.**

@kezhenxu94 Let's do another round recheck for the latest codes if this result is consistent. We should begin to evaluate the object pool. From my experiences, reducing the `new object` should help this obviously.

FYI @Ax1an I think you are interested in this topic. cc @wankai123 @hanahmily @mrproliu @dmsolr

**Comment by wu-sheng** [comment]
Another feedback from @Ax1an 

- July 14th. Codes without session enhancement and L1 optimization

![image](https://user-images.githubusercontent.com/5441976/126060442-8acbe46c-4e3e-40a1-ba30-8946875262f6.png)

- Yesterday(Junly 17th)

Receiver
![image](https://user-images.githubusercontent.com/5441976/126060637-9824d990-f3c3-460c-8875-74f01b3c39f5.png)

Aggregator
![image](https://user-images.githubusercontent.com/5441976/126060642-1897e6dc-696c-417b-9463-aee6e9332ea5.png)

___
Both of these are not including the asynchronous mode for the metrics.

**Comment by wu-sheng** [comment]
![image](https://user-images.githubusercontent.com/5441976/126060789-57f3a394-6e2e-40c5-ad25-7c1aba2030ee.png)

This is the point L1 aggregation optimization deployed online.

**Comment by wu-sheng** [comment]
![image](https://user-images.githubusercontent.com/5441976/126061406-01ade0ee-416a-4572-83c9-a9231422cc6c.png)
![image](https://user-images.githubusercontent.com/5441976/126061407-c6321b32-efcd-4110-b761-4fb6a20fea7b.png)

We can see from @Ax1an prod env(without asynchronous mode for the metrics), the trends of `heap memory` and `Eden/old Gen` are both fluctuated, which is a piece of evidence we at least should try to do object pooling, and run a comparison.

@kezhenxu94 Let's keep this as a TODO in the next weeks' perf/scale testing.

**Comment by lujiajing1126** [comment]
Very interesting work. I am also trying to introduce pooling in Skywalking-BanyanDB these days.

I would follow the discussion in this thread.

**Comment by kezhenxu94** [comment]
Pooling objects (`Source` and `Metrics`) doesn't help a lot in benchmark results.
