### ISSUE TITLE
the code logic of getting kafka topic at oap and agent side is not consistent

### ISSUE THREAD

**Issue by Cool-Coding** [apache/skywalking#7324]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
Skywalking8.6.0 mac jdk1.8.0_191

- What happened?
the code logic of getting kafka topic at oap and agent side is not consistent. Let's see.

- OAP side

```java
// the AbstractKafkaHandler class
 public String getTopic() {
       StringBuilder sb = new StringBuilder();
       if (StringUtils.isNotBlank(config.getMm2SourceAlias())) {
           sb.append(config.getMm2SourceAlias()).append(config.getMm2SourceSeparator());
       }

       if (StringUtil.isNotBlank(config.getNamespace())) {
           sb.append(config.getNamespace()).append("-");
       }
       sb.append(getPlainTopic());
       return sb.toString();
   }
```
- Agent side

```java
//  the KafkaProducerManager
  String formatTopicNameThenRegister(String topic) {
        String topicName = StringUtil.isBlank(KafkaReporterPluginConfig.Plugin.Kafka.NAMESPACE) ? topic
                : KafkaReporterPluginConfig.Plugin.Kafka.NAMESPACE + "-" + topic;
        topics.add(topicName);
        return topicName;
    }
```
___
### Requirement or improvement
We can see the getting logic among oap and agent isn't consistent; Getting topics in oap depend on "mm2SourceAlias" and "mm2SourceSeparator" besides of namespace and origin topic; but only namespace and origin topic in agent; the two fields "mm2SourceAlias" and "mm2SourceSeparator" don't have other usage;

#### First change the logic of getting kafka at oap side

```java
 // the AbstractKafkaHandler class
  public String getTopic() {
        StringBuilder sb = new StringBuilder();
       
        if (StringUtil.isNotBlank(config.getNamespace())) {
            sb.append(config.getNamespace()).append("-");
        }
        sb.append(getPlainTopic());
        return sb.toString();
    }
```

**Comment by wu-sheng** [comment]
There 2 configurations were added through https://github.com/apache/skywalking/pull/5949. The PMC team doesn't use or test it directly. @osiriswd was the code contributor.

**Comment by wu-sheng** [comment]
This seems caused by a Kafka mirror system.

**Comment by wu-sheng** [comment]
The doc has included this
> When use Kafka MirrorMaker 2.0 to replicate topics between Kafka clusters, you can set the source Kafka Cluster alias(mm2SourceAlias) and separator(mm2SourceSeparator) according to your Kafka MirrorMaker [config](https://github.com/apache/kafka/tree/trunk/connect/mirror#remote-topics).

**Comment by wu-sheng** [comment]
This was reported through #7316

**Comment by Cool-Coding** [comment]
> There 2 configurations were added through #5949. The PMC team doesn't use or test it directly. @osiriswd was the code contributor.

@wu-sheng Is the function of replicating  topicsKafka in  MirrorMaker 2.0 still using in product environment? Can I change the code logic of getting kafka topic at oap side and remove the two fields?

**Comment by wu-sheng** [comment]
> Is the function of replicating topicsKafka in MirrorMaker 2.0 still using in product environment? 

Is this contributed by contributors. I don't know how the community uses it. This would have a side effect. We could accept a feature only part of users need this, but has no harm.

> Can I change the code logic of getting kafka topic at oap side and remove the two fields?

What do you mean? I am confused.

**Comment by Cool-Coding** [comment]
> > Is the function of replicating topicsKafka in MirrorMaker 2.0 still using in product environment?
> 
> Is this contributed by contributors. I don't know how the community uses it. This would have a side effect. We could accept a feature only part of users need this, but has no harm.
> 
> > Can I change the code logic of getting kafka topic at oap side and remove the two fields?
> 
> What do you mean? I am confused.

@wu-sheng ok, I see. the two fields only used in the logic of getting topic name at oap side.

**Comment by wu-sheng** [comment]
> > > Is the function of replicating topicsKafka in MirrorMaker 2.0 still using in product environment?
> > 
> > 
> > Is this contributed by contributors. I don't know how the community uses it. This would have a side effect. We could accept a feature only part of users need this, but has no harm.
> > > Can I change the code logic of getting kafka topic at oap side and remove the two fields?
> > 
> > 
> > What do you mean? I am confused.
> 
> @wu-sheng ok, I see. the two fields only used in the logic of getting topic name at oap side.

These 2 are only used when you need MirrorMaker, nothing more.
