### ISSUE TITLE
support smi

### ISSUE THREAD

**Issue by q82184828** [apache/skywalking#7327]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ √] Feature or performance improvement

___
### Question
- i want to know, Will Skywalking support SMI(service mesh interface), cause it is a standard interface for service meshes on Kubernetes，Will it be easy to integrate when it becomes famous?

___
### Bug
- None

___
### Requirement or improvement
- None

**Comment by wu-sheng** [comment]
I don't know what do you mean about supporting SMI. It is an interface for the control/data pannel. We are just observing the implementation.

What is your understanding of SkyWalking service mesh solution?

**Comment by q82184828** [comment]
SMI is an adapter like database adapter，or just a specification like java specification？if just a specification，as you say，observing the implementation. ,I don't know much about SMI，Thank you for your advice。

**Comment by q82184828** [comment]
SMI is an adapter like database adapter，or just a specification like java specification？if just a specification，as you say，observing the implementation. 
I don't know much about SMI，Thank you for your advice。

**Comment by wu-sheng** [comment]
This is out of SkyWalking's scope.
