### ISSUE TITLE
[Nodejs] how could I achieve traceId through nodeJS API

### ISSUE THREAD

**Issue by Young200808** [apache/skywalking#7328]
I would like to achieve traceId through nodeJS API,  just like java api "TraceContext.traceId()"，but I could not found this usage from below nodeJS doc

https://github.com/apache/skywalking-nodejs

could any one help on this?

**Comment by wu-sheng** [comment]
I think the nodejs is running in the whole auto instrumentation way. There is no API for manual usage today.
