### ISSUE TITLE
ElasticSearch config  need  template order

### ISSUE THREAD

**Issue by pkxiuluo** [apache/skywalking#7331]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
 Some ElasticSearch cluster has base template as default, and skywalking also has its own template 。when  index creating match multi template,they will be merged into one with specific order 。

So we ​need  a config to set order to make  template merging correctly。

refer to  [ES Doc multiple-templates-v1](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates-v1.html#multiple-templates-v1)

this requirement is simple，if you agree with me , i can finish this work  by myself.

**Comment by wu-sheng** [comment]
My question would be, what kinds od template are you planning to apply?

**Comment by pkxiuluo** [comment]
> My question would be, what kinds od template are you planning to apply?

In current code, all index template creating without order , elasticsearch will give order 0 as default。

To keep code simple and safe ,it is reasonable offering a global config  , like other settings and mapping config in StorageModuleElasticsearchConfig .

So ,I suggest  it should apply to all index template 。

**Comment by wu-sheng** [comment]
I get this. My question is majorly about what issue are you facing? How do you notice this confliction.

**Comment by wu-sheng** [comment]
We have skywalking literal string in names, and provided namespace to avoid confliction. It is important for us to know, what this new parameter is for?

**Comment by pkxiuluo** [comment]
My skywalking share a same es cluster with other business。

To standardize all index settings ,like number_of_shards、number_of_replicas ,ES ops set a  common base template which using "*" as index_patters。

“*” means it can matching all index.

```
 GET _template/base
```

```
{
  "base" : {
    "order" : 0,
    "index_patterns" : [
      "*"
    ],
   "settings":{
     "number_of_shards"： "10",
     "number_of_replicas"： "3"
     ......
   }
   ......
}
```

the "number_of_replicas" is too many for skywalking data ,and the"number_of_shards" is too less。but some config may be fitness. 

so i want to raise the skywalking priority in template merging ，rather than  change common base template`s index_pattern to  exclude skywalking index.

**Comment by pkxiuluo** [comment]
Its also work to create a ES cluster only for skywalking, And other config is not allowed。 It is OK。
but having ability to set order is  more nice.

**Comment by wu-sheng** [comment]
According to the doc you shared, the higher-order could override the lower. Then do you mean we should add a setting item, but still keep it as `0` in default?

**Comment by pkxiuluo** [comment]
> According to the doc you shared, the higher-order could override the lower. Then do you mean we should add a setting item, but still keep it as `0` in default?

Yes, keep 0 as default。keep it compatible for the pervious。

**Comment by wu-sheng** [comment]
> > According to the doc you shared, the higher-order could override the lower. Then do you mean we should add a setting item, but still keep it as `0` in default?
> 
> Yes, keep 0 as default。keep it compatible for the pervious。

OK, I think it is fine to add this.

**Comment by wu-sheng** [comment]
You could send the pull request, and please make sure the document is well updated.

**Comment by pkxiuluo** [comment]
> You could send the pull request, and please make sure the document is well updated.

OK ,i will work on it  this weekend。

**Comment by wu-sheng** [comment]
Take your time, this is not urgent.
