### ISSUE TITLE
 Apache Skywalking is not able to collect Endpoint and Traces for Websphere

### ISSUE THREAD

**Issue by skundu1234** [apache/skywalking#7333]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
- We tried to add skywalking agent of a JVM for  WebSphere server .After that that service is visible in Apache Skywalking UI but we can not see any Endpoints and Traces after giving some load as well.

Let me know if any details are required.

**Comment by wu-sheng** [comment]
First of all, we don't have WebSphere plugin, we don't know how this works. But we have read users deployed it on the WebSphere, but use the SpringMVC plugin.

I don't know what is your case. Also, WebSphere is a commercial product, in the ASF, we don't plan to hijack that. This would lead to an IP issue.
