### ISSUE TITLE
[Client JS] traceSDKInternal may not working、fetch.ts should handle exception、exitspan's url tag may be an empty stirng

### ISSUE THREAD

**Issue by Lighfer** [apache/skywalking#7335]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
#### traceSDKInternal may not working

The `hasTrace` variable in the `fetch.ts` and `xhr.ts` may have  wrong value, for example:

```javascript
ClientMonitor.register({
  collector: 'http://IP/skywalking',
  traceSDKInternal: false
  ...
})
```

the collector's pathname is `/skywalking`, so the segments report request will send to `http://IP/skywalking/v3/segments`, and it's pathname is `/skywalking/v3/segments`,  so the result of following code will be `false`:

```javascript
([ReportTypes.ERROR, ReportTypes.ERRORS, ReportTypes.PERF, ReportTypes.SEGMENTS] as string[]).includes(
  url.pathname,
)
```

#### fetch.ts should handle exception

```javascript
// fetch.ts
const response = await origFetch(...args); // should wrap with try catch to ensure that the error log and segment  can be collected
```

___
### Requirement or improvement

When the request send failed, The exitSpan's url tag in the `fetch.ts` and `xhr.ts`  may be an empty string,  such as the cors error. So i think it can be replaced  with the request's url when the responseURL is empty.

```javascript
// xhr.ts or fetch.ts
const exitSpan: SpanFields = {
  ...
  tags: options.detailMode
    ? [
        ...
        {
          key: 'url',
          value: segCollector[i].event.responseURL // may be an empty string
          // maybe replae wih: segCollector[i].event.responseURL || `${url.protocol}//${url.host}${url.pathname}`
        },
      ]
};
```

**Comment by wu-sheng** [comment]
Would you send a pull request to fix?
