### ISSUE TITLE
[NodeJS] is eggjs supported？

### ISSUE THREAD

**Issue by jxwanglong** [apache/skywalking#7336]
I tried to use skywalking-client-js and skywalking-backend-js to track the call chain, but it didn't seem to work.
The following is the problem：
1、Failed to report from the browser
I'm not sure if this is caused by a server version issue
![image](https://user-images.githubusercontent.com/19237831/126142509-acacd525-fa3f-4c36-9128-e55e250caba9.png)
2、Start the trace from the browser, go through the eggjs service and access the java service, but there is no browser span in the call chain because eggjs uses the new traceId when accessing the java service.
following is from brower
![image](https://user-images.githubusercontent.com/19237831/126155584-27aa5d5a-a739-469b-a13a-7dbb2cffe73f.png)
following is from eggjs
![image](https://user-images.githubusercontent.com/19237831/126155692-82265ef0-debf-4948-aab6-7c29b9f5f8ed.png)

**Comment by wu-sheng** [comment]
We never said either project supports eggjs.

**Comment by wu-sheng** [comment]
The document is very clear.
