### ISSUE TITLE
prometheus meter analyzer produce IllegalArgumentException and NaN value

### ISSUE THREAD

**Issue by Lighfer** [apache/skywalking#7343]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug

https://github.com/apache/skywalking/blob/62411964a46aa22d47319ca863feed3a39169548/oap-server/analyzer/meter-analyzer/src/main/java/org/apache/skywalking/oap/meter/analyzer/prometheus/PrometheusMetricConverter.java#L87-L100

I think `Line 91` should be:
```java 
.filter(t -> t != NIL && t._2.samples.length > 0)
```
because `line 98` will throw an `IllegalArgumentException` if `samples.length == 0`.

---

https://github.com/apache/skywalking/blob/62411964a46aa22d47319ca863feed3a39169548/oap-server/analyzer/meter-analyzer/src/main/java/org/apache/skywalking/oap/meter/analyzer/dsl/SampleFamily.java#L75-L79

I think `line 78` should be:
```java
return new SampleFamily(Arrays.stream(samples).filter(sample -> !Double.isNaN(sample.getValue())).toArray(Sample[]::new), Optional.ofNullable(ctx).orElseGet(RunningContext::instance));
```
because sample's value may be 'NaN'.

**Comment by wu-sheng** [comment]
@wankai123 I think you were just asking about this? Please take a look.

**Comment by wu-sheng** [comment]
@hanahmily Could you confirm this? We faced the same issue in the latest OTEL collector too.

**Comment by wankai123** [comment]
Which plugin did you use, `prometheus-fetcher-plugin` or `otel-receiver-plugin`? 
AFAIK the otel latest version has the `NaN` issue.

**Comment by hanahmily** [comment]
I agree to filter the `NaN` value. We didn't take into account that the double values might be `NaN`.

**Comment by wankai123** [comment]
![image](https://user-images.githubusercontent.com/16773043/126306611-1574b7ad-0f76-4764-8d9c-b4e7a16bc289.png)
I got the metrics like this by using `otel-collector 0.30.0`,  the `NaN` value from otel-collector, and it seems a duplicate and wrong metric. If we don't know why they send this, I agree to filter the NaN value for defensive.

**Comment by Lighfer** [comment]
> Which plugin did you use, `prometheus-fetcher-plugin` or `otel-receiver-plugin`?
> AFAIK the `otel-collector` latest version has the `NaN` issue, the version below 0.29.0 words well.

Latest version too.

According to prometheus/client_golang#85, the NaN is reasonable

**Comment by wu-sheng** [comment]
> > Which plugin did you use, `prometheus-fetcher-plugin` or `otel-receiver-plugin`?
> > AFAIK the `otel-collector` latest version has the `NaN` issue, the version below 0.29.0 words well.
> 
> Latest version too.
> 
> According to [prometheus/client_golang#85](https://github.com/prometheus/client_golang/issues/85), the NaN is reasonable

I agree NaN is meaningful than 0 or any other way. But I think we should take care of it one way or another.

**Comment by wu-sheng** [comment]
I think we also should add a NaNSampleFamily as a subclass of `SampleFamily`, what do you think? @hanahmily @Lighfer @wankai123

**Comment by Lighfer** [comment]
> I think we also should add a NaNSampleFamily as a subclass of `SampleFamily`, what do you think? @hanahmily @Lighfer @wankai123

I think NaN value should just be handled in more details, aggregation operators or other methods in `SampleFamily` should take care of it, but I didn't understand the meaning of adding a NaNSampleFamily class, I think NaN value is meaningful when dealing with those samples where it comes from ,but meaningless when just put all NaN value  together？

**Comment by wu-sheng** [comment]
My point is about, we need to put it works in all operations. But NaN is not a number or double, we need to be very careful about how to process it.
We could add a pull request to fliter it first. But more importantly, we should adopt this, rather than filtering it.
