### ISSUE TITLE
Some questions about logger refresh mechanism in the agent startup process.

### ISSUE THREAD

**Issue by buyanhub** [apache/skywalking#7348]
- Why do you submit this issue?
- [√] Question or discussion

___
### Question
- What do you want to know?

I have some doubts about logger in the agent startup process.

The first step of agent startup process is to load configuration items. Source code shows below:

```
try {
    SnifferConfigInitializer.initializeCoreConfig(agentArgs);
} catch (Exception e) {
    // try to resolve a new logger, and use the new logger to write the error log here
    LogManager.getLogger(SkyWalkingAgent.class)
            .error(e, "SkyWalking agent initialized failure. Shutting down.");
    return;
} finally {
    // refresh logger again after initialization finishes
    LOGGER = LogManager.getLogger(SkyWalkingAgent.class);
}
```

What is the reason for resolve a new logger when catch an Exception and why dose it need to refresh logger again after initialization finishes ? I found it dose not need to resolve or refresh logger in earlier version.

**Comment by wu-sheng** [comment]
Because agent logger init process could fail, then logger could have different implementation. You should know, the community does not take the responsibility to explain codes.
