### ISSUE TITLE
Live demo is down

### ISSUE THREAD

**Issue by Hongbo-Miao** [apache/skywalking#7350]
Hmm, the live demo is down. Tried Chrome, Firefox, Safari. Different machines. Also with and without VPN.

![image](https://user-images.githubusercontent.com/3375461/126466036-6561712c-9280-41fe-8e93-bee1533f7d97.png)

**Comment by kezhenxu94** [comment]
It works from my side, please check your network / proxy / firewall

**Comment by Hongbo-Miao** [comment]
@kezhenxu94 This one https://demo.skywalking.apache.org/ ?
For network, I tried without VPN, with my Stanford University VPN, Tesla VPN. Also tried my phone 4G network.
For browsers, on my MacBook Pro, I tried Chrome, Firefox, Safari, Brave. On my iPhone, I tried Brave, Safari.
All got same result...

**Comment by kezhenxu94** [comment]
Use http, not https

**Comment by Hongbo-Miao** [comment]
Oh nice it works now. Thanks!

Both Brave 1.29.12 and Firefox 92.0a1 will redirect to `https` even I input `http`.
Chrome and Safari won't redirect.

I think it would be great to support `https` as this quite like standard of Internet.
