### ISSUE TITLE
SpringCloud Gateway，在Gateway-server服务上的日志log4j2输出 traceId 总是 TID: N/A

### ISSUE THREAD

**Issue by pangshuqiang** [apache/skywalking#7351]
- [ *] Question

___

应用服务：Skywalking8.6.0 server，在docker运行

访问链路：user --> gateway-server --> weifor-server

插件拷贝：从\agent\optional-plugins\目录查找对应apm-spring-cloud-gateway-2.1.x-plugin-8.6.0.jar和apm-spring-webflux-5.x-plugin-8.6.0.jar拷贝到\agent\plugins\目录下（没找到apm-spring-cloud-gateway-2.2.x-plugin-8.6.0.jar ？？？？？？）

项目环境：
`<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.12.RELEASE</version>
    </parent>

    <properties>
        <spring-cloud.version>Hoxton.SR12</spring-cloud.version>
        <spring-cloud-alibaba.version>2.2.6.RELEASE</spring-cloud-alibaba.version>
        <skywalking.version>8.6.0</skywalking.version>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            
            <exclusions>
                
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-log4j-2.x</artifactId>
            <version>${skywalking.version}</version>
        </dependency>
    </dependencies>`

日志配置文件log4j2.xml
`<Property name="log.pattern">%d ${sys:PID} [%15.15t] %-5p --- [${app.name},%traceId] %C{1.} - %m%n%xwEx</Property>`

其中正常的有：
1、Skywalking管理端，可以看到User-->gateway-server-->weifor-server的拓扑图
![图片](https://user-images.githubusercontent.com/28327645/126471928-91e41570-c47e-4fbe-9e13-0d230d90578d.png)

2、weifor-server能正常输出traceId，比如：`2021-07-21 17:59:05,808 13844 [nio-9010-exec-5] INFO  --- [weifor-server,TID: b6c210a62ef04941a7d8a84af6438b8a.176.16268615457990015].....`

但是网关gateway-server总是输出traceId为TID: N/A，比如：
`2021-07-21 17:59:05,802 24408 [ctor-http-nio-2] INFO  --- [gateway-server,TID: N/A].......`

为什么网关gateway-server不能自动生成traceId，毕竟入口是从gateway-server这个服务开始的，是我哪里没有配置吗？还是说本身gateway-server就不会输出traceId？？？

way??

**Comment by wu-sheng** [comment]
Please use English in Github, we are for global people.

**Comment by wu-sheng** [comment]
Community doesn't provide support service. You could read codes.

**Comment by cyniubi** [comment]
how to solve it? I just had the same problem

**Comment by taxus1** [comment]
> 



> how to solve it? I just had the same problem

can you solve?
