### ISSUE TITLE
Support https for live demo website

### ISSUE THREAD

**Issue by Hongbo-Miao** [apache/skywalking#7352]
Why do you submit this issue?

- [x] Feature or performance improvement

___

### Requirement or improvement

I was trying the live demo. However, my browsers Brave 1.29.12 and Firefox 92.0a1 will redirect to `https` even I input `http`.
(Chrome and Safari won't redirect)

I think it would be great to support `https` as this is quite like the standard of Internet today.

BTW, the tool looks awesome!

**Comment by wu-sheng** [comment]
https is not supported.

**Comment by Hongbo-Miao** [comment]
@wu-sheng would you mind clarifying? Do you mean Skywalking does not support `https` at all? As in production even internally, we do need use https.
Or just the live demo no plan to support https?

**Comment by wu-sheng** [comment]
apache.org is the foundation level cert. We are not going to apply for that.

**Comment by Hongbo-Miao** [comment]
Oh I see, thanks!
