### ISSUE TITLE
`make build.agent` doesn't work

### ISSUE THREAD

**Issue by qsliu2017** [apache/skywalking#7355]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug

`make build.agent` does not work,
<img width="630" alt="截屏2021-07-21 下午11 12 41" src="https://user-images.githubusercontent.com/57934883/126513924-c1899c62-d8a4-4d2d-afef-1a47fbf0c7c0.png">
it seems like some submodules depend on `apm-webapp` and this make target doesn't build it.

**Comment by wu-sheng** [comment]
Build the whole project at least once.
