### ISSUE TITLE
Is the ServiceInstanceGenerator's priority is highest or lowest

### ISSUE THREAD

**Issue by Cool-Coding** [apache/skywalking#7356]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is the priority of <code>ServiceInstanceGenerator</code> class highest or lowest?

```java
public interface BootService {
    void prepare() throws Throwable;

    void boot() throws Throwable;

    void onComplete() throws Throwable;

    void shutdown() throws Throwable;

    /**
     * {@code BootService}s with higher priorities will be started earlier, and shut down later than those {@code BootService}s with lower priorities.
     *
     * @return the priority of this {@code BootService}.
     */
    default int priority() {
        return 0;
    }
}

public class ServiceInstanceGenerator implements BootService {
    @Override
    public void prepare() throws Throwable {
        if (!isEmpty(Config.Agent.INSTANCE_NAME)) {
            return;
        }

        Config.Agent.INSTANCE_NAME = UUID.randomUUID().toString().replaceAll("-", "") + "@" + OSUtil.getIPV4();
    }

    @Override
    public void boot() throws Throwable {

    }

    @Override
    public void onComplete() throws Throwable {

    }

    @Override
    public void shutdown() throws Throwable {

    }

    @Override
    public int priority() {
        return Integer.MAX_VALUE;
    }
}
```

I think <code>ServiceInstanceGenerator</code>'s priority should be highest as other service maybe use instance name. 
As <code>BootService</code> says, higher priorities will be started earlier and shut down later. but, I find <code>ServiceInstanceGenerator</code> is the last one prepared and started. lt's the earliest one shut down.

```java
    private void prepare() {
        bootedServices.values().stream().sorted(Comparator.comparingInt(BootService::priority)).forEach(service -> {
            try {
                service.prepare();
            } catch (Throwable e) {
                LOGGER.error(e, "ServiceManager try to pre-start [{}] fail.", service.getClass().getName());
            }
        });
    }

    private void startup() {
        bootedServices.values().stream().sorted(Comparator.comparingInt(BootService::priority)).forEach(service -> {
            try {
                service.boot();
            } catch (Throwable e) {
                LOGGER.error(e, "ServiceManager try to start [{}] fail.", service.getClass().getName());
            }
        });
    }

    public void shutdown() {
        bootedServices.values().stream().sorted(Comparator.comparingInt(BootService::priority).reversed()).forEach(service -> {
            try {
                service.shutdown();
            } catch (Throwable e) {
                LOGGER.error(e, "ServiceManager try to shutdown [{}] fail.", service.getClass().getName());
            }
        });
    }
```

**Comment by wu-sheng** [comment]
Let's talk on Kafka issue. I don't want to introduce priority system for this. This will make core too complex and unnecessary complex.

**Comment by Cool-Coding** [comment]
> Let's talk on Kafka issue. I don't want to introduce priority system for this. This will make core too complex and unnecessary complex.

@wu-sheng I think <code> ServiceInstanceGenerator</code> should be this first class to be prepared. lt's priority should be highest. but it actually is the last one prepared

**Comment by wu-sheng** [comment]
I don't think it should have priority. Others service should use it after prepare stage. The oap server has similar requirement in the modularization system.

**Comment by Cool-Coding** [comment]
> I don't think it should have priority. Others service should use it after prepare stage. The oap server has similar requirement in the modularization system.

@wu-sheng I agree with you if other services don't use it in prepare stage. thanks for your reply.

**Comment by wu-sheng** [comment]
> > I don't think it should have priority. Others service should use it after prepare stage. The oap server has similar requirement in the modularization system.
> 
> 
> 
> @wu-sheng I agree with you if other services don't use it in prepare stage. thanks for your reply.

If it is using, it is a bug.
