### ISSUE TITLE
INSTANCE_NAME generated in KafkaServiceManagementServiceClient class is not suitable

### ISSUE THREAD

**Issue by Cool-Coding** [apache/skywalking#7357]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement

```java
  // the KafkaServiceManagementServiceClient class
   @Override
    public void prepare() {
        .....
        Config.Agent.INSTANCE_NAME = StringUtil.isEmpty(Config.Agent.INSTANCE_NAME)
            ? UUID.randomUUID().toString().replaceAll("-", "") + "@" + OSUtil.getIPV4()
            : Config.Agent.INSTANCE_NAME;
    }
```
As we see, Config.Agent.INSTANCE_NAME is generated if lt's empty. I think it is not suitable. <code>Config.Agent.INSTANCE_NAME </code> shouldn't be empty as the <code>ServiceInstanceGenerator</code> class should prepare earlies.  

why did the author add the logic of generating instance_name here? I guess it relates to the problem of  <code>ServiceInstanceGenerator</code>'s priority mentioned at #7356

**Comment by wu-sheng** [comment]
This seems wrong in prepare stage. Prepare stage should not depend on other module, it should be an internal process.

**Comment by Cool-Coding** [comment]
> This seems wrong in prepare stage. Prepare stage should not depend on other module, it should be an internal process.

@wu-sheng I think we should remove the logic of generating instance name in KafkaServiceManagementServiceClient. if you aggree, i will do it.

**Comment by wu-sheng** [comment]
I think it should reuse the existing logic, rather than generating again.

**Comment by Cool-Coding** [comment]
> I think it should reuse the existing logic, rather than generating again.

@wu-sheng yes, I also think so. Instance name is already gerenated at <code>ServiceInstanceGenerator</code> prepare phase.  Other classes should directly use it.
```java
public class ServiceInstanceGenerator implements BootService {
    @Override
    public void prepare() throws Throwable {
        if (!isEmpty(Config.Agent.INSTANCE_NAME)) {
            return;
        }

        Config.Agent.INSTANCE_NAME = UUID.randomUUID().toString().replaceAll("-", "") + "@" + OSUtil.getIPV4();
    }

    @Override
    public void boot() throws Throwable {

    }

    @Override
    public void onComplete() throws Throwable {

    }

    @Override
    public void shutdown() throws Throwable {

    }

    @Override
    public int priority() {
        return Integer.MAX_VALUE;
    }
}
```

**Comment by wu-sheng** [comment]
You could try and test.

**Comment by Cool-Coding** [comment]
> You could try and test.

@wu-sheng ok, I will work on it today

**Comment by Chasun-fhd** [comment]
The instance name can be generated based on some predefined rules?
scenario：
i have above 15 instance in prod which share the same client agent configuration.
when i set agent.instance_name， seems like  there 15 same items in the combobox
while i use default configuration. `uuid@hostname` would be too long for that. 

such as  i prefer to use hostname only. or i shoud modify the `ServiceInstanceGenerator` logic by myself ?

**Comment by wu-sheng** [comment]
> The instance name can be generated based on some predefined rules?
> 
> scenario：
> 
> i have above 15 instance in prod which share the same client agent configuration.
> 
> when i set agent.instance_name， seems like  there 15 same items in the combobox
> 
> while i use default configuration. `uuid@hostname` would be too long for that. 
> 
> 
> 
> such as  i prefer to use hostname only. or i shoud modify the `ServiceInstanceGenerator` logic by myself ? 

Please don't make the context mass. Your question has been answered many times. Read document and search issues.
