### ISSUE TITLE
Design and implementation of `zeebe-client-plugin`

### ISSUE THREAD

**Issue by vcjmhg** [apache/skywalking#7360]
Please answer these questions before submitting your issue.

* Why do you submit this issue?

* [x] Question or discussion
* [ ] Bug
* [x] Requirement
* [ ] Feature or performance improvement

---

### Question
* What do you want to know?
The zeebeBroker used in `plugin-scenario` is a service built on the external network by me. Is there any way to mock zeebe broker in the `zeebe-plugin-scenario`. It seems impossible to deploy zeebe through docker, and it seems unreasonable to place zeebe packages into `zeebe-plugin-scenario` directly.

---
### Requirement or improvement

* Please describe your requirements or improvement suggestions.

# Summary

`Zeebe` is a workflow engine from Camunda, designed to meet the scalability requirements of high-performance applications running on cloud-native software architectures and to support workflows that span multiple microservices in low latency, high-throughput scenarios. When we use zeebe for service orchestration, due to the lack of support for the zeebe plugin, the span of the process instance will be disconnected from the corresponding Jobwork, forming mutually independent spans.

For easy understanding, we imagine the following scenario:

The user accessed service A through the gateway, and service A created a process instance through service B. JobWorker activates an internal task by polling ZeebeBroker, which in turn calls other services such as kafka.
![image](https://user-images.githubusercontent.com/55177318/126644037-e65ed15e-7bf1-4d59-b9a7-f91474cc3a1b.png)

Without the `zeebe-client-plugin`, when the scenario is displayed in skywalking, the spans of several locations in the figure below will be disconnected, forming serval independent spans.
![image](https://user-images.githubusercontent.com/55177318/126644050-d39fc172-388a-4974-b6ea-2ef2a17cbfdb.png)

Without the `zeebe-client-plugin`,the spans generated by the creation of process variables and the execution of their corresponding JobWorker can be connected in series. And make the service ZeebeBroker transparent, because in actual scenarios, we don’t care about the internal processing logic of ZeebeBroker. Just like this:

![image](https://user-images.githubusercontent.com/55177318/126644086-0ac66171-7f7b-4096-853a-d94a6554cf18.png)

The final span display result is similar to the following:
![image](https://user-images.githubusercontent.com/55177318/126644115-83c7960d-9117-4c4d-99e4-2f4ad257f290.png)

Service A creates a process instance named process_id through `CreateWorkflowInstance`(). And the process instance is executed by the JobWorker whose type is activateJob. Finally, the remote api service is called inside JobWorker.

# how to desgin

Before create process instance, we create an ExitSpan and put the contextCarrier into process variables of zeebe.

Before execute Job, we get the contextCarrier and restore context.

![image](https://user-images.githubusercontent.com/55177318/126644143-3092394e-141a-460c-82a5-b95336b6b40e.png)

why we use process variable?

ZeebeBroker is too complicated, a simple schematic diagram is as follows:

![image](https://user-images.githubusercontent.com/55177318/126754284-7d85c003-8935-4875-a8a4-f81e71b7300d.png)

If we choose to directly enhance on ZeebeBroker, we need a lot of enhancement points. High difficulty on the one hand, low efficiency on the other

# test results in UI

![image](https://user-images.githubusercontent.com/55177318/126730240-5d495f91-83c9-4d84-aba9-b74b233027ee.png)

# Issues to be discussed

The zeebeBroker used in `plugin-scenario` is a service built on the external network by me. Is there any way to mock zeebe broker in the `zeebe-plugin-scenario`. It seems impossible to deploy zeebe through docker, and it seems unreasonable to place zeebe packages into `zeebe-plugin-scenario` directly.

**Comment by wu-sheng** [comment]
Is ZeebeBroker a server? From a graph, it looks like.

**Comment by wu-sheng** [comment]
From your graph, you should treat it like a Kafka server, which means, having exit span and entry span.

**Comment by vcjmhg** [comment]
It looks very similar to the Kafka server, but the difference is that every step of its operation is based on event-driven, that is to say, the event created by createInstance() and the message received by JobWorker are not related in any way.

![image](https://user-images.githubusercontent.com/55177318/126753335-4d19887b-8344-4088-968c-8e6b43cb9fa1.png)

In server, I can try to enhance it in the process part, but because the creation of events is very frequent, so its efficiency may be very low.

**Comment by wu-sheng** [comment]
It doesn't have to enhance the server side, which is another story. My points are 
1. You should have your own component for Zeebe. 
2. Is topology working? Show with the server?

**Comment by wu-sheng** [comment]
I think you have to set the layer as MQ, the server could show up correctly on the topology page. Or you prefer to instrument server directly.

**Comment by vcjmhg** [comment]
Ok, the layer has changed to MQ. It turns out that setting to RPC is indeed inappropriate.
Currently, the topology show like this:
![image](https://user-images.githubusercontent.com/55177318/126761335-cddeba79-05b3-43d4-a5be-3ed10999d027.png)

**Comment by vcjmhg** [comment]
> 1. You should have your own component for Zeebe.

![image](https://user-images.githubusercontent.com/55177318/126762059-bcbba20f-1127-4ecd-b7a4-20cf94660e9c.png)
Do you mean that zeebe should appear as a component so that we can see the working status of zeebe broker?

**Comment by wu-sheng** [comment]
If you set it as MQ, and have correct peer IP, then it should have a node i. topology.

**Comment by vcjmhg** [comment]
like this?
![image](https://user-images.githubusercontent.com/55177318/126779616-b1ae1d0d-fa73-44ea-9b72-9d71f78cecf5.png)

**Comment by wu-sheng** [comment]
What is create instance?

**Comment by vcjmhg** [comment]
The error result when the peer was not set correctly before, after restarting the OAP, the display is as follows：
![image](https://user-images.githubusercontent.com/55177318/126781258-22d69be7-a266-435a-8aa5-f8205f4fcb9b.png)

**Comment by wu-sheng** [comment]
And is the Zeebe open sourced? Does it have an icon to contribute to UI repo?
Then the topology could show the node with an meaningful icon, rather than current cloud icon.

**Comment by vcjmhg** [comment]
Yes, it's open-sourced. And I will do it.

**Comment by vcjmhg** [comment]
And I want to know how to mock the server in my test project.
In `activemq-scenario`, I don't find the URL of server .  It has a `brokenUrl` but is not injected in the project. 
![image](https://user-images.githubusercontent.com/55177318/126782744-77817c7a-b78e-4d91-8960-54cf1ecee74f.png)
![image](https://user-images.githubusercontent.com/55177318/126782805-8973b77d-4fa7-4bc4-b106-3ae3d3539f65.png)

**Comment by wu-sheng** [comment]
There is a docker compose out there. Have you checked?

**Comment by vcjmhg** [comment]
ok, I find it.

**Comment by vcjmhg** [comment]
Sorry, many things need to modify. Need to re-check compliance. After the modification is completed, the PR will be re-initiated

**Comment by vcjmhg** [comment]
Sorry, many things need to modify. Need to re-check compliance. After the modification is completed, the PR will be re-initiated
