### ISSUE TITLE
Is it possible to construct skywalking plugin test cases for some component with different version?

### ISSUE THREAD

**Issue by liuhaoXD** [apache/skywalking#7362]
- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

In the production environment, it's quite difficult to force all projects to use components with the same version.

For example, project A uses spring-mvc:1.3.2 as the web framework, while project B uses spring-mvc:1.3.3. It's hard to say that the skywalking agent spring-mvc plugin can work on both 1.3.2 and 1.3.3, and changes we made on the agent plugin are backward compatible with the older version of the specific component.

**Comment by kezhenxu94** [comment]
Read our tests codes, we tested different versions of the frameworks in the CI already

**Comment by kezhenxu94** [comment]
https://github.com/apache/skywalking/tree/master/test/plugin
