### ISSUE TITLE
how to fileter the service or method

### ISSUE THREAD

**Issue by auqf** [apache/skywalking#7365]
![image](https://user-images.githubusercontent.com/8895540/126750186-1a7e23d7-6775-4b46-b4b3-4d2e56b9dd20.png)
how can I config the filter rules? I have try many times and as follows, it's failed
![image](https://user-images.githubusercontent.com/8895540/126750397-44258ea8-aa40-42d7-9805-58bce779546c.png)

**Comment by wu-sheng** [comment]
Your UI shows a very very old version. I don't sure why it is.

**Comment by auqf** [comment]
i use the 8.4,it's olded?

**Comment by wu-sheng** [comment]
Your screenshot is not 8.x

**Comment by wu-sheng** [comment]
Filtering service is pointless. It is as same as no agent installation. Filtering endpoint is custom ignore plugin. It is in the doc.

**Comment by auqf** [comment]
![image](https://user-images.githubusercontent.com/8895540/126751543-1f53d549-7864-4953-bfe2-0e12e8ea95a1.png)
this is my web, the old pic is not mine
