### ISSUE TITLE
InstanceTraffic supportUpdate=true bug

### ISSUE THREAD

**Issue by ayumiono** [apache/skywalking#7369]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking 8.3.0
- Which company or project?

- What happened?

i got 7 indice for skywalking_instance_traffic：skywalking_instance_traffci-20210720, skywalking_instance_trfffic-20210721...., skywalking-instance_traffic-20210726，

and i want update a instance properties which id is  "bXlzdGVlbC1kaS1kYXNoYm9hcmQtbxxx.1_bXlzdGVlbC1kaS1kYXNoYm9hcmQtbWd0LTU3xxxWI4NGYtOWJ0eDlAMTAuODMuMy4xNg==" 

what i expect is the doc in the latest indice (skywalking-instance_traffic-20210726) updated

but what actually happened is some other older indice rather than the latest indice (skywalking-instance_traffic-20210726) updated.

i read the source code, find that instance_metrics doc's id does not contain any time_bucket info, and when search by instance_traffic/ids，the ES return multiple docs with the same id. and on the same time, the MetricsPersistentWorker.loadFromStorage will map these docs with the same id into just one k/v, means the older one may override the newest one，that lead to we cannot update  the newest instance_traffic docs

is it a bug? thx

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is not a bug. We said it is an update, what you were expecting is delete and insert.

**Comment by ayumiono** [comment]
> This is not a bug. We said it is an update, what you were expecting is delete and insert.

> This is not a bug. We said it is an update, what you were expecting is delete and insert.

@wu-sheng thanks for you reply, i'm afraid that you may misunderstood what id said. what i expect is that when the agent update the instance properties to the oap server for now, the oap server should save the update into the latest indice which is meaningful rather than some older indice, am i right?  

update is right of cause, it is not a bug. What the bug exactlly is the ES return multiple docs when we search instance_traffiic by id, and we chose a wrong indice to update 

```
@Override
    public void combine(final Metrics metrics) {
        final InstanceTraffic instanceTraffic = (InstanceTraffic) metrics;
        this.lastPingTimestamp = instanceTraffic.getLastPingTimestamp();
        if (instanceTraffic.getProperties() != null && instanceTraffic.getProperties().size() > 0) {
            this.properties = instanceTraffic.getProperties();
        }
        if (instanceTraffic.getAgentInfo() != null) {
            this.agentInfo = instanceTraffic.agentInfo;
        }
        /**
         * Keep the time bucket as the same time inserted.
         */
        if (this.getTimeBucket() > metrics.getTimeBucket()) {
            this.setTimeBucket(metrics.getTimeBucket());
        }
    }
```
above is InstanceTraffic.combine code, i just confused that why we keep the time bucket as the old timebucket, why can not we just keep the newest timebucket (which is the time when agent report a instance update to oap server) so that we can chose the right indice to update

my english is poor, i hope i deliver my point clealy above, thx!

**Comment by wu-sheng** [comment]
> thanks for you reply, i'm afraid that you may misunderstood what id said. what i expect is that when the agent update the instance properties to the oap server for now, the oap server should save the update into the latest indice which is meaningful rather than some older indice, am i right?

No, you are not correct. Once you add a new row, there would be duplicate records in the query, which is not necessary.

**Comment by wu-sheng** [comment]
> What the bug exactlly is the ES return multiple docs when we search instance_traffiic by id, and we chose a wrong indice to update

Where does a duplicate record come from? We don't insert the entity into the newer index at all.

**Comment by ayumiono** [comment]
> > thanks for you reply, i'm afraid that you may misunderstood what id said. what i expect is that when the agent update the instance properties to the oap server for now, the oap server should save the update into the latest indice which is meaningful rather than some older indice, am i right?
> 
> No, you are not correct. Once you add a new row, there would be duplicate records in the query, which is not necessary.

thanks for you reply. I do not ask to add a new row.

**Comment by wu-sheng** [comment]
**what i expect is that when the agent update the instance properties to the oap server for now, the oap server should save the update into the latest indice which is meaningful rather than some older indice**

This is what you said. If not add a new row, how it is possible?

**Comment by ayumiono** [comment]
> > What the bug exactlly is the ES return multiple docs when we search instance_traffiic by id, and we chose a wrong indice to update
> 
> Where does a duplicate record come from? We don't insert the entity into the newer index at all.

thanks for you reply. the ES return duplicate record because of we(skywalking es persistence plugin) search ES by indice alias

```
@Override
    public List<Metrics> multiGet(Model model, List<String> ids) throws IOException {
        SearchResponse response = getClient().ids(model.getName(), ids.toArray(new String[0]));

        List<Metrics> result = new ArrayList<>(response.getHits().getHits().length);
        for (int i = 0; i < response.getHits().getHits().length; i++) {
            Metrics source = storageBuilder.map2Data(response.getHits().getAt(i).getSourceAsMap());
            result.add(source);
        }
        return result;
    }
```

**Comment by wu-sheng** [comment]
Hi, could you get your head clear? If there is no one updates the time bucket, there is no chance to insert another new record. 

I think this duplicate record is caused by ES is not queryable in the short term, then the OAP inserts a new one. This has nothing related to the source codes you posted.

Think again because you reply further. Or read your words again, they are against each other.

**Comment by ayumiono** [comment]
> Hi, could you get your head clear? If there is no one updates the time bucket, there is no chance to insert another new record.
> 
> I think this duplicate record is caused by ES is not queryable in the short term, then the OAP inserts a new one. This has nothing related to the source codes you posted.
> 
> Think again because you reply further. Or read your words again, they are against each other.



```
indice                                                                           id                    
skywalking-instance_traffic-20210721                        service_instance_id_xxxx
skywalking-instance_traffic-20210722                        service_instance_id_xxxx
skywalking-instance_traffic-20210723                        service_instance_id_xxxx
skywalking-instance_traffic-20210724                        service_instance_id_xxxx
skywalking-instance_traffic-20210725                        service_instance_id_xxxx
skywalking-instance_traffic-20210726                        service_instance_id_xxxx
```
indice is above for example, 
for now,  a instance report a ServiceInstanceUpdate to oap server, 
```
@Override
    public void dispatch(final ServiceInstanceUpdate source) {
        InstanceTraffic traffic = new InstanceTraffic();
        traffic.setTimeBucket(source.getTimeBucket());
        traffic.setName(source.getName());
        traffic.setServiceId(source.getServiceId());
        traffic.setLastPingTimestamp(source.getTimeBucket());
        traffic.setProperties(source.getProperties());
        traffic.setAgentInfo(source.getAgentInfo());
        MetricsStreamProcessor.getInstance().in(traffic);
    }
```
the InstanceTraffic's timebucket is 20210726 right? 
and when the new InstanceTraffic object received by MetricsPersistentWorker, the MetricsPersistentWorker will try to load cache from ES using multiGet(), which will use skywalking-instance_traffic/_search and return 6 record right?

if the MetricsPersistentWorker chose the skywalking-instance_traffic-20210726 docs to update everything is fine, but there is no code to make sure for that now

**Comment by wu-sheng** [comment]
> and return 6 record right?

What do you mean 6 records? 

> if the MetricsPersistentWorker chose the skywalking-instance_traffic-20210726 docs to update everything is fine, but there is no code to make sure for that now

Choosing `skywalking-instance_traffic-20210726` is totally wrong. You can't update a row originally from 20210721 and make it updated in `*0726`. 
SkyWalking keep the time bucket unchanged, then the data is only updated in the original index(assume `0721`)

**Comment by wu-sheng** [comment]
![image](https://user-images.githubusercontent.com/5441976/126947622-74865957-35b2-4364-889e-44184050a7c3.png)

The codes you posted are making against what you said later. That is what I mean, you don't get yourself clear.

**Comment by ayumiono** [comment]
> What do you mean 6 records?

thanks for reply, below is code how the persistence worker load cache from ES

 ```
private void loadFromStorage(List<Metrics> metrics) throws IOException {
        if (!enableDatabaseSession) {
            context.clear();
        }

        List<String> notInCacheIds = new ArrayList<>();
        for (Metrics metric : metrics) {
            if (!context.containsKey(metric)) {
                notInCacheIds.add(metric.id());
            }
        }

        if (notInCacheIds.size() > 0) {
            List<Metrics> metricsList = metricsDAO.multiGet(model, notInCacheIds);
            for (Metrics metric : metricsList) {
                context.put(metric, metric);
            }
        }
    }
```
suppose notInCacheIds just has one element -> service_instance_id_xxxx, since we got 6 indices(*0721~*0726 like i supposed earlier), metricsDAO will return 6 records. However the context will just keep only one instance_traffic. If the context hold *0726, it will be just what i expect cause the agent report the update just for now, for today, and i want the *0726 indice to be updated,  but  if the context hold other but *0726, it will be strange, cause the agent report udpate right now but a older indice for example *0722 updated, right?

**Comment by wu-sheng** [comment]
> suppose notInCacheIds just has one element -> service_instance_id_xxxx, since we got 6 indices(0721~0726 like i supposed earlier), metricsDAO will return 6 records

I don't need to read the whole reply. This is already totally wrong. You should simulate the scenario from the beginning, rather than just guessing.  There are never 6 records in 5 indices for one instance. There is always only one, as the time bucket never changed.

I am going to keep saying the same thing. You take a lot of time to read codes and reply, but you forget the most important things, you do some wrong assumptions from the beginning.

**Comment by ayumiono** [comment]
Apologize for this issue indeed. It's not skywalking's bug, According to the skywalking source code, there will always only one instance traffic instance for a service instance principlely. I guess it is because our es cluster sometimes return empty resultset even there exist doc in the indices, as a result, a brand new instance traffic indices created.
