### ISSUE TITLE
Does skywalking support opentelemetry protocol https://opentelemetry.io/docs/?

### ISSUE THREAD

**Issue by chenhaipeng** [apache/skywalking#7374]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Does skywalking support opentelemetry protocol https://opentelemetry.io/docs/?

**Comment by wu-sheng** [comment]
> OpenTelemetry is a set of APIs, SDKs, tooling and integrations

Where they say, they are a kind of protocol?

**Comment by chenhaipeng** [comment]
> > OpenTelemetry is a set of APIs, SDKs, tooling and integrations
> 
> Where they say, they are a kind of protocol?
In other words, how can I access skywalking if I use opentelemetry SDK or API？

**Comment by wu-sheng** [comment]
Why are you doing that? How you do is not a question the community should answer.

**Comment by chenhaipeng** [comment]
> Why are you doing that? How you do is not a question the community should answer.

I have built a relatively large skywalking cluster, and there have been more business accesses, but there are many language implementations, such as java, go, python, etc., and the reporting agents are very inconsistent, such as zipkin, jaeger, and skywalking. I see that the community has a new protocol for opentelemetry. I want the business to uniformly use the latest agreement of the community. What should I do to migrate? So if you have this question, thank you very much for answering

**Comment by wu-sheng** [comment]
For all languages you mentioned, we have provided languages agents, you could remove all others. 
We have done the full research about working with Zipkin-style pure tracing data format(https://github.com/SkyAPM/zipkin-skywalking), the result is very clear, they are too pure to be a tracing system only.
SkyWalking from day one is designed as an APM, you can't use a lower-level system format to get higher-level analysis results and fully functions.

**Comment by chenhaipeng** [comment]
> designed

If I use opentelemetry sdk to report data, is skywalking compatible? Most businesses want a simple and unified choice, if possible, whether to use opentelemetry sdk to report data instead of zipkin, jaeger and the like.

> For all languages you mentioned, we have provided languages agents, you could remove all others.
> We have done the full research about working with Zipkin-style pure tracing data format(https://github.com/SkyAPM/zipkin-skywalking), the result is very clear, they are too pure to be a tracing system only.
> SkyWalking from day one is designed as an APM, you can't use a lower-level system format to get higher-level analysis results and fully functions.

If I use opentelemetry sdk to report data, is skywalking compatible? Most businesses want a simple and unified choice, if possible, whether to use opentelemetry sdk to report data instead of zipkin, jaeger and the like.

**Comment by wu-sheng** [comment]
I just gave you the answer, don't I? Could you at least read the content?

**Comment by JaredTan95** [comment]
@chenhaipeng 
From your description, I got you mean that you want java, go, python, etc application to report data to skywalking, for that point, skywalking provided those languages agent or sdk. you can find it in https://skywalking.apache.org/docs/.

As you mentioned opentelemetry protocol, that would be another discussion, right?

**Comment by wu-sheng** [comment]
Conclusion to all people reading this thread later.

Don't be naive about the technology. From OpenTracing to OpenTelemetry, there is always a tricky term like a so-called unified solution for tracing. I don't want to waste time to argue whether this is possible or not, whether they(OpenTracing and OpenTelemetry are actually the same groups of people, except I exited) are doing right or wrong.

But at least, observability is not tracing. The APM is not just tracing. SkyWalking is doing a used-to-be commercial-level only tracing-based APM system, and now to extend to be a whole APM system including tracing/metrics/logging/event. Dapper is the paper 10 years ago, worlds changes, APM vendors and industry have a very clear conclusion, if you want to analysis topology and metrics in high performance from the tracing, Dapper-similar data format(Zipkin, Jaeger, anything) is not enough.

If you want to understand the real world, read the STAM paper, https://wu-sheng.github.io/STAM/, which is a thing designed for 2020, rather than 2000.

**Comment by chenhaipeng** [comment]
> @chenhaipeng
> From your description, I got you mean that you want java, go, python, etc application to report data to skywalking, for that point, skywalking provided those languages agent or sdk. you can find it in https://skywalking.apache.org/docs/.
> 
> As you mentioned opentelemetry protocol, that would be another discussion, right?

Thank you for the answers from the two above. The background is: the company recommends this (opentelemetry) protocol, and other businesses use this protocol to seamlessly switch to the implementation of different APM products. What I really want to ask is whether you can use opentelemetry sdk to report to skywalkling, similar Jaeger is also a plug-in of skywalking, even if it only has the function of trace.

**Comment by wu-sheng** [comment]
Jaeger receiver is removed. Either Jaeger or Zipkin receivers can't provide any metrics analysis or topology generation. That is why I said, don't be naive. Your leaders are willing to trust a slide(PPT), I really can't help in any way. Really sorry to hear people are still far away from understanding the complexity of observability. They read a slide saying, we are switchable, and trust without asking any question about how is that possible? If all things are that easy, you have built all things on your own, don't you?

**Comment by wu-sheng** [comment]
Please, let's don't waste more time on this topic. We should only talk about the real scenarios, rather than wasting time on a marketing story.

**Comment by wu-sheng** [comment]
> other businesses use this protocol to seamlessly switch to the implementation of different APM products

What is an APM? You have said by yourself, `even if it only has the function of trace.`. Notice what is already in your mind. OK?

**Comment by chenhaipeng** [comment]
> > other businesses use this protocol to seamlessly switch to the implementation of different APM products
> 
> What is an APM? You have said by yourself, `even if it only has the function of trace.`. Notice what is already in your mind. OK?
> 
> **Tracing system** is not an APM system, never will be.

I understand your design philosophy. I think about how to solve this problem. Thanks for the answer~~~

**Comment by wu-sheng** [comment]
You only can 2 options
1. Give up, choose a side. Don't have to choose SkyWalking, like mentioned many times, choose zipkin or jaeger if you only need a pure trace system. There is no point to use an APM to replace a tracing system.
2. Build your own backend based on an old-fasion big data platform, built all things on your own. If you really believe `switch`. But building your own is not `switch` at all too.

**Comment by slcnx** [comment]
> you can't use a lower-level system format to get higher-level analysis results and fully functions.

opentelemetry上传给skywalking的数据，图画不出来。可能字节码注入技术比较落后吧。
