### ISSUE TITLE
any way  to monitor the lost of segments?

### ISSUE THREAD

**Issue by 844067874** [apache/skywalking#7375]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
It should be able to monitor the lost of segments.
In my application,it happends frequently,the segment lost,it also do not print error log in skywalking-api.log.

**Comment by wu-sheng** [comment]
What do you mean lost? Where are they lost?

**Comment by 844067874** [comment]
sometimes the tracing is completed,sometimes some segment has lost,exclude memory leak.
should I adjust buffer.buffer_size?

**Comment by wu-sheng** [comment]
It is hard to tell, maybe buffer size, or ES and OAP cluster is not powerful enough, then agents run into protection mode. Also network could be the issue.
Anyway, your description is not clear to talk deeply.
