### ISSUE TITLE
No active span

### ISSUE THREAD

**Issue by zhishenglin** [apache/skywalking#7376]
___
### Bug
- 版本：6.4.0
- 没有任何特殊配置，使用skywalking监听程序。在程序调用feign远程接口时报错：no active span。
- 特殊的地方：在调用远程feign之前，调用了redisson的乐观锁。乐观锁释放后调用feign远程接口，然后接口报错。
![image](https://user-images.githubusercontent.com/42052484/127022876-91092685-0eb3-4c1c-b72b-36d40cb8b787.png)

**Comment by wu-sheng** [comment]
Please use English on Github. 6.4 is too old. Try latest release.
