### ISSUE TITLE
[QUESTION] Need specifications about field of indecies Skywalking created in Elasticsearch.

### ISSUE THREAD

**Issue by happyfeetw** [apache/skywalking#7380]
- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- A specification about the field of indecies that skywalking creates in elasticsearch, telling the relationship of those indecies and what the field represent for, cuz reading from source code may help but is of low efficiency. 

- Why do I submit?
I've read official docs and various info on the internet for several days for these informations but got nearly nothing useful nor strongly related to my expectation.
Really need help. Thanks!

**Comment by wu-sheng** [comment]
We don't that kind of doc. Sorry. Different storage implementations have different designs in different versions.
And from a community, no one contributed this kind of doc.

**Comment by happyfeetw** [comment]
Finally I managed to find that what I want is just there called data-query-protocol, but thanks for your reply anyway. :)
