### ISSUE TITLE
[Python] provide a wrapper script to initiate the Python agent without code changes in user app

### ISSUE THREAD

**Issue by ZhouWlnd** [apache/skywalking#7381]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Question
- What do you want to know?
Now java can use non-invasive way to use skywalking, such as : 
`java -jar $JAVA_AGENT -jar lab-39-demo-2.2.2.RELEASE.jar`

But python needs to add code to the original project， such as：
```
from skywalking import agent, config

config.init(collector_address='127.0.0.1:11800', service_name='your awesome service')
agent.start()
```
How does python use skywalking in a non-intrusive way like java？

**Comment by kezhenxu94** [comment]
For now, this is the only way to use Python agent, non-intrusive way needs some wrapper script to wrap the Python interpreter, if you're interested in contributing we can discuss.

**Comment by wu-sheng** [comment]
Is this possible in theory?

**Comment by kezhenxu94** [comment]
> Is this possible in theory?

It's possible

**Comment by Superskyyy** [comment]
I'm quite interested in this one, could you elaborate a bit more on how this can be achieved? @kezhenxu94

**Comment by kezhenxu94** [comment]
> I'm quite interested in this one, could you elaborate a bit more on how this can be achieved? @kezhenxu94

@Superskyyy thanks for your interest, the basic idea is to write a command line tool (in Python language, for example, named `sw-python`) and start the SkyWalking Python agent first, then start the user-app command, e.g. `sw-python app.py`, or `sw-python gunicorn myproject.wsgi`, or `sw-python django ......`, etc.

I haven't had a chance to look into the details but the following might be a start point:

```python
import os
import sys

from skywalking import config, agent

if __name__ == '__main__':
    args = sys.argv[1:]

    bin_directory = os.path.dirname(sys.argv[0])

    python_exe = os.path.basename(sys.executable)
    python_exe_path = os.path.join(bin_directory, python_exe)
    if (not os.path.exists(python_exe_path) or
            not os.access(python_exe_path, os.X_OK)):
        python_exe_path = sys.executable

    config.service_name = 'provider'
    config.logging_level = 'DEBUG'
    agent.start()

    os.execl(python_exe_path, python_exe_path, *args)
```

**Comment by Superskyyy** [comment]
Ha I see how it works. I'll first finish the log reporter related work then start implementing this one.

**Comment by Superskyyy** [comment]
Shall we introduce some new user friendly config file for the command-line option to use?

It could be used like the following
`sw-python --config=sw_agent.yaml run your application`

**Comment by kezhenxu94** [comment]
> @kezhenxu94  Shall we introduce some new user friendly config file for the command-line option to use?
> 
> 
> 
> It could be used like the following
> 
> `sw-python --config=sw_agent.yaml run your application` 
> 
> 

We could do that but it's optional because all the configurations can be set via env vars, it's the wrapper script's responsibility to pass the env vars down to the agent.

**Comment by Superskyyy** [comment]
> > @kezhenxu94  Shall we introduce some new user friendly config file for the command-line option to use?
> > It could be used like the following
> > `sw-python --config=sw_agent.yaml run your application`
> 
> We could do that but it's optional because all the configurations can be set via env vars, it's the wrapper script's responsibility to pass the env vars down to the agent.

Got it, will make it optional.

**Comment by Superskyyy** [comment]
After some investigation, I believe a `sitecustomize` script is the right way to go. Using pure `exec*` overrides the whole process thus using a new interpreter instance, thus won't work.

**Comment by kezhenxu94** [comment]
@Superskyyy site module is another option, if it works, I'm totally OK to use it.
