### ISSUE TITLE
something wrong in es index init 

### ISSUE THREAD

**Issue by q82184828** [apache/skywalking#7386]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

- useing skywalking 8.6.0, es6.
- when i visit skywalking-ui topology, get error message "Exception while fetching data (/topo) : null", can't see any data.

___

- What happened?
below is log:
![image](https://user-images.githubusercontent.com/26521260/127418853-fdfcf4f1-68e0-490f-8b51-45a4ec44e3b8.png)

backward, some other error about es index for timed task:
![image](https://user-images.githubusercontent.com/26521260/127418732-2639c43c-e139-4fa6-b66f-e32ed1cdf818.png)

It seems that the ES initialization failed or some data was not generated, so i clear all es index and restart oap and ui, but always error，see es init index list:
sw_metrics-longavg-20210729   
sw_metrics-histogram-20210729 
sw_metrics-sum-20210729       
sw_meter-avg-20210729         
sw_metrics-max-20210729       
sw_metrics-doubleavg-20210729 
sw_ui_template                
sw_metrics-percent-20210729   
sw_metrics-percentile-20210729
sw_metrics-cpm-20210729       
sw_metrics-rate-20210729      
sw_metrics-apdex-20210729

Thank you very much. Looking forward to your reply!

**Comment by wu-sheng** [comment]
I can't see what is going wrong, we run all codes through e2e tests repeatedly, they are all passed.

**Comment by q82184828** [comment]
Is it caused by my wrong configuration?

**Comment by wu-sheng** [comment]
Can't see, never faced this.

**Comment by q82184828** [comment]
oap.yml
![image](https://user-images.githubusercontent.com/26521260/127420137-628e369d-872e-41b5-b325-ae0222aebee2.png)

oap-configmap.yml
![image](https://user-images.githubusercontent.com/26521260/127420298-3a72af8a-dc47-465a-b1ad-a04e3cfd99a3.png)

oap dockerfile
![image](https://user-images.githubusercontent.com/26521260/127420177-a8352106-2b10-4a04-9556-2306f6a01afa.png)

ui.yml
![image](https://user-images.githubusercontent.com/26521260/127420090-57c3c64b-b67d-491e-b9bb-7ae2621f2a58.png)

ui dockerfile
![image](https://user-images.githubusercontent.com/26521260/127420221-2e3c4f9d-f2c5-4755-9fdf-aa559fa76046.png)

agent dockerfile
![image](https://user-images.githubusercontent.com/26521260/127420452-2d3dfd0a-4285-43d8-a339-46c5e9868526.png)

agent config is default.

**Comment by echojun186** [comment]
Hello, did you solve this problem?I also had the same problem

**Comment by XDfield** [comment]
same here

**Comment by userkdg** [comment]
UP!

可以尝试找出异常数据进行删除来解决。目前发现是历史数据问题导致的，暂未发现其他情况导致关系问题。

- 查找，还没来得及看接口逻辑代码，对ES数据存储数据结构还不没了解。直接用UI接口进行查找
``` 
curl --location --request POST 'http://localhost:12800/graphql' \
--header 'Content-Type: application/json; charset=utf-8' \
--data-raw '{
  "query": "query queryData($duration: Duration!, $serviceIds: [ID!]!) {\n  topology: getServicesTopology(duration: $duration, serviceIds: $serviceIds) {\n    nodes {\n      id\n      name\n      type\n      isReal\n    }\n    calls {\n      id\n      source\n      detectPoints\n      target\n    }\n  }}",
  "variables": {
    "serviceIds": [
      "5pWw5o2u5byA5Y+R5pyN5Yqh.1",
      "5pWw5o2u6L+Q57u05pyN5Yqh.1",
      "5bmz5Y+w6YWN572u5pyN5Yqh.1",
      "572R5YWz5pyN5Yqh.1",
      "5pWw5o2u6ZuG5oiQ5pyN5Yqh.1",
      "5rOo5YaM5Lit5b+DKE5hY29zKQ==.1"
    ],
    "duration": {
    // 调整时间范围 筛选出异常关系数据，当然很熟悉ES数据结构和接口逻辑的可以直接查询es数据
      "start": "2024-01-13", 
      "end": "2024-01-17",
      "step": "DAY"
    }
  }
}'
```

- 删除区间内的ES数据
``` 
-- delete
POST  http://localhost:9200/sw_metrics-all-20240110/_delete_by_query
{
  "query": {
    "match": {
      "metric_table": {
        "query": "service_relation_server_side"
      }
    // 增加其他更细化的查询条件，若生产数据。
    }
  }
}
```
