### ISSUE TITLE
Does skywalking support @Trace (java, gradle) annotations on the android side？

### ISSUE THREAD

**Issue by SongXueZhi** [apache/skywalking#7387]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does skywalking support @Trace (java, gradle) annotations on the android side, and manual instrumentation to record the trajectory?

I added the relevant parameters of skywalking agent in VM Options and used @Trace annotation. It behaves normally in the springboot program, but it seems to be unsuccessful on the andriod side (java, gradle).

In fact, there is also  no result in a simple program with only the main method.

Looking forward to your reply!

**Comment by wu-sheng** [comment]
We even don't know whether agent works for Android. No one tested about this. Or for further, I think Android doesn't support agent mode at all, doesn't it?

**Comment by SongXueZhi** [comment]
Okay, thanks for your answer. I may need to conduct more survey on Android. There may be some instrumentation techniques that can be considered.

Anyway, SkyWakling is the best practice of OpenTelemetry, and we are trying to apply SkyWalking to collect traces in a complex system environment, and then further carry out some warning and debugging work on the traces.

For example, the robot system, which contains extremely heterogeneous environment, include various languages (java, c++, python, etc.), protocols (coap, mqtt, etc.), systems (Android, linux, etc.), Even diversified hardware .

Could you please share some suggestions, that will greatly promote our work!

**Comment by wu-sheng** [comment]
Java, c++ and python all have agents. Linux is more about monitoring not tracing.
Protocols don't matter, it relies on the language agent plugins in tracing case.
