### ISSUE TITLE
When using, the front-end UI reports an error

### ISSUE THREAD

**Issue by frankhui521** [apache/skywalking#7388]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS, and JRE?
apache-skywalking-apm-es7-8.6.0.tar.gz  CentOS7.5.1804  java version "1.8.0_181"

- What happened?
I search through the current service on the UI interface, which is easy to get stuck and report errors。
Errors are reported as follows：
TypeError: Cannot read property 'key' of undefined
    at nr (vendors~app.78360fae.js:29)
    at vendors~app.78360fae.js:29
    at S (vendors~app.78360fae.js:29)
    at vendors~app.78360fae.js:29
    at S (vendors~app.78360fae.js:29)
    at vendors~app.78360fae.js:29
    at S (vendors~app.78360fae.js:29)
    at a.__patch__ (vendors~app.78360fae.js:29)
    at a.t._update (vendors~app.78360fae.js:29)
    at a.r (vendors~app.78360fae.js:29)
___
What should I do?

**Comment by wu-sheng** [comment]
It could be caused by duplicate services, which is original ElasticSearch performance issue. Make sure there is no duplicate service in the service traffic index alias. 
Or wait for next 8.7.0 release.

**Comment by frankhui521** [comment]
> It could be caused by duplicate services, which is original ElasticSearch performance issue. Make sure there is no duplicate service in the service traffic index alias.
> Or wait for next 8.7.0 release.

I use elasticsearch-7.13.3-x86_ 64 version. The data directory data of elasticsearch was deleted last Friday. Maybe for this reason, I'll take a look again. Thank you!
