### ISSUE TITLE
Need support trace id export 

### ISSUE THREAD

**Issue by pkxiuluo** [apache/skywalking#7394]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Whether exporter module support  trace 、Segment or their id export ?
Or can we subscribe the messages ?
If has not now , do we have some plan about it?

**Comment by wu-sheng** [comment]
No, we are not going to do that. This feature requires the target system as powerful as SkyWalking OAP cluster, which on most cases is impossible.
If you ask for something, SkyWalking requires your use cases.

**Comment by wu-sheng** [comment]
No, we are not going to do that. This feature requires the target system as powerful as SkyWalking OAP cluster, which on most cases is impossible.
If you ask for something, SkyWalking requires your use cases.
