### ISSUE TITLE
Could not using browser to refresh UI.

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#7397]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- **Which version of SkyWalking, OS, and JRE?**
- Browser: Chrome 92.0.4515.107
- Official demo environment: http://demo.skywalking.apache.org

- **What happened?**
- When using the browser to refresh UI, it returns the `404` error code. If I use UI tabs to switch or refresh it works fine.

**Comment by wu-sheng** [comment]
@JaredTan95 I think you missed this in the webapp tech stack change.

**Comment by JaredTan95** [comment]
I clicked `refresh` button in the chrome browser,  seems no problem.

**Comment by wu-sheng** [comment]
Button works. This means browser level refresh.

**Comment by wu-sheng** [comment]
Such as you are at topology, and use f5 to refresh, 404 found.

**Comment by JaredTan95** [comment]
Okay, I see.

**Comment by wu-sheng** [comment]
We got community report about this too :)
