### ISSUE TITLE
[Java] Java agent fails to report spans finished near the program ending 

### ISSUE THREAD

**Issue by yaojingguo** [apache/skywalking#7404]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
1. SkyWalking 8.4.0. 
2. macOS 10.15.5
3. Oracle JDK 1.8.0_162-b12 

Java agent fails to report spans that finish at the end of the program. go2sky has a similar problem: https://github.com/SkyAPM/go2sky/issues/123

**Comment by wu-sheng** [comment]
I have answered this at https://github.com/SkyAPM/go2sky/issues/123#issuecomment-891823291. Same here. 
We don't do that. An exiting process could include a tracing context, this would never end, and timeout wouldn't help.
