### ISSUE TITLE
[BUG]  Skywalking-nodejs throw error TraceReportClient.js

### ISSUE THREAD

**Issue by vaibhavpatil-symblai** [apache/skywalking#7405]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
-
- [x] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?

Steps 
1 Installed node js 
$ npm install --save skywalking-backend-js
2 Local standalone setup of skywalking server 
https://programming.vip/docs/getting-started-with-skywalking.html - working fine and having all configs in place and UI also working
2 Configure to our APP

**const {default: agent} = require('skywalking-backend-js');
agent.start({
    serviceName: 'my-serv-name-2aug',
    serviceInstance: 'my-serv-name-2aug',
});**

On start found below ERROR 

{
  file: '/Users/MYMACHINE/Desktop/node_modules/skywalking-backend-js/lib/agent/protocol/grpc/clients/TraceReportClient.js',
  code: 2,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: '',
  level: 'error',
  message: 'Failed to report trace data 2 UNKNOWN: ',
  stack: 'Error: 2 UNKNOWN: \n' +
    '    at Object.exports.createStatusError (
    '    at callbackTrampoline (internal/async_hooks.js:134:14)'
}

Thanks Skywalking-nodejs team , excellent plugin but should support all case! 
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
Need to support node JS app and should option to expose custom metrics from CODE

**Comment by kezhenxu94** [comment]
`Error: 2 UNKNOWN:` this gRPC error is very hard to diagnose from our side because it’s even UNKNOWN to gRPC side, so you have to check some basic items, 1. you set the OAP address correctly 2. The network between the OAP and the agent is accessible. 

You can also compare your codes with our tests in the nodejs repo to see what makes it different in your side.

**Comment by vaibhavpatil-symblai** [comment]
Thanks, @kezhenxu94 for your reply we will check the above points and will update you shortly!

**Comment by kezhenxu94** [comment]
> Thanks, @kezhenxu94 for your reply we will check the above points and will update you shortly!

@vaibhavpatil-symblai closing this for now, if you have any new finding, please reply here or open a new issue
