### ISSUE TITLE
[Trace] Integration with OAP

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#7412]
This task intends to link OAP to banyandb based on the[ interaction API ](https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/v1/rpc.proto).

Since the banyandb only supports trace data for now, we should:

 * create a branch, named `banyandb-integration` in main repo.
 * add a new storage module named `banyandb`.
 * send trace data to banyandb in the new module, while sending reset data to h2.

^^^ @wu-sheng anythings else should be included?

**Comment by lujiajing1126** [comment]
Pls assign to me.

**Comment by wu-sheng** [comment]
@hanahmily I think @lujiajing1126 is not able to create an official branch. You need to create for him.

To @lujiajing1126, as the SkyWalking master branch only accepts `squash merge`(when we do `banyandb-integration` to `master`), the final status of this feature could only be counted as one commit of you. Is that a concern for you? It is totally understandable if you want that statistic being kept. Please let me know.

**Comment by lujiajing1126** [comment]
> @hanahmily I think @lujiajing1126 is not able to create an official branch. You need to create for him.
> 
> To @lujiajing1126, as the SkyWalking master branch only accepts `squash merge`(when we do `banyandb-integration` to `master`), the final status of this feature could only be counted as one commit of you. Is that a concern for you? It is totally understandable if you want that statistic being kept. Please let me know.

The squash merge is totally ok for me.

**Comment by wu-sheng** [comment]
Branch created, https://github.com/apache/skywalking/tree/banyandb-integration

**Comment by hanahmily** [comment]
We have finished the first round of integration. I will open another issue to track current work.
