### ISSUE TITLE
service_cpm = sum( service_instance_cpm )  ?

### ISSUE THREAD

**Issue by klmzfyf** [apache/skywalking#7413]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- What do you want to know?
excuse me.
does service_cpm = sum( service_instance_cpm )  ?
in my case, service_cpm !=  sum( service_instance_cpm ) .

**Comment by wu-sheng** [comment]
Generally, they should match, but if the traffic is too little, it could mismatch.
The real matching thing is traffic_count(not set in OAL, but logically you can). 

CPM = calls / duration.
Such as in hour-level metrics, you at least need 60 calls per hour could have 1 CPM.

**Comment by klmzfyf** [comment]
> Generally, they should match, but if the traffic is too little, it could mismatch.
> The real matching thing is traffic_count(not set in OAL, but logically you can).
> 
> CPM = calls / duration.
> Such as in hour-level metrics, you at least need 60 calls per hour could have 1 CPM.

thank, Professor Wu
