### ISSUE TITLE
Information on Openapi based Endpoint Grouping

### ISSUE THREAD

**Issue by onurccn** [apache/skywalking#7414]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [  ] Bug
- [  ] Requirement
- [  ] Feature or performance improvement

___
### Question
- What do you want to know?
1 - Are there any limits on openapi yaml files? I have used EndpointGroupingRuleReader4OpenapiTest and that class does not load my openapi definition which is over 3000 lines. I figured checkstyle is limiting the definition file limits. Can i increase these values via ENV variable? 

2 - I couldn't tell if skywalking-server correctly loaded my openapi file or not based on logs. I think there should be logging if no file loaded etc.

3 - getGroupRegex method does not care for statically added server context paths. (For example endpoint is /records but server is setup as /api/records). This information usually goes to servers.url in openapi definition (server.url being '/api' in this case). Should we consider such setup?

**Comment by wu-sheng** [comment]
> What do you want to know?
1 - Are there any limits on openapi yaml files? I have used EndpointGroupingRuleReader4OpenapiTest and that class does not load my openapi definition which is over 3000 lines. I figured checkstyle is limiting the definition file limits. Can i increase these values via ENV variable?

I think we don't limit size, and checkstyle is only working for IDE, rather than runtime. Could you share more about this?

> 2 - I couldn't tell if skywalking-server correctly loaded my openapi file or not based on logs. I think there should be logging if no file loaded etc.

Welcome to send a pull request to enhance this. This is a new feature, we are glad to see the feedback.

> 3 - getGroupRegex method does not care for statically added server context paths. (For example endpoint is /records but server is setup as /api/records). This information usually goes to servers.url in openapi definition (server.url being '/api' in this case). Should we consider such setup?

We should consider that. Do you have anything to pull request?

**Comment by onurccn** [comment]
Firstly, thanks for the quick reply!

> > What do you want to know?
> > 1 - Are there any limits on openapi yaml files? I have used EndpointGroupingRuleReader4OpenapiTest and that class does not load my openapi definition which is over 3000 lines. I figured checkstyle is limiting the definition file limits. Can i increase these values via ENV variable?
> 
> I think we don't limit size, and checkstyle is only working for IDE, rather than runtime. Could you share more about this?

Its good to hear that its not applied on runtime. I have placed my openapi file under openapi-definitions folder within project and run tests from IDE, that explains why i couldnt load my file in the first place.

Also I couldn't run tests with openapi-defitinions folder outside project path. (ex. /tmp/openapi-definitions). ClassLoader cant reach that location. Maybe this is happening on runtime as well. Because i think i cant get i to load my yaml files. Glad to provide more detailed feedback if you direct me how to get them.

I will try to open a pull request for improvements whenever i can.

**Comment by wankai123** [comment]
> Firstly, thanks for the quick reply!
> 
> > > What do you want to know?
> > > 1 - Are there any limits on openapi yaml files? I have used EndpointGroupingRuleReader4OpenapiTest and that class does not load my openapi definition which is over 3000 lines. I figured checkstyle is limiting the definition file limits. Can i increase these values via ENV variable?
> > 
> > 
> > I think we don't limit size, and checkstyle is only working for IDE, rather than runtime. Could you share more about this?
> 
> Its good to hear that its not applied on runtime. I have placed my openapi file under openapi-definitions folder within project and run tests from IDE, that explains why i couldnt load my file in the first place.
> 
> Also I couldn't run tests with openapi-defitinions folder outside project path. (ex. /tmp/openapi-definitions). ClassLoader cant reach that location. Maybe this is happening on runtime as well. Because i think i cant get i to load my yaml files. Glad to provide more detailed feedback if you direct me how to get them.
> 
> I will try to open a pull request for improvements whenever i can.

Did you put the openapi file under `skywalking/oap-server/server-core/src/test/resources/openapi-definitions` ? If you run a test you need to put it under the test resources, not the project root resources. There are also some samples under test resources.

**Comment by wu-sheng** [comment]
> Also I couldn't run tests with openapi-defitinions folder outside project path. (ex. /tmp/openapi-definitions).

That is not SkyWalking's codes are designed for.  Please read @wankai123 's comments. Could you share a little about why you want the codes running outside? Are you trying to integrate it somewhere else?

**Comment by onurccn** [comment]
> > Also I couldn't run tests with openapi-defitinions folder outside project path. (ex. /tmp/openapi-definitions).
> 
> That is not SkyWalking's codes are designed for. Please read @wankai123 's comments. Could you share a little about why you want the codes running outside? Are you trying to integrate it somewhere else?

Actually, I do not. I'm just trying to get it working on runtime. I thought it might be related with my openapi definitions folder location.

**Comment by wankai123** [comment]
where did you put it?  you can try to put it under `config/openapi-definitions` if you can't found the folder `openapi-definitions` under `config`, try to create one by yourself.

**Comment by onurccn** [comment]
> where did you put it? you can try to put it under `config/openapi-definitions` if you can't found the folder `openapi-definitions` under `config`, try to create one by yourself.

Yeah currently it is located there.
