### ISSUE TITLE
the apm ignore  plugin not work!!!!!!!

### ISSUE THREAD

**Issue by apple987** [apache/skywalking#7418]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
why this plugin not work?
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?

current version 8.7.0.RELEASE,Configure the plug-in according to the official documentation,like this:
1.copy the apache-skywalking-apm-bin\agent\optional-plugins\apm-trace-ignore-plugin-8.7.0.jar to directory apache-skywalking-apm-bin\agent\plugins\
2.create the file 
[Uploading apm-trace-ignore-plugin.zip…]()
3.spring boot start with the angent config:-javaagent:D:\\apache-skywalking-apm-bin\\agent\\skywalking-agent.jar  SW_AGENT_NAME=boot;SW_AGENT_COLLECTOR_BACKEND_SERVICES=127.0.0.1:11800
4.check the skywalking ui trace page like this:
![1628399014(1)](https://user-images.githubusercontent.com/21330215/128621439-4adbb992-0d33-4a6e-b446-c5061d63cde1.jpg)

when switch only the skywalking to version 6.6.0.RELEASE,the apm-ignore plugin works well! is there any change for this plguin?need help thanks!!!

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Why so many exclamation points? Why do you do like this?
Be polite is the 1st thing in a community.

**Comment by apple987** [comment]
Sorry, it's urgent

**Comment by wu-sheng** [comment]
Urgent is for you, not for community. This is not customer-provider commercial service.
The community is only a place people working together when they have time.

**Comment by wu-sheng** [comment]
We have this plugin test case, you could check on your own.
