### ISSUE TITLE
Add plugin for Tomcat 10(Jakarta)

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7420]
## Background of Tomcat 10
Users of Tomcat 10 onwards should be aware that, as a result of the move from Java EE to Jakarta EE as part of the transfer of Java EE to the Eclipse Foundation, the primary package for all implemented APIs has changed from javax.* to jakarta.*. This will almost certainly require code changes to enable applications to migrate from Tomcat 9 and earlier to Tomcat 10 and later.

Because this chaos in the J2EE ecosystem, we need a separate plugin for Tomcat 10 and ecosystem round it. Potentially need new plugin for SpringMVC as it had embed Tomcat in the future. Be careful when someone does this.

**Comment by Kritip123** [comment]
There is nothing to work on this issue right?

**Comment by wu-sheng** [comment]
> There is nothing to work on this issue right?

No, this is just an issue to track. Do you want to contribute this?

**Comment by Kritip123** [comment]
> > There is nothing to work on this issue right?
> 
> No, this is just an issue to track. Do you want to contribute this?

Actually, I am new to Open-source. Saw it was a good first issue, so asked if I had anything to do with this issue. I am really ambitious to start contributing to this project. Could you guide me on which one to start with? And can I contribute to this issue?

**Comment by wu-sheng** [comment]
If this is your first time, it is better to use slack for more general talking. And try to do quick start first.

**Comment by Kritip123** [comment]
> If this is your first time, it is better to use slack for more general talking. And try to do quick start first.

Sure I am looking forward to it. How can I get the link for it?

**Comment by wu-sheng** [comment]
Project readme and website both have it.

**Comment by Kritip123** [comment]
Sir, its saying "someone already part of the workspace needs to invite the interested party or parties". Otherwise I am not able to join.

**Comment by wu-sheng** [comment]
> Sir, its saying "someone already part of the workspace needs to invite the interested party or parties". Otherwise I am not able to join.

I send the invitation according to your GitHub profile's mail. Please check.

**Comment by Kritip123** [comment]
Thank you. Hope to have a great experience working with you.

**Comment by Kritip123** [comment]
> > Sir, its saying "someone already part of the workspace needs to invite the interested party or parties". Otherwise I am not able to join.
> 
> I send the invitation according to your GitHub profile's mail. Please check.

Thank you. Hope to have a great experience working with you.

**Comment by deepto98** [comment]
@wu-sheng Is this issue still open? If so, can I try this out? I'm new to the project, so can you point me to some resources to get started on this task?

**Comment by wu-sheng** [comment]
Yes, this is still open. 
You first should understand how Java agent works, and tracing basic idea(Google dapper paper).
After that, plugin development and testing docs, and take a reference from existing Tomcat 8 plugin.

**Comment by deepto98** [comment]
Okay, thanks. I'll start on this and reach out if I'm stuck

**Comment by deepto98** [comment]
@wu-sheng Can you also point me to the Tomcat 8 plugin directory?

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-java/tree/main/apm-sniffer/apm-sdk-plugin/tomcat-7.x-8.x-plugin

This is the latest.

**Comment by shankeerthan-kasilingam** [comment]
Hi @wu-sheng,
If it's still open, Can I give it a try?

**Comment by wu-sheng** [comment]
Yes, this is still open. Welcome to contribute.

**Comment by wutingjia** [comment]
Hi @wu-sheng , I’m a bit hard to understand doc [https://github.com/apache/skywalking-java/blob/main/docs/en/setup/service-agent/java-agent/Plugin-test.md] when  I want to create test. It has not obvious step what should I do. 

step0 Environment Requirements
step1 `bash ${SKYWALKING_HOME}/test/plugin/generator.sh`
step2 Adjust the code like  **tomcat-thread-pool-scenario** ？（l can not find tests like tomcat-78x-scenario）
step3  bash ./test/plugin/run.sh -f ${scenario_name}
step4 upload to GitHub Actions Job

Is that right ？or need other steps？

**Comment by wu-sheng** [comment]
First of all, this task could run locally. Adding to GHA is easy like this https://github.com/apache/skywalking-java/blob/main/.github/workflows/plugins-test.1.yaml or other plugins-test YMALs.

**Comment by wu-sheng** [comment]
This is plugin test dev doc, https://skywalking.apache.org/docs/skywalking-java/v8.9.0/en/setup/service-agent/java-agent/plugin-test/

**Comment by wutingjia** [comment]
> This is plugin test dev doc, https://skywalking.apache.org/docs/skywalking-java/v8.9.0/en/setup/service-agent/java-agent/plugin-test/

yeah I have seen this doc. So I raised the above question. Your answer teach me how to do `step4 upload to GitHub Actions Job` but still not solve my main confuse . The specific steps of test what I mentioned above is right or omit something? That doc emphasis on how to config parameters in tests, but have not a clear flow. So it may difficult for beginners to understand（like me）

**Comment by wu-sheng** [comment]
I am not sure about other questions. Are you facing issues about step 3(local run)? It could be easier to help you.

**Comment by wutingjia** [comment]
> I am not sure about other questions. Are you facing issues about step 3(local run)? It could be easier to help you.

ok I'll look into it myself and get back to you if I have any questions

**Comment by wu-sheng** [comment]
Sure, just follow the steps of that doc, and make sure tests pass locally. The GHA is simple.

**Comment by wutingjia** [comment]
when run an existing feign-scenario test with `bash ./test/plugin/run.sh -f ${scenario_name}` the docker log likes following：

[2022-03-01 07:12:32:057] [ERROR] - org.apache.skywalking.plugin.test.agent.tool.Main.verify(Main.java:53) - 
assert failed.
SegmentItemNotFoundException
expected: feign-scenario
actual: Not Found

What preparations have I missed ？

**Comment by wu-sheng** [comment]
This error means no `segment` reported, all cases could pass on Linux or Intel Mac.(At least my M1 mac can't run this for now)

**Comment by wutingjia** [comment]
I use Intel Mac and try another existing test，but result is the same. Does anyone know why ?

<details>
<summary>detail log</summary>

To start mock collector
http://localhost:12800/receiveData: HTTP/1.1 200
Mar 01, 2022 7:56:18 AM org.apache.skywalking.testcase.httpclient5.Httpclient5Application logStarting
INFO: Starting Httpclient5Application on 1d14d6e43c9e with PID 54 (/run/httpclient-5.x-scenario/libs/httpclient-5.x-scenario.jar started by root in /usr/local/skywalking/scenario)
Mar 01, 2022 7:56:18 AM org.apache.skywalking.testcase.httpclient5.Httpclient5Application logStartupProfileInfo
INFO: No active profile set, falling back to default profiles: default
Mar 01, 2022 7:56:18 AM org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext prepareRefresh
INFO: Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1c25b8a7: startup date [Tue Mar 01 07:56:18 GMT 2022]; root of context hierarchy
Mar 01, 2022 7:56:20 AM org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer initialize
INFO: Tomcat initialized with port(s): 8080 (http)
Mar 01, 2022 7:56:20 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Mar 01, 2022 7:56:20 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.23
Mar 01, 2022 7:56:20 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring embedded WebApplicationContext
Mar 01, 2022 7:56:20 AM org.springframework.web.context.ContextLoader prepareEmbeddedWebApplicationContext
INFO: Root WebApplicationContext: initialization completed in 1609 ms
Mar 01, 2022 7:56:20 AM org.springframework.boot.web.servlet.ServletRegistrationBean onStartup
INFO: Mapping servlet: 'dispatcherServlet' to [/]
Mar 01, 2022 7:56:20 AM org.springframework.boot.web.servlet.FilterRegistrationBean configure
INFO: Mapping filter: 'characterEncodingFilter' to: [/*]
Mar 01, 2022 7:56:20 AM org.springframework.boot.web.servlet.FilterRegistrationBean configure
INFO: Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
Mar 01, 2022 7:56:20 AM org.springframework.boot.web.servlet.FilterRegistrationBean configure
INFO: Mapping filter: 'httpPutFormContentFilter' to: [/*]
Mar 01, 2022 7:56:20 AM org.springframework.boot.web.servlet.FilterRegistrationBean configure
INFO: Mapping filter: 'requestContextFilter' to: [/*]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Mar 01, 2022 7:56:20 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter initControllerAdviceCache
INFO: Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1c25b8a7: startup date [Tue Mar 01 07:56:18 GMT 2022]; root of context hierarchy
Mar 01, 2022 7:56:21 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping register
INFO: Mapped "{[/httpclient-5.x/back],methods=[GET]}" onto public java.lang.String org.apache.skywalking.testcase.httpclient5.BackController.back()
Mar 01, 2022 7:56:21 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping register
INFO: Mapped "{[/httpclient-5.x/case/healthcheck],methods=[GET]}" onto public java.lang.String org.apache.skywalking.testcase.httpclient5.FrontController.healthcheck()
Mar 01, 2022 7:56:21 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping register
INFO: Mapped "{[/httpclient-5.x/case/asyncGet],methods=[GET]}" onto public java.lang.String org.apache.skywalking.testcase.httpclient5.FrontController.asyncGet() throws java.lang.Exception
Mar 01, 2022 7:56:21 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping register
INFO: Mapped "{[/httpclient-5.x/case/get],methods=[GET]}" onto public java.lang.String org.apache.skywalking.testcase.httpclient5.FrontController.get() throws java.lang.Exception
Mar 01, 2022 7:56:21 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping register
INFO: Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
Mar 01, 2022 7:56:21 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping register
INFO: Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
Mar 01, 2022 7:56:21 AM org.springframework.web.servlet.handler.SimpleUrlHandlerMapping registerHandler
INFO: Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
Mar 01, 2022 7:56:21 AM org.springframework.web.servlet.handler.SimpleUrlHandlerMapping registerHandler
INFO: Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
Mar 01, 2022 7:56:21 AM org.springframework.web.servlet.handler.SimpleUrlHandlerMapping registerHandler
INFO: Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
Mar 01, 2022 7:56:21 AM org.springframework.jmx.export.annotation.AnnotationMBeanExporter afterSingletonsInstantiated
INFO: Registering beans for JMX exposure on startup
Mar 01, 2022 7:56:21 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Mar 01, 2022 7:56:21 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
Mar 01, 2022 7:56:21 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Mar 01, 2022 7:56:21 AM org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer start
INFO: Tomcat started on port(s): 8080 (http)
Mar 01, 2022 7:56:21 AM org.apache.skywalking.testcase.httpclient5.Httpclient5Application logStarted
INFO: Started Httpclient5Application in 3.863 seconds (JVM running for 7.179)
Mar 01, 2022 7:56:22 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring FrameworkServlet 'dispatcherServlet'
Mar 01, 2022 7:56:22 AM org.springframework.web.servlet.DispatcherServlet initServletBean
INFO: FrameworkServlet 'dispatcherServlet': initialization started
Mar 01, 2022 7:56:22 AM org.springframework.web.servlet.DispatcherServlet initServletBean
INFO: FrameworkServlet 'dispatcherServlet': initialization completed in 14 ms
http://127.0.0.1:8080/httpclient-5.x/case/healthcheck: HTTP/1.1 200
To visit entry service
Hello backTo receive actual data
To validate
[2022-03-01 07:56:28:273] [ERROR] - org.apache.skywalking.plugin.test.agent.tool.Main.verify(Main.java:53) - 
assert failed.
SegmentItemNotFoundException
expected: httpclient-5.x-scenario
actual: Not Found

segmentItems: []
meterItems: []
[ERROR] Scenario[httpclient-5.x-scenario-5.0] failed!
/Users/wutingjia/IdeaProjects/skywalking-java/test/plugin/workspace/httpclient-5.x-scenario/5.0/scenario.sh: line 57: /Users/wutingjia/IdeaProjects/skywalking-java/test/plugin/workspace/httpclient-5.x-scenario/5.0/logs/container.log: No such file or directory

</details>
In this case，I am difficult to write my own tests with reference 😭

**Comment by wu-sheng** [comment]
I just run ` bash ./test/plugin/run.sh -f feign-scenario` on Linux(Intel) ubuntu 20, it passed without any issue. And I could pass tests in 2021 on Mac when I had an Intel-based MacOS.

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/5441976/156131000-bdeb1471-f650-4734-8405-2d8e084354a2.png">

**Comment by wutingjia** [comment]
> How are you using Tomcat? Could you share? I guess you are using some specific Spring versions?

I  use tomcat like this:
```
Tomcat tomcat = new Tomcat();
 Connector con = new Connector();
 con.setPort(18080);
....
tomcat.start();
```
beacuse I can not find tomcat trace test only can find meter test，so I reference the jetty plugin trace test.
Also I see in the webflux plugin test there is the param `withPlugins` in the configuration.yaml. I guess I can use this param to choose specify version plugin ？

**Comment by wutingjia** [comment]
Sorry, I can't understand  1 very well 😭，could you  give me more detailed information? Do you mean I should use spring as a server framework（replace the embedded tomcat version）to test instead of tomcat only ？

For 3 I've already done that. But what I really mean is if there are two plugins(like tomcat78、tomcat10),they enhance the same method，how test framework know which plugin should be choose ?

**Comment by wu-sheng** [comment]
If you can't follow (1), ignore it. That is just an option.

(3) It is not determined by test framework. You could check witness class and witness method for plugin instrumentation definition. The plugin [dev doc](https://skywalking.apache.org/docs/skywalking-java/v8.9.0/en/setup/service-agent/java-agent/java-plugin-development-guide/#implement-plugin) includes this, step 4.

**Comment by wutingjia** [comment]
ok，for 3 I got it.

for 1 do you mean that beacuse of tomcat-container uses tomcat:8.5-jdk8-openjdk, tomcat:8.5-jdk14-openjdk or tomcat:8.5-jdk17-openjdk image ，not include tomcat 10.x，and this week tomcat 10.x image is planned to be added,
so I should use jvm container image? That's what I did if that's what you meant.

so In fact I used jvm-container  and tomcat only（without spring）to build server serivce， is that right ?

**Comment by wu-sheng** [comment]
Yes, that is my (1) means. That could be added later. 

Tomcat in dependency and Tomcat as container likr (1) have different class loader path. That is why we provide 2 ways for you. Once @dmsolr added, you could have 2 plugin test cases. Before that, follow your current way.

**Comment by wutingjia** [comment]
Is there any way that starting tomcat with java agent in IDEA (no VM options)so that I can breakpoint debugger like springboot service ?

**Comment by wu-sheng** [comment]
Do you want to debug the agent plugin? I guess you could read a Chinese blog? https://skywalking.apache.org/zh/2019-01-24-skywalking-remote-debug/ Remote debug is the recommended way to debug in agent case.

**Comment by wutingjia** [comment]
> Do you want to debug the agent plugin? I guess you could read a Chinese blog? https://skywalking.apache.org/zh/2019-01-24-skywalking-remote-debug/ Remote debug is the recommended way to debug in agent case.

Earlier, I learn a way to debug agent without remote debug，to set `VM options`(-javaagent) In IDEA and open agent module and test module in the same project. In that way I even can debug the code in `premain` method
But it seems only available for spring service，tomcat application can not set VM options。If using remote debug , I can only debug the code in some **uninitialized logic** like `beforeMethod` is that right?

**Comment by wu-sheng** [comment]
Remote debug is open to all cases. Do you need to verify some special cases? I think the Tomcat plugin doesn't require this complex case.
There is a setting in remote debug, `suspend=Y` could make the target service wait for your agent attachment.

**Comment by wutingjia** [comment]
> 

thanks~ I will try it

**Comment by wutingjia** [comment]
Sorry to bother again，I am now in a situation like this：I think that I have already enhanced some method like tomcat78 through debug `AbstractClassEnhancePluginDefine` and `ClassEnhancePluginDefine` They all found  my instrumentation normally and enhance it，like this:

![8620732217524cf1741e0e2c03709be](https://user-images.githubusercontent.com/33154970/156766101-20fbf277-a638-40e3-a2c0-3d324b1a5fbc.jpg)

but when I take a request the breakpoint in the `beforeMethod` is not be executed.
Could you tell me what this might be? Or how should it be checked?

**Comment by wu-sheng** [comment]
Then it may be caused by the method not matching. This debug only shows your class declaration works.

**Comment by wu-sheng** [comment]
And make sure Tomcat78 plugin doesn't override you, make sure your witness class and method works correctly too.

**Comment by wutingjia** [comment]
I find the real reason is that the class in the classloader is still verison9,so witness‘s result is reverse 
![1455f13e5edcfda6e154f0471e17003](https://user-images.githubusercontent.com/33154970/156780176-6b75be05-c13b-4fa7-a2d5-eaffec26236b.jpg)

but my dependencies are verison10:
![1da616d8bbfd7af8148176b29896e73](https://user-images.githubusercontent.com/33154970/156780351-fa6a48df-1a0f-4a31-9b5d-523bcac92d08.jpg)

I don't know why there is such a confusing situation

But even then it should take effect，because the `StandardHostValue#invoke` 's method signature has not changed

**Comment by wu-sheng** [comment]
> I don't know why there is such a confusing situation

Check you tar ball, maybe you package things wrong.

> But even then it should take effect，because the StandardHostValue#invoke 's method signature has not changed

If class name and method name are both unchanged, tomcat78 plugin will conflict with tomcat9 plugin. Those two interceptors will only take effects one randomly according to the runtime sequence.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-java/pull/122 adds compatibility to run test war app in different Tomcat. Thanks to @dmsolr

**Comment by yswdqz** [comment]
Is it still open? I want to try it。

**Comment by wu-sheng** [comment]
Yes, it is still open. I didn't have update.

**Comment by Superskyyy** [comment]
> Is it still open? I want to try it。

Would you like us to assign this one to you?

**Comment by yswdqz** [comment]
Yes, I will do my best to resolve it.

**Comment by Superskyyy** [comment]
Okay, assigned to you, good luck coding.
