### ISSUE TITLE
v8.3.0 modify recordDataTTL ,but  it dose not work ;

### ISSUE THREAD

**Issue by wangshuo-dota** [apache/skywalking#7421]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ 1] Question or discussion

___
### Question
- What do you want to know?
- To midify es7 storage record data time, change recordDataTTL  from 3 to 7. After skywalking restart, it does not work out;
- want to know why
![企业微信截图_16284793917310](https://user-images.githubusercontent.com/53133870/128657778-0f636431-3518-42ec-aeb1-e48b685d8b92.png)
![企业微信截图_16284792975213](https://user-images.githubusercontent.com/53133870/128657781-7f34ce36-c7f7-49f6-bf87-cd32abf1ec6a.png)

 

- Which version of SkyWalking, OS, and JRE?
skywalking v8.3.0
es 7

**Comment by wu-sheng** [comment]
8.3.0 is too old to track, read the changelog.
