### ISSUE TITLE
[NGINX-LUA] can't find service in UI

### ISSUE THREAD

**Issue by huangmingyou** [apache/skywalking#7422]
config a nginx agent with the example nginx.conf;
use tcpdump capther network package found the 
nginx post  a /v3/segments to the skywalking oap server.
the server respons http 200 ok and data is "{}"

and the nginx post "/v3/management/keepAlive" to server.

but , when search the service in the UI , can't find the service?

the skywalking service run in a k8s cluseter , install with helm ,
how open the debug in log4j.xml ?

**Comment by wu-sheng** [comment]
Check timezone as we highlighted in the first line of deployment doc.
