### ISSUE TITLE
How to decode the data_binary in the table segment

### ISSUE THREAD

**Issue by PerezYuan** [apache/skywalking#7423]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- How to decode the data_binary in the table segment. When I use base64 utf-8 decode, the value has something like this ᘜ磲/ ݴ磲

CjViODZmOGE3NThlZTg0YjE3OGUzNmI0N2Y2NWFmZTJlYi40Ny4xNjI4NDA0NjAyMzQxMDAwMRI1NzVhYzRmMzU2N2U0NGViNjkxNTkwMjgxNmNjMTE2M2IuNDQuMTYyODQwNDU3ODc4MDAwMDAaiAIIARjc9Oejsi8g3fTno7IvMmFjb20uZXhhbXBsZS5kZW1vcHJvdmlkZXIucHJvdmlkZXIuSGVsbG9TZXJ2aWNlSW1wbCRQcmVmaXhGdW5TdGF0aWMuYmVmb3JlU3RhdGljKGphdmEubGFuZy5TdHJpbmcpQAJiGQoIbmFtZXRydWUSDWhlbGxvMTExITY2Nzdqdgjc9Oejsi8SbQoIbXRzdGF0aWMSYWNvbS5leGFtcGxlLmRlbW9wcm92aWRlci5wcm92aWRlci5IZWxsb1NlcnZpY2VJbXBsJFByZWZpeEZ1blN0YXRpYy5iZWZvcmVTdGF0aWMoamF2YS5sYW5nLlN0cmluZykaiAIIAxACGOT056OyLyDk9Oejsi8yXmNvbS5leGFtcGxlLmRlbW9wcm92aWRlci5wcm92aWRlci5IZWxsb1NlcnZpY2VJbXBsJFByZWZpeEZ1bi5iZWZvcmVTYXlIZWxsbzIoamF2YS5sYW5nLlN0cmluZylAAmIaCgluYW1lZmFsc2USDWhlbGxvMTExITY2Nzdqdgjk9Oejsi8SbQoLbXRub25zdGF0aWMSXmNvbS5leGFtcGxlLmRlbW9wcm92aWRlci5wcm92aWRlci5IZWxsb1NlcnZpY2VJbXBsJFByZWZpeEZ1bi5iZWZvcmVTYXlIZWxsbzIoamF2YS5sYW5nLlN0cmluZykahAIIAhjk9Oejsi8g5PTno7IvMl1jb20uZXhhbXBsZS5kZW1vcHJvdmlkZXIucHJvdmlkZXIuSGVsbG9TZXJ2aWNlSW1wbCRQcmVmaXhGdW4uYmVmb3JlU2F5SGVsbG8oamF2YS5sYW5nLlN0cmluZylAAmIaCgluYW1lZmFsc2USDWhlbGxvMTExITY2NzdqdQjk9Oejsi8SbAoLbXRub25zdGF0aWMSXWNvbS5leGFtcGxlLmRlbW9wcm92aWRlci5wcm92aWRlci5IZWxsb1NlcnZpY2VJbXBsJFByZWZpeEZ1bi5iZWZvcmVTYXlIZWxsbyhqYXZhLmxhbmcuU3RyaW5nKRpkCAQY6/Tno7IvIOv056OyLzJQY29tLmV4YW1wbGUuZGVtb3Byb3ZpZGVyLnByb3ZpZGVyLkhlbGxvQnlIdHRwU2VydmljZSRQcmVmaXhGdW4uYmVmb3JlU2F5SGVsbG82KClAAhrIAhD///////////8BGN3z56OyLyCP9eejsi8q1AESNWI4NmY4YTc1OGVlODRiMTc4ZTM2YjQ3ZjY1YWZlMmViLjQ3LjE2Mjg0MDQ2MDIzNDEwMDAxGjViODZmOGE3NThlZTg0YjE3OGUzNmI0N2Y2NWFmZTJlYi40Ny4xNjI4NDA0NjAyMzQxMDAwMCADKhJkZW1vLWh0dHAtY29uc3VtZXIyK2JkN2RiMDMzNjJlZDRmNWQ4ODMwM2Y4MjAxY2RlNzgzQDE3Mi4yMS4wLjE6Dy9zYXlIZWxsb0J5SHR0cEIQMTAuMjAuMS4xNzc6ODg5MDIPL3NheUhlbGxvQnlIdHRwSANQDmItCgN1cmwSJmh0dHA6Ly8xMC4yMC4xLjE3Nzo4ODkwL3NheUhlbGxvQnlIdHRwYhIKC2h0dHAubWV0aG9kEgNHRVQiEmRlbW8taHR0cC1wcm92aWRlciorNGUyZDRlM2UxMGEzNGI4NzhkYTg2NDNhN2E4MWE1NTZAMTcyLjE4LjAuMQ==

Thank you

**Comment by wu-sheng** [comment]
We have provided the source codes. You should read by yourself.

**Comment by PerezYuan** [comment]
I see the dependency in the apm-network parseFrom. Now it works, thank you very much.
