### ISSUE TITLE
请问FollowsFrom是什么意思，是指span之间是父子关系还是兄弟关系吗？

### ISSUE THREAD

**Issue by JiCoM** [apache/skywalking#7433]
Q1：请问FollowsFrom是什么意思，是指span之间是父子关系还是兄弟关系吗？
Q2: 请问spanID，为什么不采取1.1，1.1.2，1.1.2.1这样的设计，这也可以节约一个parentID字段

**Comment by wu-sheng** [comment]
English is required for global people. This isn't the thing we should answer.
