### ISSUE TITLE
[Python] Whether the agent intend to support Python2 in the near future

### ISSUE THREAD

**Issue by liangWenPeng** [apache/skywalking#7437]
Since many older projects are based on Python2, it is desirable to provide a Python2  agent.

**Comment by wu-sheng** [comment]
I think we have passed that for a long time. Sorry.

**Comment by kezhenxu94** [comment]
> Since many older projects are based on Python2, it is desirable to provide a Python2 agent.

Python2 is end of life for a long time, we have no plan to support that
