### ISSUE TITLE
why slow statements doesn't support the detail info

### ISSUE THREAD

**Issue by jackmiking** [apache/skywalking#7447]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
why slow statements doesn't support the detail info
___
### Bug
- Which version of SkyWalking, OS, and JRE?
 skywalking version is 8.5.0,jre is openjdk11. os is linux.

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- could it show the detail query or the table name.
-
![image](https://user-images.githubusercontent.com/7358173/129148313-68b5ac0a-63cc-4743-a3e0-3ef4603d40b5.png)

**Comment by wu-sheng** [comment]
This depends on how agent collects data. Some of the request are too big to collecting. Read the plugin source codes, you will know.
