### ISSUE TITLE
question about using  the HTTP1.1  to send a single segment object in JSON format

### ISSUE THREAD

**Issue by chenzhao11** [apache/skywalking#7453]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
SW version : 8.6.0
HI  ,  I want to send a single segment object in JSON format  to the  OAP follows the document. However when I use postman to post the data  the UI only shows the ServiceName，the uploaded segment is not shown in the trace.   Did I  miss something？thanks in advance  
       (https://skywalking.apache.org/docs/main/v8.6.0/en/protocols/http-api-protocol/#post-httplocalhost12800v3segment)
![image](https://user-images.githubusercontent.com/37374154/129301478-0e1711ba-a0be-4887-b679-9a76b5f51dc2.png)
![image](https://user-images.githubusercontent.com/37374154/129301542-751736df-8659-4705-bde3-b214a957b926.png)

**Comment by wu-sheng** [comment]
If you are playing protocol, read the source codes. This is a very advanced integration.

**Comment by chenzhao11** [comment]
ok, thanks for your reply
