### ISSUE TITLE
the design of storage log in dataBase

### ISSUE THREAD

**Issue by qiuhuanhen** [apache/skywalking#7456]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [√ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
-  (First of all, I'm sorry for I submit the issue again because it's seems I don't make myself clear before ,and now I try to make it more clear)  .     The  method of org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2TableInstaller#createTable   occur error  in mysql version 5.5 or lower  (I notice MysqlTableInstaller extends H2TableInstaller) ,and detalis pls look at contents What happened

___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.5 version
- Which company or project?
module:   storage-jdbc-hikaricp-plugin
- What happened?
Index colum too large .   I notice  the method of  createTableIndexes in MysqlTableInstaller class, it  make a distinction between Column.getLength() < 256 and extraQueryIndex.  However , the id colum is also index colum default. Such as the inner talbe of skywalking creating: alarm_record ,  the length of  id colum is 512 more than 255, so it occur error : Index colum too large because 512*3  >>767 bytes . And In mysql 5.7 or higher ,it's right because in those version , creating table sql will append ROW_FORMAT=DYNAMIC default but 5.5 or lower is COMPACT. ROW_FORMAT can only act on table but not database , but the creating table  sql is writed by skywalking method in H2TableInstaller#createTable , it seems our user can not change.Our use can only set GLOBAL innodb_large_prefix = ON in mysql ,but it doesn't act on COMPACT (DYNAMIC  is  active)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
- maybe  append  a row code : tableCreateSQL.appendLine("ROW_FORMAT=DYNAMIC") in H2TableInstaller#createTable  method  , ( COMPACT default and it will change if declare DYNAMIC ) it seems not agreat impact on other code ,and  there are still many users  in mysql5.5 version, could you please consider it ?

**Comment by wu-sheng** [comment]
We don't want to make the codes too complex, as basically MySQL single node has a very limited performance to support large scale.

**Comment by wu-sheng** [comment]
We make length of id to 512 because of it could be that long in the core.
