### ISSUE TITLE
Invalid value for config --- skywalking-python 

### ISSUE THREAD

**Issue by ZhouWlnd** [apache/skywalking#7457]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question

___
### Question
- What do you want to know?

Hello，I use `gunicorn` to start my `flask` service. So I inserted python agent into `gunicorn.py`. But the following error was reported. What is the reason?

![image](https://user-images.githubusercontent.com/26432419/129432291-ebcc5462-0127-44f3-8297-9140387a522b.png)

ps: My python version is 3.7.2， skywalking-python is 0.6.0

**Comment by kezhenxu94** [comment]
The screenshot provides nothing helpful. Please provide more context.

**Comment by ZhouWlnd** [comment]
The all logs are as follows：

![image](https://user-images.githubusercontent.com/26432419/129433981-aa941878-562a-4d47-b650-390c1c7c9d54.png)


Specifically, I added the python agent code to the `gunicorn.py`  like this：

![image](https://user-images.githubusercontent.com/26432419/129434037-29b3d83b-6d18-45aa-8f3a-44c6291116bf.png)


The `gunicorn` is a tool to start my `flask` service.  Does this mean that skywalking-python can't support `gunicorn`？I think `gunicorn` is a way of http server. 

Maybe I need to add python agent to my `flask` service instead of `gunicorn.py`?

**Comment by kezhenxu94** [comment]
@ZhouWlnd hi, you are using 0.6.0, please refer to the corresponding doc https://github.com/apache/skywalking-python/tree/v0.6.0#set-up-python-agent

We change the property name in master branch.

**Comment by ZhouWlnd** [comment]
I think you don’t understand what I mean at all.  In fact, I used the correct property name. `collector` `service` is right. The above agent code is just an example.

**Comment by wu-sheng** [comment]
> I think you don’t understand what I mean at all.  In fact, I used the correct property name. `collector` `service` is right. The above agent code is just an example.

Pay attention how ask a question at the community. Learn how to describe your scenario.

**Comment by ZhouWlnd** [comment]
Sorry,  what information do you need? I will express as clearly as possible.

**Enviroment**：`python 3.7.2`     `skywalking-python 0.6.0`  `gunicorn` `flask`

**1.** I use `gunicorn` to start my `flask` service.   `gunicorn.py` is a startup script based on `gunicorn`. I want to trace my service. So I added the following code in  `gunicorn.py` :

![image](https://user-images.githubusercontent.com/26432419/129436209-ea7de056-7ff0-43fc-8b4a-e4a5f4db6eb5.png)

**2.** Then I run my `gunicorn.py` as  `gunicorn -c gunicorn.py app:app`

**3.** The running log is as follows:

![image](https://user-images.githubusercontent.com/26432419/129436097-b23bf882-b06b-407d-8af1-574c9288eff4.png)

**Comment by kezhenxu94** [comment]
@ZhouWlnd please provide a minimal reproduce gunicorn project to reproduce the issue. I mean the codes of the whole project, you can minimize the codes but make sure it's runnable to reproduce the problem. I can keep this issue open for some time and wait for your reproduce project, then we can triage the issue

**Comment by ZhouWlnd** [comment]
Thanks for your reply, I will try my best to provide reproducible code, but this may be more difficult.

Could you be sure that skywalking-python can support `gunicorn`？
Or maybe I need add the python agent code to `flask`？

**Comment by wu-sheng** [comment]
The demo codes are required if you want the maintainers to take time.
They wouldn't try anything. Because this basically is your responsibility.
Their time and energy are high valued.

**Comment by wu-sheng** [comment]
Close issue, until you could provide demo codes, with clear description about how to run the codes step by step.
Remember, maintainers have no obligation to debug, even fix bugs. They are watchers, not service providers.

**Comment by kezhenxu94** [comment]
> Thanks for your reply, I will try my best to provide reproducible code, but this may be more difficult.
> 
> 
> 
> Could you be sure that skywalking-python can support `gunicorn`？
> 
> Or maybe I need add the python agent code to `flask`？

Reproducible demo is essentially evidence for potential bugs in open source projects.

And this is our committer that runs skywalking agent in gunicorn https://github.com/apache/skywalking/issues/5263#issuecomment-671378544

**Comment by kezhenxu94** [comment]
@ZhouWlnd you should also search first before opening an issue. And learn the example I posted on how to report an issue.

**Comment by Superskyyy** [comment]
A quick search returns me this very similar issue back in 2011 in [Gunicorn repo](https://github.com/benoitc/gunicorn/issues/156), please try search before asking.

First, we don't have that error line in SW-Python, the error is coming from Gunicorn itself. Now with your SS indicating, you imported skywalking.config -> which apparently overrides the original `config` variable that Gunicorn listens to as its own config.. Now I guess we know why it went wrong.

**Comment by ZhouWlnd** [comment]
Thank you very much for your patient guidance!
