### ISSUE TITLE
Skywalking Multi-tenant

### ISSUE THREAD

**Issue by chenhaipeng** [apache/skywalking#7467]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Why does skywalking not provide agent config custom attributes, I need custom attributes to isolate tenants, for example, agent.tags=userId, backend uses userId to isolate data

___

**Comment by wu-sheng** [comment]
In an open source community, this means we don't have contributors want to do this, and no committer says we would like to maintain if the contributor(s) are gone.
Nothing special, all existing features are following the same logic.

**Comment by wu-sheng** [comment]
This has been answered many times, don't repeat the questions. Search the issue list first.
