### ISSUE TITLE
password

### ISSUE THREAD

**Issue by iSpringFish** [apache/skywalking#7502]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by iSpringFish** [comment]
> 通过docker 安装 skywalking-oap skywalking-ui 默认密码是多少？
> docker run --name skywalking-oap --restart always -d
> -p 11800:11800
> -p 12800:12800
> -e TZ=Asia/Shanghai
> -e SW_STORAGE=elasticsearch7
> -e SW_STORAGE_ES_CLUSTER_NODES=172.16.100.237:9200
> apache/skywalking-oap-server:8.3.0-es7
> 
> docker run --name skywalking-ui --restart always -d
> -p 8088:8080
> -e TZ=Asia/Shanghai
> --link skywalking-oap:skywalking-oap
> -e SW_OAP_ADDRESS=skywalking-oap:12800
> apache/skywalking-ui
> 
> 启动容器后，可以访问 localhost:8088 登录界面，但是通过admin/admin无法登录
> `[root@localhost ~]# docker logs skywalking-ui
> 
> . ____ _ __ _ _
> /\ / ' __ _ () __ __ _ \ \ \
> ( ( )__ | '_ | '| | ' / ` | \ \ \
> \/ )| |)| | | | | || (| | ) ) ) )
> ' || .__|| ||| |_, | / / / /
> =========||==============|/=////
> :: Spring Boot :: (v2.4.8)
> 
> 2021-08-20 09:46:39.088 INFO 1 --- [ main] o.a.s.apm.webapp.ApplicationStartUp : Starting ApplicationStartUp v8.7.0 using Java 11.0.9 on 78b813f5f35a with PID 1 (/skywalking/webapp/skywalking-webapp.jar started by root in /skywalking)
> 2021-08-20 09:46:39.099 INFO 1 --- [ main] o.a.s.apm.webapp.ApplicationStartUp : No active profile set, falling back to default profiles: default
> 2021-08-20 09:46:41.494 INFO 1 --- [ main] o.s.cloud.context.scope.GenericScope : BeanFactory id=cab36694-a4fc-3018-881d-bdde2b7e0925
> 2021-08-20 09:46:41.653 INFO 1 --- [ main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2021-08-20 09:46:41.655 INFO 1 --- [ main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2021-08-20 09:46:41.659 INFO 1 --- [ main] trationDelegate$BeanPostProcessorChecker : Bean 'reactorDeferringLoadBalancerExchangeFilterFunction' of type [org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2021-08-20 09:46:43.063 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [After]
> 2021-08-20 09:46:43.064 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Before]
> 2021-08-20 09:46:43.064 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Between]
> 2021-08-20 09:46:43.064 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Cookie]
> 2021-08-20 09:46:43.064 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Header]
> 2021-08-20 09:46:43.065 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Host]
> 2021-08-20 09:46:43.065 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Method]
> 2021-08-20 09:46:43.065 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Path]
> 2021-08-20 09:46:43.065 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Query]
> 2021-08-20 09:46:43.066 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [ReadBody]
> 2021-08-20 09:46:43.066 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [RemoteAddr]
> 2021-08-20 09:46:43.066 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Weight]
> 2021-08-20 09:46:43.067 INFO 1 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [CloudFoundryRouteService]
> 2021-08-20 09:46:43.523 INFO 1 --- [ main] o.s.b.a.e.web.EndpointLinksResolver : Exposing 2 endpoint(s) beneath base path '/actuator'
> 2021-08-20 09:46:43.806 WARN 1 --- [ main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
> 2021-08-20 09:46:44.063 INFO 1 --- [ main] o.s.b.web.embedded.netty.NettyWebServer : Netty started on port 8080
> 2021-08-20 09:46:44.257 INFO 1 --- [ main] o.a.s.apm.webapp.ApplicationStartUp : Started ApplicationStartUp in 6.463 seconds (JVM running for 7.709)
> `

**Comment by wu-sheng** [comment]
Discussion should be on https://github.com/apache/skywalking/discussions, and all should be in English.
