### ISSUE TITLE
Endpoint search will cause the entire page to jam

### ISSUE THREAD

**Issue by github646048825** [apache/skywalking#7519]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
 [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
skywalking8.7  ES7.13

- Which company or project?

- What happened?
after selecting the service, enter the endpoint name, which cannot be selected, and the whole page cannot be clicked and refreshed. Is this a bug or my configuration problem？
![1629456188(1)](https://user-images.githubusercontent.com/79822553/130222131-87b2ab4a-bb76-4498-a577-f6f30c4aae20.jpg)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Why submit again?
