### ISSUE TITLE
[License-Eye] skywalking-eyes doesn't recognize absolute path in .gitignore

### ISSUE THREAD

**Issue by spacewander** [apache/skywalking#7538]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

skywalking-eyes

- What happened?

Take https://github.com/apache/apisix/ as an example.
git clone this repo, touch conf/apisix-aa.yaml.
You will find this file is ignored by `.gitignore`, in absolute path format `/conf/apisix-*.yaml`.

Then you can run `docker run -it --rm -v $(pwd):/github/workspace apache/skywalking-eyes header check`, you will find out this file is not ignored.

**Comment by wu-sheng** [comment]
Is an git ignored hosted in the repo? What is the point?

**Comment by kezhenxu94** [comment]
> Why is an git ignored hosted in the repo? What is the point?

A case I can think about is to put some files in the codebase that are meant to be modified ever

**Comment by wu-sheng** [comment]
This seems a very not-typical operation. I want to hear what @gxthrj says. Move this discussion.
