### ISSUE TITLE
[License-Eye] pyx files (cython)

### ISSUE THREAD

**Issue by keiranmraine** [apache/skywalking#7552]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

### Requirement or improvement

Please can one or more of the following be added to the sykwalking-eyes functionality (or expansion of docs if already available):

* Runtime extensions equivalence via CLI (py=~pyx)
* Ability to define extension equivalence in the `.licenserc.yaml`
* Add common cython file extentions to core.

**Comment by kezhenxu94** [comment]
@keiranmraine can you read https://github.com/apache/skywalking-eyes#supported-file-types and try to contribute to this enhancement?

**Comment by keiranmraine** [comment]
According to the current main branch the `.pyx` extension is supported:

https://github.com/apache/skywalking-eyes/blob/082ccc7d63f8cde9afdb6eee30843b8f0a8182ed/assets/languages.yaml#L1090

The it appears that although it works for `check` it fails for `fix:

`check` - identifies file needs update:

```
docker run -it --rm -v $(pwd):/github/workspace apache/skywalking-eyes header check
...
INFO Totally checked 138 files, valid: 13, invalid: 1, ignored: 124, fixed: 0 
ERROR the following files don't have a valid license header: 
pygas/matrix.pyx 
```

`fix` - indicates unsupported:

```
docker run -it --rm -v $(pwd):/github/workspace apache/skywalking-eyes header fix
INFO Totally checked 138 files, valid: 13, invalid: 1, ignored: 124, fixed: 0 
ERROR unsupported file: pygas/matrix.pyx
```

**Comment by keiranmraine** [comment]
Repo/file in example can be found here:
https://github.com/cancerit/pygas/blob/develop/pygas/matrix.pyx

**Comment by kezhenxu94** [comment]
@keiranmraine yes, `check` is generally available for most (if not all) programming languages, but `fix` need to know what's the comment style of a specific language.

**Comment by keiranmraine** [comment]
Ah, okay so it needs a section like the Python one creating for Cython.  I'll look at it.

**Comment by keiranmraine** [comment]
FYI if you find people are unable to build the docker file this will solve the problem for them:

https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

Created: https://github.com/apache/skywalking-eyes/pull/62

**Comment by kezhenxu94** [comment]
> FYI if you find people are unable to build the docker file this will solve the problem for them:
> 
> 
> 
> https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2
> 
> 
> 
> Created: https://github.com/apache/skywalking-eyes/pull/62

Thanks for the information.

**Comment by wu-sheng** [comment]
@kezhenxu94 Is this done?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 Is this done?

Fixed by https://github.com/apache/skywalking-eyes/pull/62
