### ISSUE TITLE
The problem remains :   NPE when thrift field is nested

### ISSUE THREAD

**Issue by lzdujing** [apache/skywalking#7571]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ T] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I already used version 8.6.0  which has fixed the error: NPE when thrift field is nested ,but context is still null, why?
___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.6.0 

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

context is null, why?

code position:
```
ServerInProtocolWrapper#readFieldBegin()
    @Override
    public TField readFieldBegin() throws TException {
       ................
        if (field.type == TType.STOP) {
            Boolean haveCreatedSpan =
                    (Boolean) ContextManager.getRuntimeContext().get(HAVE_CREATED_SPAN);
            if (haveCreatedSpan != null && !haveCreatedSpan) {
                try {
                    AbstractSpan span = ContextManager.createEntrySpan(
                            context.getOperatorName(), createContextCarrier(null));
                    span.start(context.startTime);
                    span.tag(TAG_ARGS, context.getArguments());
                    span.setComponent(ComponentsDefine.THRIFT_SERVER);
                    SpanLayer.asRPCFramework(span);
                } catch (Throwable throwable) {
                    LOGGER.error("Failed to create EntrySpan.", throwable);
                } finally {
                    context = null;
                }

        return field;
    }
```

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by lzdujing** [comment]
@dmsolr   Can this issue be reproduced?

**Comment by dmsolr** [comment]
@lzdujing Sorry. A tittle busy these days. I will do this on weekend.

**Comment by lzdujing** [comment]
@dmsolr ok,thank you.

**Comment by lzdujing** [comment]
@dmsolr Could you take a look this issue for me sometime soon? We are waiting to solve the problem a little  worry . Thank you.

**Comment by lzdujing** [comment]
@wu-sheng Yes,I understand. We have tried our best to solve it and never give up.But It's a little hard for us . So we hope the community can help us and we expressing thanks for it.

**Comment by dmsolr** [comment]
Hi @lzdujing 
I had talked with @zifeihan , he will follow this.
I am not familiar with Nacos, so that is my guess. It seems like thrift-plugin is not compatible with nacos sdk. Maybe nacos spring sdk will modify thrift classes in runtime. 

BTW, you provided a `rar` package, that is hard to open in MacOS/Linux. 
And this case happens in such a complex environment, I am really difficult to make it works.

**Comment by lzdujing** [comment]
@dmsolr Ok,thanks.

**Comment by zifeihan** [comment]
@lzdujing Can you provide a zip to replace the rar package? In addition, the error log of the agent is also needed, which is a bit busy these days. I will take time to follow up on this issue during the weekend.

**Comment by lzdujing** [comment]
@lzdujing I'll provide a zip today.

**Comment by lzdujing** [comment]
@zifeihan I'll provide a zip today.

**Comment by lzdujing** [comment]
@zifeihan I have uploaded the  non-compressed demo already.

**Comment by zifeihan** [comment]
@dmsolr @lzdujing Sorry for being late. I have been too busy recently. Through debugging, I found that the thrift plugin processes TBaseProcessor and TBaseAsyncProcessor, but the demo reference uses TMultiplexedProcessor, so an exception has occurred. I am repairing and testing. I will submit pr tomorrow.

**Comment by dmsolr** [comment]
Thanks, @zifeihan 
Yes, I really didn't cover this case `TMultiplexedProcessor`.

**Comment by zifeihan** [comment]
@lzdujing It has been tested on your demo project, and the test results are all normal. I have been busy recently, so the related test scenario has not been added. If you have time, can you submit a pr to help cover the related test scenario?

**Comment by lzdujing** [comment]
Thank you very much. I'll check it tody.

**Comment by lzdujing** [comment]
@ zifeihan After updating  the code the problem of reporting errors has been solved,but,the server still can't track it.
![server](https://user-images.githubusercontent.com/13194663/133013922-094c6660-14da-49e7-87d2-fcaa655c5314.png)
![client](https://user-images.githubusercontent.com/13194663/133013929-28d01185-ccdb-40a6-9121-33436c33ef20.png)

**Comment by zifeihan** [comment]
It has been fixed, please refer to the latest version.
![image](https://user-images.githubusercontent.com/16839929/133071149-12e37dbd-03d1-4cbb-b29e-1dbc509798cb.png)

**Comment by wu-sheng** [comment]
Fixed through https://github.com/apache/skywalking-java/pull/22

**Comment by lzdujing** [comment]
@ zifeihan I have downloaded the last version and tested. It is ok now.Thanks a lot.
