### ISSUE TITLE
Support PagerDuty immigration for alarm

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7572]
PagerDuty(https://www.pagerduty.com/) is widely used for on-call globally. We are welcome the contributions to support it as alarm notification channel.

**Comment by harry-dev98** [comment]
hey, I am kinda new to this community. I'd like to head with this issue to start contributing, can you please share bit of more information what is the requirement of this issue?

**Comment by wu-sheng** [comment]
@harry-dev98 Thanks. We have various notifications, from webhook to slack. PageDuty seems a very important channel to forward the alarm.

https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-alarm/#webhook

The source codes about the existing notification implementations are here, https://github.com/apache/skywalking/tree/master/oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider.

**Comment by harry-dev98** [comment]
Okay this is what i understand: 
So we do have couple of  channels already like webhook, gRPChook, slackhook,.. etc. And now we need to add pagerduty as another new channel supported by skywalking, right?

also, is pagerduty opensource? I looked through their website its kinda paid service (yes free for some caped usage)

**Comment by wu-sheng** [comment]
It is not open source. But once it has open HTTP API, we could try to integrate.
This is totally optional, and rarely changed API. 
Please check whether this is correct.

**Comment by harry-dev98** [comment]
regarding APIs, yes pagerduty provides REST APIs. Basically two types of APIs one for managing the account other for events generated by some tool like skywalking,etc. So should i try integrating events api for now, and lateron can be extended to other type of API i.e. to manage account.

We just need to make sure the alarm notifications reach pagerduty account of the user, right?

**Comment by wu-sheng** [comment]
> So should i try integrating events api for now, and lateron can be extended to other type of API i.e. to manage account.

Yes, try event APIs. And we may not need to spend time on account management APIs. As we don't have UI or feature about this. Only if you want to provide some scripts to create or set up account, then those APIs help.

> We just need to make sure the alarm notifications reach pagerduty account of the user, right?

Yes, you could create a trial account, and make sure the alarm messages landed there.

**Comment by Superskyyy** [comment]
Hey there, just curious about the progress. Back when this issue was first created, I actually set up a PagerDuty developer account and a mock integration to try the implementation. Now PagerDuty people actually reached out to me asking about if SkyWalking would like to list the integration officially on their [website](https://www.pagerduty.com/integrations/). If there's no Apache regulations against it, I think we should do it when this merges. FYI @wu-sheng @harry-dev98  

From my intern experience, PagerDuty is extremely popular and widely used among companies worldwide, I believe this is a good step to expand our community globally.

**Comment by wu-sheng** [comment]
@Superskyyy Good to know they are listing this. I read the list page, which seems fine from policy perspective. 
Before that, we need this feature ready and released, then we at least have a version mentioned on their page.

**Comment by wu-sheng** [comment]
@harry-dev98 Do you have any update to share?

**Comment by wu-sheng** [comment]
Or @Superskyyy Do you already have codes of this feature ready to submit?

**Comment by Superskyyy** [comment]
> Or @Superskyyy Do you already have codes of this feature ready to submit?
@wu-sheng 
Nah, I simply tested with its APIs on the mock integration, I didn't add anything to SW codebase. I'll say lets wait a day or two for Harry's response, if no response I can do it and if goes smoothly we can release it next month. We plan to release 8.8.0 after Oct.10th right?

**Comment by wu-sheng** [comment]
Yes, that is the current plan.

**Comment by wu-sheng** [comment]
Yes, that is the current plan.

**Comment by harry-dev98** [comment]
Hey there, i don't have solid advancement, i just used pager duty apis just to understand how they work, and then got busy with my own stuff.. it may take some time to integrate 🥺

**Comment by Superskyyy** [comment]
Fyi @wu-sheng  ^^

**Comment by wu-sheng** [comment]
> Fyi @wu-sheng ^^

Then, @Superskyyy If you want and have time, it is open for you to take over responsibility.

**Comment by Superskyyy** [comment]
> > Fyi @wu-sheng ^^ 
> 
> Then, @Superskyyy If you want and have time, it is open for you to take over responsibility.

I can figure something out this weekend, I think it doesn't require too much changes for only a alarm.

**Comment by Superskyyy** [comment]
Also PagerDuty is a very interesting platform that differs from previous platforms that we support, it can do bi-directional interaction, maybe interesting to have some side projects in the future. For this one, I will only implement basic alarms.

**Comment by wu-sheng** [comment]
> Also PagerDuty is a very interesting platform that differs from previous platforms that we support, it can do bi-directional interaction, maybe interesting to have some side projects in the future. For this one, I will only implement basic alarms.

Make sense. Feel free to open a discussion and involve their team in. 
Let's see what we could build.

**Comment by Superskyyy** [comment]
Update, I implemented it over last weekend. Been busy at school reading papers, it might take another few days before opening PR.

**Comment by wu-sheng** [comment]
Sure, we will be on China National Day vacation, and we are doing 8.8.1 release as a hot fix release.
Feel free to send pull request to 8.9.0

**Comment by wu-sheng** [comment]
@Superskyyy Is this PR ready to go? Or we should find someone else to cover this?

**Comment by chen-ni** [comment]
@wu-sheng I can work on this if nobody else is working on it. Could you please assign it to me?

**Comment by wu-sheng** [comment]
Done, you could simply do this. You don't need to wait for this assignment.

**Comment by chen-ni** [comment]
@wu-sheng Got it, thanks! Will start now and keep this updated.
