### ISSUE TITLE
[Bug] Spring MVC @RequestBody 调用错误

### ISSUE THREAD

**Issue by abel533** [apache/skywalking#7614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

![image](https://user-images.githubusercontent.com/1787798/131457463-e5bc8ebe-ed1a-420a-aee9-6eb4411e8436.png)

接收的对象中有 `BigDecimal` 字段，经过 agent 字节码加强后，调用该方法报错：

![image](https://user-images.githubusercontent.com/1787798/131457601-fd97331e-ecbc-4eea-ba4a-a1e3c16276f0.png)

### What you expected to happen

去掉skywalking后方法恢复正常。

### How to reproduce

上面有代码。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please use English on the GitHub discussion.
