### ISSUE TITLE
[Feature] Does skywalking currently support django+uwsgi deployment?

### ISSUE THREAD

**Issue by slientup** [apache/skywalking#7617]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

When I use "python manage.py runserver 127.0.0.1:8091" to run the django project, skywalking-ui can display real-time data normally, but when I use uwsgi+nginx to deploy in production, skywalking-ui is nothing。

When I restarted the uwsgi process, skywalking-ui had the previously undisplayed data. Through the tcpdump packet capture, I confirmed that no data packets were sent to skywalking when the uwsgi process was normal, but when the uwsgi process was restarted, many packets sent to skywalking。

it is similar #6324

django=3.2
apache-skywalking=0.6.0
uwsgi=2.0.19.1

### What you expected to happen

no

### How to reproduce

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Hi, @slientup please provide reproducible steps when you are reporting a bug, otherwise we are not able to help to reproduce and fix, if you cannot provide reproducible steps, open in [Discussion](http://github.com/apache/skywalking/discussions) first.

**Comment by kezhenxu94** [comment]
@slientup also, did you read the whole comments in https://github.com/apache/skywalking/issues/6324 ? Does it help somehow?

**Comment by wu-sheng** [comment]
@slientup You should follow the issue template required, if there no enough information, community would not follow up.

**Comment by slientup** [comment]
> Hi, @slientup please provide reproducible steps when you are reporting a bug, otherwise we are not able to help to reproduce and fix, if you cannot provide reproducible steps, open in [Discussion](https://github.com/apache/skywalking/discussions) first.

Step 1：When I use "python manage.py runserver 127.0.0.1:8091" to run the django project on dev env, skywalking-ui can display real-time data

Step 2：when I use uwsgi+nginx to deploy django project  in production env, skywalking-ui is nothiing.

**Comment by slientup** [comment]
> @slientup also, did you read the whole comments in #6324 ? Does it help somehow?
@kezhenxu94  it is some helpful. After I replaced uwsgi with gunicorn, skywalking-ui showed the data in real time
