### ISSUE TITLE
[Bug] H2MetadataQueryDAO.searchService doesn't support group

### ISSUE THREAD

**Issue by LIU-WEI-git** [apache/skywalking#7653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

H2MetadataQueryDAO.searchService (Line 162-167) doesn't support group. Related to Pull Request #5851.

### What you expected to happen

We should call service.setGroup in H2MetadataQueryDAO.searchService.

### How to reproduce

Just comparing every implement of IMetadataQueryDAO.searchService, you will find the implement of H2 (H2MetadataQueryDAO) doesn't call setGroup function.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Thanks for pointing out. Welcome to fix
