### ISSUE TITLE
[Bug] ElasticSearch storage `secretsManagementFile` hot reloading doesn't work as expected

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7655]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The `BulkProcessor` created here is bound to the `client` and the `BulkProcessor` is not updated afterwards.

https://github.com/apache/skywalking/blob/de59bf7aebc20110c21c0e39e9b987e4aec91911/oap-server/server-library/library-client/src/main/java/org/apache/skywalking/oap/server/library/client/elasticsearch/ElasticSearchClient.java#L569-L578

When the `secretsManagementFile` is updated, the `client` will be re-created in `elasticSearchClient.connect()`, and the original `BulkProcessor` is still bound to the old ElasticSearch client, which should not work.

https://github.com/apache/skywalking/blob/69ddc07cc152c415f385f863baff65c9c6079e2b/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/StorageModuleElasticsearchProvider.java#L145-L148

### What you expected to happen

The `BulkProcessor` should use the newly-created ElasticSearch client, or the ElasticSearch client is not created, only update the needed fields.

### How to reproduce

I notice this when reviewing the codes in #7634 , but haven't fixed it in #7634 , we'd better fix this in 8.8.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please update this in the change log of #7634

**Comment by kezhenxu94** [comment]
> Please update this in the change log of #7634

This is a bug report, and the bug exists in all previous version, what's the point to include this in the change log?

**Comment by wu-sheng** [comment]
> what's the point to include this in the change log?

Because your PR(even rewrite all) fixed this bug, isn't it?

**Comment by kezhenxu94** [comment]
No 😢, I haven't found out the best way to fix this yet, 

> I notice this when reviewing the codes in #7634 , but haven't fixed it in #7634 , we'd better fix this in 8.8.0

**Comment by kezhenxu94** [comment]
> No 😢, I haven't found out the best way to fix this yet,

OK, now it's fixed in #7634 and change log is updated too
