### ISSUE TITLE
[Eyes] Add more Licenses template for identity the License type 

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#7677]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

License Tools (apache/skywalking-eyes)

### What happened

When I using skywalking-eyes to check the licenses in [skywalking-infra-e2e], I found some unknown identity licenses. Here is the link: https://github.com/apache/skywalking-infra-e2e/pull/42#issuecomment-914873814

### What you expected to happen

The unknown licenses could be identified.

### How to reproduce

Using skywalking-eyes to resolve dependency licenses in skywalking-infra-e2e.
```shell
license-eye dependency resolve
```

### Anything else

I will some another PR to add more templates for identity the licenses.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This belongs to `license eye`.
