### ISSUE TITLE
The demo server is down

### ISSUE THREAD

**Issue by williamdes** [apache/skywalking#7692]
### What happened

The demo server is down (ERR_CONNECTION_REFUSED)

### What you expected to happen

See the demo

### How to reproduce

Go to https://skywalking.apache.org/#demo

And then https://demo.skywalking.apache.org/

**Comment by wu-sheng** [comment]
I just checked, it is up and running from my browser side.

**Comment by kezhenxu94** [comment]
@williamdes in the demo env, we don't support https, please force to use http if you browser automatically directs from http to https

**Comment by williamdes** [comment]
Please fix your website or server
The go button sends you to https..
I can help setup https if you have an infrastructure repository

**Comment by williamdes** [comment]
I use Brave browser, maybe this is what causes the issue

**Comment by wu-sheng** [comment]
The source codes of website are here.

https://github.com/apache/skywalking-website

**Comment by williamdes** [comment]
Thank you !
Indeed the link is http, where is the infrastructure managed ?

https://github.com/apache/skywalking-website/blob/e481896aff488819be6043663dd3e919b25c18be/content/_index.html#L81

**Comment by wu-sheng** [comment]
No other infra manages that, Apache Software Foundation uses Apache server hosts static page. 
Like @kezhenxu94 said, this is more like browser side setting. 
You could check http page on your browser, then you know whether link is changed or not.

**Comment by williamdes** [comment]
> You could check http page on your browser, then you know whether link is changed or not.

My browser and a lot of other ones do HTTPS upgrades without asking

> No other infra manages that, Apache Software Foundation uses Apache server hosts static page.

My question was what infrastructure hosts the demo server ?

**Comment by wu-sheng** [comment]
It is a private GCP VM, sponsored by Tetrate.

**Comment by williamdes** [comment]
> It is a private GCP VM, sponsored by Tetrate.

Okay, I would recommend you to use acme.sh
It's easy and open source, a git clone and run bash solution

**Comment by wu-sheng** [comment]
> > It is a private GCP VM, sponsored by Tetrate.
> 
> Okay, I would recommend you to use acme.sh
> It's easy and open source, a git clone and run bash solution

It is just a VM on the Google cloud, nothing special. All in the runtime are SkyWalking binary.

**Comment by williamdes** [comment]
So Google Cloud does not provide an SSL overlay ??

**Comment by wu-sheng** [comment]
> So Google Cloud does not provide an SSL overlay ??

The key issues is, SSL private keys are managed by Apache Software Foundation Infra team, which requires everything has to been deployed on the ASF Infra. But this demo is deployed on the 3rd party, sponsor VM. So, we can't have the key, but the domain name is under skywalking.apache.org, then, we have to keep it in http only.
