### ISSUE TITLE
[Bug] ProfileThreadSnapshotQuery.queryProfiledSegments adopts a wrong sort function

### ISSUE THREAD

**Issue by LIU-WEI-git** [apache/skywalking#7695]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The InfluxDB implementation of IProfileThreadSnapshotQueryDAO.queryProfiledSegments, ProfileThreadSnapshotQuery.queryProfiledSegments, adopts a wrong sort function. See the
[Line 80](https://github.com/apache/skywalking/blob/4eb37d4d53cd77e173f3e1d418ba7fe7afe5a8a3/oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/query/ProfileThreadSnapshotQuery.java#L80). It uses **the `bottom` function** for `SegmentRecord.START_TIME`. The bottom function means adopts ASC order. However, the corresponding implementation of H2 and ES use DESC order. See the [H2 implementation](https://github.com/apache/skywalking/blob/4eb37d4d53cd77e173f3e1d418ba7fe7afe5a8a3/oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/h2/dao/H2ProfileThreadSnapshotQueryDAO.java#L84) and the [ES implementation](https://github.com/apache/skywalking/blob/4eb37d4d53cd77e173f3e1d418ba7fe7afe5a8a3/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/query/ProfileThreadSnapshotQueryEsDAO.java#L101)

### What you expected to happen

The [Line 80](https://github.com/apache/skywalking/blob/4eb37d4d53cd77e173f3e1d418ba7fe7afe5a8a3/oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/query/ProfileThreadSnapshotQuery.java#L80) of ProfileThreadSnapshotQuery should adopt DESC order. Just change `InfluxConstants.SORT_ASC` to `InfluxConstants.SORT_DES`.

### How to reproduce

Just comparing every implementation of IProfileThreadSnapshotQueryDAO.queryProfiledSegments, you will find the implementation of InfluxDB(ProfileThreadSnapshotQuery) adopts a wrong sort function.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please go ahead.
