### ISSUE TITLE
[Feature] Refactor SkyWalking Python to use the CLI for CI instead of legacy setup

### ISSUE THREAD

**Issue by Superskyyy** [apache/skywalking#7701]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Since the non-intrusive integration feature is merged, SkyWalking Python will move to replace the `import skywalking` commands in all existing CI test cases with the new `sw-python` CLI. 

Discussed in https://github.com/apache/skywalking-python/pull/156#issuecomment-904302575

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
Weird finding, the Sanic plugin seems to fail on Python 3.6(passes on 3.7-3.9) when I switch to CLI based test.
 
Sanic dropped general support for Python 3.6 https://github.com/sanic-org/sanic except for a LTS version. I don't know if that could be contributing to the failure.

**Comment by Superskyyy** [comment]
Also found out we may need a review of tested lib versions as many have evolved over a major version number since the plugins are added. Testing for unsupported versions(like Django==2.0) is slowing down the CI.

**Comment by kezhenxu94** [comment]
> Also found out we may need a review of tested lib versions as many have evolved over a major version number since the plugins are added. Testing for unsupported versions(like Django==2.0) is slowing down the CI.

That is reasonable and we can review the tested version from time to time, or have automatic pipeline to check the newer versions of the libs. 

We typically test the latest 3 major versions of the libs (if we claim to support it)

**Comment by kezhenxu94** [comment]
> Weird finding, the Sanic plugin seems to fail on Python 3.6(passes on 3.7-3.9) when I switch to CLI based test.

Any logs?

**Comment by Superskyyy** [comment]
> > Weird finding, the Sanic plugin seems to fail on Python 3.6(passes on 3.7-3.9) when I switch to CLI based test.
> 
> Any logs?
CLI based run - fails on Python 3.6 b/c provider.py reporting a exit span from 7002(requests) instead of entry span from 7007(sanic)
https://github.com/Superskyyy/skywalking-python/runs/3625969357
Original run - passes for all versions
https://github.com/Superskyyy/skywalking-python/actions/runs/1243676935

**Comment by kezhenxu94** [comment]
@Superskyyy please just ignore that error if you cannot figure out why shortly, and continue the process, when you open the PR, I can help to debug locally

**Comment by Superskyyy** [comment]
> @Superskyyy please just ignore that error if you cannot figure out why shortly, and continue the process, when you open the PR, I can help to debug locally

Thanks, the others are done and passed, opening pr soon.
