### ISSUE TITLE
[Bug] [python] Python agent 0.7.0 raise a excception "Method not found: skywalking.v3.TraceSegmentReportService/collect"

### ISSUE THREAD

**Issue by Stark-X** [apache/skywalking#7703]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

When the python agent upgrade to `v0.7.0`, there will be lots of exception in log.
e.g.:
```
>
skywalking [ReportThread] [ERROR] <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Method not found: skywalking.v3.TraceSegmentReportService/collect"
        debug_error_string = "{"created":"@1631509662.444794228","description":"Error received from peer ipv4:x.x.x.x:11800","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Method no
t found: skywalking.v3.TraceSegmentReportService/collect","grpc_status":12}"
```

### What you expected to happen

no exception will throw

### How to reproduce

Skywalking 8.1.0
Python agent 0.7.0

Just start and it'll reproduce.

If using the latest `sw-python`, the application will failed to start.
If using the code snippet to start the agent, the application works normally, but lots of exception will thorwn

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Use the latest SkyWalking server. 8.1.0 doesn't support the new agent release.
