### ISSUE TITLE
[Feature] Add e2e test to Python agent based on skywalking-infra-e2e

### ISSUE THREAD

**Issue by Superskyyy** [apache/skywalking#7708]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Adding e2e testing for Python agent features(log reporter etc.) using [skywalking-infra-e2e](https://github.com/apache/skywalking-infra-e2e)

Originally discussed in https://github.com/apache/skywalking-python/pull/147#issuecomment-894727435

Will implement this when I get time.

### Use case

Provide testing coverage of more features.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
It is even better you could begin to replace the main repo's e2e.

**Comment by Superskyyy** [comment]
> It is even better you could begin to replace the main repo's e2e.

https://github.com/apache/skywalking/issues/7368 Is this being actively worked on? I can help out.

**Comment by Superskyyy** [comment]
> > > It is even better you could begin to replace the main repo's e2e.
> > 
> > 
> > #7368 Is this being actively worked on? I can help out.
> 
> Not yet, feel free to jump in if you are interested in,

Ok I'ma finish #7701 first then let's see if I can deal with 7368.

**Comment by wu-sheng** [comment]
@Superskyyy Are you working on this now?

**Comment by Superskyyy** [comment]
> @Superskyyy Are you working on this now?

Not yet, it's on my list though, it's been really busy at school recently.

**Comment by wu-sheng** [comment]
Could you try to finish this? I hope we could move forward 1.0 soon. @Superskyyy

**Comment by Superskyyy** [comment]
Tracing and Logging e2e coverage is implemented and merged. Closing this issue, note to myself, profiling is not covered yet.
