### ISSUE TITLE
[Feature] Make UI showing backend error

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Please add a popup page when UI do GraphQL and face some errors from the backend.

### Use case

We faced backend bug which causes the error response. But UI doesn't visualize it, but only could be found in the browser command. Let's bring it on the table.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
A global pop up tooltip should be enough , we don’t need to think about where to put the error message per page.

**Comment by wu-sheng** [comment]
> A global pop up tooltip should be enough , we don’t need to think about where to put the error message per page.

Agree. Just notice, as we request multiple GraphQL query(s) continuously, we may need be able to show multiple pop up tooltips.
