### ISSUE TITLE
[Bug] The methods of H2EventQueryDAO doesn't sort the data by Event.START_TIME

### ISSUE THREAD

**Issue by LIU-WEI-git** [apache/skywalking#7713]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Comparing [H2EventQueryDAO](https://github.com/apache/skywalking/blob/94623f283139e31484979205ef7c14d73c91b0d0/oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/h2/dao/H2EventQueryDAO.java#L73) with [ESEventQueryDAO](https://github.com/apache/skywalking/blob/94623f283139e31484979205ef7c14d73c91b0d0/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/query/ESEventQueryDAO.java#L135) and [EventQueryDAO](https://github.com/apache/skywalking/blob/94623f283139e31484979205ef7c14d73c91b0d0/oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/query/EventQueryDAO.java#L116), you will find the latter two sort data by Event.START_TIME, but the first one doesn't. This difference has existed since PR #6183. I think it is a bug probably.

### What you expected to happen

Add `order by` clause to those query SQL of H2EventQueryDAO.

### How to reproduce

Just compare every implementation of IEventQueryDAO.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LIU-WEI-git** [comment]
[EventQueryDAO](https://github.com/apache/skywalking/blob/94623f283139e31484979205ef7c14d73c91b0d0/oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/query/EventQueryDAO.java#L73) and [ESEventQueryDAO](https://github.com/apache/skywalking/blob/94623f283139e31484979205ef7c14d73c91b0d0/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/query/ESEventQueryDAO.java#L128) use the pagination ("limit" and "from") of the first condition. However, [H2EventQueryDAO](https://github.com/apache/skywalking/blob/94623f283139e31484979205ef7c14d73c91b0d0/oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/h2/dao/H2EventQueryDAO.java#L115) adopts the [sum of limit size of all condition](https://github.com/apache/skywalking/blob/94623f283139e31484979205ef7c14d73c91b0d0/oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/h2/dao/H2EventQueryDAO.java#L100) with out offset. Should I modify H2EventQueryDAO according to the other two?

**Comment by wu-sheng** [comment]
I am not sure what does first condition mean. @kezhenxu94 should know more than me.

**Comment by kezhenxu94** [comment]
Hi @LIU-WEI-git , thank you for reporting this, the `EventQueryDAO` and `ESEventQueryDAO` should use the same logic with `H2EventQueryDAO`. The first condition serves as a prototype of the query condition list so we should not use the sum of limit size of all conditions as the result limit, which would be unreasonable large and not expected use case.

**Comment by LIU-WEI-git** [comment]
Got it. I will submit a PR soon.
