### ISSUE TITLE
[Bug] H2LogQueryDAO and LogQuery don't support fuzzy query of AbstractLogRecord.CONTENT

### ISSUE THREAD

**Issue by LIU-WEI-git** [apache/skywalking#7723]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Both of [H2LogQueryDAO](https://github.com/apache/skywalking/blob/92f0ebf126fe242ee30f8ab8106b41f8ff39d656/oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/h2/dao/H2LogQueryDAO.java#L87) (H2 storage plugin) and [LogQuery](https://github.com/apache/skywalking/blob/92f0ebf126fe242ee30f8ab8106b41f8ff39d656/oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/query/LogQuery.java#L83) (InfluxDB storage plugin) don't use the parameter--`keywordsOfConten`t and `excludingKeywordsOfContent`. They don't support fuzzy query of `AbstractLogRecord.CONTENT`. Related PR #6120

### What you expected to happen

We should make H2LogQueryDAO and LogQuery support fuzzy query of `AbstractLogRecord.CONTENT` like [LogQueryEsDAO](https://github.com/apache/skywalking/blob/92f0ebf126fe242ee30f8ab8106b41f8ff39d656/oap-server/server-storage-plugin/storage-elasticsearch-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/elasticsearch/query/LogQueryEsDAO.java#L111) in ES storage plugin.

### How to reproduce

As mentioned above.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
We don't support fuzzy search on the 2 storages because they are not good at indexing and searching, or is poor performant, or is not recommended in production environment, I don't know how you will implement this?

**Comment by wu-sheng** [comment]
This is not a bug, it is designed likr this. Check the APIs, they response to UI whether this storage supports content fuzzy query.

**Comment by LIU-WEI-git** [comment]
Got it. Thanks for your explanation.
