### ISSUE TITLE
[Bug] XmlConfiguration cannot be cast to OapConfiguration

### ISSUE THREAD

**Issue by ayumiono** [apache/skywalking#7728]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

skywalking-oap:8.7.0 when i start the oap server local, it comes to an error org.apache.logging.log4j.core.config.xml.XmlConfiguration cannot be cast to org.apache.skywalking.oap.server.core.logging.log4j.OapConfiguration

it seems like the OapConfigurationFactory not working, i read the apache logging docs and the org.apache.logging.log4j.core.config.plugins.util.PluginManager source code，and i do not find  PluginManager .addPackage() method is invoked in server-core/logging code

i do not quite understand the mechanisms，if i miss any setting?

### What you expected to happen

none

### How to reproduce

none

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is not in the scope of SkyWalking.

**Comment by wu-sheng** [comment]
> skywalking-oap:8.7.0 when i start the oap server local, it comes to an error org.apache.logging.log4j.core.config.xml.XmlConfiguration cannot be cast to org.apache.skywalking.oap.server.core.logging.log4j.OapConfiguration

@kezhenxu94 But this description doesn't match the possible case, I am afraid. If something in default has `cast exception`, the OAP server can't start up.

**Comment by kezhenxu94** [comment]
> > skywalking-oap:8.7.0 when i start the oap server local, it comes to an error org.apache.logging.log4j.core.config.xml.XmlConfiguration cannot be cast to org.apache.skywalking.oap.server.core.logging.log4j.OapConfiguration
> 
> @kezhenxu94 But this description doesn't match the possible case, I am afraid. If something in default has `cast exception`, the OAP server can't start up.

Yes I agree absolutely that the default settings should be OK. That's why I ask @ayumiono to recheck and provide more information.
