### ISSUE TITLE
[Core] Metric data processing 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#7733]
### Description

This intends to track the progress of handling the metric data.

We slipped the topic into several tasks:

- [x] Protobuf APIs (https://github.com/apache/skywalking-banyandb/pull/57)
- [x] KV storage improvement: add interceptors on flushing and compacting to support value encoding and compression.(https://github.com/SkyAPM/badger/commit/7f8fa9a51476cfd07f7cf90d95d9b80dd70e8de7)
- [x] Measure module: parsing protocols, writing, reading.
- [ ] Query
- [ ] Liaison
- [ ] Java client
- [ ] OAP storage layer

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You are using same title as 7731

**Comment by hanahmily** [comment]
> You are using same title as 7731

If you referred to #7732 , it's about stream data instead of metrics

**Comment by wu-sheng** [comment]
Got it.

Please update the subtasks, we have to provide DDL APIs to support metrics in BanyanDB, including
1. Create metric entity
2. Read metadata and index metadata of entity
3. Support altering entity definition
