### ISSUE TITLE
[Feature] Add Alibaba Druid plugin

### ISSUE THREAD

**Issue by VictorZeng** [apache/skywalking#7735]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Druid is a database connection pool from Alibaba inc.

Provide Druid database connection pool plugin with skywalking java-agent.

### Use case

When the application service uses Druid connection pool, it tracks the acquisition and closing of connections.

### Related issues

nothing.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
When is the latest date of this project? I haven't heard it for a while.

**Comment by VictorZeng** [comment]
> When is the latest date of this project? I haven't heard it for a while.

druid the latest version 1.2.6 release on Apr, 2021.

**Comment by wu-sheng** [comment]
OK, then it is fine to have plugin for it.
