### ISSUE TITLE
[INFRA/eyes] Support for Ruby/Rails files

### ISSUE THREAD

**Issue by afriqs** [apache/skywalking#7744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

License headers for ruby (`.rb`) ans rails (`.erb`) files are not supported yet due to lack of `comment_style_id`.

### Use case

Add license headers to such files.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by afriqs** [comment]
Hi,

I would like to provide tests but I don't see how :shrug: 

When I `cd test && go test -v` I only see two passing tests : *TestConfigHeaderSpdxASF* and *TestConfigHeaderSpdxPlain*.

I think it may be related to `test/tesdata/include_test/with[out]_license` but don't know how ti use them...

Note : not a `go` developer :innocent:

**Comment by kezhenxu94** [comment]
Hi @afriqs , thank you. The `tests` directory serves as a demonstration data actually. And for new file support, you might want to add a case in https://github.com/apache/skywalking-eyes/blob/main/pkg/header/fix_test.go

**Comment by kezhenxu94** [comment]
No update for 1 year, closing

**Comment by pboling** [comment]
I've implemented ruby support to SkyWalking Eyes, but I'm not a Go expert, so I'd appreciate feedback!

**Comment by afriqs** [comment]
Hi, we finally added tests for ruby, erb and slim files. Hope this is ok now 😅
