### ISSUE TITLE
[Bug] java.lang.NumberFormatException in MysqlURLParser

### ISSUE THREAD

**Issue by wuguanyu** [apache/skywalking#7758]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

In some case, When jdbc url have no db information？ 
For example 
jdbc:mysql://ip:host?serverTimezone=Asia/Shanghai

![Uploading image.png…]()

### What you expected to happen

No numberFormat exception

### How to reproduce

Use jdbc:mysql://ip:host?serverTimezone=Asia/Shanghai In org.apache.skywalking.apm.plugin.jdbc.connectionurl.parser.MysqlURLParser

### Anything else

Use jdbc:mysql://ip:host?serverTimezone=Asia/Shanghai In org.apache.skywalking.apm.plugin.jdbc.connectionurl.parser.MysqlURLParser

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wuguanyu** [comment]
@Override
    public ConnectionInfo parse() {
        URLLocation location = fetchDatabaseHostsIndexRange();
        String hosts = url.substring(location.startIndex(), location.endIndex());
        String[] hostSegment = hosts.split(",");
        if (hostSegment.length > 1) {
            StringBuilder sb = new StringBuilder();
            for (String host : hostSegment) {
                if (host.split(":").length == 1) {
                    sb.append(host).append(":").append(DEFAULT_PORT).append(",");
                } else {
                    sb.append(host).append(",");
                }
            }
            return new ConnectionInfo(component, dbType, sb.substring(0, sb.length() - 1), fetchDatabaseNameFromURL());
        } else {
            String[] hostAndPort = hostSegment[0].split(":");
            if (hostAndPort.length != 1) {
                return new ConnectionInfo(component, dbType, hostAndPort[0], Integer.valueOf(hostAndPort[1]), fetchDatabaseNameFromURL(location
                        .endIndex()));
            } else {
                return new ConnectionInfo(component, dbType, hostAndPort[0], DEFAULT_PORT, fetchDatabaseNameFromURL(location
                        .endIndex()));
            }
        }
    }
The following java code throw NumberFormat exception Beacause of jdbcUrl have no db information
Integer.valueOf(hostAndPort[1])

**Comment by wu-sheng** [comment]
What do you mean `ip:host`? I am a little confused. Could you share a real connection URL? We are expecting `IP:port`

**Comment by wuguanyu** [comment]
> What do you mean `ip:host`? I am a little confused. Could you share a real connection URL? We are expecting `IP:port`
jdbc:mysql://127.0.0.1:3306?serverTimezone=Asia/Shanghai

**Comment by wu-sheng** [comment]
I feel you have read the codes with details. Do you have already known the issue and the way to fix?
You could submit a pull request to fix by yourself.

**Comment by wuguanyu** [comment]
> I feel you have read the codes with details. Do you have already known the issue and the way to fix?
> You could submit a pull request to fix by yourself.

Yes i read some source code,I find some code duplicate code in MssqlJtdsURLParser,MssqlJdbcURLParser.
I will try to fix this issue by myself

**Comment by wu-sheng** [comment]
OK, assigned to you. Thanks.
