### ISSUE TITLE
[Feature] set instance properties in json format: `agent.instance_properties_json`

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7762]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

> I find some configurations are in configurations.md , but not in the agent.config , such as ```agent.trace_segment_ref_limit_per_span``` 、```agent.instance_properties[key]=value``` . Otherwise , the configuration ```plugin.dubbo.consumer_provider_length_threshold ``` in the agent.config is not the same as ```plugin.dubbo.provider_arguments_length_threshold``` in the configurations.md.  

@dashanji can you open a pull request to fix this? For `agent.instance_properties[xxx]`, I think we also need to migrate to the format of `agent.instance_properties_json={}`.  `plugin.dubbo.consumer_provider_length_threshold` should be typo of `plugin.dubbo.consumer_length_threshold`

_Originally posted by @kezhenxu94 in https://github.com/apache/skywalking/issues/7470#issuecomment-922471256_

### Use case

For containerized scenarios, we should be able to set the `agent.instance_properties` easily via environment variables, instead of modifying the config file.

### Related issues

https://github.com/apache/skywalking/pull/7470#issuecomment-922471256

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Anyone who wants to take this, please reply and I can assign.

**Comment by deepto98** [comment]
@kezhenxu94 Hi, I would like to take this up, can you please assign it to me? Since I am new to the project, can you also please give a bit more context about the task, and the files which I should start looking at?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 Hi, I would like to take this up, can you please assign it to me? Since I am new to the project, can you also please give a bit more context about the task, and the files which I should start looking at?
> 
> 

Hi @deepto98 , thanks for the interest, the rationale behind this task is that, for containerized scenarios, the style of `agent.instance_properties[xxx]=xxx` is hard (if not impossible) to modify, using json style like `agent.instance_properties_json={xxx:yyy}`, the users can modify via environment variables.

**Comment by JaredTan95** [comment]
https://github.com/apache/skywalking-java/pull/67 supported
