### ISSUE TITLE
[Feature] Support for Apache HttpClient 5 plugin.

### ISSUE THREAD

**Issue by heihaozi** [apache/skywalking#7763]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Apache HttpClient 5 is considered stable and production ready. 
It is being actively maintained and supported. 
Can the Apache HttpClient 5 plugin be supported?

### Use case

Support for Apache HttpClient 5 plugin.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
>  Yes I am willing to submit a PR!

You clicked this, are you going to submit this feature?

**Comment by heihaozi** [comment]
> 
> 
> > Yes I am willing to submit a PR!
> 
> You clicked this, are you going to submit this feature?

Yes, I will.

**Comment by wu-sheng** [comment]
> > > Yes I am willing to submit a PR!
> > 
> > 
> > You clicked this, are you going to submit this feature?
> 
> Yes, I will.

Assigned. Contribution is always welcome.
