### ISSUE TITLE
[Client JS] The ```fetch``` API changes the return value type, and the business code cannot run normally

### ISSUE THREAD

**Issue by wuwen5** [apache/skywalking#7765]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Client Side Agent (apache/skywalking-client-js)

### What happened

```js
let innerOnConnectFinished = function () {
    fetchThen(fetch('/cim-server/cim/message/token'), (data) => bind(data))
};
```

![35186D73-A2D2-4B90-9E7F-72E3B47A74F8](https://user-images.githubusercontent.com/5037807/134296167-cac90f07-afad-4530-99d5-cc8b0d472464.png)
![569EE476-699C-40FA-9B8E-D54A56890C8A](https://user-images.githubusercontent.com/5037807/134296242-9e6df5bf-d1fd-4e38-a43f-7b2b86212742.png)

fetch.ts 

```diff
try {
    response = await originFetch(...args);
    return response
        .clone()
-      .json()        
-      .then((body: any) => body)
-      .catch((err: any) => err);
+     .clone(); 
}
```

 I don't know why we need these three lines, but if I delete it, everything will be fine

### What you expected to happen

```js
fetch(url).then(response => response.json())
```

### How to reproduce

```js
fetch(url).then(response => response.json())
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Fine0830** [comment]
The reason for error reporting is that the response data as json data. Perhaps it is text or other. The code can intercept http response body. Now it seems that we don't need it.

**Comment by wu-sheng** [comment]
> The reason for error reporting is that the response data as json data. Perhaps it is text or other. The code can intercept http response body. Now it seems that we don't need it.

@Fine0830 The text should be fine.
