### ISSUE TITLE
[Satellite] Support transmit Envoy ALS/Metric protocol

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#7774]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Envoy has a lot of observable data that can be analyzed. At present, OAP has provided support for analytical capabilities.
So we should providing protocol transmit ability in Satellite as well. The following is an introduction link for related protocols. Need to provide support for the v2 and v3 versions of ALS and Metrics respectively.

Metrics service: https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/metrics/v3/metrics_service.proto.html
ALS: https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/accesslog/v3/als.proto

### Use case

The satellite could transmit Envoy Metrics and ALS protocol data.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
v2 are required for both of them. The OAP backend supports them in the same time, please check whether satellite could be both.

**Comment by mrproliu** [comment]
> v2 are required for both of them. 

Sure, v2 and v3 versions need both of them.

> The OAP backend supports them in the same time, please check whether satellite could be both.

I have checked the OAP analysis code, there are combine the message content, but it needs to make sure v2 and v3 versions must be compatible. I think satellite could just transmit them, don't need to combine the message content.

**Comment by wu-sheng** [comment]
> I have checked the OAP analysis code, there are combine the message content, but it needs to make sure v2 and v3 versions must be compatible. I think satellite could just transmit them, don't need to combine the message content.

No, satellite doesn't need to change the content, just forward them.

**Comment by mrproliu** [comment]
> > I have checked the OAP analysis code, there are combine the message content, but it needs to make sure v2 and v3 versions must be compatible. I think satellite could just transmit them, don't need to combine the message content.
> 
> No, satellite doesn't need to change the content, just forward them.

Sure.
