### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ddwla4** [apache/skywalking#7785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

skywalking8.7.0版本，在高并發請求下，traceid會產生重複的。

### What you expected to happen

高并發場景，導致traceid重複

### How to reproduce

使用的是spring boot 2.3版本，集成了apm-toolkit-logback-1.x,版本為8.7.0。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please make sure you follow the issue template requirement. All things should be in English, and `reproduce` steps should include all details.
