### ISSUE TITLE
[Feature] Add Fastjson plugin 

### ISSUE THREAD

**Issue by VictorZeng** [apache/skywalking#7786]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Fastjson a fast JSON parser/generator for Java. It's the most popular json parsing library in China from Alibaba inc.

### Use case

When the application service uses Fastjson, it tracks the json serialization and deserialization(optional plug-in).

### Related issues

Nothing.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Make sense. Feel free to go
