### ISSUE TITLE
[Feature] Add ClickHouse JDBC plugin

### ISSUE THREAD

**Issue by wallezhang** [apache/skywalking#7815]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

ClickHouse® is a column-oriented database management system (DBMS) for online analytical processing of queries (OLAP). This plugin will trace sql execution as other jdbc plugin.

### Use case

When execute an sql, this plugin will fetch the sql and other information(like execution time, status) related to this execution.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wallezhang** [comment]
Hi @kezhenxu94 ,

I found that the JDBC driver of ClickHouse is implemented using HTTP protocol, so it will be handled by HTTPClient Plugin. And it can't be recognized as an db span through trace information. It looks like an ordinary http request, and the request path is always `/`, because of the sql is in the request body.

This plugin will intercept JDBC methods and insert a correct db span, but there are still other wrong type spans produced by HttpClient plugin, how should I exclude these? Any ideas?

**Comment by wu-sheng** [comment]
Is HttpClient in sync or async? If it is in sync, it is easy. Adding an exit span to the JDBC implementation, than its exit span disappears automatically.

**Comment by wallezhang** [comment]
> Is HttpClient in sync or async? If it is in sync, it is easy. Adding an exit span to the JDBC implementation, than its exit span disappears automatically.

It is in sync, I will try it. Thanks for reply.
