### ISSUE TITLE
[CLI] Support command `dependency instance` 

### ISSUE THREAD

**Issue by wankai123** [apache/skywalking#7822]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

e2e case require command `dependency instance` to get instance topology

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Hi @JarvisG495 since [you added](https://github.com/apache/skywalking-cli/pull/113) dependency service command, do you want to take care of this too? FYI @fgksgf

**Comment by JarvisG495** [comment]
> Hi @JarvisG495 since [you added](https://github.com/apache/skywalking-cli/pull/113) dependency service command, do you want to take care of this too? FYI @fgksgf

Yes, I'm going to take care of this as well.

**Comment by kezhenxu94** [comment]
> > Hi @JarvisG495 since [you added](https://github.com/apache/skywalking-cli/pull/113) dependency service command, do you want to take care of this too? FYI @fgksgf
> 
> Yes, I'm going to take care of this as well.

@JarvisG495 thank you very much 🙇🏻 assign to you

**Comment by JarvisG495** [comment]
> > > Hi @JarvisG495 since [you added](https://github.com/apache/skywalking-cli/pull/113) dependency service command, do you want to take care of this too? FYI @fgksgf
> > 
> > 
> > Yes, I'm going to take care of this as well.
> 
> @JarvisG495 thank you very much 🙇🏻 assign to you

My pleasure : )
I have submitted a PR in skywalking-cli.
