### ISSUE TITLE
[Feature] When can skywalking support hbase for storage？

### ISSUE THREAD

**Issue by zhyhzhylove** [apache/skywalking#7835]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Due to business needs, in online env, trace data is collected in full, approximately 25 billion pieces of data are generated every day，which is almost 10T. Now using es for storage, the cost is too high。Hbase might be a good choice

### Use case

Use hbase to store trace data

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I am afraid not, 10T for ElasticSearch is not a big issue. We don't have anyone working on hbase or similar tech stack.
SkyWalking is an APM, with incoming native swlf-built database. We don't like idea about using big data for operation team.
