### ISSUE TITLE
[Bug] There is a problem with elasticsearch index query 

### ISSUE THREAD

**Issue by jaredhu** [apache/skywalking#7836]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The indexes of es are created on a daily basis, and the index we use when querying is not added. * To match all, when querying, it will directly prompt that no index can be found.
![image](https://user-images.githubusercontent.com/6262851/135222010-ce7c117b-f9d0-4771-9cca-6a0a0688982a.png)
![image](https://user-images.githubusercontent.com/6262851/135222098-72a4642a-2c0b-45ac-9eea-fc50905e76b7.png)

### What you expected to happen

![image](https://user-images.githubusercontent.com/6262851/135222231-283f7182-069b-43ce-86c0-bdfd3900883a.png)

### How to reproduce

It can be reproduced with version 8.8.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
What query are you doing? Our demo.skywalking.apache.org is working without error.

**Comment by kezhenxu94** [comment]
@jaredhu can you also provide the ES version?

**Comment by jaredhu** [comment]
7.10.0

**Comment by jaredhu** [comment]
@kezhenxu94 
![image](https://user-images.githubusercontent.com/6262851/135225014-218f2da0-72e0-4729-aff6-8bf73060f41f.png)
Exception thrown by the latest code running locally

**Comment by wu-sheng** [comment]
This looks like template missing?

**Comment by jaredhu** [comment]
template？where do I get it

**Comment by wu-sheng** [comment]
`cpm.*` is not an expected way for query. There is a `xxx_cpm` template to define this already.

**Comment by wu-sheng** [comment]
When OAP server boots, the template is created automatically, unless you have an index having the same name.

**Comment by jaredhu** [comment]
The image I got from the hub (docker pull apache/skywalking-ui:8.8.0)

**Comment by jaredhu** [comment]
No, there is no one with the same name, I emptied it all

**Comment by jaredhu** [comment]
Now, I got the latest code on github, and I have the same problem when running locally

**Comment by wu-sheng** [comment]
There is nothing related to docker, it is about ElasticSearch. 
Try to debug `StorageEsInstaller#isExists` and `StorageEsInstaller#createTimeSeriesTable`.

**Comment by jaredhu** [comment]
> `cpm.*` is not an expected way for query. There is a `xxx_cpm` template to define this already.

Is this the problem? How can I fix it?

**Comment by wu-sheng** [comment]
Check what I replied. I am not sure what is bug yet.

**Comment by jaredhu** [comment]
> 与 docker 无关，它与 ElasticSearch 相关。 尝试调试`StorageEsInstaller#isExists`和`StorageEsInstaller#createTimeSeriesTable`。

no-init or init?

**Comment by wu-sheng** [comment]
No difference.

**Comment by jaredhu** [comment]
> 与 docker 无关，它与 ElasticSearch 相关。 尝试调试`StorageEsInstaller#isExists`和`StorageEsInstaller#createTimeSeriesTable`。

I have read here, it was created normally

**Comment by jaredhu** [comment]
![image](https://user-images.githubusercontent.com/6262851/135226410-1000976c-7414-4f91-922d-449037936cac.png)

**Comment by wu-sheng** [comment]
Again, this is index, not template.

**Comment by jaredhu** [comment]
![image](https://user-images.githubusercontent.com/6262851/135226877-347e387c-cb76-4724-80c1-25e98103bb37.png)
The concept of the template is not clear, so it is not clear how to try

**Comment by jaredhu** [comment]
Oh, I found the template, and I also saw -* does exist, but why is it not used when querying?
![image](https://user-images.githubusercontent.com/6262851/135227779-fc78c71d-8606-4193-8ff1-9b3633388b13.png)

**Comment by jaredhu** [comment]
StorageEsInstaller#isExists  There are bugs and need to be fixed. The registered ones do not contain templates

**Comment by wu-sheng** [comment]
> StorageEsInstaller#isExists There are bugs and need to be fixed. The registered ones do not contain templates

Could you be more clear about what do you mean?

**Comment by wu-sheng** [comment]
I can see @kezhenxu94 activated e2e testing for your case.

https://github.com/apache/skywalking/runs/3741642509?check_suite_focus=true

You could check the logs, it seems everything is working for 7.10.0 and 7.10.1

**Comment by jaredhu** [comment]
String tableName = IndexController.INSTANCE.getTableName(model);

Only the aggregation method is considered here

IndexController.LogicIndicesRegister.registerRelation(model.getName(), tableName);

The mapping relationship registered here is actually only the aggregation method.
When querying, the template should be used (indexPatterns=[saas-apm_alarm_record-*]). What I want is whether the indexPatterns of the template can be registered in this map

**Comment by wu-sheng** [comment]
I am sorry, what do you mean `what I want`. I thought this is a bug report.

**Comment by wu-sheng** [comment]
Again, we use template name to query, not `xxx-*` to query.

**Comment by jaredhu** [comment]
Oh, sorry, I think whether I can register the indexPatterns of the template in this map. When I use it, I find that I will get it from this map, so, I can use indexPatterns to query

**Comment by wu-sheng** [comment]
What you are using? If you write something private, it is out of community's scope.

**Comment by jaredhu** [comment]
> Again, we use template name to query, not `xxx-*` to query.

Maybe I still don’t understand, at least the query is problematic at the moment

**Comment by jaredhu** [comment]
> What you are using? If you write something private, it is out of community's scope.

I'm just telling my thoughts, it still depends on how you deal with it

**Comment by wu-sheng** [comment]
This is why we run e2e testing, and just showed your the logs. 

https://github.com/apache/skywalking/runs/3741642509?check_suite_focus=true

I am not saying this is not an issue, but we can't reproduce it by following your information.

**Comment by wu-sheng** [comment]
What you asked for change doesn't make sense. ElasticSearch template is already a native mechanism to do the things. What you proposed is not required.

If your ElasticSearch can't be queried by template name, which you checked it exists, then, I am totally confused.

**Comment by jaredhu** [comment]
e2e testing is normal, so, how can I troubleshoot this problem now?

**Comment by wu-sheng** [comment]
What kind of ElasticSearch are you using? Someone set up for you? Have you tried a local and totally new ElasticSearch?

**Comment by jaredhu** [comment]
Yes, assigned by the engineer, it’s a bit troublesome to change es

**Comment by jaredhu** [comment]
Is this related to es? There are indexes in es, but there is a problem with the url generated when querying

**Comment by wu-sheng** [comment]
Please learn ElasticSearch template first. You are not following the context. At least understanding what we are saying, then reply, rather than repeating your own words.

**Comment by jaredhu** [comment]
![image](https://user-images.githubusercontent.com/6262851/135234456-50433f20-b147-4ca9-9885-0f6d3aa9f162.png)
Is it normal for you to generate such a URL?

**Comment by wu-sheng** [comment]
As far as I know, yes. This is a template name. Why are you keeping asking me same thing?

**Comment by jaredhu** [comment]
Because it is impossible to find things in es, an error was reported directly
![image](https://user-images.githubusercontent.com/6262851/135235414-e395f6c5-39ae-4117-967f-5b04f0ddaae3.png)

**Comment by wu-sheng** [comment]
That is exactly why I ask you to check what is specially for you ElasticSearch. Why does template do not work at your side.

**Comment by jaredhu** [comment]
> That is exactly why I ask you to check what is specially for you ElasticSearch. Why does template do not work at your side.

so, may be the reason of es, I will study this

**Comment by jaredhu** [comment]
![image](https://user-images.githubusercontent.com/6262851/135245615-e3f3e0e5-7822-4745-830a-6cff5e8a16a4.png)
I think I know, you used alias search first, and some of the indexes created did not have aliases.

**Comment by wu-sheng** [comment]
All indices should have an alias, because we used `prefix` match.

**Comment by jaredhu** [comment]
I think it may be the problem of k8s. K8s has been deployed with multiple historical versions. It may be caused by some cached jar packages. After I initialized the index of es with the tar package directly on the machine, it can run normally.
