### ISSUE TITLE
[Bug] zipkin-receiver-plugin not include in 8.8.0, ModuleNotFoundException: [receiver_zipkin] missing,

### ISSUE THREAD

**Issue by offSwitch** [apache/skywalking#7842]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

org.apache.skywalking.oap.server.library.module.ModuleNotFoundException: [receiver_zipkin] missing.
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:55) ~[library-module-8.8.0.jar:8.8.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-starter-8.8.0.jar:8.8.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-8.8.0.jar:8.8.0]

### What you expected to happen

work correctly

### How to reproduce

receiver_zipkin:
  selector: ${SW_RECEIVER_ZIPKIN:default}
  default:
    host: ${SW_RECEIVER_ZIPKIN_HOST:0.0.0.0}
    port: ${SW_RECEIVER_ZIPKIN_PORT:9411}
    contextPath: ${SW_RECEIVER_ZIPKIN_CONTEXT_PATH:/}
    jettyMinThreads: ${SW_RECEIVER_ZIPKIN_JETTY_MIN_THREADS:1}
    jettyMaxThreads: ${SW_RECEIVER_ZIPKIN_JETTY_MAX_THREADS:200}
    jettyIdleTimeOut: ${SW_RECEIVER_ZIPKIN_JETTY_IDLE_TIMEOUT:30000}
    jettyAcceptorPriorityDelta: ${SW_RECEIVER_ZIPKIN_JETTY_DELTA:0}
    jettyAcceptQueueSize: ${SW_RECEIVER_ZIPKIN_QUEUE_SIZE:0}
    instanceNameRule: ${SW_RECEIVER_ZIPKIN_INSTANCE_NAME_RULE:[spring.instance_id,node_id]}

### Anything else

compare with 8.7.0
![image](https://user-images.githubusercontent.com/11695496/135369840-c7106e3d-b9e2-4257-93f5-5a06cca6d469.png)
![image](https://user-images.githubusercontent.com/11695496/135369870-a3e1e4c5-1bd9-49c2-8726-a0c76733222a.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Hi @offSwitch , thanks for reporting, I've created a pull request to fix this, but before the 8.9.0 release, you can compile the `zipkin-receiver-plugin` module and download `zipkin2` dependencies, then put them into the `oap-libs` directory.

**Comment by ZPerling** [comment]
```
2021-10-21 10:32:02,995 org.apache.skywalking.oap.server.starter.OAPServerBootstrap 57 [main] ERROR [] - [receiver_jaeger] missing.
org.apache.skywalking.oap.server.library.module.ModuleNotFoundException: [receiver_jaeger] missing.
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:55) ~[library-module-8.8.1.jar:8.8.1]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-starter-8.8.1.jar:8.8.1]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-8.8.1.jar:8.8.1]
```

The sampe problem

**Comment by wu-sheng** [comment]
> ```
> 2021-10-21 10:32:02,995 org.apache.skywalking.oap.server.starter.OAPServerBootstrap 57 [main] ERROR [] - [receiver_jaeger] missing.
> org.apache.skywalking.oap.server.library.module.ModuleNotFoundException: [receiver_jaeger] missing.
> 	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:55) ~[library-module-8.8.1.jar:8.8.1]
> 	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-starter-8.8.1.jar:8.8.1]
> 	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-8.8.1.jar:8.8.1]
> ```
> 
> The sampe problem

Fixed in the master and will be included in 8.9.0.

**Comment by ZPerling** [comment]
> > ```
> > 2021-10-21 10:32:02,995 org.apache.skywalking.oap.server.starter.OAPServerBootstrap 57 [main] ERROR [] - [receiver_jaeger] missing.
> > org.apache.skywalking.oap.server.library.module.ModuleNotFoundException: [receiver_jaeger] missing.
> > 	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:55) ~[library-module-8.8.1.jar:8.8.1]
> > 	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-starter-8.8.1.jar:8.8.1]
> > 	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-8.8.1.jar:8.8.1]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The sampe problem
> 
> Fixed in the master and will be included in 8.9.0.

my promblem caused by receiver_jaeger, not receiver_zipkin

**Comment by offSwitch** [comment]
> 

Maybe you could try using OpenTelemetry to collect jaeger's link trace information and convert it to skywalking format

**Comment by offSwitch** [comment]
@jiangguilong2000 
Maybe you could try using OpenTelemetry to collect jaeger's link trace information and convert it to skywalking format

**Comment by 470390366** [comment]
> @jiangguilong2000 Maybe you could try using OpenTelemetry to collect jaeger's link trace information and convert it to skywalking format

Do you use zipkin receiver to upload trace data to skywalking? I encountered some problems when using zipkin receiver and would like to discuss with you.

**Comment by berylshow** [comment]
> 链接跟踪信息

how to do this?

**Comment by berylshow** [comment]
> @jiangguilong2000 也许您可以尝试使用 OpenTelemetry 收集 jaeger 的链接追踪信息标记其转换为 Skywalking 格式

how to do this?thanks
