### ISSUE TITLE
Add “.exe” suffix to the Windows compiled executable program for  skywalking-eyes

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7845]
### Discussed in https://github.com/apache/skywalking/discussions/7844

<div type='discussions-op-text'>

<sup>Originally posted by **codeglzhang** September 30, 2021</sup>
 In skywalking-infra-e2e, we can use `make build` to get a Windows executable program `skywalking-eyes\bin\windows\license-eye`. However, in the command line of Windows, whether the file is an executable program is determined by whether the file has a specific suffix, such as ".exe". Thus, commands such as  `bin/darwin/license-eye -c test/testdata/.licenserc_for_test_fix.yaml header check` will not be executed correctly under Windows. 
![image](https://user-images.githubusercontent.com/17879307/135402537-93e625f4-d376-4995-b692-344896a18938.png)
After renaming the file `skywalking-eyes\bin\windows\license-eye` to `skywalking-eyes\bin\windows\license-eye.exe`, the command is executed.
![image](https://user-images.githubusercontent.com/17879307/135402746-a394f342-8e98-422c-bd38-c822385bfb31.png)
The same is true for `skywalking-infra-e2e`.
</div>

**Comment by wu-sheng** [comment]
If this has `.exe` suffix, then we need to be careful about dealing with `skywalking-eyes` checking or others in ASF doing check for our release. This could be identified as binary file, which is not allowed in the ASF source release. Meanwhile, according to your description, this should have a very clear document about what this exe is.

**Comment by wu-sheng** [comment]
And for more importantly, does this enough for Windows? We have `swtcl`(having Windows binary, but set up Linux's binary only) and many other scripts, are they working too?

The reason I asked about is that, once we say something in the doc, these `a/b/c` are for Windows, we actually are saying, we are going to support `infra-e2e` in Windows, and users even expect the consistent setting for Windows and MacOS/Linux.

**Comment by kezhenxu94** [comment]
> If this has `.exe` suffix, then we need to be careful about dealing with `skywalking-eyes` checking or others in ASF doing check for our release. This could be identified as binary file, which is not allowed in the ASF source release. Meanwhile, according to your description, this should have a very clear document about what this exe is.

`.exe` is definitely binary file, and it is only distributed in binary tar, not source tar.

This issue is just to add a suffix `.exe` to the binary files, which were already distributed but not work because of lack of `.exe`.

> And for more importantly, does this enough for Windows? We have swtcl(having Windows binary, but set up Linux's binary only) and many other scripts, are they working too?

> The reason I asked about is that, once we say something in the doc, these a/b/c are for Windows, we actually are saying, we are going to support infra-e2e in Windows, and users even expect the consistent setting for Windows and MacOS/Linux.

For `license-eye` it should be supported in Windows, but for `infra-e2e` it depends on how the users compose the control file, I'll just remove the label `infra-e2e`.

**Comment by wu-sheng** [comment]
> This issue is just to add a suffix .exe to the binary files, which were already distributed but not work because of lack of .exe.

Once it could be generated/compiled and located in binary tar only, it is good.
