### ISSUE TITLE
[Feature] add support to OpenTelemetry trace receiver

### ISSUE THREAD

**Issue by congzhangzh** [apache/skywalking#7848]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I use open telemetry on .net core, and some other teams use Skywalking, we want to mix the trace context.

Hope skywalking add open telemetry receiver, so that’s possible to use oltp export to send trace to skywalking.

Btw, that will need some custom context extract and inject for tech boundaries, I will do that on dotnet side.

Ref:

1. https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/README.md

2. https://skywalking.apache.org/blog/2021-02-07-infrastructure-monitoring/

3. https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md

4. https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Context/Propagation/CompositeTextMapPropagator.cs

5. https://github.com/apache/skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Propagation-Headers-Protocol-v3.md

6. https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-receivers.md
7. https://github.com/apache/skywalking/blob/master/docs/en/protocols/HTTP-API-Protocol.md

8. https://github.com/apache/skywalking-data-collect-protocol/blob/master/language-agent/Tracing.proto

9. https://github.com/apache/skywalking/blob/master/docs/en/protocols/README.md#language-based-native-agent-protocol

Tks,
Cong

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If anything is going to happen on dotnet, it is out of ASF scope. That project belongs to SkyAPM community from legal perspective.
We discussed this topic, which is similar with Zipkin. We can't see the chance to analyze metrics and topology from its traces too.

**Comment by wu-sheng** [comment]
If you transfer trace format from their sides, and follow SkyWalking trace format, we don't need to open new receiver.

**Comment by congzhangzh** [comment]
> If you transfer trace format from their sides, and follow SkyWalking trace format, we don't need to open new receiver.

Tks, can you provide some compare table about semantics and  name/value spec between skywalking and open telemetry?

I can only inspire by node implement now, https://github.com/apache/skywalking-nodejs/blob/master/src/agent/protocol/grpc/SegmentObjectAdapter.ts

https://github.com/apache/skywalking-nodejs/blob/master/src/agent/protocol/grpc/clients/TraceReportClient.ts

**Comment by congzhangzh** [comment]
I need these information to do:
1. Extract for income
2. Inject for outcome
3. Export implement

**Comment by wu-sheng** [comment]
This is SkyWalking protocol, https://skywalking.apache.org/docs/main/latest/en/protocols/readme/#language-based-native-agent-protocol

Sorry, we don't have such table to match, due to we don't support this.

**Comment by congzhangzh** [comment]
Ok, tks, I will try later

Maybe dotnet implement can give some more inspire

https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/src/SkyApm.Core/Tracing/CarrierPropagator.cs

**Comment by congzhangzh** [comment]
Btw, a basic idea  Just for reference if some other one need:
1. Use http api to do trace push for quick start, https://skywalking.apache.org/docs/main/latest/en/protocols/http-api-protocol/ , use bulk mode for performance
2. A new propagator base on https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Context/Propagation/B3Propagator.cs
3. a new exporter base on https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.Zipkin/ZipkinExporter.cs

**Comment by wu-sheng** [comment]
`Cross Process Propagation Headers Protocol v3` and `SkyWalking Trace Data Protocol v3` are required if you just set up a MVP. Others are recommended due to SkyWalking's other agents, especially Java, implemented all of them.

**Comment by congzhangzh** [comment]
Ok, tks

**Comment by wu-sheng** [comment]
@congzhangzh With one month, do you have anything to update?

**Comment by congzhangzh** [comment]
> @congzhangzh With one month, do you have anything to update?

No progress now. I use skywalking directly in our dotnet core microservice to meet the project deadline,
It's easy and magic by the way:)

As all other java spring projects all use skywalking, this is the easy path for my team.

BTW the java agent system will automate intercept so much more type of manager beans and function call ,  dotnet part is very limit.

how to extend it to use custom EventSource and activate in System.Diagnostic namespace?

**Comment by wu-sheng** [comment]
> No progress now. I use skywalking directly in our dotnet core microservice to meet the project deadline,
It's easy and magic by the way:)
As all other java spring projects all use skywalking, this is the easy path for my team.

Thanks for update. Then, I would close this issue. I talked from time to time with community users, they all eventually choose native agents rather than OpenTelemetry. Which is reasonable as most agents are out of box.

> BTW the java agent system will automate intercept so much more type of manager beans and function call , dotnet part is very limit.
how to extend it to use custom EventSource and activate in System.Diagnostic namespace?

I think you need to open discussion with that project maintainers. DotNet ecosystem is not as active as other languages, from what I am seeing in SkyWalking.

**Comment by berylshow** [comment]
@wu-sheng Please~ I open the Zipkin-receiver  in skywalking（8.9.1）, and then export the Zipkin format using the opentelemetry-collector-contrib(zipkinexporter). Can it display trace in skywalking? I did this, but there are prompts and errors. I think I may not use it correctly. Can you tell me how to configure it correctly? Thankyou~
Errors are reported as follows:
2022-05-07T09:43:05.081Z        error   exporterhelper/queued_retry_inmemory.go:109     Exporting failed. No more retries left. Dropping data.   {"kind": "exporter", "name": "zipkin", "error": "max elapsed time expired failed the request with status code 415", "dropped_items": 2}
The configuration is as follows:  
      zipkin:
        endpoint: http://skywalking-oap.skywalking:11800
        format: proto
        tls:
          insecure: true

**Comment by wu-sheng** [comment]
@berylshow This is not a place for you to drop random OpenTelemetry logs. 

If you want to follow Zipkin receiver's latest update/fix, search the PR list, https://github.com/apache/skywalking/pulls?q=is%3Apr+zipkin+is%3Aclosed.

OpenTelemetry's logs are not our responsibility.
