### ISSUE TITLE
[Bug] JavaAgent could collect server info (CPU, Memory) but no trace info.

### ISSUE THREAD

**Issue by Duytq7** [apache/skywalking#7850]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Please, answer me to this situation:
- Module use JDK 8+, wrapper tanuki
- skywalking could collect server info (CPU, Memory) but no trace info.
- no unusual log (WARN or ERROR level).

### What you expected to happen

Skywalking could collect server info (CPU, Memory) and trace info

### How to reproduce

I think you can support me by checking config'app

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You don't provide enough message to indi the status.
