### ISSUE TITLE
[Feature] skywalking插件支持jersey

### ISSUE THREAD

**Issue by xiongshiyan** [apache/skywalking#7855]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

skywalking插件支持jersey

### Use case

skywalking的插件支持jersey吗？我的项目使用了vertx+jersey，jersey作为表现层的接口框架，通过提供类似Spring的注解来表达URI。例如@Path，@GET，@POST等。我集成skywalking的agent之后，能发现这个service，但是不能发现endpoint，所以我怀疑是skywalking不支持jersey，因为我另外一个项目纯使用vertx web是没问题的。

### Related issues

https://github.com/apache/skywalking/issues/2780

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
All official discussion of SkyWalking must be in English. We have provided QQ groups for Chinese discussion channel.
All plugins of SkyWalking are contributed by the community.
