### ISSUE TITLE
[Feature] Add apache kylin jdbc plugin

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#7869]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Apache Kylin™ is an open source, distributed Analytical Data Warehouse for Big Data; it was designed to provide OLAP (Online Analytical Processing) capability in the big data era. By renovating the multi-dimensional cube and precalculation technology on Hadoop and Spark, Kylin is able to achieve near constant query speed regardless of the ever-growing data volume. Reducing query latency from minutes to sub-second, Kylin brings online analytics back to big data.

### Use case

when we use apache kylind jdbc to get data, this plugin can get the executed sql and  target server,  execution time,  execution status。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to submit a pull request?

**Comment by xu1009** [comment]
> Are you going to submit a pull request?

yes，the plugin in my project has already worked, now i am reading to submit a pull request

**Comment by xu1009** [comment]
> the

@wu-sheng  follow the test doc，i stuck in scenario test，the mock collector in the docker container can not receview data, but local(depoly mock collector can get data from agent) is ok，the agent config backend_service is 127.0.0.1:11800 or 127.0.0.1:19876 in mock collector doc, or other?

**Comment by xu1009** [comment]
> There are hundreds of cases there, have you tried them?

i find the problem, the entryService is very slow，but the test curl set time out 3s，when curl time out and then get receive data from mock collector，the entryService still not end， so the segments is null

**Comment by wu-sheng** [comment]
Make your test service as fast as possible. We have limited resources for CI, but we have to test all plugins in most changes.
