### ISSUE TITLE
[Bug] TracePathMatcher should match pattern "**" with paths end by "/"

### ISSUE THREAD

**Issue by sialais** [apache/skywalking#7875]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

we config trace ignore paths by "agent/config/pm-trace-ignore-plugin.config", but found paths ends by "/" are not ignored with "**".

example configuration in pm-trace-ignore-plugin.config:
```text
trace.ignore_path=/v1/kv/config/**
```
request path "/v1/kv/config/someurl/" is not ignored.

### What you expected to happen

request path "/v1/kv/config/someurl/" (end with slash) should be ignored, as ""/v1/kv/config/someurl"(not end with slash)

### How to reproduce

just run agent with example config.

### Anything else

Ant path match style should match paths end with slash. [Spring AntPathMatcher](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html).

In skywalking-java-agent, there are unit tests for this, but they do not act in the way "ant path matcher" describes.

- https://github.com/apache/skywalking-java/blob/v8.7.0/apm-sniffer/optional-plugins/trace-ignore-plugin/src/test/java/org/apache/skywalking/apm/plugin/trace/ignore/TracePathMatcherTest.java#L62
- https://github.com/apache/skywalking-java/blob/v8.7.0/apm-sniffer/optional-plugins/trace-ignore-plugin/src/test/java/org/apache/skywalking/apm/plugin/trace/ignore/TracePathMatcherTest.java#L97

they should return true, as described in [skywalking doc](https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/agent-optional-plugins/trace-ignore-plugin/#how-to-configure) 

> The current matching rules follow Ant Path match style , like /path/*, /path/**, /path/?.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Welcome to submit a pull request to fix and add a new UT to cover new case.

**Comment by newboy2004** [comment]
i want to submit a pull request to fix it  and add a new UT
please assign it to me!

**Comment by wu-sheng** [comment]
Assigbed

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-java/pull/72 gets no update.

**Comment by DominikHubacek** [comment]
Hi, I d like to fix this issue, please assign it to me.

**Comment by wu-sheng** [comment]
> Hi, I d like to fix this issue, please assign it to me.

Done, please refer to precious PR, there are some edge case discussions there.

**Comment by DominikHubacek** [comment]
> > Hi, I d like to fix this issue, please assign it to me.
> 
> Done, please refer to precious PR, there are some edge case discussions there.

Which PR ?

**Comment by wu-sheng** [comment]
> https://github.com/apache/skywalking-java/pull/72 gets no update.

This one.

**Comment by DominikHubacek** [comment]
@wu-sheng  I created PR - but I am unable to set you for review
PR: https://github.com/apache/skywalking-java/pull/81

**Comment by wu-sheng** [comment]
Review will take time. You submitted at my night. 😄
I have pinged the plugin author.
