### ISSUE TITLE
[Nodejs][Bug] Getting error log "Error installing plugin mysql2 *" when start agent

### ISSUE THREAD

**Issue by chzhuo** [apache/skywalking#7879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Server Side Agent (apache/skywalking-nodejs)

### What happened

Getting error log "Error installing plugin mysql2 *" when run `start()`

### What you expected to happen

no error log

### How to reproduce

I have only two files  

package.json
```json
{
  "name": "mynode",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "mysql2": "^2.3.0",
    "skywalking-backend-js": "^0.3.0"
  }
}

```
  
index.js
```js
const { default: agent } = require('skywalking-backend-js');

agent.start({
    serviceName: 'boblog',
    serviceInstance: 'boblog-1',
    collectorAddress: '10.0.5.198:12800',
});

```
nodejs version: v14.16.1
Then run command `node index.js` 
![image](https://user-images.githubusercontent.com/10919124/136641828-07a1d039-2b2d-4619-a9bf-6b25e5eca083.png)

### Anything else

I traced the error and found throwing from this line
![image](https://user-images.githubusercontent.com/10919124/136641790-674b8435-3517-41f4-a822-1be25acc065b.png)

https://github.com/apache/skywalking-nodejs/blob/master/src/core/PluginInstaller.ts#L65

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Hi @chzhuo thanks for reporting! First of all, failing to install a plugin does no harm if you're not using that library, but your demo application `index.js` is also meaningless and it exits immediately even if the mysql2 plugin succeeded to install because you don't have any real server running.

**Comment by chzhuo** [comment]
I get the same error log in an online app that connects the Mysql server by `mysql2`, so I use this demo to reproduce this error.  
I think mysql2-plugin did not work well when getting this error log.
