### ISSUE TITLE
[Feature] Add okhttp 2.x plugin

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#7889]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

OkHttp is an HTTP client，now，skywalking has support 3.x and 4.x version, 2.x is different, so plan to support  okhttp 2.x plugin

### Use case

when we use OkHttp 2.x version post request, the plugin can get request message

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-java/pull/49
