### ISSUE TITLE
[Feature] [Satellite] Prometheus Fetcher support to configure TLS for scrape in kubernetes servicediscovery situation

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#7890]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When the target service enabled SSL/TLS and deployed in k8s, we have to support users to configure SSL/TLS for prometheus scrape job.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No update in 26 days, if there is no one working on this, we could close this for now.
