### ISSUE TITLE
[Feature] [Satellite] Support to configure re-label 

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#7891]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In k8s, Satellite fetches the metrics and then puts some label like 'instance'. But as you know, 'instance' is preserved for SW OAP. So I think we cloud support to configure re-label by users.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This makes sense, are you or someone going to contribute this?

**Comment by dmsolr** [comment]
I and @gxthrj will do this next month(maybe). If anyone is interesting, can assign him.

**Comment by wu-sheng** [comment]
No update in 26 days, if there is no one working on this, we could close this for now.
