### ISSUE TITLE
[Bug] [Satellite] Missing histogram type metrics 

### ISSUE THREAD

**Issue by dmsolr** [apache/skywalking#7892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Satellite (apache/skywalking-satellite)

### What happened

Satellite Prometheus Fetcher module sends meter data to OAP, and then we cannot see any histogram type metrics. (I am sure I have some histogram type metrics in target service).

I logged the meter data in `MeterServiceHandler#collect()` like this:
```java
public StreamObserver<MeterData> collect(StreamObserver<Commands> responseObserver) {
    final MeterProcessor processor = processService.createProcessor();
    return new StreamObserver<MeterData>() {
        @SneakyThrows
        @Override
        public void onNext(MeterData meterData) {
            System.out.println(ProtoBufJsonUtils.toJSON(meterData));

            try (HistogramMetrics.Timer ignored = histogram.createTimer()) {
                processor.read(meterData);
            } catch (Exception e) {
                errorCounter.inc();
                log.error(e.getMessage(), e);
            }
        }
  ...
```

### What you expected to happen

Can found histogram type metrics

### How to reproduce

deploy a service and expose metrics by http server.
deploy oap.
deploy satellite and configure scrape job and client.
 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@gxthrj Please take a look.
