### ISSUE TITLE
[Feature] Add MicroBench module to make it easier for developers to write JMH TEST

### ISSUE THREAD

**Issue by CalvinKirs** [apache/skywalking#7910]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When I wanted to write JMH Test in SkyWalking, I found that: JMHTest is distributed in various modules, and each class needs to do things like setting basic properties: For example:

```
 public static void main(String[] args) throws RunnerException, FileNotFoundException {

        Options opt = new OptionsBuilder()
            .include(EndpointGroupingBenchmark4Openapi.class.getName())
            .addProfiler(GCProfiler.class)
            .jvmArgsAppend("-Xmx512m", "-Xms512m")
            .forks(1)
            .build();

        new Runner(opt).run();
    }
```

### Use case

Maybe we can create a MicroBench module to provide basic abstract classes,
The default settings include:

Warmup Iterations: 10
Measure Iterations: 10
Number of Forks: 2

etc...

These settings can be customized through system properties at runtime.

Its name may be like this: AbstractMicrobenchmark, the developer is writing JMH TEST needs to make his JMH Test extend the AbstractMicrobenchmark, which makes sure the test gets run through JUnit and configures some defaults:

another advantage is that in terms of code structure, all JMH Tests are separated from ordinary Tests.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
What module? Do you mean maven module?

**Comment by CalvinKirs** [comment]
> What module? Do you mean maven module?

Like this.

https://github.com/netty/netty/tree/4.1/microbench

https://github.com/netty/netty/tree/4.1/microbench/src/main/java/io/netty/microbench/util

We can provide some basic JMH classes so that writing the JMH Test can be much easier.

**Comment by wu-sheng** [comment]
I think SkyWalking has `server-testing` maven module to host base codes for testing. If you want to add and reflect something, welcome to submit pull requests.
