### ISSUE TITLE
[CLI][Feature] Require commands to manage UI configuration.

### ISSUE THREAD

**Issue by wankai123** [apache/skywalking#7911]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Storage E2E need to verify UI template: get, add, change, disabled 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Relate to https://github.com/apache/skywalking/issues/8477
