### ISSUE TITLE
[Bug] Adding agents affects spring AOP

### ISSUE THREAD

**Issue by 457775987** [apache/skywalking#7915]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

After I add an agent, a class defaultaopproxyfactory in spring AOP will have one more field by default. This class is a serialized class, resulting in a mismatch in the deserialization suid
![join-agent](https://user-images.githubusercontent.com/2177178/137060663-be4dcabe-40a3-45b7-a6d8-e6fd0dacaf2f.png)
![no-agent](https://user-images.githubusercontent.com/2177178/137060668-04500170-32f8-4e4c-9f48-366e84b5f927.png)

### What you expected to happen

 Adding agent does not affect the existing structure 。

### How to reproduce

。。。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
All issues should have good title and reported in English.

**Comment by wu-sheng** [comment]
Yes, this field is planned to be added, and a lot of plugins require this field to provide high performance. That is one of many reasons of SkyWalking agent having such good performance

**Comment by 457775987** [comment]
At present, spring security should serialize this class to redis. We directly join skywalking through javaagent without other special operations. At present, because the additional field of agent affects suid calculation, we can only deal with spring security?

**Comment by 457775987** [comment]
Sorry, it's translated in English by software. I want to explain that this defaultaopproxyfactory is saved by spring security after the user logs in. I didn't do this. When I request an address, it will be intercepted by spring security and go to redis to obtain the user information. Can it be solved only through spring security 。
（抱歉，英文使用软件翻译的，我的意思想说明，这个DefaultAopProxyFactory是spring security在用户登录之后保存的，我没有做这个事情，当我请求一个地址的时候，会被spring security拦截，前往redis获取用户信息反序列化出现的，是不是只能通过spring security解决）

**Comment by wu-sheng** [comment]
OK, I may add something enhancing this later. But, generally, Spring should not do like this.

**Comment by 457775987** [comment]
Thank you. Can you release a version after modification, and then close the issue so that I can receive notifications

**Comment by wu-sheng** [comment]
> Thank you. Can you release a version after modification, and then close the issue so that I can receive notifications

Official release is controlled by the PMC, not me. So, I don't know when they call for release.

**Comment by wu-sheng** [comment]
> stream classdesc serialVersionUID = 7930414337282325166, local class serialVersionUID = 7250238719487042907

@457775987 I read this error again, it makes me feeling, a dynamic field is not the root cause. The instrumentation itself is.

I am not sure when `serialVersionUID` gets changed, does rebooting make `local class serialVersionUID` changed every time?

Also, another question is, does the same application(agent installed) put the AopProxyFactory into the cache? From my understanding, there is one JVM process without agent installed puts the class instance(AopProxyFactory) into the cache, and another JVM process with agent installed read it out, or vice versa. Then, this class structure mismatching happens.

**Comment by 457775987** [comment]
I'm trying to change serialization to Jackson. Compared with jdkserializationredisserializer, I have encountered some problems. OAuth and spring security may need to do a lot of work, which has not been solved yet

**Comment by 457775987** [comment]
After many attempts, there are many problems with JSON serialization and its support is not very good. The current solution is to add the skywalking agent system to declare that defaultaopproxyfactory overrides the one provided by spring AOP, and declare a fixed private static final long serialVersionUID = 7930414337282325166l;
