### ISSUE TITLE
[Bug] Adding skywalking-agent.jar affects spring AOP

### ISSUE THREAD

**Issue by 457775987** [apache/skywalking#7916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

After I add an agent, a class defaultaopproxyfactory in spring AOP will have one more field by default. This class is a serialized class, resulting in a mismatch in the deserialization suid，
This is a screenshot of the test, comparing one with an agent and one without an agent

![join-agent](https://user-images.githubusercontent.com/2177178/137061284-b88bd0fb-e91d-4771-ae96-d000e2b281e9.png)
![no-agent](https://user-images.githubusercontent.com/2177178/137061287-82c67977-3029-4995-9d50-74ac3bc6c342.png)

### What you expected to happen

Adding agent does not affect the existing structure,  What is a good solution？

### How to reproduce

**Only unit tests are needed, and VM parameters are added and deleted respectively：**
-Dskywalking.agent.service_name=ims-his-web
-Dskywalking.collector.backend_service=xxx:11800
-javaagent:D:\skywalking\apache-skywalking-apm-8.7.0\apache-skywalking-apm-bin\agent\skywalking-agent.jar

**Code：**
@Test
    public void doTest() throws Exception {
        DefaultAopProxyFactory aop = new DefaultAopProxyFactory();
        Long att = ObjectStreamClass.lookup(DefaultAopProxyFactory.class).getSerialVersionUID();

        System.out.println("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
        System.out.println(att);
}

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Duplicate #7915
