### ISSUE TITLE
[Bug] Log Search function not effective

### ISSUE THREAD

**Issue by Liubey** [apache/skywalking#7917]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-rocketbot-ui)

### What happened

I have use grpc reporter to collect log to the es,but in /log page,I can not use any english character or chinese character to search log.
by the way,search by trace id is ok.

![image](https://user-images.githubusercontent.com/5568302/137074059-690fdb90-b29b-4d98-bb82-0b12112e1786.png)

request is:
curl 'http://localhost:8080/graphql' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: "Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'Origin: http://localhost:8080' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:8080/log' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7' \
  --data-raw '{"query":"query queryLogs($condition: LogQueryCondition) {\n    queryLogs(condition: $condition) {\n        logs {\n          serviceName\n          serviceId\n          serviceInstanceName\n          serviceInstanceId\n          endpointName\n          endpointId\n          traceId\n          timestamp\n          contentType\n          content\n          tags {\n            key\n            value\n          }\n        }\n        total\n    }}","variables":{"condition":{"keywordsOfContent":[],"excludingKeywordsOfContent":[],"tags":[],"paging":{"pageNum":1,"pageSize":22,"needTotal":true},"queryDuration":{"start":"2021-10-13 123731","end":"2021-10-13 130731","step":"SECOND"}}}}' \
  --compressed

### What you expected to happen

search my log

### How to reproduce

skywalking 8.7.0
es 7.5
springboot + logback

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Liubey** [comment]
> Press enter after input.

but,to be honest,It's not obvious.

**Comment by wu-sheng** [comment]
> > Press enter after input.
> 
> but,to be honest,It's not obvious.

Because you could set multiple keywords to match, there is no other way to provide this.
