### ISSUE TITLE
[Feature] Add OpenJDK 17 (LTS) test for backend server runtime

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#7943]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I can see the OpenJDK 17 is available, please add this version for runtime verification.

This doc should be updated as well accordingly, https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-setup/#requirements-and-default-settings

### Use case

Just in case users choose latest LTS JDK 17 radically, even from our experiences, this seems not a recommended one.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
After plugin test tool container and a new plugin(JDK17 compiling and runtime), this doc should be updated, https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/readme/

**Comment by lujiajing1126** [comment]
I would like to help migrate the docker images to `eclipse-temurin` ones.

**Comment by kezhenxu94** [comment]
> I would like to help migrate the base docker images to `eclipse-temurin` ones.

Not sure whether you are talking the same thing. @wu-sheng is asking for verification on Java 17 but @lujiajing1126 is asking for arm Docker support, FWIW we already have ARM Docker images for OAP https://github.com/apache/skywalking/pkgs/container/skywalking%2Foap

Changing the base Docker image is not recommended IIRC, unless it's only for testing (E2E).

**Comment by wu-sheng** [comment]
@kezhenxu94 `eclipse-temurin` is `adoptopenjdk`(https://adoptopenjdk.net/). I am thinking about whether we should adopt the latest temurin release. WDYT?

**Comment by wu-sheng** [comment]
Another thing is, whether we should provide JDK17 runtime docker image on GitHub repo for testing?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 `eclipse-temurin` is `adoptopenjdk`(https://adoptopenjdk.net/). I am thinking about whether we should adopt the latest temurin release. WDYT?

If you mean test the OAP on latest temurin release and make the tests pass, I'm +1

**Comment by kezhenxu94** [comment]
> Another thing is, whether we should provide JDK17 runtime docker image on GitHub repo for testing?

I can add a step to push that image

**Comment by wu-sheng** [comment]
@kezhenxu94 Notice this from https://hub.docker.com/_/adoptopenjdk

```markdown
## DEPRECATION NOTICE
This image is officially deprecated in favor of the eclipse-temurin image, and will receive no further updates after 2021-08-01 (Aug 01, 2021). Please adjust your usage accordingly.
```

The base image should be updated too. And JDK17 runtime could be considered if it doesn't break release process.

**Comment by lujiajing1126** [comment]
> > I would like to help migrate the base docker images to `eclipse-temurin` ones.
> 
> Not sure whether you are talking the same thing. @wu-sheng is asking for verification on Java 17 but @lujiajing1126 is asking for arm Docker support, FWIW we already have ARM Docker images for OAP https://github.com/apache/skywalking/pkgs/container/skywalking%2Foap
> 
> Changing the base Docker image is not recommended IIRC, unless it's only for testing (E2E).

Yes. At the very beginning, I meant only the E2E parts.

Then due to the deprecation warning from the https://hub.docker.com/_/adoptopenjdk repo mentioned by @wu-sheng, I suppose we should migrate all base images to the recommended ones built by `eclipse-temurin`.
