### ISSUE TITLE
Support Jetty Server 8.1.3

### ISSUE THREAD

**Issue by Jessica-Liu** [apache/skywalking#795]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@ascrutae This is a new requirement, please check your schedule, and reply about whether included in 5.0.0-alpha . Thanks.

**Comment by wu-sheng** [comment]
@carlvine500 @clevertension Does any of you have interested in supporting this? Jetty 8 is an old version. And all PMC members have no time to do this.
