### ISSUE TITLE
[Feature]Extend the protocol to query logs with task ID

### ISSUE THREAD

**Issue by Fine0830** [apache/skywalking#7966]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

On the Profile page, when a task is viewed at different times, its logs are different. Query logs with task ID, which can make to view task logs at different times without refreshing the page.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@mrproliu Consider to add a `getProfileTaskLogs` service in GraphQL. The storage level implementations may or may not need to change.

**Comment by wu-sheng** [comment]
We don't have to break protocol, I think. Adding one should be enough.
