### ISSUE TITLE
[Bug] [Python] A lot of irrelevant spans get together in one trace record

### ISSUE THREAD

**Issue by zqm233** [apache/skywalking#8075]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

I use the apache-skywalking 8.7.0  with the es storage and skywalking python agent 0.7.0 
When I use it , There is a problem that some irrelevant spans  get together in one trace record, and the number of spans will be thousands. 
![image](https://user-images.githubusercontent.com/15966865/140274734-79cfb869-41dd-4ebc-8613-605e3e078ed8.png)

![image](https://user-images.githubusercontent.com/15966865/140274795-a5dd93dc-6dcb-45ac-bdc1-55e3aa6547c5.png)

### What you expected to happen

Just don't know

### How to reproduce

I use the apache-skywalking 8.7.0  with the es storage and skywalking python agent 0.7.0 . It's ok when test it. But when I use it in production environment, the wrong happens

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
As you are also using Lua agent, can you confirm that it's not Lua agent's problem? For example, did that bug also happen when you invoke a Java API thorough the same APISIX?

**Comment by wu-sheng** [comment]
From reading the graph, the parent span is a flask plugin for large numbers of children. It may relate to a multiple threads issue?

**Comment by zqm233** [comment]
> As you are also using Lua agent, can you confirm that it's not Lua agent's problem? For example, did that bug also happen when you invoke a Java API thorough the same APISIX?

When I use only python-agent, it also happens. So it's not lua agent's problem.

**Comment by wu-sheng** [comment]
@zqm233 You should learn, typically, it would be very hard to diagnose thread-relative issue. It is better you could debug and find out the reason and scenario.

**Comment by kezhenxu94** [comment]
> > As you are also using Lua agent, can you confirm that it's not Lua agent's problem? For example, did that bug also happen when you invoke a Java API thorough the same APISIX?
> 
> When I use only python-agent, it also happens. So it's not lua agent's problem.

Do you have a reproducible demo project that can help to diagnose the bug?

**Comment by zqm233** [comment]
> @zqm233 You should learn, typically, it would be very hard to diagnose thread-relative issue. It is better you could debug and find out the reason and scenario.

tks. I'll try it.

**Comment by zqm233** [comment]
> > > As you are also using Lua agent, can you confirm that it's not Lua agent's problem? For example, did that bug also happen when you invoke a Java API thorough the same APISIX?
> > 
> > 
> > When I use only python-agent, it also happens. So it's not lua agent's problem.
> 
> Do you have a reproducible demo project that can help to diagnose the bug?

The bug only shows in production environment even the same project. I guess it related to high concurrency or something. And I use uwsgi and http config to run my flask app.  I don't know if it has something to do with it

**Comment by Superskyyy** [comment]
> > > > As you are also using Lua agent, can you confirm that it's not Lua agent's problem? For example, did that bug also happen when you invoke a Java API thorough the same APISIX?
> > > 
> > > 
> > > When I use only python-agent, it also happens. So it's not lua agent's problem.
> > 
> > 
> > Do you have a reproducible demo project that can help to diagnose the bug?
> 
> The bug only shows in production environment even the same project. I guess it related to high concurrency or something. And I use uwsgi and http config to run my flask app. I don't know if it has something to do with it
@zqm233 
Hello, did you have any extra findings? It will be helpful if you can provide some more details, such as general specifications of your deployment, platform, versions and method of integration (i.e. non-intrusive or via import).

**Comment by wu-sheng** [comment]
No update in months.
