### ISSUE TITLE
[Feature] query log count

### ISSUE THREAD

**Issue by BFergerson** [apache/skywalking#8083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, you can query logs via `ILogQueryDAO` but you cannot just query log counts. I think we should add a parameter that indicates that only `Logs.total` should be populated. That way you can quickly get a feel for how many logs there are without having to fetch them all.

### Use case

I just want to know how many of a particular format of a log pattern was captured at a particular time. I don't want the log data.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Storage like h2 MySQL don't support pattern searching, and storage like ElasticSearch doesn't return the exact total count of result.

**Comment by wu-sheng** [comment]
From the database perspective, count is fetching all data 😄 
We were discussing even to remove the count in the general query, which has not been applied.
The biggest concern behind this is performance impact, count someyimes causes more than query itself. And, I agree, getting only count is better than both count and first N records.

**Comment by wu-sheng** [comment]
> I just want to know how many of a particular format of a log pattern was captured at a particular time. I don't want the log data.

I think we need to be more clear about what is a particular format? Could you provide some examples?

**Comment by BFergerson** [comment]
@kezhenxu94, that actually does look like it'll work for H2. Maybe not so much for ES. Either way, I'll close this issue. I was trying to come up with a way to query log counts without writing H2/ES specific code, but I think the custom code is necessary.

@wu-sheng, I use `plugin.toolkit.log.transmit_formatted=false` so I don't care so much about the log data. I just care about the tags and the number of times each pattern has occurred. So if I can get the count, I can calculate log density.

**Comment by wu-sheng** [comment]
>  I use plugin.toolkit.log.transmit_formatted=false so I don't care so much about the log data. I just care about the tags and the number of times each pattern has occurred. So if I can get the count, I can calculate log density.

Have you taken a look at how LAL(Log Analysis Language) engine works? It could fetch the tags(regex) and generate metrics for MAL(metrics analysis language script) engine to get all the number related things you want. In your case, I think it is `sum`.

**Comment by BFergerson** [comment]
@wu-sheng, yeah you're right. I'm currently learning more about LAL/MAL and now that you mention it that's obviously how I should do it. I won't be able to get counts for logs that happened prior to adding the new meters, but that'll be fine. Moving forward they'll have queriable counts. Thanks again.
