### ISSUE TITLE
[Bug] when using Dubbo 3.x，there is no correct trace info collected and displayed，maybe it does not work well or Dubbo 3.x is not supported yet now?

### ISSUE THREAD

**Issue by ronanzhan** [apache/skywalking#8095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
>  I had searched in the issues and found no similar feature requirement.

You clicked this but you never did.

https://github.com/apache/skywalking/issues/7203
