### ISSUE TITLE
[Feature] support ClickHouse as storage

### ISSUE THREAD

**Issue by valkex** [apache/skywalking#8098]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

ClickHouse is an excellent OLAP database, I think it can be used as one of the storage options of skywalking

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Duplicate #3860. No update for a long time. Unless you are going to submit some proposal(Design doc), I think we don't plan to work on this direction.

**Comment by valkex** [comment]
> Duplicate #3860. No update for a long time. Unless you are going to submit some proposal(Design doc), I think we don't plan to work on this direction.

How to submit a proposal(Design doc)?I have prepared the code for this feature.

**Comment by wu-sheng** [comment]
You could submit a google doc(open to people have known link) proposal to the mail list. Then PMC will review how aregenerally metadata(traffic), metrics, records(traces, logs, profiling snapshots), no streaming data(ui management and profile task) supported by Clickhouse, and whether do you have a benchmark to verify whether the design is suitable for large scale product environment.

**Comment by wu-sheng** [comment]
This is a very complex and important extension. The project will accept it until the proposal and codes have been proved officially.

Take a reference from IoTDB storage option from https://github.com/apache/skywalking/pull/7766. It is closing to be accepted.

**Comment by sglztc** [comment]
> > Duplicate #3860. No update for a long time. Unless you are going to submit some proposal(Design doc), I think we don't plan to work on this direction.
> 
> How to submit a proposal(Design doc)?I have prepared the code for this feature.

Can you share this code? Thank you very much.
