### ISSUE TITLE
[Feature] Skywalking-Client-JS supports to add custom attributes as tags in spans

### ISSUE THREAD

**Issue by rain00yu** [apache/skywalking#8128]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Skywalking-Client-JS supports tracing custom attributes (like client id、client nickname) as tags in spans.

### Use case

Other than http method and url, supports a a few custom attributes as tags in spans. Allow user to specify the keys and values.

`"spans": [`
     ` {`
        `"operationName": "*******",`
        .....
        `"peer": "************",`
        `"tags": [`
         ` {
            "key": "http.method",
            "value": "GET"
          },`
          `{
            "key": "url",
            "value": "******"
          },`
         **`{
            "key": "cus key1",
            "value": "cus value1"
          },`
          `{
            "key": "cus key2",
            "value": "cus value2"
          }`**
        `]`
      `}`
`]`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Is there any way you recommend? The client JS is running automatically, with one several lines added on the page, there is no clear place to tag the HTTP request.

**Comment by wu-sheng** [comment]
No update for a week.
