### ISSUE TITLE
[Feature] [Showcase] Add event and alarm to the showcase

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8130]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add 2 more features, event and alarm, to the showcase. These two may not be a case, but, some setups should be added.

### Use case

This eventually would show up on the demo.skywalking.apache.org

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@kezhenxu94 I noticed you have added the event, right?

**Comment by kezhenxu94** [comment]
Event is added. Alarm is not yet
