### ISSUE TITLE
[Feature] [Java] Add JDK HttpURLConnection support for more JDKs

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8133]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

With some package changes of com.sun in JDK library codebase, HttpURLConnection plugin loses compatibility. Let's enhance it to cross JDK versions support.

I have talked with @JaredTan95 , he will lead this.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by toffentoffen** [comment]
I would like to work on this issue @wu-sheng

**Comment by wu-sheng** [comment]
Thanks, Marc. Assigned to you. Good luck.

**Comment by ypg521** [comment]
🔢

**Comment by pg-yang** [comment]
I'm not sure , May I work on this issue?

**Comment by wu-sheng** [comment]
I think you could. We don't have an update on this for now.

**Comment by pg-yang** [comment]
I found HttpClientWriteRequestInterceptor.java use ` java.net.HttpURLConnection`。
But `sun.net.www.http.HttpClient` depend on `sun.net.www.protocol.http.HttpURLConnection` in java7+,Is it  the  reason for  losing compatibility?
By the way, I can't found which java version depend on ` java.net.HttpURLConnection` for `sun.net.www.http.HttpClient` , I have tried java 7、8、17、18

**Comment by wu-sheng** [comment]
I don't know the details. If you think they are supported, try to work on test cases(plugin test scenarios). We should verify.

**Comment by pg-yang** [comment]
OK. I will inspect `jdk-http-scenario` test cases
And  maybe wait for  @JaredTan95 's suggestion  at the same time

**Comment by wu-sheng** [comment]
This is actually an easy way, we should have a doc on the boostrap plugin doc page.

https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/bootstrap-plugins/

You could submit a pull request to update this doc.

Also, I think you use module in your demo codes, right? Otherwise, should all things are all unamed, right?

**Comment by pg-yang** [comment]
I didn't use module
It can work in java9-15  because  `--illegal-access ` default model is permit , and since jav16  the model is deny
See https://openjdk.org/jeps/403 (Section Description)

**Comment by pg-yang** [comment]
So , let's update the doc happily.
Just a little people use java module .  upgrade to java16 is a long story

**Comment by wu-sheng** [comment]
Agree. Also, we could add `--illegal-access` and `--add-exports java.base/sun.net.www=ALL-UNNAMED` into the docs too.
For longer storage, I am thinking, for JDK instrumentation, we have to add a mechanism to identify JDK17+ plugins or belongs, and load different plugins according to the runtime JRE version.

Then for this plugin, we could add module dependency declare into the plugin jar, and try to make it works.

**Comment by pg-yang** [comment]
For this plugin, maybe we shouldn't enhance  a internal class such as `sun.net.www.http.HttpClient`? I think.
About adding ` a mechanism to identify JDK17+ plugins` ,  If you  agree with the above,  The mechanism may not very useful.Because JDK changes are infrequent and  Java-Agent use `Class/Method match mechanism` to  enhance specified Class,It's enough for multiple JDKs

Anyhow  `java.*` package  or other package for end user always be exposed

**Comment by wu-sheng** [comment]
Make sense. You could take a deeper look, to see whether we could instrument a exposed class?
