### ISSUE TITLE
[Feature] [SWCK] Supports Kubernetes 1.22.x

### ISSUE THREAD

**Issue by RolandMa1986** [apache/skywalking#8136]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

**Apache SkyWalking Cloud on Kubernetes** can't be deployed on Kubernetes 1.22.x since some deprecated API is used by the **SWCK**. 
**SWCK** should have a plan to support the latest Kubernetes.

### Use case

To support Kubernetes 1.22.x,  the following API reference need to be upgraded:

apiextensions.k8s.io/v1beta1 -> apiextensions.k8s.io/v1, available since v1.16
apiregistration.k8s.io/v1beta1 ->  apiregistration.k8s.io/v1, available since v1.10
Ingress  networking.k8s.io/v1beta1 -> networking.k8s.io/v1, available since v1.19

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Assigned to @RolandMa1986 according to you have selected PR planned.

**Comment by RolandMa1986** [comment]
Hi @wu-sheng , 
What's the minimal version of Kubernetes that needs to be supported by SWCK  in the next release? 
It would be very easy to support **Kubernetes 1.19** and above only, since all the API versions are compatible. But if SWCK needs to support an older version than 1.19, we need to consider how to change the API version in the Controller and Templates.

**Comment by wu-sheng** [comment]
I think this should be @hanahmily 's call. He is leading the project.

**Comment by hanahmily** [comment]
Yep, we have a plan to upgrade kube runtime by bumping up the kubebuilder v3 in **SWCK-0.5.0** which will support the latest Kubernetes. 

A canonical strategy is to release major version, for example 1.0.0, to adopt to the new APIs, backporting new feats into the old revision. But, SWCK is not production ready, have not released 1.0.0, I tend to use current major version to do update.
