### ISSUE TITLE
java agent ConnectionCache maybe get error connectionInfo [Bug] 

### ISSUE THREAD

**Issue by zhyhzhylove** [apache/skywalking#8137]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

 ConnectionCreate5xInterceptor:         

ConnectionInfo connectionInfo = ConnectionCache.get(allArguments[0].toString(), allArguments[1].toString());

allArguments[0].toString()：db host
allArguments[1].toString(): db port

this code will get wrong info when two instances on one db。

### What you expected to happen

db.instance: db name is wrong

### How to reproduce

ConnectionCache map key = host + port + dbname

### Anything else

nothing

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhyhzhylove** [comment]
skywalking agent v8.4.0

**Comment by wu-sheng** [comment]
We only accept bug report for latest release.

**Comment by wu-sheng** [comment]
Ans this gets disussed before, we treat IP:port as one database instance.
