### ISSUE TITLE
[Feature] [MAL Core] Add a match pattern mechanism for the MAL core

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8145]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I noticed in the showcase(also demo env), we always face `oap::` services, which mean no actual service name.
I finally got a chance to confirm with @kezhenxu94 why. It turns out `oap`'s self-observability and `vm`'s monitoring have the same metric name.

We need a mechanism to identify the source of a SampleFamily to avoid this case. I would like to propose these kind of mechanism.

We add a field precondition field into all MAL related configuration files, including `oc-receiver`, `envoy-metrics-receiver`, `meter-receiver` etc. This field should be a closure returning true/false. When `false` is returned, this SampleFamily set isn't pushed into rules of all including expressions, but simply skip.

@hanahmily Could you confirm this mechanism makes sense?

### Use case

This feature could avoid empty service issue, and generally it increase the performance of MAL engine, because less calculation are applied by the input metrics set.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
FYI @wankai123 due to you asked about this in afternoon.

**Comment by wankai123** [comment]
We can get otel `job_name` from `node.getServiceInfo()`, then could add a tag like `job_name=skywalking` to all metrics.
I think we can use this to do the filter.

**Comment by wu-sheng** [comment]
Even we use a tag filter, we need the closure setup to filter irrelative metrics out.

**Comment by wankai123** [comment]
yes, the metrics should filter before into MAL rules

**Comment by hanahmily** [comment]
MAL tends to generate the metrics that are mandatory. If the metrics are invalid, related MALs are redundant, having to be removed from the configuration.

What leads to such issues? Can we avoid them from the source? If their service tags are absent, could we have a chance to provide them? If not, I prefer to drop them.

**Comment by wu-sheng** [comment]
No, they are not redundant. 2 kinds of agent/source(s) are generating the metrics with same name.

**oap's self-observability and vm's monitoring have the same metric name**. More importantly, this could happen again in other monitoring cases.

**Comment by wu-sheng** [comment]
For making understanding easier, @hanahmily you could consider like this, MetricA from VM monitoring uses the same name SkyWalking OAP self-monitoring is using. Changing any side of these two doesn't make sense.

**Comment by wu-sheng** [comment]
@kezhenxu94 @hanahmily @wankai123 Another point we should consider is, once the names of entity(such as service name for service, service/instance names for instance) are empty, we should skip this metric before forward it to streaming.

This is not for fixing this case, @wankai123 's job label seems more reliable and official, but we need to filter some illegal or unexpected data.

**Comment by wu-sheng** [comment]
> the filter rule should consider one MAL config need multiple metrics source(otel job), like k8s_service require both cAdvisor and kube-state-metrics

That is why I proposed `precondition` as closure, then you could do `either` check, rather than struggling about using `at least having` or `includes`.
