### ISSUE TITLE
[Feature] Tracing context propagation, from JDBC plugin to Database Proxy(ShardingSphere)

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#8164]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now we use the [CyborgFlow](https://github.com/SphereEx/CyborgFlow) project to perform database switching and complete monitoring functions in the process of full-link stress testing, but we cannot yet complete the support for the topology map because there is currently no tracer at the database level. This issue is used to improve this part of the function. Mainly divided into two parts:
1. The agent transmits the Tracing Context to the database: puts comment into sql prefix. Multiple tracing context item are created as one comment, use "," to separate each item, and the key value in each item is separated by ".". The format is as follows: `/* sw8_context:base64_encode(item1_key).base64_encode(item1_value),base64_encode(item2_key).base64_encode(item2_value) */`.
2. The database analyzes the Trading Context: Currently [ShardingSphere](https://github.com/apache/shardingsphere) is willing to participate in it and participate in the development of the plug-in.

### Use case

When the user uses the database (as a tracer) that SkyWalking supports to monitor, then we can observe the internal execution of the database in the topology diagram and link it with the application.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Is there anyone assigned to?

**Comment by wu-sheng** [comment]
About the milestone, unless there is committer proposing a time limited assignment, I prefer to keep it open. We don't want push too hard on contributions.

**Comment by mrproliu** [comment]
For the first part(transmits the Tracing Context to the database) I could do this in the java MySQL plugin. but for part two, @soulasuna do you have any idea who will do this?

**Comment by wu-sheng** [comment]
For what you propose, we need to cover `sw8`, `sw8-x` and `sw8-correlation` as keys, even in the SQL comment. 
- https://skywalking.apache.org/docs/main/latest/en/protocols/skywalking-cross-process-propagation-headers-protocol-v3/
- https://skywalking.apache.org/docs/main/latest/en/protocols/skywalking-cross-process-correlation-headers-protocol-v1/

Because those are protocol definitions.
____
Meanwhile, how to put in the comment isn't a protocol level definition. But, considering this injection will effect  existing standard SQL plugins, it is better to provide a new configuration at JDBC plugin level to activate this and build this format.

**Comment by wu-sheng** [comment]
> The database analyzes the Trading Context: Currently ShardingSphere is willing to participate in it and participate in the development of the plug-in.

I am not sure what does this mean. Is it going to have a ShardingSphere proxy plugin on the way?

**Comment by mrproliu** [comment]
> For what you propose, we need to cover `sw8`, `sw8-x` and `sw8-correlation` as keys, even in the SQL comment.

Yes, all these keys should be covert and put into the SQL comment.

> 
> Meanwhile, how to put in the comment isn't a protocol level definition. But, considering this injection will effect existing standard SQL plugins, it is better to provide a new configuration at JDBC plugin level to activate this and build this format.

That's true. we need to create a new configuration item to activate them. I think `plugin.jdbc.is_propagating_context` is fine, it mean should we need to add the tracing context to the SQL, default is `false`.

**Comment by mrproliu** [comment]
> > The database analyzes the Trading Context: Currently ShardingSphere is willing to participate in it and participate in the development of the plug-in.
> 
> I am not sure what does this mean. Is it going to have a ShardingSphere proxy plugin on the way?

Yes, ShardingSphere proxy needs to create a plugin to analyze the context and make it as a `Span` into the Tracing Context.

**Comment by wallezhang** [comment]
Hi everyone, I have a question, if the original sql has a hint, will this have an impact, or will the added comment have additional parsing cost for the SQL engine? Maybe ShardingSphere proxy plugin will remove the tracing context before sending the sql to the backend database.

**Comment by wu-sheng** [comment]
> if the original sql has a hint, will this have an impact, 

We will try to avoid this case.

> or will the added comment have additional parsing cost for the SQL engine? 

It changes the SQL, so from SQL string perspective, it has a little. And it costs more network bandwidth for sure.

> Maybe ShardingSphere proxy plugin will remove the tracing context before sending the sql to the backend database.

From my understanding, ShardingSphere should do. Let's see. @tristaZero

**Comment by wallezhang** [comment]
> > if the original sql has a hint, will this have an impact,
> 
> We will try to avoid this case.
> 
> > or will the added comment have additional parsing cost for the SQL engine?
> 
> It changes the SQL, so from SQL string perspective, it has a little. And it costs more network bandwidth for sure.
> 
> > Maybe ShardingSphere proxy plugin will remove the tracing context before sending the sql to the backend database.
> 
> From my understanding, ShardingSphere should do. Let's see. @tristaZero

Thanks for the reply. If application connect to the real database not a proxy, I think add a tip to describe the impact on this is a good idea.

**Comment by wu-sheng** [comment]
> Thanks for the reply. If application connect to the real database not a proxy, I think add a tip to describe the impact on this is a good idea.

This would never be activated in default. A new config(default=off) will be added for this keep tracing case only

**Comment by wu-sheng** [comment]
Project open sourced here, https://github.com/SphereEx/CyborgFlow
A CN blog posted, https://skywalking.apache.org/zh/2022-01-18-cyborg-flow/

If anyone needs this blog in English, please let us know, we are glad to translate. Generally, this feature is requested in China community.
