### ISSUE TITLE
[Enhancement] Bump grpc and protobuff version to allow building on Mac M1 osx-aarch_64

### ISSUE THREAD

**Issue by toffentoffen** [apache/skywalking#8184]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

When you try build skywaling on a Mac M1 some artifacts are missing for the osx-aarch_64 architecture as described in https://github.com/apache/skywalking/blob/master/docs/en/FAQ/How-to-build-with-mac-m1.md#problem.

### What you expected to happen

Build skywalking without using `-Dos.detected.classifier=osx-x86_64`  and instead use the natively available artifacts for Mac M1 osx-aarch_64.

### How to reproduce

Execute `./mvnw clean package -Dmaven.test.skip` to build on a Mac M1 without using `-Dos.detected.classifier=osx-x86_64` as suggested in https://github.com/apache/skywalking/blob/master/docs/en/FAQ/How-to-build-with-mac-m1.md

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Assigned, thank you.
