### ISSUE TITLE
[Document] Setup Satellite as Load Balancer Document and add it into the showcase

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#8185]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Recently, I'm still working on optimizing the [skywalking-satellite](https://github.com/apache/skywalking-satellite), letting it could be running in production as a load balancer between `agent`/`envoy` and `oap`.
After the satellite optimizing is finished, I will add documentation to help users how to set up it, and add it into the [showcase](https://github.com/apache/skywalking-showcase).

### Use case

Let users easy to using satellite as a Load Balancer.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Removing milestone, we may need more tests and an official release.

8.9.0 is planned to launch after https://github.com/apache/skywalking/pull/7766/ gets merged.

**Comment by wu-sheng** [comment]
PMC member shows concerns about Satellite in the showcase, let's keep it in document only for now. 

Ref, https://github.com/apache/skywalking-kubernetes/pull/83#issuecomment-979661763
