### ISSUE TITLE
[Feature][Showcase] Java agent injection for kubernetes

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#8195]
### Description

Introduce a new case that shows how the java agent injector works to showcase repo.

We can add a new `feature` into the repo by referring to the [agentless case](https://github.com/apache/skywalking-showcase/blob/9b9e6a7f661df67e9d0396afe972da2cff1bfe61/deploy/platform/kubernetes/features.mk?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L57) which is recommended by @kezhenxu94 

In this feature, we should 

 * create a new namespace for the operator
 * deploy the swck operator.
 * remove the java app image with the java agent. Use the java agent injector to attach the official agent image.
 * update the agent's backend address to the `single-node` or `cluster` feature. (Their address is identical. One of them should be deployed with this feature)

@dashanji Do you interest in this?

@wu-sheng @kezhenxu94 any insight about this?

**Comment by wu-sheng** [comment]
Are we going to remove the `agent-image` based solution? Using injection to replace?

**Comment by hanahmily** [comment]
> Are we going to remove the `agent-image` based solution? Using injection to replace?

FWIK, `agent-image` solution is broadly used in kubernetes environment. I prefer adding a new feature instead of replacing it.

**Comment by wu-sheng** [comment]
I would recommend you to read this discussion context. https://github.com/apache/skywalking-kubernetes/pull/83#issuecomment-979649648

I don't have to make showcase complex, as we never have a chance to cover all user cases. Showcase should be simple, straight forward, no option. Otherwise, it makes no different with current documentation.
I prefer to write a document(I think we have it already, right?) and a step-by-step blog(more searchable in the search engine) to introduce this feature.

What do you think?

**Comment by hanahmily** [comment]
> I don't have to make showcase complex, as we never have a chance to cover all user cases. Showcase should be simple, straight forward, no option. Otherwise, it makes no different with current documentation. I prefer to write a document(I think we have it already, right?) and a step-by-step blog(more searchable in the search engine) to introduce this feature.

Make sense. a canonical path is better and neater than many options. I will update the task list accordingly.

**Comment by dashanji** [comment]
Yes, I'd like to do it.
