### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wuxingyun** [apache/skywalking#8199]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-rocketbot-ui)

### What happened

![XUDC~)CVFAP{EDL }@IOPOM](https://user-images.githubusercontent.com/37184972/143814880-930c44c8-c182-4286-8a74-5a52ea388c63.png)
![{FUYL6DL%UV0 J_X89T2 8V](https://user-images.githubusercontent.com/37184972/143814899-b7bbc527-af42-40b1-aa98-22bb12cef7a3.png)

The first click on the navigation will take you to the page, but when you refresh it, it will go straight to 404

### What you expected to happen

.

### How to reproduce

.

### Anything else

Deployment way   ：docker pull apache/skywalking-ui:8.7.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Search before asking 

https://github.com/apache/skywalking/pull/7403
