### ISSUE TITLE
[Feature] [Nodejs] intercept the http.get

### ISSUE THREAD

**Issue by chzhuo** [apache/skywalking#8225]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The plugin `HttpPlugin`  of nodejs agent not intercept the method `http.get`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you going to submit a pull request about this?

**Comment by vijal-patel** [comment]
could I work on this?

**Comment by kezhenxu94** [comment]
> could I work on this?

Yes thanks!

**Comment by vijal-patel** [comment]
Hi @kezhenxu94 @chzhuo. How can I replicate this issue and what is the expected outcome after the fix?

I've tested by setting skywalker up locally and both client and server side GET requests are viewable in the /dashboard/GENERAL/Service/c2VydmVy.1/General-Service route of the UI

**Comment by kezhenxu94** [comment]
> Hi @kezhenxu94 @chzhuo. How can I replicate this issue and what is the expected outcome after the fix?
> 
> 
> 
> I've tested by setting skywalker up locally and both client and server side GET requests are viewable in the /dashboard/GENERAL/Service/c2VydmVy.1/General-Service route of the UI
> 
> 
> 
> PS - I tested by running https://github.com/apache/skywalking-nodejs/tree/v0.5.1/tests/plugins/http locally

Can you try to reproduce by changing this to http.get?

https://github.com/apache/skywalking-nodejs/blob/289e8af995cb0702adabacccd669c10974299411/tests/plugins/http/client.ts#L30

**Comment by kezhenxu94** [comment]
Lack of information about how to reproduce from the reporter.
