### ISSUE TITLE
[Code Comments] The comment of the trySampling() method is outdated, which causes some confusion.

### ISSUE THREAD

**Issue by buyanhub** [apache/skywalking#8227]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Refer discussions #8217 

Current comment

```
/**
 * @param operationName The first operation name of the new tracing context.
 * @return true, if sampling mechanism is on, and getDefault the sampling factor successfully.
 */
public boolean trySampling(String operationName) {
    if (on) {
        int factor = samplingFactorHolder.get();
        if (factor < samplingRateWatcher.getSamplingRate()) {
            return samplingFactorHolder.compareAndSet(factor, factor + 1);
        } else {
            return false;
        }
    }
    return true;
}
```

`getDefault` is a nonexistent method。

### What you expected to happen

Change comment to:

```
/**
 * When the sampling mechanism is on and the sample limited is not reached, the trace segment
 * should be traced. If the sampling mechanism is off, it means that all trace segments should
 * be traced.
 * @param operationName The first operation name of the new tracing context.
 * @return true if should sample this trace segment. When sampling mechanism is on, return true if sample limited is not reached.
 */
```

### How to reproduce

needless

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-java/pull/80
