### ISSUE TITLE
[Bug] Normal Service traffic data will be covered by other node type if they got same service name

### ISSUE THREAD

**Issue by creeew** [apache/skywalking#8237]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

v8.6.0
In es storage, Normal service and browser app got the same name

![image](https://user-images.githubusercontent.com/30746864/144597607-a0ad8b20-58a0-4efa-a4ff-a8f9878287db.png)
In the APM area, we got a service and the name is "SAME NAME", and then we got a browser perfData report with the same service name "SAME NAME".
![image](https://user-images.githubusercontent.com/30746864/144598006-266fc2a6-7a2f-48df-be2a-8cd5668d70af.png)
In the web browser area we got the "SAME NAME" service.

But when you back to the APM area, the "SAME NAME" service will disappear.

### What you expected to happen

Service in APM would not be affect by other type service traffic. Although they got the same service name

### How to reproduce

report a segment with service name is "same_covered_name"
```
POST localhost:12800/v3/segments
[
    {
        "traceId": "222.13",
        "traceSegmentId": "222.12",
        "service": "same_covered_name",
        "spans": [
            {
                "logs": [],
                "tags": [
                    {
                        "key": "http.method",
                        "value": "GET"
                    },
                    {
                        "key": "url",
                        "value": "http://localhost:8080/get/cover"
                    }
                ],
                "operationName": "{GET}/get/cover",
                "spanLayer": 3,
                "startTime": 1638529487000,
                "peer": null,
                "spanId": 0,
                "parentSpanId": -1,
                "endTime": 1638529487000,
                "componentId": 14
            }
        ],
        "serviceInstance": "2@2.2.2.1"
    }
]
```
and in getAllService, we can get the service with name "same_covered_name"
```
{
    "data": {
        "services": [
            {
                "key": "c2FtZV9jb3ZlcmVkX25hbWU=.1",
                "label": "same_covered_name"
            }
        ]
    }
}
```
report browser perfData with service name is "same_covered_name"

```
POST localhost:12800/browser/perfData
{
    "redirectTime": 1,
    "dnsTime": 1,
    "ttfbTime": 1,
    "tcpTime": 1,
    "transTime": 1,
    "domAnalysisTime": 1,
    "fptTime": 1,
    "domReadyTime": 1,
    "loadPageTime": 1,
    "resTime": 1,
    "sslTime": 1,
    "ttlTime": 1,
    "firstPackTime": 1,
    "fmpTime": 1,
    "pagePath": "/get/cover1",
    "serviceVersion": "cover_version",
    "service": "same_covered_name"
}
```

In the method getAllService, we cannot get the service with name "same_covered_name", in the es, node_type was change to 6 cause browser perfData cover the service which name is "same_covered_name"
```
{
                "_index": "sw_service_traffic-20211203",
                "_type": "_doc",
                "_id": "c2FtZV9jb3ZlcmVkX25hbWU=.1",
                "_score": 1,
                "_source": {
                    "node_type": 6,
                    "flag": "wei",
                    "name": "same_covered_name",
                    "service_group": null
                }
}
```

### Anything else

in the method `org.apache.skywalking.oap.server.core.analysis.IDManager.ServiceID#buildId(java.lang.String, org.apache.skywalking.oap.server.core.analysis.NodeType)` normal node type and browser node type treat as same. So we will got the same id if name is same. And browser service traffic will update normal service traffic since they got the same id in es. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Service name is unique, period. All other information is attachment.
