### ISSUE TITLE
[Feature] Is there a plan to add Trace and Metrics export in opentelemetry-collector-contrib? 

### ISSUE THREAD

**Issue by 470390366** [apache/skywalking#8244]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I saw that @liqiangz submitted the log export in opentelemetry-collector-contrib. Is there any plan to add Trace and Metrics export? 

### Use case

I expect to use opentelemetry-sdk and opentelemetry-api to record and upload traces, metrics, and logs, and send them to skywalking for display. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
>  I had searched in the issues and found no similar feature requirement.

You at least should do this. And read documents.

**Comment by berylshow** [comment]
> 
@wu-sheng  hello，Please, What version of trace is planned to be added in the opentelemetry-collector-contrib exporter?
I see ,At present, only logs and metrics are supported. Thanks~
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/skywalkingexporter

**Comment by berylshow** [comment]
@wu-sheng hello，Please, What is the version of the opentelemetry-collector-contrib exporter that you plan to add a trace to?
I see that logging and metrics are currently supported. Has trace been supported? Thank you~
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/skywalkingexporter

**Comment by wu-sheng** [comment]
No, we don't have plan as there is tech block, which is why we can't transfer Zipkin span to SkyWalking full functional tracing. APM level tracing with analysis is different from what OpenTelemetry defined.

**Comment by berylshow** [comment]
> 

Ok, get it, Thanks
