### ISSUE TITLE
[Bug] Earlier versions of netty-codec or other jar packages have security breach in agent 8.8.0

### ISSUE THREAD

**Issue by Linda-pan** [apache/skywalking#8249]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

  In skywalking agent 8.8.0, netty and netty-codec versions are 4.1.63.Final, and guava versions are 20.0, which are found to have security breach. The netty version should be upgraded to version 4.1.68.Final or above, while the guava version should be upgraded after 30.0.
  At the same time, I found that the version of oap 8.8.0 is different, netty-codec's version is 4.1.68.Final and guava's version is 28.1-jre. Whether the version of the agent can be modified is consistent on both sides?

### What you expected to happen

Maintain a consistent version and no security breach in the final version

### How to reproduce

The netty version should be upgraded to version 4.1.68.Final or above, while the guava version should be upgraded after 30.0.

### Anything else

**Some of the descriptions of security breach are listed below.**
**netty-codec-http**
**Netty is an open-source, asynchronous event-driven network application framework for rapid development of maintainable high performance protocol servers & clients. In Netty before version 4.1.59.Final there is a vulnerability on Unix-like systems involving an insecure temp file. When netty's multipart decoders are used local information disclosure can occur via the local system temporary directory if temporary storing uploads on the disk is enabled. On unix-like systems, the temporary directory is shared between all user. As such, writing to this directory using APIs that do not explicitly set the file/directory permissions can lead to information disclosure. Of note, this does not impact modern MacOS Operating Systems. The method "File.createTempFile" on unix-like systems creates a random file, but, by default will create this file with the permissions "-rw-r--r--". Thus, if sensitive information is written to this file, other local users can read this information. This is the case in netty's "AbstractDiskHttpData" is vulnerable. This has been fixed in version 4.1.59.Final. As a workaround, one may specify your own "java.io.tmpdir" when you start the JVM or use "DefaultHttpDataFactory.setBaseDir(...)" to set the directory to something that is only readable by the current user.**
**netty-codec**
**The Bzip2 decompression decoder function doesn't allow setting size restrictions on the decompressed output data (which affects the allocation size used during decompression). All users of Bzip2Decoder are affected. The malicious input can trigger an OOME and so a DoS attack**
**guava**
**A temp directory creation vulnerability exists in all versions of Guava, allowing an attacker with access to the machine to potentially access data in a temporary directory created by the Guava API com.google.common.io.Files.createTempDir(). By default, on unix-like systems, the created directory is world-readable (readable by an attacker with access to the system). The method in question has been marked @Deprecated in versions 30.0 and later and should not be used. For Android developers, we recommend choosing a temporary directory API provided by Android, such as context.getCacheDir(). For other Java developers, we recommend migrating to the Java 7 API java.nio.file.Files.createTempDirectory() which explicitly configures permissions of 700, or configuring the Java runtime's java.io.tmpdir system property to point to a location whose permissions are appropriately configured.**

**Comment by wu-sheng** [comment]
> Maintain a consistent version and no security breach in the final version

This would not be going to happen. This is an open source project, you have all rights to open fork or change the dependency privately.

**Comment by kezhenxu94** [comment]
the netty version is 4.1.68.Final in 8.9.0 and master branch, we typically won't back port CVEs to all previous versions, instead, we encourage users to upgrade to the latest SkyWalking if possible

https://github.com/apache/skywalking/blob/1fdf3a8acf0b86be276d4a6cd288ae9c23e9aa42/oap-server-bom/pom.xml#L63

**Comment by kezhenxu94** [comment]
gRPC haven't had an official release for netty 4.1.68.Final yet (https://github.com/grpc/grpc-java/issues/8617), we can upgrade but we also have to test (and undertake the risk) on our own, (we did this in OAP), what's your opinion? @wu-sheng

**Comment by wu-sheng** [comment]
As this is a dependency CVE, I would like to keep it open for now. AFAIK, we don't have 8.9.0 release plan for short term..

**Comment by wu-sheng** [comment]
This CVE belongs to gRPC, we would be better to wait and upgrade after they released or we need to do 8.9.0 agent release.

**Comment by Linda-pan** [comment]
Thank you for your reply, I will temporarily install a secure version of the jar to use, and look forward to your update.
