### ISSUE TITLE
[Bug] Unable to use zipkin receiver 

### ISSUE THREAD

**Issue by 470390366** [apache/skywalking#8262]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

After I set up the zipkin receiver, I started the oap server and reported an error ，
error：failed to bind to xxxx:9411
![企业微信截图_16389572177533](https://user-images.githubusercontent.com/45119426/145187482-8bf6d5b6-6fe4-45c2-a9de-645b1c4cc66b.png)
I confirm that the ip and port of zipkin are ok, because I have built zipkin and can use it. 

and 
When I want to use zipkin receiver, when storage is set to zipkin-elasticsearch7, there is also an error, the error is no provider found for module storage 
![image](https://user-images.githubusercontent.com/45119426/145188226-6b8b5e48-fcf2-4fb5-a7c4-89ce5236d52c.png)

I don’t know if I am using the correct one, please guide me 

### What you expected to happen

Hope to receive zipkin's data and display it 

### How to reproduce

![image](https://user-images.githubusercontent.com/45119426/145188542-3bab45fe-14cc-432f-9b25-987ee130a57f.png)
Set the above variables 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Why can't bind ip and port should be answered by us?

**Comment by 470390366** [comment]
> not existing is a clear message. That provider doesn't exist. There is no es6 and es7 suffix anymore.
This log print makes me feel like you misspelled the code internally because there is an extra "/"

**Comment by 470390366** [comment]
> Why can't bind ip and port should be answered by us?

This log print makes me feel like you misspelled the code internally because there is an extra "/"

**Comment by wu-sheng** [comment]
That is not our output. Check the stack, and we have no point to change that.
