### ISSUE TITLE
前端浏览器请求一直超时

### ISSUE THREAD

**Issue by cj12580** [apache/skywalking#8277]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Client Side Agent (apache/skywalking-client-js)

### What happened

![image](https://user-images.githubusercontent.com/19181652/145508745-482e3ff1-1546-4403-b570-86df30710ed8.png)

前端请求200成功，查看日志提示超时

### What you expected to happen

![image](https://user-images.githubusercontent.com/19181652/145508745-482e3ff1-1546-4403-b570-86df30710ed8.png)

前端请求200成功，查看日志提示超时

### How to reproduce

![image](https://user-images.githubusercontent.com/19181652/145508745-482e3ff1-1546-4403-b570-86df30710ed8.png)

前端请求200成功，查看日志提示超时

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We require all things on GitHub should be in English. So closing and locked.
And this is mostly like a local setup question, rather than a bug. Check logs, and try quick start.
