### ISSUE TITLE
[Feature][Java Agent] apm-customize-enhance-plugin add support for returnedObj

### ISSUE THREAD

**Issue by chanjarster** [apache/skywalking#8292]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently apm-customize-enhance-plugin doesn't support `returnedObj` expression, see [doc][1].

Since it's similar with @Trace toolkit, I think `returnedObj` should be supported.

[1]: https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/customize-enhance-trace/

### Use case

```xml
<enhanced>
    <class class_name="SomeClass">
        <method method="someMethod(java.lang.String)" static="false">
            <tag key="tag_1">returnedObj</tag>
            <log key="log_1">returnedObj</tag>
        </method>
    </class>
    <class class_name="SomeClass2">
        <method method="someMethod(java.lang.String)" static="false">
            <tag key="tag_1">returnedObj.foo</tag>
            <log key="log_1">returnedObj.bar</tag>
        </method>
    </class>
</enhanced>
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Welcome to add if this is useful for you.
