### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by songangweb** [apache/skywalking#8298]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-rocketbot-ui)

### What happened

使用在dokcerhub提供的官方镜像 最新版本
https://hub.docker.com/r/apache/skywalking-ui

修改webapp.yml  配置项不生效
discovery:
      client:
        simple:
          instances:
            oap-service:
              - uri: http://xxxxx:12800

只能启动镜像时 设置坏境变量
ENV SW_OAP_ADDRESS="http://xxxxx:12800"

### What you expected to happen

配置文件应该生效

### How to reproduce

新建一个dockerfile

FROM  apache/skywalking-ui:8.9.1

LABEL description="skywalking-ui"

WORKDIR /skywalking

COPY ./build/component/skywalking/ui/webapp.yml /skywalking/webapp/webapp.yml

CMD ["/bin/sh -c /skywalking/docker-entrypoint.sh"]

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
All things on GitHub should be in English. So closing. And what you did private, like private docker image, it is on your own. Not community responsibility.
