### ISSUE TITLE
[Bug]  No data can be searched in trace

### ISSUE THREAD

**Issue by ltx0633** [apache/skywalking#8306]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

No data can be searched in trace, but there are in the data source，It may be found when the search criteria is endpoint name + trace ID

### What you expected to happen

![image](https://user-images.githubusercontent.com/47582550/146367146-322c17ba-8985-4e57-b846-2413fabf1469.png)
![image](https://user-images.githubusercontent.com/47582550/146367271-bae69045-b8b5-45b5-b3a7-303257b6c95e.png)
![image](https://user-images.githubusercontent.com/47582550/146367288-d9f4a28d-3df9-4a50-8533-5ffdf3e48e75.png)

### How to reproduce

      SW_CORE_METRICS_DATA_TTL: 60
      SW_CORE_RECORD_DATA_TTL: 60
      SW_STORAGE_ES_OTHER_METRIC_DATA_TTL: 60
      SW_STORAGE_ES_MONTH_METRIC_DATA_TTL: 60
      SW_STORAGE_ES_RECORD_DATA_TTL: 60
      SW_STORAGE_ES_OTHER_METRIC_DATA_TTL: 60
      SW_STORAGE_ES_MONTH_METRIC_DATA_TTL: 60
      SW_STORAGE_ES_QUERY_MAX_SIZE: 10000
      SW_STORAGE_ES_QUERY_SEGMENT_SIZE: 1000
      SW_STORAGE_ES_QUERY_PROFILE_TASK_SIZE: 1000
      SW_STORAGE_ES_QUERY_MAX_WINDOW_SIZE: 100000

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
There is no endpoint name based query anymore in the latest version.
Check your env, we can see things are good at demo env.
