### ISSUE TITLE
apm-toolkit-log4j-2.x prints %traceId to a thread name+raceId after upgrade to log4j 2.15.0 [Bug] 

### ISSUE THREAD

**Issue by lixplor** [apache/skywalking#8307]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

I'm using apm-toolkit-log4j-2.x to print trace id in the log file. It can be transfer to TID: xxx when using log4j 2.14.1
After upgrading to log4j 2.15.0, the pattern layout `%traceId` is recognized as `%t` with a word `raceId` by log4j. So I got a log like this:

```
2021-12-17 08:00:00.000 INFO http-bio-8080-exec-3raceId c.e.App - This is a message
```

My log4j2.xml pattern layout config:

```
%d{yyyy-MM-dd HH:mm:ss.SSS %-5level %traceId %logger{1.} - %m%n
```

### What you expected to happen

I think there's some changes is new version of log4j. I'm expecting a fix to a newer version

### How to reproduce

Using `log4j 2.15.0`, `apm-tookit-log4j-2.x`
set log4j2 pattern layout with `%traceId`
print a log

### Anything else

Every line of log is printed as this wrong format

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Welcome to feedback about why this is happening. We don't have people working on log4j2 2.15+ yet.

**Comment by lixplor** [comment]
After upgrading to log4j 2.17.0, this issue is fixed. Thanks for your attention. 
Now I'm closing this issue.
