### ISSUE TITLE
[Bug] Nodejs client should emit 'end' after request

### ISSUE THREAD

**Issue by QingkaiLi** [apache/skywalking#8318]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Client Side Agent (apache/skywalking-client-js)

### What happened

By the doc of http [https://nodejs.org/dist/latest-v16.x/docs/api/http.html#class-httpclientrequest](https://nodejs.org/dist/latest-v16.x/docs/api/http.html#class-httpclientrequest)

HttpPlugin should emit 'end' or 'finish' instead of 'close'。 [code](https://github.com/apache/skywalking-nodejs/blob/3c486f17f89a397f89f5fa17cd3e1bd0b61f17f4/src/plugins/HttpPlugin.ts#L122)
```
wrapEmit(span, req, true, 'close');

```

### What you expected to happen

HttpPlugin emit 'end' or 'finish' event after http request，then the span will be reported

### How to reproduce

use the test case 。and nodejs env > 12

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@QingkaiLi We are expecting your pull request. Thanks for your reporting.

**Comment by wu-sheng** [comment]
No update in months.
