### ISSUE TITLE
[Doc] alarm OP "=" do not support

### ISSUE THREAD

**Issue by zhyyu** [apache/skywalking#8333]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I config the backend-alarm according to the doc [https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-alarm/](url). When I use the equal "=" op in the config, I got an IllegalArgumentException "unknown op, ="

### What you expected to happen

I check the code `org.apache.skywalking.oap.server.core.alarm.provider.OP`

```
public static OP get(String op) {
        switch (op) {
            case ">":
                return GREATER;
            case ">=":
                return GREATER_EQ;
            case "<":
                return LESS;
            case "<=":
                return LESS_EQ;
            case "==":
                return EQUAL;
            default:
                throw new IllegalArgumentException("unknown op, " + op);
        }
    }
```

And found that there are no op "=" in the switch, but "==" op exist. So the doc [https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-alarm/](url) 

> OP. The operator. It supports >, >=, <, <=, =. We welcome contributions of all OPs.

which is error. The alarm doc should be updated.

### How to reproduce

config an alarm config including "=" op

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Welcome to contribute.
