### ISSUE TITLE
[Feature] I need log feature ---> [View surrounding documents]

### ISSUE THREAD

**Issue by erdengzhazha** [apache/skywalking#8348]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

it can help me find relevant logs quickly ， Kibana has this feature

### Use case

![image](https://user-images.githubusercontent.com/43720808/147542617-c39563c4-d2e5-4ef3-8189-f965499e2eca.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We have log view already. And we don't have interest comparing to Kibana.

**Comment by erdengzhazha** [comment]
You misunderstand what I mean ,  The logging feature I need is  find  a single log context （查询单个日志的上下文）

**Comment by wu-sheng** [comment]
What is the log context? If you want to discuss some features, please be clear what it is, and what is the use case. 
The point is, don't use 3rd party system(commercial or open source) to say what it is. It doesn't make sense.

**Comment by erdengzhazha** [comment]
![image](https://user-images.githubusercontent.com/43720808/147547834-8c847120-bdd4-48ba-897e-e4e1b0f7469f.png)

**Comment by wu-sheng** [comment]
How you do define this thing? What is the scope? There are thousands of pods running, and a lot of logs are collected.

**Comment by erdengzhazha** [comment]
Ok, I will share with you if I have some ideas for solutions
