### ISSUE TITLE
[Core] TSDB basic data management 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#8392]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

TSDB supports essential storage structure management, containing the below feats:

- [x] Open the database. If the path contains nothing, tsdb creates a new file layout. (https://github.com/apache/skywalking-banyandb/pull/64)
- [ ] ~~Introduce the lock and manifest files to manage file layout.~~
- [x] Make blocks and segments move forward, which means new entries emerge and old ones are pruned. TSDB will introduce a new strategy component to collect metrics and determine when and how to create new blocks. (https://github.com/apache/skywalking-banyandb/pull/70)
- [x] Implement a block controller which determines how many blocks should be active. It closes blocks based on the LRU algorithm. 
- [x] Enhance the data scanner to select blocks based on the query criteria. The scanner has to apply to the block controller for blocks if the blocks are inactive.  

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lujiajing1126** [comment]
Due to the downSampling in the OAP server side, we have to support writing data to a block older than the current open ones.

For example, we start the banyandb server at "2022-01-27T01:40:20Z", the oldest block may start from "2022-01-27T01:40:20Z" while the OAP server would send stream entities with timestamp "2022-01-27T01:00:00Z" due to the downSampling at hour level.

![image](https://user-images.githubusercontent.com/2568208/151276008-fc0675be-5c9a-4fc7-897b-be9df660877c.png)

**Comment by hanahmily** [comment]
> Due to the downSampling in the OAP server side, we have to support writing data to a block older than the current open ones.
> 
> For example, we start the banyandb server at "2022-01-27T01:40:20Z", the oldest block may start from "2022-01-27T01:40:20Z" while the OAP server would send stream entities with timestamp "2022-01-27T01:00:00Z" due to the downSampling at hour level.
> 
> ![image](https://user-images.githubusercontent.com/2568208/151276008-fc0675be-5c9a-4fc7-897b-be9df660877c.png)

Added this to the task list.

**Comment by hanahmily** [comment]
Move the cold writing to 

> > Due to the downSampling in the OAP server side, we have to support writing data to a block older than the current open ones.
> > For example, we start the banyandb server at "2022-01-27T01:40:20Z", the oldest block may start from "2022-01-27T01:40:20Z" while the OAP server would send stream entities with timestamp "2022-01-27T01:00:00Z" due to the downSampling at hour level.
> > ![image](https://user-images.githubusercontent.com/2568208/151276008-fc0675be-5c9a-4fc7-897b-be9df660877c.png)
> 
> Added this to the task list.

Moved to https://github.com/apache/skywalking/issues/8815
