### ISSUE TITLE
日志排序

### ISSUE THREAD

**Issue by wannianxianyu** [apache/skywalking#8400]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

SkyWalking UI中查看收集到的日志信息没办法按照程序的顺序输出（时间戳相同，毫秒）， 貌似毫秒级不满足elasticsearch排序？希望日志的输出顺序可以跟程序控制台一致，这样更容易查看日志

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
All issues on GitHub should be in English. Closing.
