### ISSUE TITLE
[Feature] support zgc metric collect

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#8411]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

zgc is new GarbageCollector from jdk 11, it is the most advanced  GarbageCollector util now, now skywalking gc not support collect the metric

### Use case

agent collect zgc count and time, from skywalking ui we can see 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xu1009** [comment]
@wu-sheng i have a question, zgc not have genration, other gc has old and young

the metirc name in skywalking is  like instance_jvm_young_gc_count,instance_jvm_young_gc_time

now in my project, zgc metric name is instance_jvm_normal_gc_count and instance_jvm_normal_gc_time 

is it ok？look foraward to your suggestions

**Comment by wu-sheng** [comment]
Do you ask for changing https://github.com/apache/skywalking-data-collect-protocol/blob/master/language-agent/JVMMetric.proto#L83?

**Comment by xu1009** [comment]
yes, https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/resources/oal/java-agent.oal

other the oal file, the gc metric name define

> Do you ask for changing https://github.com/apache/skywalking-data-collect-protocol/blob/master/language-agent/JVMMetric.proto#L83?

**Comment by wu-sheng** [comment]
Please submit proposal change to API repo first. Let's do this step by step.

**Comment by xu1009** [comment]
ok
