### ISSUE TITLE
[OAP][Dependency] OAP binary package differences between JDK9 and JDK11

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8412]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This is a memo for all developers, especially @apache/skywalking-committers 

SkyWalking OAP server binaries packaged in JDK8 and JDK11 include different dependence libs. 

This happened before, but I didn't invest why, but I faced this again at https://github.com/apache/skywalking/pull/8405/commits/5f76ea938a7db9e3af534bb9016c360021c5e126. 

J2EE was renamed to Jakarta EE before the JDK11, so, gRPC(maybe other projects too) has a JVM-sensitive dependency mechanism to adopt it. So, when the developer packages the project in JDK11+, some more libs are included in `oap-libs`.

I also checked `8.9.1` image in JDK11, and verified we don't need this even in the runtime. So, generally, we don't need to add these into the license file.

@kezhenxu94 Just a suggestion, do you think we should consider excluding it from gRPC explicitly? Or is this possible? I think if we could, it is better we do this.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
In development stage I think JDK 8 is still our recommendation and used in our official released binary tar, JDKs >8 are supported at runtime and users can package on their own but in that case licenses are not our concern. I think we don't need extra actions unless we decide to move forward to JDK 11 as our recommended development JDK in the future.

**Comment by kezhenxu94** [comment]
One thing noteworthy is that @apache/skywalking-committers who acts as a release manager should release the binary tar in JDK8.

**Comment by wu-sheng** [comment]
The release manager could make mistakes. If excluding is possible in JDK11, it is better to try.

**Comment by kezhenxu94** [comment]
> The release manager could make mistakes. If excluding is possible in JDK11, it is better to try.

Excluding is possible I think. 

If release manager make mistake in this step. Users might face unsupported class versions (compiled in JDK11 and run in Java 8), which conflicts with our claim that we support Java 8 as minimum Java version in OAP.
