### ISSUE TITLE
[Bug] skywalking can not catch the endpoint by python fastAPI

### ISSUE THREAD

**Issue by katelei6** [apache/skywalking#8413]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

we use python，and use fastAPI
config：
from fastapi import FastAPI
from skywalking import agent, config

app = FastAPI()

config.init(collector_address='11.65.20.5:11800', service_name='your awesome service')
agent.start()
@app.get("/test")
async def root():
    return {"message": "Hello World"}

but the UI cannot find the endpoint

### What you expected to happen

so I think skywalking is not support the fastAPI
when we use flask，the endpoint can be catched.

### How to reproduce

![image](https://user-images.githubusercontent.com/79354895/149088268-f1908119-2aab-4694-9402-85b85ce78173.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
FastAPI is not on the support list. Please read document before submitting an issue.

https://skywalking.apache.org/docs/skywalking-python/latest/en/setup/plugins/

**Comment by katelei6** [comment]
if we want to use fastAPI and skywalking can support
we shoud develop the plugin to support?

**Comment by wu-sheng** [comment]
Yes, you need a new plugin.
