### ISSUE TITLE
[Feature] Unified the configuration for all Redis plugins on whether to collect redis parameters.

### ISSUE THREAD

**Issue by ArjenDavid-sjtu** [apache/skywalking#8414]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

There are Jedis, Lettuce and Redission plugins for Redis client in SkyWalking, but only Lettuce plugin have a [`LettucePluginConfig`](https://github.com/apache/skywalking-java/blob/main/apm-sniffer/apm-sdk-plugin/lettuce-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/lettuce/v5/LettucePluginConfig.java) class to define whether to trace redis parameters([added in this PR](https://github.com/apache/skywalking/pull/6614)). While there is no way for Jedis and Redission plugins to do the similar configuration.

### Use case

I think it will be good that all the three Redis plugins act in the same way. Because users are not very concerned about which client they are using, they just want to collect redis parameters for more details or discard redis parameters for better performance. 
So a general configuration for all redis plugins or two more separated configurations for each redis plugin are needed, to define whether to trace redis parameters.

### Related issues

https://github.com/apache/skywalking/issues/6613

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Mostly, the config should belong to the plugin itself. Especially in your case, `Lettuce and Redission` are totally 2 frameworks. They should not share configs unless there is a specific reason. 
If Redission plugin needs some configs, it is better to add inside Redission plugin.

**Comment by ArjenDavid-sjtu** [comment]
Ok, I will commit a PR to add configs for `Redission` and `Jedis`.
