### ISSUE TITLE
[NIGNX-LUA][Bug] require("skywalking.client"):startBackendTimer() config  multiple servers are not supported

### ISSUE THREAD

**Issue by tanshanshan** [apache/skywalking#8423]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Nginx Lua Agent (apache/skywalking-nginx-lua)

### What happened

I use
`require("skywalking.client"):startBackendTimer("http://x.x.x.x:12800")
`is fine
log is 
2022/01/13 11:47:26 [debug] 7491#7491: *6 [lua] client.lua:230: reportTraces(): 1 segments reported.

but  I use
`require("skywalking.client"):startBackendTimer("http://x.x.x.x:12800,http://x1.x1.x1.x1:12800,http://x2.x2.x2.x2:12800")`
error log is 
2022/01/13 11:33:16 [error] 46427#46427: *4 [lua] client.lua:124: reportServiceInstance(): Instance report fails, response code 400, context: ngx.timer

I watch lua code , I think currently support that we can just config one skywalking server

### What you expected to happen

support config multiple skywalking servers

### How to reproduce

`require("skywalking.client"):startBackendTimer("http://x.x.x.x:12800,http://x1.x1.x1.x1:12800,http://x2.x2.x2.x2:12800")`

these addresses are all ok. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is a HTTP server, many proxies exist for cluster mode. No need to support
