### ISSUE TITLE
[Feature] [Java] Support collect thread pool metrics

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#8433]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

thread pool monitor is important in web service, server container, like tomcat, undertow etc, monitor its worker pool is very import, every project needs implement it

### Use case

when use skywalking, we can config target class extends ThreadPoolExecutor, get thread pool metric, like coresize, maxsize, poolsize, queue size..., and send this metric to oap service every second, from ui, can see the metric

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Then we need a way to build a labels(pool name) metric for connection pool. What do you want to build?
Could you provide more details?

**Comment by xu1009** [comment]
now, in my projeject, agent core has a model contains pool name and thead threadPoolExecutor instance, the agent plugin set the thread pool name and instance to it on constructor, and the core get  message from the model, and send metrics to oap service

**Comment by wu-sheng** [comment]
Could you share what do the OAP and UI look like?

**Comment by xu1009** [comment]
instance_undertow_thread_pool_core_size = from(ServiceInstanceJVMThreadPool.corePoolSize).filter(threadPoolNameType == ThreadPoolNameType.UNDERTOW).longAvg();
instance_undertow_thread_pool_max_size = from(ServiceInstanceJVMThreadPool.maximumPoolSize).filter(threadPoolNameType == ThreadPoolNameType.UNDERTOW).longAvg();
instance_undertow_thread_pool_size = from(ServiceInstanceJVMThreadPool.poolSize).filter(threadPoolNameType == ThreadPoolNameType.UNDERTOW).longAvg();
instance_undertow_thread_pool_queue_size = from(ServiceInstanceJVMThreadPool.queueSize).filter(threadPoolNameType == ThreadPoolNameType.UNDERTOW).longAvg();
instance_undertow_thread_pool_active_count = from(ServiceInstanceJVMThreadPool.activeCount).filter(threadPoolNameType == ThreadPoolNameType.UNDERTOW).longAvg();


message ThreadPool {
    ThreadPoolNameType type = 1;
    int64 corePoolSize = 2;
    int64 maximumPoolSize = 3;
    int64 poolSize = 4;
    int64 queueSize = 5;
    int64 activeCount = 6;

}

enum ThreadPoolNameType {
    UNDERTOW_WORKER_POOL = 0;
    TOMCAT_WORKER_POOL = 1;
}


![image](https://user-images.githubusercontent.com/22722907/149704058-2878ba41-13d6-4aef-985d-be8c09280ef1.png)

**Comment by wu-sheng** [comment]
This kind of filter function is very hard coded, and it has to set for all kinds of pools, which is not flexible, and have to set a lot of UI components to list all possibilities.
I am thinking whether we should treat this as a logic endpoint? And metrics reporting through meter API rather than JVM and OAL analysis.

**Comment by xu1009** [comment]
emm, the agent plugin  and oap server is easy to add new thread pool,  the problem is how to display it in ui, i am not familiar with what you say, this has some demo in skywalking project，or, we can make basic plugin to collect metirc and save it, every one can customizing their dashboard ui

**Comment by wu-sheng** [comment]
For agent side, it is very similar to agent tracing plugin. Just calling different core APIs. Check this.

https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/java-plugin-development-guide/#meter-plugin

**Comment by wu-sheng** [comment]
At the backend, you just need to learn meter receiver and MAL

1. https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-meter/#manual-meter-api
2. Meter design, https://skywalking.apache.org/docs/main/latest/en/concepts-and-designs/meter/
3. MAL, https://skywalking.apache.org/docs/main/latest/en/concepts-and-designs/mal/

And learn fron slueth MAL setup
1. https://skywalking.apache.org/docs/main/latest/en/setup/backend/spring-sleuth-setup/
2. Configuration file example, https://github.com/apache/skywalking/blob/fc27f766c5da0f4165152025a6ba4080d034d1fc/oap-server/server-starter/src/main/resources/meter-analyzer-config/spring-sleuth.yaml

**Comment by xu1009** [comment]
ok, i have a look

**Comment by xu1009** [comment]
i have tried, it is ok，plugin can give the  threadPoolExecutor instance,  and agent core build thread pool metrics, and send it to backend by meter api

**Comment by wu-sheng** [comment]
It is good to know. Could you post the metric sample here? To make the further review easier?

**Comment by xu1009** [comment]
![image](https://user-images.githubusercontent.com/22722907/149902103-ef7a634a-ea27-4f33-9244-2876363b0e2e.png)

![image](https://user-images.githubusercontent.com/22722907/149902167-b39e052e-b84f-4143-9890-8d5e50b27c4a.png)

**Comment by wu-sheng** [comment]
I think we should use `labeled value`, which only requires one metric name in the MAL script. And UI's component title could be `Thread Pool`,  which could add more pool relative metrics easily.

**Comment by xu1009** [comment]
i do not get your mean, there are many kinds of thread pool, every type thread pool can have a ui component, all in one seems strange，and it is difficult to look

**Comment by xu1009** [comment]
i think we can provide some base thread pool metric collect, like undertow, tomcat, other user can easy to add based on this way, and they can custom their own ui component

**Comment by wu-sheng** [comment]
> i do not get your mean, there are many kinds of thread pool, every type thread pool can have a ui component, all in one seems strange，and it is difficult to look

We don't have to set all thread pool metrics in one UI component. But `labeled value` could reduce the cost of the database resources. The way you are doing right now, is making one metric per database row. But labeled value could compress all types(queue size, pool size, max pool size) into one metric name.

```
undertow_thread_pool{pool_name="undertow_pool1",type="pool_size"} 10
undertow_thread_pool{pool_name="undertow_pool2",type="pool_size"} 15
undertow_thread_pool{pool_name="undertow_pool2",type="max_size"} 20
```

Then you just need one metric name on the UI, `undertow_thread_pool`.

**Comment by xu1009** [comment]
you mean the agent report metric with same name and different tags by meter api ?

**Comment by wu-sheng** [comment]
Yes. And AFAIK the MAL could land this one metric name with different tags in the storage.

**Comment by wu-sheng** [comment]
This config still could make the metrics into different metric name. I prefer we could do
```
metricsRules:
    - name: java_thread_pool
       exp: java_thread_pool
```
If you want to separate pools of Java, you could use  `undertow_thread_pool`. And types of `metric_type` is going to be available on the UI automatically as labels.

Coud you try this? @wankai123 could help if you face any issue.

**Comment by xu1009** [comment]
i try, it not work, could you give some demo with ui template and oal config

**Comment by wu-sheng** [comment]
Check K8s monitoring temple config. Or just put the metric name on UI setup mode page, and enter. It will tell you, it's a labeled value.
Don't use tag equal to split one metric into several.

**Comment by wu-sheng** [comment]
This is a labeled value metrics visualized as a chart
![image](https://user-images.githubusercontent.com/5441976/150038471-10f7d54b-ef4d-4f52-b0fd-044ff525ffc8.png)
![image](https://user-images.githubusercontent.com/5441976/150038517-d1bf2966-dc93-4a3e-9a30-3724e2fcdf04.png)

**Comment by xu1009** [comment]
![image](https://user-images.githubusercontent.com/22722907/150060150-d49e19a1-5dee-43de-9a12-10a39dafcc15.png)

![image](https://user-images.githubusercontent.com/22722907/150060306-3ff3f22f-df3f-40aa-9612-a3cf0b4e9c62.png)


![image](https://user-images.githubusercontent.com/22722907/150060184-a80b6442-1a59-4f34-a4f3-72e811ad92fc.png)

![image](https://user-images.githubusercontent.com/22722907/150060215-5b38f6f6-8543-41fc-8f66-5e052b197cde.png)


yes, i config it in this way, but, it has no data in ui

**Comment by wu-sheng** [comment]
Could you check what does the metric look like in the database?

**Comment by wu-sheng** [comment]
And please provide the data in the MeterReceiver. Then we could know what is going on.

**Comment by xu1009** [comment]
<img width="1244" alt="企业微信截图_f3a61c2b-75c1-4388-b698-5050d9f59509" src="https://user-images.githubusercontent.com/22722907/150081024-af46573e-d93b-43a4-a654-c780cd6ff128.png">

this is the data from MeterServiceHandler， the database is h2, i do not have tool to look

**Comment by wu-sheng** [comment]
Could you put this in JSON format? And print it in the console, and provide us the rawdata? This debug screenshot is hard for us to know the details.

**Comment by xu1009** [comment]
{"metricCase_":1,"metric_":{"name_":"thread_pool","labels_":[{"name_":"metric_type","value_":"active_size","memoizedIsInitialized":-1,"unknownFields":{"fields":{}},"memoizedSize":-1,"memoizedHashCode":0},{"name_":"pool_name","value_":"undertow_worker_pool","memoizedIsInitialized":-1,"unknownFields":{"fields":{}},"memoizedSize":-1,"memoizedHashCode":0}],"value_":0.0,"memoizedIsInitialized":-1,"unknownFields":{"fields":{}},"memoizedSize":-1,"memoizedHashCode":0},"service_":"Your_ApplicationName","serviceInstance_":"e33531aac85b4b93b8404b4f5f008fc8@192.168.255.10","timestamp_":1642576599799,"memoizedIsInitialized":1,"unknownFields":{"fields":{}},"memoizedSize":-1,"memoizedHashCode":0}

**Comment by xu1009** [comment]
{"metricCase_":1,"metric_":{"name_":"thread_pool","labels_":[{"name_":"metric_type","value_":"max_pool_size","memoizedIsInitialized":-1,"unknownFields":{"fields":{}},"memoizedSize":-1,"memoizedHashCode":0},{"name_":"pool_name","value_":"undertow_worker_pool","memoizedIsInitialized":-1,"unknownFields":{"fields":{}},"memoizedSize":-1,"memoizedHashCode":0}],"value_":80.0,"memoizedIsInitialized":-1,"unknownFields":{"fields":{}},"memoizedSize":-1,"memoizedHashCode":0},"service_":"","serviceInstance_":"","timestamp_":0,"memoizedIsInitialized":1,"unknownFields":{"fields":{}},"memoizedSize":-1,"memoizedHashCode":0}

**Comment by wu-sheng** [comment]
@wankai123 @mrproliu Could you take a look? I hope the final result keep `thread_pool` as metric name, and labels(undertow_worker_pool + max_pool_size) as the final label.

@xu1009 It is better you could use `H2` server mode to check the data, or ElasticSearch. Otherwise, it is hard for us to help this very detailed thing.

**Comment by mrproliu** [comment]
In the MAL, if you want to make it as labels metrics, need to add the  aggregate function on the metric. In this case, it should be thread_pool.avg(['pool_name', 'metrx_type', 'service']).

**Comment by xu1009** [comment]
![image](https://user-images.githubusercontent.com/22722907/150095867-59abaa71-4b5d-405b-aea8-57e87b57a3d3.png)

it is not ok, the above image is data in database

**Comment by wu-sheng** [comment]
The data looks good, what do you mean `not ok`?
![image](https://user-images.githubusercontent.com/5441976/150096504-435e8fd8-e23b-47c2-ae27-1b44e0b7a73f.png)

This is my understanding of the data.

**Comment by xu1009** [comment]
![image](https://user-images.githubusercontent.com/22722907/150101656-3ca65f63-3070-43a3-b8cf-4356455f5c52.png)

![image](https://user-images.githubusercontent.com/22722907/150101730-3cde927c-23b2-4317-bd0f-1a6aacdff8a9.png)

no data display in ui

**Comment by wu-sheng** [comment]
Do you check the instance name(entity name in the table) and time bucket?

And, you could debug `MetricsQuery#readLabeledMetricsValues` to see what is going on. The logic is also not hard.

**Comment by wu-sheng** [comment]
@xu1009 Any update?

**Comment by xu1009** [comment]
![image](https://user-images.githubusercontent.com/22722907/150175697-c3070ab7-65ad-40c6-a0bf-8546c33d04b3.png)

it is ok

**Comment by wu-sheng** [comment]
Cool, good to see this. Let's move on to the official PR/Review to take care of code details. Thank you so much for you patience.

**Comment by wu-sheng** [comment]
@xu1009 Are you going to add more meter plugins for thread pools?
