### ISSUE TITLE
[SWCK] Could not deploy metrics adapter to GKE 

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#8437]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

SWCK (apache/skywalking-swck)

### What happened

I got an error when I deploy the SWCK metrics adapter in the 0.6.0 release version.

error message: 
F0117 03:59:06.697216       1 main.go:80] unable to run custom metrics adapter: error creating self-signed certificates: mkdir apiserver.local.config: permission denied

screenshots:
![image](https://user-images.githubusercontent.com/3417650/149706129-96ee52db-943b-4000-9cd1-e2f8e854de3d.png)

### What you expected to happen

I want the metrics adapter could work.

### How to reproduce

1. Create a new GKE cluster.
2. Download the 0.6.0 release on the official download page.
3. Apply the `config/adapter-bundle.yaml`.

Then, the adapter pod would be crash. 

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@hanahmily We seem need a hot patch release.
