### ISSUE TITLE
[Bug] for python-agent, the oap-ui does not show my python serviceName

### ISSUE THREAD

**Issue by little-hang** [apache/skywalking#8444]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

1、my configure
python 3.7.3
skywalking 8.9.1

2、my python code as follows:
`import json
import requests
import base
from flask import Flask, request
from skywalking import agent, config

config.init(collector_address='127.0.0.1:11800', service_name='serviceA', log_reporter_active=True)  
config.flask_collect_http_params = True
agent.start()
app = Flask(__name__)

@app.route('/get_beheaves', methods=['POST'])
def delete_regress_tasks():
    print(111, request.headers)
    input_param = request.get_json()
    # Step1
    url = "http://127.0.0.1:8884/is_adult"
    headers = {
        'Content-Type': 'application/json'
    }
    response = requests.request("POST", url, headers=headers, data=json.dumps(request.get_json()))
    print('Step1:', response.text)
    is_adult = json.loads(response.text)['is_adult']
    # Step2
    base.thread_test()
    # Step3
    ret = base.decide_beheave(is_adult)
    return json.dumps(ret)
    

if __name__ == '__main__':
    app.run(debug=True)
`
3. the oap-ui does not show my python serviceName

### What you expected to happen

Problem: the oap-ui does not show my python serviceName
![image](https://user-images.githubusercontent.com/24517540/149904473-d5a9d76d-c4de-4903-98c9-89e028629336.png)

The OAP logs:
![image](https://user-images.githubusercontent.com/24517540/149905296-ef6e874e-e791-45b8-8c3c-653008d3b10e.png)

### How to reproduce

ask for help

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Duplicated https://github.com/apache/skywalking/discussions/8443
