### ISSUE TITLE
develop the plugin error！ModuleNotFoundError: No module named 'skywalking.protocol.logging'

### ISSUE THREAD

**Issue by katelei6** [apache/skywalking#8452]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

when we git clone the python agent，want
 to develop the plugins, when we install the package, running, the error:  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.7/site-packages/skywalking/agent/__init__.py", line 24, in <module>
    from skywalking.protocol.logging.Logging_pb2 import LogData
ModuleNotFoundError: No module named 'skywalking.protocol.logging'

### What you expected to happen

we can not find the logging in skywalking.protocol

### How to reproduce

we can not find the logging in skywalking.protocol

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Reading the compiling doc. The git submodule is required.
