### ISSUE TITLE
Skywalking能监控weblogic下的应用吗

### ISSUE THREAD

**Issue by POPIWEN0209** [apache/skywalking#8456]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

是不是不支持监控weblogic下的应用

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
All issues on GitHub must be in English.
