### ISSUE TITLE
[Feature] we develop plugin to support mysqlclient

### ISSUE THREAD

**Issue by katelei6** [apache/skywalking#8462]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[Feature] we develop plugin to support mysqlclient,  can you see out code to contributing ?

### Use case

[Feature] we develop plugin to support mysqlclient,  can you see out code to contributing ?

### Related issues

[Feature] we develop plugin to support mysqlclient,  can you see out code to contributing ?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Which language agent do you mean? Could you be more specific? All agent repositories accept pull requests to add a new plugin in the mainstream. You just need to follow all the tests and reviwers' comments.

**Comment by katelei6** [comment]
I have an question: 我们的组件信息是Unknown，但是python的文件__init__里面，我们设置了MysqlClient = 7013，但是没有获取到这个值@wusheng

**Comment by wu-sheng** [comment]
@katelei6 Please keep in English if you want to GitHub discussion. Please translate above first.

**Comment by katelei6** [comment]
I have an question:  we can see the infomation about trace in UI,  but the component infomation is  Unknown，
but in  our python file：  __init__.py，we  set MysqlClient = 7013，but can not use this

**Comment by wu-sheng** [comment]
I can see python mysql plugin is using `component_id=7003`, check here 

https://github.com/apache/skywalking-python/blob/d4e5ccd8b1e6d08a3c9eeb748ede8c99ff261895/skywalking/plugins/sw_pymysql.py?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L40

The definition is from here, check the file and OAP version you are using.

https://github.com/apache/skywalking/blob/2c8504a3edbabb47fef6fcd1e3d2301688a09f72/oap-server/server-starter/src/main/resources/component-libraries.yml#L532-L534

**Comment by katelei6** [comment]
if we develop the plugin support mysqlclient, this can we contruibute? beause in our project, we use mysqlclient instead of pymsql, so we develop this new plugin.

**Comment by wu-sheng** [comment]
You could send a pull request to https://github.com/apache/skywalking-python, and add the required tests.

**Comment by wu-sheng** [comment]
If you need MySQL component id, check the file I shared above. It should be `5`
```yaml
Mysql:
  id: 5
  languages: Java,C#,Node.js
```

And you need to send a pull request here to add Python in the `languages`.

**Comment by katelei6** [comment]
remote: Permission to apache/skywalking-python.git denied to katelei6.
fatal: unable to access 'https://github.com/apache/skywalking-python/': The requested URL returned error: 403

**Comment by wu-sheng** [comment]
Check your network. It is only a GitHub repo. It is as same as here.
