### ISSUE TITLE
[Feature] Support Google Guava AsyncEventBus

### ISSUE THREAD

**Issue by wallezhang** [apache/skywalking#8482]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Google guava `EventBus` is a component used to deliver distribution events in the process. When asynchronous distribution is used, trace will be lost, so I want to provide a plugin to support propagating trace information.

### Use case

When use `com.google.common.eventbus.EventBus#post` method to dispatch a event, inject trace context to the event and extract in execution thread context.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wallezhang** [comment]
@wu-sheng Hi, How should I know which type of plugins need to be put into optional-plugins module?

**Comment by wu-sheng** [comment]
Generally, if a plugin could impact the performance(such as collecting parameters, due to serialization costing), or generate many spans expectedly(such as Spring's bean annotation, it is unpredictable), then it is safer to be put in the optional. So, usually JDK rt.jar level instrumentation should be optional.

**Comment by wallezhang** [comment]
OK, I see. Thanks for your reply.

**Comment by wallezhang** [comment]
@wu-sheng Because of `post(event)` method parameter type is `Object`, so I can't define enhanced class in the instrumentation stage. So is there any way to enhance a class or inject a virtual field to the instance dynamically?

**Comment by wu-sheng** [comment]
I am afraid not. Usually, you have to make a wrapper to host this `object` and context snapshot, and unwrap it to the original object in the event processor(or some consuming concept in `AsyncEventBus`.
