### ISSUE TITLE
[Bug] Broken links on download page

### ISSUE THREAD

**Issue by sebbASF** [apache/skywalking#8498]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Nginx Lua Agent (apache/skywalking-nginx-lua)

### What happened

The download page links for the 0.6.0 lua code are broken.

Also the source for a current release MUST be served from the mirror system, i.e. it must be present under 

https://downloads.apache.org/skywalking/nginx-lua/0.6.0/

It looks like the wrong names have been used here.

Please fix urgently

### What you expected to happen

As above

### How to reproduce

As above

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Hi, I checked the links and files, the file names were not in the correct format by the release manager, and kept `latest` in the name.
I fixed them in https://dist.apache.org/repos/dist/release/skywalking/nginx-lua/0.6.0/, but https://archive.apache.org/dist/skywalking/nginx-lua/0.6.0/ is not updated. 

Is there a period task running in the background? Should we wait or do something?

**Comment by wu-sheng** [comment]
This download link works now, https://www.apache.org/dyn/closer.cgi/skywalking/nginx-lua/0.6.0/skywalking-nginx-lua-0.6.0-src.tgz

**Comment by sebbASF** [comment]
Thanks, the download page is good now.

The archive may take up to a day to catch up.
