### ISSUE TITLE
[Python] [Bug] sw-rabbitmq TypeError when there are no headers (pre-sw messages)

### ISSUE THREAD

**Issue by dcryans** [apache/skywalking#8499]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

Started a rabbitmq consumer on an environment with messages already present in a queue.
These messages don't use headers

I got an error that looked like this 'Stream Connection Lost: Type Error null is not iterable'

It's important for this to work to make sure we don't break production when we deploy skywalking (our queues always contain data)

I am willing to create the PR myself but will need some guidance.
I really like this project and could bring more PRs in the future.

### What you expected to happen

I expected the instrumentation not to kill my application

### How to reproduce

Add messages to rabbitmq without headers (without sw implementation)
Then consume them with a sw-rabbitmq instrumented python app

### Anything else

So the fix I did in the agent's code is very basic
I don't know what kind of error handling you guys expect.

![image](https://user-images.githubusercontent.com/14256909/152231902-6a6e7979-f69c-4c00-a8b2-9772d8942940.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Hi @dcryans , thanks for reporting this and sharing the details, your fix with `try-except` looks kind of overkill to me and it might be expensive .

What about adding a condition `header_frame.properties.headers is not None` before the `for` loop so that we don't need to go into the loop if there is no header, otherwise it will be throwing and catching over and over again, that's unnecessary.

If you agree please directly file a pull request to apache/skywalking-python repo, thanks!

**Comment by dcryans** [comment]
Hi @kezhenxu94,

Usually, from what I know, try/except (or catch in java) will be less expensive when everything goes well and more expensive if it goes bad

Since SkyWalking is adding headers to messages, I thought try except would be faster in most cases

Here's an example of try vs if:
https://stackoverflow.com/questions/2522005/cost-of-exception-handlers-in-python

Unless most people only instrument part of their stack? Then messages from instrumented apps would be more expensive.

Let me know what you prefer, then I'll send the PR.

**Comment by kezhenxu94** [comment]
> Hi @kezhenxu94,
> 
> Usually, from what I know, try/except (or catch in java) will be less expensive when everything goes well and more expensive if it goes bad
> 
> Since SkyWalking is adding headers to messages, I thought try except would be faster in most cases
> 
> Here's an example of try vs if:
> https://stackoverflow.com/questions/2522005/cost-of-exception-handlers-in-python
> 
> Unless most people only instrument part of their stack? Then messages from uninstrumented apps would be more expensive.
> 
> Let me know what you prefer, then I'll send the PR.

Do you mean if the header exists the condition I suggested to add will contrarily pull down the performance but remain nearly the same with the `try-except`? If so, feel free to use `try-except` as you said the headers should exist for most cases.

**Comment by dcryans** [comment]
Hi @kezhenxu94,

So how do I get the permission to create the branch?


Thank you!

**Comment by kezhenxu94** [comment]
> Hi @kezhenxu94,
> 
> 
> 
> So how do I get the permission to create the branch?
> 
> 
> 
> 
> 
> Thank you!

You creat a fork repository under you account, create a branch and send pull request to the upstream repository, then we'll review and merge into the official repository.
