### ISSUE TITLE
[Feature] Add curl tag on springmvc span, which is useful to reproduce bug and fix bug.

### ISSUE THREAD

**Issue by chenzz** [apache/skywalking#8500]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add curl tag on springmvc span, which is useful to reproduce bug and fix bug.

### Use case

Image the case:
> QA send the developer a traceId, and say,
> "The response of the traceId is not right"
> 
> The developer get the traceId, but could not find the problem, so he decided to reproduce the problem, and debug the system.

In this case, curl is very useful for developer to reproduce the bug and debug!

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/5676311/152592903-197ca586-ef08-40ee-aa64-ef871557417a.png">

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/5676311/152593151-2ca3b467-4172-40d1-8895-cb8202058116.png">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
URL, URI and HTTP method, evem with headers are in tags already. Tracing system has to work effectively in high traffic load, this new tag seems not worth.

**Comment by wu-sheng** [comment]
In some cases, the request could be POST, and the request body would be huge, this tag is very likely causing potential memory issue for few use cases.

**Comment by chenzz** [comment]
> URL, URI and HTTP method, evem with headers are in tags already. Tracing system has to work effectively in high traffic load, this new tag seems not worth.

You are right, seems I should change the code of skywalking UI, rather than skywakking agent..

Show the curl command base the old tag, right?

**Comment by wu-sheng** [comment]
UI optimization is fine, but you should notice this of Rockbot UI

> Rocketbot UI is replaced by the new [Booster UI](https://github.com/apache/skywalking-booster-ui) since 9.0.0 release.

So, we are establishing the booster UI in a new repo, https://github.com/apache/skywalking-booster-ui. This is not done yet. I would like to recommend you submitting a pull request after this UI is ready.

**Comment by wu-sheng** [comment]
Closing this.

**Comment by chenzz** [comment]
Got it.

Do you know, What is the booster UI release plan?

**Comment by wu-sheng** [comment]
@Fine0830 is the PMC member initializing it. Our plan is around March, 99% of the backend is ready for it.
