### ISSUE TITLE
[Feature] [BanyanDB Java Client] Implement Java Client for first BanyanDB release

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8502]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The repo has been created, https://github.com/apache/skywalking-banyandb-java-client

We should follow @hanahmily 's first BanyanDB protocols, and implement all features on top of gRPC Java.

@hanahmily please sync with Zhenxu about the latest protocols.
@kezhenxu94 Please evaluate the existing code.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
@lujiajing1126 Pls submit the java client issues found in the stream module integration.

**Comment by hanahmily** [comment]
done
