### ISSUE TITLE
[Feature] [BanyanDB Java Client] Support Sharding from cluster side.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8503]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In BanyanDB, we agree on supporting sharding-based cluster mode.  is not in the high priority on the server-side, because the only advantages of this are database runtime scaling, but it is too early to say so in a new database.
Meanwhile, client-side sharding is not hard with the experience of building Apache ShardingSphere for years, and we have our native protocol and OAP all in control.

We should support static configuration-based sharding to work with multiple BanyanDB servers with each one of them having native replication. This feature could exist for long term until BanyanDB has its cluster mode(at least later than 0.3.0 server release, @hanahmily right?)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
The liaison module is designed as the gateway of the banyandb server. It has the capacities of traffic routing, service discovering, and sharding. Banyandb's modules have a chance to run as a standalone process. To liaison's case, we have start-up a process where this module is only loaded. The idea likes the ingest node of Elasticsearch.

We could add the sharding feature to the liaison as our original design based on the above. I don't tend to support a client-side sharding in banyandb java client. Another critical downside of rich client solutions is the multi-language support. We have to implement the sharding feat in several clients, the command-line tool, and the UI. A thin-client path is better for us from my perspective.

**Comment by wu-sheng** [comment]
Yes, we will do the traffic routine in the Liaison. What I proposed here is a temporary solution. I don't push too hard on the cluster direction, as clearly, replication and data sync mechanism are more important.
This is a minimal step in the project establishment.
