### ISSUE TITLE
[Feature] [BanyanDB] Establish CLI

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8505]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The CLI is a good first step for a BanyanDB native go client helping developers to check data. @hanahmily designed the repo of BanyanDB server(https://github.com/apache/skywalking-banyandb) as a golang monorepo, so, let's add the CLI inside the same repo.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
We are referring to the same feature here right? https://github.com/apache/skywalking/issues/9047 Shall we close one of them?

**Comment by wu-sheng** [comment]
@hanahmily Are these duplicated?

**Comment by hanahmily** [comment]
yep, let's close this one since we have some discussion in #9047
