### ISSUE TITLE
[Feature] [BanyanDB] Support OR logical operator for query

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#8513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, all query conditions specified in the query criteria are implicitly combined with `AND`.

### Use case

We need `OR` semantics in the condition for the following scenarios,

1. Topology query
2. Event query: `Events queryEvents(List<EventQueryCondition> conditionList)`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@lujiajing1126 You are a committer now, please pick the suitable labels and milestone for the issue(s).

**Comment by lujiajing1126** [comment]
Got it

**Comment by hanahmily** [comment]
After some investigation, topology querying relies on `in` operation, which has been supported. There is a single scenario: event querying, which needs `or`.

To support `or` logical operation, we have to bring a breaking change to the current querying message structure, rebuild the querying process and update java-client accordingly. Comparing the wide range of changes and the trivial use case, I would like to move this to 0.2.0. 

@dmsolr You have to union and distinct results on implementing the `EventQueryDao` before supporting this.

**Comment by hanahmily** [comment]
Closed by https://github.com/apache/skywalking-banyandb/pull/170
