### ISSUE TITLE
[Bug] TimeRange in the query is out of range

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#8514]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

For the well-known [`timestamp`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#timestamp) type from protobuf,

> Range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By restricting to that range, we ensure that we can convert to and from RFC 3339 date strings. See https://www.ietf.org/rfc/rfc3339.txt.

However, in the implementation of BanyanDB, the bound of time (epoch nanoseconds) is represented by the type of `int64`, thus the time range should adhere to this limitation.

https://github.com/apache/skywalking-banyandb/blob/b61ab295c38c672ca7aa60e308d0d64037272766/banyand/tsdb/series_seek_sort.go#L113-L116

### What you expected to happen

The time range should be limited by the bound from `1677-09-21 00:12:43.145224194` to `2262-04-11T23:47:16.854775806Z`. This is also the default value in [`influxdb`](https://www.influxdata.com/blog/tldr-influxdb-tech-tips-november-10-2016/).

1. The `sw-banyandb-java-client` should impose this range check.
2. The liaison module or the query parser should validate this boundary.
3. OAP storage module should be careful with this.

### How to reproduce

For example, use `9999-12-31T23:59:59.999999999Z` as the upper bound of the time range, we would get nothing from the database which is not expected.

### Anything else

> Q: What’s the maximum timestamp that InfluxDB can handle?
> A: The maximum timestamp is 9223372036854775806 or 2262-04-11T23:47:16.854775806Z. The minimum timestamp is -9223372036854775806 or 1677-09-21T00:12:43.145224194Z.
> InfluxDB returns a [parsing error](https://docs.influxdata.com/influxdb/v1.0/troubleshooting/errors/#unable-to-parse-time-outside-range) if your point has a timestamp outside that time range.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
`int64` should represent the millisecond. If protocol is expecting nanoseconds, how about we use timestamp rather than int64?
