### ISSUE TITLE
[Enhancement] Align protoc version with protobuf-java version

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#8522]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In #8405, grpc and protobuf versions have been upgraded to avoid a CVE issue.

Then I suppose the corresponding `protoc` should also be upgraded to avoid potential conflicts.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Thanks for fixing this.

**Comment by kezhenxu94** [comment]
> In #8450, grpc and protobuf versions have been upgraded to avoid a CVE issue.

Looks like you link to a wrong issue

**Comment by lujiajing1126** [comment]
> > In #8450, grpc and protobuf versions have been upgraded to avoid a CVE issue.
> 
> Looks like you link to a wrong issue

Thanks! It should be 8405 instead of 8450.

**Comment by lujiajing1126** [comment]
Also I noticed the mac-M1 compilation FAQ
https://github.com/apache/skywalking/blob/master/docs/en/FAQ/How-to-build-with-mac-m1.md

Shall we update this FAQ since the Apple Silicon support has already been added from `protobuf` 3.17.3.

**Comment by wu-sheng** [comment]
> Also I noticed the mac-M1 compilation FAQ https://github.com/apache/skywalking/blob/master/docs/en/FAQ/How-to-build-with-mac-m1.md
> 
> Shall we update this FAQ since the Apple Silicon support has already been added from `protobuf` 3.17.3.

Noticed, personally, I want to keep. Because we can't upgrade for earlier releases, which is still not working in M1. But the `search` on the right top of website is only working for the latest doc. I and @Jtrust are knowing this issue for months, but we are still too busy to find a solution.
