### ISSUE TITLE
[Feature] UI add Top-N metric click query entity info

### ISSUE THREAD

**Issue by sunOnly** [apache/skywalking#8541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

UI add Top-N metric click query entity info

### Use case
![image](https://user-images.githubusercontent.com/22111568/153707388-5e80c90a-76a8-435d-bc40-656c3966990c.png)

### Related issues
https://github.com/apache/skywalking-rocketbot-ui/issues/568
_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
A new UI is replacing the rocketbot UI
