### ISSUE TITLE
[Feature] [E2E-INFRA] Make skywalking-infra-e2e work with docker-compose V2

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#8567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the current `skywalking-e2e-infra` implementation, the logic of building container name is hard-coded with `_` as the separator. While using with `docker-compose` v2, it is incompatible,

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/2568208/155049517-17cbd981-4054-48d6-a255-ddf32b1506e7.png">

https://github.com/docker/compose/blob/5becea4ca9f68875334c92f191a13482bcd6e5cf/compose/service.py#L1492-L1498

In the latest version (written in `go`), [`-` is used](https://github.com/docker/compose/blob/981aea674d052ee1ab252f71c3ca1f9f8a7e32de/pkg/compose/convergence.go#L252-L257). So the container created cannot be found, and thus the program exits unexpectedly.

<img width="994" alt="image" src="https://user-images.githubusercontent.com/2568208/155049970-584c28f0-32d8-4f88-a767-6f5d36dee719.png">

A possible approach to solve this is to check `docker-compose` version in the `infra-e2e` and use different strategies for v1 and v2.

Another possible solution is to compare the container name by ignoring the difference between `_` and `-` .

### Use case

Currently, docker-compose v1 is not under active maintenance.

We may support v2.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@kezhenxu94 Please take a look and confirm the way it will change.

**Comment by kezhenxu94** [comment]
> compare the container name by ignoring the difference between _ and - .

this sounds good to me.

**Comment by wu-sheng** [comment]
@lujiajing1126 Notice, you are using a wrong prefix of issue name, this should be `[E2E-INFRA]`, not `CLI`.

**Comment by lujiajing1126** [comment]
> @lujiajing1126 Notice, you are using a wrong prefix of issue name, this should be `[E2E-INFRA]`, not `CLI`.

Thanks for pointing out. Fixed.
