### ISSUE TITLE
[Bug] when trigger equal times, it do not stop

### ISSUE THREAD

**Issue by ethan256** [apache/skywalking#8589]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Infra E2E (apache/skywalking-infra-e2e)

### What happened

When the trigger reaches the specified number of times, it does not stop

### What you expected to happen

it is should stop current goroutine.
[docs](https://skywalking.apache.org/docs/skywalking-infra-e2e/latest/en/concepts-and-designs/module-design/)

### How to reproduce

when times equal executedCount, return current goroution

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Hi @ethan256 , thanks for raising this, actually, this is by design and the doc is kind of outdated,

```
- times: How many times to trigger the action, 0=infinite.
```

this should be: "how many times to trigger the action before aborting if the trigger failed, or continue if the trigger succeeded"

**Comment by kezhenxu94** [comment]
@ethan256 would you like to open a pull request to fix the doc?

**Comment by ethan256** [comment]
1. when trime is bigger, the err chan not return first error.
2. when interval equal execute timeout, time.NewTicker maybe exec again

**Comment by ethan256** [comment]
when times is bigger, the err chan not return first error.
when interval equal execute timeout, time.NewTicker maybe exec again

**Comment by kezhenxu94** [comment]
> when the `times` is large, the `err chan` does not return first error but the last one,

`err chan` should return the last one, why do you want to return the first one error? For example, if the target service is not ready, trigger request may return error `connection refused`, and after some retries, the service is ready but you are request a non-existing path `/api/non-existing`, why would you expect to get the first error (`connection refused`) instead of the last one (`404 Not Found`)?

**Comment by ethan256** [comment]
[`h.times == h.executedCount` makes sure to only send the first error](https://github.com/apache/skywalking-infra-e2e/blob/main/internal/components/trigger/http.go#L82)
