### ISSUE TITLE
[Bug] Abnormal problems in the use of apm-trace-ignore-plugin 

### ISSUE THREAD

**Issue by qiyue0421** [apache/skywalking#8593]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Currently, skywalking version is 8.9.0 and skywalking Java agent version is 8.8.0

I want to filter the endpoint `POST: / checktoken` on the agent side

How to set the configuration file APM trace ignore plugin As defined in config, the following configuration does not seem to take effect:
`trace. ignore_ path=${SW_AGENT_TRACE_IGNORE_PATH:Lettuce/**,Mysql/**,xxl-job/**,SpringScheduled/**,POST:/checkToken}`

At present：
`Lettue / * *, MySQL / * *, XXL job / * *, springscheduled / * *` can take effect normally
`Post:/checktoken` cannot take effect

![image](https://user-images.githubusercontent.com/33716216/155673329-dfaf9381-6762-4034-a203-00896a4c5ea6.png)
I look forward to your reply very much. Thank you

### What you expected to happen

Failed to take effect in test environment

### How to reproduce

Use the current version of plugins to reappear.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Try this in agent 8.9.0. https://github.com/apache/skywalking-java/pull/81

And if you want to report a bug, it is better to locate why the match fails, we can't have your applications.

**Comment by qiyue0421** [comment]
![image](https://user-images.githubusercontent.com/33716216/155678333-70c78d79-5860-403c-ab14-70fe8e0f1371.png)
