### ISSUE TITLE
[Bug] SW_TRACE_IGNORE_PATH not work

### ISSUE THREAD

**Issue by katelei6** [apache/skywalking#8604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

export SW_AGENT_INSTANCE=11.67.108.15
export SW_TRACE_IGNORE_PATH=/nacos/v1/ns/instance/beat,/actuator/prometheus
the config not work

### What you expected to happen

I want to ignore some endpoint, but the config can not work.

### How to reproduce

export SW_AGENT_INSTANCE=11.67.108.15
export SW_TRACE_IGNORE_PATH=/nacos/v1/ns/instance/beat,/actuator/prometheus

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Assigned to you.

**Comment by kezhenxu94** [comment]
> export SW_AGENT_INSTANCE=11.67.108.15
> export SW_TRACE_IGNORE_PATH=/nacos/v1/ns/instance/beat,/actuator/prometheus

@katelei6 are you sure this is Python agent? from the 2 paths they looks like Java stack, at least `/actuator/prometheus` looks like Spring Actuator endpoint:

**Comment by katelei6** [comment]
I see the ignore path is write to env, but it not work! @kezhenxu94

**Comment by katelei6** [comment]
I try it again, in ~/.bashrc to config, the env is right, in /etc/profile to config, the env can not use?@kezhenxu94

**Comment by wu-sheng** [comment]
I think your question is a little out of the project boundary. You could easily verify whether a system variable is accessible in a python program. We don't care and control where you set, it is OS's responsibility.

**Comment by leon5233** [comment]
> I think your question is a little out of the project boundary. You could easily verify whether a system variable is accessible in a python program. We don't care and control where you set, it is OS's responsibility.

The configuration on the official website does not take effect
1. Set through the system environment variable,you need to add skywalking.trace.ignore_path to the system variables, the value is the path that you need to ignore, multiple paths should be separated by ,
2. Copy/agent/optional-plugins/apm-trace-ignore-plugin/apm-trace-ignore-plugin.config to /agent/config/ dir, and add rules to filter traces
`trace.ignore_path=/your/path/1/**,/your/path/2/**
`
