### ISSUE TITLE
[Bug] Length of column events.parameters is too small to hold "Start Java Application" event with long JAVA_OPTS

### ISSUE THREAD

**Issue by mustangxu** [apache/skywalking#8608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

When start a Java application with skywalking javaagent, events are failed to insert into table 'events' because the length of column 'parameters' is 1024 only.
e.g. My application has a very-long "JAVA_OPTS" generated by the IDE, see the attachment

<img width="612" alt="screenshot" src="https://user-images.githubusercontent.com/194269/155977687-1a904781-75aa-4042-92fe-70736d6bd133.png">

### What you expected to happen

1. extend the length of 'events.parameters' or
2. just truncate the input for walk-through

### How to reproduce

Start a Java app. with long JAVA_OPTS

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I think we at least should support (2) and what is your expected length?

This should be easy to fix, do you want to submit a fix?

**Comment by mustangxu** [comment]
> I think we at least should support (2) and what is your expected length?
> 
> This should be easy to fix, do you want to submit a fix?

I am glad to submit a fix. Some details need to discuss like you mentioned:
1. Is it proper to truncate the information (or is it necessary to store the whole parameter string)? I find the parameters will be displayed like the screenshot
2. Whether a long-enough column type like 'TEXT' affects the performance, not only in database, other storage types like ES as well

<img width="593" alt="screenshot" src="https://user-images.githubusercontent.com/194269/156118233-4acc2b9f-cb47-407c-9d6e-b18c88ef531d.png">

**Comment by wu-sheng** [comment]
(1) We should try our best to show all, this would not be queried, right? Just log them for further visualization.
(2) Using TEXT with `storageOnly = true` should not impact the performance. If you just need to read them, but not use it as a query condition, which I think it is your case here.
