### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Bjxzc** [apache/skywalking#8631]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Kong Agent (apache/skywalking-kong)

### What happened

Env：
kong：
 
![image](https://user-images.githubusercontent.com/56501044/157157333-31a54a3b-7334-4da8-9a8d-fc73f8f13be0.png)

agent:
![image](https://user-images.githubusercontent.com/56501044/157157382-dfafa0b5-e7f4-4411-aed0-bf62daf785e1.png)

agent-config:
![image](https://user-images.githubusercontent.com/56501044/157157496-5b1f5deb-1980-4b79-971c-7dbe8e69398b.png)

erro:
2022/03/07 17:55:19 [error] 31410#0: *5150 [kong] init.lua:271 [skywalking] .../local/share/lua/5.1/kong/plugins/skywalking/handler.lua:46: attempt to index local 'metadata_buffer' (a nil value), client: 10.x.x.x, server: kong, request: "GET /admin/metrics HTTP/1.1", host: "10.x.x.x:80"
2022/03/07 17:55:19 [error] 31410#0: *5150 failed to run body_filter_by_lua*: /usr/local/share/lua/5.1/skywalking/span.lua:223: attempt to index local 'span' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/skywalking/span.lua:223: in function 'tag'
        .../local/share/lua/5.1/kong/plugins/skywalking/handler.lua:75: in function <.../local/share/lua/5.1/kong/plugins/skywalking/handler.lua:72>
        /usr/local/share/lua/5.1/kong/init.lua:265: in function 'execute_plugins_iterator'
        /usr/local/share/lua/5.1/kong/init.lua:1177: in function 'body_filter'
        body_filter_by_lua:2: in main chunk, client: 10.x.x.x, server: kong, request: "GET /admin/metrics HTTP/1.1", host: "10.x.x.x:80"

### What you expected to happen

Bulk error log ;kong won't work while skywalking-plugin is open

### How to reproduce

add plugin from kong admin API ;  kong restart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No title for the issue. Please make sure they are in good format.

Kong plugin is tested [here](https://github.com/apache/skywalking-kong/tree/master/test/e2e/e2e-test-kong) driven by GitHub Action, https://github.com/apache/skywalking-kong/blob/master/.github/workflows/e2e.yml 

Kong config, https://github.com/apache/skywalking-kong/blob/master/test/e2e/e2e-test-kong/docker/conf/kong.conf

**Comment by wu-sheng** [comment]
Also, I noticed, you have gRPC listed, we never tested it. You should cross-check the difference between your and e2e's config.
