### ISSUE TITLE
[Feature] supports the export of hourly and daily metrics

### ISSUE THREAD

**Issue by sunOnly** [apache/skywalking#8634]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

supports the export of hourly and daily metrics
org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker Change as follows

![image](https://user-images.githubusercontent.com/22111568/157161952-8ec0f78f-b395-4c36-b27d-b4c1eed89b9e.png)

org.apache.skywalking.oap.server.core.analysis.worker.MetricsStreamProcessor Change as follows
![image](https://user-images.githubusercontent.com/22111568/157161969-3a45e561-08d2-4486-9acb-35f455830a4b.png)

### Use case

Export metrics reanalysis

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Could you describe the scenario about when do you need this?

**Comment by wu-sheng** [comment]
I assigned to you as you checked `Yes I am willing to submit a PR!` and also propose this. You are the first one proposing this kind of exposing.

**Comment by sunOnly** [comment]
> Could you describe the scenario about when do you need this?
The complete metrics information of entities in the dashboard can only be viewed separately. To display the entity metrics information in a table, see the following figure
![image](https://user-images.githubusercontent.com/22111568/157163387-91904669-a732-454b-b959-71ef9fa6830c.png)

**Comment by wu-sheng** [comment]
GraphQL style query protocol is for this. We don't have to export everything for this case

**Comment by sunOnly** [comment]
> The complete metrics information of entities in the dashboard can only be viewed separately. To display the entity metrics information in a table, see the following figure

The implementation is OK, but the performance is not good,
Export converts the same entity information into one line, and improves the performance of one-time query results

**Comment by wu-sheng** [comment]
The design of exporting is to make metrics available in 3rd party, so, generally you could build everything else on your own.
What you are doing, I can't say wrong, but strange and special about how to use SkyWalking.

**Comment by wu-sheng** [comment]
I don't know what do you mean performance is not good. From my understanding, your whole page could be done by a single one-request GraphQL, which should have no performance at all.

**Comment by sunOnly** [comment]
> The design of exporting is to make metrics available in 3rd party, so, generally you could build everything else on your own. What you are doing, I can't say wrong, but strange and special about how to use SkyWalking.

Is it reasonable to support hour and day export function positioning?

**Comment by wu-sheng** [comment]
Could you check https://github.com/apache/skywalking/issues/8634#issuecomment-1061423697? I think we should have a clear answer after this discussion. After all, I just want all features to be on top of reasonable requirements.

**Comment by sunOnly** [comment]
> I don't know what do you mean performance is not good. From my understanding, your whole page could be done by a single one-request GraphQL, which should have no performance at all.
Use cases query all entity information of the same component at one time, and different indicator information needs multiple database interactions

**Comment by sunOnly** [comment]
> I don't know what do you mean performance is not good. From my understanding, your whole page could be done by a single one-request GraphQL, which should have no performance at all.
Use cases query all entity information of the same component at one time, and different indicator information needs multiple database interactions

**Comment by wu-sheng** [comment]
What do you mean components? I think that is impossible for any system. The only solution is you have kinds of big data platforms generating a report rather than getting data in real time. But in that case, minute level metrics should be better for data analysis.

**Comment by sunOnly** [comment]
> What do you mean components? I think that is impossible for any system. The only solution is you have kinds of big data platforms generating a report rather than getting data in real time. But in that case, minute level metrics should be better for data analysis.

Endpoint type, exporting hours and days. Don't do the second calculation

**Comment by sunOnly** [comment]
> > What do you mean components? I think that is impossible for any system. The only solution is you have kinds of big data platforms generating a report rather than getting data in real time. But in that case, minute level metrics should be better for data analysis.
What do you mean components?
Other user-defined types in HTTP or Dubbo services. Query all metric information in type
exporting hours and days. Don't do the second calculation

**Comment by wu-sheng** [comment]
> Use cases query all entity information of the same component at one time

You mentioned `component`, I don't know.

**Comment by sunOnly** [comment]
> Use cases query all entity information of the same component at one time
> You mentioned `component`, I don't know.

HTTP or Dubbo or user-defined type. All measurement information in the query type

**Comment by wu-sheng** [comment]
If you are using this kind of custom feature, it seems out of our SkyWalking's scope. You should know, we recommend you aggregate from minute on your own platform, which is more accurate. The exporting to support `INCREMENT` and `TOTAL`, in hour/day level, these would become very tricky.

**Comment by sunOnly** [comment]
> If you are using this kind of custom feature, it seems out of our SkyWalking's scope. You should know, we recommend you aggregate from minute on your own platform, which is more accurate. The exporting to support `INCREMENT` and `TOTAL`, in hour/day level, these would become very tricky.
get,I only subscribe to TOTAL

**Comment by wu-sheng** [comment]
That is why upstream can't accept everything, different team has different agenda and plans, but we need a consistent and widely suitable APIs.

**Comment by wu-sheng** [comment]
I am going to close this for now, as tagged this as `TBD`. If you have a better proposal, I am willing to discuss it, but right now, your proposal seems close to your private requirements only.
