### ISSUE TITLE
Overhaul UI dependencies' licenses

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#8638]
A reminder, we should overhaul https://github.com/apache/skywalking/tree/master/dist-material/release-docs/licenses/ui-licenses accordingly as the UI project is completely replaced and must have some dependencies' changes

_Originally posted by @kezhenxu94 in https://github.com/apache/skywalking/pull/8637#discussion_r821646311_

**Comment by kezhenxu94** [comment]
This needs to be done before 9.0.0 so I create this issue to track.

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking/pull/8783
