### ISSUE TITLE
[CLI] Support the process metadata query 

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#8650]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

After the Process GraphQL query protocol has been merged. 
We need to add the Process entity query in CLI. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Move to CLI milestone.
