### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yi121013215** [apache/skywalking#8667]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I modify the recordDataTTL to 2 from 3, metricsDataTTL to from 7, but the es6 data do not delete.
![捕获](https://user-images.githubusercontent.com/10719426/158087424-0410d0bd-2882-46ff-9b89-8dbcf6cadff4.PNG)
![捕获1](https://user-images.githubusercontent.com/10719426/158087489-6e16c70b-8c8c-4ef6-81f3-a77bf0166e8d.PNG)
![捕获2](https://user-images.githubusercontent.com/10719426/158087617-a71223f1-06ae-493b-bebd-f696043f9e47.PNG)

oap version：8.9.1
es version : 6.8.18

### What you expected to happen

I expect that the disk will not grow all the time and will eventually reach a peak.

### How to reproduce

Step1: build es , no additional settings.
Step2: modify recordDataTTL and metricsDataTTL, start oap and webapp.
Step3: bbserve disk growth.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No title, and this seems a discussion only
