### ISSUE TITLE
[Bug] Profile Error

### ISSUE THREAD

**Issue by yangvipguang** [apache/skywalking#8693]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

When I use  Profile , it occurs 
![image](https://user-images.githubusercontent.com/11416887/158730785-7f6e7ce7-c80b-4b43-8b71-7fb22c17354f.png)

### What you expected to happen

Should like as below
![image](https://user-images.githubusercontent.com/11416887/158732794-732324bf-371b-4a5c-a0f2-fe234134ede7.png)

### How to reproduce

platform: alicloud  ack  kubernetes
deployment: helm 
version: 8.9.1
javaagent: skywalking-java-agent:8.9.0-alpine

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This UI is being replaced, v9 is coming next. We know this error report when you click `analyze` before selecting a profiled segment.
