### ISSUE TITLE
[Feature] Support limitation and circuit break per GraphQL request

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8694]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

By leveraging the GraphQL query, users could initial a 1k+ sub GraphQL queries/mutations in one single HTTP request. Then this could crash the OAP server.

It is better we could provide a feature with a configuration to set up the number limitation. And response error if too many requests in one HTTP call.

We need to check whether we could do this in today's GraphQL framework.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Do we only limit by the number of sub-queries?

**Comment by wu-sheng** [comment]
What else do you suggest?
