### ISSUE TITLE
[Website] Documentation search engine not picking up latest docs

### ISSUE THREAD

**Issue by Superskyyy** [apache/skywalking#8712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Website (apache/skywalking-website)

### What happened

Sorry if this goes into the wrong category. I just found out that the recent docs (including OAP > 8.7.0-8.9.1 & Python agent entirely etc.) were not picked up by the Algolia search engine at all.  Now searching for keywords within those docs either returns nothing or results from other repos, which is quite confusing.

The config file was hosted in the Algolia [repo](https://github.com/algolia/docsearch-configs/blob/master/configs/skywalking.json), which happened to be deprecated and now requires configuration through a [web interface](https://crawler.algolia.com/) that I don't have access to.  

FYI @Jtrust, as you added the previous configs through GitHub.

### What you expected to happen

Versioned doc pages should yield corresponding search results when using the top right search box. 

### How to reproduce

1. Search within [Java agent: v8.9.0](https://skywalking.apache.org/docs/skywalking-java/v8.9.0/readme/) returns nothing.
2. Search within [Python agent: latest](https://skywalking.apache.org/docs/skywalking-python/latest/readme/) only returns results from OAP docs, while v0.7.0 gives nothing

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@Jtrust I think we missed some settings?

**Comment by wu-sheng** [comment]
@Superskyyy Look like `algolia` has a lot of changes seems last time we checked. I have created a new application on algolia for this, @Jtrust will take care it later today or tomorrow. If you like, I could invite you into this workspace too.

**Comment by Superskyyy** [comment]
> @Superskyyy Look like `algolia` has a lot of changes seems last time we checked. I have created a new application on algolia for this, @Jtrust will take care it later today or tomorrow. If you like, I could invite you into this workspace too.

Certainly! I want to help out make things up-to-date. Thank you.

**Comment by wu-sheng** [comment]
The invitation is sent, notice, this is a new application, so everything is blank for now.

**Comment by Superskyyy** [comment]
> The invitation is sent, notice, this is a new application, so everything is blank for now.

Looks good, I accepted.

**Comment by Superskyyy** [comment]
Do we still have access to the Algolia crawler? It seems we don't have permission to configure crawler for the application anymore. 
IDK if the crawler simply takes a URL and does its job like old times or now use the following action, but they both require access from the Algolia application <-> Algolia crawler that we may need request for.
https://github.com/algolia/algoliasearch-crawler-github-actions

**Comment by wu-sheng** [comment]
This is a good find. @Jtrust Could you check this?

**Comment by Jtrust** [comment]
> This is a good find. @Jtrust Could you check this?

@Superskyyy Thanks for your information. We are using DocSearch V2, now there is V3, maybe migrating to V3 can solve the problem. Let me try

**Comment by Superskyyy** [comment]
> DocSearch

Thank you, I have no idea how the whole thing works..
