### ISSUE TITLE
[Feature] [BanyanDB] Support function in row merging

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the MVP of BanyanDB, all rows would be overrides when the latest data was inserted with the same ID.
In advanced, it is better BanyanDB could provide a function based merging mechanism to merge previous and new data. Based on this, SkyWalking OAP `L1->L2` distributed aggregation would not be necessary, and also would not require **reading metrics from DB before flushing back**, **maintaining session**.

### Use case

This would highly advanced feature, which should not be considered in the first release. In longer-term, this would show much better performance as a native database.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Considering this was added as a part of OSPP 2024, we need to consider. @hanahmily  
1. Complete feature description
2. In-one-minute aggregation and downsampling workflow
3. Function (re)implementation solution
4. Testing methods for <3> and relative framework setup.

This feature should have larger scope than students can do in OSPP.

**Comment by StLeoX** [comment]
First, we need an API called `MeasureAggregateFunctionService.Support` that returns a list of currently supported aggregate functions.
Each element of this list is a `MeasureAggregateFunction`, which agrees on how the aggregation is calculated on a particular field type.
Finally, `AggregationFunction` needs to be added to the FieldSpec to record what aggregation function was used to compute on it.

**Comment by wu-sheng** [comment]
OAP alternative expectation and use case
---

Alternatively, we would like to do downsampling data for hour and day dimensionalities. These data would not need to worry about alarm features.

So, L1 and L2 will still exist with the alarm feature. But we will disable the downsampling mechanism in BanyanDB storage and hand over it to BanyanDB.

Note, BanyanDB operation, OAP will be required to build this server side row-level aggregation when it is ready, ref https://github.com/apache/skywalking/issues/8720

source from, https://github.com/apache/skywalking/issues/12653

**Comment by hanahmily** [comment]
After a lengthy discussion, we've determined that separating the merging work from OAP is inefficient. The merging process needs to analyze the original data stream. Attempts to assign this task to different platforms have proven ineffective. Therefore, I have decided to close this issue for now.
