### ISSUE TITLE
[Feature] [BanyanDB] Support customer insert/update trigger

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8721]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

After we have https://github.com/apache/skywalking/issues/8720, we could build a more aggressive mechanism. All downsampling metrics(hour/day) could be calculated inside BanyanDB, because with rows mergeable with custom `function`, the downsampling just requires the same aggregation function mechanism with `timestamp` downsampling(minute->hour, minute->day) and a new logic table name.

One NOTICE before begin this, we should know, database kernel level trigger+function aggregation would make more flush write to hour/day metrics(but this is limited).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
Closed by #8720
