### ISSUE TITLE
[Bug] throws ModuleStartException is redundant

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/skywalking#8737]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

In `org.apache.skywalking.oap.server.analyzer.provider.meter.process.MeterProcessorTest#testProcess` 
I think throws ModuleStartException is redundant ,Because I do not find method to throw this exception

### What you expected to happen

do not throw ModuleStartException

### How to reproduce

title

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
CI covers this UT in every PR, we never saw it fails.

Are you finding a way to fix it? You clicked `I am willing to submit a PR!`
