### ISSUE TITLE
[Bug] [Nodejs] install plugin error if mongodb driver is 4.1.3

### ISSUE THREAD

**Issue by youth7** [apache/skywalking#8742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Server Side Agent (apache/skywalking-nodejs)

### What happened

In file `lib/plgins/MongoDBPlugin.js` there is a line contain this code :
> `this.Cursor = installer.require('mongodb/lib/cursor');`

this will cause en error : `Uncaught Error Error: Cannot find module 'mongodb/lib/cursor'` if version of mongodb driver is `^4.1.3`. But it is fine if mongodb driver is 3.

![图片](https://user-images.githubusercontent.com/8315732/160083630-ce7172fe-72d3-4a41-befa-d20e58d165b2.png)

### What you expected to happen

should support high version Mongodb driver  

### How to reproduce

use `skywalking-backend-js` and version of mongodb is `^4.1.3`. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
> this will cause en error : Uncaught Error Error: Cannot find module 'mongodb/lib/cursor' if version of mongodb driver is ^4.1.3. But it is fine if mongodb driver is 3.

This means we don't support mongodb 4.x, please consider contributing if you need.

**Comment by vanceeasleaf** [comment]
yarn add skywalking-backend-js-zy
