### ISSUE TITLE
[Feature] Automatically weave into the thread pool without modifying the business code

### ISSUE THREAD

**Issue by Cool-Coding** [apache/skywalking#8743]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, we must wrap the <code>Runnable</code> or <code>Callable</code> object with <code>RunnableWrapper</code> or <code>CallableWrapper</code>. when we want to pass a traceId across the thread.

<Code>java.util.concurrent.ThreadPoolExecutor</code> is generally used in bussiness projects. Business developers won't want to change their codes when the project is weaved by apm agent.  so i think it is necessary to develop a agent plugin to weave into <Code>java.util.concurrent.ThreadPoolExecutor</code> automatically. And i have achived it in my project, it works. I want to hear your opinion. Thanks!

### Use case

We provide another choice for developers and it is helpful to promote APM in a company.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you want, feel free to submit a pull request to enhance with tests. :) I think we have no objection to stopping this kind of new plugin.

**Comment by Cool-Coding** [comment]
> If you want, feel free to submit a pull request to enhance with tests. :) I think we have no objection to stopping this kind of new plugin.

Ok, i will add this plugin and tests. Thanks for your reply!

**Comment by Cool-Coding** [comment]
@wu-sheng Please assign this to me. Thank you!

**Comment by wu-sheng** [comment]
Done, you don't have to be assigned. Once you submit the PR, we could work on that. Assigning is for asking this person to track progress.

**Comment by Cool-Coding** [comment]
> Done, you don't have to be assigned. Once you submit the PR, we could work on that. Assigning is for asking this person to track progress.

I see. Thank you! I thought that if i am not assigned, other  person can also submit the PR .

**Comment by wu-sheng** [comment]
I see, don't worry, if so, I will ping you first to check the status.
