### ISSUE TITLE
[Bug] when catch InterruptedException we can not just print error log

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/skywalking#8750]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

In `org.apache.skywalking.apm.agent.core.commands.CommandService#run` when catch `InterruptedException` we just print error log and request interrupted flag is setting `false`,so higher layer code can not know the interruped status

### What you expected to happen

Restore the interrupted status

### How to reproduce

when catch InterruptedException

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Conclusion, this is not a bug, just **Remove unnecessary InterruptedException catch**
