### ISSUE TITLE
[Feature] java agent add cpu load limit config and releated cds

### ISSUE THREAD

**Issue by zhyyu** [apache/skywalking#8773]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

when the cpu load is too high, the agent can not sample according to the cpu load limit config (maybe like agent.sample_avg_cpu_load_limit). Also, this config can be changed through cds.

### Use case

as description.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please submit pull requests separately. We need to review this mechanism carefully.

**Comment by wu-sheng** [comment]
No update in a long time. Closing.
