### ISSUE TITLE
[Doc] Add agent-Satellite compatibility version matrix

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#8791]
https://github.com/apache/skywalking/blob/f8feaa97b7aba577551e2db092a3c29306127eed/docs/en/setup/service-agent/agent-compatibility.md?plain=1#L7-L13

I think we need another matrix like this to indicate what versions of the language agents can connect to what versions of Satellite

| Satellite |Java|Python|NodeJS|LUA|Kong|Browser Agent|Rust| 
 ----------- | ---------- | --------- | --------- |--------- |--------- |--------- |--------- |
 8.0.1 - 8.1.0 | 8.0.0 - 8.3.0 | < = 0.6.0| < = 0.3.0 | All | All | No | All | 
 8.2.0 - 8.3.0 | 8.0.0 - 8.3.0 | < = 0.6.0| < = 0.3.0 | All | All | All | All |
 8.4.0 - 8.8.1 | \> = 8.0.0 | All | All | All | All | All | All | 
 8.9.0+ | \> = 8.0.0 | All | All | All | All | All | All |
 9.0.0+ | \> = 8.0.0 | All | All | All | All | All | All |

**Comment by wu-sheng** [comment]
@mrproliu I think we at least require a minimal version. We faced NodeJS agent incompatibility in testing today.

**Comment by mrproliu** [comment]
Two things to note:
1. Update document, add a new matric to document which native agent support transport protocol to the satellite. 
2. Update the Satellite, let it could support transport compat protocol from the agent.

**Comment by wu-sheng** [comment]
@kezhenxu94 Older releases should be supported by Satellite(latest) through https://github.com/apache/skywalking-satellite/pull/104 , could you give a try?
