### ISSUE TITLE
[Bug]  use kafka plugin, the consumer can not recive message

### ISSUE THREAD

**Issue by katelei6** [apache/skywalking#8794]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

when i use skywalking the plugin of kafka, the consumer can not recive messae, I debug the code, find 
 #for item in carrier:
                #headers.append((item.key, bytes(item.val, encoding='utf-8')))

if  i not use this ,it can run well.

### What you expected to happen

I think the plugin can not let the consumer happen issue.

### How to reproduce

1 use skywalking of kafka  
2 the consumer can not work well
3 when i not use the code of kafka plugin
![image](https://user-images.githubusercontent.com/79354895/161380677-f43bddef-a7d1-4b5e-8294-56aec7f3b9c1.png)
4 the consumer is ok

I think the encode of header has issue.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Maybe you are not using UTF-8? Header injection is important, and UTF-8 is the default charset in the whole SkyWalking ecosystem.

**Comment by wu-sheng** [comment]
No update.
