### ISSUE TITLE
[Feature] Add skywaliking plugin for support   Apache ShenYu (incubating) gateway，support version 2.4.x and after version

### ISSUE THREAD

**Issue by hutaishi** [apache/skywalking#8796]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[Apache ShenYu](https://shenyu.apache.org/) (incubating) is a gateway, 
I want to add a plugin to implement tracing for the gateway.

### Use case

Achieving observability of the gateway.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hutaishi** [comment]
Please assign this plugin development to me, thanks！

**Comment by wu-sheng** [comment]
Assigned. Good luck.

**Comment by wu-sheng** [comment]
@hutaishi I want to Shenyu community could provide a clear position about what would be the relationship between this plugin and your own agent. As I have mentioned in [mail list](https://lists.apache.org/thread/n2bgo3znm90ff7kqsw7c5zott0p330yk). The shenyu's agent is very similar to (maybe from) SkyWalking's agent. I am very concerned about the conflict.

**Comment by hutaishi** [comment]
Hi，shenyu community has completely removed the agent module, so there is no conflict.

**Comment by wu-sheng** [comment]
Got it.
