### ISSUE TITLE
[Core] Cold writing 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#8815]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Support writing cold data whose timestamp is out of the current writing window. 

The block controller tends to create cold blocks to collect these data instead of opening the closed blocks online. The scanner and fetcher of the series should look at cold blocks for handling querying tasks. We also need a periodical job to merge cold and regular blocks. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by azhsmesos** [comment]
please assigned it to me

**Comment by wu-sheng** [comment]
> please assigned it to me

Thank you for being intered, but this is a core feature, Gao hss owned this.
It is better yoi could talk to him, and begin with some more friendly work.

**Comment by hanahmily** [comment]
We have supported this feature.
