### ISSUE TITLE
[Feature] [BanyanDB] Return rich error with canonical status codes

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#8830]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We use `gRPC` protocol for skywalking-banyandb, but currently we simply return standard `errors.Error` from go stdlib when error occurs.

https://github.com/grpc/grpc-go/issues/1581#issuecomment-337059527

Quoted: 

> It's not explicitly documented now.
In the doc for status package, there's this line that conveys the same message:

```
gRPC service handlers should return an error created by this package, and 
gRPC clients should expect a corresponding error to be returned from the RPC call
```

Etcd is doing exactly what we want,

- https://github.com/etcd-io/etcd/issues/8691
- https://github.com/etcd-io/etcd/blob/main/client/v3/retry.go
- https://github.com/etcd-io/etcd/blob/main/api/v3rpc/rpctypes/error.go

Some other references:

- https://jbrandhorst.com/post/grpc-errors/
- https://www.baeldung.com/grpcs-error-handling

### Use case

...

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
I tend to introduce some codes to handle errors gracefully

- `InvalidArgument`. This means the client input fails validation.
- `NotFound`. This denotes a resource that is not found.
- `AlreadyExists`: This indicates the resource already exists for creating one.
