### ISSUE TITLE
[Bug] Uncaught (in promise) TypeError: Cannot read property 'getAllTemplates' of undefined

### ISSUE THREAD

**Issue by sruby** [apache/skywalking#8831]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened
version: 8.9.1
The interface does not display any information.
![image](https://user-images.githubusercontent.com/15009808/162163424-0e6889bb-cfb9-4e04-a706-12aba93f7a90.png)

I think it's a front-end problem.

Browser console error message：
`app.f4e7af01.js:1 Uncaught (in promise) TypeError: Cannot read property 'getAllTemplates' of undefined`
![image](https://user-images.githubusercontent.com/15009808/162163918-f90f36de-6ea4-4e20-a4a4-3140528f99ac.png)

Browser response:
We're sorry but SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue.
![image](https://user-images.githubusercontent.com/15009808/162163844-fb842e19-f943-4d03-b0f9-2fc14c3ad399.png)

agent data is sent to oap normally：
skywalking-api.log:
`DataCarrier.DEFAULT.Consumer.0.Thread TraceSegmentServiceClient : 1 trace segments have been sent to collector.`

But there is no problem with the non-container installation method.

### What you expected to happen

The interface can be displayed normally.

### How to reproduce

Install skywalking by docker-compose, please refer to the attached yml file.
[docker-compose.devops.latest.yml.zip](https://github.com/apache/skywalking/files/8441414/docker-compose.devops.latest.yml.zip)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
RocketBot UI works as expected for 8.x release. Your errors just mean, OAP is not booting successfully.

**Comment by insanebeast** [comment]
I have the same problem, have you worked it out yet?

**Comment by qyddle** [comment]
I use docker to deploy version 9.0 and the same problem occurs.
![image](https://user-images.githubusercontent.com/6300036/170230848-72c30f38-26ca-4010-a73a-d3d7cc5a436b.png)
![image](https://user-images.githubusercontent.com/6300036/170230914-da869abd-7926-4914-8548-79c5bca269df.png)

**Comment by wu-sheng** [comment]
@qyddle Your backend is not working.

**Comment by qyddle** [comment]
> @qyddle Your backend is not working.

oal starts without error message

**Comment by qyddle** [comment]
> @qyddle Your backend is not working.

The backend is started through docker according to the official website documentation

**Comment by qyddle** [comment]
> @qyddle Your backend is not working.

I tested it with both versions 8.9.0 and 8.9.1. There is no error message in the es, oap and ui startup background, but the information printed on the F12 console of the above screenshot browser is the same when accessing.

**Comment by wu-sheng** [comment]
If our official demo works for you, then your backend is not working as expected. We can't and shouldn't debug your env.
Notice, your primary env is on your own.

**Comment by insanebeast** [comment]
> I use docker to deploy version 9.0 and the same problem occurs. ![image](https://user-images.githubusercontent.com/6300036/170230848-72c30f38-26ca-4010-a73a-d3d7cc5a436b.png) ![image](https://user-images.githubusercontent.com/6300036/170230914-da869abd-7926-4914-8548-79c5bca269df.png)

I also get this error with deploying version 9.0 in docker, finnally I deploy with startup.sh and then it works...

**Comment by qyddle** [comment]
> If our official demo works for you, then your backend is not working as expected. We can't and shouldn't debug your env. Notice, your primary env is on your own.
You said that the UI error is because the OAP backend service is not working properly. I did not find any error information in the startup log. Could you please help me to check if there are any problems in the logs of the next three services?

[skywalking-docker.txt](https://github.com/apache/skywalking/files/8777121/skywalking-docker.txt)
[es-docker.txt](https://github.com/apache/skywalking/files/8777133/es-docker.txt)
[oap-ui.txt](https://github.com/apache/skywalking/files/8777173/oap-ui.txt)

**Comment by qyddle** [comment]
> > 我使用 docker 部署 9.0 版本，出现同样的问题。![图片](https://user-images.githubusercontent.com/6300036/170230848-72c30f38-26ca-4010-a73a-d3d7cc5a436b.png) ![图片](https://user-images.githubusercontent.com/6300036/170230914-da869abd-7926-4914-8548-79c5bca269df.png)
> 
> 在 docker 中部署 9.0 版时，我也遇到了这个错误，最后我使用 startup.sh 进行部署，然后它就可以工作了......

You didn't start the 9.0 version with docker at the end? But it is no problem to start through startup.sh

**Comment by insanebeast** [comment]
yep, I search a lot and find no solution with this F12 console error, oap,ui,es all of them have no error log, maybe there is a bug in frontend code. when I deploy it directly on the server with startup.sh and it works fine

**Comment by qyddle** [comment]
> 
Well, so do I.

**Comment by freshgeek** [comment]
Well, so do I.

use offiece docker-image , start processing is no error message

**Comment by wu-sheng** [comment]
demo.skywalking.apache.org is using the same images.
If you can't, you have to check your private env. We don't find any issue.

**Comment by cylrk** [comment]
Is this problem solved?

**Comment by Superskyyy** [comment]
> Is this problem solved?

RocketbotUI is now obsolete and replaced by BoosterUI [here](https://github.com/apache/skywalking-booster-ui), you will need to upgrade your skywalking deployment to version 9.x. @cylrk
