### ISSUE TITLE
[Bug] 8.7.x、8.8.x、8.9.x UI docker image error

### ISSUE THREAD

**Issue by qq31758581** [apache/skywalking#8832]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

通过Docker部署UI镜像后，界面出现空白

### What you expected to happen

可能是镜像没有更新

### How to reproduce

#7401 https://github.com/apache/skywalking/issues/7401
与这个BUG相同，目前拉取8.7以上版本的ui镜像安装都会报500错误
使用8.6以下版本部署正常，请问是否镜像打包有问题？

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Require English on GitHub. And docker images are used by many people in products, so they are good. Check the docs, the deployment steps and settings changed from version to version.

**Comment by qq31758581** [comment]
果然中国人做的东西都是一泡屎
