### ISSUE TITLE
[Feature] Update eBPF Profiling task as service level

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#8833]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, the eBPF Profiling could operate with a single process. But to make it easier to use, so change it to bind with the service level. Using the `label` to aggregate similar processes.

### Use case

eBPF Profiling works with the service level. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Is this an OAP side task tracker?

**Comment by mrproliu** [comment]
Including OAP, Rover, and CLI side.
