### ISSUE TITLE
[Feature] [UI] Consider to add an avg number for metrics of service/instance/endpoint list?

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8834]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="1686" alt="image" src="https://user-images.githubusercontent.com/5441976/162403913-03ffa501-2b11-46c9-88c7-b9e1a8d9525b.png">

In v9, we have a linear graph on the service/instance/endpoint list, could we have a summary(avg calculation by UI) value on the table, and use a pop-out graph to show the trend? 
By that, I am thinking to add all red metrics, (1) load (2) success rate (3) apdex on one table, and also would not make too many graphs on one page.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Fine0830** [comment]
Make scene to me...
