### ISSUE TITLE
[Bug] Java client failed to handle duplicate data points

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#8845]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

BanyanDB identifies unique data points by their metadata(name and group), entity id, and timestamp. For points with the same of them, the database server uses the new value to override the old one. 

Since the java client accepts the milliseconds as the timestamp's unit from the [document](https://github.com/apache/skywalking-banyandb-java-client#stream-1), we should handle the same points on this part. 

The possible solution is the influxdb module: https://github.com/apache/skywalking/blob/master/oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/base/RecordDAO.java#L53

### What you expected to happen

None

### How to reproduce

None

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> BanyanDB identifies unique data points by their metadata(name and group), entity id, and timestamp. For points with the same of them, the database server uses the new value to override the old one.

This is what we expect, and trace segment ID would be duplicated. What is the issue about exactly?

**Comment by wu-sheng** [comment]
> The possible solution is the influxdb module: https://github.com/apache/skywalking/blob/master/oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/base/RecordDAO.java#L53

This is really not a good example to refer. I am talking with @dmsolr to get this out.

**Comment by wu-sheng** [comment]
I have confirmed this is a bug in InfluxDB storage implementation. I have asked @dmsolr to adjust codes to fix this.
So, what is the case of BanyanDB actually?

**Comment by hanahmily** [comment]
As I mentioned, the data point id is a combination of metadata, entity_id, and timestamp. If an instance sends several segments in one millisecond, the last one that reaches banyandb will win, and each previous data point is dropped. 

>  I have asked @dmsolr to adjust codes to fix this.

I would like to know how to fix this. banyandb could get benefits from the same solution. @dmsolr Would you please elaborate it a bit in this thread?

**Comment by hanahmily** [comment]
I have discussed this with @wu-sheng, and will be working on it.

**Comment by wu-sheng** [comment]
@lujiajing1126 I will add a new annotation and attributed in storage model to define the global indices, such as trace id in trace and log, `segment id + span id`(you may miss before) in log.

**Comment by lujiajing1126** [comment]
> @lujiajing1126 I will add a new annotation and attributed in storage model to define the global indices, such as trace id in trace and log, `segment id + span id`(you may miss before) in log.

Also, could you please add index type annotation to indicate which type of index should be used. For numeric type, we have two kinds of indexes,

1. TREE, (for range search)
2. INVERTED

**Comment by wu-sheng** [comment]
I can, are these type available for global index or just general index(tag)?

**Comment by lujiajing1126** [comment]
> I can, are these types available for global index or just general index(tag)?

I suppose it's OK to support simply general indexes, since currently we only have one global index, i.e. `TraceID` (String + inverted index).

**Comment by wu-sheng** [comment]
One type, yes. But not just trace id, read https://github.com/apache/skywalking/issues/8845#issuecomment-1094453157

We need to add a virtual column for segment + span id, named as global_span_id. You will need them in trace and log correlation search
