### ISSUE TITLE
[Bug] Java agent MySQL plugin NPE

### ISSUE THREAD

**Issue by xu1009** [apache/skywalking#8860]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

mysql-5.x-plugin npe when connction url not with database, such as jdbc:mysql://ip:port

### What you expected to happen

mysql-5.x-plugin can work when connction url with database or not with

### How to reproduce

mysql-5.x-plugin work when connction url not with database 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@xu1009 You missed the title

**Comment by wu-sheng** [comment]
If you are going to submit the patch in one day, I should be able to wait for this fix. 

I am just going to release 8.10.0 right now :)

**Comment by xu1009** [comment]
it is simple, i will submit it today
