### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by czxin788** [apache/skywalking#8861]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Client Side Agent (apache/skywalking-client-js)

### What happened

![~MTWGWZJAB3BRKTKM`8%A{W](https://user-images.githubusercontent.com/13861904/163095540-9a858a0e-70c2-4c9f-ba2a-271501eeab59.png)

![MEZ@GTLK0 `YI_(%HQF5ZR6](https://user-images.githubusercontent.com/13861904/163095648-d29a2464-b0ce-4809-8781-8e7db95311b6.png)

![pol9WvxzfF](https://user-images.githubusercontent.com/13861904/163095705-89a03d45-1ea6-4670-bf49-5c3213133dc4.png)

### What you expected to happen

expected  the trace has data

### How to reproduce

vue 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No title, please fix.

**Comment by wu-sheng** [comment]
All thing should be in English.
