### ISSUE TITLE
[Bug] In SpringBoot, When undertow is used to replace tomcat, the Endpoint is duplicated。

### ISSUE THREAD

**Issue by teamoTNT** [apache/skywalking#8868]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

In SpringBoot, When undertow is used to replace tomcat, the Endpoint is duplicated。
![image](https://user-images.githubusercontent.com/103160892/163136432-0a89703e-108f-46ee-a431-0022cef87148.png)
The endpoint "UndertowDispatch"  is weird， I don't think is one request.
Meantime, I user the trace-ignore-plugin.jar, and the configuration is (SW_TRACE_IGNORE_PATH=/swagger-resources/**,UndertowDispatch,/health/check), It's couldn't ignore the endpoint 'UndertowDispatch';
My version is 8.6.0.

### What you expected to happen

 the endpoint "UndertowDispatch"  should pass.

### How to reproduce

user undertow。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You could remove undertow plugin if you don't need it.

**Comment by teamoTNT** [comment]
When i remove undertow plugin, the trace_id of the log will be displayed as N/A。 We are using logtube framework。
![1650338981(1)](https://user-images.githubusercontent.com/103160892/163914488-e86ec01d-a7c9-4c1e-9df5-c132cc165976.png)

**Comment by wu-sheng** [comment]
We don't have logtube integration, so, don't know what is going on

**Comment by teamoTNT** [comment]
How can we get tradeId when we remove undertow plugin.
Currently we use this method (org.apache.skywalking.apm.toolkit.trace.TraceContext.traceId()) to get tradeId to integrate logtube.

**Comment by wu-sheng** [comment]
If you want to discuss a question, open a new discussion(not issue).
Your ask has nothing related to this issue.

**Comment by teamoTNT** [comment]
OK, thk
