### ISSUE TITLE
[Feature] [ShenYu]Apache ShenYu (incubating) plugin support dubbo proxy

### ISSUE THREAD

**Issue by hutaishi** [apache/skywalking#8869]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Apache ShenYu (incubating) gateway plugin  currently does not support dubbo's proxy trace.
I want to support the tracing of dubbo's proxy，Because friends of the community need such features.
The request path is as follows：
client http request -> entry service(eg:nginx) -> ShenYu (incubating) gateway ->  dubbo service provider

### Use case

support the tracing of dubbo's proxy

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-java/pull/162
