### ISSUE TITLE
[Bug] Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 514

### ISSUE THREAD

**Issue by chenhaipeng** [apache/skywalking#8878]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Elasticsearch bulk process ,some time occurr this error："reason":"Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 518, I guess the endpointname is too long and the generated id exceeds the limit.

### What you expected to happen

Metrics buid id0, it relies on enpointname base64 conversion.
```
public abstract class Metrics extends StreamData implements StorageData, HavingDefaultValue {


    @Override
    public String id() {
        if (id == null) {
            id = id0();
        }
        return id;
    }

    protected abstract String id0();
}
```

### How to reproduce

when is enpointname is too long

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We have set the threshold to limit endpoint length. Are you using the latest version?

**Comment by chenhaipeng** [comment]
> We have set the threshold to limit endpoint length. Are you using the latest version?

this version is v8.9.1

**Comment by wu-sheng** [comment]
I am not aware of any place having this issue. If you do, please submit a pull request.

**Comment by faustine8** [comment]
We are using v9.0.0. We found that NOT the "endpointname" is to lang, is the "id" (of endpoints) is too long actually. The "endpointNameMaxLength" config not work. There are the errors: 

```text
 {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: id [2022051615_em1uLWJhc2UtcGxhdC1qb2I6Onptbi1iYXNlLXBsYXQtam9iLXRhc2s=.1-Y29tLnptbi5iYXNlLmNoYW5uZWwuZHViYm8uaW50ZXJmYWNlcy5jaGFubmVsLmNvbW1pc3Npb24ucGFyYW0uQ2hhbm5lbENvbW1pc3Npb25QYXJhbU1vZGlmeVJlbW90ZVNlcnZpY2UubW9kaWZ5Q29tbWlzc2lvbkJ5S2V5KENoYW5uZWxDb21taXNzaW9uUGFyYW1E-em1uLWJhc2UtY2hhbm5lbDo6em1uLWJhc2UtY2hhbm5lbC1kdWJibw==.1-Y29tLnptbi5iYXNlLmNoYW5uZWwuZHViYm8uaW50ZXJmYWNlcy5jaGFubmVsLmNvbW1pc3Npb24ucGFyYW0uQ2hhbm5lbENvbW1pc3Npb25QYXJhbU1vZGlmeVJlbW90ZVNlcnZpY2UubW9kaWZ5Q29tbWlzc2lvbkJ5S2V5KENoYW5uZWxDb21taXNzaW9uUGFyYW1E] is too long, must be no longer than 512 bytes but was: 530; ... "},"status":400}
```

and 

```text
 {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: id [endpoint_relation_cpm_2022051615_em1uLWJhc2UtcGxhdC1qb2I6Onptbi1iYXNlLXBsYXQtam9iLXRhc2s=.1-Y29tLnptbi5iYXNlLmNoYW5uZWwuZHViYm8uaW50ZXJmYWNlcy5jaGFubmVsLmNvbW1pc3Npb24ucGFyYW0uQ2hhbm5lbENvbW1pc3Npb25QYXJhbU1vZGlmeVJlbW90ZVNlcnZpY2UubW9kaWZ5Q29tbWlzc2lvbkJ5S2V5KENoYW5uZWxDb21taXNzaW9uUGFyYW1E-em1uLWJhc2UtY2hhbm5lbDo6em1uLWJhc2UtY2hhbm5lbC1kdWJibw==.1-Y29tLnptbi5iYXNlLmNoYW5uZWwuZHViYm8uaW50ZXJmYWNlcy5jaGFubmVsLmNvbW1pc3Npb24ucGFyYW0uQ2hhbm5lbENvbW1pc3Npb25QYXJhbU1vZGlmeVJlbW90ZVNlcnZpY2UubW9kaWZ5Q29tbWlzc2lvbkJ5S2V5KENoYW5uZWxDb21taXNzaW9uUGFyYW1E] is too long, must be no longer than 512 bytes but was: 552; ... "},"status":400}
```

**Comment by leohuai** [comment]
Same problem in version 8.9.1,how to fix it?
error log:

2024-01-12 18:48:17,036 org.apache.skywalking.library.elasticsearch.bulk.BulkProcessor 153 [armeria-eventloop-epoll-4-3] ERROR [] - [8.9.1-91ab0a3 (20211210154203)] Failed to execute requests in bulk 
java.util.concurrent.CompletionException: java.lang.RuntimeException: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: id [endpoint_relation_cpm_202401121847_c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LnJvdXRpbmcua2V5L1Byb2R1Y2Vy-c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLnJvdXRpbmcua2V5L0NvbnN1bWVy] is too long, must be no longer than 512 bytes but was: 514;2: id [endpoint_relation_sla_202401121847_c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LnJvdXRpbmcua2V5L1Byb2R1Y2Vy-c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLnJvdXRpbmcua2V5L0NvbnN1bWVy] is too long, must be no longer than 512 bytes but was: 514;3: id [endpoint_relation_percentile_202401121847_c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LnJvdXRpbmcua2V5L1Byb2R1Y2Vy-c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLnJvdXRpbmcua2V5L0NvbnN1bWVy] is too long, must be no longer than 512 bytes but was: 521;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: id [endpoint_r 
elation_cpm_202401121847_c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LnJvdXRpbmcua2V5L1Byb2R1Y2Vy-c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLnJvdXRpbmcua2V5L0NvbnN1bWVy] is too long, must be no longer than 512 bytes but was: 514;2: id [endpoint_relation_sla_202401121847_c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LnJvdXRpbmcua2V5L1Byb2R1Y2Vy-c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLnJvdXRpbmcua2V5L0NvbnN1bWVy] is too long, must be no longer than 512 bytes but was: 514;3: id [endpoint_relation_percentile_202401121847_c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmRlbGF5LnJvdXRpbmcua2V5L1Byb2R1Y2Vy-c2hhcmUuZWNzZWxlY3Rpb246OnBoLXNlbGVjdGlvbi11cGRhdGUtc2VydmljZQ==.1-UmFiYml0TVEvVG9waWMvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLmV4Y2hhbmdlUXVldWUvcGhocy5zZWxlY3Rpb24uZGVsaXZlcnkudXBkYXRlLnN0b3JlLnJvdXRpbmcua2V5L0NvbnN1bWVy] is too long, must be no longer than 512 bytes but was: 521;"},"status":400}

**Comment by chenhaipeng** [comment]
see here:
https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/resources/application.yml
serviceNameMaxLength: ${SW_SERVICE_NAME_MAX_LENGTH:70}
instanceNameMaxLength: ${SW_INSTANCE_NAME_MAX_LENGTH:70}
# The max length of service + endpoint names should be less than 240
endpointNameMaxLength: ${SW_ENDPOINT_NAME_MAX_LENGTH:150}

**Comment by leohuai** [comment]
> ```
> see here:
> https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/resources/application.yml
> serviceNameMaxLength: ${SW_SERVICE_NAME_MAX_LENGTH:70}
> instanceNameMaxLength: ${SW_INSTANCE_NAME_MAX_LENGTH:70}
> # The max length of service + endpoint names should be less than 240
> endpointNameMaxLength: ${SW_ENDPOINT_NAME_MAX_LENGTH:150}
> ```
thanks
