### ISSUE TITLE
[Feature] Webapp enables text compression, cache control

### ISSUE THREAD

**Issue by Fine0830** [apache/skywalking#8882]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Since text-based resources should be served with compression to minimize total network bytes, webapp should be enabled text compression. 

Since the browser does not need to make a request to receive the same file every time, accessing these resource copies will be very fast, I think webapp should be enabled cache control.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wankai123** [comment]
The default cache strategy is using `Last-Modified` now, so I suggest keep that way.
