### ISSUE TITLE
[Bug] [CI] [Backend and Java agent] Dead link check fails

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#8894]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

SkyWalking Twitter is https://twitter.com/ASFSkyWalking

The readme doc links to there, but CI reports 404, but actually, it exists.

I tried to upgrade to the newer dead-link check tool, but it seems don't support page hook(`/uri#hook`).

### What you expected to happen

Make dead link check back to work

### How to reproduce

Every CI reports this.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
FYI, I noticed this tool is GitHub action available now. 

https://github.com/marketplace/actions/markdown-link-check

**Comment by Superskyyy** [comment]
This problem happens to all repos with the ASFSkyWalking Twitter link, I tried to resolve it yesterday but the npm package couldn't work anyhow. Instead using the GHA version of the package magically works... `gaurav-nelson/github-action-markdown-link-check@v1`

Here's a link to a successful run https://github.com/Superskyyy/skywalking-python/runs/6042396915?check_suite_focus=true

I'm not sure if the action is Apache approved, other than that it should work.

**Comment by wu-sheng** [comment]
I think once you submit a pull request, you will know.

**Comment by wu-sheng** [comment]
> I tried to resolve it yesterday but the npm package couldn't work anyhow.

I tried locally too, the tool is working, but it reported `page internal hook` as 404. Maybe some parameter should be set?

**Comment by wu-sheng** [comment]
@kezhenxu94 I didn't close this as Java repo still has issues.

**Comment by kezhenxu94** [comment]
OK, I just saw all CI tasks in Java repo main branch passed but didn't notice the link checker task was not running in main branch, let me fix now
