### ISSUE TITLE
[Bug] ES flush thread will stop work when flush schedule task have exception

### ISSUE THREAD

**Issue by yangyiweigege** [apache/skywalking#8895]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

when i use skywalking in test enviorment,  i find the trace data write to ES have most delay.sometimes data write to ES will cost 30 minute later.

### What you expected to happen

the trace write to ES  within 20 seconds。

### How to reproduce

ES connectTimeout  set 3000 seconds.

### Anything else

the flush task have exception cause the schedule thread all waiting ,didn't work :
<img width="1036" alt="6592F812-C690-479B-85EA-E36EE03EA8CA" src="https://user-images.githubusercontent.com/23202824/163744919-73362212-180a-4347-9e0b-da9fc5a13842.png">

so  i add a try catch code in native,the exception is :
![39920013-C59B-402B-A14E-D37AE76435D2](https://user-images.githubusercontent.com/23202824/163745218-df761845-cf7a-40f6-98a1-762135b11934.png)

how to deal:
1.add try cache code in org.apache.skywalking.library.elasticsearch.bulk.BulkProcessor#flush
2.set more time for ES connection time, response time to  avoid exception.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Assigned to you. Wait for your PR to discuss details on that.

**Comment by wu-sheng** [comment]
Try to use `RunnableWithExceptionProtection` to avoid try/catch.

**Comment by wu-sheng** [comment]
@yangyiweigege Do you have any update what what you are going to do?

**Comment by yangyiweigege** [comment]
> @yangyiweigege Do you have any update about what you are going to do?

i will replace the  runable code in flush scheduler by use RunnableWithExceptionProtection ,eg:
               new RunnableWithExceptionProtection(this::flush,
                       t -> log.error("flush data to ES failure.", t) 
and i will submit pr  later.

**Comment by kezhenxu94** [comment]
This doesn’t make sense to me. You don’t have available/reachable ES server but you still set a very large connection timeout (3000 seconds == 50 minutes!!!). The default flush interval is less than 1 minute so you will get many flush tasks that are waiting for the connection to be established. This is nothing related to exception in the task, I believe all possible exceptions are catches in the flush method.

**Comment by yangyiweigege** [comment]
> This doesn’t make sense to me. You don’t have available/reachable ES server but you still set a very large connection timeout (3000 seconds == 50 minutes!!!). The default flush interval is less than 1 minute so you will get many flush tasks that are waiting for the connection to be established. This is nothing related to exception in the task, I believe all possible exceptions are caught in the flush method.

3000 ms, I write the wrong number。

**Comment by wu-sheng** [comment]
The timeout threshold is not the community's concern. The current value is reasonable.

I am just curious what is the exception.

**Comment by yangyiweigege** [comment]
I only noticed that flush schedule  throws this exception, but I don't know what the concret exception is. i will take time to design the exception.

**Comment by yangyiweigege** [comment]
> The timeout threshold is not the community's concern. The current value is reasonable.
> 
> I am just curious what is the exception.

I only noticed that flush schedule throws this exception, but I don't know what the concret exception is. i will take time to design the exception.

**Comment by kezhenxu94** [comment]
> 
> 
> 
> 
> 
> 
> > The timeout threshold is not the community's concern. The current value is reasonable.
> 
> > 
> 
> > I am just curious what is the exception.
> 
> 
> 
> I only noticed that flush schedule throws this exception, but I don't know what the concret exception is. i will take time to design the exception.

The exception "EmptyEndpointException" means there is no healthy ES server that can establish a connection

**Comment by yangyiweigege** [comment]
> connection

but in actually，we have the healthy ES server...maybe it‘s only timeout?

**Comment by kezhenxu94** [comment]
> > connection
> 
> 
> 
> but in actually，we have the healthy ES server...maybe it‘s only timeout?

Might be. You can try `curl` in the same machine as your OAP, to your ES server and see the time elapsed and status code. Like `curl http://<es>:<port>/_cluster/health`

**Comment by kezhenxu94** [comment]
> > connection
> 
> 
> 
> but in actually，we have the healthy ES server...maybe it‘s only timeout?

Might be. You can try `curl` in the same machine as your OAP, to your ES server and see the time elapsed and status code. Like `curl http://<es>:<port>/_cluster/health`

**Comment by kezhenxu94** [comment]
> > connection
> 
> 
> 
> but in actually，we have the healthy ES server...maybe it‘s only timeout?

Might be. You can try `curl` in the same machine as your OAP, to your ES server and see the time elapsed and status code. Like `curl http://<es>:<port>/_cluster/health`

**Comment by yangyiweigege** [comment]
> > > The timeout threshold is not the community's concern. The current value is reasonable.
> > 
> > 
> > > 
> > 
> > 
> > > I am just curious what is the exception.
> > 
> > 
> > I only noticed that flush schedule throws this exception, but I don't know what the concret exception is. i will take time to design the exception.
> 
> The exception "EmptyEndpointException" means there is no healthy ES server that can establish a connection

i have found the  really reason of why schedule task will throw exception, please see https://github.com/apache/skywalking/pull/8909
