### ISSUE TITLE
[Feature] Associate metrics with trace on UI

### ISSUE THREAD

**Issue by Fine0830** [apache/skywalking#8896]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add metric configurations to link trace tab and query trace with the duration and order fields.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Implemented in https://github.com/apache/skywalking-booster-ui/pull/115

**Comment by Fine0830** [comment]
> Implemented in [apache/skywalking-booster-ui#115](https://github.com/apache/skywalking-booster-ui/pull/115)

This [pr](https://github.com/apache/skywalking-booster-ui/pull/115) implements https://github.com/apache/skywalking/issues/9195. Currently, this function has not been realized yet.

**Comment by wu-sheng** [comment]
Yes, sorry.

**Comment by wu-sheng** [comment]
Should I continue to push this later in 9.3.0? As we are focusing on ebpf network profiling feature as a key feature of 9.3.0?

**Comment by Fine0830** [comment]
> Should I continue to push this later in 9.3.0? As we are focusing on ebpf network profiling feature as a key feature of 9.3.0

Yes.

**Comment by wu-sheng** [comment]
The last step is tracked through https://github.com/apache/skywalking/issues/9842
