### ISSUE TITLE
[Bug] ES BulkProcessor in BatchProcessEsDAO Initialize multiple times

### ISSUE THREAD

**Issue by yangyiweigege** [apache/skywalking#8897]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

org.apache.skywalking.oap.server.core.storage.PersistenceTimer#extractDataAndSave:
will initialize BulkProcessor  multiple times  in concurrent and create multiple flush task,  in actually, BatchProcessEsDAO have only one referenced BulkProcessor.

### What you expected to happen

BatchProcessEsDAO only init BulkProcessor  once time.

### How to reproduce

in concurrent init.

### Anything else

you can see at last one flush schedule : 
<img width="1036" alt="6592F812-C690-479B-85EA-E36EE03EA8CA" src="https://user-images.githubusercontent.com/23202824/163746291-27d1e44a-2e24-410a-bc0b-7ba321266bf0.png">
 but  one of the flush task,the request is all zero:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/23202824/163746360-4d2ba68b-e935-425b-897f-48433f1dc31d.png">
no actually meaning.

how to avoid:
the init code in org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.BatchProcessEsDAO#flush  by DCL.
```java
        if (bulkProcessor == null) { 
                synchronized(this) {
                       bulkProcessor  = new BulkProcessor();
               }
        }  

```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Assigned to you. Wait for your PR to discuss details on that.

**Comment by kezhenxu94** [comment]
I don’t think there is “concurrent init” as you said. Please read my comment in the other issue you posted. The fact you observed is true but the analysis is wrong.

**Comment by wu-sheng** [comment]
Agree, I can't see the case, that is why I am just pending on what he is going to propose. No data to consumer is common, such as no log reported.

**Comment by yangyiweigege** [comment]
code in org.apache.skywalking.oap.server.core.storage.PersistenceTimer#extractDataAndSave:
```java
 final CompletableFuture<Void> future =
            CompletableFuture.allOf(workers.stream().map(worker -> {
                return CompletableFuture.runAsync(() -> {
                    List<PrepareRequest> innerPrepareRequests;
                    // Prepare stage
                    try (HistogramMetrics.Timer ignored = prepareLatency.createTimer()) {
                        if (log.isDebugEnabled()) {
                            log.debug(
                                "extract {} worker data and save",
                                worker.getClass().getName()
                            );
                        }

                        innerPrepareRequests = worker.buildBatchRequests();

                        worker.endOfRound();
                    }

                    if (CollectionUtils.isEmpty(innerPrepareRequests)) {
                        return;
                    }

                    // Execution stage
                    HistogramMetrics.Timer executeLatencyTimer = executeLatency.createTimer();
                    batchDAO.flush(innerPrepareRequests)
                            .whenComplete(($1, $2) -> executeLatencyTimer.close());
                }, prepareExecutorService);
            }).toArray(CompletableFuture[]::new));
```
batchDAO is only one, but works have many and each work will invoke  batchDAO.flush in different threads, and batchDAO only have one BulkProcessor.   it means:
if (BulkProcessor == null ) can invoked many time。
batchDAO have only one BulkProcessor. 
Multiple scheduled tasks are initialized, but in reality, only one is useful. For the rest， ArrayBlockingQueue<Holder> requests  always  0 size.

**Comment by wu-sheng** [comment]
OK, yes, it could be in a concurrency case. @yangyiweigege You are correct, we miss a lock here.

**Comment by yangyiweigege** [comment]
> OK, yes, it could be in a concurrency case. @yangyiweigege You are correct, we miss a lock here.

i think can use double-checked locking(DCL)  in (BatchProcessEsDAO.flush and insert ) to avoid the bulkProcessor init many times.

**Comment by wu-sheng** [comment]
Yes, agree.
