### ISSUE TITLE
Possible bug fix: redundant `shade.package` property

### ISSUE THREAD

**Issue by Cool-Coding** [apache/skywalking#8904]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

There are `shade.package` properties in the path `apm-sniffer/pom.xml` and `apm-sniffer/apm-agent-core/pom.xml`.  I am not sure whether `shade.package` should only be defined in `apm-sniffer/pom.xml`.

`<shade.package>org.apache.skywalking.apm.dependencies</shade.package>`

### What you expected to happen

if this is a bug, I will remove the `shade.package` property in `apm-sniffer/apm-agent-core/pom.xml`.

### How to reproduce

Take a look at  `apm-sniffer/apm-agent-core/pom.xml` and `apm-sniffer/pom.xml`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I don't check this for years, but I remember once you removed one, the codes have issues.

**Comment by Cool-Coding** [comment]
> I don't check this for years, but I remember once you removed one, the codes have issues.

@wu-sheng  It won't cause codes issues. I verified it just now in my local computer using command `mvn clean package`.
Also, I looked at the shaded package in `apm-agent-core.jar`, the `shade.package` have worked.

![image](https://user-images.githubusercontent.com/29882506/163813323-9b1f6144-6a36-44e2-aee2-c231642b8d9a.png)

**Comment by wu-sheng** [comment]
Oh, you are just saying `<shade.package>org.apache.skywalking.apm.dependencies</shade.package>`. I thought you were talking about the shade plugin. Sorry.

Yes, these are duplicated, it was there due to a legacy reason because we didn't have separate `plugins` jars. They were in the agent.jar as a whole in the past(before 3.x I think?)

If you want to remove one, feel free to do. For me, it is a beauty proof of being a long history project. :) 

Do what you need to do, thanks for checking the codes carefully.

**Comment by Cool-Coding** [comment]
> Oh, you are just saying `<shade.package>org.apache.skywalking.apm.dependencies</shade.package>`. I thought you were talking about the shade plugin. Sorry.
> 
> Yes, these are duplicated, it was there due to a legacy reason because we didn't have separate `plugins` jars. They were in the agent.jar as a whole in the past(before 3.x I think?)
> 
> If you want to remove one, feel free to do. For me, it is a beauty proof of being a long history project. :)
> 
> Do what you need to do, thanks for checking the codes carefully.

Ok，I will submit a PR tomorrow. Thank you for letting me learn about the agent history.
