### ISSUE TITLE
client-js of vue3 [Feature] 

### ISSUE THREAD

**Issue by dengshenkk** [apache/skywalking#8911]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

client-js support vue3.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If you want to submit new feature support, welcome. If not, there is nothing we could track here.

The official issue tracker is for bugs or new features (someone has decided to do)
