### ISSUE TITLE
[Feature] [SWCK] Support for OAP dynamic configuration

### ISSUE THREAD

**Issue by dashanji** [apache/skywalking#8921]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The Issue is to support the OAP's [dynamic configuration](https://skywalking.apache.org/docs/main/latest/en/setup/backend/dynamic-config/) in SWCK.  
The key design is to add a field in CRD `OAPServer` to indicate whether the dynamic configuration is required. If required, the `OAPServer Controller` needs to create a `Configmap` so that users can use the dynamic configuration through the `Configmap`.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
Thanks for this proposal

There are two kinds of files in today's skywalking OAP configuration system: static config file attached to the OAP deployment and ConfigMap-based dynamic file. The end users have to pick the right path by referring to the documents and mind the break changes on upgrading the OAP. If it is the case, A union configuration CRD and Controller seems a gleam for such a scenario. 

You should provide a CRD to support both config files. The controller will identify the version of OAP, then determine which kind of file should be applied to OAP. The update strategy is very different:

  * Static file: Controller creates a new ConfigMap, and updates the OAP deployment. The previous file should get cleaned when the rolling upgrade process is completed successfully or rolled back when there are any errors. 
  * Dynamic file: Update ConfigMap.

**Comment by dashanji** [comment]
Make sense to me, the static file really needs a controller to manage. Thanks for the detailed description.
