### ISSUE TITLE
[Bug] the filed at path '/service_relation_server_resp_time/value{0}/id' was declared as anon null type,

### ISSUE THREAD

**Issue by lorihen** [apache/skywalking#8922]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

All are single deployments, The default H2 database used by OAP. there are some errors When I visit the topology tab page
![image](https://user-images.githubusercontent.com/45053680/164441287-ed1cd0cd-ded6-4998-81b5-232d2fb223c0.png)
I found out that it is because the monitored application has no data generated within the set time period.

"The field at path '/service_relation_client_cpm/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt' The field at path '/service_relation_client_resp_time/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt'"
"The field at path '/service_relation_server_resp_time/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt' The field at path '/service_relation_server_cpm/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt'"
"The field at path '/service_cpm/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt' The field at path '/service_sla/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt' The field at path '/service_resp_time/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt'"

### What you expected to happen

1. is it normal?
2. How to close this alarm message prompt?

### How to reproduce

environment:
OAP+UI   9.0.0
AGENT   8.10.0
Select a time period without requesting data to query，visit the topology tab page

### Anything else

Necessarily occur

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Mostly your OAP server is not working as expected, or down.

**Comment by AaronW-BE** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.
> 
> ### Apache SkyWalking Component
> OAP server (apache/skywalking)
> 
> ### What happened
> All are single deployments, The default H2 database used by OAP. there are some errors When I visit the topology tab page ![image](https://user-images.githubusercontent.com/45053680/164441287-ed1cd0cd-ded6-4998-81b5-232d2fb223c0.png) I found out that it is because the monitored application has no data generated within the set time period.
> 
> "The field at path '/service_relation_client_cpm/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt' The field at path '/service_relation_client_resp_time/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt'" "The field at path '/service_relation_server_resp_time/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt' The field at path '/service_relation_server_cpm/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt'" "The field at path '/service_cpm/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt' The field at path '/service_sla/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt' The field at path '/service_resp_time/values[0]/id' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'ID' within parent type 'KVInt'"
> 
> ### What you expected to happen
> 1. is it normal?
> 2. How to close this alarm message prompt?
> 
> ### How to reproduce
> environment: OAP+UI 9.0.0 AGENT 8.10.0 Select a time period without requesting data to query，visit the topology tab page
> 
> ### Anything else
> Necessarily occur
> 
> ### Are you willing to submit PR?
> * [x]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

Same error for me, how did you solved this error, thanks a lot.

**Comment by AaronW-BE** [comment]
> > Same error for me, how did you solve this error, thanks a lot.
> 
> @AaronW-BE @lorihen Could you try the latest master at least with this commit of booster UI and see. #8964 it's fixed here.

I used the docker distribudion, version 9.0.0, so still need waiting new version ....

**Comment by wu-sheng** [comment]
If you are talking about 8963, it is not a blocking issue. This error only shows out when there is no node and line of your topology. Put some services installing agent or export metrics/logs to SkyWalking, it would be fine.
Read the PR's description, before you jump into a conclusion.

**Comment by AaronW-BE** [comment]
> 

Okay, I see. thanks for your reply.
