### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by it-ll** [apache/skywalking#8930]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Use log4j2 to print logs asynchronous(All Loggers Asynchronous), the format is json, and there is no traceId on the web ui

### What you expected to happen

UI web displays traceID

### How to reproduce

Configure the lo4j2 log as All Loggers Asynchronous, the log format as Json, and the traceId is not displayed on the reported skywalking

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Async writer is not supported, because `getTraceId` is not in the correct context.

**Comment by wu-sheng** [comment]
Check doc first https://skywalking.apache.org/docs/skywalking-java/v8.10.0/en/setup/service-agent/java-agent/application-toolkit-log4j-2.x/

There are several difference usages.

**Comment by it-ll** [comment]
Asynchronous means that it does not support display on the ui？

**Comment by it-ll** [comment]
1、The log format is configured as：
 <PatternLayout  charset="UTF-8" pattern="[%d][%t][%p][%c:%L][%traceId] %m%n"/>
can print normally traceID；
2、The log format is configured as json format cannot be printed out traceId
      <JsonLayout eventEol="true" compact="true">
                <KeyValuePair key="timestamp" value="$${date:yyyy-MM-dd HH:mm:ss.SSS}" />
                <KeyValuePair key="projectName" value="***" />
                <KeyValuePair key="podName" value="****" />
     </JsonLayout>
why？

**Comment by it-ll** [comment]
1、The log format is configured as：
<PatternLayout  charset="UTF-8" pattern="[%d][%t][%p][%c:%L][%X{X-B3-TraceId}] %m%n"/>
can print normally traceID；
2、The log format is configured as json format cannot be printed out traceId
 <JsonLayout eventEol="true" compact="true">
                <KeyValuePair key="timestamp" value="$${date:yyyy-MM-dd HH:mm:ss.SSS}" />
                <KeyValuePair key="projectName" value="qwe" />
                <KeyValuePair key="podName" value="abc" />
 </JsonLayout>
why？

**Comment by it-ll** [comment]
1、The log print format is configured as
`PatternLayout  charset="UTF-8" pattern="[%d][%t][%p][%c:%L][%X{X-B3-TraceId}] %m%n"/>`
can print normally traceId
2、The log print format is configured as json
`<JsonLayout eventEol="true" compact="true">
                <KeyValuePair key="timestamp" value="$${date:yyyy-MM-dd HH:mm:ss.SSS}" />
                <KeyValuePair key="projectName" value="unm" />
                <KeyValuePair key="podName" value="vfr" />
   </JsonLayout>`
can not  print normally traceId
why？

**Comment by sunjiajie** [comment]
> 1、The log print format is configured as `PatternLayout charset="UTF-8" pattern="[%d][%t][%p][%c:%L][%X{X-B3-TraceId}] %m%n"/>` can print normally traceId 2、The log print format is configured as json `<JsonLayout eventEol="true" compact="true"> <KeyValuePair key="timestamp" value="$${date:yyyy-MM-dd HH:mm:ss.SSS}" /> <KeyValuePair key="projectName" value="unm" /> <KeyValuePair key="podName" value="vfr" /> </JsonLayout>` can not print normally traceId why？

me too
