### ISSUE TITLE
[Feature][SWCK] Add k8s event exporter CRD and controller

### ISSUE THREAD

**Issue by fgksgf** [apache/skywalking#8937]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Since skywalking k8s event exporter is releasing 1.0, we can provide a CRD in SWCK to better integrate it.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mikechengwei** [comment]
I can finish it, plz assign to me.

**Comment by kezhenxu94** [comment]
> I can finish it, plz assign to me.

Thank you! Assigned.

**Comment by rabajaj0509** [comment]
Is this feature implemented already? If yes, then we might want to close the issue. If not, and if @mikechengwei is not working on this anymore, I can pick it up as well -- @fgksgf @kezhenxu94

**Comment by kezhenxu94** [comment]
> Is this feature implemented already? If yes, then we might want to close the issue. If not, and if @mikechengwei is not working on this anymore, I can pick it up as well -- @fgksgf @kezhenxu94 

Thank you @rabajaj0509 for your interest in this issue. I think you can work on this.

**Comment by rabajaj0509** [comment]
Apologies for the delay in this issue. I have set up a k8s cluster for this story. Am currently trying to get familiar with the resource ( event-exporter) currently and trying to get it up and running with pure K8s deployment.

**Comment by dashanji** [comment]
@rabajaj0509 Excuse me, any update about this issue?
