### ISSUE TITLE
[Bug] some indexes not created after es init completed

### ISSUE THREAD

**Issue by tuhao1020** [apache/skywalking#8941]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

1. prepare an elasticsearch cluster 
2. install skywalking via helm, use es installed in the step 1
3. wait es-init to complete and oap/ui to get running
4. uninstall skywalking
5. delete alarm_record  index in the es
6. reinstall skywalking
7. oap server shows the following logs: 
```
2022-04-24 2022-04-24 09:09:00,866 org.apache.skywalking.oap.server.core.storage.model.ModelInstaller 43 [main] INFO  [] - table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later.
```

### What you expected to happen

the alarm_record index (or other removed indexes) should  be created again

### How to reproduce

es version: 6.8.13
skywalking version: 8.9.1

1. prepare an elasticsearch cluster 
2. install skywalking via helm, use es installed in the step 1
3. wait es-init to complete and oap/ui to get running
4. uninstall skywalking
5. delete alarm_record  index in the es
6. reinstall skywalking

### Anything else
SW_TELEMETRY=prometheus, SW_PROMETHEUS_FETCHER=default, meter-avghistogrampercentile is not created, is it as expected?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This means init-container doesn't run successfully. Check your env. And this is not a bug, just a question.
