### ISSUE TITLE
[Feature]  Support export to a file（eg: csv） for log query 

### ISSUE THREAD

**Issue by dcw2012** [apache/skywalking#8957]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Current  on the  log query page, query results cannot be exported to a file.  the user experience is not very good. Considering save the search results to a CSV file for downloading. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We are welcome you to contribute, but the feature request is usually self assign, meaning someone will submit PR later.

Close for now, as you are not going to do.
