### ISSUE TITLE
[Feature] add dynamic configuration mysql implementation

### ISSUE THREAD

**Issue by zhyyu** [apache/skywalking#8961]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Some companies do not want to add additional dependency when they already have mysql. So adding dynamic configuration mysql implementation will reduce the complexity of deployment.

### Use case

add dynamic configuration mysql implementation.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you proposing to use MySQL as the configuration center?

**Comment by zhyyu** [comment]
> Are you proposing to use MySQL as the configuration center?

Yes.

**Comment by wu-sheng** [comment]
It seems strange to me. A single Zookeeper or etcd costs little, and very rare to see a company even doesn't have one of this.

**Comment by zhyyu** [comment]
> It seems strange to me. A single Zookeeper or etcd costs little, and very rare to see a company even doesn't have one of this.

I used to use nacos to do that. But for high availability, It needs at least 3 nodes to do that and it wastes a lot of resources. Because the oap dynamic configuration number is small, and can config `period` to reduce the query qps, so I think can reuse existing mysql to do that.

**Comment by wu-sheng** [comment]
You could do that, but from my perspective, upstream is not going to accept this officially. We have a lot of options, and MySQL is not typical to do this.
