### ISSUE TITLE
[Bug] The same instance of a service appears

### ISSUE THREAD

**Issue by it-ll** [apache/skywalking#8972]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

The same instance of a service appears
![飞书20220428-202224](https://user-images.githubusercontent.com/41061792/165751201-8e3de5d6-ccdd-4876-ba82-a393775b5f84.png)

### What you expected to happen

Different instances of a service appear

### How to reproduce

Redeploy the service, the same instance appears

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No interest for v8 UI anymore.

**Comment by it-ll** [comment]
![飞书20220428-202807](https://user-images.githubusercontent.com/41061792/165751957-4d829024-155e-4ad1-ad66-6d0e4272756b.png)
 v9 UI same problem

**Comment by wu-sheng** [comment]
What issue?

**Comment by wu-sheng** [comment]
Service instance is created when reboot. That is correct.

**Comment by it-ll** [comment]
One instance should be displayed after restarting, in fact multiple identical instances are displayed

**Comment by wu-sheng** [comment]
That is your thought, not ours. Instance name could be set manually from some agents.

**Comment by it-ll** [comment]
okay，but I think there should be only unique instance after service restart, not the one before showing on ui

**Comment by wu-sheng** [comment]
You thought many things, open-source community have our own way. Committer and contributor make the call. If you want to make a decision, you need to contribute codes. Credits matter in here.
