### ISSUE TITLE
[Document] Basic usage guide

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#8989]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

BanyanDB recently took part in several code summer camps to attract more contributors to enhance the accessibility of the database servers by adding web apps and CLI tools. But there are no other materials for the candidates other than the original design document, which is a bit outdated. 

The basic guide will include:

  * Build and install the database server from the source. 
  * Examples of APIs interaction. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Let's build one and host it on the website. Please follow the website requirements to build folder structure and menu.yaml. We could keep latest doc on the website with released version docs.
