### ISSUE TITLE
[Feature] add plugin.jdbc.trace_sql_parameters into agent CDS

### ISSUE THREAD

**Issue by zhyyu** [apache/skywalking#9028]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add plugin.jdbc.trace_sql_parameters into agent CDS. 

### Use case

Sometimes don't want to change the agent config and restart the application to see the sql parameter. Add  plugin.jdbc.trace_sql_parameters into agent CDS make it can be changed dynamic.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@zhyyu Are you working on this?

**Comment by zhyyu** [comment]
> @zhyyu Are you working on this?

Yes, I am working on it. I meet some classloader issue, `org.apache.skywalking.apm.plugin.jdbc.JDBCPluginConfig.Plugin.JDBC` is loaded by two different `AgentClassLoader` . I am finding out the reason.

**Comment by zhyyu** [comment]
![image](https://user-images.githubusercontent.com/22634485/167979023-782797a4-75b6-4bef-8744-5c715e77f41c.png)

I write a  `JDBCPluginDynamicConfigService` `BootService` register the watcher change the config, but business thread use another classloader to see `JDBCPluginConfig.Plugin.JDBC.TRACE_SQL_PARAMETERS`, so the watcher don't work..

**Comment by wu-sheng** [comment]
I think you don't need a service,  you should have a watcher(AgentConfigChangeWatcher). Have you checked this?

**Comment by zhyyu** [comment]
> AgentConfigChangeWatcher

I create a new bootservice and watcher in jdbc-commons package. If i do not create a new  service, can I reuse `ContextManagerExtendService` or other existed bootservice to register my new warcher?

**Comment by wu-sheng** [comment]
Why do you make things so complex? You just need a watcher, and when the JDBC plugin is intercepting Driver initialization, you register this into the kernel, then you could have everything you need.

**Comment by wu-sheng** [comment]
You don't need `bootservice`. DCS has a kernel level service already.
