### ISSUE TITLE
[Document] Examples of CRUD operations 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9045]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

BanyanDB's CRUD operations include:

* Write/Update and Query [Measures](https://github.com/apache/skywalking-banyandb/blob/main/docs/crud/measure)
* Write/Update and Query [Streams](https://github.com/apache/skywalking-banyandb/blob/main/docs/crud/stream)
* Create, Update, Delete, Get and List [Properties](https://github.com/apache/skywalking-banyandb/blob/main/docs/crud/property)

gRPC’s easy interoperability with JSON. Therefore, the examples could use JSON to represent the input and output of APIs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by remGigo** [comment]
I'd like to take this task. :)

**Comment by lujiajing1126** [comment]
> I'd like to take this task. :)

Assigned to u
