### ISSUE TITLE
[OSPP] Command Line Tools

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9047]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

BanyanDB needs a command line tool to 

- Register/Unregister native resources using schema operations APIs
- CRUD the data using relevant APIs
- Monitor the health status of servers using observability APIs

This task depends on https://github.com/apache/skywalking/issues/9044

_This is a task of Open Source Promotion Plan_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by remGigo** [comment]
I'm really interested in this task, could you pls explain what does the “observability APIs” in the third purpose above refer to?

**Comment by remGigo** [comment]
Oh, I see , that might be this https://github.com/apache/skywalking/issues/9048. :)

**Comment by wu-sheng** [comment]
Would you consider to enhancing https://github.com/SkyAPM/go2sky SDK first? We should be able to have. go2sky + meter APIs first, then we could have trace(optional only) + meter (required) + logs (optional) collecting for BanyanDB natively.

**Comment by Superskyyy** [comment]
> Oh, I see , that might be this #9048. :)

> Would you consider to enhancing [SkyAPM/go2sky](https://github.com/SkyAPM/go2sky) SDK first? We should be able to have. go2sky + meter APIs first, then we could have trace(optional only) + meter (required) + logs (optional) collecting for BanyanDB natively.

I believe (9048) depends on the go2sky OSPP task? Let's focus on other subtasks first then see how that task go.

**Comment by wu-sheng** [comment]
Could we create one on go2sky repo? (Out of ASF though)

**Comment by Superskyyy** [comment]
@arugal FYI :)

**Comment by kezhenxu94** [comment]
> I believe (9048) depends on the go2sky OSPP task?
> Could we create one on go2sky repo? (Out of ASF though)

Out of curiosity, if there is dependency between multiple OSPP projects, how/when do we expect the students of each project to finish the project? Every single student should have equal time to do the work without being stressed by the fact that there is another student's work depends on  his/hers

**Comment by hanahmily** [comment]
> Out of curiosity, if there is dependency between multiple OSPP projects, how/when do we expect the students of each project to finish the project? Every single student should have equal time to do the work without being stressed by the fact that there is another student's work depends on his/hers

#9048 is not an OSPP or GSoC project. It's an independent intro-level task for normal contributors.
