### ISSUE TITLE
[Feature] Instrument banyand server

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9048]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add a series of metrics to the banyand server to measure the internal status of memory, file system, and individual modules. Furthermore, the SkyWalking OAP server could collect them to analyze, and UI could render them. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/issues/9047#issuecomment-1125604323

@kezhenxu94 @Superskyyy @remGigo Let's continue the discussion here. My suggestion is either we make this task on go2sky purely or go2sky + banyandb instrumentation (advanced one).

**Comment by kezhenxu94** [comment]
> My suggestion is either we make this task on go2sky purely or go2sky + banyandb instrumentation (advanced one).

We could do this, adding meter feature to go2sky is definitely a big 👍 .

But why we have to couple BanyanDB and go2sky. I mean:

- We can use Prometheus protocol to provide BanyanDB metrics just like [how satellite did](https://github.com/apache/skywalking-satellite/tree/main/internal/satellite/telemetry/prometheus), OAP can already consume these metrics.
- We can add go2sky into BanyanDB if we want to add more instrumentation like traces (I believe we don't need that tho)
- We can add a independent project in go2sky to add meter feature.

SO there is no dependency between go2sky and BanyanDB

**Comment by wu-sheng** [comment]
We don't choose Prometheus for now to BanyanDB. We had a discussion before. OTEL fetcher already causes many concerns.
I agree that the tasks for students or new contributors should not have a dependency, so I suggest updating the task description.

**Comment by wu-sheng** [comment]
Quoted https://github.com/apache/skywalking/issues/9047#issuecomment-1125620275

So, there is no concern here.

**Comment by kezhenxu94** [comment]
> Quoted [#9047 (comment)](https://github.com/apache/skywalking/issues/9047#issuecomment-1125620275)
> 
> So, there is no concern here.

Ok, so to sum up, an OSPP project depends on 2 non-OSPP tasks.

#9047 depends on this issue to finish the task 👇

> - Monitor the health status of servers using observability APIs 

But this issue depends on go2sky to provide meter feature...

**Comment by hanahmily** [comment]
> #9047 depends on this issue to finish the task 👇
> 
> > * Monitor the health status of servers using observability APIs
> 
> But this issue depends on go2sky to provide meter feature...

The basic observability APIs are ready for CLI to access. They are based on Prometheus exporter go libs. The relevant feats in this thread could be based on them.

**Comment by complone** [comment]
I'd like to know where I need to bury the dots and what configuration format I need to render in yaml in order to keep track of the relevant details

**Comment by complone** [comment]
I'd like to know where I need to bury the dots and what configuration format I need to render in yaml in order to keep track of the relevant details

**Comment by lujiajing1126** [comment]
> I'd like to know where I need to bury the dots and 

I guess "bury the dots" means what kind of operations and information we should collect or record?

> what configuration format I need to render in yaml in order to keep track of the relevant details

I suppose according to Hongtao's comment https://github.com/apache/skywalking/issues/9048#issuecomment-1125633917 above, Prom's text-based format is enough now.

**Comment by complone** [comment]
> Prometheus

@lujiajing1126 Yes. I need to know which metrics from Prometheus should be collected

**Comment by complone** [comment]
@lujiajing1126 I will first track the relevant process of BanYanDB. Be familiar with the general process. In order to collect information such as memory, file system and the internal state of each module

**Comment by complone** [comment]
Hello everyone, by tracking the code of skywalking-banyandb stress test: https://github.com/apache/skywalking-banyandb/blob/main/test/stress/stress_suite_test.go. I tracked that in the KV class, statistics can be passed through dbOpts Some storage metrics of banyandb, code location: https://github.com/apache/skywalking-banyandb/blob/5886070c8406d1fe0df82b7579933f4d9b1435db/banyand/kv/kv.go#L190
At present, I want to add the buried point function of go2sky to the code segment here to obtain the storage information of banyandb. I don't know if my understanding is correct?

@hanahmily Can you give me some advice?

**Comment by complone** [comment]
In addition, I think the indicators should be aggregated here. It is only necessary to give go2sky to report the indicators to the OAP backend of skywalking.

See [code location](https://github.com/apache/skywalking-banyandb/blob/5886070c8406d1fe0df82b7579933f4d9b1435db/banyand/kv/badger.go)

**Comment by wu-sheng** [comment]
I don't think go2sky has meter APIs for now. Besides all instrument works, you should begin to discuss those APIs at the go2sky repo with project leader @arugal and other members.

**Comment by complone** [comment]
> I don't think go2sky has meter APIs for now. Besides all instrument works, you should begin to discuss those APIs at the go2sky repo with project leader @arugal and other members.

Ok, I am investigating the feasibility of adapting go2sky api to meter api. After sorting out the plan, I will communicate with you in the form of google doc

**Comment by complone** [comment]
> @complone您好，由于go2sky Meter api是学生通过OSPP承担的，请先尝试与导师沟通，以免发生碰撞。

ok thanks for letting me know

**Comment by Superskyyy** [comment]
> > @complone您好，由于go2sky Meter api是学生通过OSPP承担的，请先尝试与导师沟通，以免发生碰撞。

I'm connecting with the student to confirm some details, will update to you.

**Comment by hanahmily** [comment]
The BanyanDB server has implemented the meter module.
