### ISSUE TITLE
[Feature] End to End Testing

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9049]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Compose several end-to-end test cases to verify the BanyanDB server(Banyand) works fine with SkyWalking ecosystem.

* Collect tracing data: demo application + Java agent + OAP + Banyand
* Collect logs: filebeat + OAP + Banyand
* Collect metrics: oap self observability + OAP + Banyand

The cases should include individual scenarios and a combination of the above.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hoteye** [comment]
https://blog.csdn.net/oqqford/article/details/125637528?spm=1001.2014.3001.5502
Here's a demo trace capture app I wrote. How can I accomplish this issue? I can do more to help。

**Comment by wu-sheng** [comment]
@hanahmily What is this issue about? The e2e is already involved in e2e tests in the main repo. 
Search `banyandb` in https://github.com/apache/skywalking/blob/master/.github/workflows/skywalking.yaml.

Could you explain a little more?

**Comment by hoteye** [comment]
I found this issue from [WeOpen Star]

**Comment by wu-sheng** [comment]
I know that. I mean this is test related issue. I am not sure what is the context of this your sharing

> https://blog.csdn.net/oqqford/article/details/125637528?spm=1001.2014.3001.5502
Here's a demo trace capture app I wrote. How can I accomplish this issue? I can do more to help。

**Comment by lujiajing1126** [comment]
> "Collect tracing data: demo application + Java agent + OAP + Banyand." So I shared the sample program I wrote

I suppose this goal has already been accomplished in the main repo.

> @hanahmily What is this issue about? The e2e is already involved in e2e tests in the main repo. Search `banyandb` in https://github.com/apache/skywalking/blob/master/.github/workflows/skywalking.yaml.
> 
> Could you explain a little more?

The second and the third ones are still missing as I understand

**Comment by wu-sheng** [comment]
That is SkyWalking project does, not ask you to implement trace.
I think you are better to knowwhat are skywalking and banyandb, also what is end to end testing. Mostly important, how we are using GitHub action and skywalking-infra-e2e today.
