### ISSUE TITLE
[Bug] [BanyanDB] Measures with the same ID should be overwritten

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#9067]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

InstanceTraffic metrics updates will cause duplicated measures.

### What you expected to happen

Measure (e.g. `InstanceTraffic`) update with the same ID should only update the existing one if there is.

### How to reproduce

Run OAP with BanyanDB

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Should be fixed by https://github.com/apache/skywalking-banyandb/pull/115
