### ISSUE TITLE
[Bug] the topology is wrong. There should be one kafka node.

### ISSUE THREAD

**Issue by Cool-Coding** [apache/skywalking#9080]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

There are two services named `agent_test_2` and `agent_test_3` and a kafka middware whose ip  is `127.0.0.1:9092`.  `Agent_test_2` pushs messages to kafka and `agent_test_3` consumes from kafka.  The topology is strange. 

<img width="538" alt="image" src="https://user-images.githubusercontent.com/29882506/168785834-68c5d217-9040-4ad4-915d-0e7c8f457815.png">

There are two kafka nodes in the topology.  but the two nodes should be the same in fact.

I have debugged the `oap` codes. I found when `oap` analysised `service relation` from segment, the source layer type of the service `agent_test_3` was set `LAYER.VIRTUAL_MQ`, however, the target layer type of the service `agent_test_2` was set `LAYER.MQ`.  it result in the same kafka service id of the two spans are  different, then, it causes the topology is strange.

### What you expected to happen

There should be one kafka node in the topology.

### How to reproduce

one service pushes messages to kafka, another service consumes from the kafka.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Both of them should be VIRTUAL_MQ.
Would you fix this?

**Comment by Cool-Coding** [comment]
> Both of them should be VIRTUAL_MQ. Would you fix this?

OK, I will pull a request.
