### ISSUE TITLE
[Bug] when i use SumAggregationBuilder , in actually , return MaxAggregation

### ISSUE THREAD

**Issue by yangyiweigege** [apache/skywalking#9111]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

when i user the SumAggregationBuilder function, in actually, it return MaxAggregation. code in
org.apache.skywalking.library.elasticsearch.requests.search.aggregation.SumAggregationBuilder

```java
public final class SumAggregationBuilder implements AggregationBuilder {
    private final String name;

    private String field;

    SumAggregationBuilder(String name) {
        this.name = name;
    }

    public SumAggregationBuilder field(String field) {
        checkArgument(!Strings.isNullOrEmpty(field), "field cannot be blank");
        this.field = field;
        return this;
    }

    @Override
    public MaxAggregation build() {
        return new MaxAggregation(name, field);
    }
}
```

### What you expected to happen

when i use SumAggregationBuilder ,it should return the sum function instead of max function.

### How to reproduce

see code in org.apache.skywalking.library.elasticsearch.requests.search.aggregation.SumAggregationBuilder

### Anything else

see code in org.apache.skywalking.library.elasticsearch.requests.search.aggregation.SumAggregationBuilder
![image](https://user-images.githubusercontent.com/23202824/169644880-05799ab4-42ed-4ebe-b415-1c1a34796b4f.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
First of all, this seems a bug. 
Meanwhile, could you share when do you use this?

**Comment by kezhenxu94** [comment]
@yangyiweigege good catch! Are you going to open a pull request?

**Comment by yangyiweigege** [comment]
> First of all, this seems a bug.
> Meanwhile, could you share when do you use this?

i want to known the  invoke all counts in period , so i secondary development based on skywalking oap.for example,i user SumAggregationBuilder to count .

**Comment by yangyiweigege** [comment]
> good catch! Are you going to open a pull request?

yes
