### ISSUE TITLE
[Feature] [UI] Replace event menu with a dashboard widget

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9126]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The current event menu was added in v9 temporarily, in this iteration, we should consider using the following timeline component style to replace it. Also, we should move the event lists into layer's widget for service/instance/endpoint level

<img width="828" alt="image" src="https://user-images.githubusercontent.com/5441976/170036345-c7943859-0dc8-4f2b-b44f-dc289afe17b2.png">

@kezhenxu94 Once we have this, we should consider this component listed as a separate tab or at the bottom of the current dashboard. One day in the longer term, we will consider widget interaction seriously(so far, it is an idea only)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@kezhenxu94 I reassigned this to you.
After @Fine0830 sync, you could work on adding this to suitable dashboards.

**Comment by wu-sheng** [comment]
Event could associate with metrics linear graph https://github.com/apache/skywalking-booster-ui/pull/120

**Comment by kezhenxu94** [comment]
> As #9361 is good to merge, @Fine0830 please remove the event menu permanently. We are going to rely on the event widget only.
> 
> @kezhenxu94 Does this make sense? ☝️

Sure!
