### ISSUE TITLE
[Bug] The current page number does not change if total page size is less than the current page number after a new query in trace page

### ISSUE THREAD

**Issue by donghbcn** [apache/skywalking#9147]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

The current page number does not change if total page size is less than the current page number after a new query in trace page in verion v8.9.1

### What you expected to happen

Maybe it's better to set the current page number to 1 if total page size is less than the current page number after a new query in trace page.

### How to reproduce

1.Search with a wider filter and get a result with relative large total page size
2.navigate to a certain page, such as 10
3.narrow down the filter, and ensure the result total page size is less than the page we navigated to in step 2.
4.we get the first page data for the new query, how ever the current page numer remain with the numer we navigated in step 2.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
v8 is not on support mode anymore.

**Comment by donghbcn** [comment]
Do you mean it's not a problem in v.9.1.0 any more?

**Comment by Superskyyy** [comment]
> Do you mean it's not a problem in v.9.1.0 any more?

V9 uses a brand new UI project and it's called boosterUI, RobcketBotUI is no longer maintained.

**Comment by donghbcn** [comment]
Understand now, thx
