### ISSUE TITLE
[BanyanDB] Build document generator 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9150]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

BanyanDB leverage [protoc-gen-doc](https://github.com/pseudomuto/protoc-gen-doc) to generate a single-page API reference. It's very convenient for the current API volume, even with some tiny flaws(the name of generated anchor contains upper case letters, which is not compatible with the official document generator). 

When more APIs emerge, the single page will not be ideal. Moreover, the future RESTFul APIs need the generator to output Openapi formatted files unsupported by "protoc-gen-doc". Based on those, we have to build a custom API document generator to build both gRPC and RESTful APIs and split them into several individual files. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@hanahmily Is this added?

**Comment by hanahmily** [comment]
> @hanahmily Is this added?

No, there is no update here.
