### ISSUE TITLE
[Feature] [UI] Export the eBPF Profiling flame graph

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#9154]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently,  we could generate the flame graph in the UI based on the analysis data of eBPF Profiling. 
To enhance interactivity, we can add a button to export the flame graph (including selection and tip functions), similar to the "Export image" function in the Trace control.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Should I continue to push this later in 9.3.0? As we are focusing on ebpf network profiling feature as a key feature of 9.3.0?

**Comment by mrproliu** [comment]
It's ok for me. Also, we could using the skywalking-cli to export the flame graph, using UI to export it just other way.

**Comment by wu-sheng** [comment]
After some discussion, we noticed this would cost too much as it is not just exporting an image, it has to include html/js with data. There is no real case why users can't use our UI but an exported page. 

Close for now.
