### ISSUE TITLE
[Bug] unknown service ManagementService

### ISSUE THREAD

**Issue by xiaoxianjie** [apache/skywalking#9159]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Server Side Agent (apache/skywalking-nodejs)

### What happened

i am try to use skywalking in my nodejs project, so i follow the readme to update my code.
but, there is some wrong when i start the app.

---------------------------------------------------
like as 
{
  file: 'xxxx\\node_modules\\skywalking-backend-js\\lib\\agent\\protocol\\grpc\\clients\\HeartbeatClient.js',
  code: 12,
  details: 'unknown service ManagementService',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [ 'application/grpc' ] },
    options: {}
  },
  level: 'error',
  message: 'Failed to send heartbeat 12 UNIMPLEMENTED: unknown service ManagementService',
  stack: 'Error: 12 UNIMPLEMENTED: unknown service ManagementService\n' +
    '    at Object.callErrorFromStatus (xxxx\\node_modules\\@grpc\\grpc-js\\src\\call.ts:81:24)\n' +
    '    at Object.onReceiveStatus (xxxx\\node_modules\\@grpc\\grpc-js\\src\\client.ts:351:36)\n' +
    '    at Object.onReceiveStatus (xxxx\\node_modules\\@grpc\\grpc-js\\src\\client-interceptors.ts:462:34)\n' +
    '    at Object.onReceiveStatus (xxxx\\node_modules\\@grpc\\grpc-js\\src\\client-interceptors.ts:424:48)\n' +
    '    at xxxx\\node_modules\\@grpc\\grpc-js\\src\\call-stream.ts:330:24\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:77:11)'
}

### What you expected to happen

i am not sure why it happen

### How to reproduce

i think, maybe then wrong using. 
so i clone 'https://github.com/apache/skywalking-showcase/tree/main/services/app', 
build docker image,  
configure the same parameters, 
it work well. 

------------------------------------
both of the tow projects, 
the only diff is my project use npm to install the skywalking-backend-js in package.json, 
but the example project build and install the skywalking-backend-js in dockerfile when build docker image.

-------------------------------------
so i am try to use npm to install skywalking-backend-js in package.json of the example project, and delete the step to build and installskywalking-backend-js in dockerfile, rebuild docker image,  configure the same parameters, then i get the same wrong.

-------------------------------------
my os is win10 home.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I think you use old OAP server.

**Comment by wu-sheng** [comment]
I just say from error log. I can't debug for you. This is your responsibility.

**Comment by wu-sheng** [comment]
It could be too many version gaps for agents.

**Comment by xiaoxianjie** [comment]
i try to build and install skywalking in Dockfile of my project, as in the example project.
it is the only change in my project.

--------------------------------------
ARG SW_AGENT_NODEJS_BACKEND_VERSION

WORKDIR /skywalking-backend-js

RUN git clone --recurse-submodules https://github.com/apache/skywalking-nodejs.git .
RUN git reset --hard ${SW_AGENT_NODEJS_BACKEND_VERSION}
RUN git submodule update
RUN git submodule sync
RUN npm install
RUN npm run build

RUN npm install /skywalking-backend-js

----------------------------------------
then, my project can report data normally
