### ISSUE TITLE
[Bug] something went wrong when use Router in expressjs with skywalking

### ISSUE THREAD

**Issue by Midqiu** [apache/skywalking#9165]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Server Side Agent (apache/skywalking-nodejs)

### What happened

when i user router in expressjs with skywalking, some went wrong.

```
app.use("/hello/",async function (req, res) {
  res.send("Hello")
})

// this is router
const router = express.Router()
router.get("/router/", async function (req, res) {
  res.send("Hello router")
})

app.use(router)


app.use("/hello2/", async function (req, res) {
  res.send("Hello2");
});
```

and the result is:
this is OK:
![)(G$S26HXV8(Q$PFMR82R`B](https://user-images.githubusercontent.com/5728399/171541992-b9d25054-3766-41bc-8b84-878694b3f26c.png)

but this has two records in skywalking:
![MTL`BUD38((@L5J5EF2%(OE](https://user-images.githubusercontent.com/5728399/171542078-71b0944f-f5a9-4c8a-bd4a-63f76eaba103.png)

and this has two records and tell me has error:
![SW9_4ZP%`AC9L1EYD%SL(@4](https://user-images.githubusercontent.com/5728399/171542127-dc19168e-ce57-46b2-8292-2e5b9cebae6d.png)

### What you expected to happen

`/router/` and `/hello2/aaa` has one record and has no error。

### How to reproduce

# 1. start this server：
```

var express = require('express')
var agent = require('skywalking-backend-js').default

agent.start({
    serviceName: "***",
    collectorAddress: "***",
})
const app = express()

app.use("/hello/", async function (req, res) {
    res.send("Hello")
})


const router = express.Router()
router.get("/router/", async function (req, res) {
    res.send("Hello router")
})

app.use(router)


app.use("/hello2/", async function (req, res) {
    res.send("Hello2");
});

const PORT = 4444
app.listen(PORT, () => {
    console.log(`Example app listening at http://localhost:${PORT}`)
})
```
# 2. Visit web address
http://localhost:4444/hello/aaa
http://localhost:4444/router/
http://localhost:4444/hello2/aaa

# 3. see the skywalking dashboard

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
Closing as fixed ^
