### ISSUE TITLE
[Bug] UI docker image start failed

### ISSUE THREAD

**Issue by BruceAn1978** [apache/skywalking#9176]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

Use below Dockerfile to build a new image and publish to k8s
```
FROM apache/skywalking-ui:9.0.0

ENV SW_OAP_ADDRESS=http://oap.bruce.io:12800

EXPOSE 8080
ENTRYPOINT ["/skywalking/docker-entrypoint.sh"]
```

The flowing errors were displayed in the log and the pod restarted times by times
_libcontainer: container start initialization failed: standard_init_linux.go:224: exec user process caused "exec format error_

### What you expected to happen

New docker container should start normally and can be accessed from the browser.

### How to reproduce

Run the Dockerfile.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
What you did on a docker file is your own responsibility. We have provided official docker image as well as helm and operator.

**Comment by BruceAn1978** [comment]
> The docker file is only pull and rebuild it and then can run the pipeline job to deploy it to the correct k8s cluster, so we can not use the official helm and oprator.

what can I do with the error?

**Comment by wu-sheng** [comment]
Support docker is not our scope. Sorry.

**Comment by BruceAn1978** [comment]
I solved the problem by modify the docker file with this line:
`ENTRYPOINT ["bash", "docker-entrypoint.sh"]`
