### ISSUE TITLE
[Feature] Modules Automated Initialization

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9186]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Introduce a system to automate initialing and connecting modules. Users could determine which modules are booted. We might base on https://pkg.go.dev/github.com/google/wire to implement this.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hoteye** [comment]
[WeOpen Star]I would like to help

**Comment by hoteye** [comment]
I got it. i well try my best

**Comment by hanahmily** [comment]
Another framework option is https://github.com/uber-go/fx
