### ISSUE TITLE
[Feature] Traffic generator

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9194]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We should leverage https://github.com/apache/skywalking/pull/8725 to setup traffic generator for:

* Verify whether each component implements specification behaviors. 
* Load testing
* Empower the development process of bydbctl and webapp.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hoteye** [comment]
我工作中使用了skywalking。我对skywalking代码比较收悉。希望能帮助解决此问题，但我还不是非常了解该问题。希望共享的同时学习开源共享的经验，提升自己的能力。

**Comment by wu-sheng** [comment]
> 我工作中使用了skywalking。我对skywalking代码比较收悉。希望能帮助解决此问题，但我还不是非常了解该问题。希望共享的同时学习开源共享的经验，提升自己的能力。

Hi, please keep all things on GitHub in English, as we need to keep global users nd developers in sync.

**Comment by zrsaber** [comment]
Can you assign it to me?I'll try to work on this.

**Comment by wu-sheng** [comment]
Traffic generator has been added, https://github.com/apache/skywalking-banyandb/pull/143.

@hanahmily Could you confirm whether there are more to do in this issue?
