### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by moma-tech** [apache/skywalking#9196]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

with v9 ui, in general dashboard, when pick a end date on the navbar, will set the start date with same value at same time, and cause a series of query error

![image](https://user-images.githubusercontent.com/7851881/172823745-85818863-cc6c-4469-80ad-9b8a1772a7e2.png)

### What you expected to happen

should only set the end date.

### How to reproduce

- General Service
- click any service to get General Dashboard
- Navbar, right top, pick any end date

### Anything else

Not really familiar with VueJS, has check the source code,  
- TimePicker.vue
- setDates() emit twice, one with positon right, one without as position is undified, thus further set the start date
- tricky walkround, double check left position
![image](https://user-images.githubusercontent.com/7851881/172824820-d80d3a22-9a2e-4c1e-8572-ee47d5f1fb32.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Everything on demo works. You could try that and recheck.

**Comment by wu-sheng** [comment]
The errors should relate to your backend not working well.
