### ISSUE TITLE
[Bug] Unhandled ERR_STREAM_WRITE_AFTER_END error is thrown because no error handler on ClientWritableStreamImpl

### ISSUE THREAD

**Issue by nieyuyao** [apache/skywalking#9197]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Server Side Agent (apache/skywalking-nodejs)

### What happened

An `write after end` is thrown and make node crashes. 

```javascript
events.js:288
    throw er; // Unhandled 'error' event
    ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:264:14)
    at ClientHttp2Stream.Writable.write (_stream_writable.js:313:5)
    at Http2CallStream.writeMessageToStream (/home/appops/approot/server/node_modules/@grpc/grpc-js/build/src/call-stream.js:332:26)
    at /home/appops/approot/server/node_modules/@grpc/grpc-js/build/src/call-stream.js:665:26
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on ClientWritableStreamImpl instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:462:5)
    at onwrite (_stream_writable.js:483:5)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

We found `TraceReportClient` used grpc request which has `client_stream` type. The related code is [here](https://github.com/apache/skywalking-nodejs/blob/703c2b6f898ec52a67b4e04444c5d168c2a194ec/src/agent/protocol/grpc/clients/TraceReportClient.ts#L63-L88).  This returns a `ClientWritableStreamImpl` class.  We need an error handler here to stop "Uncaught error" exceptions from bubbling up, as pointed out in this [issue](https://github.com/grpc/grpc-node/issues/2072#issuecomment-1080938635).

### What you expected to happen

Add one error hander to stream to prevent this error be thrown.

### How to reproduce

None

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No update in 17 days.

**Comment by wu-sheng** [comment]
Not much detail to follow. Close for now.

**Comment by nieyuyao** [comment]
Is anyone following up on this issue?
