### ISSUE TITLE
[Bug] fileOutputStream in FileWriter has been flushed and cleared when switching to a new file, which causes NPE.

### ISSUE THREAD

**Issue by xiaomiusa87** [apache/skywalking#9201]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

When Config.Logging.MAX_FILE_SIZE is smaller，fileOutputStream will be set to null.  
But  LogFileWriter scheduled tasks are still executing ，fileOutputStream.flush()  will produce NPE ，Although it was captured

![image](https://user-images.githubusercontent.com/72253502/173171032-c67ec245-4ad6-441a-b76d-1f3492cf515c.png)
![image](https://user-images.githubusercontent.com/72253502/173171947-2324a423-8bb7-4dd8-842b-545958a538c9.png)

### What you expected to happen

Expect not produce NPE 

### How to reproduce

Skywalking  version: 8.9.1
Skywalking-Java-Agent  version: 8.10.0
SpringBoot 

### Anything else

No response

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Wait for your pull request.

**Comment by xiaomiusa87** [comment]
> Wait for your pull request.

I have submitted pr :  https://github.com/apache/skywalking-java/pull/205

**Comment by wu-sheng** [comment]
The fix is good. I want to be clear, this bug is caused by `fileOutputStream` has been flushed and cleared when switching to a new file. So this bug doesn't relate to time(per second), more about reach the limit of file size.

**Comment by xiaomiusa87** [comment]
> The fix is good. I want to be clear, this bug is caused by `fileOutputStream` has been flushed and cleared when switching to a new file. So this bug doesn't relate to time(per second), more about reach the limit of file size.

Yes, it has little effect. It just seems a little strange
