### ISSUE TITLE
[Bug]  [Skywalking Version 9.1.0] can not assigned static path

### ISSUE THREAD

**Issue by Suancaiyu0707** [apache/skywalking#9214]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

can not assigned static path

### What you expected to happen

can assigined static path from webapp.yml

### How to reproduce

config webapp.yml and add properties spring.mvc.static-path-pattern but not effect

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't support that.
