### ISSUE TITLE
Trace page auto-freshing bahaviour

### ISSUE THREAD

**Issue by BertOnline** [apache/skywalking#9224]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

After skywalking 9.1.0 turns on auto refresh, the trace page automatically refreshes every few seconds. Even after auto refresh is turned off, the trace page still automatically refreshes every few seconds. The trace pages of versions before 9.0 are not affected by auto refresh。

### What you expected to happen

Trace pages are not affected by automatic refresh.

### How to reproduce

http://demo.skywalking.apache.org/general

In the official example, turn on automatic refresh to observe the trace page, and then turn off automatic refresh to observe the trace page.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@Fine0830 Do you think it is reasonable to not follow auto-fresh on trace/log/profiling/ebpf-profling pages?

**Comment by Fine0830** [comment]
> @Fine0830 Do you think it is reasonable to not follow auto-fresh on trace/log/profiling/ebpf-profling pages?

It's a bug, let me fix it.
