### ISSUE TITLE
Can we log traceid only with skywalking agent，no OAP

### ISSUE THREAD

**Issue by childewuque** [apache/skywalking#9235]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

springboot 2.6.7
apache-skywalking-java-agent-8.10.0

Can logback print TraceID when everything is configured normally but AOP is not started?
In addition, what is the relationship between apm-toolkit-logback-1.x and  apm-toolkit-logback-1.x-activation? Is there any introduction? 
thank you！

### Use case

We have a product.
Sometimes，it  only needs  traceid in log.
Sometimes,  it  needs  skywalking  all  and traceid in log

### Related issues

no 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No, you can't. This doesn't make any sense to SkyWalking.

**Comment by childewuque** [comment]
@wu-sheng 
The lightweight traceid solution is also valuable. It is mainly in the product environment used by enterprises. Some enterprises are short of resources and only want to print traceid. Some have rich resources and can use a full set of skywalking

Thanks.

**Comment by wu-sheng** [comment]
That is your choice, not community. SkyWalking has no interest to waste so much time to adopt a private feature.
