### ISSUE TITLE
[Feature Rust Agent]: Maybe add `.build_server(false)`, tonic-build do not build Server code.

### ISSUE THREAD

**Issue by CherishCai** [apache/skywalking#9271]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Maybe add `.build_server(false)`, tonic-build do not build Server code.

https://github.com/apache/skywalking-rust/blob/5fded8e7cb936de4a6a3d6b689f9d22645466d2f/build.rs#L18

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::configure()
        .build_server(false)
        .compile(
            &["./skywalking-data-collect-protocol/language-agent/Tracing.proto"],
            &["./skywalking-data-collect-protocol"],
        )?;
    Ok(())
}

```

### Use case

do not appear `trace_segment_report_service_client::TraceSegmentReportServiceServer` in `skywalking.v3.rs`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't intend to build server codes. This is a SDK for Rust.

**Comment by CherishCai** [comment]
now the Server code is useless.
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/16837364/175764090-8838d958-e861-4d8e-88e3-a7a42bc6258b.png">

so maybe `.build_server(false)` do not build Server code. 
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/16837364/175764029-a473b5d3-d2cd-411d-a16a-ebacc6cee223.png">

**Comment by wu-sheng** [comment]
If you want to propose something, could you be more clear? 
If you want to polish generated codes, it is good to go.
In the open source, only technology perspective uncertainthings need to be discussed. But this seems just a polish.You don't need a permission.

**Comment by CherishCai** [comment]
Maybe it's because I didn't express it clearly enough.
What I mean is that the `trace_segment_report_service_client::TraceSegmentReportServiceServer` built by tonic-build is redundant now, and adding `.build_server(false)` can reduce the generation of this code.
