### ISSUE TITLE
[Doc Rust Agent] Typo in `context/propagation/context.rs`.

### ISSUE THREAD

**Issue by CherishCai** [apache/skywalking#9272]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. previos -> previous
https://github.com/apache/skywalking-rust/blob/5fded8e7cb936de4a6a3d6b689f9d22645466d2f/src/context/propagation/context.rs#L29

2. infomation - > information
https://github.com/apache/skywalking-rust/blob/5fded8e7cb936de4a6a3d6b689f9d22645466d2f/src/context/propagation/context.rs#L48

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This kind of typo could be fixed easily through a pull request. I can't see why we need an issue to track.

**Comment by wu-sheng** [comment]
Could you submit a pull request to fix directly?

**Comment by CherishCai** [comment]
> Could you submit a pull request to fix directly?

OK, thanks for your reply.
