### ISSUE TITLE
Available to Flutter web

### ISSUE THREAD

**Issue by Spiderbezno** [apache/skywalking#9282]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

A client in Dart o similar to add compatibility with the framework FLutter in the web

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Can't see the relevant.
