### ISSUE TITLE
skywaking-ui log charset is wrong[Bug] 

### ISSUE THREAD

**Issue by wuzemian** [apache/skywalking#9294]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

skywaking-ui log charset is wrong when use GRPCLogClientAppender 8.11.
![微信图片_20220701111046](https://user-images.githubusercontent.com/28946366/176816113-ee644187-9bd0-4d48-9d5f-9303bec04667.png)
0

![微信图片_20220701111346](https://user-images.githubusercontent.com/28946366/176816354-c41e1924-62e1-4237-aebd-c16492aa35dd.png)

### What you expected to happen

skywaking-ui log charset 

is wrong when use GRPCLogClientAppender 8.11.0

### How to reproduce

logback use GRPCLogClientAppender 8.11.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't have people who have checked the charset for Chinese. Sorry. If you want to dig this deeper, you are on your own.
