### ISSUE TITLE
[Python] add docs about how to run tests locally (or even simplify it if it's too complex)

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#9301]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Related to https://github.com/apache/skywalking-python/pull/214#pullrequestreview-1026894959 .

Our contributor has to look around the repo for demo scripts to run the tests locally. Sometimes they have to try over and over. I'd expect the guide to run tests locally should be clearly documented step by step.

We should add a new section in https://github.com/apache/skywalking-python/blob/master/docs/en/contribution/PluginTest.md

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiang1997** [comment]
I write a guide to local test in this [commit](https://github.com/jiang1997/skywalking-python/commit/acc9f08f01edba66991907d8a6b428777371f199). Do you have any suggestions for this before I pull request.

**Comment by wu-sheng** [comment]
You could send a pull request directly. It is fine if more polish could be done.

**Comment by jiang1997** [comment]
Got it.

**Comment by kezhenxu94** [comment]
Closed by apache/skywalking-python#222
