### ISSUE TITLE
[UI] Introduce Network Profiling Widget 

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#9314]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, we have the agent of eBPF. Then we can generate the topology between processes by observing the network. 
I have drawn a prototype diagram to illustrate how the widget would be used in the UI. Please refer to the documentation for details. 
https://docs.google.com/document/d/17MDFgwEGbSEmM0j8TOP80yG4YceboOcwsuUniDJqHi8/edit?usp=sharing

### Use case

When the Service Instance is selected, the user can use this widget to profiling the network topology between processes. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I reopen this to track that our dashboard is not set for network profiling. Pending on @mrproliu
