### ISSUE TITLE
About  annotation org.apache.skywalking.apm.toolkit.trace.Tag

### ISSUE THREAD

**Issue by xzyJavaX** [apache/skywalking#9322]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

Use annotation org.apache.skywalking.apm.toolkit.trace.Tag, for example：
```
@Service
public class DemoService {
    @Tag(key = "kkk", value = "vvv")
    public void tag() {
        //
    }
}   
```
```
@GetMapping("tag")
public String tag() {
    demoService.tag();
    return "tag";
}
```
Access interface “/tag”, key "kkk" will exist，value will be null.
![AF3110CF-2006-45C0-A898-EF87FD4A9F36](https://user-images.githubusercontent.com/49760141/177690342-a29f9118-0183-4c27-8b5e-0e931c8376af.png)
So is this a feature or a bug？
Related documents：https://skywalking.apache.org/docs/skywalking-java/v8.11.0/en/setup/service-agent/java-agent/application-toolkit-trace/

### What you expected to happen

skip

### How to reproduce

Start skywalking APM locall, use the above code to mount skywalking-agent and start it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You need to check data first, whether key value is collected by the agent?

**Comment by wu-sheng** [comment]
And use 9.1 backend and UI if data gets reported.

**Comment by wu-sheng** [comment]
AFAIK, the tag collecting is tested in every PR through

https://github.com/apache/skywalking-java/blob/19dd412b34784d33188819fd11a3b508177df9d0/test/plugin/scenarios/apm-toolkit-trace-scenario/config/expectedData.yaml#L61

**Comment by lujiajing1126** [comment]
I've checked the OAP backend, it just received "null". 

The problem is whether plain text is supported by the `@Tag` annotation. According to the current implementation, only expression is supported.

**Comment by wu-sheng** [comment]
I can't find doc mentioned plain text supported. AKA, it should be not assumed supported.
Then there is no bug.
