### ISSUE TITLE
[Bug] Service tab trend chart

### ISSUE THREAD

**Issue by chopin-d** [apache/skywalking#9324]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

In Dashboard Service Tab, When I choose the whole point time e.g(7:00-8:00), the curve in the trend chart is disordered.
![image](https://user-images.githubusercontent.com/59589401/177722549-22eea898-73d6-45a0-8b49-ef16918f16d7.png)

### What you expected to happen

fixbug

### How to reproduce

In Dashboard Service Tab, When I choose the whole point time e.g(7:00-8:00), the curve in the trend chart is disordered.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Fine0830** [comment]
It seems to be [skywalking-rocketbot-ui](https://github.com/apache/skywalking-rocketbot-ui). Rocketbot UI is replaced by the new [Booster UI](https://github.com/apache/skywalking-booster-ui) since 9.0.0 release.

**Comment by wu-sheng** [comment]
8.x is not maintained anymore. So, we wouldn't take care of this, no matter it is a bug or not.
