### ISSUE TITLE
[Bug]Skywalking-ui:9.1.0 white screen 

### ISSUE THREAD

**Issue by sampsonye** [apache/skywalking#9330]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

Skywalking-ui:9.1.0 white screen 
```
docker run -p 8880:8080 -it apache/skywalking-ui:9.1.0
```

### What you expected to happen

![image](https://user-images.githubusercontent.com/5895634/178134096-f7081de3-b456-485f-ab1a-86a205a892fa.png)
```
app.fa552757.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getTimeInfo')
    at app.fa552757.js:1:99870
    at c (vendors~app.453f44f2.js:42:161777)
    at Generator._invoke (vendors~app.453f44f2.js:42:161530)
    at Generator.next (vendors~app.453f44f2.js:42:162140)
    at r (vendors~app.453f44f2.js:1:10049)
    at s (vendors~app.453f44f2.js:1:10252)
```

### How to reproduce

1. run by docker
```
docker run -p 8880:8080 -it apache/skywalking-ui:9.1.0
```
2. open the browser

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
There is no point if you don't check logs to see something is not working.

**Comment by codecodesam** [comment]
> There is no point if you don't check logs to see something is not working.

我也发生了一样的问题，没有任何错误日志

**Comment by verbunk** [comment]
I have this bug as well. My install is new (k8s / helm) but has been working for a few days with no error.

```
2022-08-10 18:44:58.707  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
8/10/2022 2:44:58 PM 2022-08-10 18:44:58.862  INFO 1 --- [           main] o.a.s.o.s.webapp.ApplicationStartUp      : Started ApplicationStartUp in 7.44 seconds (JVM running for 8.518)

```

It seems to be in the front-end only. Looking into the browser Elements everything seems to load except the app: and the GraphQL query does finish but takes 3-5s.

**Comment by pugwoo** [comment]
I have the sample problem too.

re-produce it:

docker run --name oap --restart unless-stopped -d -e TZ='Asia/Shanghai' -p 11800:11800 -p 12800:12800 apache/skywalking-oap-server:9.1.0

docker run --name oap-ui --restart unless-stopped -d -e TZ='Asia/Shanghai' -e SW_OAP_ADDRESS=http://127.0.0.1:12800 -p 8080:8080 apache/skywalking-ui:9.1.0

and then visit 8080 port

**Comment by ericheshenghao** [comment]
```
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: http://skywalking-oap:12800
```
add the http prefix finally make it

**Comment by iTingle** [comment]
@sampsonye Hi, the same trouble, do you solve it?

**Comment by jinguangshan-oss** [comment]
the same trouble too

**Comment by viccP** [comment]
> ```
>     environment:
>       TZ: Asia/Shanghai
>       SW_OAP_ADDRESS: http://skywalking-oap:12800
> ```
> 
> I add the `http//` prefix finally make it

it's work,I just try
