### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wangyiyong** [apache/skywalking#9343]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

![image](https://user-images.githubusercontent.com/10657084/179128099-1836819a-1cd2-4879-8ece-7c555dd8bd15.png)

At new version 9.1.0    i can't find key words search.   i can use this feature on old version.

### What you expected to happen

i can search log with keywords.

### How to reproduce

1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
It is available on the demo. Maybe something different at your side?

**Comment by wu-sheng** [comment]
And you didn't provide issue title.

**Comment by wangyiyong** [comment]
I found the search label was hidden. And&nbsp; i use&nbsp; mysql to storge log datas. Is this effect?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/skywalking"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月15日(星期五) 上午9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/skywalking] [Bug]  (Issue #9343)





 
It is available on the demo. Maybe something different at your side?

**Comment by wangyiyong** [comment]
sorry! I will be more serious next time !





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/skywalking"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月15日(星期五) 上午9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/skywalking] [Bug]  (Issue #9343)





 
And you didn't provide issue title.

**Comment by wu-sheng** [comment]
MySQL doesn't support content fuzzy search.

**Comment by wu-sheng** [comment]
MySQL could only support tag based query. You need to learn Log Analysis Language to fetch tags from logs contents. Rather than randomly seaeching. MySQL could crash easily in this way.
