### ISSUE TITLE
[Bug] java.sql.SQLSyntaxErrorException: Unknown column '_$_enhanced_class_field_ws' in 'field 

### ISSUE THREAD

**Issue by pennypppp** [apache/skywalking#9357]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

java.sql.SQLSyntaxErrorException: Unknown column '_$_enhanced_class_field_ws' in 'field 

### What you expected to happen

...

### How to reproduce

项目所有方法动态添加@Trace注解后,访问出现代理错误

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This field is added by the agent. If you face conflict, I am afraid this is caused by your ORM component, and you instrumented an ORM object.
This is your manual instrumentation issue.
