### ISSUE TITLE
[Bug] Trace Profiling

### ISSUE THREAD

**Issue by yinbucheng** [apache/skywalking#9364]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

![image](https://user-images.githubusercontent.com/30992273/180115454-7ede6f15-0350-4cc2-ae9a-4bf6f42dfee5.png)

When I use skywalking performance analysis, there is obviously less time in the details
My code is as follows
![image](https://user-images.githubusercontent.com/30992273/180115953-08085c57-2870-4c76-80a7-a349f955d058.png)

The following is the waiting time for log printing
![image](https://user-images.githubusercontent.com/30992273/180115849-0947c442-2a52-4400-b1e0-cafaa42532c1.png)

### What you expected to happen

The time consumption in the list should be consistent with that in the thread stack, and should not be so different

### How to reproduce

code：
![image](https://user-images.githubusercontent.com/30992273/180116083-ecee9e20-46fe-4b63-a761-d5d77c0bf40c.png)
task:
![image](https://user-images.githubusercontent.com/30992273/180116231-9dd27136-bd01-40be-8975-a89f6fd948e5.png)

oap和ui：9.1.0
agent：8.11.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You checked `Yes I am willing to submit a PR!`. Does this mean you know what is happening?

**Comment by wu-sheng** [comment]
You should check the sampling snapshot the agent collected. This should be a good start, https://skywalking.apache.org/docs/main/latest/en/guides/readme/#profile

**Comment by wu-sheng** [comment]
No update after reporting.
