### ISSUE TITLE
[Feature] Monitoring MySQL Server

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

@yswdqz finished his first contribution in https://github.com/apache/skywalking-java/pull/286. This is a huge step for a new contributor. After this, he DM me asking for a new place to continue his contributions to the SkyWalking community.

So, I want to begin a new extension for SkyWalking's monitoring target - **Database server**.

Right now, we have a **Virtual Database** layer to monitor database performance from a tracing perspective(analyzing metrics from database access spans). But Database Server in the topology is not observed directly.

In this new issue, I want to work with @yswdqz and assist him to help on adding MySQL server monitoring in the SkyWalking 9.2 or 9.3 release

### Use case

There are several steps we could follow to do this research and further work

## Background

Unlike tracing relative monitoring, SkyWalking could do observability through a pure metrics ecosystem. Such as, we use OpenTelemetry collector + OpenCensus exporter to monitor Linux and K8s. I prefer we continue this tech stack for MySQL server monitoring.

The dataflow would be `MySQL Server` -> `OpenTelemetry Collector` -> `SkyWalking OpenCensus Receiver` -> `MAL engine`

## Steps
1. Do research about the ways of MySQL server and OpenTelemetry integration. Various blogs such as [this](https://observiq.com/blog/how-to-monitor-mysql-with-opentelemetry/)(just a reference) introduce how this could work.
2. We discuss and pick one possible solution.
3. Learn [MAL](https://skywalking.apache.org/docs/main/latest/en/concepts-and-designs/mal/) and get ideas about how to use MAL to analyze metrics. Could take a look at K8s and Linux monitoring.
4. Discuss which metrics we should do for the MySQL server. We could involve more people in this part, such as ppl from MySQL or ShardingSphere community. I could help with this.
5. Add `MySQL` layer to OAP, and begin to set up dashboards(can't be a menu for now)
6. When all dashboards are ready, we could ask @Fine0830 to help with moving `virtual database` as a sub-menu of general service(So, general service could have two children, services and virtual database). And change the `virtual database` to `Database`, then add `MySQL` as a sub and a root layer.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yswdqz** [comment]
OK, I will do my best to resolve it!

**Comment by yswdqz** [comment]
Please tell me where is the code of K8s and Linux monitoring? I want to take a look.

**Comment by wu-sheng** [comment]
You don't need codes.
MAL is all you need, https://github.com/apache/skywalking/tree/master/oap-server/server-starter/src/main/resources/otel-oc-rules

**Comment by yswdqz** [comment]
I get it.

**Comment by yswdqz** [comment]
Through the blog, I learned how to go from MySQL Server to OpenTelemetry Collector, but I am confused about how to go from OpenTelemetry Collector to SkyWalking OpenCensus Receiver, and I don't know much about SkyWalking OpenCensus Receiver,  Are OpenCensus Receiver and Opentelemetry Receiver (https://skywalking. apache.org/docs/main/latest/en/setup/backend/opentelemetry-receiver/) the same?

**Comment by wu-sheng** [comment]
Yes, Opentelemetry collector has OC exporter for it. 
Take a look at k8s e2e settings. It guides you how it works.

**Comment by yswdqz** [comment]
OK, I will take a look.

**Comment by yswdqz** [comment]
So set the exporters of the OpenTelemetry Collector to OTLP gRPC and set the port to 11800, the data will flow to the SkyWalking OpenCensus Receiver, and then I just need to write the yaml.
Is the idea right?

**Comment by wu-sheng** [comment]
Yes, you are correct.

**Comment by yswdqz** [comment]
I'm trying to configure yaml, but I'm running into a problem: how can I see the final data in oap?

**Comment by wu-sheng** [comment]
What do you mean? The data would be persistent in the database.

**Comment by yswdqz** [comment]
I get it.
I forget the database and trying to see from the UI before.

**Comment by yswdqz** [comment]
I configure the setting of the `opentelemetry-collector` to print metric data in the console, The form of the data is similar to the following:
``` 
Metric #16
Descriptor:
     -> Name: mysql.threads
     -> Description: The state of MySQL threads.
     -> Unit: 1
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
Data point attributes:
     -> kind: STRING(cached)
StartTimestamp: 2022-07-28 01:09:58.7576015 +0000 UTC
Timestamp: 2022-07-28 02:57:07.0609427 +0000 UTC
Value: 0
```
The format provided to me by `MAL doc` is as follows:
```
instance_trace_count{region="us-west",az="az-1"} 100 
```
Maybe the data format will change by the `SkyWalking OpenCensus Receiver`.
But I am confused about when I configure the `metricsRules` by MAL what will the names of these Metrics(such as the `instance_trace_count` of above) I need to call?

**Comment by wu-sheng** [comment]
`instance_trace_count` is the metric family name reported. `mysql.threads` should be renamed to `mysql_threads`, I am guessing.

`OCMetricHandler` should be able to check what you received.

@wankai123 should know more than me about the details.

**Comment by yswdqz** [comment]
OK, I will see it.

**Comment by yswdqz** [comment]
I have a general understanding of `MAL`, and I successfully persisted a part of data to the database.
And I am comfused about the expSuffix, such as the `vm.yaml`：
```
expSuffix: service(['node_identifier_host_name'] , Layer.OS_LINUX)
```
I can understand that the `layer` I should set to `MYSQL` in the future, but how do I understand `service` above?
Is it the entity type of the setting when I new a dashboard, and what should I configure it to be?

**Comment by yswdqz** [comment]
I get it ,I missed this part of the doc at the time.
Now what should I do? Maybe the step 4?

**Comment by wu-sheng** [comment]
You could send a pull request to add Layer to the codes. Then step <4>

**Comment by yswdqz** [comment]
OK, I will try to do it.

**Comment by yswdqz** [comment]
I saw that there is a `DATABASE` layer in the Layer enum. Does it conflict with the `MYSQL` layer?

**Comment by wankai123** [comment]
> I saw that there is a `DATABASE` layer in the Layer enum. Does it conflict with the `MYSQL` layer?

No, doesn't, that's Virtual database

**Comment by yswdqz** [comment]
I get it.

**Comment by yswdqz** [comment]
After reading the commit history of Layer.java, I found that I only need to modify this file (Layer.java) to add the MYSQL layer, without changing any other files or documents?

**Comment by wu-sheng** [comment]
Yes, that is correct.

**Comment by yswdqz** [comment]
OK, I have sent the pr.

**Comment by yswdqz** [comment]
Thank you for your edit, I'm always not rigorous enough. I will do better next time.
Now we should do the step <4>?

**Comment by wu-sheng** [comment]
Yes, let's move on step 4.

**Comment by yswdqz** [comment]
How can I help with this part？

**Comment by wu-sheng** [comment]
What do you mean? Step 4 means you review the otel metrics, and summary a list of metrics meaningfully.
You could refer examples from Gafana/Prometheus or MySQL examples of other APM tools.

**Comment by yswdqz** [comment]
OK, I understand!

**Comment by yswdqz** [comment]
I'm running into a problem. The metric is following:
```
Metric #4
Descriptor:
     -> Name: mysql.buffer_pool.pages
     -> Description: The number of pages in the InnoDB buffer pool.
     -> Unit: 1
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
Data point attributes:
     -> kind: STRING(free)
StartTimestamp: 2022-07-29 16:08:05.723937 +0000 UTC
Timestamp: 2022-07-29 16:08:15.7352765 +0000 UTC
Value: 4161
NumberDataPoints #1
Data point attributes:
     -> kind: STRING(misc)
StartTimestamp: 2022-07-29 16:08:05.723937 +0000 UTC
Timestamp: 2022-07-29 16:08:15.7352765 +0000 UTC
Value: 27
NumberDataPoints #2
Data point attributes:
     -> kind: STRING(data)
StartTimestamp: 2022-07-29 16:08:05.723937 +0000 UTC
Timestamp: 2022-07-29 16:08:15.7352765 +0000 UTC
Value: 4004
```
I want to calculate  `(1 - free pages) / total pages`. So I write the exp `100 - mysql_buffer_pool_pages.tagEqual('kind','free') * 100 / mysql_buffer_pool_pages.sum([])`

This exp can not save any data to database, but use `mysql_buffer_pool_pages.tagEqual('kind','free')`  and 'mysql_buffer_pool_pages.sum([])`' alone will save the data successfully.

I don't know why it will happen, maybe I can not use a data twice in one exp?

**Comment by wu-sheng** [comment]
@wankai123 ☝️

**Comment by wu-sheng** [comment]
In my mind `mysql_buffer_pool_pages.sum([])` would make all labels disappear, how could you create an entity from this MAL exp? SampleFamily is calculated when labels are matched. 

You could re-read this part of doc, https://skywalking.apache.org/docs/main/latest/en/concepts-and-designs/mal/#binary-operators

**Comment by yswdqz** [comment]
Thank you, I understand where I am wrong.
And I change the exp to `100 - mysql_buffer_pool_pages.tagEqual('kind','free').sum([]) * 100 / mysql_buffer_pool_pages.sum([])`
It works successfully now.

**Comment by wu-sheng** [comment]
It works, but logically you can't build an legal entity accordingly. So, label should include the server name/IP to list on service list on the dashboard.

**Comment by yswdqz** [comment]
I get it, I will change it later.

**Comment by yswdqz** [comment]
I am trying to set up the dashboard. Does he have docs? I only find this one(https://skywalking.apache.org/docs/main/latest/en/ui/readme/#custom-dashboard) and it cannot give me enough help.

Also, I think I have some problem with my understanding of Entity type. 
What is the meaning of those enum of Entity type?  And what will I set to the dashboard.

```
service([svc_label1, svc_label2...], Layer) extracts service level labels from the array argument, extracts layer from Layer argument.
```
I also can not understand the first parameter in `service` function in `MAL` . What is the meaning of `service level labels`?

**Comment by wu-sheng** [comment]
That is because you don't have enough hierarchy of how we visualize data.
Try to think in this way
1. We would list service on the dashboard as the first page in menu. How does this list come from if you only use MAL?
2. Metrics have to bind with an entity, service, instance,or endpoint. Then you have to generate one of these according to you metrics labels.

That is why you need to provide label(s) for service function to generate an entity.

Docs actually are helping a little but not much for visualization. The examples are. All the dashboards you can see are good examples to show you the features of today's UI.
 
Usually, service list, aka mysql server list comes first. Then you could dive into one service dashboard with more metrics.

**Comment by wu-sheng** [comment]
> I also can not understand the first parameter in service function in MAL . What is the meaning of service level labels?

Specifically, you need labels value to indicate which service(mysql server) metric you are generating.

**Comment by yswdqz** [comment]
Thank you, I will try it again.

**Comment by yswdqz** [comment]
I'm wondering how the `skywalking UI` finds the service.
I set up a `Service List widget` but has nothing in it.

**Comment by wu-sheng** [comment]
It loads data from service_traffic index through GraphQL API,
https://github.com/apache/skywalking-query-protocol/blob/master/metadata-v2.graphqls#L119


You could check the query with parameters from Browser logs.

**Comment by yswdqz** [comment]
I get it.

**Comment by wu-sheng** [comment]
The service function you asked about in previous discussion would create this metadata.
But you need to make sure the label of name and layer are correct and match your dashboard entity level.

**Comment by yswdqz** [comment]
That's right.
It works successfully after I fix a typo.

**Comment by yswdqz** [comment]
I have configured yaml and set up the dashboard, although I feel that some settings are not very good.
So, what should I do next?

**Comment by wu-sheng** [comment]
>  although I feel that some settings are not very good.

What do you mean? Which parts are not good?

> So, what should I do next?

You could write a long comment here to list all metrics with explanation(what are these metrics for).

**Comment by yswdqz** [comment]
> What do you mean? Which parts are not good?
I feel that in the dashboards I designed, there are some not suitable.
> You could write a long comment here to list all metrics with explanation(what are these metrics for).
OK, I will do it later.

**Comment by wu-sheng** [comment]
> I feel that in the dashboards I designed, there are some not suitable.

You could list your confusion with the metrics. We could discuss it there. If you feel the markdown is not enough for review, I think a google doc is always a good choice.

**Comment by yswdqz** [comment]
When I wrote the doc, I found that there are some metrics mysqlreceiver (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mysqlreceiver) not provided, I plan to use prometheus mysqld exporter to add, is this ok?

**Comment by wu-sheng** [comment]
Yes, sure. Which one could provide more metrics and more clear, it is better.

**Comment by yswdqz** [comment]
I get it, I will adjust the metric I designed.

**Comment by yswdqz** [comment]
I finished the doc.
https://docs.google.com/document/d/1S8c80jvsWft9700xMwJASXFWyCkZlg3XiolAiLndfIk/edit?usp=sharing

**Comment by wu-sheng** [comment]
> I finished the doc. https://docs.google.com/document/d/1S8c80jvsWft9700xMwJASXFWyCkZlg3XiolAiLndfIk/edit?usp=sharing

@tristaZero Could you help with reviewing this doc about MySQL metrics? We are going to provide this on the SkyWalking dashboard. The real server-side monitoring for MySQL server.

**Comment by wu-sheng** [comment]
@yswdqz I need you to grant `comment` access to me.

**Comment by yswdqz** [comment]
OK, I have granted.

**Comment by tristaZero** [comment]
Hello, this design doc looks great basically! Especially Part 1, 2, 3, and 5 is helpful for the end-users. As the first bunch of metrics, I think it's enough and then we could listen to the community's voice to expand them. 
BTW, ShardingSphere acts as a DB server and also has [some metrics](https://github.com/apache/shardingsphere/blob/master/shardingsphere-agent/shardingsphere-agent-plugins/shardingsphere-agent-plugin-metrics/shardingsphere-agent-metrics-prometheus/src/main/resources/prometheus/metrics.yaml) for your reference.
Look forward to this task!

**Comment by yswdqz** [comment]
I get it , Thank you for your help !

**Comment by wu-sheng** [comment]
> I get it , Thank you for your help !

Notice, if you want to continue on new things, ShardingSphere is one another point, after we have MySQL and PostgreSQL server monitoring :)

**Comment by wu-sheng** [comment]
Of course, another thing is adding MySQL server to our showcase.

**Comment by yswdqz** [comment]
I see. I'm resetting the dashboard. After this, I will add the showcase.

**Comment by wu-sheng** [comment]
Don't hurry. Dashboard review would take time. After the dashboard is ready, docs are updated, then we move on showcase repository.

**Comment by yswdqz** [comment]
OK.

**Comment by yswdqz** [comment]
I've set up the Dashboard, what do I need to provide for review?

**Comment by wu-sheng** [comment]
You could open the PR to provide MAL, Dashboard, and document, as well as screenshots.

**Comment by yswdqz** [comment]
Which doc should I change? `docs/en/setup/backend/backend-receivers.md`   and   `CHANGES.md` ?

**Comment by wu-sheng** [comment]
There are several changes you should do

1. Move [Virtual Database](https://skywalking.apache.org/docs/main/latest/en/setup/service-agent/virtual-database/) under general service as a sub menu
2. Add a new [MySQL Database] doc at the place of current Virtual Database.
3. The content of the doc could refer https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-k8s-monitoring/, which should include intro, dataflow, setup, metrics list, and all relative things which would be helpful for end users.

And the document should be pinned and linked at the top of your root dashboard like this,

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/5441976/183091328-8bcee55e-6bf2-4e76-b2a5-5f3fd50c4a1c.png">

**Comment by yswdqz** [comment]
And which folder should I add file to?

**Comment by yswdqz** [comment]
I get it.

**Comment by wu-sheng** [comment]
And then, 

1. https://skywalking.apache.org/docs/main/latest/en/setup/backend/opentelemetry-receiver/ As you are using OC receiver to access the data, the new rule name should be added here.

But what is this? `docs/en/setup/backend/backend-receivers.md`.  Is this an expired doc?

**Comment by yswdqz** [comment]
I see it(docs/en/setup/backend/backend-receivers.md) in the commit of `support k8s monitoring` , maybe is expired.
Anyway, I understand. I'll finish it tomorrow.

**Comment by yswdqz** [comment]
I have sent the PR, https://github.com/apache/skywalking/pull/9432

**Comment by wu-sheng** [comment]
@yswdqz On the showcase, you could add a new feature `mysql`. And use similar ways like e2e did, execute same scripts periodly.

**Comment by yswdqz** [comment]
I get it, I'll try it now.

**Comment by yswdqz** [comment]
@wu-sheng  Should I reuse the vm's opentelemetry collector or create a new one?

**Comment by wu-sheng** [comment]
I think a new one as sidecar(in k8s) would be easier and better in separating feature deployment, right?

@kezhenxu94 WDYT? I think we don't want a dependency between showcase features.

**Comment by kezhenxu94** [comment]
> I think a new one as sidecar(in k8s) would be easier and better in separating feature deployment, right?
> 
> @kezhenxu94 WDYT? I think we don't want a dependency between showcase features.

Yes exactly, please copy the vm monitoring folder and adjust to replicate a MySQL example.

**Comment by yswdqz** [comment]
I get it.

**Comment by yswdqz** [comment]
@wu-sheng 
I've configured the docker section.
But when I configure the kubernetes section, I have a problem about start it. When I run 
`make deploy.kubernetes FEATURE_FLAGS=single-node,mysql`
It will make an error:
```
[root@VM-20-12-centos skywalking-showcase]# make deploy.kubernetes FEATURE_FLAGS=single-node,mysql
make[1]: 进入目录“/skyshowcase/skywalking-showcase/deploy/platform/kubernetes”
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown.
error: no objects passed to apply
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown.
error: no objects passed to apply
```
I think this error is caused by
https://github.com/apache/skywalking-showcase/blob/main/deploy/platform/kubernetes/Makefile#L40.
Because when I change `sh` to `/bin/sh`. It will not cause this error. But pods will always fail to start, such as:
```
oap-deployment-775c856bdb-62s6t              0/1     Pending             0          22m
```
I don't know much about k8s, so I don't know where is the problem.

**Comment by wu-sheng** [comment]
@kezhenxu94 PTAL

**Comment by wu-sheng** [comment]
Do you have a KinD or real k8s env?

**Comment by yswdqz** [comment]
I have a KinD.

**Comment by wu-sheng** [comment]
You could submit a pull request draft, it would be easier to recheck by Zhenxu.

**Comment by yswdqz** [comment]
OK, I have sent the PR, [#63](https://github.com/apache/skywalking-showcase/pull/63)

**Comment by yswdqz** [comment]
But it's more likely a problem with my environment. I have not configured the k8s environment before( I don't know much about k8s, I'm learning it recently.). And I get the same error when I run the unmodified showcase.

**Comment by wu-sheng** [comment]
You need some local kubectl installed, and maybe k9s(tool) to check the logs and status on k8s.

**Comment by yswdqz** [comment]
OK, I will take a try.

**Comment by HHawaii** [comment]
During the monitoring of mysql by skywalking, the receivers are used to configure the Collector's data source. In this case, the receivers grab data from mysqld_exporter of prometheus, Is the terminal address of prometheus configured as mysqld_exporter?
