### ISSUE TITLE
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@c7ee880 java.lang.IllegalStateException: Stream was terminated by error, no further calls are allowed[Bug] 

### ISSUE THREAD

**Issue by EchoCourage** [apache/skywalking#9380]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

启动报错

### What you expected to happen

一些请求被禁用

### How to reproduce

helm默认参数部署
helm install "${SKYWALKING_RELEASE_NAME}" ${REPO}/skywalking -n "${SKYWALKING_RELEASE_NAMESPACE}" --set oap.image.tag=9.1.0 --set oap.storageType=elasticsearch --set ui.image.tag=9.1.0 --set elasticsearch.imageTag=6.8.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Network breaks, nothing related to skywalking.

**Comment by wu-sheng** [comment]
We can't fix from an error stack.
Don't treat us like a customer service.

**Comment by EchoCourage** [comment]
thanks, I'll take a look again.
