### ISSUE TITLE
[Feature] About log collecting and meter(Metrics) reports skywalking-rust.

### ISSUE THREAD

**Issue by jmjoy** [apache/skywalking#9384]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Mentioned in <https://github.com/apache/skywalking/issues/9297#issuecomment-1188532431>, the features of the next version of skywalking-rust.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment]
Is the log collecting means [Span::add_log](https://docs.rs/skywalking/latest/skywalking/context/span/struct.Span.html#method.add_log)? 

If yes, it's already done.

**Comment by wu-sheng** [comment]
No, it isn't. Log collecting mean logs with trace context could be reported through grpc log API. It is less expensive than including in spans. Also, you would be able to search logs without trace ID.

**Comment by jmjoy** [comment]
For logging, I want to implement it by integrate with the tokio log framework [tracing](https://crates.io/crates/tracing), add the grpc subscriber and some filed in log, such as:

```rust
// The GrpcSubscriber implement `tracing::Subscriber`.
let subscriber = skywalking::logging::GrpcSubscriber::new();

tracing::subscriber::set_global_default(subscriber);

let trace_context = create_the_trace_context();

info!("some log", skywalking.ctx = trace_context);
```

Because tracing is not only a log framework, but also a trace framework, so in the future, I want to integrate skywalking Tracer with [tracing](https://crates.io/crates/tracing), like [tracing-opentelemetry](https://crates.io/crates/tracing-opentelemetry).

**Comment by wu-sheng** [comment]
You could create APIs fot native logging/tracing integration, and provide a shell on the APIs for tokio tracing. This would be helpful to set up APIs boundaries.

**Comment by jmjoy** [comment]
Add logging:
https://github.com/apache/skywalking-rust/pull/41

**Comment by jmjoy** [comment]
I have some doubts about metric, where will the metric data be displayed on the UI?

**Comment by wu-sheng** [comment]
> I have some doubts about metric, where will the metric data be displayed on the UI?

Nearly all data on the pages? You need to follow MAL to pre-process metrics

- https://skywalking.apache.org/docs/main/latest/en/concepts-and-designs/mal/
- https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-meter/

**Comment by wu-sheng** [comment]
You could take a look for k8s, virtual machine(linux), and MySQL server monitoring.

**Comment by jmjoy** [comment]
> You could take a look for k8s, virtual machine(linux), and MySQL server monitoring.

:ok_hand:

**Comment by wu-sheng** [comment]
Log APIs - https://github.com/apache/skywalking-rust/pull/41
Metrics APIs - https://github.com/apache/skywalking-rust/pull/44

**Comment by 4t145** [comment]
> For logging, I want to implement it by integrate with the tokio log framework [tracing](https://crates.io/crates/tracing), add the grpc subscriber and some filed in log, such as:
> 
> ```rust
> // The GrpcSubscriber implement `tracing::Subscriber`.
> let subscriber = skywalking::logging::GrpcSubscriber::new();
> 
> tracing::subscriber::set_global_default(subscriber);
> 
> let trace_context = create_the_trace_context();
> 
> info!("some log", skywalking.ctx = trace_context);
> ```
> 
> Because tracing is not only a log framework, but also a trace framework, so in the future, I want to integrate skywalking Tracer with [tracing](https://crates.io/crates/tracing), like [tracing-opentelemetry](https://crates.io/crates/tracing-opentelemetry).

Sorry to bother you but do we have any tokio tracing subscriber layer implemente by now? Is there any hint if I want to intergrate skywallking-rust with tokio tracing?

**Comment by wu-sheng** [comment]
> > For logging, I want to implement it by integrate with the tokio log framework [tracing](https://crates.io/crates/tracing), add the grpc subscriber and some filed in log, such as:
> > ```rust
> > // The GrpcSubscriber implement `tracing::Subscriber`.
> > let subscriber = skywalking::logging::GrpcSubscriber::new();
> > 
> > tracing::subscriber::set_global_default(subscriber);
> > 
> > let trace_context = create_the_trace_context();
> > 
> > info!("some log", skywalking.ctx = trace_context);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Because tracing is not only a log framework, but also a trace framework, so in the future, I want to integrate skywalking Tracer with [tracing](https://crates.io/crates/tracing), like [tracing-opentelemetry](https://crates.io/crates/tracing-opentelemetry).
> 
> Sorry to bother you but do we have any tokio tracing subscriber layer implemente by now? Is there any hint if I want to intergrate skywallking-rust with tokio tracing?

What is that tracing doing? If it only does pure tracing such as Zipkin, I am afraid, that is not enough for SkyWalking's requirements.

**Comment by 4t145** [comment]
Tokio [tracing](https://crates.io/crates/tracing) is the most widely used trace framework in the Rust world. I'am not demand that the crate [skywalking-rust](https://github.com/jmjoy/skywalking-rust) to support tokio tracing. I ask because the creator of this issue [jmjoy](https://github.com/jmjoy) mentioned that he was thinking about to integrate crate [skywalking-rust](https://github.com/jmjoy/skywalking-rust) with tokio tracing there like what [tracing-opentelemetry](https://crates.io/crates/tracing-opentelemetry) (maybe it's a new crate named `tracing-skywalking`) do. Since opentelemetry has been well supported in tokio traicng I wonder if there is the same thing in skywalking.

**Comment by wu-sheng** [comment]
> Tokio [tracing](https://crates.io/crates/tracing) is the most widely used trace framework in the Rust world. I'am not demanding that the crate [skywalking-rust](https://github.com/jmjoy/skywalking-rust) to support tokio tracing. I ask because the creator of this issue [jmjoy](https://github.com/jmjoy) mentioned that he was thinking about to integrate crate [skywalking-rust](https://github.com/jmjoy/skywalking-rust) with tokio tracing there like what [tracing-opentelemetry](https://crates.io/crates/tracing-opentelemetry) do (maybe it's a new crate named `tracing-skywalking`). Since opentelemetry has been well supported in tokio traicng I wonder if there is the same thing in skywalking.

That is a new thing. But at least, this is not a thing we discussed here.
