### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MrJXL** [apache/skywalking#9386]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

![image](https://user-images.githubusercontent.com/17782002/181018473-de4df17f-e90b-4ce9-83e8-b68c5155cb0b.png)
When I use RunnableWrapper.of() tracks the link. There will be two identical endpoints under the trace. Skywalking version 9.1.0

### What you expected to happen

I want to delete the endpoint beginning with Thread/org.apache.skywalking.apm.toolkit.trace.RunnableWrapper/run

### How to reproduce

use RunnableWrapper.of()

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No title.
