### ISSUE TITLE
[Bug] v9.1.0 Redis in Topogy always not show as technology icon but a question mark ,

### ISSUE THREAD

**Issue by StreamLang** [apache/skywalking#9404]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

In Skywalking Java , Lettuc or Jedis Plugin span is SpanLayer.Cache;
but in OAP, when OAP analysis from SpanLayer to layer (RPCAnalysisListener#identifyRemoteServiceLayer), it will be Layer.CACHE(9,true);
because of Filed "isNormal" is true,  when gen ServiceID  ,"isReal" will be true, so graphQL result will be null. 
Redis Node won't  show as his technology icon

### What you expected to happen

maybe add a VIRTUAL_CACHE like VIRTUAL_DATABASE to Layer 

### How to reproduce

start up OAP v.9.1.0 release version ,  and use java-agent v8.11.0 , java app use lettuce connect to redis, 
will see question mark in topology , redis node.

### Anything else

..

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Yes, `VIRTUAL_CACHE` makes sense, please submit a pull request with screenshots(before/after) to verify the topology is back to normal.

**Comment by wu-sheng** [comment]
@StreamLang Are you going to submit a pull request to fix this?

**Comment by StreamLang** [comment]
> @StreamLang Are you going to submit a pull request to fix this?
yes , PR will be submitted today
