### ISSUE TITLE
[Bug] Docker images for docker-compose are incorrect.

### ISSUE THREAD

**Issue by ericrdgz** [apache/skywalking#9427]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I cloned the respository and attempted to run the docker-compose file which errors due to the images not existing that are specified in the .env file.

the docker/.env file needs to change to the following. The lines in bold being what needs changing.

ES_VERSION=7.4.2
**OAP_IMAGE=apache/skywalking-oap-server:latest**
**UI_IMAGE=apache/skywalking-ui:latest**

### What you expected to happen

The issue is erroneous because the docker-compose file does not work as it is. Which me being new to Skywalking and wanting to take it for a local test run, meant I had to troubleshoot the error for 30 minutes.

### How to reproduce

Run the docker-compose file as is.

### Anything else

issue will happen for any user who is trying to run the docker-compose file that is currently on latest master branch

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Could you send a pull request to specify the changes?

**Comment by kezhenxu94** [comment]
The docker compose is meant to be used after a local build. If you wan to use it with latest released Docker images, you should export the two env vars before running docker-compose up, not modifying the .env file
