### ISSUE TITLE
[Feature] Support for Micronaut plugin

### ISSUE THREAD

**Issue by pg-yang** [apache/skywalking#9429]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The first step is support    [ Micronaut Server Application](https://docs.micronaut.io/latest/guide/#creatingServer) and [Micronaut Client](https://docs.micronaut.io/latest/guide/#creatingClient)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pg-yang** [comment]
```
endTo receive actual data
To validate
[2022-08-08 15:06:30:826] [ERROR] - org.apache.skywalking.plugin.test.agent.tool.Main.verify(Main.java:53) - 
assert failed.
SegmentNotFoundException:
expected: 
  Segment:
  - span[-1, 0] GET:/micronaut/success

actual: 
  Segment[52b9160c868a4b7a95852f01acd16b25.37.16599711821650000] e
  expected:     Span[-1, 0] GET:/micronaut/success
  actual:       span[-1, 0] HEAD:/micronaut/healthCheck
  reason:       [operation name]: expected=>{GET:/micronaut/success}, actual=>{HEAD:/micronaut/healthCheck}

  Segment[52b9160c868a4b7a95852f01acd16b25.41.16599711841430000] e
  expected:     Span[-1, 0] GET:/micronaut/success
  actual:       span[-1, 0] GET:/micronaut/success
  reason:       [tag(url) value]: expected=>{/micronaut/success}, actual=>{http://localhost:8080/micronaut/success}


  Segment[52b9160c868a4b7a95852f01acd16b25.44.16599711842720000] e
  expected:     Span[-1, 0] GET:/micronaut/success
  actual:       span[-1, 0] GET:/micronaut/404
  reason:       [operation name]: expected=>{GET:/micronaut/success}, actual=>{GET:/micronaut/404}

  Segment[52b9160c868a4b7a95852f01acd16b25.48.16599711847720000] e
  expected:     Span[-1, 0] GET:/micronaut/success
  actual:       span[-1, 0] GET:/micronaut/error
  reason:       [operation name]: expected=>{GET:/micronaut/success}, actual=>{GET:/micronaut/error}

```
My test-scenario is a web server , it accept healthy check request and test request .
When I run my test-scenario , I got above error .It seems like Plugin automatic test framework compare healthy check request with test request
Is there some way to ignore healthy-check-url when comparing segment info ? Or some other reason cause this problem ?

**Comment by wu-sheng** [comment]
This is the issue. URI GET:/micronaut/success is checked, but fails, because tag doesn't match.

**Comment by pg-yang** [comment]
I misunderstood the report message . Haha

> This is the issue. URI GET:/micronaut/success is checked, but fails, because tag doesn't match.
