### ISSUE TITLE
[Testing] Check goroutines leak for testing 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9454]
### Description

Introduce https://onsi.github.io/gomega/#codegleakcode-finding-leaked-goroutines to check leaked goroutines after running UTs in below packages:

- [x] #9458 
- [x] #9459 
- [x] #9460 
- [x] #9461 
- [x] #9462 
- [x] #9463 
- [x] #9957

**Comment by mikechengwei** [comment]
Plz assign this issue to me.

**Comment by hanahmily** [comment]
@mikechengwei Do you still work on this?

**Comment by mikechengwei** [comment]
> @mikechengwei Do you still work on this?

I'm sorry, I'm busy with work recently, I will continue to do it.

**Comment by hanahmily** [comment]
> > @mikechengwei Do you still work on this?
> 
> I'm sorry, I'm busy with work recently, I will continue to do it.

All right, take your time. You had better sync with upstream before diving into it. We changed largely this month.

**Comment by hanahmily** [comment]
@mikechengwei. FYI, https://github.com/apache/skywalking/issues/9463 is assigned to @zeusbee.

**Comment by mikechengwei** [comment]
> Thank you. @mikechengwei. Your perseverance makes this long-term task happen.

Thanks for trust，i hope that can help to complete more meaningful problems.
