### ISSUE TITLE
[Testing] Fix stream's leaked goroutines

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9460]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This is a sub-task of https://github.com/apache/skywalking/issues/9454 to fix leaked goroutines in the stream package

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mikechengwei** [comment]
I can finish it, can assign to me ?

**Comment by mikechengwei** [comment]
Solve pr ref:https://github.com/apache/skywalking-banyandb/pull/214
