### ISSUE TITLE
[Document] Add BanyanDB User Guide

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9467]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In this doc, we should illustrate how to set up the BanyanDB server with other components of SkyWalking:

* Onboard BanyanDB server
* Set up OAP to connect this server
* Provide a demo to send data to the backend.
* Show the results on the UI.

After reading this guide, users could learn how to onboard a SkyWalking service empowered by BanyanDB. We should also provide various artifacts deployment methods: official binary package and a docker image. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We have quick start for this.
