### ISSUE TITLE
[Bug] xxl-job 2.3.x version not support

### ISSUE THREAD

**Issue by BigXin0109** [apache/skywalking#9470]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

use  xxl-job  version: 2.3.0 ,  plugin: apm-xxl-job-2.x-plugin  not support.

### What you expected to happen

logback  tid is N/A 

2022-08-14 14:48:04.249 INFO  TID:N/A Thread-82 c.x.j.e.s.jobhandler.SampleXxlJob: demoJobHandler beat at:0
2022-08-14 14:48:06.253 INFO  TID:N/A Thread-82 c.x.j.e.s.jobhandler.SampleXxlJob: demoJobHandler beat at:1
2022-08-14 14:48:08.257 INFO  TID:N/A Thread-82 c.x.j.e.s.jobhandler.SampleXxlJob: demoJobHandler beat at:2
2022-08-14 14:48:10.261 INFO  TID:N/A Thread-82 c.x.j.e.s.jobhandler.SampleXxlJob: demoJobHandler beat at:3
2022-08-14 14:48:12.266 INFO  TID:N/A Thread-82 c.x.j.e.s.jobhandler.SampleXxlJob: demoJobHandler beat at:4

### How to reproduce

demo: https://github.com/xuxueli/xxl-job/tree/2.3.0/xxl-job-executor-samples/xxl-job-executor-sample-springboot
add maven :
```
<dependency>
    <groupId>org.apache.skywalking</groupId>
    <artifactId>apm-toolkit-logback-1.x</artifactId>
    <version>8.11.0</version>
</dependency>
```
logback.xml:
```
<encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
    <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
        <!-- 日志格式中添加 %tid 即可输出 trace id -->
        <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %tid %t %logger{36}: %msg%n</pattern>
    </layout>
</encoder>
```
demo:  com.xxl.job.executor.service.jobhandler.SampleXxlJob#demoJobHandler
```
    /**
     * 1、简单任务示例（Bean模式）
     */
    @XxlJob("demoJobHandler")
    public void demoJobHandler() throws Exception {
        XxlJobHelper.log("XXL-JOB, Hello World.");
        for (int i = 0; i < 5; i++) {
            XxlJobHelper.log("beat at:" + i);
            logger.info("demoJobHandler beat at:{}", i);
            TimeUnit.SECONDS.sleep(2);
        }
        // default success
    }
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Version not supported is not a bug. If you want to add more, a pull request is welcome.

**Comment by leon756** [comment]
@BigXin0109 This may be helpful for you:
https://github.com/leon756/skywalking/tree/v8.7.0-xxl-job-2.3-plugin
