### ISSUE TITLE
[Feature] Support multiple MySQL instances as a sharding cluster powered by ShardingSphere.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9477]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

As ShardingSphere provides a new DistSQL concept recently, it gives us an opportunity to evaluate whether it is good enough to create dynamic routing rules automatically.

SkyWalking creates new tables(in MySQL and PostgreSQL) according to metrics definition based on MAL and OAL, the traditional configuration file based sharding is not suitable for us.

Also, we need to use `hint` mechanism to try to implement TTL deleting through `truncate`, rather than the heavy `delete`.

### Use case

Support Sharding and Time-series based rolling for metrics/logs/traces/events/profiling telemetry data in SkyWalking

### Related issues

Doc of ShardingSphere, https://shardingsphere.apache.org/document/5.1.2/en/reference/distsql/syntax/rdl/rule-definition/sharding/create-default-sharding-strategy/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tristaZero** [comment]
Hello, it looks cool. ;-) 
Sure, [ShardingSphere](https://shardingsphere.apache.org/) not only provides the DistSQL(SQL-Like) to manage your distributed or sharding DB and table but makes itself more cloud-native on K8S by providing an [operator](https://medium.com/codex/database-plus-embracing-the-cloud-shardingsphere-on-cloud-solution-released-29916290ad06).

**Comment by wu-sheng** [comment]
MySQL-Sharding is supported since 9.3.0, ref https://skywalking.apache.org/docs/main/next/en/setup/backend/backend-storage/#mysql-sharding

We are working with ShardingSphere community to expand better compatibility, because right now, this feature is only working with 5.1.2 release, but fails in 5.2.0 and 5.2.1

A blog would be posted to provide more introduction after SkyWalking's 9.3.0 release.
