### ISSUE TITLE
[Feature] Enhance the legend of metrics graph widget with the summary table

### ISSUE THREAD

**Issue by Fine0830** [apache/skywalking#9483]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Enhance the legend of metrics graph widget with the summary table.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If this is for the single value type, this could be a configuration rather than a widget. The summary table is an attachment to activate.

**Comment by wu-sheng** [comment]
When we use this labeled value, we should provide a policy such as `order by` + `top n` in the summary table.
