### ISSUE TITLE
[Feature] Support for NATS Java client Plugin

### ISSUE THREAD

**Issue by pg-yang** [apache/skywalking#9487]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have supported Micronaut . And I discover Micronaut support [NATS](https://docs.nats.io/) as message system . 
So , I want to try implementing [NATS Java Client ](https://github.com/nats-io/nats.java)agent plugin   . And I will put the plugin to `optional-plugins` module.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> I will put the plugin to optional-plugins module.

Could you explain why this should be in `optional`? Is that able to hurt the application somehow? Or trigger some conflicts?

**Comment by pg-yang** [comment]
> > I will put the plugin to optional-plugins module.
> 
> Could you explain why this should be in `optional`? Is that able to hurt the application somehow? Or trigger some conflicts?

I think it's not commonly used .Your suggestion ?

**Comment by wu-sheng** [comment]
If this is only targeting NATS client's classes(such as under `io.nats.client.*` only), the agent would not make it work automatically.
About the optional plugins, https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/optional-plugins/, you could notice all plugins have their own reasons to be optional only, as they may have a side-effect.

**Comment by pg-yang** [comment]
Got it . I will choose appropriate  module
