### ISSUE TITLE
[Feature] contrl trace by manually

### ISSUE THREAD

**Issue by taotao365s** [apache/skywalking#9489]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I want to control the trace by manually.  I just found there is function  in the SOFA-tracer, so I can contrl the trace.

````
public class DemandThread extends Thread {
        @Override
        public void run() {
            
            //TODO how can we reset new Trace, but not in original trace in before.
            
            while (true) {
                
                //do something.

                try {
                    Thread.sleep(1000 * 20);
                } catch (InterruptedException e) {
                    log.error("error", e);
                }
            }

        }
    }
````

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You have submitted on discussion, don't create noice.
