### ISSUE TITLE
[Feature] Optimize the configuration to make it easier to add, delete or change

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9506]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Create a new template service(GraphQL) to provide menu structure in JSON with hierarchy structure, carrying menu name, and layer name if it is a leaf menu.

### Use case

To avoid we have to change the UI codes repeatedly to add new features. We current accepted many new features which required new menu items to add.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Fine0830** [comment]
Let's keep the menu configuration in UI. I will optimize the configuration to make it easier to add, delete or change.
