### ISSUE TITLE
[Bug] Fix dependency license's NOTICE and binary jar included issues in the source release.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9512]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

We received reports from incubator discussion

```
So taking a quick look at a SkyWalking release [1] I can see a couple of minor issues with LICNSE and NOTICE. You may want to fix these.

Hints:
Is OpenCensus mentioned in LICENSE?
Does prometheus client_model have a NOTICE file?
Does mavin-wrapper have a NOTICE file?

Also there is a compiled code (a jar) in the source release. Source release cannot include compiled code.

Kind Regards,
Justin

1. https://www.apache.org/dyn/closer.cgi/skywalking/9.1.0/apache-skywalking-apm-9.1.0-src.tgz <https://www.apache.org/dyn/closer.cgi/skywalking/9.1.0/apache-skywalking-apm-9.1.0-src.tgz>

```

### What you expected to happen

We should remove the jar file from the source tar.

### How to reproduce

Just repackage the v9.1.0 tag for a source release.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
hi, according to AL2, we also need to add the corresponding NOTICE. 
![image](https://user-images.githubusercontent.com/16631152/186118579-a295af11-b954-47d4-a1c9-3a66df853e36.png)

**Comment by wu-sheng** [comment]
Yes, we should add. Some tiny issues are fine :) Just make this as good as possible.

**Comment by wu-sheng** [comment]
I found the jar file introduced by `mvnw` run once in the packaging process. @kezhenxu94 confirmed it is about the version number.

https://github.com/apache/skywalking/blob/77ba2d553d77a4acacd8b2498cb09ea983a9baf4/tools/releasing/create_source_release.sh#L63-L65

**Comment by CalvinKirs** [comment]
> I found the jar file introduced by `mvnw` run once in the packaging process. @kezhenxu94 confirmed it is about the version number.
> 
> https://github.com/apache/skywalking/blob/77ba2d553d77a4acacd8b2498cb09ea983a9baf4/tools/releasing/create_source_release.sh#L63-L65

It will be downloaded automatically when we run ./mvnw, so we need to exclude it
