### ISSUE TITLE
[Feature] Update jedis plugin to support jedis 3.x 4.x

### ISSUE THREAD

**Issue by pg-yang** [apache/skywalking#9534]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The latest jedis is 4.x . The current `jedis-scenario` is support jedis 3.9 , It passed my preliminary tests
I will rename `jedis-2.x-plugin` to `jedis-2.x-3.x-plugin` if it work right on 3.9 (need more test)  .And add a new module`jedis-4.x-plugin` 
Of course , if `jedis-2.x-plugin` needs very little modification it can support 4.x , I will not add new module. This depends on code  compatibility

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pg-yang** [comment]
Oh, I forget `Streams` command .  I will test the command . And reconstruct these code , put  appropriate code to appropriate  module.

**Comment by wu-sheng** [comment]
> I will rename jedis-2.x-plugin to jedis-2.x-3.x-plugin if it work right on 3.9 (need more test) .And add a new modulejedis-4.x-plugin

If you need to add a new plugin for 4.x, then 2.x-3.x plugin may need to add witness classes to make sure both of these plugins existing in the default folder.

**Comment by pg-yang** [comment]
Got it , I'll tell you about the module details first , then start coding  .

**Comment by pg-yang** [comment]
Update  
### module :

```
-- jedis-plugins
---- jedis-2.x-3.x-plugin
---- jedis-4.x-plugin
---- jedis-2.x-4.x-commons

```

* `jedis-2.x-4.x-commons`  include common  method ,class  , or interceptor class
`jedis-2.x-3.x-plugin` This module rename from `jedis-2.x-plugin` .  Update jedis dependency to 3.9.0 , and support stream command  .  It work with  `jedis-2.x-4.x-commons` togther . Notice witness classes 
* ` jedis-4.x-plugin` The main goal is to accommodate the jedis API  , Also work with  `jedis-2.x-4.x-commons` togther . Notice witness classes 


### test-scenario
* jedis-2.x-scenario .  Rename from `jedis-scenario` . The code doesn't change
* jedis-3.x-scenario  . include base command test( same as ` jedis-2.x-scenario`) , add  stream command test
* jedis-4.x-scenario . Same as ` jedis-3.x-scenario`

**Comment by wu-sheng** [comment]
Generally good

> jedis-2.x-4.x-commons include common method ,class , or interceptor class

I think this could be `jedis-commons`? What classes exactly in the common plugin?

**Comment by pg-yang** [comment]
I want put  interceptor class to this module . I don't guarantee  this module  can't  apply to jedis 5.x  in  future . 
The future-man  should notice it .

**Comment by wu-sheng** [comment]
Make sense.

**Comment by wu-sheng** [comment]
Are you going to submit this soon? I plan to release 8.12.0 recently.

**Comment by pg-yang** [comment]
Should be done at this weekend .
