### ISSUE TITLE
[Feature] Remove  inappropriate dependency  from  elasticsearch-7.x-plugin 

### ISSUE THREAD

**Issue by pg-yang** [apache/skywalking#9540]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

First , every  plugin  should  be  independent  . Right  ?
`elasticsearch-7.x-plugin` depend  on ` elasticsearch-6.x-plugin` , it reference  some constant  , config class  from 6.x .
So,   we should  remove  the dependency  .  I want  to  copy these  constant , config class from 6.x  rather  than  create  a common  module , Because the code is little  .

https://github.com/apache/skywalking-java/blob/92665b8add7020f26f67519a6e6c7fef49e42643/apm-sniffer/apm-sdk-plugin/elasticsearch-7.x-plugin/pom.xml#L45

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Ideally, yes, we shoud keep them independent, unless they share some commons package.

**Comment by wu-sheng** [comment]
Are you going to submit this soon? I plan to release 8.12.0 recently.

**Comment by pg-yang** [comment]
no problem , tonight at the latest
