### ISSUE TITLE
[Bug] error 500 with zipkin receiver

### ISSUE THREAD

**Issue by etchevef** [apache/skywalking#9547]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I have 2 java applications (one in tomcat, one in weblogic) with the opentelemetry java agent (https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#exporters), which is exporting traces to skywalking in zipkin mode (-Dotel.traces.exporter=zipkin). 

The zipkin-receiver is activated in skywalking, but it returns an error 500 instead of storing the traces.

### What you expected to happen

Skywalking should have accepted the traces, same as it does in zipkin (it works both with zipkin and the zipkin port in jaeger), instead we get the following error in skywalking-oap-server.log :

[bug_zipkin_receiver.log](https://github.com/apache/skywalking/files/9461285/bug_zipkin_receiver.log)

### How to reproduce

I am using skywalking 9.1, and the opentelemetry java agent 1.17. None of the metrics works, with both application, so any application should work. 
Javaagent configuration is : 
CATALINA_OPTS="$CATALINA_OPTS -Dotel.service.name=tomcat-2 -Dotel.traces.exporter=zipkin -Dotel.exporter.zipkin.endpoint='http://x.x.x.x:9412/api/v2/spans' -Dotel.metrics.exporter=none -javaagent:/opt/tomcat/opentelemetry-javaagent.jar"
(port is deliberately incremented to 9412 (zipkin-receiver) and 9413 (zipkin-querry) because 9411 is already used)

I have attempted multiple zipkin-receiver configurations, currently it is : 
receiver-zipkin:
  selector: ${SW_RECEIVER_ZIPKIN:default}
  default:
    # For HTTP server
    searchableTracesTags: ${SW_ZIPKIN_SEARCHABLE_TAG_KEYS:http.method}
    sampleRate: ${SW_ZIPKIN_SAMPLE_RATE:10000}
    enableHttpCollector: ${SW_ZIPKIN_HTTP_COLLECTOR_ENABLED:true}
    restHost: ${SW_RECEIVER_ZIPKIN_REST_HOST:0.0.0.0}
    restPort: ${SW_RECEIVER_ZIPKIN_REST_PORT:9412}
    restContextPath: ${SW_RECEIVER_ZIPKIN_REST_CONTEXT_PATH:/}
    restMaxThreads: ${SW_RECEIVER_ZIPKIN_REST_MAX_THREADS:200}
    restIdleTimeOut: ${SW_RECEIVER_ZIPKIN_REST_IDLE_TIMEOUT:30000}
    restAcceptQueueSize: ${SW_RECEIVER_ZIPKIN_REST_QUEUE_SIZE:0}
    # The sample rate precision is 1/10000, should be between 0 and 10000
    enableKafkaCollector: ${SW_ZIPKIN_KAFKA_COLLECTOR_ENABLED:false}

query-zipkin:
  selector: ${SW_QUERY_ZIPKIN:default}
  default:
    # For HTTP server
    restHost: ${SW_QUERY_ZIPKIN_REST_HOST:0.0.0.0}
    restPort: ${SW_QUERY_ZIPKIN_REST_PORT:9413}
    restContextPath: ${SW_QUERY_ZIPKIN_REST_CONTEXT_PATH:/zipkin}
    restMaxThreads: ${SW_QUERY_ZIPKIN_REST_MAX_THREADS:200}
    restIdleTimeOut: ${SW_QUERY_ZIPKIN_REST_IDLE_TIMEOUT:30000}
    restAcceptQueueSize: ${SW_QUERY_ZIPKIN_REST_QUEUE_SIZE:0}
    # Default look back for serviceNames, remoteServiceNames and spanNames, 1 day in millis
    lookback: ${SW_QUERY_ZIPKIN_LOOKBACK:86400000}
    # The Cache-Control max-age (seconds) for serviceNames, remoteServiceNames and spanNames
    namesMaxAge: ${SW_QUERY_ZIPKIN_NAMES_MAX_AGE:300}
    ## The below config are OAP support for zipkin-lens UI
    # Default traces query max size
    uiQueryLimit: ${SW_QUERY_ZIPKIN_UI_QUERY_LIMIT:10}
    # Default look back for search traces, 15 minutes in millis
    uiDefaultLookback: ${SW_QUERY_ZIPKIN_UI_DEFAULT_LOOKBACK:900000}

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This seems a bug when there is no `remoteEndpoint`, ref from 

https://github.com/apache/skywalking/blob/f1f519cae469f2f3d9e3b8f81648b80536090444/oap-server/server-receiver-plugin/zipkin-receiver-plugin/src/main/java/org/apache/skywalking/oap/server/receiver/zipkin/trace/SpanForward.java#L69

Errors in logs
```
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.receiver.zipkin.trace.SpanForward.lambda$send$0(SpanForward.java:69) ~[zipkin-receiver-plugin-9.1.0.jar:9.1.0]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_332]
	at org.apache.skywalking.oap.server.receiver.zipkin.trace.SpanForward.send(SpanForward.java:52) ~[zipkin-receiver-plugin-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.receiver.zipkin.handler.ZipkinSpanHTTPHandler.lambda$doCollectSpans$0(ZipkinSpanHTTPHandler.java:119) ~[zipkin-receiver-plugin-9.1.0.jar:9.1.0]
```

**Comment by wu-sheng** [comment]
@etchevef Would you like to add a `not null` check to `span.localEndpoint()` before getting `ipv4`/`ipv6`, and test again locally?

**Comment by wu-sheng** [comment]
This should be fixed through https://github.com/apache/skywalking/pull/9252 in the 9.2.0.

The release should be available on Friday, and the tag exists already.
