### ISSUE TITLE
[Feature] Monitoring MySQL's Slow SQL

### ISSUE THREAD

**Issue by yswdqz** [apache/skywalking#9548]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

MySQL supports recording the slow SQL statement to the log file, we can monitor this file, so that we can analyze the slow query situation of MySQL.

### Step

1.Extend LAL to convert LogData into DatabaseSlowStatement for subsequent analysis.
2.Use fluent-bit to monitor MySQL's log file, and send data to OAP via http.
3.Edit the UI to display the data.
4.Add showcase and E2E test.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yswdqz** [comment]
What should I set the `traceId` and `Id` of the `TopNDatabaseStatement`?
Followings are the log of MySQL:
```
mysqld, Version: 5.7.18 (MySQL Community Server (GPL)). started with:
Tcp port: 3306  Unix socket: /var/run/mysqld/mysqld.sock
Time                 Id Command    Argument
# Time: 2022-08-25T12:12:17.282398Z
# User@Host: root[root] @  [175.172.57.107]  Id:     4
# Query_time: 10.000410  Lock_time: 0.000000 Rows_sent: 1  Rows_examined: 0
SET timestamp=1661429537;
SELECT sleep(10);
# Time: 2022-08-25T12:28:44.460038Z
# User@Host: root[root] @  [175.172.57.107]  Id:     4
# Query_time: 60.001244  Lock_time: 0.000344 Rows_sent: 6  Rows_examined: 6
use sys;
SET timestamp=1661430524;
SELECT sleep(10),variable from sys_config;
```

**Comment by wu-sheng** [comment]
For the trace ID , I don't think you would have that. 
ID should be encoded in the TopNDatabaseStatement, could you check the source codes?

**Comment by yswdqz** [comment]
The ID is generate by traceId and spanId, such as following:
```
slowStatementBuilder.setId(segmentObject.getTraceSegmentId() + "-" + span.getSpanId());
```

**Comment by wu-sheng** [comment]
I see, the thid should be changed as a generated ID if segmentID and spanID absent.

**Comment by yswdqz** [comment]
Does thid mean thread id?

**Comment by wu-sheng** [comment]
No, ID is required to be globally unique. Is there anything specific isourceoriginal data? Or could the agent fill a UUID tag for every row of data?

**Comment by yswdqz** [comment]
I get it. May be need to generate a UUID.

**Comment by wu-sheng** [comment]
It is better if the agent could generate this ID, and OAP just uses it in the LAL.

**Comment by yswdqz** [comment]
I am confused about the `latency` of TopNRecord.java , is It the query time of SQL statement? And what is it unit?

**Comment by yswdqz** [comment]
I have saved records to table "TopNStatement". but when I want to show this metric("TopNStatement") in UI, it still has no data. Need I do something else to show them in UI?

**Comment by wu-sheng** [comment]
> I am confused about the `latency` of TopNRecord.java , is It the query time of SQL statement? And what is it unit?

Latency should be SQL execution time.

**Comment by wu-sheng** [comment]
> I have saved records to table "TopNStatement". but when I want to show this metric("TopNStatement") in UI, it still has no data. Need I do something else to show them in UI?

Which metric name do you use? It should be as same as OAL declared.

**Comment by yswdqz** [comment]
> > I have saved records to table "TopNStatement". but when I want to show this metric("TopNStatement") in UI, it still has no data. Need I do something else to show them in UI?
> 
> Which metric name do you use? It should be as same as OAL declared.

No, I want to use the TopNStatement metric which declared by OAP. I am already save data in the table `TopNStatement`.What else should I do?

**Comment by yswdqz** [comment]
> > I am confused about the `latency` of TopNRecord.java , is It the query time of SQL statement? And what is it unit?
> 
> Latency should be SQL execution time.

Is his unit ms？I saw that its datatype is bigint.

**Comment by wu-sheng** [comment]
> > > I am confused about the `latency` of TopNRecord.java , is It the query time of SQL statement? And what is it unit?
> 
> > 
> 
> > Latency should be SQL execution time.
> 
> 
> 
> Is his unit ms？I saw that its datatype is bigint.

Yes, it is ms.

**Comment by wu-sheng** [comment]
> > > I have saved records to table "TopNStatement". but when I want to show this metric("TopNStatement") in UI, it still has no data. Need I do something else to show them in UI?
> 
> > 
> 
> > Which metric name do you use? It should be as same as OAL declared.
> 
> 
> 
> No, I want to use the TopNStatement metric which declared by OAP. I am already save data in the table `TopNStatement`.What else should I do? 

You could go to virtual database dashboard, check the configuration of slow SQL list. Yours should be the same.

**Comment by yswdqz** [comment]
I understand.

**Comment by wu-sheng** [comment]
@yswdqz How is your side work? Are things working as expected?

**Comment by yswdqz** [comment]
> @yswdqz How is your side work? Are things working as expected?

Everything is OK, I am writing the e2e. And I will sent the PR tomorrow.
Is it OK that I just set the slow statement there?
![image](https://user-images.githubusercontent.com/74546965/188673102-453663e6-fdca-406b-863f-64ec68e10ea5.png)

**Comment by wu-sheng** [comment]
I think you could use a tab widget? Metrics dashboard as tab 1, slow SQLs as tab2?

**Comment by yswdqz** [comment]
Is that OK?
![image](https://user-images.githubusercontent.com/74546965/188683456-5bec7080-da5f-4b62-9b73-086ab723b5a1.png)
![image](https://user-images.githubusercontent.com/74546965/188683487-626f974d-9833-4f68-8d1b-ed3359409279.png)

**Comment by wu-sheng** [comment]
The first tab name should be inspection.(metrics are only what they are)
The second is fine. 

BTW, do you plan to update slow statements docs on the same doc page?

**Comment by yswdqz** [comment]
> The first tab name should be inspection.(metrics are only what they are) The second is fine.

OK, I have changed it.

> BTW, do you plan to update slow statements docs on the same doc page?

I will do it tomorrow.

**Comment by wu-sheng** [comment]
> > The first tab name should be inspection.(metrics are only what they are) The second is fine.
> 
> 
> 
> OK, I have changed it.
> 
> 
> 
> > BTW, do you plan to update slow statements docs on the same doc page?
> 
> 
> 
> I will do it tomorrow.
 
OK, I just ask, then we don't need a new link to another doc.

**Comment by wu-sheng** [comment]
Please send MAL enhancement PR separately. It is not hard relative with this slow SQL feature.

**Comment by yswdqz** [comment]
> Please send MAL enhancement PR separately. It is not hard relative with this slow SQL feature.

OK, I will send it soon, and it is a LAL enhancement, not MAL.

**Comment by wu-sheng** [comment]
Yes. My fault.
