### ISSUE TITLE
[Feature] Add impala jdbc plugin

### ISSUE THREAD

**Issue by lv-lifeng** [apache/skywalking#9555]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You could send a pull request to contribute new plugins for other open source projects.

**Comment by wu-sheng** [comment]
Please be clear about what you plan to do later when you submit an issue.

In skywalking, issue is used for tracking on planned things.

https://github.com/apache/skywalking-java/pull/302

**Comment by lv-lifeng** [comment]
> Please be clear about what you plan to do later when you submit an issue.
> 
> In skywalking, issue is used for tracking on planned things.
> 
> [apache/skywalking-java#302](https://github.com/apache/skywalking-java/pull/302)

got it.
