### ISSUE TITLE
webapp support web context name for reverse proxy

### ISSUE THREAD

**Issue by Yelijah** [apache/skywalking#9570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Does ui support web context name such as "/skywalking"? I can't find any configuration.

When I  rewrite /skywalking to / in nginx, the static resources's url in html is still /xx.js. 
my nginx conf:
```
        location /skywalking {
            # auth_basic "nginx basic http test for skywalking";
            # auth_basic_user_file /usr/local/etc/nginx/password;
            # auth_jwt "closed site" token=$cookie_sw_auth_token;
            # auth_jwt_key_file /usr/local/etc/nginx/jwt_key;
            proxy_http_version 1.1;
            proxy_next_upstream http_500 http_502 http_503 http_504 http_403 http_404 http_429 error timeout invalid_header non_idempotent;
            #proxy_next_upstream_timeout 0;
            #proxy_next_upstream_tries 0;
            proxy_redirect off;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            #proxy_buffering off;
            #proxy_buffer_size     64k;
            #proxy_buffers         32 64k;
            #proxy_busy_buffers_size 64k;
            
            proxy_connect_timeout    75;
            proxy_read_timeout       400;
            proxy_send_timeout       400;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
            proxy_pass http://SW.com;
            rewrite "^/skywalking/(.*)$" /$1 break;
        }
```

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/33784573/188596239-7b1f2ab1-51b0-4c90-a142-8a334eb4900c.png">

### Use case

I want ui support context name or support nginx rewrite

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pg-yang** [comment]
You could  define  your  own  URL prefix  , and  rewrite  the  URL in  nginx  .

**Comment by wu-sheng** [comment]
We replied this many many times. This is not supported.

**Comment by wu-sheng** [comment]
Search issues before you submit a new one.

**Comment by Yelijah** [comment]
> Search issues before you submit a new one.

I'm sorry, I did searched some issues opened in 2019. 
But I think this feature was already supported after 3 years, but I'm wrong.

**Comment by wu-sheng** [comment]
No one took an action, then nothing happened. This is open source.
