### ISSUE TITLE
[Feature] Polish up ConfigInitializer 

### ISSUE THREAD

**Issue by pg-yang** [apache/skywalking#9577]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The following issue  should be  resolved 
When  config  property is blank , the target filed shouldn't  be set . Because it will  override default value .
Sorry ,It's  my  mistake  ,  I will fix it.  The related  PR https://github.com/apache/skywalking-java/pull/304 .

Another issue  is  reading property and  converting  it  to java.util.Map . The code look like :

```
// read map from user declared field 
Map map = (Map) field.get(null);
// set  value  to  map 
setForMapType(configKey, map, properties, keyType, valueType);
```
Above  code  means  merge  default value    and   property value .  I think it's  not  appropriate . we should use default value or property  value ,  should't merge these  value  .Right ?

The  last issue 
```
                    final Length lengthDefine = field.getAnnotation(Length.class);
                    if (lengthDefine != null) {
                        if (value != null && value.length() > lengthDefine.value()) {
                            value = value.substring(0, lengthDefine.value());
                        }
                    }
```
This means  if  the  property  value  is  too long , cut it . I'm not  sure  the  code is appropriate . if  we  `cut  it ` , maybe cause some  error , for  example , invalid  incomplete  config , and there  is nothing for  warning user 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
> When config property is blank , the target filed shouldn't be set 

This is a bug

> When config property is blank , the target filed shouldn't be set . Because it will override default value

I am not sure whether we like this. We could keep the config not declared in the `agent.config` to avoid this overriding issue. Because if you change this part, generally, you block the chance to override the default value to blank. 
This is a tradeoff. Not really a bug.

> Another issue is reading property and converting it to java.util.Map .

What is the bug of this? Could you explain? The target type is `map`, then we convert to it.

> This means if the property value is too long , cut it . I'm not sure the code is appropriate 

This is by design. Things like `service name`, we do cutting it to follow the protocol requirement.

**Comment by pg-yang** [comment]
Got  it
If  user  set  key  but  the value  is  blank .  we  should  set a blank field  . 
If  user  set  key  and   the value  is not  blank .  we  should  override filed  . 
If user don't set property  , we don't  set the target field .

Let's  talk  about Map filed . if  I  declare my field in class as following 
```
private static Map<String,String > filed = new HashMap<String, String>() {
            {
                put("a", "1");
                put("b", "2");
            }
        };
```
Then I config  the property  like `XXXX.field[c]=3` in `agent.config` , Finally , I will  get  a  map  that contains `a ` ,`b`,`c` .
I think  we should't merge the initial  value and property value  , property value should override initial filed , Finally , I should  get  a  map  that  only contains `c`.


> This is by design. Things like `service name`, we do cutting it to follow the protocol requirement.

Let's log warn message , or throw an exception ?

**Comment by wu-sheng** [comment]
> Then I config the property like XXXX.field[c]=3 in agent.config , Finally , I will get a map that contains a ,b,c .
I think we should't merge the initial value and property value , property value should override initial filed , Finally , I should get a map that only contains c.

Yes, that is correct. We should fix this.

> Let's log warn message , or throw an exception ?

For a config setup, I don't want the service would break. `warn message` is fine.
