### ISSUE TITLE
[Feature] Micrometer 1.10 Observation API support

### ISSUE THREAD

**Issue by marcingrzejszczak** [apache/skywalking#9578]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I'm a maintainer of Spring Cloud Sleuth and Micrometer projects (together with @shakuzen and @jonatan-ivanov). 

Spring Cloud Sleuth 3.1.x is the last line of Spring Cloud Sleuth. There will be no Spring Cloud Sleuth 3.2 nor 4.0 (you can read more [here]( https://github.com/spring-cloud/spring-cloud-sleuth/tree/main#spring-cloud-sleuth)). There will be no Spring Boot 3 compatible version of Spring Cloud Sleuth. Sleuth will be replaced by Micrometer Observation and Micrometer Tracing.

[Micrometer Observation](https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-observation) is coming as part of the Micrometer 1.10 release and [Micrometer Tracing](https://github.com/micrometer-metrics/tracing) is a new project. The idea of Micrometer Observation is that you instrument code once but you get multiple benefits out of it - e.g. you can get tracing, metrics, logging or whatever you see fit). You can read more about it [here](https://micrometer.io/docs/tracing).

### Use case

We would like to ensure that Skywalking still works well without Spring Cloud Sleuth but with new features coming with Micrometer 1.10 and Micrometer Tracing.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Thanks for updating. As you selected Yes I am willing to submit a PR!, should I expect some PRs coming about the new micrometer integrations from you?

**Comment by marcingrzejszczak** [comment]
Sure, I can look into that. The thing is that we have milestones and snapshots of Micrometer 1.10 / Tracing etc. and we'll have GA versions mid November. How do you want us to proceed - do you want us to do a PR on snapshots and we'll merge the PR with GA versions in November?

**Comment by wu-sheng** [comment]
I think we need a GA version by following ASF policy.

And due to SkyWalking's agent could adopt versions, I hope to keep deprecated integration with the [old micrometer(Metrics part)](https://github.com/apache/skywalking-java/tree/main/apm-application-toolkit/apm-toolkit-micrometer-registry). Then, you could add a new module `apm-toolkit-micrometerXXX` to support your next GA version with a new module in the [activation part](https://github.com/apache/skywalking-java/tree/main/apm-sniffer/apm-toolkit-activation).

If you have any doubt, ping me.

**Comment by wu-sheng** [comment]
> Have you deprecated that part or are you suggesting that we're deprecating it by using the new API?

We are not deprecating anything. Is micrometer API unchanged?

> Also, since I've not done any previous work on Skywalking, do you have any guide / suggestions on how I should proceed with this work?

This toolkit is actually a kind of plugin, we have plugin dev and test docs.
The general boundaries are, toolkit just provide a API shell to integrate with 3rd party, all integration with agent kernel APIs should be placed in toolkit activation(a term of the agent plugin for toolkit)

https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/java-plugin-development-guide/

https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/plugin-test/

**Comment by wu-sheng** [comment]
@marcingrzejszczak Do we expect some changes for this? Or it is still compatible?

**Comment by marcingrzejszczak** [comment]
Hey, I didn't have time to do any work on this since yesterday we've released 1.10.0 GA of micrometer. We need to do some house keeping first (add missing docs etc.) and then I'll be able to spend some time on this.

**Comment by wu-sheng** [comment]
I am just checking whether we still need to keep tracking this. Thanks for the update.

**Comment by marcingrzejszczak** [comment]
So I've started to look into this and I don't really know how to start. 

What I see is that the current micrometer integration actually creates the `MeterRegistry` and integrates with the Skywalking internals. Skywalking has an abstraction for a Span and a Metric. With Micrometer 1.10.x we are introducing a new abstraction called Observation which could actually in cases of Timer like metrics be reconsidered to be used instead of other abstractions. That way depending on what you have on the classpath you could then trigger metric and span creation yourself. 

I think we could have a chat about this either here or on Zoom to discuss how we should proceed. WDYT?

**Comment by wu-sheng** [comment]
Yes, I am at UTC+8 TZ now. If you like, I could invite you to join slack, we could chat and arrange an online meeting. 

> Send Request to join SkyWalking slack mail to the mail list(dev@skywalking.apache.org), we will invite you in.

**Comment by marcingrzejszczak** [comment]
I've sent the email :)

**Comment by marcingrzejszczak** [comment]
We've discussed how we would proceed.

- We will work on Spring Framework 6 and RestTemplate instrumentation first
- Since it's already using Micrometer 1.10 Observation API we will create an empty ObservationHandler that will be instrumented by SkyWalking
- Then we will create an agent interceptor that will add concrete logic to the handler

Is that correct @wu-sheng ?

**Comment by wu-sheng** [comment]
Yes, that is correct. Let's forward this integration in this way.

**Comment by wu-sheng** [comment]
Fixed by https://github.com/apache/skywalking-java/pull/401
