### ISSUE TITLE
[Bug] Log report service accepts dynamic fields injectable through JSON format

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9579]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

This thing was found through this PR review, https://github.com/apache/skywalking/pull/9575#discussion_r964495722

@yswdqz uses this hijacking way to build an extra field(isSlowSQL) like this `if(parsed.isSlowSql)`.
__

### What you expected to happen

@kezhenxu94 I didn't expect there is a hijacking way to add a new field w/o the LAL process. The extra field should be all considered as tags concept.

Could you recheck this part of LAL kernel and prevent this misuse permanently?

### How to reproduce

LAL

```
rules:
  - name: mysql-slowsql
    dsl: |
      filter {
        json{
        }
        if(parsed.isSlowSql){
          slowSql {
                    serviceName parsed.service as String
                    id parsed.id as String
                    statement parsed.statement as String
                    latency parsed.query_time as Long
                    layer parsed.layer as String
                    timeBucket parsed.time as Long
                  }
        }
        sink{
        }
      }
```

Reported JSON format log
```json
[{"date":1662478799.208541,"body":{"json":{"json":"{\"time\":\"20220906153959\",\"isSlowSQL\":\"true\",,\"id\":\"cb92c1a5b-2691e-fb2f-457a-9c72a392d9ed\",\"service\":\"root[root]@[175.172.37.237]\",\"statement\":\"SET timestamp=1662478799;select sleep(2);\",\"layer\":\"MYSQL\",\"query_time\":2000}"}},"service":"root[root]@[175.172.37.237]"}]
```

### Anything else

For now, I would say this is a hijacking, but not a security issue. So far, the extra field is only a simple type field with value(like a string). But usually, this is exposing a risk.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Hi, why do you think `parsed.isSlowSql` is so called "hijack", `parsed` is the original log fields parsed from the text format by log parser (json/regexp/yaml, etc.), it's an intermedia variable and I don't think we should limit the fields.

**Comment by kezhenxu94** [comment]
Note: `parsed` is not what we use to persist in storage.

**Comment by wu-sheng** [comment]
This is from the protocol definition perspective. We documented and exposed a log receiving protocol, but actually, users could push more fields than we defined.

**Comment by kezhenxu94** [comment]
> This is from the protocol definition perspective. We documented and exposed a log receiving protocol, but actually, users could push more fields than we defined.

Hi,

1. `parsed` is parsed from `LogDataBody body`. https://github.com/apache/skywalking-data-collect-protocol/blob/906a834dc0c3fb66719b8313f8f9298be3a27349/logging/Logging.proto#L63
2. The protocol never/cannot define what fields users can push, `body` is a raw text/json/yaml, you have no idea what can be in the raw text/json/yaml.
3. As I said, `parsed` is just an intermedia variable, it's not what we persist in storage. What we persist is the [`Log` Java bean](https://github.com/apache/skywalking/blob/526aa3a5fd077ce548eed8e78052eff394209847/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/source/Log.java), and its fields are defined.

**Comment by wu-sheng** [comment]
I am totally fine user could add a new field in the parsed object. This is not what I felt was wrong.
The key point is a network protocol. We need to protect our services by not receiving data we expected. Once we limit that, the further process is open to user to define and add new fields according to their requirements.

**Comment by kezhenxu94** [comment]
> I am totally fine user could add a new field in the parsed object. This is not what I felt was wrong.
> The key point is a network protocol. We need to protect our services by not receiving data we don't expected and define. Once we limit that, the further process is open to user to define and add new fields according to their requirements.

Can you help, how we can limit what users can push here in the `LogDataBody body` field? It's a raw text https://github.com/apache/skywalking-data-collect-protocol/blob/906a834dc0c3fb66719b8313f8f9298be3a27349/logging/Logging.proto#L63

**Comment by wu-sheng** [comment]
Oh, I didn't realize this parsed is including the `body`. I was expecting `parsed.body.xxx` is for user extension.

So, what would happen if I put an `endpoint` as a key in the JSON formated body? Is the JSON's endpoint or endpoint in the root field has higher priority?

**Comment by kezhenxu94** [comment]
> So, what would happen if I put an `endpoint` as a key in the JSON formated body? Is the JSON's endpoint or endpoint in the root field has higher priority?

Hi, it does nothing if you put an `endpoint`/`instance`/`service` in the json body, UNLESS users explicitly specify that this one should override the top-level `endpoint` (which is [defined in the protocol](https://github.com/apache/skywalking-data-collect-protocol/blob/906a834dc0c3fb66719b8313f8f9298be3a27349/logging/Logging.proto#L61) like this


```groovy
filter {
    // ...
    extractor {
        endpoint parsed.endpoint
    }
}
```

**Comment by wu-sheng** [comment]
OK, thanks for the explanation. No more concern.
