### ISSUE TITLE
[Bug] apm-webapp config property oapServices  should contain scheme 

### ISSUE THREAD

**Issue by pg-yang** [apache/skywalking#9594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The  default value  of  `oapServices` is  `${SW_OAP_ADDRESS:-localhost:12800}`.

https://github.com/apache/skywalking/blob/12a18e6977a29f5e25f8db53a4053629ab6c0986/apm-webapp/src/main/resources/application.yml#L20
`URI.create("localhost:12800").getAuthority()` would get  null  , and  cause NPE in finally  .

https://github.com/apache/skywalking/blob/12a18e6977a29f5e25f8db53a4053629ab6c0986/apm-webapp/src/main/java/org/apache/skywalking/oap/server/webapp/OapProxyService.java#L48

### What you expected to happen

`URI.create("http://localhost:12800").getAuthority()` is  right , the  result  is  `localhost:12800`

### How to reproduce

Start apm-webapp through   default config 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Why there is a - before localhost?

**Comment by kezhenxu94** [comment]
snakeyaml respects a shell-style default value indicator `${ENV_VAR:-defaultValue}`, it's not surprising if you are familiar with shell env var.

<img width="1159" alt="Screen Shot 2022-09-13 at 15 28 43" src="https://user-images.githubusercontent.com/15965696/189838077-03fcc407-14dd-46b5-a2b8-fcbd71afd77d.png">

**Comment by wu-sheng** [comment]
So, `localhost:12800` is not correct, right?

**Comment by kezhenxu94** [comment]
> So, `localhost:12800` is not correct, right?

Right, it's wrong, they have to add the scheme prefix
