### ISSUE TITLE
[Bug] Apache ShenYu agent Tid is null

### ISSUE THREAD

**Issue by lishuo5263** [apache/skywalking#9598]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

* Use latested Skywalking version is 8.12.0
  * ![image](https://user-images.githubusercontent.com/19170961/189881932-9549bd8c-f420-4540-a1bd-3a1cc665898b.png)
* Make sure ShenYu bootstrap loaded apm-shenyu-2.4.x-jar
  *  ![image](https://user-images.githubusercontent.com/19170961/189882822-08881de7-6583-4b7a-9acf-88b4209f5620.png)
* Here is request detail
  * ![image](https://user-images.githubusercontent.com/19170961/189884416-00cd98c7-bace-4ebb-8132-aa86e084c122.png)
 
 

### What you expected to happen

* Should be use exchange.getAttributes() get TraceId or tid.

### How to reproduce

* Use latested Skywalking agent ,copy shenyu-2.4.x.jar to plugins.
* Start ShenYu bootstrap
* look at console tid output

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please ping Shenyu community to review and follow this fix.

**Comment by lishuo5263** [comment]
A fix PR has now been submitted：https://github.com/apache/skywalking-java/pull/309

**Comment by ZhangYuJie-88** [comment]
我已更新skywalking agent 版本为8.13，且把shenyu插件从optional-plugins移动到plugins目录，仍然获取不到traceId，请问还需要做什么？

**Comment by wu-sheng** [comment]
@ZhangYuJie-88 We required English for comments in GItHub. Removing yours.

**Comment by wu-sheng** [comment]
It is better if you could ask the Shenyu community directly. They are leading on this from beginning, we just host and help on releasing its plugin.

**Comment by coderDylan** [comment]
This problem has not been solved yet

**Comment by wu-sheng** [comment]
Locking the issue. Because no matter what is the issue, we have nothing to do.
