### ISSUE TITLE
[Feature] Update related repo and add a blog for SWCK v0.7.0

### ISSUE THREAD

**Issue by dashanji** [apache/skywalking#9625]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

As the swck v0.7.0 is released, we need to update the relevant repo to support new features such as [skywalking-showcase](https://github.com/apache/skywalking-showcase) and add a blog to introduce new features for swck users.

- [x] Update [skywalking-showcase](https://github.com/apache/skywalking-showcase) for swck v0.7.0.
- [ ] Add a blog about how to use the new features for swck users. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
The showcase is only a way to demonstrate features, not for product use.

FYI @kezhenxu94

**Comment by dashanji** [comment]
Make sense to me, then I just need to change the version of swck.
