### ISSUE TITLE
[Bug] Failed to create profiling task

### ISSUE THREAD

**Issue by xzyJavaX** [apache/skywalking#9633]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

When I select the endpoint name as "ALL", systems display "Task created successfully", but the task was not created.
![8FFE397B-E7CD-49ED-B6AA-8CBC62865AB2](https://user-images.githubusercontent.com/49760141/190953574-a2057d41-8deb-42c4-bdc8-ddd02eee43cc.png)
![15BA9BF0-1E21-4818-8C80-77318AA94805](https://user-images.githubusercontent.com/49760141/190953578-e8a3da1a-f14e-4f42-82c3-a28b6ac3d5af.png)

### What you expected to happen

The creation is successful, or the endpoint name is prohibited from providing "ALL" for users to select when creating tasks

### How to reproduce

Start apache-skywalking-apm-9.2.0, enter "Trace Profiling" page, select "ALL" as the endpoint name when creating tasks.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
You must specific an endpoint. This is only a small UI bug.

**Comment by wu-sheng** [comment]
Are you going to submit a pull request to fix on UI?

**Comment by xzyJavaX** [comment]
Sorry, I don't know much about UI
