### ISSUE TITLE
[Bug] skywalking UI not show Log Tab

### ISSUE THREAD

**Issue by hellopeath** [apache/skywalking#9675]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/114063945/191948144-8907ee30-9872-4817-8945-99f684074fdc.png">

the version is 9.2.0-cb8845a,but the same version, in the other environment it have tab Log

<img width="1717" alt="image" src="https://user-images.githubusercontent.com/114063945/191948389-b5cbaccf-4d90-468e-815f-bba0c3c37695.png">

### What you expected to happen

I want to know why

### How to reproduce

use the version 9.2.0-cb8845a

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
It is being shown on demo env. I can't see the issue.

All dashboards are customizable. You may change on your side.

**Comment by hellopeath** [comment]
> It is being shown on demo env. I can't see the issue.
> 
> All dashboards are customizable. You may change on your side.

But where is the configuration please? Is there any documentation to refer to?
