### ISSUE TITLE
[Feature] Add APISIX metrics monitoring in Gateway catalog

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9677]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Apache APISIX community works closely with us. @moonming is our committer and also their PMC chair.

I am looking forward to using `Prometheus + OTEL collector --otlp--> OAP` to set up a default dashboard for APISIX gateway.

Ref doc, https://apisix.apache.org/docs/apisix/plugins/prometheus/

This would be another level one menu(Gateway), between `browser` and `database`.

This is open to the community volunteer to pick up.

### Related issues

We recently have received contributions for MySQL and PostgreSQL server monitoring, anyone wants to start from here, could refer those
1. https://github.com/apache/skywalking/issues/9376
2. https://github.com/apache/skywalking/issues/9472

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pg-yang** [comment]
Please assign to me

**Comment by pg-yang** [comment]
APISIX should be submenu of  `gateway ` or level one menu (named gateway )? 
Currently we would have an gateway apisix

**Comment by wu-sheng** [comment]
APISIX should be a submenu of the gateway. There are many gateways, such as Kong, Nginx, OpenResty.

**Comment by pg-yang** [comment]
![image](https://user-images.githubusercontent.com/3917424/193243750-fc79d321-869b-40a2-bfbc-74d3b67733c8.png)


![image](https://user-images.githubusercontent.com/3917424/193243591-3e4b3121-b163-43f9-94ea-31e8aa0ba951.png)


![image](https://user-images.githubusercontent.com/3917424/193243610-55e5e139-648d-40f2-9a2a-1e4d9cefe760.png)


![image](https://user-images.githubusercontent.com/3917424/193243633-2dbcc8f4-f339-4749-bf4f-dff707a35fd8.png)

How about the layout?

**Comment by wu-sheng** [comment]
APISIX's Prometheus supports Endpoint level metrics? Is that path routing rule path? Or is it really access URI? Which could be thousands easily.
Notice, this is a pure question, it isn't SkyWalking's concern.

**Comment by pg-yang** [comment]
The  metrics which contains  route , node face to specific node(or upstream ), else other to  all node 
```
# HELP apisix_bandwidth Total bandwidth in bytes consumed per service in APISIX
# TYPE apisix_bandwidth counter
apisix_bandwidth{type="egress",route="",service="",consumer="",node=""} 678
apisix_bandwidth{type="egress",route="routes#1",service="1",consumer="",node="127.0.0.1"} 678
apisix_bandwidth{type="ingress",route="",service="",consumer="",node=""} 627
apisix_bandwidth{type="ingress",route="routes#1",service="1",consumer="",node="127.0.0.1"} 252
```
If we only collect metrics from apisix aspect (skip metrics which don't contain `route` ,`node` ) , the result  would be incomplete .
If group metrics by  `type ` `route `  `node ` , the  label would be too many , the number would be `typeNumer*routeNumber*nodeNumer `
So  I mapping node to instance , route to endpoint .

**Comment by wu-sheng** [comment]
What is your question to discuss?

Once endpoints are only rules, I am good.

**Comment by gxthrj** [comment]
I think it is OK.
In the default prometheus metrics template of `APISIX`, metrics labels such as `route` and `node` will indeed lead to a surge in the number of metrics. 
I think it is OK to map `node` to `instance` or  `route` to `endpoint`. The only downside is that you need to click it layer by layer.

**Comment by wu-sheng** [comment]
Thanks, and yes, I think these two mappings make sense.

**Comment by wu-sheng** [comment]
@kezhenxu94 As the PR of MAL and UI settings are going to be merged soon, I suppose. I want to discuss with you about how to add this as a part of showcase

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/5441976/193457416-786102e7-ed0b-46f6-9ea0-11055632bddc.png">

Currently, we have a complete distributed system for demonstrating tracing, logging collecting, agent metrics collecting. 
Should or should not we add an APISIX gateway between browser and `app server (NodeJS)` as a tier1 Gateway, which could both activate skywalking plugin for tracing and Prometheus plugin for this new Gateway monitoring.

Do you have any suggestion?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 As the PR of MAL and UI settings are going to be merged soon, I suppose. I want to discuss with you about how to add this as a part of showcase
> 
> 
> 
> <img width="1222" alt="image" src="https://user-images.githubusercontent.com/5441976/193457416-786102e7-ed0b-46f6-9ea0-11055632bddc.png">
> 
> 
> 
> Currently, we have a complete distributed system for demonstrating tracing, logging collecting, agent metrics collecting. 
> 
> Should or should not we add an APISIX gateway between browser and `app server (NodeJS)` as a tier1 Gateway, which could both activate skywalking plugin for tracing and Prometheus plugin for this new Gateway monitoring.
> 
> 
> 
> Do you have any suggestion?

Yes I think it's a suitable case to add APISIX as a tier1 gateway as this is a typical usage of APISIX. 

Currently I'm using `npm start` to start the app(browser) and app(server), which is not a typical production deployment method, so we can set up APISIX as a static file server to serve the front end files AND proxy the app(server).

**Comment by wu-sheng** [comment]
That seems good. @pg-yang Could you follow this way to build the showcase?

**Comment by pg-yang** [comment]
Sure  , I need to understand showcase project first  , and would ask you if have trouble

**Comment by wu-sheng** [comment]
Zhenxu built the current distributed system, he would be able to help you if needed.

**Comment by pg-yang** [comment]
@kezhenxu94 
Currently , app-ui  and app-server in one docker image . I  need to split to two image .

image-1 contains app-server 
image-2   contains app-ui  and apisix gateway  simultaneously .  And apisix would proxy request to ui , app-server  . 

RIght ?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 
> 
> Currently , app-ui  and app-server in one docker image . I  need to split to two image .
> 
> 
> 
> image-1 contains app-server 
> 
> image-2   contains app-ui  and apisix gateway  simultaneously .  And apisix would proxy request to ui , app-server  . 
> 
> 
> 
> RIght ? 

Yes.
