### ISSUE TITLE
SkyWalking Rocketmq plugin modifies the TAG of Rocketmq sending messages

### ISSUE THREAD

**Issue by zhoushuai1119** [apache/skywalking#9686]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

SkyWalking Version：8.6.0
RocketMQ version：4.9.1

SkyWalking is integrated in my project. When using Rocketmq to send messages, it is found that the TAG sending messages has been modified, which makes it impossible to be consumed。When I remove the two plug-in JAR packages, apm-rocketmq-3. x-plugin-8.6.0.jar and apm-rocketmq-4. x-plugin-8.6.0.jar, the message is sent normally.

![image](https://user-images.githubusercontent.com/29701159/192186069-092df1fb-9290-4b5b-9a04-ce281e6e4f49.png)

### What you expected to happen

I hope not to modify the TAG of sending messages, otherwise I will not be able to consume messages

### How to reproduce

Sending messages using DefaultMQProducer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment]
https://github.com/apache/rocketmq/issues/3331 Seems the same as this one? It was fixed in Java agent 8.8.0

**Comment by wu-sheng** [comment]
8.6.0 is one year old. Please try the latest, if it has any issues, please report it to RocketMQ community.
I remember it was contributed by them.

**Comment by zhoushuai1119** [comment]
> [apache/rocketmq#3331](https://github.com/apache/rocketmq/issues/3331) Seems the same as this one? It was fixed in Java agent 8.8.0

Thank you. I'll try to upgrade the SkyWalking version. Why did the issues mention Rocketmq? No wonder I found the issues about this

**Comment by wu-sheng** [comment]
As I replied in many issues, SkyWalking agents(all languages) are hosting source codes for various oss communities. 
They were not written by skywalking maintainers. 

Also, different projects have different rules and polices for their header/metadata in the RPC, you have to ask them to get the suggestions.
