### ISSUE TITLE
[Bug] RocketMq message tag missing

### ISSUE THREAD

**Issue by zengLH1981** [apache/skywalking#9703]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

user rocketMQ send a message with tag.
but lost the tag

### What you expected to happen

keep the tag

### How to reproduce

rocketmq 4.9.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't change message. Please reach RocketMQ community for details.

**Comment by zengLH1981** [comment]
> We don't change message. Please reach RocketMQ community for details.

bug I remove the skywalking agent ，the tag appear

**Comment by wu-sheng** [comment]
I don't mean this isn't a bug, but RocketMQ plugin was contributed and maintained by the RocketMQ community. 
We just distributed it as it is better to be out-of-box on the SkyWalking side. This principle fits most plugins about the agent plugins
