### ISSUE TITLE
[Feature] Add SlowSQL(MySQL/PostgreSQL) to showcase

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9706]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add showcase for https://github.com/apache/skywalking/pull/9614 and https://github.com/apache/skywalking/pull/9673

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
DONE
