### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by huoshenyingmu** [apache/skywalking#9720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

![image](https://user-images.githubusercontent.com/27325498/193168608-91b12722-1b0f-4002-9c63-4502e9965b77.png)
![image](https://user-images.githubusercontent.com/27325498/193168762-e8347088-9be8-4c11-9039-92fa772e5778.png)
Abnormal time selection (bug)

There is a problem with the time selection in the second picture. In 1, the minutes have been modified, and in 2, the time will also change. It is the same in 1

### What you expected to happen

![image](https://user-images.githubusercontent.com/27325498/193168608-91b12722-1b0f-4002-9c63-4502e9965b77.png)
![image](https://user-images.githubusercontent.com/27325498/193168762-e8347088-9be8-4c11-9039-92fa772e5778.png)
Abnormal time selection (bug)

There is a problem with the time selection in the second picture. In 1, the minutes have been modified, and in 2, the time will also change. It is the same in 1

### How to reproduce

![image](https://user-images.githubusercontent.com/27325498/193168608-91b12722-1b0f-4002-9c63-4502e9965b77.png)
![image](https://user-images.githubusercontent.com/27325498/193168762-e8347088-9be8-4c11-9039-92fa772e5778.png)
Abnormal time selection (bug)

There is a problem with the time selection in the second picture. In 1, the minutes have been modified, and in 2, the time will also change. It is the same in 1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We can't reproduce this on the demo and local env. I would say most likely this is a fixed bug in old releases.
