### ISSUE TITLE
web client import skywalking-client-js, request http://xxxxxx:12800/browser/perfData  response 404 not found ，sky v8.7.0

### ISSUE THREAD

**Issue by catalpa-tree** [apache/skywalking#9723]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

NodeJS Client Side Agent (apache/skywalking-client-js)

### What happened

request http://xxxxxx:12800/browser/perfData  response 404 not found
![image](https://user-images.githubusercontent.com/69246580/193237097-b54948c3-3308-4396-884e-eba01342f152.png)

### What you expected to happen

success

### How to reproduce

postman

### Anything else

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by catalpa-tree** [comment]
why is Missing configuration? or How to do ?

**Comment by wu-sheng** [comment]
Why a 404 should be a bug? This is clearly you don't send requests to the right place.

Also, if you are using postman rather than the agent, it is your responsibility to understand the protocol, and report correctly.

**Comment by catalpa-tree** [comment]
> Why a 404 should be a bug? This is clearly you don't send requests to the right place.
> 
> Also, if you are using postman rather than the agent, it is your responsibility to understand the protocol, and report correctly.

It is not bug, I was just asking what I should do？It has been accessed according to skywalking-client-js, but now it reponse 404
![企业微信截图_3cc9ede0-86bc-44be-99d6-ab3fd70e376e](https://user-images.githubusercontent.com/69246580/193239939-becfe122-cc7f-41a8-a171-46c1777cdbac.png)
![企业微信截图_53412481-385e-45f6-af66-2d010f6c4562](https://user-images.githubusercontent.com/69246580/193239978-c8f41a83-7350-4f53-a440-8ab263da9006.png)

**Comment by wu-sheng** [comment]
Sorry, that is your env, we don't have a special configuration to respond 404 on purpose. 
OAP don't know if it is from the client agent or your postman. The only reason is you are sending the request to the wrong place.

**Comment by catalpa-tree** [comment]
> http://xxxxxx:12800/browser/perfData



> Sorry, that is your env, we don't have a special configuration to respond 404 on purpose. OAP don't know if it is from the client agent or your postman. The only reason is you are sending the request to the wrong place.

You mean the configured address http://xxxxxx:12800 incorrect? But this is the oap server address, and the others are encapsulated in skywalking-client-js

**Comment by wu-sheng** [comment]
How could I know? If the agent is correct, you should be able to know where to send easily.

**Comment by catalpa-tree** [comment]
> How could I know? If the agent is correct, you should be able to know where to send easily.

It's OK to collect Java information from the same address through the agent, then change the port to 12800, and skywalking client js reports this error after configuration. So what's the problem?

**Comment by wu-sheng** [comment]
https://skywalking.apache.org/docs/skywalking-showcase/next/readme/

Showcase is there for you to set features out of box on k8s or docker compose. We wouldn't debug for your env, we can't afford that cost.
