### ISSUE TITLE
[Rover] license issue

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#9727]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I happened to find the license of the source file [protocol_analyze.h](https://github.com/apache/skywalking-rover/blob/main/bpf/profiling/network/protocol_analyze.h#L19) is GPL-2.0 but [we declare it as Apache 2.0](https://github.com/apache/skywalking-rover/blob/48fb8ced2e4aaf505777c6eac2587d799ab9c2bd/LICENSE#L218), which is not allowed as per ASF’s policy. 

we should fix this as soon as possible before the next release. 

### What you expected to happen

No license conflict

### How to reproduce

No need to reproduce. 

### Anything else

Note that the GPL files are used in pixie and pixie being Apache2.0 licensed doesn’t mean the GPL files become Apache2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@mrproliu As a protocol analyzer, I think it should be very easy to rebuild one, and we just need HTTP 1.1/2 identifying.

**Comment by kezhenxu94** [comment]
Another thing I found is that this file is not a simple copy of the original file. It adds some other content from other file but doesn't mention the changes and the other files. I'm not sure whether there are other similar cases or not. Please overhaul the files that are copied from other repos.
