### ISSUE TITLE
[Bug] In this case, profiling tasks should not be created

### ISSUE THREAD

**Issue by xzyJavaX** [apache/skywalking#9742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

During the creation of profiling task, a field called time_bucket will be generated,time_bucket is converted from the end time of task monitoring.For example, for Task A, the monitoring start time is 12:00:00, the monitoring time is 5 minutes, and the monitoring end time is 12:05:00, time_bucket is 12:05.Then create Task B, with the start time of 12:04:00 and the end time of 12:09:00, will go to the database to check whether there is a time_ Buckets in this range. If yes, throw "current service already has monitor task execute at this time".For example, start is 12:04:00, end is 12.09:00, and there is a time_bucket is 12:05, so Task B failed to be created.
But if you create a task with a monitoring time of 15 minutes at 12:00:00,  time_bucket is 12:15. At this time, a task with start is 12:04:00 and end is 12:09:00 can be created successfully. This should not be as expected.
There is also a UI problem. When the "current service already has monitor task execute at this time" is returned, the pop-up window will show that the creation was successful, but it was not actually created.
![518a51ea-b99f-4c57-af35-6af68dd0657b](https://user-images.githubusercontent.com/49760141/194735415-6d71be0d-b0b6-4b28-85b6-2e99cc94f626.png)

### What you expected to happen

In this case, profiling tasks should not be created

### How to reproduce

First create a profiling task with a monitoring duration of 15 minutes, and then create a profiling task with a monitoring duration of 5 minutes

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This seems a bug. Are you going to submit a pull request to fix?

**Comment by xzyJavaX** [comment]
Yes I am willing to submit a PR

**Comment by wu-sheng** [comment]
Assigned to you. cc owner @mrproliu
