### ISSUE TITLE
[Bug] The image port of the UI can only be 8080

### ISSUE THREAD

**Issue by zhaomingcheng01** [apache/skywalking#9743]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

If you change the port, you can't access it

### What you expected to happen

Port can be changed

### How to reproduce

Change a port

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
We don't lock that.
