### ISSUE TITLE
[Bug] Server startup failed. Cannot create worker GC thread. Out of system resources

### ISSUE THREAD

**Issue by wannianxianyu** [apache/skywalking#9748]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

oap Server startup failed
```
[0.003s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /skywalking/hs_err_pid1.log
```

This is my server running environment, Alibaba Cloud Server
```
# yum list installed | grep docker
containerd.io.x86_64                         1.4.3-3.1.el8                           @docker-ce-stable
docker-ce.x86_64                             3:20.10.3-3.el8                         @docker-ce-stable
docker-ce-cli.x86_64                         1:20.10.3-3.el8                         @docker-ce-stable
docker-ce-rootless-extras.x86_64             20.10.3-3.el8                           @docker-ce-stable

# free -h
              total        used        free      shared  buff/cache   available
Mem:           31Gi        16Gi       1.6Gi       3.0Mi        13Gi        14Gi
Swap:            0B          0B          0B

```

In the same environment, I have tried to use different versions of oap
```
skywalking-oap-server:9.2.0  fail
skywalking-oap-server:9.1.0  fail
skywalking-oap-server:9.0.0  success
```
[I found a similar problem](https://github.com/adoptium/temurin-build/issues/3020)
However, I cannot upgrade the Docker version because it is a production environment

### What you expected to happen

Start the service normally

### How to reproduce

Maybe it can be reproduced in the lower version Docker environment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is out of community scope. It isn't our concern.

**Comment by crazyman2010** [comment]
same issue, skywalking 9.0.0 is ok and skywalking 9.2.0 report error.
----------------------
docker version:
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:27:18 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:20 2019
  OS/Arch:          linux/amd64
  Experimental:     true
-------------------------------------------
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31674
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31674
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
