### ISSUE TITLE
[Bug] [PHP]  Bad role for documentation

### ISSUE THREAD

**Issue by remicollet** [apache/skywalking#9753]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

CLI (apache/skywalking-cli)

### What happened

In package.xml documentation have role="src" instead of expected role="doc"

### What you expected to happen

role="doc" for NOTICE, README.md, LICENSE

### How to reproduce

pecl install ...

### Anything else

There is no component in above dropdown for the PHP agent

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heyanlong** [comment]
@remicollet Thanks you for report the bug, I'll fix it now

**Comment by jmjoy** [comment]
`README.md` will be compiled into the `.so` because of https://github.com/apache/skywalking-php/blob/737b4f65824bb4939faa3e9452b83c73bf5ddfe8/src/lib.rs#L18 , others can be used as docs.

**Comment by heyanlong** [comment]
https://github.com/apache/skywalking-php/pull/16

**Comment by jmjoy** [comment]
https://github.com/apache/skywalking-php/pull/16 Merged.
