### ISSUE TITLE
[Bug] [PHP] support for rust 1.58

### ISSUE THREAD

**Issue by remicollet** [apache/skywalking#9757]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

CLI (apache/skywalking-cli)

### What happened

```
+ make -j10
PHP_CONFIG=/usr/bin/php-config cargo build --release
error: package `dashmap v5.4.0` cannot be built because it requires rustc 1.59 or newer, while the currently active rustc version is 1.58.1
make: *** [Makefile:191: modules/skywalking_agent.so] Error 101

```

### What you expected to happen

Build OK with rust 1.58 (default version in RHEL, Alma, Rocky...)

### How to reproduce

Build on RHEL

### Anything else

CentOS Stream 8 and 9 already have rust 1.62
so this new version will probably be available in RHEL 8.7 and 9.1 (in a few weeks)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment]
The rust version is limit by third-party dependency `dashmap`, therefore, it is difficult to downgrade the rust version, or use the newer version rust rather than the one installed by distribution?

**Comment by remicollet** [comment]
> The rust version is limit by third-party dependency dashmap, therefore, it is difficult to downgrade the rust version,

Or downgrade dashmap version requirement

> or use the newer version rust rather than the one installed by distribution?

Not possible (from packaging PoV)
