### ISSUE TITLE
[Bug] [PHP] offline build

### ISSUE THREAD

**Issue by remicollet** [apache/skywalking#9758]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

CLI (apache/skywalking-cli)

### What happened

Unable to build offline as the dependencies are download on the fly

### What you expected to happen

Able to buid offline

### How to reproduce

`pecl install skywalking_agent-0.1.0.tgz`

### Anything else

A possible workaround (used for success for other extension skywalking)

run "cargo vendor xxx" and add this folder (its archive) in the package

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@remicollet Could you share why you expect offline build? Is there any specific case requiring this?

**Comment by remicollet** [comment]
this is a common practice (even mandatory for official repository) to build packages (RPM or other formats) offline
also required for reproducible builds.

**Comment by wu-sheng** [comment]
I will leave this to @heyanlong @jmjoy to decide. After all, at the ASF, we either provide ASF-owned source codes or a compiled binary for convenience. 
All repositories of SkyWalking, even the whole ASF, follow this practice. It seems we face conflicts cross-orgs.
