### ISSUE TITLE
[BanyanDB] Support "IN" and "NOT IN" binary operation in criteria 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9759]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The query module should implement "IN" and "NOT IN" defined by APIs. 

BTW, the OAP server doesn't need this operation for now. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DevPJ9** [comment]
Hello, @hanahmily I would like to contribute. Can you please provide some more info on the task?

**Comment by DevPJ9** [comment]
Thanks, @hanahmily. I will start with the changes and will let you know If I get stuck. :)

**Comment by DevPJ9** [comment]
Hello @hanahmily I have understood the requirement and I will do the changes and raise a PR, However, I have not worked with "go" language so I might do the changes wrong. Kindly guide me through those mistakes.

**Comment by DevPJ9** [comment]
Hello @hanahmily I have raised a PR #9759. Can you please review and about the tag_filter changes, I am sorry but I don't know how to proceed further.

**Comment by hanahmily** [comment]
Fixed by https://github.com/apache/skywalking-banyandb/pull/191
