### ISSUE TITLE
[BanyanDB] Update Protobuf specs of Java Client

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9761]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Update Java client based upon https://github.com/apache/skywalking-banyandb/pulls?q=is%3Apr+is%3Aclosed+label%3Aapi+milestone%3A0.2.0. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Java client has itd own milestone.
