### ISSUE TITLE
MySQL/PostgreSQL monitor should be able to support cluster mode scenario

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#9762]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In recent pull requests from @yswdqz we can monitor metrics from MySQL and PostgreSQL, but currently we assume that every MySQL/PostgreSQL server only has one instance, and we use that instance as the service name, (refer to our demo environment http://demo.skywalking.apache.org/mySQL)

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/15965696/195023145-784519cb-af23-4736-b9dc-cdc87862f11d.png">

However, a MySQL/PostgreSQL server should be able to have multiple instances and form a cluster, in that case, we should have aggregated metrics for those instances.

### Use case

When there are multiple instances/nodes for one MySQL/PostgreSQL server, users can have an aggregated overview of the database server.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
@yswdqz I can't assign this to you YET, are you willing to continue this?

**Comment by wu-sheng** [comment]
@yswdqz I think we could have perf of both k8s service and per pod(as skywalking instance level).

We had a similar discussion with @pg-yang from https://github.com/apache/skywalking-showcase/pull/83#issuecomment-1272504487. Generally about the same preferences.

**Comment by yswdqz** [comment]
Yes, I will.
But I am doing another PR now, might be doing this later.

**Comment by wu-sheng** [comment]
If you mean the SQL-sign, I think you don't need to hurry. After all, I could image that is a long-term feature, we may face forward and backward several times, also be struggling due to the tradeoff :)

**Comment by yswdqz** [comment]
> If you mean the SQL-sign, I think you don't need to hurry. After all, I could image that is a long-term feature, we may face forward and backward several times, also be struggling due to the tradeoff :)

Got it.

**Comment by wu-sheng** [comment]
@yswdqz How is this going?

**Comment by yswdqz** [comment]
> @yswdqz How is this going?

I haven't started it yet ( because of something about my university ). I will start it tomorrow.

By the way, Does this mean that I should set what I previously set as `service` to `instance` and then set the cluster's metrics to `service`?

**Comment by wu-sheng** [comment]
Yes, each IP/pod should be an instance.

**Comment by yswdqz** [comment]
Got it.

**Comment by yswdqz** [comment]
I am comfused about which metrics should I to set for cluster because there are many kind of cluster (such as galera, MMM) and  It's hard to find good metrics/exporter for most of them.
And is this issue ("have an aggregated overview of the database server") means that I just need to set service lever dashboards the same as instance level?

**Comment by kezhenxu94** [comment]
> I am comfused about which metrics should I to set for cluster because there are many kind of cluster (such as galera, MMM) and  It's hard to find good metrics/exporter for most of them.
> 
> And is this issue ("have an aggregated overview of the database server") means that I just need to set service lever dashboards the same as instance level?

The service name should be set by users in a label `service`. Usually they should set this to the business usage such as `product1`, `product2`

**Comment by wu-sheng** [comment]
About which metrics, I think there would not have much difference. When you set up a MySQL service in prod env, usually there is read/write or master/slave deployment for a database to provide HA or higher performance. 
This is generally why Zhenxu asked you to monitoring MySQL from a service perspective rather than currently from a single MySQL node(instance) perspective.

**Comment by yswdqz** [comment]
> About which metrics, I think there would not have much difference. When you set up a MySQL service in prod env, usually there is read/write or master/slave deployment for a database to provide HA or higher performance. This is generally why Zhenxu asked you to monitoring MySQL from a service perspective rather than currently from a single MySQL node(instance) perspective.

So the slow sql monitoring should be service level(not instance level)?

**Comment by wu-sheng** [comment]
I think we only support slow SQL at service for now.

I just talked with @mrproliu about extending sampled records for various entity level, even for relationship.

FYI @Fine0830 We may need to adjust sampled record widget as well.

**Comment by yswdqz** [comment]
To confirm, do I need to wait for the new pr to be submitted or temporarily set slowsql to service level?

**Comment by wu-sheng** [comment]
> temporarily set slowsql to service level?

This should be good enough for now.

**Comment by yswdqz** [comment]
> > temporarily set slowsql to service level?
> 
> This should be good enough for now.

Got it.

**Comment by wu-sheng** [comment]
Make sense to me.

**Comment by yswdqz** [comment]
MySQL - Service:
![image](https://user-images.githubusercontent.com/74546965/200229086-5a43f535-4860-42fb-9664-1c77fb23c9ee.png)
![image](https://user-images.githubusercontent.com/74546965/200229147-2dc04a36-3d9d-4e9a-8e01-4ea0fda8c21c.png)
MySQL - Instance:
![image](https://user-images.githubusercontent.com/74546965/200231187-62b3fb64-d968-4b1b-9110-6242d338cf02.png)

Is that ok?

**Comment by kezhenxu94** [comment]
> And I remove the instance level's Slow Statement. Now Slow Statement only exist in service level.

Hi, why do you think we should remove Slow Statements in instance level?

The other screenshots looks good to me

**Comment by yswdqz** [comment]
For now instance level Slow Statements is not supported.

**Comment by kezhenxu94** [comment]
> For now instance level Slow Statements is not supported.

Do you mean UI component doesn't support instance level Slow Statement?

**Comment by yswdqz** [comment]
> > temporarily set slowsql to service level?
> 
> This should be good enough for now.

It is not supported by LAL slow sql spec, too. I used to think the service level was enough. If it is needed, I can change the LAL part.

**Comment by kezhenxu94** [comment]
> > > temporarily set slowsql to service level?
> > 
> > 
> > This should be good enough for now.
> 
> It is not supported by LAL slow sql spec, too. I used to think the service level was enough. If it is needed, I can change the LAL part.

OK, let's only support service level for now
