### ISSUE TITLE
[BanyanDB] Java client's UTs fails with JDK16,17

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9771]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

UTs fail due to Powermock with JDK 16 or 17. The runtime will complain with below errors:

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module org.apache.skywalking.banyandb.v1.client.BanyanDBClientStreamQueryTest.setUp(BanyanDBClientStreamQueryTest.java)
```

It might relate to https://github.com/powermock/powermock/issues/1094

And JDK 11 will raise following warnings:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.powermock.reflect.internal.WhiteboxImpl (file:/Users/gao/.m2/repository/org/powermock/powermock-reflect/2.0.9/powermock-reflect-2.0.9.jar) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of org.powermock.reflect.internal.WhiteboxImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

We should bump up powermock once it fixes it.

### What you expected to happen

No

### How to reproduce

No

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
If we provide consistent JDK 8,11,17 support, please add them into CI compiling process to keep this. It is hard to track from codes review.

**Comment by wu-sheng** [comment]
I think we only add target JDK level, CI is just using default JDK?
