### ISSUE TITLE
[Bug] The profiling task did not work

### ISSUE THREAD

**Issue by xzyJavaX** [apache/skywalking#9779]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

In skywalking-java, the command will be obtained by accessing OAP through RPC request. In OAP, the command will be cached, and the cache will be updated every 10 seconds. The query criteria are:
```
final List<ProfileTask> taskList = profileTaskQueryDAO.getTaskList(
        null, null, profileTaskCache.getCacheStartTimeBucket(), profileTaskCache
                .getCacheEndTimeBucket(), null);
public long getCacheStartTimeBucket() {
    return TimeBucket.getMinuteTimeBucket(System.currentTimeMillis());
}
public long getCacheEndTimeBucket() {
    return TimeBucket.getMinuteTimeBucket(System.currentTimeMillis() + TimeUnit.MINUTES.toMillis(25));
}
```
ProfileTask TimeBucket:
```
task.setTimeBucket(TimeBucket.getMinuteTimeBucket(taskStartTime));
```
Because DownSampling is used Minute, so in most cases, it is OK. For example, at 12:30:40, when profiling task A is created, the TimeBucket is 1230. After 3 seconds, the cache starts to update. At this time, the time is 12:30:43, and the getCacheStartTimeBucket is 1230, which can still be queried.
But if we create a profiling task B at 12:30:58, the TimeBucket is 1230. After 3 seconds, the cache starts to update. At this time, the time is 12:31:01, and the getCacheStartTimeBucket is 1231. In this way, the taskB cannot be found in the future, this causes task B did not work.

### What you expected to happen

Every analysis task works,maybe we should modify the start time and end time of the query,for example:
```
public long getCacheStartTimeBucket() {
    return TimeBucket.getMinuteTimeBucket(System.currentTimeMillis() - TimeUnit.MINUTES.toMillis(5));
}
public long getCacheEndTimeBucket() {
    return TimeBucket.getMinuteTimeBucket(System.currentTimeMillis() + TimeUnit.MINUTES.toMillis(5));
}
```

### How to reproduce

Create a profiling task B at 12:30:58.The closer the task creation time is to the end of minutes, the easier it is to reproduce.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This seems a race condition, and I believe this is a bug. FYI @mrproliu 

@xzyJavaX I think you are going to submit a patch to fix, right?
