### ISSUE TITLE
[Bug] EndpointRelation#prepare NPE

### ISSUE THREAD

**Issue by codecodesam** [apache/skywalking#9785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

![image](https://user-images.githubusercontent.com/89377053/195553400-51950fd6-87d9-4027-9c68-e1ae2c0c4e94.png) Server version: 9.1.0;
Situation:org.apache.skywalking.oap.server.core.source.EndpointRelation#prepare(101) has a NPE;
Frequency:a most of segment

### What you expected to happen

I review the code and find a place that maybe cause EndpointRelation.serviceLayer Null;
```
// org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.EndpointDepFromCrossThreadAnalysisListener#parseRefForEndpointDependency
if (isMQ || config.getUninstrumentedGatewaysConfig()
                  .isAddressConfiguredAsGateway(networkAddressUsedAtPeer)) {
    sourceBuilder.setSourceServiceName(networkAddressUsedAtPeer);
    sourceBuilder.setSourceEndpointOwnerServiceName(reference.getParentService());
    sourceBuilder.setSourceServiceInstanceName(networkAddressUsedAtPeer);
    if (isMQ) {
        sourceBuilder.setSourceLayer(Layer.VIRTUAL_MQ);
    } else {
        sourceBuilder.setSourceLayer(Layer.VIRTUAL_GATEWAY);
    }
}
```
sourceBuilder did not set a attribute (**sourceEndpointOwnerServiceLayer**);

org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.RPCTrafficSourceBuilder#toEndpointRelation
- sourceEndpointOwnerServiceName is not null,but sourceEndpointOwnerServiceLayer is null

### How to reproduce

make the condition is true
```
isMQ || config.getUninstrumentedGatewaysConfig()
                                  .isAddressConfiguredAsGateway(networkAddressUsedAtPeer)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please search the change log and compare the latest codes before submitting a bug.

This has been fixed several months ago, https://github.com/apache/skywalking/pull/9300

**Comment by codecodesam** [comment]
> 

thanks;
