### ISSUE TITLE
[Feature] endpoint name grouping by OpenAPI definitions in Node.js agent

### ISSUE THREAD

**Issue by BFergerson** [apache/skywalking#9787]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In https://github.com/apache/skywalking/pull/7130 the Java agent started using OpenAPI definitions for endpoint URLs. I think the Node.js agent should as well.

### Use case

There is no ability to tell the difference between POST/GET/etc endpoint with the same URL when using `Query.searchEndpoint`.

### Related issues

https://github.com/apache/skywalking/issues/7113

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
#7130 did this at the backend, I think nodejs agent doesn't have to redo this again on the agent side? This regex matching is CPU costing.

**Comment by BFergerson** [comment]
You're right, I forgot this was moved from the agent to the backend. Why then do the Node.js tests not have the OpenAPI definitions?

Node.js Entry:
https://github.com/apache/skywalking-nodejs/blob/9ab3d0ec872337bd1cf54f43fe0c29cbcc66ca0f/tests/plugins/express/expected.data.yaml#L80-L101

Java Entry:
https://github.com/apache/skywalking-java/blob/02fc1aee94dd44fdf60e4892ca202809cf2d46c1/test/plugin/scenarios/okhttp-scenario/config/expectedData.yaml#L47-L64

**Comment by wu-sheng** [comment]
That is another issue. Nodejs doesn't follow, as this recommendation is new actually.

Feel free to adjust.

**Comment by BFergerson** [comment]
Should this be done on the agent or backend?

**Comment by wu-sheng** [comment]
The endpoint format should be changed on the agent side to follow the `{METHOD}:{URI}`
