### ISSUE TITLE
[Bug] if i want to access the web by nginx's prefix mode, js file will not with the prefix path

### ISSUE THREAD

**Issue by lukenc** [apache/skywalking#9791]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

if i want to access the web by nginx's prefix mode, js file will not with the prefix path.

nginx config just like this

`    location ^~/trace/ {
          charset UTF-8;
          proxy_pass http://trace-service/;
      }`

then js will be 404.
and it is a white page ,nothing in it
because the prefix /trace.

### What you expected to happen

solution:

in `skywalking-ui/src/router/index.ts`:

`createWebHistory` change to  `createWebHashHistory`

this edit for request `/graphql` :

in `skywalking-ui/src/graphql/fetch.ts`:
```
  const res: AxiosResponse = await axios.post(
    "/trace/graphql",
    { query: param.queryStr, variables: { ...param.conditions } },
    { cancelToken: cancelToken() }
  );
```

will be like this:

```
await axios.post(
   **window.location.pathname+** "/graphql",
    { query: param.queryStr, variables: { ...param.conditions } },
    { cancelToken: cancelToken() }
  );
```

and in `skywalking-ui/src/graphql/index.ts`:

same like this

```
axios
      .post(
        **window.location.pathname+**"/graphql",
        {
          query: query[this.queryData],
          variables: variablesData,
        },
        { cancelToken: cancelToken() }
      )
```

next load js is another matter:

pls add   

`publicPath: "./",`

to `module.exports`

like this 
```
module.exports = {
  outputDir: "dist",
  productionSourceMap: false,
  **publicPath: "./",**
  devServer: {
...........
```

and now it works .

### How to reproduce

1: use nginx match prefix mode.

2: just do like the quick start

it will reproduce

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Generally, we don't recommend to host OAP under other web root.

https://skywalking.apache.org/docs/main/next/en/security/readme/

Take a look at security notice, you should be more cautious when expose UI and OAP.

**Comment by wu-sheng** [comment]
It is relative. The major reason you put skywalking dashboard under a web root, it is to share the port with other applications.

But SkyWalking trusts reported telemetry data, and share the query port with HTTP format data collecting port. This is why I mentioned security notice.

In the last months, dozens of mails between ASF security team and us, this kind of exposing should be taken care of.

SkyWalking dashboard is recommended to run separately, and host on trusted network.
