### ISSUE TITLE
[Bug] Span ended too soon in Neo4J transaction

### ISSUE THREAD

**Issue by guillaume-alvarez** [apache/skywalking#9800]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

When using a Neo4J 4.x java driver, the skywalking agent closes transactions spans just after the call, not waiting for asynchronous result.

### What you expected to happen

It should wait until a result is returned before closing the span.

### How to reproduce

Use the agent on code calling `Session.writeTransaction` API in the Neo4J java client.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please update the issue title.

**Comment by guillaume-alvarez** [comment]
> @guillaume-alvarez Would you open a pull request for the fix?
I'm trying to build the project. Is there any doc with the advised maven commands?

**Comment by wu-sheng** [comment]
For compiling and docker build, https://skywalking.apache.org/docs/skywalking-java/next/en/contribution/compiling/

**Comment by guillaume-alvarez** [comment]
I tried but I get a lot of errors like this one:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project java-agent-network: Compilation failure: Compilation failure: 
[ERROR] /C:/skywalking/bug_neo4j/skywalking-java/apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/command/BaseCommand.java:[21,51] package org.apache.skywalking.apm.network.common.v3 does not exist

**Comment by wu-sheng** [comment]
There is `git submodule` in the repository. If `...v3` doesn't exist, it means you don't CLONE the repo correctly, I am afraid. 

`./mvnw clean package -Pall` is the key, if this is in the git env, it would download submodules automatically. There should be files here

<img width="295" alt="image" src="https://user-images.githubusercontent.com/5441976/196363484-6290cc4b-1481-4efa-ae2d-2601991741ed.png">

**Comment by wallezhang** [comment]
> Ping @wallezhang in case you are still watching this plugin.
> 
> @guillaume-alvarez Would you open a pull request for the fix?

Thanks for reporting the bug, this is indeed a situation that was not considered at that time.
