### ISSUE TITLE
[Feature] Support SpanAttachedEvent Concept

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9803]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This is a new extension and the first one after [Trace Data Protocol v3](https://skywalking.apache.org/docs/main/next/en/protocols/trace-data-protocol-v3/). So I marked this as v3.1, the main document would be updated once this is really implemented.

## Case Scenario
When an RPC is being traced by the in-process language agent, a span would be reported by the client-side agent.
And the rover would be aware of this RPC due to the existing tracing header.
Then, the rover agent collects extra information from the OS level to provide assistance information to diagnose network performance.

## Who is going to implement this
The Rover(ebpf) agent would implement this. This relies on the rover agent having the capability to decode HTTP(at least) header and body on the fly.

## Query Protocol 
```
# Since 9.3.0
# Record is a general and abstract type for collected raw data.
# In the observability, traces and logs have specific and well-defined meanings, and the general records represent other
# collected records. Such as sampled slow SQL statement, HTTP request raw data(request/response header/body)
extend type Query {
    # Query collected records with given metric name and parent entity conditions, and return in the requested order.
    readRecords(condition: RecordCondition!, duration: Duration!): [Record!]!
}
```

A new query protocol is being added, to replace the `readSampledRecords`. This would be a compatible upgrade to support more use cases for sampled records(such as in instance level) and incoming HTTP header/body collecting(through ebpf agent).

### Use case

In ebpf case, we would be able to sample HTTP request/response according to latency threshold, even 100% sampling. And link those records with trace ID/span ID decoded from the sw8(skywalking)/b3(zipkin) header. Then we could have this diagnose workflow, `slow HTTP request` -> `TRACE view` -> `RPC span with attached event`. The event includes the HTTP request/response in step <1>, as well as statistics of network events(ref https://github.com/apache/skywalking-data-collect-protocol/pull/77)

### Related issues

Another doc should be added later after this implementation to introduce what it is the SpanAttachedEvent Concept - Owner @wu-sheng 

We have introduced this concept in the protocol definition, we also should update the docs of protocol and chapters in the concepts part to explain this new concept.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Fine0830** [comment]
If you have finished the development, please let me know. @mrproliu
