### ISSUE TITLE
[Feature] Upgrade BanyanDB storage module

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9805]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Since #9761 merged, we could kick off upgrading the OAP BanyanDB storage module.

The client lib introduces several improvements:

* `exist` endpoints of metadata registry. stream and measure `exist` methods' [return value](https://github.com/apache/skywalking-banyandb-java-client/blob/main/src/main/java/org/apache/skywalking/banyandb/v1/client/metadata/ResourceExist.java#L25
) has `hasGroup`, which will simplify the interaction of creating groups.
* `AbstractQuery`'s [`and` method](https://github.com/apache/skywalking-banyandb-java-client/blob/main/README.md#example-of-and) has the same semantic as before. We could leave it alone.
* `AbstractQuery`'s [`or` method](https://github.com/apache/skywalking-banyandb-java-client/blob/main/README.md#example-of-or) could fit the profile query scenario. 
* `Property`'s `apply`, `get` and `delete` operations support selecting tags. We could disable a UI template by updating a tag instead of a whole property.
* Tag specification supports the `index_only` flag. We could set trace segment's `searchable` tags to `index_only=true`.
* `WriteProcessor`'s `add` method could return a `CompletableFuture<Void>`. We could return it to the OAP's core module.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
As @hanahmily requests, I talked with @wankai123 to take cover this after https://github.com/apache/skywalking/issues/9745 is done.

**Comment by wu-sheng** [comment]
@wankai123 We could do this with https://github.com/apache/skywalking/issues/9183 together, as it is a TODO from 0.1 integration as well.
