### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xiao116134** [apache/skywalking#9818]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

queryTraces
Exception while fetching data (/data) : com.linecorp.armeria.common.ContentTooLargeException: maxContentLength: 10485760, contentLength: 18738897, transferred: 10492044

### What you expected to happen

如何解决

### How to reproduce

![Uploading image.png…]()

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No title, no details. And all contents should be in English.
