### ISSUE TITLE
[Bug] [Test] K8sTagTest can't pass on M1

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#9824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Zulu 1.8 on aarm
```
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not a subtype
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not a subtype
```

Zulu 11 on aarm
```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.skywalking.library.kubernetes.KubernetesServices$MockitoMock$54094179
```

### What you expected to happen

The test could pass on M1

### How to reproduce

Run it on M1. We may consider don't mock `enum` through powermock. As this is the only one test using it, and only it fails.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lujiajing1126** [comment]
Shall we consider deprecating Powermock and completely moving to Mockito

**Comment by wu-sheng** [comment]
We should consider, but we don't have people working on this. And this is the first issue we met.

**Comment by lujiajing1126** [comment]
@xzyJavaX works in our team. I suppose he can make an investigation for the possible migration

**Comment by wu-sheng** [comment]
Thanks, that would be great.

**Comment by kezhenxu94** [comment]
So this looks to be m1-specific as I tried Zulu 1.8, Zulu 11, and Temurin 1.8 Temurin 11 etc., all passed.

One thing to note is that I can see the same logs (not even error logs) on Zulu 1.8 but all tests passed still.

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/15965696/197117650-34295111-c162-4464-8602-1dcbbdcae9fa.png">

**Comment by wu-sheng** [comment]
I guess so too. This test is definitely passed because CI/e2e had verified it.

**Comment by wu-sheng** [comment]
I investigated this issue, and explained the reason here, https://github.com/apache/skywalking/pull/9945
