### ISSUE TITLE
[Bug] JVMMetricsHandler histogramBatch has some error

### ISSUE THREAD

**Issue by shichaoyuan** [apache/skywalking#9837]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

~~`MeterServiceHandler`~~

https://github.com/apache/skywalking/blob/9d3982db74dbe7ba9c028aef674ace13fb74cc18/oap-server/server-fetcher-plugin/kafka-fetcher-plugin/src/main/java/org/apache/skywalking/oap/server/analyzer/agent/kafka/provider/handler/JVMMetricsHandler.java#L59-L70

```
        histogram = metricsCreator.createHistogramMetric(
            "meter_in_latency",
            "The process latency of meter",
            new MetricsTag.Keys("protocol"),
            new MetricsTag.Values("kafka")
        );
        histogramBatch = metricsCreator.createHistogramMetric(
            "meter_in_latency",
            "The process latency of meter",
            new MetricsTag.Keys("protocol"),
            new MetricsTag.Values("kafka")
        );
```

`histogramBatch`  has the same name as `histogram`

### What you expected to happen

the name of `histogramBatch` should be "meter_batch_in_latency" or some other.

### How to reproduce

none

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
What is the issue actually? 

https://github.com/apache/skywalking/blob/9d3982db74dbe7ba9c028aef674ace13fb74cc18/oap-server/server-fetcher-plugin/kafka-fetcher-plugin/src/main/java/org/apache/skywalking/oap/server/analyzer/agent/kafka/provider/handler/MeterServiceHandler.java#L73-L79

From here, they are measure different things, so they are using different metric names.

**Comment by wu-sheng** [comment]
I think those should be removed. I took a look at `JVMMetricReportServiceHandler`. There is no self-obs metric actually for the JVM receiver.
What proposal are you going to do? Remove these metrics?

**Comment by shichaoyuan** [comment]
I just read this part of code in "kafka-fetcher-plugin", not pay attention to other related code.

As you replied firstly, `histogram` and `histogramBatch` should use different metric names in `JVMMetricsHandler`.

**Comment by shichaoyuan** [comment]
got it, thank you for your detailed explanation.
I think both are ok.

**Comment by wu-sheng** [comment]
This is an easy fix, we prefer you could submit a pull request to fix.
