### ISSUE TITLE
[BanyanDB-UI] Refactor the top level menus

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9845]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The top-level menus should reflect the structure and state of banyandb. I propose the new menus should be:

* Dashboard: A collection of metrics that help diagnose the server.
* Stream: create, read and edit streams. Query data in a stream. (identical to the existing database page)
* Measure: create, read and edit measures. Query data in a measure. (identical to the existing database page)
* Property: Apply, delete and read properties.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Do we have ppl working on this?

**Comment by hanahmily** [comment]
> Do we have ppl working on this?

The guy who worked on GSoC's related issue is glad to contribute to this.

**Comment by WuChuSheng1** [comment]
I will implement it as soon as possible, please assign it to me.I will implement it this week.

**Comment by hanahmily** [comment]
@WuChuSheng1 has completed it.
