### ISSUE TITLE
[BanyanDB-UI] Create, Edit, Delete and Read Measure 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9847]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Do what #9845 asked.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by WuChuSheng1** [comment]
I will implement it as soon as possible, please assign it to me
