### ISSUE TITLE
[Bug] [UI]  lack of icon

### ISSUE THREAD

**Issue by baixjian** [apache/skywalking#9848]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

In general page，trace Tab，when search Status Error，at .trace-detail-wrapper
<img width="754" alt="image" src="https://user-images.githubusercontent.com/109275788/197976004-8d1f1be5-76b1-4e4f-b93c-7e9e09536f3f.png">
 lack clear Icon

### What you expected to happen

-

### How to reproduce

-

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@Fine0830 I think this is a nit. I am not sure whether this is icon missing or we don't need this.

**Comment by Fine0830** [comment]
I cannot reproduce this issue.

**Comment by Fine0830** [comment]
It works well.

<img width="1683" alt="1" src="https://user-images.githubusercontent.com/20871783/197980125-2e009e0d-2927-4be3-abfa-4ed950ac0f90.png">

**Comment by wu-sheng** [comment]
@baixjian I think you may need to check your own env then.

**Comment by baixjian** [comment]
> It works well.
> 
> <img alt="1" width="1683" src="https://user-images.githubusercontent.com/20871783/197980125-2e009e0d-2927-4be3-abfa-4ed950ac0f90.png">
i mean in this line [https://github.com/apache/skywalking-booster-ui/blob/main/src/views/dashboard/related/trace/Detail.vue#L21](url)
should be` <Icon iconName="clear" />` and we miss the clear.svg

**Comment by Fine0830** [comment]
I have removed the un-use icon.
