### ISSUE TITLE
[Feature] Allow per index shard and replicas number overrides.

### ISSUE THREAD

**Issue by toffentoffen** [apache/skywalking#9849]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, when Elasticsearch storage option is used you can specify the number of shard and replicas **all** the indices should use. Each index which backs a concrete metric, (or all metrics), record, ..., has different growing rates. Therefore, we would like to have an option to override shard/replica setting per index. Specially, this feature would be really helpful as since 9.2.0 
a new storage option was introduced https://skywalking.apache.org/docs/main/v9.2.0/en/faq/new-elasticsearch-storage-option-explanation-in-9.2.0/ that magnifies the different growing rate between indices.

### Use case

We would like to have an option to override shard/replica setting per index as each index might have different growing rates.
Specially, this feature would be really helpful as since 9.2.0 
a new storage option was introduced https://skywalking.apache.org/docs/main/v9.2.0/en/faq/new-elasticsearch-storage-option-explanation-in-9.2.0/ that magnifies the different growing rate between indices.

- We need a way to set the default shard numbers and default replicas number using `SW_STORAGE_ES_INDEX_SHARDS_NUMBER` and `SW_STORAGE_ES_INDEX_REPLICAS_NUMBER`.
- We should be able to override the default number of shards or replicas targeting concrete Indices irrespectively of `SW_STORAGE_ES_LOGIC_SHARDING`. Which means if `SW_STORAGE_ES_LOGIC_SHARDING` is false only 4 indices can be overriden. If `SW_STORAGE_ES_LOGIC_SHARDING` is false, ~40 indices can be overriden.
- Instead of having 1 property name per index, we could have 1 new property that contains a JSON to override per index number of shard of replicas. The new property could be `SW_STORAGE_ES_INDICES_SETTINGS` . But any other name is fine as well.
- If overriding property is define, it will be used. If an index does not have an override, the default values will be used.
- About the JSON format I don’t have a strong opinion, whatever is easier I am fine with. However, It could be something like, if `SW_STORAGE_ES_LOGIC_SHARDING` is set to false for instance:
```json
{
  "metrics-all": {
    "shards_number": 4,
    "replicas_number": 2
  },
  "zipkin_span": { // This will override discard the `SW_STORAGE_ES_SUPER_DATASET_INDEX_SHARDS_FACTOR`
    "shards_number": 2,
    "replicas_number": 0
  }
}
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mikechengwei** [comment]
I expect that I can complete this function, so please assign it to me, give me a chance, thanks.

**Comment by wu-sheng** [comment]
@mikechengwei Hi, it is great to see you have interests. But, for this particular one, it is a kernel-level change, and we have assigned this to one of the PMC members @wankai123 to check and decide how to fix it.

**Comment by mikechengwei** [comment]
> @mikechengwei Hi, it is great to see you have interests. But, for this particular one, it is a kernel-level change, and we have assigned this to one of the PMC members @wankai123 to check and decide how to fix it.

Ok.
