### ISSUE TITLE
[Feature] Multithreads enhancement request

### ISSUE THREAD

**Issue by zlr25** [apache/skywalking#9850]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

There are a number of ways to implement multithread programming in java. I did a simple test: using new Thread() inside a controller to generate multiple threads, then query and write database in each thread. When I call the test controller, SW can only capture each pointcut like mysql driver, controller call, but cannot line them up like an entire trace. 

Therefore, I believe, currently, the tracing is not working at multithread scenario. This feature is a significant one since multithread is common, and support the tracing in new threads, synchronized methods as well as reused threads created by thread pool during the biz logic are needed.

### Use case

new Thread();
ThreadPoolExecutor.submit();
CompletableFuture.doSomething();

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is wrong asking from a tech perspective. This is an open-source community, not a commercial service.
We have provided full documents to explain how the plugin works in x-thread cases, what are x-thread APIs in agent kernel. You didn't read it, and your questions don't make any sense.
