### ISSUE TITLE
[Bug]  trace data lose

### ISSUE THREAD

**Issue by XTUxiongda** [apache/skywalking#9862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

In the morning，i Received five warning messages。so, i use these traceid to query trace in the skywalking UI.
At the very beginning, I found one, but after a while I searched again and couldn't find it.
So I went directly to elasticsearch to query the sw_segment-20221028 index, and found that only one of the traceid data was stored in it.

my skywalking version is 8.6.0
agent.sample_n_per_3_secs use default -1

### What you expected to happen

I hope that the full amount of collected data can be found according to traceId

### How to reproduce

definitely appear in version 8.6.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I don't know why this should be reported to the community. This is not a tech issue, how you operate the project and run it in your private and prod env, is your own responsibility.
How we could know what happened at an env we never touched?

**Comment by wu-sheng** [comment]
And you submitted this repeated in discussion(https://github.com/apache/skywalking/discussions/9858), QQ group, and even private ping. 
This is very annoying. Blocking at all places.
