### ISSUE TITLE
[Feature] [BanyanDB storage] Integrate new TopN and native double/float fields

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking#9864]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Since TopN calculus is supported by BanyanDB from 0.2, we can make use of this mechanism in OAP core.

And we have to add double/float support in BanyanDB

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
Double type supporting relates to #8940
