### ISSUE TITLE
[Bug] [PHP]Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hyper-self** [apache/skywalking#9866]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

PHP 7.3.33 (cli) (built: Nov 30 2021 08:42:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies

/tmp/pear/download/skywalking_agent-0.1.0 # make
PHP_CONFIG=php-config cargo build --release
make: *** [Makefile:193: modules/skywalking_agent.so] Segmentation fault (core dumped)

### What you expected to happen

core dumped

### How to reproduce

dont konw

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please make your title of issue complete.

**Comment by jmjoy** [comment]
Which OS and release version do you use?

**Comment by hyper-self** [comment]
php:7.3-fpm-alpine

**Comment by hyper-self** [comment]
> Which OS and release version do you use?

php:7.3-fpm-alpine

**Comment by hyper-self** [comment]
docker image 
php:7.3-fpm-alpine

**Comment by jmjoy** [comment]
Please use higher version alpine for building Rust, because there is a known bug for musl.

https://github.com/rust-lang/rust/issues/76021

**Comment by hyper-self** [comment]
My current Linux Alpine,Which version can succeed？

#cat /etc/alpine-release
3.15.1
#cat /etc/apk/repositories
https://mirrors.aliyun.com/alpine/edge/main
https://mirrors.aliyun.com/alpine/edge/community
https://mirrors.aliyun.com/alpine/edge/testing

#apk info musl
musl-1.2.3-r1 description:
the musl c library (libc) implementation

musl-1.2.3-r1 webpage:
https://musl.libc.org/

musl-1.2.3-r1 installed size:
608 KiB

# php -v
PHP 7.3.33 (cli) (built: Mar 18 2022 04:05:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies

**Comment by jmjoy** [comment]
What's your Dockerfile, or build steps?

**Comment by hyper-self** [comment]
FROM php:7.3-fpm-alpine

RUN set -ex \
	# 切换源
	&& echo "https://mirrors.aliyun.com/alpine/edge/main" > /etc/apk/repositories \
	&& echo "https://mirrors.aliyun.com/alpine/edge/community" >> /etc/apk/repositories \
	&& echo "https://mirrors.aliyun.com/alpine/edge/testing" >> /etc/apk/repositories \
	# install composer
    && wget https://mirrors.aliyun.com/composer/composer.phar \
    && chmod u+x composer.phar \
    && mv composer.phar /usr/local/bin/composer \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer \
    # php
    && apk add --update --no-cache --virtual .build-deps1 g++ autoconf make \
    && apk add --update --no-cache --virtual .build-deps2 git gearman-dev libevent-dev openssl-dev jpeg-dev freetype-dev libpng-dev libzip-dev libxml2-dev \
    && docker-php-ext-install pcntl posix mysqli pdo_mysql soap sockets \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/freetype2 --with-jpeg-dir=/usr/include --with-png-dir=/usr/include \
    && docker-php-ext-install -j$(nproc) gd \
	&& pecl install redis zip gearman apcu mongodb event \
	&& docker-php-ext-enable redis zip gearman apcu mongodb event \
    && apk del .build-deps1

CMD ["php-fpm"]

**Comment by hyper-self** [comment]
FROM php:7.3-fpm-alpine

RUN set -ex \
    && echo "https://mirrors.aliyun.com/alpine/edge/main" > /etc/apk/repositories \
    && echo "https://mirrors.aliyun.com/alpine/edge/community" >> /etc/apk/repositories \
    && echo "https://mirrors.aliyun.com/alpine/edge/testing" >> /etc/apk/repositories \
    && apk add --update --no-cache --virtual .build-deps1 g++ autoconf make cargo clang protobuf \
    && apk add --update --no-cache --virtual .build-deps2 git libevent-dev openssl-dev jpeg-dev freetype-dev libpng-dev libzip-dev libwebp-dev libmcrypt-dev libxml2-dev \
    && docker-php-ext-install pcntl posix pdo_mysql soap sockets \
    && docker-php-ext-configure gd --with-webp=/usr/include/webp --with-jpeg=/usr/include --with-freetype=/usr/include/freetype2/ \
    && docker-php-ext-install -j$(nproc) gd \
	&& pecl install redis zip apcu mcrypt event skywalking_agent \
	&& docker-php-ext-enable redis zip apcu mcrypt event skywalking_agent \
	&& apk del .build-deps1

CMD ["php-fpm"]

**Comment by jmjoy** [comment]
I think the coredump was caused by `make`, not `rust`.

**Comment by hyper-self** [comment]
Errors have been mentioned above：

/tmp/pear/download/skywalking_agent-0.1.0 # make
PHP_CONFIG=php-config cargo build --release
make: *** [Makefile:193: modules/skywalking_agent.so] Segmentation fault (core dumped)

Successed:
alpine:3.16.2
 # php -v
PHP 7.4.32 (cli) (built: Oct  7 2022 00:41:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
# apk info musl
musl-1.2.3-r0 description:
the musl c library (libc) implementation

musl-1.2.3-r0 webpage:
https://musl.libc.org/

musl-1.2.3-r0 installed size:
608 KiB

**Comment by hyper-self** [comment]
I want to succeed in this version : php:7.3-fpm-alpine

**Comment by hyper-self** [comment]
![image](https://user-images.githubusercontent.com/38802072/200110314-9f5ff3d4-bc9b-4902-94a1-6134b947f29c.png)
