### ISSUE TITLE
Metadata registration bugs

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9902]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

There are some tiny bugs related to the metadata registration:

  * Lack of checking the group existed when applying a property.
  * The update time is absent when creating schemas.
  * Some required fields lack validations when creating schemas.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HHoflittlefish777** [comment]
please assign to me

**Comment by hanahmily** [comment]
There are some check rules for `schema.proto`

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L39

* `name` is required
* `tags` contains one item at least

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L45

`name` and `type` are required.

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L55

All fields are required except for `updated_at `

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L67

There are one item at least

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L89

All fields are required.

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L101

All fields are required expect for `interval`, `fields` and `updated_at`.

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L118

`metadata`, `source_measure ` and `field_name` are required.

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L144

All fields are required except for `analyzer` and `updated_at`.

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L184

All fields are required.

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/database/v1/schema.proto#L194

All fields are required except for `updated_at`.

**Comment by hanahmily** [comment]
`property.proto` checking rules:

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/property/v1/property.proto#L30

All fields are required.

## https://github.com/apache/skywalking-banyandb/blob/main/api/proto/banyandb/property/v1/property.proto#L38

All fields are required except for `updated_at`.
