### ISSUE TITLE
[Bug] dubbo 3.1.0 skywalking 8.9.1 agent 8.12.0 tid no transmit

### ISSUE THREAD

**Issue by JavaLionLi** [apache/skywalking#9905]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

dubbo 3.1.0 skywalking 8.9.1 agent 8.12.0 tid no transmit

A service
![image](https://user-images.githubusercontent.com/31852897/199906473-0d63cfb7-4388-44d5-adf1-4f82c20c57d6.png)
B service
![image](https://user-images.githubusercontent.com/31852897/199906559-7cd43791-1e2a-4e10-9e70-fa42f53862f9.png)

### What you expected to happen

Context transfer tid

### How to reproduce

dubbo 3.1.0 skywalking 8.9.1 agent 8.12.0

`
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
            <version>8.12.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-trace</artifactId>
            <version>8.12.0</version>
        </dependency>
`
`
    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
                <pattern>[%tid] ${console.log.pattern}</pattern>
            </layout>
            <charset>utf-8</charset>
        </encoder>
    </appender>
`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Ask Dubbo community, maybe they change thread models.

**Comment by JavaLionLi** [comment]
> Ask Dubbo community, maybe they change thread models.

![image](https://user-images.githubusercontent.com/31852897/199910025-1f3195e4-2022-4b3e-8f9a-d9ecf80fafa4.png)
dubbo貌似把这个方法淘汰了

**Comment by JavaLionLi** [comment]
> > Ask Dubbo community, maybe they change thread models.
> 
> ![image](https://user-images.githubusercontent.com/31852897/199910025-1f3195e4-2022-4b3e-8f9a-d9ecf80fafa4.png) dubbo貌似把这个方法淘汰了 3.1.X中应该不能这么用

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-java/tree/main/test/plugin/scenarios/dubbo-3.x-scenario

Dubbo 3 case exists, you could check. And toolkit has logic relationship with Dubbo. You have yo make sure the codes run in the same thread of Dubbo instrumented claases(filters)

What you post, I can not tell it is relative or not. You seem only pushing all things to us, this is not how we work.

**Comment by JavaLionLi** [comment]
> https://github.com/apache/skywalking-java/tree/main/test/plugin/scenarios/dubbo-3.x-scenario
> 
> Dubbo 3 case exists, you could check. And toolkit has logic relationship with Dubbo. You have yo make sure the codes run in the same thread of Dubbo instrumented claases(filters)
> 
> What you post, I can not tell it is relative or not. You seem only pushing all things to us, this is not how we work.

No asynchronous, all synchronous

**Comment by wu-sheng** [comment]
If you just try to read source codes a little, you would know, NA means you even don't install agent. Or agent kernel is not working.

https://github.com/apache/skywalking-java/blob/main/apm-application-toolkit/apm-toolkit-logback-1.x/src/main/java/org/apache/skywalking/apm/toolkit/log/logback/v1/x/LogbackPatternConverter.java#L34

**Comment by JavaLionLi** [comment]
> 

......... If the agent is not installed, where does the above log come from

**Comment by JavaLionLi** [comment]
> If you just try to read source codes a little, you would know, NA means you even don't install agent. Or agent kernel is not working.
> 
> https://github.com/apache/skywalking-java/blob/main/apm-application-toolkit/apm-toolkit-logback-1.x/src/main/java/org/apache/skywalking/apm/toolkit/log/logback/v1/x/LogbackPatternConverter.java#L34

......... If the agent is not installed, where does the above log come from

**Comment by JavaLionLi** [comment]
> If you just try to read source codes a little, you would know, NA means you even don't install agent. Or agent kernel is not working.
> 
> https://github.com/apache/skywalking-java/blob/main/apm-application-toolkit/apm-toolkit-logback-1.x/src/main/java/org/apache/skywalking/apm/toolkit/log/logback/v1/x/LogbackPatternConverter.java#L34

It has been explained at the top that the logback plug-in has been imported
If you keep avoiding problems, then I don't want to say

**Comment by JavaLionLi** [comment]
> > If you just try to read source codes a little, you would know, NA means you even don't install agent. Or agent kernel is not working.
> > https://github.com/apache/skywalking-java/blob/main/apm-application-toolkit/apm-toolkit-logback-1.x/src/main/java/org/apache/skywalking/apm/toolkit/log/logback/v1/x/LogbackPatternConverter.java#L34
> 
> ......... If the agent is not installed, where does the above log come from

As mentioned above, service A has tid, service B does not, and they all import the same dependency

**Comment by wu-sheng** [comment]
Only the toolkit without agent could output `"TID: N/A";`, as the codes show.

> If you keep avoiding problems, then I don't want to say

I don't know what you mean. 
From an open-source perspective, we don't have any obligation to support. That is what Apache 2.0 license says. 
We don't owe you anything.

**Comment by JavaLionLi** [comment]
> Only the toolkit without agent could output `"TID: N/A";`, as the codes show.
> 
> > If you keep avoiding problems, then I don't want to say
> 
> I don't know what you mean. From an open-source perspective, we don't have any obligation to support. That is what Apache 2.0 license says. We don't owe you anything.


I think the tid of service A is not transferred to service B, which is just a problem.

Similarly, B service calls A service, B has tid, A does not

Can we prove that both A and B have agents

I didn't say how you were. I just gave feedback. If you think it's OK, then it's OK

**Comment by wu-sheng** [comment]
I don't think there is the case. Even the trace context(including your trace ID) is not propagated into service B, you would still have trace ID, just a new one.

I had provided you with a very clear thing. There is no more I can say.

> Can we prove that both A and B have agents

https://github.com/apache/skywalking-java/blob/main/apm-application-toolkit/apm-toolkit-logback-1.x/src/main/java/org/apache/skywalking/apm/toolkit/log/logback/v1/x/LogbackPatternConverter.java#L34 is for proving only no-agent not installed.

**Comment by JavaLionLi** [comment]
> 

Another point is not clear. There is no problem with the link on the UI. 
Only 'logback' cannot be output
I will continue to investigate

**Comment by JavaLionLi** [comment]
> I don't think there is the case. Even the trace context(including your trace ID) is not propagated into service B, you would still have trace ID, just a new one.
> 
> I had provided you with a very clear thing. There is no more I can say.
> 
> > Can we prove that both A and B have agents
> 
> https://github.com/apache/skywalking-java/blob/main/apm-application-toolkit/apm-toolkit-logback-1.x/src/main/java/org/apache/skywalking/apm/toolkit/log/logback/v1/x/LogbackPatternConverter.java#L34 is for proving only no-agent not installed.

Another point is not clear. There is no problem with the link on the UI.
Only 'logback' cannot be output
I will continue to investigate
