### ISSUE TITLE
[Feature] Support query trace by group

### ISSUE THREAD

**Issue by xcbeyond** [apache/skywalking#9907]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, trace can be queried only through these conditions in [TraceQueryCondition](https://github.com/apache/skywalking/blob/master/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/input/TraceQueryCondition.java). In more cases, we need to query by group. It is recommended that you support the query

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
What you need is not what a community needs. This is not how open source works
