### ISSUE TITLE
[Feature]  add plugin for support apache eventMesh

### ISSUE THREAD

**Issue by heihei180** [apache/skywalking#9910]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

support Apache EventMesh.

### Use case

enhance client to trace.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No update in 15 days, close for now. If you want to continue working on this, please let use know.
