### ISSUE TITLE
[test]

### ISSUE THREAD

**Issue by LookSin** [apache/skywalking#9920]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

No executable test cases found when running on IDEA

### What you expected to happen

can you tell me where is the test case

### How to reproduce

Run the test source code to see if there are any test cases

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Don't use upstream to test. This is a spam.
