### ISSUE TITLE
[Feature] DMSQL client plugin

### ISSUE THREAD

**Issue by Noodate** [apache/skywalking#9926]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

support  DMSQL  database.

### Use case

enhance client to trace.

### Related issues

No response

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
First of all, you should make sure the title is correct and complete when you submit anything to a community.

DMSQL is a commercial product of IBM. It is not licensed for us to do so.

**Comment by Noodate** [comment]
Sorry, DMSQL is a domestic database，Damon database management system is a high-performance database management system with completely independent intellectual property rights launched by Damon, which is called DM for short，In recent years, domestic databases have been used more and more widely, which is a trend

**Comment by wu-sheng** [comment]
It is also a commercial product.
Nothing different from license perspective.
There is nothing about a trend in this discussion.

**Comment by Noodate** [comment]
Okay! Thank you for your communication which has benefited me a lot.
