### ISSUE TITLE
[Feature]  add plugin for support Apache Struts 1

### ISSUE THREAD

**Issue by Noodate** [apache/skywalking#9931]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

support Apache Struts 1

### Use case

enhance client to trace.

### Related issues

No response

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I don't believe struts one is still active. Unless you are going to contribute, feel free to do.
We don't encourage committer team to spend time on this.

**Comment by Noodate** [comment]
Hahaha, Struts 1 is rarely used, but it still exists. Now that I have made it, I am still willing to make a little contribution to the open source community

**Comment by wu-sheng** [comment]
I would recommend you to open the project on your own name, rather than to upstream.
Because we have to ask plugin test to cover popular versions, but there is no version for it to be active any more.

**Comment by Noodate** [comment]
OK，Thank you
