### ISSUE TITLE
[Bug] The reportError(Throwable throwable) method and run() method in GRPCChannelManager cannot be re linked due to multithreading

### ISSUE THREAD

**Issue by Zhannan3** [apache/skywalking#9950]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

If the run() methods Code in

notify(GRPCChannelStatus.CONNECTED);
reconnectCount = 0;
reconnect = false;

And reportError (Throwable Throwable) methods

if (isNetworkError(throwable)) {
  reconnect = true;
  notify(GRPCChannelStatus.DISCONNECT);
}

The code is run simultaneously, but in the order

notify(GRPCChannelStatus.CONNECTED);
reconnectCount = 0;
reconnect = true;
notify(GRPCChannelStatus.DISCONNECT);
reconnect = false;

Will appear
GRPCChannelStatus equals DISCONNECT
reconnect = false;
As a result, run() in GRPCChannelManager cannot establish a link again,Agent will no longer report information

### What you expected to happen

GRPCChannelStatus equals DISCONNECT
reconnect = false;
As a result, run() in GRPCChannelManager cannot establish a link again,Agent will no longer report information

### How to reproduce

run() method and reportError (Throwable Throwable) method run simultaneously

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Which version are you talking about? I am feeling this had been fixed by https://github.com/apache/skywalking-java/pull/290 months ago.

```
notify(GRPCChannelStatus.CONNECTED);
reconnectCount = 0;
reconnect = true;
```

This is not going to be the execution order anymore.

**Comment by Zhannan3** [comment]
> 你说的是哪个版本？我觉得这已经被[apache/skywalking-java#290](https://github.com/apache/skywalking-java/pull/290)个月前修复了。
> 
> ```
> notify(GRPCChannelStatus.CONNECTED);
> reconnectCount = 0;
> reconnect = true;
> ```
> 
> 这将不再是执行顺序。

V9.2.0

**Comment by wu-sheng** [comment]
You are asking about the agent, v9.2.0 is only a backend version.

**Comment by Zhannan3** [comment]
> 您问的是代理，v9.2.0 只是一个后端版本。

v8.13.0

**Comment by wu-sheng** [comment]
I replied. The workflow mentioned is impossible for today's codes from my check. Please be clear about what you are asking.

**Comment by Zhannan3** [comment]
> I replied. The workflow mentioned is impossible for today's codes from my check. Please be clear about what you are asking.

We use the Java agent version V8.13.0. When the Java agent and skywalking are not connected for a long time, and the probe attempts to link skywalking for many times without success, the probability of not trying to link skywalking again does appear. I think the answer in[ Apache/skywalking java # 290](https://github.com/apache/skywalking-java/pull/290) can solve our problem

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-java/pull/290 is being used since 8.12, and 8.13 also includes the codes.
I don't know why you mentioned 8.13.0 is not working.

**Comment by Zhannan3** [comment]
> [apache/skywalking-java#290](https://github.com/apache/skywalking-java/pull/290) is being used since 8.12, and 8.13 also includes the codes. I don't know why you mentioned 8.13.0 is not working.

sorry, I made a mistake,Our production line really uses 8.11.0, and the test uses 8.13.0.
