### ISSUE TITLE
[Testing] Fix integration test's leaked goroutines

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9957]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This is a sub-task of https://github.com/apache/skywalking/issues/9454 to fix leaked goroutines in the `test/integration` package. There are three sub-packages need to add goroutines leak testing: `query`, `cold` and `other`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@hanahmily Why is this tagged in 0.4.0? I think 0.3.0 is not tagged, but the PR has been merged.
