### ISSUE TITLE
[Bug] Satellite dose not support dotnet CLRMetricReportService

### ISSUE THREAD

**Issue by inversionhourglass** [apache/skywalking#9960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Satellite (apache/skywalking-satellite)

### What happened

Satellite does not support the CLRMetric defined by SkyAPM-dotnet. The error message is as follows:
```
Report CLR Stats error. Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="unknown service CLRMetricReportService", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1668481297.736307016","description":"Error received from peer ipv4:x.x.x.x:11800","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":953,"grpc_message":"unknown service CLRMetricReportService","grpc_status":12}")
 at SkyApm.Transport.Grpc.V8.CLRStatsReporter.ReportAsync(CLRStatsRequest statsRequest, CancellationToken cancellationToken)
```

Satellite version: 1.0.1
SkyAPM-dotnet version: 1.3.0

### What you expected to happen

Support CLRMetric.

### How to reproduce

Use dotnet agent to report data.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
.net agent is a 3rd party project, we rely on their community to maintain their protocols and features. 
SkyWalking is just helping on hosting them.

**Comment by wu-sheng** [comment]
Friendly ping @liuhaoyang
