### ISSUE TITLE
 log data is too large, the trace log can't recorded.

### ISSUE THREAD

**Issue by FTDC** [apache/skywalking#9961]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

when the log data is too large,  the trace log can't  recorded.   
because the elasticsearch keywork type max lenth is  UTF8 encoding is longer than the max length 32766
sugguest  keep a record and ignore any unnecessary information

After setting ignore_above, data beyond the specified length is not indexed and cannot be returned through term exact matching retrieval
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/ignore-above.html#ignore-above%3E

### What you expected to happen

trace log insert elastic error

"caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Document contains at least one immense term in field=\"content\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: '[49, 53, 55, 56, 52, 54, 51, 51, 51, 118, 99, 111, 109, 115, 97, 100, 112, 97, 110, 100, 97, 117, 115, 115, 97, 102, 101, 114, 118, 112]...'"
        }

### How to reproduce

GRPC-LOG 

record  more than  32766 [whose UTF8 encoding is longer than the max length 32766]  length word

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FTDC** [comment]
lose trace logs

**Comment by wu-sheng** [comment]
Why do you have so large log in prod env? We never faced this as this seems nonsense.

**Comment by wu-sheng** [comment]
The trace and log are not stored as a keyword type. I am not sure about your description. 
The raw data of trace and log(backend and browser) are only considered as `byte[]` in the final storage, which should not be length sensitive.

**Comment by wu-sheng** [comment]
> After setting ignore_above, data beyond the specified length is not indexed and cannot be returned through term exact matching retrieval
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/ignore-above.html#ignore-above%3E

5.4 is too old, and we never

**Comment by wu-sheng** [comment]
The only thing I can get is `AbstractLogRecord#content`, which seems using a match query. @FTDC 

@kezhenxu94 Should we consider a length limitation?

**Comment by kezhenxu94** [comment]
> The only thing I can get is `AbstractLogRecord#content`, which seems using a match query. @FTDC
> 
> @kezhenxu94 Should we consider a length limitation?

Do you mean limiting the length of 👇 this field? 

https://github.com/apache/skywalking/blob/7c8867bed7110c7eac5379dca5119ae6faf68857/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/analysis/manual/log/AbstractLogRecord.java#L86-L88

**Comment by wu-sheng** [comment]
I am planning to add a mechanism to make this field as text, rather than a keyword.
I think that could fix the issue

**Comment by FTDC** [comment]
yes ,   You guys were quick to respond
