### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zhaozuowu** [apache/skywalking#9962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

When I successfully installed the SkyWalking PHP Agent extension and restarted the php process, an error was reported：
![image](https://user-images.githubusercontent.com/5884470/202070808-cd479267-84b1-4499-9e06-e76935b265ec.png)

### What you expected to happen

When I successfully installed the SkyWalking PHP Agent extension and restarted the php process, an error was reported：
![image](https://user-images.githubusercontent.com/5884470/202070808-cd479267-84b1-4499-9e06-e76935b265ec.png)

### How to reproduce

When I successfully installed the SkyWalking PHP Agent extension and restarted the php process, an error was reported：
![image](https://user-images.githubusercontent.com/5884470/202070808-cd479267-84b1-4499-9e06-e76935b265ec.png)

### Anything else

When I successfully installed the SkyWalking PHP Agent extension and restarted the php process, an error was reported：
![image](https://user-images.githubusercontent.com/5884470/202070808-cd479267-84b1-4499-9e06-e76935b265ec.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
No title.
