### ISSUE TITLE
[Bug]  skyWalking PHP agent report error

### ISSUE THREAD

**Issue by zhaozuowu** [apache/skywalking#9963]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

PHP (apache/skywalking-php)

### What happened

When I successfully installed the SkyWalking PHP Agent extension and restarted the php process, an error was reported：
![image](https://user-images.githubusercontent.com/5884470/202070808-cd479267-84b1-4499-9e06-e76935b265ec.png)

### What you expected to happen

I expected it report success

### How to reproduce

When I successfully installed the SkyWalking PHP Agent extension and restarted the php process, an error was reported：
![image](https://user-images.githubusercontent.com/5884470/202070808-cd479267-84b1-4499-9e06-e76935b265ec.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhaozuowu** [comment]
> Dose you use `php-fpm`? If so, please run and show the result of `ps -ef | grep php-fpm`.
Yes, I use php-fpm.


> ps -ef | grep php-fpm

![image](https://user-images.githubusercontent.com/5884470/202401588-28188321-f48c-4dfd-baec-3dc5c1faba7b.png)

**Comment by jmjoy** [comment]
Seen that the grpc worker process not exists, please check the log if there's some ERROR log.

**Comment by zhaozuowu** [comment]
> 看到grpc worker进程不存在，请查看日志是否有ERROR日志。

Why grpc worker not exists

> Seen that the grpc worker process not exists, please check the log if there's some ERROR log.

**Comment by zhaozuowu** [comment]
> Seen that the grpc worker process not exists, please check the log if there's some ERROR log.

Why grpc worker not exists? Which Error log I can check?

**Comment by zhaozuowu** [comment]
> Seen that the grpc worker process not exists, please check the log if there's some ERROR log.

Why grpc worker process not exists? Which Error log I can check?

**Comment by thecalmund** [comment]
Why did you closed this issue? I also have the same problem.

**Comment by jmjoy** [comment]
> Why grpc worker process not exists? Which Error log I can check?

Configuration of `skywalking_agent.log_file`.

Ref: https://skywalking.apache.org/docs/skywalking-php/next/en/setup/service-agent/php-agent/readme/#configure-phpini

**Comment by zhaozuowu** [comment]
> Ref: https://skywalking.apache.org/docs/skywalking-php/next/en/setup/service-agent/php-agent/readme/#configure-phpini




> > Why grpc worker process not exists? Which Error log I can check?
> 
> Configuration of `skywalking_agent.log_file`.
> 
> Ref: https://skywalking.apache.org/docs/skywalking-php/next/en/setup/service-agent/php-agent/readme/#configure-phpini


When I successfully installed the SkyWalking PHP Agent extension and restarted the php process, an error was reported：

![image](https://user-images.githubusercontent.com/5884470/203085006-3b36301a-9fc6-4329-af38-dffef04b1fb5.png)

**Comment by zhaozuowu** [comment]
> > Ref: https://skywalking.apache.org/docs/skywalking-php/next/en/setup/service-agent/php-agent/readme/#configure-phpini
> 
> > > Why grpc worker process not exists? Which Error log I can check?
> > 
> > 
> > Configuration of `skywalking_agent.log_file`.
> > Ref: https://skywalking.apache.org/docs/skywalking-php/next/en/setup/service-agent/php-agent/readme/#configure-phpini
> 
> When I successfully installed the SkyWalking PHP Agent extension and restarted the php process, an error was reported：
> 
> ![image](https://user-images.githubusercontent.com/5884470/203085006-3b36301a-9fc6-4329-af38-dffef04b1fb5.png)



> > Why grpc worker process not exists? Which Error log I can check?
> 
> Configuration of `skywalking_agent.log_file`.
> 
> Ref: https://skywalking.apache.org/docs/skywalking-php/next/en/setup/service-agent/php-agent/readme/#configure-phpini

The Error log Is:
![image](https://user-images.githubusercontent.com/5884470/203085331-f0398a81-4f32-4f94-8222-1dd8cceaf23d.png)
