### ISSUE TITLE
trace search by tag not work [Bug] [Skywalking UI ] [9.2.0]

### ISSUE THREAD

**Issue by XiamenGeek** [apache/skywalking#9974]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

I tried to search trace by tag (key and value), but it doesn't work. There are many values in the drop-down list, but the value I want to search is not in the list.   As a result, the tag search cannot to be autocompleted, then cannot to be searched.  Actually, this value is  tagged in the existed trace  and pushed to Skywalking OAP in the time scope.
When I have only limited serveral trace records when skywalking was just installed in the beginning , it's ok to search by tag(key and value). 

### What you expected to happen

Normaly, when I search trace by tag,  traces should be searched by the existed tag(key and value). 
The existed value  should be appeared in the drop-down list, and can be autocompleted , and then to be searched. 

### How to reproduce

Skywalking agent push trace records which tagged by key/value to skywalking OAP, and the trace records should be big engough, may be at least 10K trace records. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@Fine0830 Auto-complete should be an assistant only. Users should be able to input key=value even not in the auto-complete candidates.

**Comment by XiamenGeek** [comment]
> @Fine0830 Auto-complete should be an assistant only. Users should be able to input key=value even not in the auto-complete candidates.

Input key=value, it the value is in the drop-down list, it can be searched, like this:
![image](https://user-images.githubusercontent.com/10876500/202207262-8366ebc8-d5f9-450d-8bc3-fd76250f76c8.png)
Input key=value, it the value is not in the drop-down list, it can not be searched, like this:
![image](https://user-images.githubusercontent.com/10876500/202207529-e1d3d399-673b-431a-aafb-e68826144397.png)
