### ISSUE TITLE
[Bug] SWCK 0.7.0 start failed with error "no matches for kind Ingress in version networking.k8s.io/v1" before k8s v1.18.3

### ISSUE THREAD

**Issue by Eason620** [apache/skywalking#9987]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

SWCK (apache/skywalking-swck)

### What happened

env:
k8s version: 1.18.3
SWCK version: 0.7.0

Question:
When we deploy SWCK 0.7.0 in k8s v1.18.3, the swck-controller-manager pod start failed and crash with the error "no matches for kind Ingress in version networking.k8s.io/v1". 

SWCK pod log:
1.668760847966308e+09	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "Ingress.networking.k8s.io", "error": "no matches for kind \"Ingress\" in version \"networking.k8s.io/v1\""}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/Users/caoye/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:139
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/Users/caoye/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:233
k8s.io/apimachinery/pkg/util/wait.poll
	/Users/caoye/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:580
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
	/Users/caoye/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:545
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
	/Users/caoye/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:132

### What you expected to happen

NO

### How to reproduce

NO

### Anything else

NO

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
K8s 1.18 is EOL 2021-05-12, ref https://kubernetes.io/releases/patch-releases/

There is no point to support that.
