### ISSUE TITLE
[BanyanDBJavaClient] Support "version" field 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9991]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This is based upon #9990 

The java client should support this new field.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mufiye** [comment]
I'm interested in this task. But is this task should wait for issue #9990 to be done?

**Comment by hanahmily** [comment]
> I'm interested in this task. But is this task should wait for issue #9990 to be done?

That's right. This is a follow-up task of #9990.
