### ISSUE TITLE
[BanyanDB][TestCase] Stimulate the OAP flushing

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#9994]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This case tends to stimulate the way of the OAP flushing process:

The testing data contain three sets that belong to the same timestamp(or the time bucket of the OAP). Each one indicates a flushing operation and has the same entities with different values. 

* Load three sets. 
  * Testing all cases after each is loaded, which could verify the Memtable.
* Load the same three sets, then restart the database after each loading.
  * Verify cases after each restart. They will confirm SSTables and the compaction results.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mikechengwei** [comment]
Can I try to finish this function?
